### ISSUE TITLE
Express TypeScript missing 'encode' option in CookieOptions

### ISSUE THREAD

**Issue by AlexLeung** [DefinitelyTyped/DefinitelyTyped#10018]
- [ ] I tried using the latest `express-server-static-core/index.d.ts` file in this repo and had problems.

When trying to write some express code to send a signed cookie, I wrote this code

```
res.cookie("name", "val", {
    encode
})
```

but the encode option was not suggested, and when I took a look at `express-server-static-core/index.d.ts` on line 102, I found that the option was missing altogether.

This is supposed to be an option, see http://expressjs.com/en/api.html#res.cookie

**Comment by vvakame** [comment]
do you use `@types` ?

**Comment by AlexLeung** [comment]
I use [typings](https://github.com/typings/typings). Would it make a difference?

**Comment by vvakame** [comment]
cc/ @blakeembrey

**Comment by blakeembrey** [comment]
Did you install the definition? I see it in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/express-serve-static-core/express-serve-static-core.d.ts#L715-L717.

**Comment by AlexLeung** [comment]
The title of this issue is 
**Express TypeScript missing 'encode' option in CookieOptions**, 
not 
**Express Typescript missing CookieOptions from res.cookie**.

Although there is a `res.cookie` method which takes a `CookieOptions` object, the `CookieOptions` interface is missing the `encode` property. See here
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/express-serve-static-core/express-serve-static-core.d.ts#L117-125
and notice how this is different from the options specified here
http://expressjs.com/en/api.html#res.cookie

**Comment by blakeembrey** [comment]
@AlexLeung I understand. You are welcome to make a PR, though I am not a maintainer here. I was pinged because @vvakame thought it might be a Typings issue and that's what I responded to - I didn't have time to debug and it wasn't clear that was the issue to me. It's possible he glanced over it the same as me.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
