### ISSUE TITLE
Error: Cannot find namespace `__React` when using fixed-data-table/fixed-data-table.d.ts

### ISSUE THREAD

**Issue by jpierson** [DefinitelyTyped/DefinitelyTyped#10010]
- [x] I tried using the latest `fixed-data-table/fixed-data-table.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `fixed-data-table/fixed-data-table.d.ts`.
  - The authors of that type definition are @pepaar and @stephenjelfs

Using this type definition I'm seeing the following error when compiling.

> c:\myproject\typings\globals\fixed-data-table\index.d.ts
> (62,41): error TS2503: Cannot find namespace '__React'.

It appears that it is relying on a globally defined variable called `__React`. Perhaps this was the behavior of an earlier version of React? I'm using the React type definition from here `registry:npm/react#15.0.1+20160601175240`.

**Comment by jpierson** [comment]
I should also probably mention that I'm using [typings](https://github.com/typings/typings) version _1.3.1_.

**Comment by lxiange** [comment]
Hi, @jpierson have you solved this problem?
I met the same failure last week, and I found a solution:
`typings install react --save --global --source dt`.
Notice the `global` and `source dt` tag, do not install it as a module.
And then you should `import * as React from 'react'` in your `.ts/.tsx` file.
It may helps you.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
