### ISSUE TITLE
lodash - IArguments is not assignable to parameter of type Dictionary<{}>

### ISSUE THREAD

**Issue by viveleroi** [DefinitelyTyped/DefinitelyTyped#10015]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `lodash/lodash.d.ts`.
  - The authors of that type definition are cc/ @bczengel @chrootsu @stepancar

When passing `arguments` to a lodash method that accepts array-like structures, typescript complains:

```
error TS2345: Argument of type 'IArguments' is not assignable to parameter of type 'Dictionary<{}>'.
Index signature is missing in type 'IArguments'.
```

For example:

```
_.transform(arguments, function(map, node) {
            //...
}, {});
```

When converting `arguments` to a real array, it works fine. `_.castArray(arguments)`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
