### ISSUE TITLE
error TS2503: Cannot find namespace 'Q'.

### ISSUE THREAD

**Issue by savaratkar** [DefinitelyTyped/DefinitelyTyped#10066]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

I get this error:

 error TS2503: Cannot find namespace 'Q'.

from my application. I checked there is no import for 'Q'. My best guess its a module defining promise object. I am not sure which module is this.

**Comment by Diullei** [comment]
did you forgot to install `Q` definition?  https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/q

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
