### ISSUE TITLE
Missing methods in typescript lodash wrappers

### ISSUE THREAD

**Issue by hhsadiq** [DefinitelyTyped/DefinitelyTyped#10074]
> TypeScript code (from https://lodash.com/docs#chain):
> 
> var users = [
> { 'user': 'barney', 'age': 36 },
> { 'user': 'fred', 'age': 40 },
> { 'user': 'pebbles', 'age': 1 }
> ];
> 
> var youngest = _.chain(users)
> .sortBy('age')
> .map(function(chr) {
> return chr.user + ' is ' + chr.age;
> })
> .first()
> .value();
> tsc compiler complaints:
> 
> error TS2339: Property 'sortBy' does not exist on type 'LoDashExplicitArrayWrapper<{ 'user': string; 'age': number; }>'.
> the same happens with pluck

Same happens with _.split and countless other methods.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by webzfactory** [comment]
This should be added for min and max on LoDashExplicitArrayWrapper: 

`    
        interface LoDashExplicitArrayWrapper<T>{

        /**
        * @see _.max
        */
        max( iteratee: ListIterator<T, number>): LoDashExplicitWrapper<T>;

        /**
         * @see _.max
         */
        max(iteratee: string): LoDashExplicitWrapper<number>;

        /**
         * @see _.max
         */
        max(): LoDashExplicitWrapper<number>;

        /**
         * @see _.max
         */
        max(iteratee: Dictionary<{}>): LoDashExplicitWrapper<number>;
    }

    interface LoDashExplicitArrayWrapper<T>{
        /**
        * @see _.max
        */
        min(
        iteratee: ListIterator<T, number>
        ): LoDashExplicitWrapper<T>;

        /**
         * @see _.max
         */
        min(iteratee: string): LoDashExplicitWrapper<number>;

        /**
         * @see _.max
         */
        min(): LoDashExplicitWrapper<number>;

        /**
         * @see _.max
         */
        min(iteratee: Dictionary<{}>): LoDashExplicitWrapper<number>;
    }`

**Comment by aj-r** [comment]
This is fixed now

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
