### ISSUE TITLE
google.charts.load missing

### ISSUE THREAD

**Issue by Ponant** [DefinitelyTyped/DefinitelyTyped#10079]
google.visualization definition does not recognize what seems to be the latest way to load charts, namely somethings like

`google.charts.load('45', { 'packages': ['corechart'] });`

Instead, it currently supports very well

`google.load(...)`

It will be great to have this definition file.
Here is an example on their website
https://developers.google.com/chart/interactive/docs/quick_start

**Comment by gmoore-sjcorg** [comment]
So I have a pull request in to add some definitions to google.visualization. I'm not sure it's appropriate but I could add the charts namespace and add the google.charts.load and google.charts.setOnLoadCallback definitions there. I can't seem to find any concrete API definitions for this though. But the examples all seem to use the google.visualization namespace after so it may be the right place to add it. Thoughts?

- [Updating Library Loader Code](https://developers.google.com/chart/interactive/docs/basic_load_libs)
- [Code Examples](https://developers.google.com/chart/interactive/docs/examples)

**Comment by Ponant** [comment]
Hi, thanks for this addition if it comes, I think too that google.visualization is a good place, but I am not expert on this stuff unfortunately. Perhaps we can ask Daniel LaLiberte to join the discussion? I will forward this post to him, perhaps he can advise.

**Comment by dlaliberte** [comment]
For most  charts, you should use only the old jsapi loader with google.load() or the new gstatic loader with google.charts.load().  You should not mix the two on the same page.  If you load the www.gstatic.com/charts/loader.js, then google.charts.load() will be defined.

For GeoChart, this is a special case because the geocoder still uses the jsapi loader, but the loading is entirely internal, and all you would need to do is include the jsapi loader and not use it.   This requirement will be changing, however, and at some point soon, you won't have to load the jsapi loader for GeoChart.

**Comment by ChanceM** [comment]
Okay so just to clarify, When loading the charts with the new gstatic loader it will still instantiate the visualizations namespace? If so it would make sense to include the google.charts.load in the visualization definition file. If that's the case I will update the definition and submit a PR.
