### ISSUE TITLE
Add support for 'batch' command to redis

### ISSUE THREAD

**Issue by shpikat** [DefinitelyTyped/DefinitelyTyped#10090]
As per [documentation](https://github.com/NodeRedis/node_redis#clientbatchcommands):

> Identical to .multi without transactions. This is recommended if you want to execute many commands at once but don't have to rely on transactions

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
