### ISSUE TITLE
node-uuid : Cannot find name 'Buffer'

### ISSUE THREAD

**Issue by barocsi** [DefinitelyTyped/DefinitelyTyped#10153]
- [x] I tried using the latest `node-uuid/node-uuid.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

`TypeScript error: typings/modules/node-uuid/index.d.ts(27,50): Error TS2304: Cannot find name 'Buffer'.`

I have no clue.

**Comment by wallverb** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10044 ?

**Comment by endel** [comment]
Yup. This should solve.

```
typings install node --save --global
```

**Comment by birkskyum** [comment]
For node 4, this will do:

`typings install env~node@4 --save --global`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
