### ISSUE TITLE
Winston: metadata types on log functions

### ISSUE THREAD

**Issue by miton18** [DefinitelyTyped/DefinitelyTyped#10151]
- [ ] I want to talk about `winston/winston.d.ts`.
  - The authors of that type definition are  bonnici https://github.com/bonnici, Peter Harris https://github.com/codeanimal

Winston store metadata with a json object, why the defintions of log functions are : 

```
(msg: string, callback: LogCallback): LoggerInstance;
(msg: string, meta: any, callback: LogCallback): LoggerInstance;
(msg: string, ... meta: any[]): LoggerInstance;
```

So with that, why I can't call : 

```
winston.info('myMessage', { "test": true })
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by miton18** [comment]
It's just a question

**Comment by DABH** [comment]
@miton18 I believe you can do this?  For example see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/winston/winston-tests.ts#L133

Does this answer your question or do you have another question or some specific code that doesn't work?  Please close the issue if this answers your question.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
