### ISSUE TITLE
Getting error while testing new typing

### ISSUE THREAD

**Issue by zivni** [DefinitelyTyped/DefinitelyTyped#10216]
I wrote a new typing to be submitted and got this error running `npm test` : 
![image](https://cloud.githubusercontent.com/assets/12896422/17018704/b16476aa-4f41-11e6-8213-24ebdffe24a2.png)
Tested on windows.

Compiling using tsc works fine (I currently using this typing in my own project)

I tried adding/removing space/new lines at the end but still got this error.

You can see the files in the [following commit](https://github.com/zivni/DefinitelyTyped/commit/1ed81fd94d6f4191a2e9dc749115029293d410e5)

Where does this error comes from? Can I submit a PR with this error?

**Comment by vvakame** [comment]
> Can I submit a PR with this error?

try it! 👍

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
