### ISSUE TITLE
async 1.4.2 or 2.0.0?

### ISSUE THREAD

**Issue by xp500** [DefinitelyTyped/DefinitelyTyped#10241]
Is the async typing supposed to refer to async `1.4.2` (as the header in that file says) or async `2.0.0`

I'm asking because some of the type definitions are broken when using async `1.4.2` because they refer to the types of async `2.0.0`

For example, the callback of the iteratee passed to `filter` in `1.4.2` only receives a boolean value, but in `2.0.0` it also receives an error, which is what `async.d.ts` represents.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
