### ISSUE TITLE
kendo-ui.d.ts ChartSeriesItem and ChartCategoryAxisItemLabels

### ISSUE THREAD

**Issue by snalesso** [DefinitelyTyped/DefinitelyTyped#10284]
I noticed these issues in version 2016.1.314 (master version), these functionalities are supported by Kendo UI but missing from the Typescript definition, causing the intellisense to mark them as errors.

Missing property:

```
interface ChartCategoryAxisItemLabels
{
    cursor?: string; // property fully missing
}

```

Missing property alternative type:

```
interface ChartSeriesItem
{
    name?: string | Function; // the Function type is missing
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
