### ISSUE TITLE
process.exitCode doesn't work or exist in node.d.ts file

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/DefinitelyTyped#10302]
process.exitCode doesn't work or exist in node.d.ts file. Please add it!

Reference: https://github.com/Microsoft/TypeScript/issues/9940

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by trixlerjs** [comment]
@vvakame Sorry, but I have no time this days. But I can add to this that 
`process.stdin.isTTY` doesn't exist in `node.d.ts` either.

**Comment by Kflash** [comment]
@vvakame Hey! I ran into this issue too. I saw that `node.d.ts` have got mayour improvements lately, but still `process.exitCode` doesn't seem to exist in `node.d.ts` file.

I this something that are going to be fixed?

**Comment by jacobg** [comment]
This is still a bug. `exitCode` is missing from `child_process.d.ts`:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/child_process.d.ts
https://nodejs.org/api/child_process.html#child_process_subprocess_exitcode

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
