### ISSUE TITLE
Wrong definition of webdriver.By.js

### ISSUE THREAD

**Issue by TitanNano** [DefinitelyTyped/DefinitelyTyped#10355]
``` TypeScript
 function js(script: any, ...var_args: any[]): (WebDriver: webdriver.WebDriver) => webdriver.promise.Promise<any>;
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cc3d223a946f661eff871787edeb0fcb8f0db156/selenium-webdriver/selenium-webdriver.d.ts#L5131

this definition doesn't work. `element()` expects a `Locator` but this method is defined to return `Promise<any>`. If we ignore typescript, everything works fine, so I think the definition is wrong here.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
