### ISSUE TITLE
PouchDB on Ionic 'cannot find namespace'

### ISSUE THREAD

**Issue by ParsaAkbari** [DefinitelyTyped/DefinitelyTyped#10359]
I am using typings to install pouchdb module on an Ionic application.

`typings install dt~pouchdb --global --save`

The pouchdb/index.d.ts file is exactly the same as what is on this github repository:

```
declare module 'pouchdb' {
    const plugin: PouchDB.Static;
    export = plugin;
}
```

However I am getting the following error:
`TypeScript error: typings/globals/pouchdb/index.d.ts(4,19): Error TS2503: Cannot find namespace 'PouchDB'.`

Feel free to reproduce:

```
$ ionic start cloudo-auth blank --v2
$ cd cloudo-auth blank
$ sudo npm install pouchdb --save
$ sudo typings install dt~pouchdb --global --save
$ ionic serve
```

Thanks for your help!

[1] http://www.joshmorony.com/offline-syncing-in-ionic-2-with-pouchdb-couchdb/

**Comment by franzz2000** [comment]
I have the same problem. Using a Mac.

**Comment by vvakame** [comment]
cc/ @blakeembrey

**Comment by blakeembrey** [comment]
DefinitelyTyped does not have a dependency system in place and relies on references. Typings does not follow references. It printed that all the references were stripped.

![image](https://cloud.githubusercontent.com/assets/1088987/17345418/60a9b2fe-5949-11e6-9cfb-09dd8100507f.png)

**Comment by franzz2000** [comment]
Thanks.
The solution would be to add all the dependencies manually to the command:

typings install --global --save dt~pouchdb dt~pouchdb-adapter-websql dt~pouchdb-browser dt~pouchdb-core dt~pouchdb-http dt~pouchdb-mapreduce dt~pouchdb-node dt~pouchdb-replication

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
