### ISSUE TITLE
JQuery Validation needs update on submitHandler callback

### ISSUE THREAD

**Issue by vukasin-nikodijevic** [DefinitelyTyped/DefinitelyTyped#10376]
Here: 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery.validation/jquery.validation.d.ts#L133

Should be:

```
        submitHandler?: (form: HTMLFormElement, event:Event) => void;
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
