### ISSUE TITLE
Sequelize - Model.update receives incorrect type for values parameter

### ISSUE THREAD

**Issue by nicosampler** [DefinitelyTyped/DefinitelyTyped#10386]
I tried using the latest [sequelize definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/sequelize/sequelize.d.ts) file and had problems in Model.update function:
`interface Model<TInstance, TAttributes> extends Hooks<TInstance>, Associations
update( values : TAttributes, options : UpdateOptions ) : Promise<[number, TInstance[]]>;`

I think the `values` argument should be of type `string`. We can use this function by sending as values only a subset of TAttributes.' What do you think about that?

Thanks in advanced.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by lukiano** [comment]
What about `update( values : Partial<TAttributes>, options : UpdateOptions )`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
