### ISSUE TITLE
TSC page on website in infinite loop

### ISSUE THREAD

**Issue by toby-griffiths** [DefinitelyTyped/DefinitelyTyped#10382]
I've just found out about tsd, & wanted to read more, but the http://definitelytyped.org/tsd/ page on the website is stuck on an infinite loop, so I can't access it.

If this is not the right place to report this, please let me know where I should post it.

Thanks,

T

**Comment by anfelor** [comment]
I have the same problem in both Firefox and Chrome on Ubuntu 16.04.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
