### ISSUE TITLE
fast-simplex-noise must be installed as global 

### ISSUE THREAD

**Issue by cloutiertyler** [DefinitelyTyped/DefinitelyTyped#10415]
- [x] I tried using the latest `fast-simplex-noise/fast-simplex-noise.d.ts` file in this repo and had problems.
  - The authors of that type definition are cc/ @tobico 

Tobias, I tried installing fast-simplex-noise, but it looks like typings is requiring that I install it globally. Is there anyway to avoid this? Could I submit a pull request to fix this problem?

**Comment by tobico** [comment]
Hi @TheArtOfEngineering, as I understand it all of the definitions on DefinitelyTyped are global. I admit I don't fully understand how local type definitions work, and I'm not aware of any way to make it work with local definitions. If you can find a way to change it to work locally instead, I'd be more than happy for you to submit a pull request.

**Comment by TheArtOfEngineering** [comment]
I will admit that I also don't fully understand how type definitions work. My understanding however is basically that you can specify

```
{
    "tree": {
        "global": false
    }
}
```

in the typings.json file to indicate that `fast-simplex-noise` is a module instead of global.

On an unrelated note (I think) I was unable to import `fast-simplex-noise` by any of the means that I tried. That is:

```
import * as FastSimplexNoise from 'fast-simplex-noise';
import FastSimplexNoise from 'fast-simplex-noise';
import { FastSimplexNoise } from 'fast-simplex-noise';
```

I was able to get it to work by changing:

```
declare module "fast-simplex-noise" {
  export = FastSimplexNoise;
}
```
to
```
declare module "fast-simplex-noise" {
  export default FastSimplexNoise
}
```
however.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
