### ISSUE TITLE
[angular-mocks.d.ts] Conflicting ILogService definitions between angular and angular-mocks

### ISSUE THREAD

**Issue by kawazoe** [DefinitelyTyped/DefinitelyTyped#10469]
I have a project that uses both the "angular" and the "angular-mocks" typings from definitely typed, installed using `typings install -SG`. In that project, I am trying to create a class that explicitly implements the `angular.ILogService` interface.

```
class Logger implements angular.ILogService {
    public debug(...args: any[]): void {}
    public log(...args: any[]): void {}
    public info(...args: any[]): void {}
    public warn(...args: any[]): void {}
    public error(...args: any[]): void {}
}
```

There seems to be conflicting definitions in angular-mocks that makes it impossible to implement this interface correctly. For instance, while the basic definition of the `angular.ILogService` interface have methods that accepts any amount of parameters using the `any` type (like in the previous sample), the definition inside angular-mocks _is declaring a field instead of a method_. A similar problem arise with the `reset()` and `assertEmpty()` methods that are required to match the interface.

```
interface ILogCall { (...args: any[]): void; }
// vs
interface ILogCall { logs: string[]; }
```

There is an `angular.ILogCall` interface that is, according to the comments, explicitely declared for this purpose. The referenced documentation does not specify any differences between the normal and the mocked version of the service beside the two extra methods.

I am wondering if these interfaces should have different name or namespaces to prevent this conflict. Or maybe, I am misunderstanding how I should install the angular-mocks typings to prevent these conflicts.

**Comment by kawazoe** [comment]
@diegovilar @daltin

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
