### ISSUE TITLE
Custom mapTypeId

### ISSUE THREAD

**Issue by today-** [DefinitelyTyped/DefinitelyTyped#10480]
- [x] I tried using the latest `googlemaps/google.maps.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `googlemaps/google.maps.d.ts`.
  - The authors of that type definition are cc/ @cgwrench @hlobil 

Google maps allows to create custom maptype, and `mapTypeId` property can hold string value:
https://developers.google.com/maps/documentation/javascript/maptypes?hl=ru#MapTypeRegistry

So I suggest to change declaration of MapOptions interface

```
export interface MapOptions {
...
mapTypeId?: MapTypeId;

...
}
```

to this
`mapTypeId?: MapTypeId|string;`

**Comment by cgwrench** [comment]
I'm not sure what the correct way to proceed here. The change you suggest word go against the documentation, which doesn't include `string` as a valid type here. However, custom map types are permitted, and are identified by strings, so presumably the suggested change does work, it may just be not documented clearly enough.

It is up to the project owners to decide if they want to stick exactly to the documentation, or to include this apparently undocumented feature.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
