### ISSUE TITLE
node: ExecOptions, ForkOptions, SpawnOptions et al lack windowsVerbatimArguments

### ISSUE THREAD

**Issue by garthk** [DefinitelyTyped/DefinitelyTyped#10519]
Not yet documented (see nodejs/node#7884), but necessary for spawning JavaScript on Windows and thus used widely, e.g. in:
- [`npm`](https://github.com/npm/npm/search?q=windowsVerbatimArguments)
- [~12K other hits on GitHub](https://github.com/search?q=windowsVerbatimArguments&type=Code)

Methods in `child_process` affected:
- `fork` (`ForkOptions`)
- `exec` (`ExecOptions`)
- `spawn` (`SpawnOptions`)
- `execFile` (`SpawnSyncOptions`)
- `execSync` (`ExecSyncOptions`)
- `spawnSync` (`SpawnSyncOptions`)
- `execFileSync` (`ExecFileSyncOptions`)

As far as I can make out, they all call `spawn` or `spawnSync`, passing options through either directly or after merging with defaults through `Object.assign`, sometimes via an argument normalisation method. See also @mscdex on nodejs/node#7884:

> if it's going to be added, it should be added to all of the methods

While we're at it, could we extract common options so we're not repeating ourselves?

``` ts
export interface CommonOptions {
    cwd?: string;
    env?: any;
    gid?: number;
    uid?: number;
    windowsVerbatimArguments?: boolean;
}
```

There might be an opportunity to extract more: `encoding` and `stdio` only occur together (`InputOutputOptions`?), as do `killSignal`, `maxBuffer`, and `timeout` (no idea).

/ping @vvakame @rogierschouten @frankebersoll

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by vidartf** [comment]
This seems to be fixed in master.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
