### ISSUE TITLE
webpack-env.d.ts is not included in the export to the @types/webpack npm package

### ISSUE THREAD

**Issue by tobico** [DefinitelyTyped/DefinitelyTyped#10578]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/webpack/webpack-env.d.ts

This type definitions file is necessary when using stuff added to the module namespace by webpack, such as `require`, but it's not currently being included in the npm module for Typescript 2.0 at https://www.npmjs.com/package/@types/webpack

**Comment by mhegazy** [comment]
There is the issue that the file webpack-env.d.ts is not included in the package, this is an easy one to fix. but there is still the question of how you get this into your compilation.

webpack-env.d.ts has a conflicting definition for require that will not allow it to be included along with node.d.ts. I am not familiar with webpack usage to be able to tell if this is correct or not.

there are two options here, 

1. in `webpack/index.d.ts` add a `/// <reference path="webpack-env.d.ts" />`, so that all imports to webpack include the env declarations, but again this means that node.d.ts can not be included.

2. do not add a `/// <reference path="webpack-env.d.ts" />`, and users interested in using the env declarations need to add: `/// <reference types="webpack/webpack-env" />` explicitlly, or add it to the `--types` list in the tsconfig.json or pass it on the commandline.

I am inclined to do 2, so let me know if you think this is not correct.

**Comment by leon** [comment]
I'm having a hard time using webpack-env's Module since there is also a Module in index.d.ts

Should we rename wepack-env Module to EnvModule?

**Comment by bdoss** [comment]
They don't appear to be dependent upon one another. The index.d.ts for @types/webpack contains the definitions for the configuration that occurs on the node.js side of things. The webpack-env.d.ts file contains the typings for the additional APIs that become available in the client side environment when code is executing inside a webpack bundle. This is where the augmented require definition comes into play that could conflict with node typings. I'm personally of the opinion that webpack-env.d.ts should be split out into it's own @types package, @types/webpack-env.

**Comment by mariustom** [comment]
> or add it to the --types list in the tsconfig.json or pass it on the commandline.

this does not work; VS Code still says it's unable to find name "require".

**Comment by use-strict** [comment]
`webpack` and `webpack-env` are two different things and they should be split into separate packages. First one is used when you want to call webpack from your <insert_favorite_build_tool_here>, while the latter defines the enviroment for your project webpacked files.  See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10978#issuecomment-250759583

@mhegazy , `webpack-env.d.ts` and `node.d.ts` are mutually exclusive, because they represent two different environments. Webpack emulates some of the node.js APIs so you can run node.js code in the browser, but there are notable differences and hence the need to have a separate `webpack-env` file.

**Comment by stephtr** [comment]
> > or add it to the --types list in the tsconfig.json or pass it on the commandline.
> this does not work; VS Code still says it's unable to find name "require".
In VS Code it does not work, but when compiling with webpack it works.

**Comment by iotch** [comment]
There is another issue with `webpack-env.d.ts` - `error TS2339: Property 'catch' does not exist on type 'void'` but webpack 2 now returns a `Promise` instance from `require.ensure()` instead of `void`.

**Comment by use-strict** [comment]
Fixed with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11684

**Comment by use-strict** [comment]
@iotch , I'm not sure about your error, but if it's specific to webpack2, maybe we need new/separate definitions
