### ISSUE TITLE
Use ghost modules on highcharts

### ISSUE THREAD

**Issue by damianog** [DefinitelyTyped/DefinitelyTyped#10597]
I want to talk about `highcharts/highcharts.d.ts`.

Hi @baltie sorry to boder, what do you think about using non-instantiated modules for highcharts following the [best practices](http://definitelytyped.org/guides/best-practices.html)?

I know this will cause a breaking changes.

**Comment by vvakame** [comment]
👀

**Comment by baltie** [comment]
I considered doing that when I updated the definitions to include everything documented, but I decided against it since it would be a breaking change, and I didn't want to do more broad changes than necessary at that moment.

However, in my opinion, it would be a good idea. It will be a breaking change, but unless we do not change more than that at this time, it is a few relatively simple search&replaces to make any TypeScript code which uses the definitions compile again.

So I think we should just go for it. :)

**Comment by subash-a** [comment]
@damianog @baltie based on your discussion in this issue I have created a PR #11377 for the
 same by using ghost modules in the highcharts definition. I have kept the `__Highcharts` namespace for the sole purpose of using it to refer to the types inside that namespace. Though the `__Highcharts` is a little awkward to use when referring to the namespace in other files we could
 certainly improve this by aliasing it into `Highcharts` and then use it. If someone could shed some light on how we could do it better I would be happy to add it into my PR. @RyanCavanaugh feel free to suggest how this can achieve the above aliasing to make things cleaner.

**Comment by subash-a** [comment]
Also as a side note, the above mentioned PR is intended for the `types-2.0` branch so that it can be available through the `@types/highcharts` npm package

**Comment by subash-a** [comment]
**Note**: A revised PR #11385 has been created targeted at `master` based on the discussion in #11377

**Comment by baltie** [comment]
@subash-a Sorry for not commenting earlier, I haven't had much free time lately. However, could you please explain why you feel the need for the double underscore prepended to Highcharts? What are the problems with just naming it Highcharts and then resolving the name conflicts? We're going to have a breaking change any way you turn it...

That said, thank you for taking the time to do this! :)

**Comment by subash-a** [comment]
@baltie apologies for delayed reply, the only reason for using `__Higcharts` is to ensure that we do not pollute the global namespace, if I were to use just `Highcharts` as the namespace it would be available to all the typescript files without having to explicitly import the module which defeats the purpose of having a module based system, I do understand that the `__` prefix is a little odd but I adopted it from [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6112#issuecomment-145455720) discussion. In the newer version of typescript there is a way to avoid this pollution of global namespace but since this definition would cater to a wider audience I thought this would be the way to go for now, I would be happy to change it into any other prefix based on your suggestion and thanks for taking the time to look into this 😄

**Comment by baltie** [comment]
@subash-a Thanks for explaining. :) I'm not that concerned about polluting the global namespace with a single interface called something noone else is going to call anything, but I see your point.

However, I think we should completely adapt the pattern that the React library has set and add a highcharts-global.d.ts file which is possible to use in legacy TS where we actually would want to be able to reference types with Highcharts.<something>.

So I'm going to redact my request to revert. Do you have the time to make the change I proposed? Have a look at the react definitions and adopt that? :)

**Comment by subash-a** [comment]
Sure @baltie I will take a look at the way the React library does it and add a global version of the type definitions, I cannot set a timeline though on when I can get the PR in, I will try to do it as early as possible and mention it in this issue at which point I guess we can close this, sounds good?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
