### ISSUE TITLE
Material UI Typings. Why doesn't TextFieldProps extend HtmlProps?

### ISSUE THREAD

**Issue by dalexander01** [DefinitelyTyped/DefinitelyTyped#10627]
I tried using the latest `material-ui/index.d.ts` file in this repo and had problems.
- The authors of that type definition are cc/ @ngbrown 

I have a textfield that I set the autofocus and maxlength props. I cannot do this however since TextField only extends React.Props in the material-ui typings. Is there any reason for this? How can I resolve?

**Comment by dalexander01** [comment]
Running into a similar problem with FlatButton since I would like to set the "title" prop of the flatbutton to set the tooltip text.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
