### ISSUE TITLE
Missing definition for AmMap in AmCharts

### ISSUE THREAD

**Issue by DPalagi** [DefinitelyTyped/DefinitelyTyped#10671]
- [x] I want to talk about `amcharts/AmCharts.d.ts`.

Hi, I'm using the file `amcharts/AmCharts.d.ts`, for Charts purpose but I have to use AmMap too which is not (yet) defined in the AmCharts file. Could you, please, update the file with the corresponding class ?

Thank you in advance,

Regards

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by avonwyss** [comment]
I've written a tool to scrope the AmCharts docs and create TS definitions from that. Unfortunately and in contrast to the standard JS AmCharts, the AmMap part of the class reference is not really suitable for that. 

For instance, if you have a look at https://docs.amcharts.com/3/javascriptmaps/AmMap methods which are not inherited methods, there are two main problems:

- While arguments are listed in the method signature (first column), the parameters column does not give any information on the types of these arguments.
- The return values (third column) does not contain useful type information either: what is for instance a `longitude` (a number, a string, any of these, an object? I don't know), same for most other methods.

Here's the output of my tool run including AmMap docs: https://gist.github.com/avonwyss/5dee2f4f9bf49e61971ee2fc12d3246f
You'll need to fix the problems starting around like 10809.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
