### ISSUE TITLE
Question: Help needed for new PR structure

### ISSUE THREAD

**Issue by microshine** [DefinitelyTyped/DefinitelyTyped#10701]
I've got 2 npm modules ([node-webcrypto-p11](https://www.npmjs.com/package/node-webcrypto-p11) and [node-webcrypto-ossl](https://www.npmjs.com/package/node-webcrypto-ossl)). Those modules implements one interface - extended WebCrypto from lib.d.ts.
What is the best way for modules declarations?

I want to create 3 modules

```
node-webcrypto (global interfaces)
node-webcrypto-p11 (implements NodeCrypto)
node-webcrypto-ossl (implements NodeCrypto)
```

There is one problem that node-webcrypto must have a link to npm modile. But it doesn;t exist. It's only global type declarations

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
