### ISSUE TITLE
Typing request: RxJS: Observable error

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#10737]
It should be possible to add a generic to `Rx.Observable` to define the type of errors in the stream.

**Comment by vvakame** [comment]
um?
Is this package? https://www.npmjs.com/package/rxjs
rxjs has own typings. https://github.com/ReactiveX/rxjs/blob/master/package.json#L197

**Comment by OliverJAsh** [comment]
This was referring to RxJS 4, typings at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/rx/rx-lite.d.ts.

That package is RxJS 5, still in beta.

**Comment by vvakame** [comment]
okay.
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
