### ISSUE TITLE
Knex.d.ts falsely relies on bluebird 2.0

### ISSUE THREAD

**Issue by ericeslinger** [DefinitelyTyped/DefinitelyTyped#10793]
- [X] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] I want to talk about `knex/knex.d.ts`.
  - The authors of that type definition are cc/ @tkQubo

It looks like the knex.d.ts definition file declares a dependency on bluebird 2.0 typings. The current version of knex.js relies in the 3.x branch of bluebird. Using bluebird (3.0) at the top level and knex in the same project results in `error TS2300 Duplicate identifier 'export='` errors, as the type system seems to be looking at both types/bluebird (for 3.0) and types/knex/node_modules/types/bluebird (for 2.0). Manually modifying the package.json and types/knex directories in my node_modules directory clear this problem up.

**Comment by taybin** [comment]
This can be closed as knex provides its own definitions now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
