### ISSUE TITLE
openlayers.d.ts Unable to create ol.interaction.Pointer

### ISSUE THREAD

**Issue by skewty** [DefinitelyTyped/DefinitelyTyped#10812]
### Unable to create an `ol.interaction.Pointer`

```
       constructor() {
           ....
           let handPointer = new ol.interaction.Pointer(
               {
                  handleMoveEvent: this.handlePointerMoveEvent
               }
           );
           ....
        }
        private handlePointerMoveEvent(evt) {
            ....
        }
```
### The error is:

> Error:(92, 59) TS2345: Argument of type '{ handleMoveEvent: (evt: any) => void; }' is not assignable to parameter of type 'Object'.
>  Object literal may only specify known properties, and 'handleMoveEvent' does not exist in type 'Object'.

I tried typecasting with:

`let handPointer = new ol.interaction.Pointer(<ol.Object>{handleMoveEvent: this.handlePointerMoveEvent});`

but then it just says:

> Error:(92, 58) TS2352: Neither type '{ handleMoveEvent: (evt: any) => void; }' nor type 'Object' is assignable to the other.
>  Property 'get' is missing in type '{ handleMoveEvent: (evt: any) => void; }'.
### This is the quick fix I used (line 3635 of openlayers.d.ts):

```
        class Interaction extends ol.Object {
            constructor(opt_options?: {})
        }
```

**Comment by skewty** [comment]
This is the quick fix I used:

line 3635 of openlayers.d.ts
```
        class Interaction extends ol.Object {
            constructor(opt_options?: {})
        }
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
