### ISSUE TITLE
ng-file-upload: IFileUploadConfigFile should not extend IRequestConfig

### ISSUE THREAD

**Issue by kristho91** [DefinitelyTyped/DefinitelyTyped#10819]
I seems that IFileUploadConfigFile should NOT extend IRequestConfig (from angular). According to the ng-file-upload docs it should be possible to do:

`
Upload.upload({
    url: 'upload/url',
    data: {file: file, 'username': $scope.username}
})`

But because of the dependency on IRequestConfig you need to add a "method:" in the object. That should not be necessary.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
