### ISSUE TITLE
Example of how to use a "module" DT file, like bowser?

### ISSUE THREAD

**Issue by nicholashead** [DefinitelyTyped/DefinitelyTyped#10813]
I've tried asking/explaining on StackOverflow and elsewhere, but I'm totally stumped: http://stackoverflow.com/questions/39127674/using-an-import-statement-breaks-other-class-references

Given a definitely file like https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/bowser/bowser.d.ts from @pocesar - which seems to be a "module"-- how am I supposed to use that in my TypeScript files? I've tried just referencing `bowser` after referencing the definitely typed browser.d.ts file - but it doesn't work. I can add `import bowser = require('bowser');` to the top of my TS file, and that seems to kinda work, but then it breaks other references in my TS file (see my Stackoverflow link for an example)-- I guess it turns my TS file into a "module" too??

I'm just totally lost here in dealing with "module" definition files. It didn't used to be like this, it seems. I've been using DefinitelyTyped for a long time. Look at the jQuery DT file - it doesn't use modules as far as I can tell, and when I reference it, it just works. It seems like bowser should not be using modules, since it's using a global/static `bowser.` method anyway, right?

I can do this I guess: `declare var bowser: BowserModule.IBowser;` but that seems wrong..

If someone can give me a guide/getting started on how folks are expected to consume/use DT module definitions, that'd be fantastic, and probably something to improve the documentation with. I'd really appreciate any help you can give me here.

**Comment by pocesar** [comment]
indeed, I'm always using browserify or SystemJS, and they turn every `import` to either a reference to a global module in `window` (through `browserify-shim`) or through an actual injection of the bowser module inside a standalone "pack" (contains all dependencies + your code)

since I wasn't using a bowser global, I forgot that the library actually export it to window. your fix is the right way to go, inside the bowser.d.ts. lodash was having this problem and bit me in the ass a couple of times (where the `_` was globally declared), but I was using it in node, so even though Typescript was compiling, it was erroring at runtime, because _ was undefined) #4046. 
but since bowser wouldn't work as-is in node (without jsdom anyway), there's no point of omitting the global declaration.

I'll send a patch
