### ISSUE TITLE
JQueryUI interactions arguments have wrong type

### ISSUE THREAD

**Issue by mwisnicki** [DefinitelyTyped/DefinitelyTyped#1082]
For example `resizable()` takes `JQueryUI.ResizableOptions` which lacks events from `ResizableEvents` so it's impossible to write typesafe code like:

``` typescript
$( ".selector" ).resizable({
  start: function( event, ui ) {}
});
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
