### ISSUE TITLE
Scattered 'own' promise implementations

### ISSUE THREAD

**Issue by pocesar** [DefinitelyTyped/DefinitelyTyped#10892]
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

I have encountered a lot of typings that provide their own version of PromiseLike. Since lib.d.ts provide this, we should guide people to stop trying to have their own `thenable` implementation and just use PromiseLike for interop. (the same goes for ArrayLike). I had problems when using bluebird or jquery promises and they weren't playing ok with each other (plugins that is)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
