### ISSUE TITLE
Strange express dependency

### ISSUE THREAD

**Issue by samizdam** [DefinitelyTyped/DefinitelyTyped#10910]
I use log4js definition and get next error on tsc (Version 1.8.9) compilation:

`typings/globals/log4js/index.d.ts(4,28): error TS2307: Cannot find module 'express'.`

But I'm not need express in my app. And I watched source code of log4js and it's not really use express as dependency: https://github.com/nomiddlename/log4js-node/search?utf8=%E2%9C%93&q=express 

If I remove from this index.d.ts [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/log4js/log4js.d.ts#L9)  and return types on lines [103](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/log4js/log4js.d.ts#L103) and [104](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/log4js/log4js.d.ts#L104) it's work well. 

Can I send PR with removed express usage to log4js/log4js.d.ts?

**Comment by vvakame** [comment]
yes!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
