### ISSUE TITLE
Bluebird types are missing `.suppressUnhandledRejections()`

### ISSUE THREAD

**Issue by cyang1** [DefinitelyTyped/DefinitelyTyped#10979]
- [x] I tried using the latest `bluebird/index.d.ts` file in this repo and had problems.

It appears to be missing the [new in bluebird 3.0](http://bluebirdjs.com/docs/new-in-bluebird-3.html) [`.suppressUnhandledRejections()` function](http://bluebirdjs.com/docs/api/suppressunhandledrejections.html).

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by Retsam** [comment]
Looks like this was fixed in #11575.  I think this issue should be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
