### ISSUE TITLE
connect-flash types out-of-date

### ISSUE THREAD

**Issue by cyang1** [DefinitelyTyped/DefinitelyTyped#10981]
- [x] I tried using the latest `connect-flash/index.d.ts` file in this repo and had problems.

The existing type definitions for `Request.flash()` seem out-of-date. Currently, it's:

``` typescript
declare namespace Express {
    export interface Request {
        flash(message: string): any;
        flash(event: string, message: string): any;
    }
}
```

but it probably should be something like (warning: unverified):

``` typescript
declare namespace Express {
    export interface Request {
        flash(): {[event: string] : string[]};
        flash(event: string): string[];
        flash(event: string, message: string): number;
        flash(event: string, messages: string[]): number;
        flash(event: string, format: string, ...args: any[]): number;
    }
}
```

Additionally, it's not currently possible to import the module using ES6 import syntax (importing using `import * as flash from "connect-flash"` complains about a non-module entity). I'm fairly new to TypeScript, but I've read that an empty namespace hack would help here.

**Comment by cyang1** [comment]
@AndreasGassmann as the listed creator of the definitions.

**Comment by RLovelett** [comment]
@cyang1 I for one think this is a great proposal. Have you moved forward with this anywhere?

**Comment by AndreasGassmann** [comment]
@cyang1 Sorry for the late reply. I'm not actively using connect-flash anymore, so I didn't see it's not compatible anymore. Feel free to update! Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
