### ISSUE TITLE
github-electron should be renamed to electron

### ISSUE THREAD

**Issue by mmc41** [DefinitelyTyped/DefinitelyTyped#10993]
The npm package used to install Electron has been renamed - the corresponding typings file should matcht the npm package.

**Comment by vvakame** [comment]
good catch. cc/ @jedmao @rhysd @miniak
https://www.npmjs.com/package/electron

**Comment by mmc41** [comment]
Note: "As of version 1.3.1, this package is published to npm under two names: electron and electron-prebuilt. You can currently use either name, but electron is recommended, as the electron-**prebuilt name is deprecated,** and will only be published until the end of 2016."

**Comment by vvakame** [comment]
umm... We can't get response from authors.
I vote 👍 for your suggestions.
Could you make a pull request?

**Comment by mmc41** [comment]
FYI: I think @miniak is maintaining the electron types (See https://github.com/electron/electron/issues/4875)

**Comment by rhysd** [comment]
@mmc41 @vvakame @miniak 

Sorry for late for catching this issue.

I :+1: to this suggestion.  Changing directory name 'github-electron' to 'electron' looks to cause no problem. However, renaming 'github-electron.d.ts' to 'electron.d.ts' has a problem.  Because there are two 'electron' modules.  Electron runtime defines all Electron APIs in 'electron' package in Electron environment.  Apart from it, 'electron-prebuilt' package was renamed to 'electron'.  So there would be name collision when we would rename 'github-electron.d.ts' to 'electron.d.ts'. 

I already created an issue for this but no one looks not interested.

https://github.com/electron-userland/electron-prebuilt/issues/181

**Comment by zeke** [comment]
Hey TypeScripters, sorry we broke your stuff!

@MarshallOfSound and I are actively working on generating an up-to-date TypeScript definition file for Electron, and will hopefully eventually ship `electron.d.ts` as part of `electron` (nee `electron-prebuilt`) itself. That would render this issue unnecessary, right?

For updates on that, watch this issue: https://github.com/electron/electron/issues/4875#issuecomment-252364976

In the meantime, I am 👍  on the `github-electron` -> `electron` rename here.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
