### ISSUE TITLE
mdns.d.ts - Cant finde namespace NodeJS

### ISSUE THREAD

**Issue by JustMeDaFaq** [DefinitelyTyped/DefinitelyTyped#11002]
I tried using latest mdns.d.ts (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/mdns/mdns.d.ts)

Tho its telling me,"Cannot find namespace 'NodeJS'

Does anyone may know how to fix it?
The authors of that type definition are @reppners @cjdellbn @vvakame

**Comment by vvakame** [comment]
you should use with `node/node.d.ts`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
