### ISSUE TITLE
FBResponseObject definition may be outdated (fbsdk/index.d.ts)

### ISSUE THREAD

**Issue by LostLucidity** [DefinitelyTyped/DefinitelyTyped#11007]
From the typings definition for fbsdk/index.d.ts .

I tried using FBResponseObject on line 166 key/pair declarations by trying to access the data key but it returns me undefined. The response I'm getting in return for the data I want looks to be top level, where things like name and id are return right of the first level of the object. It's been a year since the interface was setup, can anyone else verify what I am seeing? 

Here's my api call:

```
FB.api('/me', {fields: name}, (response) => {
  console.log("Successful login for " + response.name);
  console.log(response);
  document.getElementById('status').innerHTML =
    'Thanks for logging in, ' + response + '!';
  return response
});
```

reponse.data does not exist. The response returns an object containing { name: 'name', id: 'id' } and whatever extra I request.
I had to remove the FBResponseObject interface and just declare an Object to get my typings to pass:
On line 177, from 
api(path : string, params : Object, callback : (fbResponseObject : Object) => any) :  Object;

To
api(path : string, params : Object, callback : (Object) => any) :  Object;

Let me know if I need to clarify. I'm not sure how the interface FBResponseObject needs to be updated for it to work in my case. Thanks.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
