### ISSUE TITLE
Update Babylon.js to 2.4.0

### ISSUE THREAD

**Issue by enricostara** [DefinitelyTyped/DefinitelyTyped#11023]
babylon.js was recently updated to 2.4.0. It would be great if the type definitions could be updated to include these.

https://github.com/BabylonJS/Babylon.js

Thanks.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
