### ISSUE TITLE
NG: ng.IDirective doesn't allow binding template to a function(elem, attrs)

### ISSUE THREAD

**Issue by georgiosd** [DefinitelyTyped/DefinitelyTyped#1102]
Not sure how this could be fixed without changing `template` to `any`.

Is there a way to say, in TS, that a property is either a string or a function?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
