### ISSUE TITLE
amcharts: property isReady missing

### ISSUE THREAD

**Issue by avonwyss** [DefinitelyTyped/DefinitelyTyped#11090]
I tried using the latest `amharts/AmCharts.d.ts` file in this repo and had problems:

When using amCharts with an asynchronous loader (such as RequireJS), it is necessary to manually set the property `isReady` (boolean) to true. This seems to be missing from the definitions though.
https://www.amcharts.com/kbase/amcharts-meets-requirejs/

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by avonwyss** [comment]
I encountered more issues with the existing AmCharts definitions so I re-created the whole set from the official AmCharts docs (actually I wrote a tool which reads the HTML help pages and creates the definitions from that). Shall I make a pull request for the new file - any advice on the suggested way to deal with this?

The most important differences are:
- Each class also has a similar "Config" interface with only properties, all but `type` being optional. This can be used to define charts as plain JSON data with the `AmCmarts.makeChart()` function - https://docs.amcharts.com/3/javascriptcharts/AmChart#makeChart
- All types, properties and methods are in the definition with the help text from the website (and properties include the `@default` if one was noted in the web help)

**Comment by vvakame** [comment]
cc/ @aleksey-bykov

**Comment by aleksey-bykov** [comment]
i originally submitted the definitions as it was a part of my project at that time, now i am not actively involved into ongoing support, if you anyone wants to take over and they *know how to do it* please let me know, other than that there is no need to cc me

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
