### ISSUE TITLE
Problem with ng-stomp

### ISSUE THREAD

**Issue by Noobaseem** [DefinitelyTyped/DefinitelyTyped#11118]
There is no export statement in the Type Definition file, how can I use this file in my module ?

**Comment by vvakame** [comment]
cc/ @lpotapczuk

**Comment by Noobaseem** [comment]
Please help
I am stuck on this one for quite some time..

**Comment by vvakame** [comment]
If you want to get answer immediately, you should go to stackoverflow.

**Comment by Noobaseem** [comment]
I have solved my problem by creating a custom type definition for my project, but I am still curious to know how ng-stomp can be used instead.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
