### ISSUE TITLE
express: RequestHandler should not be marked as optional

### ISSUE THREAD

**Issue by Strate** [DefinitelyTyped/DefinitelyTyped#11164]
There is no marks about possible optional `next` argument in RequestHandler in express's documentation. So, seems that it should not be marked as optional. Making this argument optional makes it harder to use with `strictNullChecks` option enabled.

Also, I could not find out reason of this commit https://github.com/DefinitelyTyped/DefinitelyTyped/commit/dcaf000f890831e3e8431f0f682c7fffd06241ee

/cc @mahald

**Comment by TonyPythoneer** [comment]
Hi @Strate , I had seen your comment on #10676.

If interface can implement override, maybe it will be solved:

```
interface RequestHandler {
    (req: Request, res: Response): any;
    (req: Request, res: Response, next: NextFunction): any;
}
```

Ideally, it's compatible with `http.createServer` and `strictNullChecks` option enabled.

/cc @sandersn

**Comment by sandersn** [comment]
The bug that @TonyPythoneer found was `http.createServer(app)` didn't work where `app` is an express app. That's because `createServer` only passes two arguments to `app`*. I don't know anything about express, actually. Could it be that there are two related types here: one that can be passed to `http.createServer`, where `next` is optional, and one that is used for request handlers that are passed to `app.get`, where `next` is required?

@TonyPythoneer a function that satisfies your `RequestHandler` would have to handle both overloads, right? In that case I think you will still need the `if (next) ... else ???` code that @Strate noticed.

*As far as I know. It's possible that `createServer` also passes a `next` argument.

**Comment by Strate** [comment]
I think that there is really 2 types, one with optional `next` argument, which is returned from `express()` function, and other with required `next` argument, which is passed to express's route handlers and middlewares.
Points in source code:
[app.handle](https://github.com/expressjs/express/blob/3e4158bcbda7017dbe7226fb76d974bd95c29ce9/lib/application.js#L123) is the function, which returned from `express()`. As you can see [here](https://github.com/expressjs/express/blob/3e4158bcbda7017dbe7226fb76d974bd95c29ce9/lib/application.js#L127-L130) third argument is really optional. Function calls `router.handle` with always populated thirs arument at the ond of function.

**Comment by Strate** [comment]
I think that easies way to solve it, is to make third argument required on `RequestHandler` interface, and add call signature with optional 3 argument on `Application` interface:
```ts
interface Application extends IRouter, Express.Application {
  (req: Request, res: Response, next?: NextFunction): any
}
```
