### ISSUE TITLE
[jquery] global $ should be removed from definition

### ISSUE THREAD

**Issue by akomm** [DefinitelyTyped/DefinitelyTyped#11187]
- [x] I want to talk about `jquery/jquery.d.ts`.

$ is to ambiguous to be defined as global variable. It can be done easily by user, optionally adding:

``` ts
declare var $: JQueryStatic;
```

It causes annoying type warnings, when other definitions use this variable too (they also should not). Having it as an opt-in makes it possible to solve the problem by just not declaring $. For example [here](https://github.com/AngularClass/angular2-webpack-starter/issues/435) a collision with `protractor` typings which also define $ (again, they should not too) is unfixable without vendor files hacking.

**Comment by use-strict** [comment]
I have a problem with this as well, mostly because in our project we don't have the $ global available and it would trigger a runtime error every time a developer forgot to import jquery and used the global.

I thought Typings would fix this, but it seems it's not able to install the dt jquery definition as non-ambient. As long as the developer will not allow splitting the jquery.d.ts file or removing the global, the only solution is to create and maintain an alternative definition for yourself.

**Comment by ashblue** [comment]
+1

**Comment by kpotura** [comment]
+1

**Comment by ffMathy** [comment]
I still think this should be done. Why was it removed at one point, but then re-added? Can we fix it with tests?

**Comment by ffMathy** [comment]
I started doing it, but it turns out (surprise!) that it is a bit more trickier than first envisioned.

Any ideas from the community on how we can get this solved?

**Comment by ffMathy** [comment]
Also related: #1564.

**Comment by akomm** [comment]
For me its a typing error to define something global, without knowledge how the module is actually loaded (globally or not). The public export $ should simply be removed. However I see this is BC break for those, who relied on it and used/use jQuery globally and no other module with same definition. 

Is there some issue with that, except the BC break?

**Comment by ffMathy** [comment]
It's great you're still chiming in with ideas.

I'm willing to go for the breaking approach, although that also requires a lot of upgrades.

**Comment by akomm** [comment]
For those, who used it like it is now and were fine with it, it should only require this declaration in global module:
```ts
declare var $: JQueryStatic;
```

Or am I wrong?

**Comment by ffMathy** [comment]
I think you're right.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
