### ISSUE TITLE
[react-bootstrap] InputGroup.Addon doesn't compile

### ISSUE THREAD

**Issue by aaronbeall** [DefinitelyTyped/DefinitelyTyped#11190]
I get an error when I try to use `InputGroup.Addon` from the React Bootstrap examples:

```
<InputGroup.Addon>@</InputGroup.Addon>
  <FormControl type="text" />
</InputGroup>
```

Gives me:

```
Error:(136, 23) TS2339: Property 'Addon' does not exist on type 'ClassicComponentClass<InputGroupProps>'.
```

However the resulting code works fine. If I import `InputGroupAddon` it doesn't render at runtime.

Shouldn't the definition declare `Addon` as static?

```
interface InputGroupClass {
    Addon: typeof InputGroupAddon;
    // vs
    static Addon: typeof InputGroupAddon;
}
```

Same goes for all the other definitions like this? (`FormControl.Feedback`, `Modal.Body`, etc)

**Comment by vvakame** [comment]
cc/ @walkerburgin @vsiao @danilojrr @Batbold-Gansukh

**Comment by vsiao** [comment]
Sounds like it should probably be static! Feel free to send a PR.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
