### ISSUE TITLE
missing: node dgram.socket.bind() (w/o params) is not defined

### ISSUE THREAD

**Issue by dharmax** [DefinitelyTyped/DefinitelyTyped#11244]
- [ X] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
