### ISSUE TITLE
Greesock TweenMax tweenConfig Object

### ISSUE THREAD

**Issue by lucap86** [DefinitelyTyped/DefinitelyTyped#11265]
According to tweenmax docs
 https://greensock.com/docs/#/HTML5/GSAP/TweenMax/to/ 
it should be great to define TweenMax.to/TweenLite.to config object param as follow:

declare type TweenConfig = {
    [tweenProp: string]: any;
    delay?: number;
    ease?: Ease;
    repeat?: number;
    repeatDelay?: number;
    yoyo?: boolean;
    paused?: boolean;
    overwrite?: string|number;
    onComplete?: Function;
    immediateRender?: boolean;
    onCompleteParams?: any[];
    onCompleteScope?: Object;
    onRepeat?: Function;
    onRepeatScope?: Object;
    onReverseComplete?: Function;
    onReverseCompleteParams?: any[];
    onReverseCompleteScope?: Object;
    onStart?: Function;
    onStartParams?: any[];
    onStartScope?: Object;
    onUpdate?: Function;
    onUpdateParams?: any[];
    onUpdateScope?: Object;
    startAt?: Object;
    useFrames?: boolean;
    lazy?: boolean;
    onOverwrite?: Function;
    autoCSS?: boolean;
    callbackScope?: Object;
}

and related method signatures to:

static to(target: Object, duration: number, vars: TweenConfig): TweenLite;
static to(target: Object, duration: number, vars: TweenConfig): TweenMax;

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by lucap86** [comment]
Done PR #11310
it also included refs #9944 0d185df already approved and merged commit, don't know why. sorry.

**Comment by endel** [comment]
It might be a good idea to replace the [`gsap`](http://npmjs.com/package/@types/gsap) definitions with the ones declared in the `greensock` package. `greensock` is not an actual npm module, [as you can see](https://www.npmjs.com/package/greensock). And, apparently, the `greensock` definitions are more up-to-date.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
