### ISSUE TITLE
[backbone] View.events definition enhancement

### ISSUE THREAD

**Issue by aventurella** [DefinitelyTyped/DefinitelyTyped#11273]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/backbone/backbone-global.d.ts#L395

Currently the events are defined as:

```
events(): EventsHash;
```

There is a comment in the code that offers casting advice, `<any>` when assigning not via function.

Wouldn't it be better to use a Union type here instead of a comment in the type definition?

```
events: (() => EventsHash) | EventsHash;
```

This would eliminate the need for the `<any>` cast in a comments of the definition. It will also operate as expected.

```
/**
* Events hash or a method returning the events hash that maps events/selectors to methods on your View.
* For assigning events as object hash, do it like this: this.events = <any>{ "event:selector": callback, ... };
* That works only if you set it in the constructor or the initialize method.
**/
```

**Comment by aventurella** [comment]
Ah I understand why it is the way it is now:

http://benmccormick.org/2015/07/06/backbone-and-es6-classes-revisited/

This helped explain it and the decorator solution is actually pretty nice. especially `@on`. So now comes a better question. What can be done to better expose the `why` so someone else doesn't fall into the same trap I fell into.

I can totally see why it's listed as a method now, not a property. And looking at the TS compiler output it makes even more sense as to why.  That doesn't come across though.

**Comment by aventurella** [comment]
I wonder if it's worth hitting up the backbone folks and checking the feasibility of adding a section to the backbone html docs about working with ES6 and TypeScript, so it's documented somewhere that people can find easily.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
