### ISSUE TITLE
[whatwg-fetch] requires ES6 target or node.d.ts but doesnt need to 

### ISSUE THREAD

**Issue by danmortimer** [DefinitelyTyped/DefinitelyTyped#11290]
the whatwg-fetch typings reference the interfaces Symbol and IterableIterator so if you target ES5 it fails to build. The fetch project it matches at https://github.com/github/fetch has built in fallbacks for the iterators and is meant to be used with ES5. So it shouldnt reference those ES6 types. 
I cant use the typings as they are without including core-js or node.d.ts  or targeting ES6, which is not actually required by the library itself.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by tobico** [comment]
Looks like the problem lines are these ones, defining an iterator interface for the Headers class - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/whatwg-fetch/whatwg-fetch.d.ts#L24-L28

These methods do exist, but they're not essential to use the library, and the type they rely on doesn't exist without ES6.

Anyone know of a way to make these definitions conditional on the types actually existing? Or any other nice way to handle this without breaking things for either use case?

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ebfa2f08edfe5f5398357c63339a462e702d9484/node/node.d.ts#L21-L27
We can use this pattern.

**Comment by seansfkelley** [comment]
The workaround I used for this was to install the typings for es6-promise and then add these to a miscellaneous/catch-all "extra typings" file I have around:

```
type IterableIterator<T> = any;
type IteratorResult<T> = any;
declare const Symbol: {
  iterator: symbol;
};
```

I wasn't able to find all of these typings shimmed out elsewhere, so I just basically exempted the whole from type checking.

**Comment by 5uper5imon** [comment]
tobico:
> These methods do exist, but they're not essential to use the library, and the type they rely on doesn't exist without ES6.

That actually isn't really the case. 
Check this: https://github.com/github/fetch/blob/master/fetch.js#L40-L56 

If it sees that Symbol.iterator  is supported (either es6 or a polyfill) then it uses those types. Otherwise it shims in the basic iterator functionality.

Because of this, I think the best option is to type the iterator shim.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
