### ISSUE TITLE
[Material-UI] Export ThemePalette interface

### ISSUE THREAD

**Issue by frankvdb7** [DefinitelyTyped/DefinitelyTyped#11300]
I'm using React context to expose a global ThemePallete throughout my application, but I need to use 'any' types for my objects because the ThemePallete is not exported. I can manually fix this by adding a simple line:

`export var ThemePalette: ThemePalette;`

It would be nice to have this export included by default.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
