### ISSUE TITLE
[bootstrap.v3.datetimepicker] Latest version is not installed by default

### ISSUE THREAD

**Issue by jws305** [DefinitelyTyped/DefinitelyTyped#11330]
There are two versions listed when installing via command line, 0.0.0 and 3.0.0.  The 0.0.0 is actually for a higher version of the library.

**Comment by andy-ms** [comment]
`npm info @types/bootstrap.v3.datetimepicker` does not show a version `0.0.0`, did you mean a different library?

**Comment by jws305** [comment]
I am using typings.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
