### ISSUE TITLE
error in findKey return type

### ISSUE THREAD

**Issue by federicoce-moravia** [DefinitelyTyped/DefinitelyTyped#11376]
In the underscore.js typings sub-repo (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/underscore)
File: underscore.d.ts

findKey returns the key of the first element that satisfied the predicate in a dictionary-like object, signature should be:

`findKey<T>(obj: _.Dictionary<T>, predicate: _.ObjectIterator<T, boolean>, context?: any): string;`

**Comment by andy-ms** [comment]
What typing is this for?

**Comment by federicoce-moravia** [comment]
underscore.js, sorry about that; I've updated my comment

**Comment by andy-ms** [comment]
Could you make a PR for this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
