### ISSUE TITLE
Set BuildAction to TypeScriptCompile when installing from nuget

### ISSUE THREAD

**Issue by nvivo** [DefinitelyTyped/DefinitelyTyped#1138]
Since 0.9, VS automatically references every typescript file without the need to add a references command to each file.

But this only works if the BuildAction is set to TypeScriptCompile, so the nuget packages should set the build action correctly when they are installed.

Currently, I set this manually but it resets to Content on every update causing lots of compilation errors until it is fixed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
