### ISSUE TITLE
Update for kendo-ui.TypeScript.DefinitelyTyped

### ISSUE THREAD

**Issue by mhsimkin** [DefinitelyTyped/DefinitelyTyped#11417]
The Telerik team told me that they have submitted updates for kendo-ui.TypeScript.DefinitelyTyped to your team.

When will the latest version of the definitions and nuget package be made available?  These changes correspond to the latest release of the Kendo UI, which was made available last week.

Thanks

marc

**Comment by andy-ms** [comment]
Hi @mhsimkin, you are probably talking about #11320. As you can see, the changes aren't in yet. We normally wait for someone knowledgable to review these packages before merging changes -- you could help review too. After it is reviewed, we can merge to master. After that, someone will have to manually merge changes from `master` to the `types-2.0` branch, and after that is in it will get published to the `@types` NPM scope.

**Comment by vvakame** [comment]
maybe he is talking about NuGet package. right?
cc/ @staxmanade

**Comment by staxmanade** [comment]
Since they have been merged - it looks like they were published on NuGet? https://www.nuget.org/packages/kendo-ui.TypeScript.DefinitelyTyped/

Is it showing up there correctly?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
