### ISSUE TITLE
[validator/validator.d.ts] Discussing local types

### ISSUE THREAD

**Issue by IOAyman** [DefinitelyTyped/DefinitelyTyped#11491]
- [x] I want to talk about `validator/validator.d.ts`.
  - The authors of that type definition are cc/ @tgfjt @chrootsu @IOAyman @louy 

@TonyPythoneer has pushed few days ago a couple of commits adding few local types ([`AlphaLocal`, `AlphanumericLocal`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11381) and [`MobilePhoneLocal`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11478)). I like the idea. 

However, an example like this
```ts
const x: string = 'en-US'
validator.isAlpha('xyz', x)
```
 would not be OK!
`'string' is not assignable to parameter of type 'AlphaLocale'`

=============================
related PRs: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11381 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11478

**Comment by TonyPythoneer** [comment]
@IOAyman, Of course, it's failed. It's because that is `String Literal Types`. It allows you to specify the exact value a string must have.

In fact, `isAlpha`, `isAlphanumeric` and `isMobilePhone` must be used specified locale which document mentioned, so I define that.

Although the locale is like or seems a `string` type, it uses specified string as type, it means specified string is the subset of string type. It's sure that `locale`  parameter can't take `string` type, I must use `String Literal Types` to exactly define it.

Example:
```
const x: ValidatorJS.AlphaLocale = 'en-US'
validator.isAlpha('xyz', x)
```

This would be passed.

**Comment by IOAyman** [comment]
@TonyPythoneer Yes I'm well aware of that.
What I did was `const x: validator.AlphaLocal = ...`, which is wrong! I should've used `ValidatorJS.AlphaLocal` instead!

Thanks :)

**Comment by TonyPythoneer** [comment]
The `validator` type is `validatorStatic`. The `validatorStatic` only exports functions, not including any type or interface.
If you need to use type to define it, you should call `ValidatorJS.something`. 😄

**Comment by IOAyman** [comment]
Right.
I tried a while back to change that to just `Validator`, but I did not have the time to fix all the related issues that would come up; Many other modules, such as `sequelize`, depend on this.

**Comment by TonyPythoneer** [comment]
If other modules which depends on  `validator`, Travis ci will report fail.
Up to now everything has been successful. 😄
