### ISSUE TITLE
lodash:  forEach() callback "key" parameter is optional.  It should not be?

### ISSUE THREAD

**Issue by jasonswearingen** [DefinitelyTyped/DefinitelyTyped#11516]
lodash .d.ts maintainers:   @bczengel @chrootsu @stepancar

using the latest lodash definition from `@types`, the `.forEach()` method (and other collection enumeration functions) has a callback with the signature

```
    interface ObjectIterator<T, TResult> {
        (element: T, key?: string, collection?: any): TResult;
    }
```

the `key?:string` parameter being nullable wreaks havoc when you turn the `"strictNullChecks": true` typescript compiler parameter on, due to the type now being `string|undefined`

is the "`?`" optional really needed?  I can't think of any situations where the key would be `undefined`.   So can it safely be changed to just `key:string`?

**Comment by vvakame** [comment]
I think maybe you are right.
please send a pull request. I'll review it.

**Comment by aj-r** [comment]
Relevant Typescript documentation: http://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#optional-parameters-in-callbacks

**Comment by aj-r** [comment]
This is fixed now

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
