### ISSUE TITLE
JqueryUI DatePicker method definition missing eg: _getInst, _formatDate etc..

### ISSUE THREAD

**Issue by tkarthick81** [DefinitelyTyped/DefinitelyTyped#11535]
- [x] I tried using the latest `jqueryui/jqueryui.d.ts` file in this repo and had problems.
  - The authors of that type definition are cc/ @johnnyreilly @DanielRosenwasser @borisyankov @errorx666 @vvakame @herrquark

Below are some method missing in jqueryUI definition for datePicker
_getInst
_formatDate
_datepickerShowing
_adjustDate
_get
_dayOverClass
_currentClass
_selectDay
_hideDatePicker
_getDaysInMonth

**Comment by johnnyreilly** [comment]
Pull requests welcome!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
