### ISSUE TITLE
How to correctly install pg?

### ISSUE THREAD

**Issue by Sean-Brown** [DefinitelyTyped/DefinitelyTyped#11564]
Node v4.0.0
Typings v1.4.0

Command: typings install dt~pg -SG

This command saves the typings file correctly (it only allows installing pg globally...) but looking at the [source file on Github](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/pg/pg.d.ts) it appears that the top comments and reference to node.d.ts get stripped and replaced by:

> // Generated by typings
> // Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/67e4127430d1b0fd0d51925b9380206180ce5e23/pg/pg.d.ts

which causes compiler errors due to "Promise" being unresolved (which is the whole point of
`/// <reference path="../node/node.d.ts" />`
at the top of the original file.), so I'm confused as to how to correctly install "pg" with typings

**Comment by TonyPythoneer** [comment]
It's because typings can't install dependence definitions. Thereforce, you should install node.d.ts and offer pg to refer it.

**Comment by vvakame** [comment]
cc/ @blakeembrey

**Comment by Sean-Brown** [comment]
For reference, I do have node defined in my typings.json, I do notice that the "pg" package looks for "../node/node.d.ts" but the typescript definition file that typings installed is located at "../node/**index**.d.ts"

**Comment by blakeembrey** [comment]
`Promise` being unresolved should be unrelated to `node.d.ts`. The local version uses your `node.d.ts` anyway, because the reference is stripped. If you want global `Promise` typings, you would need to install them _or_ you need to set your `tsconfig.json` target to `es6`.

**Comment by Sean-Brown** [comment]
WebStorm is confused:
![no_promise](https://cloud.githubusercontent.com/assets/1503131/18929673/65bae3dc-8593-11e6-856c-a8df21bfe85d.PNG)

I haven't actually tried compiling the whole project yet because the "pg" package is part of a new feature that's not close to implemented, I was just wondering about the "correct" way to add a typings package because all the other packages I added don't have the same issue about "Cannot find name ..."

**Comment by vitaly-t** [comment]
@Sean-Brown WebStorm is confused because the default for TypeScript compilation is ES5.

For full-syntax compilation use the following...

Menu File->Settings->Language & Frameworks->TypeScript, switch on `Enable TypeScript Compiler`, and put `--target es6 --module commonjs` into `Command line options`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
