### ISSUE TITLE
Redux: Dispatch has unused generic type parameter

### ISSUE THREAD

**Issue by alexfoxgill** [DefinitelyTyped/DefinitelyTyped#11599]
```
/**
 * A *dispatching function* (or simply *dispatch function*) is a function that
 * accepts an action or an async action; it then may or may not dispatch one
 * or more actions to the store.
 *
 * We must distinguish between dispatching functions in general and the base
 * `dispatch` function provided by the store instance without any middleware.
 *
 * The base dispatch function *always* synchronously sends an action to the
 * store’s reducer, along with the previous state returned by the store, to
 * calculate a new state. It expects actions to be plain objects ready to be
 * consumed by the reducer.
 *
 * Middleware wraps the base dispatch function. It allows the dispatch
 * function to handle async actions in addition to actions. Middleware may
 * transform, delay, ignore, or otherwise interpret actions or async actions
 * before passing them to the next middleware.
 */

interface Dispatch<S> {
    <A extends Action>(action: A): A;
}
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/redux/redux.d.ts#L102

What is the point of the `S` type parameter? It's not clear what it's supposed to be

**Comment by TonyPythoneer** [comment]
I think it's typo. You can send PR to fix that. :smile:

**Comment by stephtr** [comment]
I don't think that's a typo. `S` stands for the store type. Dispatch can be wrapped by additions, for example [redux-thunk](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/453537778d3b137322995807e03ae560a58be099/redux-thunk/redux-thunk.d.ts), whose Dispatch depend on S.

**Comment by alexfoxgill** [comment]
@stephtr maybe I misunderstand but presumably the 'wrapped' version is a different function in a different module?

**Comment by stephtr** [comment]
The unwrapped version itself doesn't need to know about `S` (it doesn't even use it). The thing is that the signature shouldn't change too much for the end user depending on which middleware he chooses.
Otherwise he would at first write `dispatch(...)`, include for example redux-thunk and then there are two options: Use `dispatch(...)` for normal dispatches and `dispatch<Store>(...)` for dispatching thunks. Everytime he changes the parameter type the template parameter has to be added or removed. Or just like now, write everywhere `dispatch<Store>(...)` in advance.
In praxis it is even more complicate because the template parameter is filled by the Store itself.
I'm not sure if that is all exactly correct (I am by far no expert in Redux), gut the main reason should be correct.

**Comment by alexfoxgill** [comment]
Could redux-thunk not be implemented with the store as a generic parameter on the method rather than the interface?

```TypeScript
declare namespace Redux {
	type ThunkAction<R, S, E> = (dispatch: Dispatch, getState: () => S, extraArgument: E) => R;

	interface Dispatch {
		<R, S, E>(asyncAction: ThunkAction<R, S, E>): R;
	}
}
```

**Comment by stephtr** [comment]
dispatch is a member of the redux store and therefore `S` is already fixed while at least R can very from call to call.
```
interface Store<S> {
    dispatch: Dispatch<S>;
}
```

But mabye it is better to ask the question at [reactjs/redux](https://github.com/reactjs/redux/issues) since they also have that TypeScript definition.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
