### ISSUE TITLE
Type of process.env should be { [key: string]: string }

### ISSUE THREAD

**Issue by ThibaultRiviere** [DefinitelyTyped/DefinitelyTyped#11615]
This will allow to typescript to trigger compile error :

``` js
    const x: number = process.env.x;
```

See Microsoft/TypeScript/issues/11239

**Comment by mizunashi-mana** [comment]
I see what you mean.  However, this request have a problem.

```typescript
const val: { [key: string]: string; } = { 'x': 'str', };
const x = val.x;
```

This code reports error: `error TS2339: Property 'x' does not exist on type '{ [key: string]: string; }'.`
If `process.env` had type `{ [key: string]: string; }`, your code would be:

```typescript
const x: number = process.env['x']; // type error!
```

There is a problem from compatibility, and it may be different from what you mean.

Actually, I recommend this request.  But, because many typescript users use syntax on their program such as `process.env.x`, for compatibility, we might be better to use `any` type for `process.env`.

**Comment by mizunashi-mana** [comment]
May be related to https://github.com/Microsoft/TypeScript/issues/560

This definition partially solves this problem.
https://github.com/types/env-node/blob/master/6/node.d.ts#L460-L463

Such code is correct on `env~node`:
```typescript
const path = process.env.PATH;
```

However, this code is invalid:

```typescript
const x = process.env.x
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
