### ISSUE TITLE
[request] jsrsasign?

### ISSUE THREAD

**Issue by suzerain** [DefinitelyTyped/DefinitelyTyped#11699]
Can't seem to find a definition file for jsrsasign.

https://github.com/kjur/jsrsasign

I found an uncommented one here:

http://codegists.com/snippet/typescript/jsrsasigndts_jmurphzyo_typescript

Does this exist already or should I take a crack at it?

**Comment by ffflorian** [comment]
@DefinitelyTyped any news on this? :slightly_smiling_face:

**Comment by williamchristophercooley** [comment]
he stated he is not going to do this apparently

https://github.com/kjur/jsrsasign/issues/306

**Comment by franklinyu** [comment]
In addition, he doesn’t strictly follows semantic versioning. For example, he introduced [`CMSUtil.verifySignedData()`](https://kjur.github.io/jsrsasign/api/symbols/KJUR.asn1.cms.CMSUtil.html#.verifySignedData) in release 8.0.4, which is supposed to be a bug-fix release. Will this be an issue? AFAIK the major and minor version of type package is the same as the original package so that user won’t accidentally use new features.

**Comment by aneilbaboo** [comment]
There's another implementation here: https://github.com/kjur/jsrsasign/issues/306#issue-269638414

**Comment by ffflorian** [comment]
I am also working on it, contributions always welcome:

https://github.com/ffflorian/jsrsasign-types
