### ISSUE TITLE
Express missing type information

### ISSUE THREAD

**Issue by gabzim** [DefinitelyTyped/DefinitelyTyped#11721]
Express exports a middleware that is not declared in the typings file. It exports the query() middleware that it invokes internally but it is also exported. 

Now this middleware is not used often but when you do URL rewriting you may need to re-parse query parameters, which is exactly the problem I'm having.

I get this error:
`error TS2305: Module '"/Users/gabriel/work/project/node_modules/@types/express/index"' has no exported member 'query'.`

But the reality is it does have that exported member. It's just not present in the `.d.ts` file. I'm not comfortable enough with typings to make a PR for this otherwise I would.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
