### ISSUE TITLE
[mongoose/mongoose.d.ts] Type 'MongoosePromise' is not assignable to type 'IThenable'

### ISSUE THREAD

**Issue by IOAyman** [DefinitelyTyped/DefinitelyTyped#11729]
- [x] I tried using the latest `mongoose/mongoose.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `mongoose/mongoose.d.ts`.
  - The authors of that type definition are cc/ @simonxca  
# 

I've got some code that looks something like this

``` ts
funcReturnsPromise()   // returns an IThennable
  .then((token) => {
    /* do stuff */
    return X.save()  // X: Model<IXDocuement>
  })
  .then( (saved: IXDocument) => { ... } )
  ...
```

I use the ['@types/promise'](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/promise/index.d.ts) library for promises. But it seems that `MongoosePromise` type is not compatible with `IThennable`.

So the previous code throws:

``` ts
Error:(YY, ZZ) TS2345: Argument of type '(x: string) => MongoosePromise<IXDocument>' is not assignable to parameter of type '(value: string) => IXDocument | IThenable<IXDocument>'.
 Type 'MongoosePromise<IXDocument>' is not assignable to type 'IXDocument | IThenable<IXDocument>'.
 Type 'MongoosePromise<IXDocument>' is not assignable to type 'IThenable<IXDocument>'.
 Types of property 'then' are incompatible.
 Type '{ <TRes>(onFulFill: (arg: IXDocument) => void | TRes | PromiseLike<TRes>, onReject?: (err:...' is not assignable to type '<R>(onFulfilled?: (value: IXDocument) => R | IThenable<R>, onRejected?: (error: any) => R ...'.
 Type 'MongoosePromise<any>' is not assignable to type 'IThenable<any>'.
 Types of property 'then' are incompatible.
 Type '{ <TRes>(onFulFill: (arg: any) => void | TRes | PromiseLike<TRes>, onReject?: (err: any) => void ...' is not assignable to type '<R>(onFulfilled?: (value: any) => R | IThenable<R>, onRejected?: (error: any) => R | IThenable<R>...'.
 Type 'MongoosePromise<any>' is not assignable to type 'IThenable<any>'.
```

**Comment by simonxca** [comment]
@IOAyman Something's suspicious here. `MongoosePromise` was changed a while ago because it didn't work with `types-2.0` so that name shouldn't be in use.

The updated instructions are here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/mongoose#promises

This is what I did, see if this works for you:
1. `npm install @types/mongoose`
2. In `node_modules/@types/mongoose/index.d.ts` remove the dependencies for `mongoose-promise` and `mpromise` at the top. This was removed a while ago from the `master` branch, but for some reason the `types-2.0` branch was not updated. I've sent a PR.
3. The definition above uses `global.Promise` (whatever that is defined as) by default, if you want to use something else, you can redefine `type Promise` in mongoose.
4. `npm install @types/promise`
5. I have a file that is included in my compile step:
```
import * as Promise from 'promise';
declare module 'mongoose' {
  type Promise<T> = Promise.IPromise;
}
```
This will override the promise type in `mongoose`
6. After that, this will return a IPromise and IThenable etc:
```
User.find(...).exec()      // returns Promise.IPromise
  .resolve(...)            // returns Promise.IThenable
  .then(...);              // returns Promise.IThenable
```
