### ISSUE TITLE
[kendo-ui/kendo-ui.d.ts] Definitions for kendo.confirm and kendo.prompt are incorrect

### ISSUE THREAD

**Issue by mhsimkin** [DefinitelyTyped/DefinitelyTyped#11732]
As per support ticket at Telerik, the current definitions for the functions confirm and prompt are incorrect.  

The underlying JavaScript functions return a jQuery promise to all the caller to wait for a response from the user.  The current Typescript definitions do not have a return type of JQueryPromise.  Therefore, the Typescipt code will not allow the use of done and fail methods of the JQueryPromise.

Theses functions are currently defined as:

``` typescript
function confirm(text: string): void;
function prompt(text: string, defaultValue: string): void;
```

When they should be defined as:

``` typescript
function confirm(text: string): JQueryPromise<any>;
function prompt(text: string, defaultValue: string): JQueryPromise<any>;
```

This issue is documented in Telerik ticket # 1064838.

Note: I'm not sure what steps I need to follow in order to submit the changes myself.  Therefore, I documented them above, in the hope that someone else can make the change.

Thanks

marc

**Comment by Xizario** [comment]
They are [corrected](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/kendo-ui/index.d.ts#L17485) and this issue can be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
