### ISSUE TITLE
AngularJS/Angular.d.js is outdated for 1.5.8

### ISSUE THREAD

**Issue by Venthe** [DefinitelyTyped/DefinitelyTyped#11769]
- [X] I tried using the latest `angularjs/angular.d.ts` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] I want to talk about `angularjs/angular.d.ts`.

https://github.com/angular/angular.js/blob/master/src/ng/filter/orderBy.js @ line 552 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angularjs/angular.d.ts @ line 746 is outdated (It does not provide optional function (val,val) for comparator.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by Venthe** [comment]
#11790 if you could :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
