### ISSUE TITLE
angular.d.ts Add Type "animation" to Interface "IModule"

### ISSUE THREAD

**Issue by stephengardner** [DefinitelyTyped/DefinitelyTyped#11846]
`property 'animation' does not exist on type IModule`  using latest `angular.d.ts`

Animations should be valid.  They are used.  [Here ](https://docs.angularjs.org/guide/animations)is the documentation for them.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by CreamFraiche** [comment]
anything going on with this?

**Comment by sarahpads** [comment]
@CreamFraiche running `npm install --save-dev @types/angular-animate` solved it for me.

**Comment by elpdpt** [comment]
@vvakame Issue can be closed? This seems to be [fixed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b3cad84aa3f656a5f0efb2f57df662ac0b5148a0/types/angular-animate/index.d.ts#L307).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
