### ISSUE TITLE
Unable to include velocity animate in projects

### ISSUE THREAD

**Issue by ajainvivek** [DefinitelyTyped/DefinitelyTyped#11869]
I am unable to include velocity-animate type definition rightly. Always it keeps throwing error _$(...).velocity is not a function_ 

```
import * as $ from 'jquery';
import 'velocity-animate';  
```

Can someone help me out here. 

Thanks,

**Comment by tbone849** [comment]
Not sure if you ever got this to work, but I just got it working in my own project.

`import * as Velocity from 'velocity-animate';`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
