### ISSUE TITLE
What type definition file includes `UrlSearchParams`. 

### ISSUE THREAD

**Issue by shaunluttin** [DefinitelyTyped/DefinitelyTyped#11875]
I am using TypeScript 2.0 and have run `npm install @types whatwg-fetch` and `npm install @types isomorphic-fetch`. Neither supports `UrlSearchParams`. The workaround for now is to add a custom type definition like this: 

```
interface URLSearchParams {}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
