### ISSUE TITLE
Didn't work for me

### ISSUE THREAD

**Issue by PompolutZ** [DefinitelyTyped/DefinitelyTyped#11887]
Hi,

I have tried to add material-ui to my project which located here:
https://github.com/PompolutZ/typescript_react_mini_boilerplate.git 

following tutorial on material-ui site, and noticed that I receive compilation time errors like:

'Could not load module ...'

I found this question on SO:
http://stackoverflow.com/questions/37186500/how-to-setup-material-ui-for-react-with-typescript

And realised that I haven't added typings, but after adding them I still cannot compile. Using material-ui sample without typescript works fine for me.

I assume that because I am quite new to this stuff I might have missed something, I will be glad for any help.

**Comment by cquick** [comment]
I'm finding the same issue, specifically attempting to include this line from the sample: 

`import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';`

Even after editing the tsconfig file and including "material-ui" in the types for compilerOptions, it still gets an error when attempting to resolve the typings. 

I want to point out that I'm using ASP.Net Core 2 with the React/Redux template. I was simply trying to change the sample project over to material-ui instead of bootstrap, but this has made using it a show-stopper unless I'm willing to drop using TypeScript.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
