### ISSUE TITLE
"sinon-stub-promise" doesn't export default function

### ISSUE THREAD

**Issue by marvinhagemeister** [DefinitelyTyped/DefinitelyTyped#11880]
- [x] I tried using the latest `sinon-stub-promise/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `sinon-stub-promise/index.d.ts`.
  - The authors of that type definition are cc/ @vintem 

The package [sinon-stub-promise](https://github.com/substantial/sinon-stub-promise) has a default function export, which is not reflected inside the typescript bindings.

`sinon-stub-promise` is used to enhance the existing sinon object. Usage per Readme is:

``` js
// js example taken from readme
var sinon = require('sinon');
var sinonStubPromise = require('sinon-stub-promise');
sinonStubPromise(sinon); // Fails in typescript
```

I tried patching the typings myself, but I'm stuck now.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by tstackhouse** [comment]
This is still an issue, as it exports a function, and not a wrapper, therefore we cannot use ES6 import syntax.

**Comment by andy-ms** [comment]
@tstackhouse Try enabling [`--allowSyntheticDefaultImports`](http://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by tstackhouse** [comment]
I was hoping to avoid that.  It seems like it would do the trick though.

I was able to work around it like so, which seemed to work just fine:

```
import * as sinon from 'sinon';
const sinonStubPromise = require('sinon-stub-promise');
sinonStubPromise(sinon);
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
