### ISSUE TITLE
react-router-redux regression

### ISSUE THREAD

**Issue by aliatsis** [DefinitelyTyped/DefinitelyTyped#11983]
A recent update to the react-router-redux typings introduced a regression that produces the following error:

```
// error TS2339: Property 'pathname' does not exist on type 'LocationDescriptor'.
let action: RouterAction;
action.payload.pathname
```

The notes in the release that broke this state the following:
- [react-router-redux] Update action payload type (#11559)

The payload for React Redux Router action is a location object. For more information look at the source code [here](https://github.com/reactjs/react-router-redux/blob/master/src/sync.js#L95)

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
