### ISSUE TITLE
Node has several types being exported as interfaces that could otherwise be Classes

### ISSUE THREAD

**Issue by watzon** [DefinitelyTyped/DefinitelyTyped#11981]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I want to talk about `node/index.d.ts`

While attempting to build a from-scratch http server in Typescript I realized that there are several class-like structures in the node definitions that are being exported as interfaces. This means that attempting to extend said interfaces results in an error.

For example:

``` typescript
import * as http from 'http';

export class Request extends http.IncomingMessage {
    constructor() {
        super();
    }
}
```

the above will thow the error `Cannot extend an interface 'http.IncomingMessage'. Did you mean 'implements'?`. Everything in `http` is exported as an interface besides `Agent`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
