### ISSUE TITLE
Make $scope optional for IComponentControllerService definition

### ISSUE THREAD

**Issue by pramodsankarl** [DefinitelyTyped/DefinitelyTyped#12028]
- [x] I tried using the latest `angularjs/angular-mocks.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I want to talk about `angularjs/angular-mocks.d.ts`.
  - The authors of that type definition are cc/ @vvakame @AlStar01 @homesar

`$scope` is optional in the locals for `IComponentControllerService` in angular 1.5. Please mark scope as optional in the locals.

Current Definition:

```
interface IComponentControllerService {
       //.......
      <T, TBinding>(componentName: string, locals: { $scope: IScope, [key: string]: any }, bindings?: TBinding, ident?: string): T;
    }
```

Either remove `$scope` from locals or just make it optional.

```
interface IComponentControllerService {
      //.....
      <T, TBinding>(componentName: string, locals: { $scope?: IScope, [key: string]: any }, bindings?: TBinding, ident?: string): T;
    }
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by pramodsankarl** [comment]
@vvakame I have [created a PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12048) for this towards types2.0 branch. But it appears CI is broken for types2.0 branch.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
