### ISSUE TITLE
needle - HTTPHeaderOptions missing some headers

### ISSUE THREAD

**Issue by willm** [DefinitelyTyped/DefinitelyTyped#12032]
- [ x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x] I want to talk about `needle/needle.d.ts`.
  - The authors of that type definition are cc/ @vvakame @bigsan @DanielRosenwasser 

I'm using needle to send requests with an Authoridsation header, however the [current type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/36d40a63a05b5cb3413737fbdf7c9a2a26f211fd/needle/needle.d.ts#L41) does not see to allow me to do this. I'd like to suggest  replacing `HttpHeaderOptions` with any as you can technically add any header you want to a request. I'm happy to make this change if you agree.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
