### ISSUE TITLE
QUnit Extend provides no support for actually extending assert

### ISSUE THREAD

**Issue by Martinspire** [DefinitelyTyped/DefinitelyTyped#12031]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `qunit/qunit.d.ts`.
  - The authors of that type definition are cc/ @diullei

Say i extend QUnit assert like in this example:
https://api.qunitjs.com/pushResult/

Then Typescript will complain about the function not existing on assert.

Shouldn't `qunit.d.ts` include functionality to make sure you are able to extend it? Or what is the recommended solution for making sure typescript recognizes your extentions?

**Comment by cfuehrmann** [comment]
I just ran into the same problem, trying to extend QUnit assert while using TypeScript. Considering the rising popularity of TypeScript, this seems to be a serious issue for QUnit.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
