### ISSUE TITLE
underscore.d.ts: Error "Duplicate identifier '_'" with TypeScript 0.9.5-dev

### ISSUE THREAD

**Issue by hastebrot** [DefinitelyTyped/DefinitelyTyped#1204]
TypeScript version: 0.9.5-dev. Newest LKG in development branch (74fcef88f112).
underscore.d.ts version: Newest in master branch.

```
.../underscore/underscore.d.ts(1376,1): error TS2000: Duplicate identifier '_'.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
