### ISSUE TITLE
Response argument for callback should be IncomingMessage

### ISSUE THREAD

**Issue by willm** [DefinitelyTyped/DefinitelyTyped#12053]
[ x] I tried using the latest xxxx/xxxx.d.ts file in this repo and had problems.
[x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
[ x] I have a question that is inappropriate for StackOverflow. (Please ask any appropriate questions there).
[ x] I want to talk about needle/needle.d.ts.
The authors of that type definition are cc/ @vvakame @bigsan @DanielRosenwasser

Seeing as this library is dependent on node, would it not make sense to make the [response argument to the callback](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/needle/needle.d.ts#L13) of type [`http.IncomingMessage`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/node.d.ts#L659)?

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
