### ISSUE TITLE
_.defaultTo missing in lodash typings

### ISSUE THREAD

**Issue by evansnicholas** [DefinitelyTyped/DefinitelyTyped#12062]
- I tried using the latest `lodash/index.d.ts` file in this repo and had problems.

I could not find a type definition for _.defaultTo.  I think it needs to be added.
- The authors of that type definition are @bczengel, @chrootsu, @stepancar.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by evansnicholas** [comment]
I have created a pull request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12101

**Comment by karfau** [comment]
Since this one is still open, I'm raising the question here:
because of the thing `defaultTo` does should the type of the first parameter not be `T | undefined | null | NaN`?
The way it is now type inference from the parameters doesn't work very well.

If you prefer I can also create a new issue or PR, would love to hear the opinion of the original author(s).

**Comment by christian-pepperstone** [comment]
#12101 was merged 26 Oct 2017, but `defaultTo` type is still missing from the latest `@types/lodash` release.
