### ISSUE TITLE
Getting Position from X Y Coordinates

### ISSUE THREAD

**Issue by RickStrahl** [DefinitelyTyped/DefinitelyTyped#12077]
I've been trying to make drag and drop file insertion work with ACE and since Ace doesn't seem to support native drag drop event (`editor.on('drop')` doesn't fire), I've been using native drop operations. I can get everything to work except capturing the actual drop insertion point.

I get x y coordinates from the DOM, but I can't figure out a way to turn that into a selection range to paste to (I capture the file then insert a URL/Path into the document).

I've tried capturing onMouseMove and `e.getDocumentPosition()` which gives me the document position, but the drag events don't seem to properly fire the mousemove event so the position isn't updated properly.,

Any suggestions on how this can be made to work?

I've run into this scenario a few times with other operations - It would be really useful to have an easy way to go from an X Y offset (relative to the control or client) and to row and column position.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
