### ISSUE TITLE
[react-bootstrap] Type error on Elements in DropdownButton title

### ISSUE THREAD

**Issue by haizz** [DefinitelyTyped/DefinitelyTyped#12085]
DropdownButton in react-bootstrap allows any React node (string, number, Element, array etc) in `title` property: 
`title: React.PropTypes.node.isRequired` (https://github.com/react-bootstrap/react-bootstrap/blob/master/src/DropdownButton.js#L12).

But in typings 1) it has string type and 2) it's marked as not required because DropdownButtonProps are based on React.HTMLProps which has `title?: string` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/36d40a63a05b5cb3413737fbdf7c9a2a26f211fd/react-bootstrap/react-bootstrap.d.ts#L188).

So this kind of code obviously gives an error:

``` jsx
<DropdownButton title={<span>...</span>}>
// ...
</DropdownButton>
```

Would be great to have this fixed.
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `xxxx/xxxx.d.ts`.
- The authors of that type definition are cc/ @walkerburgin @vsiao @danilobjr @Batbold-Gansukh

**Comment by tomffee** [comment]
👍 Added very similar issue few minutes ago

**Comment by haizz** [comment]
@walkerburgin @vsiao @danilobjr @Batbold-Gansukh

I think this issue is quite important because it blocks the ability to use glyphicons in DropdownButtons, for example. Previous versions of the react-bootstrap typings allowed that and right now lots of code is broken due to this regression.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
