### ISSUE TITLE
[react-bootstrap] Tab title as string but should also allow React.Node

### ISSUE THREAD

**Issue by tomffee** [DefinitelyTyped/DefinitelyTyped#12086]
Firstly, I need to say I am new with typescript.

I tried using the latest `react-bootstrap/index.d.ts` [[source](https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/0f4a73ef205e808cc824d81ff6839d3fa27df251/react-bootstrap/react-bootstrap.d.ts)] in this repo and had problems.

The problem is that if I use code like this:

``` javascript
<Tabs 
      defaultActiveKey={1}
      id="lorem-id-tabs"
>
  <Tab
      eventKey={1}
      title={
          <div>
              <span className="lorem-ipsum">Dolor</span>
           </div>
      }
    >
       //...lorem
    </Tab>
</Tabs>
```

it gives me error for type `Type 'Element' is not assignable to type 'string'.`

In the latest documentation for Tabs in _react-bootstrap_ [[source](https://react-bootstrap.github.io/components.html#tabs-props-pane)] this option is available.

The same problem is with the `NavItem`. I looked at the source file and saw that the usage is the same.

Would it be possible to change that prop so it can take `string | React.Node` instead of `string`

Thx for answer and have a nice day 😉 
- [x] I tried using the latest react-bootstrap/index.d.ts file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

``` json
//package.json
"typescript": "^2.0.3",
"typescript-require": "^0.2.9-1",
"typings": "^1.4.0",
```
- [ ] I have a question that is inappropriate for StackOverflow. (Please ask any appropriate questions there).
- [x] I want to talk about xxxx/xxxx.d.ts.
  cc// : @walkerburgin @vsiao @danilobjr @Batbold-Gansukh

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
