### ISSUE TITLE
Move all declarations in a subfolder for @types-2.0

### ISSUE THREAD

**Issue by ibratoev** [DefinitelyTyped/DefinitelyTyped#12094]
Consider moving all declarations in a subfolder, for example named _declarations_. So for example, the _abs_ declarations will not be in a top _abs_ folder in the repo but in _declarations/abs_.

This will make it generally easier to work with the repo. It will improve the readability of the home GitHub and the README.

The migration to the @types-2.0 branch sounds like the perfect time for such a change.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
