### ISSUE TITLE
websql conflicts with phonegap

### ISSUE THREAD

**Issue by heathbar** [DefinitelyTyped/DefinitelyTyped#12112]
phonegap/index.d.ts and websql/index.d.ts both declare an interface named `SQLError` with a property named `message`, but they do not agree on the type.

Compiling a project with both definition files yields the following error:
`Subsequent variable declarations must have the same type.  Variable 'message' must be of type 'string', but here has type 'DOMString'. websql/index.d.ts`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
