### ISSUE TITLE
Angular Typedef issue IDirective

### ISSUE THREAD

**Issue by d-n-k** [DefinitelyTyped/DefinitelyTyped#12275]
I have a before current version implementation of directives and it's running through compilation - OK,
Now after this current update I have a failing error:

```
Types of property 'scope' are incompatible.
    Type '{ vrNotifications: string; }' is not assignable to type 'boolean | { [boundProperty: string]: string; }'.
      Type '{ vrNotifications: string; }' is not assignable to type '{ [boundProperty: string]: string; }'.
        Index signature is missing in type '{ vrNotifications: string; }'.
```

Can you clarify, on how to implement it correctly? 

```
 scope?: boolean | {[boundProperty: string]: string};
```

*\* Should new update break so many changes?

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by thorn0** [comment]
@d-n-k What TS version are you using? Is there something that prevents you from updating to v2.x?

**Comment by brianhines** [comment]
I've upgraded to TS2.0 and I still get this error, code looks similar to this:

`export class someDirective implements ng.IDirective {
    static instance(): ng.IDirective {
        return new someDirective();
    }
    ...
    scope = {
        prop: '@'
    };
    ....
}

angular.module('app.somedirective').directive('someDirective', someDirective.instance);`

Get an error on the class declaration and the line inside the instance method:

Types of property 'scope' are incompatible.
    Type '{ prop: string; }' is not assignable to type 'boolean | { [boundProperty: string]: string; }'.
      Type '{ prop: string; }' is not assignable to type '{ [boundProperty: string]: string; }'.
        Index signature is missing in type '{ prop: string; }'.

It works if I change the scope property in angular.d.ts to an any (or even back to boolean | Object;) or if I declare my scope variable like this: 

`scope: boolean | { [ key; string]: string } = {
    prop: '@'
};`

Any ideas on how to implement this without adding the extra typing on the scope variable but still not lose the typing on the interface definition?

**Comment by thorn0** [comment]
What are your compiler options?

**Comment by brianhines** [comment]
I'm using VS2015 so my TS Build properties are ECMAScript versoin is ECMAScript 5 (tried 6 also) and my module system is CommonJS (tried ES2015 also).  Anything in particular I should be looking for?  Or another place I should be looking for more compiler option information?

**Comment by thorn0** [comment]
I don't know. It's really strange. You shouldn't get this error in TS 2.0. Double check that you're really using the new version of the compiler.
See http://stackoverflow.com/questions/22077023

**Comment by brianhines** [comment]
Ah, so since you asked, I went ahead and verified my project was using the latest version of typescript by changing my 2.0 folder to z2.0, which of course gave me the error "The specified task executable location "C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0\tsc.exe" is invalid".  So my project seems to be set up correctly, but that lead me to the 1 warning I have in my error list:

> Your project file uses a newer version of the TypeScript compiler and tools than supported by this version of Visual Studio.  Your project may be using TypeScript language features that will result in errors when compiling with this version of the TypeScript tools.  To remove this warning, remove the <TypeScriptToolsVersion> element from your project file.

So I guess I'm referencing 2.0 but since VS2015 isn't updated, I'm not truly using 2.0.  Guessing that's my problem then huh?  I'm going to try to update VS and see if that fixes the issue.

**Comment by thorn0** [comment]
It may suffice to update only the [TS extension](https://www.microsoft.com/en-us/download/details.aspx?id=48593), not whole VS.

**Comment by brianhines** [comment]
Sorry, Thanksgiving break, just now getting back to this.  That was the issue.  I changed my Typescript Version to 2.0 but I needed to update VS (possibly the TS extension update would have worked but I updated VS to Update 3) and I no longer see those errors.  Thanks for all your help!

**Comment by brianhines** [comment]
Looks like that was the key.  Once I installed VS2015 Update 3 and changed my version to 2.0, those errors went away.  I did try updating the TS Extension and it didn't seem to fix the issue because VS 2015 recognized it as too new of a TS version to be using with Update 2.  Wouldn't have expected that, but with all of it updated, everything worked.  Thanks for all your help.

**Comment by thorn0** [comment]
In this case, please close the issue.
