### ISSUE TITLE
RequireJS: require:Require vs require:NodeRequire compile warning/error

### ISSUE THREAD

**Issue by electricessence** [DefinitelyTyped/DefinitelyTyped#12283]
Noticed that when I import requirejs as a @ type file from NPM I get conflicts.
Any idea how to properly get around this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
