### ISSUE TITLE
Make JSON files and `.editorconfig` match

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#12280]
The flie `.editorconfig` specifies 2 space indents for JSON files, but all (or almost all) of our `tsconfig.json` and `package.json` files use 4 spaces.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
