### ISSUE TITLE
electron.d.ts is wrong

### ISSUE THREAD

**Issue by dolanmiu** [DefinitelyTyped/DefinitelyTyped#12282]
- [x] I tried using the latest `electron.d.ts` file in this repo and had problems.

when I simply type `typings install electron --save --global --source=dt`

I get weird typescript definitions:

![screen shot 2016-10-26 at 22 49 55](https://cloud.githubusercontent.com/assets/2917613/19746535/c128a604-9bce-11e6-841f-e601f99a7e55.png)

Therefore, whenever I try to use electron, it gives me:

![screen shot 2016-10-26 at 22 53 07](https://cloud.githubusercontent.com/assets/2917613/19746598/03af8d26-9bcf-11e6-977e-e494ea469366.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
