### ISSUE TITLE
How to create a type definition for a CommonJS module that exports a function?

### ISSUE THREAD

**Issue by mohsen1** [DefinitelyTyped/DefinitelyTyped#12395]
I'm trying to contribute a type definition for a module that exports like this:

```js
  module.exports = function (store) {
    return store;
  };
```

But using `export =` or `export default` gave me all sort of errors. 

What is the best of exporting for modules like this today?

**Comment by vvakame** [comment]
```
function foo(store:any): void;
export = foo;
```
try this form.

**Comment by mohsen1** [comment]
@vvakame without declaring any module? 

let's say that file that is exporting function is at `node_modules/foo/index.js`

and I'm putting my `.d.ts` file in `node_modules/@types/foo/index.d.ts`

If content of `index.d.ts` is the following, it won't work:

```ts
dclare module 'foo' {
function foo(store:any): void;
export = foo;
}
```

When I import `"foo"`, I get following error: 

```ts
import fn from 'foo';
```
```
 error TS2497: Module ''foo'' resolves to a non-module entity and cannot be imported using this construct.
```

**Comment by vvakame** [comment]
```
function foo(store:any): void;
declare namespace foo {}
export = foo;
```

```
import * as fn from 'foo';
```

http://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html

**Comment by mohsen1** [comment]
That's not working either. It's the same problem as https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11720

if a npm module is exporting a function, there is that problem...

**Comment by mohsen1** [comment]
@mhegazy what you recommend?

**Comment by andy-ms** [comment]
The error message is correct: `"foo"` is a non-module entity -- a function. It should be imported as `import foo = require("foo")`. And @vvakame is correct that you shouldn't need the `declare module "foo"` wrapper, since the location of the types (`node_modules/@types/foo/index.d.ts`) already determines the module being declared.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
