### ISSUE TITLE
React-MDL typings not compatible with TypeScript 2.0

### ISSUE THREAD

**Issue by nickzelei** [DefinitelyTyped/DefinitelyTyped#12419]
- [x] I tried using the latest `react-mdl/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `react-mdl/index.d.ts`.
  - The authors of that type definition are cc/ @RyanCavanaugh 

I upgraded to TypeScript 2.0 and suddenly these type definitions no longer work anymore.

A case being the <Cell /> Component does not have the "offset" prop defined for it anywhere.
A few other components do not have the inherited property "className".

You can see the full list by trying to compile any project that is using React-MDL under TypeScript 2.0.

How was this not an issue in TS 1.8?

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
