### ISSUE TITLE
socket.io-client: make SocketIOClient asccessible externally

### ISSUE THREAD

**Issue by wclr** [DefinitelyTyped/DefinitelyTyped#12432]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/socket.io-client/index.d.ts

Is it possible to make it exported and externally accessible interfaces of namespace `SocketIOClient` (`SocketIOClient.Socket`, `SocketIOClient.ConnectOpts`)?

cc @RyanCavanaugh

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by whitecolor** [comment]
I'm not sure how to implement this correctly.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
