### ISSUE TITLE
Type for default value in linq.d.ts for ElementAtOrDefault, FirstOrDefault, LastOrDefault and SingleOrDefault

### ISSUE THREAD

**Issue by jonas-k** [DefinitelyTyped/DefinitelyTyped#12436]
I want to talk about `linq/linq.d.ts`

With the introduction of strict null checks in Typescript 2.0 it is not possible anymore to use null or undefined as default value for the functions ElementAtOrDefault, FirstOrDefault, LastOrDefault and SingleOrDefault if the type of the enumerable does not contain null or undefined.
I suggest to rewrite the definitions as follows: (this is compatible to what the js code does)

ElementAtOrDefault(index: number, defaultValue: T): T;
=> ElementAtOrDefault<U>(index: number, defaultValue: U): T | U;

FirstOrDefault(defaultValue: T, predicate?: ($: T) => boolean): T;
=> FirstOrDefault<U>(defaultValue: U, predicate?: ($: T) => boolean): T | U;

...

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
