### ISSUE TITLE
Hapijs version update

### ISSUE THREAD

**Issue by basharov** [DefinitelyTyped/DefinitelyTyped#12450]
- [x] I want to talk about `hapi/hapi.d.ts`.
 I saw in comment of the file that it's for v 13.0.0 though the latest is 15.2 and I suppose the original comment even though it can be not for the latest version, but probably not for 13.0 too.

Should it be updated to reflect the latest changes in the typings file?

**Comment by TonyPythoneer** [comment]
@basharov If you found it's not latest, please send PR. :smile:

**Comment by AJamesPhillips** [comment]
I looked back through the commit history.  I didn't look at the hapi changelog for v12 to v13 but it was certain that v12 was when the major work was done so in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16065 this is the code in the v12 directory.
The v16 directory contains all the efforts since Jason Swearingen v12 commit 918608a5e007d925f4f60a275881057f07c12619
And the index.d.ts for 16.1 contains all the up to date definitions for v16.1 (as far as I can tell so far) but if you could check and submit any changes to #16065 before it's merged that'd obviously be useful.

**Comment by AJamesPhillips** [comment]
@basharov @andy-ms we can close this now #16065 has merged 👍
