### ISSUE TITLE
node_fetch uses dom-specific typings

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#12455]
- [X] I tried using the latest `node-fetch/index.d.ts` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] I want to talk about `node-fetch/index.d.ts`.
  - The authors of that type definition are cc/ @torstenwerner

It defines a method `blob(): Promise<Blob>;` on `class Body`.
`Blob` is a type specific to the "dom" library option. It's not available if just using `es2016` typings.
In addition, this method does not seem to be [implemented](https://github.com/bitinn/node-fetch/blob/master/lib/body.js).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
