### ISSUE TITLE
`sinon` is not recognized as a valid variable

### ISSUE THREAD

**Issue by ipeychev** [DefinitelyTyped/DefinitelyTyped#12478]
- I want to talk about `sinon/sinon.d.ts`.
- The authors of that type definition are cc/ @pleerock

Hello,

I'm new to Angular2 and using sinon with TypeScript, so please bear with me.

I have an Angular2 project and I would like to use Sinon there. In package.json I have "@types/sinon": "1.16.31". I'm also using `karma-sinon`.

The problem is that neither `sinon` nor `Sinon` are recognized as valid variables in Visual Studio Code. However, adding a spy using `sinon.spy` works fine - the problem is that sinon is not recognized as variable and I have plenty of compile errors in the console.
I tried many ways to solve the issue. I tried to import `Sinon`, but it cannot be imported from 'sinon' module, neither `sinon`. In the same time, `SinonSpy` **can** be imported -  `import { SinonSpy } from 'sinon';` works fine, but not `import { Sinon } from 'sinon'` or `import { sinon } from 'sinon'`.

If I do `import * as sinon from 'sinon'` then Visual Studio recognizes it, but then in the browser, which runs the test I get an exception.

How in general sinon should be used? Is it `Sinon.spy(...)` or `sinon.spy(...)`?

Here is how I'm using it right now:
```javascript
let login: SinonSpy = sinon.spy(userActions, 'login');
```

This works fine in the browser, but Visual Studio Code does not recognize sinon as a valid variable.

Thanks,

**Comment by andy-ms** [comment]
#12490 should fix the casing problem.
As for importing it, you should use `import sinon = require("sinon")` instead of `import { sinon } from "sinon"`.

**Comment by fatso83** [comment]
This should be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
