### ISSUE TITLE
Occurring Error Installing Multiple Type Declarations

### ISSUE THREAD

**Issue by almazorajan** [DefinitelyTyped/DefinitelyTyped#12487]
I've installed toastr and sweetalert today. and when I'm about to run it, multiple errors were detected in the jquery part of type declarations. 'Multiple identifiers', 'Duplicate export = '. Kindly let me know if this is valid.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
