### ISSUE TITLE
`react-addons-update` has no default export

### ISSUE THREAD

**Issue by odensc** [DefinitelyTyped/DefinitelyTyped#12509]
- [x] I tried using the latest `react-addons-update/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

When using the `react-addons-update` typings, I get the following error:
```js
Module '"[...]/node_modules/@types/react-addons-update/index"' has no default export.
```

If I change in the definition file:
```js
export = React.__Addons.update;

to

export default React.__Addons.update;
```

It works fine.

The syntax I am using to import is `import update from "react-addons-update"`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
