### ISSUE TITLE
Stripe definitions are actually stripejs definitions

### ISSUE THREAD

**Issue by pleerock** [DefinitelyTyped/DefinitelyTyped#12515]
I tried using the latest `stripe/stripe.d.ts` file in this repo and had problems.
  - The authors of that type definition are cc/ @ahi @borisyankov @longzheng @ianschmitz @a904guy @amritk 

What we have there are in stripe definitions are actually types of the stripejs, not stripe node module itself. This lead to confusion and unusability when using stripe on the backend. Solution is either to rename stripe to stripejs (but this may be a problem if someone push a stripejs module with completely different implementation. Another solution is to keep it as it is and include backend stripe's typings into this package itself

**Comment by bryanerayner** [comment]
It would be fantastic if this could be resolved soon. Presently in my own projects using Stripe, I'm having to write .d.ts files by hand... not the most enjoyable experience.

Can we get a consensus from the authors of stripejs and resolve the issue?

**Comment by pleerock** [comment]
If you really need this, then most probably you have to do it on your own, make a proposal, confirm it from main contributors and implement it.

**Comment by amritk** [comment]
I believe this was already done, is this what you were talking about?

**Comment by galuszkak** [comment]
I think like @amritk that this is done.

This issue should be closed. There are `@types/stripe-v2` `@types/stripe-v3` and `@types/stripe-node` . Two first are client side libraries and last one is for NodeJS. Feel free to @pleerock @bryanerayner ask if this isn't clear 👍 .

**Comment by LinusU** [comment]
Isn't this super confusing?

Shouldn't the name correspond with the name of the npm package? I just installed `@types/stripe` since I had installed the `stripe`-package from npm, and then the definitions didn't work because they where for the wrong package.

Shouldn't the server name be `@types/stripe` and the client name be `@types/stripejs`?

**Comment by galuszkak** [comment]
@LinusU It isn't on npm like Google Maps JS client. This is external script that You just include in your HTML or load async from their CDN.

**Comment by SimonSchick** [comment]
@galuszkak can you elaborate how to make tsc load `stripe-node` typings for `stripe` I cannot get it work locally.

**Comment by LinusU** [comment]
I'm having the same use case as @SimonSchick, I have installed `stripe` from npm and I just want to get the typings for it. I feel that I should be able to do `npm install @types/stripe` and for me the fact that it installs typings for something else is a bug...

Would renaming `@types/stripe` to `@types/stripe.js` and `@types/stripe-node` to `@types/stripe` be acceptable?

**Comment by amritk** [comment]
Actually, it would make more sense to rename the npm package from stripe to stripe-node as it points to the github stripe-node repository:
https://github.com/stripe/stripe-node

I think the best solution would be to get the types included in that repo.

**Comment by SimonSchick** [comment]
@amrikt I'd disagree, renaming the actual package would affect more consumers than renaming the typings.

Also a workaround is this:


```
{
  "compilerOptions": {
    ...
    "baseUrl": "./",
    "paths": {
      "stripe": [
        "node_modules/@types/stripe-node"
      ]
    },
  },
}

```

**Comment by galuszkak** [comment]
@LinusU You are wrong. Now there is `@types/stripe-v3` for Stripe.js API v3 `@types/stripe-v2` for Stripe.js API V2. For Stripe in Node.JS there is `@types/stripe-node`. I think it's clear seperation. `@types/stripe` it's older version, You shouldn't use it and should be discourage from it.

**Comment by SimonSchick** [comment]
@galuszkak the problem is there also is a `stripe-node` package and TS doesn't resolve stuff correctly without the fix I mentioned above, it's generally really confusing and frustrating to deal with.

**Comment by galuszkak** [comment]
@SimonSchick I probably don't understand You are using in one project frontend and backend Stripe? Is that Your case?

**Comment by SimonSchick** [comment]
No, I installed `stripe` via npm, installed `node-stripe`, and TS was complaining that it couldn't find typings for `stripe` until I added my fix from above.

**Comment by galuszkak** [comment]
Still not following @SimonSchick. Those are 2 different NodeJS packages. Why You need both of those? `stripe` is official package released by Stripe company.

**Comment by galuszkak** [comment]
@SimonSchick for `stripe` package you should use `@types/stripe-node` so per my understanding You have something wrong, because for me it works out of box If I have both packages installed. Can You share some failing example with minimal configuration?

**Comment by LinusU** [comment]
> I think it's clear seperation.

I think that the problem is that there was no way for me to know about this without digging thru the issue tracker here. Every other type package is named the same as the npm counterpart, which makes it just work out of the box.

> Those are 2 different NodeJS packages. Why You need both of those? stripe is official package released by Stripe company.

I think that @SimonSchick was running `npm install stripe @types/stripe-node`. 

-----

For me the big issue is this: **how am I supposed to know that I should install `@types/stripe-node`?**

The compiler even tells me to install `@types/stripe`:

> error TS7016: Could not find a declaration file for module 'stripe'. 'node_modules/stripe/lib/stripe.js' implicitly has an 'any' type.
  Try `npm install @types/stripe` if it exists or add a new declaration (.d.ts) file containing `declare module 'stripe';`

**Comment by LinusU** [comment]
> Actually, it would make more sense to rename the npm package from stripe to stripe-node as it points to the github stripe-node repository

@amritk I don't think that getting other package maintainers to change their name is the way to move the DefinitelyTyped project forward.

There is nothing that says that you have to have the same name of your github repository and your npm package. In fact, you don't even need to have a github repo at all to back your npm package.

The repository is named `stripe-node` because they are maintaining packages for multiple platforms. They also have `stripe-ios`, `stripe-go`, `stripe-ruby`, `stripe-dotnet`, `stripe-php`, etc. Do you really think that the stripe package in the ruby package manager should be called `stripe-ruby`, or that the composer package for stripe should be called `stripe-php`, the NuGet package `stripe-dotnet`, and so on?
