### ISSUE TITLE
d3-box and d3-slider need to be upgraded for types-2.0

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#12538]
- [X] I want to talk about `d3-box` and `d3-slider`.
  - The authors of that type definition are cc/ @lk-chen

These two packages are currently lacking a `tsconfig.json`. They seem to be trying to augment the `d3` namespace, but `d3` is now a module. What should be done with these?

CC @tomwanzek

**Comment by tomwanzek** [comment]
@andy-ms thanks for cc-ing me. `d3-box` and `d3.slider` are not part of D3 version 4, i.e. they are not modules within the canon of D3.

Having had a quick glance at them, it seems they are using D3 v3.x. So, I would suggest, the same approach we found to work with other legacy dependencies  on D3 v3.x be applied.

I.e.:
(1) Add a `package.json` stub:
```
{
  "dependencies": {
    "@types/d3": "^3.5.36"
  }
}
```
(2) Add a `tsconfig.json`:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": true,
        "strictNullChecks": false,
        "noEmit": true,
        "forceConsistentCasingInFileNames": true
    },
    "files": [
        "d3.slider.d.ts",
        "d3.slider-tests.ts"
    ]
}
```
Adjusting the file names as necessary for the treated definitions/tests.

(3) Change`/// <reference path="../d3/d3.d.ts"/>` to `///<reference types="d3" />` in the definition file

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
