### ISSUE TITLE
dataTables: [ts] Property 'DataTable' does not exist on type 'JQuery'.

### ISSUE THREAD

**Issue by neilyoung** [DefinitelyTyped/DefinitelyTyped#12576]
---removed--

**Comment by pbarranis** [comment]
I was dealing with precisely the same error in the title of this issue and was disappointed to see no one had commented on the fix.  Obviously it's not a problem with the code in this module, but hey, a note about how it was fixed would be helpful!

It turned out the solution, for me, was getting the `import` statement to be correct.  What was needed was:
`import 'DataTables.net';`

I'm new to TypeScript, so this took a little time to figure out.  Why does it look strange?  Go to https://www.typescriptlang.org/docs/handbook/modules.html and look for the heading **Import a module for side-effects only**.  HTH someone else in the future...

**Comment by agap2-ag** [comment]
If you simply need to get over it for testing purposes, just extend the JQuery object:

    const $dt: JQuery &  {DataTable?: any} = $('#my-table-id'); // DataTable is an optional property
    $dt.DataTable();
