### ISSUE TITLE
_debugger package

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#12585]
- [X] I want to talk about `_debugger/index.d.ts`.
  - The authors of that type definition are cc/ @basarat

* Could this be integrated into the "node" package?
* Where is the "_debugger" module documented? Does the underscore mean it's meant to be private? I didn't find any mention of it here: https://nodejs.org/api/debugger.html

**Comment by basarat** [comment]
> Where is the "_debugger" module documented

Not documented. Best see source : https://github.com/nodejs/node/blob/103858e95f07894fa391b09c5331c7f81b123bb2/lib/_debugger.js

Fun fact. All the nodejs source `lib` files are requireable :heart:

> Does the underscore mean it's meant to be private

Yes. Its what nodes own `debug` command uses.

> Could this be integrated into the "node" package?

Because of lack of documentation probably not. We refuse undocumented stuff in definitions of super famous stuff like jquery. Same should apply for any undocumented but desirable behaviour into node. Nonetheless was too useful to not host here :rose:

**Comment by andy-ms** [comment]
Looks like this will have to be renamed. Microsoft/types-publisher#185

**Comment by basarat** [comment]
@DefinitelyTyped/contributors can we make an exception for `_debugger` to add it to `node.d.ts` or should we delete this package? 

Its needed for anyone and everyone who wants to work with nodejs debugging

**Comment by mhegazy** [comment]
Why is this need for a separate package, and not in "node\index.d.ts"? it is a built in module, is not it?

**Comment by basarat** [comment]
@mhegazy the only reason is that its undocumented stuff which we try not to add in popular libraries. So I added it externally. That was fine at the time cause people could do `tsd install _debugger`. Personally I am fine with both options: getting completely removed or moved into node/index.d.ts :rose:

**Comment by vvakame** [comment]
sorry for late. I vote 👍 to add `_debugger` to `index.d.ts`.

**Comment by basarat** [comment]
Alright. Move to index.d.ts from my side too 🌹👍🏻😊
