### ISSUE TITLE
react-bootstrap: Where is Navbar.Form?

### ISSUE THREAD

**Issue by mayerwin** [DefinitelyTyped/DefinitelyTyped#12600]
- [x ] I tried using the latest `react-bootstrap/react-bootstrap.d.ts` file in this repo and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x] I want to talk about `react-bootstrap/react-bootstrap.d.ts`.
- The authors of that type definition are not accessible with @ (Walker Burgin <https://github.com/>, Vincent Siao <https://github.com/vsiao>, Danilo Barros <https://github.com/danilojrr>, Batbold Gansukh <https://github.com/Batbold-Gansukh>).

I cannot get this (from the doc) to compile as it complains `Navbar.Form` is missing:

```
const navbarInstance = (
  <Navbar>
    <Navbar.Header>
      <Navbar.Brand>
        <a href="#">Brand</a>
      </Navbar.Brand>
      <Navbar.Toggle />
    </Navbar.Header>
    <Navbar.Collapse>
      <Navbar.Form pullLeft>
        <FormGroup>
          <FormControl type="text" placeholder="Search" />
        </FormGroup>
        {' '}
        <Button type="submit">Submit</Button>
      </Navbar.Form>
    </Navbar.Collapse>
  </Navbar>
);

ReactDOM.render(navbarInstance, mountNode);

```

**Comment by vvakame** [comment]
We can't get response from author. please ping me after 3 days. I'll merge this PR.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by mayerwin** [comment]
Sorry, I am not familiar enough with typings definition and react-bootstrap yet to prepare a PR I would feel confident pushing.

**Comment by tomffee** [comment]
`Navbar.Text` is also not defined

**Comment by JoshuaRamirez** [comment]
Hmm, any updates on this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
