### ISSUE TITLE
Improve Travis check process duration for types 2.0 branch

### ISSUE THREAD

**Issue by JimiC** [DefinitelyTyped/DefinitelyTyped#12625]
Currently `Travis` process duration for checking each PR is ~2h. Many builds fail because the process times out.

I have noticed that the build process is done with the flag `--all`, doing checks for all types.
The branch `master`, on the contrary, builds with flag `--changes`, that detects only the changes to the repo.

Could `types-2.0` also be done with flag `--changes`, to speed up the process?

**Comment by vvakame** [comment]
cc/ @RyanCavanaugh @andy-ms @mhegazy

**Comment by vvakame** [comment]
I think [definition-tester](https://github.com/DefinitelyTyped/definition-tester/) is not supported the composition of the `types-2.0` branch.
Microsoft team is working on [2.0](https://github.com/DefinitelyTyped/definition-tester/commits/2.0) branch on definition-tester repository I guess.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
