### ISSUE TITLE
Lodash missing flatMapDeep

### ISSUE THREAD

**Issue by srolel** [DefinitelyTyped/DefinitelyTyped#12643]
- [x] I tried using the latest `lodash/index.d.ts` file in this repo and had problems.

**Comment by TonyPythoneer** [comment]
@Mosho1 Is it `types-2.0`?

**Comment by Mosho1** [comment]
It's what gets installed with `@types`. I just checked and it's not in `types-2.0` either regardless.

**Comment by TonyPythoneer** [comment]
`@types` is from `types-2.0` branch. 
If you have any question, you can tag authors.

**Comment by vasspilka** [comment]
:+1:

**Comment by vasspilka** [comment]
+1

**Comment by aj-r** [comment]
This is fixed now. Duplicated by #14168.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
