### ISSUE TITLE
webpack-env.d.ts does not declare process

### ISSUE THREAD

**Issue by kube** [DefinitelyTyped/DefinitelyTyped#12646]
@use-strict

webpack-env.d.ts does not declare `process` as a global variable, so you cannot check:

```ts
if (process.env.NODE_ENV === 'production') {
  // ...
}
```

As `node.d.ts` collides with `webpack-env.d.ts` maybe `process` declaration should be added?

I added a declaration in my own `webpack-env.d.ts`, I'm not sure it's the good way though:
```ts
interface NodeProcess {
    env: {
        NODE_ENV: string,
        [name: string]: string
    }
}
```

And at the end of the file:
```ts
declare var process: __WebpackModuleApi.NodeProcess
```

Would this be accepted as a pull request, or is there a better way to do this?

**Comment by use-strict** [comment]
I can see that by default Webpack only defines process.env as an empty object. What usually happens is that you use the `DefinePlugin` to add `process.env.NODE_ENV` string to be replaced at build time. I assume this is what you are doing.

If the above is correct, the right place to add your definition would be the scope of your project. At most, we could add in `wepback-env.d.ts` what Webpack exposes by default, without custom configuration:
e.g.
```
interface NodeProcess {
    browser: true;
    env: {};
}
```

There are also some methods that are replaced by Webpack with `noop`, so I don't know if it makes any sense to add those too.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
