### ISSUE TITLE
core-js: Split into standard and non-standard definitions

### ISSUE THREAD

**Issue by avonwyss** [DefinitelyTyped/DefinitelyTyped#12694]
- [X] I want to talk about `core-js/core-js.d.ts`.
  - The authors of that type definition are @rbuckton

I use the "shim only" part of core-js. Unfortunately some non-standard part of the the full definitions conflict with some other definitions I have, and in general I'd prefer only to have definitions for the parts I use.

Wouldn't it make sense to split the definitions into standard and non-standard, so that one can chose what he wants without getting conflicts (e.g. ES5 target with default core-js => both standard and non-standard definitions, ES5 with shim-only => only standard definitions, ES6 with core-js => only non-standard definitions as TS will already include the compiler-provided ES6 definitions).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
