### ISSUE TITLE
angular-local-storage should be updated

### ISSUE THREAD

**Issue by krzepa** [DefinitelyTyped/DefinitelyTyped#12742]
angular-local-storage/angular-local-storage.d.ts
the latest version 5.0.x of angular local storage allows to specify to which type of storage save data so set and get method should be changed accordingly e.g.
    set<T>(key: string, value: T, storageType?:string): boolean;
    get<T>(key: string, storageType?:string): T;

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by amariniello** [comment]
Would like to help..but a bit of a newbie on github (pull request etc.)
i added these definitions to update my local enviroment

declare namespace angular.local.storage {

    type StorageType = 'localStorage' | 'sessionStorage';

    interface ILocalStorageService {
      
        set<T>(key: string, value: T, storageType?: StorageType): boolean;

        get<T>(key: string, storageType?: StorageType): T;

        keys(storageType?: StorageType): string[];

        clearAll(regularExpression?: RegExp, storageType?: StorageType): boolean;

        bind(scope: angular.IScope, property: string, value?: any, key?: string, storageType?: StorageType): Function;

        length(storageType?: StorageType): number;
    }
}

**Comment by krzepa** [comment]
I've just created pull request https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16047

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
