### ISSUE TITLE
knockout.kogrid: "kg" module

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#12764]
- [X] I want to talk about `knockout.kogrid/index.d.ts`.
  - The authors of that type definition are cc/ @huer12 @davhdavh 

This does `declare module "kg"`. But `npm info kg` is an entirely different package. Does a "kg" module really exist? I can't it; the library seems to only define globals.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
