### ISSUE TITLE
Issue with pnantomjs

### ISSUE THREAD

**Issue by Alessar** [DefinitelyTyped/DefinitelyTyped#12775]
- [x] I want to talk about `phantomjs/phantomjs.d.ts`
- [x] I used latest type definitions for PhantomJS v1.9.0 API
- [x] I used phantomjs 2.0.0 and 2.1.1
```
fileSystem.write(filename, "text", "w");
```
If filename equals `undefined` or `null` in that simple code, phantomjs enters in loop and nothing else can be done after that (only Ctrl+C).
I checked native test in phantomjs repo, and all checks with `undefined` or `null` filename were done correctly and phantomjs said about errors and works after it without strange behavior.
So I suppose that some transformation between libraries can work uncorrectly.

P.S. Workaround is to check filename before invoke, but behavior of phantomjs is very strange.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
