### ISSUE TITLE
leaflet-label: FeatureGroup definition does not match leaflet 1.0

### ISSUE THREAD

**Issue by HarelM** [DefinitelyTyped/DefinitelyTyped#12787]
In leaflet-label.d.ts the definition for ```FeatureGroup``` extension methods should be without Generics.
Also ```IEventPowered``` and ```ClassStatic``` are no longer present in 1.0 definitions.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by HarelM** [comment]
I have no clue how to fix this, I just know that I can't work with the new definition file...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
