### ISSUE TITLE
gapi.auth2: Please add getGivenName() and getFamilyName() inside BasicProfile interface

### ISSUE THREAD

**Issue by yevheni** [DefinitelyTyped/DefinitelyTyped#12814]
Please add getGivenName() and getFamilyName() inside BasicProfile interface, as:

export interface BasicProfile {
    getId(): string;
    getName(): string;
    **_getGivenName(): string;
    getFamilyName(): string;_**
    getImageUrl(): string;
    getEmail(): string;
  }

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
