### ISSUE TITLE
node-uuid: repo has been moved.

### ISSUE THREAD

**Issue by HyunSeob** [DefinitelyTyped/DefinitelyTyped#12820]
- [x] I want to talk about `node-uuid/index.d.ts`.
  - The authors of that type definition are cc/ @jeffmay

The package has been moved to https://github.com/kelektiv/node-uuid/. but this has been not updated.

**Comment by jeffmay** [comment]
It's been a while since I've used this. Do you just want me to update the URL here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node-uuid/node-uuid.d.ts#L2

Also, feel free to make the changes you need, and I'll review them.

**Comment by HyunSeob** [comment]
OK. Let me try it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
