### ISSUE TITLE
@types/passport: Duplicate identifier 'export='.

### ISSUE THREAD

**Issue by Hongbo-Miao** [DefinitelyTyped/DefinitelyTyped#12871]
I tried using the latest `passport/passport.d.ts` file in this repo and had problems.
The authors of that type definition are cc/ @Horiuchi_H

When I use with 

```
"@types/passport": "0.2.34",
"@types/passport-local": "1.0.29",
```

I got error:

>     ERROR in [at-loader] node_modules/@types/passport-local/node_modules/@types/passport/index.d.ts:51:5
>         Duplicate identifier 'export='.
> 
>     ERROR in [at-loader] node_modules/@types/passport/index.d.ts:84:5
>         Duplicate identifier 'export='.

[This line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f5ab2df94e1aabf0fc6d783ad01c4c4671760627/passport/passport.d.ts#L86) causes the error.

It works well in @types/passport 0.2.32. The error starts from @types/passport 0.2.33, and also shows in 0.2.34

**Comment by vvakame** [comment]
cc/ @horiuchi

**Comment by horiuchi** [comment]
@Hongbo-Miao Sorry I cannot repro that error.
What version of TypeScript do you use?

My env:
```
$ tsc -v
Version 2.1.4
```

**Comment by TitaneBoy** [comment]
@horiuchi @enaeseth 

Hi guys...With the last update of `@types/passport@0.3.5` and `@types/passport-http@0.3.3`, when we execute tsc -p tsconfig.json, we got some typescript error on the index.d.ts comming from your modules.

![image](https://user-images.githubusercontent.com/15614466/32078628-9a78f182-ba75-11e7-90e3-84b0846d18a2.png)

This issue breaks unfortunetly our continuous integration. Can you please help us to fix this issue and publish a new version of these typed definition ?

Thank you in advance for your answers and help

**Comment by TitaneBoy** [comment]
@horiuchi @enaeseth 

Hi guys...With the last release of @types/passport@0.4.0, I still have the typescript error described in this issue.

![image](https://user-images.githubusercontent.com/15614466/32620184-09accecc-c54b-11e7-8b43-0070eb883ae4.png)

Can you please help us by fixing this issue ? I still can't update passport typed definition because it breaks our continuous integration because of this issue.

Thanks you very much

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
