### ISSUE TITLE
draft-js out of date

### ISSUE THREAD

**Issue by Shuumatsu** [DefinitelyTyped/DefinitelyTyped#12901]
typescript version : 2.1.10

@types/draft-js is now not compatible
 it's for 0.7.0 but the version of draft-js is now > 0.9

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by willisplummer** [comment]
i think this issue can be closed

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
