### ISSUE TITLE
Box2DWeb spelling mistake

### ISSUE THREAD

**Issue by cmann1** [DefinitelyTyped/DefinitelyTyped#12919]
File: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/36d40a63a05b5cb3413737fbdf7c9a2a26f211fd/box2d/box2dweb.d.ts
Line: 5150

**b2PullyJoint** should be **b2PulleyJoint** (the **e** is missing)

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
