### ISSUE TITLE
chart.js.d.ts has no Doughnut Chart and Pie Chart options

### ISSUE THREAD

**Issue by greatromul** [DefinitelyTyped/DefinitelyTyped#12915]
I tried using the latest `chart.js.d.ts` file in this repo and had problems. It has no [Doughnut Chart and Pie Chart options](http://www.chartjs.org/docs/#doughnut-pie-chart-chart-options). I mean options specific to Pie & Doughnut charts:

- _cutoutPercentage_
- _rotation_
- _circumference_ etc.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by DanielYKPan** [comment]
I got the same problems. It has no Doughnut Chart and Pie Chart options.
version: "@types/chart.js": "^2.4.3",

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
