### ISSUE TITLE
Box2DWeb b2PulleyJointDef missing paramter

### ISSUE THREAD

**Issue by cmann1** [DefinitelyTyped/DefinitelyTyped#12920]
File: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/36d40a63a05b5cb3413737fbdf7c9a2a26f211fd/box2d/box2dweb.d.ts
Line: 5271

The Initialize method is missing the the ratio parameter - it should be:

`
public Initialize(bA: b2Body, bB: b2Body, gaA: Box2D.Common.Math.b2Vec2, gaB: Box2D.Common.Math.b2Vec2, anchorA: Box2D.Common.Math.b2Vec2, anchorB: Box2D.Common.Math.b2Vec2, ratio:number): void;
`

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
