### ISSUE TITLE
Domready typing gives error

### ISSUE THREAD

**Issue by atrauzzi** [DefinitelyTyped/DefinitelyTyped#12935]
Domready looks like this:

```
declare function domready(callback: () => any) : void;

export = domready;
export as namespace domready;
```

Which keeps giving me the message that it has no default export. Or this:

```
error TS2497: Module '"....../node_modules/@types/domready/index"' resolves to a non-module entity and cannot be imported using this
construct.
```

**Comment by atrauzzi** [comment]
Looking into it, it would appear as though it's still banking on the old inclusion syntax: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/domready/domready-tests.ts

**Comment by vvakame** [comment]
Is this issue still happen?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
