### ISSUE TITLE
vex version 3 update

### ISSUE THREAD

**Issue by bbatliner** [DefinitelyTyped/DefinitelyTyped#12951]
Hi, I'm a maintainer over at [vex](https://github.com/HubSpot/vex). I heard that the DefinitelyTyped definitions are out of date for the latest major release of vex.

I will plan on taking a look at the definitions and submitting a PR with an update in the near future. Let me know if there's anything I should keep in mind or if someone else is better for the job.

**Comment by tivnet** [comment]
@bbatliner 

Hi Brendan, I just made a PR to add the `defaultOptions` - as an example.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16478

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
