### ISSUE TITLE
react router typings

### ISSUE THREAD

**Issue by L3V147H4N** [DefinitelyTyped/DefinitelyTyped#12980]
Error:
(214,38): error TS2314: Generic type 'HTMLAttributes<T>' requires 1 type argument(s).
(272,19): error TS2314: Generic type 'MouseEvent<T>' requires 1 type argument(s).

**Comment by vvakame** [comment]
Is this issus still happen?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
