### ISSUE TITLE
@types/gulp-util update broke my build.   there is a mismatch betwen git and npm repo.

### ISSUE THREAD

**Issue by karlhiramoto** [DefinitelyTyped/DefinitelyTyped#12997]
@paulvanbrenk  I see you did the last commit on this file.

1) This version works
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/gulp-util/index.d.ts#L14

2) A few hours ago the npm version was updated
https://www.npmjs.com/package/@types/gulp-util

My build broke:
```
node_modules/@types/gulp-util/index.d.ts(14,27): error TS2510: Base constructors must all have the same return type.
```

npm install @types/gulp-util
└── @types/gulp-util@3.0.29

```
$ head -n 14 node_modules/@types/gulp-util/index.d.ts |tail -n 1
export class File extends vinyl { }
```

**Comment by karlhiramoto** [comment]
at https://www.npmjs.com/package/@types/gulp-util  it says the current version is 0.0.0

**Comment by paulvanbrenk** [comment]
Not sure about the version mismatch.

Making the typings more robust, but adding explicit null-checks seems to have broken extending `File` which is unfortunate.

**Comment by gforceg** [comment]
This broke a cli project that I am working on. Is there some package.json magic I can do to get my compilation to work until this is resolved?

**Comment by karlhiramoto** [comment]
@gforceg  what fixed my project as setting  "@types/gulp-util": "3.0.28",

**Comment by gforceg** [comment]
@karlhiramoto Thanks! I'll try that.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
