### ISSUE TITLE
Declare member of type PouchDB

### ISSUE THREAD

**Issue by wassy92x** [DefinitelyTyped/DefinitelyTyped#12991]
- [x] I tried using the latest `pouchdb/index.d.ts` file in this repo and had problems.

I can't define a member with the type "PouchDB".
I always get the following error: `Cannot find name 'PouchDB'.`

PouchDB is imported into the file in the following way: `import PouchDB from "pouchdb";`
So, how can I create a member variable with type "PouchDB" ?
`private mDB: PouchDB;`  <-- The error gets shown in this line.

**Comment by nros** [comment]
It seems as if "PouchDB" is just a namespace. Try the following instead.

`
private mDB: PouchDB.Database<YOUR_DOCUMENT_TYPE>;
`

or a more elaborate example:

```
export type MyJSONType = {
    [propName: string]: string|number|boolean|MyJSONType;
};

export type MyPouchDBData = MyJSONType & {
    _id: string;
    _rev?: string;
};

export class DatabaseService {
    private mDB: PouchDB.Database<MyPouchDBData>;
    public DatabaseService(databaseName: string) {
        this.mDB = new PouchDB(databaseName);
    }
    // ...
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
