### ISSUE TITLE
How to install @types/xxx.d from local file

### ISSUE THREAD

**Issue by karthickthangasamy** [DefinitelyTyped/DefinitelyTyped#13001]
I can install typings file from local path using below command.

`typings install dt~jquery --save --global`

Is there any equivalent available for `@types` definition file.?

**Comment by karthickthangasamy** [comment]
is there any possibilities/update.?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
