### ISSUE TITLE
Duplicate identifier because of doubled dependencies

### ISSUE THREAD

**Issue by Tinostarn** [DefinitelyTyped/DefinitelyTyped#13011]
- [x ] I tried using the latest `materialize-css/index.d.ts` file in this repo and had problems.

Hi,

I use materialize-css and angular2-materialize directives. I couldn't use the global object `Materialize` because of `Cannot find name Materialize`. I was glad to find out the definition here so I installed it.
The problem now is that I have a lot of `Duplicate identifier` coming from the jQuery type dependency.
I inspected the directories : 
```
@types 
    materialize-css
        index.d.ts
        node_modules 
            @types 
                jquery
    pickadate 
        index.d.ts
        node_modules 
            @types 
                jquery
```

As you can see, materialize-css installs `@types/jquery`, but also `pickadate` which itself installs `@types/jquery`, leading to that `Duplicate identifier issue`.
I am on Typescript 2.0.9 and I tried to exlude the directory `node_modules/materialize-css/node_modules` but it didn't work.
Can you help me ?

Thx

**Comment by supertino7** [comment]
Any idea on how to fix this problem ? 
For now, I just created my own materialize.d.ts and copied/pasted content from the repo to my file, but it's not ideal :/

**Comment by vvakame** [comment]
I think this issue is solved alread. isn't it?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
