### ISSUE TITLE
react-bootstrap.d.ts dropdownbutton interface missing title field (node) 

### ISSUE THREAD

**Issue by darewreck54** [DefinitelyTyped/DefinitelyTyped#13031]
- [ x ] I tried using the latest `react-bootstrap/react-bootstrap.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X] I want to talk about `react-bootstrap/react-bootstrap.d.ts`.
  - The authors of that type definition are cc/ @....

Hi, 

I believe the type definition for react-bootstrap.d.ts is missing a title field for dropdownbutton.  Based on https://react-bootstrap.github.io/components.html#btn-dropdowns-props-dropdown-button  it has a title filed that is a node.

Thanks,
D

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by nostalgiaz** [comment]
@darewreck54 any news?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
