### ISSUE TITLE
ng: TS 0.9.5 and IHttpPromise error callback

### ISSUE THREAD

**Issue by georgiosd** [DefinitelyTyped/DefinitelyTyped#1303]
Two things:

a) TS 0.9.5 beta is out with several breaking changes the most important one being the restrictions around `any`. As far as I can see it means that you must add a template parameter for `$http` methods.

e.g. `post<T>(url, ...): ng.IHttpPromise<T>`

b) This makes the signature of the error callback more evident - shouldn't the type parameter for the error callback be `any`? (it's `TResult` right now) - it's not necessary that the error result is the same as the success result.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
