### ISSUE TITLE
[Request] discord.js -> discord.ts.d

### ISSUE THREAD

**Issue by nomsi** [DefinitelyTyped/DefinitelyTyped#13048]
I use the discord.js library a lot and it would be nice not to use ```typings install github:``` and move forward to the new @types-2.0 method with this library.

Currently a few of them already exist, probably could use some modifications, but, 
the one I currently use is
https://github.com/acdenisSK/discord.js-typings

I can still use typings.json with TypeScript2, though, correct?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
