### ISSUE TITLE
Need guidance for adding updated GeoJSON spec typings

### ISSUE THREAD

**Issue by JeffJacobson** [DefinitelyTyped/DefinitelyTyped#13053]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `geojson/index.d.ts`.
  - The authors of that type definition are cc/ @cobster

The GeoJSON specification was [updated in August 2016](https://tools.ietf.org/html/rfc7946) and I would like to add support for this version of this standard to DefinitelyTyped (and the `@types` on npm). I have some questions about how I should do this.

* I am assuming that I would not be overwriting the existing `geojson/*` files due to [breaking changes](https://tools.ietf.org/html/rfc7946#appendix-B) in the standard. Is that assumption correct? 
* Assuming I am not overwriting the old `geojson` type definitions, where should my updated copies go? Should they go in a new folder (called something like `geojson-2016-08` or `geojson-rfc7946`) or in a separate file inside of the existing `geojson` folder?

Changes from the previous version of the GeoJSON standard
-------------------------
* The `crc` property has been removed. WGS 84 coordinate system now always assumed.
* `id` property now supports numbers in addition to string values.
* Positions can no longer have more than three elements.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
