### ISSUE TITLE
Highcharts: "stops" options on the yAxis is missing

### ISSUE THREAD

**Issue by BrianLaughlan** [DefinitelyTyped/DefinitelyTyped#13066]
In [Highcharts ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/highcharts/highcharts.d.ts).... "stops" on the yAxis for the **solid gauge chart** is missing from the .d.ts... 

![image](https://cloud.githubusercontent.com/assets/8556999/20835156/5561f1c2-b899-11e6-9e2c-40d4341cc40d.png)

http://api.highcharts.com/highcharts/yAxis.stops

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
