### ISSUE TITLE
Information request to write typings for @types

### ISSUE THREAD

**Issue by danfma** [DefinitelyTyped/DefinitelyTyped#13117]
I want to contribute with a definition library for `react-router 4.0.0-alpha.6`, but I need some information. I read the contribution guide, but maybe it needs an update to work with the new @types.

1. I will create a definition for the `react-router@4.0.0-alpha.6`, but we already have a react-router definition. By following the contribution guide, I should rename the current definitions to `react-router-2.0.0.d.ts` and then create a new as `react-router.d.ts`, but that could be a problem, because I'm creating a definition for a future version of the library, not the stable one. How to proceed?

2. The `react-router` has a dependency for the library `history`. How can I express that in my definition? Will the `/// <reference types="history" />` be enough? I'm asking because the vscode don't resolve that.

Maybe we should create another path structure like a subdirectory with the version like `react-router/4.0.0-alpha.6/typings.d.ts` or simple, at the root, `react-router-4.0.0-alpha.6/typings.d.ts`, but the can cause problems because of the great number of libraries published today.

**Comment by andy-ms** [comment]
Might have to wait on Microsoft/types-publisher#3.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
