### ISSUE TITLE
event-stream return type change prevents code from compiling

### ISSUE THREAD

**Issue by eppsilon** [DefinitelyTyped/DefinitelyTyped#13124]
Commit https://github.com/DefinitelyTyped/DefinitelyTyped/commit/fb6858d70a9dae58336cfd2d47a23af873ed777a causes the issue.

I have some code that uses `event-stream` to merge some streams that TS has inferred are `NodeJS.ReadWriteStream`s. That type extends `stream.Stream`, so it compiled fine. The change linked above has changed the return types to `MapStream` - which extends `stream.Stream` but not `NodeJS.ReadWriteStream`.

cc @Penryn @andy-ms

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
