### ISSUE TITLE
TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by soupman99** [DefinitelyTyped/DefinitelyTyped#13135]
I've installed `socket.io-client` & `@types/socket.io-client`

But I get this error:
`TypeError: Cannot read property 'request' of undefined`

I'm using webpack, but don't know if that's contributing to the issue. 

**Is there an easy way to solve this?**

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
