### ISSUE TITLE
Highstock (highscharts) types not working

### ISSUE THREAD

**Issue by Skuriles** [DefinitelyTyped/DefinitelyTyped#13232]
- [ x] I tried using the latest `highcharts/index.d.ts` file in this repo and had problems.
- [ ] I want to talk about `highcharts/highstock.d.ts`.

I'm using the highstocks module from highcharts, but the compiler throws errors
`import * as Highcharts from "highcharts/highstock"` 
Compiler Error:
`Property 'StockChart' does not exist on type 'typeof "foo/node_modules/@types/highcharts/highstock"`

For me it looks like, that typescript is using @types/highcharts/highstock/index.d.ts which does not exist and the default index.d.ts from node_modules/@types/highcharts does not have a property "StockChart" either. 
For testing I've added the Property StockChart to the Static interface in index.d.ts, this would work if use systemJs to import highstock.js instead highcharts.js and so the compiler uses index.d.ts to get the types. 

So how can I make the compiler to use the highstock.d.ts file instead of index.d.ts to prevent compile errors?

See [C12437](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12437#issuecomment-266022952) (last entries) as reference

**Comment by andy-ms** [comment]
`highstock.d.ts` currently doesn't define any exports, so that explains your compile error if you try getting the `StockChart` property from it. It sounds like you expect there to exist a `"highcharts/highstock"` module with importable values. Is this how the library works at runtime? If so, `highstock.d.ts` should be modified to define some exports. (Being vague here because I'm not at all familiar with the library.)

CC @damianog @DavidKDeutsch @baltie

**Comment by Skuriles** [comment]
The lib is splitted in highcharts and highstocks (highstocks full includes highcharts). 
In the @types files form highcharts it is nearly the same. 
The index.d.ts has types for highcharts, the highstock.d.ts extends the types for higcharts and has some own new properties

@andy-ms -> so you are right. 
To use highstock you have to include highcharts/highstock module and according to this there should be a highcharts/highstock module definition in highstock.d.ts

**Comment by Skuriles** [comment]
Any update in pipeline or more info needed?

**Comment by andy-ms** [comment]
You could make a PR yourself. Could be as simple as adding:

```ts
export = __Highstock;
export as namespace Highstock;
```

(might be a good time to get rid of the `__` in `__Highstock` too.) Be sure to test it with your real code: [here's how](https://github.com/DefinitelyTyped/DefinitelyTyped#test-a-new-package).

**Comment by Skuriles** [comment]
Ok... I will check your link and the whole PR stuff as soon as I have more time (maybe tomorrow)

A quick test with my app did the trick with the following code in highstock.d.ts:
 `declare var Highstock: __Highstock.Static;
export = Highstock;
export as namespace Highstock;`

and in my TS file you can use it like this:
`import * as Highstock from "highcharts/highstock";`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
