### ISSUE TITLE
Sequelize.Instance<TAttributes> .set, .setAttributes and .update are not typesafe

### ISSUE THREAD

**Issue by iH8c0ff33** [DefinitelyTyped/DefinitelyTyped#13253]
- [x] I want to talk about `sequelize/index.d.ts` on branch types-2.0.
  - The authors of that type definition are cc/ @samuelneff @codeanimal @drinchev....

I fixed this using latest (Typescript `2.1`) features on my project, and would like to contribute making my work usable by others. (PR is coming)

**Comment by drinchev** [comment]
Hey I checked the PR, but I don't know why the tests fail. Frankly, I don't use `TS 2.1`, so it will break my code.

However, I think it's a good improvement if we can write the additional tests on that.

**Comment by iH8c0ff33** [comment]
@drinchev if I understand correctly the problem seems related to the test itself not compiling correctly

**Comment by drinchev** [comment]
Yep. Tests needs to be fixed before this is merged.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
