### ISSUE TITLE
conflict between node & tsmonad typings

### ISSUE THREAD

**Issue by emmanueltouzery** [DefinitelyTyped/DefinitelyTyped#13250]
- I tried using the latest tsmonad-0.0.29 & node-0.0.2 files and had problems.
- I tried using the latest stable version of tsc. (2.1.4)
  - The authors of that type definition are cc/ @ValentinTrinque and @vvakame 

When combining both type definitions, I get a conflict =>

    node_modules/tsmonad/dist/tsmonad.d.ts(670,13): error TS2403: Subsequent variable declarations must have the same type.
    Variable 'module' must be of type 'NodeModule', but here has type '{ exports: any; require(id: string): any; id: string; filename: string; loaded: boolean; parent: ...'.

I also opened a bug on the tsmonad repo, the library ships a .d.ts and it has the same issue => https://github.com/cbowdon/TsMonad/issues/28

**Comment by andy-ms** [comment]
Related: #13378

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
