### ISSUE TITLE
Victory type definitions are incomplete

### ISSUE THREAD

**Issue by atroy** [DefinitelyTyped/DefinitelyTyped#13292]
- [x] I tried using the latest `victory/victory.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `victory/victory.d.ts`.
  - The authors of that type definition are cc/ @andy-ms @asvetliakov 

It seems that the definition is missing the VictoryTooltip, everything else just works fine. As I am new to this chart lib it could also be the fact that this lib targeting 0.9.0 current version is 0.14.1.

**Comment by andy-ms** [comment]
You could always make a [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute).

**Comment by asvetliakov** [comment]
@atroy 
The definition was written for victory 0.9.0
I'm going to update victory definition in further weeks, but you can go forward and send PR

**Comment by andy-ms** [comment]
> Also, does anyone know a workaround to use even if the type definitions are not present in the typings file?

You could use [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) ... or better, make a pull request here fixing it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
