### ISSUE TITLE
NodeJS wrong definition for Socket

### ISSUE THREAD

**Issue by microshine** [DefinitelyTyped/DefinitelyTyped#13307]
- [x] I tried using the latest `node/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `node/index.d.ts`.

`Socket` is declared as Interface in nodejs module `dgram`, but it's specified as `class` in nodejs [documentation](https://nodejs.org/api/dgram.html#dgram_class_dgram_socket). I can't create my own class which extends `Socket`

**Comment by microshine** [comment]
I resolve this problem with this
```typescript
import { Socket } from "dgram";
let SocketClass: SocketContructor = require("dgram").Socket;

interface SocketContructor {
    new (type: string): Socket;
}

export class DHCPServer extends SocketClass {
}
```

But it's not pretty )

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
