### ISSUE TITLE
showdown/showdown.d.ts missing setFlavor

### ISSUE THREAD

**Issue by mmc41** [DefinitelyTyped/DefinitelyTyped#13302]
- [x ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

@cbowdon @tan9 DefinitelyTyped/showdown/showdown.d.ts is missing the setFlavor methods documented on https://github.com/showdownjs/showdown

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by liammann** [comment]
Hey,
I've submit a pull request to fix this - #15015 

Thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
