### ISSUE TITLE
Angular/Angular-Resource/Lodash TS1316 errors 'TS1316:Global module exports may only appear at top level' after update last version.

### ISSUE THREAD

**Issue by spat-ne-hochu** [DefinitelyTyped/DefinitelyTyped#13338]
Today angular.d.ts, angular-resource.d.ts, lodash.d.ts update
WTF?

![1234](https://cloud.githubusercontent.com/assets/7813784/21180443/173ac566-c20a-11e6-8b5d-8b4fa211aed6.png)

**Comment by deinok** [comment]
same

**Comment by bwestlin** [comment]
Same here too

**Comment by foke** [comment]
same here

**Comment by kyosik** [comment]
Same...

**Comment by Wykks** [comment]
Probably related to https://github.com/Microsoft/TypeScript/issues/10178

**Comment by beheh** [comment]
This is due to #13280 and the switch to types-2.0.

**Comment by scopsy** [comment]
Same here

**Comment by jmaicaaan** [comment]
Same

**Comment by Heartz66** [comment]
Same

**Comment by caiwan** [comment]
Same.

**Comment by shrisggs** [comment]
same

**Comment by vbartari** [comment]
Can anyone please post the exact solution here?

**Comment by ehartford** [comment]
halp

**Comment by ashmna** [comment]
same

**Comment by Nostrus** [comment]
I finally managed to solve this today with the help of this [article.](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) As mentioned in the Typings issue:

> Typings can not install anything using "export as namespace"

And this is true for the angular definitions. So instead of typings I used npm to install the angular definitions:

`npm install @types/angular --save`

to resolve the dependency issue, I installed typescript, too (might not be required):

`npm install typescript`

Finally I added 

`import * as angular from "angular";`  

at the top of my file, below the already existing
 
`/// <reference path="../../typings/index.d.ts" />` reference.

**Comment by Wykks** [comment]
Best solution I found so far, which does not force do put an `import * as angular from 'angular' ` everywhere :
(warning: @ types only !)
Create a new file `globals.d.ts`
```
import * as _angular from 'angular';
declare global {
  const angular: typeof _angular;
}
```
Then add 
```
/// <reference path="./globals.d.ts" />
```
In your main entrypoint

**Comment by DanielJoyce** [comment]
This is such a mess. Some libraries are still stuck providing globals, some have umd modules. The paths between  their community provided .d.ts files and the actual file to use at run time also don't line up ( and typescript won't rewrite urls, so then you need rollup ).

So yet again I am forced to determine what stupdity is needed to make TSC happy.

In my case, I am running into a similair issue with sockjs-client and its typings

I know you want to drag javascript kicking and screaming into modern times. But until that point we need to work with existing libraries. This kind of stuff needs to be spelled out in documents, maybe a section on "Fixing common module pitfalls", or a switch to tsc to "Shut up, just turn these warnings off, it will be a global at runtime"

Yet another day wasted jumping through needless hoops.

**Comment by PrestonII** [comment]
Hey @Wykks - thanks for that!

Any ideas on how would you include other angular modules like angular-route in your solution?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
