### ISSUE TITLE
mathjax types issue with ionic2

### ISSUE THREAD

**Issue by jagannathTL** [DefinitelyTyped/DefinitelyTyped#13384]
I tried using the latest "mathjax/index.d.ts" file in this repo and had problems saying its not a module
The authors of that type definition is rolandzwaga

**Comment by andy-ms** [comment]
So far as I can tell, mathjax *isn't* a module. https://github.com/mathjax/MathJax
Can you provide some working JavaScript code that TypeScript is giving incorrect compile errors for?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
