### ISSUE TITLE
Durandal interface composition.CompositionContext incorrect

### ISSUE THREAD

**Issue by chschmal** [DefinitelyTyped/DefinitelyTyped#1338]
Hi!

Please review the interface composition.CompositionContext. It seems to contain some required properties which should not be required:
Properties mode, parent, activeView, composingNewView, child are marked as required, however, they are apparently not (all) required. Also method triggerAttach() : void;
Please have a look in the durandal js files, where composition.compose() is called. There you can see, that these parameters are obviously not required for the correct function.

Moreover, interface composition.CompositionContext has a property "tranistion". This should certainly be calles "transition".

Thank you!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
