### ISSUE TITLE
highcharts - missing colorCounter

### ISSUE THREAD

**Issue by crh225** [DefinitelyTyped/DefinitelyTyped#13391]
- [X ] I tried using the latest `highcharts/index.d.ts` file in this repo and had problems.
- [X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X] I want to talk about `highcharts/index.d.ts`.
  - The authors of that type definition are cc/ @....
@damianog, @baltie
colorCounter is missing from chartObject.

see https://github.com/highcharts/highcharts/issues/6138

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
