### ISSUE TITLE
snapsvg/index.d.ts is not a module.

### ISSUE THREAD

**Issue by jbeard4** [DefinitelyTyped/DefinitelyTyped#13411]
- [x] I tried using the latest `snapsvg/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `snapsvg/index.d.ts`.
 - The authors of that type definition are cc/ @RyanCavanaugh @rakatyal @lhk

Running `tsc test.ts` produces:

```
test.ts(1,23): error TS2306: File '/Users/jbeard4/tmp/test-snapsvg/node_modules/@types/snapsvg/index.d.ts' is not a module.
```

You can find a minimal repro of what I have tried here: https://github.com/jbeard4/snapsvg-typescript-fails

For Typescript v2.1.4

**Comment by andy-ms** [comment]
The documentation doesn't mention anything it about being importable as a module. It looks like this is a global library. Your test code is:

```ts
import Snap = require('snapsvg');
var s:Snap.Paper = new Snap('#div');
```

If you ignore the compile errors, does that work at runtime?
If not, the type definition is correct, and you should instead `/// <reference types="snapsvg" />` and use the global `Snap` variable / namespace.

**Comment by jbeard4** [comment]
Yes, this is confirmed working at runtime. snapsvg can be loaded as a commonJS module, and built with browserify. When snapsvg is loaded as a commonJS module, the Snap object will be local to the module into which snapsvg is loaded; and mina is set a global variable. 

What is the best way to use TypeScript type definitions to define this behavior?

**Comment by andy-ms** [comment]
OK, here's what should be done:

* If `mina` is always global, that section (containing `function mina` and `namespace mina`) should go in a `declare global { ... }` wrapper.
* Below that should be added the lines `export = Snap;` and `export as namespace Snap;`
* Update one of the test files to use `import Snap = require("snapsvg");` instead of the global.
* Add `snapsvg-tests-2` and `snapsvg-tests-3` to `snapsvg/tsconfig.json` "files". These have some `noImplicitThis` errors; CC @lhk and @tgfjt who last worked on them. Also @DanielRosenwasser. (If you can't fix the errors now you could set `"noImplicitThis": false` in `tsconfig.json`.)
* Also delete the `/// <reference path="snapsvg.d.ts"/>` in `snapsvg-tests-3.ts`.
* If you're up to it, add `snapsvg/tslint.json` containing `{ "extends": "../tslint.json" }` and see what errors you get. (If you don't want to handle an error yet you can disable it in the `tslint.json`.)

**Comment by jbeard4** [comment]
Thank you for following up. I will make the above revisions and get back to you.

**Comment by AlexBokhankovich** [comment]
Adding
```
///<reference path="../../../../node_modules/@types/snapsvg/index.d.ts" />
import "snapsvg-cjs";
```
did the trick

Where 'snapsvg-cjs' is [this](https://www.npmjs.com/package/snapsvg-cjs)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
