### ISSUE TITLE
Missing unique(function) declaration

### ISSUE THREAD

**Issue by Csabusa** [DefinitelyTyped/DefinitelyTyped#13462]
Joi api reference says: array.unique([comparator])
But has no declaration in index.d.ts.

https://github.com/hapijs/joi/blob/v10.0.6/API.md#arrayuniquecomparator
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/joi/index.d.ts

**Comment by andy-ms** [comment]
You could make a PR adding one.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
