### ISSUE TITLE
[react-native] - TransformsStyle

### ISSUE THREAD

**Issue by jemise111** [DefinitelyTyped/DefinitelyTyped#13479]
- [x] I tried using the latest `react-native/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I want to talk about `react-native/index.d.ts`.
  - The authors of that type definition are cc/ @bgrieder

Maybe I'm missing something here but using transforms in this way:

```
<View style={{transform: [{scale: 1}]}} />
```

results in this:

```
error TS2322: Type '{ transform: [{ scale: number; }]; }' is not assignable to type 'ViewStyle'.
  Types of property 'transform' are incompatible.
    Type '[{ scale: number; }]' is not assignable to type '[{ perspective: number; }, { rotate: string; }, { rotateX: string; }, { rotateY: string; }, { rot...'.
      Types of property '0' are incompatible.
        Type '{ scale: number; }' is not assignable to type '{ perspective: number; }'.
          Object literal may only specify known properties, and 'scale' does not exist in type '{ perspective: number; }'.
```

My thinking is that this is happening because the `transform` key expects an array that contains each possible transform object when in reality only one (or more) is required.

Shouldn't the TransformsStyle interface look something like this:

```
export interface TransformsStyle {
    transform?: {[key: string]: (string | number)}[]
    ...
}
```

And ideally the key could only be one of:

```
type transformsKey = 'perspective' | 'rotate' | 'rotateX' | 'rotateY' | 'rotateZ' | 'scale' | 'scaleX' | 'scaleY' | 'translateX' | 'translateY' | 'skewX' | 'skewY';
```

But I'm not sure enforcing keys is possible.

If I'm missing something here please let me know. Any guidance would be really helpful. Thanks!!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
