### ISSUE TITLE
AmCharts.isReady type not set

### ISSUE THREAD

**Issue by jzapantis** [DefinitelyTyped/DefinitelyTyped#13473]
- [X] I tried using the latest `/amcharts/index.d.ts` file in this repo and had problems. with my angular2 component using this code:

`        if (AmCharts.isReady) {
            createChart();
        } else {
            AmCharts.ready(function () {
                createChart();
            });
        }
`

Basically:

`var isReady: boolean;` is not set. 

I add it to index.d.ts - but I thought I would share here as well.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by jzapantis** [comment]
I posted a pI'll request with the change. 

Please see the PR with the title: "added isReady: boolean handler"

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
