### ISSUE TITLE
 async.d.ts Wrong callback type for Control Flow, when used with an object instead of an array

### ISSUE THREAD

**Issue by MathieuLescure** [DefinitelyTyped/DefinitelyTyped#1347]
```
async.parallel({
    one: function (callback) { ... },
    two: function (callback) { ... }
}, function (err, results) {
    results.one
});
```

The previous code return the following error:

The property 'one' does not exist on value of type '{ one: (callback: any) => void; two: (callback: any) => void; }[]'.

Current Version:

```
...
parallel<T>(tasks: T[], callback?: AsyncMultipleResultsCallback<T>): void;
parallel<T>(tasks: T, callback?: AsyncMultipleResultsCallback<T>): void;
...
```

Suggested modification:

```
...
parallel<T>(tasks: T[], callback?: AsyncMultipleResultsCallback<T>): void;
parallel<T>(tasks: T, callback?: AsyncSingleResultCallback<T>): void;
...
```

**Comment by Penryn** [comment]
I believe this issue is worth closing--there have since been several updates to `async.d.ts`.

If you find something wrong with the async definitions, it'd be best to file a new issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
