### ISSUE TITLE
moment-timezone: How to access interface `MomentZone`?

### ISSUE THREAD

**Issue by DanielSWolf** [DefinitelyTyped/DefinitelyTyped#13483]
- [x] I tried using the latest `moment-timezone/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `moment-timezone/index.d.ts`.
  - The authors of that type definition are cc/ @RyanCavanaugh, @andy-ms, @mhegazy

[`moment-timezone/index.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/moment-timezone/index.d.ts) defines the interface `MomentZone` within the namespace `MomentTimezone`. Due to the way the exports are written, however, I don't see a way to access that interface from TypeScript code. What can I write in place of the `???` in the following code?

```
interface HasTimezone {
  timezone: ???
}
```

**Comment by andy-ms** [comment]
I've verified that `node -p 'require("moment") === require("moment-timezone")'` is `true`, so `export = moment` is correct.

Since it's not really a separate module, I think it would be better to remove `export as namespace MomentTimezone` and `declare namespace MomentTimezone` and just move it all into the `declare module "moment"` augmentation. i.e.:

```ts
declare module "moment" {
    interface MomentZone { ... }
    interface MomentTimezone { ... }
    interface Moment { ... }
    const tz: MomentTimezone;
}
```

Then you can just do either `import { MomentZone } from "moment"` or `import { MomentZone } from "moment-timezone"`.

CC @michelsalib
