### ISSUE TITLE
isomorphic-fetch typings fail to run with tslint --type-check

### ISSUE THREAD

**Issue by KnisterPeter** [DefinitelyTyped/DefinitelyTyped#13526]
- [x] I tried using the latest `isomorphic-fetch/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `isomorphic-fetch/index.d.ts`.

Hi @zhengbli,

currently when using `@types/isomorphic-fetch` with ts 2.1.x and tslint 4.x and enabled --type-check for tslint it fails with the following error:

```
xxx/source/pretend/node_modules/tslint/lib/runner.js:91
                    throw new Error(messages.join("\n"));
                    ^

Error: Error at xxx/source/pretend/node_modules/@types/isomorphic-fetch/index.d.ts:183:5: An export assignment cannot be used in a module with other exported elements.
```

**Comment by andy-ms** [comment]
It's possible that you have some other declaration of `isomorphic-fetch` conflicting with the one defined there..
Speaking of, adding linting to `isomorphic-fetch` would detect the problem that it uses `declare module "isomorphic-fetch"` rather than having exports on the top-level.
(Although, it looks like [some parts](https://github.com/matthew-andrews/isomorphic-fetch/blob/master/fetch-npm-node.js#L12) (`fetch`, `Response`, `Headers`, `Request`) need to go in a `declare global { ... }` block.)

**Comment by KnisterPeter** [comment]
Maybe I've hosed up something. I've used it in combination with omni-fetch (that was broken and is fixed now) and it all see to be okay.
Sorry.
