### ISSUE TITLE
@types/selenium-webdriver/index.d.ts should include IWebDriver declaration

### ISSUE THREAD

**Issue by yashaka** [DefinitelyTyped/DefinitelyTyped#13599]
- [ ] I want to talk about `selenium-webdriver/index.d.ts`.
  - The authors of that type definition are cc/ @BillArmstrong, @Kuniwak, @cnishina

Please, add IWebDriver interface declaration in index.d.ts 

I need it to implement a Decorator over WebDriver. I.e. create an alternative enhanced WebDriver implementation, but still compatible through IWebDriver interface.

**Comment by cnishina** [comment]
Question:

The IWebDriver and WebDriver classes are the same except IWebDriver has methods that do nothing and WebDriver is the implementation. Why not extend the existing WebDriver?

```
import {WebDriver} from 'selenium-webdriver';

class EnhancedWebDriver extends WebDriver {
```

Todo:

`class IWebdriver` is exported in 3.0.x and should be added along with other selenium-webdriver 3.0.x updates.

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/webdriver.js#L244

**Comment by yashaka** [comment]
> The IWebDriver and WebDriver classes are the same except IWebDriver has methods that do nothing and WebDriver is the implementation. Why not extend the existing WebDriver?

Because I would prefer Composition over Inheritance in this example. My "AlternativeWebDriver" probably will become much more than "IWebDriver interface declares". It sounds for me more like "has a" relationship (Composition), not "is a" (Inheritance). 

By the way, we have IWebElement in index.d.ts, so it seems to be reasonable to have IWebDriver, at least for consistency :)

**Comment by cnishina** [comment]
I'd be happy to review your PR. 😄

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
