### ISSUE TITLE
@types/node - liked to add ability to define type of process.env

### ISSUE THREAD

**Issue by breath103** [DefinitelyTyped/DefinitelyTyped#13633]
Hi. i'd like to suggest pretty straight forward feature, which is you can define type process.env by declaration merging.

which is already implemented in types/env-node, you can check it https://github.com/typings/registry/issues/770.

so that if you write
```
declare namespace NodeJS {
    export interface EnvironmentVariables {
        SOME_THING: string;
        SOME_OTHER_THING: string;
    }
}
```
then type of process.env will be updated with *EnvironmentVariables*

let me know how you guys think. i'll get this thing done if you guys think this works.

**Comment by xeoneux** [comment]
@breath103 what's the update on this? Is this implemented yet?

**Comment by xealot** [comment]
Great idea

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
