### ISSUE TITLE
@types/mongodb How about add generics to collection?

### ISSUE THREAD

**Issue by beary** [DefinitelyTyped/DefinitelyTyped#13731]
- [x] I tried using the latest `@types/mongodb.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `@types/mongodb.d.ts`.
  - The authors of that type definition are cc/ @CaselIT 

like this

```typescript
interface User {
  _id: ObjectID
  name: string
  age: number
}

MongoClient.connect('%$#&%*^%^$').then(async db => {
  let userCollection = db.collection<User>('user')
  let user = await userCollection.findOne({ name: 'Alex' })
  let users = await userCollection.find().toArray()

  // Because of generics, the ide know the type of the user is 'User',
  //and is can show the properties after I entered the '.'
  let age = user.age
  users.forEach(_user => console.log(_user.name))
})
```

I think it's useful...
thanks for your work

**Comment by CaselIT** [comment]
This would work properly only for interfaces, but I think it could be useful. 
I'll update the definitions when I have the time. If you want to add this feature, feel free to do it.

**Comment by CaselIT** [comment]
I've added the generic version. Sadly it cannot be merged without breaking existing code since typescript will complain with in a lot of `error TS2314: Generic type '...' requires 1 type argument(s).`

Until https://github.com/Microsoft/TypeScript/issues/2175 is fixed I do not think it can be merged without issues. At least I do not know any workaround 😞 

In the meantime you can install the generic version with `typings` using
```
typings i github:Think7/typings-mongodb#generics
```

**Comment by beary** [comment]
👍 good job ! thanks mate

**Comment by hinell** [comment]
Here we go.
