### ISSUE TITLE
wu/index.d.ts is unusable

### ISSUE THREAD

**Issue by sparebytes** [DefinitelyTyped/DefinitelyTyped#13791]
- [x] I tried using the latest `wu/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `wu/index.d.ts`.
  - The authors of that type definition are cc/@RyanCavanaugh 

I believe wu/index.d.ts is missing `export = wu;` at the very end. I wasn't able to use the types with TSC 2.1.4

**Comment by estaub** [comment]
Fixed in #22289 .

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
