### ISSUE TITLE
[Request] Add missing keycloak-authz.js types to existing @types/keycloak-js

### ISSUE THREAD

**Issue by askannon** [DefinitelyTyped/DefinitelyTyped#13874]
There is already a ts.d definition for the "keycloak-js" npm: @types/keycloak-js
But it only provides definitions for the "keycloak.js" file. There is however a second JS file in the "keycloak-js" npm: "keycloak-authz.js". Would be great if definitions for that could be added to the @types/keycloak-js npm as well.

Thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
