### ISSUE TITLE
Export as namespace error

### ISSUE THREAD

**Issue by HeorhiiWW** [DefinitelyTyped/DefinitelyTyped#13903]
- [ x] I tried using the latest `crypto-js/index.d.ts` file in this repo and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x] I want to talk about `crypto-js/index.d.ts`.
  - The authors of that type definition are cc/ @misak113

I have problem with index.d.ts and typescript 2.2.  It says that **export as namespace CryptoJS;**
is invalid. Removing this line solves the problem for me

**Comment by HeorhiiWW** [comment]
Sorry typescript version 2.1

**Comment by misak113** [comment]
Hi,
ok, can you push the recommended update & create Pull Request?

**Comment by mhegazy** [comment]
Can not reproduce this issue. make sure you are running on TS 2.1

```sh
c:\test>npm install @types/crypto-js
test@1.0.0 c:\test
`-- @types/crypto-js@3.1.32

c:\test>tsc --v
Version 2.1.4

c:\test>tsc node_modules\@types\crypto-js\index.d.ts

c:\test>echo %ERRORLEVEL%
0

```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
