### ISSUE TITLE
Shouldn't LoDashImplicitWrapperBase.toLength() return number instead?

### ISSUE THREAD

**Issue by Meldinoor** [DefinitelyTyped/DefinitelyTyped#13959]
According to index.d.ts (line 12710) this function returns LoDashImplicitWrapper<number>, but when testing the latest version of lodash I get a number. Is this an error in the definitions file?

**Comment by aj-r** [comment]
Yes, it was an error. It's fixed now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
