### ISSUE TITLE
react-virtualized does not contain List in definitions

### ISSUE THREAD

**Issue by andrewdewaal** [DefinitelyTyped/DefinitelyTyped#13964]
- [ ] I tried using the latest `react-virtualized/indexd.ts` file in this repo and had problems.
The "List" object exists in the JS, but is not included in the types. 
To ensure the use of the virtualized list in a TS project, this definition will need to be added.

  - The authors of that type definition are cc/ @bvaughn

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
