### ISSUE TITLE
Protractor dependencies

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#13977]
- [X] I want to talk about `protractor-helpers/package.json` and `protractor-http-mock/package.json`.
  - The authors of that type definition are cc/ @johncant @Crevil @BillArmstrong @Kuniwak @cnishina

It's important that the latest versions of libraries be able to work together. Currently `protractor-helpers` and `protractor-http-mock` depend on old versions of `selenium-webdriver`. Can they be updated to use the new one directly?

This would mean removing the `package.json` dependency and relying on our usual tsconfig:
```json
"baseUrl": "../",
"typeRoots": [
    "../"
],
```

(This is going back on what I said in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11233#issuecomment-248033034)

**Comment by cnishina** [comment]
I think this is an issue for the protractor-helpers and protractor-http-mock authors. Can these published packages work with the latest Protractor that uses the latest selenium-webdriver typings? It looks like these are actively being used (npm download graphs: [protractor-helpers](https://npm-stat.com/charts.html?package=protractor-helpers&from=2016-01-01&to=2017-01-11) and [protractor-http-mock](https://npm-stat.com/charts.html?package=protractor-http-mock&from=2016-01-01&to=2017-01-11))

I haven't heard of these modules other than in DefinitelyTyped. Protractor does not maintain these repositories and will probably not update these typings.

That being said, I'll put a PR together just to see if we can just flip the version.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
