### ISSUE TITLE
Express-serve-static-core TS2665 error together with Express

### ISSUE THREAD

**Issue by LudwikJaniuk** [DefinitelyTyped/DefinitelyTyped#14021]
- [x] I tried using the latest `express-serve-static-core/index.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] No, I'm using typescript 1.8
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

I tried installing the Express typings, and also express-serve-static-core as it is a dependency. However, when compiling, I get `Error:(12, 15) TS2665:Module augmentation cannot introduce new names in the top level scope.` for line 12 of file `express-serve-static-core/index.d.ts`.

**Comment by LudwikJaniuk** [comment]
And the error disappeared when I manually removed the `global` wrapper around the Express namespace.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
