### ISSUE TITLE
Proposal: Deprecate supertest-as-promised

### ISSUE THREAD

**Issue by TonyPythoneer** [DefinitelyTyped/DefinitelyTyped#14055]
Hello, @andy-ms 

The [supertest-as-promised](https://github.com/WhoopInc/supertest-as-promised) author had declared the project is deprecated. I suggest deleting `supertest-as-promised` type.

It's because [supertest had supported promise](https://github.com/visionmedia/supertest/blob/master/History.md#200--2016-07-29). It also means that [superagent had supported promise](http://visionmedia.github.io/superagent/#promise-and-generator-support). (BTW, superagent is wrappered by supertest)

We could look [superagent in DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4869992bc079b88280b9ff91213528904109e8ae/superagent/index.d.ts#L83), it had promise support, so `supertest-as-promised` users can peacefully use `supertest`.

**Comment by TonyPythoneer** [comment]
cc @andy-ms

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
