### ISSUE TITLE
Project crash in this fabric.js commit ?

### ISSUE THREAD

**Issue by Jandou6** [DefinitelyTyped/DefinitelyTyped#14057]
- [ ] I want to talk about `fabric/index.d.ts`.
  - The authors of that type definition are cc/ @ andy-ms 

hello @andy-ms , I found that you change the type@fabric . 

today i install my node_modules...and found that has the error tips that i never see:

![](http://oage4l7r6.bkt.clouddn.com/error1.jpeg)

and i found that you has changed the name of the fabric..and i use `import * as fabric from 'fabric'`to import the fabric .sure no error tips in terminal。

but ......

And now i can't use the way of the past to rewrite the fabric.js.

this is the way i rewrite the fabric in past:
```
_.assign(fabric, {Canvas});
```

but i found that i must use the way:
```
_.assign(fabric['fabric'], {Canvas});
```
Is you add the namespace in fabric ,so that i must use that way ?

And I don't know the right way the rewrite the inner of the fabric now.....

And....

i use the `applyMixins(Canvas, [fabric.Canvas]);` to quote the original methods,and now lose.

**Comment by andy-ms** [comment]
For the first problem, see Microsoft/TypeScript#10178.
For the second problem, could you tell me what works at runtime? Do `fabric` and `fabric['fabric']` both work at runtime, or does only one?

**Comment by Jandou6** [comment]
in my project that i only has `fabric`,but it can't rewrite the inner of the fabric.js. SO i use `fabric['fabric']`,it can rewrite it but why must use this way ? I see not simplier than only write `fabric`,and I found that if i want to use some methods in fabric i must use it like that `fabric['fabric'].util.xxxxx` not like previous....'fabric.util.xxxx'.

And `applyMixins(Canvas, [fabric.Canvas]);` be invalid.

**Comment by andy-ms** [comment]
So, you're saying that `require("fabric")` is just an object with a `fabric` property?

**Comment by Jandou6** [comment]
yes

**Comment by Jandou6** [comment]
Sorry~last night is too late ...so can not reply you more infomation.

Now I found that I use` import 'fabric' `in earlier time.And now i use `import * as fabric from 'fabric'`~

But many methods can not run. Could you tell how i should do to solve this?

As all as, I think that my project crash because of this `import * as fabric from 'fabric'`;

**Comment by nuntipat** [comment]
@andy-ms Currently, only `fabric['fabric']` works at runtime so I need to for example `let canvas = new fabric['fabric'].Canvas(...);` instead of just `let canvas = new fabric.Canvas(...);`. 

I use `import * as fabric from 'fabric';` at the top of the file. Did I miss something? I think that the problem has something to do with mixing namespace and module.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
