### ISSUE TITLE
Google-maps - Some problems with the set up

### ISSUE THREAD

**Issue by ArmindoBC** [DefinitelyTyped/DefinitelyTyped#14061]
Hello,

I'm  trying to set up the examples of google-maps that are provided in the github, but I'm having a lot of issues.

Here are an example of the console errors that I'm having: 
![untitled](https://cloud.githubusercontent.com/assets/4803517/22022826/77b2a23a-dcbb-11e6-9248-8ffcc6dd1c78.png)

So, if any of you guys could help me, i would be really grateful : ) 

Thank you in advance :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
