### ISSUE TITLE
THREE.FontLoader wrong return type

### ISSUE THREAD

**Issue by itreppert** [DefinitelyTyped/DefinitelyTyped#14081]
Hi,

in the THREE.FontLoader load callback, there's a wrong return type:
string should be THREE.Font.

Regards,
Holger

```
    export class FontLoader {
        constructor(manager?: LoadingManager);

        manager: LoadingManager;

        load(url: string, onLoad?: (responseText: string) => void, onProgress?: (event: any) => void, onError?: (event: any) => void): void;
        parse(json: string): Font;
    }
```

```
    export class FontLoader {
        constructor(manager?: LoadingManager);

        manager: LoadingManager;

        load(url: string, onLoad?: (response: THREE.Font) => void, onProgress?: (event: any) => void, onError?: (event: any) => void): void;
        parse(json: string): Font;
    }
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
