### ISSUE TITLE
Durandal and Breeze implicit 'any' types errors

### ISSUE THREAD

**Issue by piwnik** [DefinitelyTyped/DefinitelyTyped#1409]
TypeScript 0.9.5
Durandal and Breeze have lot of errors when disallow implicit 'any' types

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
