### ISSUE TITLE
alertify type definitions not up to date

### ISSUE THREAD

**Issue by CodeLiftSleep** [DefinitelyTyped/DefinitelyTyped#14117]
This is a valid alertify confirm message that pops up but it is throwing an error with the typescript definition file...appears it is from a old version of alertify not .3.1.1 the latest one

```
            alertify.confirm(confirmTitle, confirmMsg, function () {
                model.remove()
                    .then(function (response) {
                        alertify.success(successMsg);
                        deferred.resolve();
                    }), function (e) {
                        alertify.error(errorMsg);
                        console.log('Error!! ' + e.name + ':  ' + e.message);
                        return $q.reject(e);
                    };
            },
                function () {
                    alertify.error('Canceled');
                });
            return deferred.promise;
        };
```

Author of this Type definition file is: andy-ms

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
