### ISSUE TITLE
angular js typescript definition file doesn't work at all...throws 70+ errors

### ISSUE THREAD

**Issue by CodeLiftSleep** [DefinitelyTyped/DefinitelyTyped#14118]
angular is not recognized as being valid with the typescript definition file and the definition file is showing 70+ errors in it which doesn't allow it to even run. Using angular 1.6 in my project just as the typescript definition file, it will not recognize anything in angular.

![image](https://cloud.githubusercontent.com/assets/17439424/22115753/4168abde-de3c-11e6-9f60-76f2dc9bb1d1.png)

![image](https://cloud.githubusercontent.com/assets/17439424/22115813/751a1f58-de3c-11e6-93de-b80012df9bdc.png)

authors are thorn0 and diegovilar

**Comment by mhegazy** [comment]
Working locally for me. can you share more context?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
