### ISSUE TITLE
Missing THREE.OBJLoader  from three/examples/js/loaders/OBJLoader.js

### ISSUE THREAD

**Issue by itreppert** [DefinitelyTyped/DefinitelyTyped#14110]
try this definition:

    export class OBJLoader extends EventDispatcher {
        constructor(manager?: LoadingManager);

        manager: LoadingManager;
        material: THREE.Material;
        regexp: string;

        load(url: string, onLoad?: (response: any) => void, onProgress?: (request: XMLHttpRequest) => void, onError?: (event: any) => void): any;
        setPath(value: string): void;
        setMaterials(materials: THREE.Material[]): void;
        _createParserState(): void;
        parse(text: string): void
    }

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
