### ISSUE TITLE
Type definitions for Jasmine 2.5 not compiling

### ISSUE THREAD

**Issue by rupeshtiwari** [DefinitelyTyped/DefinitelyTyped#14122]
- [ ] I tried using the latest `DefinitelyTyped/jasmine.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version 1.8 of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (When I compile my project it errors out and not compiling jasmine.d.ts 2.5).
Error says:
Build: Statement exppected at line 70, 254
Build: Declaration or statement expected. at line 258,584
Build: cannot compile external modules unless the '--module' flag is provided 581...
Any many ; expected errors.

I found there is one interface which has comma instead of semicolon please check:

```
  
    interface CustomReporterResult {
        description: string,
        failedExpectations?: FailedExpectation[],
        fullName: string,
        id: string;
        passedExpectations?: PassedExpectation[],
        pendingReason?: string;
        status?: string;
    }

```

**Comment by mhegazy** [comment]
What version of the compiler are you using? commas are allowed declaration separator in TS 1.5 if i remember correctly.

**Comment by roopkt** [comment]
TS 1.4

**Comment by mhegazy** [comment]
Feel free to send a PR to change the commas to semicolons. but the latest in DT now is TS 2.0, so tests are not running against any earlier versions, and it is likely such things will be broken again.

**Comment by roopkt** [comment]
Thanks Hegazy !

**Comment by zvirja** [comment]
@rupeshtiwari I've just checked the latest definition and issue should be resolved:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f764e7d5b727818dfc56f87b9864d1ae25c610b0/types/jasmine/ts3.1/index.d.ts#L632-L640

Could you please close it if it's solved?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
