### ISSUE TITLE
tls.TLSSocket is missing super class definitions of net.Socket

### ISSUE THREAD

**Issue by Orillion360** [DefinitelyTyped/DefinitelyTyped#14141]
Node [documentation](https://nodejs.org/api/tls.html#tls_class_tls_tlssocket) states that `tls.TLSSocket` is a subclass of `net.Socket`, however the current Typescript Definition file at `@types/node` has TLSSocket defined as extending `stream.duplex`.

Attempts to make `tls.TLSSocket` a subclass of `net.Socket` fail because it has mismatching method signature for some methods.

The .d.ts file for `tls.TLSSocket` needs to include all methods and properties that `net.Socket` has as well.

An example of a missing method called is `.setKeepAlive(enable: boolean, initialDelay: number)`

**Comment by jtut1731** [comment]
Pull request for fix (v6 and root:v7):
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15013

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
