### ISSUE TITLE
@types/msgpack should refer msgpack-node for consistency

### ISSUE THREAD

**Issue by yohei1126** [DefinitelyTyped/DefinitelyTyped#14157]
- [x] I tried using the latest `msgack/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `msgack/index.d.ts`.
  - The authors of that type definition are cc/ @enrapt-mochizuki

"npm install msgpack" installs [msgpack-node](https://github.com/msgpack/msgpack-node)
https://www.npmjs.com/package/msgpack
But "npm install @types/msgpack" installs types for [msgpack-javascript](https://github.com/msgpack/msgpack-javascript)
https://www.npmjs.com/package/@types/msgpack

This is very confusing. @types/msgpack should refer [msgpack-node] for consistency.

**Comment by yohei1126** [comment]
Please let me know what do you think about this. @enrapt-mochizuki

**Comment by yohei1126** [comment]
if my understanding is correct, definitelytyped module and npm module must be the same name.

**Comment by llint** [comment]
I ran into the same issue, and this is definitely a problem! A moderator should be watching the consistency of npm packages and definitelytyped packages!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
