### ISSUE TITLE
lodash is missing flatMapDeep

### ISSUE THREAD

**Issue by manuelfink** [DefinitelyTyped/DefinitelyTyped#14168]
lodash has two methods flatMapDeep and flatMapDepth which are missing from the typing resulting in the following error

```
Property 'flatMapDeep' does not exist on type 'LoDashStatic'.
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/lodash/index.d.ts

Please add like https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/lodash/flatMap

**Comment by codeepic** [comment]
It's been 6 months since this issue was reported and it's still not fixed. Have the same problem in my work project.

**Comment by krishollenbeck** [comment]
Same issue here. Using "@types/lodash": "4.14.66" and "lodash": "^4.11.1".

**Comment by iwona-trabka** [comment]
I have same issue. Still waiting

**Comment by aj-r** [comment]
This is fixed now

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
