### ISSUE TITLE
Add a d.ts for package.json

### ISSUE THREAD

**Issue by atrauzzi** [DefinitelyTyped/DefinitelyTyped#14165]
That way, if someone imports it, they can access the known-standard NPM entries.

**Comment by TonyPythoneer** [comment]
What is it? Could you describe more clear?

**Comment by atrauzzi** [comment]
Basically the schema for `package.json`.  That way when I `const manifest = require("path-to-package.json")`, I can type it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
