### ISSUE TITLE
msgpack: index.d.ts should have module declaration

### ISSUE THREAD

**Issue by yohei1126** [DefinitelyTyped/DefinitelyTyped#14180]
- [x] I tried using the latest `msgpack/indexd.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `msgpack/indexd.d.ts`.
  - The authors of that type definition are cc/ @enrapt-mochizuki

If I import msgpack, I got the following error.

```
[ts] File 'd:/work/node_modules/@types/msgpack/index.d.ts' is not a module.
```

So, index.d.ts should have a module declaration like the following.

```
declare module "msgpack" {
  export = msgpack;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
