### ISSUE TITLE
Infer maximum typescript version from dependencies

### ISSUE THREAD

**Issue by ericanderson** [DefinitelyTyped/DefinitelyTyped#14205]
Its getting to be a pain to have to specify the typescript version for all modules that depend on a module. You can see this in the recent react PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13155) and the soon lodash PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13994) which makes it very hard to see the meat of the changes amid hundreds of file updates.

If possible, I would propose a resolution phase in which any module A that depends on module B, that the max(A.tsVersion, B.tsVersion) becomes the implicit tsVersion for A.

My apologies @andy-ms that this is in this repo and not the build tool repo, but I cannot seem to find said repo at the moment.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
