### ISSUE TITLE
Unable to install typings using tsd

### ISSUE THREAD

**Issue by mathikp** [DefinitelyTyped/DefinitelyTyped#14208]
I have tried installing a typing using tsd which gives zero result.

![sshot-1](https://cloud.githubusercontent.com/assets/13851265/22241400/2c0dbe02-e245-11e6-887a-11ee7981643e.png)

**Comment by mathikp** [comment]
Any update here?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
