### ISSUE TITLE
materialize-css: typescript definitions need update

### ISSUE THREAD

**Issue by DetlefPeters** [DefinitelyTyped/DefinitelyTyped#14213]
```
>typings info dt~materialize-css --versions
TAG                   VERSION DESCRIPTION COMPILER LOCATION                                                                                                             UPDATED
0.97.5+20170120192433 0.97.5                       github:DefinitelyTyped/DefinitelyTyped/materialize-css/index.d.ts#26857897650290c60cf75d3ed28b3f80d52f9942           2017-01-20T19:24:33.000Z
0.97.5+20161130005836 0.97.5                       github:DefinitelyTyped/DefinitelyTyped/materialize-css/materialize-css.d.ts#8613472d8f7c7769d4e417aa749fa14e7b5811da 2016-11-30T00:58:36.000Z
```
The typescript definitions are still based on v0.97.5
Due to the changes in Modal API, it is now impossible to use the latest materialize-css version 0.97.8 with typescript :-(

Please update your materialize-css.d.ts.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
