### ISSUE TITLE
old typing with npm i @types/....

### ISSUE THREAD

**Issue by egorovsa** [DefinitelyTyped/DefinitelyTyped#14219]
How can i install old typing with npm i @types/...
For example:
I have some typing in my typings folder. I would like to reinstall it to node_modules/@types folder
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/99a779e9eb0c473ee65e49438b348bf7e9a97b84/google-libphonenumber/google-libphonenumber.d.ts
How can i do it?

**Comment by mhegazy** [comment]
Not sure i understand the question. if you are using typings and happy with it, no reason to migrate. if you want to use `@types`, not sure what typings has to do with that?

**Comment by SenHeng** [comment]
@egorovsa
just append the version number of the library you're using.

eg.

```
yarn add @types/angular@1.5.9
...
success Saved 2 new dependencies.
├─ @types/angular@1.5.9
└─ @types/jquery@1.10.31
```

But this only works if microsoft made the types available.  Check which ones are available like this.

```
yarn info @types/angular

...
  versions:
   [ '1.5.1-alpha',
     '1.5.2-alpha',
     '1.5.3-alpha',
     '1.5.4-alpha',
     '1.5.5-alpha',
     '1.5.6-alpha',
     '1.5.7',
...
```

**Comment by egorovsa** [comment]
I  use yarn for install packages, and yarn has 

> 5. yarn add <git remote url>#<commit/tag> installs a package from a remote git 

i should use exactly this commit, but i can't understand how......

> https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/99a779e9eb0c473ee65e49438b348bf7e9a97b84/google-libphonenumber/google-libphonenumber.d.ts

i would't like use typings, because it is not so convenient, whenever you can use just package.json  for all.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
