### ISSUE TITLE
Request: pgwSlider definitions

### ISSUE THREAD

**Issue by sugarflux** [DefinitelyTyped/DefinitelyTyped#14210]
I'm hoping someone might be able to hook me up with definitions for pgwSlider - a lightweight JQuery photo gallery...

http://pgwjs.com/pgwslider/

Here's what i have so far (a long way from perfect):

```
/// <reference path="../jquery/jquery.d.ts"/>

interface JQuery {
    pgwSlider(): JQuery;
    pgwSlider(options: IpgwSliderOptions): JQuery;
}  

interface IpgwSliderOptions {
    mainClassName?: string;
    listPosition?: string;
    selectionMode?: string;
    transitionEffect?: string;
    autoSlide?: boolean;
    displayList?: boolean;
    displayControls?: boolean;
    touchControls?: boolean;
    verticalCentering?: boolean;
    adaptiveHeight?: boolean;
    maxHeight?: number;
    beforeSlide?(): void;
    afterSlide?(): void;
    adaptiveDuration?: number;
    transitionDuration?: number;
    intervalDuration?: number;
}

declare class pgwSlider {

    startSlide(): void;
    stopSlide(): void;
    getCurrentSlider(): number;
    getSlideCount(): number;
    displaySlide(index: number): void;
    nextSlide(): void;
    previousSlide(): void;
    destroy(): void;
    reload(): void;
    reload(options: IpgwSliderOptions): void;

}

declare module "pgwslider" {
    export default pgwSlider;
}

```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
