### ISSUE TITLE
GoogleAppsScript.Base.Ui.ButtonSet is Property not Enum.

### ISSUE THREAD

**Issue by Measter** [DefinitelyTyped/DefinitelyTyped#14221]
According to the [Google Apps Reference](https://developers.google.com/apps-script/reference/base/button-set), this code should work:

    function MyFunction() {
        const ui = DocumentApp.getUi();
        const response = ui.alert("Text", ui.ButtonSet.YES_NO);
    }

However, I'm getting compile error TS2339: Property 'YES_NO' does not exist on type 'ButtonSet'.

Basically, GoogleAppsScript.Base.Ui.ButtonSet is a property of type GoogleAppsScript.Base.ButtonSet, not the enum like it should be.

Doing this compiles:

    function MyFunction() {
        const ui = DocumentApp.getUi();
        const response = ui.alert("Text", GoogleAppsScript.Base.ButtonSet.YES_NO);
    }

However does not run on Google Apps giving this error: ReferenceError: "GoogleAppsScript" is not defined.

The latest implementation of the GoogleAppsScript.Base.UI interface in /google-apps-script/google-apps-script.base.d.ts is defined in this way.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
