### ISSUE TITLE
faker.image.imageUrl() params

### ISSUE THREAD

**Issue by Seniagin** [DefinitelyTyped/DefinitelyTyped#14260]
I tried using the latest `faker/index.d.ts` file in this repo and had problems.
```Faker.image.imageUrl()``` got 4 arguments here: https://github.com/Marak/faker.js/blob/master/lib/image.js#L38,
but only 3 is defined:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/faker/index.d.ts#L105,
 please, add missing one

**Comment by thedaviddias** [comment]
@YegorZaremba I believe this issue could be closed by now.

**Comment by YegorZaremba** [comment]
@thedaviddias I too, but im not a issue creator :disappointed:

**Comment by YegorZaremba** [comment]
@Seniagin just ping bro

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
