### ISSUE TITLE
chai-enzyme TypeError TS2339: Property 'text' does not exist on type 'Include'

### ISSUE THREAD

**Issue by raptoria** [DefinitelyTyped/DefinitelyTyped#14269]
In the Official chai-enzyme documentation, it shows:
expect(wrapper.find('#child')).to.contain.text('Te')

According to:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/chai-enzyme/index.d.ts

The Text attribute exists on Assertion and not Include (hence the error)
Contain, which is an Include, expects a selector as an argument

My test:

```
  it('Has File', () => {
    const wrapper = render(<FileMenu />);
    expect(wrapper.find('.dropdown')).to.contain.text('File');  //line 17..
  });
```

```
ERROR in ./test/components/FileMenu/FileMenuTest.tsx
(17,50): error TS2339: Property 'text' does not exist on type 'Include'.
```

My work around:
`expect(wrapper.find('.dropdown')).to.have.text().matches(/File/);`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
