### ISSUE TITLE
Request for Cannon.js definition

### ISSUE THREAD

**Issue by flipchart** [DefinitelyTyped/DefinitelyTyped#1429]
Physics engine which compliments Three.js nicely

Official page: http://cannonjs.org/
Github repo: https://github.com/schteppe/cannon.js

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
