### ISSUE TITLE
@types/requirejs  - window.require not defined

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#14290]
I am getting this:

```
10 const globalRequire = window.require;
                                ~~~~~~~

public/js/hot-reloader.tsx(10,30): error TS2339: Property 'require' does not exist on type 'Window'.

```

but I am using the @types/requirejs import, here is config:

```js
{
  "compilerOptions": {
    "baseUrl": ".",
    "jsx": "react",
    "paths": {
      "@hot-reload-handler": [ "public/js/hot-reload-handler"],
      "@hot-reloader": [ "public/js/hot-reloader"],
      "redux": ["node_modules/redux/index"],
      "redux-thunk": ["node_modules/redux-thunk/index"],
      "uuid": ["d.ts/uuid"],
      "@redux-store":["public/js/data-stores/redux-store"]
    },
    "types": [
      "react",
      "react-dom",
      "whatwg-fetch",
      "requirejs"              // <<<<<< 
    ],
    "target": "es5",
    "module": "amd",
    "noImplicitAny": false,
    "removeComments": true,
    "allowUnreachableCode": true,
    "moduleResolution": "classic",
    "lib": [
      "es2015",
      "es2016",
      "dom"
    ]
  },
  "compileOnSave": false,
  "include": [
    "./d.ts/**/*.ts",
    "./public/**/*.ts",
    "./public/**/*.tsx"
  ]
}
```

which I using like so:

`tsc --pretty --jsx react --project tsconfig-fe.json`

trying figure out why `window` would not have `require` defined, this is requirejs! :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
