### ISSUE TITLE
@types/angular-mocks lack of 1.6.* version 

### ISSUE THREAD

**Issue by alexey-shakura** [DefinitelyTyped/DefinitelyTyped#14293]
There's no typings for angular 1.6.1 now. Let's do this

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
