### ISSUE TITLE
@angular-ui-router compatiblity problems

### ISSUE THREAD

**Issue by squadwuschel** [DefinitelyTyped/DefinitelyTyped#14298]
@michelsalib @matiishyn 

I've Problems when using the Typings without any AMD or CommonJs. I just want to use it in Visual Studio with plain old JavaScript and not Loaders.

Visual Studio is not finding the Types like

ng.ui.IStateService = Its not working

when I remove the complete "header"

    import * as angular from 'angular';

    export default "ui.router";

    export type IState = angular.ui.IState;
     ....
    export type IType = angular.ui.IType;

and just use write

    declare namespace  angular {
       export namespace ui {
           interface IState {
               name?: string;
               ....

its working fine. Perhaps you could check the typings that they also work for ppl with no Loaders.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
