### ISSUE TITLE
uuid: TypeScript type definition conflicting on `require`

### ISSUE THREAD

**Issue by BrainCrumbz** [DefinitelyTyped/DefinitelyTyped#14297]
- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

Reposting here an issue initially opened in [kelektiv/node-uuid](https://github.com/kelektiv/node-uuid/issues/168#issuecomment-275526848). Someone there mentioned that this project should be a more appropriate place where to post it.

-----

Hello all. We tried installed this dependency (node-uuid]), at current v3.0.1, in an Angular 2/ TypeScript 2/ Webpack 2 project. In order to make that build, we also installed type definition from `@types/uuid`, currently v2.0.3.

The build then fails anyway with the following:

> xxxxx\node_modules\@types\node\index.d.ts:73:13
    Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'Require', but here has type 'NodeRequire'.

At a first look, that seems some kind of conflict with another `require`definition. In `package.json` we also have `@types/requirejs`, v2.1.28. Has anyone experienced this same issue using the library in TypeScript?

**EDIT** Our `project.json` does not explicitly include `@types/node`. That comes with `@types/uuid`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
