### ISSUE TITLE
Bootstrap/index.d.ts bug

### ISSUE THREAD

**Issue by csharpner** [DefinitelyTyped/DefinitelyTyped#14307]
- [x] I tried using the `@types/bootstrap` package and had problems.
- [x] I tried using the latest stable version https://github.com/DefinitelyTyped/DefinitelyTyped
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov 

This line #6:
/// <reference types="jquery"/>

Causes problems.  But if I change it to...
/// <reference path="../jquery/jquery.d.ts" />

...It fixes it.

**Comment by mhegazy** [comment]
?

the lines above are empty. what am i missing?

**Comment by csharpner** [comment]
Good question!  I don't know what happened to the post.  It's been to long now, I'm not sure what those lines were anymore. :(

**Comment by DoubleCouponDay** [comment]
I think I have a similar problem.

I noticed bootstrap.typescript.definitelytyped 0.9.8 for nuget wont compile straight away
line 7 of its index.d.ts file:
/// <reference types="jquery"/> Cannot find the type definition file for jquery
when I comment it out, I cant use this package just fine. what gives?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
