### ISSUE TITLE
Cannot find name 'Partial'

### ISSUE THREAD

**Issue by sollabeck** [DefinitelyTyped/DefinitelyTyped#14311]
- [x] I tried using the `@types/4.14.51` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

Getting an error with the latest version of lodash. It seems like Partial was recently added to the following file but it isn't defined. Maybe I'm doing something wrong.

[Line 245 of the following file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/lodash/index.d.ts
)

Image: https://cl.ly/0T3w1Q3a1T1a

**Comment by IanTaiteAgl** [comment]
I'm getting the same.

On line 245 we have:

`type PartialObject<T> = Partial<T>;
`

On line 247 a namespace is defined with pretty much everything else defined within it, so I'm expecting the above to be:

`type PartialObject<T> = _.Partial<T>;
`

however, that doesn't work because Partial, defined on line 10634 is not generic.

`type PartialObject<T> = _.Partial;
`

The above gets rid of the red squiggles in vs code but probably doesn't solve the problem. I just don't have enough experience in this area to know whether a type is missing, i.e. Partial<T>, whether my hack would work, or whether something else is needed. 

For now, I've fixed my package.json to require version 4.14.50 as the problem appears to be in the .51 file only.

**Comment by carusology** [comment]
Ran into this today on our CI server too. It looks like a bug in the definition to me as well. @lukas-zech-software, it looks like you made the change [here](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/2461ee114f7718677d6c369061e6ad946f517de2#diff-431377a17b9e465836267d609781e68cR245). Are we missing something, or is this a bug that slipped through?

**Comment by carusology** [comment]
Yeah, Partial<T> defined in typescript v2.1 [here](https://github.com/Microsoft/TypeScript/blob/fb23e6dba1e79c2c13f116299756062ee36cbf09/lib/lib.d.ts#L1366-L1392), and announced [here](https://blogs.msdn.microsoft.com/typescript/2016/12/07/announcing-typescript-2-1/).

Try upgrading typescript to v2.1 and see if the error goes away. Little hamstrung to test myself atm.

**Comment by lukas-zech-software** [comment]
The changes introduced in #13994 will only compile with Typescript 2.1 or higher as the `Partial` keyword was introduced in this version.

The error has nothing to do with  `_.Partial`, the naming is only coincidentally alike with the `Partial` keyword from Typescript (see [here](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#mapped-types) for details)

As @andy-ms pointed out [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13994#issuecomment-275801094) you can still install the old typings compatible with Typescript 2.0 by using `@types/lodash@ts2.0`

**Comment by lukas-zech-software** [comment]
@carusology If your CI relies on the typings I would suggest to always use a fixed version or even commit for the typings in your `package.json` as there is currently no way to use SemVer with DefinitelyTyped and every new feature introduced would break your build if you always install the newest typings

**Comment by carusology** [comment]
Heh, @lukas-zech-software, you don't need to worry about my random build server, I know you didn't do anything wrong. I was just unaware of the new type on v2.1.

Thanks for chiming in so quickly.

**Comment by ashblue** [comment]
Woke up to our team wondering why TypeScript stopped compiling. Is there going to be a fix placed in the typings file to resolve the namespace issue? I understand the problem is a TypeScript 2.1 issue and not Lodash. But an ETA, scope required for a fix, and/or if anyone has next steps would be really nice to know.

**Comment by lukas-zech-software** [comment]
@ashblue As already described in this issue and in this [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13994#issuecomment-276057119) this is not an error in the typings and therefore won't be fixed.

You will need to install the typings fix to the older version still supporting Typescript 2.0 by either using `@types/lodash@ts2.0` or `@types/lodash@4.14.50` and keep it fixed at this version.

The typings are not backwards compatible and you must install an older version of the typings or upgrade to Typescript 2.1

**Comment by dgaeta** [comment]
See also SPFx [issue 394](https://github.com/SharePoint/sp-dev-docs/issues/394). If you are dependent on a third party library that uses a ~ pattern, then you cannot control what version "npm install" chooses.

**Comment by lukas-zech-software** [comment]
You can control what `npm install` does quite exactly by locking down the dependency tree by using `npm shrinkwrap` which is highly advisable for all projects used in production

**Comment by sollabeck** [comment]
Going to close this issue. Thanks for the response guys.
