### ISSUE TITLE
Non-typescript import of Configstore

### ISSUE THREAD

**Issue by st-clair-clarke** [DefinitelyTyped/DefinitelyTyped#14315]
- [x ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

After adding configstore and @types/configstore to my package.json, I tried to do the following in a typescript file

`readonly conf = new Configstore(pkg.name, {foo: 'bar'});`

The default import for Configstore is
`
import Configstore = require('configstore')`

which is NOT typescript-type imports

When I try to do 

`import {Configstore} = from 'configstore'`

Configstore could not be found

Is there something wrong with the typings? I am using

configstore@2.1.0
@types/configstore@2.1.0

Thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
