### ISSUE TITLE
Chrome: index.d.ts Issue with desired Typing of onBeforeNavigate.addListener 

### ISSUE THREAD

**Issue by sreimer15** [DefinitelyTyped/DefinitelyTyped#14330]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**
```
EXAMPLE CODE:

// The addListener function is passed in a WebNavigation.ParentedCallBackDetails
// but also takes a filters object.

chrome.webNavigation.onBeforeNavigate.addListener((requestDetails) =>  {
    console.log(requestDetails)
},
    // this is the line where the compiler complains
    {urls: ["<all_urls>"]}
);
```
The Typing is as follows:
```
chrome.webNavigation.onBeforeNavigate.addListener(
  chrome.WebNavigation.WebNavigation.ParentedCallBackDetails,
  filters: chrome.WebNavigation.WebNavigationEventFilter
)
The type that the compiler wants for the WebNavigation filter is 
url: []string, 
when the api wants a 
urls: []string
//- if you pass in a url property you get an error, you need a urls property 
```
The reason for this confusion is that the official docs say that [BeforeNavigation](https://developer.chrome.com/extensions/webNavigation) takes a "filters" object, which might seem like it is referring to [this] (https://developer.chrome.com/extensions/events#filtered)
but is actually referring to [this](https://developer.chrome.com/extensions/match_patterns)
The addListener takes a different type of urls filter.

```
**Expected behavior:**

A new interface might need to be defined, there is a RequestFilter type which has a urls property, but 
I don't think it fills this contract correctly. Perhaps the addListener call back can have a RequestFilter passed into it instead of a WebNavigationEventFilter
```
**Actual behavior:**
```
The Chrome Extension Docs are very ambiguous. 
The docs mention that you can pass in a url filter, but it is not of type url filter. It is actually a url filter string that describes what  urls are allowed to pass [through](https://developer.chrome.com/extensions/match_patterns). 
```
I'd love to submit a PR, or with any help with the matter. Thank you!
  - Authors: @matthewkimber @otiai10 @couven92 @rreverser

**Comment by epicgirl1998** [comment]
my extension uses `chrome.webNavigation` with the `url` property and i think you broke the typings for it (i'm pretty annoyed about it)

the docs say to use use the `url` property (array of objects), and the `urls` one (array of strings) isn't even mentioned there (which means the typings for the standard way were removed, and replaced with typings for a non-standard way)

the example from the docs you linked with the documented way to filter `webNavigation`s is now invalid:

![file](https://cloud.githubusercontent.com/assets/25940153/24166799/380a6386-0e7d-11e7-99ec-adb4c4db7ac6.png)

i can see two ways to fix this:

* add the `urls` property back so both of the filtering methods can be supported (since they both work)

* revert the changes. reasoning: is having types for an undocumented api a good idea?

i just hope someone sees this

**Comment by epicgirl1998** [comment]
@sreimer15

I did some testing and found out that filtering using the `url` property (array of strings) doesn't even work, and the callback was still being called for all navigations like the filter wasn't there. Your test used the filter `http://*/*` to match all (non-secure) urls which led me into thinking it worked when it was simply being ignored.

I'm submitting a PR to fix the typings and hope you can get your navigations correctly filtered too.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
