### ISSUE TITLE
d3-drag problems with Angular 2

### ISSUE THREAD

**Issue by gretamosa** [DefinitelyTyped/DefinitelyTyped#14335]
Hi @tomwanzek,

I'm trying to reproduce the following d3 example (http://bl.ocks.org/cjrd/6863459) in my Angular2 app with d3-drag and d3-select capabilities but I found the following error:

```
TypeError: Cannot read property 'button' of null
    at SVGGElement.defaultFilter (drag.js:10)
    at SVGGElement.mousedowned (drag.js:41)
    at SVGGElement.<anonymous> (d3.js:811)
    at ZoneDelegate.invokeTask (zone.js:275)
    at Object.onInvokeTask (ng_zone.js:262)
    at ZoneDelegate.invokeTask (zone.js:274)
    at Zone.runTask (zone.js:151)
    at SVGGElement.ZoneTask.invoke (zone.js:345)
```

My Typescript file has the following imports:
```
import * as d3 from 'd3';
import * as d3Drag from 'd3-drag';
import * as d3Selection from 'd3-selection';
```

Finally, I'm using d3 v4.4.4 (with @types from npm repository) and Angular2. Using only d3-select, the example works but without drag&drop capabilities.

I'm not sure wether it is a bug or coding error but any tip would be appreciated.

Thanks,

**Comment by tomwanzek** [comment]
As mentioned before, I do not suspect this to be an issue related to the definitions themselves and better suited to be triaged on Stackoverflow.

For one, your import statements are duplicative. You are importing the standard D3 bundle (`d3`) and then duplicating the already included imports for `d3-drag` and `d3-selection`.

From the looks of it, you are experiencing a run-time error because the binding of the `d3.event` has been affected by the duplication. So when the `drag` event filter gets invoked, the event is not well defined.

**Comment by tomwanzek** [comment]
As an FYI, there is also a known complication with the event binding, see [d3 Issue 2733](https://github.com/d3/d3/issues/2733).

This may or may not play a part, It was also one of the reasons why I created the (D3 Angular 2 Service)[https://github.com/tomwanzek/d3-ng2-service]. While the services focus, is more of a rapid prototyping, given its pre-defined D3 module composition, if you look at the source code, you could readily build a more tailored feature set service for your needs.

**Comment by tomwanzek** [comment]
@gretamosa Can this be closed?

**Comment by tomwanzek** [comment]
@andy-ms could you please close this one as well, it has not seen recent activity.
