### ISSUE TITLE
lab: namespace; use types for options

### ISSUE THREAD

**Issue by garthk** [DefinitelyTyped/DefinitelyTyped#14348]
- [x] I tried using the `@types/lab` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @prashaantt, @andy-ms 

I've tried extending the definitions in [`@types/lab`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/lab) so I can retire the typings I'm maintaining in [`lab-transform-typescript`](https://github.com/garthk/lab-transform-typescript/tree/master/typings-local). The main deltas are:

* Tests for the Promise-based tests and test hooks
* Typings for `ScriptOptions.cli`

With respect to the latter, there's no ghost module (see [Best Practices](http://definitelytyped.org/guides/best-practices.html)) in the current typings, preventing use of an `enum` for `ScriptOptions.cli.progress`. It's also giving TypeScript 2.1.5 some trouble:

```
$ tsc -p tsconfig.json 
index.d.ts(244,1): error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.
```

I'm also having trouble figuring out the intent behind `ExperimentAlt` and `TestAlt`. If they were to support the TDD and BDD aliases as documented for `lab`, I'd expect them to be named as such and group `suite` and `test` for TDD and `describe` and `it` for BDD… so I guess that's not what they're for. What are they for? If I don't know, and they're not tested, it'll be hard not to break whatever part of your code relies on them. Are you using them directly, or are they just part of the internal structure of the typings?

I figured I'd ask if you'd protest before going to the effort of fixing everything and filing a PR.

**Comment by andy-ms** [comment]
Not familiar with the library itself, but you shouldn't need "ghost modules" to augment this. Just use [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html), as in `declare module "lab" { ... new/merged definitions ... }`.

**Comment by prashaantt** [comment]
@garthk The definition compiled without issues when it was first submitted. I can't recall why I stuck with `ExperimentAlt` and `TestAlt` because it doesn't make sense to myself now, though it's likely that I first had it as `Experiment` and `Test` and needed to introduce the -Alt for some variants, perhaps after which I refactored and left these names behind. This is a mistake and should be corrected. But both TDD and BDD styles (`experiment`, `suite` and `describe`) inherit the same interfaces so I'm not sure much is to be gained splitting them, though some interface names could probably be improved. Please feel free to submit your PR, regardless.

@andy-ms Are there any recommendations to make these kind of interface name changes smooth for consumers?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
