### ISSUE TITLE
[request] vanilla-masker definitions

### ISSUE THREAD

**Issue by QuentinFchx** [DefinitelyTyped/DefinitelyTyped#14341]
Hi folks,

I'm new to Typescript and I'd like to create the set of definitions for the [vanilla-masker](https://github.com/BankFacil/vanilla-masker) library. There is a wip [here](https://github.com/BankFacil/vanilla-masker/issues/83) but I did not manage to make it work (I got the `'VMasker' only refers to a type, but is being used as a value here` error ...).

Any help appreciated :)

Thank you in advance!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
