### ISSUE TITLE
@types/ckeditor - Typo in `instanceReady` event

### ISSUE THREAD

**Issue by christian-sch** [DefinitelyTyped/DefinitelyTyped#14354]
in DefinitelyTyped/ckeditor/index.d.ts on line 1210:

`insanceReady?: (evt: CKEDITOR.eventInfo) => void;`

but should be:

`instanceReady?: (evt: CKEDITOR.eventInfo) => void;` 

(missing 't')

**Comment by DrewHoo** [comment]
Looks like this is fixed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
