### ISSUE TITLE
[TypeScript] TypeScript error: /.tmp/typings/foundation/index.d.ts(7,1): error TS1084: Invalid 'reference' directive syntax.

### ISSUE THREAD

**Issue by somashekharsk** [DefinitelyTyped/DefinitelyTyped#14365]
getting this error when i do the gulp default, my changes in .ts files are not reflecting on browser.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
