### ISSUE TITLE
enzyme definitions with strictNullChecks: true can't be compiled

### ISSUE THREAD

**Issue by honzabrecka** [DefinitelyTyped/DefinitelyTyped#14375]
**Type definitions for Enzyme v2.7.0**

```ts
const e = <div></div>// e's type is JSX.Element
shallow(e)// complains, because it expects argument of type ReactElement<P>
```

Can you provide working example that compiles with `strictNullChecks: true` in tsconfig, please?

cc @MarianPalkus

**Comment by vutran** [comment]
This was brought up by a recent merge here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14284

**Comment by MarianPalkus** [comment]
I'll try to have a look at this issue later on today or tomorrow.

**Comment by MarianPalkus** [comment]
I don't find the time to look at this  issue.
Can you have a look, @noHomey, @pelotom?

**Comment by jwbay** [comment]
I think https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14476 resolved this

**Comment by beagleknight** [comment]
I am getting the same error using the following packages:

```
├─ @types/enzyme@2.8.3
│  └─ @types/react@15.0.25
├─ @types/react-dom@15.5.1
│  └─ @types/react@15.0.25
├─ @types/react@15.0.38
├─ enzyme@2.9.1
├─ react-i18nify@1.8.7
│  └─ react@15.5.4
└─ react@15.6.1
```

**Comment by beagleknight** [comment]
I get rid of some of the errors downgrading `@types/react` to `15.0.25`. I hope it helps!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
