### ISSUE TITLE
Unable to import directly from `react/lib/ReactComponent`, etc

### ISSUE THREAD

**Issue by trusktr** [DefinitelyTyped/DefinitelyTyped#14386]
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @yuit @faddee @RyanCavanaugh @vsiao There's lots of authors actually, so if you can tag who you think is most relevant, please do.

I was trying to import some things directly from React, like `react/lib/ReactComponent`, and other things. I think it is a valid use case.

TypeScript is unable to find declarations when doing that.

**Comment by vsiao** [comment]
It's not officially supported API (the React team explicitly discourages usage of said modules), so we don't include them on DT. You can write your own custom definitions for them.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
