### ISSUE TITLE
namespace chrome.debugger cannot be declared in @types/chrome

### ISSUE THREAD

**Issue by jagthebeetle** [DefinitelyTyped/DefinitelyTyped#14385]
According to a comment in chrome/index.d.ts, the chrome.debugger namespace was blocked on  [Microsoft/TypeScript#8312](https://github.com/Microsoft/TypeScript/pull/8312/). I assume this is because of the reserved word `debugger`. 

The referenced PR seems to have in fact solved the use of strict-mode reserved keywords, which per the spec/SyntaxKind enum [do not currently include](https://github.com/Microsoft/TypeScript/blob/4086bd13c7b459ab4302c48fc3ac428cc2078e08/lib/typescript.d.ts#L347) reserved word `debugger`. (The compiler's enforcement requires that 
```
node.originalKeywordKind >= SyntaxKind.FirstFutureReservedWord &&
node.originalKeywordKind <= SyntaxKind.LastFutureReservedWord &&
```
which maps to the strict-mode reserved words).

In my own project I work around this by downcasting `chrome` to an interface  (where `debugger` does work), and I haven't been able to find a nicer solution:
```
interface PatchedChrome {
  debugger: DebuggerNamespace
}
let chromeDebugger = (chrome as any as PatchedChrome).debugger;
```
I don't understand the TypeScript compiler well enough to know if this is an issue against them, so I'm opening it here first.

---
- [x] I tried using the `@types/chrome` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @otiai10, @matthewkimber, @couven92, @RReverser

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
