### ISSUE TITLE
Fix Knockout and strictNull

### ISSUE THREAD

**Issue by aersamkull** [DefinitelyTyped/DefinitelyTyped#14381]
- I tried using Knockout with strictNull, TypeScript version is 2.1
- Authors: @vvakame 

I get this error: 
![image](https://cloud.githubusercontent.com/assets/5270024/22507665/e7af50de-e886-11e6-8f5b-aaebceaab912.png)

(The first error  can be ignored, the others are from the typings itself)

**Comment by aersamkull** [comment]
If you remove all those 
```TypeScript
[key: string]: KnockoutBindingHandler;
```
It's fixed

**Comment by telmo-rodrigues** [comment]
I have the same issue, i just updated my TypeScript version to 2.5 and my package from NuGet to NPM and got these errors.
Is this a viable solution ? Will we have to remove all these when the package updates again ? or is there a config in tsconfig.json that allows the complier to work with these signatures

**Comment by ltlombardi** [comment]
In Visual Studio 2015, Typescript 2.4 and current version of Knockout Typings, there is not errors.

@aersamkull  Is this still relevant. If not please close this issue

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
