### ISSUE TITLE
[Request] Update pako typings. 

### ISSUE THREAD

**Issue by ProbablePrime** [DefinitelyTyped/DefinitelyTyped#14392]
I tried using the typings for `pako`, they currently target `0.2.8` the latest version is 1.0.4 and some of the types have changed considerably.

This is a request to update them to the latest version.

- [X] I tried using the `@types/pako` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cappellin

**Comment by cappellin** [comment]
Unfortunately I have no plans to update the version of Pako in the project where I use it, so I will not update the typings to the latest version soon.

**Comment by ProbablePrime** [comment]
I appreciate the reply, I'll take a stab at it myself if i get the chance. Thank you!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
