### ISSUE TITLE
Some 'style' properties in Highcharts are type 'Object' rather than 'CSSObject'

### ISSUE THREAD

**Issue by extremeandy** [DefinitelyTyped/DefinitelyTyped#14394]
In file **highcharts/index.d.ts**

E.g. `SubtitleOptions` has `style?: Object;`. This means it's not possible to assign style properties without casting to `any`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
