### ISSUE TITLE
How to model plug-ins with TS 0.9.5

### ISSUE THREAD

**Issue by johnnyreilly** [DefinitelyTyped/DefinitelyTyped#1441]
Hi Guys,

This is _not_ an issue - I just wanted to share a useful discussion that I'd seen that may prove useful to people upgrading typing libraries from 0.9.1 to 0.9.5:

https://typescript.codeplex.com/discussions/472172

In particular I would focus on jon turner's last 2 comments - they provide a useful steer on the importance of reference definition order.  Take a look (and obviously feel free to close this as an issue - given that it isn't)...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
