### ISSUE TITLE
leaflet-markercluster - MarkerClusterGroupOptions missing chunkProgress definition

### ISSUE THREAD

**Issue by okon3** [DefinitelyTyped/DefinitelyTyped#14445]
Type definition for `chunkProgress` is missing from `MarkerClusterGroupOptions ` inside @types/leaflet-markercluster

here's the reference:
https://github.com/Leaflet/Leaflet.markercluster#chunked-addlayers-options

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
