### ISSUE TITLE
phonegap-plugin-push not being imported

### ISSUE THREAD

**Issue by davidanaya** [DefinitelyTyped/DefinitelyTyped#14447]
Hi,

I'm having problems when trying to import phonegap-plugin-push type definitions.

I installed it with `$npm install --save-dev @types/phonegap-plugin-push`

I installed the typings with npm and the I tried to import it in my ts file using
```import { PushNotification } from 'phonegap-plugin-push';```
and I expected to have type information when using PushNotification methods, but instead
I get a `[ts] File 'my_src_path/node_modules/@types/phonegap-plugin-push/index.d.ts' is not a module` error

I already open an issue in the [github of the plugin](https://github.com/phonegap/phonegap-plugin-push/issues/1567) but I was told to open it here instead as the problem might be related to some sort of branch refactoring here.

Can anyone help? Thanks.

**Comment by hinell** [comment]
As you [can see](../blob/master/phonegap-plugin-push/index.d.ts#L1) it doesn't export anything cause it is a global module. Import it like
```ts
import 'phonegap-plugin-push'
```
or try to use [typings](../../../typings/typings)

**Comment by karser** [comment]
No need to import anything, run following:
```
npm install --save-dev @types/phonegap-plugin-push
```
update src/tsconfig.app.json:
```
"types": [ "@types/phonegap-plugin-push" ]
```

**Comment by karser** [comment]
@Nick-lab I updated my comment

**Comment by dhananjaykumar880** [comment]
With the new phonegap-plugin-push, you get types.
all you have to do is add `"types": ["phonegap-plugin-push/types"]` in tsconfig.app.json

import "phonegap-plugin-push/types" will not resolve typing.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
