### ISSUE TITLE
Restify Client close() method doesn't exist.

### ISSUE THREAD

**Issue by chasewalden** [DefinitelyTyped/DefinitelyTyped#14455]
I tried using the `@types/restify` package and had problems.

There should be a `close()` method on all three of the clients, but there isn't one. This prevents one from closing a Client from the Server, therefore blocking the Server from ever closing.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
