### ISSUE TITLE
Standard TD Rules for defining interfaces that are nested?

### ISSUE THREAD

**Issue by daryllabar** [DefinitelyTyped/DefinitelyTyped#14473]
This question revolves around the [DefinitelyTyped/xrm](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/xrm) library.  (see [this](https://drive.google.com/file/d/0B9-OddqJEKamWEs0MV9MMDdsWE0/view) cheat sheet for a high level view of what it all involves).

The td file contains an Xrm Namespace at the root, with an XrmStatic interface.  The XrmStatic Interface (I'm guessing the static is to avoid naming collisions?  But then why isn't it used else where?) defines a Page and Utility.  That makes sense, (although I'm going to submit a PR to make Page and Utility interfaces in and of themselves).  But then there is an Xrm.Data interface that is only used inside the Xrm.Page, but it's not defined in Xrm.Page Module at Xrm.Page.Data, even thought there is an Xrm.Page.data module.  

I feel like everything was added very haphazardly, with some interfaces in the Xrm Namespace, and some in nested modules there of...  Is there any sort of rule that we should be following when maintaining this?  Like interfaces should be nested as deeply as they can, or maybe interfaces should all be defined at the root level of the project?

So a guess a more generic way of asking this question is, given:
```
Xrm.Page.X,Y
```
Should the the td file contain interfaces for `X` and `Y` at` Xrm.X` and `Xrm.Y` respectively, or should they be at` Xrm.Page.X` and `Xrm.Page.X.Y`?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
