### ISSUE TITLE
Angular's $document is a jqLite-wrapped object, not Document

### ISSUE THREAD

**Issue by tgudlek** [DefinitelyTyped/DefinitelyTyped#1448]
Current definition:
interface IDocumentService extends Document {}

Documentation:
A jQuery (lite)-wrapped reference to the browser's window.document element.

Acutal Angular implementation:
...
return jqLite(window.document);
...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
