### ISSUE TITLE
@types/enzyme - CommonWrapper doesn't have `.find` any more

### ISSUE THREAD

**Issue by hesher** [DefinitelyTyped/DefinitelyTyped#14504]
- [ ] I tried using the `@types/enzyme` package and had problems.
  - Authors: @aozgaa 
The latest commit breaks any code that uses `CommonWrapper.find()`, Is that by design? If not there should be a generic `find` in `CommonWrapper`

**Comment by TonyPythoneer** [comment]
Please free to send PR.

**Comment by hesher** [comment]
I can try. I'll see if there's a common interface to derive from

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
