### ISSUE TITLE
react-router + react-router-redux broke

### ISSUE THREAD

**Issue by normalser** [DefinitelyTyped/DefinitelyTyped#14511]
Typings got updated to the latest:

```
├── @types/react-router@2.0.47 
├── @types/react-router-redux@4.0.40 
```

and now it throws an error:

```
node_modules/@types/react-router-redux/index.d.ts(9,10): error TS2305: Module 
'"node_modules/@types/react-router/index"' has no exported member 'Location'
```

**Comment by mxl** [comment]
react-router-redux@4 uses react-router@3
There is definitions for react-router@3 available https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-router/v3

I think this issue is outdated and can be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
