### ISSUE TITLE
Types don't seem to be working with @types/nedb

### ISSUE THREAD

**Issue by marcusjwhelan** [DefinitelyTyped/DefinitelyTyped#14516]
- [ x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @reppners Stefan Steinhart. 

I am working on a package that is purely nodejs using commonjs and I don't seem to get any support from the @types/nedb package. If a moderator or admin could look at the file and possibly point out errors or point me in the right direction to pull that down and make edits and send out a pull request the nedb package.

**Comment by marcusjwhelan** [comment]
None of the interfces are exported. There is no export of the Cursor or Exec. It would be nice if parts of the types were exported to use besides nedb datastore.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
