### ISSUE TITLE
@types/facebook-js-sdk

### ISSUE THREAD

**Issue by Serginho** [DefinitelyTyped/DefinitelyTyped#14528]
```ts
    interface AuthResponse {
        status: string;
        authResponse: {
            accessToken: string;
            expiresIn: number;
            signedRequest: string;
            userID: string;
        };
    }
```

authResponse has grantedScopes param when use FB.login(() => {}, {return_scopes: true), so the correct object is:

```ts
    interface AuthResponse {
        status: string;
        authResponse: {
            accessToken: string;
            expiresIn: number;
            grantedScopes: string;
            signedRequest: string;
            userID: string;
        };
    }
```

**Comment by hinell** [comment]
You're free to open PR

**Comment by glen-84** [comment]
Shouldn't this be closed?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
