### ISSUE TITLE
Published packages don't contain LICENSE file.

### ISSUE THREAD

**Issue by krotscheck** [DefinitelyTyped/DefinitelyTyped#14533]
- [ x ] I tried using the `@types/c3` package and had problems.

Our typescript-based project is currently going through legal review, and none of the published @types tarballs contain the MIT license file. Could you please add it?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
