### ISSUE TITLE
Leaflet and GeoJson version dependencies

### ISSUE THREAD

**Issue by sroucheray** [DefinitelyTyped/DefinitelyTyped#14542]
- [x] I tried using the `@types/leaflet` package and had problems.
It seems latest versions of @types/leaflet (namely 1;0.51, 1.0.52) require last version of @types/geojson (1.0.0).

Trying to use @types/leaflet 1.0.52 with @types/geojson 0.30 produces this kind of errors:
```
node_modules/@types/leaflet/index.d.ts:692:87 
    Type 'GeometryCollection | MultiPoint' does not satisfy the constraint 'GeometryObject'.
  Type 'GeometryCollection' is not assignable to type 'GeometryObject'.
    Property 'coordinates' is missing in type 'GeometryCollection'.
```
package.json of @types/leaflet does not enforce this version dependency by using *:
```
...
"dependencies": {
    "@types/geojson": "*"
  }
...
```

Is it possible to update @types/leaflet to enforce version dependencies.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
