### ISSUE TITLE
error in @types/react-router v.3.0.3

### ISSUE THREAD

**Issue by mziraki** [DefinitelyTyped/DefinitelyTyped#14575]
- [x] I tried using the `@types/react-router` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @sergey-buturlakin @mrk21 @vasek17 @ngbrown @awendland @KostyaEsmukov @johnnyreilly @LKay

problem:
 error  in path\to\project\node_modules\@types\react-router\lib\Router.d.ts

(4,5): error TS2305: Module '"path/to/project/node_modules/@types/history/index"' has no exported member 'Hash'.

there is no Hash in history definition but in Router.d.ts:

import {
    Action,
    Hash, <---- this line
    History,
    Href,
    LocationKey,
    LocationState,
    Path,
    Pathname,
    Search
} from "history";

**Comment by etienne-dldc** [comment]
If anyone is interested, I have solved the problem by adding the last version of `@types/history` to `package.json` then delete `node_modules` and re-install.

Hope it will work for you as it did for me. ❤️

**Comment by LKay** [comment]
This should be already resolved after https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14587 was merged. The reason was, `react-router@3` depends on `history@3`nut definitions for `history@4` was used.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
