### ISSUE TITLE
@types/angular-ui-bootstrap

### ISSUE THREAD

**Issue by jsmarsch** [DefinitelyTyped/DefinitelyTyped#14630]
I tried using the types/angular-ui-bootstrap package, and now I have tons of build errors along the lines of:
"Build" duplicate identifier 'angular'
these are being raised from the angular-animate index.d.ts (which was fine before I imported angular-ui-bootstrap)

I also get the error:
Buile: Module 'angular.ui' has no exported member 'bootstrap' these errors are in the actual angular-ui-bootstrap index.d.ts file -- sorry, but I really don't understand what's happening here.

My setup:
we use typings to pull our definintions (we are on typescript 1.8.10

if I uninstall the angular-ui-bootstrap typings, everything works (we have over a dozen or so typings packages installed, and no problems, so I _think_ my configuration is ok. 

Is there something wrong with the typings, or is there something I should look at on my end?

I don't know whether this helps, but typings installed the angular-bootstrap-ui definitions under typings/modules, but all of the other angular-* typings were installed under typings/globals.  I have to confess, I do not understand the rhyme or reason behind what goes into the /globals folder or the /modules folder, so maybe that is part of the problem?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
