### ISSUE TITLE
Not able to import Evaporate

### ISSUE THREAD

**Issue by leolorenzoluis** [DefinitelyTyped/DefinitelyTyped#14634]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kookster, @chrisrhoden

Trying to import evaporate typed definition with angular cli.

but I get 
/node_modules/@types/evaporate/index"' resolves to a non-module entity and cannot be imported using this construct.

**Comment by kookster** [comment]
That definition is over a year old, so it wouldn't surprise me if it isn't working with the latest, but in case it helps, we're using this successfully here:

https://github.com/PRX/publish.prx.org/blob/master/src/app/core/upload/upload.service.ts#L3

**Comment by leolorenzoluis** [comment]
I tried your example too, but I get

Module ''evaporate'' has no default export

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
