### ISSUE TITLE
node_modules\@types\loadash\index.d.ts : error TS1005: ';' expected.

### ISSUE THREAD

**Issue by sireeshaB** [DefinitelyTyped/DefinitelyTyped#14670]
node_modules\@types\loadash\index.d.ts : error TS1005: ';' expected.

While running gulp server, getting errors like above. Can anyone help me to resolve this issue?
Thanks in advance.
following are the versions list:
node -v --  v7.4.0
npm -v--    v3.10.10
tsc -v  --     v2.1.4
tsd --version --  0.6.5

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
