### ISSUE TITLE
Expose DraftEditorProps in draft-js definitions

### ISSUE THREAD

**Issue by mattoni** [DefinitelyTyped/DefinitelyTyped#14691]
@eelco would it be possible to expose the  DraftEditorProps interface in the definitions? I'm trying to build a wrapper for the Editor with some default functionality, but want to still be able to pass through the default editor props via spread operator.

Thanks!

**Comment by willisplummer** [comment]
These are exported as `EditorProps` [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/draft-js/index.d.ts#L908). Looks like this issue can be closed @mattoni :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
