### ISSUE TITLE
@types/assert throws exception

### ISSUE THREAD

**Issue by streamcode9** [DefinitelyTyped/DefinitelyTyped#14708]
- [x] I tried using the `@types/assert` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention] the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @vvakame

I have next file:
```ts
// index.ts
import { assert } from 'assert'
```
Run next command: `tsc index.ts`

I've got next exception: "index.ts(1,24): error TS2306: File 'D:/1/node_modules/@types/assert/index.d.ts' is not a module."

If I change
```ts
declare function assert(value:any, message?:string):void;
declare namespace assert {
...
}
```
to
```ts
declare module 'assert' {
	function assert(value:any, message?:string):void;
        ...
	export = assert
}
```
it works fine.
Additional information https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
