### ISSUE TITLE
[@types/openlayers] 3.18 ol.interaction.SelectEvent -> 3.19+ ol.interaction.Select.Event

### ISSUE THREAD

**Issue by kolja2** [DefinitelyTyped/DefinitelyTyped#14732]
- [ ] I tried using the `@types/openlayers` package and had problems.
- Authors: @osechet, (@achimha)

It seems, that from OpenLayers 3.18 to 3.19 the following was changed:
- 3.18: ol.interaction.**SelectEvent**
- 3.19 ol.interaction.**Select.Event**

Current version (4.0.1) of DefinitelyTyped/openlayers/index.d.ts (https://github.com/achimha/DefinitelyTyped/commit/ab494ae5d1ee13a845819cd0fafcb80c44cdd380) shows
`5567: class SelectEvent extends ol.events.Event {`

while openlayers/src/ol/interaction/select.js (https://github.com/openlayers/openlayers/blob/master/src/ol/interaction/select.js) shows
`391: ol.interaction.Select.Event`

so the types don't match once ol.interaction.Select.Event is used with TypeScript (ol.interaction.SelectEvent seems only to be usable till <3.19)

(I'm new to github so don't have a proper clue yet, how to handle that stuff.)

**Comment by osechet** [comment]
@kolja2 Feel free to fork the DefinitelyTyped repo and update the file according to the new documentation. Then open a pull request (PR) that will be verified before integration into the main repo.

**Comment by kolja2** [comment]
@osechet I'll give it a try as soon as possible.

**Comment by kolja2** [comment]
PR at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14741.

Don't know, how to connect PR and this issue.

**Comment by jhwegener** [comment]
This issue could be closed since types are now released for v4.0.1, or?

**Comment by osechet** [comment]
Can we close this issue?

**Comment by jhwegener** [comment]
think so, I have currently no problems with that.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
