### ISSUE TITLE
_.reduce doesn't work without supplying accumulator

### ISSUE THREAD

**Issue by wheelerlaw** [DefinitelyTyped/DefinitelyTyped#14758]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar

From: https://github.com/lodash/lodash/issues/3019

The signature of `_.reduce` indicates that the accumulator is an optional argument. However, in TypeScript, not supplying the accumulator results in the compiler throwing an error:

```
Type '{}' is not assignable to type 'number'.
```

Here is an example: 
```
let numbers: number[] = [1, 2, 3];
let result = _.reduce(x, (accum, value, idx, coll) => value + accum);
```

As soon as I provide a value for the accumulator, the error goes away.

**Comment by aj-r** [comment]
Maybe we need to add some new overloads to `reduce` that assume `TResult` is the same as `T`, so type inference works correctly for the first argument.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
