### ISSUE TITLE
Incorrect Chrome definitions

### ISSUE THREAD

**Issue by NN---** [DefinitelyTyped/DefinitelyTyped#14763]
[This](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/df23346707493018518e7c8cd04d7e6e7dce1f05) commit removed 'url' from chrome.webNavigation filters which is valid according to the spec:

https://developer.chrome.com/extensions/webNavigation
https://developer.chrome.com/extensions/events#filtered
```js
      chrome.webNavigation.onCommitted.addListener(function(e) {
        // ...
      }, {url: [{hostSuffix: 'google.com'},
                {hostSuffix: 'google.com.au'}]});
      
```

https://chromium.googlesource.com/chromium/chromium/+/master/chrome/common/extensions/api/web_navigation.json

  - Authors:  @sreimer15

**Comment by epicgirl1998** [comment]
i ran into this too and i hope someone who knows git better than me can revert it, or someone who knows typescript better than me can fix it

i can't find any mentions of a `urls` property in the documentation pages you linked which suggests that the pull request removed the types for the documented way to filter webNavigations (using the `url` property) and added them for an undocumented one

i noticed this about the added test too:

```javascript
chrome.webNavigation.onBeforeNavigate.addListener(function (requestDetails) {
    // ...
},{urls: ["http://*/*"], types: ["image"]});
```

* there's a `types` property from the `chrome.webRequest` api ([docs](https://developer.chrome.com/extensions/webRequest)) in the filter here that isn't mentioned in the docs you linked, and doesn't seem to be doing anything here (the callback is still called for all navigations, not just images)
* (minor nitpick: the callback parameter is named `requestDetails` even though it's the details for a navigation, not a request)

my opinion on the change: it seems like someone forgot to read the docs and assumed the `chrome.webNavigation` api is just another `chrome.webRequest`

i hope i didn't get anything wrong because that would be embarrassing
