### ISSUE TITLE
No initialize() function in L.Class definition

### ISSUE THREAD

**Issue by mikhailshilkov** [DefinitelyTyped/DefinitelyTyped#14808]
- [X] I tried using the `@types/leaflet` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] Authors: @alejo90

When creating a new leaflet control in typescript, I call something like 

```
export var MyThing = L.Polyline.extend({
  initialize: function (latlngs: L.LatLngBoundsExpression, corridor: number, options?: L.PolylineOptions): void {
    L.Polyline.prototype.initialize.call(this, latlngs, options);
```

which gives a typescript error because `initialize` is not in type definitions.

Such usage is described in the documentation:
http://leafletjs.com/reference-1.0.3.html#class

Any reason why it's not defined yet?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
