### ISSUE TITLE
react-redux MapStateToProps should probably have two interfaces

### ISSUE THREAD

**Issue by ProTip** [DefinitelyTyped/DefinitelyTyped#14824]
```ts
interface MapStateToProps<TStateProps, TOwnProps> {
    (state: any, ownProps?: TOwnProps): TStateProps;
}
```

I believe if the component takes props they will be required so the optional ```ownProps?``` is a bit inconsistent.

Should we change to two interfaces?

```ts
interface MapStateToProps<TStateProps, TOwnProps> {
    (state: any): TStateProps;
}

interface MapStateToProps<TStateProps, TOwnProps> {
    (state: any, ownProps: TOwnProps): TStateProps;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
