### ISSUE TITLE
I'm a Typescript newbie. trying to use it on a medium-sized project. I'm using VS 2015 and bower for all client side Package management. I have installed DefinitelyTyped through bower, but it has around 2000 folders for various plugins.  Is there a way I can used DefinitelyTyped but with only the required plugin sets? Can I delete off plugins which i do not need?Will get an dependency issues?

### ISSUE THREAD

**Issue by rajgeo** [DefinitelyTyped/DefinitelyTyped#14830]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

**Comment by mhegazy** [comment]
DefinitelyTyped is a repository for **all** definition files available. Cloning the whole repo is probably not what you want.

All the definition files on definitely Typed are available under npm under `@types` organization.

So i would recommend you first identify what definition packages you need, then install them directly. for example: `npm install @types/lodash`.

You might find the documentation on http://www.typescriptlang.org/docs/handbook/declaration-files/consumption.html helpful.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
