### ISSUE TITLE
Errors in node definition

### ISSUE THREAD

**Issue by JirkaDellOro** [DefinitelyTyped/DefinitelyTyped#14842]
In the latest (for Node.js v7.x API) node definition file

I get three reports for "type-expected" (line numbers of the raw file)

81:         parent: NodeModule | null;
284:       setEncoding(encoding: string | null): this;
4017      type DoesZapCodeSpaceFlag = 0 | 1;

**Comment by JirkaDellOro** [comment]
and one here
 70:         main: NodeModule | undefined;

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
