### ISSUE TITLE
Recursive definition for ReactNode

### ISSUE THREAD

**Issue by markboyall** [DefinitelyTyped/DefinitelyTyped#14846]
In the React.d.ts, there's a comment about how ReactNode cannot be recursive, but this isn't true. A type alias cannot be recursive, but it can include an interface that references it, such as in the following:

```
    type ReactText = string | number;
    type ReactChild = ReactElement<any> | ReactText;

    interface ReactNodeArray extends Array<ReactNode> { }
    type ReactNode = ReactChild | boolean | ReactNodeArray;
```

It would be good if the React.d.ts from this repository was updated with this.

**Comment by andy-ms** [comment]
Try making a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
