### ISSUE TITLE
L.MarkerOptions property 'icon' type and setIcon method should also accept type L.DivIcon

### ISSUE THREAD

**Issue by dnasir** [DefinitelyTyped/DefinitelyTyped#14853]
- [x] I tried using the `@types/leaflet` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alejo90 

Referring to lines [L1316](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4869992bc079b88280b9ff91213528904109e8ae/leaflet/index.d.ts#L1316) and [L1331](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4869992bc079b88280b9ff91213528904109e8ae/leaflet/index.d.ts#L1331) they should both accept type ``L.DivIcon`` as demonstrated on the documentation page here: http://leafletjs.com/reference-1.0.3.html#divicon

This is currently causing build errors unless you cast them to type ``L.Icon``.

**Comment by alejo90** [comment]
It was fixed and approved in #14750 but hasn't been merged.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
