### ISSUE TITLE
Module @types/react has no exported member TransitionGroupProps

### ISSUE THREAD

**Issue by ArtemZag** [DefinitelyTyped/DefinitelyTyped#14865]
- [x] I tried using the `@types/react-addons-transition-group@15.0.1` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: Asana <https://asana.com>, AssureSign <http://www.assuresign.com>, Microsoft <https://microsoft.com>

It works fine for 'types/react@15.0.8'. But the problem appears when I update '@types/react' to version 15.0.12. 

![image](https://cloud.githubusercontent.com/assets/1687370/23330513/315cb724-fb58-11e6-9686-216f8493f73f.png)

**Comment by patsissons** [comment]
almost certainly your `@types/react-addons-transition-group` module is at `0.14.0`, upgrade to the latest `15.0.0` version and your issue should go away.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
