### ISSUE TITLE
Typescript 2.2 support

### ISSUE THREAD

**Issue by timjacobi** [DefinitelyTyped/DefinitelyTyped#14871]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

Hi. I just finished creating a definition which uses the new `object` type introduced in _2.2_. Could you please let me know how I can get `npm test` passing or what other type I should use in the meantime?

Thanks!

**Comment by c7hm4r** [comment]
The instructions for creating a pull request seem actually to be contradictory at this point. The [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#edit-an-existing-package) states you should do `npm install -g typescript@2.0`. The checklist for pull requests says "Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes)", where you are instructed to "follow advice from the [handbook](http://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)", which says "Instead of `Object`, use the non-primitive `object` type (added in TypeScript 2.2)."

in my opinion, backwards compatibility is more important than using `object`. So I would align to TypeScript 2.0.

**Comment by timjacobi** [comment]
Thanks.  How would you do it in 2.0 then? Use `{}`?

**Comment by c7hm4r** [comment]
[{} and Object seem to be practically equivalent.](http://stackoverflow.com/q/21396195) It’s a matter of taste, I think.

**Comment by c7hm4r** [comment]
… but I am no TypeScript expert!

**Comment by timjacobi** [comment]
Hey guys, what is the status on this?

**Comment by c7hm4r** [comment]
I found that once but did not find this GitHub issue again until now: https://blog.mariusschulz.com/2017/02/24/typescript-2-2-the-object-type

Essence, enriched with findings in my IDE:
- `object` represents any non-primitive type (that's not valid: `let x: object = 4`)
- `Object` is the interface for non-primitive JavaScript objects. So custom interfaces can extend `Object` but not `object`. VS Code suggests `Object`'s methods only if the interface of the object extends `Object`, but you can actually use these methods anywhere except on `null` or `undefined`. If you write `let x: Object` tslint warns "Don't use 'Object' as a type. Avoid using the `Object` type. Did you mean `object`? (ban-types)".
- `{}` is similar to `Object`, but `interface IThing extends {}` is not valid. `let x: {} = 4` is accepted by tslint. VS Code does not suggest `Object`'s methods on `x`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
