### ISSUE TITLE
MapLayer and MapComponent are missing in `@types/react-leaflet`

### ISSUE THREAD

**Issue by fangpenlin** [DefinitelyTyped/DefinitelyTyped#14872]
- [x] I tried using the `@types/react-leaflet` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @danzel

**Comment by danzel** [comment]
OIC, I missed them as there were no examples in the `react-leaflet` repository for them.
Feel free to add :)

https://github.com/PaulLeCam/react-leaflet/blob/master/src/MapLayer.js
https://github.com/PaulLeCam/react-leaflet/blob/master/src/MapComponent.js

Looks like `MapLayer` is the class that Layers on the map inherit from (example: LayerGroup).

And it looks like `MapComponent` is the class that everything that goes on the `<Map>` inherits from. (except controls)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
