### ISSUE TITLE
@types/mongoose: Property 'renameCollection' does not exist on type 'Collection'

### ISSUE THREAD

**Issue by denghuiquan** [DefinitelyTyped/DefinitelyTyped#14886]
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a similar question that is inappropriate for [StackOverflow](http://stackoverflow.com/questions/41604265/property-mapreduce-does-not-exist-on-type-collectionany).  (Please ask any appropriate questions there).

**Comment by denghuiquan** [comment]
I found that the `rename` in the`Collection`, and `renameCollection` in the Db, but the mongoose doc show us that the `renameCollection` should be property of `Collection`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
