### ISSUE TITLE
Incorrect type info for rewriters in LoggerOptions of winston

### ISSUE THREAD

**Issue by nvdbleek** [DefinitelyTyped/DefinitelyTyped#14891]
- [x] I tried using the `@types/winston` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bonnici and @codeanimal

The type of rewriters in LoggerOptions is `TransportInstance[]` I think that this should be `MetadataRewriter[]`. (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/winston/index.d.ts#L241)

**Comment by DABH** [comment]
@nvdbleek As far as I can tell this is resolved in the latest version of the typings for winston; see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/winston/index.d.ts#L238 .  Please close this issue if you agree that it looks good now?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
