### ISSUE TITLE
marker.setIcon(divIcon) throws error

### ISSUE THREAD

**Issue by gmfun** [DefinitelyTyped/DefinitelyTyped#14892]
- [X ] I tried using the `@types/leaflet` package and had problems.
- [X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @alejo90 

```javascript
let divIcon = L.divIcon({html: ""})
let m = L.marker([], {icon: DivIcon}) // this throws error
```

Posible solution
```javascript
export class Marker extends Layer {
  ...
  setIcon(icon: Icon | DivIcon): this
}
```

**Comment by alejo90** [comment]
It was fixed and approved in #14750 but hasn't been merged.

**Comment by gmfun** [comment]
Using this with angular/cli... Compilation break because of this. It would greatly help if us if this pr is merged. Thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
