### ISSUE TITLE
@types/globalize: globalize/index.d.ts is not a module

### ISSUE THREAD

**Issue by noemi-salaun** [DefinitelyTyped/DefinitelyTyped#14894]
- [X] I tried using the `@types/globalize` package and had problems.
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @gcastre <https://github.com/gcastre/>
  - Authors: @aram <https://github.com/afromogli/>

In the [Globalize documentation](https://github.com/globalizejs/globalize#getting-started), there is
```js
var Globalize = require( "globalize" );
```

but when I try to do
```ts
import * as Globalize from "globalize";
// OR
import Globalize = require("globalize");
```
I have the error : `@types/globalize/index.d.ts is not a module`.

But if I ignore the error, it works in runtime.

**Comment by andy-ms** [comment]
Here's what to do:

* Delete `declare var Globalize: GlobalizeStatic;`.
* Move all the interfaces into:
```ts
declare namespace globalize {
    interface DateFormatterOptions { ... }
    ...other interfaces...
}
```

* Delete `/// <reference types="cldrjs" />` and use:
```ts
declare var globalize: globalize.Static;
export as namespace Globalize;
export = globalize;
```

You should now be able to `import Globalize = require("globalize");`.
Also, could you fix the tests? Apparently they were commented out in #4872. No idea what they should be like now since they don't work any more.

**Comment by jbcpollak** [comment]
Just ran into this

**Comment by RobertKitzing** [comment]
me too, can someone fix this in the npm package?
