### ISSUE TITLE
[d3] Minor versions no longer pinned (package.json)

### ISSUE THREAD

**Issue by tomwanzek** [DefinitelyTyped/DefinitelyTyped#14925]
@andy-ms The `package.json` stub we had until recently used to pin the minor version of the **d3* standard bundle definitions to the corresponding minor versions of the constituent D3 module definitions was recently removed.

[see commit here](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/728bd4841d611d463af5304a88ac39ec2fdad70a)

By implication, if someone wants to pull an older version of the **d3** definitions, e.g. d3@4.3, to match their actual d3 module version, they are receiving the _latest_ minor version definitions for the constituent D3 modules.

These may contain additional features, only added with e.g. d3 4.4.

Is there an alternative to avoid this issue, or can we re-introduce the stub `package.json`?

Thanks for a quick response, we have a couple of minor version changes to `d3-geo` which would run into exactly the above scenario. (see #14756 and #14831)

cc @gustavderdrache @ledragon

**Comment by andy-ms** [comment]
It sounds like what you want is for path mapping to work for minor versions instead of just major versions.  But we decided against it:

* Minor version changes in a package should be backwards-compatible, so it shouldn't break existing code to upgrade.
* Older defintions are almost always not maintained. `@types/foo@1.5` will be more accurate than `@types/foo1.4`, even for people still on version `foo@1.4`.
* It's not such a big deal if a type definition has a function that's missing as runtime. It's a bigger deal if it's missing a function that's present at runtime, because then working code won't compile. Since later versions of a definition will fill in more functions as more people contribute, later is better.
* We don't want to keep around every minor version of every package. And we don't want the maintenence overhead of updating a package's dependencies on every minor version update of a dependency.

(These reasons don't apply to major version updates since those can change the shape of the API entirely.)

So, just make the updates to `@types/d3-geo` and let existing `@types/d3` users pull it in.

**Comment by tomwanzek** [comment]
I understand where you are coming from, i.p historically with other definitions in DT. I suppose, I am being somewhat aspirational on at least the minor version correspondence of the d3 bundle vs the constituent modules.

There simply a part of me that revolts a little, when an IDE autocomplete suggestion contains object members, which will lead to runtime errors, while compiling just fine. It seems anathema to the cognitive model of TypeScript.

The D3 scenario strikes me as different from others as we are dealing with a straight-through re-export of the pinned constituent modules. This is very different from a definition, which simply imports other module dependencies for internal use.

My concern is the mental jump someone has to make from using say d3@4.4 with @types/d3@d4.4 to noticing a minor version disconnect on say **d3-hierarchy** under the hood. It means simply running into a runtime error.

**Comment by tomwanzek** [comment]
P.S. so far the only "complication" with the `package.json` maintenance for **d3** was the two-step process:
* merge/publish PR on constituent module to new minor version
* submit follow-up PR to update `package.json`stub for **d3** and bump its minor version
Not the biggest of efforts though...

**Comment by tomwanzek** [comment]
Closing this for now, may have to reopen, if definition consumers report issues with minor version disconnects.
