### ISSUE TITLE
[Question] Relation of `@types\` packages versions  to their original libraries

### ISSUE THREAD

**Issue by tugberkugurlu** [DefinitelyTyped/DefinitelyTyped#14940]
How does the versions of `@types` packages related to the version of the original libraries? For example: https://www.npmjs.com/package/@types/chai package seems to be on version `3.4.35` but latest chai version is `3.5.0`. Does that mean that `@types/chai` package is old?

**Comment by rharriso** [comment]
Is there some documentation or guidance on this issue?

**Comment by apexskier** [comment]
This is [documented in the README](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library) today.

(I think this issue can be closed)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
