### ISSUE TITLE
react-redux @connect

### ISSUE THREAD

**Issue by PavelPolyakov** [DefinitelyTyped/DefinitelyTyped#14941]
Hi,

I must say I'm new to typescript, but I try to use it with React and Redux.

I met the next case, here I'm trying to use the decorator `@connect` together with my component:
```javascript
@autobind
@connect((store) => {
    return {
        states: store.states
    };
})
export default class Index extends React.Component<any, any> {
    componentWillMount() {
        this.props.dispatch(loadStates())
    }
    render() {
        return (
            <section className="container">
                <h1>Webpack React</h1>
                <div className="panel panel-default">
                    hello
                </div>
            </section>
        )
    }
}
```

During the compilation the error appears:
```
ERROR in ./app/pages/Index.tsx
(8,1): error TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass<{}>' is not assignable to type 'typeof Index'.
    Type 'Component<{}, ComponentState>' is not assignable to type 'Index'.
      Property 'componentWillMount' is missing in type 'Component<{}, ComponentState>'.
```

In case I will remove the `componentWillMount` method from the component - there is no error.

After that, I've tried to apply the `connect` as a function call, like this:
```javascript
@autobind
class Index extends React.Component<any, any> {
    componentWillMount() {
        this.props.dispatch(loadStates())
    }

    render() {
        return (
            <section className="container">
                <h1>Webpack React</h1>
                <div className="panel panel-default">
                    hello
                </div>
            </section>
        )
    }
}

export default connect((store) => {
    return {
        states: store.states
    };
})(Index);
```

This works fine, no errors during the compilation.

I really want to use decorators as long as I can. Unfortunately the produced error doesn't ring a bell to me :) I would be glad in case somebody can point me to the right direction.

pinging @tkqubo, @jgillich as I saw you helped in the similar topic:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/6237

Let me know if I can provide more information.

Regards,

**Comment by PavelPolyakov** [comment]
Hi @ericanderson, @sandersn, @rockmacaca, @RyanCavanaugh ,

Possibly you can point me to the right direction or share your view on the issue?

**Comment by ericanderson** [comment]
I'm not sure without a full sample. In the second case your call to connect happens after autobind. 

For questions your best off on stackoverflow though. Can you produce a sample project with your node modules included?

**Comment by PavelPolyakov** [comment]
Hi @ericanderson , thanks for answering.
I think the issue is connected with the definitions themselves, so created it here.

Here is the full example:
https://github.com/PavelPolyakov/webpack-typescript-react

in the file https://github.com/PavelPolyakov/webpack-typescript-react/blob/master/app/components/States.tsx , as soon as you uncomment the `@connect` part - you'll see the error.

![image](https://cloud.githubusercontent.com/assets/839290/23544464/6f1d89fa-fff7-11e6-92c5-d228e63d71bd.png)

Regards,

**Comment by rockmacaca** [comment]
+1 for trying SO, but we're helpful people too ; ). I would avoid using `connect` as a class decorator, the typings around connect are kind of broken because of the way TypeScript handles them. In summary, `@connect` mutates the class by creating a wrapper component that is parametrized with types that differ from the target class, which TypeScript doesn't support. You can read more on this in #9951.

The currently typings try to mitigate this issue by overloading the of `connect()` with no arguments to infer loose types for the wrapped class. However, this breaks once you try to use `@connect` with one or more arguments. I'm actually using my own set of typings for react-redux in my own personal projects, but I can't submit a PR here since it breaks too many things for people that rely on the loose typings.

[I've put my own typings in a gist here](https://gist.github.com/rockmacaca/5ee4a0eb7a70319c652916ef15e9be27) for anyone else that stumbles into this, so feel free to use them. Basically, if you'd like to use `@connect` as a decorator, you just include a single type parameter containing the merged props. Because of TS's limitations, you'll have to make the State and Dispatch props you define there optional or else it will complain about missing properties when you try to use the component in JSX.

**Comment by PavelPolyakov** [comment]
hi @rockmacaca,

thank you for your suggestion. As you've mentioned, I also don't think using custom typings is an option in case we are talking not only about the pet projects, as this option is less scalable.

Bad thing that current TS state doesn't support that.

I've tried to put your typings here:
https://github.com/PavelPolyakov/webpack-typescript-react/tree/custom-react-redux

However have the same error.

Hope that this would be solved at some point of time :) For now indeed it doesn't seem that it worth to use `@connect` as decorator.

Regards,

**Comment by rockmacaca** [comment]
@PavelPolyakov I put in a PR in your repo with all the typings working correctly if you want to peek at that. I'm not really in charge here, but this should probably be closed as a duplicate of 9951.

**Comment by PavelPolyakov** [comment]
Thanks for the help, closing it.
