### ISSUE TITLE
[Request] add SSE (EventSource)

### ISSUE THREAD

**Issue by victornoel** [DefinitelyTyped/DefinitelyTyped#14957]
There exists one implementation already on github: https://github.com/yankee42/typescript-server-sent-events

But I think the author is not maintaining it anymore and so never submitted it here…

I can try to make a PR, but I'm not exactly sure if it is correct the way it currently is (for example originally an `EventSource` should extend an `EventTarget`, and stuffs like this).

**Comment by steveQuadros** [comment]
Looks like this has never gotten any steam. I'd be happy to contact @yankee42 or get his code into the repo to move this forward.

**Comment by yankee42** [comment]
Just two add my comment as the author of the implementation linked above:

I never took the time to work through the contribution guidelines for this project in detail, but the only reason I did not create a PR is that I was putting that off. If anyone wants to copy my implementation and create a PR, I am perfectly happy with that.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
