### ISSUE TITLE
Incorrect definition for node/dns.resolveTxt(...)

### ISSUE THREAD

**Issue by 3n-mb** [DefinitelyTyped/DefinitelyTyped#14967]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc, version 7.7.1 as of today.

There is an error in definition of dns.resolveTxt on [line 1855](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/index.d.ts#L1855):
returned value and `addresses`, given to a callback should be `string[][]` instead of `string[]`.
See [doc for this function](https://nodejs.org/api/dns.html#dns_dns_resolvetxt_hostname_callback), and node runs according it.

**Comment by 3n-mb** [comment]
PR #15043

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
