### ISSUE TITLE
@types/node : wrong property in options in fs.createWriteStream

### ISSUE THREAD

**Issue by abenhamdine** [DefinitelyTyped/DefinitelyTyped#14981]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: Microsoft according to file, but who should I ping ? 

Per docs (https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options), in options it's defaultEncoding and not encoding.
See L2602.

![image](https://cloud.githubusercontent.com/assets/7466144/23559496/7d5819fa-0037-11e7-9a33-0312951ce891.png)

And options could also be a string, so there should be a union type with a string.

**Comment by jtut1731** [comment]
If you look at the source, you will see that the option is "encoding".  I believe that the document is incorrect.  Did you try it?
https://github.com/nodejs/node/blob/master/lib/fs.js

**Comment by abenhamdine** [comment]
ohhh yes you're right. 
Looks like it's a nodejs doc issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
