### ISSUE TITLE
angular-material type expected

### ISSUE THREAD

**Issue by scriptsure** [DefinitelyTyped/DefinitelyTyped#14984]
- Authors: @rgthree @RyanCavanaugh @andy-ms 

Getting these issues when i go to compile the typescript. Any idea why?

/typings/modules/angular-material/index.d.ts(161,39): error TS1110: Type expected.
/typings/modules/angular-material/index.d.ts(176,34): error TS1110: Type expected.

Also since all the globals are removed i assume that we would replace this, for example:

`private $mdMedia: angular.material.IMedia,`

with this:

`private $mdMedia: material.IMedia,`

Is that correct? Why was this change necessary?

Aaron

**Comment by andy-ms** [comment]
Check your TypeScript compiler version. Looks like a parse error.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
