### ISSUE TITLE
@types/node: incorrect signature for net.Socket.destroy

### ISSUE THREAD

**Issue by 3n-mb** [DefinitelyTyped/DefinitelyTyped#14997]
Definition of [Socket.destroy in net](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/index.d.ts#L1906) has no parameters, while, according to [node v7.7 docs](https://nodejs.org/api/net.html#net_socket_destroy_exception), this method may take an exception.
When an exception is given, quote, an 'error' event will be emitted and any listeners for that event will receive exception as an argument, end of quote. So, this parameter isn't trivial for event firing, and def should be fixed.

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc, and a fresh types pack
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/), cause it is a bug, not a question.

**Comment by TonyPythoneer** [comment]
Please free to send a PR. Thanks.

**Comment by 3n-mb** [comment]
PR #15044

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
