### ISSUE TITLE
Improve @types/fb with TS union

### ISSUE THREAD

**Issue by colltoaction** [DefinitelyTyped/DefinitelyTyped#15006]
- Authors: @JoshStrobl, @apexskier, 

I'd like to propose some improvements to the `fb` typings. Based on Facebook's documentation, I figured out the only time `FB.login` response has an `authResponse` is when `status === "connected"`. Based on this information, I believe the following interfaces would better reflect the API, instead of the current `authResponse?: AuthResponse` member:

```ts
type LoginStatusResponse = LoginOkResponse | LoginNotAuthorizedResponse | LoginNotInFacebookResponse;

interface LoginNotAuthorizedResponse {
    status: "not_authorized";
}

interface LoginNotInFacebookResponse {
    status: "unknown";
}

interface LoginOkResponse {
    status: "connected";
    authResponse: AuthResponse;
}

interface AuthResponse {
    accessToken: string;
    expiresIn: number;
    signedRequest: string;
    userID: string;
}
```

**Comment by apexskier** [comment]
Makes sense to me!

**Comment by simeyla** [comment]
For anyone finding this issue now note that `@types/fb` is deprecated in favor of `@types/facebook-js-sdk`.

The equivalent to `fb.LoginStatusResponse` is now `fb.StatusResponse`

Here's the new types https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/facebook-js-sdk/index.d.ts

**Comment by cubuspl42** [comment]
@simeyla 
I'm quite confused about this whole Facebook SDKs situation. So `@types/fb` was never for [https://www.npmjs.com/package/fb](https://www.npmjs.com/package/fb)?

**Comment by apexskier** [comment]
At the time I worked on them, these types were actually called `fbsdk`, not `fb`. I did some quick digging, and the rename occurred as part of the major types reorganization https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4f7524fc65c0d1389af81a83a95dfe1ea59ad5e9#diff-1d2e9916e2d94ef0dbd0edf15e406ae4, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9739. The types originally were added in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/2136, and weren't associated with the `fb` package (which doesn't appear to be official in any way).

I'm guessing the `fb` naming was semi-unintentional and that yes, this was never for the `fb` package. If you want to contribute new types for the `fb` package, my guess would be that you should create a PR [as normal](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and since there's a major version bump, the `@types/fb` name will be fine to use (having the name historically apply to multiple packages seems less bad than creating a new non-standard name to me).

**Comment by apexskier** [comment]
@dt-bot, @typescript-bot This issue can be closed, I think, since the original `@types/fb` package is deprecated.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
