### ISSUE TITLE
Serialport typings not complete

### ISSUE THREAD

**Issue by hansmbakker** [DefinitelyTyped/DefinitelyTyped#15000]
- [x] I tried using the `@types/serialport` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @codefoster, maybe @fkloepf

The `byteDelimiter` and `byteLength` parsers are missing. I think
```
        static parsers: {
            byteDelimiter: (delimiter: number[]) => void,
            byteLength: (length: number) => void,
            readline: (delimiter: string) => void,
            raw: (emitter: any, buffer: string) => void
        };
```
should help but I'd like input from the author.

**Comment by fkloepf** [comment]
The bindings are not complete yet and I just fixed a few things. But I would suggest to create a pull request with these changes/additions.

**Comment by fttx** [comment]
SerialPort.list() doesn't work either

**Comment by codefoster** [comment]
Can y'all just add what's missing?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
