### ISSUE TITLE
@types/es6-shim missing 'Function.prototype.name'

### ISSUE THREAD

**Issue by JohnWeisz** [DefinitelyTyped/DefinitelyTyped#15038]
- [x] I tried using the `@types/es6-shim` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rbuckton 

I believe the following interface should belong to `es6-shim`:

```ts
interface Function {
    /** Returns the name of the function. */
    readonly name: string;
}
```

I've been ninja adding it myself for a year now, and it works (1) flawlessly with browsers that natively support it, (2) flawlessly with a `Function.prototype.name` polyfill, (3) according to spec.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
