### ISSUE TITLE
@types/fullcalendar is missing overloaded option method

### ISSUE THREAD

**Issue by thejewdude** [DefinitelyTyped/DefinitelyTyped#15047]
- [x] I tried using the `@types/fullcalendar` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nestalk @panic175 

According to the FullCalendar [docs](https://fullcalendar.io/docs/utilities/dynamic_options/) we can pass an options object to the option method to dynamically set many options at once. This overload is not in the current definition. 

The current definition only has this version:
```typescript
/**
* Get/Set option value
*/
fullCalendar(method: 'option', option: string, value?: any): void;
```
A possible solution is to also define this version:
```typescript
fullCalendar(method: 'option', options: Options): void;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
