### ISSUE TITLE
Definition Request: CucumberJS

### ISSUE THREAD

**Issue by rcollette** [DefinitelyTyped/DefinitelyTyped#1506]
https://github.com/cucumber/cucumber-js

**Comment by davidemannone** [comment]
I would need it too...

**Comment by lscordilis** [comment]
This would be really great. The syntax is not very friendly.

**Comment by tboyce** [comment]
+1
I have started one for myself but not being all that familiar with the cucumber API or how to write TypeScript definitions makes it very challenging. Is anyone else working on this?

**Comment by AbraaoAlves** [comment]
There is something wrong with PR #7167? @Diullei help us.

**Comment by vvakame** [comment]
:+1:

**Comment by Diullei** [comment]
:+1:  ;)

**Comment by laurelnaiad** [comment]
I would like to propose that the functions on the Hooks and StepDefinitions interfaces should be optional.

That way, we can use actual classes, inheritance, etc.

For instance, as is, I can't say

```
export class MyWorld {
  constructor() {
    var hooks = <cucumber.Hooks>this;
    hooks.registerHandler('AfterFeatures', function (event, callback) {
      // etc.
```

because MyWorld doesn't implement the actual Hooks interface.

But when I make the Hooks interface functions optional, the compiler becomes happy (note the question marks).

```
	export interface Hooks {
		Before?(code: HookCode): void;
		After?(code: HookCode): void;
		Around?(code: AroundCode):void;
		setDefaultTimeout?(time:number): void;
		registerHandler?(handlerOption:string, code:(event:any, callback:CallbackStepDefinition) =>void): void;
	}
```

Similarly for StepDefinitions, of course.

Thoughts?
