### ISSUE TITLE
TypeScript errors in @types/webcomponents.js

### ISSUE THREAD

**Issue by LosEagle** [DefinitelyTyped/DefinitelyTyped#15064]
When compiling Polymer with TypeScript, TS throws following errors in @types/webcomponents:

```
node_modules/@types/webcomponents.js/index.d.ts(58,14): error TS2403: Subsequent variable declarations must have the same type.  Variable 'shadowRoot' must be of type 'ShadowRoot', bu
t here has type 'ShadowRootPolyfill'.
node_modules/@types/webcomponents.js/index.d.ts(58,14): error TS2687: All declarations of 'shadowRoot' must have identical modifiers.
node_modules/@types/webcomponents.js/index.d.ts(70,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'customElements' must be of type 'CustomElemen
tRegistry', but here has type 'CustomElements'.
```

My TS version is 2.2.1
I'm using types/polymer for Polymer not polymer-ts.

**Comment by bravomikekilo** [comment]
The problem also appeared in building TensorFlow Tensorboard

**Comment by threezool** [comment]
I get the same issue when building in Visual Studio, a restart of VS helps but after a few more builds it fails again.

**Comment by TimLuq** [comment]
I also ran into this issue. My guess is if you are using a version of the library which already supports `Element.shadowRoot` and `Window.customElements` this is what happens.

It worked fine after just commenting out the two lines which causes this error in `node_modules/@types/webcomponents.js/index.d.ts`. (Lines 58 and 70)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
