### ISSUE TITLE
mongodb/index.d.ts line 883 wrong

### ISSUE THREAD

**Issue by FullTS** [DefinitelyTyped/DefinitelyTyped#15062]
Problem with this file:
[https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/mongodb/index.d.ts]()

***Line 883***
```ts
export interface FindOneAndReplaceOption {
    projection?: Object;
    sort?: Object;
    maxTimeMS?: number;
    upsert?: boolean;
    returnOriginal?: boolean;  //Line 883 Wrong
}
```

Should be modified to:
```ts
returnNewDocument?: boolean;
```

See the official document: 
[https://docs.mongodb.com/v3.2/reference/method/db.collection.findOneAndUpdate/]()

**Comment by wong2** [comment]
right

**Comment by dantehemerson** [comment]
The field was changed to `new` and the method doesn't exists. So i think this should be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
