### ISSUE TITLE
node.js domain#exit not defined TMK

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#15080]
Please see this issue:

https://github.com/Microsoft/TypeScript/issues/14480#issuecomment-284861641

thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
