### ISSUE TITLE
geolib has a declaration file by now

### ISSUE THREAD

**Issue by mightyiam** [DefinitelyTyped/DefinitelyTyped#15109]
https://github.com/manuelbieh/Geolib/blob/24b1ac5576e7f8e891b7dd59fa809c21ef4ae4b9/dist/geolib.d.ts

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
