### ISSUE TITLE
ServiceWorkerGlobalScope addEventListener

### ISSUE THREAD

**Issue by lucianobapo** [DefinitelyTyped/DefinitelyTyped#15123]
- [ ] I tried using the `@types/service_worker_api` 0.0.9 package and had problems.

Error:(738, 11) TS2430:Interface 'ServiceWorkerGlobalScope' incorrectly extends interface 'EventTarget'.
  Types of property 'addEventListener' are incompatible.
    Type '<K extends any, ServiceWorkerEventMap>(type: K, listener: (event?: ServiceWorkerEventMap[]) => an...' is not assignable to type '(type: string, listener?: EventListenerOrEventListenerObject, useCapture?: boolean) => void'.
      Types of parameters 'listener' and 'listener' are incompatible.
        Type 'EventListenerOrEventListenerObject' is not assignable to type '(event?: any[]) => any'.
          Type 'EventListener' is not assignable to type '(event?: any[]) => any'.
            Types of parameters 'evt' and 'event' are incompatible.
              Type 'any[]' is not assignable to type 'Event'.
                Property 'bubbles' is missing in type 'any[]'.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
