### ISSUE TITLE
intro.js in multilingual angular 2 page

### ISSUE THREAD

**Issue by peyman-ghasemi** [DefinitelyTyped/DefinitelyTyped#15138]
I am using the DefinitelyTyped library. I wanted to add some guide for my users using introjs
 it is okay when I write my guides in single language for example by this line : 
`<div data-step="1" data-intro="some text" >`

but when I try to have multilingual guides using ng2-translate , I get nothing. here is my code :

`<div data-step="1" data-intro=" 'dashboard.welcome' | translate " >`

in data-intro property, I have tested combination of {{ }} , " " or ' ' to see if the syntax is wrong but none of them solved my problem. I wonder if some one can help me .

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
