### ISSUE TITLE
assert.equal, check same type of actual and expected

### ISSUE THREAD

**Issue by roginvs** [DefinitelyTyped/DefinitelyTyped#15162]
I found with a surprise that `assert.equal` have both types as 'any' (even the strictEqual too):
```
export function equal(actual:any, expected:any, message?:string):void;
```
Why not do this way:
```
export function equal<T>(actual: T, expected: T, message?:string):void;
```
? It is better to catch any errors on compile time, not in the runtime, is not it?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
