### ISSUE TITLE
Issue in @types/q version 1.0.0

### ISSUE THREAD

**Issue by KirillArefev** [DefinitelyTyped/DefinitelyTyped#15187]
- [x] I tried using the `@types/q` package and had problems.
- [x] I tried using the latest stable version of tsc v2.2.1.
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] Authors: @bnemetchek, @AndrewGaspar, @johnnyreilly 

Looks like merge of PR #15161 introduced new issue:

`
Error at .../node_modules/@types/q/index.d.ts:187:5: Export declarations are not supported in namespace.
`
With version 0.0.32 everything works good.

Could anyone look at this issue please?

**Comment by mhegazy** [comment]
This is a fix to add `Q.try` definition, this has not been possible in the past because of a TypeScript bug (see https://github.com/Microsoft/TypeScript/issues/1784), the issue was fixed in TS 2.2, so if you are using TS2.1, you need to stick with `@types/q@0.0`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
