### ISSUE TITLE
cropperjs/cropperjs.d.ts is missing the methods: `zoomTo` & `rotateTo` and the event: `zoom`.

### ISSUE THREAD

**Issue by Phoenix359** [DefinitelyTyped/DefinitelyTyped#15199]
Also the 6 events must have different interfaces for the property: `detail`.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @stepancar

Please see: 
- https://github.com/fengyuanchen/cropperjs#zoomtoratio
- https://github.com/fengyuanchen/cropperjs#rotatetodegree
- https://github.com/fengyuanchen/cropperjs#zoom

NOTE: I already have created an index.d.ts where these issue's are fixed.
[index.txt](https://github.com/DefinitelyTyped/DefinitelyTyped/files/847297/index.txt)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
