### ISSUE TITLE
Service_worker_api problems

### ISSUE THREAD

**Issue by wiNgeRf0rN1ceE** [DefinitelyTyped/DefinitelyTyped#15197]
Guys help
When you run the project, a bunch of errors.(angular 2 quickstart template)
How to fix them?
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/b8f39ec65d8c9fa9286704b02a7d2515cd8de8c6/service_worker_api

Errors:
node_modules/@types/service_worker_api/index.d.ts(731,38): error TS1005: ',' expected.
node_modules/@types/service_worker_api/index.d.ts(733,58): error TS1005: ']' expected.
node_modules/@types/service_worker_api/index.d.ts(733,59): error TS1005: ')' expected.
node_modules/@types/service_worker_api/index.d.ts(733,60): error TS1131: Property or signature expected.
node_modules/@types/service_worker_api/index.d.ts(733,62): error TS1131: Property or signature expected.
node_modules/@types/service_worker_api/index.d.ts(735,5): error TS1131: Property or signature expected.
node_modules/@types/service_worker_api/index.d.ts(735,6): error TS1131: Property or signature expected.
node_modules/@types/service_worker_api/index.d.ts(814,38): error TS1005: ',' expected.
node_modules/@types/service_worker_api/index.d.ts(816,49): error TS1005: ']' expected.
node_modules/@types/service_worker_api/index.d.ts(816,50): error TS1005: ')' expected.
node_modules/@types/service_worker_api/index.d.ts(816,51): error TS1131: Property or signature expected.
node_modules/@types/service_worker_api/index.d.ts(816,53): error TS1131: Property or signature expected.
node_modules/@types/service_worker_api/index.d.ts(818,5): error TS1131: Property or signature expected.
node_modules/@types/service_worker_api/index.d.ts(818,6): error TS1131: Property or signature expected.

**Comment by idiotWu** [comment]
It requires typescript 2.1+, are you using any lower version?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
