### ISSUE TITLE
Issue in @types/elasticsearch

### ISSUE THREAD

**Issue by harikv** [DefinitelyTyped/DefinitelyTyped#15202]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @pushplay @mhegazy @jppelerin @bfsmith @ahmadferdous 

Is there any specific reason for using PromiseLike in the @types/elasticsearch definitions? 
This does not allow the usage of the then().catch() promise workflow

**Comment by pushplay** [comment]
Looking at what Elasticsearch does in Node the object it returns isn't an instance of `Promise` but it does have `then` and `catch`.  The Promise constructor can be configured but if the user chooses a worse class then that's their problem.

I'm in favour of it.  Any other opinions?

**Comment by pushplay** [comment]
Alrighty.  @harikv if you want to take the lead on this that would be cool.  Otherwise I can do it but I probably won't get to it for a few days.

**Comment by harikv** [comment]
Sure. I'll submit a PR.

**Comment by kosl90** [comment]
After looking at the source code, I find it returns Promise by default, here is the flow:
- In API definition(https://github.com/elastic/elasticsearch-js/blob/master/src/lib/apis/5_3.js#L5906), `ca` function(https://github.com/elastic/elasticsearch-js/blob/master/src/lib/apis/5_3.js#L1 ) is used.
~~~JavaScript
var ca = require('../client_action').makeFactoryWithModifier(function (spec) {
  return require('../utils').merge(spec, {
    params: {
      filterPath: {
        type: 'list',
        name: 'filter_path'
      }
    }
  });
});
~~~
- looking at https://github.com/elastic/elasticsearch-js/blob/master/src/lib/client_action.js#L68 which returns `transport.defer.promise`
~~~JavaScript
var def = this.transport.defer();
def.reject(e);
return def.promise;
~~~
- althrough `transport.defer` is configurable(https://github.com/elastic/elasticsearch-js/blob/master/src/lib/transport.js#L40), the default defer returns a Promise object indeed(https://github.com/elastic/elasticsearch-js/blob/master/src/lib/transport.js#L102).
~~~JavaScript
  var defer = {};
  defer.promise = new Promise(function (resolve, reject) {
    defer.resolve = resolve;
    defer.reject = reject;
  });
  return defer;
~~~

So, I prefer to use `Promise` instead of `PromiseLike`.

BTW, according to https://github.com/elastic/elasticsearch-js/blob/master/src/lib/client.js#L53, I also prefer that `Client` interface should have a `close` method.

**Comment by pushplay** [comment]
Quality research!  👍 

Looks like we still don't have a pull request on this issue.  Is that something you want to do @kosl90?

**Comment by kosl90** [comment]
@pushplay ok, I will try it.

**Comment by kosl90** [comment]
@pushplay I wonder which branch should I use?

**Comment by pushplay** [comment]
@kosl90 Fork the `master` branch and make your pull request back to it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
