### ISSUE TITLE
mathjax processSectionDelay and useGlobalCache not typed

### ISSUE THREAD

**Issue by shankarcse2010** [DefinitelyTyped/DefinitelyTyped#15234]
- [x] I tried using the `@types/mathjax` package and had problems.
- [x] I have seen processSectionDelay and useGlobalCache not typed on their corresponding interface, can please update those codes?

**Comment by andy-ms** [comment]
Make a pull request?

**Comment by shankarcse2010** [comment]
@andy-ms  I can't find index.d.ts files on the previous link
Link: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/mathjax

**Comment by andy-ms** [comment]
Clone the repo and `cd DefinitelyTyped/types/mathjax`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
