### ISSUE TITLE
Missing props on GeoJSON in @types/react-leaflet

### ISSUE THREAD

**Issue by estaub** [DefinitelyTyped/DefinitelyTyped#15299]
@danzel 

The props `style` and `onEachFeature`, and probably others, are missing from `GeoJSONProps`.

[GeoJSON](https://github.com/PaulLeCam/react-leaflet/blob/master/lib/GeoJSON.js) is really [poorly documented](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Components.md#geojson) in react-leaflet.
It turns out it supports (as in "it works") all (I think) of the options described in [leaflet GeoJSON](http://leafletjs.com/reference-1.0.0.html#geojson) as props.

I know that react-leaflet's GeoJSON supports `style` and `onEachFeature`.  My reading of the code (easily wrong!) is that any otherwise unrecognized props _in any react-leaflet component_ are passed through to leaflet as options, via a universally-invoked `getOptions()` method.  So if I'm correct, any component's `options` documented in leaflet should be included in the {SomeComponent}Prop interface - even if they aren't explicitly documented in react-leaflet.  There are probably a few exceptions somewhere, of course.

I'm not that experienced with all this, so I could easily have gotten something wrong.  You might want to consult with @PaulLeCam.

**Comment by danzel** [comment]
Make a PR and I'll review it :)

**Comment by estaub** [comment]
Turns out to be easier than I assumed, just add Leaflet.GeoJSONOptions as a base interface::
```
interface GeoJSONProps extends FeatureGroupProps, Leaflet.GeoJSONOptions {
    data: GeoJSON.GeoJsonObject;
}
```
Sorry, I've not done a PR before and don't want to start with one on DefinitelyTyped!

**Comment by danzel** [comment]
Hah ok. Will do this next week

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
