### ISSUE TITLE
[STRIPE] is not a module

### ISSUE THREAD

**Issue by jeusdi** [DefinitelyTyped/DefinitelyTyped#15303]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ahi @borisyankov @longzheng @ianschmitz @a904guy @amritk

I'm using this line in order to import `@types/stripe`:

    import * as Stripe from '@types/stripe';

I've also tried with:

    import * as Stripe from 'stripe';

I'm getting the message:

> [ts] File 'd:/projects/living/user-platform/project/node_modules/@types/stripe/index.d.ts' is not a module.

I'm using typescript 2.2.1.

Any ideas?

**Comment by jelling** [comment]
I'm struggling with the same issue. Are you trying to use stripe type definitions client-side or server-side? 

If server-side, the correct type package is actually "stripe-node", not "stripe", which is really the typings for Stripe.Js. 

However, I still haven't gotten the stripe-node typings to work. VSCode says that "index.d.ts" is not a module. But it looks like one when I review the file.

**Comment by jelling** [comment]
Think I've figured it out.

Short version: you don't need an import statement for the stripe-node package. You can just do this:

`let foo = Stripe.card;`

And you will get intellisense options for the object. 

Longer version: the reason for this is that stripe-node module does not export a module; it looks like it tries, but it doesn't seem to work. Perhaps typescript changed since they created the typing? 

Either way, when a type is not included in a module it is considered a global type. Lucky for us, TypeScript [automatically includes global types](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types). 

> By default all visible “@types” packages are included in your compilation. Packages in node_modules/@types of any enclosing folder are considered visible; specifically, that means packages within ./node_modules/@types/, ../node_modules/@types/, ../../node_modules/@types/, and so on.

**Comment by jeusdi** [comment]
Thanks @jelling. I'm trying to use it on client side. According to [this question](http://stackoverflow.com/questions/42951809/using-external-library-into-typescript-and-webpack-project) on stackoverflow and [this issue](https://github.com/swagger-api/swagger-codegen/issues/4397#issuecomment-288632159) it seems `@types/stripe` is outdated.

So the only solution is to add `<script>` tag reference on `index.html` and `import * as Stripe from 'stripe';` into your typescript code.

**Comment by jelling** [comment]
@stephenstroud Here's my client-side code that works for me:

```
    var handler = (<any>window).StripeCheckout.configure({
      key: '{yourkey}',
      locale: 'auto',
      allowRememberMe: false, 
      email: email, 
      token: function (token: any) {
        // You can access the token ID with `token.id`.
        // Get the token ID to your server-side code for use.
        console.log(token);
        onboard.checkout(token)
          .then((result)=> 
             // TODO: put whatever you want to happen after checkout
            );
      }
    });

    handler.open({
      name: 'XXX',
      description: 'YYYY',
      amount: 49900
    });
```

Because Stripe has no working type file at this point, we need to tell Typescript that the object exists. I do that in the first line via this code:

` (<any>window).StripeCheckout.configure({`

The "<any>window" makes Typescript aware of the Window object and  the "<any>" cast tells it that it's a generic object without known types. Accordingly, the TS compiler no longer balks about the ".StripeCheckout" part of the line because TS knows there's an object BUT also knows it doesn't know the structure of the object. I.e., we could also write "(<any>window).MadeUpFunction" and it wouldn't balk.

Alternately, the following will also work and look prettier:

`declare var StripeCheckout: any; // ambient declaration`

**Comment by stephenstroud** [comment]
@jelling Thanks so much for this, it has saved me a huge headache and works well. I went with (<any>window).

**Comment by galuszkak** [comment]
You don't have to import anything. If you have older TypeScript you probably need to include it in tsconfig.json in `types` section only.

There are now 2 packages `@types/stripe-v3` and `@types/stripe-v2`, so depeneding which version You use, or both you should include those. Intelisense should be out of box, as Stripe is global object.

I think this issue should be closed.

**Comment by ncaq** [comment]
I use `StripeCheckout` too.
But I get error message.
~~~
    ERROR in [at-loader] ./node_modules/@types/stripe-checkout/index.d.ts:6:23 
        TS2688: Cannot find type definition file for 'stripe/v2'.
    
    ERROR in [at-loader] ./node_modules/@types/stripe-checkout/index.d.ts:19:21 
        TS2304: Cannot find name 'StripeTokenResponse'.
~~~

I added `@types/stripe-checkout` and `@types/stripe-v2`.
What this?

**Comment by galuszkak** [comment]
@ncaq sounds need to be fixed. I will send Pull Request.

**Comment by galuszkak** [comment]
@ncaq I've submitted Pull Request here:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18243

Sorry for trouble.

**Comment by andy-ms** [comment]
@galuszkak Does that PR fix this issue? Good to close?

**Comment by galuszkak** [comment]
@andy-ms yes.

**Comment by bitgandtter** [comment]
Im getting this same error on v3.0.7 using angular 6 any advice or solution?

**Comment by galuszkak** [comment]
@bitgandtter You should use `@types/stripe-v2` or `@types/stripe-v3` not `@types/stripe` depend on which version You are using. ;)

**Comment by bartekchab** [comment]
quite long time without answer... but I'm still facing this issue. I'm using @types/stripe-v3.
@bitgandtter did you mange to solve that?

**Comment by bjornharvold** [comment]
I am using v3.0.8 with Angular 6.1.10 and Angular CLI v6.2.5 with Typescript and I have the same problem. 

My IntelliJ IDE finds the types  and wants to import objects in this unusual fashion: 
`import Source = stripe.Source. `
but that gives me the error: Cannot find namespace 'stripe';

It also cannot find 'Stripe' object to import.

I have tried all the different ways to import Stripe the way I import my other Typescript libraries but it doesn't want to be found.

I had to revert back to declaring Stripe:any and stripe:any in my typings file but that's not something I really want to do. 

At this point, I don't know what the @types/stripe-v3 library is good for because I cannot figure out how to use it. This has not been an issue with any other types I've used before unless the developer forgot to explicitly export / declare the classes.

#confused

**Comment by andy-ms** [comment]
The way the package `@types/stripe-v3` is declared now is that it declares a *global* variable `Stripe` and a global namespace `stripe` containing interfaces. You don't import it at all but just start using the `Stripe` variable directly.

**Comment by bjornharvold** [comment]
<img width="502" alt="screen shot 2018-10-13 at 12 12 43 pm" src="https://user-images.githubusercontent.com/641791/46901643-93f3ec00-cee1-11e8-851a-726cd9778398.png">
<img width="783" alt="screen shot 2018-10-13 at 12 13 15 pm" src="https://user-images.githubusercontent.com/641791/46901644-948c8280-cee1-11e8-830b-606063061960.png">
<img width="710" alt="screen shot 2018-10-13 at 12 16 31 pm" src="https://user-images.githubusercontent.com/641791/46901661-d87f8780-cee1-11e8-90aa-15201136f7a8.png">

Tried following your advice and not import anything. My IDE cannot find the variables. Angular CLI complains as well.

Could you attach a a working sample?

**Comment by andy-ms** [comment]
@bjornharvold Try `/// <reference types="stripe-v3" />` to ensure the types are included in the project.

**Comment by bjornharvold** [comment]
Thanks @andy-ms - For everyone else coming across this thread who is having issues getting Stripe types to work with Angular and Webpack:

`npm i --save-dev @types/stripe-v3`

Edit your tsconfig.app.json file and add:
```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/app",
    "module": "es2015",
    "types": [
      "stripe-v3"
    ]
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}
```

That's it. Now you can refer to Stripe such as this:
`const stripe: stripe.Stripe = Stripe('key');`

**Comment by schankam** [comment]
Yeah, adding the type in the tsconfig.app.json works ! Thanks @bjornharvold

**Comment by StefanRein** [comment]
Or just add typeRoots for future types:

```javascript
{
    "compilerOptions": {
        "typeRoots": [
            "./node_modules/@types"
        ]
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}

```

**Comment by minhphan1704** [comment]
ERROR in node_modules/ngx-stripe/lib/services/stripe.service.d.ts(20,24): error TS1144: '{' or ';' expected.
Please help me ti fix this bug. thanks
