### ISSUE TITLE
@types/lodash All declarations of 'WeakMap' must have identical type parameters

### ISSUE THREAD

**Issue by baywet** [DefinitelyTyped/DefinitelyTyped#15316]
- [x ] I tried using the `@types/lodash@4.14.57` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

Since version 4.14.57 came out, all our builds are breaking with the same error message.
`error TS2428: All declarations of 'WeakMap' must have identical type parameters`
Everything was fine with 4.14.56, only change reported on our source base/dependencies today.

**Comment by baywet** [comment]
CC @AviVahl

**Comment by AviVahl** [comment]
@types/lodash now requires ts2.2, as it uses the new `object` type, so that's probably why it fails.
I'm not sure how the auto publishing works here, but I thought it'll bump a major version of the typings. Perhaps one of the ms people around here can assist.
How can this be avoided? How does one bump the major version of a @types package?

**Comment by baywet** [comment]
Already using typescript 2.2.1, only have one version of @types/lodash (using npm here).
Nuking node_modules folder didn't fix the issue.
Here is what most of our tsconfig files look like: 
```
{
  "compilerOptions": {
    "target": "ES5",
    "sourceMap": true,
    "typeRoots": [ "node_modules/@types/" ],
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "declaration": false,
    "watch": true
  },
  "compileOnSave": true,
  "include": [
    "src/**/*"
  ],
  "exclude": [
    ".vscode",
    "node_modules",
    "dist"
  ]
}
```

**Comment by AviVahl** [comment]
Other types included is @types/lodash@4.14.5**6**? That would cause a conflict I believe.

**Comment by baywet** [comment]
no no, what I provided is an export of all the types I have after reverting the changes. I only have 1 version of @types/lodash

**Comment by AviVahl** [comment]
@baywet I checked the combination of these @types packages on my end, and I suspect the error is caused by a conflict of `@types/core-js@0.9.35`, which **also** has a WeakMap definition.

Please try upgrading to `@types/core-js@0.9.37` (alongside the new @types/lodash version). The new version removed this definition and instead requires you to specify the libs for the types in your tsconfig (the "lib" key). see: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15108

**Comment by AviVahl** [comment]
@andy-ms do you think the collections polyfills in lodash should also be removed to avoid @types libraries conflicts with ts's own libs?

I'm referring to:
```ts
// Backward compatibility with --target es5
declare global {
    interface Set<T> { }
    interface Map<K, V> { }
    interface WeakSet<T> { }
    interface WeakMap<K extends object, V> { }
}
```
from lodash/index.d.ts

**Comment by baywet** [comment]
Thanks for helping @AviVahl  Upgrading to @types/core-js@0.9.37 causes me this issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15140 
I also have this issue when upgrading to @types/node@7.0.8  https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15104

I think everything is more or less related, still trying to figure out what.

**Comment by AviVahl** [comment]
Glad to assist. We too feel the same pains (types conflicting) on our end many times, although we use exact versioning for our 3rd-party versions (no carets in the package.json).

I think this entire mess revolves around the fact that you can use a library like lodash in a browser without WeakMap (I'm guessing the `isWeakMap` function will throw in runtime or something similar), but @types/lodash requires the WeakMap definition for its typings... so while the real library can run in several targets (es5, es2015, etc...), its typings require es2015 lib.

@types/lodash (and similarly @types/core-js until its recent version) declared a generic WeakMap interface in case the uses project uses "es5" target, and doesn't specify relevant libs with these interfaces. This created a conflict once the built-in lib changed with a more specific WeakMap type (one that uses ts2.2's `object` type). So @types packages declaring their own native structures interfaces might not be the best way.

Removing these declarations would require end user project to add type libs to its config in order to use @types/core-js. Not sure this is the most graceful way to go. Perhaps TypeScript should warn if a type package that requires es2015 lib is loaded in a project that 'target's es5 (the default `tsc --init` config) and uses the automatically loaded 'lib'?

I'm guessing failing on missing or conflicting definitions should be avoided, but the answer might have to come from the way TypeScript itself handles type packages? That's why I think MS employees are most relevant to the discussion...

**Comment by baywet** [comment]
In my case I solved it by doing two things:
Upgrading to @types/node@7.0.10 @types/core-js@0.9.37 and @types/lodash@4.14.57
Updating my tsconfig.json to include that
```
"lib": [
      "dom",
      "dom.iterable",
      "es2015",
      "scripthost"
    ],
```
The issue seems to be that we were in a transitioning period for a certain number of libraries to rely on these provided typings, but not all of them were updated at the same time.
Bottom line I think libraries typings should rely as much as possible on provided "core language" typings.
However there should be a way for a typing to declare a dependency on a core typing provided by typescript.
Thanks very much for your help @AviVahl

**Comment by andy-ms** [comment]
@AviVahl In that case I don't think it's so bad since they're not redeclaring the entirety of the type, just forward-declaring their existence.

**Comment by tanskanm** [comment]
I also have "[1] [0] (19507,15): error TS2428: All declarations of 'WeakMap' must have identical type parameters."

In my package.json I have (the ones that seem to be related to the issue):
```
"@ngrx/store": "^2.2.1", 
"lodash": "^4.17.0",
"react-dom": "^15.4.2",
"@types/core-js": "^0.9.37",
"@types/lodash": "^4.14.58",
"typescript": "^2.2.0",
```

> npm install lodash
+-- UNMET PEER DEPENDENCY @ngrx/core@^1.1.0
+-- @types/lodash@4.14.58
`-- UNMET PEER DEPENDENCY react@^15.4.2

I added to tsconfig: 
```
"lib": [
      "dom",
      "dom.iterable",
      "es2015",
      "scripthost"        
    ]
```
but that didn't help

In node_modules lodash version is 4.17.4
and @types/lodash version is 4.14.58

I hadn't done npm install for a while and everything worked fine until I did. I checked my backup and lodash+@types/lodash versions were the same so no difference there. Something else got updated that broke my build. Can anyone help me with this?

**Comment by andy-ms** [comment]
@tanskanm Try using find-all-references on WeakMap to see where the other declaration is. The one in TypeScript's own lib is the correct one, any others must match.

**Comment by tanskanm** [comment]
It seems to be interface WeakMap<K, V> everywhere except in:
es7-reflect-metadata/dist/dist/shim/weakmap.d.ts: export declare class WeakMap<T, V>
es7-reflect-metadata\src\shim\weakmap.ts: export class WeakMap<T, V>

And in some places it is: interface WeakMap<K extends object, V> { }

**Comment by andy-ms** [comment]
`K extends object` is correct, `es7-reflect-metadata` should be updated.

**Comment by andy-ms** [comment]
@tanskamm Try upgrading your @types/lodash version, and use find-all-references to view all declarations of `WeakMap`. They should all have `K extends object`, the one that doesn't is wrong. (If that one is in `lib.d.ts` then you need to upgrade TypeScript.)
