### ISSUE TITLE
Doesn't support anymore jssha 1.6 ?

### ISSUE THREAD

**Issue by FrancescoMussi** [DefinitelyTyped/DefinitelyTyped#15333]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

Hi guys!
A quick question: you don't support anymore jssha1.6?

I think many mobile developers are going crazy since ngCordovaOauth doesn't support jssha v2 and we are forced to use jssha 1.6

But now that DefinitelyTyped doesn't support jssha 1.6 so the only thing we are left is to throw our macs down the window and start using drugs..

**References:**
jssha issue with jssha 1.6 - because of DefinitelyTyped don't supporting 1.6:
https://github.com/Caligatio/jsSHA/issues/51

ngCordovaOauth not supporting jssha v2:
https://github.com/nraboy/ng-cordova-oauth/issues/93

Thank you guys!
Hope you clarify to me a little bit the situation!

**Comment by andy-ms** [comment]
Hi, are you referring to `@types/jssha`?
That package doesn't seem to be well maintained.
It doesn't list a version number either, so I don't know if it's for jssha v1 or v2.

Take a look. If they look like they're for v1 but have some mistakes, you could fix them.

If they look like they're for v2, you can create v1 typings.
Just copy everything there into a new `types/jssha/v1` subdirectory and edit from there.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
