### ISSUE TITLE
Broken JetBrains IDEs

### ISSUE THREAD

**Issue by LispEngineer** [DefinitelyTyped/DefinitelyTyped#15390]
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/354cec620daccfa0ad167ba046651fb5fef69e8a

This commit seems to have broken all JetBrains IDEs which relied on your data to download TypeScript stubs.

See: https://youtrack.jetbrains.com/issue/WEB-26160

Not sure if you were aware of that, or care, or if it was intentional or not. Seems to have been committed 20 hours ago. Obviously it's not up to you to make sure your GitHub works for JetBrains, but I didn't know if you wanted to be made aware of this.

**Comment by LispEngineer** [comment]
This might be a dup of #15367.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
