### ISSUE TITLE
phantomjs and node duplicate identifiers

### ISSUE THREAD

**Issue by moshie** [DefinitelyTyped/DefinitelyTyped#15471]
- [x] I tried using the `@types/phantomjs` & `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @keesey 

When attempting to compile phantom js file and node js I am met with the following error

```
node_modules/@types/node/index.d.ts(84,13): error TS2300: Duplicate identifier 'require'.
node_modules/@types/phantomjs/index.d.ts(6,18): error TS2300: Duplicate identifier 'require'.
```

By the looks of it the require definition is clashing with the node require definition. Is there anything I can do about this?

**Comment by andy-ms** [comment]
I think these environments are legitimately incompatible, as in you can't use both at the same time at runtime. Try setting [`"types"`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) in your tsconfig to include just the types you're using.

**Comment by moshie** [comment]
Could you explain a little more about how I can utilize types, the documentation isn't very informative..

As a temporary Fix / Hack I removed the phantomjs typings and declared the variables at the top of the phantomjs file. Not an elegant solution as I don't have the typings for phantomjs.

Is there anyway to "disable" the node typings for the phantomjs file?

**Comment by andy-ms** [comment]
The `"types"` option allows you to explicitly list which types you want included. By default anything in `node_modules/@types` is included. You can use `"types": ["phantomjs"]` to get only those types.
This is a project-wide setting, so if some of your code runs on node.js but other code runs on phantomjs, they should probably have separate tsconfigs.
Note that a `/// <reference types="phantomjs" />` directive would do the same thing. And once a global type definition (like node or phantomjs) is added, it's available everywhere in your project. So again, you probably want to segregate node and phantomjs code.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
