### ISSUE TITLE
Mocha type for IRunnable omits the .timeout() method

### ISSUE THREAD

**Issue by ericeslinger** [DefinitelyTyped/DefinitelyTyped#15485]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kazimanzurrashid, @otiai10, @jt000, @enlight

Mocha's Runnable class has a `.timeout(val: number): IRunnable` method that sets the timeout on the particular test. This is useful in this kind of situation.

    describe('something', () => {
      it('does something normal', () => {});
      it('does something that takes a while', () => {}).timeout(5000);
    });

I just rewrite these tests as

    (it as any)('does something funky without typescript help', ()=> {}).timeout(5000)

instead. But having that timeout method on IRunnable would be rad. I'd do a PR, but I'm actually not sure how to say "returns this" by type in typescript on an abstract base class, since ITest is a subinterface of IRunnable- would there be a separate timeout() method on ITest that returns ITest, overriding the one on IRunnable that returns IRunnable?

**Comment by mrpinsky** [comment]
@ericeslinger You can set the return type to `this` ([Polymorphic This Types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#polymorphic-this-types)),  which should handle the inheritance issues.

**Comment by aleung** [comment]
This issue should be closed. Already fixed by #15487.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
