### ISSUE TITLE
@types/knex Missing MSSQL config definition

### ISSUE THREAD

**Issue by cadriel** [DefinitelyTyped/DefinitelyTyped#15488]
@andy-ms @baronfel

In order to get knex to connect successfully to an MSSQL Azure database, my connection config has to look as follows;

```
    {
      client: 'mssql',
      connection: {
        user: 'username',
        password: 'password',
        server: 'servername',
        options: {
          encrypt: true,
          port: 1433,
          database: 'database-name',
          connectionTimeout: 200,
          pool: {
            max: 10,
            min: 0,
          },
        },
      },
    }
```

However - `@types/knex` doesn't support this - making things more difficult.

**Comment by baronfel** [comment]
Would you mind either:

1. creating a schema for this config like is done [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/knex/index.d.ts#L479) and then adding it an an option [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/knex/index.d.ts#L458), or 
2. providing some documentation for what the shape of this config should be so that someone else could do it?

**Comment by cadriel** [comment]
I wouldn't mind at all, PR incoming.

**Comment by baronfel** [comment]
Can this be closed now?

**Comment by cadriel** [comment]
The MsSql side was already merged I believe.
