### ISSUE TITLE
@types/leaflet GeoJSONOptions should extend PathOptions, PathOptions properties need update

### ISSUE THREAD

**Issue by tylkomat** [DefinitelyTyped/DefinitelyTyped#15508]
The Leaflet documentation states that [GeoJSONOptions](http://leafletjs.com/reference.html#geojson)

> Additionally accepts all [Path options](http://leafletjs.com/reference.html#path-options) for polylines and polygons.

I suppose `GeoJSONOptions` should therefore extend `PathOptions` instead of `LayerOptions`.

Also the `PathOptions` in the documentation are missing `renderer` and `dashOffset` properties, but include `clickable` and `pointerEvents`.

I could submit a pull request, but the `index.d.ts` in the repo looks much different from what I got from `npm`. In the repo there are no `export` statements for example.

Authors: @alejo90

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
