### ISSUE TITLE
Greensock roughease wrong config param

### ISSUE THREAD

**Issue by lucap86** [DefinitelyTyped/DefinitelyTyped#15506]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gsap/Ease.d.ts

in RoughEase class

```
config(steps?: number): RoughEase;
```

should be

```
config(steps?: RoughEaseConfig): RoughEase;
```

here api documentation
https://greensock.com/docs/#/HTML5/GSAP/Easing/RoughEase/config/

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
