### ISSUE TITLE
@types/bluebird AggregateError definition is wrong

### ISSUE THREAD

**Issue by kolbma** [DefinitelyTyped/DefinitelyTyped#15589]
- [X] I tried using the `@types/bluebird` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @lhecker @andy-ms 

Look at your own documentation above the definition. 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bluebird/index.d.ts#L722
There should be some kind of array.  But it just extends Error.

**Comment by ddwwcruz** [comment]
Can you provide a link to the right definition? Or make a PR?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
