### ISSUE TITLE
Convert angularfire to use bundled firebase typings

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#15599]
@thSoft, @frankbille, @nimaen, @vbortone, @in-async, @dsebastien, @ciekawy

`angularfire` currently uses DefinitelyType's `firebase` typings.
But those typings are for firebase v2, while the lastest angularfire uses firebase v3.
Also, our angularfire typings are for v0.8, while the latest is v2.3.

Firebase bundles its own types now, so I'd like to get rid of them here on DefinitelyTyped, but angularfire relies on them now. Could someone please bring `angularfire` up to date, and use the bundled `firebase` types instead of the ones on DefinitelyTyped? Here's how to do it:

* `cd types/angularfire`
* Add a `package.json` containing `{}`.
* Run `npm install firebase --save`.
* Change `/// <reference types="firebase"/>` to `import firebase = require("firebase")`.
* Fix compile errors.

**Comment by epool** [comment]
covered on #22311

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
