### ISSUE TITLE
React-Router-Dom4.0.3 Build Object Err

### ISSUE THREAD

**Issue by dvbz** [DefinitelyTyped/DefinitelyTyped#15592]
When building a project with @types/react-router-dom, after successful compilation with TypeScript & bundling with Webpack, VS 2015 Community throws a Build: Cannot find name 'object' err(TS2304) on index.d.ts of @types/react-router-dom.  Error is thrown @ lines 82 & 83 of index.d.ts

**TypeScript Version:**  2.2.2 
**React-Router Dom Version:** 4.0.0
**@Types/React-Router-Dom Version:** 4.0.3

**Code**
`  interface StaticRouterProps {
    basename?: string;
    location?: string | object;
    context?: object;
  }
  class StaticRouter extends React.Component<StaticRouterProps, void> {}

**Comment by omkarjoshi-cc** [comment]
Same problem.

**Comment by omkarjoshi-cc** [comment]
@sergey-buturlakin Please help.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
