### ISSUE TITLE
Update Node - child_process - ForkOptions

### ISSUE THREAD

**Issue by scippio** [DefinitelyTyped/DefinitelyTyped#15619]
- [X] I tried using the `@types/xxxx` package and had problems.

Pls. update ForkOptions:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L1732

Add `stdio` option https://nodejs.org/docs/latest/api/child_process.html#child_process_child_process_fork_modulepath_args_options

I don't have a time for create patch now... sorry :-1: (maybe this week I'll create it...)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
