### ISSUE TITLE
Add types for connect-gzip-static

### ISSUE THREAD

**Issue by slawiko** [DefinitelyTyped/DefinitelyTyped#15664]
Let's add types for this package: https://github.com/pirxpilot/connect-gzip-static

NPM package: https://www.npmjs.com/package/connect-gzip-static

**Comment by andy-ms** [comment]
You'll probably have to create the pull request yourself. See the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute).

**Comment by slawiko** [comment]
@andy-ms of course! I'm going to do that

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
