### ISSUE TITLE
[Request] Definition request: strsplit

### ISSUE THREAD

**Issue by kgtkr** [DefinitelyTyped/DefinitelyTyped#15678]
strsplit
https://github.com/joyent/node-strsplit

**Comment by andy-ms** [comment]
This looks like a pretty simple library. Could you try doing this yourself?
Would this work?

```ts
declare function strsplit(str: string, pattern: RegExp, limit: number): string[];
export = strsplit;
```

The reason I ask you to make the PR is that you can [test](https://github.com/DefinitelyTyped/DefinitelyTyped#test) it in your own code before committing, to be sure that it's really the right definition.

**Comment by kgtkr** [comment]
```
declare function strsplit(str: string, pattern?: RegExp|string, limit?: number): string[];
export = strsplit;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
