### ISSUE TITLE
@types/sequelize --- missing paranoid in interface IncludeOptions

### ISSUE THREAD

**Issue by AndrewLaBabies** [DefinitelyTyped/DefinitelyTyped#15670]
- [x] I tried using the `@types/sequelize`  (^4.0.46) package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @samuelneff, @codeAnimal, @drinchev

**index.d.ts --> interface IncludeOptions** missing following, please add it in V3 and V4 @types/sequelize, thanks.
```
paranoid?: boolean;
```

document indicates paranoid can be used in 'include': 
http://docs.sequelizejs.com/en/latest/docs/models-usage/#including-soft-deleted-records

**Comment by pirmax** [comment]
Where is this change?

**Comment by villasv** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sequelize/index.d.ts#L3303

Can we close this issue?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
