### ISSUE TITLE
Angular IScope has no type safety anymore

### ISSUE THREAD

**Issue by massimocode** [DefinitelyTyped/DefinitelyTyped#15683]
See this: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/82447ac01078f1f5d9b25ea27712c3317f94adde#diff-b2ae00ce2584e4857fb9b28e6095f2baR319

This exists in the latest type definition.

This was fine up until the TypeScript team decided that with version 2.2 anything with an indexer would be allowed to be accessed with dot notation: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html#dotted-property-for-types-with-string-index-signatures

It means we essentially lose all type safety on anything deriving from IRootScope.

**Comment by andy-ms** [comment]
Don't forget to mention the package authors or no one will see this.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
