### ISSUE TITLE
collector, spec and monitor functions should not return type Object 

### ISSUE THREAD

**Issue by mutsys** [DefinitelyTyped/DefinitelyTyped#15704]
All of these functions intend for the developer to return some sort of object having their own application-specific properties, however the type `Object` implies a javascript object that has no user-defined properties at all. This makes handling the value returned from `DropTargetMonitor.getItem()` and `DropTargetMonitor.getDropResult()`, for example rather annoying to deal with. At a minimum, this requires a cast to a known type or `any` to be able to use the returned value. A generic signature for the return type of these methods could make it easy for returned value to given the correct type. If that is not an option, then at least `Object` should be changed to `any`, allowing a developer to use the returned value as expected without having to take the extra step of casting the value.

**Comment by andy-ms** [comment]
Please fill in the [issue template](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
