### ISSUE TITLE
high stock stockChart function missing 

### ISSUE THREAD

**Issue by gaotter** [DefinitelyTyped/DefinitelyTyped#15707]
I tried using the `@types/highcharts` package and had problems.
I imported hightstock like this "import * as Highstock from 'highcharts/highstock';" but was not able to access the stockChart function in TypeScript. I could see the function logging the object in the browser. After some testing,  I open the  "highstock.d.ts" file and added this under the Static interface, it worked:
 interface Static extends Highcharts.Static {
        StockChart: Chart;
		stockChart(renderTo: string | HTMLElement, options: Options, callback?: (chart: ChartObject) => void): ChartObject;
    }

But this is just local, so if I use the npm install, this will not be part of it. 

Is there a better way of doing this, and will it be part of a future fix?

**Comment by andy-ms** [comment]
You could make a pull request doing that.

**Comment by gaotter** [comment]
I  tired to run the npm run lint highcharts but are getting the error 'Object.entries is not a function' same when i run the tests.

**Comment by andy-ms** [comment]
You need to install a newer node version that provides that function.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
