### ISSUE TITLE
Module not found: Error: Can't resolve '@types/bcrypt'

### ISSUE THREAD

**Issue by jried31** [DefinitelyTyped/DefinitelyTyped#15734]
Problem: Unable to resolve "@types/bcrypt" in an angular2 Typescript project.
Installation: npm install --save @types/bcrypt

Declaration inside file.ts
import {hashSync} from '@types/bcrypt';

Error Received: Module not found: Error: Can't resolve '@types/bcrypt'
Angular2 Server Command: "ng serve" from Angular CLI

Is there a configuration that Im missing so that the module is seen?

**Comment by CaselIT** [comment]
You need to use the package name the `.ts` file, the `@types` is just an npm namespace to group all the type definitions.

Import it as `import {hashSync} from 'bcrypt';` and it should work

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
