### ISSUE TITLE
@types/mqtt: Client class missing properties.

### ISSUE THREAD

**Issue by wcatron** [DefinitelyTyped/DefinitelyTyped#15760]
I tried using the `@types/mqtt` package and had problems.

The client properties aren't available.
- [connected](https://github.com/mqttjs/MQTT.js#mqttclientconnected)
- [reconnecting](https://github.com/mqttjs/MQTT.js#mqttclientreconnecting)

Authors:
- @PekkaPLeppanen

**Comment by PekkaPLeppanen** [comment]
These types at `@types/mqtt` are made against MQTT.js v1 API and its documentation quite some time ago. Current types for v2 API are maintained inside the MQTT.js repo.

I checked that the types at the MQTT.js included these properties you mentioned.

**BTW**: `@types/mqtt` is listed in `notNeededPackages.json`file.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
