### ISSUE TITLE
Issue: Adding Snapshot to the Test Case Level using Jasmine and TypeScript 

### ISSUE THREAD

**Issue by anuvratashu** [DefinitelyTyped/DefinitelyTyped#15836]
I am getting the error while using allure reporter with jasmine and typescript.

**jasmine.getEnv().afterEach(done => {
            browser.takeScreenshot().then(function (png) {              
                allure.createAttachment('Screenshot', function () {
                    return new Buffer(png, 'base64')
                }, 'image/png')();
        done();
            });
        });**
Here as typescript check the type , so i am getting the below error for the line
However, the same code works fine with Javascript and jasmine.

So please help how to have the same code work for typescript and jasmine
jasmine.getEnv().afterEach(done =>

**[ts] Argument of type '(done: any) => void' is not assignable to parameter of type '() => void'.
(parameter) done: any'**

The Jasmine typings that come from there do not have a signature with callback . So what can be done in this case.

**Comment by andy-ms** [comment]
Sounds like in `interface Env`, `afterEach` should be declared as `afterEach(action: (done: DoneFn) => void): void;` and not just `afterEach(afterEachFunction: () => void): void;`.
Is the same true for `beforeEach`, `beforeAll`, and `afterAll`?
CC package authors @borisyankov @theodorejb @davidparsson

**Comment by anuvratashu** [comment]
When can shall i expect this problem to be resolved?

**Comment by anuvratashu** [comment]
Please update are we going to get a new jasmine release with the issue resolved

**Comment by andy-ms** [comment]
@anuvratashu You could make a pull request yourself.

**Comment by monkpit** [comment]
@andy-ms @borisyankov @theodorejb @davidparsson I have submitted a PR to address this issue. #23133

**Comment by zvirja** [comment]
@anuvratashu @monkpit Issue is fixed, so should be closed ✔️

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
