### ISSUE TITLE
Type mismatch in @types/async `map` function signature. 

### ISSUE THREAD

**Issue by slalomandrew** [DefinitelyTyped/DefinitelyTyped#15849]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @kern0 @Penryn @fenying @pascalmartin 

**What version of async are you using?**
    "@types/async": "^2.0.40",
    "async": "^2.3.0",

**Which environment did the issue occur in (Node version/browser version)**
NodeJS v7.3.0

**What did you do? Please include a minimal reproducable case illustrating issue.**
```const ids: string = items.map((i) => i.id);
async.mapLimit(ids, 20, async.asyncify(this.processId)); ```

**What did you expect to happen?**
At least compile. 

**What was the actual result?**
Error in bail mode: [at-loader] ./resources/items/items.service.ts:236:28 
    TS2345: Argument of type 'string[]' is not assignable to parameter of type 'Dictionary<{}>'.
  Index signature is missing in type 'string[]'.

**Comment by anselmstordeur** [comment]
I am having the same Problem on some Projects. What is the Problem here? The TypeDefinitions look alright.

**Comment by fenying** [comment]
Ummm, that's due to the signature of method `async.asyncify`.

```ts
export function asyncify(fn: Function): Function;
```

Here's a method, by changing the signature to

```ts
export function asyncify(fn: Function): (...args: any[]) => any;
```

So that ts will ignore the verification for callbacks' signature.

Do you have any idea? @borisyankov @Kern0 @Penryn @pascalmartin

------------------------------------

Besides, there are two signatures of `mapLimit`. It could be merged into one signature like

```ts
export function mapLimit<T, R, E>(
    arr: T[] | Dictionary<T> | IterableIterator<T>,
    limit: number,
    iterator: AsyncResultIterator<T, R, E>,
    callback?: AsyncResultArrayCallback<R, E>
): void;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
