### ISSUE TITLE
Npm returns 404 when installing type mocha

### ISSUE THREAD

**Issue by Nickolaus** [DefinitelyTyped/DefinitelyTyped#15867]
This link just shows the git 404 page:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/mocha

has the type been replaced or renamed?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
