### ISSUE TITLE
Threejs missing typing for ShapeBufferGeometry

### ISSUE THREAD

**Issue by blackstrings** [DefinitelyTyped/DefinitelyTyped#15871]
- [x] I tried using the latest `@types/threejs@0.84.3` package with the latest npm install three and had problems.

  - Authors: @....
Kon <http://phyzkit.net/>, Satoru Kimura <https://github.com/gyohk>, Florent Poujol <https://github.com/florentpoujol>, SereznoKot <https://github.com/SereznoKot>, HouChunlei <https://github.com/omni360>, Ivo <https://github.com/ivoisbelongtous>, David Asmuth <https://github.com/piranha771>

While THREE.ShapeGeometry is recognized as a type, THREE.ShapeBufferGeometry isn't.
In the mean time i had to provide the missing type in index.d.ts
```
 export class ShapeBufferGeometry extends Geometry {
        constructor(shape: Shape, options?: any);
        constructor(shapes: Shape[], options?: any);

        addShapeList(shapes: Shape[], options: any): ShapeGeometry;
        addShape(shape: Shape, options?: any): void;
    }
```

I propose ShapeBufferGeometry should get added to the index.d.ts file for @types/three

**Comment by efokschaner** [comment]
Related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17819

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
