### ISSUE TITLE
MathJS Missing Node Types

### ISSUE THREAD

**Issue by elu00** [DefinitelyTyped/DefinitelyTyped#15879]
- [x] I tried using the `@types/mathjs` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @siavol, @jesperronn

Hi all, just noticed that a couple class definitions are missing for mathJS.    
Specifically, the following class definitions [here](http://mathjs.org/docs/expressions/expression_trees.html#nodes) seem to be missing.
I'd really appreciate anyone adding these definitions to this repo, however I can make an attempt at doing so if nobody else wants to pick it up.
Thanks!

**Comment by carmanchris31** [comment]
Also the `math.expression.parse.*` methods here: http://mathjs.org/docs/expressions/customization.html#customize-supported-characters

**Comment by Diluka** [comment]
`math.simplify` is missing too
see http://mathjs.org/docs/expressions/algebra.html

**Comment by DanielJoyce** [comment]
Also, parsed MathNodes, the 'type' property is apparently now 'valueType', so the typings no longer match properly

**Comment by dkonasov** [comment]
`math.import` method is missing too

**Comment by pawkrol** [comment]
@dkonasov Please checkout latest PR #31089

**Comment by dkonasov** [comment]
@pawkrol great, thanks!

**Comment by cinderblock** [comment]
Types for `math.eigs` are missing

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
