### ISSUE TITLE
React-redux

### ISSUE THREAD

**Issue by przemo098** [DefinitelyTyped/DefinitelyTyped#15899]
Hey I currently downloaded types/react-redux but when I create provider I get error:
Failed prop type: The prop `store` is marked as required in `Provider`, but its value is `undefined`.
But in compilation time I got no errors with Provider I guess `<Provider/>` property `store` should be marked as necessary.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
