### ISSUE TITLE
KendoUI Professional 2017.2.223

### ISSUE THREAD

**Issue by advapiIT** [DefinitelyTyped/DefinitelyTyped#15946]
Hello,
latest version of kendo-ui.TypeScript.DefinitelyTyped (version 0.2.5) refers to kendoui professional  v2016.3.1029, latest version is 2017.2.223, it's possible to have an update on this?
Thanks

**Comment by andy-ms** [comment]
Please fill in the [issue template](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
