### ISSUE TITLE
mongo cursor map function type

### ISSUE THREAD

**Issue by snytkine** [DefinitelyTyped/DefinitelyTyped#15991]
I am looking at the latest type definition for mongodb @types/mongodb 2.1.42 and I think that the type of **map** function of the **cursor** object can be typed more specific.

Current definition:
` map(transform: Function): Cursor<T>;`

But since this transform function changes documents very likely changing the type of documents, I think the better
signature for this function should be:

`
map<U>(transform: (T) => U ): Cursor<U>
`

**Comment by andy-ms** [comment]
Please fill in the [issue template](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by dobesv** [comment]
- [x] I tried using the `@types/mongodb` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT, @alanmarcell, @kikar, @bitjson, @dante-101, @mcortesi, @EnricoPicci, @AJCStriker, @julien-c, @daprahamian

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
