### ISSUE TITLE
oracledb: missing getRows function in IResultSet

### ISSUE THREAD

**Issue by jlaamanen** [DefinitelyTyped/DefinitelyTyped#16012]
- [X] I tried using the `@types/oracledb` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Bigous

[@types/oracledb NPM summary](https://www.npmjs.com/package/@types/oracledb) explains that the typings should be compatible with node-oracledb version 1.5.0, but `getRows` function is missing under `IResultSet` interface.

I checked node-oracledb with version tag 1.5.0, and it seems to be implemented in that version (latest stable version is 1.13.1): https://github.com/oracle/node-oracledb/blob/v1.5.0/src/njs/src/njsResultSet.cpp#L288

**Comment by Bigous** [comment]
Hi @jlaamanen, this is complicated :D 

Some history:

I started putting definitions here (v 1.5.0)...

Then typescript community stopped using `tsd` and started using `typings`. `tsd` was deprecated in favor of `typings`. `typings` recommends to use their registry as the oficial repository, but supports a few other sources (like, DefinitelyTyped, github repositories, npm, among others). Their [registry is just an index](https://github.com/typings/registry/blob/master/npm/oracledb.json) to author repositories (which I liked a lot) and you can find [my latest implementation](https://github.com/Bigous/typed-oracledb) there ([which has the getRow function](https://github.com/Bigous/typed-oracledb/blob/master/index.d.ts#L193-L206)).

Than typescript 2.x.x came and changed everything again... They created a branch on this repository (called `types`) and there is an automatic procedure that post all the type definitions from that branch to npm under `@types/`. My last updated type definition for `node-oracledb` (v1.11) is also published [over there](https://www.npmjs.com/package/@types/oracledb).

So, if your problem is just the getRow (nothing newer than v1.11), please use either the npm `@types/oracledb` or the one from [my repository](https://github.com/Bigous/typed-oracledb) using `typings` instead of `tsd`.

I'm one of the contributors of `node-oracledb` but, unfortunately, I was not able to contribute more in the past 6 months. Sorry about that :(.

If you look at oracle/node-oracledb#169 you can see all the history ;)

Hope have helped.

**Comment by jlaamanen** [comment]
@Bigous, thanks for your reply! I'm actually already using `@types/oracledb`, I thought this was the repo where they come from.

I actually have no problems with `getRow` function, but `IResultSet` should also have `getRows` function for fetching multiple rows at once from the result set. The functions should be quite similar, but `getRows` would also have parameter `numRows: number`.  The function reference can be found from [here](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#getrows).

I can open a new issue on your repository and close this one, if that's fine.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
