### ISSUE TITLE
React-Native - Missing attribute "testID" for TouchableOpacity

### ISSUE THREAD

**Issue by mikach** [DefinitelyTyped/DefinitelyTyped#16022]

**Comment by mnzaki** [comment]
@mikach I believe this has been fixed by 621cf88db53de571251d356289124ae3233e9af8

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
