### ISSUE TITLE
Add method to interface in angular-dynamic-locale

### ISSUE THREAD

**Issue by msieben-andrena** [DefinitelyTyped/DefinitelyTyped#16041]
- [x] I tried using the `@types/angular-dynamic-locale` package and had problems.
Hi,
could you add the method
defaultLocale(locale: string): void;
to the tmhDynamicLocaleProvider interface in angular-dynamic-locale's index.d.ts?
(See https://github.com/lgalfaso/angular-dynamic-locale/blob/master/src/tmhDynamicLocale.js, line 193)

Thank you very much,
Marco

**Comment by berhir** [comment]
@msieben-andrena The updated version is already available on npm

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
