### ISSUE TITLE
applicationinsights-js: a question mark after the method name

### ISSUE THREAD

**Issue by zygimantas** [DefinitelyTyped/DefinitelyTyped#16056]
- [x] I tried using the `@types/applicationinsights-js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kamilszostak @andy-ms 

Should a question mark be here? It causes the "Object is possibly 'undefined'" during the app compilation.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/applicationinsights-js/index.d.ts#L783

Weird looking workaround:

    if (AppInsights.downloadAndSetup !== undefined) {
        AppInsights.downloadAndSetup(this.config);
    }

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
