### ISSUE TITLE
history - createHref incorrect parameters

### ISSUE THREAD

**Issue by arolson101** [DefinitelyTyped/DefinitelyTyped#16063]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sergey-buturlakin, @ngbrown, @rokoroku

the declaration for createHref is:
```createHref(location: Path | LocationDescriptorObject): Href;```
but it will actually only accept a LocationDescriptorObject; calling it with a Path is not supported: https://github.com/ReactTraining/history/issues/464

**Comment by rokoroku** [comment]
Good catch, I'll prepare a PR.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
