### ISSUE TITLE
@types/sequalize missing charset

### ISSUE THREAD

**Issue by drosi94** [DefinitelyTyped/DefinitelyTyped#16069]
charset missing from interface Options at index.d.ts

**Comment by andy-ms** [comment]
Make a pull request?

**Comment by drosi94** [comment]
OK,  I can try

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
