### ISSUE TITLE
unable to import many threejs packages

### ISSUE THREAD

**Issue by yoghesh** [DefinitelyTyped/DefinitelyTyped#16079]
I am using Type definitions for three.js 0.84.6. I am able to use the core of threejs but i have issues in using the trackbarcontrol, orbitalbontrol, etc. I am getting the following error. I am new to the typescript please what i am doing wrong.

`import { Component, OnInit, Input } from '@angular/core';

import { Scene, PerspectiveCamera, TrackballControls, Mesh, WebGLRenderer, SphereGeometry, MeshBasicMaterial, AmbientLight, OrbitControls } from 'three'

@Component({
  selector: 'app-three-drenderer',
  templateUrl: './three-drenderer.component.html',
  styleUrls: ['./three-drenderer.component.css']
})
export class ThreeDrendererComponent implements OnInit {

  private scene: Scene;
  private camera: PerspectiveCamera;
   private trackball: TrackballControls;
  private mesh: Mesh;
  private renderer: WebGLRenderer;
  private domContainer: HTMLElement;

  @Input()
  public set container(value: HTMLElement) {
    if (value)
    { this.domContainer = value; }
  }
   constructor() { }
  ngOnInit() {
    if (this.domContainer) {
      const width = window.innerWidth;
      const height = window.innerHeight / 3;

      this.scene = new Scene();
      this.camera = new PerspectiveCamera(45, width / height);
      this.camera.position.set(0, 0, 100);

      this.renderer = new WebGLRenderer({ antialias: true });
      this.renderer.setPixelRatio(window.devicePixelRatio);
      this.renderer.setSize(width, height);
      this.renderer.setClearColor(0x000000);

      this.domContainer.appendChild(this.renderer.domElement);
      this.trackball = new TrackballControls(this.camera, this.domContainer);

      let geom = new SphereGeometry(5, 50, 50);
      let material = new MeshBasicMaterial({ color: 0xffffff });
      this.mesh = new Mesh(geom, material);

      this.scene.add(this.mesh);
      const light = new AmbientLight(0xcccccc);
      this.scene.add(light);
      this.animate();
    }
  }

  public animate() {
    window.requestAnimationFrame(_ => this.animate());
    this.trackball.update();
    this.renderer.render(this.scene, this.camera);
  }
}
`

**Comment by csuarezgfx** [comment]
Please add the three-collada-loader to the list. The actual ColladaLoader has many functions and properties that are not listed in TypeScript definition file.

**Comment by raffalevy** [comment]
Just had this issue with `OrbitControls`. What's going on is that `OrbitControls` etc. aren't really part of the core Three library; they have to be included separately, as per [the docs](https://threejs.org/docs/index.html#examples/controls/OrbitControls) for `OrbitControls`:

> To use this, as with all files in the /examples directory, you will have to include the file seperately in your HTML.

IMO these classes shouldn't be included in the core type definition, since they make it look like they exist when they don't.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
