### ISSUE TITLE
ember typings: Missing the Ember.RSVP.hash method

### ISSUE THREAD

**Issue by perlun** [DefinitelyTyped/DefinitelyTyped#16120]
- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jedmao

When looking at the [Ember index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember/index.d.ts) file, I noted that `Ember.RSVP.hash` is missing. (I saw this when sitting and editing a file in Visual Studio Code

Here is the API reference at the Ember side: https://www.emberjs.com/api/classes/RSVP.html#method_hash

**Comment by john-griffin** [comment]
Also just hit this.

**Comment by mike-north** [comment]
This issue can be closed

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b697ec8a1bb26313b4d56a0af66b9c45c9920cef/types/rsvp/index.d.ts#L328

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
