### ISSUE TITLE
dijit/_WidgetBase has extra "isValid" property

### ISSUE THREAD

**Issue by thanhduchuynh** [DefinitelyTyped/DefinitelyTyped#16150]
In dijit.d.ts, dijit._WidgetBase declaration contains an "isValid" property which does not exist in the JavaScript.  This prevents anyone from deriving a class from _WidgetBase and implementing an interface which has "IsValid" as a function.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
