### ISSUE TITLE
NodeJS: TTY 'ReadStream' only refers to a type, but is being used as a value here. 

### ISSUE THREAD

**Issue by mentos1386** [DefinitelyTyped/DefinitelyTyped#16201]
```
import { ReadStream } from 'tty';
import { openSync } from 'fs';

const TTYReadStream = new ReadStream(openSync('/dev/tty1', 'r'));
```

When trying to compile, i get error:
`TS2693: 'ReadStream' only refers to a type, but is being used as a value here.`

From the dcumentation, it should be possible to use `ReadStream` from `tty`
> The tty module provides the tty.ReadStream and tty.WriteStream classes. In most cases, it will not be necessary or possible to use this module directly.

I created a solution, but im not that experianced in type script. [Fix](https://github.com/mentos1386/DefinitelyTyped/commit/4b1582f351408c65e19b349bcb6e2b7cc51e44b5)

**Comment by ajcrites** [comment]
This is still an issue. I believe that the proposed fix is correct so you should create a pull request.

**Comment by mentos1386** [comment]
@ajcrites Okey, i'll create pull request later today.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
