### ISSUE TITLE
Does `wNumb` needs to be ambient?

### ISSUE THREAD

**Issue by kbtz** [DefinitelyTyped/DefinitelyTyped#16203]
@acoreyj Hey thanks for providing typings for the slider and wNumb!
Maybe letting the typings for wNumb ambient makes sense in the development environment for the slider but to actually use wNumb in the slider options we need to first import it as a module.
```
// Works because wNumb typings are loaded as ambient
const wNumb: wNumb = require('wnumb')

// Throws an error saying that these typings aren't for a module (Typescript 2.1.5)
import * as wNumb from 'wnumb'
```
Just wondering if exporting those declarations would break anything on your end, thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
