### ISSUE TITLE
@types/ejs-locals resolves to a non-module entity and cannot be imported using this construct.

### ISSUE THREAD

**Issue by leminhphuoc89** [DefinitelyTyped/DefinitelyTyped#16217]
- I tried using the `@types/ejs-locals` package and had problem.
- Solution: add more `declare namespace ejsLocals { }` into index.d.ts. Ex:

declare function ejsLocals(): Function;
declare namespace ejsLocals { }
export = ejsLocals;

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
