### ISSUE TITLE
No any exported function for bootstrap-datepicker

### ISSUE THREAD

**Issue by teddywest32** [DefinitelyTyped/DefinitelyTyped#16237]
- [x ] I tried using the `@types/bootstrap-datepicker` package and had problems.

There is no any exported class of modules defined like some other types definitions.
Eg:

Found in Hammerjs:
```
declare module "hammerjs" {
    export = Hammer;
}
```
Found in Select2:
```
declare class Select2 {
    constructor(element: JQuery, options: Select2Options);
    focus(): void;
    destroy(): void;
    on(event: string, callback: Function): void;
    selection: any;
    dropdown: any;
    results: any;
    $container: JQuery;
    $dropdown: JQuery;
    $selection: JQuery;
    $results: JQuery;
    options: {options: 
```

I am pretty new to importing the definition to the typescript files. How could we use this types definition without any export function?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bootstrap-datepicker/index.d.ts

**Note:** I am trying to import into Angular 2 project

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
