### ISSUE TITLE
Chart.js version 2.4 definition file not compiling

### ISSUE THREAD

**Issue by kims901** [DefinitelyTyped/DefinitelyTyped#16358]
I'm trying to use the chart.js definition file version 2.4.0 from this link https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chart.js/index.d.ts
but getting the error in visual studio 2013, Help needed.

Thanks.
![error](https://cloud.githubusercontent.com/assets/19765307/25762421/9dd02028-31ac-11e7-9351-c09133fd7c2f.jpg)

**Comment by andy-ms** [comment]
You're probably using an old version of TypeScript. All packages on DefinitelyTyped require at least TypeScript 2.0.

**Comment by kims901** [comment]
Thanks andy, yes I'm using typescript version 1.6 but is there a way to use the Chart.js version 2.4 with typescript version 1.6?
Thanks for your help..

**Comment by andy-ms** [comment]
Apparently not, since the updated typings are giving you errors.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
