### ISSUE TITLE
Node 7.x fs function types do not account for file descriptors

### ISSUE THREAD

**Issue by jmquigley** [DefinitelyTyped/DefinitelyTyped#16370]
The type definitions in Node 7.x for the `fs` library don't accept the file descriptor as an argument.  When using `appendFileSync()` with a number (file descriptor) I receive the typescript error **_"TS2345: Argument of type 'number' is not assignable to parameter of type 'string'"_**.  The Node library does take a number parameter as an option for these functions:

https://nodejs.org/api/fs.html#fs_fs_appendfilesync_file_data_options
https://github.com/nodejs/node/blob/master/lib/fs.js

That function can accept three data types: `<string> | <Buffer> | <number>`.  The type definitions contains:

```
export function appendFileSync(filename: string, data: any, options?: { encoding?: string; mode?: number; flag?: string; }): void;
export function appendFileSync(filename: string, data: any, options?: { encoding?: string; mode?: string; flag?: string; }): void;
```
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts

It seems that all of the file function are only defined to take a string (path) with the first parameter.

Node 7.8.0
Typescript 2.3.2
@types/node 7.0.18

**Comment by andy-ms** [comment]
Pull requests accepted.

**Comment by mees-** [comment]
I created a pull request for this #16477

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
