### ISSUE TITLE
@types/restify missing method definitions for JsonClient and StringClient

### ISSUE THREAD

**Issue by kolbma** [DefinitelyTyped/DefinitelyTyped#16386]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @blittle, @stevehipwell, @mhegazy, @andy-ms 

There are missing some method definitions for JsonClient and StringClient.
For example this
https://github.com/restify/clients/blob/master/lib/StringClient.js#L90
https://github.com/restify/clients/blob/master/lib/StringClient.js#L113
https://github.com/restify/clients/blob/master/lib/StringClient.js#L184

**Comment by stevehipwell** [comment]
@kolbma - Feel free to create a pull request with the client typings updated.

However please be aware that the restify clients have been split into their own package and will no longer be part of the core restify module as of the upcoming v5 release. There are currently no typings for this seperate module but I might be able to take a look over the weekend.

**Comment by kolbma** [comment]
Ok. That's why there are multiple repo's now... In the meantime I've put some definitions for this in my own code to get type checking. When I update to the v5 release I'll have a look again.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
