### ISSUE TITLE
Definition Request: node-tap

### ISSUE THREAD

**Issue by isaacs** [DefinitelyTyped/DefinitelyTyped#16400]
A lot of people really want to add typings to node-tap.

However, I'm unwilling to add anything without tests, and no one seems to know how to test this (without rewriting the whole lib in typescript, which I'm not going to do).

Anyone wanna pick up the ball from https://github.com/tapjs/node-tap/pull/256 and create a TypeScript definition file for the second most popular test framework in Node.js?  Or provide some guidance about how to write a test for it, so that I don't break it accidentally at some point in the future?

Thanks!

**Comment by Ethan-Arrowood** [comment]
If https://github.com/tapjs/node-tap/pull/607 gets merged, this issue can be closed.

**Comment by uwinkelvos** [comment]
PR: #43974

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
