### ISSUE TITLE
ReactChildren causing issues in react-virtualized for TS 2.3.2

### ISSUE THREAD

**Issue by joewood** [DefinitelyTyped/DefinitelyTyped#16415]
TypeScript 2.3.2 adds more strict type checks around ReactChildren. Components with a declared `children` property of type `ReactChildren` is now failing against `Element` arrays. The react-virtualized package has a `Table` component that explicitly types the `children` property as `ReactChildren`. This causes TypeScript compiler errors with a `Column` element array. Removing the `children` property fixes the issue.

Author: @kaoDev

**Comment by kaoDev** [comment]
I will have a look into this, but could take a few days till I have time. 
The issue should be connected to https://github.com/Microsoft/TypeScript/issues/13618

**Comment by joewood** [comment]
No problem, thanks @kaoDev. This is definitely new in TypeScript, as I had similar issues with my components. I think the `children` type should be `Column` for `Table` (according to that link above). Although, it may be easier to just remove the `children` property and leave it as the default.

**Comment by kaoDev** [comment]
PR is submitted, together with an update to version 9.7 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16515

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
