### ISSUE TITLE
Typings for request package needs update

### ISSUE THREAD

**Issue by PAStheLoD** [DefinitelyTyped/DefinitelyTyped#16439]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dvishniakov  @joeskeen  @ccurrens (authors without commits in DT this year: Bartvds bonnici soywiz)

For example the `rejectUnauthorized` option is missing from the definitions:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/06303669ae82d3e9eea8ac9975c0c683a0b104a7/types/request/index.d.ts

https://github.com/request/request/blob/29a0b172d6f7b5e9f5e344c5758a672e7814d90f/request.js

**Comment by dvishniakov** [comment]
@PAStheLoD unfortunately authors of request package don't maintain Typescript definitions for it. So I made a PR with changes for my own needs and it was recently merged.
Please consider doing the same. From my side I can help to review it

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
