### ISSUE TITLE
tar types out of date as of v3

### ISSUE THREAD

**Issue by isaacs** [DefinitelyTyped/DefinitelyTyped#16430]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/tar/index.d.ts

Node-tar has just been published with version 3.0 which uses a very different API.  See https://github.com/npm/node-tar

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
