### ISSUE TITLE
@Types/convict uses depricated parameter types

### ISSUE THREAD

**Issue by HugoKlepsch** [DefinitelyTyped/DefinitelyTyped#16449]
- [x] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Nemo157

The validate function in the newest version of convict takes in a parameter of 
`options?: { allowed: string }`
but the current @Types/convict has validate() taking in a 
`options?: { strict?: boolean }`
which is deprecated and does not support the new interface. 

Also, the convict() function can either take in a 'Schema' type (which is defined properly) or a string (which is missing from the definition).

`interface convict {
[...]
    (config: convict.Schema): convict.Config;
}`
Note that the parameter to the function does not allow just a string.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
