### ISSUE TITLE
[feature request] braintree-web-drop-in

### ISSUE THREAD

**Issue by buu700** [DefinitelyTyped/DefinitelyTyped#16474]
The Braintree v3 SDK now supports `braintree.dropin` as the v2 SDK did:

* https://github.com/braintree/braintree-web-drop-in

* https://developers.braintreepayments.com/guides/drop-in/javascript/v3

Edit: changed title for accuracy. My assumption had been that braintree-web-drop-in would need to be loaded via a side effect import and then a `dropin` property would be added to the exported value of braintree-web (as in their documented `<script>`-based examples), but actually this is used as an entirely separate module that just depends on braintree-web, so it would need to have its own independent type definition.

**Comment by buu700** [comment]
Relevant reference documentation (just added for https://github.com/braintree/braintree-web-drop-in/issues/158): https://braintree.github.io/braintree-web-drop-in/docs/current

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
