### ISSUE TITLE
Update to support fabric.js 1.7

### ISSUE THREAD

**Issue by tstackhouse** [DefinitelyTyped/DefinitelyTyped#16475]
- [ x ] I tried using the `@types/fabricjs` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @oklemencic, @joewashear007, mrand01

The current definitions are compiled against fabric.js 1.5, which works well enough in most cases, however certain properties such as `setStroke` and related are missing and causing breaking compilation failures.  I'm still new to the TS world otherwise I would try to build and submit a PR myself.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
