### ISSUE TITLE
redux-form optional properties

### ISSUE THREAD

**Issue by arolson101** [DefinitelyTyped/DefinitelyTyped#16538]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @carsonf, @aikoven, @LKay

First of all, thanks for putting together this awesome definition file!

A couple minor issues:
- ```WrappedFieldProps<S>``` - ```input``` is not optional.  (This is the only way I see to access the field's ```name```)
- ```WrappedFieldMetaProps<S>``` - ```form``` is not optional
- ```Config<FormData extends DataShape, P, S>``` - ```onChange``` values is FormData and should also have dispatch and props parameters

**Comment by szabolcsx** [comment]
I recently had to use the onChange event and I noticed that the parameters are still missing. Do you accept PR's?

**Comment by LKay** [comment]
@szabolcsx PRs are always welcome!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
