### ISSUE TITLE
Can we get some consistent naming conventions for hapi?

### ISSUE THREAD

**Issue by atrauzzi** [DefinitelyTyped/DefinitelyTyped#16568]
Using `@types/hapi` and there's `Camel_Snake` case `IStyleInterfaces` and `RegularTypes` as well.

There are so many bad habits to inherit from both C# and JavaScript, the TS coding guidelines make it pretty clear that they want a clean break: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines

Where names don't originate from the original JS library, I really think the typings should try to stay simple and only use business-language.

**Comment by AJamesPhillips** [comment]
@atrauzzi I just did a major rewrite of the typings.  Bit confused, where are you seeing the `Camel_Snake` case and `IStyleInterfaces`, they should all be removed from the latest `index.d.ts`.  If not then please submit a PR to correct them.  There's only a couple of minor exceptions that I made for helping people:

* `HTTP_METHODS_PARTIAL_lowercase` to contrast with `HTTP_METHODS_PARTIAL` and `HTTP_METHODS`.
* `_ReplyValue` to signify that it's exported but I don't think anyone should have a need to use it.
* `Continue_Reply` and `Base_Reply`, again they're only expected to be used internally.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
