### ISSUE TITLE
Upgrading to typescript 2.3.2 causing "Duplicate identifier error"

### ISSUE THREAD

**Issue by shrutic** [DefinitelyTyped/DefinitelyTyped#16646]
- [x] I tried using the `@types/xxxx` package and had problems.
     I tried using @types/whatwg-fetch and made sure it was in latest version and I keep getting the following error( Doesnt happen on typescript compiler 2.1.6)
![image](https://cloud.githubusercontent.com/assets/4141641/26264605/4fa5261e-3c92-11e7-8b7a-ce5acf05df07.png)

- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
I upgraded to 2.3.2 which is the latest version 
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ryan-codingintrigue

**Comment by aluanhaddad** [comment]
This is happening because the fetch declarations are now provided by TypeScript itself.

To resolve this error, either uninstall `npm:@types/whatwh-fetch` or use the `--noLib` flag.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
