### ISSUE TITLE
[ReactNative] all "transforms" properties could also be Animated.AnimatedInterpolation

### ISSUE THREAD

**Issue by Dimous** [DefinitelyTyped/DefinitelyTyped#16653]
Subj

PerpectiveTransform, RotateTransform,  RotateXTransform, RotateYTransform, RotateZTransform, ScaleTransform, ScaleXTransform, ScaleYTransform, TranslateXTransform, TranslateYTransform, SkewXTransform, SkewYTransform

```
StyleSheet.create({
    icon: {
        transform: [
            {
                rotateX: this.animatedValue.interpolate({
                    inputRange: [0, 1],
                    outputRange: ["0deg", "180deg"],
                }),
            }
        ]
    }
})
```
@alloy @gyzerok

**Comment by Dimous** [comment]
I must note, it applies to all _interpolatable_ properties of Animated.View

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
