### ISSUE TITLE
Need type declarations for zeromq

### ISSUE THREAD

**Issue by nikhilk** [DefinitelyTyped/DefinitelyTyped#16663]
Type declarations exist for zmq (usable via @types/zmq), but they are not usable for the preferred package - zeromq which is at https://www.npmjs.com/package/zeromq. The latter, zeromq, contains pre-built binaries.

Since @types/zeromq is missing, the following happens: one has to use this code:

    import zmq = require('zmq')

so that typescript can pick up the type declarations. However that doesn't work at runtime when the `require('zmq')` cannot be resolved. 

I believe the fix is to copy the zmq type declarations to zeromq, and publish  @types/zeromq to npm.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
