### ISSUE TITLE
Support deprecated html attributes like table@align or provide a workaround

### ISSUE THREAD

**Issue by yesil** [DefinitelyTyped/DefinitelyTyped#16693]
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript and even tried 2.4 snapshot version.
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Seems to be a feature request).
- [x] I have reported the issue to [TypeScript issue tracker](https://github.com/Microsoft/TypeScript-React-Starter/issues/15) first.

In our project, we need to render markup that needs to be displayed perfectly in email clients therefore we have to use html attributes like `align`, `border`, `hspace`, `vspace`.
Currently I cannot set `align` attribute on `table`element. I get the following error:

`TS2339: Property 'align' does not exist on type 'HTMLProps<HTMLTableElement>'.`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
