### ISSUE TITLE
[node] Writable stream does not have cork and uncork methods

### ISSUE THREAD

**Issue by mcheshkov** [DefinitelyTyped/DefinitelyTyped#16726]
`stream.Writable` and `NodeJS.WritableStream` does not have methods `cork()` and `uncork()`, and, according to docs, they are available since v6.0.0 in v6 and since v7.0.0 in v7.

https://nodejs.org/api/stream.html#stream_writable_cork
https://nodejs.org/api/stream.html#stream_writable_uncork

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

types/node/index.d.ts does not list any authors. The last commits were made by @ikokostya with @mhegazy and @DanielRosenwasser

**Comment by mcheshkov** [comment]
So it's available on node v8 now, what about v6 and v7?

**Comment by paulvanbrenk** [comment]
Feel free to port the changes to the appropriate definition files, and we'll merge them in.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
