### ISSUE TITLE
@types/node missing connecting value definition in net.Socket

### ISSUE THREAD

**Issue by yfyhsoft** [DefinitelyTyped/DefinitelyTyped#16733]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

This value is Added in node.js 6.1.0, It looks like there is no definition for this value.

**Comment by gurisko** [comment]
I made a pull request #16810 with this change. Let's wait for the feedback.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
