### ISSUE TITLE
Gulp types causing trouble

### ISSUE THREAD

**Issue by RWOverdijk** [DefinitelyTyped/DefinitelyTyped#16736]
https://travis-ci.org/SpoonX/wetland/builds/235954769#L181,L185

I want to mention the authors, but I can't find their github handles.

This used to work, so either the typings changed and I'm right to submit this issue, or I messed up and you're allowed to yell at me.

**Comment by RWOverdijk** [comment]
Update: I have removed this type from my project. I ended up not needing them.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
