### ISSUE TITLE
node http agent incomplete definition

### ISSUE THREAD

**Issue by npenin** [DefinitelyTyped/DefinitelyTyped#16735]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @

Dear team,

The http agent is incomplete as it is missing the createConnection method, getName method, ...

Could you please think about refreshing it ?

Thanks,
Nicolas

**Comment by bradharms** [comment]
How come this hasn't received any attention in the last 3 years?

**Comment by lili21** [comment]
Also missing the `on`, `once`, `emit` method.

**Comment by tricklynch** [comment]
Hey all,

I began fixing this, but I'm noticing some inconsistencies between the documentation and Node's code. You can see [here](https://github.com/nodejs/node/blob/master/lib/_http_agent.js#L168) that `Agent.prototype.createConnection = net.createConnection`. In `Agent`'s docs, it says that `agent.createConnection` returns a `stream.Duplex`, but in `net`'s docs, it says that `net.createConnection` returns a `stream.Socket`. I'm not entirely sure how to figure out when to use `net.Socket` vs `stream.Duplex`.

I have only tested one overload of `agent.createConnection`, since that is the issue I was running into [here](https://github.com/tricklynch/httpproxy/blob/master/src/index.ts#L39). I would appreciate if others could test the fix too.

Regardless, I have pushed a [fix](https://github.com/tricklynch/DefinitelyTyped/commit/6dcbb6978be969489b139ef325a622d6ff45ada7) to my fork. I held off on making a PR for now since it's only been lightly tested.

@lili21, I did not come across any documented, or undocumented, events in `Agent`. Can you give an example of how you're using those methods on `Agent`?

@SimonSchick, @weswigham, and @rbuckton, it'd be helpful if you reviewed the fix and provided some guidance on how I can figure out if `net.Socket` or `stream.Duplex` should be used. I @'d you three because you came up in `http.Agent`'s git blame.

Sincerely,
Patrick

**Comment by renatomariscal** [comment]
@tricklynch A `net.Socket` is a `stream.Duplex`: https://nodejs.org/docs/latest-v8.x/api/stream.html#stream_duplex_and_transform_streams. 

The Agent documentation says, you can override and any Duplex (which includes a Socket) is a valid result.
So although the default implementation returns a `net.Socket`, the definition of `Agent.keepSocketAlive` should be using `Duplex`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
