### ISSUE TITLE
[Hapi] Update cache options

### ISSUE THREAD

**Issue by AJamesPhillips** [DefinitelyTyped/DefinitelyTyped#16747]
Need to update cache options (typings and documentation)

https://github.com/hapijs/hapi/pull/3479/commits/79720b9f3d90709765076e7429770ee5533b000b

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
