### ISSUE TITLE
node.d.ts gives error "node.d.ts (98,9): Expected ';'"

### ISSUE THREAD

**Issue by danielmahadi** [DefinitelyTyped/DefinitelyTyped#1674]
Hi Guys,

I am using node.d.ts in my project and I get an error when I referenced node.d.ts. 

Here is how I compiled it: 
tsc app.ts

and there are errors that I got:
node.d.ts (98,9): Expected ';'
node.d.ts (1,8): modifiers can not appear before an expression statement or label

Please give me pointer on this issue.

Regards,
Daniel Mahadi

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
