### ISSUE TITLE
Can't use Console interface

### ISSUE THREAD

**Issue by troywweber7** [DefinitelyTyped/DefinitelyTyped#16785]
- [X] I tried using the `@types/node` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

There should be a way to import the shape of the `Console`. This way it can be used with `class MyConsole extends Console` or `class MyClass implements Console`.

I have tried the following to no avail (the PhpStorm IDE complains because it is trying to point me to the lib.es6.d.ts version instead of the node.d.ts version, or it complains about accessing a private member):

```
import { Console } from 'console'
```
```
import Console = NodeJS.Console
```
```
class MyConsole implements console.Console
```

None of these work. Am I missing something?

**Comment by andy-ms** [comment]
It actually is possible. You just need to do:
```ts
import { Console } from "console";
class C extends Console {
    log(message: string) {
        super.log(message);
        super.log(message);
    }
}
```

Although, it sounds like you don't actually want to extend console, you just want to use a type similar to it? In that case I would recommend writing an interface yourself. TypeScript will allow you to assign the native `console` to it if the types match, and you can also assign your own objects to it.

```ts
interface MyConsoleInterface {
    log(message: string): void;
    error(message: string): void;
}
const native: MyConsoleInterface = console;
const custom: MyConsoleInterface = {
    log(msg) {},
    error(msg) {},
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
