### ISSUE TITLE
Issues with params in TS 0.9.5 and JQuery

### ISSUE THREAD

**Issue by JayBeavers** [DefinitelyTyped/DefinitelyTyped#1681]
I've filed an issue with using JQuery Promises that surfaces in the TS 0.9.5 compiler that didn't happen in 0.9.1, see https://typescript.codeplex.com/workitem/2168.

I see a similar issue in the definition of JQuery.on():

```
on(events: string, handler: (eventObject: JQueryEventObject, ...args: any[]) => any): JQuery;
```

vs.

```
on(events: string, handler: (eventObject: JQueryEventObject, data: any) => any): JQuery;
```

I've looked at the JQuery documentation for [.on()](http://api.jquery.com/on/) and it seems the second definition, without the params array, is 'more correct'.  I would think that the params array definition would be a 'superset', but the 0.9.5 compiler seems to disagree.

Thoughts?  Is jquery.d.ts wrong to be using ...args: any[] in place of the simpler arg: any?  Or is the 0.9.5 TS compiler wrong in seeing a compatibility break between these two definitions?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
