### ISSUE TITLE
@types/react-native has wrong typings for FlatList>ListHeaderComponent

### ISSUE THREAD

**Issue by dinzo** [DefinitelyTyped/DefinitelyTyped#16820]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

I'm currently using FlatList on ReactNative 0.43.0:
https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js#L101
``` ListHeaderComponent?: ?(ReactClass<any> | React.Element<any>),```

The type definition is technically incorrect as it does not account for ```React.Element<any>```:

```ListHeaderComponent?: React.ComponentClass<any> | null```

As a result, you will see errors like this when trying to pass in an element as a ListHeaderComponent: 

```error TS2352: Type 'Element' cannot be converted to type 'ComponentClass<any>'. Type 'Element' provides no match for the signature 'new (props?: any, context?: any): Component<any, ComponentState>'```

@jeremistadler can you please weigh in?

**Comment by jeremistadler** [comment]
@dinzo You are correct, the type is wrong. 

I think this would work: 
```typescript
ListHeaderComponent?: React.ComponentClass<any> | React.StatelessComponent<any>
```

Would you mind doing a PR or should I?

**Comment by dinzo** [comment]
@jeremistadler i can do it, thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
