### ISSUE TITLE
Webpack Dev Server interface types locked in a namespace

### ISSUE THREAD

**Issue by atrauzzi** [DefinitelyTyped/DefinitelyTyped#16824]
- I tried using the `@types/webpack-dev-server` package and had problems.
- @maestroh

Would it make sense to remove the namespace all together and just have the interfaces as exported members as part of the module?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e74b92b39782d85d7845835944ccfb707111118e/types/webpack-dev-server/index.d.ts#L12-L50

This would be very useful as I wish to be able to create instances of the interfaces prior to providing them to a new dev server.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
