### ISSUE TITLE
@types/cropperjs misses method scale (updated definitions attached)

### ISSUE THREAD

**Issue by Arikael** [DefinitelyTyped/DefinitelyTyped#16837]
- [x] I tried using the `@types/cropperjs` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @stepancar

method scale is missing in the definition.
I attached a new index.d.ts with the added definitions -> [index.d.ts.txt](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1037517/index.d.ts.txt)

Hope this helps, please tell me if you need it in another format or something. I never did a pull request and have just beginner knowledge of git(hub)

**Comment by Arikael** [comment]
any news on that?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
