### ISSUE TITLE
[Request] mailgun-js

### ISSUE THREAD

**Issue by andybarron** [DefinitelyTyped/DefinitelyTyped#16842]
Repository: https://github.com/bojand/mailgun-js
Author mention: @bojand

**Comment by ZhangYiJiang** [comment]
mailgun-js types are now available, so this should probably be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
