### ISSUE TITLE
lodash assign/extend parameter 'T extends P' restriction

### ISSUE THREAD

**Issue by redthor** [DefinitelyTyped/DefinitelyTyped#1685]
Is this valid use of `_.assign`?

```
// Add 'boo' property to a function
var augmentedFn = _.assign( function() { return 'hi'; }, { boo: 'there' } );
augmentedFn();
// -> 'hi'
augmentedFn.boo
// -> there
```

When typescript compiles I get:

```
error TS2086: Type '{ boo: string; }' does not satisfy the constraint '() => string' for type parameter 'T extends P'.
```

Reference:
https://github.com/borisyankov/DefinitelyTyped/blob/master/lodash/lodash.d.ts#L2787

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
