### ISSUE TITLE
Mongoose updates for 4.8 and above

### ISSUE THREAD

**Issue by thaoula** [DefinitelyTyped/DefinitelyTyped#16861]
Hi @simonxca, @horiuchi,

What is the process if updating the typescript definitions for Mongoose to support 4.8 and above. 

I would like to use the new collation support in Mongo DB 3.4 and the support of collations helpers in Mongoose 4.8 and above.

Regards,
Tarek

**Comment by simonxca** [comment]
@thaoula Hi Tarek, can you try adding these lines https://github.com/simonxca/DefinitelyTyped/commit/43489c161b923211af7719c4a317964cbcf9dc29 to your definition file (`node_modules/@types/mongoose/index.d.ts`)  and see if that works for you?

I'm going to merge it into DefinitelyTyped assuming it works as expected. And the version number for these definitions is not really accurate. We just add stuff if we find anything missing.

**Comment by thaoula** [comment]
Many thanks @simonxca

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
