### ISSUE TITLE
@types/core-js: References to non-existent `PropertyKey`, `Symbol` constructor types broken

### ISSUE THREAD

**Issue by andybarron** [DefinitelyTyped/DefinitelyTyped#16887]
# Issues
- `DictConstructor` starting on line 340 references `PropertyKey`, which is never defined.
- Starting on line 1280 and continuing through line 2107, I'm getting the error `Propery 'X' does not exist on type SymbolConstructor`, starting with `for`, `hasInstance`, `isConcatSpreadable`, etc. and continuing until `unscopables`.
- Weirdly, this doesn't seem to bother `tsc` (probably since I never use the types in question), but `tslint` is spitting out all these errors during the type-checking phase.
- In a quick test, TypeScript assigns type `any` to e.g. `Symbol.keyFor` , which is wrong.

# Checklist
- [x] I tried using the `@types/core-js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rbuckton

**Comment by dafabulousteach** [comment]
When using tsc on CLI, the tsconig.json file is not referenced. I am stuck with this same error.

**Comment by hennievw** [comment]
I'm also experiencing the same issue...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
