### ISSUE TITLE
[@types/react] Access modifiers for ComponentLifecycle<P, S> interface function members

### ISSUE THREAD

**Issue by anton-pv** [DefinitelyTyped/DefinitelyTyped#16893]
- [ ] I tried using the `@types/react` package and had problems.

After latest update of `@types/react` to `15.0.25` access modifiers of `ComponentWithLifecycle` interface function members **are forced to be public in inherited classes**.
_(This is due to declaration merging - you now have both class and interface `Component<P, S>`)_

I'm working on a large project and we have many own components that are extending `React.Component<P,S>`. By using `protected` access modifiers for overridden react-specific members (_componentDidMount_, etc.)  we could hide them from being called outside of react (and i believe they shouldn't be public). 

What are benefits in changing them to be public?

Additionally, since we also use **tslint**, changing access modifiers in all project will also break **member-ordering** rule and require a lot of additional changes to rearrange them.

Simplified example and tsc error (works fine with `15.0.24`):

```
import * as React from "react";

export class MyComponent<P, S> extends React.Component<P, S>
{
    protected componentDidUpdate(prevProps: P, prevState: S)
    {
// [ts] Class 'MyComponent<P, S>' incorrectly extends base class 'Component<P, S>'.
//  Property 'componentDidUpdate' is protected in type 'MyComponent<P, S>' but public in type 'Component<P, S>'.
    }
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
