### ISSUE TITLE
problem when using the '@types/dhtmlxscheduler'

### ISSUE THREAD

**Issue by aymenelhajayed** [DefinitelyTyped/DefinitelyTyped#16911]
When using dhtmlxscheduler in my Angular2 application and trying to load the events data using the following code : 

```
scheduler.load("http://*******/v2/live/rest/evenement/json"+'?site='+localStorage.getItem('restPublisite'), "json");
let dp = new dataProcessor("http://*************/v2/live/rest/evenement/json"+'?site='+localStorage.getItem('restPublisite'));
    dp.init(scheduler);

```
The events are not displayed and have the following  error in navigator console : 

> error_handler.js:54 EXCEPTION: Uncaught (in promise): Error: Error in :0:0 caused by: dataProcessor is not defined

**It would be nice if someone could has already using dhtmlx scheduler with angular2 and can give me any help**

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
