### ISSUE TITLE
[request] Request for update to @types/nodemailer

### ISSUE THREAD

**Issue by jasonburrows** [DefinitelyTyped/DefinitelyTyped#16927]
- [X] I tried using the `@types/nodemailer` package and had problems.

The type information for node mailer is very out of date.  I'm requesting that this get updated.  I'm just not familiar enough with the project to do it myself but would be very happy if someone could update this type information for node mailer 4.

**Comment by gurisko** [comment]
Any chance for anyone to look at this? The current type definitions are for version 1.3.2 while Nodemailer 4.0.1 is the latest one. @andris9

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
