### ISSUE TITLE
FullCalendar version 3

### ISSUE THREAD

**Issue by jregistr** [DefinitelyTyped/DefinitelyTyped#16935]
Are there any plans on making updates to support version 3.4 of full calendar?
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@nestalk
@hasellcamargo
@panic175

**Comment by knightmeister** [comment]
[fullcalendar.d.zip](https://github.com/DefinitelyTyped/DefinitelyTyped/files/2320448/fullcalendar.d.zip)
Attached the .d.ts file as a zip from 3.9. These are obtainable via npm, i.e. `npm install fullcalendar`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
