### ISSUE TITLE
@types/uws pong method doesn't exist

### ISSUE THREAD

**Issue by hansagames** [DefinitelyTyped/DefinitelyTyped#16950]
`@types/uws`
looks like that method `pong` mentioned in typings doesn't exist in lib.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
