### ISSUE TITLE
ramda is missing sortWith function

### ISSUE THREAD

**Issue by xiongemi** [DefinitelyTyped/DefinitelyTyped#16971]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

@https://github.com/donnut @https://github.com/mdekrey @https://github.com/LiamGoodacre'

ramda type library is missing sortWith function: http://ramdajs.com/docs/#sortWith

**Comment by andy-ms** [comment]
@donnut @mdekrey @LiamGoodacre @mrdziuban

**Comment by tycho01** [comment]
@xiongemi consider trying the typings at [`types/npm-ramda`](https://github.com/types/npm-ramda/). while not merged here yet, they're ahead for typing ramda.

**Comment by KubaJastrz** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/34116971d51734a829306e7e3e7c7d9a0e3fe7cf/types/ramda/index.d.ts#L2358-L2364

Issue can be closed.

**Comment by KubaJastrz** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/34116971d51734a829306e7e3e7c7d9a0e3fe7cf/types/ramda/index.d.ts#L2316-L2320

`sortWith` is implemented. Issue can be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
