### ISSUE TITLE
PIXI typings are out of date

### ISSUE THREAD

**Issue by funkeh** [DefinitelyTyped/DefinitelyTyped#16986]
PIXI typings have been updated to 4.5.2, if the version here and the version on NPM could be updated that would be great.

https://github.com/pixijs/pixi-typescript

**Comment by clark-stevenson** [comment]
Thanks @funkeh  I just noticed this ticket after more than half a year!

Pixi has been updated here several times since this issue was open so we can assume this is stale.  It has been around a month or so since an update here but not much has changed on the definitions during this time.  The next update will be in the next couple of weeks.

**Comment by clark-stevenson** [comment]
@andy-ms  

Feel free to close this when you next have time.
