### ISSUE TITLE
JWT

### ISSUE THREAD

**Issue by svipas** [DefinitelyTyped/DefinitelyTyped#16989]
I'm using VS Code. It's based on TypeScript, it uses all TS definitions. The problem is with `jsonwebtoken` library. `jwt.sign(...,)` doesn't have Object.

// Type definitions for jsonwebtoken 7.2.0
// Project: https://github.com/auth0/node-jsonwebtoken
// Definitions by: Maxime LUCE <https://github.com/SomaticIT>, Daniel Heim <https://github.com/danielheim>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.2

```typescript
export declare function sign(payload: string | Buffer | object, secretOrPrivateKey: string | Buffer, options: SignOptions, callback: SignCallback): void;
```
In JWT you can pass any object you want, but simple `jwt.sign({userId: 1},...)` doesn't work it says:

```
Argument of type '{ userId: number; }' is not assignable to parameter of type 'string | object | Buffer'.
  Object literal may only specify known properties, and 'userId' does not exist in type 'string | object | Buffer'.
```

**Comment by andy-ms** [comment]
Should be fixed by Microsoft/TypeScript#16290. Please try it out with `typescript@next`.

**Comment by mdebruijne** [comment]
As @andy-ms mentioned, this is due to a bug in TypeScript (Microsoft/TypeScript#16235)

The workaround is to use type inference (or casting), for example;

```javascript
const payload = { "foo": "bar" }

jwt.sign(payload, secret)
```

**Comment by svipben** [comment]
@mdebruijne Thanks, already did that.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
