### ISSUE TITLE
@types/jsonwebtoken has broken backward compatibility

### ISSUE THREAD

**Issue by eliprand** [DefinitelyTyped/DefinitelyTyped#17007]
- [x] I tried using the `@types/jsonwebtoken` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mdebruijne and @andy-ms 

The change introduced 4 days ago with [this commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/47c53f1ca2d521f279d3e0f363b470a8b7cef316#diff-3a9f9d7466c591650d18e9a27bb201ba) has broken backwards compatibility. It is not accepting generic objects such as `{id:1234}`.

The following line of code:
`const signed = jsonwebtoken.sign({id:1234}, 'secret');`

gets the following error:
`Object literal may only specify known properties, and 'id' does not exist in type 'string | object | Buffer'.`

Using `tsc 2.2.2` same results at `tsc 2.3.4`

I believe this was mentioned in #16989

**Comment by andy-ms** [comment]
Should be fixed by Microsoft/TypeScript#16290. Please try it out with typescript@next once that's in.

**Comment by eliprand** [comment]
@andy-ms I will revert to `7.2.0` for now until the next release of TypeScript comes out. ETA?

**Comment by mdebruijne** [comment]
As @andy-ms mentioned, this is due to a bug in TypeScript (Microsoft/TypeScript#16235)

The workaround is to use type inference (or casting), for example;

```javascript
const payload = { "foo": "bar" }

jwt.sign(payload, secret)
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
