### ISSUE TITLE
node child_process.ForkOptions wrong definition

### ISSUE THREAD

**Issue by zh99998** [DefinitelyTyped/DefinitelyTyped#17017]
`stdio` can be string or array. 

``` TypeScript
export interface ForkOptions {
        cwd?: string;
        env?: any;
        execPath?: string;
        execArgv?: string[];
        silent?: boolean;
        stdio?: any[];  // <- here
        uid?: number;
        gid?: number;
    }
```
```
stdio <Array> | <string> See child_process.spawn()'s stdio. When this option is provided, it overrides silent. If the array variant is used, it must contain exactly one item with value 'ipc' or an error will be thrown. For instance [0, 1, 2, 'ipc'].
```
https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options

**Comment by andy-ms** [comment]
Pull requests accepted once we've upgraded to 8.0 (#16860)

**Comment by davalapar** [comment]
`detached?: boolean` also missing for `ForkOptions`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
