### ISSUE TITLE
node net.Socket and ReadableStream incompatible in strict mode

### ISSUE THREAD

**Issue by zh99998** [DefinitelyTyped/DefinitelyTyped#17020]
```typescript
import { Socket } from 'net';
import ReadableStream = NodeJS.ReadableStream;

let test: NodeJS.ReadableStream = new Socket();
```

tsconfig.json
```
{
   ...
   "strict": true
   ...
}
```

```
index.ts(4,5): error TS2322: Type 'Socket' is not assignable to type 'ReadableStream'.
  Types of property 'setEncoding' are incompatible.
    Type '(encoding?: string | undefined) => Socket' is not assignable to type '(encoding: string | null) => ReadableStream'.
      Types of parameters 'encoding' and 'encoding' are incompatible.
        Type 'string | null' is not assignable to type 'string | undefined'.
          Type 'null' is not assignable to type 'string | undefined'.
```

**Comment by andy-ms** [comment]
Pull requests accepted once we've upgraded to 8.0 (#16860)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
