### ISSUE TITLE
Regarding error of @types/webrtc

### ISSUE THREAD

**Issue by rajjerry** [DefinitelyTyped/DefinitelyTyped#17026]
I am using types/webrtc and I got error when complie the code on production mode.
I am using angular4 and my typescript version is 2.1.5.
Error is : 
**[at-loader] Checking finished with 2 errors                                                                                       
[at-loader] src/app/services/webrtc.service.ts:34:38                                                                              
    Property 'onDatachannel' does not exist on type 'RTCPeerConnection'.                                                          
                                                                                                                                  
[at-loader] src/app/services/webrtc.service.ts:142:38                                                                             
    Property 'onaddstream' does not exist on type 'RTCPeerConnection'.** 

In development I got same error and I got stream as well.
So please help me out to ran code on production mode.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
