### ISSUE TITLE
@types/vexflow has wrong definition for class Note

### ISSUE THREAD

**Issue by nearbydelta** [DefinitelyTyped/DefinitelyTyped#17023]
- [x] I tried using the `@types/vexflow` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sebastianhaas @andy-ms 

I found that constructor of class Note has wrong definition.
The original VexFlow requires BarNote has empty constructor and BarNote is a child class of Note.
But the current type definition requires a parameter for BarNote, because of line 622(constructor of Note).
`constructor(note_struct: {type?: string, dots?: number, duration: string});`
So I added duration for BarNote as follows, although this seems very weird, and it failed to display Stave.
`new BarNote({duration: '16'})`
I think the line 622 should declare note_struct as a optional parameter.
When I fixed this manually in index.d.ts as follows, it seemed everything works fine.
`constructor(note_struct?: {type?: string, dots?: number, duration: string});`

Is this safe for changing `note_struct` as optional parameter?

**Comment by andy-ms** [comment]
Pull requests welcome.

**Comment by bohoffi** [comment]
Hi @nearbydelta as mentioned in #17817 

But I think that this will not completely work as expected.
Although this will work with `BarNote` it will crash with `Note` if one **does not pass** the parameter when constructing note as of:
```ts
if (!note_struct) {
  throw new Vex.RuntimeError(
    'BadArguments', 'Note must have valid initialization data to identify duration and type.'
  );
}
```
in the `Note` constructor.

@sebastianhaas @rquiring any thoughts on this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
