### ISSUE TITLE
Highcharts, full version 5 support?

### ISSUE THREAD

**Issue by ipip2005** [DefinitelyTyped/DefinitelyTyped#17024]
Highcharts 5 has some exciting new features like Accessibility in chart options.
It would be awesome that @types/highcharts could also be upgraded to version 5 and have these new options in definitions.

  - Authors: @damianog @baltie @AlbertOzimek

**Comment by hanssens** [comment]
@ipip2005 I had the same and setup PR #17970 that supports v5.0.10. Hope someone has the time to look at it to get it approved.

**Comment by hanssens** [comment]
The mentioned PR #17970 has been merged and is now also available through npm. If there are any discrepancies they should ideally be registered as seperate issues. 

@ipip2005 I believe this fixes this particular issue?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
