### ISSUE TITLE
@types/tinymce plugins props in init Settings

### ISSUE THREAD

**Issue by thiagolacerda** [DefinitelyTyped/DefinitelyTyped#17035]
This issue is more of a general question for the maintainers of tinymce types @martinduparc and @iPoul.
Lot of users use tinymce plugins, and the vast majority of those plugins need the dev to pass some configuration properties in the init Settings.
Currently, the Settings that are exposed in the type definitions here does not contain any of those plugins attributes.
What you guys think would be the best way to support those here? Add everything in the Settings interface? Create separate interfaces?
I'm willing to submit PRs in order to support them, but I would like to gather your advice first.

Thanks

**Comment by JosephFoti** [comment]
^ Seconded, specifically noting that the types for `base_url` and `suffix` are missing which are necessary for initializing locally hosted tinyMCE.js files in Angular 7. Also willing to submit a PR to patch this if need be.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
