### ISSUE TITLE
Breaking Change : TypeScript 2.4 

### ISSUE THREAD

**Issue by yuit** [DefinitelyTyped/DefinitelyTyped#17036]
Thanks @RyanCavanaugh for investigating.

**Need investigation**
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bittorrent-protocol/index.d.ts#L82
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-zoom/d3-zoom-tests.ts#L107
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/falcor-router/falcor-router-tests.ts#L128
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/kefir/kefir-tests.ts#L88
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/oibackoff/oibackoff-tests.ts#L23
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/selenium-webdriver/test/index.ts#L824

**Seem good**
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose-sequence/mongoose-sequence-tests.ts#L19
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/passport-local-mongoose/passport-local-mongoose-tests.ts#L34

**Correct**
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/multiplexjs/index.d.ts#L293
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/observe-js/index.d.ts#L104

**Comment by tomwanzek** [comment]
Can d3-zoom be removed from this list of needs investigation? Just doing some D3-related housekeeping... 😄 :

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
