### ISSUE TITLE
three: Wrong declaration for class PolyhedronGeometry in three-core.d.ts

### ISSUE THREAD

**Issue by matthewtebbs** [DefinitelyTyped/DefinitelyTyped#17041]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript.

The current type is declared as using arrays of Vector3 and Face3 as,

```typescript
export class PolyhedronGeometry extends Geometry {
    constructor(vertices: Vector3[], faces: Face3[], radius?: number, detail?: number);

    parameters: {
        vertices: Vector3[];
        faces: Face3[];
        radius: number;
        detail: number;
    };
    boundingSphere: Sphere;
}
```

It should be using declared as using arrays of numbers like this,

```typescript
export class PolyhedronGeometry extends Geometry {
    constructor(vertices: number[], indices: number[], radius?: number, detail?: number);

    parameters: {
        vertices: number[];
        indices: number[];
        radius: number;
        detail: number;
    };
    boundingSphere: Sphere;
}
```

To match the declaration in _three/src/geometries/PolyhedronGeometry.js_.

**Comment by matthewtebbs** [comment]
Created PR [#17072](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17072)

**Comment by matthewtebbs** [comment]
(Re-created) PR for this as [17074](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17074)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
