### ISSUE TITLE
[Request] Fluent.js

### ISSUE THREAD

**Issue by voodooattack** [DefinitelyTyped/DefinitelyTyped#17079]
It would be amazing to have TS definitions for [Fluent.js](https://github.com/projectfluent/fluent.js).

I tried making them myself but I'll be the first to admit that I'm no expert at writing definition files.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
