### ISSUE TITLE
@types/realm: cannot use ObjectClass

### ISSUE THREAD

**Issue by diggyk** [DefinitelyTyped/DefinitelyTyped#17109]
@Akim95

No one on StackOverflow has been able to help me use the ObjectClass type.  Realm expects the `schema` to be on the constructor but just passing in constructors in an array fails type checking for `ObjectClass[]`

https://stackoverflow.com/questions/44470349/using-typescript-with-realm-js

**Comment by Akim95** [comment]
Ok, I will check this issue later.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
