### ISSUE TITLE
interface GraphQLField in definition.d.ts file is not correct

### ISSUE THREAD

**Issue by nisimjoseph** [DefinitelyTyped/DefinitelyTyped#17105]
- [x] I tried using the `@types/graphql` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `DefinitelyTyped/types/graphql/type/definition.d.ts`) so they can respond.
  - Authors: @firede 

in the `interface GraphQLField` field `args` is not supposed to be an `Array`. it a `Hash` `{[field:string]:GraphQLArgument}`.
the GraphQL runtime is not accepting this Array type and give runtime exception.

**Comment by corydeppen** [comment]
This has been open for a while and I noticed the folks mentioned in the main graphql declaration file weren't included on this issue.

/cc @TonyPythoneer, @calebmer, @intellix, @kepennar, @freiksenet, @IvanGoncharov, @DxCx

**Comment by IvanGoncharov** [comment]
@nisimjoseph It's correctly defined as an Array, see `graphql-js`:
https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L674
same as here: 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/graphql/type/definition.d.ts#L316

In `graphql-js` it's done intentionally to preserve the order of arguments.

@corydeppen There are no discrepancies, so it's safe to close this issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
