### ISSUE TITLE
Can the visjs typing be made to work with Typescript v1?

### ISSUE THREAD

**Issue by hornetnz** [DefinitelyTyped/DefinitelyTyped#17126]
Trying to get visjs added to my project, which is using Typescript 1.7.5. I installed dt~vs, but get a lot of compilation errors on the file. I assume this is due to my TS version. Is there an older version I can pull that will be compatible? Or any way to modify the existing to satisfy TS 1.7.5?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
