### ISSUE TITLE
mongoose dependency error

### ISSUE THREAD

**Issue by rwpino** [DefinitelyTyped/DefinitelyTyped#17128]
- [ ] I tried using the `@types/mongoose` package and had problems.
node_modules/@types/mongoose/index.d.ts(1310,38): error TS2339: Property 'Decimal128' does not exist on type 'typeof "mongodb"'.
I solved removing 
class Decimal128 extends mongodb.Decimal128 {} declaration from line 1310

**Comment by andy-ms** [comment]
Might have to do with your version of `@types/mongodb`. Are they both the latest version?

**Comment by YouriT** [comment]
I think it might be due to the dependency being `"@types/mongodb": "*",` and the fact that the last version including Decimal128 should require a version of @types/mongodb that is higher than 2.2. In my case every `yarn install` does install me @types/mongodb@2.1.41 which doesn't contain `Decimal128`.

**Comment by YouriT** [comment]
To solve it had to remove the `yarn.lock` and install again (so that it takes the last version of mongodb types). But the correct thing to do would be to put the proper version dependency in the types/mongoose.

**Comment by YouriT** [comment]
@rwpino why did you close this? IMO it's not fixed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
