### ISSUE TITLE
[@types/reactstrap] Support react-router props

### ISSUE THREAD

**Issue by mjdease** [DefinitelyTyped/DefinitelyTyped#17123]
- [x] I tried using the `@types/reactstrap` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alihammad, @mfal, @danilobjr

Reactstrap components can accept react router props for navigation purposes.
For example this code works but the current typings disallow it:
```
<Button tag={Link} to={this.props.path}>{this.props.buttonText}</Button>
<NavLink tag={Link} to={this.props.path}>{this.props.linkText}</NavLink>
```

More discussion on this:
https://github.com/reactstrap/reactstrap/issues/83#issue-168537815
https://github.com/reactstrap/reactstrap/issues/13#issuecomment-267846609

**Comment by corydeppen** [comment]
Adding `[key: string]: any;` to interfaces that have a `tag` prop might be an easy, flexible way to support scenarios like this where the component isn't in the React or TypeScript definition files. This approach is also mentioned in [reactstrap/reactstrap#276 (comment)](https://github.com/reactstrap/reactstrap/issues/276#issuecomment-297663082).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
