### ISSUE TITLE
better type for process.on("message")

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#17138]
Ref: #17137

**Comment by Flarna** [comment]
It seems there is more needed then #17137 as "message" was added only for process.on() but not for all the other EventEmitter Apis.
Besides that it's not longer possible now to register/emit any other event types, whether specified once like "newListener" or "removeListener" nor customer events.
At least not with Typescript 2.3. Not sure why typescript is not selecting the methods in the base class which allow  any string/symbol.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
