### ISSUE TITLE
Incorrect ambient declarations for require

### ISSUE THREAD

**Issue by coderfin** [DefinitelyTyped/DefinitelyTyped#1716]
Currently the "Ambient declarations for 'require'" declare requirejs and require as type Require.  The problem with this is that require can also have a type of RequireConfig. This is the case if you define the config object as the global variable require before require.js is loaded (http://requirejs.org/docs/api.html#config).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
