### ISSUE TITLE
component should allow React.StatelessComponent

### ISSUE THREAD

**Issue by waynebrantley** [DefinitelyTyped/DefinitelyTyped#17164]
@types/react-router-dom

@tkrotoff @huy-nguyen 

Given a route
```<Route path='/someRoute' component={SomeComponent} />```

``SomeComponent`` has to be a ``React.Component``.  However, it should allow it to be a ``React.StatelessComponent`` too.

**Comment by huy-nguyen** [comment]
@waynebrantley What library are you talking about?

**Comment by waynebrantley** [comment]
@huy-nguyen 
Dang it....where did that go.  Anyway React-Router did not seem to like the stateless component.

**Comment by VSDekar** [comment]
@waynebrantley i have the same problem when using Route with Redux's connect() method, but no problem with a normal StatelessComponent.

How does your StatelessComponent look like?

**Comment by tkrotoff** [comment]
PR are welcome :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
