### ISSUE TITLE
Node fs.readFileSync filename parameter type 

### ISSUE THREAD

**Issue by BurtHarris** [DefinitelyTyped/DefinitelyTyped#17170]
- [x] I tried using the `@types/node@6.0.78` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @parambirs , @RobDesideri , @tellnes , @WilcoBakker 

The `filename` parameter to `fs`s `readFile()`, `readFileSync()`, `writeFile`, etc seems over constrained.    Is there some reason these were declared to be `string` rather than `string | Buffer | number`?   

See https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_fs_readfile_file_options_callback for info.

**Comment by mohammadprabowo** [comment]
Looks like type definition is wrong / not updated.

**Comment by snalesso** [comment]
Up

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
