### ISSUE TITLE
Select2: createTag method missing

### ISSUE THREAD

**Issue by StefanKern** [DefinitelyTyped/DefinitelyTyped#17180]
For `DefinitelyTyped/types/select2/index.d.ts` the `createTag` method is missing ([link ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/select2/index.d.ts)). 

This method is defined in the official plugin dolumention: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/select2/index.d.ts following.

This is espacially anoying since it is the only way to tell the plugin to use only tags from the list and not create them itself.

Workaround:
```
interface Select2OptionsWCreateTag extends Select2Options{
    createTag?: (params: any) => IdTextPair;
}

```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
