### ISSUE TITLE
@types/ramda/index"' has no exported member '__'

### ISSUE THREAD

**Issue by nottoseethesun** [DefinitelyTyped/DefinitelyTyped#17205]
- [x ] I tried using the `@types/ramda` package and had problems.
  - Authors: @donnut,  @mdekrey, @LiamGoodacre, @mrdziuban

I get, `.../node_modules/@types/ramda/index"' has no exported member '__'.` 

However, I need to use `R.__` for `curry`.   And I don't want to pull in the whole of rambda just to get `R._`.

**Comment by marcondag** [comment]
I'm not one of the original authors of `@types/ramda` but I am working on this currently.

**Comment by zernie** [comment]
Hey @marcondag, are you still working on this?

**Comment by marcondag** [comment]
@zernie 
I thought I'd posted a response here a while ago regarding this issue, but it is currently not something that is easy to solve and I've lost some bandwidth at work to work on this sort of thing.

There is a relevant discussion [here](https://github.com/types/npm-ramda/issues/173).

I would also recommend using [`types/npm-ramda`](https://github.com/types/npm-ramda) in general as the project there has a lot more momentum.

**Comment by zernie** [comment]
@marcondag wow this is much more complex than I thought it'd be. Thanks for the links you've provided.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
