### ISSUE TITLE
@types/bootbox missing definition for bootbox.init(function)

### ISSUE THREAD

**Issue by StevenLiekens** [DefinitelyTyped/DefinitelyTyped#17215]
- Package: `@types/bootbox` https://github.com/DefinitelyTyped/DefinitelyTyped/tree/a19e9bf8bf4a1c05cd1a17afbb3361c6e52c84af/types/bootbox
 - Authors: Vincent Bortone <https://github.com/vbortone/>, Kon Pik <https://github.com/konpikwastaken/>, Anup Kattel <https://github.com/kanup/>, Dominik Schroeter <https://github.com/icereed/>, Troy McKinnon <https://github.com/trodi/>, Stanny Nuytkens <https://github.com/stannynuytkens>

---

Bootbox supports supplying a callback function that is invoked when a dialog is opened.
It is documented here: http://bootboxjs.com/documentation.html#public-functions

This is the syntax:

```js
var dialog = bootbox.dialog({
    /* Your options... */
});
dialog.init(function(){
    // Do something with the dialog...
});
```

`init(function)` is not currently supported by the `@types/bootbox` package because `dialog()` and friends return `JQuery` instead of a custom type and there is no definition for `init()` on `JQuery`.

```js
interface BootboxStatic {
  alert(message: string, callback?: () => void): JQuery;
  alert(options: BootboxAlertOptions): JQuery;
  confirm(message: string, callback: (result: boolean) => void): JQuery;
  confirm(options: BootboxConfirmOptions): JQuery;
  prompt(message: string, callback: (result: string) => void): JQuery;
  prompt(options: BootboxPromptOptions): JQuery;
  dialog(message: string, callback?: (result: string) => void): JQuery;
  dialog(options: BootboxDialogOptions): JQuery;
  // ...
}

declare var bootbox: BootboxStatic;
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a19e9bf8bf4a1c05cd1a17afbb3361c6e52c84af/types/bootbox/index.d.ts#L88-L95

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
