### ISSUE TITLE
Replace many Thenable interfaces with PromiseLike

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#17251]
The following packages define a `Thenable` interface:

* `bluebird` (#17245)
* `consul`
* `ember`
* `es6-promise`
* `falcor`
* `hellojs`
* `highland`
* `html2canvas`
* `jquery`
* `selenium-webdriver`
* `rsvp`
* `tspromise`
* `typescript-deferred`
* `when`

Can these all be replaced with `PromiseLike`?

**Comment by leonard-thieu** [comment]
`Thenable` can be replaced in `jquery`. I defined it as an alias to `PromiseLike` to match jQuery's documentation.

Can I ask what's the motivation behind changing it?

**Comment by andy-ms** [comment]
Mostly just for deduplication. But we also want to avoid incorrectly authored interfaces, and correctly writing `PromiseLike` is harder than it looks.

**Comment by leonard-thieu** [comment]
> correctly writing `PromiseLike` is harder than it looks.

True. I experienced that first-hand trying to write `jqXHR` and `Deferred` for `jquery` (both are `Promise`-like interfaces). I'm _still_ not sure they're 100% correct.

**Comment by Torhal** [comment]
This seems to have broken some distinctly Bluebird-centric methods such as [spread](http://bluebirdjs.com/docs/api/spread.html) - code using types/sequelize v3 that previously existed without issue now gives the error ```[ts] Property 'spread' does not exist on type 'Promise<[myType, boolean]>'.```

**Comment by leonard-thieu** [comment]
Related https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10892

**Comment by Martin-Wegner** [comment]
Is the issue https://github.com/SeleniumHQ/selenium/issues/4391 related to this issue?

**Comment by taybin** [comment]
PR for highland here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36140

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
