### ISSUE TITLE
HammerJS definitions are missing constants

### ISSUE THREAD

**Issue by radix** [DefinitelyTyped/DefinitelyTyped#17264]
- [x] I tried using the `@types/hammerjs` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @milkisevil @codler

I am porting some plain Hammerjs-using code to Typescript. I notice that several constants are missing:

* SUPPORT_TOUCH
* SUPPORT_POINTER_EVENTS
* SUPPORT_ONLY_TOUCH 
* INPUT_TYPE_TOUCH
* INPUT_TYPE_PEN
* INPUT_TYPE_MOUSE
* INPUT_TYPE_KINECT
* PROPS_XY
* PROPS_CLIENT_XY

The only one that I use myself is `SUPPORT_TOUCH`, but I skimmed the code to find these others.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
