### ISSUE TITLE
Definition Request: jest-cli

### ISSUE THREAD

**Issue by matthieujabbour** [DefinitelyTyped/DefinitelyTyped#17271]
Hi,
Please consider adding new definition for `jest-cli` (can be found at https://github.com/facebook/jest/tree/master/packages/jest-cli).

Thanks for the amazing job already done here !

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
