### ISSUE TITLE
Stripe v2 StripeCard does not have id property

### ISSUE THREAD

**Issue by elynnaie** [DefinitelyTyped/DefinitelyTyped#17280]
- [x] I tried using the `@types/stripe` 2.0.2 package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

The v2 stripe type `StripeCard` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/stripe/v2/index.d.ts#L66) does not have the `id` property, which should be a string. According to the [Stripe API documentation](https://stripe.com/docs/api#tokens) cards will have `id` on them.

**Comment by galuszkak** [comment]
@denaje that's not true. Stripe v2 doesn't have in any response id of the card. It's only on server side, and Your link only show API for server side processing. You probably had in mind stripe-node which is different package and has `id` property see:
`https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/stripe-node/index.d.ts#L3825`.

This issue should be closed.

**Comment by dmayerdesign** [comment]
I think the real issue is that `@types/stripe-node` doesn't match the name of the package that it corresponds to, `stripe`. `@types/stripe` needs to be renamed to `@types/stripejs` or something similar so that this can be corrected.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
