### ISSUE TITLE
@types/vue-resource is outdated

### ISSUE THREAD

**Issue by EliaECoyote** [DefinitelyTyped/DefinitelyTyped#17293]
```"@types/vue-resource": "0.9.31"``` 
is not compatible with the latest current Vue version 
```"vue": "2.2.6"```

**Comment by Bleser92** [comment]
There is one option that you can try
[https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4](https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4)

**Comment by asulta** [comment]
Thank you @Bleser92 !
I guess I'll change library since I want my libraries to be typed in my project

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
