### ISSUE TITLE
@types/mapbox-gl "circle-color" should be "string | StyleFunction"

### ISSUE THREAD

**Issue by magnolo** [DefinitelyTyped/DefinitelyTyped#17294]
- [x] I tried using the `@types/mapbox-gl` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
- Authors: @dobrud, @alex3165, @andy-ms

hey hey,  thank you for pushing the types for mapbox-gl to the latest version. I am very pleased about that. But it think there is something missing. Within the CirclePaint Interface the property 'circle-color' is defined as 'string'. Shouldnt it be 'string | StyleFunction' because it is also possible for data-driven styling?

Thx a lot
M

**Comment by magnolo** [comment]
Also the 'fill-extrusion-pattern' inside the 'FillExtrusionPaint' should be optional?
plz correct me if i am wrong

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
