### ISSUE TITLE
underscore.d.ts - Invalid declaration of _Chain<T>.sort function

### ISSUE THREAD

**Issue by ArtemAvramenko** [DefinitelyTyped/DefinitelyTyped#17317]
- [x] I tried using the `@types/underscore` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

`compareFn` should return number, but [declared](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/underscore/index.d.ts#L6045) as:
```
sort(compareFn: (a: T, b: T) => boolean): _Chain<T>;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
