### ISSUE TITLE
[@types/openlayers] Coherence with @types/geojson

### ISSUE THREAD

**Issue by bbaia** [DefinitelyTyped/DefinitelyTyped#17321]
OpenLayers:
```
bbox is [number, number, number, number]
position is [number, number]
```

GeoJSON:
```
bbox is number[]
position is number[]
```

According to the specs, GeoJSON is OK

**Comment by osechet** [comment]
@bbaia Since you didn't mentioned the authors (as suggested in the template), I didn't see your issue until now. 
First it seems the GeoJSON definitions changed to go in the same direction as openlayers. So I think this issue is not relevant anymore.
Second, I don't think one was right or wrong. Both libraries handles coordinates and bounding boxes differently. openlayers expects a coordinate to be (x, y) when geojson expects it to (x,y) or (x,y,z). If you pass a Geojson coordinate into openlayers or the opposite, you cannot predict the behavior.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
