### ISSUE TITLE
@types/bootstrapTable

### ISSUE THREAD

**Issue by bgg520** [DefinitelyTyped/DefinitelyTyped#17340]
- [ ] I tried using the `@types/bootstrapTable` package and had problems.
the method like this:
$('#table').bootstrapTable('method', parameter);
can't be use;
the interface should be like this:
interface JQuery {
    bootstrapTable(options?: any, option?: any): JQuery;
}
and the method can be compile;

bootstrapTable document: http://bootstrap-table.wenzhixin.net.cn/documentation/
  - Authors: @....

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
