### ISSUE TITLE
@types/inquirer ChoiceOption value should be type any

### ISSUE THREAD

**Issue by jonavila** [DefinitelyTyped/DefinitelyTyped#17368]
- [ x ] I tried using the `@types/inquirer` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo 

I'm trying to pass an array of choices to a question using key value pairs but and I'm unable to use objects in the value property. Right now, values are restricted to strings. I've tested the use of objects and it worked as explained in:
https://github.com/SBoudrias/Inquirer.js/issues/392

 I propose a change to the value property of the interface ChoiceOption:

Current:
```        
interface ChoiceOption {
  name?: string;
  value?: string;
  type?: string;
  extra?: any;
  key?: string;
  checked?: boolean;
  disabled?: string | ((answers: Answers) => any);
}
```

Proposed:
```        
interface ChoiceOption {
  name?: string;
  value?: any;
  type?: string;
  extra?: any;
  key?: string;
  checked?: boolean;
  disabled?: string | ((answers: Answers) => any);
}
```

**Comment by psumstr** [comment]
adding @parvez

**Comment by psumstr** [comment]
@ppathan @tkqubo Thoughts?

**Comment by user3587412** [comment]
I agree, I think it makes sense to change the type to `any` since you can pass in any type for the `value` property.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
