### ISSUE TITLE
jquery: The result of $.parseHTML is no longer valid input for JQuery methods

### ISSUE THREAD

**Issue by Kovensky** [DefinitelyTyped/DefinitelyTyped#17381]
```ts
$('.someElement').append($.parseHTML(someInput)) // Node[] not assignable to Element[]
```

The type of `$.parseHTML` is now, indeed, more accurate (`$.parseHTML('some text outside tags')` produces a `TextNode` in the array), but now this is causing type errors on JQuery methods that do behave correctly even when receiving a `TextNode`, such as `append`.

**Comment by leonard-thieu** [comment]
I wasn't sure how to handle this situation. I was thinking I could make those methods more permissive and accept `Node` instead of `Element` but I didn't know which methods would accept `Node` without issue.

jQuery specifies either `Element` or `Element | Text` as the type for a parameter that accepts a DOM object. 
If it's the case that methods that specify `Element | Text` (like `.append()`) still behave correctly when given any `Node`, then those could be changed to accept `Node`.
