### ISSUE TITLE
node: Mark legacy APIs with @deprecated

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#17447]
This would help people who are [linting](https://palantir.github.io/tslint/rules/deprecation/) for the use of deprecated APIs.
Ref: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17433#discussion_r123829807
CC @Flarna

**Comment by Flarna** [comment]
Please note that legacy url api in NodeJs is not deprecated (at least not in NodeJs 8).

**Comment by andy-ms** [comment]
Anything else that could be marked though?
We might have comments for legacy APIs anyway, although we don't have tooling to warn you about that.

**Comment by Flarna** [comment]
see https://nodejs.org/api/deprecations.html
I have not checked the current definition in detail; at least some Buffer constructors are there which are deprecated.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
