### ISSUE TITLE
Node.Js v8 socket.connect() method

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [DefinitelyTyped/DefinitelyTyped#17462]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @parambirs @RobDesideri @tellnes @WilcoBakker 
----

According to docs https://nodejs.org/dist/latest-v8.x/docs/api/net.html#net_socket_connect
socket.connect() method definition should look like this:
```ts
connect(port: number, host?: string, connectionListener?: Function): net.Socket;
connect(path: string, connectionListener?: Function): net.Socket;
connect(options: Object, connectionListener?: Function): net.Socket;
```
in current version there is only two variants and :void return type.
am i missing something?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
