### ISSUE TITLE
404 error when trying to download the 'types/node' package when using sinopia

### ISSUE THREAD

**Issue by zbennett10** [DefinitelyTyped/DefinitelyTyped#17475]
- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

**Comment by zbennett10** [comment]
npm ERR! code E404
npm ERR! 404 Not Found: @types/node@^7.0.18

Getting a 404 when trying to download electron using Sinopia. When I switched my npm registry conifg variable to point straight to the npm's main registry, the problem was solved. I'm not sure why sinopia was getting a 404 error but I thought I'd drop this issue here in case it is a problem for more people.

**Comment by DanielRuf** [comment]
Same when using the official mirror https://skimdb.npmjs.com/registry

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
