### ISSUE TITLE
Massive.js Table.insert/update definitions are incorrect

### ISSUE THREAD

**Issue by dmfay** [DefinitelyTyped/DefinitelyTyped#17476]
@clarenceh hello! Per [this issue](https://github.com/dmfay/massive-js/issues/404) the Table `insert` and `update` functions in fact return Promises for objects if invoked with a single object rather than an array (for `insert`) or both a criteria and a changes object (`update`); the documentation was incorrect.

**Comment by clarenceh** [comment]
@dmfay hi! Thanks for the information and I had updated the type definition as per the latest document and it had been merged. Will be reflected in latest package (3.0.2) upon published.
Cheers.

**Comment by dmfay** [comment]
There's one issue with the change -- the original signature and return value for `save` were correct since it doesn't do bulk operations. It will fail an assert if given anything other than an object.

**Comment by clarenceh** [comment]
@dmfay Hi, thanks for the input. However, I have read the issue you mentioned and you mentioned the following:

**save is a very (very!) thin wrapper on update and insert, which is also affected -- given an object it returns an object, given an array it returns an array.** 

Base on the statement, I assume that when save take an object, it will return object, while return array when pass in an array. I have further updated the definition using TypeScript's overload feature:

    save(data: object): Promise<T>;
    save(data: object[]): Promise<T[]>;

Does you say that save only accept an object, but able to return object or array of objects? Kindly clarify and I will update the definition accordingly.

I am also thinking of directly put the TypeScript definition file into massive project itself instead of put it here separately, this will greatly simplify TS developers using massive (like me). I also can provide sample on how to use TS with massive.

Let me know your thought.

Thanks
Clarence

**Comment by dmfay** [comment]
`save` only accepts an object and will fail an assert if given anything else. The assert is [here](https://github.com/dmfay/massive-js/blob/master/lib/table.js#L138), although strictly speaking it looks like you could sneak an array in for inserts -- I should change that to `_.isPlainObject` so it's clearer what `save` is and isn't about.

I'm happy to review pull requests. If adding TypeScript definitions to Massive makes TS users' collective lives easier and doesn't affect the rest of us, I'm all for it! Please do add documentation & examples though :)

**Comment by clarenceh** [comment]
@dmfay OK I got it. So save will only accept object and hand over to insert or update, depends on whether the object includes the PK of the object. So I believe the following signature is more appropriate for the save operation:

`save(data: object): Promise<T>;`

I will update the definitions accordingly.

Regards
Clarence

**Comment by jnystrom** [comment]
@clarenceh it looks to me that the `Loader` definition is not correct.  This does not have the information around the document metatdata.  IE `documentPkType`:

```
   interface Loader {
        blacklist?: string | string[];
        whitelist?: string | string[];
        functionBlacklist?: string | string[];
        functionWhitelist?: string | string[];
        allowedSchemas?: string | string[];
        exceptions?: string | string[];
        scripts?: string;
    }
```

[Massive DOCS](https://dmfay.github.io/massive-js/connecting.html#loader-configuration-and-filtering):

 // override default 'serial' data type, used for new document
  // tables id/primary key, i.e. 'serial' or 'uuid'
  documentPkType: 'serial',

  // applies if documentPkType is set to 'uuid'. Override default
  // 'v4' UUID variation, i.e. 'v1', 'v1mc', 'v3', 'v4' or 'v5'
  uuidVersion: 'v4',

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
