### ISSUE TITLE
@types/async support question

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#17477]
- [x] I tried using the `@types/xxxx` package and had problems.

I am just trying to figure out the best way to mitigate this warning. I am willing to do whatever is right. 

**I am fairly sure there is nothing wrong with `@types/async`, I just need help figuring out how to do this one right.**

any help appreciated.

<img width="1002" alt="screenshot 2017-06-25 20 06 06" src="https://user-images.githubusercontent.com/11139560/27523410-e0ea0a92-59e1-11e7-93e3-56b9b077db14.png">

thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
