### ISSUE TITLE
Jquery and Angular project throws `Duplicate identifier 'cssPropertySetter'.` with @types/angular 1.6.22

### ISSUE THREAD

**Issue by nachshons** [DefinitelyTyped/DefinitelyTyped#17495]
After the last npm release 1.6.2. projects with  @types/angular and @types/jquery fail tslint.
This is caused by angular types now including jqlite.d.ts which clashes with jquery.d.ts

The error thrown by the tslint:

```
node_modules/@types/angular/jqlite.d.ts(799,6): error TS2300: Duplicate identifier 'cssPropertySetter'.
node_modules/@types/jquery/index.d.ts(705,6): error TS2300: Duplicate identifier 'cssPropertySetter'.
node_modules/@types/jquery/index.d.ts(707,5): error TS2374: Duplicate string index signature.
```

**Comment by DMaguireKane** [comment]
My build was failing when package.json had `"@types/angular": "^1.0.0"` which npm resolved to 1.6.22. 
This may have conflicted with my jquery version "^2.0.0" since angular 1.6 library is dependent on jquery 3 which my current setup does not support.

Anyway changing the package.json to use `"@types/angular": "~1.5.0"` fixed it for me.

**Comment by leonard-thieu** [comment]
I put in a PR to fix it (#17510).

Also, I hate type aliases.

**Comment by nachshons** [comment]
@leonard-thieu, @paulvanbrenk, Do you know when this will be published to NPM?

**Comment by ielektronick** [comment]
Hi guys.
Any updates on that? I see that PR is merged, although changes have not been published to NPM yet. :(

**Comment by andy-ms** [comment]
@ielektronick That was published, but it only affected earlier versions of jquery, so it won't affect you if you're using the 3.x branch.
