### ISSUE TITLE
Miss-named interface in mongodb package

### ISSUE THREAD

**Issue by cfstwilson** [DefinitelyTyped/DefinitelyTyped#17505]
Came across a typo in the interface `CollectionBluckWriteOptions`. Should be `CollectionBulkWriteOptions` (`Bluck` -> `Bulk`)

Figured I'd open an issue instead of a pull request because I don't know how API-breaking changes are handled.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
