### ISSUE TITLE
[@types/react] JSX element type 'Component<any, ComponentState>' is not a constructor function for JSX elements

### ISSUE THREAD

**Issue by morlay** [DefinitelyTyped/DefinitelyTyped#17567]
- [x] I tried using the `@types/react@15.0.33` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

lots of errors when I update from `15.0.30` to `15.0.33`

```
Error:(60, 5) TS2605:JSX element type 'Component<any, ComponentState>' is not a constructor function for JSX elements.
  Types of property 'setState' are incompatible.
    Type '{ <K extends never>(f: (prevState: ComponentState, props: any) => Pick<ComponentState, K>, callba...' is not assignable to type '{ <K extends never>(f: (prevState: {}, props: any) => Pick<{}, K>, callback?: (() => any) | undef...'.
      Types of parameters 'f' and 'f' are incompatible.
        Types of parameters 'prevState' and 'prevState' are incompatible.
          Type 'ComponentState' is not assignable to type '{}'.
            Type 'void' is not assignable to type '{}'.
```

Change `new (props?: P, context?: any): Component<P, ComponentState>` to `new (props?: P, context?: any): Component<P, typeof ComponentState>`  in `new` of `ComponentClass` will fix it

```
 interface ComponentClass<P = {}> {
    new (props?: P, context?: any): Component<P, typeof ComponentState>;
    propTypes?: ValidationMap<P>;
    contextTypes?: ValidationMap<any>;
    childContextTypes?: ValidationMap<any>;
    defaultProps?: Partial<P>;
    displayName?: string;
 }
```

**Comment by morlay** [comment]
Someone can help to create PR to fix it?
I could not download the huge repo 😿

**Comment by Kovensky** [comment]
It seems that that happens if the `ComponentState` is not assignable to `object`. It seems to be a bug with typescript generic defaults, where giving a value as a default prevents giving a value that is not compatible with it as an actual value.

The opposite problem happens if `null` is put as the default for the state -- an interface/object cannot be passed.

**Comment by tkrotoff** [comment]
Don't fully understand the context of your error, anyway:

`Type 'void' is not assignable to type '{}'` happens when doing something like `React.Component<void, ...>` (or  `React.Component<null, ...>` or `React.Component<undefined, ...>`) instead of `React.Component<{}, ...>`.
This is caused by React.Component now using default attributes: `React.Component<P = {}, S = {}>`.

**Comment by morlay** [comment]
@tkrotoff 
it is not an error for Props, it is for State.
may be just generic defaults issue

We can drop `Component` to make it use the defaults of `S`, too.

```ts
 interface ComponentClass<P = {}> {
    new (props?: P, context?: any): Component<P>;
    propTypes?: ValidationMap<P>;
    contextTypes?: ValidationMap<any>;
    childContextTypes?: ValidationMap<any>;
    defaultProps?: Partial<P>;
    displayName?: string;
 }
```

**Comment by morlay** [comment]
After clean and `npm install`, works again =. =

**Comment by jonathanconway** [comment]
@morlay worked for me too, but also had to remove my `yarn.lock` file.
