### ISSUE TITLE
@types/angular 1.5.x for typescript 2.4

### ISSUE THREAD

**Issue by klmdb** [DefinitelyTyped/DefinitelyTyped#17563]
Since the release of typescript 2.4, my angular 1.5 project doesn't build anymore.

I read [here](https://github.com/Microsoft/TypeScript/issues/16536)  that it should be fixed, but I only see updates to the 1.6.x version of the types, not the 1.5.x version.

**Comment by elijah-schow** [comment]
I'm getting similar errors in 1.6.x as well. Angular 1.6.6. @types/angular 1.6.32.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
