### ISSUE TITLE
Yarn: @types/uuid has later versions than the latest version.

### ISSUE THREAD

**Issue by robertmassaioli** [DefinitelyTyped/DefinitelyTyped#17561]
There looks to have been a version mistake in the Yarn packages:

![drag](https://user-images.githubusercontent.com/149178/27618931-6ddf55fc-5c02-11e7-9562-62b267d4d801.png)

Source: https://yarnpkg.com/en/package/@types/uuid

If we could delete all of the 3.3.* releases from yarn OR get a 3.4 version of uuid released that would be great.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
