### ISSUE TITLE
@types/node readFileSync doesn't allow sending a URL argument

### ISSUE THREAD

**Issue by xp500** [DefinitelyTyped/DefinitelyTyped#17574]
- [X] I tried using the `@types/node` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ikokostya

According to https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options `fs.readFileSync` can receive a `String`, `Buffer`, `URL` or `integer` as the `path` parameter. However, the types for node v7 only declare the `String` parameter.

**Comment by demurgos** [comment]
This issue can be closed now. Node's type definition define `url.URL` as a valid argument for the `fs` functions.

**Comment by ikokostya** [comment]
@xp500 Yes, in latest types versions for `Node.js 10.12` [`fs.readFileSync`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c34029e6e0361bf10a286e18aa8c9a3522d0230c/types/node/index.d.ts#L4946) takes [`PathLike`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c34029e6e0361bf10a286e18aa8c9a3522d0230c/types/node/index.d.ts#L3683) as argument, where `URL` is included.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
