### ISSUE TITLE
Problem with recompose `branch(condition, renderComponent(Component))`-pattern in TS 2.4

### ISSUE THREAD

**Issue by ahstro** [DefinitelyTyped/DefinitelyTyped#17570]
After upgrading to TypeScript 2.4.1, recompose's `branch(condition, renderComponent(Component))`-pattern - used in [their docs](https://github.com/acdlite/recompose/blob/master/docs/API.md#rendercomponent) - causes this error:
```
TS2345: Argument of type 'ComponentEnhancer<{}, {}>' is not assignable to parameter of type 'InferableComponentEnhancer'.
Type 'ComponentClass<{}>' is not assignable to type 'TComp'.
```

This particular error was fixed by changing the return type of `renderComponent` from `ComponentEnhancer<any, any>` to `InferableComponentEnhancer` for me, but I couldn't quite figure out the test suite nor the rest of the declaration file, so I didn't want to make a PR.

CC: Authors of the recompose declaration files: @iskandersierra, @mrapogee

**Comment by morlay** [comment]
Seems because of `ComponentClass` in `@types/react` #17567.

**Comment by zunder** [comment]
@ahstro did you manage to solve the problem according to @morlay comment? I am still having the problems getting it running.

**Comment by ahstro** [comment]
@zunder I hacked it for now, using `branch(something, renderComponent(Loading) as InferableComponentEnhancer)`

**Comment by krasevych** [comment]
I got the same problem but with `hoistStatics`.

```
const enhance = compose(...some)
export default hoistStatics(enhance)
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
