### ISSUE TITLE
React-Redux typings missing additional options for Connect

### ISSUE THREAD

**Issue by BrianHanechak** [DefinitelyTyped/DefinitelyTyped#17584]
- [X] I tried using the `@types/react-redux` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @seansfkelley @thasner 

The connect function in React-Redux supports an optional "options" parameter. This has five properties defined, but only one of them is defined in this typing. This creates a problem if you upgrade to TypeScript 2.4, causing a TS2559 error if you pass in an "options" value that contains one of the four missing arguments but none of the common arguments.

The optional arguments that are missing are:

    areStatesEqual
    areOwnPropsEqual
    areStatePropsEqual
    areMergedPropsEqual

There's also an argument in this typing (`withRef`) that does not appear to be part of the React-Redux API anymore.

**Comment by vashchukmaksim** [comment]
+1

**Comment by vashchukmaksim** [comment]
+1 Really need it!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
