### ISSUE TITLE
How to declare extra content for an exist node module which has @types/index.d.ts file?

### ISSUE THREAD

**Issue by mrdulin** [DefinitelyTyped/DefinitelyTyped#17598]
I use redux-promise-middleware, and install its types definition file.

It means, I already have `node_modules/@types/redux-promise-middleware/index.d.ts` file.

Here is the code:

```ts
import { Middleware } from 'redux';

export default function promiseMiddleware(config?: { promiseTypeSuffixes: string[] }): Middleware;
```

But, I want to declare some extra variables, so, I wrote my own definition file like below:

`src/types/index.d.ts`

```ts
// -- redux-promise-middleware
declare module 'redux-promise-middleware' {
  export const PENDING: string;
  export const FULFILLED: string;
  export const REJECTED: string;
}
// --
```

But tsc give me an error:

`Error:(4, 8) TS1192:Module ''redux-promise-middleware'' has no default export.`

My guess is my own `index.d.ts` overwrite the `node_modules/@types/redux-promise-middleware/index.d.ts`.

So, My question is, how to solve this conflict, I want them work together.

@ianks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
