### ISSUE TITLE
Sequelize's typings use a non-Promise-compatible Promise (Bluebird)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DefinitelyTyped/DefinitelyTyped#17599]
Since Bluebird added some changes that conflict with the ES2015 Promise definition, the following happens when you try to assign a regular Promise to a Bluebird one.

```
type Promise<any> is not assignable to Bluebird<any>
```

Very frustrating. In the case of  `sequelize`, specifically, see the following code: 
```typescript
export interface MissionModel extends Sequelize.Model<MissionInstance, MissionAttributes> {
    create(missionAttributes: MissionAttributes, options?: Sequelize.CreateOptions): Promise<MissionInstance>;
}
```

`MissionModel` will have the following error unless `Promise` is `import`ed as `* from "bluebird"`:
```
src\server\models\mission.ts(3,18): error TS2430: Interface 'MissionModel' incorrectly extends interface 'Model<MissionInstance, MissionAttributes>'.
  Types of property 'create' are incompatible.
    Type '(MissionAttributes: MissionAttributes, option?: CreateOptions | undefined) => Promise<MissionInst...' is not assignable to type '(values?: MissionAttributes | undefined, options?: CreateOptions | undefined) => Bluebird<Mission...'.
      Type 'Promise<MissionInstance>' is not assignable to type 'Bluebird<MissionInstance>'.
        Types of property 'then' are incompatible.
          Type '<TResult1 = MissionInstance, TResult2 = never>(onfulfilled?: ((value: MissionInstance) => TResult...' is not assignable to type '{ <U>(onFulfill?: ((value: MissionInstance) => U | PromiseLike<U>) | undefined, onReject?: ((erro...'.
            Type 'Promise<any>' is not assignable to type 'Bluebird<any>'.
```

Related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11027.

**Comment by lhecker** [comment]
I don't believe this issue is in any way related to #11027, which is about the quite possible task of assigning `Bluebird<T>` instances to `Promise<T>`. (The only thing missing is that Bluebird does not set the `Symbol.toStringTag ` property yet, which makes them not quite compatible.

This issue on the other hand is about you trying to assign `Promise<T>` instances to `Bluebird<T>` instances, which will never work, since Bluebird _extends_ the native Promise interface, making such an assignment impossible.

The only question now is wether the Sequelize typings are incorrect by requiring the use of Bluebird promises. I sadly cannot judge this though, as I'm not really familiar with how their code works. Is it even possible to use native Promises with Sequelize? And even if that's the case: Are all functions compatible or only some? The only thing I know is that their internal code is using Bluebird, which makes the interfaces requiring Bluebird as well a sane default option.

Apart from that I'd be happy to review any PRs, but I fear I do not have enough time at hand to solve this issue myself. 😕

**Comment by JoshuaKGoldberg** [comment]
I think this has probably aged away by now.
