### ISSUE TITLE
email-templates misses result as Promise

### ISSUE THREAD

**Issue by janwo** [DefinitelyTyped/DefinitelyTyped#17595]
- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sunild @cyrilschumacher 

First, thanks for your definitions. Unfortunately, I realized that an alternative return type of a Promise is missing. The official tests (https://github.com/crocodilejs/node-email-templates/blob/master/examples/handlebars_i18n/index.js) state, that you can use the render-method as a promise. I tested it and it works!

**Comment by cyrilschumacher** [comment]
Hello, indeed, this type of return is not proposed by the definition. You can make a pull request to add this type, otherwise I can propose a pull request soon.

**Comment by janwo** [comment]
@cyrilschumacher I added a PR, see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17603.

**Comment by cyrilschumacher** [comment]
@janwo Nice! I have approved your pull request ;)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
