### ISSUE TITLE
dtslint does not support TypeScript 2.4

### ISSUE THREAD

**Issue by iRoachie** [DefinitelyTyped/DefinitelyTyped#17626]
Since Typescript 2.4 was released two days ago it broke a lot of dependencies. We need to be able to lint definitions against version 2.4 which currently gives an error.

`Could not parse version: line is '// TypeScript Version: 2.4'`

**Comment by leonard-thieu** [comment]
I think the maintainers typically wait a month before allowing new version features. However, I do think it'd be nice to be able to **test** definitions against the current version of TypeScript in addition to the declared version (especially since tests complete much faster now).

Personally, I'd like to be able to test if my weak type workaround works correctly in both 2.3 and 2.4.

**Comment by iRoachie** [comment]
Ideally I’d like to be able to pass a version flag to the test script. Right now many libraries are accepting PRs for braking changes introduced in Typescript 2.4 but there’s no way to test if these PRs actually work correctly

**Comment by leonard-thieu** [comment]
That sounds like a good idea.

Could also consider extending the `TypeScript Version` header to declare additional versions that you want to test against.

For example:
```typescript
// TypeScript Version: 2.3 2.4
```

would allow the 2.3 feature set and test against TypeScript 2.3 and 2.4.

**Comment by leonard-thieu** [comment]
@andy-ms What do you think about this?

**Comment by andy-ms** [comment]
I think that field should specify the minimum typescript version, and not list specific later versions. A comment listing `2.3 2.4` would look pretty silly once `2.9` is the latest.
On the TS team we do a full test of DefinitelyTyped when a new TS version is published. We could choose to run `typescript@next` tests as part of the test suite, but that would mean that breaking changes in the nightlies would block unrelated pull requests. We could alter dtslint to always test against `typescript@latest` though.

**Comment by leonard-thieu** [comment]
Always testing against latest sounds good to me.

**Comment by iRoachie** [comment]
@andy-ms Is this actionable? Something we can work on?

**Comment by andy-ms** [comment]
If you want to help speed it up you could make a pull request to dtslint.

Currently in `index.ts` we call `testWithVersion` twice, but only if there was a failure in the older version. I think this code should be removed from `index.ts` (so `testWithVersion` is called only once), and this functionality handled in the `expect` rule instead.

In `expectRule.ts`, it receives a path to an older TypeScript installation. It then creates a Program object using that version of TS and calls `getPreEmitDiagnostics` on that.
This could be changed to run the rule twice, once on Program for the passed-in typescript version, and then on a Program created with a regular `require("typescript")`, which should be the latest. (Change `package.json` to have a dependency on `"typescript": "latest"` instead of `"typescript": "next"`.) Error message should reflect the TS version they came from, unless they are present in both versions.
