### ISSUE TITLE
jquery.d.ts

### ISSUE THREAD

**Issue by IvanKosh** [DefinitelyTyped/DefinitelyTyped#17646]
pls add

    contextmenu(handler: (eventObject: JQueryEventObject) => any): JQuery;
    contextmenu(eventData: any, handler: (eventObject: JQueryEventObject) => any): JQuery;

right-button-click event

**Comment by leonard-thieu** [comment]
These are available in `@types/jquery` v3. Are they an option for you?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
