### ISSUE TITLE
chalk 2 has released. Update @types/chalk

### ISSUE THREAD

**Issue by vajahath** [DefinitelyTyped/DefinitelyTyped#17644]
- [x] I tried using the `@types/chalk` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Diullei @Bartvds @nicojs 

[Chalk 2](https://github.com/chalk/chalk/releases/tag/v2.0.0) has released. It'd be awesome if we have the `.d.ts` for chalk 2.

**Comment by BendingBender** [comment]
It seems that they are already working on a typedef that will be distributed directly with the package. When they are done with it, we should make a pull request here to remove the typings.

The progress is being tracked here: https://github.com/chalk/chalk/pull/169

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
