### ISSUE TITLE
different types for write function for knockout writeable computed

### ISSUE THREAD

**Issue by nmehlei** [DefinitelyTyped/DefinitelyTyped#1766]
Hi,
The current definition of KnockoutComputedDefine<T> requires that the return type of read() and the parameter type of write(T) be the same. That is not required by knockout and limits the useability severely. 
I changed 
write? (value: T): void; 
to
write? (value: any): void;
locally to work around it. I don't see any other way than using any except using two generic parameters, one for the write function argument.

**Comment by ThomasMichon** [comment]
If you want to achieve this, it might be best to define an alternate interface for ```KnockoutComputed<T>```, for example ```KnockoutSplitComputed<R, W>```. If you then invoked ```ko.computed``` and passed ```read``` and ```write``` functions of different types, you would get back an instance of that new interface. You could add that as an overload to the typing for ```ko.computed```.

This way those who depend on type-safety for their existing read/write computed observables would not lose it just because of the available alternate use case.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
