### ISSUE TITLE
$setValidity in INgModelController incorrect type?

### ISSUE THREAD

**Issue by katharinekerr** [DefinitelyTyped/DefinitelyTyped#17662]
- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @diegovilar @thorn0 @calebstdenis @leonard-thieu 

Firstly, thanks for the types. 

I have an issue with using the `$setValidity` type in the INgModelController interface.

Currency it is: 
`$setValidity(validationErrorKey: string, isValid: boolean): void;`
and I believe it should be: 
`$setValidity(validationErrorKey: string, isValid: boolean | undefined | null): void;`

since `isValid` can be also be `undefined` or `null`. For reference https://docs.angularjs.org/api/ng/type/ngModel.NgModelController.

Thanks!

**Comment by leonard-thieu** [comment]
👍

Seems right to me. Do you want to put in the PR for this?

**Comment by katharinekerr** [comment]
Awesome. Yup, will do. I'll try to have it out by the end of the week.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
