### ISSUE TITLE
@types/material-ui is missing a type for typography 

### ISSUE THREAD

**Issue by vadapallikrishna** [DefinitelyTyped/DefinitelyTyped#17679]
I am getting following error 
./src/App.tsx
(5,24): error TS7016: Could not find a declaration file for module 'material-ui/Typography'. '/home/krishna/hacks/fnhck/node_modules/material-ui/Typography/index.js' implicitly has an 'any' type.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
