### ISSUE TITLE
@types/bluebird forces a compiler upgrade

### ISSUE THREAD

**Issue by octogonz** [DefinitelyTyped/DefinitelyTyped#17671]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @fengb @well1791 @andy-ms

The `@types/bluebird` package was recently changed such that it requires the TypeScript 2.3 compiler.  It also has an undocumented dependency on ES2015.Collection, i.e. I need to a use a command-line like this:

```
tsc example.ts --lib DOM,ES5,ScriptHost,ES2015.Collection
```

With TypeScript 2.2.2, I get this error:

```
node_modules/@types/bluebird/index.d.ts(50,17): error TS1005: ',' expected.
node_modules/@types/bluebird/index.d.ts(50,31): error TS1005: ',' expected.
```

With TypeScript 2.3.4, the error goes away.

Although it's nice to always be on the bleeding edge, not everyone has that luxury.  My group is responsible for around 100 projects that build using a common tool chain.  Last time we upgraded the TypeScript compiler, it took us an entire week to migrate everything, and then we also needed to publish migration instructions for our third party developers.  Thus, even though TypeScript version 2.2.2 seems "ancient", three months is pretty new from the perspective of a core library like Bluebird that should support as broad an audience as possible.

We have worked around this problem by downgrading to an older version of `@types/bluebird`.  However, downgrading itself was problematic, since we didn't have an explicit dependency on Bluebird.  We got accidentally upgraded because [DefinitleyTyped packages have unconstrained version numbers for their dependencies](https://github.com/Microsoft/types-publisher/issues/360#issuecomment-312401100).

**Comment by fengb** [comment]
Looks like we added these dependencies:
1. Default type arguments for `.then<TResult1 = T>()` _(TS 2.3)_
2. `.props(Map)` _(ES2015.Collection)_ or _(ES6)_
3. `.props(object & {})` _(TS 2.2)_
4. `.props({ [K keyof T] })` _(TS 2.1)_

1 can be reimplemented in 2.1 semantics, but I'm not quite sure about 2 + 3. I can give it a shot though.

**Comment by pgonzal** [comment]
Thanks!

**Comment by fengb** [comment]
Seems like this was intentionally changed to match the standard (2.3) `PromiseLike` definition: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17245

I'm disinclined to revert this...

**Comment by lhecker** [comment]
@fengb @pgonzal I don't think this issue can be "solved". The only regrettable part is rather that we didn't push out a new semver major version when we made Bluebird TypeScript v2.3+ only. Instead it'd probably be for the best if https://github.com/Microsoft/types-publisher/issues/360 is solved soon.

Reason being: Compatibility with `PromiseLike` is (or will be) an important feature for Bluebird, so we absolutely cannot revert this. The dependency on `ES2015.Collection` is also regrettable, but Bluebird conditionally checks for the existence of ES6 `Map`s and supports them if that's the case. Since TypeScript has no "easy" tools for conditional compilation we had to add it unconditionally to the typings. In general this shouldn't pose a problem though right?

AFAIR it should be possible to do simple version pinning with NPM though, which should solve this issue in the meantime, right?

**Comment by dearibujar** [comment]
Is there a fix or workaround for this?

**Comment by andy-ms** [comment]
@dearibujar `npm install @types/bluebird@ts2.2`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
