### ISSUE TITLE
Leaflet Layer.addTo() should allow LayerGroups.

### ISSUE THREAD

**Issue by Timmmm** [DefinitelyTyped/DefinitelyTyped#17687]
See https://github.com/Leaflet/Leaflet/pull/5600

@alejo90

The `Layer.addTo()` documentation says the type should be `Map`, but it actually can also be `LayerGroup`. I suspect this is because their documentation system LeafDoc might not support sum types. Or it could just be an oversight.

**Comment by alejo90** [comment]
Fixed in #17688

**Comment by Timmmm** [comment]
Oops thought it had been merged already...

**Comment by franklinyu** [comment]
It is merged now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
