### ISSUE TITLE
Wrong type returned from $input.select2('data')

### ISSUE THREAD

**Issue by styfle** [DefinitelyTyped/DefinitelyTyped#1769]
I thought this was a [bug with TypeScript](https://typescript.codeplex.com/workitem/2182) but the authors said the overloaded method is defined wrong. I'll repeat the problem here and hopefully someone can figure out the root cause:

The wrong method is being used and therefore the wrong type is being returned from  $input.select2('data').

For example, after initializing the DOM element with select2, I retrieve the selected item:

``` ts
var data = $input.select2('data');
```

The type `JQuery` is being returned instead of `any` which is expected.

The select2.d.ts source has the following:

``` ts
    select2(): JQuery;
    select2(it: IdTextPair): JQuery;
    select2(options: Select2Options): JQuery;
    select2(method: string): any;
    select2(method: string, value: any, trigger?: boolean): any;
    /**
    * Get the id value of the current selection
    */
    select2(method: 'val'): any;
    /**
    * Set the id value of the current selection
    * @params value Value to set the id to
    * @params triggerChange Should a change event be triggered
    */
    select2(method: 'val', value: any, triggerChange?: boolean): any;
    /**
    * Get the data object of the current selection
    */
    select2(method: 'data'): any;
```

Visual Studio is telling me that the select2 method being used is the following:

``` ts
select2(options: Select2Options): JQuery;
```

instead of the expected method:

``` ts
select2(method: 'data'): any;
```

Am I doing something wrong or is this a bug?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
