### ISSUE TITLE
@types/expressjs Wrong typescript definition?

### ISSUE THREAD

**Issue by ArdentZeal** [DefinitelyTyped/DefinitelyTyped#17764]
Hello everyone,

I have a problem with the expressjs typescript definition. I published a post on stackoverflow, maybe someone can help me out. 

https://stackoverflow.com/questions/44920881/expressjs-typescript-argument-of-type-typeof-express-router-is-not-assigna

Thanks in advance

**Comment by micksatana** [comment]
Hi @ArdentZeal,

If no longer the issue, kindly close it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
