### ISSUE TITLE
@types/iscroll/index.d.ts is not a module.

### ISSUE THREAD

**Issue by darek8686** [DefinitelyTyped/DefinitelyTyped#17766]
- [ ] I tried using the `@types/iscroll` package and had problems.

When I use import:

`import {IScroll} from '@types/iscroll';`

and error

> Module not found: Error: Can't resolve '@types/iscroll' in '..../web/src/app/commons/components/timeline/timeline-list'

> File '/home/darek/edok/udostepnianie.web-gui/web/node_modules/@types/iscroll/index.d.ts' is not a module.

When I add `export {IScroll};` at the end of index.d.ts it seems to work.

**Comment by dahuahe** [comment]
+1

**Comment by wildcors** [comment]
+1

**Comment by IureaCosmin** [comment]
+1

**Comment by giordanocardillo** [comment]
+1

**Comment by Chris-Slade** [comment]
+1

**Comment by xulch** [comment]
+1

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
