### ISSUE TITLE
@types/pdfjs-dist/index.d.ts - PDFViewer interface should be defined and PDFJSStatic.PDFViewer() should return a that instead of void

### ISSUE THREAD

**Issue by maxliu-ms** [DefinitelyTyped/DefinitelyTyped#17775]
- [ ] I tried using the `@types/pdfjs-dist` package and had problems.
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jbaldwin

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
