### ISSUE TITLE
@types/youtube width and height

### ISSUE THREAD

**Issue by ritox842** [DefinitelyTyped/DefinitelyTyped#17799]
Hello.

Can you please change the types of PlayerOptions.height and PlayerOptions.width to accept string also?
I'm using the player with height and width of 100% and I can't pass it as a number.

It's work's for me..

**Comment by tcigrand** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26448

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
