### ISSUE TITLE
Version 4.4 needed for tsx instead jsxFactory. Problems with widget support

### ISSUE THREAD

**Issue by Seikon** [DefinitelyTyped/DefinitelyTyped#17801]
Hi,

I had problems compiling widgets because jsxFactory is not now the render factory. Now we have to use tsx, but txs only is included in version 4.4. I see the latest update is 4.3.1, so we need the 4.4 version in order to use tsx.

Thank you.

**Comment by Seikon** [comment]
Updated!

Thank you.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
