### ISSUE TITLE
@types/three missing ShapeBufferGeometry & ExtrudeBufferGeometry

### ISSUE THREAD

**Issue by senften** [DefinitelyTyped/DefinitelyTyped#17819]
Using @types/three@0.84.15, three-core.d.ts is missing definitions for

ShapeBufferGeometry
ExtrudeBufferGeometry

**Comment by efokschaner** [comment]
Related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15871

@senften if you'd like to try adding them yourself I'll provide as much help + reviews as you need.

**Comment by senften** [comment]
Sorry for the delay in responding. 
I found a workaround for this particular issue in my code so I'm not hung up, but I'd certainly be happy and willing to help. It looks pretty straight forward as I look through some of the other typings

I'm unavailable next week so it will be another week before I can look into though.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
