### ISSUE TITLE
@types/react-responsive, does it support components and className?

### ISSUE THREAD

**Issue by jacktan165** [DefinitelyTyped/DefinitelyTyped#17866]
At the moment I want to add className to <MediaQuery /> but I can't because it does not have a type for that.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
