### ISSUE TITLE
@types/sockjs-client is not exporting interfaces

### ISSUE THREAD

**Issue by cedvdb** [DefinitelyTyped/DefinitelyTyped#17873]
At the moment the types informations in `sockjs-client` are unusable. Thus one has to use 

`import * as SockJS from 'sockjs-client'`

but that doesn't give any type information.

 The interfaces are not exposed with the standard `import { Interface } from '..';`

I tried to update it myself but failed to do so.

 [Similar request](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11042)

**Comment by BendingBender** [comment]
This is fixed now via #18157.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
