### ISSUE TITLE
GridStore missing from @types/mongodb

### ISSUE THREAD

**Issue by RiverAge** [DefinitelyTyped/DefinitelyTyped#17883]
Hello every one!

I referenced mongodb but found the GridStore is not defined in this module!Is it missing from the type definitions for MongoDB?

- [mongodb types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongodb/index.d.ts)
- [mongodb driver source tree](https://github.com/mongodb/node-mongodb-native/blob/2.2/index.js)
- [mongodb driver document](http://mongodb.github.io/node-mongodb-native/2.1/api/GridStore.html)

Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
