### ISSUE TITLE
javascript-state-machine - Cannot call constructor.

### ISSUE THREAD

**Issue by spacejack** [DefinitelyTyped/DefinitelyTyped#17890]
- [x] I tried using the `@types/javascript-state-machine` package and had problems.

@borisyankov

As per the example on the [javascript-state-machine readme](https://github.com/jakesgordon/javascript-state-machine):

```typescript
import * as StateMachine from 'javascript-state-machine'
const sm = new StateMachine({
	init: 'solid',
	transitions: [
		{name: 'melt', from: 'solid',  to: 'liquid'},
		{name: 'freeze', from: 'liquid', to: 'solid'}
	],
	methods: {
		onMelt: function() {console.log('I melted')},
		onFreeze: function() {console.log('I froze')}
	}
})
```

Results in error: `Cannot use 'new' with an expression whose type lacks a call or construct signature.`

**Comment by sundeer** [comment]
Same here. These definitions were written for v2.4. JSM is now v3. 

[https://github.com/jakesgordon/javascript-state-machine/blob/master/docs/upgrading-from-v2.md#construction](url)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
