### ISSUE TITLE
@types/countdown toString Unrecognised

### ISSUE THREAD

**Issue by ChrisTalman** [DefinitelyTyped/DefinitelyTyped#17903]
There seems to be an issue with `@types/countdown`. I receive the following error from TypeScript.

```
ERROR in ./src/modules/Initialise.ts
(85,64): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type '((radix?: number) => string) | ((label?: string) => string)' has no compatible call signatures.
```

The code which causes this error is as follows.

```
countdown(Date.now(), Date.now() + timeout).toString();
```

So far as I am aware, this is perfectly valid code, which works in the compiled JavaScript. However, TypeScript does not seem to understand it. Could there be a problem in the declaration file?

@gjuchault and @andy-ms seem to have been involved with this declaration file.

**Comment by andy-ms** [comment]
Looks like Microsoft/TypeScript#7294.
`countdown` returns `TimeSpan | number`, which have different signatures for `toString()`. The call here should be compatible with either, but TS can't figure that out.
However, the [docs](http://countdownjs.org/readme.html) say `The return value is a Timespan object` and don't mention returning a `number`, so maybe the type definition is wrong?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
