### ISSUE TITLE
@types d3-sankey

### ISSUE THREAD

**Issue by tboehnisch** [DefinitelyTyped/DefinitelyTyped#17927]
I tried using the `@types/d3-sankey` package in ionic and had problems.

I get errors on:

var sankey = d3Sankey.sankey()
.nodeWidth(20)
.nodePadding(40)
.size([width, height])

Im not sure if its a typing problem, but i cant use d3-sankey the way before. Can you provide a small example on how to use the typings properly?

**Comment by tomwanzek** [comment]
@tboehnisch I just came across this issue in routine maintenance. Please @-mention the definitions authors when filing an issue on DefinitelyTyped. In the present case: myself. Otherwise, they easily fall through the cracks.

That being said: If this is still an open issue from your side, please provide some more detail, i. p. the TypeScript error message(s). If you obtained clarification, e.g. on StackOverflow, please simply close this issue.

Thanks.

**Comment by tomwanzek** [comment]
@tboehnisch can this issue be closed?

**Comment by tomwanzek** [comment]
@andy-ms could you please close this issue due to lack of activity? Thx.

@tboehnisch should you still have a question related to the use of the d3-sankey definitions, you could try StackOverflow. If you believe, there is an actual issue with the way the definitions are written, please do not hesitate to ask for this issue to be re-opened with additional detail. Thanks for understanding.
