### ISSUE TITLE
@types/react -- Missing animationDuration on CSSProperties

### ISSUE THREAD

**Issue by Olian04** [DefinitelyTyped/DefinitelyTyped#17939]
The `CSSProperties` interface is missing a definition for the css property `animation-duration`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
