### ISSUE TITLE
[react-measure] needs big overhaul for react-measure version 2.0

### ISSUE THREAD

**Issue by estaub** [DefinitelyTyped/DefinitelyTyped#17943]
@asvetliakov

Everything has changed!

**Comment by asvetliakov** [comment]
@estaub 
I'm totally lack of free time. Could you make a PR?

**Comment by estaub** [comment]
@asvetliakov Sorry, I'm not skilled at declarations, not clear on react-measure v2, and busy too!  Whoever does it should probably recruit @souporserious to review.  I doubt he has TS skills, but hopefully he can read along.

**Comment by souporserious** [comment]
Unfortunately I haven't worked with TS. Not opposed to trying to help when I get a chance though! :)

**Comment by estaub** [comment]
I've given up on v2, since I am not getting any resize events for some reason.  But I got quite a ways on re-doing the declaration file.  I'm unlikely to pursue it any farther for several months.  If anyone has use, see attached.
[react-measure.d.ts.txt](https://github.com/DefinitelyTyped/DefinitelyTyped/files/1149833/react-measure.d.ts.txt)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
