### ISSUE TITLE
Missing onClose property on component MaterialUI/AutoComplete

### ISSUE THREAD

**Issue by grzegorzlademan** [DefinitelyTyped/DefinitelyTyped#17941]
- [ OK ] I tried using the `@types/0.17.14` package and had problems the same refers to master
- [ OK] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

There is property 'onClose' missing on MaterialUI/AutoComplete.

Temporary solution: 
Manually add to your node_modules/@types/material-ui/index.d.ts
'onClose?: () => void;' 

@ngbrown

**Comment by Jack-Works** [comment]
@types/material-ui 0.18.0 still not fix this problem

**Comment by Jack-Works** [comment]
Temporary solution: Manually add this to your global.d.ts in your project root.
```ts

declare namespace __MaterialUI {

	export interface AutoCompleteProps<DataItem> extends TextFieldProps {
		onClose?(): void;
	}
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
