### ISSUE TITLE
[node] Missing keepAliveTimeout in Server interface

### ISSUE THREAD

**Issue by lxwbr** [DefinitelyTyped/DefinitelyTyped#17957]
Authors: @parambirs @RobDesideri @tellnes @WilcoBakker @octo-sniffle @smac89 @Flarna

nodejs v8.0.0 added a keepAliveTimeout to the Server according to [docs](https://nodejs.org/api/http.html#http_server_keepalivetimeout). Current definitions seem not to reflect this change.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
