### ISSUE TITLE
@types/exceljs missing read method

### ISSUE THREAD

**Issue by spacem** [DefinitelyTyped/DefinitelyTyped#17969]
- [x] I tried using the `@types/exceljs` package and had problems.
  - Authors: @rogierschouten 

It is missing read method that takes a stream.
Something like this:
interface Excel.Xlsx {
  ...
  read(stream: Stream.Readable): Promise<void>;
}

Can see in this file
https://github.com/guyonroche/exceljs/blob/48ac18ecf4260ee4857df9cd9e33daf108ce029f/lib/xlsx/xlsx.js

I am quite new to typescript. Not sure if I should be cloning and just submitting a PR for this?

**Comment by rogierschouten** [comment]
@spacem yes a PR would be the thing to do. You can just add what you need, just like I added what I needed.

**Comment by rogierschouten** [comment]
Well, @Diluka as mentioned above feel free to write a PR

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
