### ISSUE TITLE
React-redux: React.ComponentClass, "but cannot be named"

### ISSUE THREAD

**Issue by atrauzzi** [DefinitelyTyped/DefinitelyTyped#17975]
Using the current typings for `react-redux`, I'm getting this error:

```
severity: 'Error'
message: 'Exported variable 'WrappedComponent' has or is using name 'React.ComponentClass' from external module ".../node_modules/@types/react-redux/node_modules/@types/react/index" but cannot be named.'
```

If I do this in the file:

```
import { ComponentClass } from "react-redux/node_modules/@types/react";
```

The error goes away.  Which is fairly odd and I'm not sure if I understand at that point why this would be okay or if it's just a bug in the typings.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
