### ISSUE TITLE
Mocha doesn't allow custom reporters

### ISSUE THREAD

**Issue by haswalt** [DefinitelyTyped/DefinitelyTyped#17984]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kazimanzurrashid  @otiai10 @jt000  @enlight 

First off the constructor options seem incorrect as reporter only allows string whereas mocha allows a string or function to be passed.

trying to pass a simple custom reporter to mocha in node also fails and can be easily replicated to show that the current definition doesn't match even the built in reporters:

```
let mocha = new Mocha();
mocha.reporter(Mocha.reporters.Spec);
```

```
Argument of type 'typeof Spec' is not assignable to parameter of type '(runner: IRunner, options: any) => any'
```

it also appears that the runner interface itself is incompatible with mocha custom reporter examples as it doesn't take into account methods inherited from EventEmitter

**Comment by JUhrig** [comment]
I ran into this issue as well, and found a less then optimal workaround.

```
let mocha = new Mocha();
mocha.reporter(function(runner, options){}); //Stop mocha from using default reporter
let runner = mocha.run(() => {});
let reporter  = new MochaTestRailReporter(runner, { reporterOptions: reporterOptions });
```

**Comment by AntSworD** [comment]
same issue，
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mocha/index.d.ts#L19
The comment said `function or string`, BUT，actually not

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
