### ISSUE TITLE
Type definitions for nw.js 0.25

### ISSUE THREAD

**Issue by futagoza** [DefinitelyTyped/DefinitelyTyped#18009]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

Can someone please update the type definitions to better support NW.js 025+
I'm currently working on a project that requires NW.js 0.25

If I can, I will try to make it myself in my spare time

**Comment by Connum** [comment]
Did anyone ever find any up-to-date type definitions for recent versions of NW.js?

**Comment by sebamatusr** [comment]
Please add some nwjs typings!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
