### ISSUE TITLE
@types/parse missing some method & variables

### ISSUE THREAD

**Issue by ryanemax** [DefinitelyTyped/DefinitelyTyped#18010]
- [x ] I tried using the `@types/parse` package and had problems.

# class Promise<T> implements IPromise<T>
- missing **catch<U>();**

# interface IBaseObject & class BaseObject implements IBaseObject
- missing **toPointer(): any;**

**Comment by artemsvirskyi** [comment]
also Parse.CoreManager

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
