### ISSUE TITLE
@types/webpack-env - TS2339:Property 'catch' does not exist on type 'void'

### ISSUE THREAD

**Issue by FDiskas** [DefinitelyTyped/DefinitelyTyped#18014]
- [x] I tried using the `@types/webpack-env@1.13.0` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] Authors: @mhegazy @use-strict 

wrong last argument, there could be an function to
see test case https://github.com/webpack/webpack/blob/master/test/cases/chunks/var-inject-error-handler/index.js
even more - it returns a promise https://github.com/webpack/webpack/blob/master/lib/JsonpMainTemplatePlugin.js#L109

and it should be posible to write code as
```js
require.ensure([], require => require('')).catch(error => alert(error));
```
or
```js
require.ensure([], require => require(''), error => alert(error));
```

**Comment by use-strict** [comment]
Definitions changed significantly since I last saw them, but shouldn't this line take care of the callback function? https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webpack-env/index.d.ts#L31

I'm unsure about changing the signature to return a promise. It would then compile only with lib es6. Maybe someone else can help here with input.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
