### ISSUE TITLE
[@types/braintree-web] Add checkoutPaypal (added in 3.7.0)

### ISSUE THREAD

**Issue by MrBlaise** [DefinitelyTyped/DefinitelyTyped#18028]
Since the 3.7.0 version of the braintree js SDK it uses the [PayPal Checkout component](http://braintree.github.io/braintree-web/current/module-braintree-web_paypal-checkout.html),
The current version of this typing does not support this feature, can this be added?
  - Authors: @Maistho, @sandersn @chlela

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
