### ISSUE TITLE
Add definition for mapbox-gl-geocoder

### ISSUE THREAD

**Issue by use-strict** [DefinitelyTyped/DefinitelyTyped#18062]
I already created a definition for the `mapbox-gl-geocoder` plugin here: https://gist.github.com/use-strict/b7363cf9ffbfd0f65582f708d4c22e67

Unfortunately I don't have the time to bring it to the point where it can be added to DefinitelyTyped and I'm hoping someone can take the time to help. Meanwhile, who needs it can do so from the provided gist.

TODO:
- [ ] Proper exports and namespacing (as npm and script tag method)
- [ ] Header and metadata (I tested it with mapbox-gl-js v0.38 and mapbox-gl-geocoder v.2.1.0)
- [ ] Tests

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
