### ISSUE TITLE
Takes 20 hours to publish to npm @types from merged

### ISSUE THREAD

**Issue by teppeis** [DefinitelyTyped/DefinitelyTyped#18067]
After #17129 was merged, updated packages are not published to npm at-types.

- [The CI job](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/253300526) was failed
- https://www.npmjs.com/package/@types/nouislider is not updated
- [commits](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master?after=c113d3ad62a3d4535b7493fccfc3c020c8d79487+69): After this merge, no packages are published.

**Comment by teppeis** [comment]
[nouislider](https://www.npmjs.com/package/@types/nouislider) has been published, but it took 20 hours to publish. Following packages are delayed too. It needs to be improved.

> The master branch is automatically published to the @types scope on NPM thanks to types-publisher. This usually happens ***within an hour*** of changes being merged.
> https://github.com/DefinitelyTyped/DefinitelyTyped#what-exactly-is-the-relationship-between-this-repository-and-the-types-packages-on-npm

**Comment by teppeis** [comment]
It seems to publish on a daily basis?
If so, README should be updated.

**Comment by saeedtabrizi** [comment]
Same problem with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18218 merge .
It takes over 20 hours and don't publish yet . 
I guess there is a problem to publish packages . 

Thanks .

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
