### ISSUE TITLE
[@types/braintree-web] Make callbacks optional for async methods.

### ISSUE THREAD

**Issue by judowalker** [DefinitelyTyped/DefinitelyTyped#18088]
Methods like `braintree.client.create()` don't require a callback because it returns a Promise which can be used instead.

Authors: @Maistho, @sandersn @chlela

**Comment by potty** [comment]
https://braintree.github.io/braintree-web/current/module-braintree-web_paypal.html#.create

`braintree.paypal.create()` should return Promise when callback is omitted, but only variant with callback is supported now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
