### ISSUE TITLE
@types/inquirer `Question.validate` return signature incomplete

### ISSUE THREAD

**Issue by SimonSchick** [DefinitelyTyped/DefinitelyTyped#18105]
- [x] I tried using the `@types/inquirer` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkQubo, @ppathan

See https://github.com/SBoudrias/Inquirer.js#question (scroll down a little), docs says returning promises is OK, typings do not reflect that.

Correct signature would be:

```typescript
validate?(input: string, answers?: Answers): boolean | string | Promise<boolean | string>;
```

**Comment by jrockwood** [comment]
Same thing for `default`, `choices`, `validate`, `filter`, and `when`. They should all be able to return a Promise. This is from the documentation and I've verified that it's the case in the implementation.

Quoted from the docs at https://github.com/SBoudrias/Inquirer.js/#objects towards the bottom:

> default, choices(if defined as functions), validate, filter and when functions can be called asynchronously. Either return a promise or use this.async() to get a callback you'll call with the final value.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
