### ISSUE TITLE
@types/socket.io-client upgrade to latest version?

### ISSUE THREAD

**Issue by BorntraegerMarc** [DefinitelyTyped/DefinitelyTyped#18127]
- [X] I tried using the `@types/socket.io-client` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @progre @divillysausages @florentpoujol

Hi devs, I think you did an awesome job with the type definitions. But the definitions are for socket.io version 1.4.4. I just wanted to ask if you have any plans on update it to the latest socket.io version 2.X?

**Comment by olastor** [comment]
+1 Also need this

**Comment by divillysausages** [comment]
I don't have the time atm so you're free to crack away at it :)

**Comment by BorntraegerMarc** [comment]
@divillysausages I will do it but could you give me a starting point how to actually do the update?
For example: where do I define the version of Socket.IO that should be used for the typescript definition?

**Comment by divillysausages** [comment]
Should be in the tsd file itself (or the naming of the file) if I remember
right. It's been a while since I've looked at it. If you check out the
files you should be able to see, as I had to do this when I did the current
version

**Comment by muuvmuuv** [comment]
Any updates here? I would also like to have an exported `Socket` to use in TS Classes for reference.

**Comment by MickL** [comment]
`@types/socket.io-client` was last updated 4 years ago on version `1.4.32` but latest is `2.3.0` :(

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
