### ISSUE TITLE
[JQueryUI] missing 'attribute' property in Sortable toArray

### ISSUE THREAD

**Issue by fourmisz** [DefinitelyTyped/DefinitelyTyped#18128]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov  @johnnyreilly 

------

http://api.jqueryui.com/sortable/#method-toArray
In this documentation, there is an option `attritube` in Sortable `toArray`. So It should be

* current
```
sortable(methodName: 'toArray'): string[];
````

* should be
```
sortable(methodName: 'toArray', options?: { attribute?: string }): string[];
````

**Comment by shmax** [comment]
Fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22932. 

@borisyankov @johnnyreilly Please close.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
