### ISSUE TITLE
[@types/vast-client] Insufficient type declaration for VastAd.creatives

### ISSUE THREAD

**Issue by krail** [DefinitelyTyped/DefinitelyTyped#18138]
@jgainfort 

According to vast-client sources `VastAd.creatives` is always an [array](https://github.com/dailymotion/vast-client-js/blob/master/vast-client.js#L321). But current definition accepts only `VastCreativeLinear` or `VastCreativeCompanion[]`.

**Comment by jgainfort** [comment]
@ILYAKraynov Thanks for pointing that out.

I opened a PR. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18141

As I mentioned in the description Im not 100% on the best solution to use. Would you be able to provide your opinion?

**Comment by ILYAKraynov** [comment]
If i properly understood source code and spec-file `VastAd.creatives` is an array that could consist from one or more `creative`. Which in turn could be one of three type: `Linear`, `NonLinear` and `CompanionAds`.

There is no special order of those types. And no requirements that one type should be complemented with another. 

Reading specs i've found suggestion to provide `LinearAd` for `CompanionAds` becuase its common practice, but it is not strict rule.

In my opinion, definition should look like something this:

```
export interface VastAd {
...
creatives: (VastCreativeLinear | VastCreativeNonLinear | VastCreativeCompanion)[];
...
}

```
or maybe event better:

```
export interface VastCreative { }

export interface VastCreativeLinear extends VastCreative { }

export interface VastCreativeNonLinear extends VastCreative{ }

export interface VastCreativeCompanion extends VastCreative{ }

export interface VastAd {
  creatives: VastCreative[];
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
