### ISSUE TITLE
@types/hapi-auth-jwt2: key in Options should support string array

### ISSUE THREAD

**Issue by bsbates** [DefinitelyTyped/DefinitelyTyped#18135]
@warrenseymour 

In the options passed to hapi.auth.strategy, the `key` option should support an array of strings, in addition to a single string or key lookup. This is supported by library, and is useful when a server has multiple keys that can be used to a decode a JWT.

**Comment by AJamesPhillips** [comment]
Also the docs say key is required by in the types it's optional?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi-auth-jwt2/index.d.ts#L43

https://github.com/dwyl/hapi-auth-jwt2

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
