### ISSUE TITLE
ng-grid IGridOptions potential bugfix

### ISSUE THREAD

**Issue by Myrmex** [DefinitelyTyped/DefinitelyTyped#1817]
Hello, I found what seems to be a bug in ng-grid definitions for IGridOptions: the data member is defined as an array of any type (data?: any[]), but if I assign to this member my $scope data array nothing is displayed when data are populated. Instead, if you make this member a string and set it to the $scope data array name, as per ng-grid JS examples, it seems to work. So I changed ng-grid.d.ts at line 40 to data?: string; and I got it working. If this is correct, it would be nice to get this fix into the next releases.
Thank you!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
