### ISSUE TITLE
@types/react -- got `Property 'value' does not exist` on <data> element

### ISSUE THREAD

**Issue by untsamphan** [DefinitelyTyped/DefinitelyTyped#18171]
version: typescript 2.4.1, types/react 15.0.38

When using <data value=xxx> like:

```typescript
import * as React from 'react';
export default function App() {
  return (
    <div>
      <data>ok</data>
      <data value='bad'>not ok</data>
    </div>
  );
}
```
It used to work but now I've got this error:
```
Type '{ value: "bad"; children: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
  Property 'value' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
```

@johnnyreilly

**Comment by dhavalshah01** [comment]
Were you able to resolve this issue ? I am facing the simmilar issue while using the inline style in react component.

export default class Reactdemo extends React.Component<IReactdemoProps, {}> {
  public render(): React.ReactElement<IReactdemoProps> {
    const inlineStyles = {

      news: {
        'overflow': 'hidden',
        'padding': '3px',
        '-webkit-user-select': 'none',
        'box-shadow': 'inset 0 - 15px 30px rgba(0, 0, 0, 0.4), 0 5px 10px rgba(0, 0, 0, 0.5)'
      }

    };
    return (
      <div className={styles.reactdemo} style={inlineStyles.news}> 
        <div className={styles.container}>

        </div>
      </div>
    );
  }
}

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
