### ISSUE TITLE
lodash.d.ts intellisense is not working 

### ISSUE THREAD

**Issue by VladimirMakaev** [DefinitelyTyped/DefinitelyTyped#1818]
I have Resharper 8.1 installed it's probably causing the issue. However if I rename "declare module _" to "declare module LodashModule" and fix compilation errors intellisense appears. Can you please rename the module declaration just be safer with all the users out there using Resharper?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
