### ISSUE TITLE
@types/node broke typescript intellisense in vscode

### ISSUE THREAD

**Issue by jerryeechan** [DefinitelyTyped/DefinitelyTyped#18183]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the `@types/JQuery` package and had problems.
authors: @parambirs @tellnes @WilcoBakker @nicolas-voigt @smac89 @Flarna @mwiktorczyk 
@RobDesideri 

These two packages make the typescript intellisense broken of type suggestion, I think this is a serious issue

normal would be:
<img width="750" alt="normal" src="https://user-images.githubusercontent.com/7359898/28333688-4581effa-6c2b-11e7-8b52-583fe85dc2ff.png">

Problem occurs with `@types/node` or `@types/JQuery` installed
<img width="752" alt="broken" src="https://user-images.githubusercontent.com/7359898/28333695-4a467c90-6c2b-11e7-8ec4-d0d11b7a2172.png">

I have filtered out that 
`
declare module "console" {
    export = console;
}
`
and
`
declare module "process" {
   export = process;
 }
`
in index.d.ts of `@types/node` cause the problem

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
