### ISSUE TITLE
user typescript  and code add addLocaleData([{ locale: 'zh_CN', parentLocale: 'zh-Hans'} ]);    but  interface Locale not have  property parentLocale。  compile error  Type '{ locale: string; parentLocale: string; }' is not assignable to type 'Locale'.       Object literal may only specify known properties, and 'parentLocale' does not exist in type 'Locale'.

### ISSUE THREAD

**Issue by zhoulijunFE** [DefinitelyTyped/DefinitelyTyped#18198]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

**Comment by andy-ms** [comment]
What `@types` package is this for?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
