### ISSUE TITLE
@types/enzyme - setProps is missing optional callback argument

### ISSUE THREAD

**Issue by thovden** [DefinitelyTyped/DefinitelyTyped#18214]
Missing argument in type definition. Will add and send pull request. 

- [x] I tried using the `@types/enzyme` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

**Comment by tkrotoff** [comment]
@thovden you can close this issue, thx

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
