### ISSUE TITLE
Webspeech api AOT compatibility

### ISSUE THREAD

**Issue by sarath-sasikumar** [DefinitelyTyped/DefinitelyTyped#18239]
I tried using the `@types/webspeechapi` package and had problems.

When the ngc command was run with the project the issues came up as shown in the image.The issues are specific to the library.

![image](https://user-images.githubusercontent.com/20787375/28404668-eafa002c-6d47-11e7-9de1-215221a200c7.png)

**Comment by Fdom92** [comment]
I'm trying to use the same types and i'm getting the same error, there is some workaround or plans to fix this??

Wanted to use this API :(

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
