### ISSUE TITLE
Too late to publish npm package automatically ,(Over the 1 hour against the documentation).

### ISSUE THREAD

**Issue by saeedtabrizi** [DefinitelyTyped/DefinitelyTyped#18255]
Hi experts.
I have an update for **orientjs** definition type in yesterday for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18218 merge pull request. 
According to documentation i expected to have  new published package in **npm** repository when code merged to master branch without any error.
The current orientjs package npm address is [orientjs definition type npm package](https://www.npmjs.com/package/@types/orientjs) .
But there is no update publishing package for orientjs yet . 
I also see  https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18067 issue ,it's very similar to my problem that i reported here .

Is there any idea ?
Thanks 
Saeed Tabrizi

**Comment by saeedtabrizi** [comment]
I guess the documentation must be update for npm publish timing .
The orientjs new package just published now . 
So i close this issue .

**Comment by sfrooster** [comment]
There's not a way to run it manually? What's the official word here? We are at 20 hours since a merge to master on kafka-node and still waiting...

**Comment by willisplummer** [comment]
i had a similar issue after merging changes for the `draft-js` package

**Comment by sfrooster** [comment]
It took closer to 48 hours...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
