### ISSUE TITLE
@types/loopback observe seems to be missing

### ISSUE THREAD

**Issue by terehov** [DefinitelyTyped/DefinitelyTyped#18250]
- [x] I tried using the `@types/loopback` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

export function user(MODEL: User) {
  MODEL.observe('access', (ctx: any, next: Function) => {...}
}

Is there another way or any other reason, why "observe" is missing in the definitions? Am I missing something or doing it wrong? 

Thank you!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
