### ISSUE TITLE
three.js clock seconds or milliseconds

### ISSUE THREAD

**Issue by roy192** [DefinitelyTyped/DefinitelyTyped#1828]
The elapsedTime property, getElapsedTime function, and getDelta function of the Clock class return the time in seconds. The comments above these mention milliseconds instead of seconds.

You can see this clearly in the getDelta function, the difference is multiplied by 0.001 (divided by 1000).

Also, the comment above elapsedTime mentions that it's counted from 1 January 1970 00:00:00 UTC. This doesn't make sense, it's counted from the when the clock is started (as stated in the line above).

oldTime, and startTime return in milliseconds (so that's correct).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
