### ISSUE TITLE
@types/i18next@8.4.1 breaks in TypeScript 2.2

### ISSUE THREAD

**Issue by sam-piper** [DefinitelyTyped/DefinitelyTyped#18342]
I upgraded from 8.4.0 to 8.4.1 and it broke our build because we are using TypeScript 2.2.2, and the new index.d.ts file does not compile.

This package update should not be a patch if the underlying version of TypeScript has changed as well, because it is clearly not backwards compatible. The package authors cannot assume that everyone will be migrating to newer versions of TypeScript as they become available.

For now I will stay with 8.4.0.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
