### ISSUE TITLE
@types/diff has no default export

### ISSUE THREAD

**Issue by antoine-pous** [DefinitelyTyped/DefinitelyTyped#18351]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- Authors: @vvakame 

Currently this types is not up to date, the latest version of diff is `3.3.0` and i can't use the library due to this error : `"node_modules/@types/diff/index" has no default export`

**Comment by andy-ms** [comment]
Based on `node -p 'require("diff")'`, it looks like this module does not have a `default` export. See the [README](https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
