### ISSUE TITLE
[@types/sequelize] Miss `$or` in type `WhereLogic`

### ISSUE THREAD

**Issue by hronro** [DefinitelyTyped/DefinitelyTyped#18387]
I want to get multi objects in one query, so I want to use `$or` operator in sequelize, but there is no `$or` in the type `WhereLogic`. Or is there any other way to achieve that ?

**Comment by lukiano** [comment]
any news?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
