### ISSUE TITLE
about @types/highlightjs

### ISSUE THREAD

**Issue by printjs** [DefinitelyTyped/DefinitelyTyped#18397]
- [x] I tried using the `@types/highlightjs` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

Why don't you have this library file?

**Comment by andy-ms** [comment]
Because no one submitted it yet?
We do have types for `highlight.js` if that's what you meant.

**Comment by andy-ms** [comment]
Both `highlightjs` and `highlight.js` were last published about a year ago, and the website https://highlightjs.org/ doesn't mention any recommended `npm install`, so I'm not sure.

**Comment by m93a** [comment]
I've searched their web and the download page https://highlightjs.org/download/ acually does state:

> Highlight.js can be used on the server through the API. The package with all supported languages is installable from NPM:
>
> `npm install highlight.js`
>
> Alternatively, you can build it from the source:
>
> `node tools/build.js -t node`

That means that the DefinitelyTyped repository has got it right 👍

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
