### ISSUE TITLE
DT bot not updating the checklist when Travis CI finishes successfully

### ISSUE THREAD

**Issue by isiahmeadows** [DefinitelyTyped/DefinitelyTyped#18460]
Here's an [example offending comment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18458#issuecomment-318522957), where the "pass the Travis CI test?" box isn't checked after the test finishes.

**Comment by leonard-thieu** [comment]
Maybe @dt-bot shouldn't mention `pass the Travis CI test?` at all given that GitHub already shows the build status. @vvakame, what do you think?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
