### ISSUE TITLE
lodash type inference problems from where arguments

### ISSUE THREAD

**Issue by gregwebs** [DefinitelyTyped/DefinitelyTyped#1847]
see https://github.com/borisyankov/DefinitelyTyped/commit/bb9cf5d3c326267c01c1c83dc14dd9d8b35e9ee7#commitcomment-5686378

That commit needs to get reverted. I am on an older version of typescript, after backing out that commit the type inference works properly again. Apparently there is a problem in 0.9.7, we should try removing the commit from the repo when 1.0 is released.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
