### ISSUE TITLE
Types for electron-devtools-installer need updating for version 2.2.0

### ISSUE THREAD

**Issue by dawnmist** [DefinitelyTyped/DefinitelyTyped#18489]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @GamesMaxed 

The default exported function in electron-devtools-installer has been updated to also take an Array<string | ExtensionReference> objects as the extensionReference input, and if it receives an array as the input it will return an Array< string > as the promise result.
  i.e. inputs: string | ExtensionReference | Array<string | ExtensionReference>
    outputs: string if input was single, Array< string > if input was an array.

There is also a new/added ExtensionReference type "CYCLEJS_DEVTOOL".

**Comment by GamesMaxed** [comment]
I'm kinda bussy at the moment but I will take a look this weekend.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
