### ISSUE TITLE
Two minor issues with rethinkdb types

### ISSUE THREAD

**Issue by viridia** [DefinitelyTyped/DefinitelyTyped#18491]
1) I believe the return type from get() is incorrect. According to the type definitions, it returns a sequence / cursor, but the actual RethinkDB driver returns a single (nullable) object.

2) It would be helpful if Cursor were generically typed. Right now there's a generic type parameter for the individual accessors but not the class as a whole. This makes it difficult to infer the row type when passing cursors to functions.

For example, I have a 'maybe' function that operates similarly to get() - it fetches a single object, but allows multiple query params rather than just an id. It accepts a promise returning a cursor and returns a promise returning a single nullable object. So I can say:

    t.table('foo').filter({ params... }).run(conn).then(maybe).then(row => { ...do something with row... };

However, because cursor doesn't have a type parameter, the 'row' parameter has to be explicitly typed rather than inferred.

@alexgorbatchev

**Comment by viridia** [comment]
I just found another one: In RethinkDB, primary keys do not have to be strings.

**Comment by viridia** [comment]
Are these type definitions still maintained?

**Comment by Maxr1998** [comment]
1. seems to have been fixed in #20521.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
