### ISSUE TITLE
incorrect type definition @types/soap

### ISSUE THREAD

**Issue by onury** [DefinitelyTyped/DefinitelyTyped#18497]
- [x] I tried using the `@types/soap` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aleung, @cagefox

`Client` and `Server` should be declared as classes instead of interfaces. This prevents developers from extending these classes (which are [originally exported to allow customization](https://github.com/vpulim/node-soap/blob/master/lib/soap.js#L91)).

**Comment by onury** [comment]
Another thing..
`[method: string]: SoapMethod | Function;` is added for service/wsdl methods but it should be `[key: string]: any;` otherwise TS will complain on any member you add to the extended class if it doesn't have a type of `SoapMethod | Function`.

**Comment by onury** [comment]
Also `soap.WSDL` is missing.

**Comment by aleung** [comment]
I had only add definitions for my need. PR is welcome.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
