### ISSUE TITLE
Log4js configure method has new properties

### ISSUE THREAD

**Issue by carlosflorencio** [DefinitelyTyped/DefinitelyTyped#18492]
- [X] I tried using the `@types/log4js` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @armorik83

The `configure` method has a new properties (categories for example):

```javascript
log4js.configure({
  appenders: { 'out': { type: 'stdout', layout: { type: 'basic' } } },
  categories: { default: { appenders: ['out'], level: 'info' } }
})
```
[Documentation](https://nomiddlename.github.io/log4js-node/layouts.html)

Code that cause an error:
```
import * as log4js from 'log4js'

log4js.configure({
  appenders: { out: { type: 'stdout', layout: { type: 'coloured' } } },
  categories: { default: { appenders: ['out'], level: 'info' } }
})
```

IConfig is outdated, the error:
```
Argument of type '{ appenders: { out: { type: string; layout: { type: string; }; }; }; categories: { default: { app...' is not assignable to parameter of type 'IConfig'
```

Hope you can update it, Thanks 😄

**Comment by iamfreee** [comment]
Maybe you can add the `level` property to the `Logger` interface
`logger.level = 'debug';` 

The method `logger.setLevel('info')` is giving an error too:
`setLevel is not a function`

**Comment by aasailan** [comment]
I modify the define file:
`export interface IConfig {
  appenders: { [propName: string]: AppenderConfig }; // 原来的是 AppenderConfig[]，但是与最新的log4js API不相符
  levels?: { [category: string]: string };
  replaceConsole?: boolean;
}`
and it is work

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
