### ISSUE TITLE
NumJs typing bugs

### ISSUE THREAD

**Issue by huan** [DefinitelyTyped/DefinitelyTyped#18508]
- [x] I tried using the `@types/numjs` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @taoqf @andy-ms

Recently we released the numjs typing definition which is awesome. (#18343)

After I used it in my [ML project](https://github.com/zixia/facenet), I found serial bugs, list as the following(will be updated):
1. `nj.images.read(input: string): NdArray<Uint32Array>;` should be `Uint8Array`, according to <https://github.com/nicolaspanel/numjs/blob/master/src/images/read.js#L17>
1. `nj.tolist(): T[];` seems will cause problems, because most of the time, the return type will not be T[].
1. `nj.array<T = number>(arr: NjArray<T>, dtype?: BaseNdArray.DataType): NdArray<T>;` seems will cause problems too, because we can construct the nj.array by `number[]`, `number[][]`, even `number[][][]`, the `nj.array` should always have `T=number`.

To be updated...

**Comment by taoqf** [comment]
> nj.tolist(): T[]; seems will cause problems, because most of the time, the return type will not be T[].

Then What time will be the return type? actually i do not use this module much, it will be so kind if you could tell me the return types so i can fix this.

> nj.array<T = number>(arr: NjArray<T>, dtype?: BaseNdArray.DataType): NdArray<T>; seems will cause problems too, because we can construct the nj.array by number[], number[][], even number[][][], the nj.array should always have T=number.

You may like use nj.array like this:
```ts
const my_array = nj.array<number[]>([[2], [3, 4]]);
```
Good luck.

**Comment by zixia** [comment]
Thanks for the quick fix!

My problem is that the `tolist(): T[]` and `nj.arrahy<T>` looks tricky for me, because I'm using the array with strange shape like:

```ts
const a = nj.array([0, [1, 2], [2, 3], [[4, [5, 6]]], 4])
console.log(a.shape) // Output: [ 5 ]

const l = a.tolist()
console.log(l[1][1]) // TSError: Element implicitly has an 'any' type because type 'number | number[] | (number | number[])[][]' has no index signature. (7017)
```

I think maybe I should not use the nj.array with un-fixed shape because in numpy it seems always with fixed rows/cols?

**Comment by taoqf** [comment]
will `a.tolist<number[]>();` work for you?

**Comment by zixia** [comment]
Yes, absolutely.

Actually, this is the solution I'm using now.

What I'm confusing is that whether there has a Typing Setting will do it automatically because the Type is not _static_ in numjs.

**Comment by zixia** [comment]
Another bug: 

`function resize(img: NdArray<Uint32Array>, height: number, width: number): NdArray<Uint32Array>;`

should be `NdArray<Uint8Array>`

**Comment by zixia** [comment]
Currently, we are leaked of `selection` property for NdArray, so I have to use `any` like this: `const data = (ndarray as any).selection.data as Uint8Array`.

According to the suggestion of author of numjs:
 <https://github.com/nicolaspanel/numjs/issues/21#issuecomment-319301957>
  and the code here: <https://github.com/nicolaspanel/numjs/blob/master/src/ndarray.js#L24>, we should add the `selection` so that we can access the buffer directly.

Data structer illustrated as the follow code & log:

```ts
// ndarray: nj.NdArray<uint8>
console.log(ndarray.selection)
```

```shell
View1duint8 {
  data: Uint8Array [ 1, 2, 3 ],
  shape: [ 3 ],
  stride: [ 1 ],
  offset: 0 }
```

**Comment by zixia** [comment]
We should export NdArray, so I can use `nj.NdArray` instead of `(nj as any).NdArray`, like the following code usage:

```ts
const b = Buffer.from(base64Text, 'base64')
const t = new Uint8ClampedArray(b)
const a = new (nj as any).NdArray(t, [512, 512, 3])
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
