### ISSUE TITLE
[keycloak-js] Update type definitions to v3.2

### ISSUE THREAD

**Issue by lmuntaner** [DefinitelyTyped/DefinitelyTyped#18518]
*/types/keycloak-js/index.d.ts*

Current types are for version 2.5
Keycloak recently released the version 3.2

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
