### ISSUE TITLE
Wrong typedefinition of Popover props title

### ISSUE THREAD

**Issue by TobiasWollmann** [DefinitelyTyped/DefinitelyTyped#18570]
Hi,

it seems to me like the type definition of title in the PopoverProps is wrong. Because they inherit from React.HTMLProps<Popover> the title attribute is required to be of type string. But you can add any JSX or HTML element to it which is than simply rendered in the header. 
Can you fix this please. Is there a local workaround i can use to make this transpile already (like extending the type and overwriting its type definition with e.g. any).

Regards,
Tobias

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
