### ISSUE TITLE
@types/meteor Match.Maybe missing

### ISSUE THREAD

**Issue by jthomaschewski** [DefinitelyTyped/DefinitelyTyped#18585]
With the upgrade of `@types/meteor` from `1.4.2` to `1.4.3` `Match.Maybe` was removed. `Match` is defined as part of `meteor/check`.

Previous definition in `index.d.ts`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c27c678fa5d0ad5035390a5f574bc0b2415078ea/types/meteor/index.d.ts#L2109

Current definition in `check.d.ts`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/82d1e3894394302bf9c5f61b963585fdcde061fe/types/meteor/check.d.ts#L32

Upstream documentation of `Match`: https://docs.meteor.com/api/check.html#matchpatterns

In the meantime downgrading to `@types/meteor@1.4.2` helps

@ardatan @andy-ms

**Comment by andy-ms** [comment]
Pull requests accepted.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
