### ISSUE TITLE
React props default to {} causes ts errors for javascript users

### ISSUE THREAD

**Issue by neekibo** [DefinitelyTyped/DefinitelyTyped#18606]
**TypeScript Version:**  2.4.0 
**VSCode Version:** 1.14.2

I am using TS to check my Javascript-React-JSX-files (.jsx). 
**Code**

```js
import React from 'react'

class MyComponent extends React.Component {

  render() {
    return this.props.simpleProp
  }
}
```

**Expected behavior:**
As stated [here](https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files#unspecified-type-parameters-default-to-any) TS compiler should default to `any` for unspecified generic type parameter.  The problem for me is [this commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b0c9072f430eb3304fb79011a36b522d54c2be9c). Now React props are specified as `{}` and therefore the compiler gives me an error:
> [js] Property 'simpleProp' does not exist on type 'Readonly<{ children?: ReactNode; }> & Readonly<{}>'.

Is there any way to prevent this without specifying all props via `@augments` comment?

I first opened an issue on Typescript repo: [Issue](https://github.com/Microsoft/TypeScript/issues/17524)

Thanks

**Comment by neekibo** [comment]
Just a local workaround: I basically reverted the mentioned commit: In my index.d.ts I replaced all <P = {}, ...> with <P, ...>

**Comment by psachs21** [comment]
Another workaround is to specify your own React class (in typescript) that all your components extend. Also not ideal but it'll work for now with a relatively easily exit path with a codemod.

```ts
// baseComponent.tsx
import React, { Component } from 'react';

export default class BaseComponent<P = any, S = any> extends Component<P,S> {
}
```

**Comment by gagarski** [comment]
The other side of the problem is that you cannot write
```tsx
return <MyComponent simpleProp={42}/>
```
in Typescript

**Comment by tkrotoff** [comment]
> Is there any way to prevent this without specifying all props via @augments comment?

What is the problem with using `@augments React.Component<any, any>`?

**Comment by jacobrask** [comment]
> What is the problem with using @augments React.Component<any, any>?

JavaScript interoperability is a key selling point of TypeScript, if you need to modify every React component in your application that point is not so strong anymore.

**Comment by tkrotoff** [comment]
> you need to modify every React component

Ok so there is nothing "broken". You can add `@ts-ignore` or `@augments`: it's shitty and boring but it works, right?

> JavaScript interoperability is a key selling point of TypeScript

I agree. But I see something even more important than JS interoperability (introduced in v2.3, April 2017): TypeScript syntax itself.

It's a tradeoff: do you favor a nice .ts syntax or a nice .js interoperability syntax when you can't have both? (Question does not only apply to React.Component: this will happen again in the future).

What could be a nice solution is to be able to override [some definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/954357f829e5597757c060e9f8ae630912e3f000/types/react/index.d.ts#L274) behavior specifically for JS interop, something like:
```TypeScript
// File react/index.d.ts

// ====> @augments Component<any, any> <====
interface Component<P = {}, S = {}> extends ComponentLifecycle<P, S> { }
```
What do you think?

Anyway, I'm a no-one here: I'm just the author of #17288 because I believe it's a nice syntax addition.

**Comment by gagarski** [comment]
> What could be a nice solution is to be able to override some definitions behavior specifically for JS interop, something like:

... or just to not rely on default generic parameters when dealing with JS :smiley: (unfortunately TS developers do not agree with that)

**Comment by jacobrask** [comment]
@tkrotoff Importing JavaScript modules has been supported for a long time, and this bug affects that as well, not just JavaScript files with `@ts-check`.

Since you authored #17288, do you think it would work to replace {} as default params with any? Before that change I could happily include any JavaScript React component in my TypeScript project. Now I have to teach everyone in the team that if you get this particular error it might be because the imported file is JavaScript and you need to do this and that workaround.

**Comment by tkrotoff** [comment]
> replace {} as default params with any

Do you mean a PR that modifies `react/index.d.ts` and replaces `{}` with `any`? Obviously not a chance this could be accepted (not talking about me).

**Comment by alecmerdler** [comment]
@tkrotoff I can't seem to get `@augments {React.Component<any, any>}` to fix this error, do you mind taking a quick look to see what I am doing wrong? 
Here is a sample repo: https://github.com/alecmerdler/tsx-jsx

**Comment by tkrotoff** [comment]
@alecmerdler not the right person to ask: I've never used .js interop

**Comment by tkrotoff** [comment]
@alecmerdler try with TypeScript 2.5+ because of this: https://github.com/Microsoft/TypeScript/issues/17157

**Comment by alecmerdler** [comment]
I've updated my [test repository](https://github.com/alecmerdler/tsx-jsx) to use TypeScript v2.5.1. Running `tsc` compiles without errors, but using `webpack` with a JSX entry file and `--entryFileIsJs` ts-loader option causes issues. Seems to be a problem with ts-loader.

**Comment by rosdi** [comment]
TypeScript 2.8.1 here, the only workaround that works is this: https://github.com/Microsoft/TypeScript/issues/14558#issuecomment-343722800
