### ISSUE TITLE
@types/node: incorrect signature for EventEmitter.listeners

### ISSUE THREAD

**Issue by andreasvoigt** [DefinitelyTyped/DefinitelyTyped#18625]
- [x] I tried using the `@types/node@8.0.19` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] Mention the authors (see Definitions by: in index.d.ts) so they can respond.
Authors: @parambirs @RobDesideri @tellnes @WilcoBakker @octo-sniffle @smac89 @Flarna @mwiktorczyk @wwwy3y3 @Tyriar @DeividasBakanas 

Let's say, I have an EventEmitter `let emitter: NodeJS.EventEmitter`.
It has a public property `emitter.listeners("eventName")` which is of type `Function[]`.

Now I want to take one of the listeners in the list and directly call removeListener:
`emitter.removeListener("eventName", emitter.listeners("eventName")[0])`

The typescript compiler will throw a type error: `error TS2345: Argument of type 'Function' is not assignable to parameter of type '(...args: any[]) => void'`

It seems, that the return type of `listeners(...)` is incorrect.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
