### ISSUE TITLE
@types/node -- Variable 'require' must be of type 'any', but here has type 'NodeRequire'.

### ISSUE THREAD

**Issue by natejgardner** [DefinitelyTyped/DefinitelyTyped#18646]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @parambirs @RobDesideri @tellnes @WilcoBakker @nicolas-voigt @smac89 @Flarna @mwiktorczyk @wwwy3y3 @Tyriar @DeividasBakanas 
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

Building fails after installing `@types/node`:

```
> npm run build
WARNING in ./~/@angular/compiler/@angular/compiler.es5.js
(Emitted value instead of an instance of Error) Cannot find source file 'compiler.es5.ts': Error: Can't resolv
e './compiler.es5.ts' in 'C:\Users\me\src\my-app\node_modules\@angular\compiler\@angular'
 @ ./~/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic.es5.js 7:0-72
 @ ./src/app/main.ts
 @ multi ./src/app/main.ts
ERROR in C:/Users/me/src/my-app/node_modules/@types/node/index.d.ts (99,13): Subsequent variable de
clarations must have the same type.  Variable 'require' must be of type 'any', but here has type 'NodeRequire'.
```

**Comment by DeividasBakanas** [comment]
Could you give some more details about this issue?
- Angular version you're currently using;
- @types/node version you have installed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
