### ISSUE TITLE
@types/express, @types/express-serve-static-core -- Basic server fails. 'Argument of type '"/api"' is not assignable to parameter of type 'RequestHandlerParams'.

### ISSUE THREAD

**Issue by natejgardner** [DefinitelyTyped/DefinitelyTyped#18647]
- [x ] I tried using the `@types/express` and `@types/express-serve-static-core` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov 

Code:
```Typescript
import * as express from "express";
import { Request, Response } from "express";
import * as bodyParser from "body-parser";
import * as api from "./routes/api";

namespace my_api  {
    let app = express();
    let port: number = process.env.port || 3000;
    app.use(bodyParser.json());
    app.use('/api', api);
    app.get('/', (req: Request, res: Response) => {
           res.send("Hello world");
    });

    app.listen(port, () => console.log(`Express app listening on port ${port}`);
}
```

When building:

```
ERROR in /path/to/server.ts (25,11): Argument of type '"/api"' is not assignable to parameter of type 'RequestHandlerParams'.
```

Related:
[expressjs/express#3263](https://github.com/expressjs/express/issues/3263)

**Comment by develucas** [comment]
hi @natejgardner 
I encountered this error too and spent way too much time figuring this out. I tried fixing types definition by writing own d.ts. files but I failed. Then I came across this [expressjs: typescript: Argument of type 'typeof <express.Router>' is not assignable to parameter of type 'RequestHandlerParams'](https://stackoverflow.com/questions/44920881/expressjs-typescript-argument-of-type-typeof-express-router-is-not-assigna)
I see a lot of problems with TypeScript types and Expressjs and maybe this issue is serious but importing without using ***** seems to solve problem at least with calling overloaded **use** function.

**Comment by carmas123** [comment]
@natejgardner  your problem is into the Api Router:

you can try a solution like this (into "./routes/api" file):

```
import { Router } from "express";
const router: Router = Router();
router.get("/", getInfo);
// ...other routes...
export = router;

```

It's work for me....enjoy :)

**Comment by danielpa9708** [comment]
Is this fixed ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
