### ISSUE TITLE
[Angular 4.3.3] types/select2/index.d.ts is not a Module

### ISSUE THREAD

**Issue by compleatguru** [DefinitelyTyped/DefinitelyTyped#18772]
- [X] I tried using the `@types/select2` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @borisyankov 
My workflow is using angular/cli then ng serve for my development.
Webpack will build the files in memory.
In my simple component, I 
`npm install --save-dev @types/select2`
`import "select2";`
`ngOnInit() {  $("#select2-dom").select2(); }`

But I got this error that select2/index.d.ts is not a Module.
Can advise how to get select2 working in a angular 4 component?

**Comment by BendingBender** [comment]
This is actually a question for StackOverflow:
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
