### ISSUE TITLE
google-libphonenumber metadata untyped

### ISSUE THREAD

**Issue by darky** [DefinitelyTyped/DefinitelyTyped#18787]
- [x] I tried using the `@types/google-libphonenumber` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonyu 

```ts
require('google-libphonenumber').metadata
```

```
message: 'Property 'metadata' does not exist on type 'typeof libphonenumber'.'
```

**Comment by leonyu** [comment]
I only typed out the API surface I used in my project. If you use other stuff in their library, then you would need to add those methods/types. The API surface is not small: 

https://github.com/googlei18n/libphonenumber/tree/master/javascript/i18n/phonenumbers

They do use Closure compiler type annotation, so that might be leveraged if we want to generate the type it instead.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
