### ISSUE TITLE
@types/google-images not exporting correctly

### ISSUE THREAD

**Issue by ianpierce12** [DefinitelyTyped/DefinitelyTyped#18797]
Author: @dolanmiu 
"@types/google-images/index has no exported member 'GoogleImages'
Browser error: TypeError: __WEBPACK_IMPORTED_MODULE_4_google_images__.GoogleImages is not a constructor

**Comment by dolanmiu** [comment]
because `GoogleImages` is an interface, it doesnt have a constructor, so you can **NOT** construct it with `new` (im guessing that what u tryna do)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
