### ISSUE TITLE
setMyLocationEnabled is not working in ionic 2

### ISSUE THREAD

**Issue by rsa408** [DefinitelyTyped/DefinitelyTyped#18794]
In this code I try to find a way to show my location button but no result.
also  `setMyLocationButtonEnabled : true` seems is not in mapotions.
```
const mapOptions: google.maps.MapOptions = {
        zoom: opts.zoom,
        minZoom: opts.zoom,
        center: myLatLng,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        disableDefaultUI: true,
        scaleControl: false,
        setMyLocationButtonEnabled : true,

        styles : [
        {
          featureType: 'poi',
          elementType: 'labels',          
          stylers: [
            { visibility: 'off' }
          ]
        }],
        zoomControl: false,
        zoomControlOptions: {
          position: google.maps.ControlPosition.BOTTOM_CENTER
        }
      };
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
