### ISSUE TITLE
Wrong position type in react-redux-toastr

### ISSUE THREAD

**Issue by stefanil** [DefinitelyTyped/DefinitelyTyped#18834]
When using `@types/react-redux-toastr` the following appears.

IS:

    <ReduxToastr
        timeOut={20000}
        newestOnTop={false}
        preventDuplicates
        position="bottom-ceter"
        transitionIn="fadeIn"
        transitionOut="fadeOut"
        progressBar
    />

When using this position, no popup is shown. The error is [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux-toastr/index.d.ts) in line 13.

SHOULD:

    <ReduxToastr
        timeOut={20000}
        newestOnTop={false}
        preventDuplicates
        position="bottom-center"
        transitionIn="fadeIn"
        transitionOut="fadeOut"
        progressBar
    />

Of course it should show the pop up.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
