### ISSUE TITLE
Alexa-SDK response definitions

### ISSUE THREAD

**Issue by dhalucario** [DefinitelyTyped/DefinitelyTyped#18871]
- [X] I tried using the `@types/alexa-sdk` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @petebeegle @hoo29 @pascalwhoop @blforce 

Im having problems with the definitions. Im cannot use the this.response property in my request. Im unable to use the audioPlayer and other similar objects that are used to control other Alexa functions.

**Comment by pascalwhoop** [comment]
@mclucario you're welcome to fix the definition files! Once a PR is created I'll take a look at it

**Comment by mclucario** [comment]
I will try to give it a shot

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
