### ISSUE TITLE
TypeError: gridApi.cellNav.on.viewportKeyDown is not a function

### ISSUE THREAD

**Issue by barkingatnight** [DefinitelyTyped/DefinitelyTyped#18884]
I tried using the `@types/ui-grid` package and had problems.
for interface ICellNavApi
         on: events
Line 1222 declares viewportKeyDown with a lowercase p
**angular-ui-grid version 4.0.6**
in angular-ui-grid/ui-grid.js,  the event is declared with uppercase P
see line 15417

This results in the error listed as the title.

**Comment by eManageCRM** [comment]
gridApi.cellNav.on.viewportKeyDown != gridApi.cellNav.on.view**P**ortKeyDown

Camel case.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
