### ISSUE TITLE
Type definitions for mocha-snapshots

### ISSUE THREAD

**Issue by JLarky** [DefinitelyTyped/DefinitelyTyped#18897]
[npm package](https://www.npmjs.com/package/mocha-snapshots) [mocha-snapshots](https://github.com/wellguimaraes/mocha-snapshots) doesn't have type definitions. I looked into similar libraries, it looks like definition file for it would be very simple like so:

mocha-snapshots.d.ts:
```
/// <reference types="chai" />

declare function mochaSnapshot(chai: any, utils: any): void;
export = mochaSnapshot;

declare global {
    namespace Chai {
        interface Assertion {
            matchSnapshot(): Assertion;
        }
    }
}
```

I'm not really familiar with how this project is ran, so I would really appreciate if someone can make proper @types npm package out of this.

I can't provide any example of how to use the package from typescript, but it would be something like [this](https://github.com/wellguimaraes/mocha-snapshots/blob/master/tests/matchSnapshot.test.js) but with typescript :) but I guess if someone is ready to help, but has problem with setting up the environment I can try to help with that.

**Comment by bennypowers** [comment]
I think there would be a bit more to it than that

This is what I came up with after spending 20 minutes or so with some code that uses these types:

```typescript
// No idea what this is
type Snapshot = any;

interface Snapshots {
  update: boolean;
  get(path: string[], index: number): Snapshot
  set(path: string[], index: number, html: string, type: 'html'): Snapshot
  match(html: string, test: string): boolean;
}

declare global {
  interface Window {
    __mocha_context__: Mocha.Context & { runnable: Mocha.Runnable & { type: string } };
    __snapshot__: Snapshots
  }
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
