### ISSUE TITLE
UglifyJS typechecking and error handling

### ISSUE THREAD

**Issue by jameswilddev** [DefinitelyTyped/DefinitelyTyped#18906]
The type definition for the uglify-js package does not include interfaces for the mangle property, so code such as this can be written and pass the type checker:

	require("uglify-js").minify("anything", {
		compress: {},
		mangle: {
			toplevel: true,
			hgkuhk: true,
			properties: {
				keep_quoted: true,
				hgkuhk: true
			}
		}
	})

(where hgkuhk is not a valid property)

Additionally, the return value of the minify function is defined as "MinifyOutput", containing strings "code" and "map".  When I execute the above, I get the following instead:

	{ error: 
	   { DefaultsError: `hgkuhk` is not a supported option
		   at DefaultsError.get (eval at <anonymous> (c:\Users\james\Desktop\spriggants 2017 08 10\node_modules\uglify-js\tools\node.js:21:1), <anonymous>:79:23)
		   at formatError (util.js:648:15)
		   at formatValue (util.js:553:18)
		   at formatProperty (util.js:794:15)
		   at util.js:654:12
		   at Array.map (native)
		   at formatObject (util.js:653:15)
		   at formatValue (util.js:592:16)
		   at inspect (util.js:186:10)
		   at exports.format (util.js:72:24)
		 message: '`hgkuhk` is not a supported option',
		 defs: 
		  { cache: null,
			eval: false,
			ie8: false,
			keep_fnames: false,
			properties: false,
			reserved: [],
			toplevel: false } } }

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
