### ISSUE TITLE
TypeScript 2 definitions for Google Maps API

### ISSUE THREAD

**Issue by luciano-aguirre** [DefinitelyTyped/DefinitelyTyped#18913]
I'm working with TypeScript 2 and Node JS. I'm trying to install Google Maps, but I'm not having success. I install the Google Maps library with "npm install @google/maps" and the typescript definitions with "npm install @types/googlemaps". The problem is they have different names! So the compiler tell me "Cannot find module "@google/maps" when I write require("@google/maps").
I would be very gratefully if you could help me.
Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
