### ISSUE TITLE
NavBar.Toggle does not have access to HTML attributes

### ISSUE THREAD

**Issue by alexandro81** [DefinitelyTyped/DefinitelyTyped#18936]
- [x ] `@types/react-bootstrap` ver. 0.0.52
- [x ] tsc ver. 2.3.4

-Authors: @walkerburgin @vsiao @danilojrr @Batbold-Gansukh @octatone @chengsieuly @katbusch 

The current type definition for the props of NavBar.Toggle is:
```
interface NavbarToggleProps {
   onClick?: React.MouseEventHandler<HTMLButtonElement>;
}
```
This triggers a compilation error when trying to do the following:
`<Navbar.Toggle className="hamburger-button" onClick={this.props.onHamburgerInvoked}/`
since `className` is an attribute that the type definition hides.
That sounds wrong: `class` is a global HTML attribute and, as such, should be applicable to the Navbar.Toggle that, in its implementation, is just a `<button>`.
This limitation seems to be present for some components (NavbarToggle, NavbarCollapse, NavbarLink, ...) and not for others (NavbarHeader, NavbarBrand, ...).

I was wondering if this was intended and, if so, why.
If not, NavbarBrand (and the other components with the same limitation) could be easily changes as follows:
```
interface NavbarToggleProps extends React.HTMLProps<HTMLButtonElement> {
   onClick?: React.MouseEventHandler<HTMLButtonElement>;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
