### ISSUE TITLE
@types/recompose: toClass + TS2507 (is not a constructor function type)

### ISSUE THREAD

**Issue by mnpenner** [DefinitelyTyped/DefinitelyTyped#18941]
@iskandersierra @mrapogee @clayne11

Sample code that reproduces the problem:

```ts
import {wrapDisplayName} from 'recompose';
import {toClass} from 'recompose';

export default function withDefault(value) {
    return (BaseComponent: React.ComponentType) => class WithDefault extends toClass(BaseComponent) {
        static displayName = wrapDisplayName(BaseComponent, "withDefault");

        constructor(props) {
            super(props);
            props.dispatch([], value);
        }
    }
}
```

![image](https://user-images.githubusercontent.com/1112998/29287004-dd0f50d4-80e8-11e7-8a23-eb2c31b44e31.png)

`toClass` forces a SFC into a [constructable] class, right? So I don't think this should error.

The relevant definitions are:

```ts
export const toClass: InferableComponentEnhancer<{}>;
export type InferableComponentEnhancer<TInjectedProps> =
        InferableComponentEnhancerWithProps<TInjectedProps, {}>
export interface InferableComponentEnhancerWithProps<TInjectedProps, TNeedsProps> {
        <P extends TInjectedProps>(
            component: Component<P>
        ): React.ComponentType<Omit<P, keyof TInjectedProps> & TNeedsProps>
    }
```

We can see that it returns a `React.ComponentType` instead of a `React.ComponentClass`. This definition could be made stronger, although I'm not sure how to do it without repeating all those definitions.

**Comment by OliverJAsh** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/commit/2fc06350940e845cd9e0c33ca66ed6802ffbfda4. Please close.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
