### ISSUE TITLE
@types/bonjour new fields, and make txt records fields as associative array

### ISSUE THREAD

**Issue by dsamarin** [DefinitelyTyped/DefinitelyTyped#18969]
- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @quentin-ol @nicolas-voigt 

Thanks for taking the time to write a type file for this package. There are new fields which I thought would interest you. I've commented the updates I've made personally but since I'm new to TypeScript I'd thought I would just let someone else make the changes for me.

```ts
// +++ we need this interface from node
import {AddressInfo} from 'dgram';

  interface ServiceOptions {
    name: string;
    host?: string;
    port: number;
    type: string;
    subtypes?: string[];
    protocol?: 'udp' | 'tcp';
// +++ support arbitrary key->string mapping
    txt?: { [key: string]: string | undefined };
  }

  interface Service extends NodeJS.EventEmitter {
    name: string;
    type: string;
    subtypes: string[];
    protocol: string;
    host: string;
// +++ new referer property (albeit spelled incorrectly like this was HTTP again)
    referer: dgram.AddressInfo;
    port: number;
    fqdn: string;
// +++ support arbitrary key->string mapping
    txt: { [key: string]: string | undefined };
    published: boolean;

    stop(cb: () => any): void;
    start(): void;
  }
```

**Comment by dsamarin** [comment]
```ts


  interface AddressInfo {
    address: string;
    family: "IPv4" | "IPv6";
    port: number;
  }
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
