### ISSUE TITLE
[sequelize] Add the changes for DefineIndexesOptions already made in v3 to v4

### ISSUE THREAD

**Issue by mgruel** [DefinitelyTyped/DefinitelyTyped#19014]
- [x] I tried using the `@types/sequelize` package and had problems.

I have a problem to add a `Sequelize.fn(...)` field to the `indexes` field of the `options`
Example:
```typescript
const ProjectModel: Sequelize.Model<ProjectInstance, Project> = db.sequelize.define<ProjectInstance, Project>("Project", {
  id: {
    type: Sequelize.INTEGER,
    field: "id",
    primaryKey: true,
    allowNull: false,
    autoIncrement: true
  },
  projectId: {
    type: Sequelize.STRING(4),
    field: "projectId",
    allowNull: false,
    comment: "Unique project key"
  },
  name: {
    type: Sequelize.STRING(200),
    field: "name",
    allowNull: true,
    comment: "project name"
  }
}, {
  schema: "operational_portal",
  tableName: "projects",
  freezeTableName: true,

  timestamps: true,
  paranoid: true,

  indexes: [
    {
      name: "unique_name",
      unique: true,
      fields: [
        Sequelize.fn("upper", Sequelize.col("projectId"))
      ]
    }
  ]
});

export default ProjectModel;
```
I found a PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16908) for v3.
The [latest documentation](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-init) from sequelize states, that `Sequelize.fn(...)` is a valid param for the `fields` array.
Documentation in `@types/sequelize` shows [similar information](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sequelize/index.d.ts#L4871)

Is there any problem from including the change in v4?

Regards
Meykel

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
