### ISSUE TITLE
Incorrect return type in nodegit tree.d.ts for walk function

### ISSUE THREAD

**Issue by michaelkruglos** [DefinitelyTyped/DefinitelyTyped#19036]
The line I'm talking about is this one:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c5d04fb2d59f78a403f38ebacff9934def2da5e5/types/nodegit/tree.d.ts#L195

The implementation in nodegit creates `EventEmitter` here:
https://github.com/nodegit/nodegit/blob/2fad5782529c11d64f602a04eaf18db64471e4e2/lib/tree.js#L147
But then augments it with function named `start` here:
https://github.com/nodegit/nodegit/blob/2fad5782529c11d64f602a04eaf18db64471e4e2/lib/tree.js#L183

Which is a problem for TypeScript, since you cannot legally call this function from TS, because it's not present on `EventEmitter`. But without this `start` function on the result of calling walk, this result becomes useless and there's no way around it, other then casting to `<any>`, which defeats the purpose of having a type definition.

Please, update the type definition to include `start` function.
Thank you so much for your efforts.

**Comment by jmtoball** [comment]
Same goes for the return type of Commit#history, which [augments the EventEmitter-instance in the same way](https://github.com/nodegit/nodegit/blob/cd5c051320f1dc8d4fb97d139371fad8f1819c20/lib/commit.js#L198).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
