### ISSUE TITLE
What is Q.IPromise?

### ISSUE THREAD

**Issue by nathggns** [DefinitelyTyped/DefinitelyTyped#1904]
What is Q.IPromise? It's found in `q.d.ts` but it's not referenced to at all in the Q documentation. 

It's also causing a bug where tsc doesn't know which overload to use (as my then function is returning a Q.Promise, not a Q.IPromise as the definition expects)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
