### ISSUE TITLE
Auth0 : authorize additional parameter is missing

### ISSUE THREAD

**Issue by sberube** [DefinitelyTyped/DefinitelyTyped#19042]
Hi,

Is it possible to pass additional-parameter in the authorize method like described in the Auth0 documentation here : https://auth0.com/docs/api/authentication?javascript#social

Or is it something that is missing from the typed file?

Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
