### ISSUE TITLE
UriOptions type in Joi doesn't match the right object

### ISSUE THREAD

**Issue by christophediprima** [DefinitelyTyped/DefinitelyTyped#19061]
- [ ] I tried using the `@types/joi` package and had problems.

@Bartvds , @laurence-myers , @cglantschnig , @broder  , @GaelMagnan , @rodic  , @schfkt

**Comment by laurence-myers** [comment]
What problems? Can you provide examples / a reproducible scenario? What version of Joi? What version of @types/joi?

If you find an issue with typings, you're probably better off fixing it yourself and raising a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
