### ISSUE TITLE
Error with #lodash #uniq

### ISSUE THREAD

**Issue by lazdmx** [DefinitelyTyped/DefinitelyTyped#1908]
Fail to compile this code

``` typescript
var x: number[ ]
 _.chain( rev ).uniq( ).value( )
```

Error is:

```
error TS2094: The property 'uniq' does not exist on value of type '_.LoDashArrayWrapper<number>'
```

**Comment by kkganesan** [comment]
+1

**Comment by MrHen** [comment]
If you use the implicit chain it will work: `_(rev).uniq().value()`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
