### ISSUE TITLE
Namespace 'moment' has no exported member 'DurationInputArg1'.

### ISSUE THREAD

**Issue by jchavarria1983** [DefinitelyTyped/DefinitelyTyped#19099]
Hi, I am trying to use fullcalendar but I am getting this error:

ERROR in C:/wamp64/www/ng2-admin/node_modules/ap-angular2-fullcalendar/node_modules/@types/fullcalendar/index.d.ts (154,27): Namespace 'moment' has no exported member 'DurationInputArg1'.

I used the follow instructions: https://github.com/lbertenasco/ap-ng2-fullcalendar

But I had no luck. Could you help me ? @panic175 @nestalk

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
