### ISSUE TITLE
tstl failures

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#19102]
@samchon
The following packages do not compile correctly under the latest TypeScript:
* `@types/3d-bin-packing`
* `@types/samchon`
* `@types/samchon-collection`
* `@types/samchon-framework`
* `@types/samchon-library`
* `@types/tstl`

It looks like (except for `samchon-collection`) the underlying packages already provide their own types, which work better than the ones on DefinitelyTyped. Can we just remove these failing packages from DefinitelyTyped?

**Comment by samchon** [comment]
Deprecate them all from the DefinitelyTyped please. 

I've wanted to keep those typings in the DefinitelyTyped because of the legacy system, not using modular system of JS (like CommonJS) but using `HTML script tag`, are rampant in my home country. 

I'm sorry for providing those troubles. I'd to solve those problems by myself, not using the DefinitelyTyped.
