### ISSUE TITLE
[bootstrap-fileinput]: Unable to use built-in methods

### ISSUE THREAD

**Issue by minuz** [DefinitelyTyped/DefinitelyTyped#19110]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CheCoxshall 

Hi @CheCoxshall,
Firstly, thank you for creating this typings, it helps a lot!
Secondly, I'm trying to use the built-in functions from the library and the compilation throws an error when doing something like `$('#input-id').fileinput('clear')` and this is due the interface definition 

```
interface JQuery {
    fileinput: (options?: BootstrapFileInput.FileInputOptions) => JQuery;
}
```

I did a simple test locally here and modified the interface as follows:
```
interface JQuery {
    fileinput: (element?:any, options?: BootstrapFileInput.FileInputOptions) => JQuery;
}
```
So now the fileinput function is able to understand the string functions used by FileInput.
I'm not sure how the pull-requests works so I thought it would be easier to describe the issue and what I did to fix it. Hopefully this can be fixed for the next version of the typings.

Cheers

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
