### ISSUE TITLE
Cannot find name "ReconnectingWebSocket"

### ISSUE THREAD

**Issue by robertop87** [DefinitelyTyped/DefinitelyTyped#19130]
- [/] I tried using the `@types/ReconnectingWebSocket` package and had problems.

`wsocket-element.ts(6,11): error TS2304: Cannot find name 'ReconnectingWebSocket'`

@nguarracino to fix this I changed from:
`export default class ReconnectingWebSocket`
to:
`declare class ReconnectingWebSocket`

I sent a PR but the change is not acceptable.

Any suggestion?

Best Regards.

**Comment by nguarracino** [comment]
@robertop87 How are you importing the definition in your TypeScript file? This works for me:

`import ReconnectingWebSocket from "reconnectingwebsocket";`
`import { Options } from "reconnectingwebsocket";`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
