### ISSUE TITLE
[Request] Type definitions for react-native-mapbox-gl

### ISSUE THREAD

**Issue by madroneropaulo** [DefinitelyTyped/DefinitelyTyped#19147]
A nice project to build maps on react native. https://github.com/mapbox/react-native-mapbox-gl

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
