### ISSUE TITLE
webpack definitions: can't specify different names for different libraries for an external dependency

### ISSUE THREAD

**Issue by ivstas** [DefinitelyTyped/DefinitelyTyped#19188]
- [x] I tried using the `@types/webpack` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @RyanCavanaugh

option `ExternalsObjectElement` does not include ability to specify different names for different libraries: https://webpack.js.org/configuration/externals/#object

Unfortunatelly, I didn't succeed augmenting this definition :(

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
