### ISSUE TITLE
Not possible to import format-unicorn

### ISSUE THREAD

**Issue by dbranco** [DefinitelyTyped/DefinitelyTyped#19241]
- [ X ] I tried using the `@types/format-unicorn` package and had problems.

I tried importing this module in Visual Studio Code and it displays an error:

[ts] File 'f:/meanstack_by_myself/node_modules/@types/format-unicorn/index.d.ts' is not a module.

I have realized that the index.d.ts from @types/format-unicorn doesn't have any declaration else a interface, am I doing something wrong? Is something missing?

Kind regards.

**Comment by andy-ms** [comment]
It looks like by default, this package is not a module, and instead injects itself into `String.prototype`.
If you really want to use it that way, you could `/// <reference types="format-unicorn" />` and just start using `"".formatUnicorn({ ... })`. You may also need `import "format-unicorn";` to get the library loaded at runtime.
Or, you could instead use it as a module with `import format = require("format-unicorn/safe")`.

**Comment by dbranco** [comment]
Thanks with the import "format-unicorn" was enough.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
