### ISSUE TITLE
@types/redux-form - SubmissionError usage issue

### ISSUE THREAD

**Issue by jbiros91** [DefinitelyTyped/DefinitelyTyped#19245]
Hello, I am using redux-form with Typescript (@types/redux-form).
I cannot figure out how to correctly use SubmissionError with typescript.

When I try using Submission error as is stated in docs:
```
throw new SubmissionError({  _error: 'Login failed!' })
```
Typescript will throw this error: 
```
Argument of type '{ _error: string; }' is not assignable to parameter of type 'void'.
```

Without typescript it is working just fine. 

So problem lies in type definition in @types/redux-form:
```
export interface SubmissionErrorConstructor<T = void> {
    new (errors?: FormErrors<T>): Error;
}

declare const SubmissionError: SubmissionErrorConstructor;
```
why is generic  void?
```
T  = void
```

What am I doing wrong or how to correctly use SubmissionError with this typing?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
