### ISSUE TITLE
Change request for google.maps.StreetViewPanorama class

### ISSUE THREAD

**Issue by azmami** [DefinitelyTyped/DefinitelyTyped#19265]
- [x] I tried using the `@types/googlemaps` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond: @cgwrench

As per the official JavaScript API V3 doc, StreetViewPanorama class extends MVCObject.
https://developers.google.com/maps/documentation/javascript/reference#StreetViewPanorama
However, StreetViewPanorama in googlemaps/index.d.ts does not extend MVCObject at the moment. Due to this, I cannot call addListener() function from StreetViewPanorama object. 

In addition, nullable value should be allowed as the first parameter ('container' param) in the StreetViewPanorama class constructor like google.maps.Map does.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
