### ISSUE TITLE
Incorrect type for AndroidBackButton children prop

### ISSUE THREAD

**Issue by SuhairZain** [DefinitelyTyped/DefinitelyTyped#19279]
- [x] I tried using the `@types/react-router-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @ezintz 

Hi,
Looking at https://github.com/ReactTraining/react-router/blob/master/packages/react-router-native/BackButton.js#L35, the `children` prop is optional for `AndroidBackButton` and the type of children seems to be `ReactElement[]` rather than `React.Component[]` as it can be either Stateless Functional Components or Class components. Is the current behavior an intended one?

**Comment by SuhairZain** [comment]
@ezintz Could you kindly take a look at this issue?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
