### ISSUE TITLE
@types/react-weui:  JSX element type 'Button' is not a constructor function for JSX elements.   Property 'setState' is missing in type 'Button'.

### ISSUE THREAD

**Issue by kennir** [DefinitelyTyped/DefinitelyTyped#19286]
- [*] I tried using the `@types/xxxx` package and had problems.
- [*] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

@types/react-weui can't import component

```
import * as React from 'react';
import { Button } from 'react-weui';

interface Props extends React.Props<any> {  // tslint:disable-line

}

interface State { }

class WechatOAuth extends React.Component<Props, State> {
  render() {
    return (
      <div>
        <Button>hello</Button>
      </div>
    );
  }
}
```

the tslint show the error message

```
[ts]
JSX element type 'Button' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'Button'.
[ts] JSX element class does not support attributes because it does not have a 'props' property.
import Button
```

  - Authors: @tairan

**Comment by ekoneko** [comment]
I think the index.d.ts should be:

````tsx
class Button extends React.Component<IButtonProps, IButtonState> 
````

**Comment by miraclesumail** [comment]
i very hate u guys, dont speak useless things , okay???

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
