### ISSUE TITLE
libxmljs definitions are outdated and/or broken

### ISSUE THREAD

**Issue by zenwarr** [DefinitelyTyped/DefinitelyTyped#19285]
- [x] I tried using the `@types/libxmljs` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @fdecampredon

There are many mistakes in type definitions for libxmljs library.
For example:
- Document.errors is declared as a function, although it is a property (
(https://github.com/libxmljs/libxmljs/wiki/Document#docerrors)
- Document and Element classes are declared with constructors, and even test code creates an instance of Document with new, although Document and other classes are created without new operator in this library (see an example in libxmljs tests: https://github.com/libxmljs/libxmljs/blob/5ca9debc3a137811c6d4204a951612eabb6c0a6d/test/document.js#L27)
- Many methods are declared as returning an object, although docs clearly state that these functions can return an object or null. For example, Document.get is declared as a function returning Element, but the documentation specifies that the function returns an element or null: https://github.com/libxmljs/libxmljs/blob/5ca9debc3a137811c6d4204a951612eabb6c0a6d/test/document.js#L27
- There is no class named XMLDocument that these typings declare. 
- Many functions and properties are missing in the type definitions.

I have made type definitions file for libxmljs for my project (https://github.com/zenwarr/organelle/blob/master/src/types/libxmljs.d.ts), but due to many differences, it is not backward compatible with the one from DT repo.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
