### ISSUE TITLE
@types/nodemaile's AttachmentObject is not correct

### ISSUE THREAD

**Issue by TabeaSpahn** [DefinitelyTyped/DefinitelyTyped#19304]
- [x] I tried using the `@types/nodemailer` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rogierschouten 

The AttachmentObject interface requires the content to be set. But you can also create attachments with just a path or filename: https://nodemailer.com/message/attachments/
This is not possible with the given interface.

**Comment by rogierschouten** [comment]
Hi @TabeaSpahn thank you for your issue, you are correct.  If you submit a PR with the change, then I will review and approve it as soon as I can.

**Comment by TabeaSpahn** [comment]
Hi @rogierschouten, thank you.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
