### ISSUE TITLE
@types/Q: Regarding fulfilment types

### ISSUE THREAD

**Issue by DigitalFlow** [DefinitelyTyped/DefinitelyTyped#19335]
Hey @bnemetchek, @AndrewGaspar, @johnnyreilly:

Thanks for providing these typings.
I was wondering, why the resolve values of Promise<T> functions are all typed 

```(value: any) => U```.

When I work with a Promise<T>, I'd also expect the value returned by it to be of type T. 
This would also allow to get propper IntelliSense without casting each value in the then function.

Could we maybe change the defintions to something like
```then<U>(onFulfill?: (value: T) => U | IPromise<U> ...```?

I'm sure the current implementation was a design decision, but could we do anything, to get propper Intellisense merely by the type of the Promise?

Kind Regards,
Florian

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
