### ISSUE TITLE
Can Angular 1.5.x type definitions be updated to include jQuery definition as peer dependency? 

### ISSUE THREAD

**Issue by ryanmcdermott** [DefinitelyTyped/DefinitelyTyped#19354]
If a user includes the Angular type definitions and jQuery type definitions (such as 3.2.x), the Angular provided type definitions of jQuery clash with the user's provided version of jQuery (such as 3.2.x). Can Angular make these jQuery type definitions a peer dependency that is also permissive on major/minor versions? This would keep users from having to put `skipLibCheck` in their `tsconfig.json`

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @.... @diegovilar @thorn0 @calebstdenis @leonard-thieu

**Comment by leonard-thieu** [comment]
The current version of `@types/angular` is v1.6. I don't believe older minor versions of type definitions are supported by DefinitelyTyped. If you're using v1.5 type definitions, you can use `@types/jquery` v2 instead which should be compatible.

**Comment by thorn0** [comment]
There is little to no API incompatibility between AngularJS 1.5.x and 1.6.x. Why not use the latest version of the definitions?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
