### ISSUE TITLE
security on website: links to broken not secure site

### ISSUE THREAD

**Issue by aretecode** [DefinitelyTyped/DefinitelyTyped#19358]
site on http://definitelytyped.org/directory/projects.html
<img width="231" alt="screen shot 2017-08-25 at 11 53 16 pm" src="https://user-images.githubusercontent.com/4022631/29739349-acf7264a-89f0-11e7-8281-60f9a1eeab54.png">
<img width="553" alt="screen shot 2017-08-25 at 11 52 55 pm" src="https://user-images.githubusercontent.com/4022631/29739351-af881c7a-89f0-11e7-9cb9-fe7ccd535468.png">

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
