### ISSUE TITLE
select2 Select2Options missing option "dir"

### ISSUE THREAD

**Issue by ayyash** [DefinitelyTyped/DefinitelyTyped#19364]
- [x] I tried using the `@types/select2` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

@borisyankov Select2Options  is missing the "dir" option found here https://select2.github.io/examples.html#localization-rtl-diacritics

**Comment by IRCraziestTaxi** [comment]
Any word on this? Where tf did Select2Options go?

**Comment by Ali-Azmoud** [comment]
any news, update?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
