### ISSUE TITLE
@types/joi [ts] Object is possibly 'undefined' error

### ISSUE THREAD

**Issue by lascarayf** [DefinitelyTyped/DefinitelyTyped#19370]
I have a typescript null validation error when i use `Joi.boolean().required().error('')` 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a3fd248f249613924e65a231f795afd0fd989929/types/joi/index.d.ts#L339

**Comment by barbaracassani** [comment]
I am having the same identical issue.

**Comment by SimonSchick** [comment]
IIrc `.error` is not always available on all schemas, use the null assertion operator.

**Comment by smilemuffie** [comment]
> IIrc `.error` is not always available on all schemas, use the null assertion operator.

I don't know why, it's doesn't work for me.

I changed my `tsconfig.json` file, "strictNullChecks": false to disable it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
