### ISSUE TITLE
Can't build with ng build --prod

### ISSUE THREAD

**Issue by rrdlpl** [DefinitelyTyped/DefinitelyTyped#19421]
I can't build my project that uses this library because this error. I reproduced in angular 4 and 2, angular-cli >= 1.0.0

ERROR in ng:///C:/Users/rdelaparral/workspace/site-builder-final/Seon.SiteBuilder.UI/node_modules/angular-esri-components/src/lib/widgets/layers-toggle/layers-toggle.component.d.ts.LayersT
oggleComponent.html (3,5): Property 'items' does not exist on type 'Collection'.

Please help :(

**Comment by dasa** [comment]
Can you use `toArray` instead?
https://developers.arcgis.com/javascript/latest/api-reference/esri-core-Collection.html#toArray

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
