### ISSUE TITLE
SP.List.addItem() doesn't return a specific SP.ListItem type

### ISSUE THREAD

**Issue by pedro-pedrosa** [DefinitelyTyped/DefinitelyTyped#19430]
- [x] I tried using the `@types/sharepoint` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @baywet 

I have noticed that while calling `addItem()` from `SP.List<SomeModel>` the returned value is of type `SP.ListItem<any>` while I believe it should return `SP.ListItem<SomeModel>`.
Is this unindended or am I missing something?

Thank you.

**Comment by baywet** [comment]
Hi @bLasTamos ,
Thanks for reaching out.
I was not the one implementing that part, however I believe it was implemented this way for a few reasons:
- The Server Side (and API's, and SDK's) don't do any kind of downcasting or dynamic type allocation, most or SharePoint's internal mechanics pre-date that. You can see that the [server side API doesn't do it for instance](https://msdn.microsoft.com/en-us/library/office/ee586483.aspx)
- Because it's only a type definition and we're relying on a "loose-type" language behind the scenes and the data is going across the wire, there's not code implemented to re-hydrate it properly, you'd get the properties but not the prototype (methods), you can see a similar issue [here](https://github.com/SharePoint/PnP-JS-Core/issues/390)
- Modern libraries [are return data as any](https://raw.githubusercontent.com/SharePoint/PnP-JS-Core/master/src/sharepoint/lists.ts) mostly for the reasons I mentioned I believe (look for ListAddResult)

So I think that even if we update the type definition, you would not have a real implementation and proper behavior behind the scenes. Not to mention that'd be a breaking change for existing projects depending on what we update exactly.

I think the proper way to implement that on your hand would be to haver a data mapper between your high-level type and the SP.ListItem type to handle serialization/de-serialization.

Does that answer your question?

**Comment by bLasTamos** [comment]
Thank you for the response. Sorry I just mentioned you, you were the only github user I found in the comments of the .d.ts file.

Well the thing is the sharepoint API doesn't use or serialize/deserialize any high-level types directly, the point of having a specific `SP.ListItem<Model>` type is that you can get autocomplete/type safety when you call `get_item`/`set_item` on a list item object.

Say your `Model` type has `prop1` of type text and `prop2` of type url. If you have an `SP.List<Model>` you should be able to get a specific `SP.ListItem<Model>` item object when you add an item to the list so that you can call a type-checked `set_item('prop1', 'string')` and `set_item('prop2', spFieldUrlValue)` on the recently added item. In runtime this doesn't make any difference because the sharepoint API doesn't care about your `Model` nor is it being used anywhere except for type safety in compile time, which is why I thought changing definition types wouldn't have any dangerous implications...

**Comment by baywet** [comment]
Agree with your interpretation on SharePoint code, it will be here. However let's say your custom type has a method defined, it will build but at runtime you won't get your method because the prototype doesn't get applied.
It's not a direct issue but it will be an easy trap for a lot of people.
The thing I'm the most concerned about is breaking existing projects at compile time by changing it, especially because I didn't originally create that type definition.
I'd like to get @andy-ms opinion here: should the approach to fix and risk breaking stuff and then handle feedback? Should we bump up the major version? (this package was originally versioned with SharePoint's product year, not even the version) How do you usually handle those legacy situations?

**Comment by bLasTamos** [comment]
Most likely you will only be making a breaking change to code that is not type safe anyway. Most people using `SP.List<Model>` are probably writing code that will compile after the change. People using `SP.List` (= `SP.List<any>`) won't see a difference.

It's still a breaking change.

**Comment by andy-ms** [comment]
> let's say your custom type has a method defined, it will build but at runtime you won't get your method because the prototype doesn't get applied.

That might be so, but getting back a `T` is still saf*er* than getting back `any`. I think making use of the generic type on `Model` would be the right decision here, as those not wanting to use the generic type can simply not provide one to `List` and it will default to `any`.
I don't know how SharePoint is versioned, but I think that if the latest version is past `2013`, *and* if the types are up-to-date with the latest version, then it would make sense to update the version in the first line of `index.d.ts` to reflect that.

**Comment by baywet** [comment]
thanks for joining the discussion @andy-ms so in my understanding those referring to any currently, when get the update, would not have any breaking change correct? (unless they did some weird casting) Worst case they'll use List<any> instead of any and benefit better compile type validation.

SharePoint is versioned like that v14 for 2010, v15 for 2013, v16 for 2016. Service Packs introduce a minor version. I don't think we have to change anything if we don't introduce a big breaking change.

**Comment by andy-ms** [comment]
It would be a breaking change for people using `List<Foo>` but not for people just using `List` (which is the same as `List<any>`.

**Comment by baywet** [comment]
hopefully the people using List<Foo> are casting in Foo when they are calling addItem or similar methods, but this is a big assumption for a breaking change.
maybe the solution would be to implement that change and change major version to 2016 (the latest on prem version of SharePoint)? there are properties that have been added to this types definition which are in facts addition from 2016. This way we protect people against breaking changes, we keep the versioning pattern initially in place with the types definition and we "upgrade to latest version of SharePoint". What do you think?

**Comment by andy-ms** [comment]
Incrementing the version would be a good idea.
I doubt people are remembering to cast from `any`, since that type is unsafe and you'll get no compile error if you just use it directly.

**Comment by baywet** [comment]
@bLasTamos do you feel like submitting a PR or would you rather having me doing it?

**Comment by bLasTamos** [comment]
I'm on holiday, you can go ahead and do it.

**Comment by baywet** [comment]
@pedro-pedrosa since the PR has been merged and the issue fixed, could you close that issue please?

**Comment by pedro-pedrosa** [comment]
Yes of course. Thank you for writing the PR.
