### ISSUE TITLE
Handlebars runtime declaration missing with strict mode on.

### ISSUE THREAD

**Issue by jeremychone** [DefinitelyTyped/DefinitelyTyped#19441]
- [x] I tried using the `@types/handlebars` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Project with Typescript and Browserify, it seems the [handelbars/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/handlebars/index.d.ts) is missing a 
```es
declare module "handlebars/runtime" {
	export = Handlebars;
}
```
Right now, it just has: 
```es
declare module "handlebars" {
    export = Handlebars;
}

declare module "handlebars/handlebars.runtime" {
    export = Handlebars;
}
```

However, with Typescript, doing a `import handlebars/handlebars.runtime` will create the following issue: 
```
 error TS2307: Cannot find module 'handlebars/handelbars.runtime'
```

doing a `import Handlebars = require("handlebars/runtime");` creates: 
```
error TS7016: Could not find a declaration file for module 'handlebars/runtime'. '/Users/jeremychone/_jeremy/_projects/mvdom-patterns/mvdom-patterns_src/node_modules/handlebars/runtime.js' implicitly has an 'any' type.
  Try `npm install @types/handlebars/runtime` if it exists or add a new declaration (.d.ts) file containing `declare module 'handlebars/runtime';
```

So, my current workaround was to add the `declare module "handlebars/runtime"` above in a `....d.ts` file. If this is the right solution, would be good to have it by default in [handelbars/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/handlebars/index.d.ts)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
