### ISSUE TITLE
'responsive' does not exist in type 'Settings'

### ISSUE THREAD

**Issue by medisoft** [DefinitelyTyped/DefinitelyTyped#19474]
I tried using the `@types/datatables.net` package and had problems. It seems that the index.d.ts file in the settings part doesn't has the responsive: boolean setting.

It is not on the git repo too.

**Comment by andy-ms** [comment]
PRs accepted.

**Comment by cdalexndr** [comment]
**@types/datatables.net 1.10.18** has the required **responsive** filed

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
