### ISSUE TITLE
@types/chai-http – Can't use ES6 import

### ISSUE THREAD

**Issue by shroudedcode** [DefinitelyTyped/DefinitelyTyped#19480]
- [x] I tried using the `@types/chai-http` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I [mentioned](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Nemo157, @G1itcher, @CaselIT

---

While I'm able to import `chai-http` using `const chaiHttp = require('chai-http')`, I can't do the same thing with ES6 imports.

```ts
import chaiHttp from 'chai-http'
```
> `Module '"/mnt/data/Projects/Node.js/express-decorators/node_modules/@types/chai-http/index"' has no default export.`

```ts
import * as chaiHttp from 'chai-http'
```
> `Module '"/mnt/data/Projects/Node.js/express-decorators/node_modules/@types/chai-http/index"' resolves to a non-module entity and cannot be imported using this construct.`

```ts
import { chaiHttp } as chaiHttp from 'chai-http'
```
> `Module '"/mnt/data/Projects/Node.js/express-decorators/node_modules/@types/chai-http/index"' has no exported member 'chaiHttp'.`

> `Module '"/mnt/data/Projects/Node.js/express-decorators/node_modules/@types/chai-http/index"' resolves to a non-module entity and cannot be imported using this construct.`

---

<strike>I found this in `chai-http`'s code:
```
module.exports = function (chai, _) { ... }
```
Isn't this a default export and shouldn't a default import (my first attempt) work then?</strike>

**Comment by CaselIT** [comment]
No, 
```
module.exports = function (chai, _) { ... }
```
is not a default export since it does not export a `default` property.

A fake namespace could be added in the definition, so you could use 
```
import * as chaiHttp from 'chai-http'
```
but I'm not sure if there are some guidelines about it.

**Comment by shroudedcode** [comment]
@CaselIT That would be great, because that's also the way I import `chai` for example.

**Comment by s-edlund** [comment]
Any progress on this yet? I'm getting typescript errors above `...resolves to a non-module entity and cannot be imported using this construct` using `import` and if I do `let chai = require('chai-http') I get an error `property chai.request does not exists on ChaiStatic`. Kind of a  catch-22.

**Comment by chadbr** [comment]
anything I can do to help on this one?

**Comment by G1itcher** [comment]
The way I currently use chai-http is:

`chai.use(require('chai-http'));`

I know it's not hugely pretty, but it does the job and is readable

**Comment by lcoenen** [comment]
@G1itcher but how do you import the type definition afterward? I used this solution but I had [this error](https://stackoverflow.com/questions/49140297/cannot-import-declaration-file)

**Comment by maxx-t** [comment]
The @G1itcher solution allows ts to transpile but I could not have (vscode) completion without adding `import 'chai-http'`, so I currently have something like:
```typescript
import 'chai-http';
import * as chai from 'chai';
chai.use(require('chai-http'));
```

**Comment by MIrinkov** [comment]
My two cents:

```typescript
import * as chai from 'chai';
import chaiHttp = require('chai-http');

chai.use(chaiHttp);
```

This abomination seems to work for me for code completion and does not trigger any warnings or errors.

**Comment by Hufschmidt** [comment]
> My two cents:
> 
> ```ts
> import * as chai from 'chai';
> import chaiHttp = require('chai-http');
> 
> chai.use(chaiHttp);
> ```
> 
> This abomination seems to work for me for code completion and does not trigger any warnings or errors.

Just for documentation purpose since google send me here.  
The solution by @MIrinkov is correct [**1**], see this [typescript issue](https://github.com/Microsoft/TypeScript/issues/21535#issuecomment-362460086).

In-depth explanations can be found in [this blog post](https://itnext.io/great-import-schism-typescript-confusion-around-imports-explained-d512fc6769c2) and in the [typescript 2.7 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html) (see *support for commonjs module* section).

**The TL;DR version:**

Normally you would use `import * as chaiHttp from 'chai-http'` to import commonjs/nodejs modules with typescript. However this does not work if the exported content is a function, since this violates ES6 module specification and thus fails with a warning from typescript:

> This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export

---

**1**: The alternative is to **enable** the `esModuleInterop` in typescript (*through cli or tsconfig.json*), which is the default for new typescript projects (*3.0.0+*) which allows you to use the *babel-like* syntax:
`import chaiHttp from 'chai-http'`

The only issue I'm currently having with this is that Atom Typescript plugin complains about `node_modules/chai-http/types/index` having no default export. tsc on the other hand transpiles without errors and tests seem to work...

**Comment by pritisolanki** [comment]
I have "esModuleInterp" set to true and calling
import * as chaiHttp from 'chai-http';

VScode  show following error

TSError: ⨯ Unable to compile TypeScript:
test/xxx.tests.ts:5:27 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
