### ISSUE TITLE
Leaflet 1.2.0, using leaflet-plugins KML no longer works

### ISSUE THREAD

**Issue by bomberblue07** [DefinitelyTyped/DefinitelyTyped#19492]
- [x] I tried using the `@types/leaflet` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alejo90

Before the Leaflet 1.2.0 typings upgrade, I used the KML plugin from leaflet-plugins without issue. Now after the typings upgrade, all of my Leaflet code in my app works properly after migrating to the new ES 6 modules except for the KML plugin.

Previously to get the KML plugin to work in my app, I just needed to load its KML.js and add this declaration to my typings file:

`declare namespace L { 
  class KML extends Layer { 
    constructor(url: string, options?: any); 
  } `

To get my TypeScript/Angular code to compile, I deleted that code from my typings file and put this code in every file in my app that uses the KML class: 

`declare class KML extends Layer { 
    constructor(url: string, options?: any); 
} `

While my code now compiles, it complains that `ReferenceError: KML is not defined`

How can I get the KML plugin to play nice with the new typings?

**Comment by alejo90** [comment]
Since new syntax had to be used to make the Leaflet module UMD/es6 compatible, I had to updated all of the typings that depend on it to also use new syntax. If I'm correct, the KML plugin you mentioned has it's own typings in it's own repository. In that case, you need to modify them to look something like this:

```
import * as L from 'leaflet';

declare module 'leaflet' {
  // your stuff here
}
```

**Comment by bomberblue07** [comment]
@alejo90

Yeah, that's not working for me. I added `import * as L from 'leaflet';
import {Layer} from "leaflet";

declare module 'leaflet' {

    class KML extends Layer {
        constructor(url: string, options?: any);
    }
}`

To my typings.d.ts file in my Angular CLI project and I come up with compilation issues that @types/leaflet/index has no exported member 'KML'

You said the KML plugin for leaflet has typings, but I can't seem to find them/reference them. Any guidance?

**Comment by bomberblue07** [comment]
Anyone have any luck with this? I ended up reverting my typings to pre-1.2.0, but that's not a sustainable solution

**Comment by bomberblue07** [comment]
The "solution" for me was to just re-write the KML plugin to not use the `L.<Class>` naming convention and to kludge-include it in my TypeScript code using `declare const KML: any;`

Not ideal, so keeping this issue open for now

**Comment by alejo90** [comment]
Sorry about the late response. I've been busy with work. I believed there were typings for this library but upon checking it's repo I found out I was mistaken. In this case, typings for leaflet-plugins have to be created. It's not too difficult to do so, since there are not too many publicly exposed types. If you want to tackle creating those typings, I'll be glad to offer guidance if you want me to. I don't offer to write them because I have never used the library and, as a result, I'm not well acquainted with it. In addition, it doesn't seem I'll be using it on any of my projects on the near future, so I wouldn't be a good maintainer candidate.

**Comment by bomberblue07** [comment]
I'm closing this issue as typings for the KML plugin are outside of the scope of leaflet typings. I was eventually able to integrate the plugin with the latest leaflet and typings by directly importing the javascript file and calling the constructor untyped
