### ISSUE TITLE
Support for controlsList for video tag

### ISSUE THREAD

**Issue by Dante-101** [DefinitelyTyped/DefinitelyTyped#19500]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @richseviora 

Chrome has started supporting `controlsList` attribute in `video` tag. Does React Typescript definition community add definitions for a Living Standard spec? 

If yes, can we add the support in React definitions? If not, is there a way to use this attribute with typescript?

API Reference:
<https://developers.google.com/web/updates/2017/03/chrome-58-media-updates#controlslist>
<https://github.com/WICG/controls-list/blob/gh-pages/explainer.md>
<https://wicg.github.io/controls-list/html-output/multipage/embedded-content.html#attr-media-controlslist>

**Comment by Dante-101** [comment]
Any update on this one?

@johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @morcerf, @tkrotoff, @DovydasNavickas, @onigoetz, @richseviora

**Comment by trajano** [comment]
It needs to be in the `HTMLMediaElement` interface defined in https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L7275 

The entry that is missing is 
`readonly controlsList: DOMTokenList`

To work around this add this to a `.d.ts` file in your project.
```
interface HTMLMediaElement {
    readonly controlsList: DOMTokenList 
}
```
and let the [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) do it's work.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
