### ISSUE TITLE
React JSX types not consistent with equivalent usage of React.createElement

### ISSUE THREAD

**Issue by PaulJuliusMartinez** [DefinitelyTyped/DefinitelyTyped#19516]
Consider the following attempt to have properly typed support for `defaultProps` in React components:

```tsx
interface Props {
  a: number
  b?: number
}

interface DefaultProps {
  b: number
}

class Example extends React.Component<Props, {}> {
  props: Props & DefaultProps
  static defaultProps: DefaultProps = {
    b: 0
  }

  render() {
    // No type error
    let x: number = this.props.b
    return (<div>{x}</div>)
  }
}
```

This should allow property `b` not to be included as a prop when creating an `Example` component, but ensure that `this.props.b` always has a type of `number` inside the `render` function. The following code should not throw any type errors.

```tsx
let jsx1 = <Example a={1} b={2} />
let jsx2 = <Example a={1} />
```

The second line however results in the error:

```
TS2322: Type '{ a: 1; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Example> & Props & DefaultProps'.
  Type '{ a: 1; }' is not assignable to type 'DefaultProps'.
    Property 'b' is missing in type '{ a: 1; }'.
```

However, if we change this to the equivalent pure JS implementation, there is no error:

```js
let createElement1 = React.createElement(Example, { a: 1, b: 2 })
let createElement2 = React.createElement(Example, { a: 1 })
```

This suggests that the `JSX` definition included with React is inconsistent with the handwritten JS equivalent.

This example was inspired by @vsaarinen's solution in [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11640) about how to properly add types for `defaultProps`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
