### ISSUE TITLE
@types/tv4 - FormatValidationFunction - invalid return type

### ISSUE THREAD

**Issue by codebysd** [DefinitelyTyped/DefinitelyTyped#19555]
- [x] I tried using the `@types/tv4` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Bartvds @psnider 

**Context:**
As per official tv4 documentation, additional JSON schema formats can be registered with tv4 by providing a format validation function. This function [must return a string error or null value](https://github.com/geraintluff/tv4#addformatformat-validationfunction). 

**Problem**
The type definition of [`FormatValidationFunction` in @types/tv4](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/tv4/index.d.ts#L55) has only `string` return type:

```javascript
export type FormatValidationFunction = (data: any, schema: JsonSchema) => string;
```

Typescript fails to compile in strict mode if the supplied validation function returns `null` as well. 

**Fix**
The definition must also have a `null` return type:

```javascript
export type FormatValidationFunction = (data: any, schema: JsonSchema) => string | null;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
