### ISSUE TITLE
pg can't use connectionString

### ISSUE THREAD

**Issue by cedvdb** [DefinitelyTyped/DefinitelyTyped#19572]
- [ x] I tried using the `@types/pg` package and had problems.

according to [documentation](https://node-postgres.com/features/connecting#connection-uri)  you should be able to do this

```
const { Pool, Client } = require('pg')
const connectionString = 'postgresql://dbuser:secretpassword@database.server.com:3211/mydb'

const pool = new Pool({
  connectionString: connectionString,
})
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
