### ISSUE TITLE
[@types/openlayers] Missing moveTolerance option in olx.MapOptions

### ISSUE THREAD

**Issue by bbaia** [DefinitelyTyped/DefinitelyTyped#19581]
See
https://github.com/openlayers/openlayers/blob/ba867f8ff8c5efdfd4a9223a354edf3f7cc214e1/externs/olx.js#L295

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
