### ISSUE TITLE
@types/react-lazyload placeholder Node type causes compiling error

### ISSUE THREAD

**Issue by shortgiraffe4** [DefinitelyTyped/DefinitelyTyped#19599]
I tried using the `@types/react-lazyload` package for react-lazyload (https://github.com/jasonslyvia/react-lazyload) and had problems.
I created a react element 
`export const ImagePlaceHolder = () => <div className={styles.placeHolder}></div>`

then used it as: 
`<LazyLoad placeholder={<ImagePlaceHolder />}></LazyLoad>`

but it caused an error `Type 'Element' is not assignable to type 'Node'.` 
I tried many different ways but couldn't get any good news. 
According to `react-lazyload` documentation, `placeholder` should be `any`. 
I'm not sure why the typings package defines it as `Node`. 

- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-lazyload
- Authors: @m0a

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
