### ISSUE TITLE
Postal code not retrieved while calling getplacepredictions API for Cordova

### ISSUE THREAD

**Issue by sridharalluri** [DefinitelyTyped/DefinitelyTyped#19674]
Hi Team,

we have built an app and used this API for retrieving the address. Every other option is received but except for postal code.

can you please help us on this.
we have used the following API "getplacepredictions"

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
