### ISSUE TITLE
BoundingBox should be of type Box3

### ISSUE THREAD

**Issue by roy192** [DefinitelyTyped/DefinitelyTyped#1968]
I have searched through the three.js code for the boundingBox property. And the only times it was set to a value, it was either null or THREE.Box3.

But in the definition file, it says that boundingBox is of type BoundingBox3D (which is an interface with only the min and max properties). I have no idea why boundingBox is defined this way... And now I can't use the methods that are defined for Box3 (which aren't in the seemingly useless interface). I also see no other usage of this interface.

I think the interface should be deleted and replaced by the actual Box3 class.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
