### ISSUE TITLE
[Request] tabula-js types

### ISSUE THREAD

**Issue by jakehockey10** [DefinitelyTyped/DefinitelyTyped#19704]
I would like types provided for [`tabula-js`](https://github.com/ezodude/tabula-js).  I'm not sure how to do it myself.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
