### ISSUE TITLE
Why HTMLDivElement doesn't has placeholder and type?

### ISSUE THREAD

**Issue by threescales** [DefinitelyTyped/DefinitelyTyped#19706]
I edit content by div with contentEditable.But in @15.6.1. placeholder can‘t support by tsx. So，what should I do？

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
