### ISSUE TITLE
Wrong return value type for react-select's filterOption prop

### ISSUE THREAD

**Issue by lufte** [DefinitelyTyped/DefinitelyTyped#19724]
- [x] I tried using the `@types/react-select` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Hesquibet, @giladgray, @iebaker, @skirsdeda, @vujevits, @devrelm, @MartynasZilinskas, @onatm 

According to the package documentation at https://github.com/JedWatson/react-select/tree/master#advanced-filters, `filterOption` is a function that returns a boolean. The type definition here says it must return an `Option` though.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
