### ISSUE TITLE
`@types/sequelize`: `$eq` missing from `WhereLogic`

### ISSUE THREAD

**Issue by hotaru355** [DefinitelyTyped/DefinitelyTyped#19736]
- [x] I tried using the `@types/sequelize` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @samuelneff, @CodeAnimal, @drinchev, @babolivier, @kukoo1, @oktapodia, @MorpheusXAUT

The `WhereLogic` interface is missing the `$eq` operator.

Note: I created a fix but am not able to run the compiled test file. The error I get is ..
```
./DefinitelyTyped/node_modules/sequelize/lib/sequelize.js:112
      options.dialect = urlParts.protocol.replace(/:$/, '');
                                         ^

TypeError: Cannot read property 'replace' of null
```
.. probably due to missing database config. Could you provide help on how to run the test file?

**Comment by drinchev** [comment]
Can't really help on that. I think your question is more generic towards DefinitelyTyped, maybe try to ping the authors of previously merged pull requests, since they will know more about how to run the tests.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
