### ISSUE TITLE
node definition missing `_writev`

### ISSUE THREAD

**Issue by reviewher** [DefinitelyTyped/DefinitelyTyped#19737]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
Authors: @parambirs @RobDesideri @tellnes @WilcoBakker @octo-sniffle @smac89 @Flarna @mwiktorczyk @wwwy3y3 @Tyriar @DeividasBakanas @kjin

Writable stream supports both `_write` and [`_writev`](https://nodejs.org/api/stream.html#stream_writable_writev_chunks_callback).  The node definition has [`_write`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L5087) but no `_writev`.

The following definition seemed to work for me:

```typescript
interface Chunk {
	chunk: any;
	encoding: string;
}
_write(chunk: Chunk[], callback: Function): void;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
