### ISSUE TITLE
Missing optional value parameter in RechartsFunction

### ISSUE THREAD

**Issue by jetpack3331** [DefinitelyTyped/DefinitelyTyped#19756]
- [ ] I tried using the `@types/recharts` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @xile611

In actual RechartsFunction type is missing optional value definition and can't use custom formatters for XAxis, YAxis etc.

**Comment by rapmue** [comment]
Which formatters should be included in the definitions?
I.e. what is the signature of the methods you think are missing?

**Comment by mthmulders** [comment]
It's [propType is `PropTypes.func`](https://github.com/recharts/recharts/blob/c8d80efe854874f69a40968c89ccde56b448b7db/src/cartesian/YAxis.js#L35), so that doesn't really help us either. [It's invoked](https://github.com/recharts/recharts/blob/c8d80efe854874f69a40968c89ccde56b448b7db/src/cartesian/Brush.js#L135) with a parameter named `text`, suggesting its input might be a String. But I wouldn't rely on that either.

So I think `(value: any) => any` is indeed the best we can do...

**Comment by rapmue** [comment]
@jetpack3331 Since the requested changes were included in the last merge, you could close this topic.

**Comment by jetpack3331** [comment]
Thx @rapmue

**Comment by tompuric** [comment]
I don't think this has been resolved. RechartsFunction is hiding parameter data in all the graphs in typescript at the moment. I am unable to use any mouse/click handlers to get graph data unless I override the RechartsFunction to take "value: any". 

Example onClick for LineChart returns {activeCoordinate, activeLabel, activePayload, activeTooltipIndex, chartX, chartY} but the current typescript definitions prevent me from accessing this value parameter.

**Comment by rapmue** [comment]
@tompuric In this issue the request was for formatters not callback functions. If you are unhappy with the current definitions, a pull request is appreciated.
