### ISSUE TITLE
@types/node doesn't work with object streams

### ISSUE THREAD

**Issue by ip** [DefinitelyTyped/DefinitelyTyped#19761]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @parambirs @RobDesideri @tellnes @WilcoBakker @octo-sniffle @smac89 @Flarna @mwiktorczyk @wwwy3y3 @Tyriar @DeividasBakanas @kjin

In the `stream` module, everything like `chunk: Buffer | string` should be replaced by `any`, because in object mode there may be any type of object.

It would be even better if the chunk type is parametrized using generics (with `Buffer | string` as a default). I'm currently forced to write my own wrapper on the existing typings using generics. Here is what I have so far: https://gist.github.com/ip/07a66ceb359494d85e26d3a0bc1b344f. You can copy-paste any parts if you want.

Also, there is this assumption in `*Stream` interfaces defined in `namespace NodeJS`. Why do these interfaces even exist, if everything using streams depends on implementation? I don't think there are any "stream interfaces" in Node at all. If you're making a custom stream, you're deriving from one of `stream.*` classes and that's it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
