### ISSUE TITLE
Please mention Git submodules as solution to common problem.

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#19815]
The readme should perhaps mention _Git submodules_.

https://git-scm.com/book/en/v2/Git-Tools-Submodules

I have a project called `suman-types`, which stores all my types for a suite of projects. I want to publish a subdirectory of suman-types to DefinitelyTyped/types/suman.

It seems like this this a common use case, is there some direction on how to do this?

**Comment by zacnomore** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package

> If you are the library author and your package is written in TypeScript, [bundle the autogenerated](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) declaration files in your package instead of publishing to Definitely Typed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
