### ISSUE TITLE
nested namespaces, bad warning message

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#19819]
Please see this SO question:
https://stackoverflow.com/questions/46271047/exporting-nested-typescript-namesapce

it looks like the compiler simply issues a bad warning message.

_SumanLib.x is an exported member, but it's a namespace, and not a valid exported member?_

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
