### ISSUE TITLE
react-autosuggest: Property not known/named differently

### ISSUE THREAD

**Issue by kuebelkasten** [DefinitelyTyped/DefinitelyTyped#19828]
- [X] I tried using the `@types/react-autosuggest` package and had problems.

I was playing around with the react-autosuggest packages including the typings. However, when I used the `BlurEvent` I got always errors that the property `focusedSuggestion` is not set.
Looking at the param that got passed to the callback, there is indeed no such property but another one named `highlightedSuggestion`.
I've changed this in the index.d.ts and it worked as expected. Not sure if this is a breaking change in the autosuggest or an issue with the typings.

I've used the latest version of typings (8.0.2) and also the latest of react-autosuggest (9.3.2)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
