### ISSUE TITLE
@types/mapbox-gl

### ISSUE THREAD

**Issue by pvdyck** [DefinitelyTyped/DefinitelyTyped#19834]
export interface StyleFunction {
		stops: any[][];
		property?: string;
		base?: number;
		type?: "identity" | "exponential" | "interval" | "categorical";
		default?: any;
		"colorSpace"?: "rgb" | "lab" | "interval";
	}

should be

export interface StyleFunction {
		stops?: any[][];
		property?: string;
		base?: number;
		type?: "identity" | "exponential" | "interval" | "categorical";
		default?: any;
		"colorSpace"?: "rgb" | "lab" | "interval";
	}

stops is not mandatory

thanks !

https://github.com/mapbox/mapbox-gl-js/issues/5318

**Comment by shiftkey** [comment]
@pvdyck would you mind making the change to the method directly and opening a pull request? 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d525d2763ff69ca4093f71906ea9a7f36f519349/types/mapbox-gl/index.d.ts#L922-L929

**Comment by pvdyck** [comment]
here it is => https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19866

**Comment by chloekraw** [comment]
👋 flagging that this ticket can be closed!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
