### ISSUE TITLE
angular-ui-router - missing bindings from IState

### ISSUE THREAD

**Issue by andreicojea** [DefinitelyTyped/DefinitelyTyped#19905]
Missing `bindings` property on `IState` interface:

ui-router docs:
https://ui-router.github.io/ng1/docs/latest/interfaces/ng1.ng1viewdeclaration.html#bindings

Should be somewhere around here, next to `resolve`:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b04ef812019bdfc4b17f1ede66fc8a6c17b42516/types/angular-ui-router/index.d.ts#L62

**Comment by christopherthielen** [comment]
DefinitelyTyped definitions are for ui-router versions 0.x.x.  Those versions were written in JavaScript. 

On the other hand, `bindings` is from UI-Router 1.0+ which is written in Typescript.  If you're using 1.0+ you should not be using DefinitelyTyped definitions.  Instead, you should use the .d.ts files distributed with ui-router 1.0+, i.e., https://unpkg.com/@uirouter/angularjs@1.0.10/lib/index.d.ts.  These files should be automatically recognized by TypeScript if you are using node module resolution.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
