### ISSUE TITLE
TS2304: Cannot find name 'Iterable'.

### ISSUE THREAD

**Issue by icjking** [DefinitelyTyped/DefinitelyTyped#19902]
ERROR in [at-loader] ./node_modules/@angular/core/src/change_detection/differs/default_iterable_differ.d.ts:28:32 
    TS2304: Cannot find name 'Iterable'.

ERROR in [at-loader] ./node_modules/@angular/core/src/change_detection/differs/iterable_differs.d.ts:15:48 
    TS2304: Cannot find name 'Iterable'.

**Comment by KyleKorndoerfer** [comment]
I have a simple TS project that has `"@types/jquery": "^3.2.12"` (most recent when started) listed as a dev dependency with `"jquery": "^3.2.1"` listed as a runtime dependency. When I run the TS compiler, I get the following output: `node_modules/@types/jquery/index.d.ts(2957,63): error TS2304: Cannot find name 'Iterable'.` This occurs with the most recent version (3.2.13) as well.

**Comment by preist** [comment]
I have the same problem.
`"@types/jquery": "^3.2.16",` and `"jquery": "^3.2.1"` in my packages.

**Comment by leonard-thieu** [comment]
This was fixed by #22766 (released as `@types/jquery@3.2.18`).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
