### ISSUE TITLE
Update to support fabric.js 2.0

### ISSUE THREAD

**Issue by HATyCEHKA** [DefinitelyTyped/DefinitelyTyped#19911]
- [x] I tried using the `@types/fabricjs` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @oklemencic, @joewashear007, @mrand01

Now missing many functions and even classes (for example, fabric.ActiveSelection).
It is impossible to develop under this version now.

**Comment by meriturva** [comment]
Hi! any news here? FabricJs 2.0 is stable now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
