### ISSUE TITLE
openui5: sap.ui `ClientModel`.`getXML()` return type void

### ISSUE THREAD

**Issue by nros** [DefinitelyTyped/DefinitelyTyped#19937]
- [ X] I tried using the `@types/openui5` package and had problems.
- [ X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @maylukas Lukas May

The definition for class `ClientModel` in file [sap.ui](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/openui5/sap.ui.d.ts) defines a getter function `getXML()` with no return type (is `void`). This might be an error.

**Comment by maylukas** [comment]
Hello @nros. This can be indeed an issue. The definitions were automatically parsed from the definition provided by SAP. Since they are not "official" they are likely to contain issues. 
I think the issues is though, that the `ClientModel` type does not define a `getXML()` getter function since this is only available on the `XMLModel`. Therefore the method should not be defined for the ClientModel in the first place.

- [https://sapui5.hana.ondemand.com/#/api/sap.ui.model.ClientModel](https://sapui5.hana.ondemand.com/#/api/sap.ui.model.ClientModel)
-  [ https://sapui5.hana.ondemand.com/#/api/sap.ui.model.xml.XMLModel]( https://sapui5.hana.ondemand.com/#/api/sap.ui.model.xml.XMLModel) (even here the return type is declared as "undefined" which is not correct I think)

Do you agree with me on this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
