### ISSUE TITLE
INgModelController should extend IController

### ISSUE THREAD

**Issue by nazarkryp** [DefinitelyTyped/DefinitelyTyped#19933]
INgModelController should extend IController as it is presumed to be parent for all other.
INgModelController cannot be used within a directive link.
INgModelController has validation methods that are ofthen required for validation
After update to latest version regression occurs

**Comment by cyrilgandon** [comment]
I will assume that you are talking about angularjs typings.

INgModelController has nothing to do with IController. INgModelController is the 4th and last argument of the link function in a directive. The signature is:

    link: function(scope, element, attrs, ngModel : INgModelController) 

That is on that instance that you can make validation stuff, see the example https://docs.angularjs.org/api/ng/type/ngModel.NgModelController#custom-control-example

**Comment by nazarkryp** [comment]
It should be,
but the 4th element is IController
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/69acc07b23b9ef174732a352fc732c363149db15/types/angular/index.d.ts#L1974

**Comment by cyrilgandon** [comment]
Oh yeah, you are totally right, the controller arguments is not always a NgModelController, my bad.
INgModelController should implements IController, I agree. You should make a PR!

**Comment by aluanhaddad** [comment]
Maybe it should be a union. Unless you are certain the object always conforms to `INgModelController` it might be best to avoid specializing the argument type.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
