### ISSUE TITLE
redux-first-router Payload should be indexable

### ISSUE THREAD

**Issue by dlindenkreuz** [DefinitelyTyped/DefinitelyTyped#19946]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Valbrand @viggyfresh 

When declaring a location reducer state as `LocationState`, I cannot access `state.location.payload.myVar` without getting an `TS2339: Property 'myVar' does not exist on type 'object'.` error. (Context: react-redux connect)

This happens because the type `Payload` is an alias of `object`. I think it should be an object with an index signature, e.g. `{ [key: string]: any }`, to account for the many use cases of `location.payload`.

**Comment by viggyfresh** [comment]
This has been a recurring point of discussion (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18562) - the short version is, even when I tried that index signature, things didn't work out (I'm now just casting `state.location.payload as MyPayload`).

Can you try locally modifying `LocationState` in your `node_modules` to have that index signature (if you're using VS Code, you can just Control/Cmd + Click on `LocationState` to open up the `index.d.ts` file for `redux-first-router`) and checking if it works? Last I recall, it didn't work

**Comment by viggyfresh** [comment]
Very interesting...I just tried it out myself and had it work out of the box. Something might have changed between TypeScript versions?

**Comment by dlindenkreuz** [comment]
Yup, works. I'm on Typescript 2.5.2.

**Comment by viggyfresh** [comment]
I'm on 2.4.2, but I think I was on 2.2 or 2.3 last time around.

I can try to put together a PR this weekend, but I'm wondering if there is a ton of value there given that `redux-first-router` is transitioning to a different API with `rudy`. @faceyspacey, what is the plan there, and how should the typings be adjusted?

**Comment by faceyspacey** [comment]
Someone mentioned moving the definitions to our own repo. it's hard for me to manage it all, especially since Im a flow guy, but I think an effort to revisit all typing issues immediately after Rudy is released (or perhaps right before it is), is what we should do. And we should just house the ts defs in the rudy repo like we do the flow defs.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
