### ISSUE TITLE
Property 'hot' is missing in type 'Module'.

### ISSUE THREAD

**Issue by vincent-cm** [DefinitelyTyped/DefinitelyTyped#19958]
version 8.0.27, 8.0.28, 8.0.29
Error: Error at .../@types/node/index.d.ts:5625:11: Class 'Module' incorrectly implements interface 'NodeModule'.
  Property 'hot' is missing in type 'Module'.
    at new UserError (.../tools/@angular/tsc-wrapped/src/tsc.ts:33:5)
    at check (.../tools/@angular/tsc-wrapped/src/tsc.ts:81:11)
    at Tsc.typeCheck (.../tools/@angular/tsc-wrapped/src/tsc.ts:168:5)
    at .../tools/@angular/tsc-wrapped/src/main.ts:154:11
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by DavidNorena** [comment]
any luck ?

**Comment by arunsn43** [comment]
Error in newer versions: 8.0.31 and older till 8.0.26 

Class 'Module' incorrectly implements interface 'NodeModule'. Property 'hot' is missing in type 'Module'

reverted to @types/node@8.0.26 to make it work..

**Comment by hoangphuong020193** [comment]
Same issue. How I can fix it? Rollback to 8.0.26?

**Comment by fullofcaffeine** [comment]
Same issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
