### ISSUE TITLE
Why is RemoteModel commented out in SlickGrid

### ISSUE THREAD

**Issue by zippy1981** [DefinitelyTyped/DefinitelyTyped#19950]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jbaldwin 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/slickgrid/index.d.ts#L1742

This has been commented out for a while. Any particular reason? I would like to use ajax fromtypescript. I guess I'm going to implement ajax outside of slickgrid and populate the grid that way.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
