### ISSUE TITLE
@types/ws: Cannot find name 'Set'.`

### ISSUE THREAD

**Issue by fttx** [DefinitelyTyped/DefinitelyTyped#19975]
- [ x] I tried using the `@types/ws` package and had problems.
- [ x] I tried using the latest stable version of tsc. 2.5.2
 - Authors: @loyd 

I get this error:
`node_modules/@types/ws/index.d.ts(158,18): error TS2304: Cannot find name 'Set'.`

my tsconfig.json

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

```

**Comment by wingtonbrito** [comment]
The only way I was able to get rid of this issue was by adding `type Set<T> = void | null | undefined | T;` inside `declare namespace jest ` . It seems they need to include all type definitions for ES2015 Collections if they planning on using them on this definition file. If we can find a way how visual studio can target the correct tsconfig.json at compile time, that might solve the issue as well. PS.  I'm using VS2017.

**Comment by asciian** [comment]
Hi @fttx. If you wouldn't mind to use `"target": "es6"` option,  this solves this issue.

**Comment by jameswilddev** [comment]
I am also having this problem.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
