### ISSUE TITLE
material-ui Avatar has no onClick - not sure how it should be added

### ISSUE THREAD

**Issue by estaub** [DefinitelyTyped/DefinitelyTyped#19988]
The [doc for Avatar](http://www.material-ui.com/#/components/avatar) notes: 

> Other properties (not documented) are applied to the _root element_.

AFAICT the definition file here (`material-ui/index.d.ts`) does not reflect this at all, and hence any use of other undocumented props causes compile errors.  In my case, I am using `onClick`, which works but doesn't compile with recent Typescript and definitions because of it being missing from the definition.

I could just provide a PR adding `onClick`, 

        onClick?: React.MouseEventHandler<{}>;

but this seems like a case where some base interface is probably called for to cover all the other relevant properties, and I don't know what should be used.  Maybe it should be the React interface for the props of the _root element_.

  - Authors: @andy-ms @mhegazy @dan-j @sheetalkamat @weswigaham

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
