### ISSUE TITLE
@types/modesl wrong callback anotations 

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/DefinitelyTyped#19986]
e.g:  events(type: 'json' | 'plain' | 'xml', events: string, cb?: () => void): void;

could be events(type: 'json' | 'plain' | 'xml', events: string, cb?: (event: Event) => void): void;

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

**Comment by neradpeter** [comment]
another one:
recvEventTimed(ms: any, cb?: () => void): void;
recvEventTimed(ms: any, cb?: (evt?: Event) => void): void;

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
