### ISSUE TITLE
[loglevel] Logger declaration conflicts with @types/handlebars' declaration

### ISSUE THREAD

**Issue by Jessidhia** [DefinitelyTyped/DefinitelyTyped#20057]
Both modules export themselves as `commonjs` declarations so it is not possible to access the types other than as ambient declarations. They do not get merged like ambient declarations, though.

For some reason, in my project, `Logger` is referring to `@types/handlebars`' version, so I have no way to refer to the `loglevel` `Logger`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
