### ISSUE TITLE
compiler not picking up type definition unless named index.d.ts

### ISSUE THREAD

**Issue by navels** [DefinitelyTyped/DefinitelyTyped#20089]
Is this by design?  I have installed `@types/dojo` which includes:

`@types/dojo/index.d.ts`
`@tpes/dojo/dijit.d.ts`

The former works fine, the latter is not picked up by the compiler and I get "TS2307: Cannot find module" errors trying to use dijit typings.  This is with ts version 2.5.2.

**Comment by andy-ms** [comment]
When you import from "dojo" we will look in `node_modules/dojo`, when you import from `dijit` we will look in `node_modules/dijit`, which doesn't exist. (See with `--traceResolution`.)
If it were written in external module style,with a different file for each `declare module`, then it would work. E.g., `dijit/BackgroundIframe` would be in a file `types/dijit/BackgroundIframe.d.ts`. Maybe those definitions should be moved?

**Comment by navels** [comment]
Thanks, I'll submit a PR soon.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
