### ISSUE TITLE
underscore js definition of where() doesnt handle arrays

### ISSUE THREAD

**Issue by pdeva** [DefinitelyTyped/DefinitelyTyped#2009]
<pre>
var powerUps:PowerUp[];
var puArr:PowerUp[] = _.where(powerUps, {name: pu.name});
</pre>

this will throw a typescript error since the return value of where() is not PowerUp[] as described in the definition file, which is clearly wrong

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
