### ISSUE TITLE
lobibox wrong type for property

### ISSUE THREAD

**Issue by matthewbierman** [DefinitelyTyped/DefinitelyTyped#20113]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lobibox/index.d.ts
Line 164: 
`  icon?: boolean;                 // Icon of notification. Leave as is for default icon or set custom string`
I think should be 
` icon?: boolean | string;                 // Icon of notification. Leave as is for default icon or set custom string`
to allow you to choose a custom icon (works in the the library)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
