### ISSUE TITLE
[@types/puppeteer] Page.evaluate has incorrect args type

### ISSUE THREAD

**Issue by ivanvanderbyl** [DefinitelyTyped/DefinitelyTyped#20198]
`Page.evaluate` accepts any type for arguments passed to evaluated functions, not just `object | ElementHandle`. Should be `...args:any[]>`

It might be a good idea to include an overloaded version of this function which indicates that an argument can be an ElementHandle which will be resolved to the real HTMLElement in the browser context.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0fb5a19d59557a682d7c1493cf7ed2c110c56c74/types/puppeteer/index.d.ts#L236-L238

**Comment by marvinhagemeister** [comment]
Awesome, thanks for spotting this! I didn't saw this and just found it by accident, because no one is mentioned in your description. If you follow the issue template, that was provided, the relevant maintainers will be notified automatically and you have a greater chance of having it fixed 🎉

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
