### ISSUE TITLE
react-redux connect

### ISSUE THREAD

**Issue by kgtkr** [DefinitelyTyped/DefinitelyTyped#20232]
# compile error
```ts
import { connect } from 'react-redux'
import * as React from "react";

declare const mapStateToProps: () => { x: number }
declare const mapDispatchToProps: () => {}
declare class Component extends React.Component<{}, {}> { }
connect(mapStateToProps, mapDispatchToProps)(Component);
```

**Comment by mDibyo** [comment]
That should give an error. You have not added the props you are deriving from the redux store state to the component.

Minimal expample that will work:
```
import { connect } from 'react-redux';
import * as React from "react";

declare const mapStateToProps: () => { x: number };
declare const mapDispatchToProps: () => {};
declare class Component extends React.Component<{ x: number }, {}> { }
connect(mapStateToProps, mapDispatchToProps)(Component);
```

**Comment by kgtkr** [comment]
This is also an error

```ts
import { connect } from 'react-redux';
import * as React from "react";

declare const mapStateToProps: () => { onEvent: () => void };
declare const mapDispatchToProps: () => {};
declare class Component extends React.Component<{ onEvent?: () => void }, {}> { }
connect(mapStateToProps, mapDispatchToProps)(Component);
```

This is inconvenient

**Comment by 19majkel94** [comment]
Yes, there is a problem with optional component props:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19989

But none of the maintainers has answered about the issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
