### ISSUE TITLE
@types/select2 not including jQuery in typescript

### ISSUE THREAD

**Issue by JoelSPendery** [DefinitelyTyped/DefinitelyTyped#20234]
- [X] I tried using the `@types/select2` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov 

I tried using the (version 4.0.41) package with (version 2.0.48) to build a Power BI custom visual using typescript, select2.js (version 4.0.1) and jQuery.js (version 2.2.4). I can compile properly without any errors thrown, but when I go to run the visual in the Power BI app, I receive the following errors in the console log:
`Select2: An instance of jQuery or a jQuery-compatible library was not found. Make sure that you are including jQuery before Select2 on your web page.`
`Uncaught TypeError: Cannot read property 'fn' of undefined`

I would have guessed that the triple slash directive at the beginning of the typing select2 file would have created an instance of jQuery and this error should not have been thrown. When I compile in VSCode, I don't receive any errors. I'm not sure if this is a bug. Any thoughts?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
