### ISSUE TITLE
Please allow for patch version

### ISSUE THREAD

**Issue by swingtempo** [DefinitelyTyped/DefinitelyTyped#20256]
It looks like definitely typed doesn't support patch versions. That would make it convenient for my team to provide patches to partners via npm, without needing to rev a minor version.  Would it be possible to support this?

**Comment by RyanCavanaugh** [comment]
This isn't possible because every published version number has to be different, so if someone just changes the comments in a file, for example, we can't re-publish `1.2.3` even if that's the version number in the header

**Comment by jayongg** [comment]
I understand.  but today we can't even have a third number. e.g. I can have:
1.0, 1.1, but not 1.1.1.

i'd like 1.1.1. Is that possible? :) I believe that last number is called the patch version number.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
