### ISSUE TITLE
react-redux no store props on the generated component

### ISSUE THREAD

**Issue by bluerface** [DefinitelyTyped/DefinitelyTyped#20275]
- [x] I tried using the `@types/4.4.40` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @thasner @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo 

I am trying to use the 'store' prop override in order to test my connected component. The code works in the test, so Im assuming that I am not making a mistake in how I am using react-redux. However the types do not recognise that the connected component has an optional 'store' prop

**Comment by mDibyo** [comment]
Hello @bluerface. Could you point us to where this behavior is documented? (Is it documented?)

**Comment by bluerface** [comment]
https://github.com/reactjs/react-redux/blob/master/docs/api.md#api
I thought it was gonna be hard to find cause it doesnt seem to be very popular, but in fact its in the second paragraph there in the documentation!

**Comment by mDibyo** [comment]
Confirmed the issue. Fix seems simple enough. Will make it over this weekend

**Comment by michaelgmcd** [comment]
@mDibyo was this ever fixed? It seems like this is still an issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
