### ISSUE TITLE
Allow "peerDependencies" in package.json

### ISSUE THREAD

**Issue by cpetrov** [DefinitelyTyped/DefinitelyTyped#20290]
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Currently, using the `"peerDependencies"` field in package.json is forbidden:

```
> dtslint types "my-plugin"

Error: .../my-plugin/package.json should not include field peerDependencies
```

Some library definitions may depend on a host package version which should not be imported twice, e.g. due to the host packages exporting duplicate definitions in this case. This can happen when the application requires a different version of the host package than the definitions of the library.

Using `"peerDependencies"` solves this problem by only allowing a single specific version of the host package to be installed.

**Comment by jfirebaugh** [comment]
The yarn maintainer explicitly says that `peerDependencies` is the correct way to solve this:

https://github.com/yarnpkg/yarn/issues/4489#issuecomment-413164280

**Comment by alloy** [comment]
As per [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39231#issuecomment-543675617), I would also like to see this being possible.

@orta Anything you think is possible here?

**Comment by orta** [comment]
I feel like _all_ types packages can basically only be installed once in the tree because a `type A` cannot exist twice in a namespace. 

That said, it might just be an oversight and no-one has sent a PR fixing it - it looks like this is an [allowlist of keys](https://github.com/microsoft/dtslint/blob/0754e730d79b64679baeb9349493d9d59048ab12/src/checks.ts#L34-L51) which don't include it. 

There's related chatter of that in here: https://github.com/microsoft/types-publisher/pull/655) in the package.json

There's related-is chatter on peer deps in here too: https://github.com/microsoft/types-publisher/pull/655

**Comment by octogonz** [comment]
@orta In https://github.com/yarnpkg/yarn/issues/6695 both @arcanis (the Yarn maintainer) and @zkochan (the PNPM maintainer) agree that DefinitelyTyped should nearly /always/ use peer dependencies instead of regular dependencies.  That thread provides a lot of technical details, as well as a specific repro.

But maybe we can boil it down to a step-by-step proof:

- **Starting point:** `@types/react-dom` depends on `@types/react`
- Suppose a project needs types for both React 15 and React 16.  As you pointed out, side-by-side versions don't make sense for ambient types (e.g. `@types/node`). But for regular imports, it's a logically sound and realistic need. Well, it's admittedly rare for the overwhelming majority of smaller projects on GitHub, but massive closed-source repos encounter side-by-side types very frequently, monorepos in particular.  And not just for React.  And not limited to side-by-side versions, but the proof is simplest if we focus on that.
- Side-by-side versions require us to think of the `node_modules` folder as a directed acyclic graph, NOT as a flat list of deps.  NPM and Yarn classic muddied the waters by [flattening the DAG into a tree](https://rushjs.io/pages/advanced/phantom_deps/), but PNPM and Yarn Plug'n'Play correctly represent the DAG.
- **The question:** When we install `@types/react-dom`, which version of `@types/react` should it get?

The **package.json** won't tell us, because it simply says:
```ts
{
    "name": "@types/react-dom",
    "version": "16.0.5",
    "dependencies": {
        "@types/react": "*",
        "@types/node": "*"
    }
}
```

Flattening won't tell us either. For example, if:

- `my-app` depends on 
  - `library@15` and 
  - `library@16`

...then typically:
- `library@15` will normally depend on both
  - `@types/react-dom@15` and
  - `@types/react@15`

...whereas:
- `library16` will depend on 
  - `@types/react-dom@16` and
  - `@types/react@16`

The right answer is to solve `"*"` by reusing the version of your ancestor in the DAG.   `library16` -> `@types/react-dom` gets version 16, whereas `library15` -> `@types/react-dom` gets 15.

The crux is that the **package.json** `dependencies` field does not impose this "inherit from DAG ancestor" meaning.  As @arcanis has repeatedly pointed out, this meaning is *confusingly suggested* by NPM's behavior, but impossible to enforce in many edge causes.  So it cannot be a guarantee.

But the `peerDependencies` field DOES have this expectation.  Its specific purpose is to defer the version selection to the DAG ancestor (`library@15` or `library@16` in my example).  All package managers agree on that.

And neatly, for ambient packages like `@types/node`, using `peerDependencies` correctly pushes up to the main project the responsibility for specifying what version of NodeJS you're building against.

`@types` dependencies should be peer dependencies.

**Comment by alloy** [comment]
To be clear, I did not take the OP to be about the many issues related to dependencies of `@types/*` on other `@types/*` packages and how those should probably be `peerDependencies`, there are plenty of threads where that’s being discussed already. However, if the OP was in fact about this, then I apologise for hijacking it and welcome the new discussion.

What I _did_ take it to mean is being able to specify `peerDependencies` that are _not_ about types, but instead about the runtime behaviour of that dependency and the types that try to describe it. For instance, in our situation the types are in `relay-runtime`, because conceptually that’s where they come from, but in reality `relay-runtime` is augmented by the `relay-compiler-language-typescript` package to emit TS types. In this case, we wanted to be able to specify that the updates to the `relay-runtime` types rely on a specific version (range) of the `relay-compiler-language-typescript` package.

**Comment by NicholasBoll** [comment]
There is currently an issue with `@types/testing-library__cypress` where that package depends on `cypress` for type definitions. Cypress handles their own types and therefore are not on DefinitelyTyped. `@types/testing-library__cypress` makes the `cypress` dependency `"*"` to attempt to not include `cypress` twice. If Cypress is listed as a dependency more than once because of module resolution conflicts, Cypress will throw an error because it tries to download a binary but will use a checksum against the wrong binary.  You really don't want Cypress more than once in your project - it is big.

Cypress recently came out with version 4, so `"*"` is now matching 4 rather than meaning "I'll work with any other version already included". If we were able to use `peerDependencies`, `"*"` would not be a resolution conflict and `cypress` would not be included more than once. Currently this is a limitation of DefinitelyTyped. It was not a limitation when the type definitions were part of the runtime source.

Usually `peerDependencies` and `devDependencies` go hand-in-hand, but neither are allowed. PR checks will fail using either. This limitation can cause issue for ambient/namespaced type definitions (Cypress also falls into this category).

https://github.com/testing-library/cypress-testing-library/issues/121

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
