### ISSUE TITLE
Should `@types/react`  be a peer dependency of `@types/react-redux`

### ISSUE THREAD

**Issue by ds300** [DefinitelyTyped/DefinitelyTyped#20299]
And similarly, should `@types/redux` also be a peer dependency of `@types/react-redux`?

I'm running into a strange bug with yarn where I get two copies of @types/react when I specify that I want to use the types for React v15

I know that's a separate issue, but I think it would go away if this library had it's dependencies on `@types/redux` and `@types/react` as peer dependencies, and I believe that's what they *should* be regardless. Indeed, `react-redux`'s package.json specifies `redux` and `react` as peer dependencies.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo, @thasner, @kenzierocks, @clayne11, @tansongyang, @nicholasboll, @mdibyo

**Comment by vkentta** [comment]
Got this same issue. Was updating project dependency `@types/react` from X to Y. Yarn resolves the existing `@types/react-redux` peer dependency `@types/react@*` separately still to X while updating the project dependency (obviously) to Y. This causes all kinds of type errors and the root for the issue was not very trivial to find (especially in my case as the project dependency that I was updating was a breaking change and some broken types were to be expected).

**Comment by npirotte** [comment]
Just got the same issue.
Got an application running on React15. It's planned to update on the long term but not on the short term.

All react dependent libraries are breaking my application typing by installing their own version of react 16.

For module itself, React is always a peerDependency, typings should follow the same conventions...

Is there a feature to do such a thing ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
