### ISSUE TITLE
Travis CI build timeout

### ISSUE THREAD

**Issue by Loghorn** [DefinitelyTyped/DefinitelyTyped#20308]
When submitting PRs for node or other definitions with a lot of dependents, the Travis CI builds fails because the job time limit is exceeded (50 minutes according to [Travis documentation](https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts) ). See for example PR #20185

**Comment by andrewstucki** [comment]
Also affects https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20694.

**Comment by Flarna** [comment]
@RyanCavanaugh @andy-ms Any idea how CI for node could be improved? Currently changing something in node definitions is a pain as we either see unrelated fails after dtlint/typescript update and/or CI timeouts.

As CI fails PRs get not merged instead requesters are instructed to fix the CI fails...
see #21253, #20542, #20695, #21012, #21003, #20720 (and maybe more)

**Comment by teppeis** [comment]
Just idea: moving to CircleCI 2.0

- faster than Travis (I feel)
- the workflow feature can parallelize job
- the timeout limit is 120 minutes (travis is 50 min)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
