### ISSUE TITLE
Underscore List methods can take null/undefined

### ISSUE THREAD

**Issue by rmehlinger** [DefinitelyTyped/DefinitelyTyped#20302]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] The authors of that type definition are cc/ @borisyankov @jbaldwin @ccurrens

Underscore's list methods generally support passing `null` or `undefined` as array arguments; they are auto-casted to the empty array `[]`. Thus, `_.union([1,2,3], undefined)` will yield `[1,2,3]`. While the wisdom of this may be open to debate, it *is* a valid use of underscore. However, [the underscore type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/underscore/index.d.ts) insist on actual `_.List<T>`s as arguments, rather than `_.List<T> | null | undefined`.

I propose adding a new `type OptionalList<T> = _.List<T> | null | undefined`, and replacing nullable List arguments with that. A similar fix is probably necessary for the object methods.

**Comment by kostia** [comment]
Any updates on this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
