### ISSUE TITLE
Wrong error type in node http server error handler

### ISSUE THREAD

**Issue by elderapo** [DefinitelyTyped/DefinitelyTyped#20327]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @parambirs, @parambirs, @RobDesideri, @tellnes, @WilcoBakker, @octo-sniffle, @smac89, @Flarna, @mwiktorczyk, @wwwy3y3, @Tyriar, @DeividasBakanas, @kjin 

```
import * as http from 'http';

const port = 3000;
const app = () => {};

http.createServer(app).listen(port); // so it throws EADDRINUSE error

const server = http.createServer(app);
server.listen(port);

server.on('error', (err: any) => {
    console.log(JSON.stringify(err, null, 4));
});
```
DefinetlyTyped defines `error` passed as first argument to callback in `server.[on/once]('error', callback);` as:
```
interface Error {
    stack?: string;
}
```
but in given example `err` is
```
Error: listen EADDRINUSE :::3000
    address:"::"
    code:"EADDRINUSE"
    errno:"EADDRINUSE"
    message:"listen EADDRINUSE :::3000"
    port:3000
    stack:"Error: listen EADDRINUSE :::3000\n    at Object._errnoException (util.js:1019:11)\n    at _exceptionWithHostPort (util.js:1041:20)\n    at Server.setupListenHandle [as _listen2] (net.js:1344:14)\n    at listenInCluster (net.js:1385:12)\n    at Server.listen (net.js:1469:7)\n    at Object.<anonymous> (/home/elderapo/nodejs/vscode-ts-node-debugging/src/index.ts:9:8)\n    at Module._compile (module.js:621:14)\n    at Module.m._compile (/home/elderapo/nodejs/vscode-ts-node-debugging/node_modules/ts-node/src/index.ts:392:23)\n    at Module._extensions..js (module.js:635:10)\n    at Object.require.extensions.(anonymous function) [as .ts] (/home/elderapo/nodejs/vscode-ts-node-debugging/node_modules/ts-node/src/index.ts:395:12)"
    syscall:"listen"
    __proto__:Object {name: "Error", message: "", constructor: , …}
```

Edit: Tested on node 8.5.0 and 8.6.0

**Comment by Flarna** [comment]
What's wrong here? Sure, the concrete Error here has other properties but it still matches the `interface Error`. An object matches an interface if all interface properties match; more properties are allowed.
In this case `ErrnoException` looks also good but not sure if this is applicable to all errors emitted by an http Server.
And as `ErrnoException` only adds optional properties it's still needed to check for presence of them.

**Comment by elderapo** [comment]
@Flarna If `err` is normal `Error` (thus it only has optional `stack` property and doesn't have properties such as code, syscall etc.) and is not casted to `any` (I think it should be avoided in TS as much as possible) [this](https://imgur.com/8LXlXPF) happens.

**Comment by Flarna** [comment]
To access the `syscall` property use of `ErrnoException` would help (and I think we should changed to use it) - but even then you have to check that `syscall` is present.
Instead of casting it to `any` you should cast to the concrete type you expect/need - after verification that this cast is valid. `any` is the last resort...
I'm not aware of any specification about which sorts of errors may be emitted by a {http.Server}. HTTP docu doesn't mention the error event at all and the base class `net.Server` just tells about Error.
In the end NodeJs is javascript and doesn't care about the definitions here so we should be careful in typing presence of properties here which are not specified anywhere.

**Comment by lonix1** [comment]
@elderapo Do you even know what `syscall` is? I can't find info on it anywhere.

Like @flarna says, none of this is documented, and yet in the express sample app, the "error" event handler has this:

    if (error.syscall !== "listen") throw error;

without explanation as to what this actually does?

**Comment by elderapo** [comment]
@lonix1, I can't remember what I needed it for. However, I managed to find it's uses [here](https://github.com/nodejs/node/search?l=JavaScript&q=syscall&type=) and [here](https://github.com/nodejs/node/search?l=JavaScript&q=syscall&type=).


If you want to learn more about it you should probably ask node/express folks.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
