### ISSUE TITLE
@types package for JSX namespace without React

### ISSUE THREAD

**Issue by gfmio** [DefinitelyTyped/DefinitelyTyped#20395]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

I'm building an application and UI library in TypeScript that is using snabbdom as a virtual DOM engine and want to support TSX syntax. Since the TypeScript compiler by default expects the JSX namespace, I get the `error TS2602: JSX element implicitly has type 'any' because the global type 'JSX.Element' does not exist.` when `noImplicitAny` is enabled in the compiler options.

To prevent this, the simplest solution would be something like this:

```typescript
declare namespace JSX {
  export type Element = any;
  export interface IntrinsicElements {
    [key: string]: any;
  }
}
```

Can I PR a typing package with this declaration? If so, is `jsx-ts` appropriate as a name?

**Comment by WorldMaker** [comment]
I've added Typescript typings directly into the latest `snabbdom-jsx` package on npm.

**Comment by gfmio** [comment]
Yes, I saw that, but then this is snabbdom specific. Snabbdom is just an example. I actually want to use `h(element, props, ...children)` differently: If `element` is a string, create a `{ element, props, children }`object, if it is a constructible function, create the corresponding object with `props` and `children` as  arguments to its constructor and, in the only other case of element being a non-constructible function, call the function directly with the arguments. This way the JSX can be utilised in a more flexible way.

For more details, see the source code below from my `h.ts`:

```
import flatten from "./helpers/flatten";

export type JsxFunction = (props: any, children: any[]) => any;

export interface IConstructor {
  new(props: any, children: any[]): any;
}

export function objectIsConstructible(obj: any): obj is IConstructor {
  return (typeof obj === "function") && ("prototype" in obj) && (obj.prototype.constructor !== undefined);
}

export function h(
    element: string | JsxFunction,
    props: any,
    ...children: any[],
  ): any {

  props = props || {};
  const flattenedChildren = flatten(children || []);

  if (typeof element === "string") {
    return { element, props, children: flattenedChildren };
  } else if (objectIsConstructible(element)) {
    return new element(props, flattenedChildren);
  } else {
    return element(props, flattenedChildren);
  }
}

export default h;
```

**Comment by WorldMaker** [comment]
The benefit to JSX types is that you get some type support for the props the library supports. In that way JSX types will likely always be library specific because Snabbdom and React, for two examples, have rather different props layouts.

I'm not sure a weak any-typed JSX types fits in DefinitelyTyped, but of course, that's just this one developers opinion. It seems more like something you'd want to bundle with your particular h.ts, if you are trying to make a library out of that.

(I'm not really seeing the advantages to your h.ts, but am curious as to motivating examples of what you are trying to do with it.)

**Comment by gfmio** [comment]
I completely understand - ideally I would like to give it better typings (if possible).

The main motivation behind this is that a JSX tag `<Tag {...props}>{ children }</Tag>` can always be understood as a triple `{ element, props, children }`, where the respective types of the `props` and `children` could either be global or dependent on `Tag`.  If `Tag` is a `string`, this representation (+ perhaps some transformation) seems the most appropriate. If `Tag` is a function, this would be something like an instance of an `Invocation` class (or it could be evaluated straight away to the result). The case of `Tag` being a class is then simply a special case, because of JavaScript's special handling of `new`. 

A specific example would be a router, which I could express as:

```TSX
const router: Router = (
    <Router>
        <IndexRoute />
        <Route />
        <Router>
             <IndexRoute />
             <Route />
        </Router>
        <NotFoundRoute />
        <NotAuthorisedRoute />
    </Router>
);
```

With this syntax, it becomes trivial to define these kind of configurations in JSX, make them user-extendible and fully flexible, without the baggage of being tied to a specific View framework, such as React or Snabbdom.

I think, configuration of any kind would make for a good use case.

**Comment by WorldMaker** [comment]
The use of JSX for DSLs like that is somewhat appealing, and I could see that Router library having very interesting types, if able. That raises the problem that it's unfortunate that in Typescript right now it's tough to multi-target JSX types within a project due to the ambient nature of the JSX namespace.

You are correct in that an immediate work around is a very weakly typed JSX namespace, but that's not a great development experience. You may want to lend your voice to some of the Typescript discussions on the subject, too.

See, for instance:

Microsoft/TypeScript#18131

Microsoft/TypeScript#15386

**Comment by gfmio** [comment]
Understood. As a possible solution, would it be possible to provide an overloaded generic `h`? Or would the TypeScript compiler not accept the typing?

I'm thinking of something like this (but I haven't tested it):

```Typescript
function h<PropsType, ChildrenType>(element: string, props: PropsType, children: ChildrenType): IJsx<PropsType, ChildrenType>;
function h<PropsType, ChildrenType, ReturnType>(element: JsxFunction<PropsType, ChildrenType, ReturnType>, props: PropsType, children: ChildrenType): ReturnType;
function h<PropsType, ChildrenType, ReturnType>(element: IConstructor<PropsType, ChildrenType, ReturnType>, props: PropsType, children: ChildrenType): ReturnType;
function h(
    element: string | JsxFunction,
    props: any,
    ...children: any[],
  ): any {
    // ...
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
