### ISSUE TITLE
@types/url-parse incorrect signature of set() method

### ISSUE THREAD

**Issue by vbodnia** [DefinitelyTyped/DefinitelyTyped#20402]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ChernenkoPaul 

Declared class `URL` contains `slashes: boolean` field which can be set by `set()` method: `set('slashes', true)` but it causes TypeScript error because `set()` signature doesn't contain `boolean` type:

```Typescript
set(property: string, value: string | object | number | undefined): URL;
```

**Comment by ChernenkoPaul** [comment]
Thanks @vbodnia , I'll fix it! I actually missed the possibility of boolean values there completely, sorry for it. 
Hope the rest worked for you? 

Until the update you can workaround the issue by using `any`, although I know it is an ill advice :)

**Comment by vbodnia** [comment]
Thanks @ChernenkoPaul , everything else works great for me!

**Comment by ChernenkoPaul** [comment]
Added a PR to DefinitelyTyped. As soon as that is reviewed and merged should work fine

**Comment by vbodnia** [comment]
@ChernenkoPaul thanks for fast answer and fix

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
