### ISSUE TITLE
react-virtualized: incomplete/wrong typings for GridCellRangeProps and Grid.defaultProps

### ISSUE THREAD

**Issue by szszoke** [DefinitelyTyped/DefinitelyTyped#20411]
- [x] I tried using the `@types/react-virtualized` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kaoDev, @guntherjh , @wasd171 

The current type definitions are incomplete for `GridCellRangeProps`.
I believe the correct type for `overscanIndicesGetter` in `Grid.defaultProps` should be `OverscanIndicesGetter` instead of `OverscanIndicesGetterParams`.

Edit: I created a pull request with the fixes.

**Comment by kaoDev** [comment]
Hey nice work you did there. The PR looks good to me and I hope it gets merged fast 😃

**Comment by szabolcsx** [comment]
@kaoDev Thanks 😃
There is another issue I noticed:
`Grid` cannot be assigned to `React.ComponentClass<GridProps>` because of `Grid.propTypes`. I get the following error:

**error TS2322: Type 'typeof Grid' is not assignable to type 'ComponentClass<GridProps>'.
  Types of property 'propTypes' are incompatible.
    Type '{ 'aria-label': Requireable<string>; autoContainerWidth: Requireable<boolean>; autoHeight: Requir...' is not assignable to type 'ValidationMap<GridProps>'.
      Types of property ''aria-label'' are incompatible.
        Type 'Requireable<string>' is not assignable to type '(object: GridProps, key: string, componentName: string, ...rest: any[]) => Error'.
          Types of parameters 'object' and 'object' are incompatible.
            Type 'GridProps' is not assignable to type 'string'.**

I think it is because the type definitions still uses `React.PropTypes` instead of the now separate `prop-types` package.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
