### ISSUE TITLE
@types 

### ISSUE THREAD

**Issue by tomitrescak** [DefinitelyTyped/DefinitelyTyped#20417]
- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andy-ms 

The ` instance(): Component<P, S>;` should be generic.

Imagine that I am trying to access instance members of the component. This is not possible.
One way of doing it it:

` instance<T>(): T | Component<P, S>;`

**Comment by andy-ms** [comment]
Not sure what package your talking about, but are you saying that `instance()` doesn't *always* return a `Component<P, S>`?

**Comment by tomitrescak** [comment]
@andy-ms sorry, it's the Enzyme package. Yes it does rerturn a Component<P, S>, but if typed like that, you have no access to instance methods

**Comment by andy-ms** [comment]
You could always use a downcast? `foo.instance() as Foo`. Trying to write it as `foo.instance<T>()` would just be a *hidden* downcast, since there's no way a function with no parameters can reliably return a `T`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
