### ISSUE TITLE
@types/googlemaps incorrectly declare the type of the "steps" property of the DirectionsStep type

### ISSUE THREAD

**Issue by DmytroLapshyn** [DefinitelyTyped/DefinitelyTyped#20420]
Hi,

v 3.29.1 declares the DirectionsStep type as

```
export interface DirectionsStep {
     /* ... skipped ... */   
     steps: DirectionsStep;
}
```
while should be

```
export interface DirectionsStep {
     /* ... skipped ... */   
     steps: DirectionsStep[];
}
```

(see https://developers.google.com/maps/documentation/javascript/reference#DirectionsStep)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
