### ISSUE TITLE
@types/storybook__react: Fix the React major version in package.json

### ISSUE THREAD

**Issue by devlato** [DefinitelyTyped/DefinitelyTyped#20425]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

Hello!
React 16 has been released recently, but in our project we're still using React 15.x (migration is planned). In package.json of `@types/storybook__react` you specified React version as any (`*`), and it causes installation of typings for React 16 internally. It causes the conflict of declarations: React 15 typings we use are conflicting with React 16 typings `@types/storybook__react`'s using.
Could you please fix the major version for the React dependency? If you don't really want to make the version fixed, I think you can publish one version for legacy React and one for the new one.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
