### ISSUE TITLE
@types/request Custom error type

### ISSUE THREAD

**Issue by vbodnia** [DefinitelyTyped/DefinitelyTyped#20436]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @soywiz @bonnici @Bartvds @joeskeen @ccurrens @lookfirst

For timeout errors module extends Error object with `connect` property, for example:
```Javascript
var setReqTimeout = function () {
       
        // ...

        if (self.req) {
          self.abort()
          var e = new Error('ESOCKETTIMEDOUT')
          e.code = 'ESOCKETTIMEDOUT'
          e.connect = false
          self.emit('error', e);
        }
      })
    }
```
So when I handle errors from module and want to use `connect` property I have to write my own extended type like that:
```Typescript
type RequestError = NodeJS.ErrnoException & { connect?: boolean };
```
Could you please provide some type for module errors? Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
