### ISSUE TITLE
[Leaflet] addHandler and constructor function

### ISSUE THREAD

**Issue by wqoq** [DefinitelyTyped/DefinitelyTyped#20470]
- [x] I tried using the `@types/leaflet` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alejo90 

I'm trying to add a handler to my Leaflet map (actually, I'm trying to manually add a Leaflet draw handler to a map without using it's toolbar), and I'm running into a syntax issue with the addHandler method in L.Map. I'm using TypeScript 2.3.

This is the line in question:
```
addHandler(name: string, HandlerClass: () => Handler): this; // HandlerClass is actually a constructor function, is this the right way?
```

Following the example [here](http://leafletjs.com/examples/extending/extending-3-controls.html), I have the following line of code:
```
this.map.addHandler('polygon', L.Draw.Polygon);
```

But that gives me the following error:
```
Argument of type 'typeof Polygon' is not assignable to parameter of type '() => Handler'.
```

If I change the addHandler line in index.d.ts to:
```
addHandler(name: string, HandlerClass: typeof Handler): this;
```
Then the error goes away, and everything works perfectly. Plus, it matches the examples in Leaflet's own documentation.

It seems like the following could be possible, too, no? That's got to be at least a little bit better than `any`.
```
export class Class {
    static extend(props: any): typeof Class;
    static include(props: any): typeof Class;
    static mergeOptions(props: any): typeof Class;
    static addInitHook(initHookFn: () => void): typeof Class;
}
```

**Comment by alejo90** [comment]
I believe you are right, changing the type of `HandlerClass` to `typeof Handler` looks like the right thing to do. About class, I'm not so sure because in the examples I recall, they call those methods with objects containing, in some instances, methods that are not present in the original class. I haven't tried it but I suspect the compiler wouldn't be so happy if we set `props` to be a `typeof` of something and people try to add new methods. Making class take a generic parameter could also be an option. Well, at least replacing `any` with `object` would be more accurate. Feel free to open a PR if you want to do it yourself or let me know and I can make the changes.

**Comment by wqoq** [comment]
You can do it. I ended up not using addHandler, so I didn't actually make any changes to pull.

**Comment by Askaholic** [comment]
@alejo90 I submitted a PR to fix this. Could someone take a look at it please? 

Another work around is to set the type of your Map object to any. This is certainly not a good solution, but you will be able to compile your code without having to modify the type definitions.

**Comment by alejo90** [comment]
@Askaholic it looks good to me. You haven't submitted a pull request, right?

**Comment by Askaholic** [comment]
@alejo90 it got merged yesterday, thanks!
