### ISSUE TITLE
@types/recharts cannot use className

### ISSUE THREAD

**Issue by kevynb** [DefinitelyTyped/DefinitelyTyped#20485]
- [x] I tried using the `@types/recharts` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @devison @remojansen

Hello,
I'm not able to specify the `className` property on the `<Bar>` element or any other, even though it will eventually get picked by the component.
Would it be possible to add this property in the types?

**Comment by rapmue** [comment]
@kevynb I think the `className` is part of a `ReactComponent` and therefor it should be possible to use `className` but I'll have a look.

@mthmulders @royxue FYI

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
