### ISSUE TITLE
Why novalidate attribute for FORM element is written in camelCase?

### ISSUE THREAD

**Issue by ndronov** [DefinitelyTyped/DefinitelyTyped#20488]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/177aab9f5b63d8ec5a481a7733c298b452731906/types/react/index.d.ts#L2663

Why `novalidate` attribute for `form` element is written in camelCase?

https://www.w3.org/TR/html5/forms.html#attr-fs-novalidate

**Comment by jimsmart** [comment]
In React, all DOM properties and attributes are camelCased.

For further details see:
https://reactjs.org/docs/dom-elements.html

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
