### ISSUE TITLE
type in lodash findKey

### ISSUE THREAD

**Issue by theGABS** [DefinitelyTyped/DefinitelyTyped#20545]
`node_modules/@types/lodash/index.d.ts line: 15221`

```
findKey<TValues, TObject>(
   object: TObject,
   predicate?: DictionaryIterator<TValues, boolean>
): string;
```
You say findKey return just string, but why you did not write more specifically

```
findKey<TValues, TObject>(
   object: TObject,
   predicate?: DictionaryIterator<TValues, boolean>
): keyof TValues;
```

So if i use something like 

`findKey({a: 5,b: 6,c: 7}, item => item === 6) `
result type be 'a' | 'b' | 'c'. 

My lodash v = 4.17.4

**Comment by aj-r** [comment]
For the same reason `Object.keys()` and `_.keys()` return `string` and not `keyof T`: the typescript interface only enforces that certain properties exist on the object. It does NOT enforce that no other unknown properties exist. So the function could theoretically return a key that doesn't exist on the object. Consider this example:

```javascript
interface A {
    x: number;
    y: number;
}
interface B {
    x: number;
}
const a: A = { x: 11, y: 22 };
const b: B = a;

const key = _.findKey(b, value => value === 22);
// key is "y", even though keyof B does not include "y"
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
