### ISSUE TITLE
puppeteer: missing $$eval method on Page

### ISSUE THREAD

**Issue by srghma** [DefinitelyTyped/DefinitelyTyped#20549]
- [x] I tried using the `@types/puppeteer` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @marvinhagemeister 

[Method defenition](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevalselector-pagefunction-args)

**Comment by marvinhagemeister** [comment]
Awesome! Thanks for spotting this one. Just made a PR that fixes this and other api changes related to the recent releases. Fingers crossed that it will be merged soon 💯

**Comment by BjornMelgaard** [comment]
Thank you very much )

**Comment by moltar** [comment]
This can be closed. $$eval method is there now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
