### ISSUE TITLE
@types/react-transition-group

### ISSUE THREAD

**Issue by bfo2ses** [DefinitelyTyped/DefinitelyTyped#20552]
I could not use it because of :
- Bad export TransitionGroup.d.ts && CSSTransition.d.ts
- require those files instead of import them in index.d.ts

I'll submit a PR :)

Thx for all the job done so far by the way !

**Comment by flushentitypacket** [comment]
I'm in the process of submitting a PR and would be happy to clean up this issue, but I'm not quite sure what it is.

Can you elaborate a bit more? What's "bad" about the exports? And why use require over import?

**Comment by flushentitypacket** [comment]
I'm off this now, but seems like there's something wrong with your setup.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
