### ISSUE TITLE
@types/webrtc Property 'deviceId' does not exist on type 'boolean | MediaTrackConstraints'

### ISSUE THREAD

**Issue by bfwg** [DefinitelyTyped/DefinitelyTyped#20569]
- [x ] I tried using the `@types/webrtc` package and had problems.

While trying to access `deviceId` within `MediaStreamConstraints.video`, I'm getting the below warning: 
```
ERROR in ...: 
Property 'deviceId' does not exist on type 'boolean | MediaTrackConstraints'.
  Property 'deviceId' does not exist on type 'true'.
```
@andy-ms

**Comment by andy-ms** [comment]
I didn't write these types, @nakakura did.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
