### ISSUE TITLE
[@types/react] React fragment issues

### ISSUE THREAD

**Issue by fongandrew** [DefinitelyTyped/DefinitelyTyped#20578]
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

----

The following fragment use-cases still don't work as of `@types/react@16.0.10`.

```tsx
class MyComponents extends React.Component<{}, {}> {
  render() {
    return ['hello', 'world', null];
  }
}
```

```tsx
class MyComponents extends React.Component<{}, {}> {
  render() {
    return this.props.children;
  }
}
```

It's a little ambiguous in the documentation as to whether fragments can include things that aren't elements or React components (https://reactjs.org/docs/react-component.html#render), but these use cases are currently possible within React itself.

**Comment by fongandrew** [comment]
Looking at the definition themselves, the issue are lines like these:

```ts
render(): Element | Element[] | string | number | null | false;
```

I'd suggest doing `render(): ReactNode` but the definition for `ReactNode` includes `{}` and `undefined`, so that might not be the way to go.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
