### ISSUE TITLE
SeamlessImmutable merge definition does not return combined types

### ISSUE THREAD

**Issue by dustinhorne** [DefinitelyTyped/DefinitelyTyped#20591]
The @types/seamless-immutable package does not return the proper combined type for the .merge method.  It instead, just returns an Immutable<T>, ignoring the type of the passed in object.  The definition instead should return the compound type as follows:
`merge<U>(part: DeepPartial<U>, config?: MergeConfig): ImmutableObject<T> & U;`

**Comment by garyyeap** [comment]
Facing same issue, could you send a pr? or I send one and will credit you.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
