### ISSUE TITLE
TS2304: Cannot find name 'ReadableStream'.

### ISSUE THREAD

**Issue by malkoto1** [DefinitelyTyped/DefinitelyTyped#20608]
- [X] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/3cc32b8e73320a5e9e4a17744236180f52c753d9)
  - Authors: @Loghorn 

Whit this commit, when using @types/whatwg-fetch: 0.0.32 the following error is given:

ERROR in <project-root>/node_modules/@types/whatwg-fetch/index.d.ts
(97,11): error TS2304: Cannot find name 'ReadableStream'.

When the version of @types/whatwg-fetch 0.0.33 the error is:

ERROR in <project_folder>/acquisition/node_modules/@types/whatwg-fetch/index.d.ts
(32,44): error TS2304: Cannot find name 'ReadableStream'.

ERROR in <project_folder>/acquisition/node_modules/@types/whatwg-fetch/index.d.ts
(102,20): error TS2304: Cannot find name 'ReadableStream'.

The two hack fixes that are possible here are:
1. Go to <project-folder>/node_modules/@types/whatwg-streams and remove the exports from the interfaces definition in the index.d.ts
2. Go to <project-folder>/node_modules/@types/whatwg-fetch and in the package.json file change the version of the whatwg-streams dependency from "*" to "0.0.3"

**Comment by nprudra** [comment]
I see similar problem with "watson-developer-console" module. 
node_modules/ibm-cloud-sdk-core/lib/content-type.d.ts(4,35): error TS2304: Cannot find name 'File'.
node_modules/ibm-cloud-sdk-core/lib/content-type.d.ts(4,42): error TS2304: Cannot find name 'ReadableStream'.

Did you find any solution?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
