### ISSUE TITLE
[@types/chart.js] wrong arguments to onClick and onHover

### ISSUE THREAD

**Issue by rmja** [DefinitelyTyped/DefinitelyTyped#20719]
- [x] I tried using the `@types/chart.js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @anuti @FabienLavocat @KentarouTakeda @larrybahr @mernen @josefpaij

The [onClick](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chart.js/index.d.ts#L156) and [onHover](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chart.js/index.d.ts#L252) callbacks should receive a mouse event as the first argument [according to the docs](http://www.chartjs.org/docs/latest/general/interactions/events.html?h=onhover). The respective lines should instead be:

```
onClick?(event: MouseEvent, active: any[]): void;
onHover?(event: MouseEvent, active: any[]): void;
```

**Comment by RetroCraft** [comment]
@rmja, can you check and see if this version works in your code?

**Comment by rmja** [comment]
@RetroCraft it doesn't. You _added_ `onHover` to `ChartOptions` instead of changing the arguments for the already existing `onHover` in `ChartHoverOptions`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
