### ISSUE TITLE
[@types/react-table] Wrong member names

### ISSUE THREAD

**Issue by blindbox** [DefinitelyTyped/DefinitelyTyped#20713]
There are quite a few members that has the wrong member names

This member should have their first letter capitalized
```ts
interface HeaderProps {
  header: TableCellRenderer; // should be Header: TableCellRenderer
}
```
This member doesn't exist. It's replaced with Cell
```ts
    interface CellProps {
        render: TableCellRenderer; // should be Cell: TableCellRenderer
    }
```
etc.

It looks like render has been replaced by the capitalized equivalent of what the render was supposed to represent i.e.

```
// from https://react-table.js.org/#props
    Cell: undefined,
    Header: undefined,
    Footer: undefined,
    Aggregated: undefined,
    Pivot: undefined,
    PivotValue: undefined,
    Expander: undefined,
    Filter: undefined,
```

- [x] I tried using the `@types/react-table` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @psakalo , @royxue

**Comment by rhonsby** [comment]
Looks like that authors have been MIA over the last month. Do you want to do this work? I'm willing to do it if not.

**Comment by blindbox** [comment]
It's been in my mind for a while to do it, but I won't due to time constraint. Go ahead and take it 👍

**Comment by Havret** [comment]
Please take a look at #21877.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
