### ISSUE TITLE
node_modules/@types/request-promise/errors.d.ts(1,21): error TS2307: Cannot find module '.'.

### ISSUE THREAD

**Issue by Jack-Works** [DefinitelyTyped/DefinitelyTyped#20715]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cglantschnig @joeskeen @AyaMorisawa

[node_modules/@types/request-promise/errors.d.ts(1,21)](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/request-promise/errors.d.ts#L1): `error TS2307: Cannot find module '.'.`
```typescript
import rp = require('.');
~~~~~~~~~~~~~~~~~~~~~^
```

**Comment by robert-franklin** [comment]
I am getting this error as well.

A workaround is to edit `node_modules/@types/request-promise/errors.d.ts` such that `import rp = require('.');` becomes `import rp = require('request-promise');`.

**Comment by NicoPennec** [comment]
@Jack-Works 
in your `tsconfig.json` file, you have to set the following compiler option:
```json
{
  "compilerOptions": {
      moduleResolution: "node",
      ...
  }
}
``` 
or  run tsc with thatt flag : `tsc --moduleResolution node`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
