### ISSUE TITLE
[@types/google-cloud__datastore] return type of runQuery should be a promise

### ISSUE THREAD

**Issue by lucacox** [DefinitelyTyped/DefinitelyTyped#20724]
From nodejs Datastore runQuery [docs](https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/1.1.0/datastore?method=runQuery): If the callback is omitted, we'll return a Promise.

function signature on line 226 of index.d.ts should be:

`runQuery(query: Query, options?: QueryOptions): Promise<QueryResult>`

**Comment by andy-ms** [comment]
Make a PR? (#20724)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
