### ISSUE TITLE
Missing module declaration in index.d.ts

### ISSUE THREAD

**Issue by visyone** [DefinitelyTyped/DefinitelyTyped#20763]
I use the library Angular with typescript.
If I try to import the library as:
import * as jTreeView from 'bootstrap-treeview'
I get the error message: "[ts] Cannot find module 'bootstrap-treeview'."
It happens because the declaration of the module is missing in index.d.ts file.
Please add the:
declare module "bootstrap-treeview" {}
in index.d.ts
Thanks

**Comment by aluanhaddad** [comment]
The current behavior is correct because _bootstrap-treeview_ is not a module it is purely a global.

The declarations introduced by the package are added to the global namespace.

If you want to import the package so that it will be added to your build by your module loader or bundler, write
```ts
import 'bootstrap-treeview';
```
Which is used to import a module for its side effects. TypeScript will not complain.

If you are using a `tsconfig.json` with an explicit `"types"` array for global packages, add `"bootstrap-treeview"`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
