### ISSUE TITLE
@types/chalk and typescript 2.6.0-rc

### ISSUE THREAD

**Issue by sanex3339** [DefinitelyTyped/DefinitelyTyped#20777]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
  - Authors: @Diullei, @Bartvds

With latest typescript 2.6.0-rc i got following error:

```
[at-loader] ./node_modules/chalk/types/index.d.ts:90:16 
    TS2714: The expression of an export assignment must be an identifier or qualified name in an ambient context. 
```

**Comment by sanex3339** [comment]
https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#arbitrary-expressions-are-forbidden-in-export-assignments-in-ambient-contexts

**Comment by alan-agius4** [comment]
I suggest you, you use the latest version of chalk without the `@types/chalk`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
