### ISSUE TITLE
support question - tell typescript to ignore compile errors using env var, etc.

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#20794]
I have this question on SO:
https://stackoverflow.com/questions/46866951/tell-ng-test-to-ignore-typescript-compile-errors

I am using `ng test` to test an Angular2 app.

I'd like to be able to tell TS to ignore compiler errors  - is there an env variable that I can use to do that? Or perhaps an option in tsconfig.json?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
