### ISSUE TITLE
[@types/puppeteer] Page.type has wrong arguments

### ISSUE THREAD

**Issue by arlampin** [DefinitelyTyped/DefinitelyTyped#20865]
`Page.type(...)` has wrong parameters, should be `(selector, text[, options])` instead of `(text[, options])`
https://github.com/GoogleChrome/puppeteer/blob/v0.12.0/docs/api.md#pagetypeselector-text-options

I think this option was changed between Puppeteer 0.11.0 and 0.12.0.

@marvinhagemeister

**Comment by marvinhagemeister** [comment]
Awesome for spotting this! I don't have the time make a PR myself (too busy with other things at the moment), but I'm happy to review any PRs to fix this.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
