### ISSUE TITLE
Restangular enhanced promises not supported

### ISSUE THREAD

**Issue by michaelbromley** [DefinitelyTyped/DefinitelyTyped#2091]
Restangular returns "enhanced" promises: https://github.com/mgonto/restangular#enhanced-promises

> Restangular uses enhanced promises when returning. What does this mean? All promises returned now have 2 additional methods and collection promises have 3.

Currently the definition file for Restangular just defines the `ng.IPromise` interface as the return value for methods that return promises.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
