### ISSUE TITLE
jasmine.d.ts v. 2.0 complete?

### ISSUE THREAD

**Issue by karlkras** [DefinitelyTyped/DefinitelyTyped#2093]
I'm attempting to migrate from jasmine 1.3 to 2.0 and the latest jasmine.d.ts appears to be missing support for adding custom matchers (formally addMatchers() )

Is this still needed or is there a another process for obtaining this functionality?

**Comment by radek-holy** [comment]
I believe that this has been fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/4235.

I just wonder whether it is really required to [manually](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/4235/files#diff-443087a7bbdcb27d0da21ebf1b396e9fR796) extend the `Matchers` interface in order to be able to call the custom matcher...
