### ISSUE TITLE
Breeze EntityManager.saveChanges has incorrect parameter type

### ISSUE THREAD

**Issue by breyed** [DefinitelyTyped/DefinitelyTyped#2095]
The last parameter of `breeze.core.EntityManager` is `errorCallback?: SaveChangesErrorCallback`, where `SaveChangesErrorCallback` is of type `(error: { XHR: XMLHttpRequest; }): void`.

The `error` parameter in `SaveChangesErrorCallback` is not actually of type `XMLHttpRequest`, but rather a type that contains `entityErrors`, `httpResponse`, and `saveResult` (see [API docs](http://www.breezejs.com/sites/all/apidocs/classes/EntityManager.html#method_saveChanges)).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
