### ISSUE TITLE
Feature request => --stream option at command line

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#20977]
As far as I know the `tsc` command will output all compile warnings/errors at the very end, buffering them up - sometimes this means users wait 10-30 seconds to get the results. Sometimes users and tools just need to know about the very first failure though! 

I think there are a lot of tools (and even end users) that would appreciate a streaming compiler where each error is written to stdout as it happens.

If this doesn't already exist, I'd recommend add a `--stream` option at the command line, something like this:

```bash
tsc --stream | tail 
```

that way a consumer can read each error as it comes in, this results in faster feedback for users.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
