### ISSUE TITLE
Specify TypeScript version in root package.json

### ISSUE THREAD

**Issue by borekb** [DefinitelyTyped/DefinitelyTyped#21066]
I'm updating some definitions and wanted to try `tsc` on it. My local TypeScript is **2.5.3** (latest stable) but the package's `package.json` evidently expects the (unreleased) **2.6** already as it produces this error:

> tsconfig.json(10,9): error TS5023: Unknown compiler option 'strictFunctionTypes'.

This was probably introduced by repo-wide patch in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20373 (the PR is so large that it's not loading for me; here's a [`.diff`](https://patch-diff.githubusercontent.com/raw/DefinitelyTyped/DefinitelyTyped/pull/20373.diff) link).

Invoking system-wide `tsc` is not a good idea anyway, I'd expect the version of TypeScript to be fixed in the root `package.json` file and having an npm script like `npm run tsc <packageName>`, similarly to what already [exists for linting](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5761cfc6f2bb9de0af9085e4f119d0ef590c500e/package.json#L21).

My current workaround is to add TS 2.6 as a dependency in that package (`types/execa` in my case) and do `npx tsc` there.

**Comment by JodiWarren** [comment]
@borekb I fixed this same issue with `npm cache clean --force`, based on this comment: https://gitter.im/Microsoft/TypeScript?at=59d846a8b20c642429d18bf4

After clearing my `node_modules` and reinstalling, `dtslint` correctly fetched all necessary Typescript versions.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
