### ISSUE TITLE
Sequelize Literal only supports one param

### ISSUE THREAD

**Issue by georgeedwards** [DefinitelyTyped/DefinitelyTyped#21078]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/sequelize` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - @codeanimal
  - @drinchev
  - @babolivier
  - @kukoo1
  - @samuelneff
 
Having an attribute with a definition in the form:

```
[fn('SUM', literal('MyQuery....', 'T')), 'True'],
```

i.e literal having the second `'T'` param - which I believe is valid sequelize, but not supported in the definitions, I think we could add another optional param to the definition on **index.d.ts** ln *5497*.

I would have done a PR, but wasn't sure what a sensible name for the param would be ( and as it is such a trivial change, I thought I might as well raise an issue).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
