### ISSUE TITLE
React PropTypes warnings when `import * from React` is used

### ISSUE THREAD

**Issue by damassi** [DefinitelyTyped/DefinitelyTyped#21102]
- [x] I tried using the `@types/react` package and had problems.
- Authors: @alloy 

When trying to fix PropTypes warnings in our app, I noticed that `import * as React from 'react'` plucks all of the exports -- including the deprecated `PropTypes` -- which triggers a warning. When replacing this with `import React from 'react'` these warnings were fixed. 

While most of the warnings in our app are now gone, in the few places that reference `@types/react` (and associated packages) the issue is still there as the typings internally use `import * as React from 'react'`.

**Comment by alloy** [comment]
The React types file doesn’t import React, can you outline what specific packages we’re using in Reaction that does import React like that? (I do know that in the React Native types we’re importing it as such, and so it would affect Emission.)

I’m not intimately familiar with the React types and the package, are there truly no downsides to importing it using the default export?

**Comment by Pajn** [comment]
This is due to how the import is transpiled and has nothing to do with the typings. The typings can not work around it either because if they exported a default export Typescript would transpile it wrong in such a way that the app would break.
A workaround you can do is make sure that either Babel is doing the transpilation from ES6 to commonjs or that you let Webpack or whatever packager you are using consume the ES6 moduels directly and then set `"allowSyntheticDefaultImports": true` in your `tsconfig` and finally replace all `import * as React from 'react'` with `import React from 'react'`

**Comment by damassi** [comment]
This makes sense 👍
