### ISSUE TITLE
AngularJS typings with TypeScript's 2.6 strictFunctionTypes don't allow extending IScope

### ISSUE THREAD

**Issue by wilg** [DefinitelyTyped/DefinitelyTyped#21160]
Creating a directive with a customized scope object is not allowed when `strictFunctionTypes` (and therefore `strict` is enabled).

This code works with `strictFunctionTypes` disabled:  

```ts
import angular from 'angular'

const m = angular.module('exampleModule', [])

interface IMyScope extends angular.IScope {
  myScopeProperty: boolean,
}

m.directive('directive', () => ({
  link(scope: IMyScope) {
    console.log(scope.myScopeProperty)
    return
  }
}))
```

But when enabled it throws:

> Property 'includes' is missing in type '() => { link(scope: IMyScope): void; }'
 
This is because `IMyScope` is not assignable to `angular.IScope`:

```ts
  link(scope: angular.IScope) {
    const x: IMyScope = scope // Type 'IScope' is not assignable to type 'IMyScope'.
                              // Property 'myScopeProperty' is missing in type 'IScope'.
  }
```

I don't think there is a way to implement this with the new strict mode without a type assertion. Perhaps the right solution is to have `IDirective` have a generic type parameter for your scope type?

----------

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @.... @diegovilar @thorn0 @calebstdenis @leonard-thieu

**Comment by chrismbarr** [comment]
I am still having a similar issue here, currently I am using `"@types/angular": "^1.6.39"` which is the latest available.

I have the following directive:

```ts
interface IEnterPressScope extends angular.IScope {
    angEnterPress: (event: JQueryEventObject) => void;
}

const enterPressDirective = (): angular.IDirective => {

    const linkFn = ($scope: IEnterPressScope, $element: angular.IRootElementService) => {
        $element.on("keydown keypress", (event: JQueryEventObject) => {
            if (event.which === 13) {
                $scope.$apply(() => {
                    $scope.angEnterPress(event);
                });
                event.preventDefault();
            }
        });
    };

    return {
        link: linkFn,
        restrict: "A", //attributes only,
        scope: {
            angEnterPress: "&"
        }
    };
};

angular
    .module("ngApp")
    .directive("angEnterPress", enterPressDirective);
```

The above code gives me the error:
```
(TS) Type '{ link: ($scope: IEnterPressScope, $element: IRootElementService) => void; restrict: string; scop...' is not assignable to type 'IDirective<IScope>'.
  Types of property 'link' are incompatible.
    Type '($scope: IEnterPressScope, $element: IRootElementService) => void' is not assignable to type 'IDirectiveLinkFn<IScope> | IDirectivePrePost<IScope> | undefined'.
      Type '($scope: IEnterPressScope, $element: IRootElementService) => void' has no properties in common with type 'IDirectivePrePost<IScope>'.
```
![image](https://user-images.githubusercontent.com/463685/34003197-ad33987c-e0c2-11e7-85ce-5a015837b9c8.png)

----------

I then tried forcing the type like this: <angular.IDirectiveLinkFn>linkFn,`, but I get a new error since I'm using an extended scope.
```
(TS) Type '($scope: IEnterPressScope, $element: IRootElementService) => void' cannot be converted to type 'IDirectiveLinkFn<IScope>'.
  Types of parameters '$scope' and 'scope' are incompatible.
    Type 'IScope' is not comparable to type 'IEnterPressScope'.
      Property 'angEnterPress' is missing in type 'IScope'.
```
![image](https://user-images.githubusercontent.com/463685/34003285-ec5422c4-e0c2-11e7-8953-612bd5d9fd55.png)

----------

And then I remembered that `IDirectiveLinkFn` takes a generic argument for the scope like this: `<angular.IDirectiveLinkFn<IEnterPressScope>>linkFn,`, but that gives yet another different error:
```
(TS) Type '{ link: IDirectiveLinkFn<IEnterPressScope>; restrict: string; scope: { angEnterPress: string; }; }' is not assignable to type 'IDirective<IScope>'.
  Types of property 'link' are incompatible.
    Type 'IDirectiveLinkFn<IEnterPressScope>' is not assignable to type 'IDirectiveLinkFn<IScope> | IDirectivePrePost<IScope> | undefined'.
      Type 'IDirectiveLinkFn<IEnterPressScope>' has no properties in common with type 'IDirectivePrePost<IScope>'.
```
![image](https://user-images.githubusercontent.com/463685/34003264-df212a0c-e0c2-11e7-921f-4e132ef09036.png)

---------

What am I supposed to do here?

**Comment by thorn0** [comment]
@chrismbarr  This type annotation is the problem:
```
const enterPressDirective = (): angular.IDirective => {
                              ^^^^^^^^^^^^^^^^^^^^
```
If you really need it, write `angular.IDirective<IEnterPressScope>` instead.

**Comment by chrismbarr** [comment]
oh that makes sense, thanks!  I added that typedef in the past due to a previous typedef issue we had.

So that fixes the issue in that case, but when a directive has something injected, now I get a new error... it never ends! 

**The Directive**
```ts
interface ISetFocusOnAttrs extends angular.IAttributes {
	angSetFocusOn: string;
}

const setFocusOnDirective = ($timeout: angular.ITimeoutService) => {

	const linkFn = (_$scope: angular.IScope, $element: angular.IRootElementService, $attrs: ISetFocusOnAttrs) => {
		$element.on("click.ang-set-focus", () => {
			$timeout(() => {
				$($attrs.angSetFocusOn).focus();
			}, 50);
		});
	};

	return {
		link: linkFn,
		restrict: "A" //attributes only
	};
};

setFocusOnDirective.$inject = ["$timeout"];

angular
	.module(CP.APP_MODULE_NAME)
	.directive("angSetFocusOn", setFocusOnDirective);
                              //^^^^^^^^^^^^^^^^^^^  --  Error here!
```

**The Error**
```
Error	TS2345
(TS) Argument of type '($timeout: ITimeoutService) => { link: (_$scope: IScope, $element: IRootElementService, $attrs: I...' is not assignable to parameter of type 'Injectable<IDirectiveFactory<IScope>>'.
  Type '($timeout: ITimeoutService) => { link: (_$scope: IScope, $element: IRootElementService, $attrs: I...' is not assignable to type '(string | IDirectiveFactory<IScope>)[]'.
    Property 'push' is missing in type '($timeout: ITimeoutService) => { link: (_$scope: IScope, $element: IRootElementService, $attrs: I...'.
```

-------

Basically everything with the typedefs is fine with your suggestion of removing the unnecessary `angular.IDirective` typedef, but this causes typescript to think that it no longer matches this typedef when services are injected.

So, to me it seems as if I either need to go back to forcing the type on the `link` (only when I have services injected into a directive), or I need to do something else that I'm not yet understanding.

**Comment by chrismbarr** [comment]
Update, this compiles file, but I don't love having to force the type on the `link` in the directive return.

```ts
interface ISetFocusOnAttrs extends angular.IAttributes {
    angSetFocusOn: string;
}

const setFocusOnDirective = ($timeout: angular.ITimeoutService): angular.IDirective<angular.IScope> => {

    const linkFn = (_$scope: angular.IScope, $element: JQLite, $attrs: ISetFocusOnAttrs): void => {
        $element.on("click.ang-set-focus", () => {
            $timeout(() => {
                $($attrs.angSetFocusOn).focus();
            }, 50);
        });
    };

    return {
        link: <angular.IDirectiveLinkFn<angular.IScope>>linkFn,
        restrict: "A" //attributes only
    };
};

setFocusOnDirective.$inject = ["$timeout"];

angular
    .module(CP.APP_MODULE_NAME)
    .directive("angSetFocusOn", setFocusOnDirective);
```

I'm going to have to stick with this unless I learn of a better way to do this.

**Comment by thorn0** [comment]
This time the problem is `$attrs: ISetFocusOnAttrs`. In TS 2.6+, function parameters are contravariant when `strictFunctionTypes` is set to `true`. However, `ISetFocusOnAttrs` is a subtype of `angular.IAttributes`, not a supertype. The workaround would look like this:
```ts
const linkFn = (_$scope: angular.IScope, $element: JQLite, $attrs0: angular.IAttributes) => {
	const $attrs = $attrs0 as ISetFocusOnAttrs
	// ...
};
```
Seems like one more type argument should be added to `IDirective`. A PR is welcome. :hammer_and_wrench:

**Comment by chrismbarr** [comment]
ok makes sense & that's good info - thanks!

The changes needed for that PR are a little above my head, so I'll have to leave that for someone else!

**Comment by Guysbert** [comment]
I had the same problem you had @chrismbarr.
I solved it this way:

My interface:
```javascript
interface MyCustomScope extends IScope {
   ...
}
```

My Directive class declaration:
```javascript
export class MyCustomDirective implements ng.IDirective<MyCustomScope> {
  ...
```

My link function:
```javascript
link = ($scope: MyCustomScope): IDirectiveLinkFn<IScope> => () => {
  ...
}
```
