### ISSUE TITLE
@types/box2d is not exported as a module / we weren't able to map it to box2dweb

### ISSUE THREAD

**Issue by itchingpixels** [DefinitelyTyped/DefinitelyTyped#21182]
Hi @jbaldwin ,

We'd love to use the box2d ts type definitions, but bumped into two potentially, connected problems:

- when importing the type definitions with the following code: `import * as Box2D from 'box2d'`, we get the following error:
`'File '/node_modules/@types/box2d/index.d.ts' is not a module.'`
It seems like there are namespaces defined but they're not exported.

- box2dweb is not defined as a dependency for this package, and we're not sure how we can map it to the imported module.

Any help with these would be greatly appreciated!

**Comment by srepollock** [comment]
Is there any fix with this? Or perhaps another physics engine (although I really would like to use box2d)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
