### ISSUE TITLE
Type ShallowRendererProps missing property disableLifecycleMethods

### ISSUE THREAD

**Issue by zelliott** [DefinitelyTyped/DefinitelyTyped#21203]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/enzyme` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @MarianPalkus @NoHomey @jwbay @huhuanming 

If you do not mention the authors the issue will be ignored.

I'm using enzyme version 3.1.0, @types/enzyme version 3.1.3, and enzyme-adapter-react-16 version 1.0.3.  According to https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#lifecycle-methods, the `ShallowRendererProps` options should have a property `disableLifecycleMethods`.  In the current version of @types/enzyme, this property is not defined on the `ShallowRendererProps` definition.  This results in a Typescript compilation error.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
