### ISSUE TITLE
[type request] add types for localforage 

### ISSUE THREAD

**Issue by championswimmer** [DefinitelyTyped/DefinitelyTyped#21237]
https://www.npmjs.com/package/localforage 

heavily used library.

**Comment by aluanhaddad** [comment]
It appears that this library comes with types. They are unfortunately not UMD style, but they will work. https://github.com/localForage/localForage/blob/master/typings/localforage.d.ts

**Comment by Elephant-Vessel** [comment]
Is @types only for type definitions where none is provided by the target library? It would be convenient if all type definitions are aggregated in @types in a unified manner.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
