### ISSUE TITLE
@types/box2d worldAABB.maxVertex and worldAABB.minVertex are not defined

### ISSUE THREAD

**Issue by chrispytoes** [DefinitelyTyped/DefinitelyTyped#21249]
- [x] I tried using the `@types/box2d` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jbaldwin @andy-ms 

I am creating a world using: `this.b2World = new b2Dynamics.b2World(new b2Math.b2Vec2(0, 0), true);`

My code compiles, but JS is giving this error:
```
b2BroadPhase.js:80 Uncaught TypeError: Cannot read property 'x' of undefined
    at klass.initialize (b2BroadPhase.js:80)
    at new klass (prototype-1.6.0.2.js:48)
    at klass.initialize (b2World.js:50)
    at new klass (prototype-1.6.0.2.js:48)
    at new Game (game.class.ts:18)
    at Object.189../modules/game.module (main.ts:3)
    at s (_prelude.js:1)
    at e (_prelude.js:1)
    at _prelude.js:1
```
The `game.class.ts:18` in the stack trace is the part where I construct the world as shown above. I haven't done anything else fancy, just used the import statements provided and constructed the world.

I did some digging and `worldAABB.maxVertex` and `worldAABB.minVertex` are not defined in the compiled JS.

**Comment by andy-ms** [comment]
Pull requests accepted.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
