### ISSUE TITLE
@types/redux-form Field Component Prop

### ISSUE THREAD

**Issue by andigu** [DefinitelyTyped/DefinitelyTyped#21240]
- [x] I tried using the `@types/redux-form` package and had problems.
- [x] I tried using the latest stable version of tsc.
- [x] I have a question that is inappropriate for StackOverflow.
- [x] Authors: @CarsonF, @aikoven , @LKay , @bancek

The component prop on Field has a signature that doesn't match the docs:
`component?: ComponentType<P> | "input" | "select" | "textarea"`, and `P` is `GenericFieldHTMLAttributes` by default, but the docs suggest that `P` should be `WrappedFieldProps`. Am I using Field incorrectly?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
