### ISSUE TITLE
[@types/react-redux] @types/react as peerDependency

### ISSUE THREAD

**Issue by dulmandakh** [DefinitelyTyped/DefinitelyTyped#21312]
Can we move @types/react from dependency to peerDependency?

I'm experiencing a issue where I have react@16 and it's typings, but types/react-redux installs react@15 typings as dependency which results many compiler errors and red underlines in VS Code.

I think that we can solve the issue using @types/react as peerDependency.

@tkqubo @thasner @kenzierocks @clayne11 @tansongyang @nicholasboll @mdibyo @pdeva

**Comment by tansongyang** [comment]
Are you using yarn by chance? If so, I think I've seen the same issue. My workaround has been adding this to `tsconfig.json`:

    "paths": {
      "react": ["node_modules/@types/react"]
    }

I got this idea from the discussion for [another issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18484#issuecomment-319968097)

**Comment by AndrewKiri** [comment]
I had similar issue today with react and its typings, whereas react that I had was `v16` but @types/react installed `v15`. Manually running `npm install @types/react@16.0.2` solved the issue with types mismatch

**Comment by peleteiro** [comment]
👍

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
