### ISSUE TITLE
@types/react-recaptcha : Cannot import using ES6 syntax

### ISSUE THREAD

**Issue by olivierr91** [DefinitelyTyped/DefinitelyTyped#21313]
How do you import react-recaptcha using ES6 import syntax?

I tried:
```
import Recaptcha from 'react-recaptcha';
import {Recaptcha} from 'react-recaptcha';
import * as Recaptcha from 'react-recaptcha';
```

I had to modify `index.d.ts` to make it work:

`export default class Recaptcha` instead of `declare class Recaptcha`

Is this something I do wrong or is it a problem with the type definition?

**Comment by orobert91** [comment]
#22055

**Comment by zzanol** [comment]
close, fixed in PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22519

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
