### ISSUE TITLE
[@types/redux-form] Missing definition for initialize

### ISSUE THREAD

**Issue by tonoslav** [DefinitelyTyped/DefinitelyTyped#21315]
- [x] I tried using the `@types/redux-form` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @carsonf @aikoven @LKay @bancek @alsiola

## Situation
I am using this [initiliaze](https://redux-form.com/7.1.2/docs/api/actioncreators.md/#-code-initialize-form-string-data-object-keepdirty-boolean-options-keepdirty-boolean-keepsubmitsucceeded-boolean-code-) action creators

I have installed latest version of types for redux-form and started to move my project into typescript

## Use
```javascript
import { SubmissionError, initialize } from 'redux-form/immutable'
...
yield put(initialize(formSelector, formData))
...
```

## Problem
![image](https://user-images.githubusercontent.com/3399021/32502618-7f6693bc-c3db-11e7-972a-69bd190c4a9c.png)
```console
Module '".../node_modules/@types/redux-form/immutable/index"' has no exported member 'initialize'.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
