### ISSUE TITLE
[@types/bluebird]: type loosing

### ISSUE THREAD

**Issue by maximelkin** [DefinitelyTyped/DefinitelyTyped#21338]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @lhecker 

Maybe we can reduce type loosing for map/reduce etc by little trick

```
declare class Bluebird<T> {
    then<V>(callback: () => V[]): BluebirdArray<V>
    then<V>(callback: () => V): Bluebird<V>
}

declare class BluebirdArray<T> {
    private constructor()
    then<V>(callback: () => V[]): BluebirdArray<V>
    then<V>(callback: () => V): Bluebird<V>
    map<V>(callback: () => V): BluebirdArray<V>
}

declare const t: Bluebird<string>

//expecting error on last map
t.then(() => [12]).map(() => 1).then(() => '12').map(() => 21)
```
But instead we receive problems with `new Bluebird((res)=> res([1,2])`

**Comment by lhecker** [comment]
@maximelkin While your proposal would make the library safer to use, it would also make the typings incorrect, since bluebird _does_ allow you to pass non-array values to a map-continuation. While it does throw an error in that case it's still technically possible.

But don't get me wrong: I'm personally all for making bluebird safer to use even if it makes the typings slightly incorrect here and there.

My basic gripe with your idea though is, that it's basically circumventing what generics are supposed to do already. I'd like to be able to just write:

```ts
declare class Bluebird<T> {
    then<U>(callback: () => U[]): Bluebird<U[]>;
    then<U>(callback: () => U): Bluebird<U>;
    // No .map definition here!
}

interface Bluebird<T[]> {
    // Because it's only defined here for Bluebird<T[]>!
    // It even hints the item type T automatically now!
    map<U>(mapper: (item: T) => U): Bluebird<U[]>;
}
```

But sadly that's currently not possible. I believe https://github.com/Microsoft/TypeScript/issues/17636 is tracking something similar to this issue.

Furthermore this would complicate/"uglify" writing code: You usually don't want to taint all your functions with a `BluebirdArray` type etc. since such an annotation would be viral up the call chain, similar to async/await.

If you combine those reasons with the fact that it's "technically possible to call .map() on non-array promises" I'm personally not really in favor of solving this issue in the proposed way. I'd rather wait for there to be an official solution for generic overloading/specialization from TypeScript.

**Comment by maximelkin** [comment]
@lhecker thank for your response
I agree with your position, so i close issue
