### ISSUE TITLE
[@types/angular]: IQService.reject not usable

### ISSUE THREAD

**Issue by dartzki** [DefinitelyTyped/DefinitelyTyped#21333]
Since @noomorph [commit from last february](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/352ee03af80d903738241bb89422e7ece88212e0) IQService.reject returns `IPromise<never>`. This makes the following use case unusable:
```ts
let someString: string = "abc";
let p = $q.resolve()
  .then(() => {
    if (someString === "abc") {
      return "yeah";
    } else {
      return $q.reject("nay");
    }
  });

let stringPromise: IPromise<string> = p; //<-- type error: Type 'IPromise<IPromise<never> | "yeah">' is not assignable to type 'IPromise<string>'
```

Afaik returning `$q.reject(...)` is the correct way to reject a promise and imo `p` in the above example should be assignable to type `IPromise<string>`, since the reject does not change the type of the success case.

My best Idea is to return the return type of `IQService.reject` back to `IPromise<any>` - any better ideas?

**Comment by noomorph** [comment]
It's a pity to see quite a straight forwards case not running as expected.

The problem here lies not in `IQService.reject` itself, I suppose, rather in a tricky definition of `then`:

```typescript
then<TResult>(successCallback: (promiseValue: T) => IPromise<TResult>|TResult, errorCallback?: null | undefined, notifyCallback?: (state: any) => any): IPromise<TResult>;
```

Thus, if you rework your code this way (namely, help `.then<T>` signature to figure things out by passing explicit `.then<string>`), it should work well enough:

```typescript
let someString: string = "abc";
let p = $q.resolve()
  .then<string>(() => {
    if (someString === "abc") {
        return "yeah";
    } else {
        return $q.reject("nay");
    }
    });

let stringPromise = p;
```

I am wondering if it's possible to fix the inference in the signature, however... but it's beyond my capabilities in time. I'm sorry to say that, but I need to meet deadlines on another project :(

In your shoes, I would have added up your case to the test suite and would have been playing with the signatures till it works out together with the previous test cases. It might be a bit risky and time
-consuming — someone other's code may break and you'll have to sit with them and work around their issues. So, I don't know what to advise.

Hope that helps.

**Comment by dartzki** [comment]
Thanks, @noomorph 
I didn't think to pass the generic type directly...
I'll see if I can make some time, but it's not a very pressing issue for me either...

**Comment by thorn0** [comment]
@dartzki Please reopen this issue as it hasn't been fixed yet.

BTW, the type definitions for the built-in promises suffer from the same problem: https://github.com/Microsoft/TypeScript/issues/17315

**Comment by dartzki** [comment]
@thorn0 setting the generic type explicitly is a valid use of the language features and therefore a correct fix. For that reason I closed the issue.

**Comment by thorn0** [comment]
It's sort of against the overall spirit/ideology of TypeScript according to which type inference should preferred over explicit type annotations as much as possible. Every new version of TS brings features that allow us write fewer explicit annotations. Same with DefinitelyTyped - if a newer version of the type definitions for some library makes you write more explicit annotations, it's a regression.

**Comment by shihabuddin** [comment]
The following code gives type error after this change. It was working fine before this change.
`$q.when('a').then(s => s ? this.$q.when('b') : undefined);`
To fix this I had to add an explicit generic type.
`$q.when('a').then<string|undefined>(s => s ? this.$q.when('b') : undefined);`
Doesn't it go against the intention of this issue (avoid explicit generic type)?

**Comment by thorn0** [comment]
@shihabuddin Are you sure you used that change? It's not on npm yet.

Anyways, this situation (different types returned from a `then` callback) is far less common then using `$q.reject` and isn't supported by the definitions for the native promises (lib.d.ts) neither. 

With `strictNullChecks` ([playground](http://www.typescriptlang.org/play/#src=Promise.resolve('a').then(s%20%3D%3E%20s%20%3F%20Promise.resolve('b')%20%3A%20undefined)%3B)):
```ts
Promise.resolve('a').then(s => s ? Promise.resolve('b') : undefined);
```
BTW, what are you compiler settings and TS version?

**Comment by shihabuddin** [comment]
Basically, this happens when the `then` callback returns either a promise or `undefined` based on a condition. It may be less common than `$q.reject`, but it's not very uncommon. One use case we have is that we send a HTTP request to one URL, then from the response we find another URL and send another HTTP request. If the second URL is not found, we return `undefined`.

```
const url1 = ...
$http.get(url1).then(response => {
  const url2 = findURL(response);
  return url2 ? $http.get(url2) : undefined;
});
```

tsconfig.json:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "sourceMap": true,
    "noEmit": true,
    "noImplicitReturns": true,
    "strictNullChecks": true,
    "declaration": true,
    "stripInternal": true
  },
  "include": [
    "app/**/*.ts"
  ]
}
```

TypeScript version: `2.6.1`

**Comment by thorn0** [comment]
Yes, for some reason (cache obviously) `npm install @types/angular` didn't install the latest version for me. Which version of `@types/angular` did your code compile fine with?

**Comment by shihabuddin** [comment]
The version `1.6.41` of `@types/angular` worked fine.

**Comment by thorn0** [comment]
What was the type of the returned promise? For `$q.when('a').then(s => s ? $q.when('b') : undefined);` v1.6.41 gives me `angular.IPromise<string | angular.IPromise<string> | undefined>`. That's not what is called "works fine".

**Comment by shihabuddin** [comment]
I see, I get the same type. It should have been `angular.IPromise<string | undefined>`.

I did't notice that because I had explicit type defined on the next `then` callback argument:
`$q.when('a').then(s => s ? $q.when('b') : undefined).then((s1?: string) => {...});`

On `v1.6.42`, the type of `$q.when('a').then<string | undefined>(s => (s ? this.$q.when('b') : undefined))` is `angular.IPromise<string | undefined>`.

So, I agree, it wasn't "working fine" on `v1.6.41`. On `v1.6.42` I just need to move the explicit type to a different place.
