### ISSUE TITLE
storybook__react's @types/react dependecy is outdated and clashes with current ver types

### ISSUE THREAD

**Issue by burabure** [DefinitelyTyped/DefinitelyTyped#21345]
- [x] I tried using the `@types/storybook__react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @joscha 

---

`@types/storybook__react` has an outdated dependency on `@react/types` which makes it clash with my project's types that are correct according to the newest `@types/react`, I had to remove the `@types/storybook__react` meanwhile because it's impossible to properly define types for components otherwise.

**Comment by joscha** [comment]
Can you create a PR to fix it @burabure?

**Comment by burabure** [comment]
@joscha I'd like to help, but I don't have the knowledge or time right now =(

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
