### ISSUE TITLE
stripe-v3

### ISSUE THREAD

**Issue by jimmyff** [DefinitelyTyped/DefinitelyTyped#21343]
I think the stripe-v3 definitions may be a little out of date, the following methods are not available:

```
stripe.retrieveSource()
stripe.paymentRequest()
```
https://stripe.com/docs/stripe-js/reference

Authors: @a904guy @ejsmith @amritk @adamcmiel @jleider @galuszkak

**Comment by galuszkak** [comment]
@jimmyff will look into that. 👍

**Comment by techieshark** [comment]
I notice that `paymentRequest` is provided in `@types/stripejs`. @RobinvanTienhoven

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f01a82e71461d48c499cceabd220e606e7d768e4/types/stripejs/index.d.ts#L51

Is `@types/stripejs` superseding `@types/stripe-v3`?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
