### ISSUE TITLE
[@types/react-select] forked version differs from npm-version

### ISSUE THREAD

**Issue by misantronic** [DefinitelyTyped/DefinitelyTyped#21340]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

I have an issue with the typings of the props `valueComponent` and `optionComponent` with the newest version of typescript (2.6.1).
Thus I forked DefinitelyTyped and saw that this has already been fixed. 
How come the npm-version differs from the master-repo and how do I install the correct version? (mine is `^1.0.59`)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
