### ISSUE TITLE
definition for @types/webdriverio log() incorrect?

### ISSUE THREAD

**Issue by mileshenley** [DefinitelyTyped/DefinitelyTyped#21358]
I think the definition for log() in index.d.ts for @types/webdriverio might be incorrect.

Currently it is:
```
        /** @deprecated */
        log(type: LoggingPreferences): Client<RawResult<LogEntry[]>> & never;

        /** @deprecated */
        log<P>(type: LoggingPreferences): Client<P>;
```

I believe it should actually be:
```   
        /** @deprecated */
        log(type: string): Client<RawResult<LogEntry[]>> & never;

        /** @deprecated */
        log<P>(type: string): Client<P>;
```
As when I call this:
`browser.log({browser: 'INFO'})`

i get the following error at runtime:
`number or type of arguments don't agree with log command`

http://webdriver.io/api/protocol/log.html suggests it should a string and when i manually change the definition as shown above and run:
`    browser.log('browser')`

it seems to work. so i think the solution is as simple as just changing the interface to expect a string, but i am not sure if there is something else i am missing?

@monolithed @nmalaguti @timbru31 @fsmedberg-tc Thoughts?

**Comment by timbru31** [comment]
Hi there @mileshenley and sorry for my late response.
You are correct, the current typings are indeed wrong.

I suggest the whole `interface LoggingPreferences` and  `type  LoggingPreferenceType` can be removed, since the (old and deprecated) JSONWireProtocol wiki pages states, that even other logs can be requested (e.g. performance), for reference see: https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#log-type

The typings `logTypes()` is wrong, too. (should return a string[] as per http://webdriver.io/api/protocol/logTypes.html)

Are you able/willing to do a PR? 👍

**Comment by uniqueiniquity** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32490
