### ISSUE TITLE
Unable define push callback method.

### ISSUE THREAD

**Issue by Prabuganesan** [DefinitelyTyped/DefinitelyTyped#21361]
If you know how to fix the issue, make a pull request instead.

I have used push plugin. When i try to define call back methods for push action the following error occured

[ts] Argument of type '"accept"' is not assignable to parameter of type 'PushEvent'.

[ts] Argument of type '"reject"' is not assignable to parameter of type 'PushEvent'.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
