### ISSUE TITLE
[Parsimmon] Question about class-like behaviors around Parser and Parsimmon

### ISSUE THREAD

**Issue by karak** [DefinitelyTyped/DefinitelyTyped#21396]
Hi, types/parsimmon maintainers, @Bartvds, @mizunashi-mana, @bcherny, @bvanreeven, @leonard-thieu

Recently, I worked with Parsimmon, and met unreasonable compile errors when touching `prototype` like this:

```typescript
Parsimmon.prototype.foo= function (p: Parsimmon.Parser<T>) {
   return this.then(p); // cause compile error!
   //return (this as Parsimmon.Parser<T>).then(p); // work-around
}
```

By mechanical translating, `Parsimmon` __is__ a class with a known constructor trick, but `Parser` is not, but just an factory method of `Parsimmon` like:

```typescript
class Parsimmon<T> {
  constructor(fn: ...);

  then();
  many();
  // and the other methods in current Parser<T>.
}
function Parsimmon<T>(fn: ...): Parsimmon<T>;

namespace Parsimmon {
  any;
  seq();
  // and the other namespace members.

  function Parser<T>(fn: ...): Parsimmon<T>;
}

export = Parsimmon;
```

So, we need more idea to handle the pretending of `Parser` as virtual alias type of `Parsimmon`.

Could you help?

Note I admit this is an edge case which you can avoid easily, and fixing might break backward compatibility.

Thanks.

# Original codes are here: [ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/88f8173559f8b1de1e3aa6658b5a30b5cba30442/types/parsimmon/index.d.ts)/[js](https://github.com/jneen/parsimmon/blob/master/src/parsimmon.js)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
