### ISSUE TITLE
promise.finally type definitions

### ISSUE THREAD

**Issue by jgerstle** [DefinitelyTyped/DefinitelyTyped#21398]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/core-js` package and had problems.
- Authors: @andy-ms 

I am trying to use promise.finally in typescript this doesn't really seem possible with core-js. I imported the polyfill and installed the type definitions, but it doesn't fix the compile issues that I have. It doesn't look like the core-js type definitions includes one for promise.finally

**Comment by andy-ms** [comment]
You can a pull request editing `types/core-js/index.d.ts` adding:
```ts
interface Promise<T> {
    finally(...): ...; // fill this in
}
```
Just like `Number` and `String` are augmented.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
