### ISSUE TITLE
@types/three is missing WebGLUTils (THREE.WebGLUTils)

### ISSUE THREAD

**Issue by DomDumont** [DefinitelyTyped/DefinitelyTyped#21409]
Hi all, it seems THREE.WebGLUTils is not exposed through @types.
I'm trying to use/port this code ( https://github.com/spite/THREE.UpdatableTexture ) in typescript.

By the way, if someone has a better option to load small texture blocks into a bigger one, i'm interested ;-)

- Authors: @gyohk @florentpoujol @SereznoKot @omni360 @ivoisbelongtous @piranha771 

Thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
