### ISSUE TITLE
[@types/ramda] - R.adjust function is missing declare

### ISSUE THREAD

**Issue by wenkanglin** [DefinitelyTyped/DefinitelyTyped#21466]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/ramda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @donnut @mdekrey @mrdziuban

Follow the doc of [ramda#adjust](http://ramdajs.com/docs/#adjust), there is an example, I try it with `@types/ramda`:
```typescript
import * as R from 'ramda';

R.adjust(R.add(10), 1, [1, 2, 3]);     //=> [1, 12, 3]
R.adjust(R.add(10))(1)([1, 2, 3]);     //=> [1, 12, 3]
```

But here is a ts mistake:
```
TS2554:Expected 2-3 arguments, but got 1
```

Because in [@types/ramda](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/index.d.ts#L176), it miss complete declare about `R.adjust`, it can be curried. These code should be declared:
```typescript
adjust<T>(fn: (a: T) => T): (index: number, list: T[]) => T[];
adjust<T>(fn: (a: T) => T): (index: number) => (list: T[]) => T[];
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
