### ISSUE TITLE
[@types/node] Crypto hash.toString parameters 0

### ISSUE THREAD

**Issue by fedgrant** [DefinitelyTyped/DefinitelyTyped#21464]
- [X] I tried using the `@types/nodesrc/hash.ts(10,13): error TS2322: Type 'string | Buffer' is not assignable to type 'Buffer'.
  Type 'string' is not assignable to type 'Buffer'.` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @parambirs, @tellnes 

```
import * as crypto from 'crypto';

function nodeHash(value) {
  const hashStream = crypto.createHash('sha512');
  hashStream.write(value);
  hashStream.end();
  return new Promise((resolve, reject) => {
    hashStream.on('readable', () => {
      const data = hashStream.read();
      if (data) {
        resolve(data.toString('hex')); //error here
      }
    });
  });
}

export default nodeHash;
```
I have the above code block. I am getting the error `src/hash.ts(12,17): error TS2554: Expected 0 arguments, but got 1.` I looked through the index.d.ts and it looks like the Hash interface  extends the ReadableStream interface which has a read property that returns either a string or a Buffer which then as a toString property which accepts a possible encoding parameter. As I was typing up this I realized that I could in theory declare my data variable as a Buffer like below.
```
hashStream.on('readable', () => {
      const data: Buffer = hashStream.read();
``` 
But then I get the error
```
src/hash.ts(10,13): error TS2322: Type 'string | Buffer' is not assignable to type 'Buffer'.
  Type 'string' is not assignable to type 'Buffer'.
```
Not sure what to do next, any advice would be appreciated.

**Comment by andnp** [comment]
Could write some sort of type guard.
```
function isBuffer(x: string | Buffer): x is Buffer {
    return x instanceof Buffer;
}
```

or could do it inline:
```
const readData = hashStream.read();
const data: Buffer = readData instanceof Buffer ? readData : new Buffer(readData);
```

**Comment by fedgrant** [comment]
@andnp you're way worked. I started looking into other ways to achieve the same thing. Ended up with 
```
const data: Buffer = (hash.read() as Buffer);
```
I still don't understand why I would have to cast the function if I tell it the compiler that data is a Buffer.

**Comment by andnp** [comment]
Well no. This is now lying to the compiler about what `data` is. Unless you know with complete confidence that `hash.read()` will return a `Buffer`, this forces the compiler to ignore the `| string` part of the type. So now if `hash.read()` returns a `string` you will have a bug in the generated javascript. If you go with the type guard I have above, both the typescript types will be happy and the javascript will be bug-free.

---

When you do something like this:
```
const data: string = 'hi';
```
You are telling the compiler "I expect data to be a string".
When this happens:
```
const data: string = 1;
```
You tell the compiler: "I expect data to be a string" and the compiler says back: "well it isn't, so this is wrong".
Finally in this scenario:
```
const data: string = 1 as string;
```
You tell the compiler: "I expect data to be a string, also pretend that 1 is a string", and the compiler says: "sure, you're the boss."

That final scenario is what you're suggesting in your last post.

---

The reason, then that any of this is necessary is that `hash.read()` can return a `Buffer` or it can return a `string`. A `string` cannot be turned into a `Buffer` so:
```
const data: Buffer = 'hello world';
```
is nonsense. This is why
```
const data: Buffer = hash.read();
```
must also not work. What if `hash.read()` returned a `string` suddenly? Now your generated javascript code may not work because `data.toString('hex')` is not a function on `string`.

---

By using a type guard and testing if the return is a `Buffer`, you can create a `Buffer` out of a string in the case that `hash.read()` actually returns a string. This means your typescript code will correctly know that `data` is a `Buffer` and that `data.toString('hex')` will work in your generated javascript. always.

---

Of course, I may be entirely interpreting your question incorrectly and you may be inferring that the typings for `hash.read()` are wrong and that `hash.read()` can only ever return a `Buffer` and `string` is not a possible type.

**Comment by fedgrant** [comment]
Originally I thought there might have been a issue, but I see now that my understanding of how the type declaration works was the issue. The declaration is meant to be a discrete type of value not a possible type of value. Thanks for the explanation, this makes a lot more sense now.
