### ISSUE TITLE
[@types/react-slick] Properties missing in CustomArrowProps

### ISSUE THREAD

**Issue by cheeZery** [DefinitelyTyped/DefinitelyTyped#21473]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-slick/index.d.ts#L11

CustomArrowProps contain more properties than `className`, `style`, and `onClick`.

In [arrows.js](https://github.com/akiran/react-slick/blob/master/src/arrows.js#L21) there's also `key` and `data-role` (same in NextArrow). If you provided a custom arrow with prevArrow (or nextArrow), `currentSlide` and `slideCount` are added additionally.

So imo the CustomArrowProps interface should be declined as

    export interface CustomArrowProps {
      key?: string;
      "data-role"?: string;
      className?: string;
      style?: React.CSSProperties;
      onClick?: React.MouseEventHandler<any>;
      currentSlide?: number;
      slideCount?: number;
    }

**Comment by r3nya** [comment]
Hey @cheeZery!
Yeah, good catch. Will fix it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
