### ISSUE TITLE
@types/jsdom@11.0.4 assumes existence of DOM lib.d.ts types

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DefinitelyTyped/DefinitelyTyped#21517]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21235
https://github.com/kevipapo1/DefinitelyTyped/commit/d6ac21e95f12e3617e92176258d523bba910aa0a

If compiled a project without the built-in `lib.d.ts`, such as with projects not meant to work in the browser, a whole bunch of "`Cannot find type DOMException`" and friends get thrown.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
