### ISSUE TITLE
Quick and dirty solution to import a large untyped plugin to a typed library

### ISSUE THREAD

**Issue by gehreleth** [DefinitelyTyped/DefinitelyTyped#21574]
Suppose, I have to integrate THREE.GLTFLoader to my project. The library THREE has its @types, but this particular class distributed separately. At the moment, the only available solution is to drop GLTFLoader.js to my project and import it somehow. But I can't include it with "import" instruction without .d.ts file. 

I need a quick and dirty solution to import this code as-is and make GLTFLoader instances. It's a tremendous amount of code, I don't have time and resources to rewrite it to Typescript or make binding for any type.

**Comment by lilred** [comment]
This would be a great question to put on Stack Overflow.

As for the actual solution - you want to define a module that exposes the `any` type. This way TypeScript will let you do whatever you like with it. You can iteratively improve it into something less open-ended if you feel like it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
