### ISSUE TITLE
error TS2322: Type '{ ListFooterComponent: Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<SectionListProperties<any>, ComponentSta...'.   Type '{ ListFooterComponent: Element; }' is not assignable to type 'Readonly<SectionListProperties<any>>'.     Types of property 'ListFooterComponent' are incompatible.

### ISSUE THREAD

**Issue by hyochan** [DefinitelyTyped/DefinitelyTyped#21611]
If you know how to fix the issue, make a pull request instead.
ListFooterComponent attributes works fine in other ListView like FlatList but not in SectionList.

current dependecies are

types/fbemitter : "2.0.32",
types/jest: "^21.1.6",
types/node: "^8.0.53",
types/react: "^16.0.24",
types/react-native: "^0.50.7",
types/react-test-renderer: "^16.0.0",

Below is screenshot where error occurs.
<img width="599" alt="screenshot" src="https://user-images.githubusercontent.com/27461460/32981486-dd17ff64-ccb9-11e7-88a1-ee5cd3193f50.png">

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
