### ISSUE TITLE
[@types/config] Has no default exports and Property does not exist on type 'IConfig'

### ISSUE THREAD

**Issue by kolya182** [DefinitelyTyped/DefinitelyTyped#21620]
I'm trying to access mongo.url from /config/development.json looks like:
```
{
   "mongo": {
                "url": "mongodb://localhost:27017/test"
    }
}
```
![2017-11-18 17 13 42](https://user-images.githubusercontent.com/3277207/32986310-5764e43e-cc84-11e7-958f-1114e6e9d4d5.jpg)
In case using:
`import * as config from "config"` i'm getting this error:
![2017-11-18 17 21 32](https://user-images.githubusercontent.com/3277207/32986345-fb4ab0ce-cc84-11e7-8f27-449ca0fcefca.jpg)

- [YES ] I tried using the latest stable version(2.6.1) of [tsc](https://www.npmjs.com/package/typescript). 
  - Authors: @andy-ms and @forrestbice , @RWander

**Comment by kolya182** [comment]
The first screen fixed by importing config as shown on the second screen. 
Another question I have.
1. Why I cant' access `url` by calling `config.mongo.url` as I would by `require('config')` which is worked for me very well. 
2. Using `config.get("mongo").url` i'm getting an error: Property 'url' doesn't exist on on type '{}'. Console logging `config.get("mongo")` : `{ url: 'mongodb://localhost:27017/trust-wallet-development' }`

**Comment by andy-ms** [comment]
TypeScript doesn't know what's going to happen at runtime, it just knows about what's already declared in type declaration files. In this case you're going to have to provide it with more information by providing an explicit type argument as in `config.get<{ url: string }>("mongo")`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
