### ISSUE TITLE
@types/react-redux: Incorrect type for `connect((state, ownProps) => ...)`

### ISSUE THREAD

**Issue by rhys-vdw** [DefinitelyTyped/DefinitelyTyped#21640]
- [ ] I tried using the `@types/react-redux` package and had problems.
  - Authors: @tkqubo @thasner @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo, @pdeva

Having the following problem:

```tsx
import React, { StatelessComponent } from "react"
import { connect } from "react-redux"

interface Props {
  foo: number,
  bar: number,
}

const Impl: StatelessComponent<Props> = (props) => {
  return <pre>{props.foo}, {props.bar}</pre>
}

const Connected = connect(
  (state: any, ownProps: Props) => ({ foo: 5 })
)(Impl)

const x = <Connected bar={5} /> // ERROR!
```

> 'Type '{ bar: 5; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<Pick<Props & { children?: ReactNode; }, ...'.
  Type '{ bar: 5; }' is not assignable to type 'Readonly<Pick<Props & { children?: ReactNode; }, "bar" | "children"> & Props>'.
    Property 'foo' is missing in type '{ bar: 5; }'.'

Changing the above code to the following works:

```tsx
const Connected = connect(
  (state: any) => ({ foo: 5 }) // remove reference to `ownProps`
)(Impl)
```

I can look into addressing this myself if necessary.

**Comment by rhys-vdw** [comment]
Bit more info:

In my real world code the issue is that I need to provide prop types to `ownProps` so that I can access the props like so:

```ts
export default connect((state: State, { responseId }: ImplProps) => ({
  order: getOrderForResponseId(state, responseId),
}))(Impl)
```

If I don't add the type to the second argument (`ownProps`) then it defaults to `{}`. But when I do add the `ImplProps` type it causes the above problem.

However I can do this:

```ts
export default connect((state: State, { responseId }: Pick<ImplProps, "responseId">) => ({
  order: getOrderForResponseId(state, responseId),
}))(Impl)
```

Or even less desirable:

```ts
import { Dissoc as Omit } from "subtractiontype.ts"

export default connect((state: State, { responseId }: Pick<ImplProps, "responseId">) => ({
  order: getOrderForResponseId(state, responseId),
}))(Impl) as ComponentType<Omit<ImplProps, "order">>
```

**Comment by mDibyo** [comment]
Typescript is not able to figure out what props come from state, and what are ownProps. You can help it along by doing the following:
```ts
import React, { StatelessComponent } from "react"
import { connect } from "react-redux"

export interface StateProps {
  foo: number;
}

export interface OwnProps {
  bar: number;
}

export interface Props extends StateProps, OwnProps { }

const Impl: StatelessComponent<Props> = (props) => {
  return <pre>{props.foo}, {props.bar}</pre>
}

export default connect<StateProps, null, OwnProps>(
  (state, ownProps) => ({ foo: 5 })
)(Impl)
```

**Comment by rhys-vdw** [comment]
Ah, so its not possible for the return value to be, in the above case:

```
Omit<ImplProps, keyof InjectedProps>
```

Where `InjectedProps` is the return type of `mapStateToProps`, and `ImplProps` is the prop shape of `Impl`?

**Comment by mDibyo** [comment]
What you suggested would probably not be possible because `mapStateToProps`, `mapDispatchToProps` and `mergeProps` all have `ownProps` as an argument. Typescript needs to check that the type of `ownProps` passed to those three are the same, and it needs to do that before the component has been used somewhere else. AFAIK, that's not possible.

**Comment by mDibyo** [comment]
You can certainly go ahead and write the interfaces that you pass as generic types to `connect` in that fashion.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
