### ISSUE TITLE
@types/angular missing error type variable in IPromise

### ISSUE THREAD

**Issue by NicBright** [DefinitelyTyped/DefinitelyTyped#21644]
Hi @diegovilar @thorn0 @calebstdenis @leonard-thieu,

I was wondering why the IPromise type in `@types/angular` is missing a type variable for rejection? After all, a promise (as soon as it is no longer pending) can be in any of 2 states (see https://promisesaplus.com/#promise-states):

fulfilled => value
rejected => reason

Both of these states are equally valid and should have a dedicated type variable.

Right now, IPromise in Angular only has one:

`interface IPromise<T> { ... }`

May I ask what's the reasoning behind this? Have you experimented already with adding an "error" type variable?

I've been recently experimenting with this a little bit, because knowing if a promise can be rejected at all (and with what rejection-type) really helps a lot regarding error handling "upstream" in the code. If you're interested in my "results", please let me know and I will be happy to show them to you.

Regards,
Nicolas

**Comment by NicBright** [comment]
Anybody got an opinion on this?

**Comment by leonard-thieu** [comment]
I think it'd be nice to have a dedicated type parameter for the rejection type. I don't know the original reason for not including it. If I had to guess, I'd say it probably had to do with the relative difficulty and complexity with implementing it correctly.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
