### ISSUE TITLE
engine.io-client and engine.io incompatibility

### ISSUE THREAD

**Issue by slawiko** [DefinitelyTyped/DefinitelyTyped#21653]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/engine.io-client` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors so they can respond.
  - Authors: @KentarouTakeda 

In `engine.io-client` we can see
```typescript
declare namespace client {
	type Message = string|ArrayBuffer|ArrayBufferView|Blob;
```

In `engine.io`
```typescript
declare namespace engine {
	type Message = string|Buffer|ArrayBuffer|ArrayBufferView;
```

Why are the types of message different in eio-client and eio? Which one is right?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
