### ISSUE TITLE
@types/fuse Issue

### ISSUE THREAD

**Issue by vehansayvazi** [DefinitelyTyped/DefinitelyTyped#21664]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @smrq 

If you do not mention the authors the issue will be ignored. 

Please take a look at this: https://reformatcode.com/code/typescript/why-does-webpack-fail-to-find-a-module-when-the-typescript-compiler-doesn39t

**Comment by aluanhaddad** [comment]
Since the declarations for fuse are part of the library itself and not maintained here on DefinitelyTyped you should file an issue there instead.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
