### ISSUE TITLE
[@types/react-bootstrap] Types for Bootstrap 3 - title prop for NavbarDropdown is only string | undefined

### ISSUE THREAD

**Issue by rluiten** [DefinitelyTyped/DefinitelyTyped#21668]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-bootstrap` package and had problems version 0.31.5.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript,
       **this is purely typedef missmatch I am on typescript 2.5.3**
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- Authors: @walkerburgin, @vsiao, @danilojrr, @Batbold-Gansukh

I have a work around to declare as follows

```typescript
    const NavDropdownHack: any = NavDropdown;
```
Then use NavDropdownHack  which  does not type error for attribute `title`.

The `title` attribute appears to be defined by the inclusion of `React.HTMLProps<Dropdown>` into `DropdownProps`.

This leaves title defined as `string | undefined` only.

From https://github.com/react-bootstrap/react-bootstrap/blob/master/src/NavDropdown.js it is defined as `title: PropTypes.node.isRequired`

It appears this attribute has this issues for a number of React Bootstrap components.

**Comment by lilred** [comment]
Please edit the title to include "[@types/**react-**bootstrap]" 🙂

**Comment by rluiten** [comment]
Done, oops on my first one.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
