### ISSUE TITLE
[@types/react] Constructor super now requires passing props

### ISSUE THREAD

**Issue by ktalebian** [DefinitelyTyped/DefinitelyTyped#21685]
As of the latest version `16.0.25` the constructor requires the `props` argument https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L280.

Before the following was safe:

```
class Foo extends React.Component<MyProps, MyState> {
   constructor() {
       super();
       this.state = ...
   }
}
```

Now this will throw `error TS2554: Expected 1-2 arguments, but got 0.`

**Comment by tiagoefmoraes** [comment]
As said in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21989#pullrequestreview-81629298

> This was intentionally changed to be required. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20987#issuecomment-339216734 for more details.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
