### ISSUE TITLE
@types/md5 Issue

### ISSUE THREAD

**Issue by pirmax** [DefinitelyTyped/DefinitelyTyped#21690]
I tried to use md5 with `import * as md5 from "md5";`

But I have this error: 

> 'Error: Cannot find module \'md5\''

**Comment by micksatana** [comment]
Make sure you run npm install for both md5 and @types/md5

```
npm install md5 @types/md5
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
