### ISSUE TITLE
Ramda: aperture does not return tuples

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#21694]
Given:

``` ts
/*
Unexpected error:
Type 'number[][]' is not assignable to type '[number, number][]'.
  Type 'number[]' is not assignable to type '[number, number]'.
    Property '0' is missing in type 'number[]'.
*/
const xs: [number, number][] = R.aperture(2, [1, 2, 3, 4, 5, 6])
```

I expect `aperture` to return an array of tuples with a length matching the input length—in this example, `2`.

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @donnut @mdekrey @mrdziuban @sbking @afharo @teves-castro @1M0reBug @hojberg @charlespwd @samsonkeung @angeloocana 

If you do not mention the authors the issue will be ignored.

**Comment by afharo** [comment]
Hi @OliverJAsh, the reason is you are expecting `xs` to be `[number, number][]`.
From my experience with TS, tuples types do not work as expected yet (like number[] with length 2 is not the same as [number, number]).

This said, there is not a current way in TS to specify some sort of 
```typescript
// Current implementation
aperture<T>(n: number, list: ReadonlyArray<T>): T[][];

// "Actual" result implementation
aperture<T>(n: number, list: ReadonlyArray<T>): [T, T, T, ...(n times), T][];
```

So I'm afraid you need to go this way:
```const xs: number[][] = R.aperture(2, [1, 2, 3, 4, 5, 6])```
Or, if [number, number][] is a mandatory behaviour for you, you can solve it like:
```typescript
const xs: [number, number][] = [1, 2, 3, 4, 5, 6].reduce((acc, val, index, arr) => {
    if ((index + 1) >= arr.length) {
        return acc;
    }
    acc.push([arr[index], arr[index + 1]]);
    return acc;
}, [] as [number, number][]);
```

**Comment by OliverJAsh** [comment]
Thanks @afharo!

**Comment by tycho01** [comment]
@OliverJAsh consider trying the typings at [`types/npm-ramda`](https://github.com/types/npm-ramda/). while not merged here yet, they're ahead for typing ramda. This issue for one is [addressed](https://github.com/types/npm-ramda/blob/master/templates/aperture.md) there, among a bunch of others.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
