### ISSUE TITLE
React-bootstrap Tabs onSelect call signature acting strange

### ISSUE THREAD

**Issue by heatherbooker** [DefinitelyTyped/DefinitelyTyped#21710]
Hi,
I'm trying to write a controlled Tabs component using react-bootstrap but keep getting errors regarding the onSelect definition. I have tried these:

```
// Option 1. (error)
onSelect = (eventKey: any, e: React.SyntheticEvent<{}>) => {
  // etc, no return
}
// Option 2. (error)
onSelect = (eventKey: MyType, e: React.SyntheticEvent<{}> => {
  // etc, no return
}
// Option 3. (error)
onSelect = (eventKey: MyType) => {
  // etc, no return
}
// Option 4. (works)
onSelect = (eventKey: any) => {
  // etc, no return
}
// Option 5. (error)
onSelect = (eventKey: any, e: any) => {
  // etc, no return
}
```

And I see the definition of the onSelect callback in the Tabs component is SelectCallback:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7b269435223e79a8ea27d59cf03acae0a741de2c/types/react-bootstrap/lib/Tabs.d.ts#L10

Which is defined here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7b269435223e79a8ea27d59cf03acae0a741de2c/types/react-bootstrap/index.d.ts#L22-L30

I'm not sure if this is a bug or how the callback is supposed to be defined on my end to make things work. Option 3 (`(eventKey: MyType)`) is what I would like to use, and option 2 would also be fine. Help appreciated, thanks!

**Comment by ericlam51** [comment]
Same issue, any fix for this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
