### ISSUE TITLE
[@types/react-virtualized] ListRowRenderer parent type incompatible with CellMeasurer parent type

### ISSUE THREAD

**Issue by kamiyo** [DefinitelyTyped/DefinitelyTyped#21746]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-virtualized` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kaoDev @guntherjh @wasd171 @szabolcsx 

I'm using CellMeasurer in a List like so:
```
<List rowItemRenderer={rowItemRenderer} ...otherProps />

rowItemRenderer: ListRowRenderer = ({ parent, ...props }) => (
    <CellMeasurer parent={parent} ...props />
)
```

The parent={parent} is erroring because the parent supplied to the function, as defined by ListRowRenderer is of type List | Grid | Table, is incompatible with the parent prop in CellMeasurer, which expects React.ReactType.

Thanks

**Comment by kamiyo** [comment]
More details:
```
    Types of property 'parent' are incompatible.
      Type 'List | Grid | Table' is not assignable to type 'ReactType<any>'.
        Type 'List' is not assignable to type 'ReactType<any>'.
          Type 'List' is not assignable to type 'StatelessComponent<any>'.
            Type 'List' provides no match for the signature '(props: any, context?: any): ReactElement<any>'.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
