### ISSUE TITLE
@types/stripe is completely missing the sources API

### ISSUE THREAD

**Issue by benstevens48** [DefinitelyTyped/DefinitelyTyped#21756]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wjohnsto , @CodeAnimal , @sampsonjoliver , @LinusU , @brannon 

`@types/stripe` is completely missing the sources API - see [https://stripe.com/docs/api#sources](https://stripe.com/docs/api#sources). It would be good to include this (especially to support types for 3d secure payments).

**Comment by sampsonjoliver** [comment]
Bit of prelim work here: https://github.com/sampsonjoliver/DefinitelyTyped/tree/stripe-node-sources

Don't really have the time to thoroughly check this, especially as I don't use the sources API in practice, hence some roughness in the parameter types. Happy for someone to fork and clean up the rest + add some tests.

Ideally we'd need to add the types for other payment source types (we only really have bank accounts and cards). That's probably another body of work in itself.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
