### ISSUE TITLE
@types/jwt-decode has missing definition.

### ISSUE THREAD

**Issue by lambdalisue** [DefinitelyTyped/DefinitelyTyped#21821]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/jwt-decode` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @GiedriusGrabauskas, @madsmadsen

If you do not mention the authors the issue will be ignored.
---

It seems `InvalidTokenError` is exposed but missing from the definition file.

https://github.com/auth0/jwt-decode/blob/master/lib/index.js#L26

It seems simple to fix but I'm not really sure how to write the definition file correctly so I just made an issue sorry.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
