### ISSUE TITLE
Does having DefinitelyTyped typings for an SDK affect if we change the SDK to be in TypeScript?

### ISSUE THREAD

**Issue by anweshan** [DefinitelyTyped/DefinitelyTyped#21896]
There are DefinitelyTyped definitions for watson-developer-cloud https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16254 in this repo. Recently however, watson-developer-cloud v3 has been changed https://github.com/watson-developer-cloud/node-sdk/tree/typescript/master in a beta release to be in TypeScript (was previously in javascript/node). Does having the DefinitelyTyped definitions for the previous version interfere with any future versions that are in TypeScript already?

**Comment by andnp** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

If a user wants to use an old version of your library (like `v2`) and wants the types, then they can set their package.json to request a version from `@types/....` that corresponds to the version of your lib that they want to use.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
