### ISSUE TITLE
Missing autoGrow and maxHeight attributes for react-native

### ISSUE THREAD

**Issue by nitrog7** [DefinitelyTyped/DefinitelyTyped#21955]
Around lines 1089 and 1114 there should be two missing attributes for the TextInputProperties interface:
- autoGrow: boolean
- maxHeight: number

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e4a7331e99970b559938af34100c263a45deb761/types/react-native/index.d.ts#L1114

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
