### ISSUE TITLE
@types/atom: Emitter's global 'Emissions' entirely pointless

### ISSUE THREAD

**Issue by lierdakil** [DefinitelyTyped/DefinitelyTyped#21965]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @GlenCFL

Since different emitters can have different 'emissions', having a global interface, especially one defining 'catch-all' string index is not helpful *at all*. Adding `Emissions` as a generic parameter to `Emitter` itself would work *much* better. Example:

```typescript
/**
 *  Utility class to be used when implementing event-based APIs that allows
 *  for handlers registered via ::on to be invoked with calls to ::emit.
 */
export class Emitter<Emissions = { [key: string]: any }> implements DisposableLike {
    /** Construct an emitter. */
    constructor();

    /** Clear out any existing subscribers. */
    clear(): void;

    /** Unsubscribe all handlers. */
    dispose(): boolean;

    // Event Subscription
    /** Registers a handler to be invoked whenever the given event is emitted. */
    on<T extends keyof Emissions>(eventName: T, handler: (value?: Emissions[T]) => void):
        Disposable;

    /**
     *  Register the given handler function to be invoked the next time an event
     *  with the given name is emitted via ::emit.
     */
    once<T extends keyof Emissions>(eventName: T, handler: (value?: Emissions[T]) => void):
        Disposable;

    /**
     *  Register the given handler function to be invoked before all other
     *  handlers existing at the time of subscription whenever events by the
     *  given name are emitted via ::emit.
     */
    preempt<T extends keyof Emissions>(eventName: T, handler: (value?: Emissions[T]) => void):
        Disposable;

    // Event Emission
    /** Invoke the handlers registered via ::on for the given event name. */
    emit<T extends keyof Emissions>(eventName: T, value?: Emissions[T]): void;
}
```

**Comment by GlenCFL** [comment]
Mentioning @smhxx as well.

**Comment by lierdakil** [comment]
Also, while on topic, `value` shouldn't be optional, since it's dictated entirely by the event in question. `Emissions[T]` can always be `something | undefined` if parameter is indeed optional.

**Comment by lierdakil** [comment]
Although that might be hard to do.

**Comment by GlenCFL** [comment]
This solves a few other problems as well, such as completely separate emitters having events with the same name, while emitting different types.

> Also, while on topic, value shouldn't be optional, since it's dictated entirely by the event in question. Emissions[T] can always be something | undefined if parameter is indeed optional.

The issue with this is that if the key has a value of something like `string|undefined`, then that parameter is still going to be required for each of the calls to the Emitter itself. The `emitter.emit("event")` call signature wouldn't work, even though the type of that second parameter would be `string|undefined`. I'm not sure if there's a way around that.

**Comment by lierdakil** [comment]
I've thought about it, and I might offer a workaround, but it's convoluted to say the least. Long story short, have two generic parameters, one for "maybe undefined"-, one for "definitely defined"-valued events. Then duplicate all method signatures accordingly. Not a lot of fun, but it'll work as an opt-in. One significant drawback of this approach is error messages can become rather useless. For example, with something like this: `emitter.on('some-event-name', (value: number) => ...)` error message will be something like `argument 'some-event-name' not assignable to type never`, instead of usual discourse on how `value: number` doesn't match `value: number | undefined`.

Frankly, having values possibly undefined does more harm than good IMO, since it (a) doesn't catch you if you forget to pass a value expected on the other end and (b) forces you to check for `undefined` where it's meaningless. Essentially pushes errors from compile-time to run-time, which is never good. Requiring a second parameter (which is possibly literal `undefined`) seems like a lesser evil by comparison.

Anyway, here's workaround-ish code:
```ts
export class Emitter<Emissions = { [key: string]: any }, Extra = {}> implements DisposableLike {
    /** Construct an emitter. */
    constructor();

    /** Clear out any existing subscribers. */
    clear(): void;

    /** Unsubscribe all handlers. */
    dispose(): boolean;

    // Event Subscription
    /** Registers a handler to be invoked whenever the given event is emitted. */
    on<T extends keyof Emissions>(eventName: T, handler: (value?: Emissions[T]) => void):
        Disposable;
    on<T extends keyof Extra>(eventName: T, handler: (value: Extra[T]) => void):
        Disposable;

    /**
     *  Register the given handler function to be invoked the next time an event
     *  with the given name is emitted via ::emit.
     */
    once<T extends keyof Emissions>(eventName: T, handler: (value?: Emissions[T]) => void):
        Disposable;
    once<T extends keyof Extra>(eventName: T, handler: (value: Extra[T]) => void):
        Disposable;

    /**
     *  Register the given handler function to be invoked before all other
     *  handlers existing at the time of subscription whenever events by the
     *  given name are emitted via ::emit.
     */
    preempt<T extends keyof Emissions>(eventName: T, handler: (value?: Emissions[T]) => void):
        Disposable;
    preempt<T extends keyof Extra>(eventName: T, handler: (value: Extra[T]) => void):
        Disposable;

    // Event Emission
    /** Invoke the handlers registered via ::on for the given event name. */
    emit<T extends keyof Emissions>(eventName: T, value?: Emissions[T]): void
    emit<T extends keyof Extra>(eventName: T, value: Extra[T]): void
}
```

**Comment by GlenCFL** [comment]
I agree that having values being potentially undefined is almost entirely negative. The only problem is that we have to allow for events that do not have an associated payload, which are very common within the [Atom codebase](https://github.com/atom/atom/search?utf8=%E2%9C%93&q=emitter.on&type=). Each of those `emitter.on("event")` calls would have to be written in TypeScript as `emitter.on("event", undefined)`. I don't think that's too much to ask, but it does break the contract for the Emitter class within TypeScript. @smhxx  for their opinion on this.

The implementation with second template parameter works, but I agree that it's just messy. If we don't want to make the values required, then it's probably the best that we can do unless we get a new TypeScript feature that helps here later on down the line.

**Comment by lierdakil** [comment]
> Each of those `emitter.on("event")`

I think you meant `emitter.emit("event")`

Anyway, good news is we have a proposal to treat `undefined`-typed parameters as optional (https://github.com/Microsoft/TypeScript/issues/12400), which is apparently on-track for TS 2.8.

Also somewhat relevant: https://github.com/Microsoft/TypeScript/issues/13257, although it's ways off and unclear if it'll ever be implemented.

**Comment by GlenCFL** [comment]
The first one should be enough to get this to work properly, so we could leverage that in a few months once 2.8 is out, assuming it makes it into the release. The only problem is that `any|undefined` is likely to still just be `any`, so we'd have to change the way we index it:
```ts
type something = object|boolean|string|number;
export class Emitter<Emissions = { [key: string]: something|undefined }> implements DisposableLike {
    ...
}
```

I think that will cover all cases, but it's something that will need to be tested once possible.

**Comment by GlenCFL** [comment]
I think the following is a reasonable compromise for the time being:

- The Emitter class will be templated using something similar to what is listed above.
- The values for the Emitter methods will no longer be potentially undefined.
- A second overload for `Emitter.emit` will be added, which takes only a single parameter. If you avoid this overload, then type checking for events should be good. This will be silently removed if the change in TS 2.8 panes out.

**Comment by smhxx** [comment]
So, just to make sure I understand the issue here, we're trying to find an elegant way of making sure that `Emitter.emit('should-have-payload')` is caught as incorrect by the compiler, without also catching `Emitter.emit('might-not-have-payload')` as incorrect, as well? It's not super easy, and I think regardless of how you do it, the error you get isn't going to be super intuitive. The ~~most elegant~~ least inelegant way I can think of is using an optional union type to express which keys are valid for the one-parameter call signature:

![example](https://user-images.githubusercontent.com/839240/33638459-ecb54546-d9eb-11e7-962a-ee5b5d601b49.PNG)

It's strange, but does technically work... and I'd be hard pressed to find any *less weird* way of doing it using current TypeScript features.

**Comment by GlenCFL** [comment]
That's correct. The issue with that implementation is that now everyone that wants to use the `Emitter.emit("event")` signature must provide that second template argument.

I think it would be best to just wait for TS 2.8 and then reevaluate then, as union types that are potentially undefined being used as a parameter will (hopefully) result in that parameter being optional within that release. Until then, the use of the `emitter.emit("event")` signature is unsafe though.

**Comment by smhxx** [comment]
With the current implementation of lookup types in TypeScript, I don't think a "perfect" solution is possible, so I think there's bound to be some form of trade-off between ease of use and strict "correctness" of the definitions. I'd say that, in the meantime until this shortcoming is improved, there are three options:

* **Prioritize ease of use:** Simply allow the single-parameter overload of `emit()` for all Emitters, and make the value parameters of the listener methods (`on()`, `once()`, etc.) optional for consistency.
* **Prioritize strictness:** Use two generic arguments for Emitter, allowing users to manually define which emitted events have optional values associated with them.

I would argue that the former is better in the context of event-kit alone, whereas, in the context of Atom, there's relatively little need for users to extend the Emitter class, and the added complexity of the second generic would mostly be contained *within* the Atom definitions themselves, not adding any extra burden to the average user. Overall, though, I think that the more lax approach is probably a safer bet. There's always the option of *not* checking for undefined, and instead telling the compiler "I know what I'm doing" by casting to the actual type with `as`... i.e. if you're expecting the event to contain a value of type `Foo`, but the compiler considers it to be `Foo | undefined`, you can do `let actualValue = value as Foo;` since `Foo` is a subset of the union type `Foo | undefined`. That's assuming you want to take on the responsibility of guaranteeing that the value won't actually *be* undefined at runtime, of course.

**Comment by GlenCFL** [comment]
I think that lierdakil's implementation is best for now then. It works in all cases, with the ability to opt-in and prevent each type from being marked as `T|undefined`.

Usage would typically be something like:
```ts
interface Emissions { "event": string }

const emitter = new Emitter<{}, Emissions>();
emitter.emit("event"); // error
emitter.emit("event", "test"); // ok
```

**Comment by smhxx** [comment]
I think that's a solid plan. The only bit of constructive criticism I'd offer is to use more intuitive names for the generic arguments to Emitter within the definitions file. "Emissions" is fairly understandable; after all, it's essentially just a Record of things that the Emitter emits. "Extra" doesn't really mean anything to me, though. Perhaps something like "StrictEmissions"? Or, to make the distinction even more evident, make them "LaxEmissions" and "StrictEmissions"? I'd probably stick a short comment in explaining that the difference is due to technical limitations, just to be safe, but at least with more expressive names the first-glance value is not quite as "[wtf is going on here?](http://i.imgur.com/J1svNp7.jpg)"

**Comment by smhxx** [comment]
Just saw your latest commit on the PR, and I think that's definitely an improvement (Optional/Required vs. Emissions/Extra.) I guess you could make an argument that Optional/Required isn't perfect because they're adjectives and don't actually explain what the generics are used for, but a quick glance at the code should be enough to let on what they are and what's "optional" or "required" about them. Plus, the entire existence of those arguments is a stopgap anyway until TypeScript supports a more sane way of achieving the usage we're aiming for, so in the long run, coming up with 100% self-evident names for them isn't the biggest priority.

**Comment by GlenCFL** [comment]
Yeah, I was about to rename them to `OptionalEmissions` and `RequiredEmissions`.

**Comment by lierdakil** [comment]
Okay, to be clear, I just quickly slapped together some code as a proof of concept, so I didn't spend *any* time deliberating naming conventions, just used the first thing that came to my mind. I completely agree that names I used are horribly non-descriptive.

I have to say though, it isn't immediately self-evident what `OptionalEmissions` and `RequiredEmissions` mean without reading the code -- it sounds like signals themselves are optional/required instead of data payload. This is not a huge deal, since it's not immediately evident from the code how those are to be used too, but as an arguably more descriptive alternative, I'd like to propose `OptionalPayloadEmissions` and `RequiredPalyloadEmissions` (although that PR is merged already, so this will have to go in separately)

**Comment by smhxx** [comment]
I would tend to agree that Required/OptionalEmissions aren't 100% self-evident, and I think you're right that, without prior knowledge, it does sound like the events themselves are supposed to be in some way required or optional. That was my reasoning with suggesting Strict and Lax (which perhaps more closely hint at the actual behavior,) but ultimately I think that the cognitive burden of the current names is relatively minor. If we can agree on a set of names that more closely suggests the actual purpose of the generic arguments, I would be in support of the change.

**Comment by lierdakil** [comment]
I think I'm just going to close this lest it becomes stale and haunts the backlogs.

**Comment by GlenCFL** [comment]
Decided to checkup on this now that TypeScript 2.8 is pending release. [Microsoft/TypeScript#12400](https://github.com/Microsoft/TypeScript/issues/12400) was moved from the 2.8 milestone to the Future milestone.
