### ISSUE TITLE
THREE.js wrong type for BufferGeometry.attributes

### ISSUE THREAD

**Issue by EvgenyKrivoshein** [DefinitelyTyped/DefinitelyTyped#21973]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/386d333cccac7f7c093da7dea1afd3fd623c5ab9/types/three/three-core.d.ts#L833

According to docs [BufferGeometry.attributes](https://threejs.org/docs/#api/core/BufferGeometry.attributes) is a hashmap.

**Comment by sampopes** [comment]
I get "Property 'needsUpdate' does not exist on type 'BufferAttribute" in typescript and as a work around I have to always use any as a type

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
