### ISSUE TITLE
is there a way to still install things global ? 

### ISSUE THREAD

**Issue by Mxesli** [DefinitelyTyped/DefinitelyTyped#22005]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

  - Authors: @Mxesli

I am having a lots of trouble with DefinitleyTypes and "npm @types\...", all this typings wont work for my project (i am working with powerbi visuals) i tried everything but i cant get it to run at all...

Main problem: i think powerbi only supports global definitons. 
But there are no global typings anymore so nothing gets compiled. 
The only thing that works is jQuery because jQuery still got a global typing ("typings install --save --global jQuery" works). 

my question: is there any place where i can still get global typings with "typings install --save --global ..." for example for frameworks like: "react", "react-dom", "antd", "angularJS" ...?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
