### ISSUE TITLE
better-sqlite3, cannot reference Statement?

### ISSUE THREAD

**Issue by yifanwu** [DefinitelyTyped/DefinitelyTyped#22024]
Hi,

Sorry if this is a dumb question, but I cannot seem to reference `Statement`, seems like it was not exported?
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b13b82c214ac5ed2397ec5f3ab6a157a9fc7e220/types/better-sqlite3/index.d.ts#L16

I tried a few different things but cannot seem to get it to export (or figure out a way to import).

Thanks! cc/@Morfent

**Comment by Morfent** [comment]
Don't worry, it's not a dumb question. `Statement` and `Transaction` aren't exported since better-sqlite3 keeps them private and prevents them from being used as constructors from outside the library. I'm not sure if you can import them, but you can define the types for them so they can be used. [This issue](https://github.com/Microsoft/TypeScript/issues/14400#issuecomment-291261491) explains a couple ways of how to do it

**Comment by yifanwu** [comment]
ah got it; thanks so much!
