### ISSUE TITLE
@types/mapbox-gl: not passing tslint

### ISSUE THREAD

**Issue by redbmk** [DefinitelyTyped/DefinitelyTyped#22035]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - GeoJSON Authors: @cobster @atd-schubert @JeffJacobson 
  - Mapbox-GL Authors: @dobrud @patrickr @alex3165 

If you do not mention the authors the issue will be ignored.

Due to some changes in `geojson`, `mapbox-gl`'s tests now have linting errors because `GeoJson.GeometryObject` no longer contains `coordinates`.

**Comment by alex3165** [comment]
PR opened to fix this https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22544

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
