### ISSUE TITLE
Type definition incorrect for Kendo-UI GridColumn

### ISSUE THREAD

**Issue by clabough** [DefinitelyTyped/DefinitelyTyped#22038]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/85c17c4f49a8b4cf6b6282c376380e7cae20ff84/types/kendo-ui/index.d.ts#L3751

Since the command property of a GridColumn can be an array of strings, for example:

`{ command: ["edit", "destroy"], title: "&nbsp;", width: "250px" }`

The current definition is 

`command?: GridColumnCommandItem[];`

but it should be

`command?: (string|GridColumnCommandItem)[];`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
