### ISSUE TITLE
Bluebird-global, long stack traces not working

### ISSUE THREAD

**Issue by jan0991** [DefinitelyTyped/DefinitelyTyped#22064]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @d-ph 

I banged my head against this for a couple of hours, and I can't figure out what I am doing wrong. I tried just about everything I can think of, below is my latest solution that seems to use bluebird promises, but it still doesn't show long stack traces. so:

**1: I installed types/bluebird-global**

**2: In my entry file:**

```
import * as Bluebird from "bluebird";
global.Promise = Bluebird;
```
**3: Then setup listener**

```
process.on("unhandledRejection", function(reason: any) {
    console.log(reason);
});
```
And it shows error stack like this (not long at all, this stack trace doesn't help me at all):

```
[Node] TypeError: Cannot read property 'url' of undefined
[Node]     at new Response (/home/home/dev4/d-project/auto-ts/node_modules/puppeteer/lib/NetworkManager.js:441:24)
[Node]     at NetworkManager._handleRequestRedirect (/home/home/dev4/d-project/auto-ts/node_modules/puppeteer/lib/NetworkManager.js:174:22)
[Node]     at NetworkManager._onRequestWillBeSent (/home/home/dev4/d-project/auto-ts/node_modules/puppeteer/lib/NetworkManager.js:221:12)
[Node]     at Session.emit (events.js:159:13)
[Node]     at Session._onMessage (/home/home/dev4/d-project/auto-ts/node_modules/puppeteer/lib/Connection.js:210:12)
[Node]     at Connection._onMessage (/home/home/dev4/d-project/auto-ts/node_modules/puppeteer/lib/Connection.js:105:19)
[Node]     at WebSocket.emit (events.js:159:13)
[Node]     at Receiver._receiver.onmessage (/home/home/dev4/d-project/auto-ts/node_modules/ws/lib/WebSocket.js:143:47)
[Node]     at Receiver.dataMessage (/home/home/dev4/d-project/auto-ts/node_modules/ws/lib/Receiver.js:389:14)
[Node]     at Receiver.getData (/home/home/dev4/d-project/auto-ts/node_modules/ws/lib/Receiver.js:330:12)
[Node]     at Receiver.startLoop (/home/home/dev4/d-project/auto-ts/node_modules/ws/lib/Receiver.js:165:16)
[Node]     at Receiver.add (/home/home/dev4/d-project/auto-ts/node_modules/ws/lib/Receiver.js:139:10)
[Node]     at Socket._ultron.on (/home/home/dev4/d-project/auto-ts/node_modules/ws/lib/WebSocket.js:139:22)
[Node]     at Socket.emit (events.js:159:13)
[Node]     at addChunk (_stream_readable.js:265:12)
[Node]     at readableAddChunk (_stream_readable.js:252:11)
```
I have NODE_ENV="development", BLUEBIRD_DEBUG=1... What am I missing?

**Comment by d-ph** [comment]
Hello Jan,

Sorry to hear you're struggling with setting this all up.

Although I've done next-to-none nodejs dev, I can't see anything obviously wrong with your setup. And as you can tell, something does work, since you can see the console output you've posted.

I have a suspicion, that what you see is expected in this scenario. Could you please try to use the test code from the official [bluebird docs](http://bluebirdjs.com/docs/features.html#long-stack-traces) to see, whether the long stack traces are really on or not?
```js
import * as Promise from "bluebird";

Promise.delay(1)
    .delay(1)
    .delay(1).then(function() {
        a.b.c;
    });
```
Put the above in any file in your code (immediately after you override the `global.Promise`, should be fine) and see whether you get a stack trace, that includes the `From previous event:` section.

Other than that, I can't really offer any more assistance. Moreover, it seems to me, that the problem is not related to the `@types/bluebird-global` specifically (since I presume you are able to compile your code successfully). Maybe someone else will be able to help you more.

You probably could also try your luck directly in [bluebird's github](https://github.com/petkaantonov/bluebird/), since guys over there are _far more_ knowledgeable in nodejs dev than me. And again, this seems like a runtime/setup problem, not a problem with the typings from `@types/bluebird-global` themselves.

Cheers,
@d-ph

**Comment by jan0991** [comment]
Hi, the code above did produce `from previous event` so the issue probably lies elsewhere, thanks for help!
