### ISSUE TITLE
Latest Typescript ? 

### ISSUE THREAD

**Issue by ramakrishnanjayaraman** [DefinitelyTyped/DefinitelyTyped#22093]
Hi,
Thank you for this wonderful library ? It appears that for v1.0.0 and above the latest typescript is not available yet. Kindly advise if someone is going to update the typescript module ? 

Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
