### ISSUE TITLE
Properties 'structured_formatting' and 'reference' don't exist on type 'AutocompletePrediction'

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/DefinitelyTyped#22105]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cgwrench, @Silver-Connection, @nertzy, @xaolas, @mrmcnerd, @martincostello, @svenkreiss 

Please, add these properties to the 'googlemaps/index.d.ts'.
The result should be like this:
```
        export interface AutocompletePrediction {
            description: string;
            matched_substrings: PredictionSubstring[];
            place_id: string;
            reference: string;
            structured_formatting: AutocompleteStructuredFormatting;
            terms: PredictionTerm[];
            types: string[];
        }
        
        export interface AutocompleteStructuredFormatting {
            main_text: string;
            main_text_matched_substrings: PredictionSubstring[];
            secondary_text: string;
        }
```
I know, that they are not presented on the Google Maps JavaScript API page, but there are in reality. I can receive them via js, not through REST web service.

Also the interface 'DirectionsWaypoint' would be more convenient as a class.

**Comment by mdorchain** [comment]
As mentioned above, the AutocompleteStructuredFormatting is missing.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
