### ISSUE TITLE
No onViewportChanged prop

### ISSUE THREAD

**Issue by bluerface** [DefinitelyTyped/DefinitelyTyped#22125]
- [x] I tried using the `@types/react-leaflet 1.1.4` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @danzel @davschne @yuit

The onViewportChanged prop does not seem to exist on the types. The code runs fine so I dont think its a spelling error  or missunderstanding of the docs etc.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
