### ISSUE TITLE
Type definitions for onChange handler don’t work when doing multiselect

### ISSUE THREAD

**Issue by stlcardsfan** [DefinitelyTyped/DefinitelyTyped#22132]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @giladgray @iebaker @skirsdeda @vujevits @devrelm @MartynasZilinskas @onatm @ninjaferret @ tehbi4

```
interface IAssessmentFactorSearchAnswer {
    readonly id: string;
    readonly label: string;
}

class MyAsyc extends Async<IAssessmentFactorSearchAnswer> {
}

public render() {
  return <MyAsyc
      ref="select"
      name={this.props.question.id}
      backspaceToRemoveMessage={""}
      value={this.state.value || ""}
      multi={true}
      minimumInput={3}
      loadOptions={this.getOptions}
      autoload={false}
      onBlur={this.handleBlur}
      onChange={this.handleChange}>
    </MyAsyc>;
}

 private handleChange(options: Option<IAssessmentFactorSearchAnswer> | Options<IAssessmentFactorSearchAnswer> | null) {
     if (Array.isArray(options)) {
         // do stuff
     }
}
```

To get my code to compile I had to type the handlechange as `Option<IAssessmentFactorSearchAnswer> | Options<IAssessmentFactorSearchAnswer> | null`
even though an array will always be sent to handlechange on an onChange event.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
