### ISSUE TITLE
Is there support for $(#foo).DataTable({ language: { select: {...}})?

### ISSUE THREAD

**Issue by saunandrea** [DefinitelyTyped/DefinitelyTyped#22145]
- [X] I tried using the `@types/datatables.net-select` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @szechyjs 

Hey Jared,

Maybe there is another type definition file I should try but the Datatable site for the dependency only lists select. Visual studio understands the "language:" but says that the select inside isn't a valid `parameter of type 'Settings'`.

From the [DataTables documentation](https://datatables.net/reference/option/language.select.rows#Types):
```

$('#example').DataTable( {
    language: {
        select: {
            rows: "%d rows selected"
        }
    },
    select: true
} );
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
