### ISSUE TITLE
Angular IRequestConfig optional method and url

### ISSUE THREAD

**Issue by marketvision-john** [DefinitelyTyped/DefinitelyTyped#2214]
Hi. Could you please make "method" and "url" in IRequestConfig interface of the Angular typing optional. For example it used in the "defaults" of the IHttpService and looks very strange in code. I think that also reasonable to change any in all the methods (get, post, etc) of the IHttpService to IRequestConfig and add <T> parameter. That would be event better. Thanks, Nick.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
