### ISSUE TITLE
[@types/atom] Missing definitions

### ISSUE THREAD

**Issue by lierdakil** [DefinitelyTyped/DefinitelyTyped#22211]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @GlenCFL @smhxx 

So, after working with these typings some more, I found I'm missing a few definitions, most of which are undocumented actually. Here they are (as interface augmentations):

```ts
interface TextEditor {
  bufferRangeForScopeAtPosition(scope: string, point: PointLike): Range
  tokenForBufferPosition(pos: PointLike): {value: string, scopes: string[]}
}
interface Grammar {
  scopeName: string
}
interface TextEditorElement extends Element {
  getModel(): TextEditor
}
interface AtomEnvironment {
  getConfigDirPath(): string
}
interface PackageManager {
  onDidTriggerActivationHook(hook: string, callback: () => void): Disposable
}
```

`bufferRangeForScopeAtPosition` works exactly like `bufferRangeForScopeAtCursor`, but for a buffer point instead of cursor: https://github.com/atom/atom/blob/3da8a892eaee5a37cde49e824baf68001a7275d0/src/text-editor.js#L3606

`tokenForBufferPosition` is defined nearby at https://github.com/atom/atom/blob/3da8a892eaee5a37cde49e824baf68001a7275d0/src/text-editor.js#L3624 -- it exposes a method from `tokenizedBuffer` and returns token text and array of scopes.

`Grammar.scopeName` should be rather self-explanatory. It's used rather extensively in Atom code base, perhaps rather interestingly, in `TextEditorComponent` to generate `data-grammar` attribute value: https://github.com/atom/atom/blob/3da8a892eaee5a37cde49e824baf68001a7275d0/src/text-editor-component.js#L470

`TextEditorElement` is not documented, but it's rather useful when binding commands to `atom-text-editor`: `CommandEvent.currentTarget` will always be `TextEditorElement` in that case. I use it to cast basically, but it might be useful for other purposes. `atom.views.getView(editor: TextEditor)` always yields `TextEditorElement`, btw.

`atom.getConfigDirPath()` is basically a thin wrapper around `process.env.ATOM_HOME`, but it caches, if nothing else: https://github.com/atom/atom/blob/ce8f300a3813e388c2c86142cfa76fe68ae0494b/src/atom-environment.js#L1186

`onDidTriggerActivationHook()` allows reacting to `grammar-used` activation hook, for example, from code. https://github.com/atom/atom/blob/3da8a892eaee5a37cde49e824baf68001a7275d0/src/package-manager.js#L731

Let me know if you think some of those should be included.

P.S. also might be interesting to get some `TextEditorComponent` stuff, like `screenPositionForPixelPosition`, `pixelPositionForScreenPosition`, `pixelPositionForMouseEvent` and `pixelPositionForMouseEvent`, but that stuff's *really* rarely needed.

**Comment by smhxx** [comment]
While normally I'd be hesitant to add definitions for undocumented methods and properties (since "undocumented" is often a stand-in for `private` in vanilla JS,) in this case it seems like most of these, if not all of them, are left out of the documentation by error rather than an intentional effort to keep them out of the API. The first example you gave, if not for the different name, could almost be considered an overload of an existing (documented) function... that indicates to me that it was probably quietly added during work on another feature, and just never made it into the docs.

At the very least, I think *all* of the missing methods should probably make their way into the defs, since methods - at least to my mind - are less likely to be changed unexpectedly than other properties. `Grammar.scopeName` seems to be stable enough as well, given its extensive use throughout Atom itself, and I don't see any harm in adding it, particularly if it's declared `readonly`.

The only one of these that I think I'm *against* adding would be `TextEditorElement`, unless I'm missing some functionality of that particular type that the `Element` class doesn't provide on its own. That's not to say that empty sub-classes added solely for type-checking purposes aren't useful, but I don't think I would force that distinction on users unless there actually is some fundamental difference between `Element` and `TextEditorElement` objects.

Overall, good work finding all this stuff. If @GlenCFL has no other objections, I'd be in support of adding these at any time.

**Comment by lierdakil** [comment]
> The only one of these that I think I'm against adding would be TextEditorElement

Note the definition:
```ts
interface TextEditorElement extends Element {
  getModel(): TextEditor
}
```
I personally find myself doing this rather often:
```ts
atom.commands.add('atom-text-editor', {
  'some-package:some-command': ({ currentTarget }) => {
    doStuff((currentTarget as TextEditorElement).getModel())
  },
})
```
I could cast as `any` of course, but this is not fun. On another note, overloading `atom.commands.add('atom-text-editor', ...` might be a better idea.

**Comment by lierdakil** [comment]
> On another note, overloading atom.commands.add('atom-text-editor', ... might be a better idea.

Might be, but it's going to be hacky at best.

**Comment by lierdakil** [comment]
Well, here's the general idea for how `TextEditorElement` could be useful: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/1953efc662b3b56f3060962cadc49feaecaf7fcb. Also, there's actually more to `TextEditorElement`: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/9fd06b63dc34f2693c8ea998f869c534e0fa9d90 (or see https://github.com/atom/atom/blob/3da8a892eaee5a37cde49e824baf68001a7275d0/src/text-editor-element.js)

**Comment by smhxx** [comment]
Now that I see the source code, I absolutely see the benefit of adding it as a class... it doesn't get much more explicit than `class TextEditorElement extends HTMLElement`. If it's an actual type within Atom's code that's exposed to the package authors and adds additional functionality to the existing Element type, I absolutely agree that it should be in the defs.

**Comment by GlenCFL** [comment]
I've used some of these myself, so I'm fine with them being added.

I'm also for the typing of the view side of the TextEditor class. The `atom-ide-ui` package uses this functionality, so I'd be sure that each definition that they use is defined, as well as the additional ones raised here. [TextEditorElement](https://github.com/atom/atom-languageclient/blob/v0.7.3/flow-libs/atom.js.flow#L956) and [TextEditorComponent](https://github.com/atom/atom-languageclient/blob/v0.7.3/flow-libs/atom.js.flow#L916).

One comment of note is:

>This is the element that is returned when you run atom.views.getView(TextEditor)`

That should be captured within our definitions.

**Comment by lierdakil** [comment]
> If it's an actual type within Atom's code that's exposed to package authors

I should probably point out, that the class isn't *directly* exposed. But it's registered as a custom HTML element, so it's easy enough to construct an instance with `document.createElement('atom-text-editor')`¹. Also, as I said, it's not rar to run into it when using `ViewRegistry` and `CommandRegistry` with `TextEditor`.

---
¹ Note to self: probably a good idea to add `'atom-text-editor': TextEditorElement` into `HTMLElementTagNameMap` while we're at it.
