### ISSUE TITLE
type definition not found for Dashboard and ControlWrapper

### ISSUE THREAD

**Issue by ingleashish** [DefinitelyTyped/DefinitelyTyped#22263]
- ui-google-combo-stacked-bar.component.ts(174,50): error TS2339: Property 'Dashboard' does not exist on type 'typeof visualization'.

- ui-google-combo-stacked-bar.component.ts(178,48):error TS2339: Property 'ControlWrapper' does not exist on type 'typeof visualization'.

- ui-google-combo-stacked-bar.component.ts(217,54):error TS2339: Property 'ControlWrapper' does not exist on type 'typeof visualization'.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
