### ISSUE TITLE
[@types/react-bootstrap] onClick missing from BreadcrumbItemProps

### ISSUE THREAD

**Issue by mshindal** [DefinitelyTyped/DefinitelyTyped#22271]
@aaronbeall @LKay @katbusch @vsiao @octatone 

In my code I created a `BreadcrumbItem` like this:

```
<BreadcrumbItem active={this.state.currentScreen === i} onClick={() => this.changeScreen(i)}>{s.title + ' '}</BreadcrumbItem>
```

I get this error:

```
TS2339: Property 'onClick' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<BreadcrumbItem> & Readonly<{ children?: ReactNode;...'.
```

The underlying component supports onClick, so the typings for `BreadcrumbItemProps` are wrong.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
