### ISSUE TITLE
[@types/jquery]  Cannot invoke an expression error in SuccessCallback type

### ISSUE THREAD

**Issue by mjmjelde** [DefinitelyTyped/DefinitelyTyped#22285]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu @borisyankov @choffmeister 

When using the following code:

```
public submit(req: JQueryAjaxSettings) {
    var oldSuccess = req.success;
    var oldError = req.error;
    const self = this;
    req.success = function(resp, xhr, status) {
        //Other processing
        if(oldSuccess) {
            oldSuccess(resp, xhr, status);
        }
    }
}
```

I get the following error message:
```
TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'TypeOrArray<SuccessCallback<any>>' has no compatible call signatures.
```
On the line:
```
            oldSuccess(resp, xhr, status);
```

Did a small test and removed the `TypeOrArray` around the `AjaxSettingsBase.success` type and the error goes away.  It may effect other function calls such as AjaxSettingsBase.error as well, just have not gotten that far into my code to test.

**Comment by leonard-thieu** [comment]
Since `success` can be `JQuery.Ajax.SuccessCallback<any>`, `JQuery.Ajax.SuccessCallback<any>[]`, or `undefined`, you need to indicate to the compiler that you know it will be `JQuery.Ajax.SuccessCallback<any>`. This can be done via a type assertion.

```typescript
var oldSuccess = req.success as JQuery.Ajax.SuccessCallback<any>;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
