### ISSUE TITLE
Types missing for HTML Elements on @types/react-jsonschema-form

### ISSUE THREAD

**Issue by johnrom** [DefinitelyTyped/DefinitelyTyped#22280]
- [x] I tried using the `@types/react-jsonschema-form` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @iamdanfox, @sirreal, @iplus26

If you try to use [HTML Form attributes](https://github.com/mozilla-services/react-jsonschema-form#form-attributes) on `Form` within react-jsonschema-form, TS shows an error like the one below, this one is for `method`.

`Property 'method' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Form> & Readonly<{ children?: ReactNode; }> & Read...`

**Comment by iplus26** [comment]
Pls show your code. `Form` of `react-jsonschema-form` is different from html `Form`

**Comment by johnrom** [comment]
Add a `react-jsonschema-form` to a typescript project and type

```
<Form action="/whatever"></Form>
```

`action` and various other html-like properties are valid for use on the Form element in `react-jsonschema-form` as I linked above.

**Comment by iplus26** [comment]
👍 Yes you're right. I think you can make a PR.

**Comment by epicfaace** [comment]
Since #22649 was closed, can this issue be closed now?

**Comment by johnrom** [comment]
I actually never ended up using `react-jsonschema-form`, so someone else will have to confirm, or maybe it can just be closed due to inactivity.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
