### ISSUE TITLE
Embedded discriminators in arrays

### ISSUE THREAD

**Issue by mike74vh** [DefinitelyTyped/DefinitelyTyped#22290]
Since 4.8.0 version of Mongoose, it's possible to use discriminator() function on DocumentArray.
It seems it's not implemented in this definition type file.
Can you implement it please ?

The idea is can do this example described in the mongoose documentation but with typescript :
```   
var eventSchema = new Schema({ message: String },
      { discriminatorKey: 'kind', _id: false });

    var batchSchema = new Schema({ events: [eventSchema] });

    // `batchSchema.path('events')` gets the mongoose `DocumentArray`
    var docArray = batchSchema.path('events');

    // The `events` array can contain 2 different types of events, a
    // 'clicked' event that requires an element id that was clicked...
    var clickedSchema = new Schema({
      element: {
        type: String,
        required: true
      }
    }, { _id: false });
    // Make sure to attach any hooks to `eventSchema` and `clickedSchema`
    // **before** calling `discriminator()`.
    var Clicked = docArray.discriminator('Clicked', clickedSchema);

    // ... and a 'purchased' event that requires the product that was purchased.
    var Purchased = docArray.discriminator('Purchased', new Schema({
      product: {
        type: String,
        required: true
      }
    }, { _id: false }));

    var Batch = db.model('EventBatch', batchSchema);
```

**Comment by hasezoey** [comment]
This can be closed because it got implement in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33014

@RyanCavanaugh
@andrewbranch
@horiuchi
@mike74vh 

*(i dont know how to tag for closure)*

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
