### ISSUE TITLE
[@types/chart.js] Missing usePointStyle options property

### ISSUE THREAD

**Issue by sinsunsan** [DefinitelyTyped/DefinitelyTyped#22293]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/chart.js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @anuti @FabienLavocat @KentarouTakeda @larrybahr @mernen @josefpaij

If you do not mention the authors the issue will be ignored.

I've used `@types/chart.js` along with chart.js version `2.7.1`

I've used the `usePointStyle: true` in `options.legend.labels.usePointStyle`
but it did not exist in `@types/charts.js` 

You can, for example, find the use of this property in one of the [sample](https://github.com/chartjs/Chart.js/blob/master/samples/legend/point-style.html#L96) of the library.

Here is my options for my use case. The purpose was to display legends as a circle.

````
options: {
        legend: {
          display: true,
          position: 'left',
          labels: {
            usePointStyle: true,
          },
        },
        tooltips: {
          enabled: true
        },
        title: {
          display: true,
          text: this.title,
          fontSize: 20,
          fontColor: '#0CB0FF',
        }
      }
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
