### ISSUE TITLE
Importy module @types/angularui

### ISSUE THREAD

**Issue by ojuniorbezerra** [DefinitelyTyped/DefinitelyTyped#22309]
hello,
every life I care like this: import 'jqueryui'; in my app.module.ts.
The compiler finds the module and does not show the compile error when I do this: $ ('.input-daterange'). datepicker ()
But, when I start the application **Can't resolve 'jqueryui'**

Where am I going wrong?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
