### ISSUE TITLE
js-yaml type definitions for LoadOptions incomplete

### ISSUE THREAD

**Issue by HyperBrain** [DefinitelyTyped/DefinitelyTyped#22400]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/js-yaml` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Bartvds , @sclausen 

If you do not mention the authors the issue will be ignored.

The definition of `LoadOptions` is missing the `onWarning` function property.

See js-yaml docs for LoadOptions (I'm using js-yaml 3.10.0:
> onWarning (default: null) - function to call on warning messages. Loader will throw on warnings if this function is not provided.

**Comment by sclausen** [comment]
> If you know how to fix the issue, make a pull request instead.

> HyperBrain - Engaged in software development since the 80's using a vast amount of languages like C/C++, JavaScript/Node.js, Java, Assembly language, ... and I still love it

**Comment by HyperBrain** [comment]
Hehe 😄 . Will fix it if I get some time, no problem.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
