### ISSUE TITLE
@types/three Accessing a Mesh's geometry property only responds with types for BufferGeometry, not Geometry

### ISSUE THREAD

**Issue by jon-grangien** [DefinitelyTyped/DefinitelyTyped#22436]
The Mesh constructor takes a union of Geometry and BufferGeometry
```typescript
export class Mesh extends Object3D {
    constructor(geometry?: Geometry | BufferGeometry, material?: Material | Material []);
//...
```

Create a mesh object, and pass a Geometry:
```typescript
// declarations:
private clothGeometry: THREE.Geometry
private clothMesh: THREE.Mesh

// implementation:
this.clothGeometry = new THREE.Geometry()
// ...work on geometry

this.clothMesh = new THREE.Mesh(this.clothGeometry, clothMaterial)
```

Now try to access a Geometry property like so:
```typescript
this.clothMesh.geometry.vertices
```
And we get TS2339: Property 'vertices' does not exist on type 'Geometry | BufferGeometry'.
  Property 'vertices' does not exist on type 'BufferGeometry'.

Jetbrains suggestions only list ones for BufferGeometry.

@gyohk @florentpoujol @omni360 @ivoisbelongtous @piranha771 @qszhusightp

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
