### ISSUE TITLE
bootstrap.v3.datetimepicker and eonasdan-bootstrap-datetimepicker are the same library

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#22456]
CC @ToastHawaii @katonap

These packages have the same underlying library, but a few differences:
* One declares `export as namespace BootstrapV3DatetimePicker;`, the other declares `export as namespace EonasdanBootstrapDatetimepicker;` I don't see mention of *either* of these global variables existing in the docs, so maybe it should just be deleted?
* They also disagree as to whether `JQuery.datetimepicker` is a property or a method.
* `eonasdan-bootstrap-datetimepicker` seems to include a lot more, but isn't updated as frequently.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
