### ISSUE TITLE
Auth0-Lock Auth0LockAdditionalSignUpField doesn't support "checkbox"

### ISSUE THREAD

**Issue by jason-capsule42** [DefinitelyTyped/DefinitelyTyped#22464]
If you know how to fix the issue, make a pull request instead.

- [ ] Auth0-Lock Auth0LockAdditionalSignUpField doesn't support "checkbox" (only supports "select" and "text")
- Authors: @scamden 

"checkbox" functionality defined here: https://auth0.com/docs/libraries/lock/v11/configuration#additionalsignupfields-array-

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
