### ISSUE TITLE
Devextreme support?

### ISSUE THREAD

**Issue by volkanalkilic** [DefinitelyTyped/DefinitelyTyped#22474]
Please add support for Devextreme. (https://js.devexpress.com/)

**Comment by micksatana** [comment]
Hi @volkanalkilic 

They seem to have type definitions in https://github.com/DevExpress/DevExtreme/blob/17_2/ts/dx.all.d.ts

Is that what you need?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
