### ISSUE TITLE
No types for VirtualizedList from "react-native"

### ISSUE THREAD

**Issue by Rolandisimo** [DefinitelyTyped/DefinitelyTyped#22495]
import { VirtualizedList } from "react-native"; // has no exported member 'VirtualizedList'.

Any roadmap to implement types for this?
Can this be marked as Definition: Request?

**Comment by kedwin** [comment]
any update on this ?

**Comment by AlekseyKolosovskiy** [comment]
no update after six months... dead place

**Comment by tenkeyless** [comment]
add this react-native index.d.ts

```javascript
export class VirtualizedList<ItemT> extends React.Component<
  VirtualizedListProps<ItemT>
> {
  scrollToEnd: (params?: { animated?: boolean }) => void;
  scrollToIndex: (
    params: {
      animated?: boolean;
      index: number;
      viewOffset?: number;
      viewPosition?: number;
    }
  ) => void;
  scrollToItem: (
    params: { animated?: boolean; item: ItemT; viewPosition?: number }
  ) => void;
  scrollToOffset: (params: { animated?: boolean; offset: number }) => void;
  recordInteraction: () => void;
}
```

**Comment by adambrenecki** [comment]
When I go to make a new issue on this repo it says to @-mention the authors of the file in question, otherwise it'll be ignored. Since this is an old issue, and that wasn't done here (presumably that issue template didn't exist when the issue was created), I'm gonna try mentioning them in a comment in the hopes that it helps:

@alloy @huhanming @iRoachie @Skn0tt @timwangdev @kamal @nelyousfi @alexdunne @swissmanu @bm-software @tkrotoff @a-tarasyuk @mvdam @Esemesek @mrnickel @souvik-ghosh @nossbigg @saranshkataria

**Comment by alloy** [comment]
@adambrenecki Thanks for the ping!

To address e.g. @zjh1943’s question, the maintainers of the react-native typings don’t really take requests–that is, we add what we use to ensure our additions are correct. So I would invite the people on this thread to do the same and submit a PR with typings that work for them (the ones by @tenkeyless look like a great starting point), after which we’ll be happy to review it!

**Comment by natsathorn** [comment]
Anyone here still got this issued?
This still happened on my machine.
