### ISSUE TITLE
zDepth and other inherited properties are missing

### ISSUE THREAD

**Issue by atrauzzi** [DefinitelyTyped/DefinitelyTyped#22524]
As per the title, many inherited properties aren't being exposed by the type definitions for react mui.

- [x] I tried using the `@types/material-ui` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/material-ui/index.d.ts) so they can respond.
  - Authors: @ngbrown @theigor @alitaheri @herrmanno @DaIgeb @allienna @schlesingermatthias @InsidersByte @artyomsv @dan-j @minodisk 

See: https://github.com/mui-org/material-ui/issues/3172

**Comment by oliviertassinari** [comment]
@atrauzzi I'm not sure it worse pushing this issue forward. We host the definitions now on v1-beta.

**Comment by atrauzzi** [comment]
That's no help to those of us still using `0.x.x` until 1 is final.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
