### ISSUE TITLE
Socket.io Client Declaration Error

### ISSUE THREAD

**Issue by anweiss** [DefinitelyTyped/DefinitelyTyped#2256]
Trying to use Socket.io in my client-side with jQuery as follows:

``` typescript
$(function() {
    var socket = io.connect('http://localhost:3000');
});
```

But getting the following error: `Could not find symbol 'io'`. I noticed that this error is described on the following StackOverflow question: http://stackoverflow.com/questions/20640400/unable-to-use-socket-io-in-typescript and that at one point there were a few lines added to the socket.io type declarations that resolved this. However, there doesn't seem to be an `io` variable declared in `socket.io.d.ts`.

**Comment by elisee** [comment]
For anyone encountering the same issue: You need to use `socket.io-client.d.ts` on the client-side, not `socket.io.d.ts` (which is for server-side stuff).

This issue can be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
