### ISSUE TITLE
jqueryui is missing checkboxradio

### ISSUE THREAD

**Issue by Tom4U** [DefinitelyTyped/DefinitelyTyped#22561]
**Declaration file for jqueryui doesn't contain declarations for checkboxradio() function.**

- [X] I tried using the `@types/jqueryui` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @johnnyreilly 

If you do not mention the authors the issue will be ignored.

**Comment by johnnyreilly** [comment]
Feel free to submit a PR!

**Comment by Tom4U** [comment]
Here's a first version including checkboxradio():

https://gist.github.com/Tom4U/b1dedd9a1e1b461e0da5d679f7b15382

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
