### ISSUE TITLE
update @types/leaflet.gridlayer.googlemutant

### ISSUE THREAD

**Issue by davidpadych** [DefinitelyTyped/DefinitelyTyped#22597]
Hello,
could I ask for a definition type update? Leaflet.GridLayer.GoogleMutant is now in version 0.6.4 

Thank you

- [ ] I tried using the `@types/leaflet.gridlayer.googlemutant` package and had problems.
- Authors: @ernest-rhinozeros

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
