### ISSUE TITLE
 [@types/react-navigation] NavigationContainer not generic

### ISSUE THREAD

**Issue by changhe3** [DefinitelyTyped/DefinitelyTyped#22604]
- [x] I tried using the `@types/react-navigation` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @huhuanming @mhcgrq @fangpenlin @abrahambotros @petejkim @iRoachie @phanalpha @charlesfamu @timwangdev @bang88 @svbutko

```typescript
export interface NavigationContainer extends React.ComponentClass<
  NavigationContainerProps & NavigationNavigatorProps<any>
> {
  router: NavigationRouter<any, any, any>;
  screenProps: { [key: string]: any };
  navigationOptions: any;
  state: { nav: NavigationState | null };
}
```

I am trying to integrate react navigation with redux ([using this tutorial](https://reactnavigation.org/docs/guides/redux)) and currently I have a TabNavigator as the top level navigator, however, it seems that NavigationContainer.router is not generically typed. If I want to have it type-checked, should I try to cast it a generic type like TabRouter<MyStateType, MyActionType, Options>, or are there any other components I should try?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
