### ISSUE TITLE
@types/socket.io-client policyPost vs policyPort

### ISSUE THREAD

**Issue by dbfup** [DefinitelyTyped/DefinitelyTyped#22617]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/socket.io-client/index.d.ts

"policyPost" should be replaced with "policyPort"

> error TS2345: Argument of type '{ 'reconnection': false; 'policyPort': number; 'forceNew': true; }' is not assignable to parameter of type 'ConnectOpts'.
> Object literal may only specify known properties, and ''policyPort'' does not exist in type 'ConnectOpts'.

Authors: @progre @divillysausages @florentpoujol

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
