### ISSUE TITLE
I wrote declaration files for the PlayCanvas game engine

### ISSUE THREAD

**Issue by snowfrogdev** [DefinitelyTyped/DefinitelyTyped#22625]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

I have written declaration file**s** for the [PlayCanvas](https://github.com/playcanvas/engine) game engine. The source code has a global structure under the `pc` namespace. I have copied the source's code file and folder structure when writing the declaration files. I have over 50 separate `d.ts` files and they all use `declare namespace pc {}`. I would now like to contribute these declaration files to DefinitelyTyped but looking at the docs I noticed that it seems to be required to put all the declarations in an index.d.ts file. How can I convert all my files and folders so that the whole thing is compatible with DefinitelyTyped? Can't I just keep my nice file and folder structure that matches the engine's source code?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
