### ISSUE TITLE
How can we make the issue tracker useful?

### ISSUE THREAD

**Issue by RyanCavanaugh** [DefinitelyTyped/DefinitelyTyped#22632]
We're currently sitting at 1,809 open issues, a number which hasn't really ever been useful to think about. The issue tracker seems to have three kinds of bugs:
 * Questions, e.g. #22625, #22474, #22093, #22005 
 * "Meta" bugs, e.g. #22475, #22221, #22172 
 * Specific problems (almost all of the rest)

As far as I can tell, no one is taking specific action on anything here. The oldest bugs are years old.

Feedback we've heard from contributors is that it's hard to "listen" for discussion or bugs related to .d.ts files they've worked on. And as we can see from the issue tracker, people who don't know how to contribute fixes aren't really getting results from filing issues on the issue tracker.

What would a *useful* DefinitelyTyped issue tracker look like?

**Comment by RyanCavanaugh** [comment]
One idea: Have "digest" issues that people can subscribe to or comment on so that a) more discussion occurs in centralized locations and b) interested parties can subscribe to notifications to packages they like. Example mockup https://github.com/RyanCavanaugh/DefinitelyTyped/issues/1

**Comment by johnnyreilly** [comment]
Worth a try - anything is better than the current quagmire!

**Comment by geovanisouza92** [comment]
I'm available for issue tracking. Reach me if I can help.

---

Another thing that could help, is find a way to reestructure the types directory, because it has thousands of directories, and it's kinda annoying listing it on github or making contributions.

**Comment by mhegazy** [comment]
A common question/request is asking for adding a new package. i think for these, we should direct users to creating a new PR with a pointer to https://github.com/Microsoft/dts-gen.

**Comment by johnnyreilly** [comment]
Excellent idea @mhegazy!

**Comment by geovanisouza92** [comment]
Another idea: write messages on console, asking for people share new typings for missing modules, after installing some `@types/*`. Something like:

```
$ npm install @types/...
@types/... added bla bla...

Hey, consider sharing your typings for missing modules you encounter.
```

---

There's a way to create a "PR cli", enabling users to create typings directly from files? I don't know, suppose that I have a `typings/xpto.d.ts` in my project for a given `xpto` module that doesn't have typings published yet. So, I wish to `dtd-gen --from-single-file typings/xpto.d.ts` and that creates a PR on DT repo. What do you think?

**Comment by iRoachie** [comment]
That’s a great idea, most of us if not all of us have a declarations.ts file in our src folder where we stub out definitions for libraries that don’t have official definitions. Would be great if we could take advantage of this.

**Comment by grant** [comment]
I'd propose writing down some goals and taking small steps:
## Goals
- Reduce quantity of issues
- Improve quality of issues
- All new issues should be in great shape (not duplicate, well formatted)

## Steps
- Manually clean/close old issues
  - Merge issues that talk about the same definition. Use GitHub task lists instead of multiple issues.
- Change the issue template to encourage searching existing issues and adding to those threads.
- Create a repo that's meant for
  - Gathering definition requests
  - Creating new definitions that can then be promoted to this repo.
- Get community help for managing these issues: #1834

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
