### ISSUE TITLE
View command in @types/npm

### ISSUE THREAD

**Issue by Vlad160** [DefinitelyTyped/DefinitelyTyped#22664]
- [x] I tried using the `@types/npm` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andy-ms 

```
npm.commands.view(args[], cb)
```
should have second argument as silent mode.

Found in source code:
```
function view (args, silent, cb) {
...
}
```

**Comment by andy-ms** [comment]
PRs accepted.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
