### ISSUE TITLE
"promisify" is missing in declaration for "util" module

### ISSUE THREAD

**Issue by rahulsethione** [DefinitelyTyped/DefinitelyTyped#22662]
util.promisify is not supported.

[Util | Node.js Documentation](https://nodejs.org/api/util.html#util_util_promisify_original)

**Comment by Flarna** [comment]
To my understanding it is: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L5565

Could you please be a little be more conrete with your problem? e.a. which version of typings, error message,...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
