### ISSUE TITLE
Alternative lib.d.ts

### ISSUE THREAD

**Issue by markrendle** [DefinitelyTyped/DefinitelyTyped#2267]
I was wondering if there had been any discussion about maybe creating an alternative (set of) definition file(s) to be used in place of lib.d.ts, to address the fact that it implements a bunch of stuff quite wrongly (e.g. ambient var declarations) and doesn't iterate fast enough to keep up with things like Chrome changing constructors for DOM4 types.

If not, can we use this issue to discuss that possibility? I'm willing to contribute to such an endeavour, but I think it might be a bit much for one person to take on.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
