### ISSUE TITLE
[@types/three] no vr in WebGLRenderer

### ISSUE THREAD

**Issue by pawelstan** [DefinitelyTyped/DefinitelyTyped#22676]
hey! why there is no vr property in WebGLRenderer?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
