### ISSUE TITLE
react-router Route lost props hinting

### ISSUE THREAD

**Issue by pocesar** [DefinitelyTyped/DefinitelyTyped#22687]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-router` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sergey-buturlakin @mrk21 @vasek17 @ngbrown @awendland @KostyaEsmukov @johnnyreilly  @LKay @DovydasNavickas @tkrotoff @huy-nguyen @grmiade @DaIgeb @egorshulga @neuoy @rraina

`Route` components are acting like `React.Component` without any props

![image](https://user-images.githubusercontent.com/461084/34595126-94decebc-f1bc-11e7-8f94-58369aa8fac8.png)

this current declaration is: 

```ts
export class Route<T extends RouteProps = RouteProps> extends React.Component<T, any> { }
```

AFAIK you can't provide the "custom" T using TSX syntax, so it's a problematic definition.

**Comment by huy-nguyen** [comment]
I think this has to do with the type definition for `react-router`, not `react-router-redux`.

**Comment by pocesar** [comment]
indeed, since `react-router-redux` depends on `react-router`, thought it was a all-in-one package

**Comment by mdeljavan** [comment]
I chaged the route component declaration to:
`export class Route extends React.Component<RouteProps, any> { }`
and everything is right.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
