### ISSUE TITLE
[Angular] Angular-resource should not override global Array interface

### ISSUE THREAD

**Issue by fredgalvao** [DefinitelyTyped/DefinitelyTyped#2274]
The angular-resource should not override/declare a global interface Array, as that messes up the original javascript definition.
Checking the history of the file, it seems that global interface definition was there to try to define the IResourceArray interface, which now works without the older Array override, so it should be very safe to just remove the global definition from the file.

**Comment by am-jo-zt** [comment]
+1 I get a lot of warnings that the property "length" can't be found because of this.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
