### ISSUE TITLE
@types/gl-matrix Why are types tagged/nominal?

### ISSUE THREAD

**Issue by spacejack** [DefinitelyTyped/DefinitelyTyped#22770]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mattijskneppers @nbabanov

`vec2` is defined like:

    export class vec2 extends Float32Array {
        private typeVec2: number;
        // ...

I don't believe the following should be prohibited:

    const out = new Float32Array(2)
    vec2.add(out, [1, 2], [2, 1])

    const out = [0, 0]
    vec2.add(out, [1, 2], [2, 1])

    const out = vec3.create()
    vec2.add(out, [1, 2], [2, 1])

I would think you should use `ArrayLike<number>` for inputs and outputs should `extend {[i: number]: number}`. For example:

    function add<T extends {[i: number]: number}> (out: T, a: ArrayLike<number>, b: ArrayLike<number>): T;

**Comment by spacejack** [comment]
Additionally I don't understand why these types are represented as classes at all. The underlying modules are plain function exports. One should be able to do:

    import * as vec2 from 'gl-matrix/vec2'
    import {add, sub} from 'gl-matrix/vec3'

etc. to benefit from tree shaking.

The library allows you to use any kind of array constructor, not just Float32Array. The factory functions should be typed more like:

    function create<T extends {[i: number]: number} = Float32Array>(): T

So that the following would work:

    const f32 = vec2.create()
    glMatrix.setMatrixArrayType(Array)
    const a: number[] = vec2.create()
    glMatrix.setMatrixArrayType(Float32Array)
    const f64 = vec2.create<Float64Array>()

**Comment by MattijsKneppers** [comment]
A partial answer:

- Array literals for input arguments should currently be allowed: 
`public static add(out: vec2, a: vec2 | number[], b: vec2 | number[]): vec2;`
- gl-matrix types are used for arguments instead of `ArrayLike<number>` because accidentally passing any other gl-matrix type than intended can result in runtime/behavior errors that are hard to debug, as discussed [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10166#issuecomment-234763309). If you see a practical scenario where allowing less strictly typed in/out arguments is beneficial it'd be good to discuss.
- Having all gl-matrix types extend Float32Array guarantees they can be passed directly to gl functions as discussed [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10166#issuecomment-234899720).

**Comment by spacejack** [comment]
My feeling is that these restrictions are too heavy handed and not really in the spirit of a general purpose library. Only the output is nominal, so that also seems inconsistent. Eg, I can still do:

    vec2.add(out, [1], [2])

One should also be able to use existing arrays or array views as outputs; not everything should need to be created via `*.create`.

Typescript can't verify that an array is of a specific length; I think that's a limitation that should be accepted and that users would be aware of that. I think it should be structurally typed only for maximum interop. (Vector classes used in libraries like three.js, cannon,js instead of structs are the cause of some of their biggest irritations IMO.)

Anyway, at present I don't have a pressing need for this lib, I was just doing some experimentation in a side project. I do feel the types should be reconsidered for general purpose use though.

**Comment by MattijsKneppers** [comment]
I proposed these changes after working with gl-matrix in several large-scale webgl projects where the biggest challenge was maintaining a sane code base and catching bugs before they subtly change the visual output of many dependent systems. In that context, IMO being notified as soon as possible when passing an incorrect type to a gl-matrix method is incredibly helpful. But I can imagine that when quickly putting together a prototype these limitations can slow one down. 

In the end I guess @toji who built the gl-matrix lib might have an opinion in this matter. From his code documentation I concluded that his preference would be the current implementation but that might be wrong.

**Comment by spacejack** [comment]
IMO types should never disable library features; ability to use the library should always trump type safety.

**Comment by toji** [comment]
With glMatrix I made a conscious decision to be extremely type agnostic to ensure that interop with other libraries and browser APIs was a simple as possible. It was (and still is) common to see apps where the 3D rendering library used it's own Matrix/Vector types, while the physics lib they use has it's own type, and then both need to be converted to TypedArrays anyway to pass into WebGL, etc. But in many cases the underlying values (at least for matrices) were stored in arrays anyway. So glMatrix says "Give me anything indexable with at least 16 elements and I'll assume it's a 4x4 matrix" and sidesteps the issue of whatever type your library wants to use altogether. (Example: If you're using Three.js you can pass `my_matrix.elements` into any glMatrix `mat4.` function and it works just fine.) This approach doesn't pan out in all situations, but it's proven remarkably versatile over the years.

The downside is that it absolutely leads to dev-time issues that could have been caught by something more strongly typed. I've personally been bitten by that many times. If I wasn't developing for Javascript I don't think I would have found it to be a reasonable tradeoff. But given the nature of the language and the realities of the ecosystem at the time it seemed appropriate.

Your mileage will definitely vary, and the choices glMatrix made should not be interpreted without appropriate context as an argument for or against strong typing.

**Comment by MattijsKneppers** [comment]
Thanks for elaborating @toji! 

It sounds as if it would be valuable to have both a stronger typed and a more general version. I'm not familiar with most of the infrastructure that depends on DefinitelyTyped so it's hard for me to tell how that should be set up in this repo. Perhaps @nkassis has a suggestion?

**Comment by spacejack** [comment]
@toji thanks for your input it's appreciated.

It's unfortunate I wasn't watching when these types were originally published otherwise I would have voiced my concerns then. As I mentioned earlier, I don't currently need these types for any current projects so I'm not going to press the issue. That said I'm willing to help if you decide to write an alternate version.

I doubt there is a way to supply two different versions of the types in the same repo. Ideally I think a general purpose version should have been the official types, and the custom nominal types could have been a separate npm package (eg. gl-matrix-nominal or similar.)

I assume I'm the only person who's raised an objection so far, and I don't want to break any existing projects.

**Comment by nkassis** [comment]
Yeah as @spacejack  as far as I know there isn't a way to have two version that could be used by npm but both version could be in the repo and used manually by checking out the file and adding it to a place that is in TS's definition search path. I've done that in the past while migrating my code to support the new definition. 

I think given the existence of setMatrixArrayType making the default support arraylike for matrix and vector probably makes sense.  Personally I've converted my code to use .create functions for out as I found it valuable to have the type check but I think the argument that it's too restrictive for a generic library is very fair. The use case above of using three.js or other matrix libraries' matrix classes instead of gl-matrix default matrix array type is a good justification I think.

**Comment by stefnotch** [comment]
> Typescript can't verify that an array is of a specific length

It seems that this is sort of possible
https://stackoverflow.com/questions/49910889/typescript-array-with-minimum-length

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
