### ISSUE TITLE
Typo: NightWatchBrowser should be NightwatchBrowser

### ISSUE THREAD

**Issue by krebbl** [DefinitelyTyped/DefinitelyTyped#22779]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/dd9e35eda05c60097bcca382408dd0a93f5a5b2d/types/nightwatch/index.d.ts#L10

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
