### ISSUE TITLE
@types/express-jwt : UnauthorizedError change

### ISSUE THREAD

**Issue by carmas123** [DefinitelyTyped/DefinitelyTyped#22781]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/express-jwt` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/wokim, https://github.com/kacepe, https://github.com/Sl1MBoy) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Sl1MBoy @kacepe @wokim 

If you do not mention the authors the issue will be ignored.

The export class UnauthorizedError  should be changed:

- FROM:
  ```
  export class UnauthorizedError extends Error  {
        name: string;
        message: string;
        code: string;
        status: number;
        inner: Error
    }
```

- TO:

```
    export type ErrorCode =
        "revoked_token"
        | "invalid_token"
        | "credentials_bad_scheme"
        | "credentials_bad_format"
        | "credentials_required";

    export class UnauthorizedError {

        /** 401 */
        status: number;
        message: string;
        name: "UnauthorizedError";
        code: ErrorCode;
        inner: { message: string };

        constructor(code: ErrorCode, error: { message: string });
    }
```

Thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
