### ISSUE TITLE
soundmanager2 definitions not a module

### ISSUE THREAD

**Issue by Robinfr** [DefinitelyTyped/DefinitelyTyped#22829]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/soundmanager2` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @elton2048 

When importing the soundmanager2 definitions I get the following error:

```
TS2306: File '/home/user/repos/project/node_modules/@types/soundmanager2/index.d.ts' is not a module.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
