### ISSUE TITLE
@types/xrm: Xrm.Entity is missing getEntityReference()

### ISSUE THREAD

**Issue by aappddeevv** [DefinitelyTyped/DefinitelyTyped#22836]
Per [https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/clientapi/reference/formcontext-data-entity/getentityreference]().

```typescript
namespace Xrm {
 namespace Entity {
   // should have
   getEntityReference(): LookupValue;
}
}
```
A quick fix is to use augmentation, so I added a patch.d.ts to my compilation path (e.g. ./src):
```typescript
declare namespace Xrm {
    interface Entity {
        getEntityReference(): Xrm.LookupValue;
    }
}
```

**Comment by carltoncolter** [comment]
I also noticed it was missing isValid and it had save marked as deprecated when save is not being deprecated.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
