### ISSUE TITLE
@types/xrm: type Xrm.FormNotificationLevel and XrmEnum.FormNotificationLevel Warning level is different, causes errors

### ISSUE THREAD

**Issue by aappddeevv** [DefinitelyTyped/DefinitelyTyped#22835]
I'm not sure which one to fix or if XrmEnum should not be used, but they are different for Warning so they are not interchangeable and give an error if you try to assign one to the other.

XrmEnum.FormNotificationLevel has Warning = "Warning" while the type has '...| "WARNING"'.

**Comment by carltoncolter** [comment]
The XrmEnum should be "WARNING" according to the documentation https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/clientapi/reference/formcontext-ui/setformnotification

**Comment by carltoncolter** [comment]
Hopefully this corrects the issues you were seeing.  Please continue to post any issues you identify here and make sure to tag them with @types/xrm.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
