### ISSUE TITLE
Editable method returning void, but expected to return Null / CKEDITOR.dom.element

### ISSUE THREAD

**Issue by abusomani** [DefinitelyTyped/DefinitelyTyped#22841]
I am using @types/ckeditor in my project. And was using the **"editable"** method.
But to my surprise this method was returning void and I was unable to attachListener to it unlike it is done in many examples of ckeditor. Even the official documentation of CKEDITOR for the same gives a return type of null or CKEDITOR.dom.element : https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.editor-method-editable
The error in the types definition is here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d0fdb3787e53609edcfe57578de1ce741aeb6950/types/ckeditor/index.d.ts#L1113-#L1114

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
