### ISSUE TITLE
@types/node no-implicit-dependencies

### ISSUE THREAD

**Issue by dolanmiu** [DefinitelyTyped/DefinitelyTyped#22906]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

I get this error when using `http2`, but not `http`:
```
[tslint] Module 'http2' is not listed as dependency in package.json (no-implicit-dependencies)
```

![image](https://user-images.githubusercontent.com/2917613/34925081-fae2933a-f99e-11e7-8b19-32c391532cce.png)

@jkomyno
@ajafff 
@Hannes-Magnusson-CK 
@eps1lon

**Comment by ajafff** [comment]
The TSLint rule `no-implicit-dependencies` currently works by getting a list of builtin modules from the current node version it runs in. That means you need to use node 9.x with the flag `--expose-http2` for linting, otherwise TSLint doesn't know there is a `http2` builtin module.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
