### ISSUE TITLE
winjs.d.ts: Maintaining different versions of the d.ts file for different versions of WinJS

### ISSUE THREAD

**Issue by jseanxu** [DefinitelyTyped/DefinitelyTyped#2293]
Hi @borisyankov ,

I'm a dev on WinJS and am looking into how we could maintain different versions/branches of winjs.d.ts for different versions of WinJS.

Since we continue to support WinJS 1.0 and 2.0, along with 2.1 and the next versions, we'd like to create typescript definition files for each version of WinJS. Do you have a pattern for maintaining different versions with d.ts files for other frameworks on DefinitelyTyped?

Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
