### ISSUE TITLE
react-table: Property  does not exist on type 'object'.

### ISSUE THREAD

**Issue by gutenye** [DefinitelyTyped/DefinitelyTyped#22947]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @royxue @psakalo @Havret 

If you do not mention the authors the issue will be ignored.

Given

```jsx
<ReactTable
  columns={[
    { name: 'Foo', id: 'foo', accessor: row => row.foo }
  ]}
/>
```

Got

```
Property  'foo' does not exist on type 'object'.
```

Expected

```
Does not throw an error.
```

For, row is typed as `object` type ([source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-table/index.d.ts#L9)), Which is incorrect, [object type](https://blog.mariusschulz.com/2017/02/24/typescript-2-2-the-object-type) has a very limited use case and should not be used here. Instead row should be typed as `any`

**Comment by Havret** [comment]
I will submit PR.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
