### ISSUE TITLE
@types/cassandra-driver methods promise

### ISSUE THREAD

**Issue by matte00** [DefinitelyTyped/DefinitelyTyped#22960]
- [X] I tried using the `@types/cassandra-driver` version 3.2.3 and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- Authors: @ywceric  @andy-ms @zspitz 

Not all methods with Promise support are implemented. 
Example: Metadata#getTable() and more...
See [Datastax's official documentation](http://docs.datastax.com/en/developer/nodejs-driver/3.3/features/promise-callback/) and [this](http://docs.datastax.com/en/developer/nodejs-driver/3.3/features/metadata/)

**Comment by andy-ms** [comment]
Pull requests accepted.

**Comment by michal-b-kaminski** [comment]
I think this was fixed in #32806, at least concerning `Metadata` namespace.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
