### ISSUE TITLE
@types/c3 tooltip order property

### ISSUE THREAD

**Issue by euginio** [DefinitelyTyped/DefinitelyTyped#22973]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/c3` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @mcliment @gerinjacob @denyo 

The definition file has not "order" property in TooltipOptions interface, but the feature exist in version 0.4.18 of c3. I think to pull request something like that:

    /**
     * Set tooltip values order
     */
    order?: undefined | string[] | ((data: Data) => boolean);

am I ok?

**Comment by iansan5653** [comment]
This should be fixed as of PR #37139. Please verify that the definition is correct.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
