### ISSUE TITLE
What about splitting up lodash index.ts?

### ISSUE THREAD

**Issue by DomiR** [DefinitelyTyped/DefinitelyTyped#23047]
Hey @aj-r, @ericanderson,

I would love to discuss the possibility to split up the `index.ts` into smaller files to regain maintainability.

For instance `const shouldBeString = _.get<string>(naughtyObjectThatCouldBeNull, 'path.to.string')` worked at some point and broke and the history for the `index.ts` is not readable.
It's was useful for writing formatters: 
`const formatTitle = foo => _.get<string>(foo, 'path.to.title', 'default')`

I think a good structure would be to have a definition and a test file per function and folders for grouping functionality like so:
```js
   index.ts
   common.ts
   --collections
     |--map.ts
     |--map-tests.ts
     |--flatMap.ts
     |--flatMap-tests.ts
   --arrays
```

Before I start to work on a pull request, I would love to get your feedback. If you think some other maintainer should be involved in the discussion please mention him/her.

**Comment by DomiR** [comment]
Or maybe better leave the current flat structure and move the definitions to the small files adding tests for them...

**Comment by aj-r** [comment]
I'm open to the idea.

Some initial thoughts: as you've noticed, we already have individual files for each function, and all they do is import one specific lodash function and re-export it. I think it would make more sense if we did it the other way around: each individual file defines one function, then `index.d.ts` imports all of those functions and re-exports them.

However, there might be a problem with the chain version of the functions - we probably shouldn't export them as part of the individual packages (e.g. `lodash.get`), because if someone does `npm install lodash.get`, they shouldn't get the chain versions. However, `index.d.ts` needs to have the chain versions. So we might 2 files for each function: one that defines both the normal and chain versions of the function, and one that re-exports only the normal version. Plus maybe a 3rd file for unit tests. Alternatively, if you can think of a better way to get around this problem, I'm all ears.

**Comment by aj-r** [comment]
As for your `_.get` problem, you probably want to remove the `<string>`. The new way to use `_.get` (and pretty much every other lodash function) is to NOT explicitly pass in any type parameters. So you should do this:

```ts
const shouldBeString: string | undefined = _.get(naughtyObjectThatCouldBeNull, 'path.to.string');
```

Note that `_.get` will return `any` now, so you should probably explicitly set your variable type to `string | undefined`. Also, you can remove the `| undefined` if you're not using `strictNullChecks`.

**Comment by aj-r** [comment]
@andy-ms I believe this should be closed
