### ISSUE TITLE
Add typings for Swiper@^4.1.0

### ISSUE THREAD

**Issue by odahcam** [DefinitelyTyped/DefinitelyTyped#23056]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the [`@types/swiper`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1b54a38a4354106cdf445d6c75f149c73a5aa28a/types/swiper/v2/index.d.ts) package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sistemico 

Related Swiper repository's issue: https://github.com/nolimits4web/Swiper/issues/2441

I can write some interfaces, but I don't know how to declare anything like modules.

**Comment by odahcam** [comment]
I started something here: https://github.com/odahcam/DefinitelyTyped/blob/master/types/swiper/v4/index.d.ts

Any help will be higly appreciated!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
