### ISSUE TITLE
Lodash: Weak type of key at forEach

### ISSUE THREAD

**Issue by Xenya0815** [DefinitelyTyped/DefinitelyTyped#23076]
I tried to use the `forEach` function to iterate over an plain object. Inside the iteratee I want to add a exhaustive check to get an error for forgotten keys.

But I can't do it because the `ObjectIterator` is defined as `(value: TObject[keyof TObject], key: string, collection: TObject) => TResult`. And the following comment has been added at the .d.ts file:

> key should be string, not keyof T, because the actual object may contain extra properties that were not specified in the type.

Is it good to have a weak type here instead of `key: keyof T`? In the most cases typescript is used in order to avoid mistakes. If you are really in the situation that you need a weak type, I would prefer to implement it epxlicitly:

    forEach<{[key: string]: any}>(...)

For the reverse way (to cast a weak function parameter to a more specific one), I do not see an option that has no rumtime disadvantages (except it's a simple iteratee, for example with only one switch where I can use `as keyof` at the expression): Assign it to an extra variable with `as keyof` or call a extra function with `as kesof`. (If there is a more elegant solution, I would be interested in it to learn typescript better.)

Even if there is a more elegant solution, I prefer to weaken a strict type check explicitly, than the reverse way.

- [x ] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @ericanderson @aj-r @ailrun @e-cloud @thorn0 @jtmthf

**Comment by aj-r** [comment]
I still think it's better to give you the more general type, and have you explicitly cast to a more specific type in cases where you're sure that's okay. The reason being that the more general type requires you to handle more situations in your code, so it forces you to avoid mistakes that way. The stricter type (`keyof T`) would allow you to make these mistakes in some cases.

However, I can see how this might be annoying, since most of the time `keyof T` instead of `string` should be fine. Open to feedback from people who know a little more about typescript best practices (@andy-ms ?).

One option I see is allowing both types of iterator functions (`key: string` and `key: keyof T`). We would use the string version by default, but if someone explicitly specifies `key: keyof T` in the function definition, we allow that, too. i.e. something like this:

```ts
type ObjectIterator<TObject, TResult> = (value: TObject[keyof TObject], key: string, collection: TObject) => TResult;
type StrictObjectIterator<TObject, TResult> = (value: TObject[keyof TObject], key: keyof TObject, collection: TObject) => TResult;

forEach<T extends object>(collection: T, iteratee?: ObjectIterator<T, any>): T;
forEach<T extends object>(collection: T, iteratee: StrictObjectIterator<T, any>): T;
```

Then both of these would work:

```ts
const obj = { a: 1, b: 2 };
_.forEach(obj, (value, key) => {
    // key has type string
});
_.forEach(obj, (value, key: keyof typeof obj) => {
    // key has type "a" | "b"

});
```

Note that the second version (`key: keyof typeof obj`) actually works already if you turn off `strictFunctionTypes`. However I don't recommend turning off `strictFunctionTypes`, so we should add `StrictObjectIterator` if we want to allow this. On the other hand, though, if you're strict enough to be using `strictFunctionTypes`, then maybe we shouldn't be allowing this, and instead forcing you to create a variable (e.g. `const key2 = key as keyof typeof obj;`).

**Comment by andnp** [comment]
I agree with the ability to opt into more precise types, but defaulting to more generic (and thus more safe) types. I think that @aj-r 's proposed solution makes the most sense here, and would alleviate a decent amount of headache when I _know_ that the object can only have keys `'a' | 'b'`.

**Comment by OliverJAsh** [comment]
@Xenya0815 FYI there's a typo in the title which might make this issue hard to find. "Loadash" should "Lodash". Would you mind fixing that?

Related: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22160

> allowing both types of iterator functions

Interestingly this [already works with `map`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22160#issuecomment-351595604):

``` ts
// with `strictFunctionTypes` enabled

const obj = { a: 'foo', b: 1 };

// Error
_.forEach(obj, (value, key: 'a' | 'b', collection) => {});
// No error
_.map(obj, (value, key: 'a' | 'b', collection) => {});
```

One potential other workaround:

``` ts
// Same as Lodash's `ObjectIterator`, but the `key` parameter is narrowed to `keyof` instead of
// `string`.
type BetterObjectIterator<TObject, TResult> = (
  value: TObject[keyof TObject],
  key: keyof TObject,
  collection: TObject,
) => TResult;

const convertObjectIterator = <T extends object, TResult>(
  iterator: BetterObjectIterator<T, TResult>,
): ObjectIterator<T, TResult> => (val, key, collection) =>
  iterator(val, key as keyof T, collection);
// or
// const convertObjectIterator = <T extends object, TResult>(
//   iterator: BetterObjectIterator<T, TResult>,
// ) => iterator as ObjectIterator<T, TResult>;

forEach(
  { a: 1 },
  convertObjectIterator((v, k) => {
    k; // "a"
  }),
);
```

**Comment by st-sloth** [comment]
> On the other hand, though, if you're strict enough to be using `strictFunctionTypes`, then maybe we shouldn't be allowing this, and instead forcing you to create a variable (e.g. `const key2 = key as keyof typeof obj;`).

is perfectly valid point.

However, there is the DX issue with first trying to satisfy the function types, then going through the type sources, then searching and going through the discussions about the topic like this one and #27954 and finding the reasoning and workarounds, and then writing more boilerplate.
And a possibility to specify a narrowed `ObjectIterator` like in @aj-r 's solution would be nice to have to eliminate that.

Would it make sense to implement a PR?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
