### ISSUE TITLE
validator module types pollute the global namespace

### ISSUE THREAD

**Issue by shivanshu3** [DefinitelyTyped/DefinitelyTyped#23097]
@tgfjt @chrootsu @IOAyman @louy @kacepe @deptno

Hi!

I installed the declaration file for the `validator` module, and noticed that it pollutes the global namespace of all my modules with the following symbols:

- ValidatorJS
- validator
- IValidatorStatic
- IURLoptions
- IFQDNoptions
- IEmailoptions

So if I use any of these symbols in my modules without importing them, TypeScript compilation succeeds, but obviously, I get failures at runtime.

I'm new to TypeScript, so I don't know how to fix this, or if this is by design. But all the other declaration files that I have used force you to import the types before using them, which makes sense.

I feel like only the built in classes like `Array`, `Buffer`, `Object`, etc. should be present in the global namespace, and the 3rd party types should not.

**Comment by aluanhaddad** [comment]
You're correct. That definition needs to be updated. It is a lot of work because of all the subpackages.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
