### ISSUE TITLE
cant get photo_reference or photo raw_reference 

### ISSUE THREAD

**Issue by warbadev** [DefinitelyTyped/DefinitelyTyped#23090]
If you know how to fix the issue, make a pull request instead.

- [yes ] I tried using the `@types/googlemaps` package and had problems.
- [yes ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ yes] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ok] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
 Authors: @cgwrench, @Silver-Connection, @nertzy, @xaolas, @mrmcnerd, @martincostello, @svenkreiss

If you do not mention the authors the issue will be ignored.

the problem is am trying to get the photos regarding the places i got 
but there is no parameter for photo_reference as described in google places documents

even though i check the console and there is a raw_reference  which is part of photos[] but i only get it from google api 
so if u can please add it in  index.d.t so that i can use it in my apps
regards

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
