### ISSUE TITLE
JQueryEventObject.originalEvent does not recognize DataTransfer Events 

### ISSUE THREAD

**Issue by xperiments** [DefinitelyTyped/DefinitelyTyped#2311]
As for definition:

interface JQueryPopStateEventObject extends BaseJQueryEventObject {
    originalEvent: PopStateEvent;
}

interface JQueryEventObject extends BaseJQueryEventObject, JQueryInputEventObject, JQueryMouseEventObject, JQueryKeyEventObject, JQueryPopStateEventObject {
}

Managed to "fix" it overloading def as:

interface JQueryEventObject
{
    originalEvent:any;
}

and:

element.bind('drop', function(event:JQueryEventObject) {
    ...
    (<DataTransfer>event.originalEvent.dataTransfer).files[0];
    ...
})

What is the correct definition for this usage...

**Comment by DonaldMcInnes** [comment]
The above fix didn't work for me, but what did was overloading interface JQueryMouseEventObject as:

interface JQueryMouseEventObject
{
    dataTransfer: any;
}

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
