### ISSUE TITLE
@types/react-select type definition update

### ISSUE THREAD

**Issue by jofbe** [DefinitelyTyped/DefinitelyTyped#23161]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-select` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Hesquibet @giladgray @iebaker @skirsdeda @vujevits @devrelm @MartynasZilinskas @onatm @ninjaferret @tehbi4

Hi,

I wanted to use a feature of the v1.2.1 of the react-select plugin (clearRenderer function), but the type definition is not up-to-date yet. Can you guys update it, so it would have all the current functionalities?

Thanks!

**Comment by FredyC** [comment]
@jofbe I suppose you can close this since there is a ReactSelect v2 for quite some time now? Nobody is probably going to bother with V1 anymore.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
