### ISSUE TITLE
types of react-table have no exported value ReactTableDefaults

### ISSUE THREAD

**Issue by eakarpov** [DefinitelyTyped/DefinitelyTyped#23193]
@types/react-table has no exported value ReactTableDefaults, so typescript compiler throws an error.

- [x] I tried using the `@types/react-table` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @royxue, @psakalo, @Havret

Example of the code producing the error
```typescript
import {ReactTableDefaults} from 'react-table';
import {I18n} from 'react-redux-i18n';

Object.assign(ReactTableDefaults, {
  PreviousComponent: (props) =>
    <button onClick={props.onClick} className='btn btn-default' disabled={props.disabled}>
      {I18n.t('prev')}
    </button>,
  NextComponent: (props) =>
    <button onClick={props.onClick} className='btn btn-default' disabled={props.disabled}>
      {I18n.t('next')}
    </button>,
});
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
