### ISSUE TITLE
Private Knex types

### ISSUE THREAD

**Issue by jwhitmarsh** [DefinitelyTyped/DefinitelyTyped#23258]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1254d58f4afc5e2d361656aecc3c7a51e1bc10db/types/knex/index.d.ts#L17-L21

Is there a reason these types aren't exported? I'm in a situation where I need to use the `Value` type. I'm quite new to TS so apologies if this can already be achieved, but I just can't seem to!

**Comment by taybin** [comment]
This can be closed as knex provides its own definitions now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
