### ISSUE TITLE
Request typings for "store/plugins"

### ISSUE THREAD

**Issue by koyta** [DefinitelyTyped/DefinitelyTyped#23269]
If you know how to fix the issue, make a pull request instead.

- [ OK] I tried using the `@types/storejs` package and had problems.
- [ OK] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @marcuswestin

Requesting typings for all Store.js plugins.

**Comment by bokub** [comment]
I think you're talking about [store](https://www.npmjs.com/package/store), and not [storejs](https://www.npmjs.com/package/storejs), but you tried to use `@types/storejs`, which explains why you had errors.

But yeah, `@types/store` would be great to have, especially when you see how popular it is.

**Comment by koyta** [comment]
@bokub you are totally right.

**Comment by damianon** [comment]
Has any progress been made on this? Types for the extensions (e.g. expire) would be great, because otherwise it's not really useable with typescript

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
