### ISSUE TITLE
[lodash] `_.pick` does not accept `ReadonlyArray`

### ISSUE THREAD

**Issue by rhys-vdw** [DefinitelyTyped/DefinitelyTyped#23278]
Sorry, I do know how to fix this, but Lodash's types are so well maintained I thought that perhaps I should ask first if there was some reasoning behind it.

Currently it's invalid to do this:

```ts
import { pick } from "lodash"

interface Foo {
  bar: number,
  baz: number,
}

const foo: Foo = { bar: 0, baz: 1 }
const props: ReadonlyArray<keyof Foo> = ["bar"]
pick(foo, props)
```

![image](https://user-images.githubusercontent.com/822105/35553010-2f540304-05ea-11e8-9941-601a81914916.png)

I would be shocked if Lodash was mutating that array.

CC:
@andy-ms
@bczengel
@chrootsu
@stepancar
@ericanderson
@aj-r
@ailrun
@e-cloud
@thorn0
@jtmthf
@DomiR

**Comment by thorn0** [comment]
It's indeed maintained well, kudos to @aj-r, however there is always a great deal of room for improvement just because, as someone wrote here, lodash is a "JS-first library" written without TypeScript in mind, so its API is highly dynamic and really tricky to write definitions for. There is a lot of complicated issues with these typings, that's why smaller things like readonlyness of that array go unnoticed. PRs are always welcome.

**Comment by aj-r** [comment]
My guess is that we should be using `List<PropertyName>` instead of
`PropertyName[]`.

**Comment by thorn0** [comment]
@aj-r Internally it does an `isArray` check, so this doesn't work:
```js
_.get({a:{b:1}}, {0:'a',1:'b',length:2})
// undefined
```
So `ReadonlyArray` seems to be a better option.

**Comment by aj-r** [comment]
Looks like there are a lot of open lodash issues right now. I'd appreciate if anyone made a PR for this (@bczengel @chrootsu @stepancar @ericanderson @https://github.com/ailrun @https://github.com/e-cloud @thorn0 @jtmthf @Domir). Just comment here if you're working on it so we don't step on each other's feet :)

**Comment by thorn0** [comment]
This one seems trivial. I'll do it.
