### ISSUE TITLE
Possible regression in @types/request-promise-native 1.10.12 ?

### ISSUE THREAD

**Issue by jbreckmckye** [DefinitelyTyped/DefinitelyTyped#23291]
FAO @gustavohenke 

I'm using request-promise-native 1.0.5. When I tried using @types/request-promise-native 1.0.12 I saw the following compile error:

`Property '[Symbol.toStringTag]' is missing in type 'RequestPromise'.`

I think TSC believes request-promise-native is returning a "Promise-like" rather than a `Promise`.

This issue does not exist with @types/request-promise-native 1.0.10

**Comment by GooSP** [comment]
Same problem here with equest-promise-native 1.0.5. Downgrading typing to 1.0.10 works.

**Comment by gustavohenke** [comment]
See #23087, cc @mastermatt

**Comment by mastermatt** [comment]
This is correct, `request-promise-native` does **not** return a `Promise`.
Check the PR linked above for a description and links to relevant code.
```ts
    const rp = requestPromise.get("http://github.com");
    console.log(typeof rp); // object
    console.log(Object.prototype.toString.call(rp)); // [object Object]
    console.log(rp.toString()); // [object Object]
    console.log(rp.toStringTag); // undefined
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
