### ISSUE TITLE
[@types/lodash] _.every treats object as NumericDictionary

### ISSUE THREAD

**Issue by zuzusik** [DefinitelyTyped/DefinitelyTyped#23317]
Starting from version `4.14.78` following code

```js
const matches = _.every({a: 'some', b: 'another'}, (value, key) => key === 'b' || value === 'some');
```

gives me 2 errors:

```
Error:(1, 52) TS2345: Argument of type '(value: {}, key: number) => boolean' is not assignable to parameter of type 'ObjectIteratee<{ a: string; }>'.
  Type '(value: {}, key: number) => boolean' is not assignable to type 'ObjectIterator<{ a: string; }, any>'.
    Types of parameters 'key' and 'key' are incompatible.
      Type 'string' is not assignable to type 'number'.
Error:(1, 68) TS2365: Operator '===' cannot be applied to types 'number' and 'string'.
```

The thing is that with `4.14.77` `_.every` in this case was resolved to
```ts
every<T>(
  collection: Dictionary<T> | null | undefined,
  predicate?: DictionaryIterator<T, boolean>
): boolean;
```
which is right resolution

And with with `4.14.78` it started to be resolved to 

```ts
every<T>(
  collection: NumericDictionary<T> | null | undefined,
  predicate?: NumericDictionaryIteratee<T>
): boolean;
```
which is wrong

this was brought by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19356

@aj-r in this PR the `Dictionary` variant of `_.every` typing was just removed

what was the reason behind this decision and should we bring it back?

**Comment by aj-r** [comment]
I'll look into it. In general the dictionary overloads were replaced with
object overloads.

**Comment by aj-r** [comment]
This actually looks like a typescript bug. If you omit the `key` parameter, you get the right overload:

```ts
_.every({a: 'some', b: 'another'}, (value) => value === 'some');
```

...and it compiles successfully.

Furthermore, adding all 3 callback parameters gives yet another error message:

```ts
_.every({a: 'some', b: 'another'}, (value, key, coll) => value === 'some');
```

```
src\test.ts (6,26): Argument of type '{ a: string; b: string; }' is not assignable to parameter of type 'NumericDictionary<{}> | null | undefined'.
  Object literal may only specify known properties, and 'a' does not exist in type 'NumericDictionary<{}> | null | undefined'. (2345)
src\test.ts (6,74): Operator '===' cannot be applied to types 'number' and 'string'. (2365)
```

I can't imagine how changing the number of callback parameters should change which overload is selected, since all overloads have the same number of callback parameters.

This works in typescript 2.4 and seems to have broken in typescript 2.5. So you can fix it by reverting to an old typescript. Alternatively you can use this workaround to force it to use the correct overload:

```ts
const obj = {a: 'some', b: 'another'};
const matches = _.every<typeof obj>(obj, (value, key) => key === 'b' || value === 'some');
// or:
const matches = _.every<_.Dictionary<string>>({a: 'some', b: 'another'}, (value, key) => key === 'b' || value === 'some');
```

**Comment by zuzusik** [comment]
Interesting! 

I definitely wouldn't like to downgrade TS because of this.

For now I worked around with specifying `string` type of key explicitly:

```ts
const matches = _.every(
  {a: 'some', b: 'another'}, 
  (value, key : string) => key === 'b' || value === 'some'
);
```

**Comment by zuzusik** [comment]
@aj-r according to this comment https://github.com/Microsoft/TypeScript/issues/21525#issuecomment-362349470 this is design limitation for now
So I believe we should work-around it here, in `DT`
I guess the easiest way would be to get back `Dictionary` variant of overload.
What do you think?

**Comment by aj-r** [comment]
Not sure how I feel about that. The dictionary overload is completely
redundant with the object overload. We could try moving the object overload
to be before the NumericDictionary, but that might break thinks for anyone
using a NumericDictionary. Some experimentation/testing will be needed.

**Comment by zuzusik** [comment]
Yeah, that's true. Previously it was not blowing just because it was going to `Dictionary` first. Looks like before it was blowing for overloads that follow `Dictionary` one, right?

**Comment by aj-r** [comment]
Looks like there are a lot of open lodash issues right now. I'd appreciate if anyone made a PR for this (@bczengel @chrootsu @stepancar @ericanderson @https://github.com/ailrun @https://github.com/e-cloud @thorn0 @jtmthf @Domir). Just comment here if you're working on it so we don't step on each other's feet :)

**Comment by aj-r** [comment]
@zuzusik we've had some recent changes with the `NumericDictionary` overloads - try with the latest version of lodash and see if this is fixed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
