### ISSUE TITLE
Joi objects.ChoiceOption

### ISSUE THREAD

**Issue by tomaz-smid** [DefinitelyTyped/DefinitelyTyped#23353]
- [x] I tried using the `@types/joi` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Definitions by: Qubo <https://github.com/tkQubo>
                 Parvez <https://github.com/ppathan>
                 Jouderian <https://github.com/jouderianjr>

@tkqubo 
@ppathan 
@jouderianjr

in 

interface ChoiceOption {
            name?: string;
            value?: string;
            type?: string;
            extra?: any;
            key?: string;
            checked?: boolean;
            disabled?: string | ((answers: Answers) => any);
        }

I think property "value" can be any, is this not so?

**Comment by SimonSchick** [comment]
I think this can be closed, this interface doesn't even exist in joi.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
