### ISSUE TITLE
How to exend ReplyNoContinue to use inert .file method?

### ISSUE THREAD

**Issue by gino8080** [DefinitelyTyped/DefinitelyTyped#23367]
hello please can someone show me how to use inert .file method with type definition?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/04dca3a08177dbcba2afc53323d38316698b360a/types/hapi/index.d.ts#L189

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
