### ISSUE TITLE
knockout.validation: KnockoutValidationRuleBase missing params?

### ISSUE THREAD

**Issue by markostimac** [DefinitelyTyped/DefinitelyTyped#23372]
Should `KnockoutValidationRuleBase` interface contain the `params: any` property?

Consider the case of defining Anonymous Custom Rules:
https://github.com/Knockout-Contrib/Knockout-Validation/wiki/Custom-Validation-Rules#anonymous-or-single-use-custom-rules

```
var testObj = ko.observable(3).extend({
   validation: {
      validator: function (val, someOtherVal) {
         return val === someOtherVal;
      },
      message: 'Must Equal 5',
      params: 5
   }
});
```

`validation` is defined as `KnockoutValidationRuleDefinition` which inherits from `KnockoutValidationRuleBase`, so we have definitions for `validator` and `message`, but we're missing the `params` property.

@danludwig

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
