### ISSUE TITLE
react-select missing exports

### ISSUE THREAD

**Issue by ff2005** [DefinitelyTyped/DefinitelyTyped#23431]
If you know how to fix the issue, make a pull request instead.

- [ X ] I tried using the `@types/react-select` package and had problems.
- Authors: @Hesquibet, @giladgray @iebaker, @skirsdeda, @vujevits, @devrelm, 
 @MartynasZilinskas, @onatm, @ninjaferret, @tehbi4, @misantronic

This typed def need to be updated, there are missing thing like exports for defaultMenuRenderer, defaultArrowRenderer, defaultClearRenderer, defaultFilterOptions.

**Comment by ff2005** [comment]
I needed to add this:

export function defaultMenuRenderer<TValue = OptionValues>(params: MenuRendererProps<TValue>): HandlerRendererResult;

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
