### ISSUE TITLE
BasicVerifyFunction needs a different signature with options = {passReqToCallback: true}

### ISSUE THREAD

**Issue by darkbasic** [DefinitelyTyped/DefinitelyTyped#23432]
- [x] I tried using the `@types/passport-http` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi @enaeseth @theigor @tlaziuk @krizalys 

```
passport.use('basic-signup', new basicStrategy.BasicStrategy({passReqToCallback: true},
  function (req, username, password, done) {}
));
```

When you set `{passReqToCallback: true}` the signature of `BasicVerifyFunction` should take into account the presence of an additional `req` parameter.

This is the current interface:
```
interface BasicVerifyFunction {
    (username: string, password: string, done: (error: any, user?: any) => void): void;
}
```

**Comment by tlaziuk** [comment]
I've made a PR for this https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23444

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
