### ISSUE TITLE
react-form onSubmitFailure error

### ISSUE THREAD

**Issue by arolson101** [DefinitelyTyped/DefinitelyTyped#23484]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-form` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cameron-mcateer

The signature for ```onSubmitFailure``` is missing the 3rd argument- the error.  It should be

```tsx
    onSubmitFailure?(errors: FormErrors, formApi: FormApi, onSubmitError: Error): void;
```

https://react-form.js.org/
```
Function that gets called when submission fails due to errors, or whenonSubmit threw an error. This function will pass two parameters: the form validation errors, the formApi, and an error thrown during the call to onSubmit. 
onSubmitFailure( errors, formApi, onSubmitError )
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
