### ISSUE TITLE
@types/elasticsearch found a mistake

### ISSUE THREAD

**Issue by makeH1greatagain** [DefinitelyTyped/DefinitelyTyped#23504]
Hi,
@bfsmith @ddunkin @pushplay @mlamp  @SimonSchick 

I don't know how to contribute so there is a explanation of the issue:

In @types/elasticsearch , go to `Cat` interface:

```
    count(params: CatCountParams, callback: (error: any, response: any) => void): void;
    count(params: CatAllocationParams): Promise<any>;

```

We should use `CatCountParams` in second line as well instead of `CatAllocationParams`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
