### ISSUE TITLE
Please add properties fullCurcle and startingAngle to ChartConfiguaration.gauge in c3 types

### ISSUE THREAD

**Issue by pranay317** [DefinitelyTyped/DefinitelyTyped#23526]
Also many other properties are missing based on the new c3js cofiguaration. Please add them to make it more reliable and usable. Thanks

**Comment by iansan5653** [comment]
For `fullCircle`:

This should be fixed as of PR #37139. Please verify that the definition is correct.

`fullCircle`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3cd6ad7fa49791641e198f0b28592245b14cd825/types/c3/index.d.ts#L274

For `startingAngle`:

I did a [search in the c3.js repository](https://github.com/c3js/c3/search?q=startingAngle&unscoped_q=startingAngle) and `startingAngle` is only referenced [once in a pretest step](https://github.com/c3js/c3/blob/991cc261ee51340ab9249d04878f40b2f3ccfcc1/spec/arc-spec.js#L285-L301). Looks like it may have been added and then removed. Please verify.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
