### ISSUE TITLE
@types/mathjs

### ISSUE THREAD

**Issue by AlexDmr** [DefinitelyTyped/DefinitelyTyped#23530]
If you know how to fix the issue, make a pull request instead.

- [ X] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @siavol

If you do not mention the authors the issue will be ignored.

There is an error in the definition of the eval method of MathNode. This method do not expect a string expression but an object instead
export interface MathNode {
                ...
                eval(expr: string): any;    <- This is not correct

Should be something like
                eval(scope: {[key: string]: any}): any

**Comment by andy-ms** [comment]
PRs accepted.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
