### ISSUE TITLE
@types/react-native-navigation type safety for passProps

### ISSUE THREAD

**Issue by ajcrites** [DefinitelyTyped/DefinitelyTyped#23586]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-native-navigation` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ egorshulga

Currently there does not seem to be a way to specify types for `passProps` during navigation although this would provide more type safety for screen navigations.

I actually created a Stackoverflow question that explains a bit: https://stackoverflow.com/questions/48757365/type-annotation-for-function-that-doesnt-expose-a-generic-type

For example:

```ts
export interface BioProps { username: string }
export class BioScreen extends React.Component<BioProps> {}

this.props.navigator.push<BioProps>({
  screen: 'bio.BioScreen',
  title: 'foo',
  // Type '{ usernam: any }' cannot be converted to BioProps
  passProps: {
    usernam,
  }
});
```

I'm not sure that generic typings on the classes with passProps would be the best way to do it, but if I had to do it that's what I would do. I'm also honestly not sure how/if this works in TypeScript.

```ts
export interface ResetScreen<T> extends Screen {
    passProps?: T
    ...

export interface PushedScreen<T> extends ResetScreen<T> {
...

export interface Navigator {
    push<T>(params: PushedScreen<T>): void;
    ...
```

**Comment by henrikra** [comment]
I have implemented that so this can be closed: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26351

**Comment by esbenvb** [comment]
While the <P> generic helps a lot, I stil miss a way to pair a props interface with a component name, just like pairing a redux action code to the payload data type - so I can make sure that a certain component is not pushed with the wrong prop types. Often I make the `push()` in some generic code that just receive the component and props from a navigation flow. 

I know it's probably hard to derive the props from the interfaces of the components, since we use strings for identifying components, instead of references to the actual components.

A simple solution could be some kind of interface where the componentName and the prop type is both defined...

But is there any way to achieve this in the current implementation of RNN or does it require a new PR?

**Comment by henrikra** [comment]
I totally agree with you. I would suggest you to make PR out of your idea and lets have discussion then. Just ping me 👍

**Comment by esbenvb** [comment]
Of course. But I'm not sure whether the current interface of RNN allows that? Since the key is always a string.

What I thought of as a solution without breaking APIs, was to have a helper function generating the `component{}` property of the layout.

That helper function could then use a `Map` to derive a component name from the supplied component object, and at the same time verify that the props of the component matches the props object supplied.

This implies that the initial `Navigation.registerComponent` is done using the same map (with reverse key/value).

Let me know if you think there's a simpler solution, otherwise I'll try to look into the one I described.

**Comment by henrikra** [comment]
I think breaking api is fine if the new api is better. You can make suggestion PR to RNN and see what happens 🤷‍♂

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
