### ISSUE TITLE
@types/redux-form FieldArray don't accept React.PureComponent<WrappedFieldArrayProps<any>>

### ISSUE THREAD

**Issue by n06rin** [DefinitelyTyped/DefinitelyTyped#23592]
- [X] I tried using the `@types/redux-form` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @carsonf @aikoven @LKay @bancek  @alsiola @tehbi4

I try to using `@types/redux-form` with redux-form@7.2.3 and have an error when setting type for a FieldArray component. I prepare a bare simple example:
```typescript
const RenderMembersFunc = (props: WrappedFieldArrayProps<any>) => (
  <div>
    here we should map our members
  </div>
);

const SimpleComponent = (props: {}) => (
  <div>
    simpleComponent
  </div>
) 

const FieldArraysForm = (props: InjectedFormProps<{}>) => {
  return (
    <form onSubmit={props.handleSubmit}>
      <FieldArray name="members" component={RenderMembersFunc} />
      <FieldArray name="members" component={SimpleComponent} />
    </form>
  );
};

export default reduxForm({
  form: "fieldArrays", // a unique identifier for this form
})(FieldArraysForm);
```
for a first usage FieldArray with RenderMembersFunc I'm get an error:
```
[ts]
Type '{ name: "members"; component: (props: WrappedFieldArrayProps<any>) => Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<FieldArray<WrappedFieldArrayProps<any>>> & Readonl...'.
  Type '{ name: "members"; component: (props: WrappedFieldArrayProps<any>) => Element; }' is not assignable to type 'Readonly<BaseFieldArrayProps<WrappedFieldArrayProps<any>> & WrappedFieldArrayProps<any>>'.
    Property 'fields' is missing in type '{ name: "members"; component: (props: WrappedFieldArrayProps<any>) => Element; }'.
```

I made a simple repo with that error here: https://github.com/n06rin/redux-form-typescript-error

Maybe I set wrong types? I'm try to find typed typescript examples, but don't find.

**Comment by lukx** [comment]
I am also seeing this since I upgraded to typescript 2.7.x (was: 2.6.2), but for a *Normal Field* using a custom component.

I reduced the differences between the working and non-working states to just the typescript-upgrade, so the [TypeScript Changelog for version 2.7](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-27) might be something to look into.

**Comment by n06rin** [comment]
@lukx for a Field with custom component I made an example here: https://github.com/n06rin/redux-form-typescript-error/blob/master/src/CustomFieldExample.tsx hope that helps.

**Comment by rvanheest** [comment]
I have the same issue for `FieldArray`. The interesting thing is: for a normal `Field`, I don't have this issue... And that's the weirdest part to me: the `Field` is not that much different from `FieldArray` in terms of the interfaces that `@types/redux-form` provides.

@n06rin I'm interested to hear if you found a solution already!

@lukx In the meantime TypeScript released [v2.7.2](https://github.com/Microsoft/TypeScript/releases/tag/v2.7.2), in which this issue still remains.

**Comment by mattdell** [comment]
+1

**Comment by henrikra** [comment]
Same error when using `Field` component with `component` prop's values as custom stateless component.

**Comment by rvanheest** [comment]
> using Field component with component prop's value as custom stateless component.

@henrikra not sure what you mean with that, but I don't experience any errors (as of yet 😉) with 'normal' `Field` components.

Full disclosure, [here is my code](https://github.com/Dans-labs/electron-experiments/tree/master/redux-form-tutorial/src/main/typescript) with:
*  [form with only `Field` components](https://github.com/Dans-labs/electron-experiments/blob/master/redux-form-tutorial/src/main/typescript/components/DemoForm.tsx)
* [form with a `FieldArray` component](https://github.com/Dans-labs/electron-experiments/blob/master/redux-form-tutorial/src/main/typescript/components/RepeatableForm.tsx)
* [library functions to (what I would call) 'custom stateless components'](https://github.com/Dans-labs/electron-experiments/blob/master/redux-form-tutorial/src/main/typescript/lib/form.tsx)

Perhaps this helps you to see what is going on with your `Field` errors.

**Comment by rvanheest** [comment]
I've been diving into this issue again. For this I used the [example repository](https://github.com/n06rin/redux-form-typescript-error) by @n06rin.

First of all I started to look into claim @lukx made about TypeScript versions. Going back all the way to 2.4 I still had the same errors.
Then, after reverting back to the latest TypeScript version (2.7.2), I started looking at the type definitions provided by `@types/redux-form`. I found a couple of interesting things here. Comparing the definitions for `Field` and `FieldArray`, they're almost the same (apart from some properties/interfaces that are different). One striking difference, however, is how `BaseFieldProps` and `BaseFieldArrayProps` define their respective `component` property. The former has:

**(`Field`)**
```typescript
interface BaseFieldProps<P = {}> extends ... {
    // ...
    component?: ComponentType<WrappedFieldProps & P> | "input" | "select" | "textarea";
    // ...
}
```

while the latter has:

**(`FieldArray`)**
```typescript
interface BaseFieldArrayProps<P = {}> {
    // ...
    component: ComponentType<P>;
    // ...
}
```

The main difference here is that for `Field`, the `WrappedFieldProps` are part of the type parameter in `ComponentType`, while its counterpart in `FieldArray` (`WrappedFieldArrayProps`) is not.

When I add this, it 'kind of' works.

```diff
interface BaseFieldArrayProps<P = {}> {
    // ...
-   component: ComponentType<P>;
+   component: ComponentType<WrappedFieldArrayProps<any> & P>;
    // ...
}
```

The other change I needed to make is in the example code by @n06rin:

```diff
-class RenderMembers extends React.PureComponent<WrappedFieldArrayProps<any>> {
+class RenderMembers extends React.PureComponent<WrappedFieldArrayProps<any> & BaseFieldArrayProps> {
  render(){
    return (
      <div>
        here we should map our members
      </div>
    );
  }
}

-const RenderMembersFunc = (props: WrappedFieldArrayProps<any>) => (
+const RenderMembersFunc = (props: WrappedFieldArrayProps<any> & BaseFieldArrayProps) => (
  <div>
    here we should map our members
  </div>
);
```

I'm not particularly happy with these changes yet, especially with the `any` type parameter in `ComponentType<WrappedFieldArrayProps<any> & P>`, but that seemed the only obvious choice for now, since all other type parameters for `WrappedFieldArrayProps` equate to `any` as well.

Question is whether this is the true solution (which is why I'm not doing a pull request yet). This change seems to be working (also in my own project), but I'm still confused by it. For example, any clue why I also need to add `BaseFieldArrayProps` in the example code?

**Comment by rvanheest** [comment]
After a failed PR I discovered a different pattern for solving this issue with `FieldArray`s. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24309#issuecomment-375969220 for more details.

**Comment by futpib** [comment]
This patch would have helped me:

```diff
--- lib/FieldArray.d.ts.bak	2019-02-21 13:16:18.796979909 +0300
+++ lib/FieldArray.d.ts	2019-02-21 13:16:24.876979785 +0300
@@ -11,13 +11,13 @@
     rerenderOnEveryChange?: boolean;
 }
 
-export interface GenericFieldArray<Field, P = {}> extends Component<BaseFieldArrayProps<P> & Partial<P>> {
+export interface GenericFieldArray<Field, P = {}> extends Component<BaseFieldArrayProps<P>> {
     name: string;
     valid: boolean;
     getRenderedComponent(): Component<WrappedFieldArrayProps<Field> & P>;
 }
 
-export class FieldArray<P = {}> extends Component<BaseFieldArrayProps<P> & Partial<P>> implements GenericFieldArray<any, P> {
+export class FieldArray<P = {}> extends Component<BaseFieldArrayProps<P>> implements GenericFieldArray<any, P> {
     name: string;
     valid: boolean;
     getRenderedComponent(): Component<WrappedFieldArrayProps<any> & P>;

```

As a workaround I had to put this in my `typings.d.ts`:

<details>
 <summary> Click to expand </summary>

```ts
// Workaround for https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23592
declare module 'redux-form' {
    export {
        FieldType,
        ErrorOther,
        FormErrors,
        WarningOther,
        FormWarnings,
        RegisteredFieldState
    } from '@types/redux-form';

    export * from '@types/redux-form/lib/reduxForm';
    export * from '@types/redux-form/lib/Field';
    export * from '@types/redux-form/lib/Fields';
    export * from '@types/redux-form/lib/Form';
    export * from '@types/redux-form/lib/FormName';
    export * from '@types/redux-form/lib/FormSection';
    export * from '@types/redux-form/lib/formValues';
    export * from '@types/redux-form/lib/formValueSelector';
    export * from '@types/redux-form/lib/reducer';
    export * from '@types/redux-form/lib/SubmissionError';
    export * from '@types/redux-form/lib/actions';
    export * from '@types/redux-form/lib/actionTypes';
    export * from '@types/redux-form/lib/selectors';

    import {Component, ComponentType} from 'react';
    import {
        Validator,
        FieldsProps,
        BaseFieldArrayProps,
        FieldArrayMetaProps
    } from '@types/redux-form';

    export interface WrappedFieldArrayProps<FieldValue> {
        fields: FieldsProps<FieldValue>;
        meta: FieldArrayMetaProps;
    }

    export interface GenericFieldArray<Field, P = {}> extends Component<BaseFieldArrayProps<P>> {
        name: string;
        valid: boolean;
        getRenderedComponent(): Component<WrappedFieldArrayProps<Field> & P>;
    }

    export class FieldArray<P = {}> extends Component<BaseFieldArrayProps<P>> implements GenericFieldArray<any, P> {
        name: string;
        valid: boolean;
        getRenderedComponent(): Component<WrappedFieldArrayProps<any> & P>;
    }
}

```
</details>


I'm running these versions:
```
├── @types/redux-form@7.4.7 
├── redux-form@7.4.2 
└── typescript@3.3.3
```

and this issue popped up after upgrading typescript from 3.0.3 to 3.3.3

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
