### ISSUE TITLE
Property 'merge' does not exist on type '{ default: LoDashStatic; }' @types/sequelize

### ISSUE THREAD

**Issue by EagleEYErus** [DefinitelyTyped/DefinitelyTyped#23605]
- [x] I tried using the @types/sequelize package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see Definitions by: in index.d.ts) so they can respond.
  - Authors: @samuelneff, @CodeAnimal, @drinchev, @babolivier, @kukoo1, @oktapodia, @MorpheusXAUT, @TitaneBoy, @zjy01, @nidzov 

```@types/sequelize - v4.27.5```
When I`m compile I have error: error TS2339: Property 'merge' does not exist on type '{ default: LoDashStatic; }'.

error occurs when esModuleInterop is equal to true

![2018-02-13 16 09 02](https://user-images.githubusercontent.com/15634499/36160354-04f098ee-10f2-11e8-84cf-82d33bef11c5.png)

**Comment by rahife** [comment]
I get the same error. Any update on this issue?
I'm using:

typescript@2.4.2
@types/sequelize@3.30.8 
@types/lodash@4.14.116

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
