### ISSUE TITLE
ThreeJS: Mesh signature

### ISSUE THREAD

**Issue by giorgiomarcias** [DefinitelyTyped/DefinitelyTyped#23607]
In the following line:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/242fcd3080c74d4b1015f7a94c6a63a9928052f0/types/three/three-core.d.ts#L4854

Argument `material`'s type should be `Material | Material[]`

**Comment by felixfontein** [comment]
Also see the discussion in 1863849c3ae983d22c145fb6e26c62b54f4286aa.

**Comment by felixfontein** [comment]
This will be fixed in r23608.

**Comment by KaelWD** [comment]
This can be closed, it was fixed with #24022

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
