### ISSUE TITLE
npm run lint chrome fails in types/chrome/index.d.ts

### ISSUE THREAD

**Issue by fredrikhr** [DefinitelyTyped/DefinitelyTyped#23624]
``` sh
$ git fetch origin
$ git checkout origin/master
# Commit 8f42ac36 checked out
$ node -v
v8.9.4
$ npm -v
5.6.0
$ npm install
$ npm run lint chrome
```

Running the `npm run lint chrome` command produces the following messages: 
> ERROR: 452:17   expect  TypeScript@next compile error:
Duplicate identifier 'ColorArray'.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8f42ac36e751ac6e40f2d989b5b6c9f7b3e81766/types/chrome/index.d.ts#L452

> ERROR: 1376:26  expect  TypeScript@next compile error:
Duplicate identifier 'debugger'.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8f42ac36e751ac6e40f2d989b5b6c9f7b3e81766/types/chrome/index.d.ts#L1376

> ERROR: 1430:18  expect  TypeScript@next compile error:
Duplicate identifier 'PageStateMatcherProperties'.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8f42ac36e751ac6e40f2d989b5b6c9f7b3e81766/types/chrome/index.d.ts#L1430

> ERROR: 1444:18  expect  TypeScript@next compile error:
Duplicate identifier 'PageStateMatcher'.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8f42ac36e751ac6e40f2d989b5b6c9f7b3e81766/types/chrome/index.d.ts#L1444

> ERROR: 1449:18  expect  TypeScript@next compile error:
Duplicate identifier 'ShowPageAction'.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8f42ac36e751ac6e40f2d989b5b6c9f7b3e81766/types/chrome/index.d.ts#L1449

> ERROR: 6873:17  expect  TypeScript@next compile error:
Duplicate identifier 'DetailsCallback'.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8f42ac36e751ac6e40f2d989b5b6c9f7b3e81766/types/chrome/index.d.ts#L6873

- Authors: @matthewkimber, @otiai10, @couven92, @RReverser, @sreimer15

**Comment by couven92** [comment]
Related issue: #23623

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
