### ISSUE TITLE
WrappedFieldMetaProps error and warnings types are any

### ISSUE THREAD

**Issue by mattdell** [DefinitelyTyped/DefinitelyTyped#23664]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/redux-form` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CarsonF @aikoven @LKay @bancek @tehbi4

Looking at the interface `WrappedFieldMetaProps`

```
export interface WrappedFieldMetaProps {
    active?: boolean;
    autofilled: boolean;
    asyncValidating: boolean;
    dirty: boolean;
    dispatch: Dispatch<any>;
    error?: any; <--- make this error?: string;
    form: string;
    initial: any;
    invalid: boolean;
    pristine: boolean;
    submitting: boolean;
    submitFailed: boolean;
    touched: boolean;
    valid: boolean;
    visited: boolean;
    warning?: any; <--- make this warning?: string;
}
```

`error` and `warning` are of type `any`, however according to the Field documentation they should only be a `string`: https://redux-form.com/7.2.3/docs/api/field.md/

I'm happy to raise a PR, but wanted to check to see if this was an intentional typing.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
