### ISSUE TITLE
webpack types have dependency on `source-map` package

### ISSUE THREAD

**Issue by pdeva** [DefinitelyTyped/DefinitelyTyped#23673]
I tried using the `@types/webpack` package and had problems.

  - Authors: @tkqubo @bumbleblym @bcherny @tommytroylin @mohsen1 @jcreamer898 @ahmed-taj @alan-agius4 @elliottsj @jason0x43 

The `@types/webpack@3.8.7` adds a dependency on `source-map "^0.7.0"`.

The `types` packages shouldnt add a dependency on actual library, just the `types` of those libraries.
Since source-map 0.7 requires nodejs 8, it even breaks a lot of builds running on older node versions.

Updating a `types` packages shouldnt cause such a big change.

**Comment by mohsen1** [comment]
This is a bug introduced in https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4a856368ece10e15654c8bcf2b839ba844d33f78

**Comment by alan-agius4** [comment]
The types of spurce-map shouldn’t be consumed.

This is the correct approach!

**Comment by alan-agius4** [comment]
Opened a PR

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23674

**Comment by jason0x43** [comment]
Sorry about that -- source-map 0.7.0 uses slightly different typings for RootSourceMap and apparently isn't widely deployed yet.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
