### ISSUE TITLE
[smtp-server] remoteAddress is should be simple string

### ISSUE THREAD

**Issue by twawszczak** [DefinitelyTyped/DefinitelyTyped#23764]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e07ab52c977b1d8353b8b4c025e073819788bbe9/types/smtp-server/index.d.ts#L77

In original implementation, `remoteAddress` property of smtp session object is just a string, not object.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
