### ISSUE TITLE
[@types/three] Missing typing for Box3Helper

### ISSUE THREAD

**Issue by luisjs** [DefinitelyTyped/DefinitelyTyped#23773]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @...

If you do not mention the authors the issue will be ignored.

(apologies, so many contributors, didn't know who to notify)

https://threejs.org/docs/#api/helpers/Box3Helper

**Comment by apierini** [comment]
Same problem here ... did you find a workaround?

**Comment by luisjs** [comment]
@apierini it's a crude one, but I basically shoehorned a definition for it in three-core.d.ts, below BoxHelper (line 7426 in 0.92.0). I don't know if it's correct but I tried following the [documentation](https://threejs.org/docs/#api/helpers/Box3Helper).

```typescript
export class Box3Helper extends LineSegments {
    constructor(object?: Object3D, color?: Color);

    box: Box3;

    updateMatrixWorld(force?: boolean): void;
}
```

**Comment by apierini** [comment]
Thanks 👍

**Comment by thomasscholz** [comment]
The parameter should be a `Box3` not `Object3D`

```typescript
export class Box3Helper extends LineSegments {
  constructor(box?: Box3, color?: Color);

  box: Box3;

  updateMatrixWorld(force?: boolean): void;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
