### ISSUE TITLE
@types/redux-form validating FieldArray

### ISSUE THREAD

**Issue by rvanheest** [DefinitelyTyped/DefinitelyTyped#23922]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CarsonF @aikoven @LKay @bancek @alsiola @tehbi4

I'm trying to use `@types/redux-form` with `redux-form@7.2.3` to follow [this tutorial on `FieldArray`s](https://redux-form.com/7.2.3/examples/fieldarrays/). Currently I'm working on validating the arrays of fields. Trying this, led me to a couple of remarks and missing features in the `@types` part.

First, here is my code:

```typescript
const validate = (values: RepeatableFormData) => {
    const errors: FormErrors<RepeatableFormData, string> = {}

    if (!values.clubName) {
        errors.clubName = "Required"
    }

    if (!values.members || !values.members.length) {
        errors.members = { _error: "At least one member must be entered" }
    }
    else {
        const result: FormErrors<MemberData>[] = values.members.map((member, index) => validateMember(member)).filter(value => !isEmpty(value))
        if (!result.length) {
            errors.members = result
        }
    }

    return errors
}

const validateMember = (values: MemberData) => {
    const errors: FormErrors<MemberData> = {}

    if (!values.firstName) {
        errors.firstName = "Required"
    }

    if (!values.lastName) {
        errors.lastName = "Required"
    }

    return errors
}
```

1. In order to get the `{ _error: "At least one member must be entered" }` to work, I need to add the extra (second) parameter in `FormErrors<RepeatableFormData, string>`. However, if I do that, the `validate` function is no longer accepted in `reduxForm<RepeatableFormData>({form: 'repeatable-form', validate})(RepeatableForm)`, since `ConfigProps` has a function `validate?(values: FormData, props: P & InjectedFormProps<FormData, P>): FormErrors<FormData>` where the second type parameter in `FormErrors` is equal to `void` (`export type FormErrors<FormData = {}, T = void> = ...`). Wouldn't it make more sense to let the `validate` argument in `ConfigProps` return `FormErrors<FormData, any>`?
2. The contents of the `FormErrors` interface is defined as `[P in keyof FormData]?: ReactElement<any> | string | ErrorOther<T>;`. However, given that for `FieldArray` the corresponding validation result should contain an array of `FormErrors`, these types don't compile. Concretely in the code above: `errors.members = result` doesn't compile since `result: FormErrors<MemberData>[]`. This leads to the question whether `FormErrors` has a correct definition. Shouldn't this also account for arrays? Or am I misusing this library and is there another way to achieve my goal within the current types?

**Comment by huwmartin** [comment]
+1 for this on both points, our team has been dealing with these same issues recently and we have temporarily settled on return type `any` for our validate and warn functions (not a solution).

It seems clear to me that the interface has gaps which don't cover accepted behaviour, but I'm struggling with it because I can't think of a workable update to the interface - seems like you would need a nested `in keyof` and to be able to infer the type `MemberData` from the generic array type.

**Comment by darioseidl** [comment]
I also had to settle for `any` for nested form field errors.

E.g. with fields named `contingent.total` and `contingent.external`
```
interface FormFields {
    contingent: {
        total: number,
        external: number
    };
}

const validate = (values: FormFields, props: Props) => {
    const errors: any = { contingent: {} };

    if (values.contingent.external > values.contingent.total) {
        errors.contingent.external = 'external must be less than or equal to total';
    }

    return errors;
};
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
