### ISSUE TITLE
[jsonwebtoken] Update definitions to 8.1.x

### ISSUE THREAD

**Issue by tomwanzek** [DefinitelyTyped/DefinitelyTyped#23953]
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SomaticIT @danielheim @brikou

Could you kindly review the [changes](https://github.com/auth0/node-jsonwebtoken/blob/master/CHANGELOG.md) between the currently published definitions version and the now current jsonwebtoken version 8.1.x?

Bringing the definitions up to the current minor would be most appreciated, even if after review it means there are no changes required beyond the chore to bump the version number.

Thanks in advance.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
