### ISSUE TITLE
Types for res.header seems to be incorrect

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#23968]
@andy-ms  @tkrotoff 

- [x] I tried using the `@types/express` package and had problems.

Here is the problem:

![screenshot 2018-02-27 18 35 38](https://user-images.githubusercontent.com/11139560/36766981-1e8510e0-1bed-11e8-8c55-58c5295e7975.png)

seems incorrect, but obviously you never know for sure...it should take a 3rd options arg right?

**Comment by ORESoftware** [comment]
hopefully it's clear but just to be sure RequestHandler is like so:

`import {RequestHandler} from 'express';`

the version of @types/express is:

` "@types/express": "^4.11.1",`

and my Express version is:

`  "express": "~4.14.1",`

**Comment by ORESoftware** [comment]
As an aside, this error is also causing me trouble:

![screenshot 2018-02-27 18 53 20](https://user-images.githubusercontent.com/11139560/36767495-981bf976-1bef-11e8-8f18-0a7a9f858d1c.png)

not sure how to fix that one

**Comment by andy-ms** [comment]
You could make a pull request adding a third argument.

For the 'exported variable' error, all you have to do is provide an explicit type to `router`.

**Comment by micksatana** [comment]
@ORESoftware I read from the docs [here](https://expressjs.com/en/4x/api.html#res) `res.header` is aliased for `res.set` which has only 2 parameters. Could you point out the `overwrite` come from which part of the doc or code. I might be able to help add it in.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
