### ISSUE TITLE
redux-forms shouldValidate() is deprecated

### ISSUE THREAD

**Issue by AstraLuma** [DefinitelyTyped/DefinitelyTyped#24013]
Per [docs](https://redux-form.com/7.2.3/docs/api/reduxform.md/#-del-code-shouldvalidate-params-boolean-code-del-optional-strong-deprecated-strong-), the `shouldValidate` parameter to `reduxForm()` has been deprecated:

> DEPRECATED: Use shouldError() and shouldWarn(). Will be removed in v8.

The new parameters are not in the [typescript declarations](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/redux-form/lib/reduxForm.d.ts#L100-L125) yet.

redux form definition authors: @carsonf @aikoven @LKay @bancek @alsiola @tehbi4

**Comment by RetroCraft** [comment]
Appears to have been fixed in #23851

**Comment by astronouth7303** [comment]
It doesn't add any deprecation notices, but it does add the replacements.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
