### ISSUE TITLE
JSZIP doesn't get globals typings without @types/node

### ISSUE THREAD

**Issue by vmagalhaes** [DefinitelyTyped/DefinitelyTyped#24032]
Hi,

I'm trying to use the version 3.1.3 of @types/jszip, but I have the globals typings node inside my project, so, when the package types jszip are installed it install together the @types/node, but this broke the project because when the project are building the console display a conflict between this two nodes.

What can I do about this? Any help?

Thank you

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
