### ISSUE TITLE
I want to translate README.md to Filipino

### ISSUE THREAD

**Issue by caratzky** [DefinitelyTyped/DefinitelyTyped#24069]
Hi @DanielRosenwasser. I'm Rizalino Caratao, I also work as a Utopian Translator. I've seen that you accepted a translation to Spanish for the README.md file. I would like to do the same, this time to Filipino and Cebuano. This is for the sake of Filipino Developers who'd possible want to contribute in this open source project. These languages are both included in ISO 639-1, a standardized nomenclature for classifying languages. 

I'll be waiting for your go signal. God bless.

**Comment by DanielRosenwasser** [comment]
Wow! That is super generous of you and we definitely appreciate that. While it may be slightly more difficult to find reviewers (we have the good fortune of @armanio123 being on our team for reviewing the Spanish content), I fully encourage you to send over translations!

**Comment by caratzky** [comment]
Thank you very much.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
