### ISSUE TITLE
Select2 missing selectionAdapter and resultsAdapter in Select2Options interface

### ISSUE THREAD

**Issue by DjangoFR** [DefinitelyTyped/DefinitelyTyped#24117]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov

Compilation fails because of missiong options **selectionAdapter** and **resultsAdapter** in Select2Options interface.

Properties should be defined under:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/select2/index.d.ts#L94

The Select2 source that references selectionAdapter is found here: 
https://github.com/select2/select2/blob/c90adc102b5e9b2faea2b871b1c764416584ee07/src/js/select2/core.js#L37

The Select2 source that references resultsAdapter is found here:
https://github.com/select2/select2/blob/c90adc102b5e9b2faea2b871b1c764416584ee07/src/js/select2/core.js#L49

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
