### ISSUE TITLE
Webpack type definition cannot be used

### ISSUE THREAD

**Issue by ivanpadavan** [DefinitelyTyped/DefinitelyTyped#24123]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@tkqubo 
@bumbleblym 
@bcherny
@tommytroylin
@jcreamer898
@ahmed-taj
@alan-agius4 
@elliottsj 
@jason0x43 

If you do not mention the authors the issue will be ignored.

   Hello everyone! As I understand typescript this definition cannot be used by anyone, because of using interception types instead of union ones.
   As I Understood `|` symbol reduces type to the most common denominator, while `&` leads to an opportunity to use any of it. So when we type
```typescript
type Module = NewModule | OldModule
```
nobody can use part of type that isn't common. So neither `NewModule` nor `OldModule` specific properties can be used.

If I misunderstood something please let me know how I should use webpack definition. 
Thank you in advance!

**Comment by jason0x43** [comment]
The `|` symbol indicates a union of one or more types. The snippet above is saying that `noParse` could be a RegExp, a RegExp[], or a function. Since TypeScript can't tell _which_ of those the value will actually have at runtime, it only allows you to use properties shared by all the types in the union. 

If you want to access `noParse` as a specific type, you'll need to figure out what type it is at runtime and explicitly cast it to that or use a type guard.

**Comment by ivanpadavan** [comment]
Sorry for disturbing, I've got a clue already. Actually `noParse` works pretty well because a type casts implicitly. Either any typecasting between primitives, objects, arrays of objects or functions works awesome. But it doesn't work well when the goal is to cast objects with a different structure. 

Sorry for interrupting and thank you for the answer!

**Comment by ivanpadavan** [comment]
But may I ask if it's possible to recast it somehow in my project using `typings.d.ts`? I'm doing it quite often like described here https://github.com/Microsoft/TypeScript/issues/10859 but here I'm stuck by a namespace stuff and not sure if it's possible.

**Comment by ivanpadavan** [comment]
Do you mind if I'll sebd pyll request, where I'll replace all the `new.. | old..` types with `new.. & old..`?

**Comment by ivanpadavan** [comment]
I have to write something like [this](https://github.com/developit/preact-cli/blob/master/src/lib/webpack/transform-config.js#L34) in typescript. And I should implicitly type module, rules, loaders to a `new` type. In most common use case (just making webpack.config with autocompletion) you should implicitly cast all the time. It's quite annoying and takes time of humanity.

**Comment by jason0x43** [comment]
As I said, can you provide a specific example of where the typings aren't working out (like, gist with code that breaks)?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
