### ISSUE TITLE
[@types/graphql-resolve-batch] Incorrect signature

### ISSUE THREAD

**Issue by Ryuko** [DefinitelyTyped/DefinitelyTyped#24153]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/graphql-resolve-batch` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Nayni

If you do not mention the authors the issue will be ignored.

Hello,
I think that your definition for graphql-resolve-batch is wrong.

As mentionned [here](https://github.com/calebmer/graphql-resolve-batch/blob/30eb41a13640405c0f16f031b9c6b4c17a0bc39c/src/batch.js#L97)
`BatchResolveFunction` can be synchronous or asynchronous. Therefore, the response should be `TReturn[]` or `Promise<TReturn[]>` and not `Array<Promise<TReturn>>`

**Comment by Nayni** [comment]
You're right, I confused it with how DataLoader works.

I've updated the type definition so that BatchResolverFunction returns either `TReturn[]` or `Promise<TReturn[]` which is the expected behavior. This also implied that now the resulting Resolver function is always an array.

You can see the changes in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24155
