### ISSUE TITLE
@types/leaflet-draw

### ISSUE THREAD

**Issue by Zahma** [DefinitelyTyped/DefinitelyTyped#24152]
Leaflet Draw // Leaflet typings don't contain the EditToolbar.js typings.
The file in question where the implementation is found is located here: 
https://github.com/Leaflet/Leaflet.draw/blob/develop/src/edit/EditToolbar.js

So all the typings that are related to this class don't work with the current typing.

example:   new L.EditToolbar.Edit();

thank you :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
