### ISSUE TITLE
Missing namespace declaration in DatastoreKey

### ISSUE THREAD

**Issue by QuestionAndAnswer** [DefinitelyTyped/DefinitelyTyped#24172]
Package: ```@types/google-cloud__datastore```
Version: ```1.1.1```

DatastoreKey declaration should also has ```namespace``` field as ```string```.

See documentation: https://cloud.google.com/nodejs/docs/reference/datastore/1.3.x/Key
Line from node.js library where namespace is written into Key object: https://github.com/googleapis/nodejs-datastore/blob/master/src/entity.js#L178

Lines in deceleration file in the current repo:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fe94393d6ac8ac3effe56d038f5b6b34c17c8611/types/google-cloud__datastore/index.d.ts#L126#L134

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
