### ISSUE TITLE
@types/acl exports still not merged

### ISSUE THREAD

**Issue by sasos90** [DefinitelyTyped/DefinitelyTyped#24170]
Hi!

Concering that pull request, I've noticed that it still wasn't released. When can we expect this to be released?

[Merged pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21803)

Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
