### ISSUE TITLE
react-measure incorrect declare type

### ISSUE THREAD

**Issue by bdely** [DefinitelyTyped/DefinitelyTyped#24237]
I am using "@types/react-measure": "2.0.2" and when I build I get "Generic type 'Component<P, S>' requires 2 type argument(s)." which is referring to line 63 in index.d.ts
`declare class Measure<T> extends React.Component<MeasureProps<T>> {}` 

@ForbesLindesay I am assuming that it is just missing the state type.

**Comment by ForbesLindesay** [comment]
Yes, that is what that error message means. You could submit a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
