### ISSUE TITLE
Outdated: @types/matter-js

### ISSUE THREAD

**Issue by jared83** [DefinitelyTyped/DefinitelyTyped#24257]
- [x] I tried using the `@types/matter-js` package and had problems.
  - Authors: @andy-ms 

Very outdated. Current version of matter is 0.14.1 - typed version is 0.10.0
For instance, take a look at IRendererOptions - [many options](https://github.com/liabru/matter-js/wiki/Rendering#options) are missing type definitions.

**Comment by andy-ms** [comment]
Pull requests accepted.

**Comment by kcolton** [comment]
This is very much still "in the oven", but work started:
https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...kcolton:master

See #24665 for more details

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
