### ISSUE TITLE
Can't import @types/radium

### ISSUE THREAD

**Issue by tommybernaciak** [DefinitelyTyped/DefinitelyTyped#24273]
- [x ] I tried using the `@types/radium` package and had problems.

- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alexgorbatchev, @nupplaphil, @asvetliakov, @mihe

I wanted to try radium. Just installed:
```
yarn add radium
yarn add @types/radium
```
When I `import Radium from 'radium'`
 I have:
`Module (...)/node_modules/@types/radium/index"' has no default export.`

I use React with Typescript.

**Comment by Q-Man** [comment]
Until radium 0.21.x you could import radium like this:

`import * as Radium from "radium";`

But since radium 0.22.x the export has changed, so the radium type definitions are invalid now and should be updated.

See 0.22.0 here: https://github.com/FormidableLabs/radium/blob/master/CHANGELOG.md

If you're importing it how I said above you'll get this error running your code:
`TypeError: Radium is not a function`

It must be imported like this now:
`import Radium from "radium";`

To make this work this line in the radium typescript definition must be changed:
`export = Radium` should be `export default Radium`

@alexgorbatchev, @nupplaphil, @asvetliakov, @mihe
Could you provide an updated version please?

**Comment by mihe** [comment]
I'm not using Radium anymore, so my interest in this is somewhat limited, but there's nothing stopping you from submitting your own pull request to fix this.

**Comment by Q-Man** [comment]
I submitted a pull Request:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24395

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
