### ISSUE TITLE
Cannot type against React Component instances.

### ISSUE THREAD

**Issue by ShanonJackson** [DefinitelyTyped/DefinitelyTyped#24296]
Consider the following component.

`IFooProps {`
    `element: JSX.Element;`
`}`

`....... extends React.Component<IFooProps, {}> {`
   ` render() {`
        `return React.cloneElement(element, {ref: (ele) => ele.getBoundingClientRect()})`
    `}`
`}`

if element is a valid JSX.Element but NOT a component this code will work and is very similar to the real-world problem i'm having, however if element is a react component instance this will fail.

correct me if i'm wrong but iv'e scoured the typing's for a way to for...
`<Foo element={<div/>}/>`   to succeed and...
`<Foo element={<Bar text={"HELLO"}/>}` to fail.

I Don't have a proposed solution and it seems no matter what type you put in place of JSX.Element it wont work as intended.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
