### ISSUE TITLE
ServiceBus listTopics signature is wrong

### ISSUE THREAD

**Issue by sergsalo** [DefinitelyTyped/DefinitelyTyped#24291]
DefinitelyTyped/types/azure-sb/lib/servicebusservice.d.ts

public listTopics(topicPath: string, callback: TypedResultAndResponseCallback<Topic[]>): void;

actual JS code: 
`
ServiceBusService.prototype.listTopics = function (optionsOrCallback, callback) {
  this._listResources('/$Resources/Topics', topicResult, null, optionsOrCallback, callback);
};`
https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/serviceBus/lib/servicebusservice.js

**Comment by naughton** [comment]
Here is a pull request to fix this issue:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24322

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
