### ISSUE TITLE
@types/lodash-es - inline documentation is broken

### ISSUE THREAD

**Issue by oliveti** [DefinitelyTyped/DefinitelyTyped#24335]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/lodash-es` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @stephenlautier

First, thank you for the great work on this typings. I'm trying to use it in an angular 5 (ng cli) project to reduce final bundle and it is working great for this.

But, it seems that somehow the lodash-es types are breaking the inline documentation and code completion (see captures).

With lodash-es 
![app component ts a14318 2018-03-16 13-35-42](https://user-images.githubusercontent.com/1235503/37520860-f5324a98-291e-11e8-9e96-efd8db42ff88.png)

With lodash
![app component ts a14318 2018-03-16 13-36-43](https://user-images.githubusercontent.com/1235503/37520904-16379234-291f-11e8-9b5e-39de3e6df923.png)

do you know why this is happening ?

**Comment by aj-r** [comment]
What IDE are you using? I'm getting proper documentation in Visual Studio Code. Maybe it's a bug with your IDE.

![image](https://user-images.githubusercontent.com/6971059/38772323-abd4d9f2-4001-11e8-899f-db689121720d.png)

Also as a note, if you use the `esModuleInterop` option with TS >= 2.7, you can use ES-style imports with plain lodash (lodash-es is not required). For example:

```ts
import _ from "lodash";
import replace from "lodash/replace";
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
