### ISSUE TITLE
Use conditional types in Sinon's SinonStubbedInstance

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DefinitelyTyped/DefinitelyTyped#24389]
- [x] I tried using the `@types/sinon` package and had problems.

```typescript
    /**
     * An instance of a stubbed object type with members replaced by stubs.
     *
     * @template TType Object type being stubbed.
     */
    type SinonStubbedInstance<TType> = {
        // TODO: this should really only replace functions on TType with SinonStubs, not all properties
        // Likely infeasible without mapped conditional types, per https://github.com/Microsoft/TypeScript/issues/12424
        [P in keyof TType]: SinonStub;
    };
```

/cc @43081j @nicojs @lumaxis @rationull @mrbigdog2u

**Comment by Carsair** [comment]
> sandbox.stub(obj, "prop", 42);
https://github.com/sinonjs/sinon/issues/161#issuecomment-7049293
> // Argument of type number is not assignable to parameter of type 'Function'.

This is a totally valid sinon stub, and should be accepted by the typing too.

**Comment by 43081j** [comment]
whoops totally forgot about this issue.

its looking like this probably won't be changed until 2.8 has wider adoption. I have done a huge cleanup of sinon's types in #25491 but left the stubbed instance types the same (weak/slightly-off).

@Carsair  in 5.x `stub(obj, method, fn)` is gone, it was deprecated in 4.x. so i guess people still using it should _not_ update their types dependency if the 5.x changes get merged.

**Comment by JoshuaKGoldberg** [comment]
Relevant: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24399

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
