### ISSUE TITLE
[@type/react] Move JSX.IntrinsicElements to @types/react-dom

### ISSUE THREAD

**Issue by simast** [DefinitelyTyped/DefinitelyTyped#24433]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz @richseviora @theruther4d @guilhermehubner

Currently, all DOM/SVG related `JSX.IntrinsicElements` types are included in `@types/react` package and not `@types/react-dom`. Is there a good reason for this? As right now the `@types/react` package is unusable with custom React renderers - where for example you might have custom `<image>` element and this will conflict with already predefined SVG `<image>` element.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
