### ISSUE TITLE
[@types/strophe] Property '*' does not exist on type 'Connection'.

### ISSUE THREAD

**Issue by soundlake** [DefinitelyTyped/DefinitelyTyped#24439]
If you know how to fix the issue, make a pull request instead.

- [v] I tried using the `@types/xxxx` package and had problems.
- [v] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [v] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [v] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andy-ms 

If you do not mention the authors the issue will be ignored.

I already commented on the commit. 
See, https://github.com/DefinitelyTyped/DefinitelyTyped/commit/5316c5da8c1ace620cec8c03635ae21e14c37c1d#r28172815

os: Windows 10
node: v9.8.0
typescript: v2.4.2, v2.7.2, next

In this kind of code, `tsc` generates error "Property '*' does not exist on type 'Connection'."
```typescript
export class StropheAccountService {
  public connection: Strophe.Connection | null = null;

  private initConnection(): boolean {
    this.connection = new Strophe.Connection(this.xmppServer);

    this.connection.rawInput = (data: string)
      => this.logger.debug("RECV", data);
    this.connection.rawOutput = (data: string)
      => this.logger.debug("SEND", data);
    ...
  }

  ...
}
```

I've tried this
```diff
-        interface Connection extends _Strophe.Connection {}
+        type Connection = _Strophe.Connection;
```
like other lines in `strophe/index.d.ts`, and it simply work.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
