### ISSUE TITLE
documentdb: _etag should be mandatory in RetrievedDocument

### ISSUE THREAD

**Issue by gunzip** [DefinitelyTyped/DefinitelyTyped#24448]
Hello,
_rid, _etag and _attachments are optional here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/documentdb/index.d.ts#L138

but they should be compulsory at least on the RetrievedDocument interface where you can be sure that the _etag values is present.

@NoelAbrahams
@brettferdosi
@ctstone
@yifanwu

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
