### ISSUE TITLE
@types/amcharts not working with AmCharts 3

### ISSUE THREAD

**Issue by KevinFernandes** [DefinitelyTyped/DefinitelyTyped#24445]
- [x] I tried using the `@types/amcharts` package and had problems.
- [x] I tried using tsc 2.6.2

@ldrick 

When I install AmCharts using the following

`npm i -S amcharts3`

and also install the `@types` using 

`npm i -S @types/amcharts`

I cannot use the types because the node_module folder names do not match up (they both need to be amcharts3).

I am using Visual Studio Code for this.

I need to use the import { AmCharts } from "amcharts"; to see the types, then change it to "amcharts3" in order to build it correctly.

I apologize if there is some "obscure" way get TypeScript/VSCode to see the types appropriately that I may not be familiar with.
I already have a typesRoot defined in my tsconfig and tried a separate `<reference type="..."/>` in my code(which did not work).

Any assistance would be greatful :)

**Comment by bhaskerchari** [comment]
Probably it looks like the amcharts @types(3.21.2) should be updated to latest amcharts version(3.21.12)

Due to version in compatability I am also facing issues and someone needs to update the amcharts @types to latest version (3.21.12)

**Comment by hwaastad** [comment]
It seems 0.0.44 is the last one  working.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
