### ISSUE TITLE
Wrong type for 'dismissible' in Notification interface

### ISSUE THREAD

**Issue by Aayrton** [DefinitelyTyped/DefinitelyTyped#24463]
Hello !

I tried using the `@types/react-notification-system` package and had problems.
It seems that there is an inconsistent Notification type for the **dismissible** option.

Should be a string with 4 different values but a boolean type is declared.

Because of that closing notification modes are not available!

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-notification-system/index.d.ts

@DeividasBakanas

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
