### ISSUE TITLE
Question: Extend Chance.js via Mixin

### ISSUE THREAD

**Issue by jameswlane** [DefinitelyTyped/DefinitelyTyped#24504]
I have been trying to write a Chance.js mixin that adds additional functionality. I can't seem to figure out what exported interface to extend for it to work correctly. I was hoping one of the authors of the type library could help point me in the right direction to extend it.
 
- [X] I tried using the `@types/chance` package and had problems extending it.

`Definitions by:` in `index.d.ts`:
  - Authors: @cbowdon
  - Authors: @brikou
  - Authors: @cafesanu

**Comment by jameswlane** [comment]
The `ChanceJS` typings do not support extending with a mixin package that would be on `npm`. 

Example of the package: // index.ts

```
import * as Chance from 'chance';

export interface ITime {
  time(): string;
}

function time() {
  const h = chance.hour({ twentyfour: true });
  const m = chance.minute();
  return `${h}:${m}`;
};

export const time: ITime = {
  time,
};
```
Example of how someone would consume it:

```
import * as Chance from 'chance';
import { time } from 'chance-time';

const chance = new Chance();
chance.mixin(time);

chance.time()
```

The error I am getting is:

```
Error:(12, 14) TS2345: Argument of type 'ITime' is not assignable to parameter of type 'MixinDescriptor'.
Index signature is missing in type 'ITime'.
Error:(25, 26) TS2339: Property 'time' does not exist on type 'Chance'.
```

After hitting Stack Overflow I got this answer, that is not idea but works for the time being: https://stackoverflow.com/a/50224390/3075517

```
const chance = new Chance() as Chance.Chance & ITime;
chance.mixin(time as any); // no error
chance.time(); // no error
```

I am not sure how to update the typing to be able to support something like this, I could really use some help.

 - Authors: @cbowdon
 - Authors: @brikou
 - Authors: @cafesanu

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
