### ISSUE TITLE
New definition: https://www.npmjs.com/package/flash

### ISSUE THREAD

**Issue by elliot-huffman** [DefinitelyTyped/DefinitelyTyped#24517]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/flash` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [N/A] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

Feature request:
Please create the typings for https://github.com/expressjs/flash (https://www.npmjs.com/package/flash).
I raised a feature request over at the project's repository but they declined to include a typescript definition in the project and pointed me to ask for the feature here.

Authors?
@andy-ms @vvakame @chrootsu @borisyankov 

Thanks!

**Comment by andy-ms** [comment]
You can make a pull request adding those definitions. There's a guide available [here](http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
