### ISSUE TITLE
Express helmet definitions seem to be off

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#24525]
@nsimmons @BlueHatbRit 

- [x] I tried using the `@types/helmet` package and had problems.

I am using @types/helmet version: `"@types/helmet": "0.0.37"`
I am using helmet version: `"helmet": "~0.9.1"`

I see this in my Express server codebase:

```js

import helmet = require('helmet');

 // ....
let SIX_MONTHS = 15778476000;
app.use(helmet.xframe());
app.use(helmet.xssFilter());
app.use(helmet.nosniff());
app.use(helmet.ienoopen());

app.use(helmet.hsts({
  maxAge: SIX_MONTHS,
  includeSubdomains: true,
  force: true
}));

```

but that leads to these errors/warnings:

![screenshot 2018-03-25 19 42 38](https://user-images.githubusercontent.com/11139560/37884412-b08e4cb4-3064-11e8-8f76-eadeea04bc13.png)

It looks like `nosniff()` has become `noSniff()` and `ienoopen()` has become `ieNoOpen()`, but what about `xframe()`?

**Comment by BlueHatbRit** [comment]
Hey there @ORESoftware, if you check the [helmet docs](https://www.npmjs.com/package/helmet), and then went back to [version 0.9](https://github.com/helmetjs/helmet/tree/v0.9.0) and they seem to have always been standard camelCase

I can't find any types which are misaligned, if you check [the types themselves](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/helmet/index.d.ts) we have:

```
export interface Helmet {
...
        contentSecurityPolicy(options?: IHelmetContentSecurityPolicyConfiguration): express.RequestHandler;
        dnsPrefetchControl(options?: IHelmetDnsPrefetchControlConfiguration): express.RequestHandler;
        frameguard(options?: IHelmetFrameguardConfiguration): express.RequestHandler;
        hidePoweredBy(options?: IHelmetHidePoweredByConfiguration): express.RequestHandler;
        hpkp(options?: IHelmetHpkpConfiguration): express.RequestHandler;
        hsts(options?: IHelmetHstsConfiguration): express.RequestHandler;
        ieNoOpen(): express.RequestHandler;
        noCache(options?: Object): express.RequestHandler;
        noSniff(): express.RequestHandler;
        referrerPolicy(options?: IHelmetReferrerPolicyConfiguration): express.RequestHandler;
        xssFilter(options?: IHelmetXssFilterConfiguration): express.RequestHandler;
...
    }
```

(Condensed for brevity)

So it seems they all line up with Helmet's documentation. In the helmet module there doesn't seem to be any `xframe()` function, but there is `frameguard` so that might be what you're looking for?

I can't see any issue with the types defined in the latest version `@types/helmet` though, unless I'm missing something which is possible!

As a side note, if you're actually running `~0.9.1` of Helmet then you really should upgrade to the latest which is version `3.12.0`. You're way behind on the release line with that version and these types will continue to be updated for the latest versions rather than older versions of the package.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
