### ISSUE TITLE
es6-promises: resolved result should be optional

### ISSUE THREAD

**Issue by fatso83** [DefinitelyTyped/DefinitelyTyped#2456]
Just got a compile error because the type definitions require one to resolve a promise with a specific value. There is nothing in the specs that demand this. The definitions currently prevents us from doing 

```
new Promise(function(resolve, reject) {
     //lots of stuff, then
     longComputation(() => resolve(), (err) => reject(err));
}
```

I think the definitions should change from being 

```
constructor(callback: (resolve : (result: R) => void, reject: (error: any) => void) => void);
```

to 

```
constructor(callback: (resolve : (result?: R) => void, reject: (error: any) => void) => void);
```

Notifying @fdecampredon

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
