### ISSUE TITLE
UpsertOptions should not require returning parameter

### ISSUE THREAD

**Issue by spacem** [DefinitelyTyped/DefinitelyTyped#24576]
- [X ] I tried using the `@types/sequelize` package and had problems.
- [X ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nrschultz

Hi nrschultz, I just updated this package and now I get the error:

error TS2345: Argument of type '{ transaction: Transaction; }' is not assignable to parameter of type 'UpsertOptions & { returning: true; }'.
  Type '{ transaction: Transaction; }' is not assignable to type '{ returning: true; }'.
    Property 'returning' is missing in type '{ transaction: Transaction; }'.

I am passing just the transaction in as the options.. I think it has something to do with your commit:
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/1b53b01f4084b83fd301c8360486722799532047

You are forcing the returning parameter here.. well it can be true false or undefined but it is required.. Since UpsertOptions extends ReturningOptions it seems unnecessary to have this here?
```
upsert(values: TAttributes, options?: UpsertOptions & { returning: false | undefined }): Promise<boolean>;
upsert(values: TAttributes, options?: UpsertOptions & { returning: true }): Promise<[TInstance, boolean]>;
```

**Comment by sqmk** [comment]
I'm having a similar issue. Please correct.

**Comment by Skyied** [comment]
me too, similar error

**Comment by nrschultz** [comment]
Hey sorry @spacem @sqmk @Skyied I'll take a crack at fixing that. 

I think I see the test case I missed, the case where some UpsertOptions, but not the `returning` option are passed to the upsert function?

There is a test case where if no options are passed, it works, so I was a bit confused.  I think I have a fix for this, I'll attach the PR here when its ready.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
