### ISSUE TITLE
A project targeting ES3 that transitively depends on @types/acorn will error on compile

### ISSUE THREAD

**Issue by laughinghan** [DefinitelyTyped/DefinitelyTyped#24595]
- [x] I tried using the `@types/acorn` package and had problems.
- [x] I tried using the latest stable version of `tsc`. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @RReverser, @e-cloud 

Repro steps:

In a clean folder (not inside a repo with a `node_modules/` already):
```sh
echo 'console.log(`hello world`);' > foo.ts
npm install --no-save @types/acorn
tsc foo.ts
```

Expected behavior: `foo.ts` compiles with no problem.

Observed behavior:
```
node_modules/@types/acorn/index.d.ts(240,8): error TS2304: Cannot find name 'Symbol'.
node_modules/@types/acorn/index.d.ts(240,28): error TS2304: Cannot find name 'Iterator'.
```

I tried to fix this, but the only thing that seems to make the error go away is:
```ts
declare global {
  interface SymbolConstructor {
    readonly iterator: symbol;
  }
  var Symbol: SymbolConstructor;
}
```

Which leaks `Symbol` and `Symbol.iterator` into the global scope for `foo.ts`, when it shouldn't be available since `foo.ts` is being compiled to target ES3.

I also tried looking into what other type packages do to fix this, but I only found other type packages that have a similar problem, for example `@types/zen-observables`:
```
node_modules/@types/zen-observable/index.d.ts(35,14): error TS2304: Cannot find name 'Symbol'.
node_modules/@types/zen-observable/index.d.ts(46,6): error TS2304: Cannot find name 'Symbol'.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
