### ISSUE TITLE
@types/karma-viewport now obsolete

### ISSUE THREAD

**Issue by squidfunk** [DefinitelyTyped/DefinitelyTyped#24590]
The latest version of [karma-viewport](https://github.com/squidfunk/karma-viewport) was just released and includes it's own typings, so [`@types/karma-viewport`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/karma-viewport/index.d.ts) is obsolete. I rather recommend removing it or it would lead to confusion.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
