### ISSUE TITLE
`placeholder` is missing from `lodash/fp`

### ISSUE THREAD

**Issue by vsviridov** [DefinitelyTyped/DefinitelyTyped#24602]
- [x] I tried using the `@types/lodash` package and had problems.
- Authors: @bczengel @chrootsu @stepancar @aj-r @Ailrun @e-cloud @thorn0 @jtmthf @DomiR 

Attempting to use `import { placeholder } from 'lodash/fp'` causes an error.
```
Module "@types/lodash/fp" has no exported member 'placeholder'.

`placeholder` is often used in curried functions to change argument order.

**Comment by aj-r** [comment]
We can export `placeholder` fairly easily, but unfortunately that won't do you much good, because none of our curried functions support placeholders yet.

We should really add placeholder support to curried functions, as well as the development-time-curried fp functions.

I'm thinking we add these exports to the `LoDashFp` interface:

```ts
placeholder: _.LoDashStatic,
__: _.LoDashStatic, // __ is an alias for placeholder
```

`LoDashStatic` isn't technically 100% correct, but it is the simplest solution that maintains compatibility with the existing types for `_.partial`.

**Comment by aj-r** [comment]
Ok, I think I have something mostly working at https://github.com/aj-r/DefinitelyTyped/tree/lodash-placeholder-single-file. Unfortunately the massive number of overloads causes the tests (`npm run lint lodash`) to run out of memory. I was able to fix the memory issues by doing the following:

- Removing the parameterless overloads of the auto-curried functions. I don't see any use case for these overloads, so we might as well remove them to improve performance.
- Removing all tsdoc comments in the `fp` definitions. Surprisingly, this had the biggest impact on performance by far.
- Refactoring the `fp` definitions to be in a single file (`fp.d.ts`) instead of distributed among individual files. This reduces the build time from 10 minutes down to 1 minute.

So we have some trade-offs for getting placeholders, but I think it's more useful to support placeholders than to support parameterless overloads and tsdoc comments.
