### ISSUE TITLE
Suggested change for edges geometry in three js.  

### ISSUE THREAD

**Issue by FrickHazard** [DefinitelyTyped/DefinitelyTyped#24620]
```
export class EdgesGeometry extends BufferGeometry {
    constructor(geometry: BufferGeometry, thresholdAngle: number);
}
```
should be: 
```
export class EdgesGeometry extends BufferGeometry {
    constructor(geometry: BufferGeometry | Geometry, thresholdAngle: number);
}
```
  - Authors: @gyohk 
                  @florentpoujol
                  @SereznoKot
                  @omni360 
                  @ivoisbelongtous
                  @qszhusightp
see https://github.com/mrdoob/three.js/blob/master/src/geometries/EdgesGeometry.js

**Comment by FishOrBear** [comment]
@FrickHazard  Can you submit a PR for this?

**Comment by piranha771** [comment]
Could you please do me a favor and remove me from the author list?

I switched from three to unity due to the lack of WebGL2 support.

Thanks in advance.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
