### ISSUE TITLE
[@types/vue-scrollto] Cannot get module augmentation to work

### ISSUE THREAD

**Issue by Stoom** [DefinitelyTyped/DefinitelyTyped#24626]
Hi, I'm trying to use the vue-scrollto types in a TSX file.  No matter how I import the module, the augmentation is not working.  I currently do this with another one of my services so I know it in general works, but there is no way I've found in Vue 2.x running on TS 2.7.2 to get it to import correctly.

```typescript
import * as VueScrollTo from 'vue-scrollto';
...
this.$scrollTo('.some-class');
```

produces:
```console
ERROR in C:/projects/test.vue
101:12 Property '$scrollTo' does not exist on type 'Test'.
     99 |
  > 100 |       this.$scrollTo('.some-class');
        |            ^
```

it's the same as importing `import 'vue-scrollto' and defining the type in my own file and  importing.

CC: @vincekovacs

**Comment by leeuwd** [comment]
This worked for me:

```js
const VueScrollTo = require('vue-scrollto');
Vue.use(VueScrollTo);

VueScrollTo.scrollTo(...);
```

**Comment by ChristianStornowski** [comment]
@vincekovacs

could you add this change to be aligned with the doc:

https://www.npmjs.com/package/vue-scrollto#programatically
```
declare class VueScrollTo {
    static install: PluginFunction<never>;

    static scrollTo: VueScrollTo.VueStatic;
}
```

https://www.npmjs.com/package/vue-scrollto#easing-detailed

```
interface Options {
        ...
        easing?: string | [number, number, number, number];
        ...
    }
```

If it's okay, I can create an merge request.

**Comment by ChristianStornowski** [comment]
Everything was merged and this ticket could be closed @Stoom ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
