### ISSUE TITLE
Npm Help

### ISSUE THREAD

**Issue by tnoonan-salesforce** [DefinitelyTyped/DefinitelyTyped#24647]
I'm trying to create an npm for one of the types that I can deploy to my internal npm server for testing. Can someone shed some light on how the package json file gets generated? 

I saw something about types-publisher. But I don't see how that's used.

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/types-publisher/blob/master/src/lib/package-generator.ts ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
