### ISSUE TITLE
[@types/ramda] merge type could be improved

### ISSUE THREAD

**Issue by variousauthors** [DefinitelyTyped/DefinitelyTyped#24681]
Merge is typed like this: 

```
merge<T1, T2>(a: T1, b: T2): T1 & T2;
merge<T1>(a: T1): <T2>(b: T2) => T1 & T2;
```

So if we merge two objects that share a key, like

```
const a = {
  id: '0'
}

const b = {
  id: 0
}

merge(a, b)
```

Then the type of `id` is `number & string`. We can do better!

```
type Omit<T, K> = Pick<T, Exclude<keyof T, K>>
type Merge<T, K> = Omit<T, keyof K> & K

merge<T1, T2>(a: T1, b: T2): Merge<T1, T2>;
merge<T1>(a: T1): <T2>(b: T2) => Merge<T1, T2>;
```

Now the type of `id` will be `number`.

I will open a PR for this change if it seems OK, but it will take me some time because I am unfamiliar with DefinitelyTyped.

(this solution requires typescript 2.8)

**Comment by andnp** [comment]
FWIW, this can be done pre-TS2.8 if that's important to people.

```typescript
type Diff<T extends string, U extends string> = ({[K in T]: K} & Record<U, never> & Record<string, never>)[T];
type Omit<T extends object, K extends Keys<T>> = Pick<T, Diff<keyof T, K>>;
type Merge<T, K> = Omit<T, keyof K> & K

merge<T1, T2>(a: T1, b: T2): Merge<T1, T2>;
merge<T1>(a: T1): <T2>(b: T2) => Merge<T1, T2>;
```

Personally I would be okay with the much cleaner (and more performant) TS2.8 solution.

**Comment by tycho01** [comment]
@variousauthors consider trying the typings at [`types/npm-ramda`](https://github.com/types/npm-ramda/). while not merged here yet, they're ahead for typing ramda.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
