### ISSUE TITLE
react is at 16.3.1 and react-dom at 16.0.4

### ISSUE THREAD

**Issue by awjreynolds** [DefinitelyTyped/DefinitelyTyped#24711]
This is creating a typescript compile error due to incompatibility between react and react-dom d.ts versions.

```Subsequent property declarations must have the same type. Property 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes, HTMLAnchorElement>```

I've overcome the issue for now by placing this in my package.json
```
    "@types/react": "^16.0.40",
    "@types/react-dom": "^16.0.4",
```

**Comment by nlaffey** [comment]
The suggested package.json by awjreynolds wasn't working for me but this is:
```
    "@types/react": "16.3.4",
    "@types/react-dom": "16.0.4",
```

**Comment by Swatinem** [comment]
I have the same problem due to `react-router`.
```
node_modules/@types/react-router/node_modules/@types/react/index.d.ts(3935,13): error TS2717: Subsequent property declarations must have the same type.  Property 'view' must be of type 'SVGProps<SVGViewElement>', but here has type 'SVGProps<SVGViewElement>'.
node_modules/@types/react/index.d.ts(2221,19): error TS2320: Interface 'Element' cannot simultaneously extend types 'ReactElement<any>' and 'ReactElement<any>'.
  Named property 'type' of types 'ReactElement<any>' and 'ReactElement<any>' are not identical.
```

Well at least yarn tells me that both `react-router`, `react-router-dom` and `react-dom` depend on `@types/react@16.1`

So pinning the version to `16.1` fixed this problem for me. But hey, maybe its a yarn problem -_-

**Comment by Swatinem** [comment]
Ok, I found out it was a yarn problem.
Somehow it does not correctly dedupe the dependencies.
Try deleting your `yarn.lock` and let it create a fresh one, then it worked for me with the most recent `@types/react` version.

**Comment by jtbennett** [comment]
`@types/react-dom` also exports react types, but has not been updated to correspond with `@types/react` 16.3.  So you get a conflict between the types exported from the two modules.  

_Workaround:_ You can use `react` 16.3 now by temporarily removing `@types/react` and including only `@types/react-dom`. The downside is that if you want to use new features in 16.3 -- like createRef() and context apis, you need to sprinkle `as any` on them, because the type definitions in `@types/react-dom` 16.0 don't have those apis yet.

Of course, the real solution is for `@types/react-dom` to be updated to match `@types/react` 16.3.

**Comment by nojaf** [comment]
I'm missing `createRef` by this mismatch.
Workaround add:
```ts
declare module "react" {
  export function createRef();
}
```

**Comment by Swatinem** [comment]
Ok, this seems to basically be https://github.com/yarnpkg/yarn/issues/4489

**Comment by kamranayub** [comment]
@jtbennett Do all we need to do is rev the types for `react-dom` and it'll pull the latest React definitions? It was last updated in March.

**Comment by kamranayub** [comment]
Alright, here's a way to fix this pretty nicely for now.

In your package.json add:

```
  "resolutions": {
    "@types/react": "16.3.11"
  },
```

As [documented by Yarn here](https://yarnpkg.com/en/docs/selective-version-resolutions) this will override sub-dependency versions to resolve to your targeted version. You can use a glob pattern too.

For me, I did this, then updated to the latest `@types/react-router-dom` and it used the new `@types/react` version 👍  If you're on latest, Yarn might want you to re-install the same package so it resolves via the new resolution.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
