### ISSUE TITLE
angular-material Missing IDialogProvider interface

### ISSUE THREAD

**Issue by nikolay-borzov** [DefinitelyTyped/DefinitelyTyped#24718]
- [x] I tried using the `@types/angular-material` package and had problems.
- [x] I tried using the latest stable version of [tsc](https://www.npmjs.com/package/typescript)

Hello @blbigelow, @PeterHajdu, @Dona278, @geertjansen, @eknowles.

Definition file missing `IDialogProvider` interface. Docs are [here](https://material.angularjs.org/latest/api/service/$mdDialog#custom-presets)

**Comment by Dona278** [comment]
I created the pull request: #24733

**Comment by jpike88** [comment]
@Dona278, these types out of date, IPresetDialog should be accepting a content property, not textContent/htmlContent.

Reference: angular/material#5947

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
