### ISSUE TITLE
TinyMCE types don't reflect that setCursorPosition accepts DOM Node

### ISSUE THREAD

**Issue by viveleroi** [DefinitelyTyped/DefinitelyTyped#24773]
The definitions for TinyMCE, includes a reference to an internal `html.Node` type when it (also?) accepts a native DOM `Node`.

This causes typescript to show an error for `editor.selection.setCursorLocation(node.nextSibling, 0);` - which is valid and works when executed.

However, the definition has: `setCursorLocation(node?: html.Node, offset?: number): void;`

Typescript complains that `Node` can't be cast to `tinymce.html.Node`.

I don't see any way to cast since `tinymce.html.Node` doesn't extend `Node`.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @martinduparc   @iPoul  @nicohartto

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
