### ISSUE TITLE
Support for MODULARIZE in emcripten definitions

### ISSUE THREAD

**Issue by cpitclaudel** [DefinitelyTyped/DefinitelyTyped#24791]
Thanks for the convenient type definitions.  Emscripten now has a MODULARIZE (see https://github.com/kripken/emscripten/blob/incoming/src/settings.js#L564) setting that makes it produce better-behaved code.  With that setting, `Module` is an interface rather than a namespace.  Would it be easy to update the typescript definitions to support that?

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- Authors: @zakki @periklis

**Comment by cpitclaudel** [comment]
Sorry, it took me a bit of time to read up on the things you mentioned. I'll admit I still don't understand everything.

> I haven't encountered an application yet, which depends heavily on that, because most frontend applications solve modularization with a combination of their JS module system of choice plus a bundler if needed. 

Can you give a concrete example? I find MODULARIZE very convenient to not polute the global namespace. 

> Although, it modularizes your compiled code base every module should afaik carry its full emscripten runtime (e.g. you libc like dependencies per module), which could lead on higher bundle sizes. I suggest to take some measurements because mileage could vary on your app/system/project.

That's not much of an issue for me, as everything lives in a single large C++ object.  Is it common to have multiple EMSCRIPTEN modules? I guess I'm saying that I see value in MODULARIZE even with a single EMSCRIPTEN binary.

> I think currently the better approach is to wait to WebAssembly to deliver full module support with ES modules, because the primitives to share code on C/C++ level will play well on the WebAssembly client side incl. security/isolation (see WASM Modules).

That doesn't seem related to what MODULARIZE does; am I misunderstanding?
(My concern is pollution of the global namespace on the JS side)

> Finally, i am not so sure how to achieve a backward compatible way of supporting namespace and interface for Module in the current typings at the same time. If you have a PR or code snippet to talk about, please feel free to publish it here. I can support you with code reviews.

Tight, that's definitely tricky.  I don't have a good answer.

**Comment by wffurr** [comment]
If the Module type is declared as an interface instead of a namespace, e.g.

declare interface MainModule {
   HEAPU8, malloc, etc....
}

Then for compatibility with most Emscripten users you can add:

declare var Module: MainModule;

And users with MODULARIZE can add typings for their own named modules, e.g.

declare var MyModule: MainModule;
declare var MyModule2: MainModule;

Right now this is the only way to have multiple Emscripten modules in a single page without stuffing them all into iframes or shadow roots.

I'll send a PR next week.  I'm working on a related project to generate typings for embind code, e.g. putting C++ types into JS.  That adds the constructors for the various bound C++ classes to the Module namespace / MainModule interface.
