### ISSUE TITLE
TinyMCE definition for Formatter.formatChanged is missing callback args

### ISSUE THREAD

**Issue by viveleroi** [DefinitelyTyped/DefinitelyTyped#24817]
For TinyMCE 4.5.x+, the definition for `Formatter.formatChanged` is missing argument types passed to the `callback` method.

Currently, it defines the method as:

`formatChanged(formats: string, callback: () => void, similar: boolean): void;`

However, `callback` is invoked with two args: a `boolean` and an object `{ node, format, parents }`

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @martinduparc   @iPoul  @nicohartto

**Comment by martinduparc** [comment]
Thanks for the heads up. Feel free to submit a PR with the change

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
