### ISSUE TITLE
lodash/fp - Exported variable '...' has or is using name '...' from external module

### ISSUE THREAD

**Issue by davetayls** [DefinitelyTyped/DefinitelyTyped#24829]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @aj-r @ailrun @e-cloud @thorn0 @jtmthf @DomiR

If you do not mention the authors the issue will be ignored.

We are using the new lodash/fp types and build our code with `-d` for the declarations. 

We get the following error:

```bash
> tsc -d --inlineSources

src/lib/classnames.ts(70,14): error TS4023: Exported variable 'filterEmptyClassName' has or is using name 'Filter3x1' from external module "node_modules/@types/lodash/fp/filter" but cannot be named.
```
Because the new interfaces aren't exported we can't import that interface to fix the build. Is there an alternative way to work with these types or should the files be changed to export them?

**Comment by aj-r** [comment]
@davetayls can you add some more details about what you're trying to do? An example that reproduces this would help.

You could try updating to the latest version of `@types/lodash` (`v4.14.107`) once it's ready - hopefully within the next 48 hours. Then you could use `_.LodashFilter3x1` or `import { LodashFilter3x1 } from "lodash/fp";`. However this might not be the best idea since those interface names are auto-generated, and it's possible they could change in the future.

What exactly are you trying to do? You might be able to explicitly cast `filterEmptyClassName` to the specific function type you're looking for (maybe `(collection: ArrayLike<T> | object | null | undefined) => T[]`?).

Specifically for `LodashFilter3x1`, in the latest version it has been simplified to a type alias instead of an interface. So maybe upgrading to `4.14.107` will make things Just Work<sup>TM</sup>.

**Comment by davetayls** [comment]
thanks @aj-r, sorry for the slow response. I'll update and see if it is resolved before going further.

The ability to `import { LodashFilter3x1 } from "lodash/fp";` would solve this issue.
