### ISSUE TITLE
Chart.js chartOptions requires "scale"

### ISSUE THREAD

**Issue by Joeyn1993** [DefinitelyTyped/DefinitelyTyped#24839]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @anuti @FabienLavocat @KentarouTakeda @larrybahr @mernen @josefpaij @danmana 

I have been trying to use chartJS to make a radar chart which uses _chart.chartOptions.scale_

The types/chart.js only allows for _chartOptions.scales_

**Comment by marianazangrossi** [comment]
I faced this same problem. I was trying to create a RadarChart using the [ng2-charts](https://github.com/valor-software/ng2-charts) lib, it wasn't working until I changed the `scales` property from `ChartOptions` interface by `scale`, in the `index.d.ts`.

Besides that, in order to customize the chart's label text, I had to change the `scaleLabel` name property by `pointLabels` in the `ChartScales` interface.

Here's an example of how I resolved this: https://stackblitz.com/edit/angular-waqq2t?file=src%2Fapp%2Fapp.component.ts

However, the `scales` and `scaleLabel` properties works when building others charts, like a bar chart.

**Comment by lexasss** [comment]
The commit `296094758ac8f06a1eeb40f187c5c7aca2cdd6d8` by @ElianCordoba and merged by @sheetalkamat that introduced `scale` property in ChartOptions (used in chart with 'radar' type) is incorrect:

`scale` property already exists in RadialChartOptions, which extends ChartOptions, and it is of type RadialLinearScale. You should create the radar chart with the following code (from "chart.js-tests.ts"):

```
const radarScaleOptions: Chart.RadialLinearScale = {
    display: false,
};
const radarChartOptions: Chart.RadialChartOptions = {
    legend: { display: false },
    scale: radarScaleOptions,
};
const radar = new Chart( el, {
    type: 'radar',
    data: { ... },
    options: radarChartOptions,
});
```
Is it possible to remove this commit?

**Comment by ElianCordoba** [comment]
Hello, we should update the property not revert the commit, by the way, have you seen this #38170?

**Comment by lexasss** [comment]
Thanks, nice discussion there. Unfortunately, chart.js's docs aren't great, causing all these guesses of what typings should be there...

**Comment by indigolain** [comment]
This pull request for adding the missing properties got merged. Please try the new version of the package and see if it’ll working for you!
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38170

**Comment by lexasss** [comment]
> Please try the new version of the package and see if it’ll work for you!

Works like a charm, thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
