### ISSUE TITLE
@types/node latest tag mistakenly pointing to old version

### ISSUE THREAD

**Issue by Jessidhia** [DefinitelyTyped/DefinitelyTyped#24866]
```console
$ npm dist-tags ls @types/node
latest: 7.0.60
ts2.0: 9.6.2
ts2.1: 9.6.2
ts2.2: 9.6.2
ts2.3: 9.6.2
ts2.4: 9.6.2
ts2.5: 9.6.2
ts2.6: 9.6.2
ts2.7: 9.6.2
ts2.8: 9.6.2
ts2.9: 9.6.2
```

It looks like there was a recent update to many node versions (#24833), and the publish bot published the v7 version last.

This is a problem that happens once in a while; maybe the bot needs to be taught to not tag publishes that are not from the "top level" dir.

**Comment by simondel** [comment]
//cc @DefinitelyTyped @parambirs @tellnes @WilcoBakker @octo-sniffle @smac89 @Flarna @mwiktorczyk @wwwy3y3 @DeividasBakanas @kjin @alvis @OliverJAsh @eps1lon @Hannes-Magnusson-CK @jkomyno @ajafff @hoo29 @n-e @KSXGitHub

**Comment by Flarna** [comment]
@andy-ms  I think this is related to publishing and therefore not in hand of module itself. I think I saw this a few times before that latest tag is always put on the latest version published - even if it is not the latest of the module (like nodejs v7 in this case).

**Comment by simondel** [comment]
This seems to have been fixed 🎉 Thanks whoever did this!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
