### ISSUE TITLE
JSX.IntrinsicElements.svg can't be returned by ReactSVGElement

### ISSUE THREAD

**Issue by WebCloud** [DefinitelyTyped/DefinitelyTyped#24899]
This was a weird find.

Because `SVGProps` extends both `SVGAttributes` and `ClassAttributes`, I cannot simply create a `StatelessComponent` that returns a `JSX.IntrinsicElements.svg`. The only workaround was to mark the return type as `React.ReactElement<React.ReactSVGElement>` which seems redundant to me since `ReactSVGElement` extends `DOMElement` which in it's turn extends `ReactElement`.

Because I am relatively new to TS I cannot propose a PR, but the solution seems more like a workaround than the accurate type.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @@johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @morcerf, @tkrotoff, @DovydasNavickas, @onigoetz, @richseviora, @theruther4d, @guilhermehubner, @joshuakgoldberg, @jrakotoharisoa

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
