### ISSUE TITLE
[@types/mongoose] Add tree to Schema

### ISSUE THREAD

**Issue by ericzon** [DefinitelyTyped/DefinitelyTyped#24902]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mongoose` package and had problems.

First of all, thank you for keep updated this.

I'm initializing a model:

``` typescript
const dataSchema = new mongoose.Schema(data, options);
// if I try:
dataSchema.tree;
```
It complains saying:

Property 'tree' does not exist on type 'Schema'.

I looked inside the definitions and tried to install the latest version without luck.

@horiuchi, @sindrenm, @lukasz-zak, @Alorel, @jendrikw, @ethanresnick, @vologab

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
