### ISSUE TITLE
Add duplicating boolean to include for @types/sequelize

### ISSUE THREAD

**Issue by jschutijzer** [DefinitelyTyped/DefinitelyTyped#24907]
- [x] I tried using the `@types/sequelize` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @samuelneff @CodeAnimal @drinchev @babolivier @kukoo1 @oktapodia @morpheusxaut @TitaneBoy @zjy01 @nidzov @Raigen @todd @nrschultz

A new property duplicating (boolean) is added on include when quering. 
when false the join can only produce one row per parent row.

Can this property be added in the IncludeOptions

**Comment by todd** [comment]
Ok, great. Yeah, we'd accept a PR for that if you wanted to submit one.

**Comment by jschutijzer** [comment]
I'll see if I have time next week

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
