### ISSUE TITLE
@types/mongodb connect function options lack "auth"

### ISSUE THREAD

**Issue by Nattapong-sir** [DefinitelyTyped/DefinitelyTyped#24906]
@CaselIT 
Based on MongoDB doc [here](http://mongodb.github.io/node-mongodb-native/3.0/api/MongoClient.html#.connect)
connect suppose to have options auth: {user:string;password:string} but the definition here doesn't have one.
I'm not sure if it appropriate so I edit index.d.ts myself and add
    ```
auth?: {
        user: string;
        password: string;
    }
```
into MongoClientOptions interface.

**Comment by Nattapong-sir** [comment]
Hi @CaselIT 
I'm new to how Github work.
I created PR. Please review.

**Comment by CaselIT** [comment]
This can be closed now
@Nattapong-sir a quick tip: when you create a PR to solve an issue you can add `Closes #issuenumber` in the PR description to automatically close the issue when it's merged

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
