### ISSUE TITLE
@types/react-virtualized: Binding element 'number' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by Mario-Eis** [DefinitelyTyped/DefinitelyTyped#24949]
- [X] I tried using the `@types/react-virtualized` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kaoDev @guntherjh @wasd171 @szabolcsx @kraenhansen @Stevearzh @mgoszcz2

`Binding element 'number' implicitly has an 'any' type.` in @types/react-virtualized/dist/es/WindowScroller.d.ts(25,42):2.8.1

TypeScript Version 2.8.1
@&#8203;types/react-virtualized Version 9.18.0

**Comment by kaoDev** [comment]
hi @Mario-Eis, 
thanks for the report, the PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24953 should fix it

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
