### ISSUE TITLE
[@types/topojson] Use topojson types for topojson-client

### ISSUE THREAD

**Issue by marcoqu** [DefinitelyTyped/DefinitelyTyped#24941]
@denisname @tomwanzek @ricardo-mello 

Is it possible to use topojson types when importing only `topojson-client`?

`import * as topojson from "topojson-client";`

If I just npm install the types, tsc gives me an error.
`Could not find a declaration file for module 'topojson-client'.`

Thanks!

**Comment by denisname** [comment]
No, you can not only import `topojson-client` types.

Topojson type definition covers seven repositories (topojson, topojson-server, topojson-simplify, topojson-client, topojson-specification, us-atlas and world-atlas) some having just one function or object.

When I worked on the definition, I just improved the already existing one for TopoJSON.
I did not divide the file into seven small one—as for d3—because it seemed exaggerated to me.
Now, if using those libraries separately is a widespread use, we may plan to divide it.

In any case you can install the types with `npm install @types/topojson` and use only the one you need.

**Comment by marcoqu** [comment]
> In any case you can install the types with npm install @types/topojson and use only the one you need.

How can I make that work? I did install `@types/topojson` and `topojson-client`, but I'm getting the error `Could not find a declaration file for module 'topojson-client'.`

I don't know if using the libraries separately is a common use case, but usually topojson-client is the only part that's needed to use maps in d3-geo. See also [this question](https://stackoverflow.com/questions/46651751/where-can-i-find-typescript-typings-for-topojson-client) on Stack Exchange.

Anyways, thanks for the support!

**Comment by denisname** [comment]
Can you try again, I divided the definition in four.
Uninstall `@types/topojson` and install `@types/topojson-client`.

**Comment by marcoqu** [comment]
works great, thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
