### ISSUE TITLE
@types/mapbox-gl canvas type not allowed

### ISSUE THREAD

**Issue by salmau** [DefinitelyTyped/DefinitelyTyped#24944]
`@types/mapbox-gl` 

  -  Authors: @dobrud, @alex3165, @andy-ms

```
map.addSource('canvas', {
    'type': 'canvas',
    'canvas': 'mycanvas',
    "coordinates": [
            [-81.490, 46.437],
            [-72.582, 46.437],
            [-72.582, 38.907],
            [-81.490, 38.907]
        ],
  });
``` 
Error :
'{ 'type': "canvas"; 'canvas': string; "coordinates": number[][]; }' not allowed by the expecting types 'VectorSource | RasterSource | GeoJSONSource | ImageSource | VideoSource | GeoJSONSourceRaw'.

In your module there are types Canvas and CanvasSource. But never called why?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
