### ISSUE TITLE
[jss] Better "major version" rollout strategy?

### ISSUE THREAD

**Issue by estaub** [DefinitelyTyped/DefinitelyTyped#24955]
On the material-ui issues, I [commented](https://github.com/mui-org/material-ui/issues/10995#issuecomment-380806182):

> They (the folks working on the jss type defs) are doing some very radical changes without a good rollout process, imho. It's not clear to me what a better process would be, though; maybe someone else has a thought.

... and I was frustrated as any reader at being more critical than constructive.  So here's my best effort at constructiveness, fwiw.

The underlying issue, as I see it, is that it isn't at all obvious how the well-trod mechanisms that we use for communicating breaking changes and allowing concurrent development on them and the current version (npm versions combined with github branching) should be used on DefinitelyTyped.

All these unrelated projects are in one big repo.  It looks like the npm version numbers come from the base project (JSS); that's not helpful where the breaking changes are happening in DefinitelyTyped.  It _may_ make sense to give up tracking the JSS version number and explicitly version @types/jss differently, with a dependency in package.json that shows what it goes to.

There may be well-known (but not to me!) good practices to make this work well in DefinitelyTyped, and good examples to learn from.  It may be worth reaching out to the stewards of DefinitelyTyped for guidance.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
