### ISSUE TITLE
[@types/mongoose] dbName option missing in createConnection

### ISSUE THREAD

**Issue by coyotte508** [DefinitelyTyped/DefinitelyTyped#25000]
- [x] I tried using the `@types/mongoose` package and had problems.
- Authors: @horiuchi, @sindrenm, @lukasz-zak, @Alorel, @jendrikw, @ethanresnick, @vologab.

```
mongoose.connect(url, {dbName: 'mydb'});
```

This is invalid typescript, but it's valid javascript: http://mongoosejs.com/docs/connections.html

Currently there exists a `db` option but no `dbName`.

The `dbName` option is necessary when authentifying as a user in another database than the one we want to connect to.

**Comment by Alorel** [comment]
Create a PR then

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
