### ISSUE TITLE
[Request] machina

### ISSUE THREAD

**Issue by FranklinYu** [DefinitelyTyped/DefinitelyTyped#25075]
https://www.npmjs.com/package/machina

I may do it in the end, if I have enough time…

**Comment by ahamlinman** [comment]
There's also an open issue to add this to machina itself: https://github.com/ifandelse/machina.js/issues/158

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
