### ISSUE TITLE
error TS2503: Cannot find namespace 'DataTables'

### ISSUE THREAD

**Issue by rsamala-osius** [DefinitelyTyped/DefinitelyTyped#25085]
While Running **ng test'** got this error

Please provide a fix for the same

**  @types / datatables.net   version 1.10.9** package.json module

**Comment by Akala200** [comment]
Yeah I am having the same issue too

**Comment by kkazmierczak** [comment]
Try to import DataTablesModule in your test (spec). It helped me.

```
import { DataTablesModule } from 'angular-datatables';

 beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ MyComponent ], imports: [ DataTablesModule ]
    })
    .compileComponents();
  }));
```

**Comment by jmedinac1987** [comment]
To solve this error they must change in the package.json the dependency: "angular-datatables": "^ 0.6.3", by "angular-datatables": "^ 6.0.0".

After refreshing the package.json with the command npm install.

Note: sorry for my level of English

**Comment by balagrishnan** [comment]
Thank you so much !

**Comment by malwareoverflow** [comment]
@kkazmierczak is right by importing DataTablesModule  it worked! Thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
