### ISSUE TITLE
kafka-node: opinion about moving the type definition in the main library

### ISSUE THREAD

**Issue by zoltan-nz** [DefinitelyTyped/DefinitelyTyped#25108]
@types/kafka-node
Authors: @yoz, @amiram, @andy-ms, @hyperlink 

I just opened a question about asking around about moving the definition file in the main library:
https://github.com/SOHU-Co/kafka-node/issues/937

Could you please comment the above issue? What do you think? Thanks. :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
