### ISSUE TITLE
react-text-mask 

### ISSUE THREAD

**Issue by Mario-Eis** [DefinitelyTyped/DefinitelyTyped#25129]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/react-text-mask` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @guilhermehubner 

There seem to be two issues that I noticed in the types of react-text-mask.

First: 
mask is `mask?: maskArray | ((input: HTMLInputElement) => maskArray)` but it could also be boolean false to deactivate the mask.

Second: 
The function of mask is `(input: HTMLInputElement) => maskArray` but it should be `(input: string) => maskArray`

So I think mask should be `mask?: maskArray | ((input: string) => maskArray) | false;` At least this is how it works for me.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by dspacejs** [comment]
I'm having the same issue. `mask` should enable a boolean as the value.
