### ISSUE TITLE
[@types/chart.js] ChartData.labels can be Array<Moment> if xAxes type is 'time'

### ISSUE THREAD

**Issue by wakorb** [DefinitelyTyped/DefinitelyTyped#25171]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @FabienLavocat , @KentarouTakeda , @larrybahr , @mernen , @chicoxyzzy , @guillaume-ro-fr , @anuti 

If creating a chart with the xAxes of type 'time' like this... the labels will be an Array\<Moment\>

```
new Chart('test', {
  type: 'line',
  .......
  options: {
    scales: {
      xAxes: [{
        type: 'time'
      }],
  ......
```
The current definition doesn't support it being an Array\<Moment\>.
```
interface ChartData {
  labels?: Array<string | string[]>;
  datasets?: ChartDataSets[];
}
```
Here's a potential fix...
```
interface ChartData {
  labels?: Array<string | string[] | Moment>;
  datasets?: ChartDataSets[];
}
```
I know the fix for this is relatively simple, but I'm not sure if you want dependencies in the types files? So I didn't create a pull request for it yet...

**Comment by mernen** [comment]
Right now Chart.js has a hard dependency on Moment.js, so I guess it's okay to also have a typing dependency.

If you're going to write a patch, please also include `Date` as an alternative.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
