### ISSUE TITLE
@types/i18next wrong type for formatter

### ISSUE THREAD

**Issue by httpete** [DefinitelyTyped/DefinitelyTyped#25181]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @GiedriusGrabauskas

I don't see why the formatFunction should only accept strings, since even the i18next examples allow passing Date, Int, or String (they use typeof to do js duck typing )

    type FormatFunction = (value: string, format?: string, lng?: string) => string;

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
