### ISSUE TITLE
Breaking changes in @google-cloud/storage@1.6.x ? (BucketQuery interface for starters)

### ISSUE THREAD

**Issue by bradleyDean** [DefinitelyTyped/DefinitelyTyped#25215]
- [* ] I tried using the @types/google-cloud__storage@1.1.7 package and had problems.
- [* ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

```
import * as admin from 'firebase-admin';
admin.storage().bucket('path').deleteFiles( {force: true});//<- lint error: see below for error 
```
Error was:
Argument of type '{force:boolean}' is not assignable to type 'BucketQuery'. Object literal may only specify....

I added 'force?:boolean' to line 106 in index.d.ts, but I definitely don't think that solves all of the problems.
It seems that much has changed in [@google-cloud/storage@latest](https://cloud.google.com/nodejs/docs/reference/storage/1.6.x/Storage) (1.6.x at the time of writing)

Which version of @google-cloud/storage are these typings attempting to be compatible with?

- Authors: @blove, @nbperry 

If you do not mention the authors the issue will be ignored.

**Comment by nbperry** [comment]
@bradleyDean I believe the original type definition was v1.1.0 however over time I doubt the definition hold up to that specific version. Someone needs to go through the definitions and update all in one go so that we can re-establish an exact mapping to the current api.

**Comment by jbdemonte** [comment]
Same problem with `WriteStreamOptions` on `file.createWriteStream`
`contentType` is now out of `metadata`

**Comment by welkie** [comment]
Note that `google-cloud/storage` now includes declaration files: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28774

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
