### ISSUE TITLE
Hapi request.params type as Dictionary of String

### ISSUE THREAD

**Issue by vberistain** [DefinitelyTyped/DefinitelyTyped#25229]
- [X] I tried using the `@types/hapi` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jasonswearingen @AJamesPhillips

Hi! I have a small question regarding the basic request.param types.

I have a basic route like this one:

```javascript
interface AddResult {
    result: number
}

server.route({
    method: 'GET',
    path: '/add/{a}/{b}',
    options: {
        validate: {
            params: {
                a: Joi.number(),
                b: Joi.number()
            }
        }
    },
    handler: (request: Hapi.Request) : AddResult => {
        const {a, b} = request.params;

        return {
            result: a + b
        };
    }
});
```

But type of request params seems to be a dictionary of strings instead of a dictionary of any. Is that like this intentionally? If so how could I define the return types correctly in this case?

**Comment by SimonSchick** [comment]
Well, by default they are a string dict, so this might be a _bad_ design but maybe we should make `Hapi.Request` a generic that defaults to a dict, we could extend this to query and payload as well.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
