### ISSUE TITLE
[@types/three] Invalid paramert type for ShapeUtils.triangulateShape

### ISSUE THREAD

**Issue by spat-ne-hochu** [DefinitelyTyped/DefinitelyTyped#25250]
@types/three
three.ShapeUtils.triangulateShape
now:
export function triangulateShape(contour: number[], holes: any[]): number[];
must be:
export function triangulateShape(contour: Vector2[], holes: any[]): number[];

documentation has not type:
https://threejs.org/docs/#api/extras/ShapeUtils.triangulateShape

proof:
https://github.com/mrdoob/three.js/blob/d3f0cca97c1dfe4f2ae4830c6e88305050d7bd75/src/extras/ShapeUtils.js#L89

@gyohk @florentpoujol @omni360 @ivoisbelongtous @piranha771 @qszhusightp @nakakura @Pro

**Comment by seritools** [comment]
The actual method type seems to be

`export function triangulateShape(contour: Vector2[], holes: Vector2[][]): ([a: number, b: number, c: number])[];`

Notice how the return type is not a Vector3, but a simple array of arrays.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
