### ISSUE TITLE
Connection typings seem to be missing properties

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#25298]
- [x] I tried using the `@types/xxxx` package and had problems.

@simonxca  @fabiob @weeco @stevenmyhre 

I am successfully reading the `"host"/"port"/"name"` properties off of `mongoose.connection` at runtime. But the typings seem to be incorrect:

![screenshot 2018-04-25 10 17 48](https://user-images.githubusercontent.com/11139560/39261745-4a7cfe54-4872-11e8-9740-52df88ba471a.png)

![screenshot 2018-04-25 10 19 48](https://user-images.githubusercontent.com/11139560/39261737-4545a6b6-4872-11e8-96c0-8f3e66df1fae.png)

(Note that Prompt is just a mongoose model.)

Can we add those properties to `Connection`?

**Comment by teolag** [comment]
Got tired of these missing attributes
Created a pull request #41833

**Comment by teolag** [comment]
The pull request is now merged to master and published to npm!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
