### ISSUE TITLE
Proposal/Discussion: NodeJS.EventEmitter should be generic

### ISSUE THREAD

**Issue by SimonSchick** [DefinitelyTyped/DefinitelyTyped#25302]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @a-tarasyuk @KSXGitHub @mohsen1 @brunoscheufler (not mentioning more for now)

If you do not mention the authors the issue will be ignored.

I was wondering if at some point the definition of EventEmitter should be changed to be more generic eg.

```typescript
    export class EventEmitter<
    T extends { [key: string]: any } = { [key: string]: any },
    > {
        static listenerCount(emitter: EventEmitter, event: string | symbol): number; // deprecated
        static defaultMaxListeners: number;

        addListener<K extends keyof T>(event: K, listener: (arg: T[K]) => void): this;
        ...
```

This would drastically improve type safety for consumers and simplify definitions.

Known issues:
- 2nd degree inheritance cannot easily
 - `symbol` is not supported as a generic index type.
 - multiple arguments are not possible to be implemented this way eg. `...args`

All of these needs to be resolved either by manually declaring the signatures (as done right now) or via declaration merging (also done by some right now).

**Comment by G-Rath** [comment]
@SimonSchick Totally agree with you!

I've just published a [package](https://www.npmjs.com/package/strongly-typed-event-emitter) that handles exactly this, that could might be suitable for being directly merged into `@types/node`.

I came across this issue while making the package, and so attempted to address your points about known issues in the readme.

Here's what I came up with:

> * 2nd degree inheritance cannot easily

This one did confuse me a bit, but I think you're referring to grandchild inheritance-type situations? i.e having a child of a child of an `EventEmitter`.

If so, I found that since my typings (and TypeScript) let you merge event maps without any hassle, the best way around this is to just add a pass-through generic to your classes:

```
class Parent<T extends EventMap = {}> extends StronglyTypedEventEmitter<ParentEventsMap & T> {

}

class Child<T extends EventMap = {}> extends Parent<ChildEventsMap> {

}
```

Personally, I think this is a fine solution, as it serves as a good indicator to if an event-emitting class is actually expected to be extended from anyway.

> * symbol is not supported as a generic index type.

Was this maybe relating to something that was solved in a later version of TS?

I did have some problems with index types & `symbol`s & `string`s, but I managed to resolve them so that TS plays nice.

> * multiple arguments are not possible to be implemented this way eg. ...args

This is the biggest "unsolvable" for me so far - it might be possible to use conditional types, but I personally think it could be more trouble than it's worth.

Multiple arguments can be definitely be allowed by just adding `...args` to the end of every function that needs it, which is at least a start.

**Comment by SimonSchick** [comment]
The last issue is actually no longer, you can use generic tuples eg. `TArgs extends any[]`.
Unfortunately I don't see this happening for a very long time due to the heavy dependence on EventEmitter.
I tinkered around with using a generic version again but it would involve forcing all packages that rely on node typing to TS 3.x.
Going to close this for now.

**Comment by BrunoScheufler** [comment]
@SimonSchick hopefully adoption of up-to-date TypeScript + features will make it easier to switch to a solution utilizing generics, since I think maintaining several versions sadly outweighs the benefits of it. Maybe we can re-open this at some point in time 👍

**Comment by malthe** [comment]
Good time to reopen? It's been 5 years ...
