### ISSUE TITLE
enabled?: boolean;

### ISSUE THREAD

**Issue by golebijo** [DefinitelyTyped/DefinitelyTyped#25338]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b6a6db1be3cc11bafa9d3dba0856d7cf7e6c0e3f/types/highcharts/index.d.ts#L488

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
