### ISSUE TITLE
[@types/lodash] - FP typings: _.unset is wrongly typed as returning a boolean

### ISSUE THREAD

**Issue by Nimelrian** [DefinitelyTyped/DefinitelyTyped#25361]
- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @aj-r @Ailrun @e-cloud @thorn0 @jtmthf @DomiR

The generated types for fp.unset are currently as follows:

```ts
interface LodashUnset {
    (path: lodash.PropertyPath): LodashUnset1x1;
    (path: lodash.__, object: any): LodashUnset1x2;
    (path: lodash.PropertyPath, object: any): boolean;
}
type LodashUnset1x1 = (object: any) => boolean;
type LodashUnset1x2 = (path: lodash.PropertyPath) => boolean;
```

Which is wrong with lodash/fp where unset returns a copy of the `object` parameter with the value at `path` deleted.

```ts
import * as _ from "lodash/fp";
const foo = {a: 42, b: 1024};
const bar = _.unset(["a"], foo); // bar will have the type boolean, which is wrong.
```

Now, unset is obviously a little hard to type, but the result should definitely not be a boolean 😃

**Comment by aj-r** [comment]
Interesting - everything in the documentation indicates that the return type should be `boolean`. But you are right, it returns the object with the property removed.

I guess the return type would need to be `Partial<T>` since this is basically the same as `omit`.

Workaround for now is to use `omit` instead.

**Comment by aj-r** [comment]
Actually the return type is more complicated, because `unset` accepts a deep property path`, but `omit` accepts a shallow path only. So I'm not sure what the return type should be. Options:

1. Return the original object type. This is not totally correct because it won't indicate that certain properties could be `undefined`.
2. Return `PartialDeep<T>`. This is technically more correct, but much more annoying to work with, as it will require callers to add many explicit type assertions.

I think I'll go with option 1 because it seems much more useful to anyone calling `unset`.
