### ISSUE TITLE
youtube missing loadModule, unloadModule, getOptions, getOption, setOption

### ISSUE THREAD

**Issue by benbro** [DefinitelyTyped/DefinitelyTyped#25370]
- [x] I tried using the `@types/youtube` package and had problems.
  - Authors: @DazWilkin @ianobermiller @JoshuaKGoldberg @eliotfallon213 

Following is missing from types:
player.loadModule('captions');
player.unloadModule('captions');
player.getOptions('captions');
player.getOption('captions', 'tracklist');
player.setOption('captions', 'track', {'languageCode': 'es'});

See [StackOverflow answer](url) for usage example.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
