### ISSUE TITLE
node-fetch is not up to date with node-fetch 2.0

### ISSUE THREAD

**Issue by evert** [DefinitelyTyped/DefinitelyTyped#25404]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/node-fetch` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @torstenwerner

node-fetch went through a couple of API changes that make it closer to the MDN fetch specification. Unfortunately, this means that the DefinitelyTyped definition is now outdated. It contains functions such as `getAll()` and is missing functions such as `keys()`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
