### ISSUE TITLE
Koa2 package doesn't fully support Http2

### ISSUE THREAD

**Issue by evert** [DefinitelyTyped/DefinitelyTyped#25403]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/koa` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DavidCai1993 @jkeylu @brikou 

Hi Koa type authors!

I'm trying to use Koa with HTTP2. I noticed some of it is supported (Http2ServerResponse vs ServerResponse), but it's not supported in KoaContext.res.

I think KoaContext.res should probably be `ServerResponse | Http2ServerResponse`

**Comment by dkushner** [comment]
Interestingly, I'm having another issue related to HTTP2. Using the following versions:

```
@types/koa => 2.0.47
koa => 2.6.2
@types/node => 7.10.2
```

I'm getting the following error when attempting to compile a Koa project:

```
node_modules/@types/koa/index.d.ts:24:57 - error TS7016: Could not find a declaration file for module 'http2'. '/node_modules/http2/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/http2` if it exists or add a new declaration (.d.ts) file containing `declare module 'http2';`

24 import { Http2ServerRequest, Http2ServerResponse } from 'http2';
```

I'm unsure if this is at all relevant to your issue but this is the first time I've encountered this issue despite having used Koa/Typescript on this exact node version (v10.10.0) a number of times before.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
