### ISSUE TITLE
Auth0 JS popup methods are missing popupOptions

### ISSUE THREAD

**Issue by roldengarm** [DefinitelyTyped/DefinitelyTyped#25434]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @adrianchia @mdurrant @peterblazejewicz 

The popup functions, like authorize, have a parameter `popupOptions` to eg specify width and height.

This is missing from the TSD.

Source: https://github.com/auth0/auth0.js/blob/master/src/web-auth/popup.js#L190

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
