### ISSUE TITLE
mongodb typings seem to be incorrect

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#25439]
@beeme1mr @lihao @jloveridge @jsedlacek @julien-c @coyotte508 

- [x] I tried using the `@types/mongodb` package and had problems.

I am looking to use this pattern:

```js
'use strict';

import {MongoClient} from 'mongodb';
const url = 'mongodb://localhost';

export const client = new MongoClient(url);

client.connect(  function (err: Error) {
    !err && log.info('mongo client connected.');
});
```

the problem is, the typings don't like this pattern. The only typings support seems to be for:

```js
MongoClient.connect(url, function(err,client){
    // ...
});
```

for my program though, I am looking to export the client object, so it is synchronously available, and just use it as an event emitter.

here are the errors I get:

<img width="397" alt="screenshot 2018-04-30 18 16 43" src="https://user-images.githubusercontent.com/11139560/39457412-aa7ab484-4ca2-11e8-92f4-b85719931316.png">

<img width="475" alt="screenshot 2018-04-30 18 16 21" src="https://user-images.githubusercontent.com/11139560/39457415-aead7d2a-4ca2-11e8-88be-d7c14ac0a8fe.png">

# Versioning 
I have this in package.json

```
 "mongodb": "^3.0.7"
 "@types/mongodb": "^3.0.15"
```

**Comment by ORESoftware** [comment]
I checked out the source, looks like the typings are incorrect, I see this in the source:

```js
function MongoClient(url, options) {
  if (!(this instanceof MongoClient)) return new MongoClient();

  // Set up event emitter
  EventEmitter.call(this);

  // The internal state
  this.s = {
    url: url,
    options: options || {},
    promiseLibrary: null,
    dbCache: {},
    sessions: []
  };

  // Get the promiseLibrary
  var promiseLibrary = this.s.options.promiseLibrary || Promise;

  // Add the promise to the internal state
  this.s.promiseLibrary = promiseLibrary;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
