### ISSUE TITLE
johnny-five: Led constructor accept also string

### ISSUE THREAD

**Issue by sintetico82** [DefinitelyTyped/DefinitelyTyped#25449]
Hello,
In the javascript library, and in the examples page, for the library johnny-five.io, the Led class accept also string for pin name: http://johnny-five.io/examples/raspi-io/

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d010c2aeab88ecc300eac377ef653fbf721ab188/types/johnny-five/index.d.ts#L392

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
