### ISSUE TITLE
[documentdb]: Allow partitionKey to accept empty Objects

### ISSUE THREAD

**Issue by PrashanthCorp** [DefinitelyTyped/DefinitelyTyped#25460]
There was a solution outlined in #222 regarding queries about documents missing the partition key. Note however, that while `partitionKey: {}` works, `partitionKey: "{}"` does not.
In light of that, it looks like partition key value should allow empty objects as valid values. 

However, neither the typings in this package nor in the @types/documentdb package seem to acknowledge this. [Here's](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/documentdb/index.d.ts#L72) the mention in this package. 
@andy-ms

**Comment by andy-ms** [comment]
@PrashanthCorp Pull requests accepted.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
