### ISSUE TITLE
Variable 'global' must be of type 'global', but here has type 'Global'.

### ISSUE THREAD

**Issue by forest1102** [DefinitelyTyped/DefinitelyTyped#25478]
When I try to import`cheerio-httpcli`, I get an error.  
I am using webpack to bundle.

## Error:
```
ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:102:13
    TS2403: Subsequent variable declarations must have the same type.  Variable 'global' must be of type 'global', but here has type 'Global'.
```

## tsconfig.json

```json:tsconfig.json
{
  "compilerOptions": {
    "module": "commonjs",
    "rootDir": "./dev",
    "outDir": "./src",
    "alwaysStrict": true,
    "baseUrl": "./",
		"lib": ["es5", "es6", "dom"],
		"typeRoots": [
      "./node_modules/@types"
    ]
  },
  "include": [
    "./dev/**/*",
		"./node_modules/@types/*"
  ]
}
```

## webpack.config.js

```
const GasPlugin = require('gas-webpack-plugin');
const es3ifyPlugin = require('es3ify-webpack-plugin');

module.exports = {
  entry: './dev/index.ts',
  output: {
    filename: 'bundle.js',
    path: __dirname + '/src',
  },
  resolve: {
    extensions: ['.ts'],
  },
  module: {
    rules: [
      { test: /\.ts?$/, loader: 'awesome-typescript-loader' },
    ],
  },
  plugins: [
    new GasPlugin(),
    new es3ifyPlugin(),
  ],
};
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
