### ISSUE TITLE
Meteor.server.method_handlers[""] has not exported

### ISSUE THREAD

**Issue by tibs245** [DefinitelyTyped/DefinitelyTyped#25512]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

  - Authors: @ardatan @andy-ms 
Hi,

I use `Meteor.server.method_handlers[""]` in server unit test in TypeScript. And I have an error because type `Meteor.server` is not defined. But I don't know how resolve it.

Temporally I use solution of hwillson on this issue : https://github.com/meteor/meteor/issues/9808

Thank if you can resolve it !

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
