### ISSUE TITLE
[@types/puppeteer] Missing definition for "page._client"

### ISSUE THREAD

**Issue by mhombach** [DefinitelyTyped/DefinitelyTyped#25527]
- [x] I tried using the `puppeteer` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @marvinhagemeister
  - Authors: @cdeutsch
  - Authors: @jwbay

The definition for "page._client" is missing or more accurate, the attribute "_client" is missing.
`let page = await browser.newPage();`
`page._client.send(...) // <-`

**Comment by marvinhagemeister** [comment]
Although JavaScript doesn't have native support for private properties, the community more or less has settled on using the `_`-prefix to denote that this property/variable should not be used outside of the specific package. Since it is not part of the public API of puppeteer (it is not mentioned in their API-Documentation), it should not be exposed via our typings.

**Comment by mhombach** [comment]
This would be really bad, because many options like setting the downloadfolder, downloadbehaviour and more can only be controlled by this attribute. All answers on questions related to those settings are pointing to that attribute and methode. So you HAVE to use it, regardless of the status of the documentation. Everybody who wants to use typescript with puppeteer and needs to change settings will encounter this problem. And i think most coders will maybe just switch back to plain js.
What about implementing it as "any" but noting within the type-definition that this is maybe experimental?

**Comment by marvinhagemeister** [comment]
@mhombach I think a better solution to resolve the situation would be to poke the puppeteer developers to make this api public.

Besides, the workaround by casting to `any` works regardless of our types:

```ts
const page = await browser.newPage();

// simply cast to any
(page as any)._client.send();
```

**Comment by FiloSottile** [comment]
I believe this is now exposed (and typed) as [CDPSession](https://github.com/GoogleChrome/puppeteer/blob/v1.5.0/docs/api.md#targetcreatecdpsession)

**Comment by lockevn** [comment]
```
const client = await page.target().createCDPSession();
await client.send('Emulation.clearDeviceMetricsOverride')
```

**Comment by websolutions-hamburg** [comment]
This is not working for me:
```javascript
const client = await page.target().createCDPSession();
await client.send('Emulation.clearDeviceMetricsOverride');
await client.send('Emulation.setVisibleSize', {
  width: 200,
  height: 200
});
```

But this works:
```javascript
await page._client.send('Emulation.clearDeviceMetricsOverride');
await page._client.send('Emulation.setVisibleSize', {
  width: 200,
  height: 200
});
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by karlhorky** [comment]
The above answer from @lockevn is now outdated - `page.target()` is now deprecated:

```
The signature '(): Target' of 'page.target' is deprecated.ts(6387)

types.d.ts(4645, 8): The declaration was marked as deprecated here.

---

'target' is deprecated. Use {@link Page.createCDPSession} directly. eslint (deprecation/deprecation)

---

(method) Page.target(): Target
A target this page was created from.

@deprecated — Use Page.createCDPSession directly.
```

![See error above](https://github.com/user-attachments/assets/45fdf89c-2492-406e-8d53-87fa0750c6be)

---

Instead use `page.createCDPSession()` directly:

```ts
const client = await page.target().createCDPSession();
await client.send('Emulation.clearDeviceMetricsOverride')
```
