### ISSUE TITLE
[react-native-navigation] TabScreen interface icon shouldn't be optional?

### ISSUE THREAD

**Issue by yamiscott** [DefinitelyTyped/DefinitelyTyped#25528]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-native-navigation` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @egorshulga

Testing out react-native-navigation, icon is optional (and any - but that's an issue for another day) for a TabScreen definition. However the library checks if icon is present and fatal errors before the app even has a chance to run, resulting in a white screen and no error message if you do not provide an icon.

This only affects Android. iOS doesn't have that check in place and an icon-less tab is a very acceptable combination. Also plenty of issues here to do with the original library, like the fact that the logic is in a deprecated file and that there's a divergence between the two, but that's a bigger body of work, when a type change could remedy the issue until the next major version.

Now I understand that there are tab styles that can be used without images, however I feel the type definition file could handle this maybe with a new interface for the bottom tabbed style? Maybe this would need discussion with the react-native-navigation people.

Granted react-native-navigation is planning to move to 2.0 soon, but for now, this could cause a number of typescript users to waste a fair chunk of time trying to work out what's going wrong, when typescript could flag up that there's an icon prop missing.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
