### ISSUE TITLE
FileSaver.saveAs is not a function in angular 2

### ISSUE THREAD

**Issue by nasirbenali** [DefinitelyTyped/DefinitelyTyped#25547]
pleaze for all help my:
code fileSaver in component.ts is
`import * as FileSaver from 'file-saver'`
`FileSaver.saveAs(new Blob([s2ab(wbout)], { type: 'application/octet-stream' }), 'exported.xlsx');
`
in systemjs.cinfigjs to package is
`'file-saver': {
      format: 'global',
      main: 'FileSaver.js',
      defaultExtension: 'js'
}`
and in meta is
`'file-saver': 'npm:file-saver/FileSaver.js'`
and in map is
`'file-saver': 'node_modules/file-saver/FileSaver.js'`
and in package.json i install
"@types/file-saver": "0.0.1", 
"file-saver": "1.3.3"

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
