### ISSUE TITLE
[@types/webpack] OneOfRule does not accept a rule without a test prop

### ISSUE THREAD

**Issue by blacksails** [DefinitelyTyped/DefinitelyTyped#25559]
`{ use: ["style-loader", "css-loader"] }` doesn't type check as a `OneOfRule`.

I want to make a rule like this:

```javascript
{
	test: /\.css$/,
	oneOf: [
		{ resourceQuery: /global/, use: ["style-loader", "css-loader"] }
		{ use: ["to-string-loader", "css-loader"] }
	]
}
```

Problem is that the objects in the oneOf array doesn't have the test prop.

- [x] I tried using the `@types/webpack` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @bumbleblym @bcherny @tommytroylin @mohsen1 @jcreamer898 @ahmed-taj @alan-agius4 @elliottsj @jason0x43 @dennispg @christophehurpeau

**Comment by blacksails** [comment]
Currently working around this by including the test in each of the one of rules:
```javascript
{
	oneOf: [
		{ test: /\.css$/, resourceQuery: /global/, use: ["style-loader", "css-loader"] }
		{ test: /\.css$/, use: ["to-string-loader", "css-loader"] }
	]
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
