### ISSUE TITLE
How to stop receiving notifications?

### ISSUE THREAD

**Issue by fabiopaiva** [DefinitelyTyped/DefinitelyTyped#25563]
I'm no longer a contributor, but still receive notifications about pull requests.
How to stop receiving those notifications?

**Comment by RyanCavanaugh** [comment]
You'll need to remove your name from the header in the definition file(s) where it appears

**Comment by fabiopaiva** [comment]
I removed my name about 20 days ago, the bot still tags me

**Comment by RyanCavanaugh** [comment]
We regenned the CODEOWNERS file so you shouldn't be seeing anything now. Let me know if something unexpected pops up. Thanks!

**Comment by 9999years** [comment]
Let's make this information a **lot** clearer, and having my work attributed to my name shouldn't be the same as signing up to be a definition maintainer.

Here's the issue I was about to open, before a rephrase of the title showed me this issue:

---

I'm not a TypeScript person, really. I just don't do too much front-end work, and I'm not a big fan of JavaScript on the command line. I have a [few PRs to this repo](https://github.com/DefinitelyTyped/DefinitelyTyped/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3A9999years) because I like giving back to the community and I wanted to help improve what I think is a good project. But now, a few times a week, I get notified for pull requests on modules in this repository.

I didn't sign up to be a maintainer, and I don't want that responsibility -- I don't know much about TypeScript and I can't really evaluate the changes being requested. How do I stop getting mentions from @typescript-bot? Can we make this information a lot clearer, if there even is some sort of unsubscribe option? Some boilerplate at the bottom of the typescript-bot comments would be nice, e.g.

> Don't want to receive these notifications? Click here to unsubscribe from this module or all DefinitelyTyped notifications.

Or, better yet, move to an opt-in model of definition maintenance, if only for the reason that not every person who can submit a PR knows enough to *approve* a PR.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
