### ISSUE TITLE
passport-google-oauth Line 36: extends should be implements

### ISSUE THREAD

**Issue by RevealedFrom** [DefinitelyTyped/DefinitelyTyped#25576]
The April update changed line 36 of index.d.ts from `implements` to `extends`. It won't compile. I had to restore it to `implements` for it to work.

- [x] I tried using the `@types/passport-google-oauth` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @staticfunction 

If you do not mention the authors the issue will be ignored.

**Comment by Koslun** [comment]
This is still an issue. Other than fixing it I would add some basic tests were the types are actually used.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
