### ISSUE TITLE
@types/dhtmlxgantt destructor() function is missing

### ISSUE THREAD

**Issue by javidsapand** [DefinitelyTyped/DefinitelyTyped#25594]
- [x] [Mention] the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mkozhukh  @chriscamicas 

while calling destructor function on Gantt instance, it alerts the " property destructor does not exist on type GanttStatic ".

After adding destructor function into index.d.ts, it works.

**Comment by grbspltt** [comment]
Looks like this was fixed [here](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/13386745414c73534cb9dcaff5780f3d13dc244e)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
