### ISSUE TITLE
@types/fabric Need to add fabric.Textbox definition

### ISSUE THREAD

**Issue by mattxu-zz** [DefinitelyTyped/DefinitelyTyped#25601]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @oklemencic @joewashear007 @mrand01 @NotWoods @bmartinson @RogerioTeixeira 

I am trying to use fabric.Textbox in Angular5 project but got Textbox not defined error. I cannot find this definition in fabric-impl.d.ts.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
