### ISSUE TITLE
@types/lodash Module has no exported member

### ISSUE THREAD

**Issue by vsviridov** [DefinitelyTyped/DefinitelyTyped#25659]
Recently I've started getting errors like `Module '".../@types/lodash/index"' has no exported member `
for the methods that are definitely there, like `map`, `filter`, `find`, `each`, `includes`, etc...

Same error also happens for the `import { map } from 'lodash/map'`

@bczengel @chrootsu @stepancar @aj-r @ailrun @e-cloud @thorn0 @jtmthf @DomiR

**Comment by aj-r** [comment]
You should import like this:

import map from "lodash/map";

No braces.

**Comment by vsviridov** [comment]
Then I get 'Module has no default export'

**Comment by vsviridov** [comment]
Usually I just import them in bulk with `import { map, filter } from 'lodash'`

**Comment by aj-r** [comment]
You need to enable esModuleInterop, or do import * as map ...

The bulk import you describe should also work. Does it not?

**Comment by vsviridov** [comment]
![image](https://user-images.githubusercontent.com/221684/39835724-ede7f86e-5385-11e8-9e17-6458f5d1ee68.png)
It works for some, but not others

**Comment by antonyoneill** [comment]
Just to bump this issue, I've just installed `@types/lodash` and I'm getting the following compilation error, repeated for each module I've included.
```
TS2497: Module '"./node_modules/@types/lodash/assign"' resolves to a non-module entity and cannot be imported using this construct.
```

Source:
```
import * as first from 'lodash/first'
import * as keys from 'lodash/keys'
import * as map from 'lodash/map'
import * as reduce from 'lodash/reduce'
import * as sortBy from 'lodash/sortBy'
import * as truncate from 'lodash/truncate'
import * as values from 'lodash/values'
```

Prior to installing the types this code compiled fine (and so I will be uninstalling the types package)

Since @vsviridov has not provided you with the versions, I hope mine are helpful:
```
➜  npm list --depth=0 typescript @types/lodash lodash
js@1.0.0 .
...
├── @types/lodash@4.14.113
├── awesome-typescript-loader@3.5.0
├── lodash@4.17.10
├── typescript@2.9.1
...
➜  cat ./tsconfig.json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "jsx": "react",
    "types": [
      "webpack-env",
      "node"
    ],
    "allowJs": true,
    "lib": [
      "DOM",
      "ES5",
      "ScriptHost",
      "es2015"
    ]
  },
  "include": [
    "./src/**/*"
  ]
}
```

I include each module separately to avoid bundling the entire lodash library when I only need a handful of the utilities

**Comment by aj-r** [comment]
Ah, I've never used awesome-typescript-loader before. I will try it.

You could try setting `"esModuleInterop": true` in your tsconfig, then import like this:

```
import assign from "lodash/assign";
```

Or you could try using `lodash-es` (and `@types/lodash-es`), which uses proper es6 modules and should support tree shaking.

**Comment by a-pavlov-parc** [comment]
I have an error: 
`4,31): Module '"/Users/apavlov/Sites/webend/node_modules/@types/lodash-es/index"' has no exported member 'chain'`

I import this like this `import { groupBy, keyBy, get, chain, times, isEmpty } from 'lodash-es';`
As told @vsviridov  it works for some, but for some, it does not http://take.ms/3LJPZ

After a small investigation, [I see that there is really no appropriate type for this method here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/lodash-es)

**Comment by valentinoPereira** [comment]
lodash-es requires webpack 4.. what about webpack 3? I'm getting this error 
`Module '"c:/laragon/www/planmymedia/node_modules/@types/lodash/uniqBy"' has no default export.`
when i'm using this `import uniqBy from 'lodash/uniqBy';`

**Comment by aj-r** [comment]
Re: @valentinoPereira : I'm not sure what you mean by "lodash-es requires webpack 4". lodash-es has no dependencies, and should work with any version of webpack.

The import you show uses `lodash`, not `lodash-es`. You should do `import uniqBy from 'lodash-es/uniqBy';` (or `import {uniqBy} from 'lodash-es';` if you're using tree shaking). Or, if you want to use plain `lodash` instead of `lodash-es`, then turn on `esModuleInterop` as I mentioned in an earlier comment.

Re: @a-pavlov-parc : chaining does not work well in `lodash-es`: (see https://github.com/lodash/lodash/issues/3298). You might want to consider another approach, like using `lodash/fp` with lodah's `flow` function as described [here](https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba).

Note that you can't use `lodash-es` with the `fp` approach, so if you want tree shaking, you'll have to do it manually by importing each function from a separate file like this:

```
import map from "lodash/fp/map";
import flow from "lodash/fp/flow";
// etc.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by sirajalam049** [comment]
Now getting the same issue with get only, working for rest.

[!] (plugin rpt2) Error: /Users/sirajalam/Documents/GitHub/siraj-ml-react-forms/src/lib/ml-form-builder/index.tsx(2,54): semantic error TS2305: Module '"../../../node_modules/@types/lodash"' has no exported member 'get'.

**Comment by GMatshwane** [comment]
Has anyone found a solution to this?

**Comment by zzswang** [comment]
Has anyone found a solution to this?

**Comment by stretchkennedy** [comment]
I saw this happening with an outdated version of typescript. Fix was upgrading it. I have no idea what the original problem was.

(Just an FYI if anyone else finds this issue while searching).
