### ISSUE TITLE
Property 'styleName' does not exist in type 'HTMLProps<HTMLElement>

### ISSUE THREAD

**Issue by BnayaZil** [DefinitelyTyped/DefinitelyTyped#25658]
Using the latest `"@types/react-custom-scrollbars": "^4.0.3"` with TypeScript 2.8.3 and React 16.3.2 some how cause unrecognized `styleName` property.

I'm also using `"@types/react-css-modules": "^4.6.1"`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by yinsang** [comment]
https://github.com/gajus/babel-plugin-react-css-modules/issues/292#issuecomment-884627877
