### ISSUE TITLE
Update jsonpath types to match 1.0.0 of library

### ISSUE THREAD

**Issue by christopherbaek** [DefinitelyTyped/DefinitelyTyped#25684]
It looks like the latest types published are for 0.2.11.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8889c1c89c0cc368928421264442a38458f9f0da/types/jsonpath/index.d.ts#L1

The library has matured to 1.0.0: https://github.com/dchester/jsonpath

Can the types be updated?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
