### ISSUE TITLE
Definition for pad is now declared by its official package

### ISSUE THREAD

**Issue by wdavidw** [DefinitelyTyped/DefinitelyTyped#25716]
I dont know what is the official policy but maybe you could remove the definition from your package to avoid confusion with your users. The declaration was added with [this commit](https://github.com/adaltas/node-pad/commit/4c34996d67811ad2044bd4e36ab51c68a50859bc)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
