### ISSUE TITLE
Nodejs version 9/10 types wrong for process.emit()

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#25721]
@OliverJAsh @Flarna @hoo29 @paulvanbrenk 

- [x] I tried using the `@types/node` package and had problems.

Surely this is incorrect for process.emit()

https://stackoverflow.com/questions/50302220/cannot-use-process-on-process-emit-with-application-code

> src/index.ts:146:22 - error TS2345: Argument of type '"express.fs.cache"' is not assignable to parameter of type '"removeListener"'.
> 
> 146         process.emit(eventName, 'not using cache for file:', absFilePath);

here is the relevant EventEmitter / Events API:
https://nodejs.org/api/events.html#events_emitter_emit_eventname_args

**Comment by ORESoftware** [comment]
I was looking at the code:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L702

perhaps the typings make it so that only certain strings as the first argument are acceptable.

In that case, the compile error message could/should be different, if possible.

**Comment by Flarna** [comment]
I expect the reason is to allow only event types supported by process according to [docs](https://nodejs.org/api/process.html#process_process_events) _and_ to have specific types for each specific event listener (even technically it's possible to register and emit any other event).

Unfortunately adding an overload for "any" event (e.g. `on(event: string | symbol, listener: (...args: any[]) => void): this` results in making all the other overloads pretty useless as any typo/mismatch you have with the others will just select this catch all overload.
e.g. `process.on("removeListener", (foo: number) => {})` would compile without complain.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
