### ISSUE TITLE
AppBarProps doesnt have onLeftIconButtonTouchTap specified in its properties

### ISSUE THREAD

**Issue by ivinjose** [DefinitelyTyped/DefinitelyTyped#25739]
Im getting the following error on compiling my TSX file:

> Property 'onLeftIconButtonTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<AppBar> & Readonly<{ children?: ReactNode; }> & Re...'.

When I looked into the index file of types/material-ui, it seems that AppBarProps doesnt have **onLeftIconButtonTouchTap** mentioned in the props. Instead it has **onLeftIconButtonClick?: React.MouseEventHandler<{}>;**

What is the problem here? Am I missing some update or the typeDefinition of AppBarProps is actually missing out on the **onLeftIconButtonTouchTap**?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
