### ISSUE TITLE
[@types/lodash] Problem using `_.pick` in conjunction with `_.keys`

### ISSUE THREAD

**Issue by th0r** [DefinitelyTyped/DefinitelyTyped#25747]
Here is a code snippet:
```ts
interface FooBar {
  foo: string;
  bar: string;
}

interface Foo {
  foo: string;
}

const fooBar: FooBar = {
  foo: 'foo',
  bar: 'bar'
};

// No error
const fooValid1: Foo = _.pick(fooBar, 'foo');
// No error
const fooValid2: Foo = _.pick(fooBar, ['foo']);
// Error: `Property `foo` is optional in type `PartialDeep<FooBar>` but required in type `Foo`
const fooError: Foo = _.pick(fooBar, _.keys({foo: 1}));
```

Notice an error in line `const fooError: Foo = _.pick(fooBar, _.keys({foo: 1}))`.

Versions:
- Tested with `typescript@2.7.2 / @2.8.3`
- `@types/lodash@4.14.108`

Mentions: @bczengel @chrootsu @stepancar @aj-r @Ailrun @e-cloud @thorn0 @jtmthf @DomiR

**Comment by aj-r** [comment]
That's because `_.keys` returns `string[]` (not `("foo")[]`), so `_.pick` doesn't know which properties you're picking. As such, it just returns `PartialDeep<T>`. That said, I wonder if it should return `Partial<T>` instead of `PartialDeep<T>`.

You'll get the same issue if you use `Object.keys()` instead of `_.keys()`.

**Comment by aj-r** [comment]
Alternatively, based on what I think your use case is, a type assertion might be more useful and more accurate:

```ts
function pick<T extends object, U extends T>(source: U, template: T): T {
    return _.pick(source, _.keys(template)) as any;
}
```

I haven't tested this but hopefully it gives you a starting point.

**Comment by th0r** [comment]
Ok, got it. Thanks!

**Comment by aj-r** [comment]
That could be fixed using the function I described above:

```ts
function pickTemplate<T extends object, U extends T>(source: U, template: T): T {
    return _.pick(source, _.keys(template)) as any;
}

export class Test implements State {
  foo: State['foo'];

  initialState: State = {
    foo: 'initial'
  };

  init(): State {
    this.loadState();
    return pickTemplate(this, this.initialState);
  }

  loadState() {
    _.assign(this, this.initialState, {foo: 'loaded'});
  }
}
```

**Comment by aj-r** [comment]
For the same reasons that `Object.keys()` returns `string[]`: see https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript.

Another reason that link doesn't mention is that `keyof T` could contain non-string types (`number` or `symbol`) which will be converted to strings by `_.keys()`. For example:

```ts
const obj = {
  1: true,
  3: true,
  5: true,
};
const keys = _.keys(obj); // ["1", "3", "5"], but keyof T is 1|3|5
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
