### ISSUE TITLE
[@types/react] Component<P, S>.render() should not return undefined

### ISSUE THREAD

**Issue by carlosmunozrodriguez** [DefinitelyTyped/DefinitelyTyped#25753]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly, @bbenezech, @pzavolinsky, @ericanderson, @morcerf, @tkrotoff, @DovydasNavickas, @onigoetz, @theruther4d, @guilhermehubner, @ferdaber, @jrakotoharisoa

`Component<P, S>.render()` is currently returning `ReactNode`. it is currently defined as:

    type ReactNode = ReactChild | ReactFragment | ReactPortal | string | number | boolean | null | undefined;

The problem comes with `undefined` . Since it is actually not a valid value to be returned by a `Component`'s `render` method

Returning `undefined` from `render()` as in this code:

    import React, { Component } from 'react';
    import { render } from 'react-dom';

    class App extends Component {
        render() {
            return undefined;
        }
    }

    render(<App />, document.getElementById('root'));

Throws the following error:

<pre>
Error in /turbo_modules/fbjs@0.8.16/lib/invariant.js (42:15)
App(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
Evaluating index.js
Booting application
</pre>

You can see it live here: [render-returning-undefined](https://stackblitz.com/edit/render-returning-undefined)

Either `ReactNode` should be redefined as:

    type ReactNode = ReactChild | ReactFragment | ReactPortal | string | number | boolean | null;

Or another type (probably with a better name) should be defined as:

    type NonUndefinedReactNode = Exclude<ReactNode, undefined>;

And use this type as the return type of `Component<P, S>.render()`

**Comment by ferdaber** [comment]
I believe this is for two reasons:
* Convenience, `undefined` is valid as far as `children` are concerned (not necessarily JSX elements that eventually resolve to `children`)
* The Typescript compiler is currently limited in its typechecking and inference of JSX elements and how they are resolved, it uses the return value of `JSX.Element` but compares it to the return types of SFCs and render methods of component classes, but NOT `React.createElement` thus creating a disparity, see https://github.com/Microsoft/TypeScript/issues/21699

Until that issue in the compiler is resolved, we need to keep `undefined` as a valid return type of `ReactNode`. You should not be using `ReactNode` as a return type for your JSX constructors, as real-life usage will lead to warnings and errors like this. For more information, also see the discussion starting from here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23422#pullrequestreview-93993569.

**Comment by FredyC** [comment]
@ferdaber The `undefined` is not valid return value, see this https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23422#discussion_r165975739 from Dan ...

**Comment by ferdaber** [comment]
Yep, I think in terms of runtime `undefined` is not valid as a JSX return type, but from what I gather from the thread is that we needed to keep it due to how TS determines if a component is a valid JSX constructor (the ability to assign the return type of the component to `JSX.Element`). I could also be totally misinterpreting it in-- in which case do you remember why we chose not to remove `undefined` from `ReactNode`?

**Comment by chyzwar** [comment]
tslint is now flagging this as well:

```
React.ReactNode 
Union type cannot include both 'null' and 'undefined'. (no-null-undefined-union)
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
