### ISSUE TITLE
[@types/leaflet]: LeafletEvent lacks some members

### ISSUE THREAD

**Issue by KarloX2** [DefinitelyTyped/DefinitelyTyped#25764]
According to 
https://leafletjs.com/reference-1.3.0.html#event
the base event object has these members:

- type
- target
- sourceTarget
- propagatedFrom
- layer (but marked as deprecated)

but in types/leaflet the LeafletEvent interface has only the first two.

Do you agree that we should add sourceTarget and propagatedFrom, both as type any?

Thanks!

**Comment by KarloX2** [comment]
I created a PR

**Comment by kygoh** [comment]
> What happened to the PR?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b325764a0b804d8215611d234e63d8e9612e6402/types/leaflet/index.d.ts#L1573-L1582

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
