### ISSUE TITLE
jquery-match-height wrong type of target option

### ISSUE THREAD

**Issue by homj** [DefinitelyTyped/DefinitelyTyped#25824]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/jquery-match-height` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kbytesys 

If you do not mention the authors the issue will be ignored.

Within the `Options` interface, the type of target is not according to the definition. The type expects a `string` whereas the library expects an `JQuery<HTMLElement>` as seen in the [Example](https://github.com/liabru/jquery-match-height#custom-target-element)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
