### ISSUE TITLE
[@types/redux-actions] handleState return value should accept `S | undefined` when passed a defaultState

### ISSUE THREAD

**Issue by sargunv** [DefinitelyTyped/DefinitelyTyped#25835]
The `handleAction` function can take a `defaultState`, When given `defaultState`, it returns a reducer with a default value for the `state` parameter. Therefore, the return type for `handleAction` should be `Reducer<State | undefined, Payload>` when given a `defaultState`. It's a similar story for `handleActions` too.

- [x] I tried using the `@types/redux-actions` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jaysoo @alexgorbatchev @alechill @alexey-pelykh

**Comment by sargunv** [comment]
@alexey-pelykh You're right; I was looking at `handleActions`, where `defaultState` can be `undefined`.

https://github.com/redux-utilities/redux-actions/blob/ba71c685f5419588d663f945c7e473cac6a63301/src/handleActions.js#L13

Regardless, when `defaultState` is passed to either function, the return type should be `Reducer<State | undefined, Payload>`, since the reducer will use `defaultState` as its `initialState`.

**Comment by alexey-pelykh** [comment]
Got it, seems to me that it's a valid point where

```
const actionsHandler = ReduxActions.handleActions({
    INCREMENT: (state: number, action: ReduxActions.Action<number>) => state + action.payload,
    MULTIPLY: (state: number, action: ReduxActions.Action<number>) => state * action.payload
}, 0);
```
should be callable as
```
actionsHandler(undefined, { type: 'INCREMENT', payload: 1 }) === 1
```

**Comment by Robfz** [comment]
Was this fixed?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
