### ISSUE TITLE
Issue Ragnarok

### ISSUE THREAD

**Issue by RyanCavanaugh** [DefinitelyTyped/DefinitelyTyped#25854]
DT is sitting at > 2,000 open issues and probably no one is actually looking at them (we're certainly not). I scan the open issues once in a while to look for "something is totally broken" but the vast majority of issues are not that.

Conversely, PRs rarely close bugs if they fix them. We have no idea which issues are still valid and which aren't.

Ideally we'd be in a state where the issue tracker represents *actionable work with available resources*. This would specifically be:
 * A recent merge totally screwed up a popular package
 * DT infra is broken in some way
 * Actionable DT infra suggestions (e.g. turn on new lint rules, etc)

*Non*-valid issues would be:
 * X typing is out of date or bad (send a PR)
 * Definition requests (send a PR)
 * X typing could be better (send a PR)
 * Anything else (send a PR)

Proposed plan
 * Bulk close all existing issues
 * New issue templates
   * DT Infra bug
   * Recent major break
   * Typings complaint ("do not file")
 * DT maintainers actively monitor open issues

**Comment by RyanCavanaugh** [comment]
If you're someone who actually does follow the issue tracker for the sake of fixing bugs in existing files, please comment here so we know you exist

**Comment by GlenCFL** [comment]
I search the issue tracker for definitions that I manage every once in a while. DefinitelyTyped is a bit intimidating because 1.) the directory structure is massive, 2.) linting and running tests requires extra knowledge, and 3.) the pull request template is rather extensive. With `@types/atom`, we did have one contributor that initially started by submitting issues and later made the leap to submitting pull requests. I doubt that individual would have bothered at all if they couldn't open those initial issues here.

From looking over the issue tracker, a lot of people do respond to issues regarding their definitions when they are mentioned. I don't think barring all issues from being posted regarding definitions is the right course of action. Instead, I'd suggest categorizing and dealing with the issues a bit differently.

The meta issues:
- DT infra is broken in some way
- Actionable DT infra suggestions (e.g. turn on new lint rules, etc)

Issues regarding an existing definition would be:
- A recent merge totally screwed up a popular package
- X typing is out of date or bad (offhandedly suggest sending a PR) 
- X typing could be better (offhandedly suggest sending a PR) 

Issues without agency (and thus unlikely be even be read):
- Definition requests (emphasize sending a PR)
- Anything else (emphasize sending a PR)

My suggestion would be closing issues in the second category after a moderate amount of timed passed without activity on the issue, with issues in the third category being closed after a much shorter duration. If DT maintainers are actively monitoring issues as they are opened, then categorizing each for later handling by a bot would be ideal.

**Comment by xt0rted** [comment]
How about setting up https://probot.github.io/apps/stale/? With that any currently outstanding issues will be asked if they're still relevant and then closed if no one responds, and then from there abandoned issues will get closed automatically.

A few weeks ago support for [multiple issue templates](https://blog.github.com/2018-05-02-issue-template-improvements/) was added, so that could be used to help guide users opening new issues.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
