### ISSUE TITLE
Problem With Versione 0.7.1 and VS2017

### ISSUE THREAD

**Issue by dvign72** [DefinitelyTyped/DefinitelyTyped#25868]
HI,
i have a project in VS2015 and I migrated it to vs2017 Community Edition.

When it was migrated, I was shown that the TypeScript compiler passed from version 2.0 to 2.8 .
Since then I have not been able to complete the project.

I always have the following error:
Error	TS2430	(TS) Interface 'dxLoadPanelOptions' incorrectly extends interface 'dxOverlayOptions'.
  Types of property 'animation' are incompatible.
    Type 'AnimationOptions' has no properties in common with type '{ show?: AnimationOptions; hide?: AnimationOptions; }'.	
InternalAPI	
C:\Source\Repos\Silversea\Silversea-InternalAPI\InternalAPI\InternalAPI\Scripts\dx.all.d.ts	2206	Active

This is the version istalled:

![2018-05-18 15_19_58-internalapi - microsoft visual studio](https://user-images.githubusercontent.com/23331605/40236958-9b47f4b8-5a9e-11e8-8ca5-64323ec28b44.png)

Many thanks for the help.

Bye
dvign72

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
