### ISSUE TITLE
Unable to use SliderObject in FlexSlider definition file.

### ISSUE THREAD

**Issue by bryanjebyrd** [DefinitelyTyped/DefinitelyTyped#25891]
Currently, in a team project, a team member of mine is wanting to use the "SliderObject" interface as a type for certain instance variables and method return types. When I export the interface it works (when I don't already have jQuery being imported in my build). If I already have jQuery being imported, I get duplicate jQuery identifier errors. 
![image](https://user-images.githubusercontent.com/19267619/40274307-6ee5f092-5ba1-11e8-9493-1382e140a45e.png).

What are we doing wrong?

FYI, of course changing the type to any will allow the build to work but this does not allow the next developer to understand what type the previous developer was truly working with.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
