### ISSUE TITLE
Plotly.LayoutAxis : overlaying with regexp string check doesn't work

### ISSUE THREAD

**Issue by meriturva** [DefinitelyTyped/DefinitelyTyped#25930]
We have few problems with 

`overlaying: 'free' | '/^x([2-9]|[1-9][0-9]+)?$/' | '/^y([2-9]|[1-9][0-9]+)?$/';` type.
I guess regexp type check doesn't work well.

fyi: @chrisgervang 

Thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
