### ISSUE TITLE
rc-slider

### ISSUE THREAD

**Issue by annslittleflower** [DefinitelyTyped/DefinitelyTyped#26005]
@mantasmarcinkus please add 
`export interface SliderProps extends CommonApiProps {
    /**
     * Set initial value of slider.
     *  @default 0
     */
    defaultValue?: number;
    /**
     * Set current value of slider.
     */
    value?: number;

    tipProps? : any;
}`

so we can use tipProps which is actually there

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
