### ISSUE TITLE
Cannot add definitions which depends external npm module

### ISSUE THREAD

**Issue by ozum** [DefinitelyTyped/DefinitelyTyped#26029]
Hi,

I'm trying to add type definitions for `schwifty` module. It depends on `objection` module. `objection` is not a TypeScript library, but provides TypeScript definitions in its own repo.

I got Travis CI error `Cannot find module 'objection'.`.

How can I add definitions. Please see related PR [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25886#issuecomment-392012243)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
