### ISSUE TITLE
Is sharedWorker constructor incorrect?

### ISSUE THREAD

**Issue by iamruslanbakirov** [DefinitelyTyped/DefinitelyTyped#26032]
I'm trying to use the type definition for SharedWorker, and I noticed that the definition of the constructor is different from the documentation on the site:
https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker/SharedWorker
It seems to me that the definition of type SharedWoker is obsolete

- [ x] I tried using the `@types/sharedworker` package and had problems.
- [ x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nakakura

**Comment by akopchinskiy** [comment]
Also SharedWorker types are not detected after installation.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
