### ISSUE TITLE
MongoDB: Missing options.arrayFilters in updateOne() and alike

### ISSUE THREAD

**Issue by omaishar** [DefinitelyTyped/DefinitelyTyped#26082]
updateOne() functions (and similar functions) accepts a ReplaceOneOptions argument.
These options lack the `arrayFilters` option.
See https://docs.mongodb.com/manual/reference/command/update/#dbcmd.update

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT
                    @alanmarcell 
                    @kikar
                    @bitjson 
                    @Dante-101
                    @mcortesi
                    @EnricoPicci
                    @AJCStriker
                    @julien-c
                    @daprahamian

**Comment by CaselIT** [comment]
The documentation that you need to check for the nodejs driver is here http://mongodb.github.io/node-mongodb-native/3.0/api/Collection.html#updateOne
From that I think that the types for `updateOne` correct

Can you maybe add an example that is causing you problems?

**Comment by DiegoMajluf** [comment]
Actually checking at the link it seems that in fact is missing

![image](https://user-images.githubusercontent.com/13073664/41559370-daf23016-7311-11e8-89a3-ac471679f6ee.png)

**Comment by danieler1981** [comment]
+1

**Comment by wyattjoh** [comment]
Added the fix in #29986!

**Comment by CaselIT** [comment]
Indeed they added it. I've reviewed #29986

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
