### ISSUE TITLE
Typo in key

### ISSUE THREAD

**Issue by jenni-divvito** [DefinitelyTyped/DefinitelyTyped#26098]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/86fa899b1f403106cc30817dc38994013894820c/types/in-app-purchase/index.d.ts#L80

`date` here should actually be `data` - See the usage here: 

https://github.com/voltrue2/in-app-purchase/blob/abaf805e30bbe6cf8ada0c62ee4e2fcfebc2dd56/lib/google.js#L325

also, based on the usage in that same place, the full type should actually be more like: 

```
export type GoogleReceipt = {
  data: string | object;
  signature: string;
} | {
  receipt: string | object;
  signature: string;
} | string;
```

**Comment by LoganDark** [comment]
Pull requests are easy to make

**Comment by chris-divvito** [comment]
Probably true, I'm working to a tight deadline and have just overridden this in my own code so it wouldn't be a blocker for me. I had time to share my finding to try and help anyone else who uses these definitions, but not to pull down a new repo, learn the contribution process for it and do up a PR, sorry. I'm not expecting someone else to fix this as some kind to top priority, drop everything and do it, just reporting it using the tool made for reporting issues. If I have time after these two coming sprints I'm on and it's still hanging around I might try to jump on it, but otherwise your reply just seems like unhelpful snarkiness.

**Comment by LoganDark** [comment]
You don't have to pull a new repo, simply visit the file and click the edit button. GitHub will create a fork for you and let you edit the file in the web UI.

I can create a pull request for you if you like.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
