### ISSUE TITLE
openlayers ol.control.Control should have protected element: HTMLElement;

### ISSUE THREAD

**Issue by skewty** [DefinitelyTyped/DefinitelyTyped#26107]
openlayers ol.control.Control should have `protected element: HTMLElement`.  Without this how are subclasses expected to access the element passed to the Control constructor?

Perhaps this is an upstream issue and Control should have a `getElement()` like Overlay.

How should this be handled?

**Comment by skewty** [comment]
Still having this issue.  Would you accept a merge/ pull request?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
