### ISSUE TITLE
@types/expect: export should be wrapped in declare module

### ISSUE THREAD

**Issue by OlafMerkert** [DefinitelyTyped/DefinitelyTyped#26102]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/86fa899b1f403106cc30817dc38994013894820c/types/expect/index.d.ts#L105

The function `expect` is not correctly recognized as a global by TypeScript

When the line with the `export` is removed, the global variable is available.

Probably the `export` should be contained in a module definition?

TypeScript version 2.8.3

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
