### ISSUE TITLE
Export this type

### ISSUE THREAD

**Issue by braxtonc** [DefinitelyTyped/DefinitelyTyped#26116]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/p-defer/index.d.ts#L6

I'd love to see this interface exported.

**Comment by LoganDark** [comment]
Then make a pull request, literally adding 7 characters (`export` plus a space)

**Comment by braxtonc** [comment]
Wasn't sure what contribution rules there were. Other projects prefer to discuss issues before work is started I'll make the PR tonight.



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by LoganDark** [comment]
This isn't an issue that exactly needs to be discussed. If you need to use that type, we need to export it. It's pretty simple and easy to understand why you'd make the PR.

**Comment by LoganDark** [comment]
Your comment in a nutshell:

> Then make a pull request, literally adding 7 characters (`export` plus a space)

Which is my comment I posted about a week ago.

**Comment by andnp** [comment]
I had hoped that my comment was of a little more value than that.

---

In general, your comments (including #26098) are coming across as snarky and aggressive. Your message is consistent: "you should contribute to this codebase!"; a message with which I wholeheartedly agree. I think you would be much better received with gentler responses that do not scare away new contributors but instead provide them with the tools necessary to contribute (for instance providing links to the contribution guide).

**Comment by LoganDark** [comment]
I'm sorry if my comments seem snarky or aggressive. I guess some other people are rubbing off on me...

**Comment by braxtonchristensen** [comment]
This was actually solved before I could open a PR thanks for the help @andnp this issue can be closed since this has been merged in #25917

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
