### ISSUE TITLE
@types/react-virtualized: Does not work with cjs/non-index imports

### ISSUE THREAD

**Issue by milesj** [DefinitelyTyped/DefinitelyTyped#26134]
@kaoDev @bvaughn @mhegazy 

Importing files using their full path CJS path (`import List, { ListRowProps } from 'react-virtualized/dist/commonjs/List';`) does not work correctly as the type definitions do not export a default module. This forces us to use (`import { List, ListRowProps } from 'react-virtualized';`) which requires the consumer of our library to use tree shaking (which not everyone does).

Using the first approach errors with the following: "[ts] JSX element type 'List' does not have any construct or call signatures.", which I'm assuming is an undefined import.

**Comment by franklixuefei** [comment]
Please also consider supporting v9.19

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
