### ISSUE TITLE
There are not params in `ParseObject#clear`

### ISSUE THREAD

**Issue by jaalzateolaya** [DefinitelyTyped/DefinitelyTyped#26145]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bb1cc0e143f40f52a8d771e93036fc211df85cfb/types/parse/index.d.ts#L363

You should change this to:
~~~ts
clear () : void;
~~~

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
