### ISSUE TITLE
Cannot use namespace 'nock' as a type.

### ISSUE THREAD

**Issue by carlnc** [DefinitelyTyped/DefinitelyTyped#26162]
To allow tsc to handle the following code:

```
import * as nock from 'nock';
function doSomethingWithNock(n: nock) {
    return nock('http://localhost.com')
        .get('*')
        .reply(200, {a: {b: 'c'}})
}
doSomethingWithNock(nock);
```

Add the following to your code:

```
// @types/nock doesn't provide an interface based on the function, so ...
interface nock { (basePath: string | RegExp, options?: nock.Options): nock.Scope }
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
