### ISSUE TITLE
@types/mongoose use keyof on Documentquery

### ISSUE THREAD

**Issue by miguelcaravantes** [DefinitelyTyped/DefinitelyTyped#26186]
is it possible to overload where method in mongoose to check property names with keyof?

example: 

`where<T>(path: keyof T, val?: any): Query<any>;`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
