### ISSUE TITLE
@types/ws error with node.d.ts < version 10

### ISSUE THREAD

**Issue by Griffork** [DefinitelyTyped/DefinitelyTyped#26195]
I'm running node version 6.12 and need to use ws. The latest library isn't compatible with any node definition files older than version 10, even though ws supports everything from 4.5 up.

Related issue (not identical and is closed): https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25890

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
