### ISSUE TITLE
@types/leaflet.gridlayer.googlemutant import issues

### ISSUE THREAD

**Issue by Tonkle** [DefinitelyTyped/DefinitelyTyped#26255]
First time so forgive me for any errors reporting this issue:

I have tried using the `@types/leaflet.gridlayer.googlemutant` package and had problems.

I am trying to integrate this into an ionic app using Leaflet - Google Maps has been selected as a more cost-effective map solution.

I have installed the module and it is present in the package.json file as well as node_modules folder, however, I am unable to import it into the project. How is this plugin designed to function as it is not exporting anything to import into page I trying to display the map?

my map.ts file is importing leaflet as follows:

````
import * as L from 'leaflet';
````

The plugin does this as well but I see no way of getting that back into the App.  

Should I be loading this plugin in some specific way to get it to work as a plugin for leaflet?

Authors: @ernest-rhinozeros

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
