### ISSUE TITLE
Is there any chance to make localization?

### ISSUE THREAD

**Issue by iccfish** [DefinitelyTyped/DefinitelyTyped#2628]
Suggestion as titled. I've read contribution guide, but didn't found the way to make localization. Is there any way to do this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
