### ISSUE TITLE
@types/storybook__react - incorrect render type for RenderFunction() ?

### ISSUE THREAD

**Issue by BrendanMcK** [DefinitelyTyped/DefinitelyTyped#26311]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @joscha @wapgear 

May do a PR later, but want to get this logged for now.

Looks to me that there's an issue with how RenderFunction is declared. It was originally introduced in commit 65f13e0eefb65c1; current impl is similar to:

```
export type Renderable = React.ComponentType | JSX.Element;
export type RenderFunction = () => Renderable | Renderable[];
```

This doesn't seem correct - not sure how render could return a *Component* type.

What we probably want to do is align with what React's own [render()](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d007ed8f4b902edd24a5fb8f42c71ccd7fbd37dc/types/react/index.d.ts#L293) returns - which is [ReactNode](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d007ed8f4b902edd24a5fb8f42c71ccd7fbd37dc/types/react/index.d.ts#L148). That could be a React.ReactElement (JSX.Element is just a subtype of this, doesn't need to be called out on its own), or a fragment/number/string. I'm currently unsure if storybook itself supports the full set of types that a ReactNode could be, or if it only supports components that render to a simple ReactElement.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
