### ISSUE TITLE
Victory - type on VictoryChartProps is incorrect

### ISSUE THREAD

**Issue by vangogh500** [DefinitelyTyped/DefinitelyTyped#26310]
It should be

`style?: VictoryStyleInterface;`

instead of

`style?: React.CSSProperties`

because the props passed in are in the form "{ { parent: React,CSSProperties } }"

https://formidable.com/open-source/victory/guides/layout/

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
