### ISSUE TITLE
breeze: Validator class does not match definition

### ISSUE THREAD

**Issue by breyed** [DefinitelyTyped/DefinitelyTyped#2631]
Breeze has a `Validator` object with methods to make a new validator instances that are used like this:

```
entity.getProperty('Email').validators.push(Validator.emailAddress());
```

`breeze.d.ts` defines a `Validator` class that seems to try to reflect the Breeze definition, but is mismatched in two ways:
1. It is missing some of the validations, e.g. `emailAddress`.
2. When using a validation that it does define, the compiler complains about incorrect types. E.g.:
   
   ```
   entity.getProperty('Email').validators.push(breeze.Validator.bool); // Compiler error
   ```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
