### ISSUE TITLE
`@types/bluebird-global` and `@types/jquery` are incompatible

### ISSUE THREAD

**Issue by rkesters** [DefinitelyTyped/DefinitelyTyped#26328]
- [x] I tried using the `@types/bluebird-global` and `@types/jquery` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (2.9.1)
@d-ph @leonard-thieu @borisyankov

My Team has had `@types/jquery` installed and working. We are incrementally moving from babeled ES6 code to TS. All files have been moved to .ts and babel has been replaced with tsc. 

Today I needed to make Bluebird the global Promise. 
- Added window.Promise = Bluebird to main entry file 
- installed `@types/bluebird-global`

Now I am getting the following error
```
node_modules/@types/jquery/index.d.ts:6550:15 - error TS2430: Interface 'PromiseBase<TR, TJ, TN, UR, UJ, UN, VR, VJ, VN, SR, SJ, SN>' incorrectly extends interface 'Promise<TR>'.
  Types of property 'then' are incompatible.
    Type '{ <ARD = never, AJD = never, AND = never, BRD = never, BJD = never, BND = never, CRD = never, CJD...' is not assignable to type '{ <TResult1 = TR, TResult2 = never>(onfulfilled?: (value: TR) => TResult1 | PromiseLike<TResult1>...'.

6550     interface PromiseBase<TR, TJ, TN,
                   ~~~~~~~~~~~
```

If I uninstall `@types/bluebird-global` then I get tsc errors about Promise.map not existing. Hence it does appear that `@types/bluebird-global` and `@types/jquery` are not compatible, but the runtime is.

**Comment by d-ph** [comment]
Hi,

Could you provide me with your `tsconfig.json`, please?

**Comment by rkesters** [comment]
@d-ph thank you for the quick response.

I tried adding in the `types` but that caused all sorts of issues. 


```
{
    "compilerOptions": {
        "target": "es5",
        "module": "AMD",
        "lib": ["es5", "es6", "es7", "es2017", "dom"],
        "noImplicitAny": false,
        "allowJs": true,
        "inlineSourceMap": true,
        "inlineSources": true,
        "outDir": "dist",
        "moduleResolution": "node",
        "downlevelIteration": true,
        "rootDir": "src",
        "baseUrl": "src",
        "paths": {
            "som/*": ["*"]
        }
    },
    "include": ["src/**/*", "typings.d.ts", "global.d.ts"],
    "exclude": ["dist"]
}
```

**Comment by d-ph** [comment]
Contrary to what the error says, the conflicted methods are the "done" and "catch":

done:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b3cad84aa3f656a5f0efb2f57df662ac0b5148a0/types/bluebird-global/index.d.ts#L80
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b3cad84aa3f656a5f0efb2f57df662ac0b5148a0/types/jquery/index.d.ts#L6572

catch:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b3cad84aa3f656a5f0efb2f57df662ac0b5148a0/types/bluebird-global/index.d.ts#L137-L142
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b3cad84aa3f656a5f0efb2f57df662ac0b5148a0/types/jquery/index.d.ts#L7027

These are the only 2 methods that are customized at the same time in both bluebird and jquery. Typescript is probably doing the correct job by flagging these methods as conflicting.

This problem is a very nasty precedence. It's probably bluebird-global's fault for forcefully taking ownership of all those custom methods in the global namespace, not allowing other projects to safely extend the global Promise to add their own methods (in their own namespace).

It pains me to say this, but there's probably no clean solution to this problem. A couple of solutions that immediately come to my mind are:

1. Don't use bluebird-global. Use `@types/bluebird` only and `import Promise from 'bluebird';` manually in all files you use Promises. This is a clean solution but annoying, and is exactly the reason you wanted to use `bluebird-global` in the first place.
2. Don't use bluebird-global. Copy its `index.d.ts` to your `global.t.ds` and comment out the [done](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b3cad84aa3f656a5f0efb2f57df662ac0b5148a0/types/bluebird-global/index.d.ts#L80) and the [custom catch](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b3cad84aa3f656a5f0efb2f57df662ac0b5148a0/types/bluebird-global/index.d.ts#L137-L142) methods. This is a terrible idea to commit vendor types to your codebase, but it's still a solution.
3. `@types/jquery` should not extend the global Promise interface and instead copy and paste the `catch` and `finally` from the lib.*.d.ts files. This is obviously not going to happen.

Nothing else comes to my mind after a while of mulling this over. Maybe other guys have better ideas, but I doubt it since this is clearly bluebird-global's problem. Kind of sad to see such a common setup (jquery + bluebird) not work like this.

Not sure what to do about it. I'll continue thinking about this, but at present it looks to me like a lost cause.

**Comment by leonard-thieu** [comment]
I've submitted a PR to fix this.

jQuery's Promise implementation is actually self-contained. I added a private copy of the global Promise interface to `@types/jquery` so the interfaces won't try to merge. Ironically, I was using the global Promise interface to ensure compatibility with other Promise implementations.

**Comment by d-ph** [comment]
Thank you for that change, Leonard. Also, thanks for adding bluebird-global as a unit test for `@types/jquery` to ensure it doesn't reoccur.

Before I realised you made that change, I asked TypeScript devs to take a look a the problem as well. But since we managed to solve it between ourselves, I will close [that other ticket](https://github.com/Microsoft/TypeScript/issues/24845).

I still don't like how `bluebird-global` is the bully in this situation. I really hope javascript community will not produce any more Promise implementations now that we have the standard one and a couple of custom ones, one of which is also overriding the global one. There's plenty to choose from, so I hope conflicts between Promise .d.ts files won't occur in the future any more. In case they do happen, I'll reopen the TS github ticket.

Thanks again for your change and sorry for causing the trouble.

Cheers.
