### ISSUE TITLE
angular-desktop-notifications is incompatible with ts@next

### ISSUE THREAD

**Issue by thorn0** [DefinitelyTyped/DefinitelyTyped#26357]
Which makes Travis fail in #26321 ([Travis](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/389121824?utm_source=github_status&utm_medium=notification)) and #26178 ([Travis](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/389011502?utm_source=github_status&utm_medium=notification)).

@Dona278 Please have a look.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
