### ISSUE TITLE
[@types/jest] Missing Jest Each methods (Jest v23)

### ISSUE THREAD

**Issue by Waldo000000** [DefinitelyTyped/DefinitelyTyped#26368]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @JoshuaKGoldberg @bradleyayers 

Missing `test.each`, `it.each`, `describe.each` etc, introduced in Jest v23. E.g. below, from [the docs](https://facebook.github.io/jest/docs/en/api.html#testeachtable-name-fn)
```
test.each([[1, 1, 2], [1, 2, 3], [2, 1, 3]])(
  '.add(%i, %i)',
  (a, b, expected) => {
    expect(a + b).toBe(expected);
  },
);
```

**Comment by Miklet** [comment]
Anyone is going to work on that? I may help with this one

**Comment by Miklet** [comment]
No one replied so I would like to take this issue.

**Comment by Miklet** [comment]
My PR has been merged, I guess we can close this issue.

**Comment by rmvermeulen** [comment]
The types as they are now miss the optional timeout parameter, e.g. this reports an error:
`it.each([])('', () => {}, 5e3);`
It should be something like
```
interface Each {
        (cases: any[]): (name: string, fn: (...args: any[]) => any, timeout?: number) => void;
        (strings: TemplateStringsArray, ...placeholders: any[]): (
            name: string,
            fn: (arg: any) => any,
            timeout?: number,
        ) => void;
    }
```

**Comment by IlCallo** [comment]
This should probably be closed now

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
