### ISSUE TITLE
[@type/weixin-app ]Two wrong interfaces

### ISSUE THREAD

**Issue by SinanJS** [DefinitelyTyped/DefinitelyTyped#26372]
- [ ] I tried using the `@types/weixin-app` package and had problems.
- [ ] the formal parameter of the  function `wx.authorize` is not `options: AuthSetting`
- [ ] the `ShareMenuOptions`  is not the same as `BaseOptions`
I tried to fix them like this:
```js
interface AuthorizeOptions extends BaseOptions {
    scope: String;
  }
 function authorize(options: AuthorizeOptions): void;
```
```js
 interface ShareMenuOptions extends BaseOptions {
    withShareTicket: boolean;
 }
```
and I have make a pull request

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
