### ISSUE TITLE
`dependencies.node` in each package's `package.json` should not be '*'

### ISSUE THREAD

**Issue by KSXGitHub** [DefinitelyTyped/DefinitelyTyped#26378]
@jdneo got [a problem](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25975#issuecomment-395667045) recently. It happened because `@types/node` wasn't updated when `@types/fs-extra` is updated. I inspected `@types/fs-extra`'s [`package.json` file](https://cdn.jsdelivr.net/npm/@types/fs-extra@5.0.3/package.json) and saw this:

```json
  "dependencies": {
    "@types/node": "*"
  }
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
