### ISSUE TITLE
browser-sync additional public methods

### ISSUE THREAD

**Issue by CoskunSunali** [DefinitelyTyped/DefinitelyTyped#26417]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @thasmo, @aznnomness, @andy-ms, @yukulele 

Is it possible that you add the `cleanup` and `reset` methods to the definition file?

They are required for our build infrastructure to work.

**Comment by andy-ms** [comment]
PRs accepted.

**Comment by aznnomness** [comment]
Added the two methods requested in this issue, there were some other things that should have been added as well. Hope this helps!

PR: [#26487](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26487)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
