### ISSUE TITLE
[@types/crypto-js]

### ISSUE THREAD

**Issue by gregbown** [DefinitelyTyped/DefinitelyTyped#26453]
- [X] I tried using the `@types/crypto-js` package and had problems.

Not totally sure how to mention author or how to find the author? apologies if it's wrong.
- [X] [Mention](https://github.com/ijager) the authors (see 
  - Authors: @mhegazy

**In latest version of crypto-js**
In order to use AES decrypt the method needs to be:
```
    // decryption
    var decrypted = AES.decrypt(
      lib.CipherParams.create({ ciphertext: ciphertext}),
      key,
      {iv: iv}
    );
```

**If you know how to fix the issue, make a pull request instead.**  
Not familiar enough to know if it is a mistake or an addition that is needed?

**This would require the definition something like this?:**
```
// Type definitions for crypto-js v3.1.9

export = CryptoJS;
export as namespace CryptoJS;

declare var CryptoJS: CryptoJS.Hashes;
declare namespace CryptoJS {
	export interface Hashes {
		lib: {
			CipherParams: {
				create: (v: any) => LibWordArray;
			};
		};
	}
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
