### ISSUE TITLE
[@types/react] - No way to differentiate JSX.Element and JSX.ComponentClass

### ISSUE THREAD

**Issue by ShanonJackson** [DefinitelyTyped/DefinitelyTyped#26462]
Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson .. etc

This ticket is more of a problem than i solution (sorry in advance).
So iv'e had this problem for about 3 minor typescript versions now and all major @types/react versions i heard whispers this would be fixed in 2.9 with React.ReactElement<any> but still isn't working for me.

So this problem arises from when your stringing lots of RenderProp components together and using getBoundingClientRect() on it.

If you pass a component instance into the Props getBoundingClientRect() wont work.
I.E `<RenderPropComponent element={<NavBar/>}/>`
If you pass a valid HTML JSX.Element instance into Props getBoundingClientRect() will work as expected.
I.E ` <RenderPropComponent element={<div/>}/>`

I'd love a way for RenderPropComponent's Prop interface to be able to not accept component instances.

```
I.E
IRenderPropComponentProps {
         element: React.ReactElement<any> 
          // which should accept <div/>... <span/>... etc. but not <Navbar/>.....<SuperCheckbox/>
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
