### ISSUE TITLE
Smartfox server definitions do not match npm release client API

### ISSUE THREAD

**Issue by gpaluk** [DefinitelyTyped/DefinitelyTyped#26499]
Re: Type definitions for SmartFoxServer Apis via NuGet

  - I tried using the `@types/sfs2x-api` package and had problems.
  - Authors: @ChanceM 

I attempted to install the Retyped.smart_fox_server NuGet package from https://www.nuget.org/packages/Retyped.smart-fox-server - (Retyped, in turn, generates C# from TS definitions), however the APIs do not correlate to the latest version of SmartFox server on NPM.

Result: This results in an API mismatch caused by out-of-sync versions of the client APIs. This in turn causes runtime errors due to API mismatch.

Expected result:
The APIs would match.

Regards

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
