### ISSUE TITLE
@types/mongoose with typescript 2.9.1 - no compiliation possible

### ISSUE THREAD

**Issue by impacmp** [DefinitelyTyped/DefinitelyTyped#26511]
- [x] I tried using the `@types/mongoose` package v5.0.15 and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- Authors: @horiuchi @sindrenm @lukasz-zak @Alorel @jendrikw @vologa

`node_modules/@types/mongoose/index.d.ts:2518:29 - error TS2694: Namespace '"/.../node_modules/@types/mongodb/index"' has no exported member 'ChangeStreamOptions'.`

`node_modules/@types/mongoose/index.d.ts:2518:77 - error TS2694: Namespace '"/.../node_modules/@types/mongodb/index"' has no exported member 'ChangeStream'.`

**Comment by r3nya** [comment]
Hey @impacmp!
Can you install `@types/mongodb` and recheck it please?

**Comment by impacmp** [comment]
Hi @r3nya 
same problem with v3.0.21 of `@types/mongodb`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
