### ISSUE TITLE
Current Lodash Types module prevent to use lodash in efficient import pattern

### ISSUE THREAD

**Issue by jimjaeger** [DefinitelyTyped/DefinitelyTyped#26520]
I use lodash in typescript angular projects and there are different way to import lodash functions in a project as described here: https://medium.com/@armno/til-importing-lodash-into-angular-the-better-way-aacbeaa40473 . I want to use option that generates low footprint. So I import functions like this: import forOwn from 'lodash/forOwn';

Without the lodash types packages the import pattern works fine but when I load the latest @types/lodash module, the compile fails.

Is there any way to use the lodash package with the described import pattern and using the lodash types package too?
@bczengel @chrootsu @stepancar @aj-r @e-cloud @Ailrun @thorn0 @jtmthf @DomiR

**Comment by thorn0** [comment]
You may want to use `lodash-es` instead. See https://twitter.com/jdalton/status/893109185264500737

**Comment by aj-r** [comment]
It should work with lodash, too. Have you enabled `esModuleInterop` in your `tsconfig.json` file?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
