### ISSUE TITLE
zen-observable type definition conflicts with node

### ISSUE THREAD

**Issue by NattapongSiri** [DefinitelyTyped/DefinitelyTyped#26547]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andy-ms 

If you do not mention the authors the issue will be ignored.
observable is defined as readonly in @types/node.
However, in here, it's not. 
So typescript compiler fail.
I've tried add readonly to observable and recompile my project. It's now run fine but I've not yet tried using/testing zen-observable project myself.

**Comment by amacleay** [comment]
I think this may be resolved by #26239 - can you confirm?

**Comment by claudiordgz** [comment]
Yes @amacleay #26239 fixes, I want to add that this conflicts with rxjs as well, they also use `readonly`

**Comment by amacleay** [comment]
Yep! #26198 is tracking that currently.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
