### ISSUE TITLE
@types/selenium-webdriver/chrome.d.ts doesn't have Options.windowSize

### ISSUE THREAD

**Issue by c-yan** [DefinitelyTyped/DefinitelyTyped#26574]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/selenium-webdriver` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @BillArmstrong, @Kuniwak, @cnishina, @SupernaviX, @bendxn

If you do not mention the authors the issue will be ignored.

`windowSize` is mentioned in the following line in the comment, but it does not exist
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/selenium-webdriver/chrome.d.ts#L77

`windowSize` exists in "selenium-webdriver/chrome.js".
So, it does not exist only in type definition.
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/chrome.js#L394

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
