### ISSUE TITLE
knockout.validation async validator does not accept a function for message.

### ISSUE THREAD

**Issue by cosmoKenney** [DefinitelyTyped/DefinitelyTyped#26596]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/knockout.validation` version 0.0.36 package and had problems.
- [x] I tried using the 2.9.1 version  of tsc. 
```javascript
ko.validation.rules['licenseNumberExists'] = {
		async: true,
		validator: ( val, params, callback ) =>
		{
		},
		message: ( params, observable ) =>// error here: Type '(params: any, observable: any) => string' is not assignable to type 'string'.
		{
			return "a message"
		}
};
```
  - Authors: @danludwig @tdreyno @kamal @leemhenson @farcaller @myabc

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
