### ISSUE TITLE
@types/mongodb 3.0.20 compile error

### ISSUE THREAD

**Issue by NattapongSiri** [DefinitelyTyped/DefinitelyTyped#26599]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT 

I recently update @types/mongodb from 3.0.19 to 3.0.20 and update after, tsc complain this:
node_modules/@types/mongodb/index.d.ts:1255:24 - error TS7006: Parameter 'T' implicitly has an 'any' type.

**Comment by CaselIT** [comment]
Fixed in this https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26594

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
