### ISSUE TITLE
[@types/i18next] incorrect typings for FormatFunction

### ISSUE THREAD

**Issue by zenwarr** [DefinitelyTyped/DefinitelyTyped#26654]
Currenlly `FormatFunction` is typed like that:

```typescript
type FormatFunction = (value: string, format?: string, lng?: string) => string;
```

But in the official documentation on i18next there is an example ([https://www.i18next.com/translation-function/formatting]()) of this function accepting not only strings, but `Date` instances too:

```javascript
i18next.init({
    interpolation: {
        format: function(value, format, lng) {
            if (format === 'uppercase') return value.toUpperCase();
            if(value instanceof Date) return moment(value).format(format);
            return value;
        }
    }
});
```

@mxl, @deerawan, @GiedriusGrabauskas

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
