### ISSUE TITLE
[@types/node]: ChildProcess.on('error', ...) accepts regular Error

### ISSUE THREAD

**Issue by tylerFowler** [DefinitelyTyped/DefinitelyTyped#26653]
I noticed that the definition for `ChildProcess.on('error', ...)` has the argument type of `Error`, however in Node it's a superset of the `Error` type. Containing fields like `code` and `path`.

Can update this myself if/when I find some time but it's a bit funky because the Node docs don't actually seem to differentiate it's data type from the normal `Error` type.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
