### ISSUE TITLE
ChartLegendItem should have an index (number) field but it does not

### ISSUE THREAD

**Issue by MarkMazel** [DefinitelyTyped/DefinitelyTyped#26671]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7a1ad856b828593d7b7fde673aef98529db1f0a0/types/chart.js/index.d.ts#L120-L131

**Comment by MarkMazel** [comment]
`index?: number;`

**Comment by MarkMazel** [comment]
Index is necessary for example for filtering items based off of their number in a legend filter. This is quite useful for large datasets for doughnut plots which are prone to being over-run by their legend and running out of room.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
