### ISSUE TITLE
googlemaps OverlayView getProjection() can return undefined

### ISSUE THREAD

**Issue by JasonKleban** [DefinitelyTyped/DefinitelyTyped#26750]
googlemaps OverlayView getProjection() can return undefined  (https://stackoverflow.com/a/21645779/162273 for outside confirmation)

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/af5a943b40ee77068b73ecf2004b8159e87ec6a1/types/googlemaps/index.d.ts#L1144

I think it should be:

```
export class OverlayView extends MVCObject {
        draw(): void;
        getMap(): Map|StreetViewPanorama;
        getPanes(): MapPanes;
        getProjection(): MapCanvasProjection | undefined; // ***
        onAdd(): void;
        onRemove(): void;
        setMap(map: Map | StreetViewPanorama | null): void;
    }
```

**Comment by aivarasbiliunas** [comment]
It can return `null` and not `undefined` according to google docs. https://developers.google.com/maps/documentation/javascript/reference/map#Map.getProjection

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
