### ISSUE TITLE
[@types/jest] util.inspect(..., { compact: boolean }) is unsupported

### ISSUE THREAD

**Issue by dbkaplun** [DefinitelyTyped/DefinitelyTyped#26767]
Minimal repro:
```ts
import util from 'util';
util.inspect(1, { compact: true });
```

Here is the [changelog](https://nodejs.org/api/util.html#util_util_inspect_object_options):

Version | Changes
-- | --
v10.0.0 | The WeakMap and WeakSet entries can now be inspected.
v9.9.0 | The compact option is supported now.
v6.6.0 | Custom inspection functions can now return this.
v6.3.0 | The breakLength option is supported now.
v6.1.0 | The maxArrayLength option is supported now; in particular, long arrays are truncated by default.
v6.1.0 | The showProxy option is supported now.
v0.3.0 | Added in: v0.3.0

Bug in the source: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4ca75191c795850da4fab102a083302eb2c5fd1f/types/node/index.d.ts#L472-L480

---

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DefinitelyTyped @parambirs @tellnes @WilcoBakker @octo-sniffle @smac89 @Flarna @mwiktorczyk @wwwy3y3 @DeividasBakanas @kjin @alvis @eps1lon @Hannes-Magnusson-CK @jkomyno @ajafff @hoo29 @n-e @brunoscheufler @mohsen1 @KSXGitHub @a-tarasyuk @islishude @r3nya @ZaneHannanAU

**Comment by Flarna** [comment]
@dbkaplun Could you create a PR to add `compact`?

**Comment by ZaneHannanAU** [comment]
@Flarna I've made PR; check #26768

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
