### ISSUE TITLE
Grammar in readme is difficult to read/parse

### ISSUE THREAD

**Issue by PandaWood** [DefinitelyTyped/DefinitelyTyped#26770]
This sentence is very difficult to understand - given it's just a simple choice of 2 things.

> Generate these by running npx dts-gen --dt --name my-package-name --template module if you have npm ≥ 5.2.0, npm install -g dts-gen and dts-gen --dt --name my-package-name --template module otherwise.

Whoever wrote this should *never* write manuals for a  nuclear reactor ;-)
It could be written simply something like this:
If NPM <= v5.8:  x
Otherwise if NPM >= v5.8: y

**Comment by andnp** [comment]
So your suggestion is to move the `otherwise` from the end of the second clause to the beginning of the clause? 

Perhaps it is important to determine the intent of the sentence: if you have `npx` available, use it to run the package. Otherwise, you'll have to globally install the package first before using it.

Of course english is _never_ more understandable than some good-ole-fashion pseudo code IMO:
```no-highlight
if (NPM.version >= 5.2) command = 'npx dts-gen'
else command = 'npm install -g dts-gen && dts-gen'

execute(`${command} --dt --name my-package-name --template module`);
```
which portrays that the arguments to the command don't change regardless of the NPM version. The only variable that depends on NPM version is the command used.

---

Anyways, feel free to make a PR changing the language to something that seems a bit easier to parse! Good documentation is the foundation upon which successful open source projects stand.

**Comment by PandaWood** [comment]
Thanks, apologies, I should have taken made the PR with my best suggestion. I will do.
My main points of improvement will be to separate the 2 options onto separate lines.
And allow the user to simply copy/paste the 2 commands directly into the console and for that to work - this doesn't now because the word "and" separates the 2 commands

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
