### ISSUE TITLE
Enzyme ReactWrapper.setProps() cannot be used with children

### ISSUE THREAD

**Issue by tkrotoff** [DefinitelyTyped/DefinitelyTyped#26795]
Example (taken from https://github.com/airbnb/enzyme/issues/1384#issuecomment-347150970):

```TSX
import React from 'react';
import { mount } from 'enzyme';
import { MyComponent, Props } from './MyComponent';

const wrapper = mount<Props>(<MyComponent />);

wrapper.setProps({
  children: React.cloneElement(wrapper.props().children, {
    ...newProps
  })
});
```

Current hackish fix:

```TSX
wrapper.setProps<any>({
  children: React.cloneElement((wrapper.props() as any).children, {
    ...newProps
  })
});
```

This is because `setProps()` take `P` that does not contain `children`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8cfe3b2c5af74d7f798948d64b27ab696d1759c0/types/enzyme/index.d.ts#L553

Should be something like:
```TSX
setProps<K extends keyof P & {children: React.ReactNode}>(props: Pick<P, K>, callback?: () => void): this;
```

But I couldn't make it work. The same issue exists for `ReactWrapper.props()`: does not return `children`.

**Comment by Hotell** [comment]
Define children explicitly on Props for your component. Explicit === better API

**Comment by tkrotoff** [comment]
Shouldn't children be implicit? In react/index.d.ts it is

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
