### ISSUE TITLE
queryRenderedFeatures first argument should be optional

### ISSUE THREAD

**Issue by mapsgeek** [DefinitelyTyped/DefinitelyTyped#26901]
I tried using the `@types/mapbox-gl` package and had problems.
that the `queryRenderedFeatures` function params should be all optional

`    queryRenderedFeatures(
      pointOrBox?: PointLike | PointLike[],
      parameters?: { layers?: string[]; filter?: any[] }
    ): GeoJSON.Feature<GeoJSONGeometry>[];`

however typescript typings error if you don't pass the PointOrBox param.

- Authors: @patrickr

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
