### ISSUE TITLE
Generated Plotly.js TSD, as possible replacement for the current TSD

### ISSUE THREAD

**Issue by brian428** [DefinitelyTyped/DefinitelyTyped#26988]
@MercifulCode @szechyjs 

As referenced over in https://github.com/plotly/plotly.js/issues/28, I have written a Gradle-based TSD generator that parses the Plotly plot-schema.json and spits out a TSD. Because it uses the actual schema JSON as its primary source of information, it covers virtually the entire API.

Using a generator is pretty much mandatory, since the API is _**far**_ too big to build up a full TSD manually. My TSD is 26,000 lines long (including extensive API doc comments). o_O

I'm not sure if there is any interest in replacing the current TSD here with a more complete version. I can foresee a few issues if the switch is made:

1. I assume that anyone using the current TSD may well have some work to do in order to use the new one.
2. Because the TSD is _generated_, pull requests to fix issues in the TSD would be lost after the next regeneration. Any fixes would really need to be made to the generator code rather than the TSD itself.
3.  And tied to #2 above, that means someone (likely me) would have to take responsibility for keeping any incoming fixes synced with the generator code, and keep regenerating the TSD every so often, as new Plotly versions are released. I think I could do this for the most part, but that would obviously be subject to my schedule, work load, etc. I can try to be timely about it, but I obviously can't guarantee anything.

So, the question is basically: is having a much more complete TSD worth the above concerns/risks?

I'll attach the current TSD (for 1.38.3) so you can see what it looks like.
[plotly.js.zip](https://github.com/DefinitelyTyped/DefinitelyTyped/files/2156078/plotly.js.zip)

**Comment by MercifulCode** [comment]
@brian428 Thanks for going through this! I absolutely think having more complete information is good. 
 
You are correct that this type definition file would break users of the current one due to changed names. As a quick example, currently `plotly.ScatterData` would be replaced by `plotly.traces.Scatter`.

I do think that using the generated files does make more sense to keep everything in sync, however. Perhaps we can go even further with this automation?

Could we be able to have this gradle tool be run automatically as part of the Plotly repo itself? It could be run to generate the file as a git hook to ensure it is always up to date and requires 0 manual augmentations.

It would also deprecate this subproject as the typings would instead be in the main repo itself - while not necessarily break compatibility as users of @types/plotly.js can explicitly map the typing directory.

What do you think?

**Comment by szechyjs** [comment]
@brian428 I agree that automated typings that are synced with the plotly.js repo is a great step forward. However, I would like to see this tool merged into the upstream plotly.js repo and made part of the build/release process to npmjs. This would then allow typings to be picked up automatically by just installing plotly.js.

You mention that your generator is gradle based, are you using java? How hard would it be to work it into the [plotly.js bundle task](https://github.com/plotly/plotly.js/blob/master/tasks/bundle.js)?

**Comment by brian428** [comment]
The generator does run via Gradle, which is based on Java (Groovy, actually). I chose Gradle because I know it, and because Groovy has a lot of features that make working with JSON, strings, and object graphs very easy. 

I'm not sure how feasible it is to integrate it into the plotly.js build, which (unsurprisingly) is a Node build. A quick Google search doesn't reveal much about trying to invoke _Java (Gradle) from Node_. Are either of you aware of something that Node offers that could kick off a Gradle task?

That said, Gradle has a Node plugin that makes it quite easy to invoke _Node from Gradle_. So in theory, if the Plotly folks were OK wrapping their Node build with a Gradle build, that would be pretty easy to do. The underlying Node build would still work fine for anyone who wanted to run the Node build directly. The Gradle Node wrapper just makes it easy to to other, "non-Node" things (like run this generator, or run Java or Docker tasks in addition to running Node tasks).

Thoughts?

**Comment by brian428** [comment]
On a side, note, I'm also happy to offer up the Gradle build itself, if someone actually wanted to try and convert it to JS/TS or something. It's fairly complex, though.

**Comment by seansfkelley** [comment]
@brian428 where is the generator code now? I took a peek at your generated types and they seem much more complete than the current ones.

The chances of getting Gradle itself into a Node build are effectively zero, unfortunately for us end users. Understandably so; as a maintainer I would not want part of my build to be written in a language I don't speak. Assuming the Plotly maintainers don't incorporate any hypothetical generator written in js into their own build (https://github.com/plotly/plotly.js/issues/28), your best bet is probably to get said hypothetical generator committed here with instructions on how to run it. So for that reason, I'm curious to see what the current generator looks like.

**Comment by brian428** [comment]
Right now it's just hosted as part of my current project's internal Git repo. I'll see if I can get it up into a Github repo.

**Comment by seansfkelley** [comment]
Ping @brian428, any progress on this front? I'd consider porting it to javascript since I keep having to add tweaks to the type definitions here...

**Comment by brian428** [comment]
@seansfkelley OK, I've pushed a version of my generator to https://github.com/brian428/plotly-gradle-tsd-generator. Let me know if that's of any help. Thanks.

**Comment by seansfkelley** [comment]
Awesome, thank you!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
