### ISSUE TITLE
Some functions are missing in @types/mongodb  

### ISSUE THREAD

**Issue by yangguangqishimi** [DefinitelyTyped/DefinitelyTyped#27037]
If you know how to fix the issue, make a pull request instead.

- [ true ] I tried using the `@types/xxxx` package and had problems.
- [ true ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [true ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alanmarcell @kikar @bitjson @Dante-101 @mcortesi @EnricoPicci 

Some functions are missing in @types/mongodb  
For example:
http://mongodb.github.io/node-mongodb-native/3.1/api/MongoClient.html#withSession

**Comment by cdimitroulas** [comment]
`MongoNetworkError` is also missing

**Comment by HosseinAgha** [comment]
@yangguangqishimi. It think `withSession` is added now. You can close this.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
