### ISSUE TITLE
[@types/proj4leaflet] wrong type for bounds in imageOverlay method

### ISSUE THREAD

**Issue by gabrielnemeth** [DefinitelyTyped/DefinitelyTyped#27040]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/proj4leaflet` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @TomaszJanusz 

In definition file the method `imageOverlay` accepts bounds, but instead of `Bounds` type, what should be according to creator of the proj4leaflet, in definition file is however typed as `LatLngBoundsExpression`.

index.d.ts:

```
const imageOverlay: (imageUrl: string, bounds: LatLngBoundsExpression, options?: ImageOverlayOptions) => ImageOverlay;
```

Example from [documentation](http://kartena.github.io/Proj4Leaflet/api/#l-proj-imageoverlay):

```
// Coordinate system is EPSG:28992 / Amersfoort / RD New
var imageBounds = L.bounds(
  [145323.20011251318, 475418.56045463786],
  [175428.80013969325, 499072.9604685671]);
L.Proj.imageOverlay(
    'http://geo.flevoland.nl/arcgis/rest/services/Groen_Natuur/' +
    'Agrarische_Natuur/MapServer/export?' +
    'format=png24&transparent=true&f=image&bboxSR=28992&imageSR=28992&' +
    'layers=show%3A0&' +
    'bbox=145323.20011251318%2C475418.56045463786%2C175428.80013969325%2C499072.9604685671&size=560%2C440',
  imageBounds);
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
