### ISSUE TITLE
[Request] Type defs for @google-cloud/bigquery

### ISSUE THREAD

**Issue by mattwelke** [DefinitelyTyped/DefinitelyTyped#27111]
I use multiple Google Cloud NPM packages but the [BigQuery](https://www.npmjs.com/package/@google-cloud/bigquery) one is missing types right now. The Google Cloud team behind the product has stated that since it's pre-1.0 right now, they have no intention of creating types for it themselves and bundling them with the NPM package. They would prefer that DefinitelyTypes take this on right now (https://github.com/GoogleCloudPlatform/google-cloud-node/issues/952).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
