### ISSUE TITLE
[@types/jsforce] Missing types for Apex Rest API

### ISSUE THREAD

**Issue by eddydangel** [DefinitelyTyped/DefinitelyTyped#27139]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/jsforce` package and had problems.
- [ ] I tried using the latest stable version of jsforce 1.8.4 and missing types for Apex Rest API [Jsforce Apex REST](https://github.com/jsforce/jsforce/blob/master/lib/api/apex.js).
- [ ] [Mention]( https://github.com/dolanmiu) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dolanmiu, @netes, @tnoonan-salesforce, @WhiteAbeLincoln  

If you do not mention the authors the issue will be ignored.

**Comment by rodush** [comment]
Same issue here

**Comment by rodush** [comment]
@dolanmiu @tnoonan-salesforce guys, I'm trying to augment with the example I see in `connection.d.ts`, but if I add something like:

```typescript
import { Connection } from 'jsforce';

interface Apex {
  post(method: string, data: object, callback?: any): void
}

declare module 'jsforce' {
  interface Connection {
    apex: Apex
  }
}
```

in the code (PHP Storm) I see the striped `.login` method:

```
return new Promise((resolve, reject) => {
    try {
      // connect, login
      sfConn.login(SF_USERNAME, SF_SECRET, (loginErr: any) => {
        if (loginErr) {
          reject(loginErr);
        }

        // and send
        sfConn.apex.post(sfMethod, { data }, (postErr: any, response: any) => {
          if (postErr) {
            reject(postErr);
          }
          resolve(response);
        });
      });
    } catch (err) {
      reject(err);
    }
  });
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
