### ISSUE TITLE
[question] Is these type definitions secure for security related modules such as auth0?

### ISSUE THREAD

**Issue by RedTailBullet** [DefinitelyTyped/DefinitelyTyped#27166]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by RyanCavanaugh** [comment]
What do you mean?

**Comment by RedTailBullet** [comment]
@RyanCavanaugh I mean will the type definitions be able to change the original code? I am just worried about the security issues that might occur if I am using it for security related modules like passport and auth0.

**Comment by RyanCavanaugh** [comment]
TypeScript's types are erased; nothing in the .d.ts files will change how your code is emitted. This is an [explicit design goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) of TypeScript you can rely on

**Comment by RedTailBullet** [comment]
@RyanCavanaugh This is great news! Thank you very much.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
