### ISSUE TITLE
[@types/googlemaps] Property 'setFields()' does not exist on type 'Autocomplete'

### ISSUE THREAD

**Issue by gsse7en** [DefinitelyTyped/DefinitelyTyped#27213]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cgwrench, @nertzy, @xaolas, @mrmcnerd, @martincostello, @svenkreiss, @bolatovumar

If you do not mention the authors the issue will be ignored.
---
#### Problem description:

Trying to make an Autocomplete request explicitly without Places Details like that:
```
this.autocomplete = new google.maps.places.Autocomplete(autocompleteInput, {
  types: ['address']
});
this.autocomplete.setFields(['formatted_address']);
```

And recieve an error:
```
Typescript Error
Property 'setFields' does not exist on type 'Autocomplete'.
```

#### Possible solution

Please, add the new functionality according to sku mapping changes. [Link](https://developers.google.com/maps/documentation/javascript/reference/3.exp/places-widget)

**Comment by chilininsd** [comment]
Ping - any word on this?

**Comment by rosilio6** [comment]
is not a mistake, just tell to the compiler that the autocomplete is type of any
 const autocomplete:any = new google.maps.places.Autocomplete(
autocompleteInput, {
  types: ['address']
});

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
