### ISSUE TITLE
Error: amqp-connection-manager depends on amqplib but has a lower required TypeScript version.

### ISSUE THREAD

**Issue by aj-r** [DefinitelyTyped/DefinitelyTyped#27238]
Getting this error during the tests on the default branch:

> Error: amqp-connection-manager depends on amqplib but has a lower required TypeScript version.

This makes it difficult to run tests for any package (not just `amqplib` and `amqp-connection-manager`). I'm guessing that `amqplib` was recently modified to require a newer typescript version. Do we need to bump the typescript version of `amqp-connection-manager`? Or should we roll back the version of `amqplib`?

- [x] I tried using the `@types/amqp-connection-manager`, `@types/amqplib` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rogierschouten @mnahkies @abreits @nfantone @zelein

**Comment by rogierschouten** [comment]
amqp-connection-manager typings are brand new (today) and therefore it is safe to bump the typescript version to a more recent one.  I'm pretty sure I'm the only user of those typings and I'm on TypeScript 2.9

**Comment by Hotell** [comment]
whoever allowed to merge that, with failing build should be punished 👀! JK but cmon folks, we're better than this ✌️

![image](https://user-images.githubusercontent.com/1223799/42689222-b5ffab20-869f-11e8-8761-c1a56c6c2b20.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
