### ISSUE TITLE
Lo-Dash: Missing isEmpty() for object and array wrappers 

### ISSUE THREAD

**Issue by rla-dev** [DefinitelyTyped/DefinitelyTyped#2726]
solution: (inserted at line 190, below definition of interface LoDashWrapperBase<T, TWrapper>)

```
interface LoDashWrapperBase<T, TWrapper> {
    /**
     * Checks if value is empty.
     * @return true for arrays, strings, or arguments objects with a length of 0 and objects with no own enumerable properties
     **/
    isEmpty(): boolean;
}  
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
