### ISSUE TITLE
angular-protractor: conflict with JQuery

### ISSUE THREAD

**Issue by turp** [DefinitelyTyped/DefinitelyTyped#2734]
I'm seeing the following conflict when using Protractor with JQuery. 

```
Subsequent variable declarations must have the same type.  
Variable '$' must be of type 'cssSelectorHelper', but here has type 'JQueryStatic'.
Web\Scripts\typings\jquery\jquery.d.ts   3936
```

I tried to uninstall JQuery, but  'angularjs.TypeScript.DefinitelyTyped 2.0.6 depend(s) on it.

I'm using the following version:

```
<package id="angularjs.TypeScript.DefinitelyTyped" version="2.0.6" targetFramework="net45" /
<package id="angular-protractor.TypeScript.DefinitelyTyped" version="0.0.4" targetFramework="net45" />
<package id="jquery.TypeScript.DefinitelyTyped" version="1.3.8" targetFramework="net45" />
```

Thanks
Jay

**Comment by StanleyGoldman** [comment]
I am struggling with this issue as well

**Comment by bgever** [comment]
+1

**Comment by ShiraazMoollatjie** [comment]
+1

I ended up using the workaround suggested by @awerlang.

**Comment by tigerswithguitars** [comment]
+1 This is most annoying.

**Comment by brian428** [comment]
I'm not really sure what's not sinking in here. Angular depends on jQuery, which defines a `$()` function. The Protractor JS library also defines a `$()` function (because this is what the underlying Webdriver API is). The jQuery and Protractor TSD's can only match the API declared by the original JS libraries. If you include both the Angular and Protractor TSDs, you're going to have a conflict. There's nothing the author of the Protractor TSD can do about this.

The only possible option would be to create a Protractor TSD that omits `$()` from the definition. But then, anyone using the TSD would be forced to use something like `element(by.css(selector))` everywhere, instead of `$()`. And I doubt that anyone would be happy with that.

Since I don't think there's no reason for Protractor code to depend on Angular or jQuery anyway, the only viable solution seems to be just not referencing the Angular TSD within the Protractor project/code.

**Comment by jt000** [comment]
If you're using Visual Studio to build & have both protractor/angular in the same project, then please put your "+1" in https://github.com/Microsoft/TypeScript/issues/1516 to let them know I'm not the only one seeing this issue

**Comment by tigerswithguitars** [comment]
This is the first google hit for the issue. I knew at the time it was VS's fault but the red mis, it made me do it.

**Comment by awerlang** [comment]
For those who want main app and tests on the same VS project, refer to PR #3528. Get it and see if anything's broken at your side. It must fix this issue.

**Comment by brp-nylin** [comment]
+1

This is really annoying indeed. I wonder why protractor used $ in the first place, wasn't jQuery well established when Protractor was developed? I can't get my e2e tests compiled with TS and TSLint and don't seem to find a way of fixing this.

Has anyone found a good workaround? I was thinking about settings up two tsd folders, but since both my app and my e2e tests needs type definitions for angular this wouldn't help anyway.

I understand the implications of this problem, and that it doesn't really help anyone to

**Comment by brian428** [comment]
Protractor is just a wrapper for Selenium/Webdriver, which uses $ and $$ extensively.

However, I'm not sure why your e2e tests project would actually need the Angular or JQuery definitions?

**Comment by nylin** [comment]
Hey (same guy, different account), no I was thinking about that a moment later and realized what you say is true. It should really be just black box testing in that case. Guess I confused it with unit testing somehow, I blame it on an empty stomach.

**Comment by stites** [comment]
+1 @brian428

Keep in mind that angular-mocks also has a reference to `angular.d.ts` — so you may have to further split your unit test definition files from your e2e ones.

**Comment by chaosmail** [comment]
Hi guys,

I sent a PR to DefinitelyTyped [https://github.com/borisyankov/DefinitelyTyped/pull/4844](https://github.com/borisyankov/DefinitelyTyped/pull/4844) to allow embedding of a noConflict version of jQuery. This would be an acceptable solution for me. Please feel free to add your comments and thoughts to the proposed workaround.

Until this PR is merged, I use the following `tsd.json` configuration (I am using a fork of DefinitelyTyped and replaced the jQuery lib). A `tsd reinstall -o` should override the current jQuery version.

```
{
  "version": "v4",
  "repo": "chaosmail/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "angularjs/angular.d.ts": {
      "commit": "2d4c4679bc2b509f27435a4f9da5e2de11258571"
    },
    "jquery/jquery-noconflict.d.ts": {
      "commit": "1e605ca6ca1a4b744077898ab9ffa758a09cd3c6"
    },
    "angular-protractor/angular-protractor.d.ts": {
      "commit": "2fe8a6fda29c3340a5e5672b1809a84c88729a30"
    },
    "selenium-webdriver/selenium-webdriver.d.ts": {
      "commit": "2fe8a6fda29c3340a5e5672b1809a84c88729a30"
    }
  }
}
```

Hope this helps someone.

Best.
Christoph

**Comment by basarat** [comment]
Here's what I did for converting the official AngularSeed project for TypeScript : https://github.com/Microsoft/TypeScriptSamples/blob/master/angular1/CONVERSION.md

The final project : https://github.com/Microsoft/TypeScriptSamples/tree/master/angular1

**Comment by SergeySolonko** [comment]
It won't work if your tests will include functionality, which depends on jQuery.

**Comment by awerlang** [comment]
@SergeySolonko to test `controller`'s you use karma, not protractor. A unit test is what you need, while protractor offers integration tests.

**Comment by SergeySolonko** [comment]
@awerlang you're right. But in this case unit tests also use jasmine and maybe another libraries for testing. And in this case if you'll create one typings.d.ts file and include it for all types of testings - you'll get this error. And in this case you'll need to create 3 typings.d.ts files:

```
typings.d.ts - for you app sources
typings.tests.unit.d.ts - for your unit tests
typings.tests.e2e.d.ts - for your e2e tests
```
Difference between them will be in these files:
```
/// <reference path="../typings/angular-protractor/angular-protractor.d.ts" />
/// <reference path="../typings/selenium-webdriver/selenium-webdriver.d.ts" />
```
Rest of the references should be the same.
Right?

**Comment by brian428** [comment]
Correct. I use separate TSDs, and separate gulp tasks to compile source vs. test code.

**Comment by xFrigginx** [comment]
+1

**Comment by nylin** [comment]
Hello!

 

You have a new message, please read <http://analyticmarketing.net/expertise.php?e0ct>

 

max@articstudios.se

**Comment by nylin** [comment]
Hello!

 

You have a new message, please read <http://beautyshub.com/represent.php?97fbp>

 

max@articstudios.se

**Comment by nylin** [comment]
Hey,
Have you heard the latest news? You're gonna love this, check it out here <http://shundudapo.freetransmediawhitepaper.com/lnftk>
Looking forward, max@articstudios.se

**Comment by mirikle** [comment]
+1

**Comment by AloeDream** [comment]
+1

**Comment by CristyTarantino** [comment]
+1

**Comment by tylerjvick** [comment]
+1

**Comment by hirako2000** [comment]
+1

**Comment by mchurichi** [comment]
+1

**Comment by jakeNiemiec** [comment]
+1

**Comment by Ch0bits** [comment]
+1

**Comment by robsonrosa** [comment]
+1

**Comment by jakeNiemiec** [comment]
We should really make a new issue, this one is from 2014. This issue is also for the first angular/protractor and I am sure all of us are here for angular2.

**Comment by robsonrosa** [comment]
angular1 here :)

**Comment by sergiomichels** [comment]
@jakeNiemiec Nope, using AngularJS 1.x here. We're just trying to minimize the migration effort in the future.

**Comment by icegnome** [comment]
+1

**Comment by ihrimech** [comment]
+1

**Comment by smitalm** [comment]
Is there any way i can use jquery and protractor typings in the same project, without modifying typings sources and without getting this error?  After all this time, there must be a way :(

**Comment by the-map** [comment]
+1

This is really annoying. Introduction of "Types" to Javascript is supposed to increase productivity! I am JS pro & I have been working on it since month and I still keep on getting such annoying issues which diverts your focus from actual functionality! Sadly, I don't see productivity in action with Types!

**Comment by sky-coding** [comment]
+1
Really, 2 years?

**Comment by Andrey-Pavlov** [comment]
Fix it please!

**Comment by jakeNiemiec** [comment]
There is ~1000 open issues, no one is going to find this (2 years and counting). 

Looking at the history of contributors, @cnishina may be able to help (his profile tagline: Mission: typescript protractor tests)

@vvakame is also a recent contributor (seemingly related issue here: https://github.com/Microsoft/TypeScript/pull/3102#issuecomment-101759155.

**Comment by cnishina** [comment]
Hi everyone. I've had this issue bookmarked for a very long time and have been meaning to respond. 

Since angular-protractor is built off an older version of Protractor, we decided to not maintain this.

Protractor has been slowly migrating JavaScript files to TypeScript. If you are using the latest version of Protractor (v 4.0.9), it has built in TypeScript support. There is a sample TypeScript project in the Protractor repo as well as in the [cookbook](https://github.com/angular/protractor-cookbook/tree/master/protractor-typescript). Just a quick note: TypeScript support is still experimental, check the changelog for any potential breaking changes.

So to not have a jQuery conflict, you must set `noGlobals` to true. (See [config file](https://github.com/angular/protractor/blob/master/lib/config.ts#L157)). This will ensure that protractor publishes a single global object called 'protractor'.

```
import {$} from 'protractor';
```

The import actually uses the global `protractor.$` and does not use global `$` that jQuery uses.

**Comment by cnishina** [comment]
Hopefully the above response is enough to close this issue. 🎉 

### Below is more details about "fixing" `angular-protractor` and probably why it might not be ideal:

#### API mismatch

Since Protractor version 1.5, some of the APIs have changed causing a version mismatch for the ambient typings. This is probably the most important reason why Protractor now supports TypeScript.

Below is the proposed fix; however, making this change will ultimately break tests for users that do not have an ambient typing problem with jQuery. This might be a good reason to use Protractor 4.0.9+.

#### The fix for Protractor 3.2+

For users that are using Protractor 3.2+ and < 4, using the `noGlobals` flag would ensure that there are no conflicts at the global namespace for `$`. The fix would be to remove the `declare var $` as well as other global variables completely from `angular-protractor.d.ts`. This would require users to set up their own Protractor variables.

```
import {Protractor} from 'protractor';

let protractor: Protractor = (global as any)['protractor'];
let $ = protractor.$; 
```

#### The fix for Protractor < 3.2

Again, the fix would be to remove the `declare var $` and other global variables as stated above and would also require users to set up their own Protractor variables (also shown above). However, if you are using jQuery in your Protractor file, there still is a global namespace problem with Protractor's $ and jQuery's $.

**Comment by jakeNiemiec** [comment]
@cnishina Thanks for following up!

**Comment by cnishina** [comment]
@andy-ms This should be closed since angular-protractor does not exist.
