### ISSUE TITLE
[@type/hammerjs] interface Recognizer.recognizeWith( otherRecognizer:string ):Recognizer??

### ISSUE THREAD

**Issue by tenCats** [DefinitelyTyped/DefinitelyTyped#27359]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/91f8a6b7d1ef61cc543d0901dcc004b846283345/types/hammerjs/index.d.ts#L276

Shouldn't it be `recognizeWith( otherRecognizer:Recognizer[] ):Recognizer;` instead ?
Same problem on `requireFailure`, `dropRecognizeWith`, `dropRequireFailure`.

You can find `class Recognizer` implementation here: https://github.com/hammerjs/hammer.js/blob/master/src/recognizerjs/recognizer-constructor.js

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
