### ISSUE TITLE
@types/mongoose 5.2.0 missing session option support and functionality

### ISSUE THREAD

**Issue by creativearmenia** [DefinitelyTyped/DefinitelyTyped#27358]
Starting from mongodb 4 transaction functionality add, from version 5.2.0 mongoose adds support for session option to be able to create transactions. @types/mongoose 5.2.0 version missing that session options and functionality.

see mongoose for transactions [example](http://thecodebarbarian.com/a-node-js-perspective-on-mongodb-4-transactions.html)

**Comment by various89** [comment]
fixed in #28745

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
