### ISSUE TITLE
Issue with @types/bluebird v3.5.22

### ISSUE THREAD

**Issue by nickjpanella** [DefinitelyTyped/DefinitelyTyped#27374]
- An Express Dependency uses `@types/bluebird` package and when building the project, it thew a hell of a lot of error.
- Authors: @lhecker 

`"typescript": "2.7.2",`

```
"extends": "../../tsconfig.json",
  "compileOnSave": false,
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "moduleResolution": "node",
    "outDir": "../../dist/server",
    "baseUrl": "./",
    "noEmitOnError": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": [
      "node", "express"
    ],
    "lib": [
      "es2015",
      "dom"
    ]
  },
  "exclude": [
    "node_modules",
  ]
```

```
$ tsc -p ./src/server/tsconfig.server.json
node_modules/@types/bluebird/index.d.ts(39,26): error TS1005: ';' expected.
node_modules/@types/bluebird/index.d.ts(39,34): error TS2693: 'Iterable' only refers to a type, but is beingused as a value here.
node_modules/@types/bluebird/index.d.ts(39,43): error TS2304: Cannot find name 'infer'.
node_modules/@types/bluebird/index.d.ts(39,49): error TS1005: ';' expected.
node_modules/@types/bluebird/index.d.ts(39,49): error TS2304: Cannot find name 'U'.
node_modules/@types/bluebird/index.d.ts(39,52): error TS1109: Expression expected.
node_modules/@types/bluebird/index.d.ts(39,54): error TS2304: Cannot find name 'U'.
node_modules/@types/bluebird/index.d.ts(39,58): error TS2693: 'never' only refers to a type, but is being used as a value here.
node_modules/@types/bluebird/index.d.ts(40,29): error TS1005: ';' expected.
node_modules/@types/bluebird/index.d.ts(40,37): error TS2693: 'Iterable' only refers to a type, but is being used as a value here.
node_modules/@types/bluebird/index.d.ts(40,51): error TS1005: '(' expected.
node_modules/@types/bluebird/index.d.ts(40,53): error TS2304: Cannot find name 'R'.
node_modules/@types/bluebird/index.d.ts(40,55): error TS1005: ',' expected.
node_modules/@types/bluebird/index.d.ts(40,57): error TS2693: 'never' only refers to a type, but is being used as a value here.
```

**Comment by lhecker** [comment]
@nickjpanella @olivier-po @aeremin As mentioned in [my comment above](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/27374#issuecomment-405754967), this is _not_ an issue and the typings are _not_ "broken".
The newest Bluebird typings simply employ language features from the newest TypeScript version (>2.8) for increased type safety.

Let me put it this way: If you use the Bluebird v3.5.20 typings you had to use TypeScript 2.3 or later and if you tried using these with an older TypeScript version it would've failed the same way as described in this issue (>2.3 was required for the `object` type, which is an unknown identifier in older TypeScript versions).

@nickjpanella Due to these reasons you may close this issue now.
cc: @RyanCavanaugh

**Comment by aeremin** [comment]
@lhecker Sorry, not meant to offend you  (wasn't even aware that you will get notification here). It's definitely broken for me _personally_ - I am stuck at Typescript 2.3 due to some of my dependencies not supporting latest versions. Also it's a bit sad that @types/bluebird don't follow semver principle of not introducing breaking changes when changing patch version. Effectively, it breaks everybody using (bluebird + @types/bluebird) with older Typescript version, even if they depend on indirectly (in my cases, npm decided to update @types/bluebird when doing clean 'npm install' on new machine).

**Comment by lhecker** [comment]
@aeremin I actually agree that proper SemVer for typings would be greatly beneficial to prevent issues like this one.
But changing the current process would not in the least be a simple process and I'm not sure how one would go about it.
@RyanCavanaugh for instance already explained the situation quite extensively [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25677#issuecomment-388215959) for instance.

Either way this is an entirely different issue though and e.g. #8735 and #25677 exist already.
If anyone has a cool way to solve this problem you could suggest it in a new issue or contribute to an existing one though. 🙂

**Comment by BeatriceThalo** [comment]
for bluebird ^3.5.1 and typescript 2.7.2, rolling back to @types/bluebird 3.0.37 and
`rm -rf node_modules/@types/request-promise/node_modules`
`rm -rf node_modules/@types/sequalize/node_modules`
worked for me

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by kelthaz** [comment]
@BeatriceThalo thanks for the solution in my case I was use 3.5.38 and then I add in my package. json     "@types/bluebird": "3.5.21",
