### ISSUE TITLE
[Mongoose:] "ref" missing in interface SchemaTypeOpts

### ISSUE THREAD

**Issue by marcelh-gh** [DefinitelyTyped/DefinitelyTyped#27389]
- @types/mongoose v5.2.0
- TypeScript v2.9.2

- Authors: @horiuchi , @sindrenm , @lukasz-zak , @Alorel , @jendrikw , @jussirantala ``

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
