### ISSUE TITLE
[@types/highcharts] Not all series.data types included

### ISSUE THREAD

**Issue by juanjosegutierrez** [DefinitelyTyped/DefinitelyTyped#27399]
- I tried using the `@types/highcharts` package and had problems.
- I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @damianog @baltie @AlbertOzimek @hanssens

In the Highcharts options there is the field series.data which is where you provide the data for the chart. The types on the latest version work for 'line' charts but not 'candlestick' charts. Currently series.data has a type of:

`Array<number | [number, number] | [string, number] | DataPoint>;`

However, when one changes the chart type to 'candlestick' the series.data types should allow:

`Array<[number, number, number, number, number]>`

Here is a link to the documentation that states this type of data is allowed:

[https://api.highcharts.com/highstock/series.candlestick](url)

Also, other items in the series options are not included for candlestick charts. For example, the type for series.upColor is not included. It looks like several types for candlestick charts are missing.

**Comment by Laubi** [comment]
Also, AreaRanges are not supported: [number | string, number, number]

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
