### ISSUE TITLE
Lodash: `fp.mapValues`: error when using contextual type inference

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#27395]
Contextual types play nicely with `fp.map`. The correct overload is used, and the generics are inferred from the contextual type.

``` ts
    // Expect type of param x to be inferred as number from contextual type
    const foo: (obj: number[]) => number[] = fp.map(
        // $ExpectType (x: number) => number
        x => x
    );
```

However, the same is not true for `fp.mapValues`:

``` ts
    // Expect type of param x to be inferred as number from contextual type
    
    /* Type 'LodashMapValues1x1<string>' is not assignable to type '(obj: Dictionary<number>) => Dictionary<number>'.
        Types of parameters 'obj' and 'obj' are incompatible.
            Type 'Dictionary<number>' is not assignable to type 'string'. */
    const foo: (obj: _.Dictionary<number>) => _.Dictionary<number> = fp.mapValues(
        // $ExpectType (x: number) => number
        x => x
    );
```

I originally tried to fix this in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27232, but the fix requires bumping the TS version for the Lodash typings to [2.8, which is not acceptable at time being](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27232#issuecomment-404627936).

/cc @aj-r

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
