### ISSUE TITLE
@types/ioredis accesing nodes() on type Redis

### ISSUE THREAD

**Issue by Jissai** [DefinitelyTyped/DefinitelyTyped#27391]
- I tried using the `@types/ioredis` package and had problems when issuing commands without id.
- Authors: @plantain-00 @chrisleck @aliarham11 @br8h @shaharmor @palindrom615

code example folowing guidelines on ioredis
https://github.com/luin/ioredis/issues/336

```
import { Cluster } from 'ioredis';

const cluster = new Cluster([
    { host: '127.0.0.1', port: 7000 },
    { host: '127.0.0.1', port: 7001 },
    { host: '127.0.0.1', port: 7002 },
]);

 cluster.on('ready', () => {
     console.log(cluster.nodes().length);
     console.log(cluster.nodes('slave').length);
});
```
compilation issue :
TS2339: property 'nodes' doesn't exist on types 'Redis'.

looking at d.ts file, interface Cluster#new returns a type Redis but Redis doesn't expose nodes().

workaround
The above code works perfectly if i delete @types/ioredis from package.json however i lose typing :)

**Comment by plantain-00** [comment]
You can create a PR to fix this

**Comment by skyzenr** [comment]
Hi @Jissai , shouldn't Cluster#new return a type Cluster which in turn should expose the same methods of the type Redis? Otherwise I am not quite sure how the interface Redis can expose a method nodes() that returns an array of Redis. How should it work?

Thanks.

**Comment by nickroberts** [comment]
#33315

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
