### ISSUE TITLE
[@types/node] ServerHttp2Session and ServerHttp2Stream

### ISSUE THREAD

**Issue by zh99998** [DefinitelyTyped/DefinitelyTyped#27405]
I copied http2 altsvc example from https://nodejs.org/api/http2.html#http2_serverhttp2session_altsvc_alt_originorstream
and there are two errors.

`ServerHttp2Stream.session` should be `ServerHttp2Session`
`ServerHttp2Stream` should have an `id` field.

```typescript
import http2 from 'http2';

const server = http2.createServer();
server.on('session', (session) => {
    // Set altsvc for origin https://example.org:80
    session.altsvc('h2=":8000"', 'https://example.org:80');
});

server.on('stream', (stream) => {
    // Set altsvc for a specific stream
    stream.session.altsvc('h2=":8000"', stream.id);
});
```

![image](https://user-images.githubusercontent.com/359622/42919113-fb1ba0ae-8b42-11e8-8683-c4c474b71cba.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
