### ISSUE TITLE
I tried using the @types/redux-orm package and had questions

### ISSUE THREAD

**Issue by lling1105** [DefinitelyTyped/DefinitelyTyped#27431]
hello @keenondrums 
first of all thanks much to you for creating this types lib for [redux-orm](https://github.com/tommikaikkonen/redux-orm).
after reading the codes from
[DefinitelyTyped/types/redux-orm/redux-orm-tests.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/redux-orm/redux-orm-tests.ts) ,and try to learn how to follow the types in my project, but i'm little confused following snippet about register models to 'schema' which you named 'ORM'
**YOURS**
```
const orm = new ORM<TestORMState>();
orm.register<TestORMModels>(Test);
```
**VS the snippet from [redux-orm-primer](https://github.com/tommikaikkonen/redux-orm-primer)**
```
export const schema = new Schema();
schema.register(Todo, Tag, User);
export default schema;
```
could you please show some snippet about how to register batch of models to the orm instance? thanks in advance. :)

**Comment by lling1105** [comment]
@keenondrums so cool, thanks!

**Comment by keenondrums** [comment]
@lling1105 could you rename the issue to something like "[@types/redux-orm] register several models"? It would help others to find it quicker

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
