### ISSUE TITLE
Easeljs.d.ts: Use of event listeners cumbersome due to use Object

### ISSUE THREAD

**Issue by wlinna** [DefinitelyTyped/DefinitelyTyped#27432]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @evilangelist @gyohk Pedro Ferreira

In my opinion, using `on` is  currently needlessly cumbersome, because the `eventObj` is defined as `Object`.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/easeljs
/index.d.ts#L663

 This means that I cannot do something like this:

`stage.on('stagemouseup', function(event: createjs.MouseEvent) { }`

or this

```
stage.on('stagemouseup', function(event): void {
   var stageX = event.stageX;
   var stageY = event['stageY'];
}
```

Instead, I always need to separately cast `event` to something else:

`var mouseEvent = <createjs.MouseEvent> event;`

Wouldn't it be better to just use `any`? I see comments like this in createjs-lib with some fields (such as `Event.target`)

`// It is 'Object' type officially, but 'any' is easier to use.`

so why not here too?

Opinions?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
