### ISSUE TITLE
error in slate: error TS2304: Cannot find name 'History'.

### ISSUE THREAD

**Issue by amitm02** [DefinitelyTyped/DefinitelyTyped#27484]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/slate` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andykent @majelbstoat @JanLoebel  @YangusKhan

If you do not mention the authors the issue will be ignored.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
