### ISSUE TITLE
lodash does not allow _.escape(number)

### ISSUE THREAD

**Issue by qbolec** [DefinitelyTyped/DefinitelyTyped#2752]
This is quite problematic, as the `_.escape` function is used implicitly by the `_.template` function whenever an author of a template uses `<%- something %>` in the template. As I consider it to be a very good and secure practice to use escaping by default, and use `<%= html %>` only in rare and justified cases, I run into type inference problems whenever `something` is actually a number (for example an id of an object, or an index in an array). 
Of course, one could ask the author of the template to change from `-` to `=` back and forth each time she decides to change the type of `something`, but this can quickly lead to a situation in which the template contains `=` and `something` is a string, because warnigs are assymetric: you get a warning when passing number to `<%- %>` but do not get a warning when passing string to `<%= %>`, so it makes you feel comfortable, even if you forgot to match the two.

I think it would allow for more secure workflow if 
`escape(num: number):string` was added to the declaration file.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
