### ISSUE TITLE
@types/mapbox-gl: ImageSource, VideoSource, and more

### ISSUE THREAD

**Issue by mikew** [DefinitelyTyped/DefinitelyTyped#27537]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dobrud @patrickr

`ImageSource` and `VideoSource` (and more) are defined as classes with specific methods, but they are allowed to be POJOs:

https://github.com/mapbox/mapbox-gl-js/blob/b446917667d8e3ce99e3ccc33623329fa5544b5c/docs/pages/example/animate-images.html#L19-L28

https://github.com/mapbox/mapbox-gl-js/blob/b446917667d8e3ce99e3ccc33623329fa5544b5c/docs/pages/example/video-on-a-map.html#L12-L19

This means examples straight from mapbox won't work in TypeScript:

<img width="563" alt="screen shot 2018-07-24 at 10 54 20 am" src="https://user-images.githubusercontent.com/4729/43142925-f2f46fb4-8f2f-11e8-9db0-7202b596f2eb.png">

```
Argument of type '{ id: string; source: { type: "image"; url: string; coordinates: number[][]; }; type: "raster"; p...' is not assignable to parameter of type 'Layer'.
  Types of property 'source' are incompatible.
    Type '{ type: "image"; url: string; coordinates: number[][]; }' is not assignable to type 'string | VectorSource | RasterSource | GeoJSONSource | ImageSource | VideoSource | GeoJSONSourceR...'.
      Type '{ type: "image"; url: string; coordinates: number[][]; }' is not assignable to type 'ImageSource'.
        Property 'setCoordinates' is missing in type '{ type: "image"; url: string; coordinates: number[][]; }'.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
