### ISSUE TITLE
What's the deal with contribution credits?

### ISSUE THREAD

**Issue by stijnherreman** [DefinitelyTyped/DefinitelyTyped#2756]
I'm redoing a definition file for a certain library because it's missing quite some definitions, and the documentation isn't using JSDoc format.

I personally have no interest in having my name at the top of the file nor having it in CONTRIBUTORS.md, if people are interested in that data they can look up revision history for it.
At the same time I'm not comfortable having the original author's name at the top of the file, since it's more or less done from scratch.

The library information and the link to this repo are useful so future maintainers know where to look for updates, but I don't see a point in having the author at the top of the file, especially since many people can contribute to the same definitions file.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
