### ISSUE TITLE
estree: ObjectExpression property needs updating

### ISSUE THREAD

**Issue by glmdgrielson** [DefinitelyTyped/DefinitelyTyped#27580]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9d267d6d685e5e34da7ff7a27f5f84b65d8653f9/types/estree/index.d.ts#L238

This should be
```typescript
     properties: Array<Property | SpreadElement>;
```

**Comment by mskelton** [comment]
I've been working with these types and this still seems like a valid issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
