### ISSUE TITLE
Can not use array style in react-native-scrollable-tab-view

### ISSUE THREAD

**Issue by hpmax00** [DefinitelyTyped/DefinitelyTyped#27595]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-native-scrollable-tab-view` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @egorshulga 

If you do not mention the authors the issue will be ignored.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/40781942/43248518-ae6a546e-90ea-11e8-8d7a-403369b32cc1.png">

and ScrollableTabView type of @types/react-native-scrollable-tab-view
<img width="521" alt="image" src="https://user-images.githubusercontent.com/40781942/43248337-1ffce8e0-90ea-11e8-8aa9-f43d673c09e3.png">

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
