### ISSUE TITLE
error TS2339: Property 'geocode' does not exist on type 'typeof ymaps'

### ISSUE THREAD

**Issue by kolkov** [DefinitelyTyped/DefinitelyTyped#27647]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/yandex-maps` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Delagen

If you do not mention the authors the issue will be ignored.

**Comment by Delagen** [comment]
I am written this typings for internal project, then I share it as no one exists. So your PR is welcome. DefinitelyTyped style of typings is ugly and restrict some functions that make typings more precise. So I use own precompiled version of lodash typings that support ambient mode. Moreover, your PR is welcome.

**Comment by Delagen** [comment]
This is the main project

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
