### ISSUE TITLE
Definition:Request: famo.us

### ISSUE THREAD

**Issue by JohnTasler** [DefinitelyTyped/DefinitelyTyped#2764]
http://famo.us/

**Comment by johnjelinek** [comment]
Any progress in this?

**Comment by clark-stevenson** [comment]
I was just wondering the same thing. It is a fairly big definition and what put me off starting is I know next to nothing about the project roadmap. The comments/documentation are not amazing.

**Comment by johnjelinek** [comment]
It seems that, since famo.us broke out into engine and framework libraries, that only the engine lib may be appropriate for TypeScript. The framework has an opinionated scaffolding tool, deploy tool, and integrated build tool that already supports ES2015 transpilation. When you deploy, it sends the component/project to their CDN that you may embed into your TypeScript app.

**Comment by JohnTasler** [comment]
Closing since famo.us has fallen and it can't get up.
