### ISSUE TITLE
[@types/rebass] Property 'is' does not exist on type 'IntrinsicAttributes & HeadingProps & { children?: ReactNode; }

### ISSUE THREAD

**Issue by MatthewKosloski** [DefinitelyTyped/DefinitelyTyped#27652]
- [x] I tried using the `@types/rebass` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rhysd

I am currently in the process of transitioning my project from JavaScript to TypeScript.  I have a component called `H1` below that uses Rebass's `Heading` component. Here is the component:
```
import * as React from 'react';
import { Heading } from 'rebass';

const H1: React.SFC<{}> = (props) => {
	return (
		<Heading {...props}
			is='h1' 
			fontSize={[2, 2, 3, 4]} 
			m={0}
			my={1}>
		{props.children}
		</Heading>
	);
}

export default H1;
```

I am getting the following error message:

```
[ts] Property 'is' does not exist on type 'IntrinsicAttributes & HeadingProps & { children?: ReactNode; }'.
```

This is my first time using TypeScript so I am unsure how to resolve this problem.  From what I understand, it appears that `is` does not exist on the [`HeadingProps` interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8ea7323a0fb649381c2ecf1bba8ea544e1ca33df/types/rebass/index.d.ts#L251).

As you can see [here](https://github.com/jxnblk/rebass/blob/master/src/Heading.js#L18) in the source code of Rebass, `Heading` should be able to take `is` as a prop.

Thanks!

**Comment by kevinkam** [comment]
It looks like `@types/rebass` didn't update for a long time.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
