### ISSUE TITLE
[@types/sinon] SinonFake should inherit from SinonSpy

### ISSUE THREAD

**Issue by abelnation** [DefinitelyTyped/DefinitelyTyped#27666]
From looking at the sinon source code, this does seem to be the case.  

See:
https://github.com/sinonjs/sinon/blob/master/lib/sinon/fake.js#L50

@mrbigdog2u
@rationull
@lumaxis
@nicojs
@43081j
@joshuakgoldberg

**Comment by JoshuaKGoldberg** [comment]
@abelnation I don't doubt that you're right, but could you please post links that would suggest this to be the case? I'm not familiar with the sinon source code itself.

**Comment by abelnation** [comment]
Yup, see here:
https://github.com/sinonjs/sinon/blob/master/lib/sinon/fake.js#L50

**Comment by 43081j** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2eda9e3a6f28e670348c35c96c1a9513c0c16a39/types/sinon/index.d.ts#L491

already returns a `SinonSpy`, so isn't this already working as expected? (though with the extra methods that should be removed i mentioned in my last comment)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
