### ISSUE TITLE
[@types/auth0-lock] missing declaration for Auth0LockPasswordless

### ISSUE THREAD

**Issue by Syntaf** [DefinitelyTyped/DefinitelyTyped#27664]
@benjaminparnell It seems the @types definitions for Auth0-lock are missing declarations for Auth0LockPasswordless. If you look at `index.js` on auth-lock:

```
...

var Auth0LockPasswordless = exports.Auth0LockPasswordless = _passwordless2.default;
var Auth0Lock = exports.Auth0Lock = _lock2.default;
```

However inside the @types definitions, there's no passwordless mention:

```
declare var Auth0Lock: Auth0LockStatic;

declare module "auth0-lock" {
    export default Auth0Lock;
}
```

If I knew how to create type definitions for stuff like this I'd make a PR, but I don't :( . Is this an easy update?

**Comment by andy-ms** [comment]
Package authors are @carusology @goldcaddy77 @lfaudreejr

**Comment by Legacy07** [comment]
So is there any solution on this as i'm currently having the same issue.

**Comment by carusology** [comment]
Feel free to submit a PR and we'll review.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
