### ISSUE TITLE
[mathjs] Multiplication result squeezing?

### ISSUE THREAD

**Issue by AlecTaylor** [DefinitelyTyped/DefinitelyTyped#27681]
Confused about this bit:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2eda9e3a6f28e670348c35c96c1a9513c0c16a39/types/mathjs/index.d.ts#L754

What does squeezing mean in this context?

BTW: It wasn't in the mathjs docs:
http://mathjs.org/docs/reference/functions/multiply.html

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
