### ISSUE TITLE
AngularJs: IRootScopeService.$watch does not allow zero parameter watch expression.

### ISSUE THREAD

**Issue by rcollette** [DefinitelyTyped/DefinitelyTyped#2772]
The first parameter to $watch may be a zero parameter function.   For example, we can pass as the first parameter, a call to anular.bind

```
scope.$watch(angular.bind(controller.property, function(){ return controller.ms[configuredIndex];}),
    function(newVal, oldval){ //});
```

The definition for $watch should allow a zero parameter function as the first parameter.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
