### ISSUE TITLE
[@types/ioredis] Several commands have return type "any"

### ISSUE THREAD

**Issue by philraj** [DefinitelyTyped/DefinitelyTyped#27784]
- [x] I tried using the `@types/ioredis` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @plantain-00 @chrisleck @aliarham11 @br8h @shaharmor 
<hr>

Hi, several commands exposed by ioredis have a return type of `any` (not even `Promise<any>`). Examples of these commands are `mget`, `hgetall`, and `smembers`, but there are many more.

Seems like Redis responses are uniform enough to be able to type every potential response, and the type definitions should at least be making it clear that the methods are returning promises. In the case of `mget` and a few others, there isn't a separate overload for callbacks and promises either.

Is there a technical reason for all this or was it just that the authors didn't have time to fully flesh out the entire API?

[edit] Furthermore it seems commands that have return types defined may have them defined incorrectly, e.g. `get` is defined as returning `Promise<string>` when it seems like it should be `Promise<string|undefined>` for missing keys.

**Comment by plantain-00** [comment]
PR is welcome

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
