### ISSUE TITLE
Please explain: npmjs outage May 24 and sudden doubling of @types downloads

### ISSUE THREAD

**Issue by ajbogh** [DefinitelyTyped/DefinitelyTyped#27819]
What happened around May 24, 2018 - May 30 in npmjs.com that caused a dip in the number of downloads for a short period of time and then a subsequent doubling of downloads for almost all, if not all, @types projects?

Are the number of downloads accurate now? Were they not accurate in the past? Is there something downloading more packages from the @types namespace now? Have more people converted to Typescript after reading something published around May 24, boosting popularity like crazy?

For instance, @types/lodash has 907,550 downloads on May 17, then dips to 550,306 on May 24, then jumps to 1,941,353 on June 14.

The dip seems to be for all projects. The npm trends graph for @types/react vs react (linked below) shows both having a low number of downloads on June 3, then a huge increase in downloads for @types/react (more than double). If you change the timeline to 1 year then you'll notice how drastic this change was.

http://www.npmtrends.com/@types/react-vs-react

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
