### ISSUE TITLE
Enhance resolve methodes are optional

### ISSUE THREAD

**Issue by nicojs** [DefinitelyTyped/DefinitelyTyped#27844]
- [x] I tried using the `@types/enhance-resolved` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @e-cloud @onigoetz @johnnyreilly 

A lot of enhance resolved methods are optional. For example: 

```typescript
    class CachedInputFileSystem {
        fileSystem: AbstractInputFileSystem;
        constructor(fileSystem: AbstractInputFileSystem, duration: number);
        stat?(path: string, callback: (err: NodeJS.ErrnoException, stats: fs.Stats) => void): void;
        readdir?(path: string, callback: (err: NodeJS.ErrnoException, files: string[]) => void): void;
        readFile?(path: string, callback: (err: NodeJS.ErrnoException, data: Buffer) => void): void;
        readJson?(path: string, callback: (err: NodeJS.ErrnoException, data: any) => void): void;
        readlink?(path: string, callback: (err: NodeJS.ErrnoException, linkString: string) => void): void;
        statSync?(path: string | Buffer): fs.Stats;
        readdirSync?(path: string): string[];
        readFileSync?(filename: string, options?: { flag?: string; }): Buffer;
        readlinkSync?(path: string | Buffer): string;
        readJsonSync?(path: string): any;
        purge(what?: string | string[]): void;
    }
```

The way I understand is that it is only implemented if it was implemented on the `fileSystem` that is provided in the constructor. So technically correct. However, this makes it so it its difficult to use when strict null checks is enabled.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
