### ISSUE TITLE
Generic type 'Dispatch<S>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by druny** [DefinitelyTyped/DefinitelyTyped#27902]
ERROR in [at-loader] ./node_modules/@types/react-redux/index.d.ts:192:16
    TS2314: Generic type 'Dispatch<S>' requires 1 type argument(s).

ERROR in [at-loader] ./node_modules/@types/react-redux/index.d.ts:199:16
    TS2314: Generic type 'Dispatch<S>' requires 1 type argument(s).

ERROR in [at-loader] ./node_modules/@types/react-redux/index.d.ts:267:16
    TS2314: Generic type 'Dispatch<S>' requires 1 type argument(s).

ERROR in [at-loader] ./node_modules/@types/react-redux/index.d.ts:323:12
    TS2314: Generic type 'Store<S>' requires 1 type argument(s).

----

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
