### ISSUE TITLE
@types/react-datepicker - add timeCaption?: string; to index.d.ts

### ISSUE THREAD

**Issue by petrusolofsson** [DefinitelyTyped/DefinitelyTyped#27926]
Could anyone please add:

timeCaption?: string;

to index.d.ts ?

The default caption is "Time" and I need to modify it to a translated caption in my project, but I can't.

@radziksh 
@andrewBalekha 
@smrq 
@Rogach 
@royxue 
@KoalaHuman 
@seansfkelley 

Thanks in advance!

**Comment by petrusolofsson** [comment]
Ok! :) Just made a pull request! @seansfkelley

**Comment by seansfkelley** [comment]
Maintainers: this issue can be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
