### ISSUE TITLE
@types/pikaday: Moment in pikaday

### ISSUE THREAD

**Issue by masiama** [DefinitelyTyped/DefinitelyTyped#27942]
- [x] I tried using the `@types/pikaday` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Authors: @MidnightDesign, @wake42

`@types/pikaday` has `moment` in dependencies although it is optional in original `pikaday` as well as removed from `package.json` (dbushell/Pikaday#718)

**Comment by PikachuEXE** [comment]
@masiama 
Are you using webpack?
If so you can take a look at [webpack specific workaround provided in `pikaday` issue](https://github.com/Pikaday/Pikaday/issues/718#issuecomment-334738391)

**Comment by masiama** [comment]
@PikachuEXE 
Yeah, I am using webpack and already used this workaround.
But still as `moment` is optional in original `pikaday` I think it could be removed  from `@types/pikaday` as well

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
