### ISSUE TITLE
@types/react-select - Unable to start working with library.

### ISSUE THREAD

**Issue by shoter** [DefinitelyTyped/DefinitelyTyped#27953]
I tried to use react-select with types from typescript but I am unable to do any basic thing with this package.

First of all I have no slight idea how to properly create options prop for the select. The type just seems wrong for me and I was unable to create anything that makes any sense.

Below types are used as a type for options props. The problem is that options require at least label and value property. I did not check but my first guess is that it was done automatically and author of react-select is using brackets to access properties? (i.e options["value"]). Hard to say but that thing seems just wrong.
```
export type OptionsType<OptionType> = OptionType[];

export interface GroupType<OptionType> {
  options: OptionsType<OptionType>;
  [key: string]: any;
}
```

Also when I just create simple SelectBase component and try to render it without setting any props I have TypeErrors :/.

![Type errors for props](https://i.imgur.com/pJVFlev.png)

The code for that is very simple: 
```
 return (<div className="ingredientIntakeAdd">
            <SelectBase 
           // value={this.state.selectedIngredientId || 0}
         //   onChange={this.onSelect}
         //   options={this.state.ingredients}
            />
</div>)
```
Here is original code where I have this issue.
https://github.com/shoter/Calories/blob/547665c512ad6f9a3eab431da8b864aa8c8e1c73/Calories.Web/src/Adder/IngredientIntakeAddComponent.tsx

  - Authors: @claasahl, @jonfreedman

**Comment by jonfreedman** [comment]
As of version 2.0.0 react-select now allows you to use any object you like as an option, see https://react-select.com/upgrade-guide

You will need to set some additional properties, you would also want to create a `<Select<Ingredient>/>` to get type consistency across methods dealing with your option type.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
