### ISSUE TITLE
[@types/redux-form] ConfigProps onChange() missing 4th parameter 'previousValues'

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/DefinitelyTyped#27997]
Hello,

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CarsonF @aikoven @LKay @bancek @tehbi4 @huwmartin @reggino @maddijoyce 

According to
https://redux-form.com/7.4.2/docs/api/reduxform.md/#-code-onchange-function-code-optional-

`onChange` receives a fourth parameter: `previousValues`, however it is not listed in reduxForm.d.ts:114

Sorry to bother you with this and thanks for maintaining these typings!

**Comment by smifun** [comment]
This was fixed by #29636

**Comment by nicknish** [comment]
This can be closed I believe!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
