### ISSUE TITLE
[text-encoding] Cannot find name TextDecoder / TextDecoderOptions.

### ISSUE THREAD

**Issue by Domvel** [DefinitelyTyped/DefinitelyTyped#28026]
I tried using the `@types/text-encoding` package and had problems.

## Enviroment: 
**Ionic CLI** `4.0.6`
**Ionic Framework** `ionic-angular 3.9.2`
**@ionic/app-scripts** `3.1.9`
**NodeJS** `8.11.3`
**npm** `5.6.0`
**OS** `Windows 10`

[text-encoding version  0.6.4](https://www.npmjs.com/package/text-encoding)
[@types/text-encoding version 0.0.33](https://www.npmjs.com/package/@types/text-encoding)

## Error
```
Cannot find name 'TextDecoderOptions' node_modules/@types/text-encoding/index.d.ts
Cannot find name 'TextDecoder' node_modules/@types/text-encoding/index.d.ts
```

## Usuage

(Snippet)
```ts
import { TextEncoder, TextDecoder } from 'text-encoding';
// ...
// Inside of a method:
let decoder = new TextDecoder('utf-8');
return decoder.decode(bytes);
// ...
```

I already tried to reinstall node_modules, package-lock.json and ionic and cordova clean. 

[View the source of the typed file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/text-encoding/index.d.ts)

The Types `TextDecoderOptions` and `TextDecoder` comes from `lib.dom.d.ts`
VS Code can find these Types. But on runtime, I get these errors.
I wondering, why is `TextEncoderOptions` and `TextEncoder` declared in text-encoding typed file? And the Decoder Interfaces NOT?

**Comment by nwmqpa** [comment]
I've thrown the missings types in this, can you please try this before I attempt any pull requests ?
`npm remove @types/text-encoding`
`npm install git+https://git@github.com/nwmqpa/-types-text-encoding.git`

**Comment by Domvel** [comment]
@nwmqpa It seems to work. 👍

**Comment by cworth33** [comment]
Is this fixed yet?
I'm still having this issue with 0.0.35

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
