### ISSUE TITLE
d3 typings and TS --strictFunctionTypes

### ISSUE THREAD

**Issue by rkirov** [DefinitelyTyped/DefinitelyTyped#28045]
We (the Google TypeScript infra team) are working on turning on --strictFunctionTypes for our codebase. We are seeing a lot of errors coming from the new typechecking of `ValueFn` and what is worse, it appears that the d3 users are not finding them terribly useful or easy to decipher what's wrong.

One example so far is with this change `d3.Selection` becomes invariant. We are testing locally modifying the d3 typings the relax some of the method types so that contrainers like `Selection` stay covariant, which seems is what our users expect - like Array, etc.

Have the d3 typings authors have any experience with that flag?

Authors: @tomwanzek @gustavderdrache @borisyankov

**Comment by denisname** [comment]
I'm a little bit late on this...

We finally ended turning on `strictNullChecks` for all d3 libraries.

Some works for `strictFunctionTypes` has already be done. But it is mostly only basic support. For `d3.Selection`, it is the TypeScript compiler who "make" it invariant under `strictFunctionTypes`. Indeed, we have something like
```typescript
export interface Selection<GElement, Datum, PElement, PDatum> {
    on(typenames: string): (this: GElement, datum: Datum, index: number) => void);
    // more methods
}
```

Therefore, selection can not be covariant, i.e. `Selection<HTMLDivElement, number, HTMLBodyElement, {}>` be a subtype of `Selection<HTMLElement, number, HTMLBodyElement, {}>`.

Now I agree that having a covariant selection will be useful. I'm also annoyed by this. So adding a more relax interface should be done. Will try to do it soon.

You say you are "testing locally modifying the d3 typings". What are you results so far?

**Comment by Ledragon** [comment]
@rkirov what is the status on this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
