### ISSUE TITLE
default error argument type should just be <any>

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#28063]
@fahrradflucht @borisyankov @kern0 @Penryn @fenying @pascalmartin

- [x] I tried using the `@types/xxxx` package and had problems.

Error arguments should have a default type, and that default type should be `<any>`.

For example, right now I have to add 3 types to async.map like so:

```js
async.map<string, number, any>();
```

bur in my humble opinion it would be convenient for users if the error argument type simply defaulted to `<any>`, such that you could do this instead:

```js
async.map<string, number>();
```

if people like the idea, I can do a PR, lmk

**Comment by fenying** [comment]
I think, `Error` should be better than `any`, just like other methods doing.
And, PRs are welcome.

**Comment by ORESoftware** [comment]
Default should be `<any>` IMO, if it's more specific like `<Error>`, then user can choose something more specific than `<any>`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
