### ISSUE TITLE
Typing not found for Extent | getting error as Namespace 'ol.interaction' has no exported member 'Extent'

### ISSUE THREAD

**Issue by junedansari** [DefinitelyTyped/DefinitelyTyped#28067]
Hi,
I am using the "@types/openlayers": "4.3.1" version. 
When i tried using 'ol.interaction.Extent' it giving me error as  Namespace 'ol.interaction' has no exported member 'Extent'
Is there anything i am missing ? or i guess typing is missing for same.
Please help .

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
