### ISSUE TITLE
lodash array chaining broken for max()

### ISSUE THREAD

**Issue by crooy** [DefinitelyTyped/DefinitelyTyped#2809]
when using a max() in a chain such as
  _.chain(myArrayWithStrings).keys().map((item) => parseInt(item, 10)).max().value()
i get the error
error TS2094: The property 'value' does not exist on value of type 'number'.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
