### ISSUE TITLE
@types/nodegit incorrect Reset.default and Reset.reset types

### ISSUE THREAD

**Issue by peterjwest** [DefinitelyTyped/DefinitelyTyped#28106]
- [x] I tried using the `@types/nodegit` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - @dolanmiu @tniessen

It looks like the `target` for `Reset.default` and `Reset.reset` have the wrong type.
The documentation clearly states this should be a Commit or Tag: http://www.nodegit.org/api/reset/#reset
However the existing type is for an Object:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/nodegit/reset.d.ts#L23

If someone can confirm this, I'm happy to make a PR.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
