### ISSUE TITLE
[@types/passport] Weird typing Bug when using ES6 import

### ISSUE THREAD

**Issue by backbone87** [DefinitelyTyped/DefinitelyTyped#28143]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi @enaeseth  @theigor @tlaziuk @danielpa9708 

Using TS 2.9.2 and latest passport typings...

The following works:
```ts
import passport from 'passport';

export default class Security {

  public readonly passport: passport.Authenticator;

  public constructor() {
    this.passport = new passport.Authenticator();
  }
}
```

While an error is reported for this:
```ts
import { Authenticator } from 'passport';

export default class Security {

  public readonly passport: Authenticator;

  public constructor() {
    this.passport = new Authenticator();
  }
}
```

Error message on assignment in constructor:
```
Type 'passport.Authenticator<e.Handler, any, any>' is not assignable to type 'passport.PassportStatic.Authenticator<e.Handler, any, any>'.
  Types of property 'use' are incompatible.
    Type '{ (strategy: Strategy): Authenticator<Handler, any, any>; (name: string, strategy: Strategy): Aut...' is not assignable to type '{ (strategy: Strategy): this; (name: string, strategy: Strategy): this; }'.
      Type 'Authenticator<Handler, any, any>' is not assignable to type 'this'.
```

Any idea?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
