### ISSUE TITLE
braft-editor Error 

### ISSUE THREAD

**Issue by luther-nwpu** [DefinitelyTyped/DefinitelyTyped#28163]
I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
 use this @types/braft-editor
      import BraftEditor = require('braft-editor')  will make error:
            
![image](https://user-images.githubusercontent.com/22161972/44181122-7ea55000-a132-11e8-82ff-6e0692d72c81.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
