### ISSUE TITLE
@types/Mongoose lacking replaceRoot method from Aggregate prototype

### ISSUE THREAD

**Issue by Maraket** [DefinitelyTyped/DefinitelyTyped#28228]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/mongoose` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @idandrd 

It appears that the replaceRoot method hasn't been included in the Aggregate class for @types/Mongoose. This has been slightly inconvenient but would be useful if it could be rectified at some point :)

**Comment by idandrd** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28240

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
