### ISSUE TITLE
Chart.js type doesn't support options field

### ISSUE THREAD

**Issue by leandropls** [DefinitelyTyped/DefinitelyTyped#28248]
Chart.js type doesn't support options field, though the library docs do say that it can be used to update the chart:
- http://www.chartjs.org/docs/latest/developers/updates.html
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b3c691dcd2f1379e324a89ae6782b503edabd39b/types/chart.js/index.d.ts#L21

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
