### ISSUE TITLE
knockoutjs: KnockoutComponentDefinition

### ISSUE THREAD

**Issue by luisrudge** [DefinitelyTyped/DefinitelyTyped#2825]
`template` is not accepting a string, only [a node](https://github.com/borisyankov/DefinitelyTyped/blob/master/knockout/knockout.d.ts#L569).
Accoring to the [spec](http://knockoutjs.com/documentation/component-registration.html#specifying-a-template), a string of markup should be accepted

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
