### ISSUE TITLE
Unable to import HighchartsNoDataToDisplay

### ISSUE THREAD

**Issue by prameetpradhan** [DefinitelyTyped/DefinitelyTyped#28285]
Unable to import HighchartsNoDataToDisplay

import HighchartsNoDataToDisplay from 'highcharts/modules/no-data-to-display';

saying @type/highcharts/modules/no-data-to-display has no default export.

**Comment by frankdavidcorona** [comment]
@prameetpradhan This is my solution:

```
import * as Highcharts from 'highcharts';
declare function require(name: string);
const HighchartsNoDataToDisplay = require('highcharts/modules/no-data-to-display');
HighchartsNoDataToDisplay(Highcharts);
```

Happy coding :+1: :100: ;-)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
