### ISSUE TITLE
Missing 'destroy' in interface Api for jCrop

### ISSUE THREAD

**Issue by michelvd** [DefinitelyTyped/DefinitelyTyped#28302]
@joeskeen I have a 'Destroy()' method in the API code which I don't see in the type definition file.
Is that missing?

From jCrop.js
```
 function destroy() //{{{
    {
      $div.remove();
      $origimg.show();
      $origimg.css('visibility','visible');
      $(obj).removeData('Jcrop');
    }
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
