### ISSUE TITLE
Fetch-Progress needs @types!

### ISSUE THREAD

**Issue by PamJoslyn** [DefinitelyTyped/DefinitelyTyped#28325]
I don't have enough time or knowledge to generate the .d.ts file for the npm package fetch-progress, but it would be nice if somebody would :)

**Comment by tup1tsa** [comment]
Can't you find something more popular? It has one star on github.

**Comment by PamJoslyn** [comment]
True. Turns out after implementing (with default types) that we could not make this work in Firefox. So it probably isn’t worth any effort.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
