### ISSUE TITLE
jquery.inputmask.d.ts

### ISSUE THREAD

**Issue by jpirok** [DefinitelyTyped/DefinitelyTyped#2837]
I wrote somewhat comeplete d.ts for jquery.inputmask.  I don't have time right now to complete it, but I want to see if some one here would be willing to finish it out.  The code is on github here https://github.com/jpirok/Typescript-jquery.inputmask

**Comment by lucax88x** [comment]
you should add this to TSD http://definitelytyped.org/tsd/?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
