### ISSUE TITLE
@types/express-serve-static-core cannot find module ‘http’ 

### ISSUE THREAD

**Issue by nolan1230** [DefinitelyTyped/DefinitelyTyped#28381]
![image](https://user-images.githubusercontent.com/7621226/44619892-7382ba80-a8be-11e8-9ab5-9b306388f0af.png)
node module has been included

/// <reference types="node" />

![image](https://user-images.githubusercontent.com/7621226/44619914-dd02c900-a8be-11e8-9fd4-26ee7a358a5d.png)

**Comment by nolan1230** [comment]
/// <reference path="../node/index.d.ts" />

resolved it by this

**Comment by nolan1230** [comment]
reference path="../node/index.d.ts"

**Comment by pluma** [comment]
Did you install `@types/node`?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
