### ISSUE TITLE
LoDash: Missing pluck method for array wrapper

### ISSUE THREAD

**Issue by garymach64** [DefinitelyTyped/DefinitelyTyped#2840]
According to the description in LoDashStatic definition, pluck exists on the lodash object and is chainable.
solution: (inserted at line 274, above the definition of LoDashArrayWrapper.compact)
interface LoDashArrayWrapper<T> {
                /**
                \* @see _.pluck
                **/
                pluck<T extends {}>(property: string): LoDashArrayWrapper<any>;
}

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
