### ISSUE TITLE
Missing methods in `@types/couchbase`

### ISSUE THREAD

**Issue by AugustSaintFreytag** [DefinitelyTyped/DefinitelyTyped#28425]
@fluggo and @maouida: There are a variety of methods missing from the **Couchbase** declaration for `@types/couchbase@^2.4.1`, most notably user management functionality in the `ClusterManager` part. Without knowing much about writing definitions, this is the patch I'm currently using, surely not enough for a merge request:

```typescript
declare module "couchbase" {

    interface ClusterManager {

        /**
         * @param domain
         * @param userid
         * @param settings
         * @param callback
         */
        upsertUser(domain: string, userid: string, settings: any, callback: Function): void;
    
        /**
         * @param domain
         * @param userid
         * @param callback
         */
        removeUser(domain: string, userid: string, callback: Function): void;
    
        /**
         * @param domain
         * @param callback
         */
        getUsers(domain: string, callback: Function): void;
    
        /**
         * @param domain
         * @param userid
         * @param callback
         */
        getUser(domain: string, userid: string, callback: Function): void;
    
    }

}
```

I'd like to add that this **leads to compile-time errors** when using `ts-node`, yet in VS Code, is recognised correctly without any noted errors.

<img width="1006" alt="screen shot 2018-08-27 at 22 38 00" src="https://user-images.githubusercontent.com/7656669/44684710-0e5bd000-aa4a-11e8-83d4-bb29e3eaba46.png">

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
