### ISSUE TITLE
No types for selenium-webdriver 4.0

### ISSUE THREAD

**Issue by ian-craig** [DefinitelyTyped/DefinitelyTyped#28464]
selenium-webdriver 4.0.0-alpha.1 has been available for 7 months, but the latest types are for 3.0.0 which is 2 years old. If selenium-webdriver 4 isn't getting a stable release soon it would be helpful to have types for the current alpha.

While using 3.0.0 types with 4.0.0 mostly works, there are some functions like `getRect` which are missing, and `getSize` which are no longer available.

Types contributers: @JoshuaKGoldberg @andy-ms @donaldpipowitch 
selenium-webdriver:  @jleyba

**Comment by sylvaindesve** [comment]
+1
Among modifications, `WebDriver#actions()` now accepts an `options` object.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
