### ISSUE TITLE
How to mark any published types package as deprecated

### ISSUE THREAD

**Issue by sachingupta** [DefinitelyTyped/DefinitelyTyped#28466]
Hi Team,

I am looking for information about marking https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/microsoftteams
https://www.npmjs.com/package/@types/microsoftteams as deprecated. Can you please point me the documentation for that?

@jayongg @WrathOfZombies

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
