### ISSUE TITLE
DOM Load and Save is missing

### ISSUE THREAD

**Issue by Mouvedia** [DefinitelyTyped/DefinitelyTyped#28470]
https://www.w3.org/TR/DOM-Level-3-LS/load-save.html

In particular `LSProgressEvent` which was widely implemented at one point.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
