### ISSUE TITLE
openlayers import Issue

### ISSUE THREAD

**Issue by hasaniadnan** [DefinitelyTyped/DefinitelyTyped#28500]
Hi, 

when installing @types/openlayers with typescript there is an issue that cannot directyl import the desired class. For Example: 
**let map = new Map** or **new ol.Map** I need to type in the import by saying "import * as ol from 'openlayers';  " because otherwise it says module/class could not be found. Is this problem due to the different versions of types/openlayers (4.6.12) and openlayers itself (5.1.3). Is there an actual version of the types for the current openlayers version

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
