### ISSUE TITLE
enzyme CommonWrapper.exists() missing .exists([selector]) overload

### ISSUE THREAD

**Issue by antonovicha** [DefinitelyTyped/DefinitelyTyped#28533]
Looks like enzyme CommonWrapper.exists() missing .exists([selector]) overload.
Definition only contains .exists() declaration:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8f7b983d5076174f520f53acc7041d6a779af7fe/types/enzyme/index.d.ts#L104

While https://airbnb.io/enzyme/docs/api/ReactWrapper/exists.html also have:

> .exists([selector]) => Boolean
> Returns whether or not the current node exists. Or, if a selector is passed in, whether that selector has any matching results.
> 
> Arguments
> selector (EnzymeSelector [optional]): The selector to check existence for.

**Comment by Ry7n** [comment]
Selector support was [added an in enzyme 3.4](https://github.com/airbnb/enzyme/blob/aa59612fbf88939f7488e5d009efbd8e82700105/CHANGELOG.md#340), but the typings are for version 3.1, so this is (somewhat) expected.

3.4 added a bunch of stuff, so it's not a trivial addition to the API, but if you want a quick workaround try:

```ts
import { EnzymeSelector } from 'enzyme';
declare module 'enzyme' {
  interface CommonWrapper {
    exists(selector?: EnzymeSelector) : boolean;
  }
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
