### ISSUE TITLE
[deepmerge] Typings are incorrect

### ISSUE THREAD

**Issue by nth-commit** [DefinitelyTyped/DefinitelyTyped#28543]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

Authors:
- @marvinscharle
- @ssy1125
- @AppLover69

These are the typings for the deepmerge function:
```
declare function deepmerge<T>(x: Partial<T>, y: Partial<T>, options?: deepmerge.Options): T;
declare function deepmerge<T1, T2>(x: T1, y: T2, options?: deepmerge.Options): T1 & T2;
```

The first overload (and therefore the one that will be picked up by TS if you don't specify the type arguments) is incorrect. A `Partial<T>` merged with a `Partial<T>` results in a `Partial<T>`, not a `T`. We cannot make the assertion that the intersection of both partial properties will be the full set of all properties of `T`.

Also, `Partial<>` is not the correct way to represent the input to deepmerge. It needs to be something like a DeepPartial (there is an example of this in the redux types).

In saying that, what is the problem with having just the second overload? What typings does the first provide that the second doesn't? Isn't it best to defer to the TS intersection operator?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
