### ISSUE TITLE
@types/stripe issing object value in ICardSourceListOptions

### ISSUE THREAD

**Issue by cgarnier** [DefinitelyTyped/DefinitelyTyped#28552]
The interface ICardSourceListOptions is not correct.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/stripe/index.d.ts#L1499

When using Stripe.customers.listSources(customer, options), it should allow to set object option to 'source'.
According the api docs, it s a valid option.
It s corresponding to the api call /v1/customers/cus_DVyfEkzJRUviqi/sources?object=source

**Comment by crallan** [comment]
Any updates on this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
