### ISSUE TITLE
calling openlayers namespaces functions - ol 5.2 and @types/ol 4.6.2

### ISSUE THREAD

**Issue by vodkatad** [DefinitelyTyped/DefinitelyTyped#28604]
- [X] I tried using the `@types/ol` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @yairtawil @osechet @wb14123 ...

I am trying to use some functions such as easeOut (found in the easing namespace), if I try to import it as 
`import {easeOut} from 'ol/easing';`
I get a compiler error:
`ERROR in src/app/app.component.ts(9,9): error TS2305: Module '"/home/data/hacknight/stomp/node_modules/@types/ol/easing/index"' has no exported member 'easeOut'.`

even if the produced js works and correctly calls the function.
If I add:
`export function easeOut(t: number): number;`

in @types/ol/easing/index.d.ts everything seems to work fine but I am not sure if this is the right way to fix this issue - are 5.2 @types underway?

Thanks!

**Comment by tomasprieboj** [comment]
any update?

**Comment by hanreev** [comment]
I've generated complete [TypeScript declaration for OpenLayers v5.3.2](https://github.com/hanreev/types-ol)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
