### ISSUE TITLE
[@types/styled-components] ThemedStyledComponentsModule from documentation does not compile

### ISSUE THREAD

**Issue by seanemmer** [DefinitelyTyped/DefinitelyTyped#28629]
@Igorbek @probablyup originally posted this in styled-components/styled-components#1959 and was told to post here.

Implementing example from docs (small change to avoid multiple imports from same module):

```
import * as styledComponents from 'styled-components'
import { ThemeInterface } from 'types'

const {
  default: styled,
  injectGlobal,
  keyframes,
  ThemeProvider,
  withTheme,
  css
} = styledComponents as styledComponents.ThemedStyledComponentsModule<ThemeInterface>

export { injectGlobal, keyframes, ThemeProvider, withTheme, css }
export default styled
```

Results in compilation error:
`This assertion is unnecessary since it does not change the type of the expression.`

I can confirm that the type of the individual methods is changing.  

E.g. the type for 'css' changes from:
`StyledComponents.ThemedCssFunction<Any>`

To:
`StyledComponents.ThemedCssFunction<ThemeInterface>`

Styled-Components Version: `3.4.2`
Typescript Version: `3.0.1`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by lifeiscontent** [comment]
@orta I have a PR to fix this issue.
