### ISSUE TITLE
@types/enzyme - `.instance()` from `.find()` should be able to return HTML*Element

### ISSUE THREAD

**Issue by weikinhuang** [DefinitelyTyped/DefinitelyTyped#28634]
When using `wrapper.find('.selector-for-html-element').instance()`, I am unable to cast the type to a native html element (or the react equivalent).

Example:

```typescript
class Foo extends React.Component<{}, {}> {
  render() {
    return (
      <div>
        <input className="foo-input" />
      </div>
    );
  }
}

const wrapper = mount(<Foo />);
const input = wrapper.find('.foo-input').instance() as HTMLInputElement;
```

```
Error:(91, 19) TS2352: Type 'Component<HTMLAttributes, any, any>' cannot be converted to type 'HTMLInputElement'.
    Property 'accept' is missing in type 'Component<HTMLAttributes, any, any>'.
```

@MarianPalkus

**Comment by hisuwh** [comment]
Only solution I can see to this would be to add a generic argument to instance so you can ovveride this if you need to.

```typescript
instance<CInstance = C>(): CInstance;
```

Typescript can't magically work out what the type of your `.foo-input` is

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
