### ISSUE TITLE
@types/node-forge no namespace 'random' in 'forge'

### ISSUE THREAD

**Issue by limbosounds** [DefinitelyTyped/DefinitelyTyped#28641]
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @westy92 @flynetworks @a-k-g @Rafal2228 @beenotung 
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

Following code
```typescript
import * as Forge from "node-forge"

interface ISRP6Config {
	N: string,
	g: string,
	k: string
}

class SRP6 {
	config: ISRP6Config
	randomString = (bytes: number = 128): string => {
		return Forge.random.generate(bytes)
	}
}
```
produces the error
```
Property 'random' does not exist on type 'typeof import("node-forge")'.
```

And inside the `index.d.ts` file is really no interface `random` :crying_cat_face:

**Comment by antony-chopin** [comment]
Also there is no interface 'sha512' in 'md'.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
