### ISSUE TITLE
@types/knex `knex.raw` does not allow chaining `.transacting`

### ISSUE THREAD

**Issue by dylanpyle** [DefinitelyTyped/DefinitelyTyped#28679]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/knex` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkQubo @MeLlamoPablo @mastermatt @micksatana @shreyjain1994

---

This is valid, working code that @types/knex disallows:

```ts
await db.raw(
  'select * from fit_partner_customers where shopify_user_id = ? for update',
  [customerId]
).transacting(trx);
```

The compile error is:
`Property 'transacting' does not exist on type 'Raw'.`

**Comment by mastermatt** [comment]
I dug into the source of Knex to a bit to double check this was intended behavior. 

It uses this file, https://github.com/tgriesser/knex/blob/master/src/interface.js, as a utility to add a handful of methods (`transacting` included) to several class like objects ([`raw`](https://github.com/tgriesser/knex/blob/master/src/raw.js#L191-L193), [`QueryBuilder`](https://github.com/tgriesser/knex/blob/2183a278268dc7aedf5edeccecb99176b9827f27/src/query/builder.js#L1074), and [`SchemaBuilder`](https://github.com/tgriesser/knex/blob/232fe9f1517dba927f6a3a1fb1b8842d7c0a4007/src/schema/builder.js#L68).
In the DT types, it seems the various methods have been added to the three interfaces ad hoc instead of extending a shared interface. I'll work on a PR in the next day or two (if I don't forget or someone beats me to it).
