### ISSUE TITLE
TS2339: Property 'on' does not exist on type 'SocketIOStatic'.

### ISSUE THREAD

**Issue by Kompwu** [DefinitelyTyped/DefinitelyTyped#28702]
- [x] I tried using the `@types/socket.io` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @progre  

How to fix it ?

**Comment by ezra100** [comment]
Can you please show the relevant part of the code that produced the error?

**Comment by Kompwu** [comment]
@ezra100 There:
```ts
io.on("connection", socket => {
  console.info(`Socket connected: ${socket.id}`);
});
```

**Comment by ezra100** [comment]
I suspect what you did is this:

``` javascript
import io = require('socket.io');
io.on('connection', myFunction)
```
Instead of this:
```javascript
import io = require('socket.io');
let sio: io.Server =    io(server); // server should be your http(s) server (of type http.Server or https.Server)
sio.on('connection', myFunction)
```
Change it to the latter and it should work fine.

**Comment by Kompwu** [comment]
@ezra100 I'm not...
```ts
const app: express.Application = express();
const port = 3000;

// Middlewares
app.use(cors());
// ...

// The fun part!
app.listen(port);
io(app);
```

**Comment by ezra100** [comment]
Can you show me the full code please? Where did you define 'io' and what type does it have (I guess it's SocketIOStatic?)? 
Are you trying to imitate [this example](https://socket.io/docs/#Using-with-Express)?
Because if so, in typescript you should change this:
`var io = require('socket.io')(server);`

to this (if you want the typing, you can still use the previous but the var 'io' would have an 'any' type):
```javascript
import ioImport = require('socket.io');
var io = ioImport(server);
```

**Comment by Kompwu** [comment]
@ezra100 Sure:
```ts
import * as express from "express";
import * as cors from "cors";
import * as bodyParser from "body-parser";
import * as io from "socket.io";

import * as index from "./routes/index";
import path = require("path");

const app: express.Application = express();
const port = 3000;

// Middlewares
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

// The fun part !
app.listen(port);
io(app);

// Sets
app.set("views", path.join(__dirname, "views"));
app.set("view engine", "ejs");
app.set("io", io);
app.engine("html", require("ejs").renderFile);

// Routes
app.use("/", index);

io.on("connection", socket => {
  console.info(`Socket connected: ${socket.id}`);
});
```
I'm a bit confuse now...
Can you show me ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by OliverLSanz** [comment]
I'm having this issue in 2025, I have two projects side to side. In one of them I get this TS error:

```
Property 'on' does not exist on type 'Socket<DefaultEventsMap, DefaultEventsMap>
```

Did you manage to fix it back then @Kompwu ?

**Comment by yanminthwin-i4b** [comment]
Facing same issue 
``` 
Property 'on' does not exist on type 'Socket<DefaultEventsMap, DefaultEventsMap>
```
```
Object literal may only specify known properties, and 'transports' does not exist in type 'Partial<ManagerOptions & SocketOptions>'.
```
