### ISSUE TITLE
angular.d.ts: Wrong types for IPromise<T>

### ISSUE THREAD

**Issue by Kinchkun** [DefinitelyTyped/DefinitelyTyped#2870]
Hi everyone,

currently I am struggling with the "then" type definition of the ng.IPromise-Interface

```
 then<TResult>(successCallback: (promiseValue: T) => TResult, errorCallback?: (reason: any) => TResult, notifyCallback?: (state: any) => any): IPromise<TResult>;
```

I think the errorCallback should return 'any' instead of 'TResult' like the other 'then' definitions does. Because: in the error case there is obviously no instance of 'TResult' available. Instead I want to give back the error result.

The same holds for the catch definition:

```
catch<TResult>(onRejected: (reason: any) => TResult): IPromise<TResult>;
```

I want to give back the error result.

What do you think?

Kind regards

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
