### ISSUE TITLE
@types/google-cloud__storage: File.copy incorrect definition

### ISSUE THREAD

**Issue by bag-man** [DefinitelyTyped/DefinitelyTyped#28749]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/google-cloud__storage` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @blove @nbperry @welkie @ogawa0071 

The definition for `File.copy()` appears to be out of date or incorrect. 

[The current typing](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-cloud__storage/index.d.ts#L130), looks like: 

```        copy(destination: string | Bucket | File): Promise<[File, ApiResponse]>;```

However the [docs](https://cloud.google.com/nodejs/docs/reference/storage/1.7.x/File#copy) and the [code](https://github.com/googleapis/nodejs-storage/blob/master/src/file.ts#L404) are now showing a second options argument:

```  copy(destination, options: CopyOptions, callback?) ```

I am unable to submit a PR at this time, but it should be a simple fix. 

Thanks

I believe the CopyOptions definition is this so you don't have to hunt around for it

```  
     /**
     * Options for copying file from buckets
     */
    interface CopyOptions {
      destinationKmsKeyName?: string;
      keepAcl?: string;
      predefinedAcl?: string;
      token?: string;
      userProject?: string;
    }
```

Upon further inspection the return type is also missing, of CopyResponse.

**Comment by welkie** [comment]
Note that `google-cloud/storage` now includes declaration files: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28774

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
