### ISSUE TITLE
@types/ - TS1209: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.

### ISSUE THREAD

**Issue by wallzero** [DefinitelyTyped/DefinitelyTyped#28744]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tlaziuk

I updated my builds to use Babel7 after following [the official blog post](https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/).

However, `@types/range-parser` (which appears to a dependency of `express`) throws an error during compilation: `TS1209: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.`

I can disable `isolatedModules` and my project builds but the guide says it is needed to `disallow features that require cross-file information for emit`.

**Comment by bopfer** [comment]
Any movement on this?  I am running into the same issue. According to the comments here: https://github.com/Microsoft/TypeScript/issues/20703#issuecomment-362005736, it should be changed to a union type of literals instead.

**Comment by wyqydsyq** [comment]
This issue has been resolved in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29783 but a [naughty bot closed the PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29783#issuecomment-432225120) as a result of Travis CI failing, [seemingly due to errors from completely unrelated packages](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/442141487?utm_source=github_status&utm_medium=notification). Looks like a maintainer/contributor with adequate permissions will need to manually re-open the PR to make travis test it again.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
