### ISSUE TITLE
TinyMCE missing union types

### ISSUE THREAD

**Issue by Gidmark** [DefinitelyTyped/DefinitelyTyped#28751]
Several methods are able to retrieve both string and a dom element, but the definition only allows string. Eg. DOMUtils getAttrib:  "elm (String) - Element string id or DOM element to get attribute from." 

Ping @martinduparc @iPoul

**Comment by martinduparc** [comment]
Thanks for the heads up. Feel free to submit a PR.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
