### ISSUE TITLE
@google-cloud/storage now provides their own declaration files, the types package should be deprecated

### ISSUE THREAD

**Issue by mattwelke** [DefinitelyTyped/DefinitelyTyped#28774]
As of version `2.0.1` on NPM, the `google-cloud/storage` package bundles its own declaration files. Therefore, the `@types/google-cloud__storage` package should be deprecated. (https://github.com/googleapis/nodejs-storage/releases/tag/v2.0.1)

**Comment by nbperry** [comment]
Nice, Thanks to @kinwa91 and the team for making this happen.

**Comment by ogawa0071** [comment]
That's great!!!

**Comment by bag-man** [comment]
The included types appear to have quite significant issues: https://github.com/googleapis/nodejs-storage/issues/384

The File object is not exported at all for instance. @welkie @kinwa91

**Comment by bag-man** [comment]
@welkie Would you be able to update it to fix https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28749 ?

**Comment by bag-man** [comment]
@welkie Much appreciated, thanks for all your effort. Definitely support moving forwards and making sure they do it right!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
