### ISSUE TITLE
@types/styled-components

### ISSUE THREAD

**Issue by maitriyogin** [DefinitelyTyped/DefinitelyTyped#28816]
If you know how to fix the issue, make a pull request instead.

- [ x ] I tried using the `@types/styled-components` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

  - Authors: Igor Oleinikov

If you do not mention the authors the issue will be ignored.

Hi,
I'm currently trying to use typescript with a react native application and have run into a problem when using @types/styled-components...
When I try and use a styled component as a component
```
const LoginFormStyledView = styled.View`
  flex: 1;
`;

const LoginForm = () => <LoginFormStyledView />;
```
I get the following

```
[ts]
Type '{}' is not assignable to type 'Readonly<ThemedOuterStyledProps<View, any>>'.
  Property 'measure' is missing in type '{}'.
under the <LoginFormStyledView /> component...
What do I need to do to get rid of this error?
```
Cheers,
Stephen.

**Comment by mounlion** [comment]
I have some issue!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
