### ISSUE TITLE
[angular-permission] Deprecated dependency

### ISSUE THREAD

**Issue by GabrielGil** [DefinitelyTyped/DefinitelyTyped#28895]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/angular-permission` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @vmishevski

The package requires "@types/angular-ui-router" which is deprecated as ui-router provides its own typings now.

Couldn't find the right way to just remove the dependency.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
