### ISSUE TITLE
@types/react-router 4.0.31 errors

### ISSUE THREAD

**Issue by rlee0525** [DefinitelyTyped/DefinitelyTyped#28894]
I tried using the most recent version of @types/react-router (v 4.0.31) and had problems.
It's now expecting strings for history, match and location but I don't think they've changed in react-router.

```javascript
history?: string | undefined; match?: string | undefined; location?: string | undefined;
```

Authors:
[Sergey Buturlakin](https://github.com/sergey-buturlakin)
[Yuichi Murata](https://github.com/mrk21)
[Václav Ostrožlík](https://github.com/vasek17)
[Nathan Brown](https://github.com/ngbrown)
[Alex Wendland](https://github.com/awendland)
[Kostya Esmukov](https://github.com/KostyaEsmukov)
[John Reilly](https://github.com/johnnyreilly)
[Karol Janyst](https://github.com/LKay)
[Dovydas Navickas](https://github.com/DovydasNavickas)
[Tanguy Krotoff](https://github.com/tkrotoff)
[Huy Nguyen](https://github.com/huy-nguyen)
[Jérémy Fauvel](https://github.com/grmiade)
[Daniel Roth](https://github.com/DaIgeb)
[Egor Shulga](https://github.com/egorshulga)
[Youen Toupin](https://github.com/neuoy)
[Rahul Raina](https://github.com/rraina)
[Maksim Sharipov](https://github.com/pret-a-porter)
[Duong Tran](https://github.com/t49tran)

**Comment by johnnyreilly** [comment]
> It's now expecting strings for history, match and location but I don't think they've changed in react-router.

That's what react router produces; just strings.  If you can prove otherwise then please do.  The motivation behind the PR was a colleague spending an afternoon wondering why when he said a parameter was a `number` in his code that it wasn't actually a `number` at runtime.  He could have been saved that with a compile time error.  Which is what he would now get 😄
