### ISSUE TITLE
jquery.pickadate inconsistent behavior

### ISSUE THREAD

**Issue by luisrudge** [DefinitelyTyped/DefinitelyTyped#2892]
I should be able to use jquery methods on the $input. Am I missing something?

![2014-09-29 00_24_05-statusreport - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/941075/4436952/258f507c-4788-11e4-8c59-c3345bec7a16.png)

**Comment by theodorejb** [comment]
@luisrudge Both these examples seem to work for me with the current definitions. If you're still having this issue, can you provide more details about the error? Otherwise the issue should be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
