### ISSUE TITLE
[@types/expo] No MapView type definitions in module

### ISSUE THREAD

**Issue by p-sebastian** [DefinitelyTyped/DefinitelyTyped#28920]
There are no type definitions for any MapView related API. 
Is this intentional?

https://docs.expo.io/versions/v30.0.0/sdk/map-view

**Comment by ande8133** [comment]
Found this: https://github.com/react-community/react-native-maps/blob/master/index.d.ts

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
