### ISSUE TITLE
three.js: can't use GLTFExporter in typescript

### ISSUE THREAD

**Issue by garyo** [DefinitelyTyped/DefinitelyTyped#28983]
- [x] I tried using the `@types/three` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mrdoob (three.js) , @MillerGregor (types/three)

I asked about this on Stack Overflow at https://stackoverflow.com/questions/52375863 and was directed to file a bug here.
It seems there's no way to properly use three.js `GLTFExporter` from typescript. There's a type decl for it in `@types/three/three-gltfexporter.d.ts` but the function itself is not exported as part of the THREE package. (I won't repeat the whole SO question here.)

In the SO question, Matt McCutchen suggests:

> It would be better if @types/three had an individual declaration file with a module augmentation of three for each optional extension such as GLTFExporter instead of declaring all the optional extensions unconditionally, so that TypeScript would be able to warn you about the problem at compile time. Consider filing a bug on DefinitelyTyped.

This simple example reproduces the problem:
```
import * as THREE from 'three'
let scene = new THREE.Scene()
function render(): void {
	let exporter = new THREE.GLTFExporter()
	exporter.parse(scene, (gltf) => {console.log("Parsed scene!"); }, {});
}
render()
```
When run with `npm start` this will give a browser error `Uncaught TypeError: THREE.GLTFExporter is not a constructor` (because it is undefined).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by nufair2006** [comment]
why is this closed? it's still relevant
