### ISSUE TITLE
@types/highcharts data type for series data

### ISSUE THREAD

**Issue by lisemon** [DefinitelyTyped/DefinitelyTyped#29039]
I would like to suggest to expand the IndividualSeriesOptions data property so that it supports data ranges with defined x values - currently the xvalues are defaulting to 0, 1, .. etc.

`data?: Array<number | [number, number] | [string, number] | DataPoint | **[number, number, number] | [string, number, number]**>;`

**Comment by lisemon** [comment]
I have a PR ready.

**Comment by lisemon** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29182

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
