### ISSUE TITLE
ObjectId constructor does not accept a string

### ISSUE THREAD

**Issue by swapzone** [DefinitelyTyped/DefinitelyTyped#2904]
I ran into problems when trying to create a new ObjectId Object with a given String. 
There is no constructor function given in your exported ObjectId class.

Could you add this constructor in:
export class ObjectId {}

Thank you, Sascha

**Comment by evereq** [comment]
Well, fromString will not exists anymore (see https://github.com/LearnBoost/mongoose/issues/1890), so instead of using mongoose.mongo.BSONPure.ObjectID.fromString correct way probably will be to just do following:
var objectId = new mongoose.Types.ObjectId("4eb6e7e7e9b7f4194e000001");

So, in the mongoose.d.ts should be constructor with string parameter, e.g:

     export module Types {
        export class ObjectId {
            toHexString(): string;
            constructor(id:string);
        }
     }

**Comment by Agamnentzar** [comment]
Fixed it here: https://github.com/borisyankov/DefinitelyTyped/pull/4373
