### ISSUE TITLE
redux-actions should test against redux

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#29107]
@jaysoo @alexgorbatchev @alechill @alexey-pelykh

`redux` types are pretty complicated so there's lots of ways the integration could go wrong. It seems like a good idea to include realistic examples of using this library with `redux` in the types.

For an example of how to test with redux, see `redux-action` (in particular its `package.json`) -- but its tests are currently broken and I don't know how to fix them. A comment says it was based on `redux-actions`, so perhaps what fixes one will fix the other.
Note `redux-action` currently tests against redux 3 but I presume redux-actions should be testing against redux 4?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
