### ISSUE TITLE
Ember smoke test should be cleaned up

### ISSUE THREAD

**Issue by BryanCrotaz** [DefinitelyTyped/DefinitelyTyped#29119]
@mike-north 

Comes out of #29079 

The smoke test that checks module stuff is imported into Ember global requires a clean up. 

If it is a pure smoke test that the correct exports have been declared, then clearly it doesn't need 100% code coverage of the module code. So a single call into each class or function would be enough to check that the export is present. At present some calls are made with multiple overload patterns, and some are not made at all. We should either test the minimum or the maximum - as this is a smoke test it should just test the minimum, otherwise other contributors will be tempted (as I was in my first review) to fill the gaps.

Checking that the _correct_ export mapping has been made should be possible by checking the type of the `new` object for example.

Some/most test calls use $ExpectType to confirm the result type. But many don't and if we're going to do it at all we should do it everywhere.

Tasks: 
- [ ] clean up unnecessary overloads
- [ ] add $ExpectType to every call

**Comment by mike-north** [comment]
tracking here: https://github.com/typed-ember/ember-cli-typescript/issues/316

**Comment by BryanCrotaz** [comment]
ahh I see.

Do you agree with my thought that we should remove overloads?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
