### ISSUE TITLE
Adding scientific charts to plotly.js

### ISSUE THREAD

**Issue by mouradmourafiq** [DefinitelyTyped/DefinitelyTyped#29127]
- [x] I tried using the `@types/plotly.js` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @chrisgervang @martinduparc @frederikaalund @taoqf @Dadstart @szechyjs @szechyjs @soorajpudiyadath @jonfreedman @meganrm

Thanks for provding the current types.

Is there any plans to extend the current types with `heatmaps` and `parcoords`?

thanks,

**Comment by StephenRUK** [comment]
I guess this is related - The configuration of contour plots is also missing in `Plotly.Data`. Tried to find the relevant JS code for the type signature myself but failed. See https://plot.ly/javascript/contour-plots/ for examples

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
