### ISSUE TITLE
Preferred location for type files

### ISSUE THREAD

**Issue by guyellis** [DefinitelyTyped/DefinitelyTyped#29157]
- [X] I have a question that is inappropriate for StackOverflow.

This might be closed on Stack Overflow as an "opinion" question.

If the maintainer of a Node module was prepared to maintain the `.d.ts` file for types in their module would that be a better place to keep the `.d.ts` file(s) vs in the DefinitelyTyped repo?

My initial thought is that the `.d.ts` file maintained with the source repo would probably be kept more up-to-date than an independent one. Also a separate dependency does not have to be managed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
