### ISSUE TITLE
[web3] Only use named exports in web3

### ISSUE THREAD

**Issue by dkent600** [DefinitelyTyped/DefinitelyTyped#29164]
Most or all of the major types in the web3 type definitions are defined as default types. This is a problem:

- default types cannot be augmented. Augmentation is desireable when working around bugs in the typings and for any application-idiomatic need to extend the web3 API.
- making some types default and other types not default make inconsistent the syntax for importing the two

Can we find a way to satisfy the required use cases without using `default` types?

@Levino

**Comment by Levino** [comment]
Thanks for creating this.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
