### ISSUE TITLE
@types/reactstrap Not working in WebStorm 2018.2.3

### ISSUE THREAD

**Issue by djereg** [DefinitelyTyped/DefinitelyTyped#29199]
- Authors: @alihammad @mfal @danilobjr @FaithForHumans @KurtPreston @timc13 @patrickrgaffney 

This is all what WebStorm shows:
![image](https://user-images.githubusercontent.com/6384768/46052039-cad5ae00-c13c-11e8-989c-9a7ed1af94cc.png)

package.json
```json
{
  "dependencies": {
    "reactstrap": "^6.4.0",
  },
  "devDependencies": {
    "@types/reactstrap": "^6.0.3",
  }
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
