### ISSUE TITLE
change in ng-grid.d.ts

### ISSUE THREAD

**Issue by lucamorelli** [DefinitelyTyped/DefinitelyTyped#2923]
Hi,  
  in the ng-grid.d.ts file I needed to do a change in the export interface IGridOptions:  
  I had to change from **columnDefs?: IColumnDef[]** to **columnDefs?: any**, otherwise I cannot write             **$scope.gridOptions.columnDefs = "colDefs"**, assigning to the columndef property another variable in the scope.  
Looks me this notation is very used to assign dinamically the column definitions.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
