### ISSUE TITLE
@types/node includes broken async iterable definitions

### ISSUE THREAD

**Issue by slikts** [DefinitelyTyped/DefinitelyTyped#29274]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Microsoft @DefinitelyTyped @jkomyno @a-tarasyuk @alvis @r3nya @brunoscheufler @smac89 @tellnes @DeividasBakanas @eyqs @Flarna @Hannes-Magnusson-CK @KSXGitHub @hoo29 @kjin @ajafff @islishude @mwiktorczyk @matthieusieben @mohsen1 @n-e @octo-sniffle @parambirs @eps1lon @SimonSchick @ThomasdenH @WilcoBakker @wwwy3y3 @ZaneHannanAU

The types for [async iterables] are incomplete. It defines:
```ts
interface AsyncIterableIterator<T> {}
```
But it doesn't define `AsyncIterator` or `AsyncIterable`. This is confusing when `AsyncIterableIterator` appears to work, but doesn't really, and then the other types are undefined.

Should the fix be just to copy the types from [esnext.asynciterable.d.ts]?

[async iterables]: http://2ality.com/2016/10/asynchronous-iteration.html
[esnext.asynciterable.d.ts]: https://github.com/Microsoft/TypeScript/blob/master/src/lib/esnext.asynciterable.d.ts

**Comment by Flarna** [comment]
This is just a forward declaration to avoid transpile errors. if you want to use these types then add `esnext.asynciterable` as lib in your tsconfig.json and the types will be merge and are useable.

**Comment by Flarna** [comment]
This is how typescript works currently. With typescript 3.0 it would be possible to use a lib reference directive to correct this but node definitions have to be compatible with typescript 2.0 currently.

I don't think duplicating standard libs into node typings (and maybe others) because of some issue in ts-jest is the solution here. I would recommend to fix the issue in ts-jest to respect the settings for tsconfig instead.

**Comment by slikts** [comment]
I had misdiagnosed the issue; it was a config error not related to ts-jest, but I think the point still stands that it's confusing for `AsyncIterableIterator<T>` to exist alone and incorrect.

**Comment by Flarna** [comment]
The type is not incorrect, it's incomplete. By adding the correct lib in tsconfig.json the full details are added. This is how forward declarations work.
The alternative would be to remove the forward declaration and require all users to add the needed libs - even if they are not using `AsyncIterableIterator` in their code. I don't think this would be a step forward.

**Comment by jordanbtucker** [comment]
It doesn't make sense to add `esnext.asynciterable` to `lib` since async iterators are an ES2018 feature, not ESNext. See https://node.green/#ES2018

`lib: ["es2018"]` should be sufficient.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
