### ISSUE TITLE
Type of React.ReactFragment, which includes {}, breaks certain usages of children in TS 3.1

### ISSUE THREAD

**Issue by Jessidhia** [DefinitelyTyped/DefinitelyTyped#29307]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly 
  - (Note: it's really hard to mention any author since none of them have github tags in the `index.d.ts`)

The type of `ReactFragment` currently includes `{}`, which causes the new, safer handling of `typeof x === 'function'` to only narrow `x` to `Function`.

[Sample playground link](http://www.typescriptlang.org/play/#src=namespace%20React%20%7B%0D%0A%20%20type%20ReactChild%20%3D%20ReactElement%3Cany%3E%20%7C%20string%20%7C%20number%0D%0A%0D%0A%20%20interface%20ReactNodeArray%20extends%20Array%3CReactNode%3E%20%7B%7D%0D%0A%20%20type%20ReactFragment%20%3D%20%7B%7D%20%7C%20ReactNodeArray%0D%0A%20%20export%20type%20ReactNode%20%3D%20ReactChild%20%7C%20ReactFragment%20%7C%20ReactPortal%20%7C%20string%20%7C%20number%20%7C%20boolean%20%7C%20null%20%7C%20undefined%0D%0A%0D%0A%20%20interface%20ReactPortal%20extends%20ReactElement%3Cany%3E%20%7B%20%7D%0D%0A%0D%0A%20%20interface%20ReactElement%3CP%3E%20%7B%0D%0A%20%20%20%20type%3A%20any%3B%0D%0A%20%20%20%20props%3A%20P%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20Props%20%7B%0D%0A%20%20children%3A%20React.ReactNode%20%7C%20(()%20%3D%3E%20React.ReactNode)%0D%0A%7D%0D%0A%0D%0Afunction%20Component(props%3A%20Props)%20%7B%0D%0A%20%20return%20typeof%20props.children%20%3D%3D%3D%20'function'%20%3F%20props.children()%20%3A%20props.children%0D%0A%7D%0D%0A)

This same code would work as intended in TS 3.0.

I don't know why an empty object is considered a valid fragment; this allows literally `any`thing to be passed as a child as long as it's not "fresh".

**Comment by Hotell** [comment]
To fix this a major overhaul of types would be needed, which is not gonna happen anytime soon IMHO

What you can do in the meantime is to use `ReactChild` or `ReactElement`

> which type is 👉 `type ReactChild = ReactElement<any> | ReactText;` and basically that's what you want.
> I didn't came to a situation when my component had to accept  boolean or empty ( null | defined ) value as children.

```ts
interface Props {
  children: React.ReactChild | () => React.ReactChild
}
```

or if you need to accept null undefined as well you can map those types via Maybe:

```
type Maybe<T> = T | null | undefined
interface Props {
  children: Maybe<React.ReactChild> | () => Maybe<React.ReactChild>
}
```

**Comment by alexpomsft** [comment]
A related issue of ReactFragment accepting {} is that it's easy to misreference functions within React components instead of calling them.  React DOM complains at runtime, but React Native doesn't which can make it hard to catch.  Regardless of runtime handling, it would be great if we could get the types updated to support this.

```typescript
<Text>{getText}</Text>   // oops!
<Text>{getText()}</Text> // fixed
```

[TypeScript playground](https://codesandbox.io/s/ypkl9m5k1v).  [Flow equivalent](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAER4XWMDcqqlcAdgM5ECpAB5EAvEwAWpGPA7c+gsAHNSBACqiJYABQBKMOIB8YYWK48BNOHCNgAPNmOowb924CQDgCboAbsYA3uYEAL4OwH6Brh5x3tHBapraEVEBLnHukc7sQA) that catches this error.

**Comment by joshburgess** [comment]
This is big a problem. Because a React component can render a fragment & ReactFragment has such a loose type, this means you can literally return anything from a React component. People can return objects that blow up and run-time and get no warning or compiler error from TypeScript. This just seems wrong. Is there any way we can address this sooner?

**Comment by quicksnap** [comment]
What is preventing `{}` from being removed as a possibility? It just seems wrong and haphazard.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
