### ISSUE TITLE
DefinitelyTyped/types/ej.web.all invalid capitalization in property

### ISSUE THREAD

**Issue by yuriy-bezrukov** [DefinitelyTyped/DefinitelyTyped#29319]
now wrong (ej.datavisualization.Diagram.HistoryChangeEventArgs)

>     export interface HistoryChangeEventArgs {
>       Source?: any[];

need 

>     export interface HistoryChangeEventArgs {
>       source?: any[];

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
