### ISSUE TITLE
JSZip pulls in Node ambient typings when they are not wanted

### ISSUE THREAD

**Issue by AlexVallat** [DefinitelyTyped/DefinitelyTyped#29310]
Would it be possible to make the Node typings in JSZip optional or split out in some way? When using JSZip as a browser project it pulls in all the Node ambient typings which can cause issues elsewhere (such as redefining setInterval, etc.)

  - Authors: @mzeiher, @forabi

**Comment by SimenB** [comment]
I'd like to go the other way - remove dom typings as we just use this in node

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
