### ISSUE TITLE
@types/hls.js - hls.audioTracks has incorrect typings (and lacks typings for subtitleTracks)

### ISSUE THREAD

**Issue by peboCodemill** [DefinitelyTyped/DefinitelyTyped#29311]
- [x] I tried using the `@types/hls.js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jgainfort 

The method `audioTracks: AudioTrack[];` returns data on the format seen below instead of the `AudioTrack` interface which is defined in `lib.dom`.

```typescript
{
  audioCodec: string,
  autoselect: boolean,
  default: boolean,
  forced: boolean,
  groupId: string,
  id: number,
  lang: string,
  name: string,
  type: string,
  url: string
}
```

Also, the method `subtitleTracks: any[];` is lacking correct typings. Would be nice if that got added as well! :)

```typescript
{
  autoselect: boolean,
  default: boolean,
  forced: boolean,
  groupId: string,
  id: number,
  lang: string,
  name: string,
  type: string,
  url: string
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
