### ISSUE TITLE
React Loadable loader component not render while no error in console.

### ISSUE THREAD

**Issue by abhinav2331** [DefinitelyTyped/DefinitelyTyped#29323]
I am using react loadable with typescript.
Below is my code looks like.

const LoadingComponent = () => <h3>please wait...</h3>;

// Campaign List
const AsyncCampaigns = Loadable({
    loader: () => import('./components/leadgeneration/exittraffic/campaigns.list.component'),
    loading: LoadingComponent    
});
// QuestionBlockCampaign
const AsyncQuestionBlockCampaign = Loadable({
    loader: () => import('./components/leadgeneration/questionblocks/question.block.campaign.component'),
    loading: LoadingComponent    
});
This is my Route
`<BrowserRouter>
                        <Switch> 
                            <Route exact path='/' component={Home} />
                            <Route path='/lead-generation/exit-traffic/campaigns' component={AsyncCampaigns} />
                            <Route path='/lead-generation/question-blocks/campaigns' component={AsyncQuestionBlockCampaign} />                            
                        </Switch>
</BrowserRouter>`

When I run my application then no error show in console and only loading content on page loader not render on page.

Please help me it urgent.

**Comment by tkajtoch** [comment]
Please check the value of `error` property from properties argument passed to `loading` property of the Loader. You should get there the desired Error object and find out why it's failing.

**Comment by Sphinxs** [comment]
How did you get the log ? (code please ?)

**Comment by GAUTAMRAJU15** [comment]
```
function LoadingComponent(props) {
  if (props.error) {
    return <div>Error! <button onClick={ props.retry }>Retry</button></div>;
  } else {
    return <div>Loading...</div>;
  }
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
