### ISSUE TITLE
Add `@types/google-apps-script` Advanced Service

### ISSUE THREAD

**Issue by grant** [DefinitelyTyped/DefinitelyTyped#29349]
Add Advanced Service types to `@types/google-apps-script`.

A list of Advanced Services can be found here:
https://developers.google.com/apps-script/advanced/adsense

**Comment by j-frost** [comment]
I've got a contribution for [google-apps-script-tests.ts](../blob/master/types/google-apps-script/google-apps-script-tests.ts):

```typescript
function getTotalUsers(): number {
    let pageToken;
    let totalUsers = 0;
    do {
        let result = AdminReseller.Subscriptions.list({pageToken: pageToken});
        const subscriptions = result.subscriptions.filter(function (subscription) {
            return subscription.skuName.indexOf('G Suite') >= 0
        });
        for (let subscription of subscriptions) {
            const planName: string = subscription.plan.planName;
            if (planName.indexOf('ANNUAL') >= 0) {
                totalUsers += subscription.seats.numberOfSeats;
            }
            else if (planName == 'FLEXIBLE' || planName == 'TRIAL') {
                totalUsers += subscription.seats.licensedNumberOfSeats;
            }
        }
        pageToken = result.nextPageToken;
    } while (pageToken);
    log(`Reporting ${totalUsers} total users`);
    return totalUsers;
}
```

For now, this is the only service that really hurts in its absence, but we've got a few projects in the pipeline where I might come back and expand the list. 

I will definitely write a blog post and reference it here, because I really think both the typings and claps itself are super valuable in making development of GAS much less painful. 

I've heard it's difficult for you guys to add typings for AppMaker in a similar fashion because AppMaker uses proprietary tools/code. While I understand that this is the case, we've been asked multiple times now by clients and colleagues alike whether similar support will ever come. Developers really like their IDEs, as it were.

**Comment by j-frost** [comment]
Alright @grant , we have the blog post online ([en_US](https://blog.seibert-media.com/2018/10/30/google-apps-scripts-clasp-and-data-studio/), [de_DE](https://blog.seibert-media.net/blog/2018/10/26/google-apps-scripts-clasp-und-data-studio/)). 

I have added some superficial descriptions of the new `DataStudioApp` in the posts, and I'd also like to request it here. Really helpful, those builders! :)

**Comment by alexgoldsilver** [comment]
Ditto on the request for DataStudioApp in here, as it's some of the most complex development best done locally.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
