### ISSUE TITLE
ThreeJS: Type 'Material | Material[]' is not assignable.

### ISSUE THREAD

**Issue by Eketol** [DefinitelyTyped/DefinitelyTyped#29384]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @Methuselah96 (sorry, I don't know who I should ask this, so I just got the last contribuitor's name).

I have some functions in my code that accept a material or an array of materials as parameter.
As a simple example:

```
private applyMaterialToMesh(mesh:THREE.Mesh, material:THREE.Material | Array<THREE.Material>):void {
	mesh.material = material;
}
```

With the current version of @types/three from npm (0.92.23), I get this error on compiling with VisualStudioCode:

> Type 'Material | Material[]' is not assignable to type 'ShaderMaterial | MeshBasicMaterial | MeshDepthMaterial | MeshFaceMaterial | MeshLambertMaterial |...'.

According to the ThreeJS API documentation about Mesh (https://threejs.org/docs/#api/en/objects/Mesh):

> Constructor
> Mesh( geometry : Geometry, material : Material )
> geometry — (optional) an instance of Geometry or BufferGeometry. Default is a new BufferGeometry.
> material — (optional) a single or an array of Material. Default is a new MeshBasicMaterial

So far I've fixed it by changing MeshMaterialType (three-core.d.ts, line 5285) from:

`export type MeshMaterialType = MeshBasicMaterial | MeshDepthMaterial | MeshFaceMaterial | MeshLambertMaterial | MeshNormalMaterial | MeshPhongMaterial | MeshStandardMaterial | ShaderMaterial | ShadowMaterial;`

to:

`export type MeshMaterialType = Material | MeshBasicMaterial | MeshDepthMaterial | MeshFaceMaterial | MeshLambertMaterial | MeshNormalMaterial | MeshPhongMaterial | MeshStandardMaterial | ShaderMaterial | ShadowMaterial;`

I want to make sure I'm right before asking to be fixed or suggesting a pull request.

**Comment by Methuselah96** [comment]
This has already been discussed in the PR that originally made the change: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27413 (see also https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26772). Would it work for your method to be written like this?:
```
private applyMaterialToMesh(mesh: THREE.Mesh, material: THREE.MeshMaterialType | Array<THREE.MeshMaterialType>):void {
	mesh.material = material;
}
```
If you don't like that or it's too narrow for you, I would suggest making a PR that removes `MeshMaterialType` altogether and reverts back to using `Material | Material[]` as the the type for material in `Mesh` and see how opposed @Astrak is to the revert. It would be useless to add `Material` to `MeshMaterialType` since the rest of them all extend from `Material`.

**Comment by Eketol** [comment]
Thanks for the quick response, I will continue the discussion on the PR.
