### ISSUE TITLE
@types/pusher-js: Pusher logging settings shouldn't be typed constant or readonly

### ISSUE THREAD

**Issue by kofno** [DefinitelyTyped/DefinitelyTyped#29413]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/pusher-js` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cainlevy 

The Pusher.log and Pusher.logToConsole cannot be set because they are typed as being constant or readonly.

![image](https://user-images.githubusercontent.com/19907/46416099-d43eb780-c6f4-11e8-8c3b-d53593c505b9.png)

**Comment by cainlevy** [comment]
@kofno I can reproduce this in my own project but not in the type tests, so it's not a quick fix for me. For now I'd recommend working around the issue with `(Pusher as any).logToConsole = true`.

**Comment by kofno** [comment]
OK... I'll do that for now. Thanks for the fast response.

**Comment by mdurling** [comment]
I think this is how ES6 modules work; imports are constants. I suspect you could also work around this using `const Pusher = require('pusher-js')` although, perhaps the better solution is to create an `enableLogging` function that sets the `logToConsole` boolean.

**Comment by alshdavid** [comment]
Might I suggest you add a static method to control logging status

```
import * as Pusher from 'pusher-js'

Pusher.setLogToConsole(true)
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
