### ISSUE TITLE
AssociationOptionsHasOne does not have scope.

### ISSUE THREAD

**Issue by tteke** [DefinitelyTyped/DefinitelyTyped#29434]
As the title says the has one options does not have scope, however, it is possible to add scope for hasOne associations.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5996b44c51b737b295c5ca67328ad88d0bd99644/types/sequelize/index.d.ts#L1305

**Comment by Saamiyah** [comment]
The index.d.ts file has been refactored.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
