### ISSUE TITLE
[Request] Definitions for Adobe CEP

### ISSUE THREAD

**Issue by SturmB** [DefinitelyTyped/DefinitelyTyped#29433]
I am brand-spankin'-new to TypeScript and Adobe CEP, otherwise I'd probably just create the definitions myself as a PR. (Although I'm not even 100% sure how to do _that_.)

[Adobe CEP](https://github.com/Adobe-CEP) is a way to create extensions for Adobe's suite of applications. To create an extension using CEP, you need a few JS library files. Specifically, `CSInterface.js`, `Vulcan.js`, and `AgoraLib.js`. These can be found in the [CEP-Resources repo](https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_8.x).

It seems an [effort was made](https://github.com/BrightShadow/CSInterface-TS) two years ago to create a definition file for `CSInterface.js`, but has since been abandoned and is now out of date.

Also, because I am still new to the TS world, there are insufficient instructions there for me to know how to even use it. I've tried for hours and errors still persist ("TS4025: Exported variable 'csInterface' has or is using private name 'CSInterface'.") on the first line, `let csInterface = new CSInterface();`. This is from just using the existing beginner instructions in the [Getting Started guide](https://github.com/Adobe-CEP/Getting-Started-guides).

I would appreciate any effort to creating definitions for Adobe CEP and, preferably, instructions on how to make sure TS 'sees' them. Thank you.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
