### ISSUE TITLE
[nodejs 10.x] fs.promises.fstat is not a function

### ISSUE THREAD

**Issue by abenhamdine** [DefinitelyTyped/DefinitelyTyped#29485]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Microsoft

If you do not mention the authors the issue will be ignored.

Nodejs 10.11
Current typings allow to write : 
```ts
import * as fs from 'fs'
// in async function
const stats = await fs.promises.fstat(file)
// will throw : fs.promises.fstats is not a function
```
but fs.promises.fstats doesn't exist, only fs.promises.stat, see https://nodejs.org/api/fs.html#fs_fs_promises_api

due to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f17caa9fa6d08a7d7b010c32568cab436a247516/types/node/index.d.ts#L5361

**Comment by zdila** [comment]
Same for Node 12.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
