### ISSUE TITLE
react-i18next definitions out of line with version 8+ of project

### ISSUE THREAD

**Issue by chillitom** [DefinitelyTyped/DefinitelyTyped#29480]
Version 8 of _react-i18next_ appears to have deprecated a few definitions and added some new interfaces..  e.g `NamespacesConsumer` [link](https://react.i18next.com/components/namespacesconsumer)
and `withNamespaces` [link](https://react.i18next.com/components/withnamespaces)
I'm relatively new to typescript and unsure of how to generate the definitions, I'd be happy to get involved if someone could give me some pointers.

- [x] I tried using the `@types/react-i18next` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @GiedriusGrabauskas @chnoch @beheh @whtsky

**Comment by stefanKuijers** [comment]
We have the same problem. How big change to you guys think we would need to this package? Are they small definitions?

**Comment by DevanB** [comment]
I've been investigating the same. I'm not well-versed in @type packages creation yet, so struggling to handle with local module augmentation.

**Comment by jadbox** [comment]
This issue is particularly annoying since translate() has been renamed to withNamespaces, however the later is not typed yet. In the meantime I'm getting warnings from i19n to use the new convention. If react-i18next would be willing to move the definitions into their repo, I'd be more apt to help update the bindings.

**Comment by DevanB** [comment]
I’ve got the withNamespaces typed out locally. But I can’t commit them back because a test doesn’t pass. The test doesn’t pass in the clean, current version of the typings too, though. 

The react-i18n maintainer is very audibly against typed javascript and refuses to help or allow types in the code base. So I’d be surprised if you were to convince him. Until then, we will all have to band together to keep the types up to date.

**Comment by Kovensky** [comment]
I started working on some type definitions locally, but I hit a snag about a week ago... and haven't picked it back up yet 😖
