### ISSUE TITLE
[material-components-web] 0.40.0 broke mdc-dialog typings

### ISSUE THREAD

**Issue by CiriousJoker** [DefinitelyTyped/DefinitelyTyped#29497]
v0.40.0 of the material-components-web project introduced breaking changes to how dialogs work.
https://github.com/CiriousJoker/DefinitelyTyped/blob/master/types/material__dialog/index.d.ts

Basically:
open => isOpen
escapeKeyAction: string;
scrimClickAction: string;
autoStackButtons: boolean;

show() => open()
close() => close(action?: string)

@BrentDouglas

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
