### ISSUE TITLE
Error: In types/quill/package.json: Dependency quill-delta not in whitelist.

### ISSUE THREAD

**Issue by m93a** [DefinitelyTyped/DefinitelyTyped#29526]
- [x] I want to add a new package (totally unrelated to quill) but `npm test` fails with the message below. Because of that, I can't test any of my code locally.
> Error: In /home/m93a/.../DefinitelyTyped/types/quill/package.json: Dependency quill-delta not in whitelist.
> If you are depending on another `@types` package, do *not* add it to a `package.json`. Path mapping should make the import work.
> If this is an external library that provides typings,  please make a pull request to types-publisher adding it to `dependenciesWhitelist.txt`.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (It's a bug report, not a question).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sumitkm, @guillaume-ro-fr, @43081j, @AnielloFalcone, @mhamri

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
