### ISSUE TITLE
[@types/jsforce] Interface Promise implementation in Chatter, metadata seems incorrect?

### ISSUE THREAD

**Issue by varmeEqualsthis** [DefinitelyTyped/DefinitelyTyped#29529]
Receiving below errors compiling jsforce with latest typescript. Looks like Promise interface is wrongly implemented.

ERROR in [at-loader] ......\node_modules@types\jsforce\api\chatter.d.ts:30:14
TS2420: Class 'Request' incorrectly implements interface 'Promise'.
Property 'finally' is missing in type 'Request'.

ERROR in [at-loader] ......\node_modules@types\jsforce\api\metadata.d.ts:115:14
TS2420: Class 'AsyncResultLocator' incorrectly implements interface 'Promise'.
Property 'finally' is missing in type 'AsyncResultLocator'.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
