### ISSUE TITLE
[@types/openlayers] Missing MapBrowserEventType

### ISSUE THREAD

**Issue by HarelM** [DefinitelyTyped/DefinitelyTyped#29521]
- [x] I tried using the `@types/openlayers` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @matthiasdailey-ccri, @pierremarc, @peszek90, @iamthechad, @yairtawil, @osechet, @gberaudo

See the following class:
https://github.com/openlayers/openlayers/blob/master/src/ol/MapBrowserEventType.js

Will be very helpful in order to remove hard coded event strings.
Thanks for all the hard work!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
