### ISSUE TITLE
IoT Event Type TODO

### ISSUE THREAD

**Issue by digitaldivvy** [DefinitelyTyped/DefinitelyTyped#29539]
@darbio 

- [ ] I tried using the `@types/aws-lambda` 8.10.13 package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

When will an IoT Event Type be included in the types definition. It still says "TODO"

See index.d.ts line 819.

**Comment by cloudsolver** [comment]
It would be 'nice to have' though not necessary, any works as a work-around.

**Comment by simonbuchan** [comment]
Going back through `aws-lambda` issues, since they seem to be being neglected.
The existing TODOs for services are more "we know these exist, but nobody using them has submitted a PR for them yet" than "I'll get around to it later".
That said, the list of remaining services is pretty small now, so I'm thinking I'll have a go at them. Some are easier than others to validate the needed types, but we actually are using several of them here at work (though not with node lambdas yet), so I'm hopeful. No specific timeframes, of course.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
