### ISSUE TITLE
[@types/arcgis-js-api] Allow ignoring autocastable properties

### ISSUE THREAD

**Issue by leqwasd** [DefinitelyTyped/DefinitelyTyped#29566]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @Esri @bsvensson

Example: 
In my config files, I define some initial value, for example, Extent, with some of my own interfaces
```
interface IConfig {
  extent: IExtent;
};
interface IExtent {
  xmax: number;
  xmin: number;
  ymax: number;
  ymin: number;
}
const config: IExtent = {
  extent: {
    xmax: 364705.8868890038
    xmin: 362800.8830789962
    ymax: 338644.1310382838
    ymin: 337948.275479906
   }
};
```
And later, when I am constructing Map and MapView, I pass these in.

```
map = new Map();
mapView = new MapView({
  map: map,
  container: container
});

mapView.extent = config.extent; // ! ! !
```

Seems like a trivial thing, but typescript and your types prevents me from doing so.
```
Type 'IExtent' is not assignable to type 'Extent'.
  Property 'center' is missing in type 'IExtent'.
```
I have to use `// @ts-ignore` over and over.
And this is just an example. Same thing could be applied to number of things!

`center` should be an autocast property, and it is in JavaScript. But TypeScript forces it on me.

At this point, these typescript definitions are usable just for intellisense. Every time I want to interact with the objects, I have to disable typescript!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
