### ISSUE TITLE
[electron-window-state] - pulls in 1.x.x electon types that conflicts with 2.x.x

### ISSUE THREAD

**Issue by Akuukis** [DefinitelyTyped/DefinitelyTyped#29567]
`@types/electron-window-state` depends on old electron (^1) types that conflict with new electron (^2) types. Package itself works fine with new electron. Types should be updated then I guess.

- Authors: @andy-ms

**Comment by andy-ms** [comment]
PRs accepted. (Actual author is @rhysd)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
