### ISSUE TITLE
d3-shape Cannot find name 'CanvasPathMethods'

### ISSUE THREAD

**Issue by vnugent** [DefinitelyTyped/DefinitelyTyped#29587]
@tomwanzek @gustavderdrache @borisyankov

- [X ] I tried using the `@types/d3-format` package and had problems.
- [X ] I tried using the latest stable version of tsc. 

Before TS upgrade: (no errors)
- typescript 2.8.4
- d3-format": "1.3.2"

After TS upgrade:
- "typescript": "3.1.1"

Error message:
```
node_modules/@types/d3-shape/index.d.ts
(2273,19): Cannot find name 'CanvasPathMethods'.
```

**Comment by gustavderdrache** [comment]
From what I can tell, the `@types/d3-format` package doesn't depend on `@types/d3-shape`, so it's likely that some other dependency (either in your package.json or pulled as a dependency of something else) is causing this problem for you.

That having been said, you're in luck! It looks like this issue was corrected in version 1.2.4 of `@types/d3-shape` - see [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27776/files) and the published [index.d.ts](https://unpkg.com/@types/d3-shape@1.2.4/index.d.ts) on unpkg. Once you've updated that, you should be on your merry way.

**Comment by vnugent** [comment]
You're right about other dependency pulling in `@types/d3-shapes`.  No longer and issue for me.  Thanks!

**Comment by HarelM** [comment]
I have the same issue after upgrading to angular 7 with typescript 3.1.1.
I think the problem is with `@types/d3-shapes`. Is there a fix to this?

**Comment by denisname** [comment]
Problem come from TypeScript 3.1. They renamed `CanvasPathMethods` to `CanvasPath`. Use `CanvasPath` under TypeScript 3.1. If you need to support also older TypeScript versions, use `d3. CanvasPath_D3Shape`.  See [d3-shape/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-shape/index.d.ts#L16-L17).

**Comment by HarelM** [comment]
I'm not referencing the types directly but instead am using a library that depends on them: d3-ng2-service.
So I'm not entirely sure how to fix this, any help would be appreciated...

**Comment by denisname** [comment]
The package `d3-ng2-service` may need an update for TypeScript 3.1. Though I don't think it should: [package.json](https://github.com/tomwanzek/d3-ng2-service/blob/master/package.json#L92).

Make sure your packages are all up to date by removing `node_modules` and run `npm install`.
