### ISSUE TITLE
Attribute "accessible" not available in @types/onoff Gpio class

### ISSUE THREAD

**Issue by uherj** [DefinitelyTyped/DefinitelyTyped#29647]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/onoff` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @marcel-ernst, @fivdi, @johntalton, @Manawyrm, @towc

If you do not mention the authors the issue will be ignored.

**Comment by Manawyrm** [comment]
Hi, 

just a heads up: just mentioning everyone who has contributed to the library in the past isn't really nice and probably isn't helping anyway... 

Your issue doesn't contain either a question or detailed problem. (apart from the fact that I have never used TypeScript and I'm not 100% sure what this repository is doing... )

Marcel Ernst is probably the right person to ask... (with a proper question and in the best case: short demo snippet code)

Best regards,
Tobias

**Comment by uherj** [comment]
Sorry for incomplete question. The problem I have is written in the subject of the issue. I am using TypeScript in my node.js project where I work with Raspberry Pi 3+. For that I need @types/onoff. If I import the Gpio class there I don't have access to the Gpio.accessible attribute that is normally available if I do not use TypeScript.

So I was wondering how can I use the Gpio.accessible attribute while using TypeScript.

Thank you.
Kind regards,
Jarek

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
