### ISSUE TITLE
[@types/flickity] Make FlickityOptions exportable

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/DefinitelyTyped#29659]
`FlickityOptions` isn't exported so it's not possible to use that type within your own scripts.

- [x] I tried using the `@types/flickity` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/). I asked the question on StackOverflow and determined the issue was with the types. See [here](https://stackoverflow.com/questions/52735292/ts-using-interface-from-third-party-typings/52735340?noredirect=1#comment92408993_52735340)
- [x] Mention the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @clmcgrath, @wagich

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
