### ISSUE TITLE
WinJS.d.ts missing external module declaration for commonjs/browserify support

### ISSUE THREAD

**Issue by joewood** [DefinitelyTyped/DefinitelyTyped#2965]
To better support **browserify** builds with the CommonJS way of using WinJS, could the following lines be added to the winjs.d.ts file?

``` typescript
declare module "WinJS" {
    export var WinJS : typeof WinJS;
}
```

This will then allow **browserify** users to import WinJS directly:

``` typescript
import winjs_imp = require("WinJS");
var WinJS = winjs_imp.WinJS;
```

Note that the CommonJS export in WinJS when using **deamdify** exports the root namespace with WinJS being exposed as a top level exported variable.  See this [issue in WinJS](https://github.com/winjs/winjs/issues/571).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
