### ISSUE TITLE
[@types/jquery] Documentation links in backticks

### ISSUE THREAD

**Issue by King2500** [DefinitelyTyped/DefinitelyTyped#29680]
Is this intended?
![image](https://user-images.githubusercontent.com/4896363/46865766-fc2dc980-ce1e-11e8-9169-a2eb55270a38.png)

![image](https://user-images.githubusercontent.com/4896363/46865805-21bad300-ce1f-11e8-9afd-4d190f3a25b6.png)

IntelliJ based IDEs (WebStorm, PhpStorm, etc.) do not resolve this.
What are those backticks for?

@leonard-thieu, @borisyankov, @choffmeister, @Steve-Fenton, @Diullei, @tasoili, @jasons-novaleaf, @seanski, @Guuz, @ksummerlin, @basarat, @nwolverson, @derekcicerone, @AndrewGaspar, @seikichi, @benjaminjackman, @s093294, @JoshStrobl, @johnnyreilly, @DickvdBrink, @terrymun

**Comment by leonard-thieu** [comment]
It's a workaround for VS Code. See #26452 for more information. Links should work as expected in both IntelliJ-based IDEs and VS Code.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
