### ISSUE TITLE
React navigation types are outdated 

### ISSUE THREAD

**Issue by andresfgonz** [DefinitelyTyped/DefinitelyTyped#29706]
current web docs shows the follow options for contentOptions : 

items - the array of routes, can be modified or overridden
activeItemKey - key identifying the active route
activeTintColor - label and icon color of the active label
activeBackgroundColor - background color of the active label
inactiveTintColor - label and icon color of the inactive label
inactiveBackgroundColor - background color of the inactive label
onItemPress(route) - function to be invoked when an item is pressed
itemsContainerStyle - style object for the content section
itemStyle - style object for the single item, which can contain an Icon and/or a Label
labelStyle - style object to overwrite Text style inside content section, when your label is a string
activeLabelStyle - style object to overwrite Text style of the active label, when your label is a string (merged with labelStyle)
inactiveLabelStyle - style object to overwrite Text style of the inactive label, when your label is a string (merged with labelStyle)
iconContainerStyle - style object to overwrite View icon container styles.

but this is the current types definitions:

`export interface DrawerNavigatorConfig
  extends NavigationTabRouterConfig,
  DrawerViewConfig {
  containerConfig?: any;
  contentOptions?: {
    activeTintColor?: string;
    activeBackgroundColor?: string;
    inactiveTintColor?: string;
    inactiveBackgroundColor?: string;
    style?: StyleProp<ViewStyle>;
    labelStyle?: StyleProp<TextStyle>;
  };
}`

for example itemStyle should be typed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
