### ISSUE TITLE
Contribution guidelines for versioning

### ISSUE THREAD

**Issue by park9140** [DefinitelyTyped/DefinitelyTyped#2972]
Update for the contribution guidelines to make it less annoying to deal with when new versions are adde

Suggested text for the version section

Version

In case there are multiple versions supported, library.d.ts file will reference in the latest version using a typescript reference.
All versions will be in the form of library-1.2.0.d.ts where the postfix should resemble a valid semantic version number (semver).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
