### ISSUE TITLE
es6-promise - Promise.all incorrect parameter type

### ISSUE THREAD

**Issue by joewood** [DefinitelyTyped/DefinitelyTyped#2975]
The definition of `all` does not match the comment on the function:

``` typescript
/** * Make a promise that fulfills when every item in the array fulfills, and rejects if (and when) any item rejects.  
 * the array passed to all can be a mixture of promise-like objects and other objects.  
 * The fulfillment value is an array (in order) of fulfillment values. The rejection value is the first rejection value.     */ 
function all<R>(promises: Promise<R>[]): Promise<R[]>; 
```

The function definition should accept a `Thenable<R>[]`, or even `any[]`

``` typescript
function all<R>(promises: Thenable<R>[]): Promise<R[]>; 
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
