### ISSUE TITLE
Bug: date() function can also return null.

### ISSUE THREAD

**Issue by ArthurBorsboom** [DefinitelyTyped/DefinitelyTyped#29780]
The file index.d.ts contains the typing for the date() method. The method is described as that only a Moment object can be returned. However, it can also return null, just as the comment above states.

IMHO: this is easily fixed by adding null as a possible return value.

Before
``` 
    /** Returns the component's model current date, a moment object or null if not set. */
    date(): moment.Moment;
```
After
```
    /** Returns the component's model current date, a moment object or null if not set. */
    date(): moment.Moment | null;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
