### ISSUE TITLE
build: linting on local env doesn't work which makes contributing PITA

### ISSUE THREAD

**Issue by Hotell** [DefinitelyTyped/DefinitelyTyped#29814]
@sandersn @RyanCavanaugh @DanielRosenwasser 

node: 8.12.0
npm: 6.4.1
os: macOS Mojave

`npm run lint react` doesn't work

![image](https://user-images.githubusercontent.com/1223799/47087674-e2282880-d21c-11e8-8e03-90b799cdaa62.png)

**Comment by Hotell** [comment]
quick fix is to explicitly install typescript and tslint as devDependency

```sh
npm i -D typescript tslint
```

**Comment by andy-ms** [comment]
Maybe you just need to refresh `node_modules` (`git clean -xfd` and `npm install` again)? Are you maybe using yarn or a proxy?
I tested this in windows and linux with npm 6.4.1 and it worked.

**Comment by Hotell** [comment]
@andy-ms I provided my environment :) and yes I tried  removing package-lock, node_modules. Nothing works except  the workaround that I've described

**Comment by andy-ms** [comment]
Maybe `npm cache clean` would help? This problem shouldn't be happening because both of DefinitelyTyped's dependencies, `dtslint` and `types-publisher`, both have `typescript` as a dependency.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
