### ISSUE TITLE
mongodb options sslCa typing is wrong acording to documentation

### ISSUE THREAD

**Issue by ergoithz** [DefinitelyTyped/DefinitelyTyped#29813]
Interface https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bbf1adeeacd4ac881e7d8546abc7101cd3de597d/types/mongodb/v2/index.d.ts#L77 says (buffer | string)[]

Documentation on both v2 http://mongodb.github.io/node-mongodb-native/2.2/api/MongoClient.html#.connect and v3 http://mongodb.github.io/node-mongodb-native/3.1/api/MongoClient.html#.connect libraries say buffer.

I'm a bit concerned about this project being a bit too creative with types.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
