### ISSUE TITLE
[styled-components] Optional types passed down as required

### ISSUE THREAD

**Issue by soutot** [DefinitelyTyped/DefinitelyTyped#29832]
I opened this [issue](https://github.com/styled-components/styled-components/issues/2096) and was oriented to reopen it here.

I'm trying to customize some Material UI components using Styled Components, however, once I wrap the MUI component with ```styled``` hoc TypeScript starts to warn regarding some props are not provided. Looking at MUI props definitions all of them are optional. If I use the pure MUI component it works fine.

Code example:

 ```
 import styled from 'styled-components';
  import { TextField } from '@material-ui/core';

  const TextFieldStyled = styled(TextField)``
  /* This returns missing props warning */   
  <TextFieldStyled 
      name={name}
      label={label}
      value={value}
      onChange={onChange}
    />

  /* This works fine */
  <TextField
      name={name}
      label={label}
      value={value}
      onChange={onChange}
    />
```

I found this PR that was used to solve a passing down props issue https://github.com/styled-components/styled-components/pull/1427/files

After updating the code to pass the props as partial. I tested and the warning is gone.
https://github.com/soutot/styled-components/blob/master/typings/styled-components.d.ts#L56

I'd like to share this with you and check if this is the correct approach or if this error was not suppose to happen and I'm missing something.

My package.json contains
"styled-components": "^3.4.9"
"@material-ui/core": "^3.2.0",
"@types/material-ui": "^0.21.5",

Thanks

@Igorbek @Igmat @Lavoaster

**Comment by nickmccurdy** [comment]
It seems like something in the declaration file for SC is using a non-homomophic mapped type (see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html).

**Comment by soutot** [comment]
@nickmccurdy I'm not sure if I got what you mean. Where is this file that you mentioned? I coudln't find any ternary condition that may fit the docs description you provided
https://github.com/soutot/styled-components/blob/master/typings/styled-components.d.ts

**Comment by jaycle** [comment]
My project is experiencing the same issue as what's reported here. Previously we were on 2.4 of SC and uncovered this during update. The error seems similar to what's reported in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30942 but I don't know enough about SC or MUI to say for sure.

For completeness, with
```javascript
"@types/styled-components": "^4.1.3",
"@material-ui/core": "^3.6.1"
```
and something like
```javascript
import styled from 'styled-components';
import Button from '@material-ui/core/Button';

const SubmitButton = styled(Button)`
  float: right;
  margin-right: 20px;
`;
```
I'll get a warning like the following when in use:
```
Type '{ children: string; disabled: false; onClick: () => void; variant: "contained"; }' is missing the following properties from type 'Pick<Pick<ButtonProps | (ButtonProps & RefAttributes<Component<ButtonProps, any, any>>), "disabled" | "media" | "hidden" | "dir" | "form" | "slot" | "style" | "title" | ... 274 more ... | "disableFocusRipple"> & Partial<...>, "disabled" | ... 281 more ... | "disableFocusRipple">': style, size, className, innerRef, classes
```

**Comment by Kovensky** [comment]
It seems changing the definition of Button to use `React.ComponentClass` instead of `React.ComponentType` fixes it. This is likely an issue with `@material-ui`'s types, but still strange that it broke as this was not supposed to be a breaking change.

**Comment by jaycle** [comment]
Why would it be an issue with MUI's type when
```javascript
const SubmitButton = styled(Button)`
  float: right;
  margin-right: 20px;
` as typeof Button;
```
works perfectly?

**Comment by t-l-k** [comment]
@Kovensy, could you clarify your reported fix? Which type specification are you changing?

**Comment by Kovensky** [comment]
`@material-ui`'s types are specifying that `Button` is simultaneously "either a `ComponentClass` or `FunctionComponent`", but neither of those are assignable to something that is only a `ComponentClass` or only a `FunctionComponent`.

```ts
import Button from '@material-ui/core/Button'

declare function test(component: ComponentClass<any>): void
declare function test(component: FunctionComponent<any>): void

test(Button) // type error, Button not assignable to either overload
```

**Comment by FredyC** [comment]
@Jessidhia Do you possibly have news for the material-ui? The workaround exists, but it's definitely ugly and makes things complicated.

**Comment by eps1lon** [comment]
@Jessidhia If we have a union of two types and one accepts a prop and one not then one should assume that the union does not accept the prop before the union was narrowed. That's at least [how typescript does it](https://www.typescriptlang.org/play/index.html#src=interface%20Foo%20%7B%0D%0A%20%20kind%3A%20'foo'%3B%0D%0A%20%20message%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Bar%20%7B%0D%0A%20%20kind%3A%20'bar'%3B%0D%0A%20%20description%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20log(descriptor%3A%20Foo%20%7C%20Bar)%20%7B%0D%0A%20%20const%20prefix%20%3D%20%60%24%7Bdescriptor.kind%7D%3A%20%60%3B%0D%0A%0D%0A%20%20%2F%2F%20%24ExpectError%0D%0A%20%20const%20message%20%3D%20%60%24%7Bprefix%7D%24%7Bdescriptor.message%7D%60%3B%0D%0A%20%20if%20(%22message%22%20in%20descriptor)%20%7B%0D%0A%20%20%20%20console.log(%60%24%7Bprefix%7D%24%7Bdescriptor.message%7D%60)%0D%0A%20%20%7D%0D%0A%20%20if%20(%22description%22%20in%20descriptor)%20%7B%0D%0A%20%20%20%20console.log(%60%24%7Bprefix%7D%24%7Bdescriptor.description%7D%60)%0D%0A%20%20%7D%0D%0A%7D).

I don't understand why `styled-components` is essentially bailing out instead of assuming that the union of `FunctionComponent` | `ClassComponent` does not accept a `ref` prop.

**Comment by DanWebb** [comment]
I also get "props not provided" errors with [Ant design components](https://ant.design/docs/react) 

This workaround is working for me currently:
```
const StyledButton = styled((props: ButtonProps) => (
  <Button {...props} />
))``
```

**Comment by dandonahoe** [comment]
@jaycle THANK YOU.

**Comment by alirezamirian** [comment]
This is not specific to MUI. I also get this error when using components generated by [styled-svg](https://www.npmjs.com/package/styled-svg)

**Comment by OrenSchwartz** [comment]
getting the same issue when using antd button.

packages are:
    "antd": "^3.10.8",
    "@types/antd": "^1.0.0",
    "@types/react": "^16.4.4",
    "react": "^16.8.3",
    "typescript": "3.3.3333",

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
