### ISSUE TITLE
[@types/redux-orm] static Model.reducer mistyped?

### ISSUE THREAD

**Issue by nolanlocke** [DefinitelyTyped/DefinitelyTyped#29847]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @keenondrums

Perhaps this is something I'm missing here, but is the static Model.reducer types off? 

In the defaultUpdater the code invokes the reducer function with three arguments
```
if (typeof modelClass.reducer === 'function') {
    // This calls this.applyUpdate to update this.state
    modelClass.reducer(action, modelClass, session);
}
```

whereas the reducer function on Model in the types file is defined as 
`static reducer(session: SessionWithModels<ORMCommonState>, action: any): any;`

**Comment by ymko13** [comment]
It seems to be off, i'm having a similar issue. First argument passed to the reducer is actually action and second is actually modelClass. So I have to do a little crazy thing with this. But i still can't get access to session. 

It most likely has something to do with the fact that we are using redux-orm > 0.09 and latest typings seem to be for 0.9

**Comment by keenondrums** [comment]
@nolanlocke @ymko13 it's indeed an issue. Thank you! PRs are welcome

**Comment by ymko13** [comment]
@keenondrums actually it seems to be mistyped regardless of version. Checked against 0.9. 
Here is a PR: 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29998

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
