### ISSUE TITLE
There is a problem to use constant of google.maps.MapTypeId as strings 

### ISSUE THREAD

**Issue by profiprog** [DefinitelyTyped/DefinitelyTyped#29858]
Why is [MapTypeId](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/24a30d0f2e6db719f3fcdc72f89157ea0cdd7ed9/types/googlemaps/index.d.ts#L260) defined as enum?
Its constants cannot be assigned to string, although they are.
Wouldn't be better define MapTypeId like: 
```typescript
declare const MapTypeId: {
  readonly HYBRID: string,
  readonly ROADMAP: string,
  readonly SATELLITE: string,
  readonly TERRAIN: string
};
```
It would be much easer to code with definition like this.

**Comment by Maxim-Mazurok** [comment]
AFAIK, it's not the same. You can use enum as a value, so `MapTypeId.HYBRID === "HYBRID"`.
But with your approach, we can't do it that way. Makes sense?

**Comment by profiprog** [comment]
If **MapTypeId** would be an enum, then yours expressions may evaluate to `true`.
But they are not. You can check it here: [https://jsfiddle.net/profiprog/829z1Lce/11/](https://jsfiddle.net/profiprog/829z1Lce/11/)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
