### ISSUE TITLE
[`@types/elasticsearch`] Why is the `body` of `SearchParams` of type `any`

### ISSUE THREAD

**Issue by anselmstordeur** [DefinitelyTyped/DefinitelyTyped#29862]
- [x] I tried using the `@types/elasticsearch` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CasperSkydt, @bfsmith, @ddunkin, @pushplay, @mlamp, @ahmadferdous, @SimonSchick, @brabster, @deerawan

Is there any specific reason why the `body` of `SearchParams` is not typed correctly? I would like to start a pull request for this, but before I try I would like to hear if anyone has tried that already and what problems occured on the way.

**Comment by SimonSchick** [comment]
Maybe due to complexity?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
