### ISSUE TITLE
IncomingMessage#connection should also be typed as tls.TLSSocket

### ISSUE THREAD

**Issue by RomainLanz** [DefinitelyTyped/DefinitelyTyped#29870]
Hey everyone 👋 

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. 

Authors: @Microsoft, @jkomyno, @BrunoScheufler, @smac89, @DeividasBakanas, @eyqs, @Flarna, @Hannes-Magnusson-CK

The definition of `IncomingMessage#connection` should be typed as `net.Socket | tls.TLSSocket` instead of only `net.Socket`.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L1252

I didn't create a PR because I cannot make it works on my side.
My editor tells me that `tls` isn't defined in the file (and it is...)

![](https://user-images.githubusercontent.com/2793951/47203814-becabe00-d381-11e8-8ab9-c2faeef6c657.png)

Would be happy to create the PR if someone provides guidance to fix this.

**Comment by RomainLanz** [comment]
It makes sense to create a dedicated `https.IncomingMessage` type.

I'll try to make the change and provide a PR if it works.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
