### ISSUE TITLE
[@types/sprintf-js] Global declaration in the sprintf-js definitions

### ISSUE THREAD

**Issue by cdagli** [DefinitelyTyped/DefinitelyTyped#29878]
Hello, 

May I ask why we have the below global declaration in the sprintf-js package? 

```
....
export function vsprintf(format: string, args: any[]): string;

declare global {
    function sprintf(format: string, ...args: any[]): string;
    function vsprintf(format: string, args: any[]): string;
}
....
```

We had some issues because of that because sprintf becomes global once it is imported once in a file and you can use it in other files without importing. I think this is wrong. Wdyt? 

- Authors: @jasonswearingen, @BendingBender

**Comment by jasonswearingen** [comment]
yes, looks wrong to me.  I'm sorry I don't use sprintf-js anymore (I use the es6 template strings instead) so I can't contribute a fix.

Personally I would encourage you to give template strings a try too:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
