### ISSUE TITLE
Backbone.sync cannot be overridden

### ISSUE THREAD

**Issue by jgonggrijp** [DefinitelyTyped/DefinitelyTyped#29883]
- [x] I tried using the `@types/backbone` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @nvivo @kenjiru 

The Backbone documentation [states](http://backbonejs.org/#Sync):

> **Backbone.sync** is the function that Backbone calls every time it attempts to read or save a model to the server. By default, it uses `jQuery.ajax` to make a RESTful JSON request and returns a [jqXHR](http://api.jquery.com/jQuery.ajax/#jqXHR). You can override it in order to use a different persistence strategy, such as WebSockets, XML transport, or Local Storage.

But if I try this:

```ts
import * as bb from 'backbone';

bb.sync = function(method, model, options?) { /*...*/ };
```

tsc gives me this error:

```console
Error TS2540: Cannot assign to 'sync' because it is a constant or a read-only property.
```

Possibly related to #7629. I see that Backbone is declared as a namespace; could this be the reason that `Backbone.sync` is considered read-only? Backbone really is an object with overridable methods.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
