### ISSUE TITLE
redux-action compile errors

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/DefinitelyTyped#29896]
@newraina

The tests in `redux-action` are currently failing (`npm run lint redux-action`). I suspect this is because of updates to `redux` and `redux-thunk` which are its dependencies. I don't understand this library well so don't know what the correct fix is.

**Comment by andy-ms** [comment]
@7hi4go @alexey-pelykh @lsanwick @florian-richter Any idea what to do here?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
