### ISSUE TITLE
[webgl-ext] error TS2430: Interface 'WebGLRenderingContext' incorrectly extends interface 'WebGLRenderingContextBase'

### ISSUE THREAD

**Issue by xiaodeaux** [DefinitelyTyped/DefinitelyTyped#29897]
- [x] I tried using the `@types/webgl-ext` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @zenmumbler 

Here's a StackOverflow post that has the relevant information: https://stackoverflow.com/questions/52846622/error-ts2430-interface-webglrenderingcontext-incorrectly-extends-interface-w

**Comment by zenmumbler** [comment]
@xiaodeaux I just submitted a PR that moves webgl-ext into the modern era. The TensorFlowJS people will still have to update or remove this types package though.

Due to this file modifying the built-in types, it now requires TS 2.7+. There's no working around this, the old types work with the old lib.d.t.s, but not with the new one and vice-versa.

**Comment by xiaodeaux** [comment]
@zenmumbler Thank you very much. I've been stuck on this problem for a few weeks and I've had very little luck in progressing.

**Comment by zenmumbler** [comment]
@xiaodeaux No problem, I see the tfjs people have already merged this so you should be good to go!
