### ISSUE TITLE
gapi.client.drive.files.create(...) is missing the resource property.

### ISSUE THREAD

**Issue by GaryChamberlain** [DefinitelyTyped/DefinitelyTyped#29901]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/gapi.client.drive` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Bolisov @alexcason 

The files.create method doesn't include the most important property: **resource**.  That's how you give it a name and a mime type.

See the example in the drive documentation: https://developers.google.com/drive/api/v3/integrate-create

See this great article where the author references this bug and describes how to hack the package in node_modules to get around it.  https://hintdesk.com/2018/08/24/angular-google-drive-api-example/

**Comment by matatablack** [comment]
up :)

**Comment by anandchakru** [comment]
@Bolisov @alexcason it is missing in `permission.create` as well

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
