### ISSUE TITLE
@types/webpack-hot-client definitions has return type of void but it should be an object with properties

### ISSUE THREAD

**Issue by ericpitcher** [DefinitelyTyped/DefinitelyTyped#29907]
When I use webpack-hot-client with the definitions from `@types/webpack-hot-client` I get an error 'Type 'void' has no property 'server' and no string index signature'.

The main export from webpack-hot-client takes the webpack compiler as the first argument and an options object as the second and then it returns an object with the properties: close, options & server but the type definitions state that it returns void.

Authors: @rynclark @ZSkycat

**Comment by ZSkycat** [comment]
you can create a PR

**Comment by barm** [comment]
@ericpitcher This should be fixed now.

@ZSkycat I think we should be able to resolve this issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
