### ISSUE TITLE
[styled-components] strongly type ThemeProvider

### ISSUE THREAD

**Issue by sandervspl** [DefinitelyTyped/DefinitelyTyped#29928]
With v3 I was able to strongly type my ThemeProvider like this, albeit a bit dirty

```typescript
import * as i from '@types';
import * as styledComponents from '../../../node_modules/styled-components';

const {
  default: styled,
  css,
  createGlobalStyle,
  keyframes,
  ThemeProvider,
} = styledComponents as styledComponents.ThemedStyledComponentsModule<i.Theme>;

export { css, createGlobalStyle, keyframes, ThemeProvider };
export default styled;
```

With an alias `styled-components` pointing to this file, I would always get the correct theme types on my styled-components. Now that types have moved to DefinitelyTyped, and now that I would like to use styled-components v4, this method no longer works.

What is the new recommended way to strongly type my theme?

**Comment by sandervspl** [comment]
Thanks, it does indeed still work, but in my case it's a little different. The problem I was facing was that I had an alias route like this that no longer works now that types have been moved.

`"styled-components": ["app/services/styled-components.ts"]`

Because in my service file I have to extract functionality and the `ThemedStyledComponentsModule` type from the actual `styled-components` library. Extracting the types from `@types/styled-components` does not work.

Guess I'm using `@styled-components` as alias for now, so that `styled-components` can correctly augment the actual package

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
