### ISSUE TITLE
[@types/velocity-animate]

### ISSUE THREAD

**Issue by choukin** [DefinitelyTyped/DefinitelyTyped#29939]
I use it like this

```js
import Velocity from 'velocity-animate'

  public enter(el: HTMLElement, done: any) {
    Velocity(el, {opacity: 1, fontSize: '1.4em'}, {duration: 300})
    Velocity(el, {fontSize: '1em'}, {complete: done})
  }
  public leave(el: HTMLElement, done: any){
      Velocity(el, {translateX: '15px', rotateZ: '50deg'}, {duration: 600})
   }
```
![image](https://user-images.githubusercontent.com/6270610/47285444-8810d400-d61d-11e8-8e77-7f27a72ecb4d.png)
error info `The 'this' context of type 'void' is not assignable to method's 'this' of type 'VelocityElements'.`

**Comment by qindj** [comment]
@choukin 
You should use the latest definition file from [julianshapiro/velocity](https://github.com/julianshapiro/velocity) , see https://github.com/julianshapiro/velocity/pull/884

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
