### ISSUE TITLE
[@types/reach__router] - History.location incorrect

### ISSUE THREAD

**Issue by atrauzzi** [DefinitelyTyped/DefinitelyTyped#29932]
Looking at the interface for `History`, I can see that `location` is incorrect.  It is not a string, it is in fact an object structure.

```
export interface History {
    readonly location: string;
    readonly transitioning: boolean;
    listen: (listener: HistoryListener) => HistoryUnsubscribe;
    navigate: NavigateFn;
}
```

If I dump the contents of location, this is what I get:

![image](https://user-images.githubusercontent.com/115199/47271152-62ab9980-d53b-11e8-8713-6735e6187cef.png)

cc. @Kingdaro

**Comment by kingdaro** [comment]
PRs welcome 🙂

**Comment by atrauzzi** [comment]
I'm not sure what type to assign it given all existing types.  Wasn't able to track down a decent candidate.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
