### ISSUE TITLE
[@types/openlayers] Missing moveTolerance for ol.olx.MapOptions

### ISSUE THREAD

**Issue by jondediego** [DefinitelyTyped/DefinitelyTyped#29999]
I tried using the `@types/openlayers` package and had problems. The options available for ol.olx.MapOptions that are used in order to instantiate an ol.Map do not include the mapTolerance option which should be available.
 I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
Authors: @matthiasdailey-ccri, @pierremarc, @peszek90, @iamthechad, @yairtawil, @osechet, @gberaudo

Thanks for all the hard work!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
