### ISSUE TITLE
[React] The React. CloneElement function parameter element does not accept the ReactChild type

### ISSUE THREAD

**Issue by fantasy525** [DefinitelyTyped/DefinitelyTyped#29997]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly 

```
<View>
			{
				React.Children.map(props.children,(element: ReactChild,index:number)=>{
						if(!element){
							return null;
						}
						return React.cloneElement(element ,// here is error type
							Object.assign({},element.props,{
							key:index,
							model:props.model,
							onChange:props.onChange
						}))
					}
				)}
		</View>
```
error: `Argument of type 'ReactChild' is not assignable to parameter of type 'ReactElement<any>'.`

but  i find

 ```    //
    // React Nodes
    // http://facebook.github.io/react/docs/glossary.html
    // ----------------------------------------------------------------------
    type ReactText = string | number;
    type ReactChild = ReactElement<any> | ReactText;`
```

How do I solve this problem?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
