### ISSUE TITLE
[@types/react-navigation] Duplicate identifier 'MessageQueue'.

### ISSUE THREAD

**Issue by fantasy525** [DefinitelyTyped/DefinitelyTyped#30001]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @huhuanming 

may be repeatedly dependent on `@react-native`
```
 "dependencies": {
        "@types/react": "*",
        "@types/react-native": "*"
    }
```
and 
![image](https://user-images.githubusercontent.com/22516157/47431258-09a76400-d7ce-11e8-86e0-3c88d0829dc5.png)

and i remove `@types/react-navigation` then errors disappears

**Comment by kristerkari** [comment]
I had the same issue. 

In my case it was happening because I had `@types/react-native` with version `^0.57.11` defined in my `package.json` and as `@types/react-navigation` has a dependency to to the react native types, it ended up installing a new version `0.57.12`, and because of that the Typescript compiler was throwing errors for duplicate types.

The way that I got it fixed was to update the `@types/react-native` in my `package.json`  to version `0.57.12`, so then there was only one version of the types in use, and the error went away.

**Comment by gtRfnkN** [comment]
I had the same problem and upgrading the react-native types to the latest version did solve the problem. However, we still using RN 0.55 and therefore upgrading the typings to 0.57 does work but might cause problems elsewhere.

The main problem was caused when I tried to upgrade RN to 0.57 and then reset it back to 0.55. During this process, I installed react-navigation & this typing. The typing itself does not require a specific RN typing and yarn is smart about it and only installs one (v0.57 from RN + v* -> v0.57). This is the written into the yarn.lock file. However, when I rolled it back, I changed RN types to v0.55. But yarn it just kept the association of v* to v0.57

**Comment by uqmessias** [comment]
I had the same issue — but with another identifier — and what solved for me was adding the resolution for `react` with a fixed version on my `package.json`.

```json
{
  "resolutions": {
    "@types/react": "^16.8.1"
  }
}
```

**Comment by truongngoctuan** [comment]
in my case, I removed yarn.lock and run `yarn` again, then it interpolate `@types/react-native@*` correctly and show `"@types/react-native@*", "@types/react-native@my-react-native-version":`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
