### ISSUE TITLE
[@types/rc-tooltip] Type 'string' is not assignable to type 'Trigger[] | undefined'.

### ISSUE THREAD

**Issue by chandelabhishek** [DefinitelyTyped/DefinitelyTyped#30030]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/rc-tooltip` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @rhysd @ahstro 

Created a PR already

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
