### ISSUE TITLE
[react-table] Test is using non-existing field

### ISSUE THREAD

**Issue by andys8** [DefinitelyTyped/DefinitelyTyped#30091]
The test is using a field `status` that is not existing on the data.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/974c1201275fc409316a86bd2a75bc7bd950657a/types/react-table/react-table-tests.tsx#L20

This is a good show case to improve the typings instead. But having strings as accessors will be hard because there is specific syntax allowed to access nested values. 

Minimum would be to change the test to reduce confusion.

Ping @rbuckton ;)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
