### ISSUE TITLE
Finding new type def for SIP.js 11.*  sessionDescriptionHandlerFactoryOptions

### ISSUE THREAD

**Issue by bezbahadori** [DefinitelyTyped/DefinitelyTyped#30123]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  -Authors: @Igorbek @Igmat @Lavoaster @andy-ms 
 
How can I find the more recent updated, version of type definition for SIP.JS 
Currently , What is the type definition of sessionDescriptionHandlerFactoryOptions

https://groups.google.com/forum/#!topic/sip_js/sahB8famQ88

If you do not mention the authors the issue will be ignored.

**Comment by Igorbek** [comment]
This is what we currently have in DT:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8390a8052b05217075b215a98a82b3daa1b408b6/types/sip.js/index.d.ts#L1-L5

The correct author to mention was @decyrus

**Comment by bezbahadori** [comment]
@Igorbek  thank you for the update. I am making changes to the file you have mentioned. Ill send PR to you guys, for updated typescripts of sipjs type def

**Comment by Ccz-Chen** [comment]
Any update for making the type definition of SIP.js 0.11?

**Comment by nud** [comment]
FYI SIP.js 0.12 contains typescript type definitions so using `@types/sip.js` is not required anymore.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
