### ISSUE TITLE
js-yaml incorrect type for: Type.predicate

### ISSUE THREAD

**Issue by vrachels** [DefinitelyTyped/DefinitelyTyped#30125]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/js-yaml` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Bartvds @sclausen 

it looks like Type.predicate should be a function, not a string

https://github.com/nodeca/js-yaml/search?q=predicate&unscoped_q=predicate

**Comment by sclausen** [comment]
Yeah it seems you're right. I look forward to review your pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
