### ISSUE TITLE
[lingui/core] Missing params in setupI18n

### ISSUE THREAD

**Issue by andys8** [DefinitelyTyped/DefinitelyTyped#30136]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/lingui__core/i18n.d.ts#L26-L30

## Missing

https://lingui.js.org/ref/core.html?highlight=language#options.missing
https://lingui.js.org/ref/core.html?highlight=language#options.locales

## Fix

```ts
export interface setupI18nProps {
    language?: string;
    catalogs?: Catalogs;
    development?: object;
    locales?: string[];
    missing?: string | ((language: string, id: string) => string);
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
