### ISSUE TITLE
Koa assert should play nice with --strictNullChecks

### ISSUE THREAD

**Issue by vsviridov** [DefinitelyTyped/DefinitelyTyped#30191]
- [X] I tried using the `@types/koa` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Authors: @DavidCai1993 @jkeylu @brikou 

Currently doing something like this produces an error
```javascript
const item = await getSomeItem();

ctx.assert(item, 404, 'Not found');

ctx.body = item.propery; // 2532: Object is possibly 'undefined'.
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
