### ISSUE TITLE
Export of sanctuary interface types

### ISSUE THREAD

**Issue by robations** [DefinitelyTyped/DefinitelyTyped#30200]
Is there a way to allow exporting the interfaces in this package?

I expected to be able to write the following:

```typescript
import {Maybe, Just} from "sanctuary";

const x: Maybe<number> = Just(1); // TS2304: Cannot find name 'Maybe'.
```

but anything that is an interface doesn't register as a value on the exported namespace. I actually thought I might be able to import the whole namespace as a workaround, but I'm getting a different error:

```typescript
import * as S from "sanctuary"; // TS2503: Cannot find namespace 'S'.

const x: S.Maybe<number> = S.Just(1);
```

Tested with typescript v2 and v3.

---
- [x] I tried using the `@types/sanctuary` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @davidchambers @cortopy @piq9117

**Comment by davidchambers** [comment]
Thanks for opening this issue, @robations.

Let me preface my answer with some caveats:

  - I'm not a TypeScript user;
  - the current type definitions apply to `sanctuary@0.14.x` rather than to `sanctuary@0.15.x`; and
  - [`S.Maybe`][1] is not an interface.

This works for me (with `sanctuary@0.14.x`):

```typescript
import * as S from 'sanctuary';

interface Maybe<A> {
  constructor: {
    '@@type': 'sanctuary/Maybe';
  };
}

const x: Maybe<number> = S.Just (1);
```

It's clearly not ideal to duplicate the interface definition. Can one export interface definitions? If so, do they have their own namespace, or would the interface conflict with the existing `Maybe` export?


[1]: https://github.com/sanctuary-js/sanctuary/tree/v0.14.1#user-content-Maybe

**Comment by davidchambers** [comment]
It's worth noting that the existing `Maybe<A>` interface ignores `A`, so `Maybe<number>` is aspirational.

**Comment by robations** [comment]
Generally, you can export an interface directly from a module by adding `export` before the definition. I admit I don't know how this would play with different module systems, will need to look closer to understand what's going on here:

```
declare var S: sanctuary.Environment;
export = S;
export as namespace S;

...

declare namespace Sanctuary {
  interface Static {
...
```

But I take your point about `A` being ignored.

**Comment by davidchambers** [comment]
I experimented and found a possible solution: moving the interface definitions to a separate file.

__node_modules/@types/sanctuary/interfaces.d.ts__

```typescript
export interface Maybe<A> {
  constructor: {
    '@@type': 'sanctuary/Maybe';
  };
}

...
```

__node_modules/@types/sanctuary/index.d.ts__

```typescript
import {Maybe, ...} from './interfaces';

declare var S: Sanctuary.Environment;
export = S;
export as namespace S;

...
```

__my-app.ts__

```typescript
import * as S from 'sanctuary';
import {Maybe} from 'sanctuary/interfaces';

const x: Maybe<number> = S.Just (1);
```

I don't know much about TypeScript, so I don't know whether this is a reasonable approach. Is it?

**Comment by robations** [comment]
I *think* that should work (not really much personal experience with adding types to non-TS packages). There are some notes here that suggest this is a valid approach:

https://definitelytyped.org/guides/best-practices.html#ghost-modules

**Comment by cdbkr** [comment]
I have run into the same issue and I agree, it would be great to rely on something like mentioned above. What's the plan for this implementation? Or, is there any alternative solution for TS 2.x and 3.x?

**Comment by elie222** [comment]
This may work better for you: https://gist.github.com/elie222/e34a6ef6b818822bda17d0bebfff5c7c

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
