### ISSUE TITLE
@types/knex enum postgresql

### ISSUE THREAD

**Issue by deelienardy** [DefinitelyTyped/DefinitelyTyped#30213]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d9812c650ac48ddb804891dfd7f672c1e0afaff4/types/knex/index.d.ts#L447

i found this part don't have part options
on knex documents, it has options for postgres 
e.g
table.enu('column', ['value1', 'value2'], { useNative: true, enumName: 'foo_type' })

can someone help me?

**Comment by taybin** [comment]
This can be closed as knex provides its own definitions now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
