### ISSUE TITLE
next-redux-saga types

### ISSUE THREAD

**Issue by IvanGrimes** [DefinitelyTyped/DefinitelyTyped#30257]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

@leocavalcante 
Hello, I have an issue with using this types for next-redux-saga.
I think this should have export default of this function like in this code, otherwise I got error from typescript like this module has no export default or has no exported member "nextReduxSaga".
Could you please add default export?
I will very appreciate to you.
Thanks.

**Comment by leocavalcante** [comment]
Hi @IvanGrimes 
Can you given more details around your project?
Can you create a minimal setup showing this error? It is reproducible?
It seams already on tests about default exporting...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
