### ISSUE TITLE
@types/pdfkit PDFDocument.registerFont does not accept Buffer in the second parameter

### ISSUE THREAD

**Issue by lwchkg** [DefinitelyTyped/DefinitelyTyped#30262]
If you know how to fix the issue, make a pull request instead.

- [*] I tried using the `@types/xxxx` package and had problems.
- [*] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [*] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @erichillah  

As title. Here's the offending code (I've shortened the code, so don't try to run it :-( ):
```ts

export class PDFProblemSetGenerator {
  private _doc: PDFKit.PDFDocument;
  private _font: FontWithMetrics;

  public constructor(
    writeStream: NodeJS.WritableStream,
    options: PDFProblemSetGeneratorOptionsPartial
  ) {
    // Code for this._doc omitted.
    this._font = {
      name: "Liberation Sans",
      data: fs.readFileSync(
        path.join(__dirname, "../assets/LiberationSans-Regular.ttf")
      );
    // @ts-ignore: this._font.data is wrongly expected to be a string.
    this._doc.registerFont(this._font.name, this._font.data);
  }
}
```

Excerpt of https://github.com/foliojs/pdfkit/blob/master/docs/text.coffee.md, which shows that `Buffer` is accepted:

> To change the font used to render text, just call the `font` method. If you
> are using a standard PDF font, just pass the name to the `font` method.
> Otherwise, pass the path to the font file, or a `Buffer` containing the font data.
> If the font is a collection font (`.ttc` and `.dfont` files), meaning that it
> contains multiple styles in the same file, you should pass the name of the style
> to be extracted from the collection.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
