### ISSUE TITLE
JQueryCallback should be paramaterised over the type

### ISSUE THREAD

**Issue by singpolyma** [DefinitelyTyped/DefinitelyTyped#3036]
`JQueryCallback` currently allows any sort of callback function to be added, would be nice if it said `JQueryCallback<T>` and then callback functions would all take an argument of that type, or similar.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
