### ISSUE TITLE
Snoowrap Subreddit.d.ts uses ReadableStream which cannot be found

### ISSUE THREAD

**Issue by Lopierdis** [DefinitelyTyped/DefinitelyTyped#30375]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/snoowrap` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @vitosamson @TheAppleFreak 

If you do not mention the authors the issue will be ignored.
[Inside the Subreddit.d.ts there is an interface called ImageUploadOptions, it has a file member that uses ReadableStream.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/snoowrap/dist/objects/Subreddit.d.ts#L214)
When trying to transpile it says an error about not being able to find ReadableStream.
A possible solution would be to use NodeJS.ReadableStream, but it seems a bit hacky, I am rather new to the subject and wondered if there might be a better solution.

**Comment by Dickurt** [comment]
Experiencing this problem as well.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
