### ISSUE TITLE
[react-table] SortingRule object is incorrect

### ISSUE THREAD

**Issue by AcostaB** [DefinitelyTyped/DefinitelyTyped#30385]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @royxue @psakalo @Havret

If you do not mention the authors the issue will be ignored.

---

The SortingRule type seems to be incorrect. The definition file has it as: 
```
export interface SortingRule {
    id: string;
    sort?: 'desc' | 'asc';
    asc?: true;
    desc?: true;
}
```
But the "sortedChangeFunction" and "sorted" props, which use SortingRule[], seem to actually work with an object of this structure: 
```
{
id: string,
desc?: boolean
}
``` 
If I am correct and this is a mistake, I can try making a PR myself. Thanks.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
