### ISSUE TITLE
[Material UI] Improper type definition for Material UI Tab component

### ISSUE THREAD

**Issue by Moondancer83** [DefinitelyTyped/DefinitelyTyped#30391]
Tab from '@material-ui/core/Tab' should accept its "component's" properties in addition to the own properties.

Example:
When using with React Router the JS version works like this:
`<Tab label="Facebook" component={Link} to="/facebook" />`
However, the TS compiler throws error like
`Tab from material UI doesn't have property to`

**Comment by Moondancer83** [comment]
see: [https://github.com/mui-org/material-ui/issues/8313](url)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
