### ISSUE TITLE
[@types/react] React.Fragment errors

### ISSUE THREAD

**Issue by IljaDaderko** [DefinitelyTyped/DefinitelyTyped#30435]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Asana, @AssureSign, @Microsoft, @johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @morcerf, @tkrotoff, @DovydasNavickas, @onigoetz, @theruther4d, @guilhermehubner, @ferdaber, @jrakotoharisoa, @pascaloliv, @Hotell, @franklixuefei

After updating to v16.7.2 I started receiving error below whenever I use fragment like this

```js
import * as React from "react"

<React.Fragment>
...
```

> [ts]
> JSX element type 'ReactElement<any> | null' is not a constructor function for JSX elements.
>   Type 'null' is not assignable to type 'ElementClass'.
> const React.Fragment: React.ExoticComponent<{
>     children?: React.ReactNode;
> }>
>

**Comment by FredyC** [comment]
See discussion here ... https://github.com/DefinitelyTyped/DefinitelyTyped/commit/9039892f8ea3823b0a37d2b9764ba413a9eb6aa9

**Comment by IljaDaderko** [comment]
@FredyC I'm having trouble to understand how it should be used still, is it only usable via `<> </>` now and no longer supports extended versions like

```
<React.Fragment>
<Fragment>
...
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
