### ISSUE TITLE
isResult parameter is missing on querySync() definitions

### ISSUE THREAD

**Issue by LsKoder** [DefinitelyTyped/DefinitelyTyped#30489]
* Bug Description
As described into querySync() [documentation](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#user-content-querySyncApi), the method could be invoked passing the following object:
Other included bug: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30355

> The SQL query to be executed or an Object in the form {"sql": sqlQuery, "params":bindingParameters, "noResults": noResultValue}. noResults accepts only true or false values. If true - query() will not return any result. "sql" field is mandatory in Object, others are optional.

* Actual **Wrong** declaration
`querySync(query: string | {sql: string, params: any[]}, params?: any[]): any[];`

* Solution
The method declaration should be as following:
`querySync(query: string | {sql: string, params?: any[], noResults?: boolean}): any[] | any;`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
