### ISSUE TITLE
Missing `resource` property in parameter to `MessagesResource.send`

### ISSUE THREAD

**Issue by jsalvata** [DefinitelyTyped/DefinitelyTyped#30492]
- [x] I tried using the `@types/gapi.client.gmail` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Bolisov 

After fixing #30491, trying to compile this code:

```
gapi.client.gmail.users.messages.send({ 'userId': 'me', 'resource': { 'raw': Base64.encodeURI(rawMessage) } })
```

throws:

```
ERROR in ...: error TS2345: Argument of type '{ 'userId': string; 'resource': { 'raw': string; }; }' is not assignable to parameter of type '{ alt?: string | undefined; fields?: string | undefined; key?: string | undefined; oauth_token?: ...'.
  Object literal may only specify known properties, and ''resource'' does not exist in type '{ alt?: string | undefined; fields?: string | undefined; key?: string | undefined; oauth_token?: ...'.
```

this is because of the `resource` attribute in the `request` parameter, which is required as per 
[Google's GMail API documentation](https://developers.google.com/gmail/api/v1/reference/users/messages/send), is not declared in `@types/gapi.client.gmail/index.d.ts`.

**Comment by lucka-me** [comment]
Maybe you can try to generate the code with the maintained fork [https://github.com/Maxim-Mazurok/google-api-typings-generator](https://github.com/Maxim-Mazurok/google-api-typings-generator) and test the code in your project, if it works correctly, please consider to make a PR to fix it for all.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
