### ISSUE TITLE
[types/auth0-js] Where is PasswordlessAuthOptions used, etc?

### ISSUE THREAD

**Issue by hrstoyanov** [DefinitelyTyped/DefinitelyTyped#30537]
@adrianchia @mdurrant @peterblazejewicz

1. Any plans for v9 ?

2. Where is PasswordlessAuthOptions used?

3. Can you provide  a common base class for AuthOption and AuthorizationOption, like (Java) : 

```
@JsType
public class BaseAuthOptions {
    public String domain;
    public String clientID;
    public String responseType;
    public ResponseMode responseMode;
    public String redirectUri;
    public String scope;
    public String audience;
}

@JsType
public class AuthOptions extends BaseAuthOptions {
    public int leeway;
    public Any[] plugins;
    public boolean _disableDeprecationWarnings;
    public boolean _sendTelemetry;
    public Any _telemetryInfo;
}

@JsType
public class AuthorizeOptions extends BaseAuthOptions {

    public String connection;
    public String state;
    public String nonce;
    public boolean owp;
    public int leeway;
    public Any[] plugins;
    public boolean _disableDeprecationWarnings;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
