### ISSUE TITLE
cheerio.xml function expects an argument of type DOM

### ISSUE THREAD

**Issue by riteshksriv** [DefinitelyTyped/DefinitelyTyped#30542]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/dbfa83b85e5425713a9dc1e3ae5c36789a551310/types/cheerio/index.d.ts#L237

In the index.d.ts, the xml function signature incorrectly mentions zero argument.

**Comment by AzSiAz** [comment]
Might do it 
But if someone is interested here is where you can see the arg for xml function
https://github.com/cheeriojs/cheerio/blob/master/lib/static.js#L98

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
