### ISSUE TITLE
[@types/chart.js] Property 'elements' does not exist on type 'typeof Chart'

### ISSUE THREAD

**Issue by nwinger** [DefinitelyTyped/DefinitelyTyped#30544]
- [x] I tried using the `@types/chart.js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @anuti @FabienLavocat @KentarouTakeda @larrybahr @mernen @josefpaij

Trying to create rounded bars, as seen here: https://codepen.io/jedtrow/pen/ygRYgo
The property `elements` seems to be missing from the definitions file, as the code runs fine but Typescript is complaining.

**Comment by phea** [comment]
+1.

**Comment by rahulcse1** [comment]
Even i am facing the same problem after upgrading my chart plugin.

**Comment by mateusmatinato** [comment]
Has anyone managed to solve?

**Comment by qqhann** [comment]
Same here.

**Comment by KentarouTakeda** [comment]
I think the following method is better.

```
const element = document.getElementById('some-id');
if(element instanceof HTMLCanvasElement) {
    new Chart(element, {});
}
```

or

```
const element = document.getElementById('some-id') as HTMLCanvasElement;
new Chart(element, {});
```
chart.js does not support all `HTMLElements`, only `HTMLCanvasElement` can be specified. If an Element that is not a Canvas is specified, the operation will be the same as when an invalid value (e.g. `null` or `undefined`) is specified.

Therefore, rather than expanding the input range on the type definition side, it may be a safer program to narrow the input side.

**Comment by sorenfruergaard** [comment]
Use Chart['elements'] instead of Chart.elements

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
