### ISSUE TITLE
Ui router has breakable change in UrlMatcher

### ISSUE THREAD

**Issue by Xrew** [DefinitelyTyped/DefinitelyTyped#3062]
Hi! In new version of ui-router 0.2.11 is breakable change with params. Chenge log is here
https://github.com/angular-ui/ui-router/blob/master/CHANGELOG.md

Problem is, that the signature of params in ng.ui.IState has changed from []any to {}. 
Please fix this issue to next version. Just change in ng.ui.IState from 

  interface IState {
        name?: string;
        template?: any;
        templateUrl?: any;
        templateProvider?: any;
        controller?: any;
        controllerAs?: string;
        controllerProvider?: any;
        resolve?: {};
        url?: string;
        params?:  any[];
        views?: {};
        abstract?: boolean;
        onEnter?: any;
        onExit?: any;
        data?: any;
        reloadOnSearch?: boolean;
    }

to 

  interface IState {
        name?: string;
        template?: any;
        templateUrl?: any;
        templateProvider?: any;
        controller?: any;
        controllerAs?: string;
        controllerProvider?: any;
        resolve?: {};
        url?: string;
        params?: {};
        views?: {};
        abstract?: boolean;
        onEnter?: any;
        onExit?: any;
        data?: any;
        reloadOnSearch?: boolean;
    }

Thanks :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
