### ISSUE TITLE
Pino LoggerOptions is missing Redact feature

### ISSUE THREAD

**Issue by ranyefet** [DefinitelyTyped/DefinitelyTyped#30631]
- [x] I tried using the `@types/pino` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @psnider @bendingBender @screendriver @alferpal

I'm trying to use redact feature of Pino and getting an error that it's not a valid type
http://getpino.io/#/docs/redaction

Please update the definition file to support that feature

Thanks,
Ran

**Comment by mcollina** [comment]
+1

**Comment by alferpal** [comment]
I'll take a look at this in a few hours if nobody's done it first

**Comment by ranyefet** [comment]
Wow! that was super fast! @alferpal Thank you!

**Comment by alferpal** [comment]
A new version of @types/pino has been released containing the requested change.

Can you test it and see if it works for you?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
