### ISSUE TITLE
[@types/twitter] collides with npm package

### ISSUE THREAD

**Issue by BendingBender** [DefinitelyTyped/DefinitelyTyped#30635]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @chitoku-k 

The name `twitter` is used by an [npm package](https://www.npmjs.com/package/twitter). The types currently describe the twitter for web types (https://developer.twitter.com/en/docs/twitter-for-websites/overview) and I'm not sure whether they are relevant at all any more. There is already a bug report, that these types don't work here: #28002. Thus I'd like to rename this package to something else (`twitter-for-web` is free atm) and create types for the `twitter` lib on npm.

Is there a process I need to follow to achieve this? @andy-ms: Sorry for bugging you, I was not sure who to ask about this and found nothing in the readme.

**Comment by chitoku-k** [comment]
Thank you for letting me know this package has naming collision with the npm package. I think it is acceptable to remame `@types/twitter` to something like `twitter-for-web` because this has not been related to `twitter` in npm as you mentioned. And I did not notice #28002 due to **silent** issue without mentioning (I'm happy to look into it later).
