### ISSUE TITLE
Custom function broken

### ISSUE THREAD

**Issue by garora** [DefinitelyTyped/DefinitelyTyped#3063]
I added custom function to jasmine.d.ts  `interface Matchers {..}` as `toHaveClass(expected: any): boolean;` and its implementation to jasmine.js as:

```
jasmine.Matchers.prototype.toHaveClass = function (expected) {
    return this.actual.hasClass(expected);
};
```

Unfortunately, I am getting error `hasClass` is undefined.

Anyway to add custom function, here?

**Comment by zvirja** [comment]
@garora I think this issue is irrelevant anymore, as now it works fine. If so, please close it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
