### ISSUE TITLE
[@types/echarts] error with v4.1.2

### ISSUE THREAD

**Issue by FrontMage** [DefinitelyTyped/DefinitelyTyped#30678]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/echarts` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @xieisabug 

I'm using `@types/echarts v4.1.2` and `echarts v4.2.0`

tcs get errors like
```
[09:12:51] { [TypeScript error: node_modules/_@types_echarts@4.1.2@@types/echarts/index.d.ts(1022,15): Error TS2304: Cannot find name 'SeriesThemeRiver'.]
  message:
   'node_modules/_@types_echarts@4.1.2@@types/echarts/index.d.ts(1022,15): Error TS2304: Cannot find name \'SeriesThemeRiver\'.',
  fileName:
   'node_modules/_@types_echarts@4.1.2@@types/echarts/index.d.ts',
  line: 1022,
  column: 15,
```
switch back to `@types/echarts v4.1.1` solved this.

**Comment by VirensCn** [comment]
我也是保存，没法编译。

**Comment by VirensCn** [comment]
@xieisabug @AntiMoron @liveangela @Ovilia

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
