### ISSUE TITLE
[@types/gestalt] Correctly handle React 16.3 refs

### ISSUE THREAD

**Issue by ermik** [DefinitelyTyped/DefinitelyTyped#30673]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @serranoarevalo

Example: Currently `Flyover` component expects `anchor` of type `React.RefObject<T>` while under the hood `gestalt` calls
```js
 anchor.getBoundingClientRect();
```
because it worked with React Refs v1 and those pointed directly to `HTMLElement`

**Comment by serranoarevalo** [comment]
PRs Welcome!!💖💖

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
