### ISSUE TITLE
disablePictureInPicture

### ISSUE THREAD

**Issue by pureZjr** [DefinitelyTyped/DefinitelyTyped#30682]
video target haven't 'disablePictureInPicture' props

**Comment by wkoncki** [comment]
To expands some more on @pureZjr somewhat cryptic report: video.js typings miss picture in picture property. To be precise videojs.ControlBarOptions is missing 'pictureInPictureToggle'. Currently this code returns typing error while being a correct vjs config
```
videojs('video-container', {
      fluid: true,
      muted: false,
      liveui: true,
      controlBar: {
        pictureInPictureToggle: true,
      },
    });
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
