### ISSUE TITLE
[@types/stripe] Stripe.sources is not defined in the types

### ISSUE THREAD

**Issue by justinglibert** [DefinitelyTyped/DefinitelyTyped#30692]
- [X ] I tried using the `@types/xxxx` package and had problems.
- [X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wjohnsto @CodeAnimal @sampsonjoliver @LinusU @brannon @kkamperschroer 

The types do not include stripe.sources which is definitely present in the api

**Comment by bakeruk** [comment]
+ 1 WTF people! Why would you leave this out!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
