### ISSUE TITLE
@types/bull lockKey is a string

### ISSUE THREAD

**Issue by moltar** [DefinitelyTyped/DefinitelyTyped#30709]
https://github.com/OptimalBits/bull/blob/9ea172098babb5c01e749c57953e9a4d1fc4bc68/lib/job.js#L90

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/28e745f92dfa682e673a012d23ed0b4950d27d27/types/bull/index.d.ts#L184

**Comment by nkprince007** [comment]
@moltar what is your problem with that? I see that it's matching the type correctly.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
