### ISSUE TITLE
How to use typesVersion in DT?

### ISSUE THREAD

**Issue by Jessidhia** [DefinitelyTyped/DefinitelyTyped#30711]
The FAQ in the repository root only tells you to bump the `// TypeScript Version` value, but that is incorrect for anything above TS 3.0. There is a linter rule that catches you if you do that and tells you to use `typesVersion` instead, but I can't find documentation on how to do it.

Also...... what is the plan for maintaining types for older TS versions? I suspect most people engaged enough to be maintainers here will be keeping up with current or even next instead of going back to check if the TS 3.0 types still work. However, requiring all type versions be updated will just create a combinatorial explosion as more and more TS versions are released.

**Comment by BendingBender** [comment]
I've added a [section in the FAQ](https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-use-features-from-typescript-31-or-above) on how to do it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
