### ISSUE TITLE
 @types/mongoose  - Schema.path() does not contain discriminator

### ISSUE THREAD

**Issue by relief-melone** [DefinitelyTyped/DefinitelyTyped#30714]
I am at the moment using the discriminator in mongoose on a Schema.path() which returns SchemaType.
This is how it should work

```
var eventSchema = new Schema({ message: String },
  { discriminatorKey: 'kind', _id: false });

var batchSchema = new Schema({ events: [eventSchema] });
batchSchema.path('events').discriminator('Clicked', new Schema({
  element: String
}, { _id: false }));
batchSchema.path('events').discriminator('Purchased', new Schema({
  product: String
}, { _id: false }));
```

However it works just like this

```
var eventSchema = new Schema({ message: String },
  { discriminatorKey: 'kind', _id: false });

var batchSchema = new Schema({ events: [eventSchema] });
const batchPath = batchSchema.path('events') as any;
batchPath .discriminator('Clicked', new Schema({
  element: String
}, { _id: false }));
batchPath .discriminator('Purchased', new Schema({
  product: String
}, { _id: false }));
```

I guess its just missing in the types definition. Current versions are

TypeScript: 3.1.6
Mongoose: 5.3.13
@types/mongoose: 5.3.1 (Authors @horiuchi @sindrenm @lukasz-zak @Alorel )

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by ealtuna** [comment]
I am running over the same issue, discriminator is missing.

**Comment by emmanuelgautier** [comment]
Not sure to understand with @relief-melone code example. According mongoose [documentation](https://mongoosejs.com/docs/discriminators.html) and [code](https://github.com/Automattic/mongoose/blob/master/lib/model.js#L990), `discriminator` method is attached to model.

**Comment by qqilihq** [comment]
I'm missing these as well and look forward to a fix.

@emmanuelgautier There's a `discriminator` function for embedded documents in arrays as well:
* https://mongoosejs.com/docs/discriminators.html#embedded-discriminators-in-arrays
* http://thecodebarbarian.com/mongoose-4.8-embedded-discriminators

**Comment by emmanuelgautier** [comment]
@qqilihq The PR was automaticaly closed because of inactivity. 

According mongoose [code,](https://github.com/Automattic/mongoose/blob/master/lib/schema/documentarray.js#L125) `discriminator` is attached to `DocumentArray` not `SchemaType` in this examples. Please make another PR with the discriminator on `DocumentArray` type instead.

**Comment by qqilihq** [comment]
@emmanuelgautier Thanks for the clarification. I created a new PR.

**Comment by qqilihq** [comment]
My PR above was merged, so I feel this can be closed.

My usage:

```
const itemArrayType = schema.path('items') as mongoose.Schema.Types.DocumentArray;
itemArrayType.discriminator('foo', new mongoose.Schema({ … }));
itemArrayType.discriminator('bar', new mongoose.Schema({ … }));
itemArrayType.discriminator('baz', new mongoose.Schema({ … }));
```

**Comment by bbhopesh** [comment]
@qqilihq If it isn't too much work for you, can you please add a type for embedded documents as well? e.g. if `events` was an object instead of array in example above. 
```
var batchSchema = new Schema({ events: eventSchema });
```

I have checked and Mongoose does support it. See `SingleNestedPath` in mongoose. Also see this https://thecodebarbarian.com/mongoose-4.12-single-embedded-discriminators.html

I don't mean to put off work on you but I have never contributed to this repo and I don't have time to get everything setup right now.

**Comment by qqilihq** [comment]
@bbhopesh I currently do not have time to do this myself, but this shouldn't be a biggie and a good opportunity to get into DT. 

Just have a look at my change set back then: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33014/files

Happy to review your PR.

**Comment by bbhopesh** [comment]
Okay.. I will do it when as I get some time. I will have to add a new class though because there is no typescript class for SingleNestedPath today.

**Comment by Rush** [comment]
So is it possible to use discriminators with typescript and mongoose?

**Comment by himalayaahuja** [comment]
@bbhopesh Is it done then?  Wanted to use it in NestSJs with mongoose..

**Comment by ValYouW** [comment]
@qqilihq What do you think about [this](https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...ValYouW:mongoose-SingleNestedPath) attempt? I am not familiar with the dt syntax... The big change is that `Schema.path()` returns `SingleNestedPath` instead of `SchemaType` (where `SingleNestedPath extends SchemaType` (which seems to be the case per [code](https://github.com/Automattic/mongoose/blob/5.10.13/lib/schema/SingleNestedPath.js#L50))

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
