### ISSUE TITLE
[@types/seamless-immutable] MergeConfig should have a `mode` property

### ISSUE THREAD

**Issue by llchan** [DefinitelyTyped/DefinitelyTyped#30729]
```
interface MergeConfig {
    deep?: boolean;
    merger?(a: any, b: any, config: any): any;
}
```

`MergeConfig` has another property `mode?: "merge" | "replace"` (defaults to "merge" internally if undefined).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/seamless-immutable` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alex3165 @xsburg @geirsagberg @RMHonor

If you do not mention the authors the issue will be ignored.

**Comment by llchan** [comment]
Yeah, it seems to be undocumented. Filed https://github.com/rtfeldman/seamless-immutable/issues/264. Thanks for adding types here :+1:

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
