### ISSUE TITLE
EventEmitter2 declared in the wrong module for people not using AMD or CommonJS?

### ISSUE THREAD

**Issue by kajmagnus** [DefinitelyTyped/DefinitelyTyped#3075]
Hi,

How do I use the recently added module  [EventEmitter2](https://github.com/asyncly/EventEmitter2) if I'm not using AMD or CommonJS? EventEmitter2 then declares a global variable, `window.EventEmitter2` (on [this line](https://github.com/asyncly/EventEmitter2/blob/master/lib/eventemitter2.js#L591)), but the TypeScript definitions declares class EventEmitter in module `eventemitter2` ([source code](https://github.com/borisyankov/DefinitelyTyped/blob/master/eventemitter2/eventemitter2.d.ts)).

If I in my TypeScript file use `eventemitter2.EventEmitter2`, then compilation works but the program fails at runtime because there is no `eventemitter2.EventEmitter2` (only a `window.EventEmitter2`). If I in my TypeScript file use `EventEmitter2`, then compilation fails.

I also tested this: (not sure if extending a `var` ought to work though)

```
var EventEmitter2: eventemitter2.EventEmitter2 = window['EventEmitter2'];

export class ReactStore extends EventEmitter2 {
   ...
```

But the TypeScript transpiler then says `error TS2095: Could not find symbol 'EventEmitter2'`.

Best regards, KajMagnus

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
