### ISSUE TITLE
Compilation errors with @types/jquery 3.3.22

### ISSUE THREAD

**Issue by anhallbe** [DefinitelyTyped/DefinitelyTyped#30765]
- [ x ] I tried using the `@types/jquery` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (3.1.6)
- [ x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu @borisyankov @Steve-Fenton @Diullei @tasoili @jasonswearingen @seanski @Guuz @ksummerlin @basarat @nwolverson @derekcicerone @AndrewGaspar @seikichi @benjaminjackman @JoshStrobl @johnnyreilly @DickvdBrink @King2500 @terrymun 

I'm getting multiple errors when building a project that depends on @types/jquery@3.3.22, using TypeScript 3.1.6:

```

node_modules/@types/jquery/JQuery.d.ts:6356:141 - error TS2344: Type 'TReturn' does not satisfy the constraint 'Node'.

6356     map<TReturn>(callback: (this: TElement, index: number, domElement: TElement) => JQuery.TypeOrArray<TReturn> | null | undefined): JQuery<TReturn>;
                                                                                                                                                 ~~~~~~~

node_modules/@types/jquery/JQueryStatic.d.ts:172:27 - error TS2344: Type 'T' does not satisfy the constraint 'Node'.

172     <T>(selection: JQuery<T>): JQuery<T>;
                              ~

node_modules/@types/jquery/JQueryStatic.d.ts:172:39 - error TS2344: Type 'T' does not satisfy the constraint 'Node'.

172     <T>(selection: JQuery<T>): JQuery<T>;
                                          ~

node_modules/@types/jquery/JQueryStatic.d.ts:192:93 - error TS2344: Type 'TElement' does not satisfy the constraint 'Node'.
192     <TElement = HTMLElement>(callback: ((this: Document, $: JQueryStatic) => void)): JQuery<TElement>;
                                                                                                ~~~~~~~
node_modules/@types/jquery/JQueryStatic.d.ts:199:55 - error TS2344: Type 'T' does not satisfy the constraint 'Node'.
  Type 'PlainObject<any>' is not assignable to type 'Node'.
    Property 'baseURI' is missing in type 'PlainObject<any>'.

199     <T extends JQuery.PlainObject>(object: T): JQuery<T>;
                                                          ~

node_modules/@types/jquery/JQueryStatic.d.ts:206:40 - error TS2344: Type 'TElement' does not satisfy the constraint 'Node'.

206     <TElement = HTMLElement>(): JQuery<TElement>;
                                           ~~~~~~~~
```

**Comment by Kovensky** [comment]
This happens if you have _another_ type that also depends on `@types/jquery` (e.g. `@types/jqueryui`.

This is what is happening on the lockfile:

```
"@types/jquery@*":
  version "1.10.35"
  resolved "https://registry.yarnpkg.com/@types/jquery/-/jquery-1.10.35.tgz#4e5c2b1e5b3bf0b863efb8c5e70081f52e6c9518"
  integrity sha512-SVtqEcudm7yjkTwoRA1gC6CNMhGDdMx4Pg8BPdiqI7bXXdCn1BPmtxgeWYQOgDxrq53/5YTlhq5ULxBEAlWIBg==

"@types/jquery@^3.3.27":
  version "3.3.28"
  resolved "https://registry.yarnpkg.com/@types/jquery/-/jquery-3.3.28.tgz#e4e4e1a72a890b9d5fce34019d961265dd1394c4"
  integrity sha512-6+0asQBU38H5kdoKvxVGE7fY8JREBgQsxONw0na0noV9D3JLN2+odBPKkTvRcLW20xSNiP8BH0nyl+8PcIHYNw==
    "@types/sizzle" "*"

"@types/jqueryui@^1.12.6":
  version "1.12.6"
  resolved "https://registry.yarnpkg.com/@types/jqueryui/-/jqueryui-1.12.6.tgz#71bb4154c11d3d7048264b935965adfc5a6c5a50"
  integrity sha512-lF4aIWtQ3Xbd6J+9WXz/day1pyf39ZMO/KUrigFAuMQ6FFVw2xZBIRCUwA7/CEnab1Bb7b4ko304Lxrp2xw8hQ==
  dependencies:
    "@types/jquery" "*"
```

Basically, because the version of `@types/jquery` currently published under the `latest` tag is `1.10.35`, the `*` resolution is picking it up. If `@types/jqueryui` is then parsed by TS it'll find the other, incompatible `@types/jquery` inside it and load both at the same time. `@types/jqueryui` (and other `@types` packages) should either have no dependency at all, a correctly versioned dependency, or a peerDependency.

Frankly, IMO DT's use of `dependencies` instead of `peerDependencies` is completely wrong. It tells the package manager it's OK to nest and create duplicate installs if the requested version range is different from the one on top, but that just doesn't work with `@types` because they're essentially side effects (for `tsc`) that shouldn't be allowed to run twice.

**Comment by leonard-thieu** [comment]
I can't seem to cause errors myself although it does seem reasonable that there should be (https://github.com/leonard-thieu/DefinitelyTyped-issue-30765/commit/f51bb3a6d0c35fe000897203876f9a6f442e425d).

I imagine this can be worked around with adjustments to the lockfile.

@weswigham @sandersn any thoughts on DefinitelyTyped's policies on this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
