### ISSUE TITLE
[@types/passport-saml] MultiSamlStrategy is missing

### ISSUE THREAD

**Issue by ksamborski** [DefinitelyTyped/DefinitelyTyped#30771]
passport-saml package contains also `multiSamlStrategy.js` file which is mentioned in docs but it is not located under `lib/passport-saml` directory in repo. Current type definitions don't provide anything for that file.

@cjbarth @dassennato Could you take a look at it?

**Comment by cjbarth** [comment]
@ksamborski feel free to add the definitions and I'll have a look at them.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
