### ISSUE TITLE
[@types/react] useRef() should be callable without a parameter

### ISSUE THREAD

**Issue by RoystonS** [DefinitelyTyped/DefinitelyTyped#30780]
I'm not 100% confident regarding what was intended with the current `| null` Mutable vs non-Mutable mechanism in the current React hook `useRef` typings, so I've raised this as an issue rather than attempting a PR.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (Tested with TSC 3.1.6)
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly, @Kovensky

According to the React docs - and several online code examples - `useRef` should be callable without a parameter, but the current types here mandate a parameter.  Obviously if used without a parameter, a generic type parameter would be required, but right now the types mandate an actual parameter.

The React documentation (https://reactjs.org/docs/hooks-faq.html#is-there-something-like-instance-variables) shows that it should be possible to write:
```
const intervalRef = useRef();
```
or more likely, in stronger-typed TS:
```
const intervalRef = useRef<number|undefined>();
```

**Comment by Kovensky** [comment]
The thinking behind making the parameter required was the same as the thinking behind making creatContext's argument required.

Dan said back in the day that even though you technically can not give an argument, you still are supposed to and that the docs having an empty argument list example was an oversight.

--

The thing with the |null is to make it more convenient to use DOM/Component refs, and you will see that all examples of useRef for that purpose have it initialized with null. It's not mutable there because React is the one that should do the mutation, not user code. Explicitly giving null in the generic argument does skip the overload, though.

You could maybe have an overload like `useRef<T = undefined>(): MutableRefObject<T | undefined>` (template default there to stop it from being `{}` by default), but I'd like to hear from @gaearon (or someone else involved) whether that's an intended use pattern or a documentation oversight.

**Comment by RoystonS** [comment]
Cool, you've obviously got your ear closer to the ground than I have - I hadn't heard that the empty arg list docs example was an oversight.  Looking at the _source_, it does look like the parameter isn't optional.

https://github.com/facebook/react/blob/504576306461a5ff339dc99691842f0f35a8bf4c/packages/react/src/ReactHooks.js#L68

**Comment by KubaJastrz** [comment]
This needs to be revisited. It's possible to use `useRef` without initial value and it works just fine. You can even find examples in react docs: https://reactjs.org/docs/hooks-faq.html#is-there-something-like-instance-variables

**Comment by RoystonS** [comment]
"Possible to use", and finding some cases in the wild doesn't mean it's officially supported.  See @Jessidhia's earlier comments about the docs being an oversight.

**Comment by Jessidhia** [comment]
There was a twitter thread about this subject yesterday as well https://twitter.com/dan_abramov/status/1097844767956918274

The conclusion was (again) that it is an oversight.
