### ISSUE TITLE
[@types/joi] multiple issues

### ISSUE THREAD

**Issue by iamchathu** [DefinitelyTyped/DefinitelyTyped#30806]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Bartvds @laurence-myers @cglantschnig 

```
node_modules/@types/joi/index.d.ts:675:19 - error TS2304: Cannot find name 'Iterable'.

675     map(iterable: Iterable<[string | number | boolean | symbol, symbol]> | { [key: string]: symbol }): this;
                      ~~~~~~~~

src/request.schema.ts:1:8 - error TS1192: Module '"/Users/Chathu/Workspace/MyProject/node-project-ts/node_modules/@types/joi/index"' has no default export.

1 import Joi from 'joi';
         ~~~

error Command failed with exit code 2.
```

**Comment by laurence-myers** [comment]
Iterable is provided in the ES2015 typings, make sure you target ES2015 (ES6) or later.

https://github.com/Microsoft/TypeScript/blob/28f8fdaccd78de926722e115157da32a50b77f4a/lib/lib.es2015.iterable.d.ts#L36

As the error states, Joi doesn't have a default export, you need to import it like this:

`import * as Joi from 'joi'`

**Comment by SimonSchick** [comment]
I think this should be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
