### ISSUE TITLE
RxJS: Rx-lite should be separate DefinitelyTyped package

### ISSUE THREAD

**Issue by rikoe** [DefinitelyTyped/DefinitelyTyped#3082]
When I reference the RxJS Definitely Typed package, I currently see the rx and rx-lite definitions intermingled. This doesn't make sense to me.

According to https://github.com/Reactive-Extensions/RxJS, rx-lite is a separate package that contains a subset of Rx-All. Shouldn't there be two DefinitelyTyped packages, one matching Rx-All (or Rx-Main, etc.) and one matching Rx-Lite?

@Igorbek / @carldebilly I am willing to contribute this change if you agree.

**Comment by heycalmdown** [comment]
+1

**Comment by eggers** [comment]
It looks like there is a module `'rx.lite'` now, though I thing it should be `rx-lite`.

See: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ffceea9dd124d277c4597c7bd12930666ec074c5/rx/rx.lite.d.ts#L13

Does that look right to everyone?

**Comment by galuszkak** [comment]
@eggers it's now `rx-lite`. `rx-lite` has it's definitions in DefinitelyTyped so I think this ticket should be closed. :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
