### ISSUE TITLE
getphoto sizing

### ISSUE THREAD

**Issue by HammadZahidAli** [DefinitelyTyped/DefinitelyTyped#30879]
I am successful in getting fb leaderboard  images but i am unable to change the texture size when i convert the texture to spriteframe. 

Code is  here:
that.leaderboardpics[i].spriteFrame = new cc.SpriteFrame(entries[i].getPlayer().getPhoto());

Any clue or help? please

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
