### ISSUE TITLE
react-places-autocomplete types are outdated

### ISSUE THREAD

**Issue by ThomWright** [DefinitelyTyped/DefinitelyTyped#30881]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-places-autocomplete` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @guilhermehubner 

If you do not mention the authors the issue will be ignored.

hibiken/react-places-autocomplete#246 

Version 7 of react-places-autocomplete has been released, and the current types are for version 6.

**Comment by tkrotoff** [comment]
Types are now up to date, see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/90961b6110f9848311859f25b600d9e25e9bd783/types/react-places-autocomplete/index.d.ts
This issue can be closed

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
