### ISSUE TITLE
pouchdb types missing adapter static method

### ISSUE THREAD

**Issue by HarelM** [DefinitelyTyped/DefinitelyTyped#30912]
- [x] I tried using the `@types/pouchdb` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @spaulg @geppy @TobiasBales @kmoe

I'm working with `pouchdb` types, and `worker-pouch` and I'm missing a static method:
`PouchDB.adapter(...)`.

The relevant thread can be found here:
https://github.com/pouchdb-community/worker-pouch/issues/52

The solution until the types will be updated is to use `any`:
```ts
import PouchDB from 'pouchdb-browser';
import WorkerPouch from 'worker-pouch';
...
(<any>PouchDB).adapter('worker', WorkerPouch);
let db = new PouchDB('Test', {adapter: 'worker'});
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
