### ISSUE TITLE
Update @okta/okta-vue for 1.0.7

### ISSUE THREAD

**Issue by mraible** [DefinitelyTyped/DefinitelyTyped#30933]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/okta__okta-vue` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Innovation-Team

I was able to use [@types/okta__okta-vue](https://www.npmjs.com/package/@types/okta__okta-vue) to add Okta authentication to a Vue + TypeScript app. However, I'm not able to get the callback to work after logging in. Maybe this is due to some changes since 1.0.1? 

Here's [the router.ts](https://github.com/oktadeveloper/spring-boot-vue-example/blob/okta/client/src/router.ts) in my project that's not working.

If I'm able to figure this out, I'd be happy to create a PR for the Okta Vue SDK that adds the types natively.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
