### ISSUE TITLE
in @types/ember__array/-private/enumerable.d.ts, some method is missing.

### ISSUE THREAD

**Issue by yezhongqiang** [DefinitelyTyped/DefinitelyTyped#30934]
Authors: @mike-north 

some method is already supported in native javascript array, but this types doesn't include it in the enumerable interface, so Ember Array we are using which depends on it does't have some method either.

I hope some method can be added to be aligned with native javascript array.

Thanks a lot in advance.

**Comment by mike-north** [comment]
> some method is already supported in native javascript array, but this types doesn't include it in the enumerable interface

Please elaborate

**Comment by yezhongqiang** [comment]
Thanks a lot for your reply, it is Array.prototype.some() method, which is supported in native java script array, but not in Enumerable interface in @types/ember__array/-private/enumerable.d.ts.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
