### ISSUE TITLE
[markdown-it] 0.0.7 breaks imports

### ISSUE THREAD

**Issue by srittau** [DefinitelyTyped/DefinitelyTyped#30954]
- [X] I tried using the `@types/markdown` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @plantain-00, @rapropos 

After upgrading `@types/markdown-it` from 0.0.6 to 0.0.7, imports are broken:

```typescript
import MarkdownIt, { Token } from "markdown-it";
md: MarkdownIt.Markdownit;
```

These imports worked under 0.0.6, but using 0.0.7 both the `Token` import, but also `MarkdownIt.MarkdowIt` are marked by Typescript as an error with "Module ... has not exported member '...'."

**Comment by plantain-00** [comment]
Token now from `'markdown-it/lib/token'`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
