### ISSUE TITLE
[@types/bookshelf] Pagination plugin is not defined.

### ISSUE THREAD

**Issue by leak4mk0** [DefinitelyTyped/DefinitelyTyped#30973]
I think we need define of bookshelf plugin.
So, first, I would like to define pagination plugin.

Pagination plugin is included in bookshelf module, however, it's optional.
We must call `bookshelf.plugin('pagination') firstly to use it plugin.
So, I'm worried about including definition of pagination plugin in definition of bookshelf.

I think two plans.
1. add definition of pagination plugin to `@types/bookshelf`
2. create definition of pagination plugin named `@types/bookshelf-pagination`.

2nd plan's source is here:
https://github.com/leak4mk0/DefinitelyTyped/tree/bookshlef-pagination/types/bookshelf-pagination

Which should I do?
Let me know if you have any ideas, please!

_Originally posted by @leak4mk0 in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/6015#issuecomment-443416070_

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
