### ISSUE TITLE
Module '"../../node_modules/@types/expo"' has no exported member 'Icon'.

### ISSUE THREAD

**Issue by xeruf** [DefinitelyTyped/DefinitelyTyped#30980]
- [x] I tried using the `@types/expo` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @KonstantinKai @martynaskadisa @janaagaard75 

`Module '"../../node_modules/@types/expo"' has no exported member 'Icon'.` is reported by TypeScript when i use expo and try to `import { Icon } from 'expo'`. Long explanation here: https://github.com/expo/expo/issues/2867
But this should be pretty self-explainatory, since `Icon` actually exists in expo and the build succeeds if I add a `@ts-ignore`

**Comment by janaagaard75** [comment]
Hi @Xerus2000,

Thanks for reporting this. We unfortunately don't have the resources to keep up to date with all the new and updated packages that the Expo team is adding, so the TypeScript definitions are always a bit behind. The good news is that [first-class support for TypeScript in the Expo SDK](https://github.com/expo/expo/issues/2164) is being added, so hopefully the situation will improve a lot with the next releases of Expo.

Have you looked at `@types/expo__vector-icons`? I doesn't look like the package has the `Icon` component, though, but you might be able to use by writing your code a little different. I have a [proof of concept of how to use the icons here](https://github.com/janaagaard75/expo-and-typescript/blob/master/src/VectorIconsScreen.tsx).

If you can find the time, you are very wellcome to create a pull request to fix this issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
