### ISSUE TITLE
@types/pdfmake's getBase64 and  getBuffer  are not definition

### ISSUE THREAD

**Issue by shinriyo** [DefinitelyTyped/DefinitelyTyped#31011]
If you know how to fix the issue, make a pull request instead.

```
    type GetBase64Function = (
        cb?: string,
        options?: string
    ) => void;

    type GetBase64Params = (
        options?: GetBase64Function
    ) => void;

    interface TCreatedPdf {
        download: CreatedPdfParams;
        open: CreatedPdfParams;
        print: CreatedPdfParams;
        getBase64: GetBase64Params;
        getBuffer: GetBase64Params;
    }
```

I think it can resolve but I have no confidence..

- [o ] I tried using the `@types/pdfmake` package and had problems.
- [ o] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [o ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bpampuch (original branch) @evolkmann (types author)

If you do not mention the authors the issue will be ignored.

**Comment by shinriyo** [comment]
`PageSize` is undefined.

```
import * as pdfMake from 'pdfmake/build/pdfmake';
```

```
pdfMake.PageSize
```
is `undefined`

so. `pdfMake.PageSize.A4` is error.

**Comment by jeralm** [comment]
This should be fixed after my pull request is merged. `pdfmake.PageSize` and `pdfmake.PageOrientation` were declared as `enum`s, which is not accurate to the source library. Declaring an `enum` in TypeScript creates an actual runtime object, but this can't happen if the `enum` is declared in a type definition. pdfMake does not provide any PageSize object of any kind.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
