### ISSUE TITLE
No declaration file for module 'Container'

### ISSUE THREAD

**Issue by sebmaz93** [DefinitelyTyped/DefinitelyTyped#31041]
- [x] I tried using the `@types/react-bootstrap` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] Authors: @vsiao @LKay 

`Type error: Could not find a declaration file for module 'react-bootstrap/lib/Container'. '/Users/sebmaz/Desktop/Workspace/Upwork/minta_back_office/node_modules/react-bootstrap/lib/Container.js' implicitly has an 'any' type.
  If the 'react-bootstrap' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-bootstrap`  TS7016`

**Comment by buren** [comment]
Seeing the same error.

Seems like there are no type definitions for `react-bootstrap` `v1.0.0.beta.X` and `v0.32.4` doesn't have the `Container` component.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
