### ISSUE TITLE
lodash/fp/reject expects string ?

### ISSUE THREAD

**Issue by lfender6445** [DefinitelyTyped/DefinitelyTyped#31064]
- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu 

_________

I am getting an error from TSC when compiling the following code 

```ts
import * as pipe from  'lodash/fp/pipe'
import * as compact from 'lodash/fp/compact'
import * as reject1 from 'lodash/fp/reject'
import * as reject2 from 'lodash/reject'
import * as isEmpty from 'lodash/fp/isEmpty'

const foo = [{
  id: 'bar',
}]

const baz = reject1(isEmpty)(foo) // <-- this produces an error
const bar = reject2(foo, isEmpty)


// pipe(
//   reject(isEmpty)
//   uniqBy('id'),
// )(foo)
```

which produces the error

```
    13  30 error    2345   Argument of type '{ id: string; }[]' is not assignable to parameter of type 'string'. (typescript-tide)
```

I'm wondering if someone could point me in the right direction here, as it appears the type definition for lodash/fp/reject is expecting a string?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
