### ISSUE TITLE
[async@2.0.50] doUntil / doWhilst - AsyncFunctionEx

### ISSUE THREAD

**Issue by viamuli** [DefinitelyTyped/DefinitelyTyped#31098]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/async@2.0.50` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov, @kern0, @Penryn, @fenying, @pascalmartin

Why is it that `doUntil` and `doWhilst` use `AsyncFunctionEx` as type for the iteratee callback parameter and not `AsyncFunction`? Since `AsyncFunctionEx` requires at least one `results` argument, there will always be compile errors when working with `doUntil` which's `iteratee` does not return any kind of result. If there is no real reason why `AsyncFunctionEx` is used, I will make a PR.

Edit:
Even the documentation says that `results` is an optional parameter:
> `callback` will be passed an error and any arguments passed to the final `iteratee`'s callback. Invoked with `(err, [results]);`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
