### ISSUE TITLE
Update types for redux-auth-wrapper

### ISSUE THREAD

**Issue by cwmacdon** [DefinitelyTyped/DefinitelyTyped#31130]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/redux-auth-wrapper` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors.
  - Authors: @LKay 

Incorrect types for `connectedAuthWrapper`.

`connectedAuthWrapper` is defined as:
```typescript
export default function connectedAuthWrapper<OwnProps = {}, State = {}>(
    config: ConnectedAuthWrapperConfig<OwnProps, State>
): AuthWrapperDecorator<OwnProps & InjectedAuthProps>;
```
with `InjectedAuthProps` defined as:
```typescript
export interface InjectedAuthProps {
    isAuthenticated: boolean;
    isAuthenticating: boolean;
}
```

`InjectedAuthProps` should not be on `connectedAuthWrapper` since they are automatically handled by the `connected` part. They should only be on `authWrapper` (see https://mjrussell.github.io/redux-auth-wrapper/docs/Getting-Started/HidingAlternate.html)

I think the return type of `connectedAuthWrapper` should just be `AuthWrapperDecorator<OwnProps>;`

**Comment by cwmacdon** [comment]
It also seems as though `isAuthenticating` should be an optional property of `InjectedAuthProps` for the regular `authWrapper` use case.

**Comment by cwmacdon** [comment]
The same problem exists with `connectedRouterRedirect` and `InjectedAuthRouterProps`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
