### ISSUE TITLE
Update react-redux types for react-redux@6.0

### ISSUE THREAD

**Issue by charrondev** [DefinitelyTyped/DefinitelyTyped#31144]
[react-redux@6.0 is out!](https://github.com/reduxjs/react-redux/releases/tag/v6.0.0). With it there are a few breaking changes.

> The `withRef` option to connect has been replaced with `forwardRef`. If `{forwardRef : true}` has been passed to connect, adding a ref to the connected wrapper component will actually return the instance of the wrapped component. (Known issue: Redux Form currently relies on withRef.)
>
> Passing store as a prop to a connected component is no longer supported. Instead, you may pass a custom `context={MyContext}` prop to both `<Provider>` and `<ConnectedComponent>`. You may also pass `{context : MyContext}` as an option to connect.

I can see a few updates that will need to be made to account for this. I'm willing to make the changes, but I'm wondering what to do about the version number. Will this package keep the types for the previous `react-redux@5.x` (v5)?

## Necessary Changes
- Remove `withRef` prop on options. Do we keep it around with a type of say `never` and add a comment on it? I would surely appreciate that when updating my types, but I'm not sure if that's something commonly done.
- Add `forwardRef` prop and a comment for it.
- Add support for the `context` prop on `InferableComponentEnhancer` and `Provider`.
- This library doesn't seem to have `getWrappedInstance` so it will not need to be removed.

## Repo Checklist
- [x] I tried using the `@types/react-redux` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo, @kenzierocks, @clayne11, @tansongyang, @nicholasboll, @mdibyo, @pdeva, @kallikrein, @val1984, @jrakotoharisoa, @apapirovski, @surgeboris

**Comment by charrondev** [comment]
I forgot to add the mentions when the issue was first created (added them in an edit). So just on the off-chance github doesn't send notifications on edit I'll put them one more time. Apologies for the inconvenience if you get 2 notifications.

**Authors**: @tkqubo, @kenzierocks, @clayne11, @tansongyang, @NicholasBoll, @mDibyo, @pdeva, @Kallikrein, @val1984, @jrakotoharisoa, @apapirovski, @surgeboris

**Comment by Voronar** [comment]
When we work with TypeScript we have to manually declare prop types injected to connected component.
In [this article](https://dev.to/voronar/practical-typescript-react--redux-4enh) I described how to do this work automatically with type inference.
Do you think about what? What about providing this utility type to main typings of react-redux library?

**Comment by charrondev** [comment]
@Voronar That's a very interesting article! I definitely see the utility in it and will play around with the pattern in the next workweek. I would prefer to keep this issue down to the _minimum_ required changes to make the existing type definitions reflect the API of `react-redux@6`. I would recommend you open a separate issue to propose the enhancement of the built in types for the `@types/react-redux`.

**Comment by Voronar** [comment]
@charrondev Thanks for the response.

**Comment by mDibyo** [comment]
IMO this should certainly be a new major version of @types/react-redux (and should remove `withRef`).

@charrondev I am interested in giving this a shot if you didn't want to.

**Comment by kenzierocks** [comment]
`withRef` removal and `forwardRef` addition are in PR #33153.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
