### ISSUE TITLE
[@types/mongoose] missing `Model<T>#watch(pipeline, options)` signature

### ISSUE THREAD

**Issue by malixsys** [DefinitelyTyped/DefinitelyTyped#31220]
- [X] I tried using the @types/mongoose package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for StackOverflow. (Please ask any appropriate questions there).
- [X] Mention the authors (see Definitions by: in index.d.ts) so they can respond.
> Authors: @horiuchi, @sindrenm, @lukasz-zak, @Alorel, @jendrikw, @ethanresnick, @vologab, @jussikinnula, @ondratra, @alfirin, @idandrd, @various89, @RyanCavanaugh

At 
`https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L2796`
a signature for `watch(pipeline, options)` is missing.

c.f. https://mongodb.github.io/node-mongodb-native/3.0/api/Collection.html#watch

**Comment by malixsys** [comment]
Example code that should work but is `TS2554` instead:
```
  getChangeStream() {
    if (query) {
      const pipeline = [{ $match: this.getPipelineMatch() }];
      return collection.watch(pipeline, { fullDocument: 'updateLookup' }); // TS2554
    }
    return collection.watch({ fullDocument: 'updateLookup' }); // this is OK
  }
```

**Comment by dcapaccio** [comment]
Had exactly the same problem, although not sure if it's the same line. The watch signature for interface Model<T … doesn't include pipeline as an argument. At `https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L2817` 

Confirmed that adding "pipeline" as a first argument fixes it and behaves as expected.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
