### ISSUE TITLE
variable declaration clash in gapi.client.cloudiot and gapi.client.pubsub

### ISSUE THREAD

**Issue by smtapp-smtio-cloud** [DefinitelyTyped/DefinitelyTyped#31225]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by smtapp-smtio-cloud** [comment]
node_modules/@types/gapi.client.cloudiot/index.d.ts(19,11): error TS2451: Cannot redeclare block-scoped variable 'projects'.
node_modules/@types/gapi.client.pubsub/index.d.ts(19,11): error TS2451: Cannot redeclare block-scoped variable 'projects'.

It seems that both packages declare variable 'projects' on the same scope (namespace gapi.client).

**Comment by Maxim-Mazurok** [comment]
Hello, can you give the most recent versions of these packages a try?
It should be fixed by the new generator: [Maxim-Mazurok/google-api-typings-generator](https://github.com/Maxim-Mazurok/google-api-typings-generator)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
