### ISSUE TITLE
@types/leaflet.markercluster - MarkerClusterGroupOptions missing clusterPane definition

### ISSUE THREAD

**Issue by ya-mitra** [DefinitelyTyped/DefinitelyTyped#31230]
Type definition for clusterPane is missing from MarkerClusterGroupOptions inside @types/leaflet-markercluster

here's the reference:
https://github.com/Leaflet/Leaflet.markercluster#other-options

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
