### ISSUE TITLE
[@types/react-table]

### ISSUE THREAD

**Issue by will-stone** [DefinitelyTyped/DefinitelyTyped#31261]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @royxue @psakalo @Havret @andys8 @Gelio

Thanks for maintaining the types on React-Table! I've found an issue when trying to use a ref on the selectTable HOC. I get this error:

```
[ts] Property 'ref' does not exist on type 'IntrinsicAttributes & Partial<TableProps<{}>> & SelectTableAdditionalProps & { children?: ReactNode; }'. [2339]
-----------------------------------------------------------------
(property) Tickets.checkboxTableRef: React.RefObject<any>
```

Adding `ref?: React.Ref` to the `SelectTableAdditionalProps` interface fixes it but I'm not sure if this is the correct place for this.

**Comment by Gelio** [comment]
I never considered the issue with using refs on components wrapped in HOCs. Thanks for pointing it out 😄

The issue was with the return type of the HOC. It was `ComponentType`:

```ts
type ComponentType<P = {}> = ComponentClass<P> | FunctionComponent<P>;
```

and because it allows `FunctionComponent`s, which do not have refs by default, refs could not be used. I changed the return type to `ComponentClass` which allows for refs.

The return type now matches exactly what the HOC returns. I attached links relevant code snippets from the `react-table` repo in the PR #31271
