### ISSUE TITLE
[@types/lodash] mapValues and other mapping functions cannot infer the iteratee argument

### ISSUE THREAD

**Issue by bmdalex** [DefinitelyTyped/DefinitelyTyped#31265]
### Description

I tried using the `@types/lodash` (`v4.14.119`) package and had problems.

`mapValues` (and quite possible other mapping functions) cannot infer custom types of the `iteratee` argument (the second one).

### Example

This simple example:

```tsx
import * as _ from 'lodash'

const myMaper = (
  obj: { [key: string]: string },
  mapper: string | ((val: string) => string)
) => {
  return _.mapValues(obj, mapper)
}
```

returns the following type error:

```[ts] Argument of type 'string | ((val: string) => string)' is not assignable to parameter of type 'string'.
Type '(val: string) => string' is not assignable to type 'string'. [2345]
```
![screenshot 2018-12-11 at 16 46 20](https://user-images.githubusercontent.com/5442794/49811817-53d7ab00-fd64-11e8-89c6-9b57e6bd5c89.png)

even though `mapValues` accepts both `string` and iterator function as 2nd argument (`iteratee`):
from: **node_modules/@types/lodash/common/object.d.ts**:
```tsx
// iteratee is string
/**
 * @see _.mapValues
 * TODO: This would be better if we had a separate overload for obj: NumericDictionary that returned a NumericDictionary,
 *       but TypeScript cannot select overload signatures based on number vs string index key type.
 */
mapValues<T>(obj: Dictionary<T> | NumericDictionary<T> | null | undefined, iteratee: string): Dictionary<any>;

// iteratee is iterator function
/**
 * @see _.mapValues
 * TODO: This would be better if we had a separate overload for obj: NumericDictionary that returned a NumericDictionary,
 *       but TypeScript cannot select overload signatures based on number vs string index key type.
 */
mapValues<T, TResult>(obj: Dictionary<T> | NumericDictionary<T> | null | undefined, callback: DictionaryIterator<T, TResult>): Dictionary<TResult>;
```

The only way I could find to fix this (without casting `mapper` to `any`) was to check the types for `mapper` manually. The code below does not throw errors but it's really strange that it's returning the same code on both branches of `if/else`.

```tsx
import * as _ from 'lodash'

const myMaper = (
  obj: { [key: string]: string },
  mapper: string | ((val: string) => string)
) => {
  return typeof mapper === 'string'
    ? _.mapValues(obj, mapper)
    : _.mapValues(obj, mapper)
}
```

**Is this by design? Am I missing something?**

Authors:
@bczengel 
@chrootsu 
@stepancar 
@aj-r 
@Ailrun 
@e-cloud 
@thorn0 
@jtmthf 
@DomiR

**Comment by aj-r** [comment]
It's because the `string` and `DictionaryIterator` types are on separate overloads. TypeScript doesn't let you pass both types in a single function call.

We could probably fix this by adding a third overload:

```
mapValues<T>(obj: Dictionary<T> | NumericDictionary<T> | null | undefined, callback: string | DictionaryIterator<T, any>): Dictionary<any>;
```

I don't have time to do this right now, but if someone can submit a PR, I might review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
