### ISSUE TITLE
Fn add() should return Schema instead

### ISSUE THREAD

**Issue by SteeveFong** [DefinitelyTyped/DefinitelyTyped#31305]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cca60bd5447b1d86d3c296c995c766de7c2ea3d5/types/mongoose/index.d.ts#L750

Right now, using fn `add(): void` returns void which is not what it should be returning. Typescript is prompting compilation error when I tried to create model from a Schema having used `add(): void`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
