### ISSUE TITLE
[@types/knex] return any for await .del(), .update(), .insert()

### ISSUE THREAD

**Issue by muturgan** [DefinitelyTyped/DefinitelyTyped#31356]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/knex@0.15.1` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Qubo, @Pablo Rodríguez, @Matt R. Wilson, @Satana Charuwichitratana, @Shrey Jain, @Joel Shepherd. 

const deletedId = await knex('table').where({id}).del();
typeof deletedId is any (number in fact);

const numberOfUpdatedRows= await knex('table').update({some}).where({id});
typeof numberOfUpdatedRows is any (number in fact);

const insertedIds= await knex('table').insert({some});
typeof insertedIds is any (Array<number> in fact);

**Comment by taybin** [comment]
This can be closed as knex provides its own definitions now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
