### ISSUE TITLE
[@types/lodash] _.assign should be able to be called without parameters

### ISSUE THREAD

**Issue by Semigradsky** [DefinitelyTyped/DefinitelyTyped#31394]
```ts
_.assign(); // {}
//  ^^^
// [ts] Expected at least 1 arguments, but got 0. [2555]
```
It is working code for lodash but not with current typings.

More real world example:
```ts
interface ISomeInterface { }

function doSmth(...args: ISomeInterface[]) {
    return _.assign.apply(_, args);
//                            ^^^
// Argument of type 'ISomeInterface[]' is not assignable to parameter of type '[any, ...any[]]'.
// Property '0' is missing in type 'ISomeInterface[]' but required in type '[any, ...any[]]'. [2345]
}
```

---

Possible solution:

change
```ts
        assign(
            object: any,
            ...otherArgs: any[]
        ): any;
```
to
```ts
        assign(
            ...args: any[]
        ): any;
```
or
```ts
        assign<TResult>(
            ...args: any[]
        ): TResult;
```
@OliverJAsh @aj-r

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
