### ISSUE TITLE
[@types/mathjs] math.concat no type for 3rd parameter

### ISSUE THREAD

**Issue by Luca-Muzi** [DefinitelyTyped/DefinitelyTyped#31406]
Hi there,
there seems to be a type error for the 3rd argument in math.concat. For example when I use math.concat I fail to compile the typescript because of this. I have had to manually edit the mathjs type file to get around this.
To reproduce I did the following:

`const newHiddenWeights = <Matrix>math.concat(newHiddenWeights, this.updateWeights(hiddenWeightVector, labels, features, specificDelta2Vector, learningRate, datasetSize, false), 0);`

A 0 value generates an error. But it is a valid value and needs to be used! Using an undefined does not work the same.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
