### ISSUE TITLE
[@types/web3] sendSignedTransaction/sendTransaction inconsistency with documentation on error 

### ISSUE THREAD

**Issue by darioAnongba** [DefinitelyTyped/DefinitelyTyped#31473]
- [x] I tried using the `@types/web3` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nitzantomer, @simon-jentzsch, @zlumer

Hi,

The documentation here: https://web3js.readthedocs.io/en/1.0/web3-eth.html?highlight=sendSignedTransaction#eth-sendtransaction-return says that on error `sendTransaction` is returning 2 parameters. The first one is the `Error` and the second is the receipt in case of an `out of gas`. 
Using types, there is an error: 
> [ts] Argument of type '(error: any, receipt: any) => Promise<void>' is not assignable to parameter of type '(error: string | TransactionReceipt | Error) => void'. [2345]

There is an inconsistency between types and the documentation.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
