### ISSUE TITLE
[@types/unist] Breaking change for Typescript 2.x published in patch update: `unknown`

### ISSUE THREAD

**Issue by DenisValcke** [DefinitelyTyped/DefinitelyTyped#31470]
- I tried using the `@types/unist` package and had problems.
- I'm using a 2.x version of Typescript because this is an "older" project that requires it.
- Authors: @Rokt33r 

12 days ago the following change was made to the above type mentioned pacakge. It was then published as a patch update but it is a breaking change for Typscript 2.x. It is a change that will only work with Typescript 3.x and higher therefor I assume it to be illogical that such a thing is published as a patch update allowing it to break "older" projects.

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/c5b361c9d1cd5092ec3c4ebb3c946ea1e8cbb5b4#diff-f51238d58ba3ae26ad14a7bb3c2e395e

I cannot fix this through a PR because this is purely due to a poor choice of versioning imho.
version 2.0.0 supports Typescript <= 2.9
version 2.0.2 supports Typescript >= 3.0

**Comment by Rokt33r** [comment]
https://spectrum.chat/unified/type-definitions/typescript-version-s-supported~7c1f6266-6be2-4d0a-b599-4ff93a6d0efd

We're discussing this issue in the above link. Until it fixed, please use specific version for a while.

**Comment by shravan20084312** [comment]
I am using ""@types/node": "8.0.17" for a typescript version 2.5.2. Can you please let me know, which version to be lowered to, so that the issue would not occur?

**Comment by Rokt33r** [comment]
@shravan20084312 It should be `v2.0.1`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
