### ISSUE TITLE
[@types/react] option tag errors with `key` prop

### ISSUE THREAD

**Issue by moog16** [DefinitelyTyped/DefinitelyTyped#31485]
- Authors: @johnnyreilly, @bbenezech 
- Definitions in: `@types/react/index.d.ts`

Getting error 
```js
[ts]
Type 'string | number | null' is not assignable to type 'string | number | undefined'.
  Type 'null' is not assignable to type 'string | number | undefined'.
(JSX attribute) React.Attributes.key?: string | number | undefined
```

This is my interface

```js
interface CustomOption extends React.ReactElement<HTMLOptionElement> {
  label: string;
}

...

renderOption() {
  return (
   <option key={index} {...nonLabelOptionData}> // key throws error
     {label}
   </option>)
}
```

Seems like the prop key is referencing 
```
    interface Attributes {
        key?: Key;
    }
```

While 

```
    interface ReactElement<P> {
        type: string | ComponentClass<P> | FunctionComponent<P>;
        props: P;
        key: Key | null; // <-- this looks like the issue. Should this be `key?: Key`
    }
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
