### ISSUE TITLE
jasmine.d.ts declares non-existant matchers

### ISSUE THREAD

**Issue by cherrydev** [DefinitelyTyped/DefinitelyTyped#3149]
None of the versions of Jasmine that I can see documentation for (1.3, 2.0, 2.1) have any of the toNot\* matchers in them.  Presumably they did in earlier versions such as 1.2.  I suggest they be removed.

Specfically:

``` typescript
        toNotBe(expected: any): boolean;
        toNotEqual(expected: any): boolean;
        toNotMatch(expected: any): boolean;
        toNotContain(expected: any): boolean;
```

**Comment by zvirja** [comment]
@cherrydev Seems to be solved. Could you close the issue?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
