### ISSUE TITLE
[@types/jquery] Missing `/// <reference types="jquery" />`

### ISSUE THREAD

**Issue by acalvo** [DefinitelyTyped/DefinitelyTyped#31509]
With **types/jquery@3.3.20** and below, the generated `*.d.ts` files that made use of jQuery objects used to include the following triple-slash directive:
`/// <reference types="jquery" />`

With **types/jquery@3.3.21** and above, that's not the case anymore, which means incorrect `*.d.ts` that cause compilation errors when used as third-party dependencies.

I made a minimal repo reproducing this issue: https://github.com/acalvo/lib-using-jquery
If you `npm install` and `npx tsc` over it, the result is https://github.com/acalvo/lib-using-jquery/blob/master/dist/index.d.ts
But if you update the typings to version 3.3.21 or above (including current 3.3.27) in [`package.json`](https://github.com/acalvo/lib-using-jquery/blob/master/package.json) and `npm install` and `npx tsc` again, the triple-slash directive is gone.

This is not the expected behaviour, is it @leonard-thieu ? It seems to happen since #29831 .

**Comment by leonard-thieu** [comment]
> This is not the expected behaviour, is it @leonard-thieu ? It seems to happen since #29831 .

I don't think this is the expected behavior. From the [handbook](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-):

> For declaration files generated during compilation, the compiler will automatically add `/// <reference types="..." />` for you; A `/// <reference types="..." />` in a generated declaration file is added if and only if the resulting file uses any declarations from the referenced package.

Your repro uses the `JQueryAjaxSettings` declaration from `@types/jquery` so TypeScript _should_ add the directive. I'm not sure why splitting up the declarations into separate files would cause it not to. @sandersn any ideas on why this is happening?

**Comment by sandersn** [comment]
@weswigham mind taking a look?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
