### ISSUE TITLE
[@types/jquery] 'JQuery.Event.target' does not exist anymore

### ISSUE THREAD

**Issue by edelm** [DefinitelyTyped/DefinitelyTyped#31506]
'JQuery.Event.target' (https://api.jquery.com/event.target/) is not defined anymore in 'types/jquery/misc.d.ts' (line 4052). Now it's just TriggeredEvent that defines 'target'.

Is it missing or am I missing something here?

**Comment by leonard-thieu** [comment]
`JQuery.Event` was updated to more accurately reflect the object you receive from calling the Event constructor (`jQuery.Event()`). An `Event` object doesn't receive its `target` property until it has been triggered through jQuery's event system. As you've discovered, that object is now represented by `JQuery.TriggeredEvent`. In general, the fix is to change declarations of `JQuery.Event` to `JQuery.TriggeredEvent`. For more details, check out #30144 (in particular, the `Migration notes` section).

**Comment by edelm** [comment]
Thanks for clearing this up! That was very helpful.
