### ISSUE TITLE
[@types/mongoose] DocumentQuery's setUpdate method does not exist

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/DefinitelyTyped#31523]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi @sindrenm  @lukasz-zak @Alorel @jendrikw @Ethan @vologa @jussikinnula @ondratra @alfirin @idandrd @dominikh  @Fazendaaa @NormanPerrin @danmana @stablio

In spite of the fact that as per [#7024](https://github.com/Automattic/mongoose/pull/7024) of [mongoose](https://github.com/Automattic/mongoose), a setUpdate method exists on DocumentQuery, it's definition is not added to @types/mongoose.

Please note that using // @ts-ignore, calling setUpdate on a Query instance works fine.

**Comment by Alorel** [comment]
Then go ahead and add it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
