### ISSUE TITLE
[@types/google-apps-script]: Missing types for Gmail Addons

### ISSUE THREAD

**Issue by johnnyasantoss** [DefinitelyTyped/DefinitelyTyped#31581]
- [ X ] I tried using the `@types/google-apps-script` package and had problems.
- [ X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @grant

I'm using the latest version (0.0.33)

There are no types for Gmail Add-ons events. I think that might be more types missing because the file under `google-apps-script/google-apps-script.gmail.d.ts` is missing a lot of things from [here](https://developers.google.com/gmail/add-ons/) & `google-apps-script/api/gmail/v1.d.ts` is empty :(

**Comment by paxperscientiam** [comment]
Yep, still incomplete.

**Comment by grant** [comment]
Yeah, creating those API types extremely manual, so I haven't got the time to create them.

I've been using Node for most API requests.

**Comment by mtgto** [comment]
Fixed in #34212

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
