### ISSUE TITLE
Missing argument in react-virtualuzed

### ISSUE THREAD

**Issue by gausie** [DefinitelyTyped/DefinitelyTyped#31595]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f91a63c5e3d276fa60e11dbbe3538d27a44fadc2/types/react-virtualized/dist/es/Table.d.ts#L348

This should accept one argument of type `TableHeaderProps`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
