### ISSUE TITLE
WinRT: Missing Windows.Web.Http namespace

### ISSUE THREAD

**Issue by limitedmage** [DefinitelyTyped/DefinitelyTyped#3162]
WinRT definition file is missing Windows.Web.Http namespace: 
http://msdn.microsoft.com/en-us/library/ie/windows.web.http

Also missing are Windows.Web.Http.Filters and Windows.Web.Http.Headers:
http://msdn.microsoft.com/en-us/library/ie/windows.web.http.headers
http://msdn.microsoft.com/en-us/library/ie/windows.web.http.filters

**Comment by pke** [comment]
Hmm this is a real pain. I wonder why no one from MSFT has issued a path yet. They supposed to work with TS themself and never use the HTTP classes? I'm afraid I have not much knowledge and time to extend the winrt file myself though.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
