### ISSUE TITLE
Jquery.fancytree typing package version incorrect

### ISSUE THREAD

**Issue by sandorfr** [DefinitelyTyped/DefinitelyTyped#31623]
There something broken around the `jquery.fancytree` typings. The last published version is `0.0.0` which does not seem right.

![image](https://user-images.githubusercontent.com/2660262/50388370-73110800-0768-11e9-9a3f-da44110ffc60.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
