### ISSUE TITLE
[CodeMirror] Use new to create a CodeMirror instance

### ISSUE THREAD

**Issue by ficristo** [DefinitelyTyped/DefinitelyTyped#31640]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/codemirror` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mihailik @nrbernard @Pr1st0n @rileymiller @toddself

CodeMirror can be istantiated also with the `new` keyword.
This snipped should parse but doesn't. It throws `error TS2350: Only a void function can be called with the 'new' keyword.`

```ts
const container = document.createElement("div");
const codeMirror = new CodeMirror(container);
```

I don't know how to fix it, I need some help.

**Comment by benkonz** [comment]
Codemirror is a global object that you can import with 
```typescript
import * as CodeMirror from 'codemirror';
```

You can then create an editor instance with 
```typescript
const container = document.createElement("textarea");
const editor = CodeMirror.fromTextArea(container);
```

**Comment by ficristo** [comment]
@benkonz my point is CodeMirror can be created with or without the `new` keyword.
```ts
// without new
const codeMirror = CodeMirror(container);
// with new
const codeMirror = new CodeMirror(container);
```
But current types aren't compatible with the `new` keyword. It would be nice if they were.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
