### ISSUE TITLE
Bug : [@types/jsforce]Type '(err: Error, ret: any) => void' has no properties in common with type 'ExecuteOptions'.

### ISSUE THREAD

**Issue by pritisolanki** [DefinitelyTyped/DefinitelyTyped#31879]
Receiving below errors compiling jsforce 1.9.1 with typescript3.2.2
-  I tried using the `@types/jsforce` package and had problems.
- Raise the issue with jsforce github and redirected here. Please find more details https://github.com/jsforce/jsforce/issues/854

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
