### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by somehowchris** [DefinitelyTyped/DefinitelyTyped#31886]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/34b631c6783abf448473a078b73e91feca87595e/types/email-templates/index.d.ts#L36

Needs to be changed to something like that

render?: ( view: string, locals: any ) =>  {};

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
