### ISSUE TITLE
@types/stream-json

### ISSUE THREAD

**Issue by guilhemheinrich** [DefinitelyTyped/DefinitelyTyped#31888]
I am using typescript on a node.js project, on which I want to use stream-json and stream-chain.
With the latest version of typescript (3.3.2), the typings for stream-json throw an error at compile time :
`Type 'typeof _everyFilModule/Class/Namespace_' is not a constructor function type`

I changed the declarations file import declaration from 
   ` import * as FileName from 'Path/To/FileName'`
to
    `import FileName from 'Path/To/FileName'`

With these changes, i got it working with:

```
import fs from 'fs';
import make from 'stream-json'
import streamArray from 'stream-json/streamers/StreamArray'
import Chain from 'stream-chain';

let chain = new Chain([
    fs.createReadStream('./dist/testRoute/sample.json'),
    make(),
    new streamArray()
    ]);
```

Maybe it is something with the `export =` and the `import *`, which I currently think is not right.

As it is not a neat fix, i don't propose a pull request.
@uhop

**Comment by uhop** [comment]
I'll try to see how changes in the latest typescript affected the typings. In any case, I wanted to update them for new versions of `stream-json` and `stream-chain`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
