### ISSUE TITLE
[@types/highcharts] theme is not recognized

### ISSUE THREAD

**Issue by mzhukovs** [DefinitelyTyped/DefinitelyTyped#31905]
@damianog @baltie @AlbertOzimek @hanssens 

Does not appear that "theme" is included so typescript doesn't like it when I try to set it via Highcharts.theme = { }

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
