### ISSUE TITLE
@types/sharp - wrong version

### ISSUE THREAD

**Issue by nolawnchairs** [DefinitelyTyped/DefinitelyTyped#31921]
Hi,

I am unable to download the new version (0.21) as listed below. When I try and install via NPM or Yarn, it downloads type definitions from 0.17 instead. This is causing my Typescript compilation to fail.

- [ x] I tried using the `@types/xxxx` package and had problems.

// Type definitions for sharp 0.21
// Project: https://github.com/lovell/sharp
// Definitions by: François Nguyen <https://github.com/lith-light-g>
//                 Wooseop Kim <https://github.com/wooseopkim>
//                 Bradley Odell <https://github.com/BTOdell>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.1

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
