### ISSUE TITLE
csv-parse should accept Buffer as input as well as string

### ISSUE THREAD

**Issue by benstevens48** [DefinitelyTyped/DefinitelyTyped#31940]
- [x] I tried using the `@types/csv-parse` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DavidM77 

The csv-parse parse method with 3 arguments should accept a Buffer as well as a string as the input (see the changlog here - https://csv.js.org/parse/changelog/.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
