### ISSUE TITLE
[aframe] Add all built-in components types as optional in DefaultComponents interface

### ISSUE THREAD

**Issue by krzysztof-grzybek** [DefinitelyTyped/DefinitelyTyped#31959]
- [x] I tried using the `@types/aframe` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @devpaul 

Hi! I was using aframe typings and I tried to use sound components as in [this example](https://aframe.io/docs/0.8.0/components/sound.html#pause-and-resume). Because there are no typing for sound component, I had to write it by my own.

What do You think about adding typings for built in components and adding them as optional in DefaultComponents interface? We could then access any component by
`entity.components.sound!.play()`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
