### ISSUE TITLE
[@types/yup] Error definition when catching ValidationError

### ISSUE THREAD

**Issue by rockingskier** [DefinitelyTyped/DefinitelyTyped#31950]
I _think_ this is an issue but it may well be my TS knowledge letting me down.

When I catch a validation error the definition for the error is incorrect and does not give me access to the properties I expect.

```typescript
try {
  // yup.boolean().validate(null)
  await yup.boolean().validate(null)  // Updated https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31950#issuecomment-452388726
} catch (error) {
  if (error instanceof ValidationError) {
    // I get here however...
	error; // (local var) error: {}
    error.message // "Property 'message' does not exist on type '{}'"
  }
}
```

ValidationError is defined in two places, [L26](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yup/index.d.ts#L26) and [L295](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yup/index.d.ts#L295), as a function and an interface respectively.

- Authors: 
  - @dhardtke
  - @vtserman
  - @MoretonBayRC
  - @sseppola
  - @YashdalfTheGray
  - @vincentjames501
  - @robertbullen

**Comment by YashdalfTheGray** [comment]
Hello!

It seems like you're using [`validate()`](https://github.com/jquense/yup#mixedvalidatevalue-any-options-object-promiseany-validationerror), which is an async call, as a synchronous call. If you wanna do that, you'd have to use `async/await` with it.

```javascript
async () => {
  try {
    await yup.boolean().validate(null);
  } catch (error) {
    // handle error
  }
}
```

Alternatively, since it returns a promise, you can also just use the standard `.then()` and `.catch()` with it.

```javascript
yup.boolean().validate(null)
.then(results => {})
.catch(errors => ());
```

or you can also use [`validateSync()`](https://github.com/jquense/yup#mixedvalidatesyncvalue-any-options-object-any) if you want to continue to use synchronous calls.

**Comment by rockingskier** [comment]
Thanks @YashdalfTheGray,

Annoyingly that is an error in my example :) My fault during copy/paste/simplify.

I am seeing the issue using sync, async and promise chain:

```typescript
function syncTest() {
  try {
    yup.boolean().validateSync("");
  } catch (error) {
    if (error instanceof ValidationError) {
      error.message; // Property 'message' does not exist on type '{}'.
    }
  }
}

async function asyncTest() {
  try {
    await yup.boolean().validate("");
  } catch (error) {
    if (error instanceof ValidationError) {
      error.message; // Property 'message' does not exist on type '{}'.
    }
  }
}

async function promiseTest() {
  return yup
    .boolean()
    .validate("")
    .catch((error) => {
      if (error instanceof ValidationError) {
        error.message; // Property 'message' does not exist on type '{}'.
      }
    });
}
```

**Comment by YashdalfTheGray** [comment]
Ah alright, I see what's happening. 

I think the types need to merge the function declaration and the interface that's declared later into a class and then it should work because right now, I think, Typescript is typing the Error as the constructor function `ValidationError` rather than the interface `ValidationError`; which is why you're getting the type being evaluated to `{}`. 

I gotta run to work right now but I should have some kind of fix tonight or tomorrow morning. 

I also realized that we don't capture `isError` and `formatError`, which are static methods on the `ValidationError` constructor function in the source code, in the types so I'll add that as well.

**Comment by jr-duarte** [comment]
`} catch (e) {
      const error = e as ValidationError;
      error.message
.....
`
