### ISSUE TITLE
Nav bsClass prop not recognized by type - Property 'bsClass' does not exist on type

### ISSUE THREAD

**Issue by petrdanecek** [DefinitelyTyped/DefinitelyTyped#31998]
- [x] I tried using the `@types/xxxx` package and had problems.
- [-] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @walkerburgin, @vsiao, @danilojrr, @Batbold-Gansukh, @octatone, @chengsieuly, @mretolaza, @katbusch, @vitosamson, @LKay, @aaronbeall, @jrakotoharisoa, @r3nya, @t49tran 

I'm getting this error:
```
Property 'bsClass' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Nav> & Readonly<{ children?: ReactNode; }> & Readonly<NavProps>'
```

for simple SFC:
```
const NavBar: React.SFC<{}> = () => (
  <Nav bsClass="nav custom" bsStyle="pills" activeKey={1}>
    <NavItem to="/dashboard">Dashboard</NavItem>
  </Nav>
);
```

I think that bsClass prop is missed in Nav type definition:
```
declare namespace Nav {
    export interface NavProps extends React.HTMLProps<Nav> {
        // Optional
        activeHref?: string;
        activeKey?: any;
        bsSize?: Sizes;
        bsStyle?: string;
        collapsible?: boolean;
        eventKey?: any;
        expanded?: boolean;
        justified?: boolean;
        navbar?: boolean;
        pullRight?: boolean;
        right?: boolean;
        stacked?: boolean;
        ulClassName?: string;
        ulId?: string;
    }
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
