### ISSUE TITLE
[@types/koa-router] the router middleware types are inconsistent with koa middlewares

### ISSUE THREAD

**Issue by emanuelmd** [DefinitelyTyped/DefinitelyTyped#32006]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dolezel, @guillaume-mayer, @Falinor 

The koa-routers middleware type signature is inconsistent with the koa middleware type signature.

For example, defining your state or custom context on the koa object allows you to use whatever you defined in the ctx, similar to what koa-body does:

```
type KState = { }; // your state
type KCustom = { }; // your custom stuff

const app = new Koa<KState, KCustom>();
```

Now suppose you have a middleware that adds something to your Koa context, say a database service.

```
interface IDatabaseMiddleware {
  dbService: MyDatabaseServiceType;
}

function dbMiddleware() {
  return function(ctx: Koa.ParametrizedContext<{}, IDatabaseMiddleware>) {
    ctx.dbService = dbServiceFactory(); // This key is added from this point onward.
  }
}
```

Using this middleware makes my interface available from that point onward on the koa object.

```
app
  .use(dbMiddleware())
  .use(async ctx => {
    ctx.dbService.doAFlip(); // this works
  })
```
Adding the same middleware on a koa-router object doesn't typecheck.
```
import Router from 'koa-router';

const router = new Router();

router
  .get('/',
    dbMiddleware(), // doesn't typecheck
    async ctx = { // ctx is untyped and doesn't compile in strict  mode
    })
```

I did some digging through the typings of the koa-router and it seems the IMiddleware interface does not extend the State/Custom generic params.

Please let me know if I'm missing something.

**Comment by Guillaume-Mayer** [comment]
I'll check if #31926 solves this issue

**Comment by astashov** [comment]
#31926 will help a bit with this issue, but maybe won't solve all your problems.
I.e. after it's merged, you'll be able to do:

```ts
import Router from 'koa-router';

interface IDatabaseMiddleware {
  dbService: MyDatabaseServiceType;
}

function dbMiddleware(ctx: Koa.ParameterizedContext<{}, IDatabaseMiddleware>) {
  ctx.dbService = dbServiceFactory(); // This key is added from this point onward.
}

const router = new KoaRouter<{}, IDatabaseMiddleware>();
router.get('/', async (ctx) => {
  // ctx here will be Koa.ParameterizedType<{}, IDatabaseMiddleware & IRouterParamContext>
});

const app = new Koa<{}, {}>();
app.use(dbMiddleware).use(router.routes()).listen(3000);
```

But your example with prepending middlewares to the route handlers is a bit trickier. The type signature of `get` is:

```ts
get(
    path: string | RegExp | (string | RegExp)[],
    ...middleware: Array<Router.IMiddleware<StateT, CustomT>>
): Router<StateT, CustomT>;
```

And I frankly dunno if that's possible to type elements of array based on the previous element of the array (so that the second element of `middleware` would be with `IDatabaseMiddleware` if the first element is `dbMiddleware()`.

We maybe could do several specific overrides exactly for this example, i.e. the `get` signature would be:

```ts
get<NewStateT, NewCustomT>(
    path: string | RegExp | (string | RegExp)[],
    preMiddleware: Router.IMiddleware<NewStateT, NewCustomT>,
    ...postMiddlewares: Array<Router.IMiddleware<NewStateT & StateT, NewCustomT & CustomT>>,
): Router<StateT, CustomT>;
```

It probably would work. What do you think, @Guillaume-Mayer ?

**Comment by Guillaume-Mayer** [comment]
I think the same, I don't see any construct that could infer type from the previous element in an array, so several overrides seems the only option, as far as I know

**Comment by emanuelmd** [comment]
I just noticed the way koa-router registers middlewares is very different from how koa does it, which kinda sucks because as you guys pointed out you cannot extend the context from that point onward and have typings on it. I'll play a bit with the type system and try to come up with good solution.

**Comment by tim-field** [comment]
@emanuelmd did you find a solution to this issue in the end, wondering if this issue could be re-opened as this issue still stands unfortunately https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31926#issuecomment-453092243

**Comment by villesau** [comment]
This is still a problem. I have an external package ( https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa-ratelimit/index.d.ts#L8 ) using koa `Middleware`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa/index.d.ts#L558, but that's incompatible with `IMiddleware` form koa router ( https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa-router/index.d.ts#L71 )  due to `@koa/multer` extedning `DefaultContext`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa__multer/index.d.ts#L41 https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa/index.d.ts#L551

I've faced similar issues many many times when defining stronger context for koa and other third party libraries.
