### ISSUE TITLE
[@types/fetch-mock] fetchMock.config property is missing, fetchMock.configure function is obsolete

### ISSUE THREAD

**Issue by evra** [DefinitelyTyped/DefinitelyTyped#32030]
- [x] I tried using the `@types/fetch-mock` package and had problems.
  - Authors: @asvetliakov @tamird @merrywhether @chrissinclair @captain-igloo

The fetchMock.config property is missing, the fetchMock.configure function is obsolete in version 7.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
