### ISSUE TITLE
Need PR help on match-sorter

### ISSUE THREAD

**Issue by cmeeren** [DefinitelyTyped/DefinitelyTyped#32038]
Author: @claasahl

I have two tiny things I'd like to fix with [the typings for match-sorter](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/match-sorter/index.d.ts), but I'm no TS/JS dev, so I'd just like some quick tips and sanity checks before I can submit a PR (or if @claasahl wants to fix this, that is even better IMHO).

**Issue 1:** It seems that `MinRanking`, `MaxRanking`, and `MinMaxRanking` can easily be combined into a structure similar to `MinMaxRanking` where `minRanking` and `maxRanking` are optional. (Granted, this opens up for only specifying `key`, but I'm fairly sure that will work fine.) 

**Issue 2:** In `MinRanking`, `MaxRanking`, and `MinMaxRanking` (or the single unified one as suggested above), `key` can be `string | ((item: T) => string)`, not just `string`. See https://github.com/kentcdodds/match-sorter/issues/53

**Comment by ChrisRu** [comment]
The object in `keys` also accepts `treshold: number` in a recent pull request: https://github.com/kentcdodds/match-sorter/pull/50

**Comment by cmeeren** [comment]
So I'm probably thinking we can replace `MinRanking`, `MaxRanking`, and `MinMaxRanking` with this, to solve everything

```ts
interface MinMaxRanking<T> {
    key: string | ((item: T) => string)
    minRanking?: number;
    maxRanking?: number;
    threshold?: number;
}
```

No idea if the syntax is correct; I don't know TS.

**Comment by ChrisRu** [comment]
The updated types have now been merged!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
