### ISSUE TITLE
Typescript complains that a valid way of calling stripe.invoices.list is actually invalid

### ISSUE THREAD

**Issue by kaifresh** [DefinitelyTyped/DefinitelyTyped#32052]
If you know how to fix the issue, make a pull request instead.

- [ X] I tried using the `@types/stripe` package and had problems.
- [ X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @vvakame @CodeAnimal 

If you do not mention the authors the issue will be ignored.

After importing `@types/stripe` and making the following call to stripe to get invoices on subscription:  `await stripe.invoices.list({subscription: subscription.id});` ([i.e. the code here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/70fe2693432f8082521f42f42f2ae75487782523/types/stripe/index.d.ts#L6763)), I get the Typescript linter complaining that this is not a valid function signature.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
