### ISSUE TITLE
I need to update the c3 interface by adding "focus".

### ISSUE THREAD

**Issue by Eduardo-Vieira** [DefinitelyTyped/DefinitelyTyped#32065]
If you know how to fix the issue, make a pull request instead.

- [ X] I tried using the `@types/c3` package and had problems.
- [ X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tdreyno 

If you do not mention the authors the issue will be ignored.

I need to update the c3 interface by adding "focus".
export interface Grid {
    focus?: {
        show: false
    };
    x?: {
        /**
         * Show grids along x axis.
         */
        show?: boolean;
        /**
         * Show additional grid lines along x axis.
         * This option accepts array including object that has value, text, position and class. text, position and class are optional. For position, start, middle and end (default) are available.
         * If x axis is category axis, value can be category name. If x axis is timeseries axis, value can be date string, Date object and unixtime integer.
         */
        lines?: LineOptions[];
    };
    y?: {
        /**
         * Show grids along y axis.
         */
        show?: boolean;
        /**
         * Show additional grid lines along y axis.
         * This option accepts array including object that has value, text, position and class.
         */
        lines?: LineOptions[];
    };
}

**Comment by iansan5653** [comment]
This should be fixed as of PR #37139. Please verify that the definition is correct.

Relevant code: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/c3/index.d.ts#L809-L811

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
