### ISSUE TITLE
Probably wrong typings for lodash/cloneDeep method

### ISSUE THREAD

**Issue by dubzzz** [DefinitelyTyped/DefinitelyTyped#32066]
Hello,

While playing around with lodash I found strange that the typing of `cloneDeep` was not removing `readonly` from the type:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/lodash/common/lang.d.ts#L69

So I decided to check whether or not the typing was right and it appears the resulting clone is no more readonly:

```typescript
const  _ = require('lodash');

const st = { a: 1 };
Object.freeze(st);

console.log(Object.getOwnPropertyDescriptor(st, 'a').writable);
// > false

console.log(Object.getOwnPropertyDescriptor(_.cloneDeep(st), 'a').writable);
// > true
```

Do you confirm that the typing should be updated and fixed?
Regards,
Nicolas

**Comment by forresthopkinsa** [comment]
This applies to a number of other lodash functions too. Many object functions return a new object, and they should not carry over the `readonly` attribute.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by cdauth** [comment]
#70545
