### ISSUE TITLE
@types/sass has no fiber option

### ISSUE THREAD

**Issue by gluons** [DefinitelyTyped/DefinitelyTyped#32091]
[`@types/sass`](https://www.npmjs.com/package/@types/sass) has no `fiber` option for `sass.render` function that [`sass`](https://www.npmjs.com/package/sass) has.

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the [`@types/sass`](https://www.npmjs.com/package/@types/sass) package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @lenovouser

If you do not mention the authors the issue will be ignored.

**Comment by Swivelgames** [comment]
This is valid. Currently running into the same issue.

Authors: @lenovouser and @jleider

**Comment by Swivelgames** [comment]
This relies on adding a new key `fiber` to `@types/sass` `sass.Options` with the `@types/fibers` `FiberConstructor` type.

I'm not entirely sure how to reference "external" type dependencies, so I'm not sure how to implement this into a PR to resolve it.

@lenovouser @jleider Any chance you could lend a hand? :)

**Comment by jleider** [comment]
I think you may want to use the triple slash directive to pull in the types you need from [@types/fibers](https://www.npmjs.com/package/@types/fibers).

https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
