### ISSUE TITLE
[@types/passport-github] passReqToCallback missing in StrategyOption

### ISSUE THREAD

**Issue by ManAnRuck** [DefinitelyTyped/DefinitelyTyped#32124]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/passport-github` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @yasupeke 

I can't pass the `passReqToCallback` option to githubStrategy.
in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1f2e5cc5ec1ba892830461dce148e40cabae7c6a/types/passport-github2/index.d.ts it exists. but this is an other package (deprecated)

**Comment by ReggaePanda** [comment]
PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32226

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
