### ISSUE TITLE
Readonly doesn't work in React Component

### ISSUE THREAD

**Issue by Jibacat** [DefinitelyTyped/DefinitelyTyped#32153]
I tried using the `@types/react@16.4.14` package and had problems.
I found the properties in state is defined to `readonly` By React.component when we use `@types/react@16.4.14`.
```
state: Readonly<S>;
```
But when I wrote `state` as a property in my Component like this:

```
interface IShareBlockState {
    show: boolean;
}

class ShareBlock extends React.Component<any, IShareBlockState>{
    static type = 'share-block';
    public state = {
        show: false,
    }
}

this.state.show = true  // *** NO ERROR ***
```
The readonly didn't work even though I could change the state straight. I thought the `state: Readonly<S>` had some problems.

**Comment by Jibacat** [comment]
```
constructor(props: any) {
        super(props);
        this.state = {
            show: false,
        }
    }
```
I tried another way and found the `readonly` worked perfectly.
I have no idea about the difference between the `state`  in `constructor` and out of `constructor`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
