### ISSUE TITLE
Install fails on Meteor 1.0

### ISSUE THREAD

**Issue by DouglasUrner** [DefinitelyTyped/DefinitelyTyped#3219]
I tried: 

```
$ meteor add typescript-libs
typescript-libs: no such package              
Babeuf-2:Skeleton-TS dlu$ meteor search typescript
Found the following packages:
meteortypescript:compiler  TypeScript is a typed superset of JavaScript

To get more information on a specific item, use meteor show
```

Has at the package name changed?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
