### ISSUE TITLE
_.some shorthand for _.matches is broken

### ISSUE THREAD

**Issue by maxim-smotrov** [DefinitelyTyped/DefinitelyTyped#32204]
- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @aj-r @Ailrun @e-cloud @thorn0 @jtmthf @DomiR 

It looks like this PR broke the `_.matches` shorthand which is `_.some` taking an object as a second parameter: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25204
Lodash doc for reference: https://lodash.com/docs/4.17.10#some
The PR was supposed to fix `_.find` by removing `object` type from `ListIterateeCustom<T, TResult>`. But that same type is used in `_.some` which allows `object` (using this causes linting error currently).
Would fix it myself if it wasn't conflicting with `_.find`. Not sure what the appropriate fix would be.

**Comment by aj-r** [comment]
Can you explain in more detail what is broken? We have tests for `_.matches` and `_.some` that are passing.

The fact that `object` was there in the first place was an oversight - it was replaced with `PartialDeep<T>` some time ago. The idea being that your match object needs to be a partial version of the object you're testing, otherwise there's no hope of ever matching it. The main goal was to help people catch typos in the match object, but it's possible that this had unintended consequences. What's your use case?

**Comment by IlyaSavich** [comment]
I got the same issue. My example is

> let localVar: Record<string, any> = {};
_.some(localVar, { someProperty: 'someValue' })

// TS2345: Argument of type '{ someProperty: 'someValue' }' is not assignable to parameter of type 'string | number | symbol | [string | number | symbol, any] | ObjectIterator<Record<string, any>, boolean> | PartialDeep<any> | undefined'. Type '{ someProperty: 'someValue' } is not assignable to type undefined'.

**Comment by aj-r** [comment]
I'm surprised that it's not assignable to PartialDeep<any>. Maybe the PartialDeep type should be improved now that we can use conditional types. PRs are welcome.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
