### ISSUE TITLE
Shortcut method definition 'patch' is missing from IHttpService interface of AngularJS

### ISSUE THREAD

**Issue by akalirong** [DefinitelyTyped/DefinitelyTyped#3221]
In angular.d.ts, the 'patch' method is missing. Can anyone help add it?

https://github.com/borisyankov/DefinitelyTyped/blob/master/angularjs/angular.d.ts

**Comment by awerlang** [comment]
@romeli @vvakame if you don't mind I can submit a PR to this. I've done this locally.

**Comment by romeli** [comment]
Sure please go ahead. I'm doing this locally too.

André Werlang <notifications@github.com>于2015年1月23日星期五写道：

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
