### ISSUE TITLE
[@types/mailparser] Type issues

### ISSUE THREAD

**Issue by MrXyfir** [DefinitelyTyped/DefinitelyTyped#32291]
- [x] I tried using the `@types/mailparser` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

@Avol-V @psnider

```ts
import { simpleParser } from 'mailparser';
// ...
const message = await simpleParser(stream);
// [ts] Property 'headerLines' does not exist on type 'ParsedMail'. [2339]
console.log(message.headerLines);

// Needs
interface ParsedMail {
  headerLines: {
    key: string;
    line: string;
  }[];
}
```

Given the last update of the type definitions there are probably lots of other things missing too.

**Comment by mfogel** [comment]
It looks like the first and third issues listed here have since been fixed. Second issue has not been addressed, as far as I can tell.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
