### ISSUE TITLE
[@types/nodemailer] Type issues

### ISSUE THREAD

**Issue by MrXyfir** [DefinitelyTyped/DefinitelyTyped#32305]
- [x] I tried using the `@types/nodemailer` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

@bioball @rogierschouten @dex4er

```ts
// [ts] Module '"path/node_modules/@types/nodemailer/lib/mail-composer"'
// resolves to a non-module entity and cannot be imported using this construct. [2497]
import * as MailComposer from 'nodemailer/lib/mail-composer';
```

This might be a nodemailer issue itself.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
