### ISSUE TITLE
Import problem @types/rc-time-picker@3.4

### ISSUE THREAD

**Issue by taras-dubyk** [DefinitelyTyped/DefinitelyTyped#32331]
If you know how to fix the issue, make a pull request instead.

I tried using the `@types/rc-time-picker@3.4.0` package and had problem with importing.
I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
How I can import this package?
  - Authors: @Hoff97

**Comment by Hoff97** [comment]
`import TimePicker from 'rc-time-picker';` should be all it takes.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
