### ISSUE TITLE
[dhtmlxgantt] [dhtmlx-gantt] Types for tasks

### ISSUE THREAD

**Issue by mpsijm** [DefinitelyTyped/DefinitelyTyped#32345]
For example the `addTask`, `createTask`, and `parse` methods have `any` as parameter, while that can be narrowed down to a type that represents the task objects in a Gantt chart.

The only problem is: there is no official type for tasks that I can find in the [docs](https://docs.dhtmlx.com/gantt/api__gantt_addtask.html), only some examples that use a subset of the fields of tasks.

@mkozhukh @chriscamicas

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
