### ISSUE TITLE
[@types/redis] Everything is a future boolean

### ISSUE THREAD

**Issue by lukepighetti** [DefinitelyTyped/DefinitelyTyped#32365]
I feel like I have to be missing something. Pretty much every GET type request is a return type boolean. HGET? boolean. HGETALL? boolean. GEORADIUS? ...boolean. The callbacks have the correct types but the promises are borked.

**Comment by SimonSchick** [comment]
Yea that seems like a weird design decision:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/redis/index.d.ts#L1176

**Comment by lukepighetti** [comment]
I'm just a little confused because five minutes trying to build something in typescript with `node_redis` it is very clear that the types are not usable. That is why I feel like I have to be missing something. Someone obviously spent a lot of time making those types. Any ideas what I might be missing?

**Comment by BendingBender** [comment]
Would be great if you could fix them and make a PR.

**Comment by lukepighetti** [comment]
Message received.

**Comment by OliverEvans96** [comment]
@lukepighetti @SimonSchick @BendingBender - please review my PR #37064 if you're able.

Thanks!
Oliver

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
