### ISSUE TITLE
Cordova Exec Function Declaration

### ISSUE THREAD

**Issue by stan1025** [DefinitelyTyped/DefinitelyTyped#3236]
To write customized cordova plugins it is necessary to create callback methods with arguments to transmit data from the native side to non-native side. With the actual declaration of cordova.exec in the type script definitions it is not possible to write the plugin fore facing code in typescript because the exec function doesnt allow arguments inside the callback methods for success and error. 

Is it possible to change this declaration to this one?
cordova.exec(success:Function,error:Function,Service:string,action:string,[args:string]);

Thanks

**Comment by zachCatalyst** [comment]
To much current plugin specs the callback methods assigned to success and fail params both need to allow (force) parameters.

exec(success: (data:any) => any, fail: (err:any) => any, service: string, action: string, args?: string[]): void;

**Comment by vvakame** [comment]
please send a pull request!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
