### ISSUE TITLE
[@types/koa-session] Conflicting with ctx object

### ISSUE THREAD

**Issue by ejose19** [DefinitelyTyped/DefinitelyTyped#32389]
Steps to reproduce:

Create a empty folder

npm init (all default)

npm install --save koa koa-session
npm install --save-dev @types/koa @types/koa-session

create index.ts and paste the following:

```typescript
import * as Koa from "koa";
const app = new Koa();

app.use(async (ctx, next) => {
  await next();
  ctx.app.emit("error");
});
```

Linter will throw an error saying "[ts] Property 'emit' does not exist on type 'Application'. [2339]", also only available methods for ctx.app are .on and .once

I took a glance at the @types/koa-session definition file and somehow the interface Application is overriding the original koa Application interface, if I comment out the interface the ctx.app regains its original Interface and the error goes away (of course this is not the correct solution, but my knowledge in typescript is not advanced to solve this)

@tlaziuk @kerol2r20

**Comment by tyteen4a03** [comment]
Just ran into this issue.

**Comment by colthreepv** [comment]
Any workaround?
Is there a way to tell Typescript to ignore that declaration merging (overwriting) ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
