### ISSUE TITLE
[@types/showdown] Throws an error in a WebWorker environment

### ISSUE THREAD

**Issue by marekdedic** [DefinitelyTyped/DefinitelyTyped#32387]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/showdown` package and had problems.

I've tried using the `@types/showdown` package in a WebWorker source, that is I have in my tsconfig:
```json
"compilerOptions": {
  "lib": ["ES6", "WebWorker"],
  "target": "ES6"
}
```

I got this error:
```
/home/user/project/node_modules/@types/showdown/index.d.ts(348,48): error TS2304: Cannot find name 'HTMLDocument'.
TypeScript: 1 semantic error
```

I think this is caused by the missing DOM library, but seeing as it is incompatible with WebWorker, I don't know, how to solve this.

  - Authors: @hamedbaatour @cbowdon @tan9 @ArielSaldana 

Thank you

**Comment by levi-pires** [comment]
It works only with the DOM library.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
