### ISSUE TITLE
[@types/sinon] sinon.spy lacks the third argument

### ISSUE THREAD

**Issue by karak** [DefinitelyTyped/DefinitelyTyped#32398]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/sinon` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mrbigdog2u @rationull @lumaxis @nicojs @43081j @tdreyno @joshuakgoldberg

If you do not mention the authors the issue will be ignored.

We can't spy accessors because the current definition of `sinon.spy` lacks third argument called `types`, which should be typed as `types?: string[]`.

See <https://github.com/sinonjs/sinon/blob/master/lib/sinon/spy.js>.

My test project is here: <https://codesandbox.io/s/92n50m2n1p>.

**Comment by nicojs** [comment]
Is this an undocumented feature? I don't see it here: https://sinonjs.org/releases/v7.2.3/spies/#creating-spies-sinonspy-method-signatures

Generally, we only add typings of features that are documented.

**Comment by 43081j** [comment]
It is undocumented. 

I suggest opening an issue with sinon to find out if it's supported (as in they won't just remove it one day and it isn't deprecated).

**Comment by karak** [comment]
OK. I issued.

**Comment by karak** [comment]
It's supported though still undocumented.
https://github.com/sinonjs/sinon/issues/1970#issuecomment-456829228

**Comment by nicojs** [comment]
Cool, feel free to create a PR (for both sinon 🚀 and definitely typed 🚀 )

**Comment by karak** [comment]
Is that documentation guarding?
Actually, I had already had a type patch in my(our) local, but no works of sinon itself.

**Comment by karak** [comment]
Ah, you mean a return value should have the type of the original method, property descriptor in this case, instead of just a callable, then?

**Comment by 43081j** [comment]
alright so the short explanation to this is that sinon does some hacky things when you spy on something.

behind the scenes, it just attaches a bunch of sinon things to the property descriptor. the descriptor is usually `{}` so you don't notice anything extra, but when you use `['get', 'set']`, it is `{get: fn, set: fn}`. Meaning technically a spy with get/set does have a `get` and `set` property (because again it is just the descriptor with sinon stuff added to it).

we can't easily represent this in strong types, though... its doable in some way i imagine but could lead to unnecessary complexity. if its wanted enough, someone should take a stab at it but otherwise i'd personally leave it out (and somehow work around it).

**Comment by karak** [comment]
Agree. The typing would be hard and complex.

Can I show my image by code bellow? I know the descriptor is just a definition, but I can't grab the final type of that execution pass.

<https://github.com/karak/DefinitelyTyped/commit/95c18e5c37c49182aace9e59a961631f2648d80b>
