### ISSUE TITLE
[@types/chromecast-caf-receiver] not compatible with imports

### ISSUE THREAD

**Issue by tundratier** [DefinitelyTyped/DefinitelyTyped#32426]
@craigrbruce: Using the types for the chromecast receiver works as long as the file does not import anything.
Once I'm adding an import TSC fails with the message "'cast' refers to a UMD global, but the current file is a module. Consider adding an import instead.".

If I'm adding `import cast from "chromecast-caf-receiver";` it fails with: Module not found: Error: Can't resolve 'chromecast-caf-receiver' in '/some/path/to/src/'.

The issue can be reproduced here: https://github.com/tundratier/cast-caf-receiver-issue.

**Comment by Samylots** [comment]
Any update on this issue?

**Comment by craigrbruce** [comment]
Not from me, I am not (and won't be) working in this repo anymore. Please submit a PR to expedite changes if required.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
