### ISSUE TITLE
[@types/angular-formly] formControl types should be NgModelController

### ISSUE THREAD

**Issue by hrwtz** [DefinitelyTyped/DefinitelyTyped#32433]
formControl objects returned by AngularFormly are actually ng.NgModelController and not ng.IFormController. The definition comments themselves mention that the type is NgModelController, but then sets it as IFormController.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2359b4c3b5226f47e3065bcb85afd84c12ee4e3a/types/angular-formly/index.d.ts#L501-L506

You can see in the angular-formly project, they are using methods on the formControl object that exists on NgModelController, but not IFormController.

https://github.com/formly-js/angular-formly/blob/c1bd043dc56bed4eecb573717c60804e993e1ab0/src/directives/formly-field.js#L249-L262

@scatcher

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
