### ISSUE TITLE
[@types/h2o2] Possible wrong definition for Headers?

### ISSUE THREAD

**Issue by KevinGruber** [DefinitelyTyped/DefinitelyTyped#32430]
Hi,

i ran into a problem with the h2o2 definitions,
because they define the headers as Dictionary of string but both IncomingHttpHeaders from node and Hapi define their Headers as: string | string[].
Was that a concious decision or was it just overlooked?

BR,
Kev

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/489aedfed2815ae507c14ec0381b6f89dfd65487/types/h2o2/index.d.ts#L28

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
