### ISSUE TITLE
[@types/qlik-visualizationextensions] extend interface IRoot with Promise

### ISSUE THREAD

**Issue by ralfbecher** [DefinitelyTyped/DefinitelyTyped#32446]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by konne** [comment]
@ralfbecher please add the following line into you local npm index.d.ts for this packages and test if everything works fine. Because the Qlik Docu is not clear, Is it qlik.Promise or qlik.promise
Line 1046:       promise: PromiseConstructor;
After you confirm that is working I will update the package.

**Comment by ralfbecher** [comment]
@konne should be:
Promise: PromiseConstructor;
