### ISSUE TITLE
esprima.d.ts: SomeExpression and SomeStatement are unnecessary and cumbersome

### ISSUE THREAD

**Issue by kevinbarabash** [DefinitelyTyped/DefinitelyTyped#3245]
Since `SomeStatement` extends all Statements, it means that any object that you try to append to `Program.body` (which is typed as `SomeStatement[]`) must contain properties from each type of `Statement` instead of just a particular `Statement`.  The same goes for `SomeExpression`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
