### ISSUE TITLE
[@types/webdriverio] missing type definition for timeouts() W3C syntax

### ISSUE THREAD

**Issue by andreacrawford** [DefinitelyTyped/DefinitelyTyped#32462]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webdriverio/index.d.ts#L1410

Type definition for `browser.timeouts()` does not include the W3C (object) syntax listed here: 
http://v4.webdriver.io/api/protocol/timeouts.html

@timbru31 @daveparslow @MrOggy85

**Comment by MrOggy85** [comment]
Hi @andreacrawford! Thank you for spotting this! 

However, while researching into this I saw that webdriverio is now bundling their own Typescript definition since 5.0.0 :tada: which means that these definitions are no longer needed. I just made a PR to delete these definitions. #32490 

Please use the types directly from the webdriverio.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
