### ISSUE TITLE
rxjs: add "fromEvent" definitions that are typed based on the "eventName"

### ISSUE THREAD

**Issue by kevinbarabash** [DefinitelyTyped/DefinitelyTyped#3246]
example (rx.async-lite.d.ts):
`fromEvent<T>(element: Node, eventName: "mousemove", selector?: (arguments: any[]) => MouseEvent): Observable<MouseEvent>;`

That way people don't have to manually add type information to the selector.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
