### ISSUE TITLE
[@types/bytebuffer] missing writeLong method

### ISSUE THREAD

**Issue by pY4x3g** [DefinitelyTyped/DefinitelyTyped#32491]
- [x] I tried using the `@types/bytebuffer` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cappellin 

The bytebuffer type def are missing the method writeLong (https://github.com/dcodeIO/bytebuffer.js/wiki/API#bytebufferwritelongvalue-offset).

**Comment by cappellin** [comment]
Opened a PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32529) to add the missing method.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
