### ISSUE TITLE
googlemaps lat/lng types incorrect

### ISSUE THREAD

**Issue by jocaron27** [DefinitelyTyped/DefinitelyTyped#32500]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/googlemaps` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cgwrench @nertzy @xaolas @martincostello @svenkreiss @bolatovumar @gauthierm 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5d6a94a306de353b32862949fd6311cb6294ac81/types/googlemaps/index.d.ts#L2275

In the latest version of the geocoding API, the return value for type LatLng: lat and lng are not functions returning numbers (() => number), but just simply type 'number'.

Not sure whether the type is out of date or the API is an old version.

**Comment by jocaron27** [comment]
Hi @Manc thanks for the info! I concluded the same thing; I think this type is specifically for the Google Maps API but the Geocoding API return value is slightly different. The comment on line 42 here seems to confirm this: https://gist.github.com/lukas-zech-software/a7e4a23a6833ec1abb1fc836138f7822

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
