### ISSUE TITLE
[@types/d3-shape] d3 pie chart pie.value() too strict

### ISSUE THREAD

**Issue by petarGitNik** [DefinitelyTyped/DefinitelyTyped#32545]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek @andy-ms  @denisname @Tragetaschen @gustavderdrache @borisyankov

Hi, when I try to assign data to pie generator I receive an error and a linter warning:

```
Type '{ label: string; value: number; }' is not assignable to type 'number | { valueOf(): number; }'. Object literal may only specify known properties, and 'label' does not exist in type 'number | { valueOf(): number; }'.
```

I'm using angular 7 with d3 v5. And latest (5.7) typings. The steps to reproduce:

```
    let pie = d3.pie()
      .sort(null)
      .value(function(d) { return d['value']; });

    pie([{label: 'a', value: 3}, {label: 'b', value: 6}]);
```

I also have to use `d['value']` instead of `d.value` because `Property 'value' does not exist on type 'number | { valueOf(): number; }'. Property 'value' does not exist on type 'number'.`. This piece of code normally works with vanilla d3, however, because of these errors I cannot compile/start project.

**Comment by gustavderdrache** [comment]
You probably want to use the [`pie<Datum>()`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-shape/index.d.ts#L622-L630) constructor instead of the [`pie()`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-shape/index.d.ts#L615-L621) constructor. Calling the `pie()` function doesn't provide enough information to the compiler to determine what is being used, so it has to be provided explicitly with angle brackets.

**Comment by petarGitNik** [comment]
@gustavderdrache Thanks! I've placed my own interface instead of `Datum`, and now it works.
