### ISSUE TITLE
react-select: `OptionRendererHandler` and `ValueRendererHandler` have incorrect typings.

### ISSUE THREAD

**Issue by JoshMcCullough** [DefinitelyTyped/DefinitelyTyped#32554]
react-select has a couple of typings issues, I think.

`OptionRendererHandler`, and `ValueRendererHandler` incorrectly specify `option: Option<TValue>` when it should be `option: TValue`.

Debugging the callback shows that the raw/original object is sent to these handlers, not one wrapped in an `Option<T>`.

**Comment by thib92** [comment]
You duplicated your own issue #32553 on this one (juste to keep it to one issue).
I noticed the same thing. The `onChange` returns `Option<T>` (is there an `Option<T>`? I couldn't find it).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
