### ISSUE TITLE
CI doesn't verify if removing a definition breaks other packages

### ISSUE THREAD

**Issue by Flarna** [DefinitelyTyped/DefinitelyTyped#32564]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sanders, @RyanCavanaugh

see #32490, webdriverio has been removed, CI was green in PR but afterwards node CI is read because chai-webdriverio needs webdriverio (see CI of #32159):

```
/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/chai-webdriverio/index.d.ts:6:23
ERROR: 6:23   expect  TypeScript@next compile error: 
Cannot find type definition file for 'webdriverio'.
ERROR: 22:38  expect  TypeScript@next compile error: 
Cannot find namespace 'WebdriverIO'.
```

Is it possible to improve CI runs to verify that no other module depends on a module which get's removed?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
