### ISSUE TITLE
[@types/moment-timezone] Incomplete Definitions

### ISSUE THREAD

**Issue by sjyn** [DefinitelyTyped/DefinitelyTyped#32560]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @michelsalib @alanblins @asermax

If you do not mention the authors the issue will be ignored.

<hr>

It looks like the definitions for moment-timezone are incomplete. Trying to call functions like `pack` and `unpackBase60` yield an 'Unresolved function or method' in TypeScript. According to moment's docs, [these methods exist on the timezone](https://momentjs.com/timezone/docs/#/data-utilities/pack/). 

Just as a sanity check, I've tried
```javascript
import * as moment from 'moment';
import 'moment-timezone';
```
and 
```javascript
import * as moment from 'moment-timezone';
```
and neither seems to yield those method definitions. Are there plans to implement this at some point in the near future?

**Comment by akashishu777** [comment]
Hi, @sjyn I have created a pull request to add the missing definitions. [Pull request url](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32653/)

**Comment by EvanHahn** [comment]
`moment-timezone` has bundled its types since 0.5.30, according to `notNeededPackages.json`. I think this issue can be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
