### ISSUE TITLE
@types/reactstrap missing UncontrolledPopover

### ISSUE THREAD

**Issue by PeterYangIO** [DefinitelyTyped/DefinitelyTyped#32600]
- [x] I tried using the `@types/reactstrap` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mfal @danilobjr @FaithForHumans @timc13 @patrickrgaffney @prabodht @georg94 

There does not appear to be a type for `UncontrolledPopover`

Reactstrap source: https://github.com/reactstrap/reactstrap/blob/master/src/UncontrolledPopover.js
Current uncontrolled types: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/reactstrap/lib/Uncontrolled.d.ts

**Comment by oprobst-ethz** [comment]
Trying to use the UncontrolledPopover gives me the following error:

`Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
`

**Comment by kaleem-elahi** [comment]
ypu have to update it to latest versions for popover and reactstrap.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
