### ISSUE TITLE
[@types/dd-trace] Document how to use the library

### ISSUE THREAD

**Issue by kevinburke** [DefinitelyTyped/DefinitelyTyped#32642]
The type definition for the "dd-trace" library, in "@types/dd-trace", exports a single variable.

    declare var trace: TraceProxy;
    export = trace;
    
    declare class TraceProxy extends Tracer {
        /**
         * Initializes the tracer. This should be called before importing other libraries.
         */
        init(options?: TracerOptions): this;
    
        // A bunch of other irrelevant code.
    }

How can I import this in my code? If I incorrectly try assign ddTrace.init() to a boolean, TypeScript tells me the type is 'TraceProxy'. However I have tried every seeming variation:

    import { TraceProxy } from "dd-trace"

fails with `node_modules/@types/dd-trace"' has no exported member 'TraceProxy'.`

    import { init, trace } from "dd-trace"

    const tracer: trace = init()

The import succeeds there but then the declaration fails: `3:15: cannot find name "trace"`

All of these variations fail:

    const tracer: trace.trace = init()
    const tracer: trace.TraceProxy = init()
    const tracer: trace.Tracer = init()
    const tracer: TraceProxy = init()
    const tracer: Tracer = init()

Importing the module fails:

    import * as ddTrace from "dd-trace"
    
    const tracer: ddTrace = ddTrace.init()

with `Cannot find name 'ddTrace'.` on line 3. 

These also failed:

    import * as ddTrace from "dd-trace"
    
    const tracer: ddTrace.TraceProxy = ddTrace.init()

with `Cannot find namespace 'ddTrace'.`

How can I declare the type definition there? I'm using the latest version of TypeScript.

**Comment by BendingBender** [comment]
You can import it with the following statement:
```typescript
import TraceProxy = require('dd-trace');
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
