### ISSUE TITLE
Definition request: angularjs ILocationProvider

### ISSUE THREAD

**Issue by jschwarty** [DefinitelyTyped/DefinitelyTyped#3266]
The angularjs $locationProvider.html5mode function can be called with a boolean or an object in AngularJS 1.3.x.
https://docs.angularjs.org/api/ng/provider/$locationProvider#html5Mode

``` javascript
$locationProvider.html5Mode({
    enabled: true,
    requireBase: false,
    rewriteLinks: true
});
```

Can we get ILocationProvider updated to add the object signature please? Also, the docs now indicate the param is of type boolean|Object so the comment about the use of boolean instead of string could be removed in the existing interface `html5Mode(active: boolean): ILocationProvider` method.

``` typescript
interface ILocationProvider extends IServiceProvider {
    hashPrefix(): string;
    hashPrefix(prefix: string): ILocationProvider;
    html5Mode(): boolean;
    html5Mode(enabled: boolean): ILocationProvider;
    html5Mode(config: { enabled: boolean; requireBase: boolean; rewriteLinks: boolean; }): ILocationProvider;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
