### ISSUE TITLE
error TS2304: Cannot find name 'Logger'.

### ISSUE THREAD

**Issue by geneconde** [DefinitelyTyped/DefinitelyTyped#3267]
I tried to run 'grunt c' on the project root and the result is this, not sure why :(

Running "typescript:base" (typescript) task

> > app/components/DefinitelyTyped/handlebars/handlebars.d.ts(20, 17): error TS2304: Cannot find name 'Logger'.
> > Warning: Task "typescript:base" failed. Use --force to continue

Thanks.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
