### ISSUE TITLE
@types/paho-mqtt should be updated to 1.1

### ISSUE THREAD

**Issue by adenysen** [DefinitelyTyped/DefinitelyTyped#32686]
- [X] I tried using the `@types/paho-mqtt` package and had problems.
- Authors: @andy-ms 

I tried using the most recent version of the typings for paho-mqtt and had issues because version 1.1 of paho-mqtt has changed their namespaces - see [paho-mqtt breaking changes note](https://github.com/eclipse/paho.mqtt.javascript#breaking-changes) .  Can these typings be updaed to reflect 1.1?

**Comment by andy-ms** [comment]
PRs accepted.

**Comment by lann** [comment]
I spent a little time trying to do this, but it isn't clear how to make it work with the tooling:

* paho-mqtt 1.1 makes a major breaking change (new namespace) from 1.0 despite being a "minor" revision
* clearbladejs-client depends on paho-mqtt 1.0
* types-publisher barfs if I try to keep 1.0 around in a subfolder (`types/paho-mqtt/v1.0`)

Obviously, paho-mqtt making a breaking change in a minor revision is a problem here, but it seems like this must be a pretty common issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
