### ISSUE TITLE
@types/mini-css-extract-plugin not compatible with webpack 4

### ISSUE THREAD

**Issue by junalmeida** [DefinitelyTyped/DefinitelyTyped#32680]
- [x] I tried using the `@types/xxxx` package and had problems.

![image](https://user-images.githubusercontent.com/991675/52078122-9b670000-2579-11e9-85de-a00e332516f5.png)

https://www.npmjs.com/package/@types/mini-css-extract-plugin

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
