### ISSUE TITLE
[react] Lifecycle methods arguments have missing types

### ISSUE THREAD

**Issue by infctr** [DefinitelyTyped/DefinitelyTyped#32705]
- [x] I tried using the `@types/react@16.7.22` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Kovensky @pshrmn 

The types for lifecycle methods are clearly there with passed down parameters, but arguments in a declared class still have type `any`. What am I missing?

```ts
// from index.d.ts

interface Component<P = {}, S = {}, SS = any> extends ComponentLifecycle<P, S, SS> { }
```

defaultProps are not type checked either. Writing types manually gets really annoying when React specific props are accessed

```ts
export interface Props {
  name: string;
}

export class Greet extends React.Component<Props> {
  static defaultProps = { name: 123 }; // no-error, `name` type should be used from Props

  componentWillReceiveProps(nextProps: Props) {
    const children = nextProps.children; // Property 'children' does not exist on type 'Props'.ts(2339)
  }

  componentDidUpdate(prevProps) {
    const prop = prevProps.prop; // no error, `prevProps` has type any
  }

  render() {
    const { name } = this.props;

    return <div>Hello ${name.toUpperCase()}!</div>;
  }
}
```

```
    "@types/react": "^16.7.22",
    "react": "^16.7.0",
    "typescript": "3.2.4"
```

[repro link](https://github.com/infctr/repro-react-lifecycle-types)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
