### ISSUE TITLE
[@types/jest-image-snapshot] wrong type definition for toMatchImageSnapshot()

### ISSUE THREAD

**Issue by MacZel** [DefinitelyTyped/DefinitelyTyped#32760]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dawnmist
_____________________________________

Type definition is wrong for toMatchImageSnapshot()
When run with custom configObject:
```
expect(snapIphone).toMatchImageSnapshot({
    customSnapshotIdentifier: 'index_iphone'
})
```
I do get typescript compiler error:
`[ts] Expected 0 arguments, but got 1.`

Temporary workaround: `// @ts-ignore`

**Comment by dawnmist** [comment]
I've created a pull request to fix the ability to specify options for `toMatchImageSnapshot` directly (and add new options to the list), however in the mean time you can use the older `configureToMatchImageSnapshot` way to define the test with type safety if you wish instead of having to use `ts-ignore`:

```javascript
import { configureToMatchImageSnapshot } from 'jest-image-snapshot';

it('Should match index', () => {
  // take snapIphone..., then:
  const toMatchImageSnapshot = configureToMatchImageSnapshot({
    customShapshotIdentifier: 'index_iphone'
  }); 
  expect.extend({ toMatchImageSnapshot });
  expect(snapIphone).toMatchImageSnapshot();
});
```

Hopefully the pull request won't take a long time to be passed through DT. :)

**Comment by MacZel** [comment]
fixed, thank you ;)
