### ISSUE TITLE
@types/lolex version broken

### ISSUE THREAD

**Issue by thejohnfreeman** [DefinitelyTyped/DefinitelyTyped#32769]
Something happened that sent the last published version of `@types/lolex` to 0.0.0: https://www.npmjs.com/package/@types/lolex

It was last updated in this PR that was merged 2019-02-03 (yesterday as of this writing): https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30309

@zyishai @JoshuaKGoldberg

**Comment by dasa** [comment]
Could it be because the version is just `3` instead of `3.0`?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
