### ISSUE TITLE
[@types/styled-components] Error with @material-ui/core

### ISSUE THREAD

**Issue by goodmind** [DefinitelyTyped/DefinitelyTyped#32765]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek 

If you do not mention the authors the issue will be ignored.

```ts
import styled from 'styled-components'
import {Button} from '@material-ui/core'

const StyledButton = styled(Button)`
`

const test = <StyledButton color="inherit">Click</StyledButton>
```

Dependencies:
```json
"@material-ui/core": "^3.9.2",
"@types/styled-components": "^4.1.8",
```

```
[ts] Type '{ children: string; color: "inherit"; }' is missing the following properties from type 'Pick<Pick<(ButtonProps & RefAttributes<Component<ButtonProps, any, any>>) | (ButtonProps & { children?: ReactNode; }), "form" | "style" | "title" | "disabled" | "mini" | ... 279 more ... | "variant"> & Partial<...>, "form" | ... 283 more ... | "variant">': style, classes, className, innerRef, and 2 more. [2740]
```

**Comment by Grmiade** [comment]
I have a relatively close issue since TypeScript 3.3.1
`Property 'children' does not exist on type 'IntrinsicAttributes & Pick<Pick<Pick<IDialogProps & RefAttributes<Dialog>, "key" | "ref"> & Partial<Pick<IDialogProps & RefAttributes<Dialog>, "style" | "title" | ... 21 more ... | "className">> & Partial<...>, "style" | ... 24 more ... | "ref"> & Partial<...>, "style" | ... 24 more ... | "ref"> & { ...; } & { ...; }'.`

It seems styled-components typings is broken :/
Maybe this fix in emotion-js could be help: https://github.com/emotion-js/emotion/pull/1194/files

**Comment by nlindroos** [comment]
Any update on this @Igorbek?

**Comment by nlindroos** [comment]
At the moment, we suppress these warnings in our project by setting the styled component's type to `StyledComponent<any, any>`, which is obviously not the best approach.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
