### ISSUE TITLE
Types error with React.cloneElement and React.Children.only

### ISSUE THREAD

**Issue by tleunen** [DefinitelyTyped/DefinitelyTyped#32797]
If you know how to fix the issue, make a pull request instead.

I have a code which does this:
```ts
    const onlyChild = React.Children.only(props.children);
    return React.isValidElement(onlyChild)
      ? React.cloneElement(onlyChild, {
          className: classNames(onlyChild.props.className, className),
        })
      : null;
```

But typescript is complaining on the line with `className: ...` with this:
```
[ts]
Argument of type '{ className: string; }' is not assignable to parameter of type 'Partial<{}> & Attributes'.
  Object literal may only specify known properties, and 'className' does not exist in type 'Partial<{}> & Attributes'. [2345]
```

So it looks like it doesn't know that the props of onlyChild extends HTMLElement? or `Attributes` are not even used here?

@Jessidhia - Would you know why by any chances?

**Comment by Lehakos** [comment]
Ping

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
