### ISSUE TITLE
joi ValidationOptions

### ISSUE THREAD

**Issue by rickhoro** [DefinitelyTyped/DefinitelyTyped#32795]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by rickhoro** [comment]
For @types/joi@14.3.1, ValidationOptions is defined in index.d.ts. ValidationOptions is missing the following three properties (these are defined in schema.js):

```
/** Missing from the Joi API doc */
raw: Joi.boolean();
/** when true, do not apply default values. Defaults to false. */
noDefaults: Joi.boolean();
/** when true, error message templates will escape special characters to HTML entities, 
for security purposes. Defaults to false */
escapeHtml: Joi.boolean();
```

This results in typescript compilation errors when any of these options are specified in an application. Would appreciate if someone who is already conversant with how to issue a pull request can offer this fix.

Please note that the definition for "raw" is not currently in the Joi API docs.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
