### ISSUE TITLE
@types/inquirer `Property 'ui' does not exist on type 'Promise<{}>'`

### ISSUE THREAD

**Issue by ambiguities** [DefinitelyTyped/DefinitelyTyped#32817]
- [X] I tried using the `@types/inquirer` package and had problems.
- [X] I tried using the latest stable version of [tsc](https://www.npmjs.com/package/typescript).
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [X] I have [listed the authors](https://github.com/blog/821-mention-somebody-they-re-notified): 
  @tkqubo @ppathan @jouderianjr @bang88 @bitjson @synarque @jrockwood @kwkelly @Ailrun 

### Problem:
  Although it still compiles with tsc and will run, it will incorrectly provide what is available in a IDE such as VS Code.

When you hover over `.ui.` in VS Code it will report: 
```
[ts] Property 'ui' does not exist on type 'Promise<{}>'. [2339]
any
```
### Example:
```ts
import * as inquirer from 'inquirer'; // 6.2.0
import { Subject } from 'rxjs'; // 5.5.12

const prompts: any = new Subject();
let i = 0;

const question = (): any => {
  ++i;
  return {
    type: 'input',
    name: `question-${i}`,
    message: 'Continue? (y,n)',
    default: i,
    validate: (answer: string): boolean => answer.toLowerCase() === 'y' || answer.toLowerCase() === 'n',
  };
};

inquirer.prompt(prompts).ui.process.subscribe(
  (result: any): void => {
    console.log(result);
    result.answer.toLowerCase() === 'n' ? prompts.complete() : prompts.next(question());
  },
  (error: Error): void => { console.error(error); },
  (): void => { console.log('complete'); },
);

prompts.next(question());

```
### Notes:
- **ts-node will not run the ts file because of the incorrect type definition.**
- **please version @types/inquirer so that it matches the InquirerJS version it is tested against.**

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
