### ISSUE TITLE
[@types/react-bootstrap-typeahead]

### ISSUE THREAD

**Issue by arichter83** [DefinitelyTyped/DefinitelyTyped#32822]
Dear @dalevfenton,  

1.) I made a PR to @types/react-bootstrap-typeahead and would be happy if you have a short look: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32809

It's based on https://github.com/ericgio/react-bootstrap-typeahead/blob/4537b2522854431f67732c9cbddd9ce5bffbc958/src/containers/typeaheadContainer.js#L141 and could also be more explicit, with something like this (but I couldn't get it working):

```
export type TypeaheadResultNew<T extends TypeaheadModel> {
  customOption: boolean;
  id: string;
  TypeaheadLabelKey<T>: string
}
export type TypeaheadResult<T extends TypeaheadModel> = T | TypeaheadResultNew<T>;
```

2.) I have a problem with the labelKey, which I don't understand. I have an:

```
interface ITag {
  name: string
  ...
}

var Tags:Mongo.Collection<ITag> = new Mongo.Collection('tags');
var options:ITag[] = Tags.find();
```

And when using `<Typeahead labelKey="name" options={options} ... />` I get the following error:

```
imports/ui/CreateQuestion.tsx:143: Type '{ ref: RefObject<Typeahead<ITag>>; labelKey: string; options: ITag[]; multiple: true; caseSensiti...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Typeahead<ITag>> & Readonly<{ children?: ReactNode...'.
  Type '{ ref: RefObject<Typeahead<ITag>>; labelKey: string; options: ITag[]; multiple: true; caseSensiti...' is not assignable to type 'Readonly<TypeaheadProps<ITag>>'.
    Types of property 'labelKey' are incompatible.
      Type 'string' is not assignable to type '"name" | ((option: ITag) => string)'.
```

Why can't "name" be assigned? It seems to works fine in the test case you provided.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
