### ISSUE TITLE
JSX element type 'ReactTable' does not have any construct or call signatures.

### ISSUE THREAD

**Issue by mahesh8488** [DefinitelyTyped/DefinitelyTyped#32845]
I tried the typescript demo file: react-table-tests.tsx under https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table.

**Comment by Fosol** [comment]
Ran into the same issue...

**Comment by iliophanis** [comment]
have you find any solution for this error when use in typescript why dont let us use ???

**Comment by Chrossu** [comment]
Hi, I fixed this issue using the same version of react-table and @types/react-table. Previously I was using 6.8.7 version of react-table but something of **>** 7.x.x @types/react-table version. Using same versions solved this error

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
