### ISSUE TITLE
Error with @types/node-forge addSigner function

### ISSUE THREAD

**Issue by loaiShaheen** [DefinitelyTyped/DefinitelyTyped#32869]
when using @types/node-forge and trying to use the addSigner function with the following code: 

```
const key = forge.pki.decryptRsaPrivateKey(forge.pem.encode(signerKeyMessage))

p7.addSigner({
    key,
    certificate,
    digestAlgorithm: forge.pki.oids.sha1,
    authenticatedAttributes: [
      {
        type: forge.pki.oids.contentType,
        value: forge.pki.oids.data,
      },
      {
        type: forge.pki.oids.messageDigest,
      },
      {
        type: forge.pki.oids.signingTime,
      },
    ],
  })
```

It gives the following error:
> Type 'PrivateKey' is not assignable to type 'string'

key is of type PrivateKey, and if i try to turn it into a string and pass it to addSigner I get the following error when I run the code:

> Invalid PEM formatted message

**Comment by loaiShaheen** [comment]
@westy92 @Apologiz 

Can you please look into this.
Thank you for your help.

**Comment by westy92** [comment]
Looking at the types, it looks like a fix may be changing the `key` type from `string` to `PrivateKey | string`. at: 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-forge/index.d.ts#L532

Code where `string` is converted to `PrivateKey` if necessary: https://github.com/digitalbazaar/forge/blob/d2940f468f251f42a5447ff22042ad7668f5b3ea/lib/pkcs7.js#L265-L267

Please test these changes locally, and if correct, submit a PR.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
