### ISSUE TITLE
IndicesExistsAliasParams extends IndicesExistsParams without making `index` optional

### ISSUE THREAD

**Issue by robdasilva** [DefinitelyTyped/DefinitelyTyped#32867]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CasperSkydt @bfsmith @ddunkin @pushplay @mlamp @ahmadferdous @SimonSchick @brabster @deerawan

Elasticsearch allows to check if an alias with a specified name exists by using `indices.existsAlias`. This function expects a parameter object with only one required property, namely `name`, which is the name of the alias to be checked.

The respective interface `IndicesExistsAliasParams` extends `IndicesExistsParams` however, which results in another property `index` being required in the parameter object, which it is not.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
