### ISSUE TITLE
[@types/react-redux]  connected component without own properties type issue

### ISSUE THREAD

**Issue by bojan-vujke** [DefinitelyTyped/DefinitelyTyped#32899]
If you know how to fix the issue, make a pull request instead.

- When there are all props defined in connect call type issue pops out. It seems to be requiring all props to be added on wrapper, both mapped state props and mapped dispatch props. Like in this [example](https://stackoverflow.com/questions/54574716/react-redux-connect-issues-with-ownprops-typescript). I tried to track it down and I believe this issue comes from InferableComponentEnhancerWithProps definition for last two cases of Connect interface. It always adds all properties to TNeedsProps. In order to avoid issues I have to overcome by exporting wrapper as ConnectedComponentClass<typeof Component, {}>

  - Authors: @tkqubo @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo @pdeva @Kallikrein @jrakotoharisoa @apapirovski @surgeboris @soerenbf

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
