### ISSUE TITLE
@types/express: 'static' modifier cannot appear on a type member

### ISSUE THREAD

**Issue by mhauens** [DefinitelyTyped/DefinitelyTyped#32905]
- [x] I tried using the `@types/express` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

  - Authors: @borisyankov 

``` javascript
ERROR in /node_modules/@types/express/index.d.ts(91,9):
TS1070: 'static' modifier cannot appear on a type member.
```

Definitions by:
``` javascript
interface Router extends core.Router {
    static push(arg0: string): any
}
```

using:
``` javascript
"express": "^4.16.4",
"next": "^7.0.2",
"react": "^16.8.1",
"@types/express": "^4.16.1",
"@types/next": "^7.0.9",
"@types/react": "^16.8.2",
"tslint": "^5.12.1",
"tslint-react": "^3.6.0",
"typescript": "^3.3.3",
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
