### ISSUE TITLE
EventsHash interface in backbone might need an update

### ISSUE THREAD

**Issue by jgonggrijp** [DefinitelyTyped/DefinitelyTyped#32910]
While working on #32909, I found this nugget in backbone.marionette:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/48cb1f507e1aeecafc2d6a1b5b13e2fb3c3fe3c2/types/backbone.marionette/index.d.ts#L388-L394

Perhaps this should be adopted in the backbone package as the base definition. However, I would need to study both Backbone and jQuery more to be able to decide on this.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @nvivo @kenjiru @jjoekoullas @zhamid @sventschui @razorness @confususs

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
