### ISSUE TITLE
[@types/next] DefaultDocumentIProps styles field

### ISSUE THREAD

**Issue by dandrei** [DefinitelyTyped/DefinitelyTyped#32932]
Hey everyone,

I'm running
- TS `3.2.1`
- Next.js `7.0.3`
- WebStorm `2018.3.3`

Here's the definition I'm having trouble with:

In:

     MyDocument.getInitialProps = (ctx): DefaultDocumentIProps => {

At:

     return {
             ...page,
             pageContext,
             // Styles fragment is rendered after the app and page rendering finish.
             styles:
                 <>
                     <style
                         id="jss-server-side"
                         // eslint-disable-next-line react/no-danger
                         dangerouslySetInnerHTML={{__html: css}}
                     />
                     {flush() || null}
                 </>
             ,
         };
Specifically, `style` gets underlined with the following message:

     TS2740: Type 'Element' is missing the following properties from type 'ReactNode[]': length, pop, push, concat, and 26 more.

Looks like for some reason, the type inferred for the `style` field is `Element`, while the expected one is `ReactNode[]` (if I'm reading it correctly).

What could be going on? The transpiled code works just fine, so it looks like it's a definition or inferring issue.

------------------------------------------------
- [x] I tried using the `@types/next` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dru89 @brikou @jthegedus @resir014 @scottdj92 @joaovieira @ajliv

If you do not mention the authors the issue will be ignored.

**Comment by scottdj92** [comment]
Hey there, do you have a repo where this is reproduced?

**Comment by dandrei** [comment]
Hi Scott, thanks for the prompt response.

Unfortunately I don't have a public repo where this is happening. But I expect it should behave the same in a new project when renaming `_document.js` to `document.tsx`. I can test it tomorrow.

When hovering over `MyDocument.getInitialProps` I get this: [https://i.imgur.com/c67ZAXw.jpg](https://i.imgur.com/c67ZAXw.jpg)

**Comment by joaovieira** [comment]
@scottdj92 it does seem `styles` could/should be of `React.ReactNode`. 

@dandrei does:

```js
styles: [
  <style
    key="jss-server-side"
    // eslint-disable-next-line react/no-danger
    dangerouslySetInnerHTML={{__html: css}}
  />,
  {flush() || null},
]
```

work out for you for the time being?

**Comment by dandrei** [comment]
@joaovieira no, actually the IDE was complaining about missing definitions for:

     import flush from 'styled-jsx/server';

so I commented it out with:

     // @ts-ignore

...because I didn't want to install a whole styles definition package (`@types/styled-jsx` ) just for one function.

**Comment by joaovieira** [comment]
It's been a while since I've looked into this. Actually, `styles` used to be a `React.ReactNode` (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/05406773b8929e49030fdf5266e4198e627454d9).

@elliottsj you changed it to a `React.ReactNode[]` in https://github.com/DefinitelyTyped/DefinitelyTyped/commit/e7bf02f9438a411536654b21b34bd4ae9f44b8db. That is the output of the `flushToReact` from `styled-jsx`, but it's not required to be that. That's just an implementation - the default implementation. The actually usage of styles [here](https://github.com/zeit/next.js/blob/v8.0.0/packages/next/pages/_document.js#L142) indicates it can be any node - including a fragment -, not necessarily an array.

**Comment by elliottsj** [comment]
@joaovieira Thanks for the patch. My original reason for making that change was based on the styled-components example Document: https://github.com/zeit/next.js/blob/80cb91ec87f6d193899c19faaa89f3cddd87da85/examples/with-styled-components/pages/_document.js#L18

Fix here: https://github.com/zeit/next.js/pull/6252

**Comment by joaovieira** [comment]
I see. I think this is only a TS issue though. So in plain JS, that is actually fine because you know that the return type of `Document.getInitialProps` is an array.

Our problem is that we use the same type `DefaultDocumentIProps` for both the class implementation and the interface that all Documents should adhere. `Document.getInitialProps` does return a `Array<React.ReactElement<any>>`, but subclasses can return more than that. I'm sure there's a way to accomplish this, but it's a head-scratcher... 🤕
