### ISSUE TITLE
[@types/tape] equality parameter type checking

### ISSUE THREAD

**Issue by taye** [DefinitelyTyped/DefinitelyTyped#32939]
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

I think it would be useful for the `t.equal(actual, expected)`, etc. methods to assert compatibility between the types of the actual and expected parameters. I've added such type assertions by extending the `tape.Tape` and `tape.Test` interfaces and I find it helpful in catching errors before even running my tests. https://github.com/taye/interact.js/blob/b2b5d39/test/test.ts.

Making this change could cause new errors in projects using the less specific typings, so I decided to open an issue before making a pull request.

@Bartvds @sodatea @DennisSchwartz @mikehenrty @rostrowski

:heart:

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
