### ISSUE TITLE
is-png "has no default export"

### ISSUE THREAD

**Issue by jameswilddev** [DefinitelyTyped/DefinitelyTyped#32983]
- [x] I tried using the `@types/is-png` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sandersn https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31208

I previously added type definitions for is-png, but they don't work when I try and use them now they've been published to NPM:

![image](https://user-images.githubusercontent.com/3138458/52617224-0e824780-2e93-11e9-9e7d-defb9e9ec585.png)

Seeking advice on how to correct this.

Previously asked on Gitter (no reply).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
