### ISSUE TITLE
[@types/styled-components] Dependency in @types/styled-components on @types/react-native causes issues with projects who depend on @types/node 

### ISSUE THREAD

**Issue by EdwardDrapkin** [DefinitelyTyped/DefinitelyTyped#33015]
This should be a peerDependency...

**Comment by riyunoa** [comment]
Can confirm that this is also an issue for me. I got the following error:
(207,13): Cannot redeclare block-scoped variable 'console'.

**Comment by danielgary** [comment]
Yes, I had to removed @types/styled-components from my repo until this is resolved

**Comment by Jessidhia** [comment]
"This should be a `peerDependency`" is true for pretty much all packages in DT that have interdependencies 😭

`*` versions are a hack.

Anyway, you can fix this locally by setting your `compilerOptions.types` in `tsconfig.json`. Set it to `[]`, or to `['node']`, or only to the list of types that need to be made automatically available without importing.

**Comment by gomezhyuuga** [comment]
Same issue here!

**Comment by svnv** [comment]
I also ran into this issue, but downgraded to `4.1.8`.

**Comment by bwlt** [comment]
The issue is that the package.json for published typings are automatically generated through the [type publisher](https://github.com/Microsoft/types-publisher); and it is [difficult to tweak](https://github.com/Microsoft/types-publisher/issues/431#issuecomment-363534033) with peerDependencies.
@Jessidhia solution worked for me, and in my opinion it is a valid solution because it overrides the default behaviour of the compiler, and the type definitions continue to works.
One thing to note: you have to add to `types` only dependencies which specify global types, in my specific case:
- node
- jest

Just check the error output of the compiler to understand which type should be added to this configuration.

Check [this section](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types) for further informations.

**Comment by devrelm** [comment]
Yup, this was introduced w/ 4.1.9 in #32843.

**Comment by bopfer** [comment]
I went with the `compilerOptions.types` change as well.  No issues now, and it seems like something that is a good idea to have anyway.

**Comment by JKillian** [comment]
Hmm sorry about causing this issue, didn't think about this side-effect. Glad to see that @Jessidhia's workaround resolves the issue in most cases. Happy to make a PR for a fix, but not sure what that would be, and @bwlt's links make it sound like there's no great solution at the moment.

Just in case it helps, here's some more info on the specific conflict in question: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15960

**Comment by StephenHaney** [comment]
So glad to find this thread, was wondering why I was getting an error related to Node / React-Native typings when I don't use React-Native.

This is potentially pretty wide ranging. Because react-scripts uses @types/node, I think all CRA TS apps will get this error if they turn skipLibCheck to false.

I tested this path:

```
npx create-react-app my-app --typescript
yarn add styled-components @types/styled-components
(Edited tsconfig to set skipLibCheck to false)
yarn run build

--> Failed. Cannot redeclare block-scoped variable 'console'
```

**Comment by brendanmc6** [comment]
@JKillian Indeed a fix would be much appreciated, as now the current version of @types/styled-components is incompatible with the [official create-react-app w/ typescript](https://facebook.github.io/create-react-app/docs/adding-typescript) setup.

My solution was to delete node_modules, lower the @types/styled-components version in package.json to 4.1.8 (most recent version before adding react-native), and reinstall.

Though the real problem is @types/react-native -- I simply don't have enough typescript knowledge to do a PR, it's unclear to me why the global types have been configured this way and what the side-effects might be. It was throwing compile errors related to `console`, `require`, and `geolocation`.

Here are some relevant tickets and PRs
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29795
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32843
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/26218
https://github.com/styled-components/styled-components/issues/1950
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24573

**Comment by fabb** [comment]
Should `@types/styled-components` be split up into 2 different typings, one for react and one for react-native?

**Comment by lewisflude** [comment]
That would be elegant!

@types/styled-components
And
@types/styled-components-native with all the native stuff.

**Comment by JKillian** [comment]
@fabb, it's tricky though because TypeScript uses the name in the import to figure out where to look up types. So even if we made `@types/styled-components-native`, when a user does `import { X } from 'styled-components/native';` TypeScript (essentially) looks for `@types/styled-components/native.d.ts` but not  `@types/styled-components-native`.

Now it's possible users could fix this with custom ['path mappings']( `@types/styled-components-native`), but that would be tricky to expect consumers to figure that out.

**Comment by erikdstock** [comment]
What is the status of this issue? I've had both the console import issue above and incorrectly failing `type-check` warnings across multiple (non-react-native) repos for several weeks now. It's nice to see they are part of the same issue, but aside from pinning to `4.1.8` is there an accepted workaround/tsconfig update for developers on this, or an update coming? (And thanks to those who have already done the work to document this!)

**Comment by fabb** [comment]
Hm, maybe add the typing files to the styled-components repo and set up dependencies properly there?

**Comment by fabb** [comment]
Or maybe remove the `require`s from the typings so the dependencies are not added to the generated package.json by the type publisher? Maybe add the peerDependencies to the `tsconfig.json` of the typings manually?

**Comment by mocantimoteidavid** [comment]
Hey guys!
I waited for the next release `4.1.13` to see if this issue would be fixed with it, but I see that it didn't.
I see that latest comment was 20 days ago. Is anyone looking into some more possible solutions?
For our project the solution with adding the `compilerOptions.types` wasn't really accepted. 
Indeed having so many types loaded (from react-native) that we never use doesn't really make sense.

**Comment by ryami333** [comment]
Confirmed still broken with `4.1.14`. Still pinned to `4.1.8`. Any resolution ahead?

**Comment by wKich** [comment]
I have same issue, but don't use styled-components. According to the `yarn.lock`, I receive `@types/node` from:
- `@types/glob@5.0.30`
- `@types/uuid@3.4.3`
- `dts-bundle@0.7.3`
- `parse5@3.0.3`
- `rollup@0.65.2`

**Comment by dotconnor** [comment]
The `@types/react-native` dependency also causes issues when using `"lib": ["dom"]`, throwing a `TS2300: Duplicate identifier` for serveral DOM APIs

<details>
<summary>Details</summary>

```
$ tsc
node_modules/@types/react-native/globals.d.ts:36:15 - error TS2300: Duplicate identifier 'FormData'.

36 declare class FormData {
                 ~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:5292:11
    5292 interface FormData {
                   ~~~~~~~~
    'FormData' was also declared here.
  node_modules/typescript/lib/lib.dom.d.ts:5302:13
    5302 declare var FormData: {
                     ~~~~~~~~
    and here.

node_modules/@types/react-native/globals.d.ts:81:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'body' must be of type 'string | ArrayBuffer | ArrayBufferView | Blob | FormData | URLSearchParams | ReadableStream<Uint8Array> | null | undefined', but here has type 'string | ArrayBuffer | DataView | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | Blob | FormData | null | undefined'.

81     body?: BodyInit_;
       ~~~~

node_modules/@types/react-native/globals.d.ts:107:14 - error TS2300: Duplicate identifier 'RequestInfo'.

107 declare type RequestInfo = Request | string;
                 ~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:18262:6
    18262 type RequestInfo = Request | string;
               ~~~~~~~~~~~
    'RequestInfo' was also declared here.

node_modules/@types/react-native/globals.d.ts:126:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'Response' must be of type '{ new (body?: string | ArrayBuffer | ArrayBufferView | Blob | FormData | URLSearchParams | ReadableStream<Uint8Array> | null | undefined, init?: ResponseInit | undefined): Response; prototype: Response; error(): Response; redirect(url: string, status?: number | undefined): Response; }', but here has type '{ new (body?: string | ArrayBuffer | DataView | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | Blob | FormData | null | undefined, init?: ResponseInit | undefined): Response; prototype: Response; error: () => Response; redirect: (url: ...'.

126 declare var Response: {
                ~~~~~~~~

node_modules/@types/react-native/globals.d.ts:196:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'abort' must be of type 'ProgressEvent', but here has type 'Event'.

196     abort: Event;
        ~~~~~

node_modules/@types/react-native/globals.d.ts:197:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'error' must be of type 'ProgressEvent', but here has type 'Event'.

197     error: Event;
        ~~~~~

node_modules/@types/react-native/globals.d.ts:198:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'load' must be of type 'ProgressEvent', but here has type 'Event'.

198     load: Event;
        ~~~~

node_modules/@types/react-native/globals.d.ts:199:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'loadend' must be of type 'ProgressEvent', but here has type 'Event'.

199     loadend: Event;
        ~~~~~~~

node_modules/@types/react-native/globals.d.ts:200:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'loadstart' must be of type 'ProgressEvent', but here has type 'Event'.

200     loadstart: Event;
        ~~~~~~~~~

node_modules/@types/react-native/globals.d.ts:201:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'progress' must be of type 'ProgressEvent', but here has type 'Event'.

201     progress: Event;
        ~~~~~~~~

node_modules/@types/react-native/globals.d.ts:202:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'timeout' must be of type 'ProgressEvent', but here has type 'Event'.

202     timeout: Event;
        ~~~~~~~

node_modules/@types/react-native/globals.d.ts:206:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'onabort' must be of type '((this: XMLHttpRequest, ev: ProgressEvent) => any) | null', but here has type '((this: XMLHttpRequest, ev: Event) => any) | null'.

206     onabort: ((this: XMLHttpRequest, ev: Event) => any) | null;
        ~~~~~~~

node_modules/@types/react-native/globals.d.ts:207:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'onerror' must be of type '((this: XMLHttpRequest, ev: ProgressEvent) => any) | null', but here has type '((this: XMLHttpRequest, ev: Event) => any) | null'.

207     onerror: ((this: XMLHttpRequest, ev: Event) => any) | null;
        ~~~~~~~

node_modules/@types/react-native/globals.d.ts:208:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'onload' must be of type '((this: XMLHttpRequest, ev: ProgressEvent) => any) | null', but here has type '((this: XMLHttpRequest, ev: Event) => any) | null'.

208     onload: ((this: XMLHttpRequest, ev: Event) => any) | null;
        ~~~~~~

node_modules/@types/react-native/globals.d.ts:209:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'onloadend' must be of type '((this: XMLHttpRequest, ev: ProgressEvent) => any) | null', but here has type '((this: XMLHttpRequest, ev: Event) => any) | null'.

209     onloadend: ((this: XMLHttpRequest, ev: Event) => any) | null;
        ~~~~~~~~~

node_modules/@types/react-native/globals.d.ts:210:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'onloadstart' must be of type '((this: XMLHttpRequest, ev: ProgressEvent) => any) | null', but here has type '((this: XMLHttpRequest, ev: Event) => any) | null'.

210     onloadstart: ((this: XMLHttpRequest, ev: Event) => any) | null;
        ~~~~~~~~~~~

node_modules/@types/react-native/globals.d.ts:211:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'onprogress' must be of type '((this: XMLHttpRequest, ev: ProgressEvent) => any) | null', but here has type '((this: XMLHttpRequest, ev: Event) => any) | null'.

211     onprogress: ((this: XMLHttpRequest, ev: Event) => any) | null;
        ~~~~~~~~~~

node_modules/@types/react-native/globals.d.ts:212:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'ontimeout' must be of type '((this: XMLHttpRequest, ev: ProgressEvent) => any) | null', but here has type '((this: XMLHttpRequest, ev: Event) => any) | null'.

212     ontimeout: ((this: XMLHttpRequest, ev: Event) => any) | null;
        ~~~~~~~~~

node_modules/@types/react-native/globals.d.ts:243:6 - error TS2300: Duplicate identifier 'XMLHttpRequestResponseType'.

243 type XMLHttpRequestResponseType = "" | "arraybuffer" | "blob" | "document" | "json" | "text";
         ~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:18436:6
    18436 type XMLHttpRequestResponseType = "" | "arraybuffer" | "blob" | "document" | "json" | "text";
               ~~~~~~~~~~~~~~~~~~~~~~~~~~
    'XMLHttpRequestResponseType' was also declared here.

node_modules/@types/react-native/index.d.ts:9385:18 - error TS2717: Subsequent property declarations must have the same type.  Property 'geolocation' must be of type 'Geolocation', but here has type 'GeolocationStatic'.

9385         readonly geolocation: Geolocation;
                      ~~~~~~~~~~~

node_modules/@types/react-native/index.d.ts:9388:11 - error TS2451: Cannot redeclare block-scoped variable 'navigator'.

9388     const navigator: Navigator;
               ~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:17847:13
    17847 declare var navigator: Navigator;
                      ~~~~~~~~~
    'navigator' was also declared here.

node_modules/typescript/lib/lib.dom.d.ts:5292:11 - error TS2300: Duplicate identifier 'FormData'.

5292 interface FormData {
               ~~~~~~~~

  node_modules/@types/react-native/globals.d.ts:36:15
    36 declare class FormData {
                     ~~~~~~~~
    'FormData' was also declared here.

node_modules/typescript/lib/lib.dom.d.ts:5302:13 - error TS2300: Duplicate identifier 'FormData'.

5302 declare var FormData: {
                 ~~~~~~~~

  node_modules/@types/react-native/globals.d.ts:36:15
    36 declare class FormData {
                     ~~~~~~~~
    'FormData' was also declared here.

node_modules/typescript/lib/lib.dom.d.ts:16941:11 - error TS2320: Interface 'Window' cannot simultaneously extend types 'GlobalFetch' and 'WindowOrWorkerGlobalScope'.
  Named property 'fetch' of types 'GlobalFetch' and 'WindowOrWorkerGlobalScope' are not identical.

16941 interface Window extends EventTarget, WindowTimers, WindowSessionStorage, WindowLocalStorage, WindowConsole, GlobalEventHandlers, IDBEnvironment, WindowBase64, GlobalFetch, WindowOrWorkerGlobalScope, WindowEventHandlers {
                ~~~~~~

node_modules/typescript/lib/lib.dom.d.ts:17847:13 - error TS2451: Cannot redeclare block-scoped variable 'navigator'.

17847 declare var navigator: Navigator;
                  ~~~~~~~~~

  node_modules/@types/react-native/index.d.ts:9388:11
    9388     const navigator: Navigator;
                   ~~~~~~~~~
    'navigator' was also declared here.

node_modules/typescript/lib/lib.dom.d.ts:18262:6 - error TS2300: Duplicate identifier 'RequestInfo'.

18262 type RequestInfo = Request | string;
           ~~~~~~~~~~~

  node_modules/@types/react-native/globals.d.ts:107:14
    107 declare type RequestInfo = Request | string;
                     ~~~~~~~~~~~
    'RequestInfo' was also declared here.

node_modules/typescript/lib/lib.dom.d.ts:18436:6 - error TS2300: Duplicate identifier 'XMLHttpRequestResponseType'.

18436 type XMLHttpRequestResponseType = "" | "arraybuffer" | "blob" | "document" | "json" | "text";
           ~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/react-native/globals.d.ts:243:6
    243 type XMLHttpRequestResponseType = "" | "arraybuffer" | "blob" | "document" | "json" | "text";
             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    'XMLHttpRequestResponseType' was also declared here.


Found 27 errors.
```
</details>

**Comment by lewisflude** [comment]
Reporting in that it’s also still broken for me using ‘4.1.14’.

**Comment by artyymcflyy** [comment]
I'm also using '4.1.14' and this is also still an issue for me.

**Comment by alloy** [comment]
As stated before [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015#issuecomment-463062037) and [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015#issuecomment-463985597), the current solution is to tell tsc to opt-in to types, rather than automatically using all types it finds in `node_modules/@types`.

I don’t think there’s any point in adding more noise about people still running into the issue when there is a workaround available, it will only make it harder for the next person to find the workaround. 

Additionally it looks like when this issue was created the template wasn’t followed and none of the maintainers got @’ed, so doing that now @Igorbek @Igmat @lavoaster @Jessidhia @jkillian @eps1lon @flavordaaave

**Comment by ryami333** [comment]
@alloy `workaround !== solution` - I don't want to (nor should I have to) use opt-in types. And, people reporting that the issue is still ongoing in subsequent releases is valid commentary.

**Comment by alloy** [comment]
@ryami333 Yup, you’re absolutely right, a single short update of it not working with the latest version is legit 👍 I expressed myself poorly when I said “not any point”.

For the record I don’t think you all should have to be satisfied with the status quo, but I worry that people that land here have a hard time understanding what they can do in the meantime with too much noise.

**Comment by fabb** [comment]
I‘d rather stick to `4.1.8` than introducing the maintenance burden of opt-in types using `compilerOptions.types`. I hope there is a proper fix for the problem before the typings diverge too much from newer lib versions.

**Comment by fabb** [comment]
Oh no, there is a performance regression from 4.1.1-4.1.12 in combination with TypeScript 3.4 😭
https://github.com/Microsoft/TypeScript/issues/30663

**Comment by m-rutter** [comment]
@alloy I'm not sure if you are a maintainer of these definitions, but what is the plan exactly with regards to closing this issue beyond having to educate TypeScript users about explict type inclusions? I think call that a solution is bad as the configuration is obscure, is painful to maintain because its a whitelist, and is very atypical across typescript typing packages. Documentation for this is also effectively hidden within the mountain of github issues in this repo.

At the moment locking 4.1.8 is not viable because of the reported severe performance regressions against it with recent versions of typescript. Do you recommend locking to an older version that 4.1.8?

**Comment by m-rutter** [comment]
If explict type incluson is the permament solution then there probably needs to be some coordinatation between this typing project and the offical styled-components documenation.

**Comment by EdwardDrapkin** [comment]
This sort of short-sightedness greatly increases the difficulty in using styled-components in react and react-native projects both.  I've been generally pleased with styled-components, but if this is still an issue the next time we have a new react project, styled-components won't be on the options list.  This has caused a ton of problems, including the seniors on the team having to investigate this issue and now we're burdened with whitelisting a bunch of types, which has caused a ton of friction over time.  This isn't just a bad decision, this is a decision that has decidedly effected our productivity on our team, and I can't in good faith recommend anyone use styled-components as long as something as trivial as the type definitions causes this much friction.  

There are plenty of ways to solve this problem that are apparently not even being considered.

1. Publish `@types/styled-components` with two sets of versions `X.Y.Z` and `X.Y.Z-rn` so that react-native users (a decidedly smaller portion of the styled-components community) can just install the react-native version instead of the node version.  The NPM registry has supported labels for years.

2. Publish `@types/styled-components` and `@types/styled-components-rn` and teach people to use package aliasing (available in both npm and yarn): `yarn add / npm i @types/styled-components@npm:@types/styled-components-rn`.

3. Refactor the type definitions so they need neither the node nor react-native dependencies in the first place.

There are solutions to this problem and the maintainers throwing their hands up in the air and forcing users down an expensive, esoteric configuration rabbit hole is more than enough reason to no longer use styled-components in my book.

**Comment by airhorns** [comment]
It's up to you if you want to use code from the volunteer run `styled-components` or volunteer run DefinitelyTyped repo and threats to not use the project aren't going to make anyone want to do free work for you. Right in the license it says the software is provided as is without warranty of any kind. 

If you think you have a solution, why not prepare a PR? Thats how this repo has come to be and how it will continue to benefit the community.

**Comment by fabb** [comment]
I like suggestion 1. Who would need to approve to make such a change?

**Comment by mariusmarais** [comment]
Can someone weigh in on whether a peerDependency would solve this issue (as per the original text above)? Depending on your exact viewpoint, that might be a more lightweight option?

**Comment by mariusmarais** [comment]
Also, can we maybe move the performance issues to another bug and focus on the React Native types being included? :)

**Comment by m-rutter** [comment]
> 
> 
> Also, can we maybe move the performance issues to another bug and focus on the React Native types being included? :)

That's already captured in other issues and a fix has already been merged in the most recent version of @types/styled-components. I was mere making reference that previous advice to lock to 4.1.8 is probably undesirable now while this performance regression is in place.

**Comment by eps1lon** [comment]
> There are solutions to this problem and the maintainers throwing their hands up in the air and forcing users down an expensive, esoteric configuration rabbit hole is more than enough reason to no longer use styled-components in my book.

You are mixing 3 different groups that affect the quality of styled-components:

- the maintainers of the implementation
- the maintainers of the types
- the maintainers of DefinitelyTyped that are responsible for publishing

Neither of these groups has direct influence on the other. Type maintainers are well aware that some types should be (optional) peer dependencies. This is a well known issue that is unresolved. It is neither the direct fault of styled-component maintainers nor type maintainers. Optional peer dependencies isn't even something supported in npm.

There's a similar issue with react-dom typings: #21310. And there are likely many more issues similar to this one e.g. Microsoft/TypeScript#18588

Publishing a different package seems fine but is also shortsighted because every package under in the `@types` namespace should have a matching npm package.

The easiest solution is probably to have a postinstal step that removes `@types/react-native`. If somebody can create a clonable repository that illustrates the issue I can play around with different workarounds and we can have a look what suites you best.

**Comment by m-rutter** [comment]
@eps1lon I think I definitely agree about the constraints around project responsibility and volunteerism that power this project and all of OSS. Some of the heat need to be take out of these conversations as everyone here is giving up their free time to make everyone's project better.

However, I think a big part of the frustration by users is that this change in 4.1.9 literately breaks all non-react native builds using the standard configuration recommended by the related [styled-components project documentation](https://www.styled-components.com/docs/api#typescript). This probably represents 90% of users of this package, but all the people tagged as "contributor" in this thread seem to be downplaying what amounts to a major breaking change requiring obscure compiler configurations, which has not been documented in any way. I think from the perspective of many users is that this change should have been reverted the moment its implications became apparent.

**Comment by eps1lon** [comment]
My intention was never to downplay the severity of this issue. I'm not affected so the last thing I'm going to do is tell everybody else how sever an issue is.

I just want to find a way how we can improve the current situation. It seemed like the conversation was steering towards either consumers blaming maintainers or contributors telling consumers to get over it. None of which helps anybody.

So help me help you. This means:
- provide a minimal repositor that:
  - describes what is expected
  - describes what happens instead
  - and how I can reproduce it with the given repository

Saying that
> This should be a peerDependency...

doesn't help because we all agree with this. It's just not actionable for us. We may however be able to improve the actual declarations. As I understand we should rather make the react-native support opt-in rather than opt-out (because react-native seems to be a less frequent use-case).

**Comment by StephenHaney** [comment]
> * provide a minimal repository that:
>   
>   * describes what is expected
>   * describes what happens instead
>   * and how I can reproduce it with the given repository

Hello! I created a repo with my example from this thread (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015#issuecomment-465338989)

Here's a link to the repo:
https://github.com/StephenHaney/types-example

This is a brand new TS Create React App, with nothing but styled-components installed. I just flipped "skipLibCheck" off to show the problem.

Try to run `yarn run build`... you'll get `Duplicate Identifier` from `node_modules/@types/react-native/globals.d.ts`.

**Comment by JKillian** [comment]
@EdwardDrapkin Thank you for your comment - while it comes across as a bit hostile, I do appreciate you trying to post ideas for practical solutions to the issue. Your three ideas were:

> 1. Publish @types/styled-components with two sets of versions X.Y.Z and X.Y.Z-rn so that react-native users (a decidedly smaller portion of the styled-components community) can just install the react-native version instead of the node version. The NPM registry has supported labels for years.

As far as I know, theres no way to do 1) within the current infrastructure. I doubt the TypeScript team has the bandwidth to add this feature (they're a surprisingly small team), but it's possible they'd accept a PR over at https://github.com/Microsoft/types-publisher if you're interested.

Similarly to your proposal, but operating within the current params of DT, every even patch version of `@types/styled-components` could support web and every odd version could support react-native. But that's a crazy maintenance burden and a crazy usage story. Also theoretically, there could be different _major_ versions of the package, one for web and one for react-native. But that's not how DT is defined to work and so it'd still be quite a weird usage story.

> 2. Publish @types/styled-components and @types/styled-components-rn and teach people to use package aliasing (available in both npm and yarn): yarn add / npm i @types/styled-components@npm:@types/styled-components-rn.

This is the idea that intrigues me the most. It's easily doable within the current limitations of DT (though I don't know if DT would necessarily allow it since it would mess things up for a future `styled-components-rn` package). It would be cool to then use TypeScript path mapping or something similar to automatically map imports from `styled-components/native` to `@types/styled-components-rn`.

I'd personally want to see a proof of concept of this before going down this path, but it seems like a possibility at least.

> 3. Refactor the type definitions so they need neither the node nor react-native dependencies in the first place.

I'm not sure how difficult this would be. I don't believe there's any easy way to drop the dependency on the `react-native` types, they're fairly integral to determining the correct prop types of the different helper functions. If you know a good way to do this though and keep functionality the same, a PR would be gladly accepted.

> There are solutions to this problem and the maintainers throwing their hands up in the air and forcing users down an expensive

This is not true though - I'm partially responsible for this issue people are having and I'd definitely like to see it resolved. It's obviously frustrating from an end-user perspective, I just don't know any easy solutions.

I will say this though: please don't think of it as a "maintainers" vs. "users" problem. There is no such distinction between "maintainer" and "user": "maintainers" are simply people who've hit issues with typings in the past and taken the time to make a PR to improve things, "users" are people who are going to do the same thing shortly 😉.

**Comment by JKillian** [comment]
@eps1lon with regards to your idea:

> The easiest solution is probably to have a postinstall step that removes @types/react-native

Do you mean as part of `@types/styled-components` or as part of the end-user application? If the former, I'd be surprised (and a bit worried) if DT lets you specify post-install scripts. If you mean the latter, I think it's definitely an alternative workaround for people who are facing these type conflicts. Not a final resolution, but one worth documenting at the least!

**Comment by eps1lon** [comment]
@JKillian At app level it should be a good enough workaround until we have explored alternative solutions. 

@StephenHaney Thanks. Will take a look.

**Comment by eps1lon** [comment]
A couple of interpretations of the issue:

1. TypeScript should not eagerly check library definitions if `skipLibCheck` is enabled. Even if the package isn't used typescript will check it and if you have some global declarations it creates conflicts where none are.

2. react-native typings shouldn't polute the global namespace. It sounds like it should rather be something declared in the lib compilerOption. Not sure if TypeScript supports custom lib files.

3. `skipLibCheck` can be disabled. I'm not sure I fully understand that option. They're already tested anyway and if it resolves unused types it can actively harm the types which is illustrated here.

4. Delete the `react-native` types if you don't need it. For `yarn` users this is as simple as creating a `.yarnclean` with the following content: `@types/react-native`. For other package managers you can create a `postinstall` step though you have to consider nested packages.

5. Remove the react-native support for styled-components types and offer 3rd party support outside of the `@types` namespace. Since I'm neither styled-components nor react-native user other people should chime in. If it's a feature that breaks the code 90% of the time we should get rid of it until we can find a better solution.

**Comment by alloy** [comment]
> @alloy I'm not sure if you are a maintainer of these definitions

@m-rutter I’m one of the maintainers of the react-native type defs, but alas I have to limit my time to reviewing PRs or fixing issues I (or my colleagues) run into ourselves.

> what is the plan exactly with regards to closing this issue beyond having to educate TypeScript users about explict type inclusions via issue tickets? I think that as a solution is bad as the configuration is obscure

We (my team) have opted to use explicit type inclusions and are fine with it as we understand it well by now, but I absolutely agree that that is not intuitive and I believe everybody involved would _like_ to see this changed.

FWIW I’m always open to reviewing PRs to the RN types that would make it easier for other type def packages to play nice together!

**Comment by GuillaumeDesforges** [comment]
Following [this example](https://github.com/sinnerschrader/feature-hub/pull/484/files#diff-0b57ba9f62edd23ad6769957a9249f2dR1), adding a `.yarnclean` file that contains `@types/react-native` fixed the issue.

**Comment by danielgary** [comment]
@GuillaumeDesforges great solution.  Thanks!

**Comment by alexandercerutti** [comment]
I also had to downgrade to 4.1.8 because newer types bring me to have non-existing problems with refs (other than this problem)

**Comment by jwalton** [comment]
> Publishing a different package seems fine but is also shortsighted because every package under in the @types namespace should have a matching npm package.

Well, that suggests a solution - we could just publish a `react-native-styled-components` package.  It could even include it's own types, and just leave @types out of it for the react-native folks.

**Comment by chetbox** [comment]
We found the `.yarnclean` hack didn't work with Electron Forge. For those still battling with this I recommend switching to `@emotion/styled`. It comes with Typescript type definitions, is smaller, and has the same API so migration is a piece of cake.

**Comment by SamHH** [comment]
@chetbox Is it possible to use that library without introducing Babel into the toolchain?

**Comment by chetbox** [comment]
@SamHH I believe so. We've used `@emtion/styled` imports as a drop-in replacement for `styled-components` imports in our React components and it's working really well. [The website](https://emotion.sh/docs/introduction) promises "Server side rendering with zero configuration."

**Comment by SamHH** [comment]
@chetbox On that page:

```
To make the css prop work with pure TypeScript (without babel plugin) you need to add /** @jsx jsx */ at the top of every file that is using the css prop:

[code block] /** @jsx jsx */

As a result you may be not able to use react fragment shorthand syntax - <></>, but still you can use <Fragment></Fragment>.
```

Not a drop-in replacement on that basis. :disappointed:

**Comment by bensaufley** [comment]
Definitely not a drop-in replacement. No support for `.attrs`, `css` is not generic, theming is different and not easily applied to `styled`… It's only drop-in insofar as it looks similar.

**Comment by jeremysabath** [comment]
Adding my voice to say @Jessidhia's solution was a life-saver for me. Thank you!

**Comment by pkieltyka** [comment]
why is this still not resolved after so many months?

**Comment by Mario-Eis** [comment]
> why is this still not resolved after so many months?

Unfortunately this is also holding us back on 4.1.8 in several projects. We do not use yarn. And it seems there is no workaround with npm so far.

**Comment by rvdende** [comment]
It took a while to figure out what was going on.. so I went back to get 4.1.18 (before react-native was added). And fixed theme provider children issue.

Here is the gist https://gist.github.com/rvdende/989151b6bb7872cd2d4ecb76a7a10306

Download the file and put it next to your .tsx files and name it typed_styled.d.ts 

Also remove your current type for styled-components

`npm uninstall @types/styled-components --save`

**Comment by Mario-Eis** [comment]
It seems with the new Typescript version 3.9.2 there is an error in version 4.1.8, the last working version of styled-component types for web projects.

```
ERROR in node_modules/@types/styled-components/index.d.ts(181,8):
TS2615: Type of property 'propTypes' circularly references itself in mapped type 'Pick<ForwardRefExoticComponent<WithOptionalTheme<Pick<any, Exclude<keyof ReactDefaultizedProps<StyledComponentInnerComponent<WithC>, ComponentPropsWithRef<StyledComponentInnerComponent<WithC>>>, StyledComponentInnerAttrs<...>
| ... 1 more ... | StyledComponentInnerAttrs<...>> | Exclude<...> | Exclude<...> | Exclude<...'.
```

In my opinion this ticket is now more important than ever.

**Comment by alloy** [comment]
Continued discussion for a builtin solution here: https://github.com/microsoft/TypeScript/issues/18588#issuecomment-628084656

**Comment by Dane2259** [comment]
@Mario-Eis have you find any solution or work around?

**Comment by xaun** [comment]
Yep still issues with this.

```
"@types/node": "^12.0.0",
"@types/styled-components": "^5.1.0",
"typescript": "3.5.2"
```

**Comment by seaneking** [comment]
Just chiming in to say that IMO specifying every type needed in your `types` array is not a solution to this issue. It's a workaround, and a single types package shouldn't force you to change the default behaviour for the ecosystem. Even the `excludeTypes` option proposed upstream is a workaround for a broken package.

**Comment by felschr** [comment]
Any updates on this?

**Comment by EdwardDrapkin** [comment]
For what it's worth, I migrated to emotion, in no small part because of this issue.  Someone should probably put a note in the styled-components documentation that its TS support is bonkers.

**Comment by orta** [comment]
Folks interested in this issue should ideally leave some feedback in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49914
