### ISSUE TITLE
[@types/pouchdb-find] Model as extra type in find calls

### ISSUE THREAD

**Issue by jlami** [DefinitelyTyped/DefinitelyTyped#33024]
- [x] I tried using the `@types/pouchdb-find` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @trubit @tiangolo

I would like the find calls to accept an extra Model as pouchdb get calls do.

```ts
db.get<SomeModel>(id);//returns SomeModel type
db.find(findOptions);//.docs are not of type SomeModel
```

You can start the whole db with a certain type. But find should be able to return different types of models.

I might have time to do a PR later, but this should be a simple fix like this:
```ts
find<Model>(request?: Find.FindRequest<Content>): Promise<Find.FindResponse<Content & Model>>;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
