### ISSUE TITLE
DataTables.net-errMode

### ISSUE THREAD

**Issue by cjpgaspar** [DefinitelyTyped/DefinitelyTyped#33039]
Using "@types/datatables.net" errMode is define as a string.

"....
declare namespace DataTables {
        interface ExtSettings {
                aTypes: any[];
                afnFiltering: any[];
                afnSortData: object;
                aoFeatures: any[];
                builder: string;
                classes: ExtClassesSettings;
                **errMode**: string;
.....
"

But in https://datatables.net/reference/option/%24.fn.dataTable.ext.errMode, is possible to define a function. 

So when I try to do:

$.fn.dataTable.ext.errMode = this.errMode; 
errMode (settings: any, helpPage: any, message: any ) {
      if (settings.jqXHR && settings.jqXHR.status !== 200) {
        ...
      }
}

I get:
Type '(settings: any, helpPage: any, message: any) => void' is not assignable to type 'string'.

How can I define a custom action when datatables return error?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
