### ISSUE TITLE
react-highlight-words import issue

### ISSUE THREAD

**Issue by damiangreen** [DefinitelyTyped/DefinitelyTyped#33050]
- [X ] I tried using the `@types/react-highlight-words` package and had problems.
- [X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X ] [Mention](https://github.com/mhegazy) (https://github.com/diogodca) (https://github.com/kellyrmilligan

These can't be imported correctly.

see https://github.com/bvaughn/react-highlight-words/issues/60

**Comment by damiangreen** [comment]
import * as Highlighter from 'react-highlight-words' // works but with warnings
import Highlighter from 'react-highlight-words' // blows up
import Highlighter from 'react-highlight-words' // doesn't work
const Highlighter = require('react-highlight-words') // works

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
