### ISSUE TITLE
@types/ramda - Typings do not work for composer function with groupBy and map

### ISSUE THREAD

**Issue by CodingPapi** [DefinitelyTyped/DefinitelyTyped#33056]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov  @jbaldwin  @ccurrens  @sandersn @Krantisinh 

say there is a listA: [ { key:"key1", val: "v1" }, { key: "key2", val: "v2"} ]

I'm trying to transform listA to an object: { "key1": {key: "key1", val: "v1"}, "key2": {key:"key2", val: "v2"}} with blow code

```
const composedData = R.compose(
   R.map(R.mergeAll),
   R.groupBy(R.prop('key')),
)(listA)
 ```

this code will throw   "Argument of type '(list: ReadonlyArray<{}>) => { [index: string]: {}[]; }' is not assignable to parameter of type '(x0: ReadonlyArray<{}>, x1: {}, x2: {}) => ReadonlyArray<{}>'.
  Type '{ [index: string]: {}[]; }' is missing the following properties from type 'ReadonlyArray<{}>': length, concat, join, slice, and 16 more."

**Comment by Justin-ZS** [comment]
It seems TS can't find a compatible type among multiple overload types.
An intersection type that should be compatible with the last one in overload types always throw an error since it is incompatible with the first one.

**Comment by Justin-ZS** [comment]
@types/ramda has too much incompatible type error with itself.
I have to remove it sadly.:confused:

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
