### ISSUE TITLE
@types/nightmare: switches constructor option not supported

### ISSUE THREAD

**Issue by Steffen911** [DefinitelyTyped/DefinitelyTyped#33062]
I tried to use the Nightmare constructor with switches like this:
```typescript
import * as Nightmare from "nightmare";

const nightmare = new Nightmare({ show: false, switches: { "ignore-certificate-errors": true } });

await nightmare
[...]
```

This fails with:
```
error TS2345: Argument of type '{ show: false; switches: { "ignore-certificate-errors": boolean; }; }' is not assignable to parameter of type 'IConstructorOptions'.
```

Although this is included as one of the examples in the [nightmare readme](https://github.com/segmentio/nightmare#switches). It directly passes the switches on to [electron](https://github.com/segmentio/nightmare/blob/master/lib/nightmare.js#L101) so I'm not sure if we can check what switches are valid.

One proposal would be to allow a switches object with any key-value combination.

@horiuchi @samyang-au @Bleser92 Could you have a look?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
