### ISSUE TITLE
@types/react-css-module doesn't work

### ISSUE THREAD

**Issue by AlvinYuXT** [DefinitelyTyped/DefinitelyTyped#33184]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-css-modules` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @KostyaEsmukov @skirsdeda @johnnyreilly @bbenezech 

I'm using ` @types/react-css-modules` version 4.6.1 and `@tyeps/react` version 16.8.3. 

Then the error comes 
`Property 'styleName' does not exist on type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.`

The reason is that `@types/react` add a new type `type DetailedHTMLProps<E extends HTMLAttributes<T>, T> = ClassAttributes<T> & E;`. 

But in `@types/react-css-modules`, it change the `HTMLAttributes` & `SVGAttributes`.

it seems like that when `DetailedHTMLProps` declared, the `HTMLAttributes` haven't combine the change in `@types/react-css-modules`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
