### ISSUE TITLE
Node Errors are not typed correctly

### ISSUE THREAD

**Issue by Almenon** [DefinitelyTyped/DefinitelyTyped#33217]
If you know how to fix the issue, make a pull request instead.
^ I would if I had the time :/ I might get to that later.

- [X] I tried using the `@types/node` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Microsoft @BrunoScheufler 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5565fe5e46e329a5ee02ddf739abe11bf16f278d/types/node/child_process.d.ts#L48

err should be typed as SystemError - see https://nodejs.org/api/errors.html#errors_system_errors

There are probably more places where it is not typed correctly,

You can see an example of where I ran into this issue in my project [here](https://github.com/Almenon/AREPL-vscode/blob/ccc13c0de823e43b5b864b318889805634a13c40/src/PreviewManager.ts#L129)

**Comment by SimonSchick** [comment]
I'm not sure that applies here, `SystemError` seems to be used very inconsistently across the code base, we have `ErrnoException` but it lacks a few of the properties that are specified in this spec.
It would be nice to know where exactly `SystemError` is used, otherwise typing their usage accurate is going to be a nightmare.
