### ISSUE TITLE
[@types/react] React.createElement doesn't type check children resulting in run-time error

### ISSUE THREAD

**Issue by gavinwahl** [DefinitelyTyped/DefinitelyTyped#33241]
`React.createElement('p', null, {x: 1})` should be a type error because React doesn't allow objects as children. Currently, it type checks and React raises "Objects are not valid as a React child (found: object with keys {x})"

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei @Jessidhia @pshrmn @threepointone

**Comment by ferdaber** [comment]
This is a known issue but simultaneously difficult to solve, because technically children can be anything, all rendering logic is deferred to the implementation of the component itself. This only raises a runtime error if the component renders its children as is, but if it's a render prop, for example, then children can validly be a function. In the case of something like i18next, children can also be plain objects.

**Comment by Jessidhia** [comment]
I have a solution in mind for it but it depends on https://github.com/Microsoft/TypeScript/pull/29818

**Comment by gavinwahl** [comment]
I see there's a different type definition for regular HTML elements, is it possible to just do it for that one?

**Comment by Jessidhia** [comment]
Not really because that still runs into a different problem (React.ReactNode includes {} in its type) 😥

**Comment by gavinwahl** [comment]
Does the type of children have to be ReactNode, or can we just define a new type that's the same but without {} for this purpose?

**Comment by ferdaber** [comment]
That's a very large breaking change that breaks a lot of people's reliance on the implicit `children` prop in `React.Component` and `React.FunctionComponent`, so I'm not comfortable making that change.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
