### ISSUE TITLE
[@types/lodash] head() does not result in something I can call .value() on when using a chain

### ISSUE THREAD

**Issue by BertusVanZyl** [DefinitelyTyped/DefinitelyTyped#33261]
Here is the first few lines from the lodash.d.ts file I am using for versioning info:
```
// Type definitions for Lo-Dash 4.14
// Project: http://lodash.com/
// Definitions by: Brian Zengel <https://github.com/bczengel>, Ilya Mochalov <https://github.com/chrootsu>, Stepan Mikhaylyuk <https://github.com/stepancar>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


/**
### 4.0.0 Changelog (https://github.com/lodash/lodash/wiki/Changelog)
```

On the lodash typing, this does not work:

`_.chain([1, 2, 3, 4]).head().value();`

On a chain, .head() does not return something that supports .value() to be called on it.

This works:
`(_.chain([1, 2, 3, 4]).head() as any).value();`

Casting to any, so that the underlying .value() can be called results in the correct value, which is 1.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
