### ISSUE TITLE
Error in TypeScript 1.3: An export assignment cannot be used in a module with other exported elements

### ISSUE THREAD

**Issue by n074v41l4bl34u** [DefinitelyTyped/DefinitelyTyped#3327]
Project does not compile in **VS 2013 Community + TypeScript 1.3.0.0** using _Type definitions for Knockout v3.2.0-beta_

source: https://github.com/borisyankov/DefinitelyTyped/blob/master/knockout/knockout.d.ts#L647

```
declare module "knockout" {
    export = ko; // <-- this line errors
}

declare var ko: KnockoutStatic;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
