### ISSUE TITLE
[@types/pino]: versioning issue

### ISSUE THREAD

**Issue by ralucas** [DefinitelyTyped/DefinitelyTyped#33289]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/pino` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @psnider @BendingBender @screendriver @paambaati @alferpal @mortiy

There seems to be an issue with the versioning of the @types/pino package.  The latest is listed as `5.8.5`, however there was a release of `5.20.0` about 6 months ago which takes precedence versioning wise, so if users are using `"@types/pino": "*"` they're getting the `5.20.0` version. Anyway that the latest can just be bumped to something higher.  Thanks.

Richard

**Comment by alferpal** [comment]
I don't think that those of us who have contributed definitions can do anything about what's published in npm under types.

Perhaps you could try to contact a maintainer?

**Comment by BendingBender** [comment]
@ralucas  Well, this is not a versioning issue. It's just nobody had the time/motivation to update `pino` types to be on par with the `5.20.0` version of the library. 

DefinitelyTyped is a community project, most types are contributed by external authors. So usually, if you want type definitions to improve you either wait or you contribute. I prefer contributing, but it's up to you to decide. Your contribution will certainly be welcome.

**Comment by Pegase745** [comment]
@BendingBender there is no version `5.20.0` of the library. It seems I've created a duplicate issue then

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
