### ISSUE TITLE
@types/ckeditor autocomplete textwatcher textmatch

### ISSUE THREAD

**Issue by uladzimir-miadzinski** [DefinitelyTyped/DefinitelyTyped#33305]
https://www.npmjs.com/package/@types/ckeditor

- [ x] I tried using the `@types/ckeditor` package and had problems.

I cant find types for CKEDITOR.plugins.autocomplete and CKEDITOR.plugins.textMatch CKEDITOR.plugins.textWatcher

can you update @types/ckeditor (ckeditor v4) for support this typings? or what should I do to make them working for me?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
