### ISSUE TITLE
This should be <SegmentedControlProps> not <SearchFieldProps>

### ISSUE THREAD

**Issue by dmaulik** [DefinitelyTyped/DefinitelyTyped#33328]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0d4dfe2e4642dccb8d078342f55bf125477f0b57/types/gestalt/index.d.ts#L941

**Comment by lurkshark** [comment]
Looks like this got fixed. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6e926863e4f727ae44332a7dcc11a45ea47f680c/types/gestalt/index.d.ts#L1394

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
