### ISSUE TITLE
@types/ramda - 0.26.x

### ISSUE THREAD

**Issue by kabo** [DefinitelyTyped/DefinitelyTyped#33347]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @donnut, @tycho01, @mdekrey, @mrdziuban, @sbking, @afharo, @teves-castro, @1M0reBug, @hojberg, @samsonkeung, @angeloocana, @raynerd, @googol, @moshensky, @ethanresnick, @leighman, @CaptJakk, @deftomat, @deptno, @blimusiek, @biern, @rayhaneh, @rgm, @drewwyatt, @jottenlips, @minitesh, @krantisinh

A bunch of stuff has been added and deprecated in 0.26.0, released on Nov 18, 2018. See https://github.com/ramda/ramda/issues/2702

Listing the function names here so that people searching for this later will find this issue.

 Added:

* `mergeLeft` and `mergeRight`
* `includes` - a renamed version of `contains`
* `hasPath`
* `thunkify`
* `then`
* `otherwise`
* `composeWith`
* `pipeWith`

 Removed:

* `memoize`, in favor of `memoizeWith`

 Deprecated:

* `merge` - in favor of new `mergeRight`
* `contains` - renaming to `includes`
* `composeP` - in favor of `composeWith(then)`
* `pipeP` - in favor of `pipeWith(then)`
* `composeK` - in favor of `composeWith(chain)`
* `pipeK` - in favor of `pipeWith(chain)`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
