### ISSUE TITLE
[@types/stripe]: Customer.retrieve missing deleted customer.

### ISSUE THREAD

**Issue by JustinTRoss** [DefinitelyTyped/DefinitelyTyped#33389]
Tagging authors per issue creation template: @wjohnsto @CodeAnimal @sampsonjoliver @LinusU @brannon @kkamperschroer @starhoshi @bruun @galtalmor @htunnicliff @squirly @tzarger

@types/stripe
`Customers.retrieve` returns `Stripe.customers.ICustomer` Interface and doesn't cover use-case in which a deleted customer is returned, as outlined in Stripe documentation.

![image](https://user-images.githubusercontent.com/17093532/53361800-756d1b00-38ed-11e9-825a-0e53573bd64b.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
