### ISSUE TITLE
[@types/react-select] `options` accepts anything

### ISSUE THREAD

**Issue by hgezim** [DefinitelyTyped/DefinitelyTyped#33430]
- [x] I tried using the `@types/react-select` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @claasahl @jonfreedman 

This doesn't show any errors but it's invalid and break on the browser:

`
<CreatableSelect
                  isMulti
                  onChange={this.onTagChange}
                  options={['1', '2', '3']}
                />
`

**Comment by robba86** [comment]
Me2

**Comment by VincentLanglet** [comment]
I have an error if I don't give correct option.

But in your example, Typescript can't infer the `OptionType`.
```
export default class Select<OptionType> extends React.Component<Props<OptionType>, State<OptionType>> {
```

A solution can be
```
export default class Select<OptionType extends SOMETHING> extends React.Component<Props<OptionType>, State<OptionType>> {
```

**Comment by jonfreedman** [comment]
I'm unclear as to what you're saying is invalid - I assume this is not working for you because you have not set getOptionValue / getOptionLabel e.g. https://codesandbox.io/s/react-codesandboxer-example-200ts

You are basically setting ```OptionType``` to string (it could be number) e.g. 
```<CreatableSelect<string> isMulti onChange={this.onTagChange} options={['1', '2', '3']} />```

I don't think there is any typing that will require getOptionValue and getOptionlLabel to be set if you're using an ```OptionType``` that isn't an object containing a ```value``` or ```label``` property respectively.

**Comment by juliencampion** [comment]
Having the same problem. @jonfreedman, the CodeSandbox link you posted works, but breaks when I change the `isMulti` prop to `false` in one of the two `Select`s. I am unable to select any of the three options.

I suspect this problem is related to `OptionType` being required to be an object in [the original types.js file](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/types.js#L4), and it only being a template parameter (without any constraint) [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/src/Select.d.ts#L232).

**Comment by juliencampion** [comment]
I'll mention the two additional authors since this issue was created: @Methuselah96 @thchia 

Thank you :)

**Comment by Methuselah96** [comment]
@juliencampion The select breaking when you change the `isMulti` prop to `false` seems to be a bug with `Creatable` in `react-select`, not a problem with the types.

**Comment by juliencampion** [comment]
I'm afraid I have to disagree. `CreatableSelect` works fine when `options` is a list of objects, like this:

```jsx
<CreatableSelect
  isMulti={false}
  getOptionLabel={v => v.text}
  getOptionValue={v => v.id}
  options={[{id: 1, text: "first text"}, {id: 2, text: "second text"}]}
/>
```

However it does not when `options` is a list of numbers or strings. This seems to agree with the definition of `OptionType` in [the original types.js file](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/types.js#L4), which requires it to be an object. This leads me to believe that `Select` and its variants are simply not designed to handle anything other than objects, and the definitions file here should reflect this fact.

**Comment by jonfreedman** [comment]
I have in fact asked this exact question of the authors but sadly no response: https://github.com/JedWatson/react-select/issues/3695

I'm semi-convinced that it's coincidence you can use the library with non-object types but it could be a breaking change for many if the types are changed to require an object type.

My 2c would be to enforce though.

**Comment by Methuselah96** [comment]
@juliencampion That makes sense. I assumed that other types were allowed beside objects, but it looks like the Flow types only allow for objects so we probably should too.

@jonfreedman I made [a PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38691) to make the change. Can you review it?
