### ISSUE TITLE
[@types/underscore] v1.8.10 throws error on basic pluck usage.

### ISSUE THREAD

**Issue by alignsoft** [DefinitelyTyped/DefinitelyTyped#33479]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/underscore ` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick

If you do not mention the authors the issue will be ignored.

After updating to the 1.8.10 version of @types/underscore (which didn't indicate any breaking changes), `_.pluck(object,'key')`; throws an `'Argument of type '"key"' is not assignable to parameter of type 'never'.'` error.

The syntax is, as far as I'm aware, correct. Am I missing something, or is this a bug? Thanks!

**Comment by MHeasell** [comment]
Oh, it looks like my patch breaks `pluck` when the first argument is of type `any` -- TypeScript fails to deduce the return type in this case and you get `never`.

I propose we revert my PR #33095 since this is probably a common scenario.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
