### ISSUE TITLE
DNSSEC fails for definitivelytyped.org "Could not establish a chain of trust to keys for definitelytyped.org".

### ISSUE THREAD

**Issue by douglasg14b** [DefinitelyTyped/DefinitelyTyped#33489]
When querying for definitivelytyped.org, DNSSEC validation fails, which for many strict DNS revolvers means that the address cannot be resolved...

This can be seen:
* https://www.dnslookup.org/definitelytyped.org/A/#dnssec
* https://dnssec-debugger.verisignlabs.com/definitelytyped.org

![image](https://user-images.githubusercontent.com/1400380/53607235-bcb80d80-3b72-11e9-93b5-18a3c2051b4a.png)

**Comment by ExE-Boss** [comment]
See&nbsp;also: http://dnsviz.net/d/definitelytyped.org/dnssec/

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
