### ISSUE TITLE
es6-promise - TypeScript 1.3 Update Request

### ISSUE THREAD

**Issue by coderfin** [DefinitelyTyped/DefinitelyTyped#3349]
It would be nice if the es6-promise.d.ts was updated to use the new TypeScript 1.3 tuple type features.

For example:

`function all<R, T>(promises: R): Promise<T>;`

This will allow code like the following to be written.

```
Promise.all<
    [Promise<Ooyala.OO>, Promise<Ooyala.VastAdsOptions[]>],
    [Ooyala.OO, Ooyala.VastAdsOptions[]]
>([
    OoyalaHelper.getOO(),
    OoyalaHelper.getVastAds()
]).then((results) => { }
```

`results` is now correctly typed as `results: [Ooyala.OO, Ooyala.VastAdsOptions[]]`.

`results[0]` type is `Ooyala.OO`.
`results[1]` type is `Ooyala.VastAdsOptions[]`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
