### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by rajivramv** [DefinitelyTyped/DefinitelyTyped#33501]
Generic type `'ReactElement<P>'` requires 1 type argument(s)

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9dceb6543243d786c478e24e057133b5e73c213a/types/recharts/index.d.ts#L174

**Comment by SimonSchick** [comment]
You completely ignored the issue template, how are we suppose to help?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
