### ISSUE TITLE
@types/ramda over does not allow changing type

### ISSUE THREAD

**Issue by martinhrvn** [DefinitelyTyped/DefinitelyTyped#33500]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @donnut @tycho01 @mdekrey @mrdziuban @sbking @afharo @tevers-castro @1M0reBug

Here is simple example, not sure if there is any workaround for this.
```
interface NumType {
  x: {y: number}
}
interface StringType {
  x: {y: string}
}

const item: NumType = {
  x: {
    y: 1
  }
}

const yLens = lensPath(['x','y'])

const convertToString = (item: NumType): StringType => over(yLens, toString, item)
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
