### ISSUE TITLE
JSX.Element interface lacks ref property

### ISSUE THREAD

**Issue by tobq** [DefinitelyTyped/DefinitelyTyped#33530]
Using the type [`react`](https://www.npmjs.com/package/@types/react).

@threepointone @pshrmn @Jessidhia @franklixuefei @hotell @pascaloliv @jrakotoharisoa @ferdaber @guilhermehubner @theruther4d @onigoetz @DovydasNavickas @tkrotoff @ericanderson @digiguru @pzavolinsky @bbenezech @johnnyreilly

With standard React, you can do:
```
const element = <Component ref={React.createRef()} />;
const component = element.ref.current;
```

Within typescript, element is an instance of `JSX.Element`.
But, `JSX.Element` doesn't _have_ a `ref` property

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
