### ISSUE TITLE
Error: Cannot find module 'bcrypt'

### ISSUE THREAD

**Issue by adamnator92** [DefinitelyTyped/DefinitelyTyped#33576]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DavidBR-SW

the bcrypt library is install success, but when i i tried to import bcrypt but it show me 
`
Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
`

**Comment by SimonSchick** [comment]
I don't think this is related to typescript/DT but a failure of installation of the bcrypt package itself.

**Comment by adamnator92** [comment]
@SimonSchick the installation is success and I'm able to view the package from `node_modules`

**Comment by SimonSchick** [comment]
Again, this has nothing to do with typings or TypeScript.
Node says it cannot find the module, check your folder structure.

**Comment by phgachoud** [comment]
@adamnator92 did u find a solution for that? I have the same issue in typescript after running

```npm install --save @types/bcrypt```
into my `class.ts`
```import bcrypt = require ('bcrypt')```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
