### ISSUE TITLE
@types/angular and typescript version

### ISSUE THREAD

**Issue by gadeynebram** [DefinitelyTyped/DefinitelyTyped#33575]
I have a project that is working on angular 1.5. Is there a way to know which minimum and/or maximum version that can be used with these definitions?

My package.json lists "@types/angular": "^1.5.23" as the current used version of @types/angular.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
