### ISSUE TITLE
[@types/node]`UnhandledRejectionListener` `reason` param type is incorrectly defined in 11.10.4

### ISSUE THREAD

**Issue by molant** [DefinitelyTyped/DefinitelyTyped#33636]
- [x] I tried using the `@types/11.9.5` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] Authors: @OliverJAsh, @Flarna, @SimonSchick, @jessetrinity, @j-olivera, @touffy

In PR #33189 the type of `UnhandledRejectionListener` `reason` param type got changed from `any` to `{} | null | undefined` by @OliverJAsh .

With this change now TS assumes that we will receive an empty object (if anything). A promise can be rejected by many reasons an in most cases this will not be the case. One could argue that it will be an `Error` but even that it's not guaranteed.

Example of code that was valid before but not now because `Property 'message' does not exist on type {}`

```ts
process.once('unhandledRejection', async (source) => {
    console.error(`Unhandled rejection promise:
    message: ${source.message}
    stack:
${source.stack}`);
    process.exit(1);
});
```

**Comment by OliverJAsh** [comment]
Hi @molant! The type we are now using, `{} | null | undefined`, is a ["poor man's `unknown`"](https://github.com/Microsoft/TypeScript/issues/26796#issuecomment-417773756). The Node types currently support TypeScript versions prior to the version which introduced the `unknown` type, thus we have to simulate this behaviour with `{} | null | undefined`.

With `unknown` and/or `{} | null | undefined`, you have to refine the type, so the type checker understands what type you're expecting:

``` ts
declare const unknown: unknown;
// aka
// declare const unknown: {} | null | undefined;

if (unknown instanceof Error) {
    unknown.message;
}
```

``` ts
process.once('unhandledRejection', async (source) => {
    if (source instanceof Error) {
        console.error(`Unhandled rejection promise:
        message: ${source.message}
        stack:
${source.stack}`);
       process.exit(1);
    }
});
```

For context, the old type `any` was far from ideal because it completely disables all type checking:

``` ts
process.once('unhandledRejection', (error) => {
    error.foo.bar.baz.bob // no compile time type error, but runtime type error!
});
```

This is why `unknown` should be preferred to `any`—it forces you to refine the type before you can safely access any properties.

**Comment by molant** [comment]
Thanks for the explanation!
I guess my frustration comes from this being a breaking change and not respecting semver, but that's what seems to happen with most of the types packages 😞

**Comment by OliverJAsh** [comment]
@molant I completely agree. I actually asked about that: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32835#issuecomment-461156576.
