### ISSUE TITLE
stripe: paymentIntents.cancel incorrectly requires more than 1 argument

### ISSUE THREAD

**Issue by SimonSchick** [DefinitelyTyped/DefinitelyTyped#33663]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/stripe` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @0xJoKe

If you do not mention the authors the issue will be ignored.

According to the docs `paymentIntents.cancel(...)` only requires the first argument, all others may be omitted, the current typings do not reflect that and I have to assume other functions you added are incorrect as well.

**Comment by 0xJoKe** [comment]
@SimonSchick Are you sure you mean `paymentIntents.update(...)`? Because I can see that the documentation's example for `paymentIntents.cancel(...)` omits the params, but I see no indication that this is the case for `paymentIntents.update(...)`.

As for the correctness of the documentations examples: I did not trust them, as they seem to be quite error prone. The `paymentIntents.update(...)` and `paymentIntents.confirm(...)` examples contain syntax errors, for example.

**Comment by SimonSchick** [comment]
Yea sorry, title is correct, text is not :)
