### ISSUE TITLE
stylelint: invalid createPlugin?

### ISSUE THREAD

**Issue by 43081j** [DefinitelyTyped/DefinitelyTyped#33665]
```ts
export function createPlugin(
    ruleName: string,
    plugin: (options: RuleOption[]) => (root: any, result: LintResult) => void,
): any;
```

now take a look at any rule in stylelint, or in any stylelint plugin, you will see something like this:

```ts
const rule = function(actual, options) {
  return (root, result) => {
    // ...
  };
}
```

Further, look at the stylelint docs:

```ts
module.exports = stylelint.createPlugin(ruleName, function(primaryOption, secondaryOptionObject) {
  return function(postcssRoot, postcssResult) {
    // ...
  };
}
```

Which means our interface is _quite_ wrong and should rather be:

```ts
export function createPlugin(
    ruleName: string,
    plugin: (primaryOption: any, secondaryOptions: RuleOption[]) => (root: any, result: LintResult) => void,
): any;
```

Will probably fix it myself unless anyone beats me to it.

cc @alan-agius4, @filipsalpe

**Comment by alan-agius4** [comment]
Hi, feel free to do a PR. kindly provide links to the relative documentation of stylelint in the PR as it will ease the PR review process.

**Comment by 43081j** [comment]
here you go:
https://stylelint.io/developer-guide/plugins/

the first example.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
