### ISSUE TITLE
vectorgrid for @types/leaflet

### ISSUE THREAD

**Issue by mkaa** [DefinitelyTyped/DefinitelyTyped#33671]
package: `@types/leaflet`
version: https://www.npmjs.com/package/@types/leaflet

i dont know how this works but can you add type def for leaflet.vectorgrid?

authors: @alejo90, @atd-schubert , @ronikar

**Comment by ronikar** [comment]
@mkaa `leaflet.vectorgrid` is a plugin, so you should create a new package. If you need an example, you can see the implementation for `leaflet.draw` [here](url).

**Comment by mkaa** [comment]
@ronikar  do you mean a new npm package?

**Comment by mkaa** [comment]
hmmm I tried to build my project in production and I get error stating 'vectorGrid does not exist on type project/node_modules/@types/leaflet/index'

**Comment by ronikar** [comment]
Yes, you should create a new package for  `leaflet.vectorgrid`
You should read the introduction about create a new package [here](https://github.com/DefinitelyTyped/DefinitelyTyped) . Then, for reference, look at the implementation of `leaflet.editable` [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/leaflet-editable) .

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
