### ISSUE TITLE
@types/bluebird v3.5.26 tsc errors

### ISSUE THREAD

**Issue by thewizarodofoz** [DefinitelyTyped/DefinitelyTyped#33680]
I am running `tsc` in my project with `@types/bluebird@3.5.26` installed.

`tsconfig.json` as follows:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "alwaysStrict": true,
    "importHelpers": true,
    "target": "es2017",
    "noImplicitAny": false,
    "sourceMap": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "allowJs": true,
    "preserveConstEnums": true
  },
  "exclude": [
    "public"
  ]
}
```

When running `tsc` the compiler throws error virtually **on every line** of `node_modules/@types/bluebird/index.d.ts`.

Created a [minimal project](https://github.com/thewizarodofoz/bluebird-tsc-errors) to isolate and demonstrate the issue.

@lhecker FYI

**Comment by lhecker** [comment]
It’s generally very helpful if you also specify the exact TypeScript version you‘re using in the issues you submit.
What’s the version you’re having this issue with?

The solution to your problem is to either upgrade your local TypeScript version (preferably 3.2) or downgrade the version of your type definitions.
Even if you downgrade you’ll probably not miss out anything: All changes to these typings in the last years only brought improvements for new TypeScript releases.

In the meantime I’ll make sure to fix [the invalid version spec](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/480aadcbb3d1225f1a8a768ecad4724ee454c97a/types/bluebird/index.d.ts#L5) in the next PR that’s submitted.

**Comment by lhecker** [comment]
Oh I just saw that your minimal project already specifies TypeScript 3.3. That's great.
Unfortunately it's still extremely likely you're using the wrong compiler.

Assuming you fix your `tsconfig.json` to have the settings your gave above and assuming you change your `app.ts` to read:
```ts
import * as Bluebird from "bluebird";

Bluebird.resolve(123);
```

Then you can run `./node_modules/.bin/tsc -p .` and you'll see it completes without errors.
Please check whether your editor is using the correct `tsc`. 🙂

**Comment by thewizarodofoz** [comment]
Sorry about this! I had `tsc v2.7.1` in my global folder.
I now see that in my CI build there are no errors (because it uses `node_modules/.bin/tsc` which is the latest version) and like you said - it works OK.

Thanks for the quick response.

**Comment by lhecker** [comment]
If this issue is resolved for you do you mind closing it?
