### ISSUE TITLE
ramda types: incorporate feedback from TS PR higher-order function type inference

### ISSUE THREAD

**Issue by KiaraGrouwstra** [DefinitelyTyped/DefinitelyTyped#33704]
The TypeScript PR at https://github.com/Microsoft/TypeScript/pull/30215 has uncovered some feedback for the Ramda types based on unit tests that turned out to fail with these changes. It would be great if these could be incorporated here. So pinging those unlucky enough to be on the list, including myself.

authors: @donnut @tycho01 @mdekrey @mrdziuban @sbking @afharo @teves-castro @1M0reBug @hojberg @samsonkeung @angeloocana @raynerd @googol @moshensky @ethanresnick @leighman @CaptJakk @deftomat @deptno @blimusiek @biern @rayhaneh @rgm @drewwyatt @jottenlips @minitesh @krantisinh

**Comment by googol** [comment]
Direct link to failing test log: https://typescript.visualstudio.com/TypeScript/_build/results?buildId=24299

**Comment by googol** [comment]
Looks like the biggest problem is the Evolve type, and I'm afraid I'm not equipped to handle it.
The `Evolvable<E>` type seems to resolve to `undefined` for any `E extends Evolver`.

Removing the `extends Evolver` contraint (and handling this constraint in the type body of `Evolvable`) would fix this, but causes other problems, with object literals (only known properties can be passed to object literals).
So this needs some better thought out fixing.

The other problems are trivial to fix (at least in the tests):
- The indexBy and times tests can be fixed by adding an explicit type argument. I would have thought though that in `R.times(R.identity)` the type parameter T would be hoisted from `R.identity` to the composition such that `R.times(R.identity): <T>(n: number) => T[]`, and similarly for `R.indexBy`. Is this an oversight in the HKT pr, or just a known limitation?
- The traverse test uses the wrong function to begin with, instead of `Array.of`, `Array.from` should be used

**Comment by tycho01** [comment]
the `evolve` issue seems addressed at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33785

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
