### ISSUE TITLE
[@types/sequelize] There is no NUMBER data type

### ISSUE THREAD

**Issue by teddy-codes** [DefinitelyTyped/DefinitelyTyped#33718]
As per: https://github.com/sequelize/sequelize/issues/7997#issuecomment-446538345, the number type exists here but is nowhere to be found within the docs.

The problem: `NUMBER` should be `INTEGER`.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b32ee2597779e6376db8c49e68d75c68e50b9287/types/sequelize/index.d.ts#L1943

**Comment by SimonSchick** [comment]
It's there:
```
> void(s = require('./'))
undefined
> s.DataTypes.NUMBER
Proxy [ { [Function: NUMBER] types: {}, key: 'NUMBER' },
  { apply: [Function: apply] } ]
> s.NUMBER
Proxy [ { [Function: NUMBER] types: {}, key: 'NUMBER' },
  { apply: [Function: apply] } ]
```

however we should probably not expose it since it's more of an abstract class.

**Comment by roberthmiller** [comment]
Yea, I don't think that it should be exposed. Should we change it to be INTEGER?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
