### ISSUE TITLE
@types/node-fetch has incorrect blob() type

### ISSUE THREAD

**Issue by pauldraper** [DefinitelyTyped/DefinitelyTyped#33721]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @torstenwerner, @nikcorg

The Body.blob() return type is given as Buffer, but that is incorrect.

```js
fetch('https://example.com').then(b => b.blob()).then(b => console.log(b.toString('binary')));
```

Expected: `'<!doctype html>...'`
Actual: `'[object Blob]'`

**Comment by nikcorg** [comment]
You're right, it is a `Blob`. Would you like to PR a fix?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
