### ISSUE TITLE
[@types/angular] (AngularJS) why do I need to register controllers with a ControllerConstructor?

### ISSUE THREAD

**Issue by crhistianramirez** [DefinitelyTyped/DefinitelyTyped#33749]
Without typescript I might have a controller that is a function and register it like so:

```javascript
angular.module('my-module', [])
    .controller('MyController', MyControllerFn);
```

It seems now however I have to provide a controller constructor:

```typescript
angular.module('my-module', [])
    .controller('MyController', () => MyControllerFn);
```

Why is this necessary?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
