### ISSUE TITLE
[@types/pdfjs-dist] GlobalWorkerOptions missing

### ISSUE THREAD

**Issue by oBusk** [DefinitelyTyped/DefinitelyTyped#33762]
- [x] I tried using the `@types/pdfjs-dist` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jbaldwin @1999

The new 2.0 definitions does not contain `pdfjsLib.GlobalWorkerOptions` at all. See 
* https://github.com/mozilla/pdf.js/blob/d587abbceb97008ed744261c219c90d3ce981f2b/examples/learning/helloworld.html#L22-L26
* https://github.com/mozilla/pdf.js/blob/d587abbceb97008ed744261c219c90d3ce981f2b/examples/webpack/main.js#L10-L12

The definitions also exports a const `PDFJS` which does not exist
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6a5529e838d9386fb6567296e84d945e25805281/types/pdfjs-dist/index.d.ts#L295

**Comment by 1999** [comment]
@oBusk I guess it's easier to drop a PR which adds the missing bits?

**Comment by oBusk** [comment]
The 2.0 definitions also incorrectly implements own Promise interface rather than using native.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/813999bd2b6b2c75dec22b5bba0b52c853af787c/types/pdfjs-dist/index.d.ts#L9-L15

Pdfjs uses native promises, see 

https://github.com/mozilla/pdf.js/blob/80135378cadd98b55a835446f0857e4bc30524e0/src/shared/util.js#L866

**Comment by sheikalthaf** [comment]
@oBusk @1999 Hi,

`renderTextLayer` i can't able to import from `pdfjs-dist`. Whether it is missing in `types` or i'm doing something wrong?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
