### ISSUE TITLE
[@types/stripe] Wrong return type for invoices.retrieveLines

### ISSUE THREAD

**Issue by brad-sobie** [DefinitelyTyped/DefinitelyTyped#33775]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:  @wjohnsto @CodeAnimal @sampsonjoliver @LinusU @brannon @kkamperschroer @starhoshi @bruun @galtalmor @htunnicliff @squirly @tzarger @saranshkataria @0xJoKe 

The return type for invoices.retrieveLines is `Promise<invoices.IInvoiceLineItem>`, but should be `Promise<IList<invoices.IInvoiceLineItem>>`. The return type for the callback is correct.

**Comment by toddrobinsonce** [comment]
@brad-sobie it looks like this was cleaned up by reacuna  in https://github.com/DefinitelyTyped/DefinitelyTyped/commit/3426c724886187726884efeb010e6cab059dea4c by 
Can this issue get closed?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
