### ISSUE TITLE
[@types/echarts] Types of property 'trigger' are incompatible.     Type 'string' is not assignable to type '"none" | "item" | "axis" | undefined'.

### ISSUE THREAD

**Issue by runner-mei** [DefinitelyTyped/DefinitelyTyped#33811]
````
57:7 Type '{ trigger: string; axisPointer: { textStyle: { color: string; }; }; }' is not assignable to type 'Tooltip'.
  Types of property 'trigger' are incompatible.
    Type 'string' is not assignable to type '"none" | "item" | "axis" | undefined'.
    55 |         },
    56 |       },
  > 57 |       tooltip: {
       |       ^
    58 |         trigger: 'axis',
````

**Comment by gino8080** [comment]
also property axis in not assignable

axis: 'x'

give error

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
