### ISSUE TITLE
[@types/pino] P has no exported member stdSerializers

### ISSUE THREAD

**Issue by Ethan-Arrowood** [DefinitelyTyped/DefinitelyTyped#33846]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @psnider @BendingBender @screendriver @paambaati @alferpal

If you do not mention the authors the issue will be ignored.

I'm working on a type definition file for Fastify logger. I want to reference the `stdSerializers` in the typings here but I'm getting the following error:
<img width="731" alt="Screen Shot 2019-03-13 at 11 16 05 AM" src="https://user-images.githubusercontent.com/16144158/54290875-190f2a00-4582-11e9-991b-493b1a412a31.png">

I thought an easy fix would be to just change `const` to `interface` (and update the `:` `;` characters too), but that breaks the tests:

<img width="754" alt="Screen Shot 2019-03-13 at 11 22 46 AM" src="https://user-images.githubusercontent.com/16144158/54291037-58d61180-4582-11e9-9bad-744eb951749f.png">

I'll keep working with this, but if any of the original authors have an idea it would be much appreciated thank you!

**Comment by Ethan-Arrowood** [comment]
Would this have something to do with the stdSerializers being imported from another module? https://github.com/pinojs/pino-std-serializers

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
