### ISSUE TITLE
CypressError: Timed out retrying: coordsHistory must be at least 2 sets of coords

### ISSUE THREAD

**Issue by mmsudy** [DefinitelyTyped/DefinitelyTyped#33893]
@brian-mann @jeniifer-shehane but cypress throwing en error like this 
![cypress](https://user-images.githubusercontent.com/48072687/54392903-61a41180-466e-11e9-9fdf-80358540abe8.PNG)

I tried to select all check box by using cy.get(div.class).click({multiple:true})
![multiselect](https://user-images.githubusercontent.com/48072687/54393298-6b7a4480-466f-11e9-8a2d-6bdaca5959fd.PNG)

#timed out retrying

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
