### ISSUE TITLE
@types/jest 'unwraps' are actually 'wraps'

### ISSUE THREAD

**Issue by burtek** [DefinitelyTyped/DefinitelyTyped#33969]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/706d838bd3437ec1f8495ff20b52e46eec8bcb8e/types/jest/index.d.ts#L591-L600

Should that really be `Matchers<Promise<R>>` or rather `Matchers` with main type of `Promise` generic? Sth like:

```ts
interface Matchers<R> {
    resolves: R extends Promise<infer T> ? Matchers<T> : Matchers<never>;
    rejects: R extends Promise<infer T> ? Matchers<T> : Matchers<never>;
}
```

I can prepare a PR for this, but just want to be sure I'm not missing a point here... I guess the best contributors to ask are @garbles for #16645 (and [this change](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16645/files#diff-4a4390f0b4b1f7ac085a3d127ce47adbR180)) and @andys8 for #27170 (and [this change](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/dfe05a96d68413ba114ff0bef1d0a95803f2fcf4#diff-4a4390f0b4b1f7ac085a3d127ce47adbR397))

CC other contributors: @NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @ahnpnl @joshuakgoldberg @UselessPickles @r3nya @hotell @sebald @antoinebrault

**Comment by garbles** [comment]
I _think_ the generic passed to the `Matchers` interface is meant to be the return of something like `toEqual()` and not the argument passed to `toEqual()`. `expect().resolves.toEqual()` returns a `Promise` which is why the definition is like this.

That said, unless something has changed in Jest very recently, these definitions are wrong because `expect().toEqual()` returns `undefined`. i.e. I'm pretty sure [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/706d838bd3437ec1f8495ff20b52e46eec8bcb8e/types/jest/index.d.ts#L495) needs to change the return type to `Matchers<void>` because the return type is not the same as the input to `expect`.

As present the following compiles and it is incorrect,

```ts
it('hmm?', () => {
  // value is actually `void` but the defs say that it's a number?
  const value: number = expect(1).toEqual(1);
});
```

**Comment by burtek** [comment]
Okay, so I guess whole package needs checking and re-writing. Not something I plan on having time to do in nearest future 😝

Thanks for clarification anyway.
