### ISSUE TITLE
cannot find namespace 'Cesium'

### ISSUE THREAD

**Issue by CHBaker** [DefinitelyTyped/DefinitelyTyped#33985]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

@Aigars Zeiza <https://github.com/Zuzon>
@Harry Nicholls <https://github.com/hnipps>
@Jared Szechy <https://github.com/szechyjs>
@Radek Goláň jr. <https://github.com/golyalpha>

Cesium 1.55.0
types/cesium 1.54.2
Angular 7.02

Types worked well until recently (intellisense, auto complete, etc). I have diffed my files, no configurations or typings have changed, it just stopped working. I'm not sure what happened, but I'm getting the posted error

> cannot find namespace 'Cesium'

I have recreated the error here: https://github.com/CHBaker/Typings-Cesium-reprod-error

**Comment by CHBaker** [comment]
I can get it working again if I add `import * as Cesium from 'cesium'` to the top of each file. but the example says that shouldn't be necessary. it says I should be able to just npm install and it works. (which it did work, for a couple days, I can't figure out how it changed)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
