### ISSUE TITLE
@types/lodash@4.14.123 throws an error

### ISSUE THREAD

**Issue by adrianpoplavsky** [DefinitelyTyped/DefinitelyTyped#34006]
- [X] I tried using the `@types/lodash` package and had problems.

@types/lodash version 4.14.123 breaks the build for objects of type ANY, when non-declared properties are used. The reason for creating this issue is that 4.14.122 doesnt break, so it seems a change that is not a PATCH has been incorporated in .123, as per SEMVER:

For example, with code:
anAnyObject.fieldNames = 'field1';
anAnyObject.customPostRawDataTransform = 'another property';

the following errors are thrown:
- error TS2339: Property 'fieldNames' does not exist on type 'object'.
- error TS2339: Property 'customPostRawDataTransform' does not exist on type 'object'.

@jonmagic

**Comment by Feling** [comment]
You have a version of @types/lodash that needs minimum typescript 2.8.
[https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33845](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33845)

**Comment by adrianpoplavsky** [comment]
> You have a version of @types/lodash that needs minimum typescript 2.8.
> #33845

no. 
> npm list @types/lodash
 `-- @types/lodash@4.14.122
> npm list typescript
+-- @angular-devkit/build-angular@0.12.4
| `-- @angular-devkit/build-optimizer@0.12.4
|   `-- typescript@3.2.4  deduped
+-- @angular/cli@7.3.1
| `-- @schematics/angular@7.3.1
|   `-- typescript@3.2.4  deduped
`-- typescript@3.2.4

**Comment by bichikim** [comment]
@adrianpoplavsky to fix that temporary

```typescript
  declare module 'lodash' {
    export = _
  }
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
