### ISSUE TITLE
@types/react-intl not working with react typescript

### ISSUE THREAD

**Issue by AndrewMerke** [DefinitelyTyped/DefinitelyTyped#34027]
I have a problem to set up react-intl with react typescript project. I tried two ways to set up everything and always getting error:

```
TS2605: JSX element type 'IntlProvider' is not a constructor function for JSX elements.
  Property 'render' is missing in type 'IntlProvider'.
```

For example I am trying to implement it like this:

 ```
  import { IntlProvider, addLocaleData } from 'react-intl';
   
   const locale = 'fr';
   // load our messages
   const messages = require('./translations/locales/fr.json');
   // get the French locale information from the browser
   import fr = require('react-intl/locale-data/fr');
   addLocaleData(fr);
      
   ReactDOM.render(
       <IntlProvider locale={locale} messages={messages} key={locale}>
           <App />
       </IntlProvider>,
       document.getElementById('root') as HTMLElement
   );
```

Versions:
"@types/react-intl": "^2.3.17",
"react-intl": "^2.8.0"

Maybe anyone had same problem?

**Comment by chrisbrooks** [comment]
Yes I've got the same issue as well, same versions.

**Comment by erickskrauch** [comment]
Mee too.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
