### ISSUE TITLE
@types/inquirer: `Question.name` consider replace string with keyof T to avoid invalid name

### ISSUE THREAD

**Issue by liaozhongwu** [DefinitelyTyped/DefinitelyTyped#34094]
In current version, `Question.name` was present as string, developer may input wrong name by accident, consider replace string with keyof T to standard it ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
