### ISSUE TITLE
react.d.ts version 0.12.1 - Unable to use with browserify - undefined is not a function

### ISSUE THREAD

**Issue by drawable** [DefinitelyTyped/DefinitelyTyped#3410]
Thanks for the type definition it's great. Unfortunately since the latest update to 0.12.1 I'm not able to use it together with commonJS (browserify).

With the current d.ts I need to do

``` javascript
import React = require("react");

var Comp = React.createClass();
```

Transpiled to JS this will become

``` javascript
var React = require("react");

var Comp = React.createClass();
```

I use `ignore("react")` when creating my bundle with browserify because I load react separately with a script-tag in my header.

This leads to the fact that the `var React = require("react");` creates an empty object {} and all calls to React-methods will result in "undefined".

Adding

``` javascript
declare var React:React.Exports;
```

to react.d.ts remedies that. The `import React = require("react");` can now be removed and all works. Code completion still works in Webstorm 9 as it works on the definition reference.

**Comment by stkb** [comment]
I don't know this helps you, but I have the same scenario as you except that I use Webpack instead of Browserify. With Webpack I add `externals: { 'react': 'React' }` to its config file and then wherever I have `var React = require("react")` at the top of my code files  Webpack inserts the global `React` object, (loaded from another script tag on the page) instead of an empty object like you're having with Browserify. Then everything works fine.

I don't know if Browserify has a similar option; I'd assume so?

**Comment by drawable** [comment]
Thanks. I'll have a look at webpack I guess. I couldn't find anything similar in browserify.

**Comment by pspeter3** [comment]
Webpack has a plugin called [literalify](https://github.com/pluma/literalify) which should handle this. This is not an issue with the type definition because React does not auto export a global variable. As a suggestion, it helps to do the following in IntelliJ so that the IDE does not confuse the React module with the React variable

```ts
import react = require("react");
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
