### ISSUE TITLE
[@react-leaflet] Support leaflet events props

### ISSUE THREAD

**Issue by SpawnAtis** [DefinitelyTyped/DefinitelyTyped#34217]
- [+] I tried using the `@types/react-leaflet` package and had problems.
- [+] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [+] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [+] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @danzel 
  - Contributors: @ZhangYiJiang

Add support for events:  https://react-leaflet.js.org/docs/en/events.html 

` <LeafletMap
            ref={this.mapRef}
             onZoom={this.changeZoomLevel}
             {...otherMapProps}
     />`

> Property 'onZoom' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Map<MapProps, Map>> & Readonly<{ children?: ReactNode; }> &

**Comment by ZhangYiJiang** [comment]
As the comments in the typedef state, use lowercase event names (ie. `onzoom` instead of `onZoom`) since camelCase event names collide with DOM event handlers.

**Comment by SpawnAtis** [comment]
@ZhangYiJiang thx) But onzoom event is not included in `MapEvents` interface https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c06a6662f8d1e4dfbaf12c3cf1da7175b636824a/types/react-leaflet/index.d.ts#L15

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
