### ISSUE TITLE
mssql bulk promise should not resolve to a number

### ISSUE THREAD

**Issue by kabo** [DefinitelyTyped/DefinitelyTyped#34210]
- [x] I tried using the `@types/mssql` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ColsaCorp @jaminfarr @buzinas @mrrichar @elhaard @pkeuter @mcdado @woodenconsulting 

Looking at the source code https://github.com/tediousjs/node-mssql/blob/b056a1a2c11ef192553125268d2c3f785e643771/lib/base.js#L1376-L1384 it resolves to 
```
{ rowsAffected }
```
where rowsAffected is a number.

Something like 
```
export interface IBulkResult {
  rowsAffected: number
}

public bulk(table: Table): Promise<IBulkResult>
```
is needed I suspect.

**Comment by achrinza** [comment]
@kabo This is already in the types. Can you confirm that it's resolved?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
