### ISSUE TITLE
[@types/react] Alternative FunctionComponent without children

### ISSUE THREAD

**Issue by Dremora** [DefinitelyTyped/DefinitelyTyped#34237]
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
 
Authors: @VincentLanglet

A change introduced recently means that every component can now accept children. This is simply not a valid assumption, and it breaks the principle of least astonishment. When creating a component, I expect to have to provide all props. If the component (e.g. an icon) expects no props, I want to simply provide `{}` as the type argument and expect any attempt to pass children (or any other props) to the component to result in an error. Moreover, children can be of a narrower type (e.g. our Button component, as per design system, only expects a string, trying to pass anything else should result in an error).

Please consider removing `PropsWithChildren` from `FunctionComponent`. Additionally, we could have a `FunctionComponentWithChildren` that satisfies the current use case.

**Comment by VincentLanglet** [comment]
Before ‘PropsWithChildren’, the definition was ‘P & { children?: ReactNode }’.

I introduce nothing with my change, except the type PropsWithChildren.

**Comment by Dremora** [comment]
I see, my mistake in incorrectly framing the problem. I've only started using TypeScript a couple of days ago (coming from Flow) and wasn't aware this has always been the case.

However, my original point still stands in that having implicit `children` may be misleading and is not always desirable.

**Comment by kachkaev** [comment]
I've been also thinking about the same problem for some time. How about keeping the existing typing and introducing something like `LeafFunctionComponent` or `FunctionComponentWithoutChildren`? This is a bit worse than `FunctionComponent` (no children) + `FunctionComponentWithChildren`, but at least it does not introduce an pretty unfortunate breaking change.

At the moment, the only right way to define a component that does accept children is very different for the one with children, which makes things inconsistent and even error-prone.

```ts
import React, { FunctionComponent, ReactNode } from "react"; 

interface MyProps {
  a: string;
  b: number;
}

const MyComponentWithChildren: FunctionComponent<MyProps> = ({a, b, children}) => {
 return null;
}

const MyComponentWithoutChildren = ({a, b}: MyProps): React.ReactNode => {
 return null;
}
```

Not specifying the return type in the second case is common, but somewhat dangerous. Without that explicit declaration the component may accidentally return `undefined` or an array, which is not what React runtime expects.

Thanks for bringing up the issue @Dremora!

**Comment by kachkaev** [comment]
@johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @tkrotoff, @DovydasNavickas, @onigoetz, @theruther4d, @guilhermehubner, @ferdaber, @jrakotoharisoa, @pascaloliv, @hotell, @franklixuefei, @Jessidhia, @pshrmn, @saranshkataria, @lukyth, @eps1lon

WDYT folks?

_PS: Sorry for mentioning so many people, but you all are listed as the authors of React typings 😬_

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6f7a141fb85d645316c66eb228f158a3f24513c9/types/react/index.d.ts#L3-L25

**Comment by ferdaber** [comment]
This is something the maintainers of this package has wanted to get away with for precisely the reasons you listed above. However due to DT not following semver it’s very hard to do this without making a lot of people angry. We were going to just wait until the next React major version so we can piggy back off of their breaking change. 

I don’t see any compelling reason to split off the current definition simply to remove implicit children, you don’t gain much by using a type for defining a function component other than static properties. It’s much more important for class components.

**Comment by kachkaev** [comment]
> You don’t gain much by using a type for defining a function component other than static properties

The reason why I'd like to have some sort of `MyComponentWithoutChildren` is to prevent developers from adding children to `<MyComponent />` by a mistake. Another scenario is creating wrapper components that only accepts one child node. Because `{ children?: ReactNode }’` is added inside `FunctionComponent`, setting these restrictions seems impossible, so type checking ends up incomplete. If there is a workaround that does not imply adding `MyComponentWithoutChildren`, I'm happy to go for it.

**Comment by eps1lon** [comment]
@kachkaev  You can reject them in the meantime via:
```tsx
interface RestrictedProps {
  children?: never;
}

function Restricted(props: RestrictedProps) {
  return <div />;
}

// Type 'string' is not assignable to type 'undefined'
<Restricted>1</Restricted>; // $ExpectError
```

**Comment by kachkaev** [comment]
Yeah but that requires switching between `const MyComponent` and `function MyComponent` based on whether I want to have the `children` prop or not. Looks quite ugly. The problem of using `function MyComponent` is that it does not check the return-type of the function unless it is explicitly stated. So there is chance for returning `undefined` or a raw JavaScript object, which is wrong.

**Comment by eps1lon** [comment]
@kachkaev  Updated above post with arrow functions:
```tsx
interface RestrictedProps {
  children?: never;
}

function Restricted(props: RestrictedProps): React.ReactElement | null {
  return <div />;
}

const Restricted2: React.FunctionComponent<RestrictedProps> = () => <div />;

// Type 'string' is not assignable to type 'undefined'
<Restricted>1</Restricted>; // $ExpectError
<Restricted2>2</Restricted2>; // $ExpectError
```

**Comment by ferdaber** [comment]
In my perspective, rather than adding yet another type alias that needs to be eventually be deprecated/unified in a future breaking change, a valid workaround is to just define your own `FunctionComponentWithoutChildren`. It just makes it easier for us to transition if there are less types we have to take care of in the next version.

**Comment by Hotell** [comment]
using `FunctionComponent` comes with lot of problems (non consistent, you cannot use generics, defaultProps and friends issues). Just use standard function annotations to be explicit.

[See rule number 8 ](https://medium.com/@martin_hotell/10-typescript-pro-tips-patterns-with-or-without-react-5799488d6680)
![image](https://user-images.githubusercontent.com/1223799/55803486-af2f6500-5ada-11e9-8c56-76686baa992e.png)

**Comment by jtomaszewski** [comment]
What would be the preferred way to add this type to existing project? Sth like that?

```ts
// global.d.ts

declare module 'react' {
  type FCWC<P = {}> = FunctionComponentWithoutChildren<P>;

  interface FunctionComponentWithoutChildren<P = {}> {
    (props: P, context?: any): React.ReactElement | null;
    propTypes?: React.WeakValidationMap<P>;
    contextTypes?: React.ValidationMap<any>;
    defaultProps?: Partial<P>;
    displayName?: string;
  }
}
```

**Comment by callumlocke** [comment]
It sounds like the best workaround for now is to set `children?: never` on your props as @eps1lon suggests. But it feels unintuitive to me.

Also, that approach only works for when you want to _prohibit_ children, due to the special properties of `never`. What if you want to allow/require children but restricted to a specific type? Examples:

- accepting a function child that will receive something computed at runtime: `SomeComputedValue => ReactNode`
- requiring an element of a certain type, e.g. in a set of layout components that must be composed in a particular way, a `Row` might accept only `children: ReactComponentElement<typeof Column>`

The above examples are less common, but are still valid cases for function components, so it's weird if you can't use the standard interface called `FunctionComponent` to type them. (Well, you can use it, but it will always overload your props type with `{ children?: ReactNode }` which might not be what you want.)

I can see it's convenient that `FunctionComponent` adds `children?: ReactNode` to your props, as it's a common case, and anyway, changing that now would break everyone's code. But it would be nice if there was a way that people could easily opt out of it.

I'm not sure if creating a separate interface called `FunctionComponentWithoutChildren` is the best idea, because that name implies it explicitly takes _no_ children, but in fact you might just want to specify a custom `children` type, like in the examples above. I suppose it could be named differently, like `FunctionComponentWithoutDefaultChildren` but that seems ugly.

Is there some way `FunctionComponent` could be made configurable, in a backwards-compatible way? Something like this:

```ts
    interface FunctionComponent<P = {}, IncludeDefaultChildren = true> {
        (props: IncludeDefaultChildren extends true ? PropsWithChildren<P> : P, context?: any): ReactElement | null;
        propTypes?: WeakValidationMap<P>;
        contextTypes?: ValidationMap<any>;
        defaultProps?: Partial<P>;
        displayName?: string;
    }
```

You could then do `FunctionComponent<Props, false>` and it would just follow your `Props` exactly. (This is just an idea for discussion, maybe it's not very idiomatic though...)

**Comment by Jomik** [comment]
How about having the children type being part of the generics?
```ts
    interface FunctionComponent<P = {}, Children = ReactNode> {
        (props: P & { children: Children }, context?: any): ReactElement | null;
        propTypes?: WeakValidationMap<P>;
        contextTypes?: ValidationMap<any>;
        defaultProps?: Partial<P>;
        displayName?: string;
    }
```
This would allow you to keep using `FunctionComponent` as we do currently. But if you don't want children you do `FunctionComponent<Props, never>`, and if you want to accept string as children `FunctionComponent<Props, string>`, etc.
A different way would be
```ts
    interface FunctionComponent<P = {}> {
        (props: P extends { children: any } ? P : PropsWithChildren<P>, context?: any): ReactElement | null;
        propTypes?: WeakValidationMap<P>;
        contextTypes?: ValidationMap<any>;
        defaultProps?: Partial<P>;
        displayName?: string;
    }
```

**Comment by julian-sf** [comment]
@Jomik That's a really good idea, but the typing is _slightly_ off.  Here is a corrected version ([playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdwAdjFlAXlnAGICuT+YBCYBhEpCZYWAHgAKcALxwA3gF8ANHBEALYABsAJpSaLMVGADpseGADkIBrAD4VdOO7gAKMMTCoAXHDyAGQqcLi6hsaBOvpGUnAa4cKsAB4wAPyByEwAngCUgdb4VuYAonpYIFLwAD5wTLx6evQecD4QYAAquWBYqFlmNhYA6jgA1gBqyHrABsgwQkwAsshgck6tHrgpWOk9fQNF5hbTs-OLwqvrObmbbh6OHE0wsr5HQciwwDMbW+4GYCoMB6ZC5WzIaqDVAwKDMADm9FUDGYrHYnB4-EEwjE4GENTEUEo+CwBjkpjUmliUQSSmKlnp9kcLmUD3c3negRCYQicWMg2p8RMSR2LD2mWyeUKQxK9IqVRqcHqjWa-3avgO-UG9NGEzOcwWS2ufzZyTF+16WuOw31FyNa2kt3ubSeyBeb06H1kX0Wv1kzseQJBYIhUMCMLhTERdGRdFFMJ4EAggT4AkuonE+JYpk8+UULhVLTjwgTACEvimsencRICdBiawDDm8woC00i8WmAmuv14Epc-m4NInA9pNwk3AAPQj9zSctQKcj6TTmhAA)):

```tsx
import * as React from 'react';

interface FunctionComponent<P = {}, Children = React.ReactNode> {
    (props: P & { children: Children }, context?: any): React.ReactElement | null;
    propTypes?: React.WeakValidationMap<P>;
    contextTypes?: React.ValidationMap<any>;
    defaultProps?: Partial<P>;
    displayName?: string;
}

interface FunctionComponentCorrected<P = {}, Children = React.ReactNode> {
    (props: P & { children?: Children }, context?: any): React.ReactElement | null;
    propTypes?: React.WeakValidationMap<P>;
    contextTypes?: React.ValidationMap<any>;
    defaultProps?: Partial<P>;
    displayName?: string;
}

const Foo: FunctionComponent = () => null;
const Bar: FunctionComponentCorrected = () => null;

const Test = () => <>
  <Foo /> // TypeError: Property 'children' is missing in type '{}' but required in type '{ children: ReactNode; }'.
  <Bar />
</>;
```

**Comment by julian-sf** [comment]
@Jomik Your second solution is great.  [Here is a playground link showing how it would work in practice](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFioDqwMACwDCA4ABsAJpQB2AHnYA+OAF4OcAGRwA3nFyjJMgPwAuTFRgA6bHhgA5CBLYBfenWDSYWKATxsAYgCu0vjAENJCJJDSWB7yKtpOSlp0cKlwABRgXKim7HBYAB6e0hLoWnriUjGmyNJMTnCGHNl8giKVMvJKuQA0umGeRSYodQCUptb4VuYAomJYIDHwAD5w0gFiYvRpcFkQYAAqLFiow5OWPDgA1gBqyGLAEsgwodIAsshgXdtpuAOFMCOrFOE3MFjuDyeLzCHy+tSYCh+qUcPg2ME4+xBHGQsGA92+KTSEmAqDAYmQTFsyEWw1QMCg7gA5vQnAw-tI6XA-BAIKZAsFoeFImElrJyvoqtJTHSGdJGYl4ulRiolOtNvR2ZyAEI4vlBEJhCLgEUeRXK5SqjZbBiFSCwOAo5BojLmpSyBSE2Q6qAKABGONkAHpvR7UrJuRAFAQeUGI6G4OGeQpZOcLH4oMhGYtTYHk4G43Qg4igA).

**Comment by radeno** [comment]
`VoidFunctionComponent` can be used for childless components.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L549
https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components/

**Comment by codercodingthecode** [comment]
Why all the trouble?
Why not just ```Omit``` the property if you don't need it?
See the example:
```ts
interface SomeProps {
    prop1: string;
    prop2: number;
}

export const SomeComponent: React.FC<SomeProps> => (props: Omit<SomeProps, 'children'>) => {
    return <WhateverComponentWithoutChildreProps {...props} />
}
```

**Comment by eps1lon** [comment]
> Why not just Omit the property if you don't need it?

Because component users will be able to pass the `children` component without the prop actually being supported.

**Comment by codercodingthecode** [comment]
While you can still pass the props, you can still restrict what you can use inside your component. 
As I came across an issue today that the children prop not being used in the current component. It was causing an issue with destructuring the props into a component. I just decided to omit the children property from getting passed into the component.
But I understand the reasons behind that proposal. 
Best wishes.

**Comment by scoobster17** [comment]
>We were going to just wait until the next React major version so we can piggy back off of their breaking change.

I'm assuming this was missed/forgotten about for React v17-, will it be published alongside React v18? It's led to articles like [this one](https://kentcdodds.com/blog/how-to-write-a-react-component-in-typescript) which I personally don't agree with.

I know there are workarounds in the above comments but it would be really nice to make children optional in the types package without the need for these workarounds.

**Comment by kachkaev** [comment]
Even if you use React 16, there is `React.VoidFunctionComponent` type, which is like `React.FunctionComponent`, but without `children`.

It is possible to configure ESLint → [`no-restricted-syntax`](https://eslint.org/docs/rules/no-restricted-syntax) with the following options:

```json
{
  "selector": "TSQualifiedName[left.name=React][right.name=/^(FunctionComponent|FC|SFC|VFC)$/]",
  "message": "Please use `React.VoidFunctionComponent` instead. Context: https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components/",
}
```

We use this Rule in conjunction with `eslint-plugin-unicorn` → [`import-style`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/import-style.md) to enforce `import * as React from "react"` instead of default and named exports:

```json
"unicorn/import-style": [ "error", { "styles": { "react": { "namespace": true } } } ]
```

**Comment by SharadJ85** [comment]
> VoidFunctionComponent

Thanks [kachkaev](https://github.com/kachkaev) , the `VoidFunctionComponent` type was useful!
