### ISSUE TITLE
Make lodash-es the source of truth instead of lodash?

### ISSUE THREAD

**Issue by mgol** [DefinitelyTyped/DefinitelyTyped#34263]
- [x] I tried using the `@types/lodash-es` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @stephenlautier @e-cloud

Currently, `@types/lodash-es` depends on `@types/lodash`, mostly just re-exporting most of its types. This creates a problem: `@types/lodash` exposes a global `_` variable which conflicts with underscore if you have both in the project (see #7141; related: #5045; previous attempts: #6088).

It seems to me it'd make sense to reverse the dependency - make `@types/lodash` depend on `@types/lodash-es`, making `@types/lodash-es` not declare any globals at all.

Thoughts? If I created a PR for that, would it be accepted?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
