### ISSUE TITLE
Support after highchart/types

### ISSUE THREAD

**Issue by Mani2693** [DefinitelyTyped/DefinitelyTyped#34290]
Hi team, 

As you know Highcharts started providing type files from highchart v7.0

We are worried if defined types provided here would stop giving updated when new changes are made from highcharts, I just need to have your thoughts on how this will be progressed in future 

Do we get continuous support and updated here ? Our enterprise application is now closely bind with our types

Hope you will understand the concern , Response would be much appreciated 

Thanks  

- [ x] I tried using the `@types/xxxx` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tdreyno @kamal @leemhenson @jonmagic @farcaller 

If you do not mention the authors the issue will be ignored.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
