### ISSUE TITLE
Fix ratelimiter with ioredis

### ISSUE THREAD

**Issue by sweepyoface** [DefinitelyTyped/DefinitelyTyped#34300]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @AyaMorisawa 

---

[ratelimiter](https://github.com/tj/node-ratelimiter) supports [ioredis](https://github.com/luin/ioredis), but the [types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/ratelimiter/index.d.ts) only include [redis](https://github.com/NodeRedis/node_redis).

I started on this [here](https://github.com/sweepyoface/DefinitelyTyped/commit/88173e766b722a385da5616d65faaf8b75001d0c), but had difficulty proceeding with testing. If anyone could help move this along it would be fantastic.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
