### ISSUE TITLE
@types/react-router-dom missing ariaCurrent prop in NavLink

### ISSUE THREAD

**Issue by Rj-s** [DefinitelyTyped/DefinitelyTyped#34317]
since "react-router-dom": "4.2.0" they have added airaCurrent prop but its missing in type.

https://github.com/ReactTraining/react-router/commit/89093a4e09c430b5c32bfb6b86de66cffd9b97ec

**Comment by ynotdraw** [comment]
This is now added via https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39987

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
