### ISSUE TITLE
[request] braintree

### ISSUE THREAD

**Issue by MarZab** [DefinitelyTyped/DefinitelyTyped#34346]
Requesting and gathering interest in a definition for the [braintree](https://www.npmjs.com/package/braintree) module.

Backlink to briantree_node repo
https://github.com/braintree/braintree_node/issues/121#issuecomment-350278149

**Comment by lamanabie** [comment]
There is already some progress https://gist.github.com/stwiname/a455abc0947b16a60301244b8cf0c7d5

**Comment by smrubin** [comment]
PR up for the braintree module: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35461

**Comment by smrubin** [comment]
Published: https://www.npmjs.com/package/@types/braintree

@MarZab Consider closing this issue.

**Comment by simllll** [comment]
Just ran into the issue,
two things are at least missing:
* braintree.WebhookNotification
* gateway.webhookNotification

I'm quite busy right now, but maybe I will find some time later this month to add it.

regards

**Comment by smrubin** [comment]
`WebhookNotification` definitions have been added.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
