### ISSUE TITLE
[@storybook__react] type updates for v5.*.*

### ISSUE THREAD

**Issue by yjkimjunior** [DefinitelyTyped/DefinitelyTyped#34365]
Logging this as it doesn't look like it's been picked up yet.

- [x] I tried using the latest types for @storybook, @storybook/addons, etc. for v4.*.* and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
@joscha @wapgear

**Comment by joscha** [comment]
v5 comes with it's own types, can you try not installing any `@types/storybook*` at all, please?

**Comment by yjkimjunior** [comment]
ah! didn't catch that, thanks! @joscha

**Comment by yjkimjunior** [comment]
@joscha, this seems to be breaking again... so either I didn't check properly before or something's changed.

My package.json looks like this: 
```
  "devDependencies": {
    "@storybook/addon-actions": "^5.0.10",
    "@storybook/addon-knobs": "^5.0.10",
    "@storybook/addon-links": "^5.0.10",
    "@storybook/react": "^5.0.10",
    "@substrate/ui-common": "^0.1.0",
    "babel-loader": "^8.0.5"
  }
```
with all the `@types/storybook*` removed and ts-lint complains for each of those that `Could not find a declaration file for module '@storybook/...`.

I'm on tsc `v3.4.4` and tslint `v5.16.0`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
