### ISSUE TITLE
Reactstrap Modal props toggle fn is missing event parameter.

### ISSUE THREAD

**Issue by mchong-teal** [DefinitelyTyped/DefinitelyTyped#34413]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alihammad, @mfal, @danilobjr

It looks like the 'toggle' property for the Modal component is passed an event (https://github.com/reactstrap/reactstrap/blob/master/src/Modal.js#L212), but this is not reflected in the type definitions.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
