### ISSUE TITLE
[@types/jqueryui] Type definitions missing from jquery ui

### ISSUE THREAD

**Issue by ankita240796** [DefinitelyTyped/DefinitelyTyped#34474]
- [x] I tried using the `@types/jqueryui` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @johnnyreilly

I tried using jqueryui type definitions but the following properties were not found on compilation: `UI.ddmanager`, `DraggableOptions.tolerance` and `DroppableOptions.containment`. After adding custom type definitions, the compilation worked:

```
declare namespace JQueryUI {
    interface DraggableOptions {
        tolerance?: string;
    }
    interface DroppableOptions {
        containment?: string;
    }
    interface UI {
        ddmanager?: any;
    }
}
```

**Comment by martin-badin** [comment]
I saw the documentation for Draggable and Droppable and there are not found those definitions. What is it `ddmanager`?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
