### ISSUE TITLE
Trying to contribute - npm install fails

### ISSUE THREAD

**Issue by rjconrad** [DefinitelyTyped/DefinitelyTyped#34502]
With a fresh clone of the master branch:

```
$ npm install
npm ERR! Unexpected end of JSON input while parsing near '...kdirp":"latest","@typ'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rick/.npm/_logs/2019-04-05T09_34_22_968Z-debug.log
```

The error log doesn't really add anything, but here it is.
[2019-04-05T09_34_22_968Z-debug.log](https://github.com/DefinitelyTyped/DefinitelyTyped/files/3047330/2019-04-05T09_34_22_968Z-debug.log)

I get the same error if I try
`npx dts-gen`
as well as 
`npm install -g dts-gen`

npm version: 6.4.1

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
