### ISSUE TITLE
@types/workbox-sw missing BroadcastChannel declaration

### ISSUE THREAD

**Issue by aashishbarnwal** [DefinitelyTyped/DefinitelyTyped#34567]
Typed definition of workbox-sw flashes error because of missing BroadcastChannel declaration:
static broadCastUpdate (channel: BroadcastChannel, cacheName: string, url: string, source: string): void;

If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wessberg 

If you do not mention the authors the issue will be ignored.

**Comment by wessberg** [comment]
Hi there. Thanks for submitting this issue. `BroadcastChannel` is declared in the `lib.webworker.d.ts` typings bundled with Typescript. To resolve the issue, please add `webworker` to the `lib` section of the `compilerOptions` of your `tsconfig.json`:

```json
{
    "compilerOptions": {
        "lib": [
            "es2015",
            "webworker"
        ]
    }
}
```

**Comment by aashishbarnwal** [comment]
Thanks for responding!
I tried adding `webworker` and still seeing the issue.

**Comment by wessberg** [comment]
I'm sorry that you are still having this issue! However, since BroadcastChannel is part of the standard library of typings, duplicating them inside of the typings for `workbox-sw` would lead to other issues, such as conflicts with existing declarations as well as introducing the need to maintain unrelated worker-specific typings inside `workbox-sw` which isn't the responsibility of that library.

You can try to set `"skipLibCheck": true` inside your `compilerOptions` and see if it helps you in your specific scenario.

**Comment by aashishbarnwal** [comment]
Thanks! Setting `"skipLibCheck": true` fixed the issue :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
