### ISSUE TITLE
[@types/react] Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by diegohaz** [DefinitelyTyped/DefinitelyTyped#34588]
#34386 possibly broke one of my components with this error:
```
TS2589: Type instantiation is excessively deep and possibly infinite.
```
My component has already complex types. My guess is that this change introduced deeper levels of type instantiation and, combined with mine, reached the typescript compiler limit.

Reproduction:
```sh
git clone https://github.com/reakit/reakit
cd reakit
git checkout cf7426f0cb35c2ed4a02308cc426d247b3145ad2
yarn
yarn add -WD @types/react@16.8.12
yarn type-check # no errors with @types/react@16.8.12
yarn add -WD @types/react@16.8.13
yarn type-check # Found 3 errors
```

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @pshrmn @saranshkataria @lukyth @eps1lon

**Comment by diegohaz** [comment]
I solved it by reducing the complexity of my types (basically removing one level in the path array), but I'm not sure this is the best solution, so this issue may be still valid.

**Comment by ferdaber** [comment]
Can you give a snippet or post a repo that has your types? It's not possible to debug with just this information.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
