### ISSUE TITLE
@types/mongoose replaceOne missing options parameter

### ISSUE THREAD

**Issue by teddis** [DefinitelyTyped/DefinitelyTyped#34603]
I tried using the latest v5.3.25 of `@types/mongoose` package and had problems. The call signatures for `Model.replaceOne()` and `Document.replaceOne()` appear to be missing the `options` parameter. I don't know how to fix this, but a workaround is to cast the options parameter as <ModelUpdateOptions> and use //@ts-ignore to disable inspection for the statement.

Authors: @horiuchi @lukasz-zak @Alorel @jendrikw et al.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
