### ISSUE TITLE
[@types/stripe-v3] Types for beta Payment Intents API

### ISSUE THREAD

**Issue by mrehayden1** [DefinitelyTyped/DefinitelyTyped#34652]
In the course of using the new Payment Intents API which is required for compliance with the new EU SCA legislation I've found the type definitions are missing.

Assuming this is the correct place for them, would it be good to have these included or should we wait for an official release?

These are the skeleton types I've created so far for use in my own code but they're far from complete.

```
namespace stripe {
  interface HandleCardPaymentOptions {
    receipt_email?: string;
    save_payment_method?: boolean;
    shipping?: any;
    source_data?: any;
  }

  interface HandleCardPaymentResult {
    error?: any;
    paymentIntent?: any;
  }

  interface Stripe {
    handleCardPayment(clientSecret: string, cardElement: stripe.elements.Element, data?: HandleCardPaymentOptions): Promise<HandleCardPaymentResult>;
  }

  interface StripeOptions {
    betas?: string[];
  }
}
```

**Comment by mrehayden1** [comment]
- [x] I tried using the `@types/stripe-v3` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @a904guy @ejsmith @amritk @adamcmiel @jleider @galuszkak @slangeder @marlosin

**Comment by marlosin** [comment]
hey, @mrehayden1 if these definitions are already available in stripe's API (is there any docs already?) and they didn't change the current API I see no problem adding them to this package. it'd be great if you open a PR with these changes :wink:

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
