### ISSUE TITLE
[@types/ramda] probably wrong PipeWith signature

### ISSUE THREAD

**Issue by SET001** [DefinitelyTyped/DefinitelyTyped#34659]
- [x] I tried using the `@types/ramda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @donnut, @tycho01, @mdekrey, @mrdziuban

according to the 0.26.1  `pipeWith` docs, neither transformation, nor result function should be unary. The unary should all but first from PipeWithFns. So Would it be correct to change definition to this?

```
        pipeWith<V0, T>(composer: (...args: any[]) => any, fns: PipeWithFns<V0, T>): (...args: any[]) => T;
        pipeWith(composer: (...args: any[]) => any): <V0, T>(fns: PipeWithFns<V0, T>) => (...args: any[]) => T;
```

**Comment by aagwali** [comment]
Hello,
I was about to post the same issue since I ended to the same conclusion trying to use a custom pipe with ramda. 
Any news about this issue ?

**Comment by heyantonmelnyk** [comment]
More than that, current types are completely outdated. 
https://ramdajs.com/docs/#pipeWith
That transformation function has 2 parameters, where the first is the next function and the second is an argument.

**Comment by chughes87** [comment]
Here we go! https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50141

**Comment by chughes87** [comment]
@SET001 My PR for fixing this issue was just merged <3

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
