### ISSUE TITLE
[@types/datatable.net-rowgroup] Property 'nodes' does not exist on type 'Api'.

### ISSUE THREAD

**Issue by manojkr029** [DefinitelyTyped/DefinitelyTyped#34685]
Hi, I'm facing an issue while using the datatable.net-rowgroup.

I have installed the type definition using npm. 

I am modifying the group element as well as its child rows in "startRender" configuration like this:

```
startRender: ((rows, group) => {
                 var collapsed = !!collapsedGroups[group];
                 rows.nodes().each((r) => {
                     r.style.display = collapsed ? 'none' : '';
                 });
                     

                 return $('<tr/>')
                     .append('<td colspan="8">' + group + ' (' + rows.count() + ')</td>')
                     .attr('data-name', group)
                     .toggleClass('collapsed', collapsed);
             })
```

It is giving me the compile time error "Property 'nodes' does not exist on type 'Api'." so I'm unable to create the build.

I'm using Angular 7

Please look into this @sandersn

**Comment by sandersn** [comment]
Pinging package author @maixiu

**Comment by maixiu** [comment]
Won't be able to have a look at it till some time. Any PR is welcome.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
