### ISSUE TITLE
@types/osmosis missing function definitions

### ISSUE THREAD

**Issue by fnetworks** [DefinitelyTyped/DefinitelyTyped#34689]
- [x] I tried using the `@types/osmosis` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jurajkocan @evanshortiss

The osmosis types seem to be missing some function definitions, e.g. ``parse`` (listed on [https://github.com/rchipka/node-osmosis/wiki#command-reference](https://github.com/rchipka/node-osmosis/wiki#command-reference))

**Comment by evanshortiss** [comment]
@fnetworks I'm not sure if these are new functions on not. It would be worth opening a PR and adding them if you have time.

**Comment by jurajkocan** [comment]
@evanshortiss i'll check on weekend
for now just ignor it (//@ts-ignore)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
