### ISSUE TITLE
@types/meteor createdat change

### ISSUE THREAD

**Issue by pmcochrane** [DefinitelyTyped/DefinitelyTyped#34709]
In a recent update to the @types/meteor definitions, the createdat property was changed from being a number to a date.

Can you confirm that this is correct as when I create a user the createdat field is populated with a number not a date.

Changing this to a date in @types/meteor throws hundreds of error compiling the code as the simpleschema and interfaces all have createdat as a number to match the contents of the property. 

I realise that this field is actually a date but meteor is storing it as a number rather than a date.

v1.2.24 is coded as a number. Later version have it coded as a date with no real reason specified for the change as far as I can see.

Thanks for looking into this.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
