### ISSUE TITLE
Request: Publish @types/ packages with tags for major versions

### ISSUE THREAD

**Issue by Pajn** [DefinitelyTyped/DefinitelyTyped#34731]
Npm packages are currently published with ts versions as tags. It would be great if they were also published with the major version of the types as tags.

For example, I would like to install the latest types for node 10 with `yarn add @types/node@10` and not have to look up the minor and patch version manually.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
