### ISSUE TITLE
node_modules/@types/angular-resource/index.d.ts(156,75): error TS2304: Cannot find name 'IPromise'.

### ISSUE THREAD

**Issue by rajatg64** [DefinitelyTyped/DefinitelyTyped#34767]

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
