### ISSUE TITLE
Alternative definition for Snap.svg

### ISSUE THREAD

**Issue by DanielRosenwasser** [DefinitelyTyped/DefinitelyTyped#3487]
I have [a definitions file for Snap.svg](https://github.com/DanielRosenwasser/DefinitelyTyped/blob/f3fec5c9588cac9ae10e0ec4edaa42c653019a55/snapsvg/snapsvg.d.ts) which seems more accurate than the current one (especially since it uses union types). I should have sent a PR sooner, but I've just been fairly busy. I don't want to trample on anyone's feet, so what are the usual politics on this?

The current tests seem to be useful, but I don't think the actual definitions are compatible.

**Comment by vvakame** [comment]
please discuss with @lhk.

I think both code has also been well organized.

**Comment by lhk** [comment]
"I don't want to trample on anyones feet". - Don't worry about that. If your code is superior, it should be the code offered to the users. There are no personal feelings involved from my side.

That being said, I'm not really sure which version I prefer. Your code is very nicely structured and makes a lot of sense, but it doesn't seem to follow the snap docs very closely.
Intuitively I think that someone who has the docs open in one window and the IDE in the other might profit from my layout, since that is actually only the docs translated to typescript as clean as possible.
Your code is more beautiful and more elegant but not that close.
In fact your code offers functionality that I didn't find in the docs and that is missing in my version: "ExplicitTransform" for example.

The one big advantage - union types - of your code could be added to my version quickly. But I wouldn't want to invest the time if the code is scratched immediately.

And finally, what do you mean with "the current tests seem to be useful, but I don't think the actual definitions are compatible" ?

The decision between the two versions is a hard one, and I don't think I'm qualified enought to make it.

**Comment by lhk** [comment]
I just saw that you're one of the main contributors to typescript itself.

That settles it. If you say that your version is preferable, it surely is

**Comment by DanielRosenwasser** [comment]
> I just saw that you're one of the main contributors to typescript itself. That settles it.

Don't sell yourself so short ;)

Honestly I wouldn't feel right proceeding unless you felt fully comfortable with my reasons.

> It doesn't seem to follow the snap docs very closely.

The issue is that in some cases, the Snap documentation is incredibly vague, ambiguous, or in some cases erroneous (though not that often). I did check the code out. Perhaps I should have stuck to the documentation, but I got a bit frustrated with trying to decipher exactly what each function was returning.

> Intuitively I think that someone who has the docs open in one window and the IDE in the other might profit from my layout, since that is actually only the docs translated to typescript as clean as possible.

I think you're right in that respect, but ultimately I needed to defer to the source itself which is why it's not as linear and as close to the documentation as I would've liked, and I appreciate that you managed to do so.

> And finally, what do you mean with "the current tests seem to be useful, but I don't think the actual definitions are compatible" ?

It seems mostly like we can merge our tests into one test file and get better coverage in general - it might be worth going through each function in the other definition to see if the end result is complete, but otherwise it's probably down to one file.

Mainly the reasons I think that my definitions are an improvement are
* Explicitly typed functions rather than `Function`, which is a big win in general.
* Use of primitive values when possible rather than `lib.d.ts` types (i.e. `string[]` vs `Array<string>`).
* `any` and more specific types over `Object` (though I do wonder if `{}` is more appropriate in certain contexts).
* Some of my overloads are a little bit more complete or safe.

If you're still feeling open to this, I'll be glad to send out a PR.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
