### ISSUE TITLE
jest.Mocked doesn't deal with declaration merging

### ISSUE THREAD

**Issue by lifeiscontent** [DefinitelyTyped/DefinitelyTyped#34889]
@NoHomey @jwbay @asvetliakov @alexjoverm @epicallan @ikatyang @wsmd @JamieMason @douglasduteil @ahnpnl @JoshuaKGoldberg @UselessPickles @r3nya @hotell @sebald @andys8 @antoinebrault

when trying to mock the fs library the declarations don't merge, not sure if this is due to bad declarations in the Node.js definition or jest

here's my example:

```ts
import base from './base';
import _fs from 'fs';

jest.mock('fs');

const fs: jest.Mocked<typeof _fs> = _fs as any;

class ErrnoException extends Error {
  constructor(public code: string, public message = '') {
    super(message);
    Object.setPrototypeOf(this, ErrnoException.prototype);
  }
}

describe('base', () => {
  describe('read', () => {
    describe('when file exists', () => {
      beforeEach(() => {
        // @ts-ignore until fixed
        fs.readFile.mockImplementation((_path, options, callback) => {
          if (typeof options === 'string' && options === 'utf8') {
            callback(
              null,
              Buffer.from(JSON.stringify({ phone: '5555555555' }), options)
            );
          }
        });
      });

      it('reads the file', async () => {
        expect(
          await base.read<{ phone: '5555555555' }>('users', '5555555555')
        ).toEqual({
          phone: '5555555555'
        });
        expect(fs.readFile).toHaveBeenCalled();
      });
    });
    describe('when file does not exist', () => {
      beforeEach(() => {
        // @ts-ignore until fixed
        fs.readFile.mockImplementation((_path, _options, callback) => {
          callback(new ErrnoException('ENOENT'));
        });
      });

      it('throws an error', () => {
        expect(base.read('users', '5555555555')).rejects.toEqual(
          expect.objectContaining({ code: 'ENOENT' })
        );
        expect(fs.readFile).toHaveBeenCalled();
      });
    });
  });
});
```

please let me know if there's something I can do on my end, I'd make a PR myself but I'm unsure how to solve the problem.

**Comment by jwbay** [comment]
This is due to `fs.readFile` having overloads declared. When asked to retrieve parameters of an overloaded method, TS will retrieve them from the last overload because it's usually the least specific. This is not the case for `fs.readFile` however.

I explored typing the mocks with the function type instead of the split params/return types, thinking it would preserve the overloads through to `mockImplementation`. It did, but this still failed assignability checking there. For any callable type F with overloads, `.mockImplementation(impl: F)` will demand all the overloads be present in the implementation type. The only solution I'm aware of here is to cast, and this works with the types as-is as well.

```ts
fs.readFile.mockImplementation(
  ((
    _path: PathLike | number,
    options: { encoding?: null; flag?: string } | undefined | null,
    callback: (err: NodeJS.ErrnoException | null, data: Buffer) => void
  ) => {
    if (typeof options === "string" && options === "utf8") {
      callback(
        null,
        Buffer.from(JSON.stringify({ phone: "5555555555" }), options)
      );
    }
  }) as typeof _fs.readFile
);
```

Note argument types must be supplied as the cast kills inference.

**Comment by lifeiscontent** [comment]
@jwbay so does the fs declaration need fixing? If I sorted the declaration would that fix it? Or would this break when you go from 2 to 3 parameters and visa versa? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ricool06** [comment]
I think I'm experiencing the same issue if I've read this correctly, except I'm trying to mock a function with multiple overloads from `aws-sdk`:

```
const ec2 = new EC2();

const successImplementation = (
  _: EC2.DescribeInstancesRequest,
  callback?: (error: AWSError, data: EC2.DescribeInstancesResult) => void
) => {
  callback(null, fakeDescribeInstancesResult);
};

jest.spyOn(ec2, 'describeInstances').mockImplementation(successImplementation); // Fails here.

// successImplementation doesn't match the overload for describeInstances that jest expects.
```

The code still compiles and runs, with the test passing as expected, despite an error being shown in the IDE.

**Comment by jgonera** [comment]
Would using something like https://stackoverflow.com/a/52761156/365238 help here?

**Comment by lifeiscontent** [comment]
@jgonera that might! Wanna try and implement it?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
