### ISSUE TITLE
Browserify transform() calling conventions

### ISSUE THREAD

**Issue by AprilArcus** [DefinitelyTyped/DefinitelyTyped#3494]
browserify.d.ts currently has

``` Typescript
interface BrowserifyObject extends NodeJS.EventEmitter {
  ...
  transform(tr:string): BrowserifyObject;
  transform(tr:Function): BrowserifyObject;
  ...
}
```

which is true as far as it goes, but `Browserify.prototype.transform` is much more polymorphic than this — it can take arguments in any of these configurations:
- function
- string
- function, object
- string, object
- object, function
- object, string
- [function]
- [string]
- [function, object]
- [string, object]

where object is an options hash whose licit keys vary on the function/string argument. I don't know if heterogeneous arrays can be annotated yet, but it seems like there must be a way to represent the other method signatures.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
