### ISSUE TITLE
[@types/express-serve-static-core] Request.ip should be string|undefined

### ISSUE THREAD

**Issue by AnyhowStep** [DefinitelyTyped/DefinitelyTyped#34964]
- [X] I tried using the `@types/express-serve-static-core` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @MarcusCemes @micksatana 

Wasn't too sure who to mention so I just picked the two most recent contributors.
In most cases, `Request.ip` is `string`, indeed.

But I've seen cases where `Request.ip` is `undefined`. Particularly if the client aborts a connection immediately (like having a timeout of 1ms).

However, making it `string|undefined` now would definitely break code for people who are using `req.ip` at the moment.

So... Thoughts?

**Comment by AnyhowStep** [comment]
So, after looking into it, the reason why `req.ip` can be `undefined` is because `req.connection.remoteAddress` is used as part of deriving `req.ip`.

1. `express` uses `proxy-addr`, passing `req` to it.
1. `proxy-addr` uses `forwarded`, passing `req` to it.
1. `proxy-addr` uses `req.connection.remoteAddress` and `req.headers['x-forwarded-for']`

It seems like `req.connection.remoteAddress` is `undefined` when the connection is aborted (for whatever reason).

Makes me wonder if this is a `node` problem. It just seems weird to me that a client can make a connection, and we can process the request, but not know the client's ip address.

**Comment by AnyhowStep** [comment]
It's a `node` thing.

https://github.com/nodejs/node/issues/23858

**Comment by AnyhowStep** [comment]
My workaround for this is to add the following middleware to the `express` app,

```ts
const app = express();
//Do we want to trust the `x-forwarded-for` header?
declare const trustProxy : boolean;
app.set("trust proxy", trustProxy);
app.use((req, _res, next) => {
    //Get the ip address eagerly.
    //Seems like the value is cached for subsequent reads.
    req.connection.remoteAddress;
    next();
});
```

From my tests, it seems to me like with this middleware, we eagerly get the `remoteAddress`, before the client disconnects, and subsequent reads to `remoteAddress`, even if done seconds after the disconnect, still give you a `string` and not `undefined`.

It's kind of hack-y and I don't claim that this will work 100% of the time but it is reliable enough for me.

**Comment by MarcusCemes** [comment]
This seems like an edge case, `undefined` and `null` behaviour is not usually hard-typed into Typescript. For example, a function that explicitly returns an object could return `undefined` or `null` without any compilation errors.

The behaviour seems to be well documented in the [Node.js docs](https://nodejs.org/api/net.html#net_socket_remoteaddress), and I believe that if the IP is vital in an asynchronous function, it should be tested for a truthy value. If you really need the client's IP, I would follow your approach of creating a `resolveIP` middleware that caches the value inside the request object, I myself only use it for rate-limiting which happens immediately after the connection is opened.

You mentioned that if the connection is immediately aborted, the IP is `undefined`? Even in top-level middleware (if the event loop is very busy, it may take a while to synchronously serve the request)? In this case, it shouldn't be taken for granted, and always tested.

Based on nodejs/node#23858 it seems like these are edge cases that tend to annoy people, we should follow their example instead of diverging with the typings. I would recommend caching "eagerly" if absolutely necessary, however, it is not possible to respond if the connection to the client is lost anyway.

**Comment by AnyhowStep** [comment]
My experience has been that `null` and `undefined` should absolutely be part of types, if there is even the slightest chance of those types being possible (in fields, variables, parameters, return types, etc.)

Not adding it to the type is just asking for surprises like these to come up, where the developer ends up having to waste time and look up why the type is lying to them. And also running into unnecessary run-time errors.

If `undefined` is even explicitly documented, even more reason for the type declarations to change.

But, that's just the perspective of someone who really loves correct static type checks.

I can totally understand why one would be reluctant to make a breaking change that would upset so many others that already know about this... Bug in the type declarations, and have found viable workarounds.

But fixing the type would help out the others who don't know, and those in the future who are using it for the first time.

Then again, I've never had to work on something used by countless others, and had to weigh correctness vs backwards compatibility

**Comment by MarcusCemes** [comment]
@AnyhowStep Casual observation, I was just adding types to my functions, and I tried adding an undefined response type.

![image](https://user-images.githubusercontent.com/20288819/57149514-28656380-6dcc-11e9-89b7-e4b1fff33ded.png)


Visual Studio Code (which I would probably consider the reference for TypeScript integration) doesn't actually show `undefined` or even `null`. The same applies to variables.

I distinctly thought of this issue when I found that out. I'm not sure if there's anything else to add, perhaps the issue should be closed?

**Comment by AnyhowStep** [comment]
`any | T` absorbs `T`. So, `any | undefined` is `any`. That's expected behavior. Because all types are sub types of `any`

Also, I code with the `strictNullChecks` flag on.

In 99% of cases, meaning type unions without `any` and `unknown`, with that flag enabled, you'll see `T| undefined` properly

**Comment by MarcusCemes** [comment]
I understand your reasoning, however:

![image](https://user-images.githubusercontent.com/20288819/57219873-ba9e7f00-6ff9-11e9-9d40-2185650b7e56.png)

As far as I understand, TypeScript doesn't "compact" types, even if one is a subtype of another. It makes sense to list all the specified types separately so that users can anticipate the possible return paths. My understanding is that the union `|` operator doesn't merge two types, but acts more like an `OR`.

![image](https://user-images.githubusercontent.com/20288819/57220273-f71eaa80-6ffa-11e9-82e4-c96e60c18fb4.png)

*Will it be a specific sport or just a sport?*  Showing just a return type of `IFootball` would not be obvious that `IFootball` extends `ISport` and that the more general `ISport` which is missing the `object` property could also be returned.

**Comment by AnyhowStep** [comment]
![image](https://user-images.githubusercontent.com/5655961/57241733-a8274400-6fff-11e9-9d92-d59b4316b347.png)

**Comment by AnyhowStep** [comment]
![image](https://user-images.githubusercontent.com/5655961/57241785-cab95d00-6fff-11e9-8ac9-ba2e32e67dac.png)

`any` is special. It will absorb all other types.

-----

![image](https://user-images.githubusercontent.com/5655961/57241826-e6bcfe80-6fff-11e9-9b5a-c8e7b4a7c8b3.png)

`string|""` is `string` because `string` absorbs `""` (because `""` is a subtype of `string`)

**Comment by MarcusCemes** [comment]
I see your point. Personally I don't use strict TypeScript rules because it tends to slow me down, especially when typings are missing/incorrect. I prefer the "augment with Typescript" experience, as it is still just Javascript at the end of the day, and you never know what bugs lie await in the internals/libraries...

If this is an issue that you run into often, and you think would be beneficial to others, why not. Submit a quick PR and add `undefined` to the return types. 

My approach is to always check for correct types when dealing with critical parameters (such as `ip` when rate limiting), especially with a dynamic language such as Javascript, and fail softly. I can't really imagine a case where you would want to recover and continue serving a client that has already disconnected, but that is irrelevant.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
