### ISSUE TITLE
Catch error in types-publisher/bin/util/util.js Travic CI test failed

### ISSUE THREAD

**Issue by polRk** [DefinitelyTyped/DefinitelyTyped#34982]
I have an error when travis ci test make a test.
https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/524361127?utm_source=github_status&utm_medium=notification

I don't know, how can u fixed it. It's not a my problem, because 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34865
azure build - OK!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
