### ISSUE TITLE
[@types/mongoose] Missing support for mongoose transaction session 

### ISSUE THREAD

**Issue by nikip28** [DefinitelyTyped/DefinitelyTyped#34984]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mongoose` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Alorel @ethanresnick @horiuchi @sindrenm @lukasz-zak @jendrikw @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @danmana @stablio

If you do not mention the authors the issue will be ignored.

**Comment by nikip94** [comment]
![Screen Shot 2019-04-25 at 2 26 03 PM](https://user-images.githubusercontent.com/16451017/56725370-60d0c600-676a-11e9-9890-0447b95576be.png)
![Screen Shot 2019-04-25 at 2 28 20 PM](https://user-images.githubusercontent.com/16451017/56725371-60d0c600-676a-11e9-9f15-e036e45dd6bd.png)

**Comment by alreadyExisted** [comment]
Maybe this will help:
https://github.com/Automattic/mongoose/blob/master/lib/query.js#L1056-L1084

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
