### ISSUE TITLE
[@types/reactwidgets] missing at least footerFormat

### ISSUE THREAD

**Issue by emmanueltouzery** [DefinitelyTyped/DefinitelyTyped#34986]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rogierschouten @sanyatuning @frodehansen2 @r3nya
@MBillemaz @georg94 @tzarger @vegtelenseg

For the date picker component, at least the `footerFormat` prop is missing =>
https://github.com/jquense/react-widgets/blob/master/packages/react-widgets/src/Calendar.js#L177-L182

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
