### ISSUE TITLE
[@types/react-helmet] Helmet.peek() return value does not match actual return value

### ISSUE THREAD

**Issue by andrastothtw** [DefinitelyTyped/DefinitelyTyped#34983]
- I tried using the `@types/react-helmet` package and the return value of `Helmet.peek()` is very different (see below)
- [✅ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Authors: @phurytw 

Currently in the type definition file:
```export const peek: () => HelmetData;```

```typescript
export interface HelmetData {
    base: HelmetDatum;
    bodyAttributes: HelmetHTMLBodyDatum;
    htmlAttributes: HelmetHTMLElementDatum;
    link: HelmetDatum;
    meta: HelmetDatum;
    noscript: HelmetDatum;
    script: HelmetDatum;
    style: HelmetDatum;
    title: HelmetDatum;
    titleAttributes: HelmetDatum;
}
```

While `Helmet.peek()` actually returns this construct (example):
```javascript
{
        baseTag: [],
        bodyAttributes: {},
        defer: true,
        encode: true,
        htmlAttributes: {},
        linkTags: [ { rel: 'canonical', href: 'https://githoob.bom' } ],
        metaTags:
        [ { name: 'description',
             content: 'bla bla' },
           { property: 'og:description',
             content: 'bla-bla' }
        ],
        noscriptTags: [],
        onChangeClientState: [Function],
        scriptTags:
        [ { async: true,
             src: 'https://www.googletagmanager.com/gtm.js?id=LEL' },
        ],
        styleTags: [],
        title: 'A title of a page',
        titleAttributes: {} 
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
