### ISSUE TITLE
wrong declaration for 

### ISSUE THREAD

**Issue by xxyyzz2050** [DefinitelyTyped/DefinitelyTyped#34980]
in node documentation [fs.mkdirSync()](https://nodejs.org/api/fs.html#fs_fs_mkdirsync_path_options)  accepts options{} in the second argument, but in declaration it accepts mode?:number | string | null whitch is wrong

![New Bitmap Image](https://user-images.githubusercontent.com/35532104/56717995-9368c780-6746-11e9-99c4-d1b7ef6f8160.jpg)

![502633b8-2878-4286-9ddd-3af850c1f65f](https://user-images.githubusercontent.com/35532104/56718065-c14e0c00-6746-11e9-8d3f-3d330e8299d4.png)

**update**
fixed by forcing update to @types/node@latest

**Comment by j-oliveras** [comment]
I see no errors: node supports a options as second parameter since version 10. See node 10 types: 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/39b4723424d50447bcce7cac1fe3c2b8a223d0cc/types/node/v10/fs.d.ts#L741-L747

`MakeDirectoryOptions` interface:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/39b4723424d50447bcce7cac1fe3c2b8a223d0cc/types/node/v10/fs.d.ts#L703-L714

**Comment by D35** [comment]
Did a global uninstall of the types and reinstall the latest version.
The answer above could be confusing for TypeScript newbies so here is what I did in a Command Window opened as Administrator:

npm uninstall -g @types/node 
npm install -g @types/node@latest

Please suggest alternatives thanks.
