### ISSUE TITLE
Can we get triggerRepaint() added to Map class in mapbox-gl?

### ISSUE THREAD

**Issue by laurenoldham1202** [DefinitelyTyped/DefinitelyTyped#35001]
@macobo or @sandersn I notice that the `triggerRepaint()` method is missing from the Map class in the mapbox-gl types. I need this method for a shared project in which we use npm to install packages. Is it possible to get this update into the npm package?

**Comment by sandersn** [comment]
@laurenoldham1202 Do you know the correct type for `triggerRepaint`? If so, you could contribute it yourself. It's pretty easy to contribute a single method to Definitely Typed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
