### ISSUE TITLE
[firefox-webext-browser] wrong types again for browser.runtime.Port

### ISSUE THREAD

**Issue by jceme** [DefinitelyTyped/DefinitelyTyped#35015]
- [x] I tried using the `@types/firefox-webext-browser` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jsmnbom 

**Related issue**: #23542

Typescript shows an error in the following situations:

```typescript
port.onMessage.addListener(msg => { ... });  // Should accept received message as first parameter.
port.onDisconnect.addListener(...); // Access error
```

This worked in v65.0 but seems to be broken again since v67.0. 
 
I guess the change is introduced by 5591d87ee8ccd9ffdd605ae2f98dbfc309bdac7f

**Comment by jsmnbom** [comment]
Yes I noticed that myself earlier too, thanks for the report. Fix should
come today or maybe tomorrow if I'm too busy :)

**Comment by jsmnbom** [comment]
#35027 just got merged so this should be fixed in the next release :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
