### ISSUE TITLE
Protobuf.js packages deprecated incorrectly

### ISSUE THREAD

**Issue by murgatroid99** [DefinitelyTyped/DefinitelyTyped#35025]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/protobufjs` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @panuhorsmalahti 

The Protobuf.js code appears to have been deleted from this repository and all non-alpha versions of `@types/protobufjs` have been deprecated with the following message:

> This is a stub types definition for protobufjs (https://github.com/dcodeIO/ProtoBuf.js). protobufjs provides its own type definitions, so you don't need `@types/protobufjs` installed!

However, this statement is only true for protobufjs version 6, so deprecating the version 5 types with this message is incorrect.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
