### ISSUE TITLE
Deprecate @types/openui5

### ISSUE THREAD

**Issue by bd82** [DefinitelyTyped/DefinitelyTyped#35039]
Hello.

SAP OpenUI5 type signatures are now (beta) delivered in a separate npm package.
- https://www.npmjs.com/package/@openui5/ts-types

Additionally @types/openui5 has not been updated for a long while.

Is it possible to deprecate @types/openui5 and add a link in the deprecate message
to point to the new @openui5/ts-types package?

Cheers.
Shahar.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
