### ISSUE TITLE
@types/pdfMake images undefined for 

### ISSUE THREAD

**Issue by sbilbault** [DefinitelyTyped/DefinitelyTyped#35081]
Hey,

- I tried using the `@types/pdfMake` package and had problems.
- the property 'images'  and 'background' (as defined in https://pdfmake.github.io/docs/document-definition-object/images/ and https://pdfmake.github.io/docs/document-definition-object/background-layer/) seems to be missing from the interface 

TDocumentDefinitions {
        info?: TDocumentInformation;
        compress?: boolean;
        header?: TDocumentHeaderFooterFunction;
        footer?: TDocumentHeaderFooterFunction;
        content: string | Content;
        styles?: Style;
        pageSize?: PageSize;
        pageOrientation?: PageOrientation;
        pageMargins?: Margins;
        defaultStyle?: Style;
    } 

- Authors: @evolkmann  (types author)

Is there a workaround to include them, or should they be added to the TDocumentDefinitions interface ?

**Comment by evolkmann** [comment]
Hi @sbilbault, I created the types quite a while ago while I was working with the library. The `images` property looks new to me. You can go ahead and open a PR adding this feature.

**Comment by sbilbault** [comment]
Hi @evolkmann 

I made a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35159) to add the missing types I needed, could you please review it ?

Thanks !

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
