### ISSUE TITLE
Incomplete typedescriptions for type <Collection> in mongodb package version 3.2.0

### ISSUE THREAD

**Issue by nokawaii** [DefinitelyTyped/DefinitelyTyped#35097]
Regarding the npm package "mongodb" in Version ~3.2.0 : 

Because of incomplete typedescriptions for at least the type <Collection>, i get typescript compiling errors in my module.

The lacking descriptions for my case are:
 
```
Property 'dropAllIndexes' does not exist on type 'Collection<any>'
Property 'ensureIndex' does not exist on type 'Collection<any>'.
Property 'findAndModify' does not exist on type 'Collection<any>'.
Property 'findAndRemove' does not exist on type 'Collection<any>'.
```
I didnt check all types or properties though. Please complete theses descriptions, so there are no more typescript compiling errors.

Thank you!

**Comment by zgayjjf** [comment]
Is there any reason for removing these methods?

**Comment by nokawaii** [comment]
Why removing? The ticket is about the lack of typedescriptions for using the mongodb package in a TS project without getting compile errors

**Comment by HosseinAgha** [comment]
@nokawaii you'll not get a fast response unless you mention the contributors of the `@types/mongodb` package :). Please fill the issue template and mentions the [@types/mongodb contributors](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongodb/index.d.ts#L4) at the end.    
The methods you mentioned are deprecated since driver version 1 (http://mongodb.github.io/node-mongodb-native/3.3/api/Collection.html#findAndModify).   
Please use the alternatives.

**Comment by mrusme** [comment]
`ensureIndex` doesn't seem to be deprecated, so it should be available, shouldn't it?

**Comment by lenjoseph** [comment]
I understand that the purpose of `ensureIndex` was to avoid duplicate indices. How can this behavior be replicated using `createIndexes`?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
