### ISSUE TITLE
[aws-lambda] Definitions assert existence of likely undefined properties

### ISSUE THREAD

**Issue by LouiseBC** [DefinitelyTyped/DefinitelyTyped#35105]
For example:
```
// API Gateway "event"
export interface APIGatewayProxyEvent {
    // ...
    headers: { [name: string]: string };
    // ...
}
```
Essentially the way these headers are defined means that event.headers.anyValueHere will always be typed as `string`, even though there is a high likelihood of the header not being set.
This issue is present in a bunch of other places too

- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @buggy @MichaelMarner @dalen @MichaelRBond 

P.s. sorry I just tagged some random authors shown in the typescript file. I'm not sure which (if any) of you are actively involved in this project.

**Comment by simonbuchan** [comment]
Going back through `aws-lambda` issues, since they seem to be being neglected.

This seems to be a particular case of Microsoft/TypeScript#13778 (which covers object keys as well as array indexes to some extent)

I'm in theory in favor of making this `headers: { [name: string]: string | undefined }`, as headers are externally controlled and thus likely to not be what you expect, but that would be too much of a breaking change at this point: far too many existing handlers will be doing something along the lines of `event.headers["content-type"].startsWith("text/")`.

Not sure this can be fixed until a major version bump, but that's really ugly to do at the moment, since it's tied to the runtime API which hasn't changed in forever. I'd suggest closing this for now, and if that changes later, this can be done then.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
