### ISSUE TITLE
leaflet - svgOverlay

### ISSUE THREAD

**Issue by sebmat003** [DefinitelyTyped/DefinitelyTyped#35108]
Can you add svgOverlay to `types/leaflet/index.d.ts`?

I have this on leaflet but not in types.

**Comment by JessedeDoes** [comment]
You could add something like this in a local copy of node_modules/@types/leaflet/index.d.ts
(it worked for me) 
```
export interface SVGOverlayOptions extends ImageOverlayOptions {
}

export class SVGOverlay extends ImageOverlay { 
    constructor(svg: string | string[] | SVGElement, bounds: LatLngBoundsExpression, options?: SVGOverlayOptions);
    setOpacity(opacity: number): this;
    bringToFront(): this;
    bringToBack(): this;
    setUrl(url: string): this;

    /** Update the bounds that this VideoOverlay covers */
    setBounds(bounds: LatLngBounds): this;

    /** Get the bounds that this VideoOverlay covers */
    getBounds(): LatLngBounds;

    /** Get the video element that represents the VideoOverlay on the map */
    getElement(): HTMLImageElement | undefined;

    options: SVGOverlayOptions;
}

export function svgOverlay(svg: SVGElement|string, bounds: LatLngBoundsExpression, options?: SVGOverlayOptions): SVGOverlay;

```

**Comment by kygoh** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/03fddd7a3f2322433a867d9edcee561ac85d950d/types/leaflet/index.d.ts#L890-L912

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
