### ISSUE TITLE
`withFileTypes` is an optional boolean value

### ISSUE THREAD

**Issue by matt-laird** [DefinitelyTyped/DefinitelyTyped#35233]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3ab10de30891a34ab1e4ec9702510d14881c4f4d/types/node/fs.d.ts#L828

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
