### ISSUE TITLE
styletron-react

### ISSUE THREAD

**Issue by erictaylor** [DefinitelyTyped/DefinitelyTyped#35302]
Currently working on creating definitions for `styletron-react@>=5.0.0`. I should have a PR up in a couple days. Will also require completion of `styletron-standard` definitions (#35301).

**Comment by erictaylor** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35324 will be needed to complete this.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
