### ISSUE TITLE
[@types/echarts] SankeySeries.links should be an array

### ISSUE THREAD

**Issue by el** [DefinitelyTyped/DefinitelyTyped#35314]
- [x] I tried using the `@types/echarts` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @xieisabug , @AntiMoron , @liveangela ,  @Ovilia , @iRON5 , @bilalucar , @tmtron , @dwhitney

This line should be an array instead. (SankeySeries.links)
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ef62e5ba7aad6502c5ab8f6d9f33841bdef9ddbf/types/echarts/options/series/sankey.d.ts#L2280

**Comment by brendanmckeown** [comment]
I'm also having this issue – `SankeySeries.links` should be an array of objects, not an object.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
