### ISSUE TITLE
[@types/plotly.js] showscale is missing in PlotData

### ISSUE THREAD

**Issue by maxencefrenette** [DefinitelyTyped/DefinitelyTyped#35321]
- [x] I tried using the `@types/plotly.js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @milesjos 

`showscale`is missing in `PlotData`. Is is used for charts such as heat maps. https://plot.ly/javascript/reference

**Comment by Oleh-Stefanovych** [comment]
The same with `selectedpoints`.

**Comment by brammitch** [comment]
I think this can be closed. `showscale` was added in #42882

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
