### ISSUE TITLE
@types/mongoose Query.all() incorrect parameter `val` type

### ISSUE THREAD

**Issue by idanlo** [DefinitelyTyped/DefinitelyTyped#35338]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra and more

In the `Query.all()` method in line `1681-1682` in the `index.d.ts` file it is stated that the `val` is a number which is incorrect, it should be an array of any (`any[]`) according to mongoose docs - https://mongoosejs.com/docs/api.html#query_Query-all

I have a use-case for my app to use `.all` and I cannot use it with typescript because of that error, so I used mongoose syntax `$all` which worked fine.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
