### ISSUE TITLE
Issue in ember.d.ts

### ISSUE THREAD

**Issue by lokananda7** [DefinitelyTyped/DefinitelyTyped#3534]
As ember allows multiple core object arguments while extending any Ember object, I suppose the type definition for "extend" function should follow the rest parameter syntax of typescript as shown below.

```
class Object extends CoreObject implements Observable {
        /**
        Creates a subclass of the Object class.
        **/
        static extend<T>(...arguments?: CoreObjectArguments[]): T;
}
```

instead of the current type definition which doesnot allow extending from multiple classes

```
 class Object extends CoreObject implements Observable {
        /**
        Creates a subclass of the Object class.
        **/
        static extend<T>(arguments?: CoreObjectArguments): T;
}
```

**Comment by mike-north** [comment]
this issue can be closed

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
