### ISSUE TITLE
[@types/webpack] anymatch is not valid deps

### ISSUE THREAD

**Issue by chyzwar** [DefinitelyTyped/DefinitelyTyped#35418]
Webpack typings depends on anymatch. Currently, webpack depend on micromatch.
https://github.com/webpack/webpack/blob/master/package.json

This implicit dependency cause issues with the latest version of anymatch. Matcher type is not exposed in the current release version. Types is now exposed in master but not yet released. 
https://github.com/micromatch/anymatch/blob/3.0.1/index.d.ts

For most people, it is working by accident of having the right version of anymatch hoisted in node_modules.  I suggest removing anymatch dependancy from @types/webapack.  

- [x] I tried using the `@types/webpack` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] Mentions
Authors: @tkqubo, @bumbleblym, @bcherny, @tommytroylin, @mohsen1, @jcreamer898, @elliottsj, @jason0x43, @dennispg, @christophehurpeau, @johnnyreilly, @rwaskiewicz, @kuehlein, @grgur @paulmillr @rubenspgcavalcante 

I get a compilation error: 
```
../../node_modules/@types/webpack/index.d.ts(1045,23): error TS2503: Cannot find namespace 'anymatch'.

```

**Comment by paulmillr** [comment]
This should be fixed with anymatch 3.0.2. Try it.

**Comment by chyzwar** [comment]
Thanks @paulmillr  It fixed my issue but It was not an anymatch problem in the first place. @types/webpack should not depend on anymatch.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
