### ISSUE TITLE
[@types/cron] Argument of type '"* * * * * *"' is not assignable to parameter of type '(string & CronJobParameters)

### ISSUE THREAD

**Issue by francoisromain** [DefinitelyTyped/DefinitelyTyped#35410]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi @winup

Hello, 

```
var { job } = require('cron')
job('* * * * * *', () => { run() }, null, true)
```
this makes a typescript error in vscode: 

```
Argument of type '"* * * * * *"' is not assignable to parameter of type '(string & CronJobParameters) | (Date & CronJobParameters) | (Moment & CronJobParameters)'.ts(2345)
```

**Comment by burtek** [comment]
@francoisromain wrong package. This types are for `node-cron` and you're using `cron`

**Comment by burtek** [comment]
@francoisromain wrong package. You mentioned authors of types for `node-cron` https://github.com/node-cron/node-cron and you're using `cron` from https://github.com/kelektiv/node-cron

**Comment by francoisromain** [comment]
Oups. I edited the message to fix it. I hope authors will receive a mention.

**Comment by burtek** [comment]
Just to be sure: @horiuchi @WinUP, we need you! :D

**Comment by WinUP** [comment]
@francoisromain A pull request was raised to solve this issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
