### ISSUE TITLE
Can't find FoldableTable

### ISSUE THREAD

**Issue by Sergio094** [DefinitelyTyped/DefinitelyTyped#35436]
I'm trying to use the Foldable Table from the documentation of ReactTable

https://www.npmjs.com/package/react-table#foldabletable

```
import FoldableTableHOC from "react-table/lib/hoc/foldableTable";
const FoldableTable = FoldableTableHOC(ReactTable);
```

but when I import it, it gives me this error 

> Could not find a declaration file for module 'react-table/lib/hoc/foldableTable'. '/node_modules/react-table/lib/hoc/foldableTable/index.js' implicitly has an 'any' type.
>   If the 'react-table' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table

In fact I can't find it here:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table/lib/hoc
Is it deprecated?

**Comment by eliaszkubala** [comment]
Did you resolve this issue?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
