### ISSUE TITLE
[@types/iframe-resizer] wrong module name

### ISSUE THREAD

**Issue by Martype** [DefinitelyTyped/DefinitelyTyped#35441]
@polar-lukas it is not "iframeResize**r**". The module is called "iframeResize".

**Comment by zbianca** [comment]
@Martype Can you be more specific?
```
// Type definitions for iframe-resizer 3.5
// Project: https://github.com/davidjbradshaw/iframe-resizer
```
I suppose this issue can be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
