### ISSUE TITLE
[@types/joi] Import stopped working with move to @hapi/joi

### ISSUE THREAD

**Issue by faustinoribeiro** [DefinitelyTyped/DefinitelyTyped#35440]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Bartvds @laurence-myers @cglantschnig @DavidBR-SW @GaelMagnan @ralekna @schfkt @rokoroku @dankraus @wanganjun @rafaelkallis @aconanlai @zaphoyd @thewillg @SimonSchick @afharo

Imports from joi TS definitions (version 14.3.3) stopped working after I updated the joi package to 'hapi/joi'.

**Comment by SimonSchick** [comment]
Install @types/hapi__joi.

**Comment by SimonSchick** [comment]
@sandersn Can we please have all hapi packages deprecated with a notice to use the new ones in the future or something?
We are going to get MANY issues like this.

**Comment by faustinoribeiro** [comment]
Thanks for the quick reply. It's working after a couple of tweaks in my case: replaced occurrences of ```import * as Joi from 'joi';``` with ```import Joi = require('@hapi/joi');``` and ```minDomainAtoms``` with ```minDomainSegments``` in emails validation.

**Comment by sandersn** [comment]
@SimonSchick can you explain more. Did the hapi packages move? Which packages moved to what new names?

**Comment by SimonSchick** [comment]
The only reference I can find atm is this: https://github.com/hapijs/hapi/issues/3941
But yes, pretty much everything in the hapi org is now released in the hapi namespace.

@hueniverse I couldn't find an official announcement that exactly explains what happens to non-namespaced modules, can you explain it here and/or link us to the corresponding docs?

**Comment by sandersn** [comment]
What does that mean for DT? How do I get a list of the packages that need to be deprecated?

**Comment by hueniverse** [comment]
Everything outside the namespace is now deprecated. And I'm starting to move types into the namespaced modules. Still working on support for types testing in lab.

**Comment by zveljkovic** [comment]
For anyone stumbling on this issue, you can create own typings for new npm `@hapi/XXX` packages. I have solved my TypeScript compilation issues with these three definitions. 

https://gist.github.com/zveljkovic/ffec59003dc76cc54c5c9cf644368f6d  hapi__boom.d.ts
https://gist.github.com/zveljkovic/a4153a26c780c0fb37486a62c4aefc4b hapi__hapi.d.ts
https://gist.github.com/zveljkovic/ac17b2280a36b218b3cc4fe072ffa147 hapi__inert.d.ts

Approach was to use existing @types/XXX definitions and to change `declare module 'hapi'` to `declare module '@hapi/hapi'` or to wrap the definition inside `declare module '@hapi/hapi'` if there was nothing to change. Also imports in the definitions should be changed to @hapi/hapi instead of just hapi.

I think similiar will work for joi or other modules. 


Be sure to include in .tsconfig, path to directory for your typings folder
```
{
	"compilerOptions": {
		...
		"typeRoots" : ["./node_modules/@types", "./typings"]
	}
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
