### ISSUE TITLE
[@types/socket.io][@types/socket.io-client] Options missing option parser

### ISSUE THREAD

**Issue by CipSoft-Components** [DefinitelyTyped/DefinitelyTyped#35469]
The options are missing the option `parser` to set a custom parser.
e.g. [https://github.com/darrachequesne/socket.io-msgpack-parser](https://github.com/darrachequesne/socket.io-msgpack-parser)

I tried the latest definitions.

Authors:
- @divillysausages 
- @florentpoujol 
- @KentarouTakeda 
- @gigi 
- @BrainMaestro

**Comment by JDThralls** [comment]
Is a merge for that coming any time soon? this problem still persists, but the PR has been closed by the bot without being merged.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
