### ISSUE TITLE
unionBy doesn't type check as well as it should

### ISSUE THREAD

**Issue by wbhob** [DefinitelyTyped/DefinitelyTyped#35485]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/lodash` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @aj-r @e-cloud @thorn0 @jtmthf @DomiR

It seems like `unionBy` would be an ideal use case for the `keyof` operator. I was thinking a signature would like this:

```
unionBy<T>(...objects: T, iteratee: keyof T)
```

I know this isn't _quite_ the right syntax, but I do recall seeing some information from the TS team that lets you rest the first `n` arguments, and the `n + m` arguments can be treated as normal arguments. I think this is a good application of `keyof` for typechecking, since in our codebase, it does not throw a compilation error if the key is not on the interface that is being unioned.

I just wanted to open an issue first for discussion, and if some of the contributors agree or have input on this proposal, I'm here for it, and if you want, I can also open a PR because this would help our code a lot!

**Comment by aj-r** [comment]
As far as I can tell, rest parameters still need to be at the end of the function, but if you find some documentation saying otherwise, let me know! That would be useful for more functions than just `unionBy`.

As for `keyof` - yes this does sound like the right thing to do, but again, it would affect more than just `unionBy`. The underlying type to change is:

```ts
type IterateeShorthand<T> = PropertyName | [PropertyName, any] | PartialDeep<T>;
```

(where `PropertyName = string | number | symbol`). We might want to replace both instances of `PropertyName` with `keyof T`. We should think carefully, though, to see if there are any instances where this would break people. I'm mainly concerned about this case:

```ts
interface A {
  id: string;
}
interface B extends A {
  specialProperty: string;
}
const array: Array<A | B> = [...];
const arrayOfBOnly = _.filter(array, "specialProperty");
```

I'm worried that this would give an error like "'specialProperty' does not exist on type 'A'". However I'm not sure if this is a common thing to do - maybe we can drop support for that use case?

**Comment by wbhob** [comment]
I think this is what I was thinking of: https://devblogs.microsoft.com/typescript/announcing-typescript-3-0-rc-2/#tuples-and-parameters. I'm not quite sure if this is applicable, but it seems like something from this could be implemented. 

Also, in terms of the `keyof` stuff: seems like as long as it works with optional types, it should be compatible. (`property?: string`). Also, it may be worthwhile to explore the implications of making a union of the types passed into `unionBy` – that way, as long as one object passed in has that property, then there is no type error.

However, what comes to mind is that when using something like `unionBy`, your explicit goal is to make a combined array of the _same type_. If we had the following interfaces:

```
interface Dog {
	paws?: number
	bark?: boolean
}

interface Kitchen {
	utensils?: number
	potsAndPans?: number
}
```

The union of these two would be meaningless. However, if one extended the other, then I think that if the property is on _one_ of the types (like I said before) it should pass. Thoughts?

**Comment by aj-r** [comment]
I agree, as long as the property is on one of the types, it should pass.
I'm just not sure if that's possible:). If you find a way to do it then go
for it.

**Comment by wbhob** [comment]
My thought would be to do something like this:

```ts
unionBy<T, U, V>(arg1: T, arg2: U, arg3:V, iteratee: keyof T & U & V)
```

Would this work? 

In hindsight, I realize that my Dog & Kitchen example is contrived and impossible to implement. However, we could take one of two directions: either union (`Dog & Kitchen`) as above, or force everything to be of type `<T>`.

**Comment by aj-r** [comment]
Ah yes that sounds like it could work

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
