### ISSUE TITLE
Problem using CreateJS libraries with Visual Studio 2013

### ISSUE THREAD

**Issue by tsiliopoulos** [DefinitelyTyped/DefinitelyTyped#3551]
The update to easeljs, tweenjs, soundjs, and preloadjs from 10 days ago seems to conflict with Visual Studio 2013 with Web Essentials for Update 4.

I believe some of the new union types are being used and are only supported by TypeScript version 1.4. The newer type definition files are the only ones available via NuGet Package Manager .

**Comment by bruniasty** [comment]
After update to TypeScript 1.4 all projects stop working: webrtc and webaudioapi libraries do not compile at all (so soundjs is useless too). Moreover canvas elements do not have width and height properties. This release is a disaster and broke my whole project...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
