### ISSUE TITLE
[micromatch] missing v4 typings

### ISSUE THREAD

**Issue by G-Rath** [DefinitelyTyped/DefinitelyTyped#35529]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @glen-84 @vemoo

If you do not mention the authors the issue will be ignored.

----

v4 of `micromatch` are out, with some changes.

One of the big ones is that a lot of `string` arguments are now `string|Array`.

**Comment by glen-84** [comment]
Send a PR?

**Comment by G-Rath** [comment]
I would if I had the typings on hand, but sadly I don't have the time to deal with checking out DefinitelyTyped locally, let alone making the typings.

Plus I don't use micromatch that much - I merely made this issue to get it written down and kicked off.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
