### ISSUE TITLE
[@types/react-native-push-notification] Conflicting interface names

### ISSUE THREAD

**Issue by gabsima-nexapp** [DefinitelyTyped/DefinitelyTyped#35526]
- [X] I tried using the `@types/react-native-push-notification` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] Authors: @PaitoAnderson @tomSawkins 

There are 2 interfaces defined in the typings with the same name `PushNotification`. One is used to describe the library with all the methods available, and the other is used to describe the notification itself.

Also, i noticed the `data` attribute is typed as an object, when it should be `any` because anything could be inside this object.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
