### ISSUE TITLE
Property ctx.log and log methods are missing in Context interface definition.

### ISSUE THREAD

**Issue by DazSanchez** [DefinitelyTyped/DefinitelyTyped#35558]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/server` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sant123 @iddan

If you do not mention the authors the issue will be ignored.

**Comment by sant123** [comment]
Hi @DazSanchez, currently those methods are not in the official documentation. Please see https://serverjs.io/documentation/context/

However if you think this is in other place, please paste it here to review it.

**Comment by DazSanchez** [comment]
There's actually some documentation about loggin from the context object here: https://serverjs.io/documentation/options/#log
This shows ctx object used by simple middleware function, however this methods are also available on ctx object inside router methods

**Comment by sant123** [comment]
Awesome! May you create a PR for that? I think that magic could go after line 37:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/server/typings/common.d.ts#L37

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
