### ISSUE TITLE
[@types/react] contentEditable event states support

### ISSUE THREAD

**Issue by yuxino** [DefinitelyTyped/DefinitelyTyped#35578]
I am try to using `plaintext-only` in `contentEditable` .  But vscode warning me `Type 'string' is not assignable to type 'boolean'.`. 

I am a typescript newbie , i don't know how to add definition for [this](https://w3c.github.io/editing/contentEditable.html#contenteditable-states). @Jessidhia

**Comment by fimars** [comment]
cc @johnnyreilly @eps1lon

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
