### ISSUE TITLE
Partial Definitions

### ISSUE THREAD

**Issue by M-Zuber** [DefinitelyTyped/DefinitelyTyped#3558]
The [chartjs](https://github.com/borisyankov/DefinitelyTyped/tree/master/chartjs) definition is missing a few parts.

Per the [documentation](http://www.chartjs.org/docs/) you should be able to do this:

``` js
Chart.defaults.Line = {/* LineChartOptions*/};
Chart.defaults.Line.scaleShowGridLines = false;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
