### ISSUE TITLE
missed eagerInstantiationEnabled option in ngRoute

### ISSUE THREAD

**Issue by WuglyakBolgoink** [DefinitelyTyped/DefinitelyTyped#35593]
Hallo @park9140 @gkalpak,

missed `eagerInstantiationEnabled` option in ngRoute

**Comment by gkalpak** [comment]
True 😅
Feel free to submit a pull request adding the missing method :wink:

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
