### ISSUE TITLE
[@types/react-virtualized] Incorrect typeof `Table.defaultProps.headerRowRenderer`

### ISSUE THREAD

**Issue by Zodiase** [DefinitelyTyped/DefinitelyTyped#35611]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6818b51c5b6556ac5f75b2df7524535c6294c50e/types/react-virtualized/dist/es/Table.d.ts#L444

It should be `headerRowRenderer: TableHeaderRowRenderer;`

## Reproduction:

```TypeScript
const CustomTable: FunctionComponent<TableProps> = (props): ReactElement => {
    return <Table {...props} />;
};
CustomTable.defaultProps = Table.defaultProps;
```

![image](https://user-images.githubusercontent.com/1815174/58056232-4b567e00-7b15-11e9-9751-0c13b684efe4.png)

**Comment by andap** [comment]
This is fixed in the latest version.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
