### ISSUE TITLE
React children type is too wide

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#35622]
Below are examples of mistakes I make all the time. For that reason, I would really like for these to be type errors, so I can catch these mistakes earlier.

IIUC, the reason these are not type errors is because the `children`/`ReactNode` type includes `{}`, which allows almost anything through. That begs the question, can we remove `{}`, or is there a valid reason to keep it?

#### Passing a function as a React child (forgot to call the function)

``` tsx
import * as React from 'react';
import { FC } from 'react';

const renderChildren = () => 'foo'

declare const MyComponent: FC<{}>;
// Oops! We forgot to call this function. But we got no type error :-(
<MyComponent>{renderChildren}</MyComponent>;

// Should be:
// <MyComponent>{renderChildren()}</MyComponent>;
```

#### Passing an `Option` as a React child (forgot to serialize/decode)

``` tsx
import * as React from 'react';
import { FC } from 'react';

type Option<T> = { value: T, orNull: () => T | null }
declare const myOption: Option<string>

declare const MyComponent: FC<{}>;
// Oops! We forgot to serialize/decode this `Option`. But we got no type error :-(
<MyComponent>{myOption}</MyComponent>;

// Should be:
// <MyComponent>{myOption.orNull()}</MyComponent>;
```

---

One workaround I know of is to explicitly define the `children` prop:

``` tsx
import * as React from 'react';
import { FC } from 'react';

const renderChildren = () => 'foo'

declare const MyComponent: FC<{ children: string }>;
// Oops! We forgot to call this function. We got a type error :-)
<MyComponent>{renderChildren}</MyComponent>;

// Should be:
<MyComponent>{renderChildren()}</MyComponent>;
```

However I hoped this wouldn't be necessary. That also doesn't help when passing children to a DOM component:

``` tsx
// Oops! We forgot to call this function. But we got no type error :-(
<div>{renderChildren}</div>;
```

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon 

If you do not mention the authors the issue will be ignored.

**Comment by eps1lon** [comment]
> Passing a function as a React child (forgot to call the function)

Structurally this is a valid function component in react. It is only rejected in TypeScript because of #20544 which is blocked by microsoft/TypeScript#21699.

It's probably better to write a lint rule for that which can consult the variable name and infer that this is not a function component. 

> Passing an Option as a React child (forgot to serialize/decode)

Is likely an issue with `ReactFragment` which is typed as `{}`. Did some quick testing locally with the `{}` removed and the react tests passed with one exception (which would crash at runtime anyway).

**Comment by ferdaber** [comment]
Nothing is ever rejected by React as far as passing children down to compound components, but when we're talking about host components then there are limitations, so we should be clear in what we actually want typechecking for. I think the best approach right now is to always explicitly type the children you expect, and for us to change the `ReactNode` type to be stricter to what host components expect.

We've tried fixing this a few times in the past but it's an incredibly large breaking change so we've kind of put it off until the next major version of React to minimize disruptions.

**Comment by OliverJAsh** [comment]
Thanks for the responses!

> change the `ReactNode` type to be stricter to what host components expect.

IIUC, the change you're suggesting would mean my above examples would error (as desired) when passing children to a `div`, for example. Is that correct?

Can you elaborate on why we can't make the same change for compound (custom?) components?

> Nothing is ever rejected by React as far as passing children down to compound components

If it's because "React wouldn't error at runtime, so the types should allow it", I would question if there are any valid, practicable use cases where functions/objects would be used as children. If there aren't any, it makes sense to me that the types could be stricter than React is. After all, this would only prevent silly people like me from making mistakes.

> always explicitly type the children you expect

I would be happy to define children explicitly, but since that isn't currently required, it would be easy to forget. I would prefer a sensible default (i.e. the examples above should error, because they make no sense at runtime), or no default, so I would be forced to define children explicitly.

I fully appreciate this would be far from a simple change to make. I'm mostly interested in what the correct behaviour should be. My team might decide to patch/fork the React types in order to fix this issue, if we can't fix it upstream.

**Comment by eps1lon** [comment]
> Nothing is ever rejected by React as far as passing children down to compound components

Right. For objects as children there might be an argument but rejecting functions would basically eliminate render-props.

Restricting the children for host components is tempting but this would break the code for everyone that has their children typed as `ReactNode` (which can happen implicitly).

It's probably best to introduce a stricter `HostChildren` type and advocate for that if you pass `children` into a host component.

**Comment by ferdaber** [comment]
@OliverJAsh compound components are allowed to manipulate children however as they want. We have render props as an example of children-as-functions, and some i18n libraries like i18next use children-as-objects. It's definitely not in the camp of "the types should fully reflect the runtime," but rather it's because of the complete flexibility the runtime allows for compound components.

As far as default goes, that's kind of what I was saying is that when we talk about "sensible defaults" we're almost always referring to children that get inserted in a JSX expression where the parent JSX tag is a host component, that's the stuff that React will yell at you for in dev mode if you pass functions or objects. It may not look like it since they can get passed down several levels before actually being rendered to the DOM, but in the end those children are going to be children of a host component.

It's why `ReactNode` is kind of weirdly problematic because its usage/definition is overloaded to mean multiple things:
- what can be returned from a render function
  - narrowest: `number | boolean | Element[] | Element | null | string`
- what can be accepted and rendered as a child of a host component
  - wider: `AboveTypes | undefined`
- what can be between the tags in a JSX expression
  - widest: `any`

**Comment by fantapop** [comment]
Would the suggested fixes also fix the issues described here?

https://stackoverflow.com/questions/44475309/how-do-i-restrict-the-type-of-react-children-in-typescript-using-the-newly-adde#answer-49408900

**Comment by giogonzo** [comment]
@OliverJAsh I guess the only option here to keep a decent level of sanity is:
- in own component declarations, always type the `children` prop precisely
  - even if accepting an "unknown" JSX tree, avoid using `React.ReactNode` directly, prefer a redefinition without `{}` as member of the union
- do not use react intrinsic elements directly in JSX (i.e. re-define `<div>` if you need it)

did you come to different conclusions?

> My team might decide to patch/fork the React types in order to fix this issue, if we can't fix it upstream.

something happened here?

**Comment by G-Rath** [comment]
I stumbled across this (& duplicates) while trying to process the fact that TypeScript considered this valid:

```
const mapStepsToTree = (steps: CursorStep[]): React.ReactNode =>
  steps.map(s => s);
```

Having read over the issues that are around on this, it's sounding like the best non-breaking step forward towards getting this situation improved would be to define a set of strict "helper" types, and encourage people to use them to explicitly type their components children:

```
type RenderFunctionReturn = number | boolean | React.ReactElement[] | React.ReactElement | null | string;
type RenderableHostComponentChild = RenderFunctionReturn | undefined;
type ValidValueToPassToJSXExpression = any;
```

Personally, I'm still trying to wrap my head around what types I should be using to represent what in JSX, so having types like the above that have been agreed upon as the The Right Types would be a huge win.

**Comment by eps1lon** [comment]
Technically `react` shouldn't be responsible for declaring what type a host component accepts. The renderer decides that as far as I know. The question is if it makes practically sense to restrict `ReactNode` to `number | boolean | null | undefined | string | React.ReactElement | React.ReactElement[]`. 

What types do host components in react-native accept?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
