### ISSUE TITLE
[@types/react-filepond] FilePondCallbackProps.onprocessfile params error

### ISSUE THREAD

**Issue by cbfrank** [DefinitelyTyped/DefinitelyTyped#35676]
In @types\react-filepond\index.d.ts, the FilePondCallbackProps.onprocessfile is defined as below:
onprocessfile?: (file: File, error: FilePondErrorDescription) => void;
while the correct one shoule be
onprocessfile?: (error: FilePondErrorDescription, file: File) => void;
The first param should be error then file

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
