### ISSUE TITLE
react-material-ui-form-validator: no `label` prop allowed

### ISSUE THREAD

**Issue by glassdimly** [DefinitelyTyped/DefinitelyTyped#35729]
@FrankBrullo,

This concerns @types/react-material-ui-form-validator:

Here's the error:
```
Error:(48, 18) TS2322: Type '{ label: string; id: string; value: string; name: string; validators: string[]; errorMessages: string[]; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<TextValidator> & Readonly<ValidatorComponentProps & TextFieldProps> & Readonly<{ children?: ReactNode; }>'.
  Property 'label' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<TextValidator> & Readonly<ValidatorComponentProps & TextFieldProps> & Readonly<{ children?: ReactNode; }>'.

Here's the code: 
```
            <ValidatorForm onSubmit={this.handleSubmit} onError={errors => console.log(errors)}>
                <TextValidator
                    label="Email"
                    name="email"
                    validators={['required', 'isEmail']}
                    errorMessages={['this field is required', 'email is not valid']}
                />
           </ValidatorForm>
```

According to the library, "You can pass any props of field components"

`label` and any arbitrary props should be passed through.

**Comment by FrankBrullo** [comment]
@glassdimly Thanks for your PR. I have approved your changes.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
