### ISSUE TITLE
@types/mongoose Typed mongoose Document

### ISSUE THREAD

**Issue by miqmago** [DefinitelyTyped/DefinitelyTyped#35755]
I'm aware that you can use `set` property from mongoose document.

Even though I'm defining interfaces for models, so it is easier to know the document property. Would it be possible to define a typed mongoose document? Right now tslint is giving an error:

```ts
export interface IMyModel {
    whatever: number;
}

        const mdoc = await MyModel.findOne({}).exec();
        // Could be defined like this:
        // const mdoc: Document<IMyModel> = await MyModel.findOne({}).exec();
        mdoc.whatever = 2;
```

```
Property 'whatever' does not exist on type 'Document'.ts(2339)
```

Authors: @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @danmana @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @Vladmel1234 @jloveridge

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
