### ISSUE TITLE
@types/mongoose missing schema.options

### ISSUE THREAD

**Issue by miqmago** [DefinitelyTyped/DefinitelyTyped#35754]
Trying to add transform function as explained [in mongoosejs documentation](https://mongoosejs.com/docs/api.html#document_Document-toObject) but seems there is a mistake in `schema` definition:

```ts
const userSch = new Schema({
    created: { type: Date, default: Date.now },
    lastModified: { type: Date, default: Date.now },
    active: { type: Boolean, default: false },
    isLegalAccept: { type: Boolean, default: false },
    ...,
});
if (!userSch.options.toObject) {
    userSch.options.toObject = {};
}
if (!userSch.options.toJSON) {
    userSch.options.toJSON = {};
}

const transform = (doc, ret) => {
    const user = ret;
    delete user.activation_code;
    delete user.password_reset_code;
    delete user.password_reset_time;
    delete user.password;
    return user;
};

userSch.options.toObject.transform = transform;
userSch.options.toJSON.transform = transform;
```

```
Property 'options' does not exist on type 'Schema<any>'.ts(2339)
```

- Authors: @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @danmana @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge

**Comment by frontendmonster** [comment]
Confirmed, `schema.options` is valid field on `Schema`.
but that's not well documented in mongoose api documentation.

**Comment by Tokenyet** [comment]
According to the [source code](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7f9ef75bffd7ea782bfaf98ffd16c1bdcf2fcbb0/types/mongoose/index.d.ts#L904), here is an example to set options:
mongoose.plugin((schema: mongoose.Schema) => { schema.set("usePushEach", true); });

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
