### ISSUE TITLE
@types/cytoscape do not support layout extension layout options

### ISSUE THREAD

**Issue by justinjdickow** [DefinitelyTyped/DefinitelyTyped#35793]
@phreed @wy193777 @ypconstante @janniclas @cerberuser

When using a custom layout extension in cytoscape the author of the extension provides custom options for layout. For example

```
cytoscape.use(klay)
let cy = cytoscape({
      container: this.container.current,
      elements: this.createElements(this.props.procedure.start),
      style: style
      layout: {
        name: 'klay',
        nodeDimensionsIncludeLabels: true,
        klay: {
          customOption: customOptionValue
        }
      }
    })
```

When you do this in typescript you get an error `not assignable to parameter of type 'CytoscapeOptions'`

The only way I could find to allow the custom options of the layout extensions is to add another interface to the LayoutOptions type like

```
type LayoutOptions =
        NullLayoutOptions | RandomLayoutOptions | PresetLayoutOptions |
        GridLayoutOptions | CircleLayoutOptions | ConcentricLayoutOptions |
        BreadthFirstLayoutOptions | CoseLayoutOptions | BaseLayoutOptions | OtherRandomOptions;

interface OtherRandomOptions {
  [key:string]: value
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
