### ISSUE TITLE
@types/mongoose documentArray suppose to return documentArray type on filter

### ISSUE THREAD

**Issue by lchimaru** [DefinitelyTyped/DefinitelyTyped#35791]
I believe documentArray should overwrite returning value of ```filter``` method, which incorrectly returning Array type instead of documentArray type. Take a look on following example:
```typescript
interface IChildDocument extends Types.Subdocument {
  a: string;
}

interface IParent {
  children: Types.DocumentArray<IChildSchema>
}

const a: IParent = {
  children: new Types.DocumentArray()
}

a.children = a.children.filter(child => child.a === 'a');
```

```a.children``` will return following error:

> Type 'IChildDocument[]' is missing the following properties from type 'DocumentArray<IChildDocument>': create, id, inspect, toObject, and 7 more.ts(2740)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
