### ISSUE TITLE
@types/slate Types need updates to reflect breaking changes (v. 0.48)

### ISSUE THREAD

**Issue by hanstar17** [DefinitelyTyped/DefinitelyTyped#35800]
It seems that the types are 0.04 versions behind the slate package. Is anyone working on updating types?

Thanks in advance!

- [x] I tried using the `@types/slate` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andykent @majelbstoat @JanLoebel @YangusKhan @kalley @Kornil @isubasti @sgreav @jackall3n @benjiro

**Comment by kaydelaney** [comment]
Hey, I've started working on this. Should hopefully have a PR up within the next day or so.

**Comment by hanstar17** [comment]
Thanks for the work @kaydelaney, I appreciate it!

**Comment by benjiro** [comment]
@kaydelaney how are you going with this? I'm able to give you a hand if you're having any troubles. I was about to start working on the new types but if your already working on it I don't mind pitching in.

**Comment by kaydelaney** [comment]
@benjiro i've been a little busy with other things at work but it's moving along, and should hopefully be done by the end of the week.

**Comment by kaydelaney** [comment]
Just to update, I should have a PR for this up later today

**Comment by kaydelaney** [comment]
Or maybe not, since Github seem to be having trouble. 😅

**Comment by kaydelaney** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37076

I don't have time to look into why this is failing on CI at the moment, but for those who are interested, feel free to take a look at the PR and leave comments or suggestions if you'd like.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
