### ISSUE TITLE
[@types/async] update async definition for version 3.0.x

### ISSUE THREAD

**Issue by erossignon** [DefinitelyTyped/DefinitelyTyped#35819]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/async` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Dmitri1337 @pascalmartin @fenying @Penryn @kern0 @borisyankov

If you do not mention the authors the issue will be ignored.

because of some breaking changes in 3.0.0 ( such as AsyncQueue drain etc ...)
@types/async 2.4.2 causes typescript compilation error when trying to fix code to new API.
see https://github.com/caolan/async/issues/1651

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
