### ISSUE TITLE
[@types/stripe] Stripe.terminal is not defined

### ISSUE THREAD

**Issue by Joel-Raju** [DefinitelyTyped/DefinitelyTyped#35821]
Tagging authors  @wjohnsto  @CodeAnimal  @sampsonjoliver  @LinusU  @brannon @kkamperschroer @starhoshi @bruun  @galtalmor @htunnicliff  @squirly  @tzarger @coffee-powered-coder 

Stripe.terminal is not defined. 
I'm trying to generate a token using ```stripe.terminal.connectionTokens.create()```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
