### ISSUE TITLE
@types/pg cannot compile with moduleResolution: "classic"

### ISSUE THREAD

**Issue by andrewdelph** [DefinitelyTyped/DefinitelyTyped#35870]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by andrewdelph** [comment]
@pspeter3

**Comment by andrewdelph** [comment]
"compilerOptions": {
        "target": "es6",
        "module": "none",
        "moduleResolution": "classic",
        "lib": ["es7", "es6", "dom"],
        "declaration": true,
        "outDir": "./lib",
        "strict": true
    },

**Comment by pspeter3** [comment]
Can you include the error messages as well please?

**Comment by andrewdelph** [comment]
node_modules/@types/webpack-sources/index.d.ts:10:62 - error TS2307: Cannot find module 'source-map'.

10 import { SourceNode, RawSourceMap, SourceMapGenerator } from 'source-map';
                                                                ~~~~~~~~~~~~


Found 1 error.

**Comment by andrewdelph** [comment]
node_modules/@types/pg/index.d.ts:225:21 - error TS2307: Cannot find module '.'.

225 import * as Pg from '.';
                        ~~~

**Comment by MarkSill** [comment]
Same error with module: "amd" and no change to moduleResolution.

**Comment by Sebruck** [comment]
Setting `moduleResolution` to `node` fixes the problem

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
