### ISSUE TITLE
Getting involved

### ISSUE THREAD

**Issue by pspeter3** [DefinitelyTyped/DefinitelyTyped#3588]
I really appreciate the DefinitelyTyped community and I was wondering if there was more that I could do besides submitting pull requests. Any feedback or suggestions would be appreciated! :smile:

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
