### ISSUE TITLE
Importing AppAuth from expo not working

### ISSUE THREAD

**Issue by akutamruta** [DefinitelyTyped/DefinitelyTyped#35896]
- [x] I tried using the `@types/expo` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @KonstantinKai @martynaskadisa @janaagaard75 

I'm using Expo client to build a react native app. I'm using v32.0.13 of @types/expo but still while importing AppAuth from expo I'm getting following error:
Module '"../../../../../../Users/abc/Development/Help/node_modules/@types/expo"' has no exported member 'AppAuth'. [2305]
This issue was marked as resolved in #3520 but I'm still seeing this issue.
What release of @types/expo has this fixed ?

Environment
Expo client

Steps to Reproduce
Install expo version 32.0.6 and @types/expo as 32.0.13 in Expo client react-native app.
Do import { AppAuth } from 'expo';
Error mentioned above shows up

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
