### ISSUE TITLE
Missing Promise types in requestretry module

### ISSUE THREAD

**Issue by baaka-ani** [DefinitelyTyped/DefinitelyTyped#35902]
The `requestretry` module is missing typings for promises.

I have created a PR to add these typings. @EricByers @trainerbill  Please review my PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35903

I have extended `request.Request` type to have promise methods like then, catch and finally too

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
