### ISSUE TITLE
react-native BUTTON interface must have an optional style  type.

### ISSUE THREAD

**Issue by justinlazaro-ubidy** [DefinitelyTyped/DefinitelyTyped#35910]
its nice if we have an optional stype type in button interface

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/21e68259f6fd43aba37e8112e3edb792975f8266/types/react-native/index.d.ts#L7173

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
