### ISSUE TITLE
Response.locals doesn't allow for type safety

### ISSUE THREAD

**Issue by jamesmfriedman** [DefinitelyTyped/DefinitelyTyped#35927]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  

## The problem
In a nuthsell, you can't make response.locals typesafe. This is important because it's considered the "right" way to pass information around through the lifecycle of a request.

- Response.locals is currently declared as `any` in express-serve-static-core
- Attempting to use declaration merging directly on express-serve-static core results in an expected TS error
```
declare module 'express-serve-static-core' {
  interface Response {
    locals: Locals;
  }
}

Subsequent property declarations must have the same type.  Property 'locals' must be of type 'any', but here has type 'Locals'.ts(2717)
```
- You can declare `locals` on the Express.Response interface, but the `any` declaration will wi everytime.
```
declare global {
  namespace Express {
    interface Response {
     // this will do nothing...
      locals: Locals;
    }
  }
}
```

## I THINK the right way to solve this is as follows
- Don't declare Locals as "any" anymore.
- Create a new interface called `Locals`
- This would require people to properly type res.locals.
```
interface Locals {
  myProp: string
}

```
- If they wanted to opt into the current `any` style behavior, they could add something like this to their local definitions
```
interface Locals {
  [key: string]: any
}

```

Thoughts?

@borisyankov
@19majkel94 
@kacepe
@micksatana
@samijaber

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by zgrybus** [comment]
Any updates on that? Still doesn't work

**Comment by orta** [comment]
You're welcome to start a GitHub discussion on it or a PR and try to fix it
