### ISSUE TITLE
How to use sinon types?

### ISSUE THREAD

**Issue by nicojs** [DefinitelyTyped/DefinitelyTyped#36019]
Authors: @mrbigdog2u, @rationull, @lumaxis, @43081j, @joshuakgoldberg, @gjednaszewski, @johnjesse, @alecf, @SimonSchick, @bergundy

Hi fellow sinon type authors 👋 . Sorry for the inconvenient cry for attention (it always comes at a bad time, feel free to ignore).

I've updated to the latest version `@types/sinon` yesterday. I needed to add generic classes to my stubs like so:

![image](https://user-images.githubusercontent.com/1828233/59089103-99d38d00-8909-11e9-96d6-6b592e10a9f8.png)

My question is: am I using the sinon types correctly? I don't feel like these typings improved the maintainability of my code. As soon as a method changes its signature I will need to update the mocks in all classes. That doesn't feel helpful. Am I doing something wrong here? 

The problem is that with mocha we declare stubs before we initialize them (in `beforeEach`). Is there a way around it that I'm unaware of? Or is everyone typing all these generic types by hand?

Thanks in advance for any help.

**Comment by 43081j** [comment]
the aim isn't to let you write less, its to have stronger types. those stubs will now have the correct type information with all the assertion methods correctly typed (e.g. `returns` will only accept what you said the method returns). 

having to be a bit more verbose is the cost of declaring all your variables before they are assigned to, its not a problem and is making good use of the types still.

**Comment by nicojs** [comment]
I've found a way around having to manually type the stubs using a small helper class:

```ts
    class TestHelper {
        existsSyncStub = sinon.stub(fs, 'existsSync');
        streamStub = {
            pipe: sinon.stub(),
            on: sinon.stub()
        };
        streamToPromiseStub = sinon.stub(Utils, 'streamToPromise');
        gotStreamStub = sinon.stub(got, 'stream');
        mkdirSyncStub = sinon.stub(fs, 'mkdirSync');
        statSyncStub = sinon.stub(fs, 'statSync');
        createWriteStream = sinon.stub(fs, 'createWriteStream');

        constructor() {
            this.gotStreamStub.returns(this.streamStub as any);
            this.streamStub.pipe.returns('expected piped value');
        }
    }
    let testHelper: TestHelper;

    beforeEach(() => {
        log = sinon.stub();
        testHelper = new TestHelper();
    });
```

Is this the way to go? Could we maybe document this somewhere so people use this way of writing code? Reaping the benefits from a short syntax and strong typing.

(getting old Java vibes from this way of working 🙈)

**Comment by 43081j** [comment]
@nicojs it seems typescript 3.5.1 release affected this, i hadn't realised!

```ts
// TS3.4
let stub: sinon.SinonStub; // this means its <any[], any>
stub = sinon.stub(obj, 'method'); // WORKS!

// TS3.5.1
let stub: sinon.SinonStub;
stub = sinon.stub(obj, 'method'); // Type 'SinonStub<[string, string], string> is not assignable to 'SinonStub<any[], any>'
```

@rbuckton do you happen to know which change between 3.4 and 3.5.1 might have caused this?

I guess the solution would be to update every usage to be `sinon.SinonStub<any>` like you recommended in my previous PR?

**Comment by JohannLai** [comment]
I got this error when resole for a promise function
```
Type 'string' is not assignable to type 'never
```

```
(method) Sinon.SinonStub<TArgs extends any[] = any[], TReturnValue = any>.resolves(value?: never): sinon.SinonStub<any[], any>
```

how can i make it work ? thanks

**Comment by Codex-** [comment]
yeah the recent changes unfortunately broken the spy method typing too

**Comment by rbuckton** [comment]
@DanielRosenwasser: Do you know what change in 3.5 could have affected this?

**Comment by 43081j** [comment]
Do note for those of you appearing here, it is not a sinon types problem, they have not changed and are correct.

The problem exists between TS3.4 and 3.5.

The error is correct: you can't assign `[TFoo, TBar]` to `any[]` as it isn't an array, it is a tuple.

TypeScript 3.4 must have inferred looser types or some such thing, or maybe it inferred a union (`any[]|[TFoo,TBar]`) whereas 3.5 now uses the default (`any[]`).

**Comment by 43081j** [comment]
As for the people having problems with `resolves`, it is due to changes in #31401.

That PR correctly tries to infer the promise's value type and, if it is impossible, is typed as `never` which means you can't use it.

Here's some examples to explain its behaviour:

```ts
// THIS WORKS

class Foo {
 myMethod(): Promise<boolean>;
}

const stub = sinon.stub(instanceOfFoo, 'myMethod'); // TReturnType will be Promise<boolean>
stub.resolves(true); // Because it is a Promise, the types correctly infer this needs a boolean

// THIS DOES NOT WORK

class Foo {
 myMethod(): any;
}

const stub = sinon.stub(instanceOfFoo, 'myMethod'); // TReturnType will be `any`
stub.resolves(true); // Because it is a `any`, it isn't typed as a Promise, so resolves doesn't know what to accept: hence, `never`

// THIS ALSO DOES NOT WORK

class Foo {
 myMethod(): Promise<boolean>;
 myMethod(foo: boolean): void; // This is an overload
}

const stub = sinon.stub(instanceOfFoo, 'myMethod'); // TReturnType will be `void`
stub.resolves(true); // Because there is an overload, TS can't infer which return type you're expecting, so again it is `never`
```

@pjo336 this example above, in particular the overloads (3rd example), is why bcryptjs types don't work with it as there are two `compare` overloads with different return types.

The sinon types should probably be loosened to default to `any` if the type can't be inferred, _not_ `never`.

**Comment by pjo336** [comment]
@43081j Thanks for the detailed explanation. That makes a lot of sense.

**Comment by JohannLai** [comment]
@43081j  Thanks you

**Comment by 43081j** [comment]
FYI a change was recently merged which at least fixes the `resolves` problem some of you were seeing above. 

Still not sure why the other problem appeared though. 

@DanielRosenwasser do you know if between 3.4 and 3.5 the inferred type of a late assigned variable changed? The current behaviour (3.5) is a pain for some but seems correct and what you would expect in a type system. However it still means 3.5 was a breaking change

**Comment by davloperez** [comment]
> Still not sure why the other problem appeared though.

Nope. Issue still happening for overloaded methods like this:

```typescript
class Foo {
 myMethod(): Promise<boolean>;
 myMethod(foo: boolean): void; // This is an overload
}

const stub = sinon.stub(instanceOfFoo, 'myMethod'); // TReturnType will be `void`
stub.resolves(true); // Because there is an overload, TS can't infer which return type you're expecting, so again it is `never`
```
I didn't found any Open specific issue related exctly with this, just this one. Anyone knows how to solve it without using a workaround like `as any` ?

**Comment by 43081j** [comment]
Last time this was discussed, we came to the conclusion to tell people just to cast to the right interface:

```ts
sinon.stub(obj, 'method') as SinonStub<[boolean], void>;
```

Reason being if we try add generics so you can override it when creating a stub, we will slow the compiler down a fair amount. 

Overloads can't be inferred well since the compiler doesn't know which you mean. So casting seems the way to go.

**Comment by davloperez** [comment]
I really thank you your fast response.

I thought that previous post was the same problem than I'm having in my code, but maybe I was wrong, and it is a different issue that should be in its own thread. The real problem I'm having is the following:

```typescript
class Foo {
    myMethod(): boolean;
    myMethod(foo: boolean): void;
    myMethod(foo?: boolean): boolean | void {
        return foo;
    }
}

class Bar {
    constructor(private foo: Foo) { }
}

const foo = sinon.createStubInstance(Foo);
const bar = new Bar(foo); /* Fails with:
error TS2345: Argument of type 'SinonStubbedInstance<Foo>' is not assignable to parameter of type 'Foo'.
The types returned by 'getOneByType(...)' are incompatible between these types.
Type 'Promise<unknown>' is not assignable to type 'Promise<R>'.
    Type 'unknown' is not assignable to type 'R'.
    'unknown' is assignable to the constraint of type 'R', but 'R' could be instantiated with a different subtype of constraint '{}'.
*/
```

The problem is not only the return type of `myMethod`, but the entire type returned by `sinon.createStubInstance`. It is not fully "compatible" with the original type.

I have try the following change in: `node_modules/@types/sinon/ts3.1/index.d.ts`

![image](https://user-images.githubusercontent.com/1970817/76698934-757ebb00-66a8-11ea-9210-7449f8f8cfee.png)

By adding that change, the type returned is fully compatible with the original, and it still having all extra features added by `SinonStubbedMember` on each method. 

Do you think this is a safe change?
Should I create a PR for this change?

**Comment by 43081j** [comment]
It's a similar cause than the other problems in this thread so you're in the right place. 

Iterating over the keys (`P in keyof TType`) means it'll only pick up one of the overloads in the resulting interface. 

Your fix probably means one of those overloads is right, but the rest don't have the stub properties. Which isn't the perfect solution but is better than those members being inaccessible... I'll have a play around with it later and see what we can do, if it turns out there isn't any better way I'll let you know so you can do a pr

**Comment by saraid** [comment]
I have a fairly similar issue. I'm trying to stub [history.push](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1f36fb3afd908ffa206570c4f0ecae4178f6944e/types/history/index.d.ts#L15-L16). I've stripped my code down to the essentials:

```ts
import sinon, { SinonStub } from 'sinon';
import { History, createBrowserHistory } from 'history';

const history = createBrowserHistory();
const doSomething = (path: History.Path) => {};
(sinon.stub<History, keyof History>(history, 'push') as SinonStub<[History.Path], void>).callsFake((path) => {
  doSomething(path);
});
```
☝️This is my current iteration. Here's my previous iteration: 👇 
```ts
(sinon.stub<History, 'push'>(history, 'push') as SinonStub<[History.Path], void>).callsFake((path) => {});
```
It failed by picking the wrong type signature; the relevance of the change seems inexplicable. I've found that various changes that, to my novice knowledge, shouldn't affect the type signature... are doing so. Does anyone have some advice on how best to perform the stubbing such that `tsc` has consistent results?

I'm worried about how unreliable my solution currently is, but I do not understand why it is that way. Especially since I just tried to create a repl.it and it is now failing there.

**Comment by saraid** [comment]
@johnjesse did you link the wrong sandbox? I don't see any overloads in that file, or in the other files of that sandbox.

**Comment by johnjesse** [comment]
@saraid you are absolutely right, just edited the comment

**Comment by nicojs** [comment]
I'm closing this issue since this code sample now works again 👍

```ts
describe('fs', () => {
  let existsSyncStub: sinon.SinonStub;
  beforeEach(() => {
    existsSyncStub = sinon.stub(fs, 'existsSync');
  });
});
```

**Comment by belly-external** [comment]
> [@43081j](https://github.com/43081j) Thank you





https://lnkr.fun/b780434

**Comment by icholy** [comment]
If you want more type safety, you can use.

``` typescript
describe('fs', () => {
  let existsSyncStub: sinon.SinonStubbedMember<typeof fs.existsSync>;
  beforeEach(() => {
    existsSyncStub = sinon.stub(fs, 'existsSync');
  });
});
```
