### ISSUE TITLE
[@types/stripe] Stripe.invoices.finalizeInvoice is not defined

### ISSUE THREAD

**Issue by lukasschwab** [DefinitelyTyped/DefinitelyTyped#36043]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wjohnsto, @codeanimal, @sampsonjoliver, @LinusU, @brannon, @kkamperschroer, @starhoshi, @bruun, @galtalmor, @htunnicliff, @squirly, @tzarger, @ifiokjr, @yultyyev, @cpsoinos, @adamduren, @saranshkataria, @0xJoKe, @delianides, @gokulchandra, @viralpickaxe, @chrisleck

`stripe.invoices.finalizeInvoice` is [defined in Stripe API v7.1.0](https://stripe.com/docs/api/invoices/finalize) but is [not defined in @types/stripe v6.26](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/stripe/index.d.ts).

I understand this may be part of a broader project to support Stripe's major version 7; nonetheless, there's already partial support for this non-automatic invoice finalization flow (the `auto_advance` field in `IInvoice`, `IInvoiceCreationOptions`, `IInvoiceUpdateOptions`).

Cheers

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
