### ISSUE TITLE
Enzyme new wrappingComponent option missing in shallow options.

### ISSUE THREAD

**Issue by pyaesone17** [DefinitelyTyped/DefinitelyTyped#36075]
- [ ] I tried using the `@types/enzyme` package and had problems with adding wrappingComponent option.

Currently it is referencing https://github.com/airbnb/enzyme/blob/enzyme@3.1.1/docs/api/shallow.md#arguments.

But at that moment, Enzyme introduce wrappingComponent option in ShallowRendererProps for provider component.
https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md#arguments

**Comment by Zacqary** [comment]
👍 This is also missing in the definitions for `mount`

**Comment by pyaesone17** [comment]
#36466

**Comment by pyaesone17** [comment]
Guys I create pull request for mount and shallow options #36466

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
