### ISSUE TITLE
@types/koa-mount cannot use koa-mount in conjunction with koa-router

### ISSUE THREAD

**Issue by tyrak** [DefinitelyTyped/DefinitelyTyped#36088]
- [X] I tried using the `@types/koa-mount` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @amirsaber, @tlaziuk

I have the following code:

    import Koa from "koa";
    import mount from "koa-mount";
    import Router from "koa-router";
    
    const app = new Koa();
    const router = new Router();
    router.get("/", (ctx) => {
    	ctx.body = "test";
    	ctx.status = 200;
    });
    app.use(mount("/test", router.routes()));

The problem is that the last line does not typecheck, because `mount` does not like the type of is argument. `mount` expects an argument of type `Koa.Middleware` (which is equivalent to `Koa.Middleware<any, {}>`). If I change the declaration of `mount` to

    declare function mount<StateT, CustomT>(
    	prefix: string,
    	app: Koa.Middleware<StateT, CustomT>
    ): Koa.Middleware<StateT, CustomT>;

then everything works just fine.

**Comment by polRk** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36365

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
