### ISSUE TITLE
@types/papaparse Update to version 5.0.0

### ISSUE THREAD

**Issue by Domvel** [DefinitelyTyped/DefinitelyTyped#36103]
Current version of types: 4.5.9
https://www.npmjs.com/package/@types/papaparse

Current version of library: 5.0.0
https://www.npmjs.com/package/papaparse

Wait, why is the typed file at version 4.5.9? There are only tags of 4.5.1 and 4.6.0 of the library.

**Comment by OrangeDog** [comment]
I assume this would cover the expansion of `dynamicTyping` (it's not just a boolean).

**Comment by OrangeDog** [comment]
This appears to have been done?
https://www.npmjs.com/package/@types/papaparse/v/5.0.3

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
