### ISSUE TITLE
@types/amqplib Connection serverProperties is always undefined

### ISSUE THREAD

**Issue by Paic** [DefinitelyTyped/DefinitelyTyped#36138]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mnahkies @abreits @nfantone @zelein 

If you do not mention the authors the issue will be ignored.

---

`amqplib` version used is `0.5.3`. Looks like the `connect` function now return a `ChannelMode` object containing a `connection` property

**Comment by jrandiny** [comment]
Hi, the latest `@types/amqplib` should have fixed this

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
