### ISSUE TITLE
googlemaps.infobubble/index.d.ts' is not a module

### ISSUE THREAD

**Issue by miguelleitevieira** [DefinitelyTyped/DefinitelyTyped#36166]
Hi,

I installed "@types/googlemaps.infobubble": "^3.0.0".

When I try to import the module to use InfoBubble:
import { InfoBubble } from 'googlemaps.infobubble';
I get an error: /@types/googlemaps.infobubble/index.d.ts' is not a module.

Someone know how to solve?

Thanks.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
