### ISSUE TITLE
@types/mapbox-gl onStart is missing for TouchZoomRotateHandler

### ISSUE THREAD

**Issue by HarelM** [DefinitelyTyped/DefinitelyTyped#36178]
- [x] I tried using the `@types/mapbox-gl` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dobrud @patrickr @macobo

I'm not sure but I believe the following method is missing in `TouchZoomRotateHandler`
`onStart`.
Looking at the code here:
https://github.com/mapbox/mapbox-gl-js/blob/d3c7405f858ace430cc87ae3b62650c64d9b252b/src/ui/handler/touch_zoom_rotate.js
Not entirely sure it's public though although it's not prefixed with `_`...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
