### ISSUE TITLE
Board should accept a string for pin argument in methods

### ISSUE THREAD

**Issue by chrisahardie** [DefinitelyTyped/DefinitelyTyped#36174]
It is valid to call identify a pin with a string:

```
board.digitalWrite("GPIO18", 1)
```

I will submit a PR shortly to allow for strings as well as numbers to be passed as the pin argument.

@nakakura @ujvzolee @Workshop2 @marcinobiedz 

PR submitted: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36177

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
