### ISSUE TITLE
Buffer concat is claimed to return single value in array

### ISSUE THREAD

**Issue by steabert** [DefinitelyTyped/DefinitelyTyped#36253]
Hi,

I came across a line in the documentation that I think is wrong, at least I couldn't find any reference in the actual NodeJS documentation that this would be the case, and neither in the code of buffer.js of the NodeJS libs.

This is the line:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/712ad9d59ccca6a3cc92f347fea0d1c7b02f5eeb/types/node/v11/globals.d.ts#L401

it claims the first value of an array is returned in case the array has only one value.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
