### ISSUE TITLE
@types/ws error TS2709: Cannot use namespace 'WebSocket' as a type on Linux

### ISSUE THREAD

**Issue by marcushultman** [DefinitelyTyped/DefinitelyTyped#36269]
Node: 12.1.0
typescript: 3.5.2
ws: 7.0.1
@types/ws: 6.0.1

importing like:
`import WebSocket from 'ws';`

macOS:
VS Code recognizes the name `WebSocket` as both class WebSocket **and** namespace WebSocket:
```
(alias) class WebSocket
(alias) namespace WebSocket
import WebSocket
```

but it compiles with `tsc` fine.

Linux:
`error TS2709: Cannot use namespace 'WebSocket' as a type.`

**Comment by willstott101** [comment]
The Websocket class is defined _outside_ of the namespace so it isn't exported by the `.d.ts` at all. IDK if this is an over-sight or intended...

**Comment by willstott101** [comment]
Ahh if you use `import WebSocket = require('ws');` then it works... pretty gammy. There must be a better way using the static keyword rather than a merged `class` and `namespace` that only works with a particular import style.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
