### ISSUE TITLE
@types/jest is outdated on npm

### ISSUE THREAD

**Issue by telmotrooper** [DefinitelyTyped/DefinitelyTyped#36285]
Function "toStrictEqual" is not available in the current package (@types/jest 24.0.15), even though [here on GitHub](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts) the interface is already updated.

`Property 'toStrictEqual' does not exist on type 'Matchers<void>'.ts(2339)`

The workaround for now is either importing the types manually or using `(expect as any)`, but could you guys update the package?

**Comment by sebranly** [comment]
I haven't checked in details whether `@types/jest` is correctly updated to match `jest` but at least `toStrictEqual` is recognized now. My `@types/jest` version is `24.0.18`

**Comment by jjcv2304** [comment]
I'm having the issue with version "ts-jest": "^26.1.0",

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
