### ISSUE TITLE
@types/redux-orm Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by franferns** [DefinitelyTyped/DefinitelyTyped#36318]
#34588 @tomasz-zablocki ![image](https://user-images.githubusercontent.com/779253/59845426-02dfe980-937b-11e9-8adc-ea412b0fe3b2.png)

Get the attached issue of type instantiation possibly infinite for complex nested models.
Below is code to reproduce the issue.

```
import Model, { MutableQuerySet} from 'redux-orm';

export interface IQuestionnaireFields {
    Name: string;
    QuestionGroups: MutableQuerySet<QuestionGroup>;
}
export class Questionnaire extends Model<typeof Questionnaire, IQuestionnaireFields> {
}

export interface IQuestionGroupFields {
    id: string;
    Name: string;
    Questionnaire: Questionnaire;
    Questions?: MutableQuerySet<Question>;
}

export class QuestionGroup extends Model<typeof QuestionGroup, IQuestionGroupFields> {
}

export interface IQuestionFields {
    id: string;
    tempModelId: string;
    QuestionGroup: QuestionGroup;
    AnswerOptions?: MutableQuerySet<AnswerOption>;
}

export class Question extends Model<typeof Question, IQuestionFields> {
}

export interface IAnswerOptionFields {
    id: string;
    tempModelId: string;
    PersonQuestionAnswersByAnswer?: MutableQuerySet<PersonQuestionAnswer>;
}

export class AnswerOption extends Model<typeof AnswerOption, IAnswerOptionFields> {
}

export interface IPersonQuestionAnswerFields {
    id: string;
    tempModelId: string;
    AnswerId: string;
    AnswerText: string;
}

export class PersonQuestionAnswer extends Model<typeof PersonQuestionAnswer, IPersonQuestionAnswerFields> {
}
```

How do i fix this issue ? 

Thanks & Regards,
Francis P.

**Comment by tomasz-zablocki** [comment]
I'll have a look at this today and let you know once i figure this one out

**Comment by franferns** [comment]
> I'll have a look at this today and let you know once i figure this one out.
> 
> Which typescript version does this occur on ?

Thanks. I use 3.5.2

**Comment by tomasz-zablocki** [comment]
It seems that the issue is rooted in the `Ref` mapped type. I'll attend to it this evening.

**Comment by tomasz-zablocki** [comment]
Hi @franferns 

First of all, sorry for the issue.

I've tried to deal with the problem yesterday, but it's more complex than I expected. I'll be working on a fix in the upcoming days. 

Meanwhile you can either change the `Model.ref` type in the typings to `object` (unfortunately loosing soem hinting on `ref/toRefArray` as a result, or maybe suppress it with `@ts-ignore` till I figure out a patch for this.

**Comment by franferns** [comment]
Thanks @tomasz-zablocki . Also are there examples for selector scenarios like how do i achieve 
https://github.com/redux-orm/redux-orm/pull/257 and also examples of selector composition ?

**Comment by tomasz-zablocki** [comment]
Hi @franferns, sorry that the issue is still in the workings, `MutableQuerySet` is one level too deep and I'm still moving things around to get everything working.

As for the new selectors API, this feature is in release candidate coming up in redux-orm 0.14, once it's out I'll update the typings promptly.

**Comment by franferns** [comment]
Hi @tomasz-zablocki  . I am trying to use the Model by manually implementing the interface Fields to the class using the new https://facebook.github.io/create-react-app/docs/adding-typescript template . 

But when i try to dispatch an action get the error 
![image](https://user-images.githubusercontent.com/779253/60577246-9e6e5280-9d9c-11e9-9425-6cd8ba33500a.png)

this used to work fine with the previous template https://github.com/microsoft/TypeScript-React-Starter 
Am i missing something ?

**Comment by tomasz-zablocki** [comment]
Can you attach Question and IQuestionFields source and the code causing the stack overflow ?

**Comment by franferns** [comment]
Thanks here the Stackoverflow link with the source code https://stackoverflow.com/q/56915761/581157

**Comment by tomasz-zablocki** [comment]
1. Check your stackoverflow question
2. Try changing the order of the Models like this to fix the **Type instantiation is excessively deep and possibly infinite** problem: 

```typescript
import Model, { MutableQuerySet } from 'redux-orm';

export interface IAnswerOptionFields {
    id: string;
    tempModelId: string;
    PersonQuestionAnswersByAnswer?: MutableQuerySet<PersonQuestionAnswer>;
}

export class AnswerOption extends Model<typeof AnswerOption, IAnswerOptionFields> {
}

export interface IPersonQuestionAnswerFields {
    id: string;
    tempModelId: string;
    AnswerId: string;
    AnswerText: string;
}

export class PersonQuestionAnswer extends Model<typeof PersonQuestionAnswer, IPersonQuestionAnswerFields> {
}

export interface IQuestionnaireFields {
    Name: string;
    QuestionGroups: MutableQuerySet<QuestionGroup>;
}
export class Questionnaire extends Model<typeof Questionnaire, IQuestionnaireFields> {
}

export interface IQuestionGroupFields {
    id: string;
    Name: string;
    Questionnaire: Questionnaire;
    Questions?: MutableQuerySet<Question>;
}

export class QuestionGroup extends Model<typeof QuestionGroup, IQuestionGroupFields> {
}

export interface IQuestionFields {
    id: string;
    tempModelId: string;
    QuestionGroup: QuestionGroup;
    AnswerOptions?: MutableQuerySet<AnswerOption>;
}

export class Question extends Model<typeof Question, IQuestionFields> {
}```

**Comment by franferns** [comment]
Thanks for your reply. By order do you mean the way in which the interfaces and the classes are arranged needed to be changed ? I have around 300+ generated Models along with interfaces and they all sit in individual files. The reason these properties are implementated individually is due to the "Type instantiation deep and possibly infinetine error" this when implemented manually works fine. Please find link with redux-orm and latest @types/redux-orm along with the old typescript enabled react template in which the same code works fine. 
https://drive.google.com/file/d/1eWmOkaKnbuRCpBEaFj7BUElq2C9IxoYD/view?usp=sharing
Is there a way i can for now use the Model syntax with just implementing the interface members ?

**Comment by tomasz-zablocki** [comment]
@franferns

I have my own repo that I'm using to develop redux-orm typings and as a playground to test them on. There's an experimental branch that kinda follows what you did - dropping the second type parameter on Model in favour of in-model properties.

Initially I thought that it's going to clash with redux-orm setup of model prototypes, but I've tested it thoroughly and it's fine. I've managed to simplify the typings to a major extent this way (from 15k to 10k) types on tsc diagnostics, but I need to check if  that's enough to get rid of this issue.

I'm sorry that it's still an issue, I'm genuinely committed to working on this and the types in general, but I'm limited to my leisure time only.

I'll check if the new flavour did the trick. It definitely gave a lot of breathing space and room for improvement and there's definitely a way.

I can adapt my experimental types branch to allow using it as a node module. I'd really appreciate if you could actively check latest types against your codebase, especially since it's that large.

Let me know if that's ok

**Comment by franferns** [comment]
Thanks @tomasz-zablocki  for your reply. Can i use this experimental types and see if it works for me ?. Or should i wait for some more time ?

**Comment by tomasz-zablocki** [comment]
@franferns you are welcome to try

https://github.com/tomasz-zablocki/redux-orm-typings/tree/experimental

The tests are updated to the new style. Additionally, I've added [this](https://github.com/tomasz-zablocki/redux-orm-typings/blob/experimental/redux-orm-typescript-playground/src/issue36318.ts) file to work on your case. It seems to work, but is it capable of handling  300 model types remains to be seen.

**Comment by tomasz-zablocki** [comment]
On a side note:

# `MutableQuerySet` is for many-to-many fields only, exposing many-to-many specific methods: `add`, `clear` and `remove`. For reverse `ForeignKey` (`fk('modelName')` fields use `QuerySet`.
# `QuerySet` and `MutableQuerySet` properties should not optional. These properties are always present on session bound Model instances.

**Comment by tomasz-zablocki** [comment]
Linking original issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36318 from DefinitelyTyped repository.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
