### ISSUE TITLE
@types/fabric  setGradient  params  bug

### ISSUE THREAD

**Issue by jinhaibin** [DefinitelyTyped/DefinitelyTyped#36344]
![image](https://user-images.githubusercontent.com/16408253/59917433-7b66a900-9454-11e9-84d2-039617e5033c.png)

![image](https://user-images.githubusercontent.com/16408253/59917480-a18c4900-9454-11e9-937e-8a2074185e79.png)

**Comment by jinhaibin** [comment]
@types 描述文件和 类库当中方法实际接受的参数不一样。

**Comment by wilkovanhoek** [comment]
Hey Guys,

I am seeing the same issue as @jinhaibin. The `IGradientOptions` interface requires a _coords_ property, but the actual options object of the `rect.setGradient` method requires the coords as individual properties (x1,y1,x2,...). Thus, one can either define the coords and will not receive a gradient fill or define the coords separately and run into compiler errors.

Unfortunately it looks like fabric.js is somewhat inconsistent at this. The _options_ used for `rect.setGradient` (http://fabricjs.com/docs/fabric.js.html#line14351) are not the same as the _options_ used for the `fabric.Gradient` methog (http://fabricjs.com/docs/fabric.js.html#line6133). So using `IGradientOptions` for both is not sufficient. Any chance someone could take a look into this?

Cheers, 
Wilko

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
