### ISSUE TITLE
[@types/matter-js] typeof IPair.id is not correct

### ISSUE THREAD

**Issue by Kynson** [DefinitelyTyped/DefinitelyTyped#36363]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/matter-js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ivanegegia @piranha771 @hasparus

### **Issue**
Interface `IPair.id` is not correct, it should be typeof `string` instead of `number`:

<pre><code>export interface IPair {
        id: number;  <= should be string
        // ...
 }
</code></pre>

`id` is `"A1B3"` which is `string` instead of `number`:

![Screenshot 2019-06-22 at 17 21 28](https://user-images.githubusercontent.com/46522440/59962022-6e0ff400-9512-11e9-857c-50bf9326c266.png)

Update it to `string` should fix the issue.

Thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
