### ISSUE TITLE
[Request] leaflet.motion

### ISSUE THREAD

**Issue by Stan92** [DefinitelyTyped/DefinitelyTyped#36376]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: https://github.com/Igor-Vladyka

Hi, 
I need some help for the d.ts file for this plugin.
https://github.com/Igor-Vladyka/leaflet.motion
I try to follow this tutorial (https://asymmetrik.com/ngx-leaflet-and-leaflet-plugins/) but I am stuck
Any help? Thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
