### ISSUE TITLE
[@types/react] "Property 'children' does not exist" with react-apollo after 16.8.12

### ISSUE THREAD

**Issue by JoshRobertson** [DefinitelyTyped/DefinitelyTyped#36406]
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ferdaber @johnnyreilly @bbenezech @ericanderson @onigoetz 

using `react-apollo` with `@types/react` has been throwing an error since version 16.8.13:

```
Type '{ children: (result: any) => any; query: any; variables: Variables; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Query<Data, Variables>> & Pick<Readonly<QueryProps<Data, Variables>> & Readonly<{ children?: ReactNode; }>, Exclude<...> | ... 13 more ... | Exclude<...>> & Pick<...> & Pick<...>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Query<Data, Variables>> & Pick<Readonly<QueryProps<Data, Variables>> & Readonly<{ children?: ReactNode; }>, Exclude<...> | ... 13 more ... | Exclude<...>> & Pick<...> & Pick<...>'
```
keeping `@types/react` at version 16.8.12 doesn't introduce this error.

More information here:
https://github.com/apollographql/react-apollo/issues/2971

**Comment by stnwk** [comment]
Has anyone _any_ idea how to fix this?

**Comment by miketmoore** [comment]
I recreated this and posted here: https://github.com/apollographql/react-apollo/issues/2971#issuecomment-571802885

I wasn't sure which was the correct issue to track it in.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
