### ISSUE TITLE
Sinon types are broken with overloads

### ISSUE THREAD

**Issue by DanTup** [DefinitelyTyped/DefinitelyTyped#36436]
This was mentioned a little in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31606 but there isn't an open issue describing it. That PR broke stubbing overloaded methods:

```ts
class Bar {
	public foo(a: string): void;
	public foo(a: number): void;
	public foo(a: string | number): void {};
}

const bar = new Bar();
const barStub = sinon.stub(bar, "foo");

// This line gives an error:
// Argument of type '"test"' is not assignable to parameter of type 'number | SinonMatcher'.
barStub.withArgs("test"); 
```

I don't know if it's possible to fix this without just changing back to `any`, but it does seem like this should work.

**Comment by murkey** [comment]
+1 - This is _really_ annoying.

**Comment by arkhamRejek** [comment]
any news on this ?

**Comment by mykwillis** [comment]
Perhaps I should've posted [this question](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31606#issuecomment-581054380) in this thread: 

Incidentally, it seems I am able to work around this problem in my particular case with good ol' @ts-ignore in my test case:

```
    const userStub = sinon.stub(User, 'findOne');

    // avoid TS2554: Expected 3-4 arguments, but got 1.
    // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
    // @ts-ignore
    userStub.withArgs({ firebaseUid: userFirebaseUid }).resolves(user);

```

**Comment by 43081j** [comment]
somehow totally didn't see this issue!

it will indeed be because the inferred types are not a combination of all the overloads but rather just one of them.

ultimately the solution is to specify the generics rather than inferring them, i think. but ill have a look in case we can just introduce a looser type for these cases.

**Comment by 43081j** [comment]
ok so the best i can come up with is that you'd have to specify your type arguments:

```ts
const barStub = stub<Bar, 'foo', [string]>(bar, 'foo');
```

If i modify the stub interface, the above will work (it won't at the min). Unfortunately you have to specify the initial two types as the following ones depend on them.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
