### ISSUE TITLE
[@types/react-select] No declaration file for Creatable in @types/react-select

### ISSUE THREAD

**Issue by jaymathew** [DefinitelyTyped/DefinitelyTyped#36481]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/xxxx` package and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @claasahl, @Darep, @burtek, @jonfreedman

`"react-select": "^3.0.4"`
`"@types/react-select": "^2.0.19"`

I am trying to use Creatable from react-select but when I import like the docs say, I receive an error.  
[https://react-select.com/creatable](url) 
The docs say to import like this 
`import Creatable from 'react-select/creatable';`
but I get this error
`Could not find a declaration file for module 'react-select/creatable'. '/path/to/app/node_modules/react-select/creatable/dist/react-select.cjs.js' implicitly has an 'any' type.ts(7016)`

I made a little app that showcases this issue.  Once the code sandbox loads you will see an error `Cannot find module 'react-select/creatable'.ts(2307)`.  While on code sandbox this error doesn't keep it from running, The error I received on my local machine is causing the app to not run.

[https://codesandbox.io/s/inspiring-wilson-nucl1?fontsize=14](url)

**Comment by dmarkow** [comment]
There's an open pull request to support v3 of react-select, until it's merged the types here only support v2. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36464

**Comment by danieldelcore** [comment]
We can probably close this issue now, since type defs for v3 have been shipped. @typescript-bot

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
