### ISSUE TITLE
[@types/fullpage.js] 'fullpage.js/index.d.ts' is not a module

### ISSUE THREAD

**Issue by Fuego314** [DefinitelyTyped/DefinitelyTyped#36500]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/fullpage.js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @JodiWarren @androberts

When trying to import fullpage.js I get the error:
`File 'c:/.../node_modules/@types/fullpage.js/index.d.ts' is not a module.`

If I add the following line to the base of the `fullpage.js/index.d.ts` file:
`export = FullPageJs;` the error dissapears. Is this the correct fix?

**Comment by Acidic9** [comment]
Any solution to this? I'm also experiencing this issue.

**Comment by nvminhhieu** [comment]
Any fix guys? I also got this issue

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
