### ISSUE TITLE
[@types/stripe] No support balanceTransactions

### ISSUE THREAD

**Issue by burkarddev** [DefinitelyTyped/DefinitelyTyped#36518]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/stripe` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I know stripe library of node was already updated `balance` to `balanceTransactions`. So I am getting `stripe.balance.listTransactions` is not a function error.
- [ ] [Mention](https://github.com/stripe/stripe-node/blob/master/lib/resources/BalanceTransactions.js) Please see this.
  - Authors: @wjohnsto @CodeAnimal @sampsonjoliver @LinusU @brannon @kkamperschroer @starhoshi @bruun @galtalmor @htunnicliff @squirly @tzarger @ifiokjr @yultyyev @cpsoinos @adamduren @saranshkataria @0xJoKe @delianides @gokulchandra @viralpickaxe @chrisleck @spacetag

Please help me. I am getting errors from live server now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
