### ISSUE TITLE
[@types/google-apps-script@0.0.54] Property 'GOOGLE_SLIDES' does not exist on type '{ new (): MimeType; prototype: MimeType; }'.

### ISSUE THREAD

**Issue by jpvanoosten** [DefinitelyTyped/DefinitelyTyped#36546]
Trying to use MimeType.GOOGLE_SLIDES in TypeScript generates the following error:

Property 'GOOGLE_SLIDES' does not exist on type '{ new (): MimeType; prototype: MimeType; }'.ts(2339)

**Comment by jpvanoosten** [comment]
Maybe I'm just a noob, but does anyone have an idea how I can solve this?

**Comment by mtgto** [comment]
@jpvanoosten  Maybe you misunderstand [GoogleAppsScript.Base.MimeType](https://developers.google.com/apps-script/reference/base/mime-type) and [ContentService.MimeType](https://developers.google.com/apps-script/reference/content/mime-type.html).

If you want to use `MimeType.GOOGLE_SLIDES`, you can write `GoogleAppsScript.Base.MimeType.GOOGLE_SLIDES`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
