### ISSUE TITLE
Cannot build against angular.d.ts with typescript 1.4

### ISSUE THREAD

**Issue by nidico** [DefinitelyTyped/DefinitelyTyped#3656]
eb3420c93c76638aadf8a5a6456f06611d4b061e introduced changes which lead to the following error in TypeScript 1.4, trying to build against angular 1.3.10:

```
DefinitelyTyped/angularjs/angular.d.ts(18,5): error TS2309: An export assignment cannot be used in a module with other exported elements.
```

This may be related to #3327.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
