### ISSUE TITLE
discussion - how do you feel about external dependencies?

### ISSUE THREAD

**Issue by regevbr** [DefinitelyTyped/DefinitelyTyped#36575]
@jgonggrijp and I are discussing the possibility to add an external dependency to the `underscore` types library (#36532)

Because extremely complex typings are required, I want to use the awesome https://github.com/pirix-gh/ts-toolbelt library to achieve that with ease.

We are wondering what is the take of the owners here on such a change?

@sandersn can you help us out on the matter?

**Comment by sandersn** [comment]
1. This is technically possible (ts-toolbelt just needs to be on the allow list in microsoft/types-publisher)
2. ts-toolbelt is a good candidate for such a dependency since it concentrates complex types in a central place. Fewer places for us to fix in case of future TS breaks.
3. I don't think making `@types/underscore` more complex is a good idea. You will run into performance and compatibility problems similar to lodash and ramda, with less and less improvement in type coverage as complexity goes up.

If the owners of underscore support improvements and the associated complexity I won't stand in the way.

**Comment by regevbr** [comment]
Thanks @sandersn for you answer.

I'm in constant contact with `ts-toolbelt` awesome owner @pirix-gh and he is making sure that all types have low performance overhead and the library is constantly evolving, so I agree with you on the performance issues take back but I think the users can benefit from strong and reliable typings in such an important library.

The main issue with adding the dependency is that we must use TypeScript 3.5 and it will prevent from users that are using older version to benefit from future changes.

@jgonggrijp do you have anything to add?

**Comment by jgonggrijp** [comment]
> @jgonggrijp do you have anything to add?

Nope.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
