### ISSUE TITLE
ts: import React, {Component} from "react" (and more)

### ISSUE THREAD

**Issue by cybermerlin** [DefinitelyTyped/DefinitelyTyped#36593]
react - 16.8.6
@types/react - 16.8.6 .. 16.8.22
----
`import React, {Component} from "react";`
if use TypeScript then not work, because in @types/react  some genius made export different from facebook/react import

![image](https://user-images.githubusercontent.com/1460479/60512536-779d1700-9cdd-11e9-85b8-2c86496cbc56.png)

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by ActuallyACat** [comment]
Try `import * as React from 'react'` 
https://stackoverflow.com/questions/54585763/what-is-the-difference-between-import-as-react-from-react-vs-import-react-fr

**Comment by cybermerlin** [comment]
@ActuallyACat , I did, but I do not wanna using React.Component, or something like this, I wanna use Component, useState,... instead (shorthand version)

**Comment by cybermerlin** [comment]
@asankaf , @johnnyreilly , @ericanderson , @pascaloliv

**Comment by cybermerlin** [comment]
+ propTypes, defaultProps

(look "this.props.options")

![image](https://user-images.githubusercontent.com/1460479/62424796-90358e00-b6dc-11e9-8997-0e276b7a34ee.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
