### ISSUE TITLE
@types/ramda assoc typings

### ISSUE THREAD

**Issue by wclr** [DefinitelyTyped/DefinitelyTyped#36618]
I wonder what was behind the decision to type assoc in such a strange order:

For example, is typed as  `assoc<VAL, OBJ, PROP>(prop, val, obj)` why not arg's order for type arguments `<PROP, VAL, OBJ>`?

**Comment by whitecolor** [comment]
@jituanlin @RyanCavanaugh ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
