### ISSUE TITLE
IAngularEvent vs JQueryKeyEventObject

### ISSUE THREAD

**Issue by arnaudpourbaix** [DefinitelyTyped/DefinitelyTyped#3662]
I am creating an Angular application with Typescript. When I add directives like ng-keydown, ng-click, I need a complete event object, especially with the former.

Currently, IAngularEvent is useless to me as it doesn't even contain critical fields like keycode for keyup/down events.
I am forced to fallback on Jquery declarations, which are very complete relating events.

It's not a big deal, but what if I need Angular specifics? I would have to extends IAngularEvent interface.

**Comment by sgwatgit** [comment]
The typings could definitely use some types for the $event object generated by the ng- directives.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
