### ISSUE TITLE
React typescript StandardLonghandProperties -moz-transform is missing

### ISSUE THREAD

**Issue by chezih** [DefinitelyTyped/DefinitelyTyped#36705]
I'm trying to put: "-moz-transform": "scale(" + zoom + ")" on react style

I got this error:
Unsupported style property -moz-transform. Did you mean MozTransform?

But I cannot see MozTransform in csstype/index.d.ts (interface StandardLonghandProperties)

What is the workaround? what is the correct key/class-name to use?

**Comment by frenic** [comment]
This is the workaround, as [described here](https://github.com/frenic/csstype/#what-should-i-do-when-i-get-type-errors), when something is missing in CSSType:

```tsx
<div style={{ ['MozTransform' as any]: 'scale(' + zoom + ')'}} />
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
