### ISSUE TITLE
babel-traverse's path.traverse type for state seems to be wrong?

### ISSUE THREAD

**Issue by kgrz** [DefinitelyTyped/DefinitelyTyped#36710]
Ref: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/132720a17e15cdfcffade54dd4a23a21c1e16831/types/babel-traverse/index.d.ts#L359-L360

The `state` object can be any object, but here it's typed as the generic parameter that's passed to `traverse`. As such, there's really no coupling I can see between the `state` and the `traverse` and `visitor` properties here. Am I missing something?

The function definition in source for `path.traverse` in babel v 6.x: https://github.com/babel/babel/blob/d8be710dc7590faf718181230ce2800c48e7d22e/packages/babel-traverse/src/path/index.js#L120-L122

The change to this from the original (correct?) definition happened in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26432/files#diff-263f7bdbfc364b0c02082b680b8424d3L356. Paging @rpetrich and @marvinhagemeister

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
