### ISSUE TITLE
[@types/react] FunctionComponent read only props

### ISSUE THREAD

**Issue by GR1ML0CK** [DefinitelyTyped/DefinitelyTyped#36729]
The `FunctionComponent<P>` does not declare its props as readonly like `Component<P, S>` does for props and state. It seems like this should have the same typing for props as `Component` does.

@johnnyreilly @bbenezech @digiguru @DovydasNavickas @eps1lon @ericanderson @DovydasNavickas @ferdaber @franklixuefei @guilhermehubner @hotell @Jessidhia @jrakotoharisoa @lukyth @onigoetz @pascaloliv @pzavolinsky @saranshkataria @theruther4d @tkrotoff

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
