### ISSUE TITLE
[@types/arcgis-js-api] Create a GeometryService object

### ISSUE THREAD

**Issue by warleymendes** [DefinitelyTyped/DefinitelyTyped#36722]
Hi Guys,
I'm trying to create a GeometryService, but the code is throwing the following error:

`ERROR Error: Uncaught (in promise): ReferenceError: __esri is not defined`

My code:
```
const geometryService:__esri.GeometryService = new __esri.GeometryService({
    url: 'https://myURL/arcgis/rest/services/Utilities/Geometry/GeometryServer'
 });
```

Is it a bug or I'm doing somethig wrong?

Thanks,
Warley Mendes

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
