### ISSUE TITLE
[@types/stripe] Interface createPerson at accounts are missing

### ISSUE THREAD

**Issue by mfeldmeier** [DefinitelyTyped/DefinitelyTyped#36725]
If you know how to fix the issue, make a pull request instead.

- [ x ] I tried using the `@types/stripe` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

This function are for stripe connect.
If you create a business-account from ``` business_type: "company" ``` you will need an owner. 
This Owner will be created by der Person API and is available from accounts/:id/persons. 
[Link to Docs](https://stripe.com/docs/api/persons/create)

**Comment by PatrickOBoyle** [comment]
Also having this issue, normally wouldn't be a problem but with the pending SCA changes within Stripe making it necessary to update to the same version that introduces this and removes the old version this is quite important

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
