### ISSUE TITLE
[@types/styled-components] StyledComponent propTypes and defaultProps errors

### ISSUE THREAD

**Issue by zarrellab** [DefinitelyTyped/DefinitelyTyped#36762]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @lavoaster @Jessidhia @jkillian @eps1lon @flavordaaave 

If you do not mention the authors the issue will be ignored.

With TypeScript, using .propTypes on a StyledComponent causes this error: Property 'propTypes' does not exist on type 'StyledComponent<FunctionComponent<ButtonProps>, any, ButtonBaseProps & ButtonActionProps, never>'. Also, .defaultProps types are not picked up by TypeScript, even though the default props do work.

[Example](https://codesandbox.io/s/styled-components-typescript-props-8g8j8?from-embed)

[Spectrum chat](https://spectrum.chat/styled-components/help/styledcomponent-proptypes-and-defaultprops-arent-playing-well-with-typescript~9c65ea53-a440-482c-ab0c-cd634e82f5a8)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
