### ISSUE TITLE
Types for wouter is missing definitions for "wouter/preact"

### ISSUE THREAD

**Issue by Hubro** [DefinitelyTyped/DefinitelyTyped#36780]
- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

When installing `@types/wouter` then `import { ... } from "wouter"` works fine, but `import { ... } from "wouter/preact"` results in:

> Could not find a declaration file for module 'wouter/preact'.

The module should have an identical interface to "wouter" (as far as I know) so hopefully it should be easy to fix.

@StrayFromThePath

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
