### ISSUE TITLE
React defaultValue property sould support number

### ISSUE THREAD

**Issue by asfernandes** [DefinitelyTyped/DefinitelyTyped#36794]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/react` package and had problems.
(Please ask any appropriate questions there).
  - Authors: @tkrotoff @DovydasNavickas @threepointone 

```ts
    interface HTMLAttributes<T> extends DOMAttributes<T> {
        // React-specific Attributes
        defaultChecked?: boolean;
        defaultValue?: string | string[];
```

should be:

```ts
    interface HTMLAttributes<T> extends DOMAttributes<T> {
        // React-specific Attributes
        defaultChecked?: boolean;
        defaultValue?: string | string[] | number;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
