### ISSUE TITLE
react-router-dom should export types from react-router

### ISSUE THREAD

**Issue by davidje13** [DefinitelyTyped/DefinitelyTyped#36870]
- [x] I tried using the `@types/react-router-dom` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @huy-nguyen @p-jackson @johnnyreilly @eps1lon

---

The `react-router-dom` package exports everything from `react-router` (see https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/index.js), but the `@types/react-router-dom` package does not export all types from `@types/react-router`.

Specifically, I have found that the type definition `StaticRouterContext` is missing, but there are plenty of others.

This leads to a rather bizarre requirement for imports:

```ts
import { StaticRouter } from 'react-router-dom';
import { StaticRouterContext } from 'react-router';
```

Which should really be:

```ts
import { StaticRouter, StaticRouterContext } from 'react-router-dom';
```

When combined with the `import/no-extraneous-dependencies` ESLint rule, this is especially problematic (as both dependencies must now be explicitly listed in `package.json`).

**Comment by artola** [comment]
I agree, see `react-router-dom` should re-export `react-router`.

https://github.com/ReactTraining/react-router/blob/6da68777497daa85d133f1d0779176d94c0a7543/packages/react-router-dom/modules/index.js#L1

**Comment by eps1lon** [comment]
Looks good. PRs welcome.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
