### ISSUE TITLE
React Immutability Helper Function `update` incorrect

### ISSUE THREAD

**Issue by joewood** [DefinitelyTyped/DefinitelyTyped#3693]
The React addon immutability help `update` doesn't match the function definition in the documentation.  The definition currently in the declaration file is as follows:

``` typescript
    update(value: any[], spec: UpdateArraySpec): any[];
    update(value: {}, spec: UpdateSpec): any;
```

With the defintion of `UpdateSpec` being:

``` typescript
interface UpdateSpec {
        $set: any;
        $merge: {};
        $apply(value: any): any;
        // [key: string]: UpdateSpec;
    }
```

The `update` function can be used to [express a graph of commands](http://facebook.github.io/react/docs/update.html) as leaf nodes embedded into an object graph matching the state object.  Given how difficult this would be to model I suggest adding a simple overload with a second parameter of type `any`:

``` typescript
    update(value: any[], spec: any): any;
    update(value: any[], spec: UpdateArraySpec): any[];
    update(value: {}, spec: UpdateSpec): any;
```

Plus, fixes to the UpdateSpec to make each field optional:

``` typescript
interface UpdateSpec {
        $set?: any;
        $merge?: {};
        $apply(value: any)?: any;
        // [key: string]: UpdateSpec;
    }
```

**Comment by vsiao** [comment]
You're right; properties on `UpdateSpec` should be optional.

If we overload like
```ts
update(value: any[], spec: any): any;
update(value: any[], spec: UpdateArraySpec): any[];
```
then the first overload will always take precedence and the return type will be `any`.

Can you give concrete examples (which we can use as tests) which fail with the current type definition?

**Comment by gameman15** [comment]
Here's a simple example that will fail with the current definition:

```TypeScript
interface Bar {
    test: string;
}
interface Foo {
    baz: any[];
}
let fooBar: Foo = { baz: [{ test: "This is a string" }] };
let newBar: Bar = update(fooBar.baz[0], {
    test: { $set: "This is a different string" }
});
```

**Comment by gameman15** [comment]
I know this is a really old issue, but it's still open and there is a case I am running into that is failing. I have an object array from another library with no type information that is causing the wrong update definition to get selected.
````TypeScript
interface IObj {
    text: string;
}
// Here untypedArray is an array of objects returned from the library and IObj is an interface I
// defined that has all of the properties on the object returned that I care about
let newObj: IObj = update(untypedArray[index], {
    text: { $set: 'An example' }
});
````
This says that it can't assign type `any[]` to `IObj`, which is incorrect as it should be returning `any` not `any[]` since I passed in an object.

**Comment by vsiao** [comment]
This utility isn't commonly used, so it's not a high priority to fix. Feel free to send a pull request if you'd like!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
