### ISSUE TITLE
Can't create session for checkout subscription

### ISSUE THREAD

**Issue by ThePoog** [DefinitelyTyped/DefinitelyTyped#37007]
If you know how to fix the issue, make a pull request instead.

- [X ] I tried using the `@types/stripe` package and had problems. Installed yesterday, 18 July'19 

code follows: 
https://stripe.com/docs/api/checkout/sessions/create
https://stripe.com/docs/payments/checkout/server#create-subscriptions

When creating a new session for a subscription plan I get a static error on items: 

```
Type '{ plan: string; }[]' is missing the following properties from type 'IList<ISubscriptionItem>': object, data, has_more, url;

index.d.ts(6467, 13): The expected type comes from property 'items' which is declared here on type 'ISubscription'
```

Code below:
```

        import * as Stripe from 'stripe';
        const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);

          stripe.checkout.sessions.create(
            {
              success_url: 'https://example.com/success',
              cancel_url: 'https://example.com/cancel',
              payment_method_types: ['card'],
              customer_email: dummy@example.com 
              subscription_data: {
                 items: [ {plan: subcriptionInfo.name,}],
             },
            function(err, session) {
              // asynchronously called
            }
          );
```

- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @sandersn 

If you do not mention the authors the issue will be ignored.

**Comment by cdock1029** [comment]
This was fixed here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38049

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
