### ISSUE TITLE
IRoute and loadedTemplateUrl

### ISSUE THREAD

**Issue by gravidThoughts** [DefinitelyTyped/DefinitelyTyped#3700]
Hi,

I am unsure about the following, so I wanted to make certain before making a pull request.

angular-route.j line 605 

`nextRoute.loadedTemplateUrl = templateUrl;`

Should this not be exposed on IRoute as a nullable string?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
