### ISSUE TITLE
pdfjslib  - No "GlobalWorkerOptions.workerSrc" specified.

### ISSUE THREAD

**Issue by neo-xy** [DefinitelyTyped/DefinitelyTyped#37050]
Hi, I'm getting an error in my Angular project:

> core.js:9110 ERROR Error: Uncaught (in promise): Error: No "GlobalWorkerOptions.workerSrc" specified.
Error: No "GlobalWorkerOptions.workerSrc" specified.

and here is my code:

`async onFilePicked(event){ 
try{

     this.PDFJS.workerSrc = event.target.files[i].name + "/pdf.worker.js";
     this.pdfDoccc = await pdfjslib.getDocument(URL.createObjectURL(event.target.files[i])).promise       
    ....
     
        } catch (e) {
            this.alert = {message: e.message + this.namesNotFound, type: "danger"}
        } 
    }
`
any suggestions?

**Comment by SneakyFish5** [comment]
Are you sure this is an error with DefinitelyTyped? Seems like an error in your code.

**Comment by neo-xy** [comment]
not sure at all but seen that people are having problem with "GlobalWorkerOptions" and blaming on types/pdfjs-dist so I thought it will be the best to write it here direcly

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
