### ISSUE TITLE
Extend Response Type with given redirected property

### ISSUE THREAD

**Issue by LaseII** [DefinitelyTyped/DefinitelyTyped#37068]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/node-fetch` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

I will open a PR with a change. 

to be honest i don't know which @author i can ask to take a look.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
