### ISSUE TITLE
[@types/bull] No support for manual queue processing

### ISSUE THREAD

**Issue by Siyfion** [DefinitelyTyped/DefinitelyTyped#37107]
I'm getting the following error when attempting to use manual queue processing functions:
```
Property 'getNextJob' does not exist on type 'Queue<IJob>'.
```
@borys-kupar / @andy-ms / @weeco

**Comment by aldo-sanchez** [comment]
Was there ever a resolution to this? I'm also facing the same issue almost a year later

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
