### ISSUE TITLE
Export Seqelize Interface

### ISSUE THREAD

**Issue by EToreo** [DefinitelyTyped/DefinitelyTyped#3717]
Export Seqelize interface so clients can use the interface as a type.

https://github.com/borisyankov/DefinitelyTyped/blob/master/sequelize/sequelize.d.ts#L150

Just need to add "export" to that line.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
