### ISSUE TITLE
[@types/chrome] Cannot read property 'sync' of undefined

### ISSUE THREAD

**Issue by ShuaiW** [DefinitelyTyped/DefinitelyTyped#37170]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/chrome` package and had problems.
- [x] I tried using the latest stable version of tsc (3.1.6) https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @matthewkimber, @otiai10, @couven92, @rreverser, @sreimer15, @MatCarlson, @ekinsol

**Comment by otiai10** [comment]
Did you successfully compile your ts to js?

Note that all the `d.ts` files are just mocks of types so that TypeScript compiler can compile your `.ts` **as if modules provided with `d.ts` exist on your runtime**. It means even when you can compile your ts with `@types/chrome`, you have to make sure the real `chrome` (and `chrome.storage` in this case) module is provided and referable on your runtime.

In my assumption, you are missing something in your `manifest.json`: https://stackoverflow.com/questions/17998123/chrome-storage-sync-undefined

Hope it helps

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
