### ISSUE TITLE
[@types/eslint] Missing props in Linter.Config

### ISSUE THREAD

**Issue by fifn2** [DefinitelyTyped/DefinitelyTyped#37183]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/eslint` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @pmdartus @j-f1 @saadq 

If you do not mention the authors the issue will be ignored.

---
I've been trying to create an eslint config object with the type `Linter.Config` type, but it appears to be missing the properties `plugins` and `extends`. Am I using the wrong type, or should I open a PR for the missing properties?

**Comment by fifn2** [comment]
#37341

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
