### ISSUE TITLE
[@types/pkijs] Missing build reference in types declaration

### ISSUE THREAD

**Issue by awattez** [DefinitelyTyped/DefinitelyTyped#37200]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/pkijs` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @microshine

If you do not mention the authors the issue will be ignored.

---

Please refer to `build` directory and not `src` directory in all type declaration.
According to `package.json` from pkijs :
https://github.com/PeculiarVentures/PKI.js/blob/master/package.json
`main` is in `build` directory

I have trouble with jest:
```
/node_modules/pkijs/src/Certificate.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as asn1js from "asn1js";
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
