### ISSUE TITLE
[@types/jest-when] Interface 'WhenMock<T, Y>' incorrectly extends interface 'MockInstance<T, Y>'

### ISSUE THREAD

**Issue by sidharthv96** [DefinitelyTyped/DefinitelyTyped#37206]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/jest-when` 2.4.1 package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @aldentaylor @immanuel192 @gstamac 

If you do not mention the authors the issue will be ignored.

```node_modules/@types/jest-when/index.d.ts(11,18): error TS2430: Interface 'WhenMock<T, Y>' incorrectly extends interface 'MockInstance<T, Y>'.
  Types of property 'mockImplementation' are incompatible.
    Type '(fn: (...args: Y) => T) => this' is not assignable to type '(fn?: ((...args: Y) => T) | undefined) => Mock<T, Y>'.
      Type 'this' is not assignable to type 'Mock<T, Y>'.
        Type 'WhenMock<T, Y>' is missing the following properties from type 'Mock<T, Y>': apply, call, bind, prototype, and 5 more.```

**Comment by chinesedfan** [comment]
@sidharthv96 Can you show source codes, besides errors?

**Comment by Sehsyha** [comment]
I had the same issue, and it doesn't come from the types of jest-when. It come from the fact that the type of return of this functions changed in jest types, so you have to update the @types/jest package in order to solve it :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
