### ISSUE TITLE
[@types/styled-components] Prop forwardedAs introduced by v4.3 is missing in types

### ISSUE THREAD

**Issue by patricknick** [DefinitelyTyped/DefinitelyTyped#37214]
If you know how to fix the issue, make a pull request instead.

- [ x] I tried using the `@types/xxxx` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: Authors: @Igorbek @Igmat @Lavoaster @Jessidhia @JKillian @eps1lon @flavordaaave

In v4.3 styled-components introduced the (quite hidden) property "forwardedAs" to forward the polymorphic as to nested styled components. But at the moment the types report an error as forwardedAs is not yet represented.

I created a little codesandbox for demonstration:
https://codesandbox.io/s/confident-rgb-s0y9n

I assume the easiest solution would be to add it here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/47b7924a7db33778c607f2db73ee0da0873d5c5c/types/styled-components/index.d.ts#L90
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/47b7924a7db33778c607f2db73ee0da0873d5c5c/types/styled-components/index.d.ts#L190

Would that be the correct solution? If so I will create a PR for this issue.

**Comment by gavinsharp** [comment]
Looks like this was fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41347.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
