### ISSUE TITLE
GlobalWorkerOptions missing in @types/pdfjs-dist

### ISSUE THREAD

**Issue by elcreator** [DefinitelyTyped/DefinitelyTyped#37236]
- [x] I tried using the `@types/pdfjs-dist` package and had problems.
TS2339: Property GlobalWorkerOptions does not exist

```
import * as pdflib from 'pdfjs-dist';

pdflib.GlobalWorkerOptions.workerSrc = '......';
```

**Comment by mattrhysgregory** [comment]
Also having this issue

Can only get it to work by requiring the library

`
const pdfjsLib = require("pdfjs-dist");

pdfjsLib.GlobalWorkerOptions.workerSrc = "pdf.worker.js";
`

**Comment by kumekay** [comment]
Looks like a dupplication of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33762

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
