### ISSUE TITLE
"can only be default-imported using the 'esModuleInterop' flag"

### ISSUE THREAD

**Issue by hems** [DefinitelyTyped/DefinitelyTyped#37244]
I tried using the `@types/web3` package and had problems:

````
Module '"xxx/node_modules/@types/web3/index"' can only be default-imported using the 'esModuleInterop' flag
````

![image](https://user-images.githubusercontent.com/27327/62147503-8df3be00-b2ef-11e9-8504-f76b2bdba1ee.png)

Perhaps @regevbr or @Levino could help here?

I suspect this PR is related to this issue: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29088

Apparently, we just need to change to `export {Web3}` instead of `export =`, but i'm not entirely sure.

This is creating issues for me when using Web3 types.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
