### ISSUE TITLE
Provide any/all supported package structures in README

### ISSUE THREAD

**Issue by jedmao** [DefinitelyTyped/DefinitelyTyped#37256]
It's hard to verify that a particular PR's test files are actually being run.

In the [create a new package](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) section of the README, it provides a folder/file structure for a DT package, but there is no mention of alternate package structures that are supported by [`types-publisher`](https://github.com/microsoft/types-publisher); specifically, [this section of code](https://github.com/microsoft/types-publisher/blob/c4762a372a40fa3dd26f7b7308d8257ba551e093/src/lib/definition-parser.ts#L237-L251) referenced [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36708#discussion_r307646650).

Please clarify and/or reference to appropriate documentation that would call out any/all supported folder/file structures for DT test files.

Additionally, please provide more verbose output in each PR's Travis-CI build that would confirm that associated test files are actually being picked up.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
