### ISSUE TITLE
Can't find name unknown

### ISSUE THREAD

**Issue by JagdishThakre** [DefinitelyTyped/DefinitelyTyped#37257]
I am getting can't find name 'Unknown'  in iOS machine.

Typescript Error
Cannot find name 'unknown'.
node_modules/@types/nodemailer/lib/smtp-connection/index.d.ts **Line no 69**

reject(err: Error \| string): unknown;
--
  | }

Typescript Error
Cannot find name 'unknown'.
node_modules/@types/nodemailer/lib/smtp-connection/index.d.ts **Line No 70**
}
interface CustomAuthenticationHandlers {

Typescript Error
Cannot find name 'unknown'.
node_modules/@types/nodemailer/lib/smtp-connection/index.d.ts **Line No 71**
}
type DSNOption = 'NEVER' | 'SUCCESS' | 'FAILURE' | 'DELAY';

Package Version : 6.2.1

It's working fine on Windows machine but getting error on Mac machine.

Please check it and provide the solution, it will be very helpful for us.

We are using this plugin in ionic 4 with firebase functions.

**Comment by SneakyFish5** [comment]
Is your TypeScript version greater than 3? You can check with `tsc -v`

**Comment by JagdishThakre** [comment]
> Is your TypeScript version greater than 3? You can check with `tsc -v`

Yes, it's 3.5.3

**Comment by JagdishThakre** [comment]
@SneakyFish5 it's very urgent, please let me know solution if you have any idea about this.

**Comment by ViditBabele** [comment]
Hey. Have you found the solution?

**Comment by jorymullet** [comment]
I found that running `tsc -v` give me `3.5.3`.

However, when I looked into the **package.json** containing my `devDependecies`, I was only at `2.x.x`. I cd'ed into that directory, and ran the following: 

`npm install --save-dev typescript@3.5.3`

Hope this helps!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by Dazzoo** [comment]
Thanks. it works with ` npm install --save-dev typescript@3.5.3`
