### ISSUE TITLE
ember router: private namespacing

### ISSUE THREAD

**Issue by dustinsoftware** [DefinitelyTyped/DefinitelyTyped#37323]
The type definitions for the `beforeModel` hook depends on `Transition`, which lives in a "-private" folder, discouraging use. Can this be exported in a public space since this is a public API?

Example use
`import Transition from '@ember/routing/-private/transition'`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/68de2097a1074aada33aacbaef9a25d02b534c78/types/ember__routing/route.d.ts#L44

@chriskrycho

**Comment by chriskrycho** [comment]
Noted, and thank you! Can you open a corresponding issue on [typed-ember/ember-cli-typescript](https://github.com/typed-ember/ember-cli-typescript/issues/new?template=---types-bug.md) (that link will make a types-specific bug there directly)? Since we don't have the ability to manage issues here, we use that for tracking/discussion/etc.

**Comment by dustinsoftware** [comment]
Discussion moved to `ember-cli-typescript`
