### ISSUE TITLE
@types/async missing promise definitions

### ISSUE THREAD

**Issue by SherloxTV** [DefinitelyTyped/DefinitelyTyped#37325]
- [x] I tried using the `@types/async` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - @borisyankov
  - @kern0
  - @Penryn

Hey there, firstly thanks for typing the awesome `async` library.

Unfortunately you only typed the callback methods, and not the promise :frowning: 

I am getting this error because of this:
```
const timesSeries: <unknown, Error>(n: number, iterator: async.AsyncResultIterator<number, unknown, Error>, callback: async.AsyncResultArrayCallback<unknown, Error>) => void
Expected 3 arguments, but got 2.ts(2554)
index.d.ts(229, 99): An argument for 'callback' was not provided.
```

Could you guys just "overload" the definitions for promises ? I am new to Typescript so I don't really know how this works.

Thanks in advance

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
