### ISSUE TITLE
@types/stripe OATH not in types

### ISSUE THREAD

**Issue by noah-witt** [DefinitelyTyped/DefinitelyTyped#37343]
@wjohnsto
@codeanimal
@sampsonjoliver
@LinusU
@brannon
@kkamperschroer
@starhoshi
@bruun
@bruun
@htunnicliff
@squirly
@tzarger
@ifiokjr
@yultyyev
@cpsoinos
@adamduren
@saranshkataria
@0xJoKe
@delianides
@gokulchandra
@gokulchandra
@chrisleck
@opticalgenesis
@opticalgenesis
@vaskevich
@vaskevich
@esetnik
@schfkt
@ChrisZieba

in this PR to stripe node oath support was added. https://github.com/stripe/stripe-node/pull/555
these do not appear in the types.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
