### ISSUE TITLE
@types/stripe stripe.customers.createTaxId and deleteTaxId are not defined.

### ISSUE THREAD

**Issue by tat-m3dicine** [DefinitelyTyped/DefinitelyTyped#37383]
If you know how to fix the issue, make a pull request instead.

- [ x ] I tried using the `@types/xxxx` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

I have a project which uses `TaxId` API from stripe. Current version installed in the project is  @types/stripe@6.31.13 and doesn't support `stripe.customers.createTaxId()` and `stripe.customers.deleteTaxId()`.

@wjohnsto @CodeAnimal @sampsonjoliver

**Comment by danmana** [comment]
Fixed by #37965

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
