### ISSUE TITLE
missing methods in `@types/continuation-local-storage`

### ISSUE THREAD

**Issue by vinodgubbala** [DefinitelyTyped/DefinitelyTyped#37429]
@andy-ms and @aboveyou00: There are a variety of methods missing from the continuation-local-storage declaration for @types/continuation-local-storage@^3.2.1, most notably enter and exit functionality. Without knowing much about writing definitions, this is the patch I'm currently using, surely not enough for a merge request:
`

    export interface Namespace {
       readonly name: string; // Note: this is readonly because changing it does not actually rename it
       readonly active: Context; // Note: this is readonly because changing it manually will break functionality
       createContext(): Context;

        set<T>(key: string, value: T): T;
        get(key: string): any;

        run(callback: Func<void>): Context;
        run<T>(callback: Func<T>): Context;
        runAndReturn<T>(callback: Func<T>): T;
        bind(callback: Func<void>, context?: Context): Func<void>;
        bind<T>(callback: Func<T>, context?: Context): Func<T>;
        bindEmitter(emitter: NodeJS.EventEmitter): void;
        enter(context: Context): void;  //New function
        exit(context: Context): void;  //New function
    }
`

I'd like to add that this leads to compile-time errors when using ts-node, yet in VS Code, is recognized correctly without any noted errors.

**Comment by vinodgubbala** [comment]
@creationix Can you please check this once? As you made the methods public with your https://github.com/othiym23/node-continuation-local-storage/commit/bc4503cbb6e0571f7461685706230b06a48ca3dc#diff-7b81bf063d158819b76b1c0b0aadee75R30

C.C: @othiym23

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
