### ISSUE TITLE
Missing types for velocity-react

### ISSUE THREAD

**Issue by dawidk92** [DefinitelyTyped/DefinitelyTyped#37468]
`velocity-react` is missing typings despite the fact that this library is 4 years old already and has over 320k weekly downloads.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
