### ISSUE TITLE
[lodash] generated `fp` types are broken

### ISSUE THREAD

**Issue by millsp** [DefinitelyTyped/DefinitelyTyped#37499]
Hi @OliverJAsh @aj-r,

I've just cloned the repo and tried to generate `fp.d.ts` with the scripts in the `3.1` folder. The generated `fp.d.ts` is different from the one that is in production and contains type errors:
```ts
    interface LodashMapValues2x2 {
        (iteratee: object): lodash.Dictionary<boolean>;
        <TKey extends keyof T>(iteratee: TKey): lodash.Dictionary<T[TKey]>;
        (iteratee: string): lodash.Dictionary<any>;
    }
```
The type parameters are missing for this type.

Could it be that someone forgot to run `npm run generate`?
Or am I missing something?

**Comment by aj-r** [comment]
They probably manually fixed the output of `npm run generate` because it generated something with errors.

This looks like a bug in `generate-fp.ts` to me. I think the generated output should be more this?

```ts
    interface LodashMapValues2x2<T> {
        <TResult>(callback: (value: T) => TResult): lodash.Dictionary<TResult>;
        (iteratee: object): lodash.Dictionary<boolean>;
        <TKey extends keyof T>(iteratee: TKey): lodash.Dictionary<T[TKey]>;
        (iteratee: string): lodash.Dictionary<any>;
    }
```

**Comment by pirix-gh** [comment]
Ok, thanks :) I thought a bug had been silently pushed.

I'll take a look, see if it can be fixed easily

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
