### ISSUE TITLE
[@types/react-pdf] error TS2707: Generic type 'ReactElement<P, T>' requires between 1 and 2 type arguments.

### ISSUE THREAD

**Issue by truca** [DefinitelyTyped/DefinitelyTyped#37506]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CodeDaraW @nhardy 

This issue is related to [this](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34041) I'm currently using these versions:

```
"react": "16.8.0",
"react-pdf": "^4.0.5",
"@types/react": "16.8.1",
"@types/react-pdf": "4.0.2",
```

And I'm getting a 3 errors in Document and 3 in Page from this: `Generic type 'ReactElement<P, T>' requires between 1 and 2 type arguments.`. I could submit a PR for this with a bit of guidance.

**Comment by truca** [comment]
Just found [this issue](https://github.com/react-dnd/react-dnd/issues/1440), tried the solution and it seems that it works

**Comment by CodeDaraW** [comment]
Yeah, it's a problem about `@types/react`, updating `@types/react` can solve it.  
See https://github.com/DefinitelyTyped/DefinitelyTyped/commit/2fc40ca501f2cc734deb9313fa1032e3381a0e26#diff-96b72df8b13a8a590e4f160cbc51f40cL86 .

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
