### ISSUE TITLE
Update animejs to 3.*

### ISSUE THREAD

**Issue by exapsy** [DefinitelyTyped/DefinitelyTyped#37521]
- Authors: @A-Babin 

Hey A-Babin! AnimeJS definition file is outdated by one major (2.0 -> 3.0) and many functions and properties have changed (such as there is no longer elasticity). 

If you would like to push an update if you have the time of course that would be comfortable.

I'm willing to help on writing the new version if I'll keep using the library, although I'm very short on time and I dont know when or even if I'll do such thing or if I may just use the previous major 2.0 anyway because of time shortage.

But if you haven't got the time I'll try to do my best if I wont move to the previous version.

**Comment by A-Babin** [comment]
Hi there! It'll require a big context shift for me since I haven't worked with animejs or TS definitions in a while. I have a little bit of time tomorrow I can look into it, but I can't promise anything, definitely not on short notice, I'm afraid.

**Comment by Eksapsy** [comment]
It's okay, we're all doing what we're doing because we enjoy it anyways.

I'll try to look it up when I'll have time if there won't be an update till then. :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
