### ISSUE TITLE
[@types/yup] last changes are not released yet

### ISSUE THREAD

**Issue by cusspvz** [DefinitelyTyped/DefinitelyTyped#37586]
At the [yup](https://github.com/jquense/yup#typescript-support)'s README there's an indication to use it with typescript. Happens that the last released version doesn't include the `InferType` type, so no one is able to use it like that.

Can we get a patch version release?

**Comment by kimroen** [comment]
As far as I can tell, the latest version of `@types/yup` does include this type, so I think this can be closed.

```ts
import { InferType } from 'yup';
```

**Comment by JipSterk** [comment]
maybe also nice to have default import with the `allowSyntheticDefaultImports` flag

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
