### ISSUE TITLE
[@types/react] ReactNode allows `Date` and other things that cause a runtime errror if rendered with React

### ISSUE THREAD

**Issue by Ryan1729** [DefinitelyTyped/DefinitelyTyped#37596]
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc `3.5.3`
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon

---

The following code does not produce a type error like I would expect:

```ts
const node: ReactNode = new Date();
```

This means that if a date is returned from a Component then we get no compile-time error, and instead get a run-time warning from React, (in development mode).

Looking at the current [definition of ReactNode](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/981cc6d51eb213943a3606c14ad75d65ea6b360f/types/react/index.d.ts#L186-L191) ...

```ts
    type ReactText = string | number;
    type ReactChild = ReactElement | ReactText;

    interface ReactNodeArray extends Array<ReactNode> {}
    type ReactFragment = {} | ReactNodeArray;
    type ReactNode = ReactChild | ReactFragment | ReactPortal | boolean | null | undefined;
```

... it appears that the issue is `ReactFragment` allowing `{}`, (which turns out to include [more than might be expected](https://www.typescriptlang.org/play/index.html#code/MYewdgzgLgBFAWBLCAVAngBwKYGF5eAGsIAuGAbwF8YBeOAJwFcsBuAWAChRJYFl1seAsQBMZKrRgj2XcNDhJUmXPiKp49LFnHU6AIhQatemZ27y+EACIgsEAHIgoAlcICSYAMpR6iYFABZEAATbQpdGDBGABtoliA)). 

Looking at [this bit of react source code](https://github.com/facebook/react/blob/a22880e5e59d5cb17fffe04af093ea54e356538d/packages/react-is/src/ReactIs.js#L30-L65) suggests that all real fragments and related react types will have a `$$typeof` property.

```ts
export function typeOf(object: any) {
  if (typeof object === 'object' && object !== null) {
    const $$typeof = object.$$typeof;
    // ... omitted code involving things like `REACT_FRAGMENT_TYPE`
  }

  return undefined;
}
```

Given a proper `$$typeof` is present, it's value appears to be either a [`symbol`](https://www.typescriptlang.org/docs/handbook/symbols.html), or a `number` (based on looking at the [definitions of `REACT_FRAGMENT_TYPE` and so forth](https://github.com/facebook/react/blob/42b75ab007a5e7c159933cfdbf2b6845d89fc7f2/packages/shared/ReactSymbols.js) from the omitted code.)

So would it work to replace `{}` in `ReactFragment` with something like `{$$typeof: symbol | number }`, or maybe `{$$typeof: symbol | number | undefined }` since those both [exclude `Date`](https://www.typescriptlang.org/play/index.html#code/MYewdgzgLgBAZiEAuGBvAJOqBPADgUxDhQmwFsAjEAGxgB8YwBXS-AJ3pibABN84AlmHw8AvjAC8jfAHcYAEQCGUfAAoAlAG4AsAChQkWBUVsUGLHkLEYpSjU7NWHBtz6DhYyWlE794aDDGAF5mmDgERCTkVLQMjhTsnK78QiLiUubhVijJ7mmaQA)? Or is there some obscure compatibility problem with that like I've seen described in some other `@types/react` issues on this repo?

**Comment by Ryan1729** [comment]
In an attempt to distill sown my wall of text there, here's the issue in a nutshell
```ts
const thisTypeChecks: {} = true;
const thisTypeChecks2: {} = 2;
const thisTypeChecksThree: {} = "Three";
```
[TS Playground link (already included above)](https://www.typescriptlang.org/play/index.html#code/MYewdgzgLgBFAWBLCAVAngBwKYGF5eAGsIAuGAbwF8YBeOAJwFcsBuAWAChRJYFl1seAsQBMZKrRgj2XcNDhJUmXPiKp49LFnHU6AIhQatemZ27y+EACIgsEAHIgoAlcICSYAMpR6iYFABZEAATbQpdGDBGABtoliA)

**Comment by ferdaber** [comment]
We ideally should not be having the empty type in `ReactNode` like you said, however a lot of developers are still relying on autotyped children (creating a class component or a function component and typing it as `SFC`) and removing it is a big breaking change. There were a couple of PRs in the past that tried to remove it and it was just a lot of breaks to dependent libraries to deal with so none of them went through.

**Comment by pomle** [comment]
Thank you for the background on this, @ferdaber 

Would you be able to elaborate or link to more information on the attempts that have been made to fix this?
I couldn't fully understand the full scope of the problem.

It seems to me like it could be harmful to the community to let ReactNode report false positives.
It seems like it would also be harmful to the confidence of @DefinitelyTyped to recommend avoiding some types.

Since I don't know much about DefinitelyTyped, is it possible to do breaking changes if one would be willing to drive acceptance for it in the community?

Is DefinitelyTyped releases compatible with NPMs semantic versioning practice?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
