### ISSUE TITLE
Recharts dataKey in scatter

### ISSUE THREAD

**Issue by nicokiva** [DefinitelyTyped/DefinitelyTyped#37598]
Scatter implementation accepts dataKey as a props but type does not accept it.

@rapmue @royxue @ZheyangSong @richbai90 @caspeco-dan

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
