### ISSUE TITLE
[@types/papaparse] `File` typedef not compatible with Node environment

### ISSUE THREAD

**Issue by tyson-kubota** [DefinitelyTyped/DefinitelyTyped#37601]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c50af0ccba4fff6c0ab1a00da4bca89e3ef4fd8e/types/papaparse/index.d.ts#L22

PapaParse supports running in a Node environment instead of a browser, but the TypeScript definitions fail to compile in a non-browser project due to the use of a `File` type, which is a reference to the web API `File` (which isn't present unless the compilation environment assumes a web browser).

https://github.com/mholt/PapaParse#papa-parse-for-node

**Comment by kevindoveton** [comment]
Until  this is fixed, as a workaround you can add `"skipLibCheck": true` to you tsconfig.json file

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
