### ISSUE TITLE
lodash: isEmpty\size === 0\etc aren't considered by the typescript as verification for `undefined`

### ISSUE THREAD

**Issue by deser** [DefinitelyTyped/DefinitelyTyped#37610]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/lodash` package and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @WilliamChelman 

![image](https://user-images.githubusercontent.com/3010698/63008420-43e01000-be8b-11e9-8749-31f240e6b19c.png)

**Comment by fabis94** [comment]
Any workaround for this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
