### ISSUE TITLE
Compile issues with npm typescript@1.4.1

### ISSUE THREAD

**Issue by dantedubon** [DefinitelyTyped/DefinitelyTyped#3763]
I installed the tsc with npm yesterday and when I download the definitions with tsd@0.5.7 and I proceed to compile my code I got a lot of compile errors from the definitions. The only way that I have found to fix this kind of errors is going back to definitions for the typescript 1.3, Do you have an idea why this is happening?

**Comment by evilryu** [comment]
Got same problem. Latest version of typescript compiler is installed via npm and I get lots of syntax errors when compiling files on this repo. Doing some digging I found out the typescript files on this repo are in 1.4 typescript and compiler is on 1.3.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
