### ISSUE TITLE
SchemaOptions.autoCreate missing

### ISSUE THREAD

**Issue by scoriiu** [DefinitelyTyped/DefinitelyTyped#37668]
According to the docs, "SchemaOptions.autoCreate" should be available, but it's not.
https://mongoosejs.com/docs/guide.html#autoCreate

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
