### ISSUE TITLE
[@types/gm] parameter of type "WriteCallback" has a wrong type

### ISSUE THREAD

**Issue by CrSjimo** [DefinitelyTyped/DefinitelyTyped#37695]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ChaosinaCan  @maartenvanvliet  @mlejva  @mrcageman

1. `type WriteCallback = (err: Error, stdout: string, stderr: string, cmd: string) => any;` is wrong. It should be `type WriteCallback = (err: Error|null, stdout: stream.Readable, stderr: stream.Readable, cmd: gm.State) => any;`(line 604)

2. Besides the function mentioned above, type of parameter `Error` in each callback function should be `Error|null` instead of `Error`

**Comment by maartenvanvliet** [comment]
Could you file a PR?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
