### ISSUE TITLE
[@types/gapi.client.slides] slides namespace is not recognized

### ISSUE THREAD

**Issue by andriychuma** [DefinitelyTyped/DefinitelyTyped#37717]
Having installed `@types/gapi.client.slides` package, `gapi.client.slides` namespace does not get recognized, whilst for instance `gapi.client.load('slides', 'v1')` signature is being recognized well.

It looks like the root cause is `presentations` const which is currently placed under `gapi.client` namespace, but should be under `gapi.client.slides` (I've tested it on the library):

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/518700405e6f24d00288c4bb3bf56d2d4b8dae97/types/gapi.client.slides/index.d.ts#L14-L21

After moving it into the right place, it looks like the issue goes away.

**Package version**
`"@types/gapi.client.slides": "1.0.1"`

**Comment by Maxim-Mazurok** [comment]
Hello, can you give the most recent version of `@types/gapi.client.slides` a try?
It should be fixed by the new generator: [Maxim-Mazurok/google-api-typings-generator](https://github.com/Maxim-Mazurok/google-api-typings-generator)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
