### ISSUE TITLE
[@types/recharts] Function parameters for ContentRenderer are typed as 'any'

### ISSUE THREAD

**Issue by C-Higgins** [DefinitelyTyped/DefinitelyTyped#37730]
Custom renderer functions have a defined set of props that are passed to them, for example the `activeShape` prop in the `Pie` component has `cx`, `cy`, `innerRadius`, `payload`, and many others in its props object. However, the types list simply `activeShape?: object | ContentRenderer<any> | React.ReactElement;` and `export type ContentRenderer<P> = (props: P) => React.ReactNode;`

`ContentRenderer<any>` is not a useful type, as there is no mention of what it receives in its props. The recharts API also does not specify this, so a manual inspection may be necessary.

@rapmue 
@royxue
@ZheyangSong
@richbai90
@caspeco-dan
@pkeuter
@jrsaunde
@crusectrl
@apalugniok
@RobertStigsson
@kousaku-maron
@iflp
@veddermatic
@g07cha

**Comment by G07cha** [comment]
Sounds about right to me, do you want to work on this?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
