### ISSUE TITLE
about hooks which supports custom store / dispatch / context

### ISSUE THREAD

**Issue by ykwmz** [DefinitelyTyped/DefinitelyTyped#37737]
After checking the api of react-redux following:
https://react-redux.js.org/next/api/hooks

There has createDispatchHook/createSelectorHook, but also custom Provider can work,
but the typescript definition file lack of that.

Could you add them ? like:
-----------------------------

declare module 'react-redux' {
    // * definition for createDispatchHook of react-redux js
    export function createDispatchHook(context: Context = ReactReduxContext): typeof useDispatch

    // * definition for createSelectorHook of react-redux js
    export function createSelectorHook(context: Context = ReactReduxContext): typeof useSelector

    // * custom provider would use custom context by React.createContext
    export interface ProviderProps<A extends Action = AnyAction> {
        store: Store<any, A>;
        context?: Context<any>;
    }
    export class Provider<A extends Action = AnyAction> extends Component<ProviderProps<A>> { }
}

**Comment by ptgamr** [comment]
+1

**Comment by abirmingham** [comment]
This appears to be done. However, `ProviderProps` is typed with `context?: Context<ReactReduxContextValue>`, and I believe that this should actually be `context?: Context<ReactReduxContextValue | null>` (see [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39216#discussion_r349157793)).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
