### ISSUE TITLE
How do I extend a  class definition in my project?

### ISSUE THREAD

**Issue by NichijouCC** [DefinitelyTyped/DefinitelyTyped#37796]
i encountered some question and don't how to solve it  when i used @types/cesium

the class definded missing some parts in index.d.ts  ，i want to extend in my own project and not change the index.d.ts file.

such as:
1.extend A class static function
2.class constrcutor params optionals

**Comment by NichijouCC** [comment]
@Aigars Zeiza

**Comment by NichijouCC** [comment]
@szechyjs

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
