### ISSUE TITLE
[@types/yargs] an option with required: true should not have undefined in its type

### ISSUE THREAD

**Issue by mleguen** [DefinitelyTyped/DefinitelyTyped#37797]
@poelstra @mizunashi-mana @pushplay @jeffkenney  @JimiC @steffenvv @forivall 

A required option or positional still has `undefined` in its type if `true` (boolean) is passed to `required`, which is unexpected :
```js
yargs.command('cmd foo', 'test command',
  yargs => {
    yargs.positional('foo', { type: 'string', required: true });
  },
  argv => {
    // type for argv.foo should be "string" but is "string | undefined"
  }
);
```
whereas it is not with `'true'` (string), as expected:
```js
yargs.command('cmd foo', 'test command',
  yargs => {
    yargs.positional('foo', { type: 'string', required: 'true' });
  },
  argv => {
    // type for argv.foo is "string"
  }
);
```

See yargs/yargs#1393

**Comment by forivall** [comment]
Yeah, I've noticed this myself, but ive manually augmented the inferred types to handle it so far. Id welcome a PR!

**Comment by jgehrcke** [comment]
> but ive manually augmented the inferred types to handle it so far. Id welcome a PR!

how do you do that? Example would be super helpful!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
