### ISSUE TITLE
"error" property not set on PaymentIntentResponse

### ISSUE THREAD

**Issue by silentsnooc** [DefinitelyTyped/DefinitelyTyped#37836]
I have just tried to get an error as I handle a `PaymentIntent` twice using `handleCardPayment()`.

```typescript
this._stripeClientService.stripe
  .handleCardPayment(paymentIntent.clientSecret)
  .then((result) => {
      console.log(result);
      if (result.error) {
        // never reached
        console.log('has an error set');
      }
    },
    (e) => {
      // nevere called
      console.log('ONREJECT');
    })
  .catch((error) => {
    // nevere called
    console.log('ERROR');
  });
```

However, no matter what, only `onfulfilled` gets called and the `result` (which is a `PaymentIntentResponse`) does not have an `error` property set.

I do se a HTTP 400 error in the console but I cannot deal with the error programmatically. Am I doing something wrong here?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
