### ISSUE TITLE
[Mongoose] Find out which is the last commit of the version

### ISSUE THREAD

**Issue by abnersajr** [DefinitelyTyped/DefinitelyTyped#37873]
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @lukasz-zak  @nacimgoura 

## Problem Description

I'm facing issues with a certain type that was introduced on a past commit. However, I don't know exactly which package version this issue was introduced. I don't know exactly how to establish a relation between a specific commit and a npm version since doesn't have tags on the Github Repo.

Example: The version npm 5.5.8. Which is the commit used to publish this version?
I don't know how to get the right version that doesn't have the bad code what I don't want.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
