### ISSUE TITLE
[@types/pluralize]: The "pluralize" function declaration export is overridden by the namespace declaration of the same name and can't be used.

### ISSUE THREAD

**Issue by insidewhy** [DefinitelyTyped/DefinitelyTyped#37887]
At the top we see:

```typescript
declare function pluralize(word: string, count?: number, inclusive?: boolean): string;
```

But right below:

```typescript
declare namespace pluralize
```

So the final:

```typescript
export = pluralize;
export as namespace pluralize;
```

Exports only the namespace. Unfortunately the namespace is also a function for this package, the function we see defined first.

**Comment by baconcheese113** [comment]
Same issue, how did you end up resolving it?

**Comment by insidewhy** [comment]
@baconcheese113 I rewrote my own simple pluralize function in like 5 lines of code.

**Comment by baconcheese113** [comment]
Hope you support pluralizing `ox`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
