### ISSUE TITLE
@types/braintree-web ThreeDSecure.verifyCard changed parameters in v3.47

### ISSUE THREAD

**Issue by puggan** [DefinitelyTyped/DefinitelyTyped#37925]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `braintree.ThreeDSecure.verifyCard` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @chlela 

The functoin braintree.ThreeDSecure.verifyCard() got new parameters in v3.47, for 3DS 2.0.
The DefinitelyTyped only support the old parameters for 3DS 1.0

**Comment by Dalez** [comment]
I've ran into the same issue. I was able to manually edit the .d.ts file to:

`    verifyCard(options: { nonce: string, amount: number, onLookupComplete: (data: verificationData, next: callback) => void }): Promise<ThreeDSecureVerifyPayload>;
    verifyCard(options: { nonce: string, amount: number, onLookupComplete: (data: verificationData, next: callback) => void }, callback: callback): void;`

On line 1236 of index.d.ts in @types/braintree/web.

However, I'm not sure how to add the verificationData definition, so I've added: `: any` to my data variable on the onLookupComplete function:

`          onLookupComplete: (data: any, next: callback) => next()`

Hopefully it will be updated soon :smile:

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
