### ISSUE TITLE
[@types/gapi.client.slides] incorrect `batchUpdate` method signature

### ISSUE THREAD

**Issue by andriychuma** [DefinitelyTyped/DefinitelyTyped#37938]
I discovered a missing `requests` property in the `batchUpdate()` signature which should be accepted according with [the documentation](https://developers.google.com/slides/how-tos/styling) (see JavaScript example tabs).

I also found a `BatchUpdatePresentationRequest` interface which most likely should somehow extend the type of `batchUpdate` input:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/518700405e6f24d00288c4bb3bf56d2d4b8dae97/types/gapi.client.slides/index.d.ts#L46-L51

Pay attention, that the `BatchUpdatePresentationRequest` interface does not reflect the request type on its own since the `presentationId` property is missing.

**Package version**
`"@types/gapi.client.slides": "1.0.1"`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
