### ISSUE TITLE
[core-js] Missing collection methods proposal

### ISSUE THREAD

**Issue by kausters** [DefinitelyTyped/DefinitelyTyped#37964]
- [x] I tried using the `@types/core-js` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rbuckton, @mfdeveloper

`core-js@3` includes [Stage 1 proposal](https://github.com/zloirock/core-js#user-content-stage-1-proposals) for [collection methods](https://github.com/tc39/proposal-collection-methods), enabling `Set.prototype.map`, `Map.prototype.filter` etc. (basically mimicking `Array` methods) via ` import core-js/proposals/collection-methods`. These don't appear to exist in `@types/core-js`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
