### ISSUE TITLE
ol.Sphere must be ol.sphere

### ISSUE THREAD

**Issue by fgrenot** [DefinitelyTyped/DefinitelyTyped#38003]
I tried using the `@types/openlayers` package on version 4.6.17 and had problems.

The `ol.Sphere` package doesn't exist on js version. It is `ol.sphere`. So currently, I need to write `(ol as any).sphere` to compile and use the good js package.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
