### ISSUE TITLE
[react-testing-library] Type definitions not good enough for WebStorm

### ISSUE THREAD

**Issue by pasku** [DefinitelyTyped/DefinitelyTyped#38018]
Suppose I keep a reference to the query methods returned by `render`, as in `getByTestId = render(<MyComponent/>).getByTestId`, where `getByTestId` is a variable that I have defined in some outer scope as let `getByTestId`.

Now suppose I want to give a type to that variable. If I Cmd+click on the `.getByTestId` part of the call above, WebStorm opens `@testing-library/dom/typings/queries.d.ts` and highlights the line export `const getByTestId: GetByBoundAttribute.` I suspect this may be incorrect in itself, but the IDE does not provide any other choice when navigating to the definition.

Accordingly, I type the variable as `GetByBoundAttribute`, and then the IDE shows a compile error:

> Type (text: Matcher, options?: MatcherOptions) => HTMLElement is not assignable to type 'GetByBoundAttribute'.

If I type the variable as (`text: Matcher, options?: MatcherOptions) => HTMLElement`, the compile error disappears. Is this the intended way of typing these query methods? In that case, it would be great if this library provided a higher-level type to avoid writing so much boilerplate.

In general, how should I discover the type of these query methods? Do you think this a WebStorm-specific issue?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
