### ISSUE TITLE
 mongoose-paginate-v2 overrides mongoose types 

### ISSUE THREAD

**Issue by kerolloz** [DefinitelyTyped/DefinitelyTyped#38014]
- [x] I tried using the `@types/mongoose-paginate-v2` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @linusbrolin @simonxca @woutgg 
---

mongoose paginate overrides the types provided by mongoose.
mongoose paginate should only add its own types and leave mongoose types as it is.
for example: 
![correct](https://user-images.githubusercontent.com/36763164/63967106-fa074480-ca9c-11e9-9704-369c7313e13c.png)
but after including mongoose-paginate-v2 the suggestions don't work anymore 
![wrong](https://user-images.githubusercontent.com/36763164/63967141-10ad9b80-ca9d-11e9-9966-cdf4339dc31a.png)

**Comment by Exiou** [comment]
Hey, I'm kinda having the same problem. I know this is an old post and no one has responded but did you come up with a solution, or something like that? sorry to bother you xd

**Comment by kerolloz** [comment]
@Exiou

Unfortunately no, I didn't figure out a solution yet.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
