### ISSUE TITLE
[@types/mathjs] cannot create a new instance of a specific type of MathNode.

### ISSUE THREAD

**Issue by hadi16** [DefinitelyTyped/DefinitelyTyped#38023]
- [x] I tried using the `@types/mathjs` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @siavol @andnp @bradbesserman @pawkrol @charlee

This should work:
```typescript
import {SymbolNode} from 'mathjs';

const foo = new SymbolNode("x");
```

This is my current workaround for the issue:
```typescript
import * as mjs from 'mathjs';

interface IMathJS extends MathJsStatic {
    // This class requires a "name" as a parameter & returns a MathNode object.
    readonly SymbolNode: new (name: string) => MathNode;
}

const math = mjs as IMathJS;
const foo = new math.SymbolNode("x");
```

The MathJS documentation describes several other types of nodes (besides SymbolNode) that can be directly instantiated: [https://mathjs.org/docs/expressions/expression_trees.html#nodes](https://mathjs.org/docs/expressions/expression_trees.html#nodes)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
