### ISSUE TITLE
[@types/fabric] Support custom properties

### ISSUE THREAD

**Issue by fdw** [DefinitelyTyped/DefinitelyTyped#38031]
- [x] I tried using the `@types/fabric` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @oklemencic, @joewashear007, @mrand01, @NotWoods, @bmartinson, @RogerioTeixeira, @BradleyHill, @bmkrol823, @glenngartner, @codertx

If you do not mention the authors the issue will be ignored.

Fabric supports adding custom properties to objects, f.e. `const blah = new fabric.Circle({[...], myCustomProperty: "myCostomValue"})`. Obviously, the types do not allow this behavior.
Instead, I expected declaration merging to work:
```
interface ICircleOptions {
  myCustomProperty ?: string
}
```

However, this does not work. I have tried Stack Overflow, but the best answer was to manually edit the `.d.ts` file, which does not feel like a solution.

**Comment by mwmw7** [comment]
hello I got a similar issue 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46101

**Comment by fdw** [comment]
I solved this problem by casting to the expected value: `const blah = new fabric.Circle({[...], myCustomProperty: myCostomValue"} as ICircleOptions)`. For some reason, the cast is accepted.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
