### ISSUE TITLE
@types/react-responsive useMediaQuery not defined

### ISSUE THREAD

**Issue by tudor07** [DefinitelyTyped/DefinitelyTyped#38073]
> Module '"../../../node_modules/@types/react-responsive"' has no exported member 'useMediaQuery'

Looks like `useMediaQuery` is not defined.
Also check: https://github.com/contra/react-responsive/issues/227

@asvetliakov @alechill @xaviergonz

**Comment by kayandrewj** [comment]
Why is this closed?

**Comment by tudor07** [comment]
@kayandrewj What do you mean? This issue is still open

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
