### ISSUE TITLE
@types/cli-progress Multibar support (since Aug 11 '19)

### ISSUE THREAD

**Issue by welljsjs** [DefinitelyTyped/DefinitelyTyped#38078]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/cli-progress` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sheetalkamat @sandersn 

[Multibar support has been added to cli-progress since August 11 2019.](https://github.com/AndiDittrich/Node.CLI-Progress/commits/master/lib/multi-bar.js)

Please update the definitions file to match the new types (`SingleBar`, `MultiBar` and `Presets`):

```js
// sub-module access
module.exports = {
    Bar: _SingleBar,
    SingleBar: _SingleBar,
    MultiBar: _MultiBar,
    Presets: _Presets
};
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
