### ISSUE TITLE
[@types/echarts] SeriesSunburst.levels should be an array

### ISSUE THREAD

**Issue by Fredx87** [DefinitelyTyped/DefinitelyTyped#38077]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/echarts` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @xieisabug, @AntiMoron , @liveangela , @Ovilia , @iRON5 , @bilalucar , @tmtron , @dwhitney

The levels property of sunburst chart should be an array
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7ab8cb6cad58fe79e4714947393e380876215b39/types/echarts/options/series/sunburst.d.ts#L4157

as shown in the documentation: https://echarts.apache.org/en/option.html#series-sunburst.levels

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
