### ISSUE TITLE
async filter function miss-defined

### ISSUE THREAD

**Issue by EToreo** [DefinitelyTyped/DefinitelyTyped#3807]
I had to modify the async type definition to include a callback that does not take an error.  From async's [documentation](https://github.com/caolan/async#filter):

> _The callback for each iterator call only accepts a single argument of true or false; it does not accept an error argument first!_ This is in-line with the way node libraries work with truth tests like fs.exists.

So I added:

``` javascript
interface AsyncResultCallbackNoError<T> { (result: T): void; }
interface AsyncResultIteratorNoError<T, R> { (item: T, callback: AsyncResultCallbackNoError<R>): void; }
```

And changed the filter definition to:

``` javascript
filter<T>(arr: T[], iterator: AsyncResultIteratorNoError<T, boolean>, callback: (results: T[]) => any): any;
```

Can these changes please be adopted?

**Comment by Penryn** [comment]
I think this will be covered by #6271

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
