### ISSUE TITLE
[@types/redux-orm] Types of property are incompatible

### ISSUE THREAD

**Issue by JonnyLinja** [DefinitelyTyped/DefinitelyTyped#38118]
@keenondrums @tomasz-zablocki 

**SUMMARY OF THE ISSUE**

0.13.4 allowed use of optional SessionBoundModels and QuerySets in interfaces when upserting / creating / updating.

0.13.5 has a types of property are incompatible error.

**THE SETUP**

I've set my interfaces to have optional SessionBoundModels and QuerySets. This is done so I can query related model objects when pulling from redux-orm, but not need to define them when inserting new objects. An example is as follows, where the team relation of groups is optional.
```
export interface GroupProperties {
    readonly id: string;
    readonly name: string;
    readonly team_id: string;

    readonly team?: SessionBoundModel<TeamsModel, {}>;
}
```

**WHAT I EXPECT TO HAPPEN**

With 0.13.4, I am able to pass the interface into the generic field when using upserts, creates, and updates. TypeScript properly warns me if I'm missing a property that I need.
```
class GroupsModel extends Model<typeof GroupsModel, GroupProperties> {
    static reducer(action: Actions, Groups: ModelType<GroupsModel> ) {
        // edited reducer for simplicity
        // this works great in 0.13.4!
        Groups.upsert<GroupProperties>({
            id: action.id.toLowerCase(),
            name: action.name,
            team_id: action.team_id.toLowerCase(),
        });
    }
}
GroupsModel.modelName = 'Groups';

GroupsModel.fields = {
    name: attr(),
    team_id: fk({
        to: 'Teams',
        as: 'team',
        relatedName: 'groups',
    }),
};

export default GroupsModel;
```

**WHAT ACTUALLY HAPPENS**

However, with 0.13.5, I get the following error.
```
Type 'GroupProperties' does not satisfy the constraint 'BlueprintProps<GroupsModel, "id", "name" | "team_id" | "team">'.
  Type 'GroupProperties' is not assignable to type '{ readonly name?: string | undefined; readonly team_id?: string | undefined; readonly team?: undefined; }'.
    Types of property 'team' are incompatible.
      Type 'SessionBoundModel<TeamsModel, {}> | undefined' is not assignable to type 'undefined'.
        Type 'SessionBoundModel<TeamsModel, {}>' is not assignable to type 'undefined'.ts(2344)
```

Switching between TypeScript 3.5.2 and 3.6.2 did not resolve the error. Downgrading to 0.13.4 resolved the errors. Not having the team SessionBoundModel in the interface resolves the error with 0.13.5. 

If this is working as intended, what is the suggested method of using TypeScript with redux-orm such that I can still access related model objects, and yet have type checking on upserts, updates, and creates?

Thanks!

**Comment by tomasz-zablocki** [comment]
@JonnyLinja let me check, I'll update on this today.

**Comment by tomasz-zablocki** [comment]
Ok one thing that I know isn't supported by current typings is `as` property in `fk` and other field creator functions. 

To be honest implementing `as` in types for 0.13 isn't something I've been planning to do. The reason for that is that the mapped types are already overly complex and adding all the additional logic required to handle `as` properly would just increase the complexity twofold. 

This alone wouldn't be a problem if not for the typescript hard-limit on recursive types - it doesn't take much to hit _'Type instantiation is excessively deep and possibly infinite'_ error with these types already.

I'm a bit surprised this syntax somehow worked for you. Anyway, you've probably missed majority of typings features. In general, for the inference and type checking to work as intended, `modelName` and `fields` have to belong to `Model` class declarations. So instead of:

```typescript
class GroupsModel extends Model<typeof GroupsModel, GroupProperties> {
...
}
GroupsModel.modelName = 'Groups';
GroupsModel.fields = {
    name: attr()
};
```
you need to do this:

```typescript
class GroupsModel extends Model<typeof GroupsModel, GroupProperties> {
  static modelName = 'Groups' as const; //const is important
  static fields = {
    name: attr()
  }
}
```

In the first snippet, typescript won't treat `modelName` and `fields` as static fields of `Groups` at the moment of declaration.

The second thing is that the type annotations shouldn't be necessary. Instead of:

```typescript
Groups.upsert<GroupProperties>({
  id: action.id.toLowerCase(),
  ...
});
}
```

This should be enough: 

```typescript
Groups.upsert({
  id: action.id.toLowerCase(),
  ...
});
}
```

And the type checking should work based on what's in `GroupProperties` and in static `fields` of `Groups` class, assuming the `fields` are declared along with related model.

Let me know if this helped.

**Comment by tomasz-zablocki** [comment]
On a side note `QuerySet` fields are always present on model instances, but the typings should never require you to provide values for them. They should respect `attr({getDefault: ()=>...})` fields and make them optional in `create`. Same goes for `attr` fields marked as non required and numeric `id` fields (or custom numeric identifiers if present).

For `create`, `upsert` and `update` you shouldn't be able to provide values for `QuerySet` fields,unless it's related to `many` field. 

You can check [tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/redux-orm/redux-orm-tests.ts) for reference.

**Comment by JonnyLinja** [comment]
Oohh, that's way easier to use. It looks like refs handle `fk` properties by treating it as a string instead of a SessionBoundModel as well. I did notice that because it allows properties that aren't defined in the interface, the compiler won't yell at an upsert where name is misspelled as nmae.

Thanks again for the help and the work on the types! It ended up being user error so I have some refactoring to do.

I'm closing the issue, but if I may ask, I'd like to confirm 3 things:

1. I do have to define the relationships in my interfaces, correct? For instance, I noticed in the tests that `BookFields` has a `publisher` in the interface.
2. Do those defined relationships need to be nullable / possibly undefined? `PublisherFields` in the tests has `books` possibly being undefined for instance, but other tests do not.
3. In terms of best practices, should the codebase refer to the models using the interface type, or SessionBoundModel types / Ref SessionBoundModel types, or something else entirely? For instance
```
// option A
function processGroup(group: GroupProperties) {}

// option B
function processGroup(group: SessionBoundModel<GroupsModel, {}>) {}
```

**Comment by JonnyLinja** [comment]
@tomasz-zablocki 

Given an interface like so
```
export interface GroupProperties {
    readonly id: string;
    readonly name: string;
    readonly team_id: string;

    readonly team?: TeamsModel;
}
```

if I send an action with this interface
```
export interface GroupAction {
    type: typeof GROUP_TEST_ACTION;
    readonly group: GroupProperties;
}
```

then the following attempt to upsert, in both 0.13.4 and 0.13.5
```
class GroupsModel extends Model<typeof GroupsModel, GroupProperties> {

    static modelName = 'Groups' as const;

    static fields = {
        name: attr(),
        team_id: fk({
            to: 'Teams',
            as: 'team',
            relatedName: 'groups',
        }),
    };

    static reducer(action: GroupAction, Groups: ModelType<GroupsModel>) {
        Groups.upsert(action.group);
    }
}

export default GroupsModel;
```

results in 
```
Argument of type 'GroupProperties' is not assignable to parameter of type 'BlueprintProps<GroupsModel, "id", "team" | "name" | "team_id">'.
  Type 'GroupProperties' is not assignable to type '{ readonly team?: undefined; readonly name?: string | undefined; readonly team_id?: string | undefined; }'.
    Types of property 'team' are incompatible.
      Type 'TeamsModel | undefined' is not assignable to type 'undefined'.
        Type 'TeamsModel' is not assignable to type 'undefined'.ts(2345)
```

In your tests, you have payload replicating the interface of the Fields rather than actually being the fields. Is this the only solution? I ask as I work with the Properties (or Fields in your tests) a lot in code, sometimes passing them through multiple sagas before they update the store. In many cases, I'll do something like `Groups.withId(action.id).update(action.group)` where `action.group` is a `Partial<GroupProperties>`.

```
interface CreateBookAction {
    type: 'CREATE_BOOK';
    // payload here replicates BookFields rather than just specifying BookFields
    payload: { coverArt?: string; title: string; publisher: number; authors?: string[] };
}
```

**Comment by tomasz-zablocki** [comment]
> Oohh, that's way easier to use. It looks like refs handle `fk` properties by treating it as a string instead of a SessionBoundModel as well. I did notice that because it allows properties that aren't defined in the interface, the compiler won't yell at an upsert where name is misspelled as nmae.

Extra properties on `create`, `upsert` and `update` are allowed since that's how `redux-orm` works. The extra properties will be persisted into the store, and they can be read back. It's not recommended though, because the additional properties would have their get/set access functions redefined on `Model` interactions. 

Additional properties are persisted in the store like `attr` fields - directly as state properties, so their values are restricted to primitives, plain objects or arrays of primitives and plain objects. Typings restrict additional property values accordingly, therefore passing `nmae` next to `name` is valid, but passing `{name: true}` is not (known properties have their types checked). Any extra properties passed to `create` are intersected with the `Model` returned from the call (compiler is aware of their presence on the returned value).

> I'm closing the issue, but if I may ask, I'd like to confirm 3 things:
> 
> 1. I do have to define the relationships in my interfaces, correct? For instance, I noticed in the tests that `BookFields` has a `publisher` in the interface.

 **yes**

Several mapped types work based on assumption that the `static fields` content is properly reflected by related fields interface. Skipping particular properties is something I hadn't thought about and such case had never been tested. Although it's possible that everything still works this way.

> 2. Do those defined relationships need to be nullable / possibly undefined? `PublisherFields` in the tests has `books` possibly being undefined for instance, but other tests do not.

They can be optional or not, depending on a case/requirement 

Typings should respect `?` modifiers and project them onto parameters of  `create`, `upsert`, `update` and retrieved `Model` instances. 

However, there are additional cases where parameter properties may become optional, majority covered by [this test].(https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d8907f303d75056e0710a72bad713179fbc78240/types/redux-orm/redux-orm-tests.ts#L129). 

A property is optional when:

* it is an entity identifier (`id` by default) and it's a `number` - because Redux-ORM generates sequential ids
* it has `?` modifier.
* it's a `many` field (`MutableQuerySet` in the fields interface) - because Redux-ORM falls back to an empty array by default
* it's an `attr` field initialized with a non-empty `{getDefault: ()=> ....}`.

Personally, I'm marking `many`/`MutableQuerySet` fields with `?` for clarity.

There are fields that are always mandatory:
* entity identifier in `upsert`
* `string` identifier proprerty in `create`
* `attr` fields initialized without `getDefault` property, not marked with `?`.

> 3. In terms of best practices, should the codebase refer to the models using the interface type, or SessionBoundModel types / Ref SessionBoundModel types, or something else entirely? For instance
> 
> ```
> // option A
> function processGroup(group: GroupProperties) {}
> 
> // option B
> function processGroup(group: SessionBoundModel<GroupsModel, {}>) {}
> ```

As a rule of a thumb I'd use the simplest type (`GroupProperties` in this case) as long as it's sufficient. It  should also conform to restrictions on types imposed by `redux-orm` / `redux`. 

The typings for upcoming redux-orm release are going to be more user friendly in this regard. `SessionBoundModel` is removed and since they are based on declaration merging, there's only one type per entity/Model being used in the client code.

**Comment by tomasz-zablocki** [comment]
> @tomasz-zablocki
> 
> Given an interface like so
> 
> ```
> export interface GroupProperties {
>     readonly id: string;
>     readonly name: string;
>     readonly team_id: string;
> 
>     readonly team?: TeamsModel;
> }
> ```
> 
> if I send an action with this interface
> 
> ```
> export interface GroupAction {
>     type: typeof GROUP_TEST_ACTION;
>     readonly group: GroupProperties;
> }
> ```
> 
> then the following attempt to upsert, in both 0.13.4 and 0.13.5
> 
> ```
> class GroupsModel extends Model<typeof GroupsModel, GroupProperties> {
> 
>     static modelName = 'Groups' as const;
> 
>     static fields = {
>         name: attr(),
>         team_id: fk({
>             to: 'Teams',
>             as: 'team',
>             relatedName: 'groups',
>         }),
>     };
> 
>     static reducer(action: GroupAction, Groups: ModelType<GroupsModel>) {
>         Groups.upsert(action.group);
>     }
> }
> 
> export default GroupsModel;
> ```
> 
> results in
> 
> ```
> Argument of type 'GroupProperties' is not assignable to parameter of type 'BlueprintProps<GroupsModel, "id", "team" | "name" | "team_id">'.
>   Type 'GroupProperties' is not assignable to type '{ readonly team?: undefined; readonly name?: string | undefined; readonly team_id?: string | undefined; }'.
>     Types of property 'team' are incompatible.
>       Type 'TeamsModel | undefined' is not assignable to type 'undefined'.
>         Type 'TeamsModel' is not assignable to type 'undefined'.ts(2345)
> ```

This doesn't work because of this part: 

> ```
>   //...
>   team_id: fk({
>             to: 'Teams',
>             as: 'team',
>             relatedName: 'groups',
>         }),
> ```

Specifically `as` option not being implemented by typings. I know this qualifies as a bug, but I don't think I'll add `as` support to `0.13.X`. It became increasingly difficult to improve this version without either introducing breaking changes or loosing parts of functionality. I'll certainly prioritize it for the next release though.

> In your tests, you have payload replicating the interface of the Fields rather than actually being the fields. Is this the only solution?
> 
> I ask as I work with the Properties (or Fields in your tests) a lot in code, sometimes passing them through multiple sagas before they update the store. In many cases, I'll do something like `Groups.withId(action.id).update(action.group)` where `action.group` is a `Partial<GroupProperties>`.
> 
> I suppose it's possible I could define `GroupFields` to just be the fields, have `GroupProperties` extend `GroupFields` and add relationship data, and then have all actions that update the store use `GroupFields.`
> 
> ```
> interface CreateBookAction {
>     type: 'CREATE_BOOK';
>     // payload here replicates BookFields rather than just specifying BookFields
>     payload: { coverArt?: string; title: string; publisher: number; authors?: string[] };
> }
> ```

I'm almost sure that when you have `GroupAction` that depends on `GroupProperties`, `GroupProperties` are a type param of `GroupModel` and `GroupAction` is an argument of `GroupModel`'s static method, you end up with an infinitely recursive definition cycle. This is the reason behind additional type, but your approach seems reasonable and solid.

It's hard to figure out the general context from the attached snippets, but if it's a React application you're developing, then make sure your components are not aware/dependent on `Model` classes. You should not expose `Model` instances to your components, instead their state should be populated using selectors or/and `Model` `ref`s.

**Comment by JonnyLinja** [comment]
Gotcha. I went with the GroupFields and GroupProperties approach, where all the `as` relationships are defined in Properties. I found that I had to make `as` relationships SessionBoundModels in order to access properties a few relationships in.

And thanks for the tips on exposing models! I've been having my components interact with viewmodels generated by memoized selectors, so they shouldn't be dependent on them.

Thanks again!
