### ISSUE TITLE
[@types/mongoose] validateSync allows `undefined` as return value.

### ISSUE THREAD

**Issue by helt** [DefinitelyTyped/DefinitelyTyped#38134]
According to 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/31929c09c7b4490f87766206b412da4a6a581dc3/types/mongoose/index.d.ts#L1395

this line
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/31929c09c7b4490f87766206b412da4a6a581dc3/types/mongoose/index.d.ts#L1397

should be

```
    validateSync(pathsToValidate?: string | string[]): Error.ValidationError | undefined;
```

?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
