### ISSUE TITLE
How to call other than get and set in redis cluster?

### ISSUE THREAD

**Issue by nadjin** [DefinitelyTyped/DefinitelyTyped#38177]
```
// redis cluster
const nodes = [{host: config.redisHost, port: config.redisPort}];
const pub = new Redis.Cluster(nodes);
const sub = new Redis.Cluster(nodes);
const redis = new Redis.Cluster(nodes);

// error :TS2551: Property 'hset' does not exist on type 'Cluster'. Did you mean 'set'?
await redis.hset('test_2', 'ok', 1);
```

When I try to connect directly to the cluster node with Redis

```
const nodes = [{host: config.redisHost, port: config.redisPort}];
const pub = new Redis.Cluster(nodes);
const sub = new Redis.Cluster(nodes);
// const redis = new Redis.Cluster(nodes);
const redis = new Redis(config.redisPort, config.redisHost);
```

error:

`(node:37468) UnhandledPromiseRejectionWarning: ReplyError: MOVED 11335 127.0.0.1:7301
    at parseError (D:\ws_workspace\contact\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (D:\ws_workspace\contact\node_modules\redis-parser\lib\parser.js:302:14)
(node:37468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:37468) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Q：
I looked at the code and the methods are all under the Redis class. How do I call these methods when I connect to the Redis cluster? 

Thank you! (●'◡'●)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
