### ISSUE TITLE
[@types/react] HTMLAttributes['defaultValue'] has different type than `value`

### ISSUE THREAD

**Issue by hsz** [DefinitelyTyped/DefinitelyTyped#38172]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon

In `HTMLAttributes` interface there is a `defaultValue` property which accepts `string | string[]`.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d8907f303d75056e0710a72bad713179fbc78240/types/react/index.d.ts#L1631

Meanwhile `value` property from every other interface (i.e. `AllHTMLAttributes`) defines it as `string | string[] | number`.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d8907f303d75056e0710a72bad713179fbc78240/types/react/index.d.ts#L1789

Shouldn't `defaultValue` be extended with `number` as well?

**Comment by eps1lon** [comment]
Typings of values for input-like elements is a frequent issue we have in Material-UI as well. 

IMO we should never allow anything other than `string` because that is the type you will get from the `value` property and attribute. If you provide any other value then react will coerce the value into a string. TypeScript already rejects weak typing for the `+` operator i.e. `1 + '2'` is rejected while `'1' + '2'` is ok. I do think we should apply the same to DOM bindings.

What might make more sense is to allow types that can also be returned from an `HTMLInputElement`. This would mean `string | number | Date` (`value`, `valueAsNumber` and `valueAsDate` respectively). 

Other than that we might as well allow `unknown` since react will stringify the values before anyway (`'' + value`).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
