### ISSUE TITLE
Upgrade @types/tedious to fix bulk-insert issue

### ISSUE THREAD

**Issue by sarahCheikhali** [DefinitelyTyped/DefinitelyTyped#38183]
If you know how to fix the issue, make a pull request instead.

- [ Y ] I tried using the `@types/tedious` package and had problems.
- [ Y ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ Y ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  
A bulk-insert issue was fixed in an upper version of tedious (cf. [https://github.com/tediousjs/tedious/issues/589](url)). Could you please upgrade @types/tedious version to match the latest version of tedious ^6.3.0 ?
- [ Y ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rogierschouten @cjthompson @v-suhame @guiampm @csharpsi

If you do not mention the authors the issue will be ignored.

**Comment by rogierschouten** [comment]
@sarahCheikhali please send a PR, DefinitelyTyped is a purely collaborative effort.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
