### ISSUE TITLE
Upgrading to 7.6.1?

### ISSUE THREAD

**Issue by bentedder** [DefinitelyTyped/DefinitelyTyped#38191]
In reference to https://github.com/babel/babel/issues/10403, it seems this may need to be bumped to 7.6.1 to avoid: 

`node_modules/@types/babel__generator/node_modules/@babel/types/lib/index.d.ts
(2098,30): JSDoc types can only be used inside documentation comments.`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/156a7ab7e1becd2df58b4ec4302fa5f8d9c44dd7/types/babel__generator/package.json#L4

**Comment by bonebizz21** [comment]
That's cool

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
