### ISSUE TITLE
[events] Please consider adding <EventMap> for EventEmitter

### ISSUE THREAD

**Issue by patarapolw** [DefinitelyTyped/DefinitelyTyped#38208]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/events` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @yasupeke @weareoutman

---

As not only that I am trying to create typing for [async-eventemitter](https://www.npmjs.com/package/async-eventemitter) https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38203, but also that there are many versions of `EventEmitter<EventMap>`,

- https://github.com/Morglod/tsee
- https://github.com/andywer/typed-emitter

If this is implemented, I would [reference](https://github.com/patarapolw/DefinitelyTyped/blob/5f25a96dd559c2e637b43c70947b9155566299f5/types/async-eventemitter/index.d.ts#L21) this typing in `async-eventemitter` as well.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
