### ISSUE TITLE
Are you going to support amplitude-js version 5+?

### ISSUE THREAD

**Issue by topikus** [DefinitelyTyped/DefinitelyTyped#38233]
With amplitude-js version 5+ I have an error
`"export 'getInstance' (imported as 'amplitude') was not found in 'amplitude-js'
ERROR in ./node_modules/amplitude-js/amplitude.esm.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/defineProperty'`

**Comment by Bo-Carlsson** [comment]
Try changing the way you import Amplitude from:

`import * as amplitude from "amplitude-js";`

to

`import amplitude from "amplitude-js";`

**Comment by topikus** [comment]
> Try changing the way you import Amplitude from:
> 
> `import * as amplitude from "amplitude-js";`
> 
> to
> 
> `import amplitude from "amplitude-js";`

node_modules/@types/amplitude-js/index"' has no default export.

**Comment by Bo-Carlsson** [comment]
I'm only depending on amplitude-js:

`"dependencies": {
    "amplitude-js": "5.3.1" }`

`node_modules/amplitude-js/amplitude.esm.js` has a default export

**Comment by topikus** [comment]
Thanks for advice, in that case it`s works good. But I whant to use types :)

**Comment by wibblymat** [comment]
This worked fine in 5.2.2, and has broken with 5.3.0. Looking at https://github.com/amplitude/Amplitude-JavaScript/blob/master/CHANGELOG.md you can see that they started shipping an ES module version, and this version exports an instance of a class Amplitude rather than just exporting a bunch of functions. Hence the mismatch between Babel and TS.

Options are:
1. Somehow force the non-ESM version to be loaded
2. Write your own type definitions for the new version
3. Put up with the type error until it's fixed by someone else
4. Stop getting types for Amplitude.

I guess 1 would be best but I don't think it's actually possible. I haven't decided which of 2 - 4 I can get away with doing :/
