### ISSUE TITLE
How to assert type check to fail in tests?

### ISSUE THREAD

**Issue by vicrac** [DefinitelyTyped/DefinitelyTyped#38239]
Perhaps it's duplicated, if it's the case, please redirect me, but how can I make a test that verifies that some piece of invalid code gets rejected by type checker?

Authors: @andy-ms

**Comment by IllusionMH** [comment]
You can use `// $ExpectError`
See https://github.com/DefinitelyTyped/DefinitelyTyped#linter and details in https://github.com/Microsoft/dtslint#write-tests repo

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
