### ISSUE TITLE
[@types/node] Improper Buffer.from types

### ISSUE THREAD

**Issue by fabiospampinato** [DefinitelyTyped/DefinitelyTyped#38272]
Authors: @jkomyno @a-tarasyuk @alvis @r3nya @btoueg @BrunoScheufler @smac89 @tellnes @Touffy @DeividasBakanas @eyqs @Flarna @Hannes-Magnusson-CK @KSXGitHub @hoo29 @kjin @ajafff @islishude @mwiktorczyk @matthieusieben @mohsen1 @n-e @octo-sniffle @parambirs @eps1lon @SimonSchick @ThomasdenH @WilcoBakker @wwwy3y3 @ZaneHannanAU @samuela @kuehlein @j-oliveras @bhongy @chyzwar

In the following snippet of code I don't get any errors inside `example1`, but I get an error inside `example2`, while the two are effectively doin the same thing. Therefor I think the types of `Buffer.from` should be improved to take into account this scenario.

```ts
function example1 ( source: ArrayBuffer | string ) {
  if ( typeof source === 'string' ) {
    Buffer.from ( source );
  } else {
    Buffer.from ( source );
  }

function example2 ( source: ArrayBuffer | string ) {
  Buffer.from ( source );
}
```

**Comment by SimonSchick** [comment]
This seems very specific and if anything should be raised with the TypeScript folks directly as this is a language limitation.

I don't believe we should be adding additional overloads to cover this specific scenario as we would have to add a bunch of type union overloads that ultimately _reduce_ type safety.

**Comment by fabiospampinato** [comment]
Are you sure `Buffer.from` can't be typed correctly (as of right now the error message is just wrong) without making the system less strict in other places? 🤔 

Could you perhaps post here the snippet of code you have in mind that would reduce type safety so that I can understand your point better?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
