### ISSUE TITLE
call ej.web.all build error:"Cannot find name ej"

### ISSUE THREAD

**Issue by malaoko** [DefinitelyTyped/DefinitelyTyped#38289]
I Use ej.web.all by Angular 7，but result is:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/32593645/64674741-0f6c6d80-d4a4-11e9-88ae-a804e7e7c6e8.png">

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
