### ISSUE TITLE
Leaflet.js types totally outdated for version 1.5.1

### ISSUE THREAD

**Issue by homer-jay** [DefinitelyTyped/DefinitelyTyped#38295]
## Description
I tried using the last version of `@types/leaflet` and found the following problems:
*  Property 'attributionControl' does not exist on type 'Map'
*  Property 'latlng' does not exist on type 'LeafletEvent'
*  Issues with L.polygon: Type 'number[]' is not assignable to type 'LatLngExpression[][]'.
*  'maximunAge' does not exist in type 'LocateOptions'

Clearly some of the types are outdated and do not match the current JS API.

##Authors: 
@alejo90
@atd-schubert
@mcauer
@ronikar
@sanfrisc
@life777

**Comment by life777** [comment]
Hi, @homer-jay 
Thanks. 

1) I couldn't find 'attributionControl' property in [Map class](https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js)
This property can be found in [MapOptions interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet/index.d.ts#L1016)

2)  LeafletEvent is a parent class interface. It's extended by different event Interfaces. Some of them don't have 'latlng' property. Example: LeafletMouseEvent has latlng property, but LeafletKeyboardEvent doesn't have it because there is no need for it.
![Screenshot from 2019-09-11 15-31-32](https://user-images.githubusercontent.com/891497/64728755-b56ea680-d4a9-11e9-8e2e-288e7b928ff9.png)

3) L.polygon accepts `latlngs: LatLngExpression[] | LatLngExpression[][] | LatLngExpression[][][]` as first parameter.
`LatLngExpression` is `LatLng | LatLngLiteral | LatLngTuple`.
It means that L.polygon accepts either `[number, number][]` or { lat: number; lng: number }[] or LatLng[]
Neither of these types is compatible with number[]. 

4) As far as I can see it's there: [link to type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet/index.d.ts#L1263)
![Screenshot from 2019-09-11 15-43-14](https://user-images.githubusercontent.com/891497/64729334-fa470d00-d4aa-11e9-9de7-ed315576a18d.png)

**Comment by homer-jay** [comment]
@life777 

1. True. Apparently it also exists in the map object. I found it in a snippet when searching for ways to remove the "Leaflet" prefix in the attribution. Examples can be found [here](https://github.com/angular-ui/ui-leaflet/issues/110#issuecomment-189914020) and [here](https://gis.stackexchange.com/questions/289527/leaflet-change-attribution-prefix-on-baselayer-change/289533#289533), although they might be outdated. I agree with you on this one, if it is not in the contract it shouldn't appear in the types.

2. I got this error in [LocationEvent](https://leafletjs.com/reference-1.5.0.html#locationevent). The snippet was something like this:
```
this.map.on('locationfound', e => { });
```
I found it in the second official tutorial [Leaflet on mobile: Geolocation](https://leafletjs.com/examples/mobile/)

3. I got that error while trying something like this:
```
export class MyCoords {
	lati: number;
	longi: number;
}

fetchMyCoords(): Promise<MyCoords[][]>{
	//returns array of arrays of 4 MyCoords each
}

this.fetchMyCoords()
.then(arrayOfArraysOfMyCoords => { 

	const polygons = arrayOfArraysOfMyCoords.map(myCoordsArray => 
		L.polygon(
			myCoordsArray.map(mc => [mc.lati, mc.longi]),
			{stroke: true}
		)
	);
});

```

4. Got it in a line like this:
```
this.map.locate({watch: false, setView: false, timeout: 60000, maximunAge: 60000, enableHighAccuracy: false});
```

**Comment by life777** [comment]
@homer-jay 

1) I'm afraid but I can't add this property to Map class because it is't included in documentation. It means that it might be a private property and can be removed in next release. I'm sorry.

2) In this snippet `e` is a Event (parent class) that doesn't have `latLng` property. To fix it you need to cast `e` to one of the child classes:
```ts
map.on('locationfound', e => console.log((e as LocationEvent).latlng));
``` 
This issue probably can be fixed by matching event classes with event names. Right now there is only one possible event handler in `on` method:

```ts
type LeafletEventHandlerFn = (event: LeafletEvent) => void
```

3) Your code looks right. I tried it by myself and didn't see any warning:
![Screenshot from 2019-09-30 17-59-33](https://user-images.githubusercontent.com/891497/65920137-32f04d00-e3ac-11e9-871d-0fa77296ddf3.png)
 
4) You misspelt this property name. In your code it's `maximunAge`, actual property name is `maximumAge`.
