### ISSUE TITLE
license of Type definitions for Vortex Web 1.2

### ISSUE THREAD

**Issue by luisapace** [DefinitelyTyped/DefinitelyTyped#38296]
Hi, my team would use DefinitelyTyped and to approve that I've to verify that all its licenses are acceptable.

Now I've seen that index.d.ts in the vortex-web-client type contains this header:

_**// Type definitions for Vortex Web 1.2
// Project: http://www.prismtech.com/vortex/vortex-web
// Definitions by: Stefan Profanter <https://github.com/Pro>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/*
 Vortex Web

 This software and documentation are Copyright 2010 to 2015 PrismTech
 Limited and its licensees. All rights reserved. See file:

 docs/LICENSE.html

 for full copyright notice and license terms.**_

But I cannot see any docs/LICENSE.html file in the DefinitelyTyped package; could you please tell me where is it?

Thanks for your help.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
