### ISSUE TITLE
react-calendar-timeline types are out of date

### ISSUE THREAD

**Issue by Intruder0404** [DefinitelyTyped/DefinitelyTyped#38302]
Hi, 

I have been talking with a developper of react-calendar-timeline because it wasnt working properly in typescript. We figured that the types are out of date.

He asked me to open an issue concerning it and tag him in.

Thanks

@Ilaiwi

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
