### ISSUE TITLE
figlet types are missing "parseFont" method

### ISSUE THREAD

**Issue by patorjk** [DefinitelyTyped/DefinitelyTyped#38318]
I maintain the figlet repo. A user (@andytan0727) put in an issue (https://github.com/patorjk/figlet.js/issues/50#issuecomment-530644305) mentioning that the parseFont method is missing from the index.d.ts file:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/figlet/index.d.ts

I am not that familiar with TypeScript, so I don't want to put in a PR, but I believe this is what would need to be added: (inside of the figlet namespace)

`function parseFont(fontName: string, data: string): FontOptions;`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
