### ISSUE TITLE
React.ComponentType definition  bug

### ISSUE THREAD

**Issue by gogoyqj** [DefinitelyTyped/DefinitelyTyped#38320]
why React.ComponentType's definition is:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5a510408049f8b7a9a2d81ed24c5f2c3f18558a0/types/react/index.d.ts#L71

not:

```ts
type ComponentType<P extends {}> = ComponentClass<P> | FunctionComponent<P>; 
```
?

because in current definition causes some problems:
```ts
export const Cmp = (props: {}) => null;
```
is compatible with
```ts
React.ComponentType<{ status: number }>
```

it's definitely wrong

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
