### ISSUE TITLE
TS2339: Property 'mv' does not exist on type 'UploadedFile | UploadedFile[]'.

### ISSUE THREAD

**Issue by ThBM** [DefinitelyTyped/DefinitelyTyped#38334]
Hello,

- [ X ] I tried using the `@types/express-fileupload` package and had problems.
  - Authors: @silkimen , @vosatom 

I'm using this piece of code and it seems like I cannot use method mv on testingSheet which is supposed to be an UploadedFile.

```
 async updateTestingSheet(request: Request, response: Response) {
    if(request.files === undefined || request.files.testingSheet === undefined) return response.status(400).send("testingSheet is required as form file input.");

    const testingSheet = request.files.testingSheet;

    await testingSheet.mv(path.join(__dirname, "..", "..", "uploads", "test.xlsx"));
    
    return response.send("ok");
  }
```

**Comment by jaymehtasa** [comment]
Also facing the same issue while accessing `mimetype` or `size`;

![image](https://user-images.githubusercontent.com/8104992/68926554-d0aca980-07ab-11ea-8860-0a2042c4c84a.png)

**Comment by Divlo** [comment]
Same problem, someone found a workaround until there is a fix ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
