### ISSUE TITLE
there is not exist jquery-backstretch plugin definitelyTyped

### ISSUE THREAD

**Issue by sargin48** [DefinitelyTyped/DefinitelyTyped#3835]
please support this plugin definitely Typed file

jquery-backstretch  
https://github.com/srobbin/jquery-backstretch

**Comment by sargin48** [comment]
i wrote it :)

///<reference path="../jquery/jquery.d.ts" />

interface JQBackstretchOptions {
    centeredX?: boolean;
    centeredY?: boolean;
}

interface JQBackstretchStatic {
    defaults?: JQBackstretchOptions;
    (option: JQBackstretchOptions): void;
    (images : any, option : JQBackstretchOptions) : void;
}

interface JQueryStatic {
    backstretch?: JQBackstretchStatic;
}

interface JQuery {
    backstretch(option?: JQBackstretchOptions): JQuery;
    backstretch(images : any, option?: JQBackstretchOptions): JQuery;
}

**Comment by vvakame** [comment]
@sargin48 please send a PR. I'll review it.

**Comment by sargin48** [comment]
///<reference path="../jquery/jquery.d.ts" />

interface JQBackstretchOptions {
    centeredX?: boolean;
    centeredY?: boolean;
}

interface JQBackstretchStatic {
    defaults?: JQBackstretchOptions;
    (option: JQBackstretchOptions): void;
    (images : any, option : JQBackstretchOptions) : void;
}

interface JQueryStatic {
    backstretch?: JQBackstretchStatic;
}

interface JQuery {
    backstretch(option?: JQBackstretchOptions): JQuery;
    backstretch(images : any, option?: JQBackstretchOptions): JQuery;
}


![123](https://cloud.githubusercontent.com/assets/3220540/6598749/6ee674c4-c80e-11e4-926e-d262eb737b3e.png)
![124](https://cloud.githubusercontent.com/assets/3220540/6598751/71f3a77c-c80e-11e4-9139-0c9f02d84dda.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
