### ISSUE TITLE
@types/testing-library__cypress: v5 find* API not included in types

### ISSUE THREAD

**Issue by jrnail23** [DefinitelyTyped/DefinitelyTyped#38365]
- Authors: @sebinsua

https://github.com/testing-library/cypress-testing-library/issues/84

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
