### ISSUE TITLE
[@types/express] Overriding send

### ISSUE THREAD

**Issue by AhmedBHameed** [DefinitelyTyped/DefinitelyTyped#38391]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/express` package and had problems.

Hello, I'm currently using @types/express typescript backend application. I noticed something strange that would make me think if that is an issue with the types implementation maybe but better to ask and explain first.

What i want to do is to monitor my send payload by overriding the method as the code follow

**This is the working code but `_with_` error**

```ts
export const payloadJournalist = function() {
  return function(req: Request, res: Response, next: NextFunction) {
    const send = res.send;
    res.send = function(body) { // Error under "res.send" in this line.
      console.log(body);
      send.call(this, body);
    };
    next();
  };
};
```

When hover over it, the error come
```txt
Type '(body: any) => void' is not assignable to type 'Send'.
  Type 'void' is not assignable to type 'Response'. ts(2322)
```

If i want to fix the error according to typescript implementation, i should return a function of type `Send` as the code bellow, but note that the code bellow causing an issue blocking next middleware from executing:

```ts
export const payloadJournalist = function() {
  return function(req: Request, res: Response, next: NextFunction) {
    const send = res.send;
    res.send = function(body) {
      const sendMethod = send.bind(this, body); // I replaced call with bind in order to get a new function then return it.
      return sendMethod;
    };
    next();
  };
};
```

I'm using:

**@types/express**: "^4.17.0",
**express**: "^4.17.1",
**Node version**: v11.10.1

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
