### ISSUE TITLE
[@types/node] querystring.stringify – possible regression

### ISSUE THREAD

**Issue by whatisaphone** [DefinitelyTyped/DefinitelyTyped#38414]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:
@microsoft
@jkomyno
@alvis
@BrunoScheufler
@OliverJAsh 

---

I think there's been a regression in the types for `querystring.stringify`. Consider this code, which strictly types the parameters to an API:

```ts
interface FooParams {
  readonly bar: string;
}

const params: FooParams = { bar: 'abc' };

fetch('https://example.com/foo?' + querystring.stringify(params));
```

Under old versions of @types/node, this worked. But now it no longer does.

Looks like the change was introduced in #33997. To be honest, I can't understand the rationale of that PR. The test doesn't seem realistic to me. What actual buggy code is it trying to prevent?

**Comment by OliverJAsh** [comment]
`interface`s don't have index signatures (because they are open to extension), but `type` aliases do. See https://github.com/Microsoft/TypeScript/issues/15300.

Can you use `type` instead?

```ts
import * as querystring from 'querystring';

type FooParams = {
    readonly bar: string;
}

const params: FooParams = { bar: 'abc' };

fetch('https://example.com/foo?' + querystring.stringify(params));
```

**Comment by whatisaphone** [comment]
Interesting, I wouldn't have thought there was a difference. Though it still seems like a regression to me, since my example is correctly-typed, yet it's now being rejected.

And using an interface seems to go against common typescript conventions:

- [The language spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#310-type-aliases)

  >Interface types have many similarities to type aliases for object type literals, but since interface types offer more capabilities they are generally preferred to type aliases.

- TSLint rule [interface-over-type-literal](https://palantir.github.io/tslint/rules/interface-over-type-literal/)

- @typescript-eslint/consistent-type-definitions [defaults to preferring `interface`](https://github.com/typescript-eslint/typescript-eslint/blob/c3c8b8643553057398395df73c9d43757b576f11/packages/eslint-plugin/src/rules/consistent-type-definitions.ts#L26).

Although perhaps the issue you linked means the convention is wrong, and we should all be using `type` instead?

Maybe someone ambitious could add a test for calling `stringify` with a type alias, so that doesn't also become invalid one day.

I don't have much time to engage here or champion a change that wouldn't be considered a straightforward bugfix. As long as some workaround exists, I'll live with it and move on happily with my life.

**Comment by OliverJAsh** [comment]
> To be honest, I can't understand the rationale of that PR.

I improved my comment explaining the reason for this change: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33997/files#r266856234

This is about protecting usages of `ParsedUrlQueryInput` when it's used _outside_ of `querystring.stringify` or `url.format`, which may happen because anyone can import/use the type—it's not private.

> it still seems like a regression to me, since my example is correctly-typed, yet it's now being rejected

BTW, here's another solution: add an explicit index signature to your interface.

``` ts
interface FooParams extends querystring.ParsedUrlQueryInput {
    readonly bar: string;
}
```

> interface types offer more capabilities 

I'm not sure that's completely true:

> Interfaces may only be used to declare object types.

– https://microsoft.github.io/TypeScript-New-Handbook/everything/#interface-vs-alias

> Although perhaps the issue you linked means the convention is wrong, and we should all be using type instead?

I'm inclined to think so. I personally use `type` almost everywhere, mainly because they can be used to define types of all sorts, not just objects. The only downside I've found is that TS doesn't always preserve the names of `type` aliases like it does for `interface`s, but [I consider that more as a bug](https://github.com/microsoft/TypeScript/issues/32287) which I hope will be fixed soon.

**Comment by whatisaphone** [comment]
>I improved my comment explaining

Ah okay, I think I get it. You want to treat `ParsedUrlQueryInput` as a sort of black hole, where you can put values in, but not get them back out, except by passing to `stringify`? That seems sane to me; the `interface` issue is just an unfortunate side-effect.

>BTW, here's another solution

That looks a lot better to me, thanks for sharing! It's even self-documenting in a way. I can live with that.

**Comment by claudekennilol** [comment]
so if I've got this
```
export class Request {
    constructor(
        public foo: number,
        public bar: number,
        public fooz: string,
        public baz: string
    ) { }
}
...
        const request = new Request(1, 2, 'three', 'four');
        const params = querystring.stringify(request);
        return this.http.get<any[]>(`${ this.route }?${ params }`).pipe(...do stuff...);
```

It runs just fine, but TypeScript complains about it
 error TS2345: Argument of type 'Request' is not assignable to parameter of type 'ParsedUrlQueryInput'.
  Index signature is missing in type 'Request'.

What's the correct way to do this?

**Comment by shamilovtim** [comment]
we shouldn't have to declare an interface just to use a simple method on an object of a library. why not just set the required type of 'any' because we truly can pass any object, array or primitive into this method? this typing is straight up incorrect.

**Comment by OliverJAsh** [comment]
> we shouldn't have to declare an interface just to use a simple method on an object of a library.

You don't have to declare an interface/type:

```ts
import * as querystring from 'querystring';

fetch('https://example.com/foo?' + querystring.stringify({ bar: 'abc' }));
```

> why not just set the required type of 'any' because we truly can pass any object, array or primitive into this method? this typing is straight up incorrect.

See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/38414#issuecomment-532604550.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
