### ISSUE TITLE
HTTPS by default for the website

### ISSUE THREAD

**Issue by lgarron** [DefinitelyTyped/DefinitelyTyped#38448]
https://definitelytyped.org is serving a valid cert.

In order of value, it would be useful to:

- [ ] Redirect from HTTP to HTTPS on the site: https://help.github.com/en/articles/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site
- [ ] Change the repo URL at the top of https://github.com/DefinitelyTyped/DefinitelyTyped to the HTTPS version.
- [ ] Preload HSTS https://hstspreload.org/ (I work on security at GitHub, so I can enable HSTS for your GH Pages site if you'd like.)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
