### ISSUE TITLE
[@types/web3] BlockHeader.receiptRoot and BlockHeader.transactionRoot are misspelled

### ISSUE THREAD

**Issue by lorenzb** [DefinitelyTyped/DefinitelyTyped#38485]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/web3` package and had problems.
- Authors: @simon-jentzsch @nitzantomer @zurbo @yxliang01 @phra @naddison36 @icaroharry @linusnorton @jpeletier @anneau @matrushka @andrevmatos @levino @zlumer @archangel-irk @sogasg @donamk @dkent600 @nerddan @alexkvak

According to https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash, the correct field names should be the pluralized "receipt**s**Root" and "transaction**s**Root", not "receiptRoot" and "transactionRoot".

See also the following sample snippet:
```typescript
let web3 = new Web3("https://mainnet.infura.io/v3/[REDACTED API KEY]")
let block = await web3.eth.getBlock(6000000);
console.log("transactionRoot", block.transactionRoot);
console.log("transactionsRoot", (block as any).transactionsRoot);
console.log("receiptRoot", block.receiptRoot);
console.log("receiptsRoot", (block as any).receiptsRoot);
```
which produces
```
transactionRoot undefined
transactionsRoot 0x50115fbf29591a3505eabfac5c5a6a8585e1d1c064a04348f00af02ddf79b58e
receiptRoot undefined
receiptsRoot 0xd7adcb6c39b2aa65a8aa739e8638bdde4b3e01cd0ff1d0024fdca745ba3e6ea5
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
