### ISSUE TITLE
forge-viewer: Viewer3D.container should be HTMLElement instead of Element

### ISSUE THREAD

**Issue by tobiasweibel** [DefinitelyTyped/DefinitelyTyped#38498]
Viewer3D.container should be HTMLElement instead of Element. I could create a PR but I guess other Elements of forge-viewer should be changed to HTMLElement as well.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/de12907d79777d50ce08036827da7425853abefd/types/forge-viewer/index.d.ts#L648

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by tobiasweibel** [comment]
Fixed in #52725.
