### ISSUE TITLE
[@type/react-infinite-calendar] locale.locale is not included

### ISSUE THREAD

**Issue by qkreltms** [DefinitelyTyped/DefinitelyTyped#38528]
It is related with issue ```locale not apply #220``` (https://github.com/clauderic/react-infinite-calendar/issues/220)

I'm using Typescript with React and I tried 

datePicker.tsx
```js
     import ko from "date-fns/locale/ko";
 //...
<InfiniteCalendar
          locale={{
            locale: ko,
            headerFormat: "YYYY MM DD",
            weekdays: ["월", "화", "수", "목", "금", "토", "일"],
            blank: "날짜를 선택하세요.",
            todayLabel: {
              long: "오늘"
            }
          }}
/>
```

index.d.ts
```diff
    locale?: {
+       locale?: any;
        blank?: string;
        headerFormat?: string;
        todayLabel?: {
            long: string;
        };
        weekdays?: string[];
        weekStartsOn?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
    };
```

It seems ```locale.locale``` is not included in index.d.ts

- [x] I tried using the `@types/react-infinite-calendar` package and had problems.
- [x] I tried using the latest stable version of @types/react-infinite-calendar": "^2.3.3
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @christianchown

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
