### ISSUE TITLE
twilio video types are incorrect.

### ISSUE THREAD

**Issue by ben8p** [DefinitelyTyped/DefinitelyTyped#38537]
Current is:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b5dcab92788e09fa1462cedcff4ae303b5f88d16/types/twilio-video/index.d.ts#L479
but it should be `maxAudioBitrate` (lower case `R`), and `maxVideoBitrate` (lower case `R`).

Also `region` is missing. Maybe more are missing

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
