### ISSUE TITLE
@types/theme-ui missing export of css utility

### ISSUE THREAD

**Issue by jonavila** [DefinitelyTyped/DefinitelyTyped#38551]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/theme-ui` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @erikdstock, @ifiokjr, @sbardian 

Theme theme-ui API exposes a `css` utility that is not included in the types:
https://theme-ui.com/api#css

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
