### ISSUE TITLE
@types/react-transition-group: wrong type for `in`

### ISSUE THREAD

**Issue by PerfectionVR** [DefinitelyTyped/DefinitelyTyped#38559]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/41fe335d209b4cd46dedafd1a91849d7fec6880d/types/react-transition-group/Transition.d.ts#L45

```
Warning: Received `true` for a non-boolean attribute `in`.

If you want to write it to the DOM, pass a string instead: in="true" or in={value.toString()}.
    in div (created by TransitionGroup)
    in TransitionGroup (created by Gallery)
    in SwitchTransition (created by Gallery)
    in div (created by Gallery)
```
```
<SwitchTransition mode="in-out">
        <TransitionGroup key={`gallery_container`}>
          <CSSTransition timeout={animationTime} classNames={`fade`} key={key}>
            <div
              className="gallery-image"
              data-key={key}
              style={{ backgroundImage: `url(${images[imageIndex].url}` }}></div>
          </CSSTransition>
        </TransitionGroup>
      </SwitchTransition>
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
