### ISSUE TITLE
dojo/dijit.d.ts is too big for WebStorm IDE

### ISSUE THREAD

**Issue by anatoliyarkhipov** [DefinitelyTyped/DefinitelyTyped#3861]
![nhxagpc](https://cloud.githubusercontent.com/assets/1934180/6639258/ec46cf20-c996-11e4-9473-1be330f9f51c.png)
![image](https://cloud.githubusercontent.com/assets/1934180/6639318/426cac80-c997-11e4-8254-814443d48e3c.png)

Maybe we can split it to multiple smaller parts? Or I missed something?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
