### ISSUE TITLE
tween.js is now known as @tweenjs/tween.js

### ISSUE THREAD

**Issue by joeflateau** [DefinitelyTyped/DefinitelyTyped#38679]
Definitions will need to be updated to match...

If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @evilangelist @jcyuan

If you do not mention the authors the issue will be ignored.

**Comment by jcyuan** [comment]
what can i do for you sir?

**Comment by joeflateau** [comment]
Just noting it as “an issue”. I don’t have the bandwidth to take it on at the moment. Someone at some point should migrate this to the new name

**Comment by jcyuan** [comment]
ah, sorry misunderstood your meaning last time. actually as you know there are huge number of tween libraries on github. the def name `tween.js` I believe was already taken a long time ago before `createjs` releasing their  product `tweenjs`.
so I think we can do nothing, 'cause the lib name can't be changed even official people.

**Comment by jcyuan** [comment]
npm install @types/tween.js  -> https://github.com/tweenjs/tween.js/
npm install @types/tweenjs   -> https://www.createjs.com/tweenjs

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
