### ISSUE TITLE
@types/aws-lambda shouldn't the APIGatewayEventRequestContext contain a headers property?

### ISSUE THREAD

**Issue by pringon** [DefinitelyTyped/DefinitelyTyped#38720]
- [x] I tried using the `@types/aws-lambda` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @pwmcintyre 

The event argument in a lambda provides the headers mapped in API Gateway and whitelisted on Cloudfront. Should an optional headers property be provided in the interface for `APIGatewayEventRequestContext`.

So far I have extended it with the extra property but it feels like I do it so often that adding it in the type declaration would make my projects cleaner. Should I just use `APIGatewayProxyEvent` instead?

**Comment by simonbuchan** [comment]
Going back through `aws-lambda` issues, since they seem to be being neglected.

`APIGatewayEventRequestContext` is a bit of an odd duck, since it's not really documented except by implication from the mapping template documentation.

Unfortunately, this is not reliable, and the actual received `event.requestContext` does not include the headers, in either the lambda proxy integration or the custom authorizer, from testing.

If you're trying to use the `APIGatewayEventRequestContext` with cloudfront because you're using API gateway as an origin, I'm not sure what the effect is, I would expect it to simply change the set of headers that API gateway receives, but not what's in the request context - AWS has done weirder things though.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
