### ISSUE TITLE
[gapi.client.gmail] Namespace 'gapi.client' has no exported member 'gmail'

### ISSUE THREAD

**Issue by justinfagnani** [DefinitelyTyped/DefinitelyTyped#38747]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Bolisov

I'm trying to use the gapi.client.gmail types, but for some reason tsc 3.6.3 can't find the `gapi.client.gmail` namespace:

> Namespace 'gapi.client' has no exported member 'gmail'. ts(2694)

When I jump to definition on `gapi.client` I am taken to `@types/gapi.client.gmail/index.d.ts` and can see the nested namespace for `gmail`, so I'm unsure what the issue is.

I do notice that `gapi.client.gmail-tests.ts` doesn't actually reference the `gapi.client.gmail` namespace, so if that file is supposed to have compile errors for bad typings, it wouldn't catch this problem.

**Comment by lucka-me** [comment]
Fixed in #45380.
I also tested [Maxim-Mazurok/google-api-typings-generator](https://github.com/Maxim-Mazurok/google-api-typings-generator), it generated the correct code.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
