### ISSUE TITLE
The scrypt that remove system and microsoft kill my project

### ISSUE THREAD

**Issue by cerqueira81** [DefinitelyTyped/DefinitelyTyped#38781]
When i install the library it run a script that remove all the references with system and microsoft.

That kill my project and i need to add all the references again.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
