### ISSUE TITLE
@types/node regression - process.stdin isn't Readable

### ISSUE THREAD

**Issue by arcanis** [DefinitelyTyped/DefinitelyTyped#38788]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @linjiajian999 @uniqueiniquity 

I believe #38237 caused a regression in the `ReadStream` / `Readable` compatibility (same for `Writable`). Cf the following:

![image](https://user-images.githubusercontent.com/1037931/66000741-5eecfa80-e4a0-11e9-8e97-1250464df91d.png)

https://www.typescriptlang.org/play/#code/JYWwDg9gTgLgBAbwEoFMCGATNAjANigXzgDMoIQ4ByAZxinREoG4BYAKHYGMIA7WuAB4AuOKkw58cALxwwZTimrUAdLQzAerNkA

**Comment by linjiajian999** [comment]
referring to [process_stdin](https://nodejs.org/api/process.html#process_process_stdin), I think the return type of `process.stdin` should be `ReadableStream` instead of `Readable`.

**Comment by uniqueiniquity** [comment]
Thanks for reporting this issue, @arcanis.
I agree that this is somewhat of a regression, but this was actually already broken.
`const x: tty.ReadStream = process.stdin;` should work but doesn't due to current limitations.
The issue you're reporting is a consequence of this core issue.
In https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32878#commitcomment-32665276, the maintainers acknowledged the issue and suggest using a type assertion for now.
