### ISSUE TITLE
@types/mongodb wrong types for types with { [K: string]: any }

### ISSUE THREAD

**Issue by HosseinAgha** [DefinitelyTyped/DefinitelyTyped#38786]
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT 

Looks like TypeScript has a bug with the usage of `Omit` (`Exclude` to be precise) and types that contain `{ [K: string]: any }`. For example we return a wrong type for the following:

```typescript
interface BooksModel {
  _id: ObjectId,
  title: string,
  [K: string]: any
}
```

Take a look at following for more info:  
https://github.com/microsoft/TypeScript/issues/31153
https://github.com/Microsoft/TypeScript/issues/25987

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
