### ISSUE TITLE
[@types/slate-react] the editor component's callback editor type is wrong

### ISSUE THREAD

**Issue by zaunermax** [DefinitelyTyped/DefinitelyTyped#38814]
- [x] I tried using the `@types/react-slate` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- Authors: @majelbstoat @JanLoebel @PatrickSachs @YangusKhan @isubasti @sgreav @Kornil @jackall3n @benjiro @kaydelaney

When passing callbacks to the editor react component (e.g. `onDrop` or `onPaste`) the editor type of the callback arguments is wrong. In the type definition, the editor has the type `CoreEditor` (the `Editor` type from the `slate` package), which is not correct. The correct type would be `Editor` from the `slate-react` package. 

I noticed this because the function `getEventRange` which takes an `Event` and a `CoreEditor` is deprecated in future Slate versions. When I tried to use `editor.findEventRange` in an `onDrop` callback, there was an error stating that `editor` does not have this function as `findEventRange` is only available on the `Event` type from the `slate-react` package. Inspecting the editor object in the console reveals, that `findEventRange` exists on the object that gets passed to the callback.

I am not quite sure how to fix this, as almost the whole type definition file of `slate-react` is referring to the `CoreEditor`... Simply changing this to the `slate-react` editor would probably break a few things.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
