### ISSUE TITLE
react-router useParams and useRouteMatch change Params types to string instead of retaining them

### ISSUE THREAD

**Issue by moonray** [DefinitelyTyped/DefinitelyTyped#38827]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-router` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sergey-buturlakin @mrk21 @vasek17 @ngbrown @awendland @KostyaEsmukov @johnnyreilly @LKay @DovydasNavickas @huy-nguyen @grmiade @DaIgeb @egorshulga @rraina @pret-a-porter @t49tran @8enSmith @wezleytsai @eps1lon @HipsterBrown 

If you do not mention the authors the issue will be ignored.

When using the old withRouter and RouteComponentProps the Params types would be retained.

e.g.
```
function CustomComponent({ match }: RouteComponentProps<{ customId: ObjectId }>) {
  const id = match.params.customId;
```
This would set the type of `id` to `ObjectId`.

`const { customId: id } = useParams<{ customId: ObjectId }>();`
This sets the type of `id` to `string`.

**Comment by eps1lon** [comment]
Sorry I never used the hooks. Could you explicitly include what is currently rejected by the type checker and add a link to the docs or a codesandbox that shows this is fine?

**Comment by ntegral** [comment]
Ran into the same issue.  It's the way useParams is implemented. Considering writing a new custom implementation that would account for something other than string types

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
