### ISSUE TITLE
The type for  ChangeStream in "@types/mongodb": "3.3.1" is likely wrong wrt destroy() method

### ISSUE THREAD

**Issue by ORESoftware** [DefinitelyTyped/DefinitelyTyped#38857]
- [x] I tried using the `@types/mongodb` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

  - Authors: @KelWill @PranavSenthilnathan  @mongodb 

I have this issue:
https://stackoverflow.com/questions/58227609/changestreamdestroy-is-not-a-method

I am on version `"mongodb": "3.3.2"`

ChangeStream#destroy is not a function/method, but maybe it should be? According to the typings it is.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
