### ISSUE TITLE
@types/bindings not installing on raspberry pi (arm)

### ISSUE THREAD

**Issue by mmc41** [DefinitelyTyped/DefinitelyTyped#38875]
If you know how to fix the issue, make a pull request instead.

- [s ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @unindented.

The most recent npm 1.5.0 of @types/bindings does not install correctly with "npm install" for raspberry pi (arm 32). The resulting folder in node_modules is empty except from a "package.json" file.

**Comment by yoursunny** [comment]
I cannot reproduce this bug on Raspberry Pi 3, Ubuntu 18.04 arm64.

```
ubuntu@pi3:~/code/dt38875$ npm i @types/bindings
npm notice created a lockfile as package-lock.json. You should commit this file.
+ @types/bindings@1.3.0
added 1 package from 1 contributor and audited 1 package in 1.118s
found 0 vulnerabilities

ubuntu@pi3:~/code/dt38875$ find node_modules/@types/bindings/
node_modules/@types/bindings/
node_modules/@types/bindings/LICENSE
node_modules/@types/bindings/README.md
node_modules/@types/bindings/package.json
node_modules/@types/bindings/index.d.ts
```

**Comment by mmc41** [comment]
Thanks - Hmm - maybe it works on arm64 only but not arm32 ?

**Comment by yoursunny** [comment]
I see no reason why this package could fail on any particular architecture. It has no dependencies and no C extensions.

> npm 1.5.0 of @types/bindings

There isn't a `1.5.0` version on NPM. Its only version is `1.3.0`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
