### ISSUE TITLE
braintree-web/local-payment not converted

### ISSUE THREAD

**Issue by nielsvanrijn** [DefinitelyTyped/DefinitelyTyped#38871]
@module braintree-web/local-payment is not integrated in the index.d.ts.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
