### ISSUE TITLE
Property 'svg' does not exist on type 'IChartistLineChart'.

### ISSUE THREAD

**Issue by artuska** [DefinitelyTyped/DefinitelyTyped#38909]
I have a chart:

```
let chart = new Chartist.Line(element, data, options);
```

if i do:

```
console.log(chart);
```

i see all chart properties and `svg` property too:

```
svg: constr {_node: svg}
```

But in my code i get `Property 'svg' does not exist on type 'IChartistLineChart'` error message.

I use `svg` because of `querySelector` method:

```
this.chart.svg.querySelector(...);
```

but now i'm supposed to write:

```
this.chart['svg'].querySelector(...);
```

- [x] I tried using the `@types/chartist` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mtgibbs, @psimonski, @affilnost, @sunnyrjuneja

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
