### ISSUE TITLE
Benchmark fails when adding packages with `typesVersions`

### ISSUE THREAD

**Issue by ExE-Boss** [DefinitelyTyped/DefinitelyTyped#38980]
When writing types for `es‑to‑primitive` (#38947), the BenchmarkPR job fails with a reason [related to the usage of `typesVersions` in a newly added package](https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=17790).

A similar issue occurs with `es‑abstract` (#38979), which depends on `es‑to‑primitive`, [causing the BenchmarkPR job to fail](https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=17953), but it’s because of the CI making a change to `types/es‑to‑primitive/package.json`, which causes git to complain when checking out the `master` branch (this should go away once #38947 is merged and #38979 is rebased).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
