### ISSUE TITLE
Google Map customized marker

### ISSUE THREAD

**Issue by ss-markmontesa** [DefinitelyTyped/DefinitelyTyped#39017]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/googlemaps` package and had problems.
I cannot create customed icon for markers like this one.
    var pinImage = {
      path: 'M 0,0 C -2,-20 -10,-22 -10,-30 A 10,10 0 1,1 10,-30 C 10,-22 2,-20 0,0 z',
      fillColor: '#000',
      fillOpacity: 1,
      strokeColor: '#000',
      strokeWeight: 1,
      scale: 1,
      labelOrigin: { x: 0, y: -30 }
    }

    var marker = new google.maps.Marker({
      label: "1",
      position: new google.maps.LatLng(35.2271, -80.8431),
      title: "test",
      map: this.map,
      icon: pinImage
    });

- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
https://www.npmjs.com/package/@types/googlemaps
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Chris Wrench,@Kiarash Ghiaseddin,@Grant Hutchins,@Denis Atyasov,@Michael McMullin,@Martin Costello,@Sven Kreiss,@Umar Bolatov,@Michael Gauthier,@Colin Doig,@Dmitry Demensky,@Vladimir Dashukevich

If you do not mention the authors the issue will be ignored.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
