### ISSUE TITLE
[@types/in-app-purchase] Requesting update to latest/1.11.4

### ISSUE THREAD

**Issue by Nolanlemahn** [DefinitelyTyped/DefinitelyTyped#39039]
- [x] I tried using the `@types/in-app-purchase` package and had problems.

In particular (at a quick glance), `iap.Config` seems to have had many fields added to it.

- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @l-jonas | @IchordeDionysos 

Thank you,
~Nolan

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
