### ISSUE TITLE
FastClick -AMD module declaration Issue

### ISSUE THREAD

**Issue by jackesdavid** [DefinitelyTyped/DefinitelyTyped#3904]
Hi guys , first of all,  thanks for this amazing community.

The current declaration module does not retrieve the correct object in intellisense...

I Think  is the correct module declaration to use with AMD and Require.js is:

//fastclick.d.ts
declare var FastClick: FastClickStatic;
declare module "fastclick" {
    export = FastClick;
}

//require.js
paths  : {  
        'fastclick':'../libs/plugins/fastclick'
    }

//usage
import fastClickPlugin = require("fastclick");
fastClickPlugin.attach(document.body);

**Comment by cspotcode** [comment]
According to the FastClick documentation, there are two different ways FastClick might be exported as an external module: one for AMD and one for CommonJS.  The .d.ts will need to support both, even though only one is available at runtime.

It looks like the module's interface needs to support all of the following:
* be `new`able and return a `FastClickObject`
* be invokable as a function and return a `FastClickObject`
* have an `attach` property that is invokable as a function and returns a `FastClickObject`
* have a `FastClick` property that is `new`-able and returns a `FastClickObject`

How about this?
```
interface FastClickCommonJS {
    (layer: any, options?: FastClickOptions): FastClickObject;
    FastClick: FastClickStatic;
}
module "fastclick" {
    var exports: FastClickCommonJS|FastClickStatic;
    export = exports;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
