### ISSUE TITLE
[@types/vexflow] Cannot access ambient const enums

### ISSUE THREAD

**Issue by seancolsen** [DefinitelyTyped/DefinitelyTyped#39079]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rquiring, @sebastianhaas, @bohoffi, @sschmidTU, @bneumann

---

Here's a simplified version of my VexFlow code:

```typescript
import Vex from 'vexflow';
const VF = Vex.Flow;
let containingDiv = document.getElementById("notation");
let renderer = new VF.Renderer(containingDiv!, VF.Renderer.Backends.SVG);
```

On `VF.Renderer.Backends`, I'm getting the following error from Typescript: 

> Cannot access ambient const enums when the '--isolatedModules' flag is
> provided.ts(2748)

How can I fix this error? Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
