### ISSUE TITLE
Log4js package naming

### ISSUE THREAD

**Issue by DenEwout** [DefinitelyTyped/DefinitelyTyped#3909]
Hi,

I know the naming convention for packages is to use the npm package name. So for the log4js-node project this would be log4js (https://www.npmjs.com/package/log4js).

The typescript definition for log4js-node (https://github.com/nomiddlename/log4js-node) is not compatible with log4js (https://github.com/stritti/log4js).

I'd like to contribute a definition for log4js. What would be the identifier of this? The contribution guide says:

"If the library is not published on npm use a new identifier, as long as it doesn't shadow an existing npm name."

So should I create a pull-request using "log4js-web"?

**Comment by vvakame** [comment]
@DenEwout umm... yes. please use log4js-web temporary.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
