### ISSUE TITLE
[@types/jsoneditor] Wrong type of onEvent optional callback in JsonEditorOptions

### ISSUE THREAD

**Issue by Amiryy** [DefinitelyTyped/DefinitelyTyped#39147]
If you know how to fix the issue, make a pull request instead.

- [v] I tried using the `@types/xxxx` package and had problems.
- [v] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [v] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/). 
 
In JsonEditorOptions it seems that the `onEvent` callback's `event` parameter type is defined as `string`.
I believe it should be a generic `Event` type.

This is a copy-paste from type declaration file:
```
export interface JSONEditorOptions {
    ...
    onEvent?: (node: Node, event: string) => void;
    ...
}
```

- [v] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @josdejong

If you do not mention the authors the issue will be ignored.

**Comment by josdejong** [comment]
@Amiryy you're right, the type of the parameter `event` is an `Event`.

Here you can see how the current implementation calls the `onEvent` callback: https://github.com/josdejong/jsoneditor/blob/42a2f89bae4754f8cddfb9a93208324803197d24/src/js/Node.js#L2587-L2609

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
