### ISSUE TITLE
npm ERR! 404 Not Found: @types/minimatch@latest

### ISSUE THREAD

**Issue by acarlstein** [DefinitelyTyped/DefinitelyTyped#39150]
Will you help me?

When running `$ npm install -g @types/minimatch`, I get
```
npm ERR! code E404
npm ERR! 404 Not Found: @types/minimatch@latest
``` 
I tried to set the `.npmrc` file with the content below but not luck:
```
@types/minimatch=http://registry.npmjs.org/
```
and
```
@types/minimatch=https://registry.npmjs.org/
```

What do I need to setup in the .npmrc to be able to install the @types/minimatch?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
