### ISSUE TITLE
[@types/xrm] Return XrmEnum for known types

### ISSUE THREAD

**Issue by KimBon** [DefinitelyTyped/DefinitelyTyped#39178]
Hi
@6ix4our / @mattngan / @markusmauch / @daryllabar / @clownwilleatme / @scottdurow

I have the feeling some functions are inconsistent in regards to returning an XrmEnum or the string/number value for it. Or it would be that I am using them the wrong way. For example:

- Xrm.ClientContext.getFormFactor(): XrmEnum.ClientFormFactor;
- Xrm.ClientContext.getClientState(): ClientState;

If you want to compare the result in an IF statement, for the first sample you should compare towards XrmEnum. For the second one, you compare with a string value "Online" or "Offline".

For ClientState, there is a ClientState type, but also an Enum exists. Would it not be more clear to always return an XrmEnum?

Kind regards

Kim

**Comment by daryllabar** [comment]
It's been awhile since I've spent a lot of time in the TS, but I believe this is the history that caused this situations.

In the beginning there were C# developers and they compiled code, and this compiled code was good.  They used enums, and this was also good.  But then the did JS and missed their typecheck safety net, so they used TS, and used Enums in TS.  But then TS came out with Union Types, which served a very similar role as Enums in TS.  Because they were also involved much less work when converting code from JS to TS, a decision was made to start using Union Types instead, but no one wanted to break existing code, so both were left.

I'm still in favor of Union Types over Enums just because of a simpler upgrade path.  So my vote is to utilize them more, and the Enums less.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
