### ISSUE TITLE
Backbone: Collection reset(), add() with attributes hash

### ISSUE THREAD

**Issue by eschwartz** [DefinitelyTyped/DefinitelyTyped#3922]
The current typing for Backbone.Collection#reset is:

``` ts
reset(models?: TModel[], options?: Silenceable): TModel[];
```

However, you can also call reset with an attributes hash. From the docs

```
Use reset to replace a collection with a new list of models (or attribute hashes)
```

The same is true for Backbone.Collection#add()

Could we add an alternative signature for reset?
## 

IMO, the best option would be to support generic attribute hash types. For Example:

``` ts
interface BookAttributes {
  title:string;
  author:string;
}

class Book extends Backbone.Model<BookAttributes> {
}

class BookCollection extends Backbone.Collection<Book> {
}

var bookCollection:BookCollection  = new BookCollection();
bookCollection.add({
  title: 'Some Book',
  author: 'Some Guy'
});
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
