### ISSUE TITLE
[@types/jasmine] type errors related to withArgs method in Spy class

### ISSUE THREAD

**Issue by dmielewczyk** [DefinitelyTyped/DefinitelyTyped#39234]
- [x] I tried using the `@types/jasmine`@3.4.4 package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @theodorejb @davidparsson  

Using `withArgs` method in Spy class is limited. Each arg need to be AsymmetricMatcher function or just a string. 

> Argument of type '{ test: string; }' is not assignable to parameter of type 'string | AsymmetricMatcher<any>'.
  Object literal may only specify known properties, and 'test' does not exist in type 'AsymmetricMatcher<any>'.

As I can read in jasmine documentation, I can specify whatever I want and it's still working like that in jasmine 3.5.0 (current) version: https://jasmine.github.io/api/edge/Spy

It has been changed in these commits:
1. https://github.com/DefinitelyTyped/DefinitelyTyped/commit/7456aa4eec4bcfc03259a7d32e619d0607bbed3b#diff-ec257de2405be71db39255c0165ed928R831
2. https://github.com/DefinitelyTyped/DefinitelyTyped/commit/aed6042848fb5d92cb4109b29719f3b4d3d98bf4#diff-ec257de2405be71db39255c0165ed928R828

**Comment by jcimoch** [comment]
+1

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
