### ISSUE TITLE
Add JSX declarations for wicg-inert polyfill

### ISSUE THREAD

**Issue by kripod** [DefinitelyTyped/DefinitelyTyped#39289]
In order to use [wicg-inert](https://github.com/WICG/inert), the following has to be added into a project-specific `declarations.d.ts` file:

```ts
declare module 'react' {
  interface DOMAttributes<T> {
    inert?: '' | undefined;
  }
}

declare global {
  namespace JSX {
    interface IntrinsicAttributes {
      inert?: '' | undefined;
    }
  }
}

export {};
```

With a `@types/wicg-inert` package, all the above could be embedded into an isolated package, improving the developer experience until React adds support for the `inert` attribute.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
