### ISSUE TITLE
node-schedule supports `tz` (timezone) in code but not in typing

### ISSUE THREAD

**Issue by benjamin21st** [DefinitelyTyped/DefinitelyTyped#39307]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tejasmanohar

If you do not mention the authors the issue will be ignored.

As this comment shows (and my experiment), the `tz` option is supported in the code, but when using TypeScript it shows error indicating that `tz` is not supported.
https://github.com/node-schedule/node-schedule/issues/217#issuecomment-478624773

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
