### ISSUE TITLE
you should use `export default class` instead of `export class`. `export class` not work for me.

### ISSUE THREAD

**Issue by immint023** [DefinitelyTyped/DefinitelyTyped#39302]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4a4375a3acedf893aaed1ee39fcec7f48b2ec8be/types/react-big-scheduler/index.d.ts#L10

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
