### ISSUE TITLE
[@types/chart.js]custom's type is not specified

### ISSUE THREAD

**Issue by qkreltms** [DefinitelyTyped/DefinitelyTyped#39344]
```
 interface ChartTooltipOptions {
        enabled?: boolean;
        custom?(a: any): void;
        mode?: InteractionMode;
        intersect?: boolean;
       //...
```
As you can see custom property of ChartTooltipOptions is not specified, but described interface in [official document](https://www.chartjs.org/docs/latest/configuration/tooltip.html#external-custom-tooltips)

- [x] I tried using the `"@types/chart.js": "^2.8.7"` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @anuti, @FabienLavocat, @KentarouTakeda, @larrybahr, @mernen, @josefpaij, @danmana, @guillaume-ro-fr, @archy-bold, @braincore, @frabnt, @alexdor, @mahnuh, @Conrad777, @adripanico, @wertzui, @lekoaf, @ElianCordoba, @indigolain

**Comment by lekoaf** [comment]
Are you referring to `(a: any)`? What type do you suggest it should have? Unfortunately there are a lot of function properties with the `any` type. They are difficult to type, but they really should be somehow.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
