### ISSUE TITLE
swagger-schema-official BaseSchema as a type alias instead of interface impacts custom extensions

### ISSUE THREAD

**Issue by JasonKleban** [DefinitelyTyped/DefinitelyTyped#39350]
BaseSchema used to be an interface and so it could be declaration merged to include custom extensions (for things like encoding generics and enums where swagger falls short).  Now it's a type alias which can't be extended like that and requires extending the consuming `Schema` and `Header` interfaces separately.  Was that change necessary?

@mohsen1 @bsouthga @nimerritt

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
