### ISSUE TITLE
[@types/hapi__hapi] Cannot use namespace 'Boom' as a type

### ISSUE THREAD

**Issue by pierretasci** [DefinitelyTyped/DefinitelyTyped#39361]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @lenovouser

When trying to run a very basic setup with TS and Hapi I get the error `Cannot use namespace 'Boom' as a type` on compile. It appears that [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blame/master/types/hapi__hapi/index.d.ts#L23) must be imported as a namespace instead of a specific type. This is causing compile errors here: 

```
    512 |      * In case of an aborted request the status code will be set to `disconnectStatusCode`.
    513 |      */
  > 514 |     response: ResponseObject | Boom;
        |                                ^
    515 |
    516 |     /**
    517 |      * Same as pre but represented as the response object created by the pre method.
```

and here

```
    4048 |         (null | string | number | boolean) |
    4049 |         (Buffer) |
  > 4050 |         (Error | Boom) |
         |                  ^
    4051 |         (stream.Stream) |
    4052 |         (object | object[]) |
    4053 |         symbol |
```

**Comment by lenovouser** [comment]
> This is due to hapi starting to ship it's own typings.

_Originally posted by @SimonSchick in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38870#issuecomment-540219275_

**Comment by harriha** [comment]
Now this is unfortunate. I'm trying to upgrade to hapi v18 (as not ready to move on to Node v12 just yet), but this issue seems to mess up the otherwise nicely-working upgrade process. Did my digging to figure out what's going on, so documenting it here for others suffering from the same issue (which will go away once moving on to hapi v19):

The change in boom itself (https://github.com/hapijs/boom/issues/253) was introduced in boom 8.0.1 (https://github.com/hapijs/boom/milestone/58), which otherwise works against hapi v18 but this typings issue was only fixed against hapi v19 here, leaving the problem to hapi v18 typings. However, for some other hapi ecosystem libraries which work against v18 this usage of Boom is correct and works (e.g. wreck, h2o2), which messes up the proper migration to hapi v18 even more as those libs are not compatible with the older Boom. 

To overcome this issue, I resorted to using [patch-package](https://www.npmjs.com/package/patch-package) and fixing the hapi v18 typings with that.

In package.json:

```
        "@types/hapi__hapi": "18.2.6",
```

Patch: 

```
diff --git a/node_modules/@types/hapi__hapi/index.d.ts b/node_modules/@types/hapi__hapi/index.d.ts
index ed8e5f9..80cba1f 100644
--- a/node_modules/@types/hapi__hapi/index.d.ts
+++ b/node_modules/@types/hapi__hapi/index.d.ts
@@ -20,7 +20,7 @@
 
 /// <reference types='node' />
 
-import * as Boom from '@hapi/boom';
+import { Boom } from '@hapi/boom';
 import * as http from 'http';
 import * as https from 'https';
 import * as Shot from '@hapi/shot';
```

**Comment by dasDaniel** [comment]
Maybe this will help someone who is having the same issues 

I've got these dependencies...
```json
  "devDependencies": {
    "@types/hapi": "^18.0.3",
    "@types/hapi__boom": "^7.4.1",
    "@types/hapi__hapi": "^18.2.5",
    "@types/hapi__inert": "^5.2.0",
    "@types/hapi__joi": "^15.0.3",
    "@types/node": "^13.11.1",
    "typescript": "^3.8.3"
  }
```

If I do `yarn` to install, I get this error

If I do `npm i`, it works fine.

so it seems like it's not liking the yarn install (I've got yarn v1.9 though)

**Comment by SimonSchick** [comment]
boom types are deprecated, the module is shipping it's own typings.
