### ISSUE TITLE
Cucumber Scenario result exception is not available in HookScenarioResult 

### ISSUE THREAD

**Issue by Phonesis** [DefinitelyTyped/DefinitelyTyped#39375]
Not sure if this is by design (can't imagine it would be) but the exception for failing Scenarios is not currently available as part of the HookScenarioResult object here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cucumber/index.d.ts

I have tried this in my tests:

```
After({ timeout: cucumberTimeOut }, async function(scenario) {
  console.log('error: ' + scenario.result.exception);
});
```

The problem appears to be that the HookScenarioResult object in the After hook HookCode object does not have the exception as part of the interface:

```
export interface ScenarioResult {
    duration: number;
    status: Status;
}
```

I have fixed it locally by simply adding it:

```
export interface ScenarioResult {
    duration: number;
    status: Status;
    exception: Error;
}
```

Can this be addressed?

**Comment by Phonesis** [comment]
Just an update, turns out it's the "Scenario: any" as param type that is key here. It works with any set as type. If I used HookScenarioResult as type it can't find exception. So this works:

```
After({ timeout: cucumberTimeOut }, async function(scenario: any) {
  console.log('error: ' + scenario.result.exception);
});
```

Whereas this doesn't:

```
After({ timeout: cucumberTimeOut }, async function(scenario: HookScenarioResult) {
  console.log('error: ' + scenario.result.exception);
});
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
