### ISSUE TITLE
[@types/swiper] esm module file path has change, now is swiper/js/swiper.esm.js, without dist now.

### ISSUE THREAD

**Issue by Sesna** [DefinitelyTyped/DefinitelyTyped#39424]
[@types/swiper] esm module file path has change.
here is the file path of swiper@5.1.0
![image](https://user-images.githubusercontent.com/8176600/67564556-ca4f8280-f755-11e9-8792-327ec46175ab.png)

this is the current type definition
![image](https://user-images.githubusercontent.com/8176600/67564709-24e8de80-f756-11e9-8761-2763843224d4.png)

it will cause a error like this
`Could not find a declaration file for module 'swiper/js/swiper.esm'.`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
