### ISSUE TITLE
@types/analytics-node - export whole AnalyticsNode namespace?

### ISSUE THREAD

**Issue by dgobaud** [DefinitelyTyped/DefinitelyTyped#39423]
@fongandrew @thomasthiebaud need access to the interfaces in the AnalyticsNode namespace - how can it be exported/made available? I think the problem is segment only exports the one class so we can't export the namespace have to export the class as export not sure there is a way to do this...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
