### ISSUE TITLE
403 Forbidden trying to contribute....

### ISSUE THREAD

**Issue by alex-randall** [DefinitelyTyped/DefinitelyTyped#3980]
Visual Studio 2013, cloned the entire repository, made the change to the file, created a descriptive commit comment, pushed, then got a 403 Forbidden.

What's wrong with the process?  What did I miss?

I have my own github projects that work no problem with Visual Studio 2013.  I understand the whole github push/pull concepts at least at the Visual Studio level.  I already read the http://definitelytyped.org/guides/contributing.html guide but it says nothing about this scenario...

Thanks for any help!

**Comment by vsiao** [comment]
You need to fork this repository, push to your own repository, then create a pull request from your fork (alex-randall/DefinitelyTyped) back to this one (borisyankov/DefinitelyTyped)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
