### ISSUE TITLE
angular-mocks definition doesn't have e2e

### ISSUE THREAD

**Issue by Foxandxss** [DefinitelyTyped/DefinitelyTyped#3985]
I am doing something like:

``` javascript
$provide.decorator('$httpBackend', angular.mock.e2e.$httpBackendDecorator);
```

And I get this error:

``` plain
Property 'e2e' does not exist on type 'IMockStatic'.
```

There is an `e2e` object on angular.mock so I guess the issue relies on the definition object. Not that what I am doing is really based on definitions, but since the angular definitions creates an angular module, my IDE (webstorm) is confused.

**Comment by vvakame** [comment]
@Foxandxss please send a PR. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
