### ISSUE TITLE
angularjs family of declarations are causing problems in PhpStorm 8

### ISSUE THREAD

**Issue by d-ph** [DefinitelyTyped/DefinitelyTyped#3986]
Hello,

`angularjs` family of declarations are causing problems in PhpStorm 8.
1. Lack of TypeScritp's union feature. But this is down to PhpStorm guys to fix, so never mind. What I ended up doing is: I manually replaced all `union` usage with type `any`.
2. angular symbol being a variable name and module name:

```
declare var angular: ng.IAngularStatic;

import ng = angular;

declare module angular {
```

The problem is that PhpStorm generally thinks, that `ng` symbol is of type angular.IAngularStatic instead of the `angular` module. I.e. I cannot access e.g. ng.IScope. I ended up renaming the `angular` module to `ng` in all declaration files and removing the `import ng = angular;` line. Would you consider do the same? I mean, I know TypeScript allows it (`tsc` works fine with these declaration files), but really, by naming two different symbols the same you're asking for trouble. I was confused myself until I actually dug into the problem.

I realize it might be a breaking change, but again: would you consider renaming the `angular` module with something else? E.g. `ng`?

Thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
