### ISSUE TITLE
[@types/mongoose] Document.get third argument is missing in type defs

### ISSUE THREAD

**Issue by nephix** [DefinitelyTyped/DefinitelyTyped#39906]
- [x] I tried using the `@types/mongoose^5.5.23` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondrata @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @danmana @ChristianBoehlke @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @Vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @iamchathu 

When using `Document.get` the [type defs](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L1277) currently only take 2 arguments. The `options` argument from the [official API docs](https://mongoosejs.com/docs/api.html#document_Document-get) is missing

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
