### ISSUE TITLE
cls_hooked function fromException not available in typescript

### ISSUE THREAD

**Issue by brandonstark** [DefinitelyTyped/DefinitelyTyped#39909]
I converted a project written in js to ts.
cls-hooked function fromException() gives error:
"Property 'fromException' does not exist on type 'Namespace'.ts(2339)"

Adding "@ts-ignore" removes the error, and the function does work.

 Mention the authors (see Definitions by: in index.d.ts) so they can respond.
Authors: @sergey-buturlakin @mrk21 @vasek17 @ngbrown @awendland @KostyaEsmukov @johnnyreilly @LKay @DovydasNavickas @huy-nguyen @Grmiade @DaIgeb @egorshulga @rraina @pret-a-porter @t49tran @8enSmith @wezleytsai @eps1lon @HipsterBrown

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
