### ISSUE TITLE
[@types/jsonwebtoken] Signature of verify

### ISSUE THREAD

**Issue by nabati** [DefinitelyTyped/DefinitelyTyped#39911]
Is the signature of the return type here really correct?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a2bceed52a36ba36a1b06038e616bb63b3fa9edc/types/jsonwebtoken/index.d.ts#L162

If you check the `decode.js` code you get 

```
  //try parse the payload
  if(typeof payload === 'string') {
    try {
      var obj = JSON.parse(payload);
      if(obj !== null && typeof obj === 'object') {
        payload = obj;
      }
    } catch (e) { }
  }
```

JSON.parse has return type `any`, which would lead me to believe that the return type should be `any` for `verify` as well.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
