### ISSUE TITLE
@types/react-virtualized: Generic type `ReactElement<P>` requires 1 type argument(s).

### ISSUE THREAD

**Issue by qburst-sharath** [DefinitelyTyped/DefinitelyTyped#39967]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-virtualized` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kaoDev @guntherjh @wasd171 @szabolcsx @kraenhansen @Stevearzh @mgoszcz2

_Issue_: Generic type `ReactElement<P>` requires 1 type argument(s). in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-virtualized/dist/es/WindowScroller.d.ts#L16 (v 9.21.5)

Version:
* Typescript: 2.8.3,
* @types/react: 16.3.4,
* @​types/react-virtualized: 9.21.5

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
