### ISSUE TITLE
Subsequent variable declarations issue with @types/node and @types/requirejs

### ISSUE THREAD

**Issue by shanmudev** [DefinitelyTyped/DefinitelyTyped#40010]
Issue when compiling project _**'error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.'**_ 
My **package.json** looks like below,

	"dependencies": {
		"@aspnet/signalr": "^1.1.4",
		"eventsource": "^1.0.7",
		"request": "^2.88.0",
		"ws": "^7.2.0"
	},
	"devDependencies": {
		"@types/chai": "^3.4.28",
		"@types/jasmine": "2.8.9",
		"@types/jasmine-ajax": "^3.1.27",
            "@types/node": "^7.0.18",
		"@types/requirejs": "^2.1.26",
		"es6-promise": "^4.2.8"
	},

Node and requirejs messed with each other with **_require_** variable. How to fix this? Which version i need to change.

**Comment by shanmudev** [comment]
Is there any possibilities to resolve this issue?

**Comment by crystalfp** [comment]
The only solution I have found is to edit the `@types/requirejs/index.d.ts` file and comment out declarations of `module 'module'` (lines 32-39) and of `var require: Require;` (line 422) and use `requirejs` instead of `require` in my sources.

**Comment by crystalfp** [comment]
Well, I copied `@types/requirejs/index.d.ts` to `requirejs.d.ts` in my source dir, edited it as in my previous comment and added the line:
```
/// <reference types="./requirejs" />
```
on top of my source file. Obviously, I removed `requirejs` and `@types/requirejs` from npm.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
