### ISSUE TITLE
Jasmine: `this` is incorrectly `<any>` in (before|after)(Each|All) and it

### ISSUE THREAD

**Issue by yelvert** [DefinitelyTyped/DefinitelyTyped#40024]
Currently the value of `this` inside `beforeEach`, `afterEach`, `beforeAll`, `afterAll`, and `it` (and possibly other related ones) is incorrectly being reported as `<any>`, instead of being a `<Spec>`

**Comment by bodinsamuel** [comment]
Hello,

Are you sure you are talking about Jasmine?
Those methods are currently return `void` and also in the code
https://github.com/jasmine/jasmine/blob/b4cbe9850fbe192eaffeae450669f96e79a574ed/src/core/Suite.js#L67

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
