### ISSUE TITLE
[@types/koa]the return type of KOA callback() function maybe error 

### ISSUE THREAD

**Issue by prometheuszyx** [DefinitelyTyped/DefinitelyTyped#40070]
- [x] I tried using the `@types/koa` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sirlantis @DavidCai1993 @jkeylu @brikou @harryparkdotio

hello, the return type of callback() function is (req: IncomingMessage | Http2ServerRequest, res: ServerResponse | Http2ServerResponse) => **void**.

maybe '(req: IncomingMessage | Http2ServerRequest, res: ServerResponse | Http2ServerResponse) => **Promise\<void\>**' is correct

**Comment by bodinsamuel** [comment]
Hello,
callback can be passed to `http.createServer()` which takes `type RequestListener = (req: IncomingMessage, res: ServerResponse) => void;`.
As suggested in doc: https://koajs.com/
```
http.createServer(app.callback()).listen(3000);
```

Do you have an example where promise.void would be acceptable ?

**Comment by thewilkybarkid** [comment]
Just discovered this by enabling `@typescript-eslint/no-misused-promises`. Should it be:

```typescript
type RequestListener = (req: IncomingMessage, res: ServerResponse) => void | Promise<void>;
```

?

**Comment by GlennyDC** [comment]
The `@typescript-eslint/no-misused-promises` reports `Promise returned in function argument where a void return was expected`. The http.createServer does not accept a Promise but the `app.callback()` is not a Promise (`Unexpected `await` of a non-Promise (non-"Thenable") value.`)

I guess the return type of `app.callback()` should just be void instead of `Promise<void>`?

app.ts:
```
import http from 'http';
import Koa from 'koa';

const app = new Koa();
http.createServer(app.callback()).listen(3000);
```

Versions:
```
"koa": "^2.11.0",
"@types/koa": "^2.11.3",
"@types/node": "^14.0.4",
"@typescript-eslint/eslint-plugin": "^2.34.0",
"@typescript-eslint/parser": "^2.34.0",
"eslint": "6.0.0",
"typescript": "^3.9.2"
```

**Comment by GlennyDC** [comment]
Anyone else experiencing the same problem?

**Comment by thewilkybarkid** [comment]
Just spotted that the `Promise` type was added in #42551.

**Comment by GlennyDC** [comment]
[#42551](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42551) clarifies the `@typescript-eslint/no-misused-promises` eslint error. Can you actually workaround this without disabling the rule for that line?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by damianobarbati** [comment]
@thewilkybarkid  @GlennyDC how did you solve this?

**Comment by GlennyDC** [comment]
@damianobarbati, I did not. The error is still present in the following versions:

```
"koa": "^2.14.2",
"@types/koa": "^2.13.6",
"@types/node": "^20.3.1",
"@typescript-eslint/eslint-plugin": "^6.0.0",
"@typescript-eslint/parser": "^6.0.0",
"eslint": "^8.43.0",
"typescript": "^5.1.3"
```
