### ISSUE TITLE
[@types/mongoose] return type of DocumentArray.discriminator

### ISSUE THREAD

**Issue by hasezoey** [DefinitelyTyped/DefinitelyTyped#40104]
- [x] I tried using the `@types/mongoose` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - @horiuchi
  - @ToucheSir
  - @richarddd
  - @orblazer

Thanks to https://github.com/Automattic/mongoose/issues/8287#issuecomment-549173877 the return type got "defined" in jsdoc, and the @types/mongoose returns type of `DocumentArray.discriminator` was wrong - i would change it, but i dont know which type would be correct

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
