### ISSUE TITLE
Stripe: createUsageRecord missing from SubscriptionItems class

### ISSUE THREAD

**Issue by shadow1349** [DefinitelyTyped/DefinitelyTyped#40108]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/stripe@7.10.0` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 

@wjohnsto 
@codeanimal 
@sampsonjoliver 
@LinusU
@brannon
@kkamperschroer
@starhoshi
@bruun
@galtalmor
@htunnicliff
@squirly
@tzarger
@ifiokjr
@yultyyev
@cpsoinos
@adamduren
@saranshkataria
@0xJoKe
@delianides
@gokulchandra
@viralpickaxe
@chrisleck
@opticalgenesis
@spacetag
@vaskevich
@dhaspden
@esetnik
@schfkt
@ChrisZieba
@pushplay
@stilborg
@jvik
@richardwardza 

If you do not mention the authors the issue will be ignored.

The SubscriptionItems class is missing the createUsageRecord function.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/stripe/index.d.ts#L11879

Here are the corresponding docs: https://stripe.com/docs/api/usage_records/create

**Comment by vichingo** [comment]
In the changelog of 7.8.0 of the stripe-node module it states it has been added to the subscriptionItems.

https://github.com/stripe/stripe-node/blob/master/CHANGELOG.md#780---2019-08-12

**Comment by irzhywau** [comment]
@vichingo I use 7.9.0 but still got this error

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
