### ISSUE TITLE
[@types/xrm] Missing methods and properties in Xrm.ExecuteResponse

### ISSUE THREAD

**Issue by Dremor** [DefinitelyTyped/DefinitelyTyped#40117]
Authors: @6ix4our / @mattngan / @markusmauch / @daryllabar / @clownwilleatme / @scottdurow

I tried to use the Xrm.WebApi endpoint, but the "Xrm.ExecuteResponse" object seem to lack the methods and properties needed to read the resulting json, when one is returned (from an action).

Example: The following code works in CRM REST BUILDER, but not in Typescript

```javascript
var parameters = {};
parameters.Code = 353389;

var new_myActionRequest= {
    Code: parameters.Code,

    getMetadata: function() {
        return {
            boundParameter: null,
            parameterTypes: {
                "Code": {
                    "typeName": "Edm.Int32",
                    "structuralProperty": 1
                }
            },
            operationType: 0,
            operationName: "new_myActionRequest"
        };
    }
};

Xrm.WebApi.online.execute(new_myAction).then(
    function success(result) {
        if (result.ok) {
            var results = JSON.parse(result.responseText);
        }
    },
    function(error) {
        Xrm.Utility.alertDialog(error.message);
    }
);
```

The missions properties and methods are at least:
- json()
- responseText

Other may be missing, I didn't try all of them.

Api Reference: https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-webapi/online/execute

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
