### ISSUE TITLE
@types/react-router-dom useHistory, push method does not exist

### ISSUE THREAD

**Issue by cprieto** [DefinitelyTyped/DefinitelyTyped#40131]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/react-router-dom` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:  @sergey-buturlakin @mrk21 @vasek17 @ngbrown @awendland @KostyaEsmukov @johnnyreilly @LKay @DovydasNavickas @huy-nguyen @Grmiade @DaIgeb @egorshulga @rraina @pret-a-porter @t49tran @8enSmith @wezleytsai @eps1lon @HipsterBrown

If you do not mention the authors the issue will be ignored.

React Router 5.1 introduces a new hook to use the history directly: `useHistory`, when using react-router-dom 5.1.2 with @types/react-router-dom 5.1.2 it is incorrectly mapped:

Documentation specifies you can use directly the history, for example, pushing against the history object with `history.push` but when using with Typescript 3.6.4 the method `push` is marked as invalid and only `pushState` exists:

```ts
const history = useHistory()
history.push("/home")
```

**Comment by 596050** [comment]
This seems to be fixed:
![image](https://user-images.githubusercontent.com/19141517/77947325-ab808980-72bb-11ea-92fe-127976d37291.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
