### ISSUE TITLE
Types for KeystoneJS v5

### ISSUE THREAD

**Issue by thekevinbrown** [DefinitelyTyped/DefinitelyTyped#40147]
I just wanted to put an issue here as per the contribution guide that I'm currently working on these types. They're local to a project I'm working on at the moment, but if anyone wants to collaborate on them out in the open I'm happy to share.

**Comment by thekevinbrown** [comment]
I've published my local work to a repo and NPM to collaborate. Anyone who wants to contribute is welcome to:
https://www.npmjs.com/package/keystone-typescript-types
https://github.com/TechInSite/keystone-typescript-types

**Comment by thekevinbrown** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40316

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
