### ISSUE TITLE
[@types/react-filepond] onprocessfile event objects are swapped around

### ISSUE THREAD

**Issue by samcarton** [DefinitelyTyped/DefinitelyTyped#40152]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @zposten 

If you do not mention the authors the issue will be ignored.

# Summary
When handling the `onprocessfile` event, the `file: File` and `error: FilePondErrorDescription` objects actually receive the opposite objects (i.e. the error details go to `file`, and the file details go to `error`).
The type definition below seems to be out of date. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/807f5db1633cba3e7b90b11314fa5da469aac42d/types/react-filepond/index.d.ts#L326

I haven't tested any of the other callbacks. But the comment at the top of the callbacks export indicates that there may have been issues with all callbacks that returned errors? The filepond docs indicate that the error object should be the first, perhaps they fixed something on their side https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#callbacks

# How to reproduce
See here for an example https://codesandbox.io/s/runtime-morning-yc7xu

**Comment by zposten** [comment]
I agree that the package functionality is now correct and following the docs.  Fixed in #40419

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
