### ISSUE TITLE
[@types/estree] optional properties should not be `undefined`

### ISSUE THREAD

**Issue by Swatinem** [DefinitelyTyped/DefinitelyTyped#40188]
Due to [a recent problem with `rollup` and `rollup-plugin-dts`](https://github.com/rollup/rollup/issues/3210), we noticed that the `@types/estree` uses `optionalProp?: T | null` for all the properties, which means that `undefined` is valid per the `@types` definition. However, rollup was expecting an explicit `null` instead.

@lukastaegert, the maintainer of rollup suggested to update the definitions to only accept `null` for optional props, as that more closely matches the estree spec and other implementations.

- [x] I tried using the `@types/estree` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @RReverser

**Comment by bodinsamuel** [comment]
Did a fix here #42163

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
