### ISSUE TITLE
Update the list of types for a tax ID

### ISSUE THREAD

**Issue by timlouw** [DefinitelyTyped/DefinitelyTyped#40181]
I had an error showing up in VS code when trying to call

`stripe.customers.createTaxId(comp.stripeID, {
        type: "za_vat",
        value: comp.vatNumber
    }).catch(error => {
        console.log('Failed to create new tax ID in stripe =>');
        console.log(error);
    })`

Error: Type of the tax ID, one of au_abn, eu_vat, in_gst, no_vat, or nz_gst

But here is an extract from the [stripe docs](https://stripe.com/docs/api/customer_tax_ids/create) about tax IDs and type:

CREATE A TAX ID
Creates a new TaxID object for a customer.

ARGUMENTS:
customer
REQUIRED
ID of the customer.

type
REQUIRED
Type of the tax ID, one of au_abn, ch_vat, eu_vat, in_gst, mx_rfc, no_vat, nz_gst, or za_vat

value
REQUIRED
Value of the tax ID.

As you can see there are more types listed on the docs than what is including in the npm package

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
