### ISSUE TITLE
No interface define of push

### ISSUE THREAD

**Issue by hafizmuhammadshoaib** [DefinitelyTyped/DefinitelyTyped#40206]
@rollymaduk @vitosamson @FlorianDr @danduh @ChristianBoehlke @divyun . Please add push interface in types. Push object is present JS core.

**Comment by ChristianBoehlke** [comment]
What library are you talking about?

**Comment by FlorianDr** [comment]
I believe @hafizmuhammadshoaib talks about this: https://www.pubnub.com/docs/web-javascript/api-reference-mobile-push 

right?

**Comment by hafizmuhammadshoaib** [comment]
@FlorianDr yes i am talking exactly about this.

**Comment by ChristianBoehlke** [comment]
I think this has been solved in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40379 and can be closed?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
