### ISSUE TITLE
[@types/slate-react] getEventTransfer return type SlateNode does not match object return

### ISSUE THREAD

**Issue by DinMon** [DefinitelyTyped/DefinitelyTyped#40268]
- [x] I tried using the `@types/slate-react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] Authors: @majelbstoat @JanLoebel @PatrickSachs @YangusKhan @isubasti @sgreav @Kornil @jackall3n @benjiro @kaydelaney

Looking back at the history of `@types/slate-react`, function `getEventTransfer(event)` return type has been changed to `{type: SlateType, node: SlateNode}` where `SlateNode` is defined as type `Node` which can be `(Document | Block | Inline | Text)`. However, the return value from the function defined in the file `slate/packages/slate-react/src/utils/get-event-transfer.js` is as below:

`const data = { files, fragment, html, node, rich, text }
  data.type = getTransferType(data)
  return data`

Is the type SlateNode refering to Node in `@types/slate` the proper return type for the function getEventTransfer? If not, does getEventTransfer return type from `@types/slate-react` need to be changed?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
