### ISSUE TITLE
google-apps-script FormsOnSubmit

### ISSUE THREAD

**Issue by ImJustMatt** [DefinitelyTyped/DefinitelyTyped#40273]
I'm not sure what the right way to support this is, but currently the interface to FormsOnSubmit is based on a Google Sheets event rather than a form event:

types/google-apps-script/google-apps-script-events.d.ts

If you refer to the Event Objects guide on Google, the Sheet will return a range on form submit, whereas the form returns a FormResponse object:

https://developers.google.com/apps-script/guides/triggers/events#google_forms_events

I think FormsOnSubmit should refer to the Form events, and something like SheetOnFormSubmit shoudl refer to the Sheet events.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
