### ISSUE TITLE
[@types/intercom-client] Typings for message in Client

### ISSUE THREAD

**Issue by malithrw** [DefinitelyTyped/DefinitelyTyped#40346]
- [x] I tried using the `@types/intercom-client]` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jineshshah36, @peping, @mikhail-monchak, @cdoe

Missing type definitions for message.

https://github.com/intercom/intercom-node/blob/master/lib/client.js#L14
https://developers.intercom.com/intercom-api-reference/reference#user-or-contact-initiated-conversation

**Comment by jineshshah36** [comment]
I can't speak for the other authors, but I contributed because we needed the types for our own projects. I don't work for Intercom. If there are types missing, I'd suggest sending a pull request.

**Comment by vongohren** [comment]
@jineshshah36 that is a great suggestion, but if you are not that well versed in typescript and just learning how it works, sending a pull request on someone elses type is a daunting task 😄

**Comment by malithrw** [comment]
Sorry for the delay. I have created a PR with the necessary definitions for the Messages. This is my first time writing definitions for a package. So pardon me if there are any mistakes. @jineshshah36 

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43485

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
