### ISSUE TITLE
[@types/node] Missing Promise.allSettled definition

### ISSUE THREAD

**Issue by TranquilMarmot** [DefinitelyTyped/DefinitelyTyped#40366]
- [x] I tried using the `@types/node` package and had problems.

This is mentioned in by @SimonSchick  in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38401 

>  I'm concerned causing incompatibilities due to name/signature conflicts of types.

Currently, `@types/node` at `12.12.7` does not have definitions for `Promise.allSettled`

**Comment by SimonSchick** [comment]
Gotta wait for new libs, alternatively you can just write your own version by extending the definition of `Promise` until we get an official one :)

**Comment by joebowbeer** [comment]
How long must we wait?

The promise extension (workaround) would be something like the following [from SO]( https://stackoverflow.com/a/60276174/901597)?

```
declare interface PromiseConstructor {
    allSettled(promises: Array<Promise<any>>): Promise<Array<{status: 'fulfilled' | 'rejected', value?: any, reason?: any}>>;
}
```

Also see: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/promise.allsettled

**Comment by danilofuchs** [comment]
`Promise.allSettled` is defined via Typescript when using `lib: ["es2020"]`.

`@types/node` is not responsible for defining the `Promise` interface.

The issue is that Node 12 does not support `es2020` fully, so using `lib: es2020` can mean some APIs are exposed to Typescript which will not be available during runtime.

Personally, I will migrate all my projects to Node 14, which supports `es2020` completely
