### ISSUE TITLE
[@types/node] Optional functions

### ISSUE THREAD

**Issue by sanji-programmer** [DefinitelyTyped/DefinitelyTyped#40376]
- [X] I tried using the `@types/node` package and had problems.
- Authors: @SimonSchick

Hi, I found two cases where a function is actually optional (it exists depending on platform or functions used). 

Function lchmod only works in MacOS: 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/949922e0959ccea0cad7a6fa787b63b7d4e67d3f/types/node/fs.d.ts#L397

An object ChildProcess will have the send functions only if it is returned from a fork:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/949922e0959ccea0cad7a6fa787b63b7d4e67d3f/types/node/child_process.d.ts#L22

Could these cases be specified in TS declaration files?

**Comment by SimonSchick** [comment]
I think making `lchmod` with `?` should suffice, this will require developers to assert it's existence.
The second one I am already aware of and I plan to include those changes for node v13 (and potentially backport).

**Comment by sanji-programmer** [comment]
thanks @SimonSchick I'm glad to help!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
