### ISSUE TITLE
Property 'defaultProps' does not exist on type ConnectedComponent

### ISSUE THREAD

**Issue by gmukul01** [DefinitelyTyped/DefinitelyTyped#40382]
**What is the current behavior?**

Property 'defaultProps' and children does not exist on type ConnectedComponent.

![image](https://user-images.githubusercontent.com/3636885/68855506-5b39ce00-0704-11ea-83cb-bdf9b7601c1c.png)
![image](https://user-images.githubusercontent.com/3636885/68855519-62f97280-0704-11ea-9ab4-20baebe619b0.png)

**What is the expected behavior?**

It should have expected types.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
