### ISSUE TITLE
braintree-web types file missing module @braintree-web/paypal-checkout

### ISSUE THREAD

**Issue by yeukyul** [DefinitelyTyped/DefinitelyTyped#40404]
@guy-shahine The types file for braintree-web is missing the module @braintree-web/paypal-checkout. Can we add that in?

See the [braintree github page](https://braintree.github.io/braintree-web/current/PayPalCheckout.html) for the documentation on this module.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
