### ISSUE TITLE
[@types/next] installs a conflicting version of next-server

### ISSUE THREAD

**Issue by cole-kerr-ef** [DefinitelyTyped/DefinitelyTyped#40403]
- [X] I tried using the `@types/next` package and had problems.
- Authors: @brikou, @jthegedus, @resir014, @scottdj92, @joaovieira, @ajliv

On Nov. 12th 2019, @types/next was upgraded to v9.0.0

As soon as we built our app (some time after), we ran into the following error:

`TypeError: Cannot read property 'publicRuntimeConfig' of undefined`

For background - we currently use next.js v8.0.3 across our monorepo, therefore we also rely on @types/next to provide the missing types.  We are only sourcing `publicRuntimeConfig` from a call to `getConfig`, which we import straight from `"next/config"`

We eventually realized that @types/next was installing its own next-server (v9.0.5) among other things. We then added the following yarn resolution to our own monorepo's root package.json (where we list @types/next as a devDependency), and the problem went away:
`"@types/next/**/next-server": "8.0.3"`
Is there a more appropriate long-term solution for this, either from the package's end or from ours?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
