### ISSUE TITLE
In snapsvg.d.ts: Snap.set() is missing

### ISSUE THREAD

**Issue by martinvicha** [DefinitelyTyped/DefinitelyTyped#4043]
I noticed that `Snap.set()` definition is missing in `snapsvg/snapsvg.d.ts`:

Missing in module `Snap`:
`export function set(): Set;`

Could, you, please, confirm?

Thanks.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
