### ISSUE TITLE
Angular ILocationService.search() should be not any;

### ISSUE THREAD

**Issue by Glutnix** [DefinitelyTyped/DefinitelyTyped#40472]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4962164b760b29b0182d853385c456c9ed7a44c4/types/angular/index.d.ts#L1020

```
        /**
         * Return search part (as object) of current url
         */
        search(): any;
```

Should this be `{ [key: string]: any }``` or `{ [key: string]: string }` ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
