### ISSUE TITLE
[@types/react-adal] getCachedToken() can return null

### ISSUE THREAD

**Issue by justrhysism** [DefinitelyTyped/DefinitelyTyped#40515]
Despite the JSDoc indicating otherwise, the `getCachedToken()` method can return `null` as seen on this line:

https://github.com/salvoravida/react-adal/blob/d8596750a2cd5b5ad70d006a730bc2390e29b818/src/adal.js#L428

Typing to be updated:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c4317350aafe716a44db30061310ce504abdb4f9/types/react-adal/index.d.ts#L209

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
