### ISSUE TITLE
[@types/lodash/fp] CurriedFunction1 result matches LoDashStatic

### ISSUE THREAD

**Issue by cnwangjie** [DefinitelyTyped/DefinitelyTyped#40548]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel, @chrootsu, @stepancar, @aj-r, @Ailrun, @e-cloud, @thorn0, @jtmthf, @DomiR

If you do not mention the authors the issue will be ignored.

----

Hi, I am trying to add some type definitions for my code. But I encountered some confusion.

The type of `t` is `CurriedFunction1`. I passed it to the second parameter of the update like the following codes.

```ts
const t = _.curryN(2, _.ary(2, _.concat))
_.update('a', t([2]), {a: [1]})
```

But the editor tells me the return value of it is LodashUpdate1x5.

```ts
(path: lodash.PropertyPath, updater: lodash.__, object: object): LodashUpdate1x5;
```

I think he should be matching the following declaration.

```ts
(path: lodash.PropertyPath, updater: (value: any) => any, object: object): any;
```

Looks like `const t = _.curryN(2, _.ary(2, _.concat))` matches `LoDashStatic`.

----

In addition, why it doesn't use generics to define the input functions? But use `(value: any) => any`?

**Comment by aj-r** [comment]
`LodashUpdate1x5` sounds strange. Are you using `lodash/fp`?

**Comment by cnwangjie** [comment]
> `LodashUpdate1x5` sounds strange. Are you using `lodash/fp`?

@aj-r Yes. Some functions wrapped by lodash/fp cannot match with `(value: any) => any` so that I get a typescript error and I have to use type assertion for the function. Is it possible to get an improvement?

**Comment by aj-r** [comment]
Interesting - `lodash.__` (which is just an alias for `LoDashStatic`) is meant to act as a placeholder, and I'm not sure why `t([2])` matches that. (Sorry I know that's not a helpful answer, but I'm just as puzzled as you are.)

I feel like we should re-order the overloads so the non-placeholder overloads are first. However I'm not sure if that would break things (i.e. would `lodash.__` incorrectly match `(value: any) => any`?).
If that doesn't work, maybe we could change the type of `lodash.__` to be something crazy like `{__lodashPlaceholder:true}` so it can't possibly match things it's not supposed to. It's not technically accurate, but I think it should be fine since nobody should use `lodash.__` as anything but a placeholder anyways.

As for why we use `(value: any) => any`, it's because there's really no way to know what the correct property type is. For example, if the property path is `'x[0].y.z'`, we can't parse that at compile time. 
For simple property types (like `'a'` in your case), we might be able to use that with a few extra overloads (kind of like we do for `_.get`), but I guess `_.update` is not very popular so nobody has bothered to do it. Feel free to submit a PR - if you do, then note that the `lodash/fp` types are auto-generated based on the plain lodash types.

**Comment by cnwangjie** [comment]
@aj-r  Thank you for your reply. You are right. If re-ordered the overloads, `lodash.__` will match `(value: any) => any`. 

I found the reason for my situation:
```ts
_.ary(2, _.concat)
```
=>
```ts
(n: number, func: (...args: any[]) => any): (...args: any[]) => any;
```

and

```ts
_.curryN(2, _.ary(2, _.concat))
```
=>
```ts
<T1, R>(arity: number, func: (t1: T1) => R): lodash.CurriedFunction1<T1, R>;
```
its value is
```ts
CurriedFunction1<any, any>
```
so, `t([2])` returns `any`

Maybe `ary` needs a more detailed type definition. Otherwise we can only assert it when calling it.

Besides, `LoDashStatic` includes `(value: any) => any`. So we can only put `LoDashStatic` before `(value: any) => any`.

Further, I think that we can use `Lodash.Function1` to replace `(value: any) => any`. It is good if the function with type passed in it. If not, you can also specify generics manually.

----

Another problem, I tried to make some changes, but I got an error when I run `npm run lint lodash `:

```
The 'use-default-type-parameter' rule threw an error in '.../DefinitelyTyped/types/lodash/lodash-tests.ts':
TypeError: Cannot read property 'default' of undefined
```

**Comment by aj-r** [comment]
Ok that makes sense. We can probably improve the type for a lot of lodash's function manipulations (including `ary`) in TS3.1 thanks to `Parameters<>` and `ReturnValue<>`.

That's a strange error that I've never seen before. I wish it gave a line number...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
