### ISSUE TITLE
[@types/mongodb] FilterQuery validation fails on generic record type

### ISSUE THREAD

**Issue by helios1138** [DefinitelyTyped/DefinitelyTyped#40584]
Authors: @CaselIT, @alanmarcell, @bitjson, @dante-101, @mcortesi, @EnricoPicci, @AJCStriker, @julien-c, @daprahamian, @denys-bushulyak, @BastienAr, @sindbach, @geraldinelemeur, @jishi, @various89, @angela-1, @lirbank, @hector7, @floric, @erikc5000, @Manc, @jloveridge, @ranguna, @HosseinAgha, @albertossilva, @Rauno56

this code illustrates the issue:
```ts
async function test<T extends { _id: ObjectId }>(
  id: T['_id'],
  collection: Collection<T>,
) {
  const record = await collection.findOne({ _id: id })
}
```
seems to me like a perfectly valid code, but `findOne({ _id: id })` is failing with an error
```
Error:(22, 41) TS2345: Argument of type '{ _id: T["_id"]; }' is not assignable to parameter of type 'FilterQuery<T>'.
  Type '{ _id: T["_id"]; }' is not assignable to type '{ [P in keyof T]?: MongoAltQuery<T[P]> | QuerySelector<MongoAltQuery<T[P]>> | undefined; }'.
```

**Comment by CaselIT** [comment]
I think this is the same problem of #39358.
It seems due to a bug of typescript. See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/39358#issuecomment-546559564

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by MansourWolou** [comment]
$
