### ISSUE TITLE
[@types/styled-components] Setting the `as` prop using `defaultProps`

### ISSUE THREAD

**Issue by timswalling** [DefinitelyTyped/DefinitelyTyped#40635]
- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] ~~I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).~~
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

Firstly, thanks to @Igorbek, @Igmat, @lavoaster, @Jessidhia, @jkillian, @eps1lon, @flavordaaave and @wagerfield for all your hard work on this.

I'm using:
- `"@types/react": "^16.9.13"`
- `"@types/styled-components": "^4.4.0"`
- `"typescript": "^3.7.2"`

I'm trying to set the `as` prop using `defaultProps`, but I'm running into two issues. Here's the code I'd like to write:

```jsx
const Button = styled.button`
  /* Button styles go here */
`;

const Anchor = styled(Button)``;

Anchor.defaultProps = {
  as: "a"
};
```

Here's the code I actually need to write:

```jsx
const Button = styled.button`
  /* Button styles go here */
`;

type AnchorProps = React.AnchorHTMLAttributes<HTMLAnchorElement>;

const Anchor = styled(Button)<AnchorProps>``;

Anchor.defaultProps = {
  as: "a"
} as object;
```

The first issue is that I'm unable to provide an `as` prop using `defaultProps` without casting to a looser type (eg `object` in the example above): I get the error that
```
Object literal may only specify known properties, and 'as' does not exist in type 'Partial<Pick<Pick<Pick<DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "form" | ... 264 more ... | "value"> & { ...; } & AnchorProps, "form" | ... 273 more ... | "value"> & Partial<...>, "form" | ... 273 more ... | "value"> & { ...; }>'.
```

The second has been discussed in #35143 (and workaround provided), but I don't think it's really been resolved: why is it necessary to explicitly include the props from the `as` component (eg `AnchorProps` in the example above)? They appear to be inferred correctly when the `as` prop is explicitly defined (eg `<Button as="a" {...props} href="/example-path" />` works correctly), just not when provided via `defaultProps`. And if it's a limitation due to TypeScript's handling of `defaultProps`, is there a simpler way setting them?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
