### ISSUE TITLE
node_modules/@types/sequelize/index.d.ts(38,8): error TS1192: Module '"validator"' has no default export.

### ISSUE THREAD

**Issue by avipunes** [DefinitelyTyped/DefinitelyTyped#40644]
since version 4.28.8, this error occurs while npm i

**Comment by louy** [comment]
Try updating `@types/validator@12`. The signature has changed between v10 and v12, and I think the sequelize package is now only compatible with v12

**Comment by intellix** [comment]
I've actually had the opposite. `npm i @types/validator@10` is what worked for me

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
