### ISSUE TITLE
react-window-infinite-loader: Impossible to ES6-style import InfiniteLoader when "allowSyntheticDefaultImports" is set to false

### ISSUE THREAD

**Issue by dmarcautan** [DefinitelyTyped/DefinitelyTyped#40661]
`import InfiniteLoader from "react-window-infinite-loader";` will result in compilation error 

> Module '".../node_modules/@types/react-window-infinite-loader/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
