### ISSUE TITLE
[@types/gremlin] Translator only accepts 'TraversalSource' but for Azure Cosmos DB you must pass 'g' as string to work

### ISSUE THREAD

**Issue by sebastiangug** [DefinitelyTyped/DefinitelyTyped#40671]
The title sums it up.

**Comment by michaelbats** [comment]
Related to PR#40672

**Comment by michaelbats** [comment]
#40672

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
