### ISSUE TITLE
[@types/tabulator-tables] the newest typescript 3.7.2 error: is not a module.

### ISSUE THREAD

**Issue by zhfjyq** [DefinitelyTyped/DefinitelyTyped#40711]
when i use typescript in vscode, version:3.7.2, it say "/@types/tabulator-tables/index.d.ts' is not a module .Vetur(2306)."

add "export default Tabulator;" to 'index.d.ts' can resloved it.
thanks!

**Comment by cbianco96** [comment]
Just wanted to re-up this issue. Still present in Typescript version 3.7.5

**Comment by BrianJVarley** [comment]
@cbianco96 That fix won't work if you need to run your project through a CI pipeline. Due to your local change to `index.d.ts ` not being on the build server.

But you can override Tabulator's index file by adding your own custom typings to your project .Including the modified `index.d.ts` file in src/@types/tabulator-tables. For example:
```
"typeRoots": ["src/@types", "node_modules/@types"],
```
See: https://www.detroitlabs.com/blog/2018/02/28/adding-custom-type-definitions-to-a-third-party-library/

**Comment by jgroth** [comment]
I've been struggling with this as well for a while, and finally got it to work. Had to do the following:

Added the following to `tsconfig.json` as suggested above.
```
"typeRoots": ["types", "node_modules/@types"],
```

Created a `types/tabulator-tables/index.d.ts` file that looks like this
```ts
declare module "tabulator-tables" {
    export default Tabulator;
}
```

In my code, I could then just do the following 

```ts
import TabulatorTable from 'tabulator-tables';

const table = new TabulatorTable("#element", {});
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
