### ISSUE TITLE
[@types/emoji-mart] Typing of CustomIcons too strict

### ISSUE THREAD

**Issue by abustany** [DefinitelyTyped/DefinitelyTyped#40734]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Jessidhia @Nicell @elvis-wolcott 

Reading [the documentation](https://github.com/missive/emoji-mart#custom-icons), it seems that the type of the `CustomIcons` interface should be "relaxed" from

```typescript
export interface CustomIcons {
    categories: Record<CategoryName, () => React.Component>;
}
```

to something like

```typescript
export interface CustomIcons {
    categories: Record<CategoryName, () => HTMLElement>;
}
```

I can prepare a PR if you think this is the way to go

**Comment by Nicell** [comment]
Sorry for the late review here. You're right here that it seems too strict. I think possibly this would be a `JSX.Element` rather than an `HTMLElement`? I believe when writing JSX it returns a `JSX.Element` instead of an `HTMLElement`.

**Comment by abustany** [comment]
No worries, thanks for taking the time to check this :) It looks like `React.ReactNode` is indeed the best solution here, as it also works with eg. a text fragment. Do you want me to whip up a PR, or will you take care of it?

**Comment by Nicell** [comment]
Yeah if you could make a PR that would be great!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
