### ISSUE TITLE
Is there any way to make a breaking change to type defs?

### ISSUE THREAD

**Issue by jedwards1211** [DefinitelyTyped/DefinitelyTyped#40736]
Not that I need to at the moment, but it's something that's always made me nervous about DT.

Let's say I realize that the type def for some class could be more precise if I add an additional type parameter without a default.  Since that change would cause compile errors for everyone, a new major version of the type defs would have to be released.

But since the type defs major/minor version is supposed to track the package major/minor version, releasing a new major version of the type defs is not possible.  This seems like a fairly significant shortcoming of version number tracking to me?  The only option is to wait for a new major version of the real package.

Having once adapted the very complex type defs for Sequelize from DT to Flow, with some structural changes, I can imagine the need to make breaking changes to type defs at times.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
