### ISSUE TITLE
[@types/react-highlight-words] Not able to import HighlighterProps interface

### ISSUE THREAD

**Issue by titenis** [DefinitelyTyped/DefinitelyTyped#40733]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ff69d22d5d124148da0a034711c573cf044f6a82/types/react-highlight-words/index.d.ts#L24

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
