### ISSUE TITLE
typescript-bot edits his comment every hour

### ISSUE THREAD

**Issue by falsandtru** [DefinitelyTyped/DefinitelyTyped#40743]
This wasteful process may adversely affect his response.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40731#issuecomment-559788420

**Comment by falsandtru** [comment]
@RyanCavanaugh

**Comment by falsandtru** [comment]
@RyanCavanaugh

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
