### ISSUE TITLE
jsPlumb implicit any

### ISSUE THREAD

**Issue by aschlosberg** [DefinitelyTyped/DefinitelyTyped#4074]
Library: jquery.jsPlumb
Interface: jsPlumbInstance
Property: bind

The callback argument of the bind function is implicitly any. I presume that is supposed to be an Event interface as follows.

`bind(event: string, callback: (e:Event) => void ): void;`

**Comment by vvakame** [comment]
@aschlosberg please send a PR. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
