### ISSUE TITLE
LICENSE file missing in @types/json5 npm package

### ISSUE THREAD

**Issue by MartisiusL** [DefinitelyTyped/DefinitelyTyped#40773]
Hello, is it possible to incorporate the LICENSE file inside the npm package and this repository ? Now it's missing. By definition your code is not proprietary and cannot be used. Can this be remedied please ?

Thank you

@Esemesek

**Comment by Esemesek** [comment]
Just checked and the `LICENSE` file is present in the latest version of the package. I think we can close this issue.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
