### ISSUE TITLE
@types/facebook-pixel trackSingle and trackCustom type support

### ISSUE THREAD

**Issue by VictorHom** [DefinitelyTyped/DefinitelyTyped#40786]
I am looking to use multiple facebook pixels on a page, and I believe that the current typings doesn't support that use case. Facebook wrote an article about it in https://developers.facebook.com/ads/blog/post/2017/11/28/event-tracking-with-multiple-pixels-tracksingle/

I believe a simple fix might be adding `(eventType:string, InitialAppId:string, eventName:string, parameters:InitiateCheckoutParameters):void;` to the `interface Event` in `@types/facebook-pixel/index.d.ts`

If you know how to fix the issue, make a pull request instead.

Currently using `"@types/facebook-pixel": "^0.0.19",`

@NoctisHsu was the original author and @vvakame for original review

happy to help out, but just wanted to check before figuring out how to set up a pr for this repo.

If you do not mention the authors the issue will be ignored.

**Comment by peterblazejewicz** [comment]
Closed via: #40801

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
