### ISSUE TITLE
@types/leaflet MarkerOptions does not have functionality to add custom data

### ISSUE THREAD

**Issue by soupay** [DefinitelyTyped/DefinitelyTyped#40787]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/leaflet` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

`       const marker = L.marker([position.latitude, position.longitude]);
        marker.options.status = "Late";
        marker.options.id ="ABCDE1234"r;
        marker.options.source = "Something";
        this.listLayer.addLayer(marker);
      }`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet/index.d.ts

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
