### ISSUE TITLE
@types/react-stripe-elements elements is missing on InjectedStripeProps

### ISSUE THREAD

**Issue by kutomer** [DefinitelyTyped/DefinitelyTyped#40799]
Hey,

I noticed that the "elements" prop is missing on the [InjectedStripeProps interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/807f5db1633cba3e7b90b11314fa5da469aac42d/types/react-stripe-elements/index.d.ts#L66), even though injectStripe is injecting it. ([as you can see here](https://github.com/stripe/react-stripe-elements/blob/91c465c95927dad429f9eba27398607dfdff2f2f/src/components/inject.test.js#L122))

Thanks, and appreciate your wonderful work :)

@dan-j @santiagodoldan @sonnysangha @9Y5 @tdreyno @yhnavein @virzak @remotealex @bombek92

**Comment by peterblazejewicz** [comment]
FYI: Closed via #40971 . Can be closed

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
