### ISSUE TITLE
enhanced-resolve types for v4 are missing

### ISSUE THREAD

**Issue by opl-** [DefinitelyTyped/DefinitelyTyped#40804]
`enhanced-resolve` v3 uses `tapable` v0, while `enhanced-resolve` v4 uses `tapable` v1. This makes it impossible to update the DefinitelyTyped types for `webpack` v4 to use the correct argument type for the `resolve.plugin` values.

As I'm not familiar with the changes between v3 and v4, I don't have the bandwidth to update the types.

Creating this issue to allow tracking. Mentioning @e-cloud, @onigoetz and @johnnyreilly for prominence.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
