### ISSUE TITLE
[@types/stripe] PaymentIntent has a few issues

### ISSUE THREAD

**Issue by tony-simplifeye** [DefinitelyTyped/DefinitelyTyped#40856]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @a904guy, @ejsmith, @amritk, @adamcmiel, @jleider, @galuszkak, @slangeder, @marlosin, @ttmarek, @kimehrenpohl, @KrishnaPravin 

The type definition for PaymentIntent has a few issues outlined below for Stripe v2019-12-03 and @types/stripe-v3: ^3.1.9:

1. Cancellation reason is misspelled

Expected:
`cancellation_reason: PaymentIntentCancelationReason | null;`

Actual:
`cancelation_reason: PaymentIntentCancelationReason | null;`

2. Missing three other parameters: payment_method_options, setup_future_usage, statement_descriptor_suffix.

I should be able to submit a PR for this sometime next week but wanted to track it here first

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
