### ISSUE TITLE
[@types/react-query] Incorrect Type on Props for canGetFetchMore

### ISSUE THREAD

**Issue by litewarp** [DefinitelyTyped/DefinitelyTyped#40899]
I get a type error when using the `@types/react-query` package with the paginated canGetFetchMore function.

The type for QueryOptionsPaginated defines the props for canGetFetchMore (lastPage, allPages) as numbers:

```
export interface QueryOptionsPaginated<TResult> extends QueryOptions<TResult> {
    paginated: true;
    getCanFetchMore: (lastPage: number, allPages: number) => boolean;
}
```

But the source shows that the full data object for lastPage and allPages is sent as the props to canGetFetchMore:

```
...(query.config.paginated && {
                canFetchMore: query.config.getCanFetchMore(
                  data[data.length - 1],
                  data
                ),
```

Similarly, in the paginated examples, the tutorial shows the nextId prop being passed in lastPage to the fetch function, which wouldn't make sense if the prop is a number:

```
    {
      paginated: true,
      getCanFetchMore: (lastPage, allPages) => lastPage.nextId,
    }
```

Thanks!

@bostondv @lukaszfiszer @tannerlinsley

**Comment by lukaszfiszer** [comment]
Indeed, the two arguments passed to `getCanFetchMore` in paginated mode should be of `TResult` and `TResult[]` types.

Would you mind sending a PR?

**Comment by ghostd** [comment]
We can close this issue?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
