### ISSUE TITLE
mongodb.DbAddUserOptions type define error

### ISSUE THREAD

**Issue by jikhww** [DefinitelyTyped/DefinitelyTyped#40907]
export interface DbAddUserOptions extends CommonOptions {
    customData?: object;
    roles?: object[];
}

the roles should be string[]

**Comment by jikhww** [comment]
many  items define object type,are you kiding me?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
