### ISSUE TITLE
[@types/react-query]: QueryResultPaginated is not correctly typed 

### ISSUE THREAD

**Issue by litewarp** [DefinitelyTyped/DefinitelyTyped#40911]
Using the QueryResultPaginated type on a paginated query results in an error.  

Type:
```
  const fetchOptions: QueryOptionsPaginated<{ page?: number }> = {
    paginated: true,
    // use any instead of TResult until PR gets merged
    getCanFetchMore: (lastPage: any) => lastPage && !!lastPage.next
  };

  const query: QueryResultPaginated<ApiData, { page?: number }> = useQuery(
    "getData",
    ({ page }: { page?: number } = {}) =>
      customFetch("https://api.endpoint/?page=" + (page || 1)),
    fetchOptions
  );

```
Error:
```
Type 'QueryResult<{ page?: number; }, { page?: number; }>' is missing the following properties from type 'QueryResultPaginated<ApiData, { page?: number; }>': isFetchingMore, canFetchMore, fetchMorets(2739)
```

Here's a [CodeSandbox](https://codesandbox.io/s/recursing-chatelet-iw82l) reproducing the issue.
 
- Authors: @lukaszfiszer

**Comment by mustafawm** [comment]
has this been fixed by now?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
