### ISSUE TITLE
Event.detail is missed from React.MouseEvent 

### ISSUE THREAD

**Issue by Teleology** [DefinitelyTyped/DefinitelyTyped#40925]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/react` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @zieka @andrewbranch

my current solution is like this 
(mouseEvent as any).detail > 1

detail property does not exist on React.MouseEvent
but actually Mouse Event has this property

**Comment by peterblazejewicz** [comment]
It's part of the more generic UIEvent, not MouseEvent:
https://reactjs.org/docs/events.html#ui-events

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
