### ISSUE TITLE
[@types/ioredis] return type for hgetall is Promise<string[]>!

### ISSUE THREAD

**Issue by MassiveFermion** [DefinitelyTyped/DefinitelyTyped#40938]
It seems that in the new version, the return type for hgetall is Promise<string[]> but it actually returns an object. In the previous version it was Promise\<any\> and it worked fine. I didn't make a pull request because I wasn't sure whether any is acceptable or not but it definitely should not be string or string[].
Thanks

@plantain-00 
@chrisleck
@aliarham11 
@br8h 
@shaharmor 
@reconbot 
@iamolegga 
@tingwai-to 
@pettyalex 
@SimonSchick

**Comment by SimonSchick** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40887 for some work, feel free to fix this individual instance tho.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
