### ISSUE TITLE
[@types/sinon-chai] Incompatibility with @types/chai 3.x

### ISSUE THREAD

**Issue by hiranya911** [DefinitelyTyped/DefinitelyTyped#40956]
- [x] I tried using the `@types/sinon-chai` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

v2.7.36 of `@types/sinon-chai` is not compatible with v3.x of `@types/chai`. If we go back one patch version to v2.7.35 everything is fine. The problem seems to be that v2.7.36 has the following line:

```
declare const sinonChai: Chai.ChaiPlugin;
```

The `ChaiPlugin` type has been introduced  recently in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37451 and is not available in `@types/chai` 3.x releases.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
