### ISSUE TITLE
Update JQuery def for current version (3.4.1)

### ISSUE THREAD

**Issue by adampenn** [DefinitelyTyped/DefinitelyTyped#40953]
I am currently using @types/jquery@3.3.31 but it would be nice to have a updates type def for 3.4.1

Let me know if this is missing anything otherwise its just a note that this needs to get done.

**Comment by leonard-thieu** [comment]
There were no new APIs introduced in 3.4. jQuery 3.5 did introduce `.even()`/`.odd()`. The [PR to update types to 3.5](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45618) has since been merged.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
