### ISSUE TITLE
[@types/styled-system] cannot use keys which are not CSS properties for font weight theming

### ISSUE THREAD

**Issue by biowaffeln** [DefinitelyTyped/DefinitelyTyped#40975]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc: 3.7.3
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @maxdeviant @phobon @zephraph @damassi @alloy @maoueh @lavoaster @jschuler @adam187 @gretzky @chrislopresto @peduarte @Dhalton @elliotbonneville @jackcaldwell @eliseumds @craga89 @HipsterBrown
If you do not mention the authors the issue will be ignored.

I have the following setup, with a Box component:
```ts
export const Box = styled.div<TypographyProps>(
  typography
);
```
a theme:
```ts
export const theme = {
  fontWeights: {
    hairline: "100",
    thin: "200",
    light: "300",
    normal: "400",
    medium: "500",
    semibold: "600",
    bold: "700",
    extrabold: "800",
    black: "900"
  }
}
```
and I'm trying to use it like this:
```tsx
<Box fontWeight="light" />
```
However, the above line gives me the following typescript error:
```
 Type '"light"' is not assignable to type 'ResponsiveValue<FontWeightProperty>'.
```

It looks like I can only use keys of type ```FontWeightProperty``` for my font weights. I do feel like using arbitrary names for my font weights is a sensible use case that should be supported. Is there a way to extend the type definition to use the keys of the ```fontWeights``` object from the theme? Alternatively, maybe one could simply type it as ```ResponsiveValue<FontWeightProperty | string>``` ?

**Comment by jackcaldwell** [comment]
This seems reasonable enough to me. Would be interested in getting others thoughts, but I'd say go ahead and open a PR for now.

**Comment by Craga89** [comment]
Would it not make more sense to simply type those yourself instead of using
the TypographyProps? Something like:

```
interface Props {
   fontWeight: typeof theme["fontWeights"]
}
```

That way you gain type safety defined by the structure of your theme? If
you need to use other TypographyProps types you can just extend it and omit
ones you're providing yourself.

------------------------------------------------------

Craig Michael Thompson
Full-stack Developer
Website: https://craigsworks.com
Phone: 07878062458

**Comment by Craga89** [comment]
Would it not make more sense to simply type those yourself instead of using the TypographyProps? Something like:

```typescript
interface Props {
   fontWeight: typeof theme["fontWeights"]
}
```

That way you gain type safety defined by the structure of your theme? If you need to use other TypographyProps types you can just extend it and omit ones you're providing yourself.

**Comment by biowaffeln** [comment]
@Craga89
What tripped me off was the fact that using arbitrary keys worked for every other type of props that I tried (since they're all typed something along the lines of ```ResponsiveValue<number | string>```), except for FontWeight, which makes the API sort of inconsistent.


But I like your suggestion! I was thinking about it and created a similar effect via declaration merging:

```ts
declare module "styled-system" {
  interface TypographyProps {
    fontWeight?: keyof typeof theme["fontWeights"];
  }
}
```
which gave me really nice autocomplete for my fontWeight prop!

I was inspired by a similar setup for styled-components referenced here: https://github.com/styled-components/styled-components-website/issues/447. I was wondering, would this strategy (merging with a base theme, so that prop types can be derived from the shape of your theme) be possible for styled-system? Something along the lines of
```ts
import theme from "./theme";

type MyTheme = typeof theme;

declare module "styled-system" {
  export interface Theme extends MyTheme {}
}
```
and then deriving the prop types from that theme?

@jackcaldwell For now I can create a PR for the first simple fix if you guys are onboard. I'd also be interested to hear your opinions on the above approach, and if you think it would be feasible as well.

**Comment by Craga89** [comment]
I'd be careful using declaration merging on the `TypographyProps`, since these keys are specific to your theme and not the overall types in all cases.

The second approach seems reasonable, and I actually think it's already doable as the types stand. I'm just not sure what the value is since the Theme export isn't used anywhere currently, unlike `styled-components` which actually consume it

**Comment by casimcdaniels** [comment]
@biowaffeln @Craga89,

Any developments in this area? The lack of typing on arguments makes styled-system feel lackluster within the typescript environment.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
