### ISSUE TITLE
Plugin doesn't preserve library interface

### ISSUE THREAD

**Issue by musicist288** [DefinitelyTyped/DefinitelyTyped#4098]
I'm trying to write a definition file for the Leaflet.MarkerCluster plugin, however there's an inconsistency in an overridden method's return type. 

The `eachLayer` interface in `MarkerClusterGroup`
(https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L349) 

is different than the `eachLayer` interface defined in `LayerGroup`
(https://github.com/borisyankov/DefinitelyTyped/blob/master/leaflet/leaflet.d.ts#L1683).

because they do not have the same return value.   To extend the interface such that the compiler does not complain, I can put either of the following:

`eachLayer(method: (layer: L.ILayer) => void, context?: any): MarkerClusterGroup;`
`eachLayer(method: (layer: L.ILayer) => void, context?: any): any`

The first  is technically incorrect since the extended version returns undefined and the second doesn't seem very helpful.

What's the best way to proceed in this case?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
