### ISSUE TITLE
Can't import leaflet types when working on Server Side rendering

### ISSUE THREAD

**Issue by victorgarciaesgi** [DefinitelyTyped/DefinitelyTyped#41086]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/leaflet` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @alejo90 
 @atd-schubert  
@mcauer  
@ronikar 
@SanFrisc 
@life777 

I'm not importing any logic from leaflet, just types

```typescript
import { LatLngBoundsLiteral, LatLngBounds, LatLngExpression, LatLng } from 'leaflet';
```

And in Nuxt.js, even though I've setup all config for using Leaflet on server side (It was perfectly working before importing types), I have a 'window is undefined' error

![image](https://user-images.githubusercontent.com/15092120/70994607-e83ec100-20ce-11ea-8264-eff3b590f7e5.png)

**Comment by kygoh** [comment]
At present leaflet is not developed for server side use. Read this [explanation in github/leaflet](https://github.com/Leaflet/Leaflet/pull/6715#issuecomment-537656504) and probable workaround.

**Comment by victorgarciaesgi** [comment]
@kygoh With Nuxt.js it's possible to have leaflet working in server side, I had no problem with this error until I imported the explicit types

**Comment by kygoh** [comment]
I'm not familiar with Nuxt.js but for Leaflet to run on server side there are many "fixes" that have to be made as explained in this article [Building a Server-Rendered Map Component](https://medium.com/@pimterry/building-a-server-rendered-map-component-part-2-using-client-side-libraries-6f1bb751f31c). The problem you faced appears to be the first issue described in that article.

I think the issue you are facing is related to leaflet, rather than @types/leaflet.

**Comment by kygoh** [comment]
> @kygoh With Nuxt.js it's possible to have leaflet working in server side, I had no problem with this error until I imported the explicit types

Probably the "fake" window object from one of Nuxt.js dependencies hasn't been defined when you imported the explicit types.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
