### ISSUE TITLE
[@types/react] Type inference for JSX attributes doesn't work if propTypes and defaultProps are both defined

### ISSUE THREAD

**Issue by zhzz** [DefinitelyTyped/DefinitelyTyped#41112]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ferdaber @Jessidhia @matt-tingen

Hello, guys! 

I've discovered that after the #34386 (16.8.13) some of my components stopped to infer types for their attributes correctly as they did before. You can see the case in my minimal repro [zhzz/types-react-issue](https://github.com/zhzz/types-react-issue).

The issue occurs only when both propTypes and defaultProps are defined.

```tsx
import * as React from 'react';

interface Props<T> {
  value: T;
  onChange: (v: T) => T;
}

export class Component<T> extends React.Component<Props<T>> {
  public static defaultProps = {};
  public static propTypes = {};
}

// Parameter 'v' implicitly has an 'any' type.
export const Example = () => <Component value={1} onChange={v => v} />;
```

There is no error in 16.8.12. 

I keep trying to dig the particular reason but have no luck so far.

**Comment by ferdaber** [comment]
It's because of how `JSX.LibraryManagedAttributes` works. It will try to "merge" to the best of its ability your props interface along with `defaultProps` and `propTypes`. I have a feeling that because your `defaultProps` and `propTypes` are empty types, it just screws with the rest of the inferred types. I would suggest that you omit it entirely if you won't be filling in the types.

**Comment by zhzz** [comment]
@ferdaber thank you for the answer!

The problem is we actually do fill these types. And the result is the same. 
```tsx
export class Component<T> extends React.Component<Props<T>> {
  public static defaultProps = {
    value: 0
  }
  public static propTypes = {
    onChange: PropTypes.func,
  }
}
```

**Comment by ferdaber** [comment]
Oh I just realized, it might be because your component is generic. Can you try to see if the same happens if your component is not generic?

**Comment by zhzz** [comment]
Yes, it does work if the component is not generic.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
