### ISSUE TITLE
[@types/jsdom] Please update to include MutationObserver

### ISSUE THREAD

**Issue by kwasimensah** [DefinitelyTyped/DefinitelyTyped#41117]
https://github.com/jsdom/jsdom/pull/2398 Added a MutationObserver implementation to jsdom and it hasn't made it way to Typescript yet.

Mentioning: @leonard-thieu  and @palmenhq

**Comment by palmenhq** [comment]
Thanks for the ping, I’ll take a look asap

**Comment by palmenhq** [comment]
Just double-checking, you're missing `MutationObserver` on jsdom's [`Window`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/33fad18d0fd6c4789726bce85635a9f749612100/types/jsdom/ts3.1/index.d.ts#L118) object or? Since its [part of TS's DOM lib](https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L10777-L10792).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
