### ISSUE TITLE
Add AdsApp definitions to google-adwords-scripts

### ISSUE THREAD

**Issue by Shinigami92** [DefinitelyTyped/DefinitelyTyped#41123]
- [x] I tried using the `@types/google-adwords-scripts` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [x] Mention the authors, so they can respond
  - Authors: @jafaircl 

I think there are some new `interface`s like AdsApp (may be an alias to `AdWordsApp`?) that can be used and are not defined in `@types/google-adwords-scripts`

**Comment by jsbrain** [comment]
Push

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
