### ISSUE TITLE
BackgroundTaskBuilder class is missing cancelOnConditionLoss property (winrt.d.ts)

### ISSUE THREAD

**Issue by alexarg** [DefinitelyTyped/DefinitelyTyped#4114]
It appears to be a Boolean property. Please see the doc here:

https://msdn.microsoft.com/en-us/library/windows/apps/windows.applicationmodel.background.backgroundtaskbuilder.cancelonconditionloss.aspx

**Comment by vvakame** [comment]
@alexarg please send a PR. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
