### ISSUE TITLE
[@types/react-query] initialData not typed

### ISSUE THREAD

**Issue by skrivitsky** [DefinitelyTyped/DefinitelyTyped#41187]
There is `initialData` in config, but it's not covered with TS
  - Authors: @lukaszfiszer , @JaceHensley

**Comment by JaceHensley** [comment]
I'd be happy to approve a PR for that 😃

**Comment by lukaszfiszer** [comment]
Fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41208. 

This issue can be now closed

**Comment by luanlucho** [comment]
Hey guys not sure if this was already solved and is going to be released soon. 

initialData is typed however the result of useQuery's data is mark as (T | undefined) when it should not be undefined anymore since it was initialised.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
