### ISSUE TITLE
@types/gapi.client.drive files.update missing 'name' property

### ISSUE THREAD

**Issue by elegos** [DefinitelyTyped/DefinitelyTyped#41212]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Bolisov @LWUsira @alexcason @sandersn 

Hello everyone,

I've noticed that the `name` field is missing from the update API definition(see [Google Drive API docs](https://developers.google.com/drive/api/v3/reference/files/update)). If you add the property and `@ts-ignore` the line, the code works as expected.

**Comment by HoldYourWaffle** [comment]
Shouldn't this be closed since #41213 was merged?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
