### ISSUE TITLE
maxDate cannot work

### ISSUE THREAD

**Issue by futurify-phuongkieu** [DefinitelyTyped/DefinitelyTyped#41241]
I cann't disable day in the future by set maxDate for DateRange

**Comment by peterblazejewicz** [comment]
Thanks for the feedback! Can you provide some more details? Which type def is that problem related to?
Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
