### ISSUE TITLE
The "additionalMetaSchemas" prop is absent in FormProps

### ISSUE THREAD

**Issue by Sumechoo** [DefinitelyTyped/DefinitelyTyped#41256]
- [✔] I tried using the `@types/react-jsonschema-form/1.6.6` package and had problems.
- [✔] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [✔] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  

The "additionalMetaSchemas" is used by schema form to pass metaschemas to the Ajv is absent in typedef.

Here is the PR with related change: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41257

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
