### ISSUE TITLE
please update nightwatch type definition to match latest version

### ISSUE THREAD

**Issue by ravi005e** [DefinitelyTyped/DefinitelyTyped#41275]
Can someone update the type definition of Nightwatch? thanks
it is urgent

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by vaibhavsingh97** [comment]
@ravi005e we had updated `@types/nightwatch` to the latest version. Feel free to create new issue, if you feel something is missing

**Comment by ravi005e** [comment]
I certainly don't see new version on repo still 2.0.6

"One day, I shall come back. Yes, I shall come back. Until then, there must
be no regrets, no tears, no anxieties. Just go forward in all your beliefs,
and prove to me that I am not mistaken in mine."
-Doctor Who (Hartnell)
Ravi Shanker
