### ISSUE TITLE
error TS2304: Cannot find name 'AudioContext'  while transpiling

### ISSUE THREAD

**Issue by autotel** [DefinitelyTyped/DefinitelyTyped#41301]
problems installing types from `@types/audio-context`. I have reviewed the code, but in the context of node js, the audio-context implementation is very strange (I am refering to the npm package in some other repository, not the declaration file)

Honestly I cannot be 100% sure this is not an error of my implementation.

Tsc version: 
* Local tsc is 3.5.3 (got it by running npx tsc -v)
* global tsc is 3.7.2 (got it by running tsc -v)

I expect that this types would be installed and simply work by doing `npm install --save-dev @types/audio-context`. It works but after that, the typescript never compiles because the compiler complains:

response after running `tsc -p`

```
node_modules/@types/audio-context/index.d.ts:32:69 - error TS2304: Cannot find name 'AudioContext'.

32 declare function getContext(options?: getContext.Options | number): AudioContext | null;
                                                                       ~~~~~~~~~~~~


Found 2 errors.
```

**Comment by AviVahl** [comment]
The tsconfig needs to specify "dom" in compilerOptions->lib in order for the AudioContext interface to be available.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
