### ISSUE TITLE
through.d.ts: Add missing "queue" function signature to ThroughStream interface

### ISSUE THREAD

**Issue by omaishar** [DefinitelyTyped/DefinitelyTyped#41320]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/through` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @AndrewGaspar 

The ThroughStream interface is missing the "queue" function signature.
Example:

A typed implementation of JSONStream.stringify():
```
import through = require("through");

// Needed due to missing "queue" signature:
type ExtendedThrough = through.ThroughStream & { queue: (s: string | null) => void };

export function stringify(open: string = "[\n", separator: string = ",", close: string = "\n]") {
  const indent = 0;

  let first = true;
  let anyData = false;

  const stream: through.ThroughStream = through(
    // tslint:disable-next-line: no-any
    data => {
      anyData = true;
      let json: string;
      try {
        json = JSON.stringify(data);
      } catch (err) {
        return stream.emit("error", err);
      }
      if (first) {
        first = false;
        (stream as ExtendedThrough).queue(open + json);
      } else {
        (stream as ExtendedThrough).queue(separator + json);
      }
    },
    () => {
      if (!anyData) {
        (stream as ExtendedThrough).queue(open);
      }
      (stream as ExtendedThrough).queue(close);
      (stream as ExtendedThrough).queue(null);
    }
  );

  return stream;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
