### ISSUE TITLE
No type defined for util.InspectOptions.stylize in @types/node

### ISSUE THREAD

**Issue by clar-cmp** [DefinitelyTyped/DefinitelyTyped#41324]
See: https://nodejs.org/api/util.html#util_custom_inspection_functions_on_objects

Would be nice to have some way of capturing the type of this method.

**Comment by SimonSchick** [comment]
See https://github.com/nodejs/node/blob/7babffbe6054754b733098c52786a23df4049a74/lib/internal/util/inspect.js#L248

This isn't really public API but I will try to get some type defs going for node v13.5

**Comment by clar-cmp** [comment]
Ah, I wasn't aware this was an unstable API, even though it showed up in the documentation. Good to know.

**Comment by SimonSchick** [comment]
passing `stylize` in the 2nd argument of `util.inspect` is unstable, the custom inspection function `stylize` (even tho it's the same thing) is not.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
