### ISSUE TITLE
[tapable@1] Port official tapable v2 typings to DefinitelyTyped's tapable v1 types?

### ISSUE THREAD

**Issue by opl-** [DefinitelyTyped/DefinitelyTyped#41380]
While working on #40722 I discovered [the official typings for tapable v2](https://github.com/webpack/tapable/blob/ffc660840d2814b00a3e5e00cecb09519136bd37/tapable.d.ts) and I feel that they are far better (at least in some aspects) than what we have in DefinitelyTyped, but they'd be incompatible with the current typings DT provides.

This raises several questions:
- Is porting the official tapable v2 typings to Definitely Typed to make them work with tapable v1, providing more flexible types for v1, something the DT project would be interested in?
- Should they instead be added to the official tapable repository (considering the webpack team seems to be happy to support TypeScript), making the DT typings redundant?
- If the first option was chosen, how would the process of releasing breaking changes to the typings be handled? Bumping the major would be confusing, as tapable v2 exists, and releasing them as a minor would likely break many projects.

@e-cloud, @johnnyreilly, @RyanCavanaugh

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
