### ISSUE TITLE
Can someone update /types/pulltorefreshjs

### ISSUE THREAD

**Issue by jeanpoelie** [DefinitelyTyped/DefinitelyTyped#41442]
The types version of pulltorefreshjs has not been updated in years, therefore we miss the distIgnore property

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @pateketrueke

**Comment by pateketrueke** [comment]
Hello @jeanpoelie I was notified on this but I'm unsure if I did the `.d.ts` from such project, looking at the code here seems like someone else (thank you!) submitted it.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pulltorefreshjs/index.d.ts#L3-L4

Can we reach them in order to update them accordingly? I'm not very familiar with, but if no response is back then I can try to update such definitions by hand.

Su much thanks for your input!

**Comment by bodinsamuel** [comment]
Tried to fix this in #42150 ☺️

**Comment by jeanpoelie** [comment]
Big 👍 for this one! I have been inactive due to work related distractions, thank you for this merge!
