### ISSUE TITLE
@types/node - http.d.ts - Server - Missing request event 

### ISSUE THREAD

**Issue by ShayBox** [DefinitelyTyped/DefinitelyTyped#41446]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick 

If you do not mention the authors the issue will be ignored.

<https://nodejs.org/api/http.html#http_event_request>

**Comment by bodinsamuel** [comment]
Tried to fix this in #42148 ☺️

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
