### ISSUE TITLE
Droppable Typescript renderClone react-beautiful-dnd

### ISSUE THREAD

**Issue by ariel-frischer** [DefinitelyTyped/DefinitelyTyped#41456]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @varHarrie  @bradleyayers @paustint @marknelissen @enricoboccadifuoco @lonyele @lukyth 

If you do not mention the authors the issue will be ignored.
I'm referencing [this issue](https://github.com/atlassian/react-beautiful-dnd/issues/1666) here because I'm getting the same error: 

> I'm using the 12.2.0 rbd version and react-beautiful-dnd": "^11.0.3 types.
> When I want to use renderClone method on Droppable component I have an error TS2769:
> Property 'renderClone' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Droppable> & Readonly<DroppableProps> & Readonly<...>'.
> I checked the index.d.ts and this method is not typed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
