### ISSUE TITLE
angular-file-upload.d.ts bad file attribute definition

### ISSUE THREAD

**Issue by nfantone** [DefinitelyTyped/DefinitelyTyped#4145]
`angular-file-upload.d.ts` declares `IFileUploadConfig` as:

``` javascript
 interface IFileUploadConfig extends ng.IRequestConfig {

        file: File;
        fileName?: string;
    }
```

But `file` should really be: `file: File | File[];` as per the [official documentation](https://github.com/danialfarid/ng-file-upload#upload-service):

> var upload = $upload.upload({
>   *url: 'server/upload/url', // upload.php script, node.js route, or servlet url
>   *file: file,  // single file or an array of files (array is for html5 only)
>   ...

**Comment by nfantone** [comment]
Nevermind: got repos mixed up. [angular-file-upload] (https://github.com/nervgh/angular-file-upload) is not [ng-file-upload](https://github.com/danialfarid/ng-file-upload). Go figure.

**Comment by nfantone** [comment]
I'm reopening this as it turns out I was right from the beginning. Also, this is rather confusing. The definition files found here seems to be from [ng-file-upload](https://github.com/danialfarid/ng-file-upload). The name of the definitions **do not match** the name of the module. 

Someone should take a look into this.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
