### ISSUE TITLE
[react-table]: Cannot specify className on column

### ISSUE THREAD

**Issue by JWess** [DefinitelyTyped/DefinitelyTyped#41452]
I'm not sure who to tag, but I think @ggascoigne could be the right choice?

Please see the issue I'm having where I cannot specify a `className` for a specific column:

https://github.com/tannerlinsley/react-table/issues/1640#issuecomment-571699971

Is this an issue with the typings?

**Comment by ggascoigne** [comment]
based on https://github.com/tannerlinsley/react-table/issues/1640#issuecomment-571699971, this isn't a bug.

Issue should be closed.

**Comment by vinnymac** [comment]
@JWess It can be a bit confusing because we have the `Column` type and also the `ColumnInstance` type. 

In the scenario you described in that comment you need to extend the `ColumnInstance` if you want to type the `column` property of the `cell`. So you can do `cell.column.className`. This is because the type of the column of the `Row` is `ColumnInstance`.

Try this
```ts
export interface ColumnInstance<D extends object = {}>
      extends Omit<Column<D>, 'id' | 'columns'>,
          UseTableColumnProps<D>,
          UseFiltersColumnProps<D>,
          UseGroupByColumnProps<D>,
          UseSortByColumnProps<D> {
            className?: string;
          }
```

you can remove the `UseXColumnProps` if you aren't using those features.

**Comment by ggascoigne** [comment]
Well Column and ColumnInstance are different for a reason.  Column is the type that you pass in to useTable, ColumnInstance is the richer value that you get provided in callbacks.  As for the rest, it depends on exactly what you are trying to do.

**Comment by vinnymac** [comment]
We know what they are trying to do because they have a link in the original comment.

```ts
cell.getCellProps({ className: cell.column.className });
```

The only thing that needs to be done here is to make sure that `ColumnInstance` has a `className` property so `cell.column.className` is happy, and you'll also need to type `TableCellProps` so that the key `className` in the object is accounted for.

This isn't a bug for sure, just a bit more than most are probably used to having to handle when utilizing a dependency.

**Comment by ggascoigne** [comment]
FYI I think that the change in #42411 should have made this easier.

I also think that this can be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
