### ISSUE TITLE
[lodash] Implicit or chained version of `zip` does not allow arrays of different types.

### ISSUE THREAD

**Issue by anandnimkar** [DefinitelyTyped/DefinitelyTyped#41504]
Sample:
```
const zipped1 = _.chain([1,2,3]).zip(["a", "b", "c"], [false, true, false]).value();
const zipped2 = _([1,2,3]).zip(["a", "b", "c"], [false, true, false]).value();
```

Error:
```
Error:(27, 42) TS2345: Argument of type 'string[]' is not assignable to parameter of type 'List<number>'.
  Index signatures are incompatible.
    Type 'string' is not assignable to type 'number'.
```

This seems similar to #23221. This might affect the other zip methods. I didn't verify this.

- [x] I tried using the `@types/lodash@4.14.149` package and had problems.
- [x] I tried using the latest stable version of tsc **(version 3.7.4)**. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @aj-r @e-cloud @thorn0 @jtmthf @DomiR @WilliamChelman

**Comment by aj-r** [comment]
It's likely that this behavior was lost when we refactored the types for TS3.1.

Out of curiosity, does this work in TS<=3.0?

**Comment by Micahnator** [comment]
I believe I'm having a related issue with _.chain. In my case I get a type error on the function given to filter(). I'm compiling with Typescript 3.8.3. Both my code and the example above in this issue work fine with @types/lodash 4.14.124, but give type errors with @types/lodash 4.14.125.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
