### ISSUE TITLE
@types/graphql 14.5.0 is empty

### ISSUE THREAD

**Issue by lambda0xff** [DefinitelyTyped/DefinitelyTyped#41505]
`npm info @types/graphql` lists `14.5.0` as the latest available version.

However, `yarn add @types/graphql` installs an empty repository.

cc: @TonyPythoneer , @calebmer , @intellix @firede

**Comment by peterblazejewicz** [comment]
Hi,
`graphql` ships with its own definition files, hence it lists the 14.5:
When installing via npm you should see `This is a stub types definition. graphql provides its own type definitions, so you do not need this installed.`, so yes, expected empty entry in node modules, but as the `package.json` for `graphql` now contains `types` entry, the TS will first look into the own Graphql definitions.
Relevant PR:
#37830

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
