### ISSUE TITLE
Send email via GAPI in Javascript

### ISSUE THREAD

**Issue by DigoFuerte** [DefinitelyTyped/DefinitelyTyped#41535]
Could someone please direct me to some documentation showing how to send an email using GAPI in Javascript. The documentation I have found on the Google Developers webpages have not been helpful in the least - more to the point, I have found several examples on the web (that address my issues to varying degrees) and from these examples I have picked out pieces of code (e.g. gapi.client.load, etc).

However, I cannot find the Google documentation to make sense of the code I have found... nor can I find a complete working example. The most hopeful example I have found is here: https://www.sitepoint.com/sending-emails-gmail-javascript-api/ ; which is based on a project on GitHub. I feel that if I could find the relevant Google documentation on the GAPI calls in this project, I could workout what I need to do.

All I need to do is send some emails from a webpage using Javascript/jQuery. Should be really easy but without knowing where to find the documentation makes it impossible - I am pulling my hair out at this stage. I already setup my Gmail account to obtain the apiKey and clientId.

After that I want to setup Google's reCAPTCHA service on the webpage to handle malicious dev's attacking the site.

Please help... desperate dev' here :(

PS: I have also posted this in StackOverflow.

**Comment by peterblazejewicz** [comment]
https://github.com/google/google-api-javascript-client/blob/master/docs/start.md

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
