### ISSUE TITLE
[styled-components] - tsserver painfully slow, recursive type usage?

### ISSUE THREAD

**Issue by jakobthomasson** [DefinitelyTyped/DefinitelyTyped#41608]
- [x] I tried using the `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc, `3.7.4`. https://www.npmjs.com/package/typescript
- [x] Shout out! @Igorbek, @Igmat, @Lavoaster, @Jessidhia, @JKillian, @eps1lon, @flavordaaave, @wagerfield, @lazyuki.

Hey folks, I've noticed an issue with the Typescript 3.7 types. 
The problem lays with the type `type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;` in the file `3.7/index.d.ts`

I looks like there is a recursive call to Omit, because if I change it to `type Omit<T, K extends keyof T> = any;` 

The issue dissapears. 

The difference is extreme, before it took tsserver about ~3 seconds to respond, now it only takes >1/2 second as it should.

**Comment by Aleksion** [comment]
I'm having similar issues. I haven't exactly pinpointed what it is, but there's two negative results of this:

- Editor becomes painfully slow
- It eventually gives up and gives "any" types for all styled components (but the CI server isn't that "generous")

**Comment by AlCalzone** [comment]
The TypeScript team is on it: https://github.com/microsoft/TypeScript/issues/34801

**Comment by eps1lon** [comment]
> The TypeScript team is on it: [microsoft/TypeScript#34801](https://github.com/microsoft/TypeScript/issues/34801)
> If I remember correctly, material-ui uses styled-components under the hood

We don't. Though there is work going on that might improve styled-components as well. But in general #34801 is not concered with styled-components.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
