### ISSUE TITLE
@types/color Type parameter 'T' has a circular default

### ISSUE THREAD

**Issue by micobarac** [DefinitelyTyped/DefinitelyTyped#41612]
```
ERROR in node_modules/@types/color/index.d.ts:13:40 - error TS2716: Type parameter 'T' has a circular default.

13 interface Color<T extends ColorParam = ColorParam> {
```

**Comment by peterblazejewicz** [comment]
shouldn't it read?
```ts
interface Color<T  = Color<ColorParam>> {
```

**Comment by dmihal** [comment]
Getting this as well

**Comment by taktakpeops** [comment]
Hello, got into the same issue. Opened PR #41815 to fix it

**Comment by BeeeQueue** [comment]
Make sure your TypeScript versions are up to date. Circular dependencies were introduced in 3.7.

You can wait with updating the package until you've updated TS, as the update doesn't add missing types or change anything else, it's just for developer experience.

**Comment by taktakpeops** [comment]
Coming back to what I said in the PR, in this case we are just mirroring the version of the modules and not really sticking to semver for the typings.

Now, my PR is not only for dev experience but mainly for building my projects in my CI.

Switching from 3.0.0 to 3.0.1 shouldn’t imply upgrading side dependencies based on semver since it’s supposedly a patch and not a minor nor major

**Comment by BeeeQueue** [comment]
All types packages are indirectly dependant on TypeScript - I don't know if updating the required TS version is enough for a new major version (I don't believe it should be).

I don't know who to @ about this either, but it'd be nice to know for sure

**Comment by jmthibault79** [comment]
Pinning the `@types/color` version to 3.0.0 resolved this compile error for me on Typescript 3.1.6.  Thanks for filing this bug.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
