### ISSUE TITLE
RSVP `filter` function can return `boolean | Promise<boolean>`

### ISSUE THREAD

**Issue by oliverlangan** [DefinitelyTyped/DefinitelyTyped#41798]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/de4c6bb742d39060dd1ccf08eadbdef97eb7178e/types/rsvp/index.d.ts#L421

There are many overloads defined for the RSVP library's `filter` method. For each of them, the `filterFn` parameter's return type should be changed from `boolean` to `boolean | Promise<boolean>`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
