### ISSUE TITLE
In angular-resource.d.ts, the IActionDescriptor interface is missing properties

### ISSUE THREAD

**Issue by battmanz** [DefinitelyTyped/DefinitelyTyped#4179]
The IActionDescriptor interface is missing the following properties:
- url
- transformRequest
- transformResponse
- cache
- timeout
- withCredentials
- responseType
- interceptor

You can see them in the [$resource](https://docs.angularjs.org/api/ngResource/service/$resource) documentation.

**Comment by vvakame** [comment]
@battmanz please send a PR. I'll review it.

**Comment by sclassen** [comment]
@vvakame this can be closed

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
