### ISSUE TITLE
 error TS2689: Cannot extend an interface 'http.IncomingMessage'. Did you mean 'implements'?

### ISSUE THREAD

**Issue by cah-tulasi-chaganti** [DefinitelyTyped/DefinitelyTyped#41828]
I have upgraded te $types/connect and still the issue is same.
Updated my node version to v10.17.0 and npm to 6.13.4.

Deleted my node modules.  did rebuild still i see the issue .
May I know how i can resolve it?

Thanks for reading.

**Comment by pedrovagner** [comment]
Same issue here.

**Comment by pedrovagner** [comment]
I just found a better way to solve this. Update your `"@types/node"`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
