### ISSUE TITLE
lodash/fp/map causes false errors on some object types

### ISSUE THREAD

**Issue by jedwards1211** [DefinitelyTyped/DefinitelyTyped#41867]
- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel, @chrootsu, @stepancar, @aj-r, @Ailrun, @e-cloud, @thorn0, @jtmthf, @DomiR, @ajmacd 

### Valid code
```ts
import map from 'lodash/fp/map'
map((x: number) => x * 2)({a: 1})
map((x: number) => x * 2)({a: 1} as Record<string, number>)
```

### tsc errors
```
(property) a: number
Argument of type '{ a: number; }' is not assignable to parameter of type 'number[] | ArrayLike<number> | null | undefined'.
  Object literal may only specify known properties, and 'a' does not exist in type 'number[] | ArrayLike<number>'.ts(2345)

Argument of type 'Record<string, number>' is not assignable to parameter of type 'number[] | ArrayLike<number> | null | undefined'.
  Type 'Record<string, number>' is missing the following properties from type 'number[]': length, pop, push, concat, and 28 more.ts(2345)
```

**Comment by aj-r** [comment]
Looks like we need to fix the way the `fp` generator writes the overloads, so it merges the array and object overloads into 1 overload. This may not be easy but if someone makes a PR I'll review it.

In the meantime, you might be able to convince TS to pick the right overload by explicitly passing a type parameter, e.g. `map<???>(x => x * 2)`. Unfortunately this approach is requirerd for a lot of `lodash/fp` functions. Look in `lodash-tests.ts` to see the intended usage of each function.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
