### ISSUE TITLE
@pollyjs/persister-fs definitions are on the wrong object

### ISSUE THREAD

**Issue by ccouzens** [DefinitelyTyped/DefinitelyTyped#41873]
The test for @pollyjs/persister-fs is

```typescript
import FSPersister from '@pollyjs/persister-fs';
import { Polly } from '@pollyjs/core';

Polly.register(FSPersister);

new Polly('<recording>', {
    persister: FSPersister
});
```
This is pretty similar to the example given in the original project's readme.

Unfortunately, the readme is written for Javascript with esmodules, and in that situation the `import FSPersister from '@pollyjs/persister-fs';` line imports from `dist/es/pollyjs-persister-fs.js`. The same line in Typescript imports from `dist/cjs/pollyjs-persister-fs.js`.

This is because the `package.lock` for `@pollyjs/persister-fs` contains:
```json
  "main": "dist/cjs/pollyjs-persister-fs.js",
  "module": "dist/es/pollyjs-persister-fs.js",
```

The commonjs file has no default export, so in Typescript `FSPersister` is undefined.

To get it to run correctly in Typescript, I need to do `import * as FSPersister from '@pollyjs/persister-fs';` and use it as `FSPersister as any`.

The bug is that there are no type definitions for the import that actually works.

---

I think this is related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12395.

I tried but couldn't figure out how to move the definition to the `*` level.

---

- [x] I tried using the `@types/pollyjs__persister-fs` package and had problems.
- [x] I tried using the latest stable version of tsc (3.7.5). https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @feinoujc (ps, thank you for writing this typescript definition)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
