### ISSUE TITLE
ko.utils.stringTokenize() and other utility functions available in Typedefinition are missing in minified versions of knockout.js

### ISSUE THREAD

**Issue by mdahamiwal** [DefinitelyTyped/DefinitelyTyped#4192]
Faced this issue while using knockout.js minified version. 
This seems similar to https://github.com/knockout/knockout/issues/670. Did a quick comparison (http://www.diffnow.com/?report=c0ge4) of functions available in knockout.d.ts (V.3.2.0) and actual knockout.3.2.0.js and looks like there are a lot of utility functions in debug.js which are not defined as ko.utils exports.

**Comment by mdahamiwal** [comment]
I have created a pullrequest https://github.com/borisyankov/DefinitelyTyped/pull/4196 to remove ko.util functions that are not part of minified js. Can someone review it?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
