### ISSUE TITLE
[@types/react-select] Use of "any" causes typing on Props to not enforce anything

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/DefinitelyTyped#42074]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Methuselah96, @claasahl, @jonfreedman, @thchia, @danieldelcore, @rjoonas 

---

I am trying to write a wrapper around `Select` from `react-select`, to add some custom props and functionality. I've imported the interface `Props`, and am extending it to add typing to my custom props.

The problem is, all typings that I add in my custom interface are ignored. I can give my custom component bogus props, and it'll accept them.

I think the issue is in [line 54  of Select.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/src/Select.d.ts#L54). There's a type called `SelectComponentProps` that uses dynamic keys:

```typescript
export type SelectComponentsProps = { [key in string]: any };
```

The interface `Props` then extends that type:

```typescript
export interface Props<OptionType extends OptionTypeBase = { label: string; value: string }> extends SelectComponentsProps {
```

And since my custom interface extends from `Props`, the dynamic keys in `SelectComponentProps` mean that my custom interface has dynamic keys as well, which means that TypeScript lets me pass in bogus props to my custom component.

Is there a reason why `Props` extends from `SelectComponentsProps`, or why `SelectComponentsProps` exists in the first place?

**Comment by jonfreedman** [comment]
We have a wrapper around react-select to apply MaterialUI styling.  We pass the react-select props as innerProps e.g. 
```javascript
export interface Props<TI> {
    innerProps: Partial<AsyncSelectProps<TI>>;
    ...
}
```
This works well and is consistent with the library itself (see https://react-select.com/components#replacing-components)

**Comment by mikewangspok** [comment]
Thanks for responding! I tried that out, and it does solve half the problem. There's still the issue of being able to add bogus props to `innerProps`, however:

```typescript
import Select from 'react-select';
import { Props } from 'react-select/base';

interface CustomSelectProps {
  innerProps: Props;
  myCustomProp: boolean;
}

const CustomSelect: React.FC<CustomSelectProps> = (props) => {
  return (
    <Select
      {...props.innerProps}
    />
  );
}

ReactDOM.render((
  // add bogus property to `innerProps`:
  <CustomSelect innerProps={{bogusProp: true}} myCustomProp={true}/>
), rootElement);
```

Perhaps I'm doing something wrong. I'm on `@types/react-select@3.0.8` and `typescript@3.7.5`.

**Comment by jonfreedman** [comment]
You're not doing something wrong, I am not sure why we have the `SelectComponentsProps` base type - it doesn't tie out with the flow types which is the usual excuse.

@VincentLanglet changed this @ https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33607

> I don't remember exactly but I needed extra props, used by my select component.
Every props should be allowed because they are passed to children component in the argument.

It looks like @lexwebb did some digging into the react-select source and found where this is needed but didn't post the actual line of code.

**Comment by VincentLanglet** [comment]
I hope @lexwebb still remember why. It's too long ago for me.

**Comment by lexwebb** [comment]
This is pushing my memory a bit aswell. Essentially from what I remember and having gone back and looked at the code; it seems that all props passed to react-select are assigned to the property named `selectProps` on the internal input inside the react-select component. Which I assume is to allow access to the root select props when replacing components etc..

You can see where this is done [here](https://github.com/JedWatson/react-select/blob/8fa6c0f01416b923d2c7a6f31ee687b6248fcd71/packages/react-select/src/Select.js#L1447)

Following that assignment up the chain eventually leads you to the root component props. There is also a TODO on [line 327](https://github.com/JedWatson/react-select/blob/8fa6c0f01416b923d2c7a6f31ee687b6248fcd71/packages/react-select/src/Select.js#L327) which seems to suggest that flow typings least may have been intended possibly?

This of course is useful behaviour when replacing the Input component but isn't that friendly to the types. I never did end up working on a PR to control this a bit better because of the usual reasons. But I think I was going to allow you pass your own type in through another generic parameter that would replace `SelectComponentsProps` and remove the any where needed.

**Comment by lexwebb** [comment]
@mikewangspok @jonfreedman I've raised a PR which i worked on this weekend which adds more typings around original change by @VincentLanglet. This should get rid of the any typing and add the options to specifically type extra input props. 

The only way i was able to achieve this however was introducing another generic parameter to the Select, in-between the existing two parameters. This may introduce breaking changes to people who use the second generic parameter, however as far as i can see it is only there to provide some typings to internal elements in the select component chain.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
