### ISSUE TITLE
TypeScript 1.5 -> Require definition has errors.

### ISSUE THREAD

**Issue by niemyjski** [DefinitelyTyped/DefinitelyTyped#4210]
[TsProject] typings/requirejs/require.d.ts(359,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type '{ (id: string): any; resolve(id: string): string; cache: any; extensions: any; main: any; }', but here has type 'Require'.
[TsProject] Build completed with errors. Outputs generated.

**Comment by rcollette** [comment]
+1 
but it only seems to do this for TS 1.5.0-beta.

**Comment by Executor89** [comment]
Any solutions?

**Comment by beuted** [comment]
**If you don't need requirejs AND node at the same time**
That was my case when I add 2 separated typescript builds, one for the front and one for the back but I add only one package.json to put all the "@types" in.

You can just manually tell TSC to take certain types with the type option:

`types: [ "requirejs" ]` for the front and `types: [ "node" ]` for the back

Hope this helps.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
