### ISSUE TITLE
onChange is required on readOnly editor @types/draftjs

### ISSUE THREAD

**Issue by josvegit** [DefinitelyTyped/DefinitelyTyped#42131]
As the title says

**Comment by peterblazejewicz** [comment]
hey,
Thanks, can you provide some more details? (a snip?) The definitoin seems to have the `onChange(editorState: EditorState): void;` on the draft editor props.

**Comment by josvegit** [comment]
![Screenshot from 2020-02-06 22-17-52](https://user-images.githubusercontent.com/24354568/73979479-8b24f600-492e-11ea-9b67-5680eb172262.png)

Unless you supply an onChange it complains

If i supply an onChange like onChange={() => {}} it works but seems weird that you need to supply a onChange to a readonly editor.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
