### ISSUE TITLE
node types introduce CommonJS arguments as globals

### ISSUE THREAD

**Issue by jkrems** [DefinitelyTyped/DefinitelyTyped#42201]
Authors (from recent commits / PRs): @mhegazy, @vvakame.

When code runs as ESM (ES module) in node, it becomes observable by everyday users that the CommonJS arguments aren't *actual* globals. Any reference to them is an error. But the typings for node declare them as globals, leading to misleading feedback. In a module or any other code running outside of CommonJS function bodies, the following CommonJS arguments shouldn't appear:

* `require`
* `module`
* `exports`
* `__filename`
* `__dirname`

I'm not sure what exactly the solution is here. My gut feeling is that these shouldn't be part of `node.d.ts` but added by tsc when the module option is set to "CommonJS". Since that's likely too disruptive, maybe a new "actual node" type definition could be added that is then extended by `node.d.ts`?

See also: https://github.com/sindresorhus/globals/pull/160

**Comment by SimonSchick** [comment]
I do agree with this but this would be more of a TypeScript core issue than DT.
TS already gives `exports` and `module.exports` a special treatment (at least in JS mode) so I'm sure they could build upon this.

**Comment by jkrems** [comment]
Created an issue against Typescript. Let's see if there's agreement on where it should be fixed. https://github.com/microsoft/TypeScript/issues/36764

**Comment by jkrems** [comment]
@SimonSchick Sounds like this is being thrown back to `@types/node` by the discussions on the TypeScript issue.

Based on those opinions I would suggest something like this:

* `@types/nodejs`: The typings for node's built-ins and true globals.
* `@types/commonjs`: The typings for CommonJS arguments as "globals" (due to a lack of type system support for "file arguments").
* `@types/node`: The combination of those two to maintain the current API.

**Comment by SimonSchick** [comment]
This wouldn't work if you have projects that use both modules and commonjs (which I've seen in the wild) which ultimately means this is not fixable by `@types/node`.

So none of the above solutions are really satisfactory because none of them really 'smart' detect the current module type per file which is why I suggested this would be a TS issue.

So my overall feeling is 👎 

Regarding the package split:

Is nodejs commonjs impl generic enough to warrant it taking that package?
From what I can find [online](https://requirejs.org/docs/commonjs.html) `__dirname` and `__filename` aren't really part of commonjs, and `require` has a bunch of non-standard extras as well which reaches into the `module` package that ships with node.

I'd suggest something like:
`@types/node-core` (or `node-esm`) for module type agnostic types.
`@types/node` for commonjs specific types (depends on `node-core`)

However this would be extra churn as we'd always have to create a `@types/node` release when we do a `@types/node-core` release.
We'd need to drive some effort to educate people that if they use modules they should not be using `@types/node` but `@types/node-core`.

**Comment by sosoba** [comment]
IMHO `Got` (and every library) should publishing two independent packages - `got` and `@types/got`. Only second of them should have dependecy of `@types/*`.

You are the victim `Typescript` team recomendation according to which:
- Javascript sourced libraries should publishing types definition separately,
- Typescript sourced libraries should publishing single `npm` package

See https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
