### ISSUE TITLE
[@types/webpack] Missing compilation functions

### ISSUE THREAD

**Issue by bschlenk** [DefinitelyTyped/DefinitelyTyped#42223]
- [x] I tried using the `@types/webpack` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo
@bumbleblym
@bcherny
@tommytroylin
@mohsen1
@jcreamer898
@alan-agius4
@elliottsj
@jason0x43
@dennispg
@christophehurpeau
@ZSkycat
@johnnyreilly
@rwaskiewicz
@kuehlein
@grgur
@rubenspgcavalcante
@andersk
@ofhouse
@danielthank

It looks like [typedefs for webpack's Compilation object](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webpack/index.d.ts#L1143) are missing most of the functions that webpack [lists in its documentation](https://webpack.js.org/api/compilation-object/). Is there any difficulty in adding these? I could send a PR but I am not that familiar with webpack plugins... I was hoping to learn more by installing the types.

**Comment by johnnyreilly** [comment]
Feel free to send PRs 🤗

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
