### ISSUE TITLE
@types/node@12.12.25 incorrect type of SpawnSyncReturns<T>["output"]

### ISSUE THREAD

**Issue by Veetaha** [DefinitelyTyped/DefinitelyTyped#42221]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] Authors: @andrewbranch @SimonSchick .

I used `spawnSync` function from nodejs `child_process` module.
It seems that the type of `SpawnSyncReturns<T>["output"]` is not correct.
It is defined as the following: 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a68259ee8883cc9899463fe79a78bb49a9d2f6de/types/node/v12/child_process.d.ts#L428

But when I run `spawnSync("someBinary", ["--version"])`
I get this:
![image](https://user-images.githubusercontent.com/36276403/74102225-1cbc7f80-4b4a-11ea-8400-e848ec9ca6df.png)

So this should better be `(null | Buffer)[]` or maybe it depends on `T`? I am not sure...

Reproduction:
```ts
require("child_process").spawnSync("ls", ["--version"]).output
```

**Comment by Veetaha** [comment]
I also noticed that when you try to spawn not existing binary all `output`, `stdout`, `stderr` and other fields are `null`, which doesn't match to currently defined types:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a68259ee8883cc9899463fe79a78bb49a9d2f6de/types/node/v12/child_process.d.ts#L426-L441

![image](https://user-images.githubusercontent.com/36276403/74102359-8be6a380-4b4b-11ea-9fa6-26402e37634f.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
