### ISSUE TITLE
domain() not recognised

### ISSUE THREAD

**Issue by BanksySan** [DefinitelyTyped/DefinitelyTyped#4224]
Webstorm is saying that the domain function is not recognised.

![image](https://cloud.githubusercontent.com/assets/996280/7399321/e2b56bd4-eeac-11e4-9968-97a9510674b8.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
