### ISSUE TITLE
apple-mapkit-js typings should contain module declaration

### ISSUE THREAD

**Issue by zastrozzi** [DefinitelyTyped/DefinitelyTyped#42243]
can you please update this typings file to include 'declare module 'apple-mapkit-js' ' so that this can be used with standard import * as mapkit from 'apple-mapkit-js' syntax? At the moment it returns an error that index.d.ts is not a module.

_Originally posted by @zastrozzi in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35287#issuecomment-584167036_

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
