### ISSUE TITLE
d3-sankey minimal vs rendered links and nodes types

### ISSUE THREAD

**Issue by beninsocrata** [DefinitelyTyped/DefinitelyTyped#42265]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/752136c29dec6f1e559dfc62f6acba08f207c280/types/d3-sankey/index.d.ts#L30

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/752136c29dec6f1e559dfc62f6acba08f207c280/types/d3-sankey/index.d.ts#L170

I'd kindly appreciate some feedback on a point I'm struggling to understand as I become more familiar with TypeScript. I wonder if I'm missing something/not quite understanding a nuance.

When using the d3-sankey library, there is a minimal sort of definition for nodes and links that includes all of the properties of a computed/rendered version as optional. In my use, I have created 'Rendered' versions of these interfaces where those properties are not optional and cast the computed graph data to that for ease of use in my D3 logic. Does it not make sense that the type definitions should have this by default?

To be specific, the `SankeyGraph` definition, which is what is returned upon calling `sankey()` will have all the values computed. However, as defined, all of those computed properties are optional and require quite a bit type guarding to use.

Thanks in advance!

@tomwanzek @jarrettmeyer

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
