### ISSUE TITLE
[react-router-dom] RouteComponentProps changing state type 

### ISSUE THREAD

**Issue by antoinerousseau** [DefinitelyTyped/DefinitelyTyped#42274]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react-router-dom` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @huy-nguyen @p-jackson @johnnyreilly @eps1lon @danielnixon @ynotdraw 

## Versions

- `react-router-dom` 5.1.2
- `@types/react-router-dom` 5.1.3

## Test Case

https://codesandbox.io/s/react-router-dom-state-bug-1s753 (see `Home.tsx`)

## Expected Behavior

The state for the current route could have a different shape than the one for the route we want to go to

## Actual Behavior

Shares state type between `history.push` & `history.replace`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
