### ISSUE TITLE
[@types/sdp-transform] MediaAttributes.rtcpFb and MediaAttributes.rtcpFbTrrInt should be arrays

### ISSUE THREAD

**Issue by cunicocwb** [DefinitelyTyped/DefinitelyTyped#42278]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/sdp-transform` package and had problems.
- [x] I tried using the latest stable version (2.4.1): https://www.npmjs.com/package/@types/sdp-transform
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @loc, @muenchow

MediaAttributes.rtcpFb and MediaAttributes.rtcpFbTrrInt should be arrays.

**Comment by loc** [comment]
Hmm. Any idea why the diff displayed by github is so useless? I'm seeing full-file red and green.

**Comment by loc** [comment]
Also, you can go ahead and make this into a pull request, not an issue.

**Comment by cunicocwb** [comment]
> Hmm. Any idea why the diff displayed by github is so useless? I'm seeing full-file red and green.

Hi loc, to be honest I don't know. On my machine, Tortoise Git shows only what I really changed (4 lines in one file, and 2 in the other).

**Comment by cunicocwb** [comment]
> Also, you can go ahead and make this into a pull request, not an issue.

Sorry, I thought an issue was needed to track it. I created a pull request right after I raised the issue: https://github.com/cunicocwb/DefinitelyTyped/pull/1 (not sure if you can see it through that link)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
