### ISSUE TITLE
[Question] Extending "this" keyword, in a a index.d.ts file

### ISSUE THREAD

**Issue by martinandersen3d** [DefinitelyTyped/DefinitelyTyped#42298]
I'm trying to create a index.d.ts file for vue project with mixins.

is there a way to extend the "this" keyword?

I want to write: this.myMethod()

and in the index.d.ts file have something like:

```
interface this{
    myMethod(): any;
}
```
is anything like this possible?

**Comment by peterblazejewicz** [comment]
try on gitter:
https://gitter.im/Microsoft/TypeScript?utm_source=share-link&utm_medium=link&utm_campaign=share-link
Solution depends on the details of toolign and used api, this could be as simple as augmenting that other module with new methods definitions, really depends.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
