### ISSUE TITLE
@types/file-saver deprecated flag ruins tslint for parameterless usage

### ISSUE THREAD

**Issue by dzonatan** [DefinitelyTyped/DefinitelyTyped#42296]
After #35617 PR, the `saveAs` function gets tslint errors for being deprecated when using without parameters (mainly in unit tests for mocking & checking if it's been called):
`expect(FileSaver.saveAs).toHaveBeenCalledWith(...)`

This is actually a known tslint problem: https://github.com/palantir/tslint/issues/4522 but it does not seem to be solved in tslint as it got deprecated.
Not many options to solve this problem: either ignore these errors line-by-line or remove the type definition.
Would you consider dropping this overload entirely under new "minor/patch" version?

@HitkoDev @chrismbarr

**Comment by peterblazejewicz** [comment]
I believe it was introduced with rc2 (v2 effectively):
https://github.com/eligrey/FileSaver.js/commit/70c261d0268e4d02154c12e8ffd6069f82275ac8#diff-dc5eaddfec51693151d584d4cd59b0cf
So the proper woudl be to retro-add v1, with old method definition. 
Would it work for you @dzonatan?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
