### ISSUE TITLE
ExtJs support in TypeScript 0.9

### ISSUE THREAD

**Issue by strawd** [DefinitelyTyped/DefinitelyTyped#423]
With the addition of generics and literal string overloads, it's finally possible to do a decent job of adding type information to ExtJs. If I can find the time I will start this myself but if anyone else has the opportunity to do so it will be very much appreciated.

**Comment by thanhptr** [comment]
Please go to find ExtTS - Premium TypeScript type definitions for Sencha Ext JS

https://github.com/thanhptr/extts

Every latest version of ExtJS 4.x, 5.x, 6.x is supported; currently latest version is 6.0.2.437.
Everything you can find from ExtJS API document is in the type definitions with strongly-typed support (such as: Ext.dom.Element, ButtonConfig,..)

Hope this help & looking forwards to your feedback!

**Comment by david-bouyssie** [comment]
I set up an alternative project to brian428 's one: https://github.com/david-bouyssie/TypExt
I forked his groovy parser to genarate a static factory of ExtJS classes.
Thus you can now do:
```
const panel: Ext.panel.IPanel = TypExt.panel.Panel.create( {
    title: 'Hello',
    width: 200,
    html: '<p>World!</p>',
    renderTo: document.body
});
```
Note that you can omit the Ext.panel.IPanel type and use TS type inference.
TypExt offers some addons like a static ExtJS model factory and I'm now working on a class factory.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
