### ISSUE TITLE
[@types/mongoose] lean<T>() method should not always return T | null

### ISSUE THREAD

**Issue by skrtheboss** [DefinitelyTyped/DefinitelyTyped#42310]
After [this](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/e45aed2f51238c421d26f3c3308d9dcf67b57fcd#diff-f77e4c92e873042528b4ef79285cdf3c) commit, If is use the lean method on a `findByIdAndUpdate` with `{ upsert: true, new: true }` options, which ensure that an entity is returned, i get the wrong type `T | null`.

**Comment by ChrisLahaye** [comment]
@skrtheboss how did you work around this issue?

**Comment by skrtheboss** [comment]
@ChrisLahaye is used `as` cast...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
