### ISSUE TITLE
[@types/jasmine] Can't pass jasmine.any(Function) to a function argument in constructor

### ISSUE THREAD

**Issue by dylansteen** [DefinitelyTyped/DefinitelyTyped#42352]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @davidparsson  @borisyankov 

Before upgrading typescript to 3.7 and updating to the corresponding version of @jasmine/types, I was able to do the following:

```
class MyClass {
  constructor(x: Function) {}
}

function myFunction(y: MyClass) {}

...
// Do test stuff
...

expect(myFunction).toHaveBeenCalledWith(new MyClass(jasmine.any(Function)));

```

I can't do this anymore, I receive this error:

`Argument of type 'AsymmetricMatcher<any>' is not assignable to parameter of type 'Function'.
  Type 'AsymmetricMatcher<any>' is missing the following properties from type 'Function': apply, call, bind, prototype, and 6 more.`

**Comment by mpicciollicmq** [comment]
@dylansteen same problem for me. Did you find a solution ?

**Comment by dylansteen** [comment]
> @dylansteen same problem for me. Did you find a solution ?

@mpicciollicmq I don't think so. I believe I just settled for `expect(myFunction).toHaveBeenCalled()` or otherwise changed the test

**Comment by mpicciollicmq** [comment]
`class MyClass {
  constructor(x: Function) {}
}

function myFunction(y: MyClass) {}

...
// Do test stuff
...

expect(myFunction).toHaveBeenCalledWith(new MyClass(jasmine.any(Function)  as any));`

Works for me.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
