### ISSUE TITLE
[@types/parsimmon] throws "error TS2370: A rest parameter must be of an array type."

### ISSUE THREAD

**Issue by kygoh** [DefinitelyTyped/DefinitelyTyped#42368]
When running dtslint@2.0.6, the following error was thrown:

> Error: Errors in typescript@2.8 for external dependencies:
../node_modules/@types/parsimmon/index.d.ts(394,32): error TS2370: A rest parameter must be of an array type.

caused by

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/86ab4d56fa27a429827c24c8ff05971e9ca766de/types/parsimmon/index.d.ts#L394

Should it be?
```ts
function seq<T extends any[]>(...parsers: T[]): Parser<UnParser<T>>;
```

**Comment by kygoh** [comment]
The issue is resolved if I [specify typescript version](https://github.com/microsoft/dtslint#specify-a-typescript-version) 3.0 in `index.d.ts`. Any version below 3.0 throws the reported error.

**Comment by kygoh** [comment]
It makes sense as [rest parameters with tuple types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#rest-parameters-with-tuple-types) was only introduced in TypeScript 3.0. But dtslint is used to tests a TypeScript declaration file, which must be able to support a lower TypeScript version?

**Comment by kygoh** [comment]
More likely the error is caused by [DefinitelyTyped Header Parser](https://github.com/Microsoft/definitelytyped-header-parser)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
