### ISSUE TITLE
HTMLNavigationSectionElement interface is missing

### ISSUE THREAD

**Issue by diegonvs** [DefinitelyTyped/DefinitelyTyped#42380]
If you know how to fix the issue, make a pull request instead.

- [✅] I tried using the `@types/react` package and had problems.
- [✅  ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [✅ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [✅] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bunnybones1, @Jessidhia, @OliverJAsh 

Trying to search for an interface to `nav` elements, We only can declare this type of element as a `HTMLElement`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
