### ISSUE TITLE
AuthResponseContext in aws-lambda should not accept props of type any

### ISSUE THREAD

**Issue by andhagman** [DefinitelyTyped/DefinitelyTyped#42418]
The context properties of an AuthResponseContext (types/aws-lambda/common/api-gateway.d.ts) can be of types string, bools and numbers hence **any** is misleading.

See: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-lambda-authorizer-output.html

The interface AuthResponseContext should not accept properties of type **any**, instead it should accept properties of type **string | boolean | number**.

**Comment by simonbuchan** [comment]
See previous attempt in #33437, my thoughts in related issue #34059, my reply in #42421.

**Comment by simonbuchan** [comment]
Let me know if the latest changes in #42420 look like they fix this for you.

**Comment by andhagman** [comment]
> Let me know if the latest changes in #42420 look like they fix this for you.

It's never as easy as it looks at the first glance. I've quickly looked through your PR and that is much better solution than the current one. Good job.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
