### ISSUE TITLE
Cypress cucumber preprocessor custom parameter type with typescript

### ISSUE THREAD

**Issue by slashersvk** [DefinitelyTyped/DefinitelyTyped#42443]
I am using cypress-cucumber-preprocessor with cypress and typescript. Also I  noticed there is a possibility to use custom parameter types as shown here:
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/support/step_definitions/customParameterTypes.js

But I am getting trouble running it with Typescript.

Interface in typscript is defined as export function `defineParameterType(): void;`
so if I import module, I cannot write a propper definition.

But if I use javascript as shown in expamle, then I always get error Uncaught Error: Undefined parameter type {boolean}

My javascript code looks like this:

```
defineParameterType({
  name: "boolean",
  regexp: /true|false/,
  transformer(s) {
    return s === 'true';
  }
});
```

Is there a way to get it working using Typescript?
I belive that solution would be to add another appropriate function to types/cypress-cucumber-preprocessor/steps/index.d.ts interface.

Author: @FalconerTC @aleccool213

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
