### ISSUE TITLE
@types/heremaps    function  getBounds  in  class Group   maybe not correct    

### ISSUE THREAD

**Issue by yyl1208** [DefinitelyTyped/DefinitelyTyped#42456]
If you know how to fix the issue, make a pull request instead.

I tried using the latest version `@types/heremaps` package and had problems.
    fuction  **getBounds()** in class  **Group**  not useful  and i found document maybe it shoud be 
    **getBoundingBox()**

  - Authors: @tdreyno @kamal @leemhenson

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
