### ISSUE TITLE
@types/react DialogHTMLAttributes missing the onClose handler

### ISSUE THREAD

**Issue by k2snowman69** [DefinitelyTyped/DefinitelyTyped#42471]
I was messing around with the dialog polyfill and ran into this bug where with typescript, the onClose handler throws a build failure

```bash
[!] (plugin typescript) Error: @rollup/plugin-typescript TS2322: Type '{ children: (false | "" | 0 | Element | null | undefined)[]; id: string; ref: RefObject<HTMLDialogElement>; className: string; onClose: () => void; }' is not assignable to type 'DetailedHTMLProps<DialogHTMLAttributes<HTMLDialogElement>, HTMLDialogElement>'.
  Property 'onClose' does not exist on type 'DetailedHTMLProps<DialogHTMLAttributes<HTMLDialogElement>, HTMLDialogElement>'.
```

Current code: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9306d151540cbf43a3ac6ec4c4feec3b900f9d57/types/react/index.d.ts#L1944:L1946

Documentation for the onClose handler
https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close_event

**Comment by mrmckeb** [comment]
I have also hit this issue. Should I create PR?

**Comment by k2snowman69** [comment]
Sure! That would be great!

**Comment by mrmckeb** [comment]
Did you encounter anything else? I found that `onCancel` and `onClose` were both missing.

**Comment by k2snowman69** [comment]
The only callback I hooked into was onClose and I opened this issue to help track (and if I had time to come back to investigate more and fix). It makes sense that others attributes are missing but I personally haven't done the investigation into what all of them are. Sorry!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
