### ISSUE TITLE
Missing HTMLArticleElement type

### ISSUE THREAD

**Issue by jfhector** [DefinitelyTyped/DefinitelyTyped#42481]
Thanks for the great, really helpful types.

#### Issue

I've just noticed that `HTMLArticleElement` doesn't exist.

#### Why it'd be valuable to have `HTMLArticleElement`

It'd be valuable to have it.
* HTML `article` elements have a [specific semantic that `div` doesn't have](https://html.spec.whatwg.org/multipage/sections.html#the-article-element).
* And it's an essential part of the [accessible way to build feeds](https://www.w3.org/TR/wai-aria-practices-1.1/#feed).

#### Example pain point of not having `HTMLArticleElement`

Not having it `HTMLArticleElement` means that we developers can't do things like:

```tsx
interface CommentProps extends HTMLAttributes<HTMLArticleElement> {
  authorAvatarImgSrc: string;
  authorName: string;
  createdAt: Date;
  text: string;
}
```

Not having a type for `HTMLArticleElement` is likely to nudge developers to choose `div` over `article`. Which gets in the way of the web being more accessible.

@kachkaev @bunnybones1 @Jessidhia

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
