### ISSUE TITLE
[@types/gulp] Outdated WatchOptions interface

### ISSUE THREAD

**Issue by darsain** [DefinitelyTyped/DefinitelyTyped#42512]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] Authors: @drewnoakes  @GiedriusGrabauskas 

Current `WatchOptions` interface is extending `chokidar.WatchOptions`, but gulp is now using [glob-watcher](https://github.com/gulpjs/glob-watcher) module, which wraps chokidar, and has a couple more options which TypeScript doesn't know about.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
