### ISSUE TITLE
definitelytyped.org domain has expired

### ISSUE THREAD

**Issue by Nezteb** [DefinitelyTyped/DefinitelyTyped#42576]
Just an FYI to... Microsoft I guess?

Click the link in the repo description and see this: https://i.imgur.com/F9szy1E.png

**Comment by DanielRosenwasser** [comment]
Looking into it now, thanks for pointing this out.

**Comment by Nezteb** [comment]
It looks like this has been resolved, definitelytyped.org

However, the HTTP domain does not redirect to the HTTPS version, but that's fine for now.

**Comment by Nezteb** [comment]
It looks like this has been resolved, http://definitelytyped.org/

However, the HTTP domain does not redirect to the HTTPS version, but that's fine for now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
