### ISSUE TITLE
aws-lambda 8.10.44 broke APIGatewayEventRequestContext

### ISSUE THREAD

**Issue by joakimsandstromfinnair** [DefinitelyTyped/DefinitelyTyped#42586]
I think https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b9b6b0e9bd5de6ed18be0a3e07816f60fe6f2cfa/types/aws-lambda/trigger/api-gateway-proxy.d.ts#L17 should also have the protocol added. Since now we get:

```
[tsl] ERROR in /Users/xx/yy/src/docs-get.ts(39,11)
      TS2345: Argument of type 'import("/Users/xx/node_modules/@types/aws-lambda/index").APIGatewayProxyEvent' is not assignable to parameter of type 'AWSLambda.APIGatewayProxyEvent'.
  Types of property 'requestContext' are incompatible.
    Property 'protocol' is missing in type 'import("/Users/xx/node_modules/@types/aws-lambda/index").APIGatewayEventRequestContext' but required in type 'AWSLambda.APIGatewayEventRequestContext'.
```

_Originally posted by @joakimsandstromfinnair in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42419#issuecomment-590298925_

**Comment by simonbuchan** [comment]
I'm pretty sure you have managed to get multiple versions of `@types/aws-lambda` installed, the types referred to are the same type (e.g. there are not multiple with the same name), so this only makes sense if the `import(...)` and `AWSLambda` names are referring to different packages, normally due to it also being a transitive dependency of another package.

Try `yarn why @types/aws-lambda` or `npm ls @types/aws-lambda` to see where the other one is coming from. Unfortunately upgrading specific packages is a bit fiddly, be prepared for reading your package manager documentation and doing lots of googling if a simple `yarn upgrade @types/aws-lambda` or equivalent breaks stuff.

**Comment by joakimsandstromfinnair** [comment]
🤦‍♂ I had one mysterious transitive dependency that caused the issue. Issue fixed on our side.

**Comment by simonbuchan** [comment]
Happens to the best of us. And also me.
