### ISSUE TITLE
@types/cesium@1.66.1 mismatched method signatures

### ISSUE THREAD

**Issue by rokkuchan** [DefinitelyTyped/DefinitelyTyped#42601]
- [ x] I tried using the `@types/xxxx` package and had problems.
- [ x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Zuzon @hnipps @szechyjs @golyalpha @KeyboardSounds @soyarsauce @jrafidi @morgansierrasnyder @crocsx

Using Cesium 1.66.0 and @types/cesium 1.66.1

In Cesium.EllipsoidGeodesic class the method interpolateUsingFraction signature should have two input parameters but it has one instead.

Should be:
interpolateUsingFraction(fraction: number, result: Cesium.Cartographic): Cesium.Cartographic;

Another found:

Globe.js 
missing showGroundAtmosphere: boolean;

Please update thanks.

**Comment by jony89** [comment]
Hey, please create PR for the signatures

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
