### ISSUE TITLE
Add error.code for node.js 8+ in @types/node

### ISSUE THREAD

**Issue by emilioplatzer** [DefinitelyTyped/DefinitelyTyped#42623]
I need `error.code` in my `.ts` for node.js since node 8.

I'am using `"@types/node"` in `package.json`'s dependencies and `"typeRoots" : ["node_modules/@types"]` in `tsconfig.json`

I write
```
var error = new Error("the message error");
error.code = "THE_CODE"
throw error;
```

I expected `error.code` be ok (without error)

Node.js docs: https://nodejs.org/docs/latest-v8.x/api/errors.html#errors_error_code to https://nodejs.org/docs/latest-v13.x/api/errors.html#errors_error_code has the definition

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
