### ISSUE TITLE
How is @nodes/types versions related to NodeJs version?

### ISSUE THREAD

**Issue by michaelgarde** [DefinitelyTyped/DefinitelyTyped#42640]
I have difficulties identifying which ~~@nodes/types~~ @types/node version that is related to which NodeJs version. I may have missed it but a description for the relations would be really useful.

It may be painfully obvious and related to the major numbers but i don't know how to be sure.

**Comment by andreineculau** [comment]
You mean `@types/node`.
See https://stackoverflow.com/questions/42035263/relationship-between-the-version-of-node-js-and-the-version-of-types-node

**Comment by michaelgarde** [comment]
> You mean `@types/node`.
Of course. Thank you.
> See https://stackoverflow.com/questions/42035263/relationship-between-the-version-of-node-js-and-the-version-of-types-node
Yes. Something like that is in my opinion missing from the documentation. However, a table describing the relation would be even nicer.

**Comment by peterblazejewicz** [comment]
> However, a table describing the relation would be even nicer.

I think there is no need, semver is followed here. I thinks that's already detailed in the readme:
https://github.com/definitelytyped/definitelytyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
