### ISSUE TITLE
[it.each, jest] compile level block for incorrect type inside ${}

### ISSUE THREAD

**Issue by geyuqiu** [DefinitelyTyped/DefinitelyTyped#42679]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/jest` package:  "@types/jest": "24.0.23",
- [x] I tried using the  version of typescript: "typescript": "3.4.5",
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

If you do not mention the authors the issue will be ignored.

_Originally posted by @JoshuaKGoldberg in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26603/commits/dba82e8e0ebe8d65d5feaffbc18d597578c728c9_

**current status**
```
describe('test add method', () => {
    it.each`
      a     | b     | result
      ${2}  | ${3}  | ${"5"}
      ${20} | ${30} | ${50}
      ${-2} | ${-3} | ${-5}
    `('add $a to $b return $result', ({a, b, result}: Case) => {
        expect(a+b).toEqual(result);
    });
});
```
![image](https://user-images.githubusercontent.com/4540661/75430183-413a9900-594b-11ea-8d80-c56914f3369d.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
