### ISSUE TITLE
[react] Wrong type for props in component returned by React.lazy()

### ISSUE THREAD

**Issue by larsnystrom** [DefinitelyTyped/DefinitelyTyped#42713]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @DovydasNavickas, @theruther4d, @guilhermehubner, @ferdaber, @jrakotoharisoa, @pascaloliv, @hotell, @franklixuefei, @Jessidhia, @saranshkataria, @lukyth, @eps1lon, @zieka, @dancerphil, @dimitropoulos

The  `LazyExoticComponent` interface looks like this:

    type LazyExoticComponent<T extends ComponentType<any>> = ExoticComponent<ComponentPropsWithRef<T>> & {
        readonly _result: T;
    };

But I think this is more accurate:

    type LazyExoticComponent<T extends ComponentType<any>> = ExoticComponent<ComponentProps<T>> & {
        readonly _result: T;
    };

I.e. the component props should not include the ref. 

If the ref is included, the type of the component returned by `React.lazy()` becomes `(props: PropsWithRef<PropsWithChildren<T>>) => React.ReactElement | null` which is incorrect, because the ref is not part of the `props` argument. The correct component type should be `(props: PropsWithChildren<T>) => React.ReactElement | null`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
