### ISSUE TITLE
Compile Errors when using underscore.d.ts

### ISSUE THREAD

**Issue by tstearn** [DefinitelyTyped/DefinitelyTyped#4272]
I'm getting compile errors (using Intellij 14.1.2) when trying to do a valid use of underscore.  For instance, this code:

> this.selectedDocFields = _.reject(this.selectedDocFields, (currRow)=> {
>                return _.findWhere(rows, {id: currRow.id});
> });

produces the following error:
    Error:(71, 47) TS2345: Argument of type 'StoredDocumentField[]' is not assignable to parameter of type 'Dictionary<StoredDocumentField>'.

These errors appear all over my code where I use _.reject().  In looking at the .d.ts file, it defines reject with both List<T> and Dictionary<T>, but the compiler only appears to see the Dictionary<T> declaration.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
