### ISSUE TITLE
Leaflet: GeoJSONOptions typing definition is too narrow (smoothFactor)

### ISSUE THREAD

**Issue by CoryLR** [DefinitelyTyped/DefinitelyTyped#42737]
I've installed Leaflet type definitions using `npm install --save @types/leaflet`, but it seems type `GeoJsonOptions` does not recognize `smoothFactor`.

Here is my code (in TypeScript):

```typescript
L.geoJSON(this.residualsGeoJson, { style: this.style, smoothFactor: 0.3 }).addTo(this.map);
```

The `smoothfactor: 0.3` part is underlined in red with the message: *"Object literal may only specify known properties, and 'smoothFactor' does not exist in type 'GeoJSONOptions<any>'."*

Tagging authors:

- @alejo90 
- @atd-schubert 
- @mcauer 
- @ronikar 
- @SanFrisc 
- @life777 
- @henrythasler 

PS I would actually be happy to contribute and fix this issue but I'm not quite sure where to begin. If someone could point me in the right direction I'd be happy to give it a shot and submit a PR.

Thanks!

Cory

(Below is default new-issue text)

---

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

**Comment by ronikar** [comment]
would you add a reference from `Leaflet` docs ?

**Comment by UIDCLR** [comment]
> would you add a reference from `Leaflet` docs ?

What do you mean? @roniker

**Comment by ronikar** [comment]
[geojson-options](https://leafletjs.com/reference-1.6.0.html#geojson-option) doesn't contain smoothFactor

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
