### ISSUE TITLE
Add pouchDB promise API

### ISSUE THREAD

**Issue by fredgalvao** [DefinitelyTyped/DefinitelyTyped#4277]
[PouchDB's API](http://pouchdb.com/api.html) was updated a while ago to also provide promised methods, instead of accepting callbacks only as is in the current [pouch.t.ds](https://github.com/borisyankov/DefinitelyTyped/blob/c4fb7fafaf697141293eaa071a483668087ad700/pouchDB/pouch.d.ts).

The definition file should reflect this change providing alternative methods that instead of asking for a callback, return a Thenable.

**Comment by vvakame** [comment]
@fredgalvao please send a pull request. I'll review it.

**Comment by fredgalvao** [comment]
See [this](https://github.com/borisyankov/DefinitelyTyped/issues/4278#issuecomment-100415643).

**Comment by AGBrown** [comment]
@fredgalvao re [my comment here](https://github.com/borisyankov/DefinitelyTyped/issues/4278#issuecomment-101016205) - our [new pouchdb.d.ts development effort](https://github.com/AGBrown/pouchdb.d.ts/) already supports both promise and callback styles - worth a look? We are also on irc://freenode.net/#pouchdb if you want to join us and discuss?

**Comment by nolanlawson** [comment]
Is this superceded by #10171?

**Comment by phil-lgr** [comment]
I think this issue can be closed?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
