### ISSUE TITLE
node-uuid as a browser lib

### ISSUE THREAD

**Issue by fredgalvao** [DefinitelyTyped/DefinitelyTyped#4279]
[node-uuid](https://github.com/broofa/node-uuid), as it is now, works on node and browser environments, but it's typed only as a node module for 2 reasons:
- does **not** export a global scope `uuid` variable.
- depends on `node.d.ts`

The first one is easy to fix: `declare var uuid: UUID;` at the end of the current node-uuid.d.ts file.

For the second one though, I haven't been able to come up with a solution that makes it work on both environments, but I'm far from an experienced TS coder and thus it might be possible. The problem is that I can't see how I'd declare that the API can receive either a Buffer or an Array without explicitly requiring node.d.ts.

As I only use node-uuid in a browser-like environment, all I had to do localy was change Buffer to Array, but I can't say how we'll make it work on both worlds without spliting files.

**Comment by vvakame** [comment]
for first one. please send a pull request.
for second one. I think It does not have to worry too much. We can refactor node-uuid.d.ts to node-uuid-common.d.ts, node-uuid-browser.d.ts and node-uuid.d.ts. extract common definitions to node-uuid-common.d.ts. extends it from node-uuid.d.ts or node-uuid-browser.d.ts.

**Comment by fredgalvao** [comment]
If node's Buffer was made to extend native Arrays, it'd be a better solution, after thinking about it for a while. We could leave node-uuid using only native Arrays and any code calling node-uuid with nodejs buffers would still work.

What do you think?

**Comment by vvakame** [comment]
I don't like adhoc tricks...
I'm not using node-uuid. I think you should talking with node-uuid.d.ts authors. @jeffmay @Nemo157 @cainjonm

**Comment by laland** [comment]
https://github.com/borisyankov/DefinitelyTyped/pull/5364

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
