### ISSUE TITLE
[lodash] `iteratee` in many functions should have type `keyof T`, not `string`

### ISSUE THREAD

**Issue by iansan5653** [DefinitelyTyped/DefinitelyTyped#42831]
I wanted to make an issue for this rather than just submitting a PR as it would be a significant change to the package's types.

In every Lodash function that accepts an `iteratee` argument, the argument can be a function that takes the value being iterated over and returns the value to be used, or it can be a string that is a key of the iterated item.

For example, `sumBy` reduces all the elements in `collection` by calling `iteratee` on them (or indexing them with the string value of `iteratee`) and summing the results. It is typed like this currently:
```ts
sumBy<T>(collection: List<T> | null | undefined, iteratee?: ((value: T) => number) | string): number;
```

However, if `iteratee` is ever a string, it should be a key of `T`, so why not type it like this:
```ts
sumBy<T>(collection: List<T> | null | undefined, iteratee?: ((value: T) => number) | keyof T): number;
```

The same is true with nearly pretty much every iterating function in the library.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
