### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by knagaraju799** [DefinitelyTyped/DefinitelyTyped#42851]
[This package](https://www.jsdelivr.com/package/npm/@types/mui-datatables) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
