### ISSUE TITLE
urijs types were broken due to namespace change

### ISSUE THREAD

**Issue by arfreitas12** [DefinitelyTyped/DefinitelyTyped#42863]
The recent PR 3 days ago broke builds / multiple npm packages because the namespace for urijs was changed from 'uri' to 'URI'.

Here is the PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/270c15f15c11aeea519c586d41acd22588df9dde

Authors:
@marcelltoth

**Comment by uyu423** [comment]
I Agree, This is so bad feature. Every patch version must has "Backward compatibility"
That commit was no backward compatibility. Need to roll back those changes.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
