### ISSUE TITLE
[@types/react-table] UseTableRowProps cannot be merged with interface UseRowStateRowProps

### ISSUE THREAD

**Issue by pakettiale** [DefinitelyTyped/DefinitelyTyped#42889]
UseTableRowProps probably has unnecessary state field:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e534774027767502c673b7f9b2859c1b3cbe9087/types/react-table/index.d.ts#L242-L251

@amcasey can you confirm whether this is correct?

**Comment by amcasey** [comment]
I'm not familiar with the underlying library.  The definition owners would be the ones to ask: @ggascoigne @stramel @gargroh @riceboyler

**Comment by ggascoigne** [comment]
I think that you are correct and that the state property in `UseTableRowProps` is wrong and simply shouldn't be there.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
