### ISSUE TITLE
[download-stats] Issue linting new type definitions because name includes "download"

### ISSUE THREAD

**Issue by nmay231** [DefinitelyTyped/DefinitelyTyped#42966]
I am trying to write new type definitions for [download-stats](https://www.npmjs.com/package/download-stats), but when I try to lint it, I get the following error:

```
$ npm run lint download-stats

> definitely-typed@0.0.3 lint /home/nmay/cur/tmp/DefinitelyTyped
> dtslint types "download-stats"

Error: /home/nmay/cur/tmp/DefinitelyTyped/types/download-stats: Contains the word 'download', which is banned by npm.
    at assertPathIsNotBanned (/home/nmay/cur/tmp/DefinitelyTyped/node_modules/dtslint/bin/index.js:218:15)
```

Obviously this package has been on NPM for 2 years, so we should be able to add definitions for it. Ideas on how to proceed with or (maybe) without linting it?

**Comment by peterblazejewicz** [comment]
@nmay231 
Hey, it looks like that's due to this TD TSLint checks:
https://github.com/microsoft/dtslint/blob/master/src/index.ts#L230-L238
Let me add someone to the discussion

**Comment by sandersn** [comment]
Unfortunately, NPM no longer allows publication of *new* packages that contain the word download. It's part of their keyword-based spam filtering approach, where the list of keywords is not published.

The best approach is to get types added to download-stats itself, since pre-existing packages are still allowed to publish new versions.

**Comment by nmay231** [comment]
Oh, so that would prohibit `@types/download-stats` even though `download-stats` already exists. Gotcha.

Thanks :+1:
