### ISSUE TITLE
@types/fundamental-react 0.8.0 isn't compatible with fundamental-react 0.8.0 

### ISSUE THREAD

**Issue by brainocean** [DefinitelyTyped/DefinitelyTyped#42975]
### Description
In npm.js, @types/fundamental-react's version is 0.8.0, but after I download it via npm install, it still has component types which are removed from fundamental-react 0.8.0, for example Alert, ListGroup etc.

### Versions
**fundamental-react:** 
0.8.0

---

![2020-03-06_17-55-47](https://user-images.githubusercontent.com/1978334/76072994-e1d82b00-5fd3-11ea-80f4-6f9a51c062f8.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
