### ISSUE TITLE
react-select: missing property Group.headingProps

### ISSUE THREAD

**Issue by sommcz** [DefinitelyTyped/DefinitelyTyped#43045]
typedefinition missing `headingProps` property.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c2384365a16d55cebbf216bc336339d81c9c26dd/types/react-select/src/components/Group.d.ts#L6

https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/components/Group.js

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
