### ISSUE TITLE
[@types/hapi__hapi] nested methods for server methods could not get type definition.

### ISSUE THREAD

**Issue by saeidalidadi** [DefinitelyTyped/DefinitelyTyped#43064]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/hapi__hapi` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rafaelsouzaf @jhsimms @saboya 

Issue: Typescript can't find types of nested server methods.

```javascript
// server.js
server.method("user.send", async (id) => {...})
```

When using the method:
```javascript
const result = await server.methods.user.send(id)
```

Typescript error: 
```
Property 'send' does not exist on type 'ServerMethod'
```

**Comment by saboya** [comment]
TypeScript can't do this automatically for you. There's an interface specifically designed to be augmented by users to allow this:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a526399b9d6bb0abfa2ac5f5da0505a96ebd6109/types/hapi__hapi/index.d.ts#L3384-L3389

So you would probably do something like this:

```
declare module '@hapi/hapi' {
  interface ServerMethods {
    user: {
      send: (id: string) => void
    }
  }
}

```

**Comment by saeidalidadi** [comment]
It works for me. thanks @saboya :+1:

**Comment by saeidalidadi** [comment]
I got new error inside `@types/hapi__hapi`
 Error:

```
Property 'mail' of type '{ user: SendMail; }' is not assignable to string index type 'ServerMethod'.
```

But everything is right inside my own code and typings.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
