### ISSUE TITLE
AsyncBooleanResultCallback return type is missing Promise<void>

### ISSUE THREAD

**Issue by aecorredor** [DefinitelyTyped/DefinitelyTyped#43101]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/async` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention] @borisyankov @kern0

Shouldn't 

```js
export interface AsyncBooleanIterator<T, E = Error> { (item: T, callback: AsyncBooleanResultCallback<E>): void; }
```

be 

```js
export interface AsyncBooleanIterator<T, E = Error> { (item: T, callback: AsyncBooleanResultCallback<E>): void | Promise<void>; }
```

so that when using filter we can use async/await in the iterator function and do something like this:

```js
  const validFriendIds = async.filter(
    data.invited,
    async (friendId, done) => {
      const areFriends = await hasFriend(creator, friendId, models);
      done(null, areFriends);
    }
  );
```

Right now I have to use `.then` to make the types happy:

```js
  const validFriendIds = async.filter(data.invited, (friendId, done) => {
    hasFriend(creator, friendId, models).then(areFriends =>
      done(null, areFriends)
    );
  });
```

From looking at the docs, they don't say that the iterator can't return a promise, so I'm thinking the types might indeed be wrong.

**Comment by khaliu** [comment]
Also, there are some methods like `each` which the documents says it returns a `Promise` when a `callback` is not present.

**Comment by aecorredor** [comment]
@khaliu  Right, the library documents are up to date, it's the types that are wrong.

**Comment by khaliu** [comment]
Seems to be fixed in this PR, but it is frozen: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37605

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
