### ISSUE TITLE
setGravity in physijs.d.ts

### ISSUE THREAD

**Issue by wasil123** [DefinitelyTyped/DefinitelyTyped#4313]
I have problem with "typed" physijs. setGravity over there have type number, but in physiJs I always used Vector3. 

When I change the d.ts file to accept Vector3 I have strange mesh behavior (it split into 2, and mirror movement).

**Comment by vvakame** [comment]
@wasil123 please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
