### ISSUE TITLE
@types/color: error TS2716: Type parameter 'T' has a circular default.

### ISSUE THREAD

**Issue by curiouscod3** [DefinitelyTyped/DefinitelyTyped#43145]
> node_modules/@types/color/index.d.ts(13,40): error TS2716: Type parameter 'T' has a circular default.

In Angular project,( regardless of framework type)

To fix this, I had to change from this :
`type ColorParam = Color | string | ArrayLike<number> | number | { [key: string]: any };`

to this 
`type ColorParam = string | ArrayLike<number> | number | { [key: string]: any };`

Any better idea?

[ref](https://github.com/Qix-/color/issues/176)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
