### ISSUE TITLE
module not found in fesm5 in angular library

### ISSUE THREAD

**Issue by RoshanGajula** [DefinitelyTyped/DefinitelyTyped#43140]
Am building an angular library.

Have dependency of using jspath. Hence, installed jspath using

npm install @types/jspath
Since jspath doesn't have typings, installed typings for jspath available online. Imported jspath as

import * as JSPath from jspath
in component where it is needed.

After doing all above steps and when i run the build package, it returns the error:

   module jspath
   not found in dist/fesm5" even if the module is available in
   node_modules

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
