### ISSUE TITLE
[@types/powerapps-component-framework] EntityReference id type is incorrect for webApi.createRecord

### ISSUE THREAD

**Issue by naostranMS** [DefinitelyTyped/DefinitelyTyped#43185]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/powerapps-component-framework` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jopursle @ghurlman 

If you do not mention the authors the issue will be ignored.

Issue:
webAPI.createRecord (and I think all of the other webAPI functions) return an EntityReference, but the type of id returned doesn't match the typing - it's just a string rather than { guid: string }

so e.g. to get the entity id from this:
`const newEntityInfo = await pcfContext.webAPI.createRecord("annotation", entityData);`
I have to explicitly cast:
`const id = (newEntityInfo.id as any) as string;`

This is a result of the fix for this issue: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37298

It seems that there are different underlying types that are both being exposed as EntityReference and there should really be two different types (or the webAPI functions need to change the data they return to match the EntityReference type).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
