### ISSUE TITLE
[@types/ioredis] Wrong callback data type for redis.hmset

### ISSUE THREAD

**Issue by chuyik** [DefinitelyTyped/DefinitelyTyped#43194]
Package: @types/ioredis
Version: 4.16.0

`hmset` method is typed like [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ioredis/index.d.ts#L454-L460):
```ts
hmset(key: KeyType, ...args: ValueType[]): Promise<BooleanResponse>;
hmset(
    key: KeyType,
    data: object | Map<string, ValueType>,
    callback: (err: Error, res: BooleanResponse) => void,
): void;
hmset(key: KeyType, data: object | Map<string, ValueType>): 
```

but real response is string "OK".

I think, that the same thing can happen to some other commands.

Authors: @thmiyathmary @plantain @chrisleck @aliarham11 @br8h @shaharmor @palindrom615 @reconbot @funthing @iamolegga @tingwai @pettyalex @SimonSchick @tianlinle @demian85

related issue: #31155

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
