### ISSUE TITLE
setTimeout and setInterval should not return the same `NodeJS.Timeout`

### ISSUE THREAD

**Issue by onionhammer** [DefinitelyTyped/DefinitelyTyped#43236]
The types are incompatible, so they should be different.

```
var timer = setTimeout(..);

clearInterval(timer)
```

should result in a typechecking compile-time error

**Comment by peterblazejewicz** [comment]
@onionhammer can you please clarify which types you're reffering to be specific? 
You're probably on the setup that is using both DOM and Node types, that shares that api.
Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
