### ISSUE TITLE
[@types/recharts] Missing definitions for 'recharts/es6'/...' imports

### ISSUE THREAD

**Issue by apedroferreira** [DefinitelyTyped/DefinitelyTyped#43251]
Hi! 

I'm importing things from recharts as in `import RadialBarChart from 'recharts/es6/chart/RadialBarChart'`

, but it seems that if I do this I don't get the typed components I would get with something like `import { RadialBarChart } from 'recharts'`

Would it be possible to type these? I'm using Create React App, and as far as I'm aware importing like this is the best way to only import parts of the library as opposed to the whole thing, unless I ejected the project and used the Recharts babel plugin for example, which I wouldn't want to do.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
