### ISSUE TITLE
[d3] attr should be readonly

### ISSUE THREAD

**Issue by gnuletik** [DefinitelyTyped/DefinitelyTyped#43267]
- [x] I tried using the `@types/d3-selection` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek @denisname 

Hi ! I'm facing an issue when trying to set an `Area` (from [d3-shape](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/d3-shape)) in the `.attr()` method (from [d3-selection](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-selection/index.d.ts))

Here's a sample of what I'm doing.

```typescript
interface DataItem {
  min: number;
  max: number;
  time: number;
}

const data: readonly DataItem[] = []

const d3chart = d3.select<SVGSVGElement>('.area')

const xScale = d3.scaleLinear<number>()
const d3area = d3.area<DataItem>()
  .x((d) => xScale(d.time))

// The error occurs here:
// The type 'readonly DataItem[]' is 'readonly' and cannot be assigned to the mutable type 'DataItem[]'.
d3chart.datum(data).attr('d', d3area)
```

Is d3 mutating the array here ? Would it be possible that Datum can be `readonly` ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
