### ISSUE TITLE
NPM: Unable to find a readme for ...

### ISSUE THREAD

**Issue by dkorolev1** [DefinitelyTyped/DefinitelyTyped#43311]
- [ x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/). 

Hi,

I have a small question regarding relationship between this repository and NPM. 

Some time ago a added Typescript definitions for the react-adal lib to the DefinitelyTyped Repo. Pull request has been approved and definitions were successfully published to NPM. 

I recently noticed that the package description in NPM isn't avaliable anymore. Instead I found the following message : _Unable to find a readme for @types/react-adal@0.4.2_ 

NPM: [https://www.npmjs.com/package/@types/react-adal](https://www.npmjs.com/package/@types/react-adal)

DefinetelyTyped (Source): [https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-adal](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-adal) 

I can also see now 3 different versions of this package in the NPM-history: 0.4.0, 0.4.1 and 0.4.2.
At the same time in the source we have a version 0.4 for these definitions and it has never changed.

My questions/things I can't understand:

1. The version of the definitions in the source (Github) has never changed. Why then these 3 different versions appeared in npm.
2. Why description works fine for the version 0.4.1 [https://www.npmjs.com/package/@types/react-adal/v/0.4.1](https://www.npmjs.com/package/@types/react-adal/v/0.4.1) and doesn't work for 0.4.2. What is the fundamental difference if in the package we still have 0.4.
3. I would like to understand what is the reason for this behaviour and how it can be fixed.

Thanks in advance!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
