### ISSUE TITLE
[universalify] Better type needed!

### ISSUE THREAD

**Issue by oganexon** [DefinitelyTyped/DefinitelyTyped#43341]
- [x] I tried using the `@types/universalify` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

- Authors: @Richienb

As it stands now, the current types are:
```typescript
export function fromCallback(fn: (...args: any[]) => any): (...args: any[]) => Promise<any> | void;
export function fromPromise(fn: (...args: any[]) => any): (...args: any[]) => Promise<any> | void;
```
As you can see, `any` are everywhere. It's very annoying because a well-defined function loses its typing.

The solution would be to specify a callback function after rest parameters. But it doesn't work that way...
```typescript
(...args: any[], cb: any)
// A rest parameter must be last in a parameter list.  ts(1014)
```

It takes away all the benefits of typescript if the function is of type `any`.

**Help needed!**

**Comment by Richienb** [comment]
@oganexon For `fromCallback`, we can't really do anything since there isn't an easy way to specify a callback as the final argument.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
