### ISSUE TITLE
Typescript of mongoose-aggregate-paginate-v2

### ISSUE THREAD

**Issue by duongkhoangiam** [DefinitelyTyped/DefinitelyTyped#43410]
- [ ] I tried using the latest stable version of tsc. https://github.com/aravindnc/mongoose-aggregate-paginate-v2

Anyone can create typescript base on this dependency ?

**Comment by chanced** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31087/files/a623516aa78e67b507e5135869f4404bd9f91ef6

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8519e8860954820c1502d0484b0f93e58bd148c6/types/mongoose-paginate-v2/index.d.ts

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
