### ISSUE TITLE
[@types/draft-js] Error: Exported variable ‘X’ has or is using name 'Draft.Model.Decorators.DraftDecoratorType' from external module “…/node_modules/@types/draft-js/index" but cannot be named.

### ISSUE THREAD

**Issue by rpoet-ds** [DefinitelyTyped/DefinitelyTyped#43426]
Hi,

We are running into an issue trying to use EditorState type.  We're receiving the TS error: Error: Exported variable ‘X’ has or is using name 'Draft.Model.Decorators.DraftDecoratorType' from external module “…/node_modules/@types/draft-js/index" but cannot be named.

We are not using Draft.Model.Decorators.DraftDecoratorType in our code, only EditorState is used.

It appears Draft.Model.Decorators.DraftDecoratorType is not exported in @types/draft-js/index...?

- [x] I tried using the `@types/draft-js` package and had problems.
- [x] I tried using the latest stable version of tsc (3.8.3). https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dmitryrogozhny @eelco

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
