### ISSUE TITLE
Class 'Module' incorrectly implements interface 'NodeModule'

### ISSUE THREAD

**Issue by Risto-Stevcev** [DefinitelyTyped/DefinitelyTyped#43441]
I tried using `@types/node` with `@types/parcel-env` and got this error (similar to #20158):
```
Class 'Module' incorrectly implements interface 'NodeModule'
```
Since `parcel-env` is based on `webpack-env`, I think it might need to be updated in a similar way but I'm not familiar enough with the type defs to submit the PR.

`parcel-env` definitions by: Fathy Boundjadj <https://github.com/fathyb>

cc @fathyb

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
