### ISSUE TITLE
@types/react-bootstrap different variants are not possible

### ISSUE THREAD

**Issue by javierguzman** [DefinitelyTyped/DefinitelyTyped#43461]
Hello all,

I have started using Typescript in my project next to React-Bootstrap and the following piece of code:

```
  const renderSearchAddressButton = (): JSX.Element => {
    return (
      <div className="search-address-button">
        <Button variant="myownvariant" onClick={onClickSearchAddressButton}>
          {t('search-address-button')}
        </Button>
      </div>
    );
  };
```

Gives me a Lint error because myownvariant is not a correct variant. The code works but the only types allowed are the following:
```
  variant?:
    | 'primary'
    | 'secondary'
    | 'success'
    | 'danger'
    | 'warning'
    | 'info'
    | 'dark'
    | 'light'
    | 'link'
    | 'outline-primary'
    | 'outline-secondary'
    | 'outline-success'
    | 'outline-danger'
    | 'outline-warning'
    | 'outline-info'
    | 'outline-dark'
    | 'outline-light';
```

Is there a way to fix this? Otherwise I think it would make sense to propose this as a feature taking into account the react bootstrap documentation specifies is ok to create your own variants, etc.

Thank you in advance and regards.

**Comment by peterblazejewicz** [comment]
@javierguzman 
I think this type definition neeeds an overhaul. It's on the v0.32, while the `react-bootstrap` is now 1.*. The property in question was not on 0.32, it's migrated from older api, see:
https://github.com/react-bootstrap/react-bootstrap/blob/e327af383680db5d67e13a87f99d12bb66203eef/www/src/pages/migrating.mdx#summary-of-breaking-changes-from-v0320
let me know if it seems correct (if so, let's redact the issue title)

**Comment by javierguzman** [comment]
Thanks @peterblazejewicz  ! I am not sure if it is clear from the link you have mentioned, but from that link I understand that the porting to 1.* is on going right now and that bStyle is going to be replaced to variant, isn´t? Anyhow I will just have to wait then for the release of 1.*

**Comment by peterblazejewicz** [comment]
Sorry if I missed something. What I've meant: it seems they've just released v.1, can you check your local package config which version you're on? That will clear things out
And the missing migration is to have props to be rewritten, at the moment variant is unkown:
```tsx
<Button bsStyle='primary'>Primary</Button>
// migrate definition to 1.* to support
<Button variant="primary">Primary</Button>
```

**Comment by javierguzman** [comment]
Thank you for the clarification @peterblazejewicz I am using react-bootstrap 1.0.0, however, @types/react-bootstrap is 0.32.20 . The @types one is the problematic one as without Typescript it works and it does not complain about variant, etc.

**Comment by peterblazejewicz** [comment]
Yes, it seems to be correct. Let me call the arms:
/cc (sorry folks for group call): @walkerburgin, @vsiao, @danilojrr, @Batbold-Gansukh, @octatone>, @chengsieuly, @mretolaza>, @katbusch, @vitosamson, @LKay, @aaronbeall, @jrakotoharisoa, @r3nya, @t49tran, @bes, @collingreen

**Comment by aaronbeall** [comment]
The type definitions in `@types/react-bootstrap` are for pre 1.0. Since react-bootstrap 1.0 the [types are built in](https://github.com/react-bootstrap/react-bootstrap/tree/master/types) and you should not also install `@types/react-bootstrap`. This has caused some confusion which I tried to [address in a PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34025) but that effort sort of stalled out. 

As for the issue with `variant` being a set of values that doesn't allow for a custom value, I am not sure how to handle that. Maybe there needs to be an optional type arg to extend it with your own custom types? Or maybe you should just use assertion? There's a tradeoff between making it easy to use the default values and letting you make mistakes.

**Comment by peterblazejewicz** [comment]
@aaronbeall Thx for stepping up!. I can help you with pushing that thing forward, can you rebase #34025, so it's up to date?  We could just mock expected setup locally and verify it works for existing project(s) Cheers!

**Comment by javierguzman** [comment]
Thanks both @aaronbeall and @peterblazejewicz !! I have tried your snippet, Aaron, but I get the following errors:
1. Conversion of type 'string|undefined' to type 'Button<"button"> may be a mistake because neither type suffienctly overlaps with the other. If this was intentional, conver the expression to 'unknown' first.
2.Type Button<"button"> is missing the following properties from type ReactElement<any, any>: type key

Does that work for you? I have to say I have uninstall pre 1.0 types and I am using built-in types of react-bootstrap 1.0 as Peter suggested.

**Comment by aaronbeall** [comment]
@javierguzman Here's a complete example of using a custom variant in TypeScript: [CodeSandBox](https://codesandbox.io/embed/charming-bose-8k877)

@peterblazejewicz The problem with my PR is that I removed react-bootstrap ([via the DT script](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#removing-a-package)) but what I think we actually want is a little different: publish to 1.0 a stub (which points users to rely on built-in type defs and makes installing `@types/react-bootstrap@^1` harmless) while preserving the 0.3.x line for maintenance. I never closed the PR only because I never quite figured out how to do that, but there are similar examples like how [react-router maintains v2, v3 and current (4+) via sub-dirs](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-router). I think we basically want the inverse of that: make current (1.0) a stub, and a sub-dir `v0`.

**Comment by javierguzman** [comment]
@aaronbeall I should definetely stop programming before drinking the first coffee of the day. I was getting the error I mentioned previously because my file extension was .ts rather than .tsx

Now it works! However, now it complains about passing an onClick prop. I guess somehow TS does not understand that MyButton returns a Button which has a super/parent class that has that prop.

Is this expected? I have fixed it adding " onClick?: any;" to MyButtonProps. But it looks fishy from my TS novice point of view.

**Comment by aaronbeall** [comment]
@javierguzman Hm, I am not sure. Can you post an example on CodeSandBox?

**Comment by javierguzman** [comment]
Hello @aaronbeall sorry for the delay; 

Here is the sandbox:
https://codesandbox.io/s/react-bootstrap-own-variant-ciml1

As you can see over onClick there is a message similar to:
TS2322: Type '{ children: string; variant: mygreen"; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & Pick<ButtonProps, "size" | "disabled" | "type" | "href" | "active" | "block"> & { variant?: "link" | "primary" | ... 17 more ... | undefined; } & { ...; }'.
  Property 'onClick' does not exist on type 'IntrinsicAttributes & Pick<ButtonProps, "size" | "disabled" | "type" | "href" | "active" | "block"> & { variant?: "link" | "primary" | ... 17 more ... | undefined; } & { ...; }'.

I thought it would be only Lint but actually if I try to run my app the compiler complains as well (error code TS2322 as you can see above). I do not really know if it is a bug or maybe you can see what it is going on because I would have thought that is correct code

**Comment by javierguzman** [comment]
I can confirm a similar problem happens if I use "className" for example.

**Comment by javierguzman** [comment]
Hello @aaronbeall ! did you get any chance to take a look at the codesandbox?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
