### ISSUE TITLE
[@types/mocha] Allows it.retries, but fails at runtime

### ISSUE THREAD

**Issue by HoldYourWaffle** [DefinitelyTyped/DefinitelyTyped#43482]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mocha` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kazimanzurrashid, @otiai10, @jt000, @enlight, @cspotcode, @1999

<br>

The current type definitions for mocha define a `retries` function on `TestFunction`:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7caeca4bfbd5ca9f306c14def3dd6b416869c615/types/mocha/index.d.ts#L484-L489

This implies (and allows) usage like this:
```ts
describe('test', function() {
	it.retries(x);
});
```

This looks a little weird to me, and (perhaps unsurprisingly) this throws an error at runtime:
```
TypeError: context.retries is not a function
    at Function.context.it.retries (node_modules\mocha\lib\interfaces\bdd.js:113:15)
    at Suite.<anonymous> (line 2)
    *** snip ***
```

Interestingly however, this function does seem to [actually exist](https://github.com/mochajs/mocha/blob/c5fc2bee0e15299825508743b25f596dff710120/lib/interfaces/bdd.js#L109-L114) at runtime.

I have very little experience with mocha, and I have no idea should happen here. Should `retries` be removed from the type definitions, or would this be considered a bug at mocha's side?

I'm using mocha v7.1.0.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
