### ISSUE TITLE
[@types/ramda] either function has faulty typings.

### ISSUE THREAD

**Issue by jonni-larjomaa** [DefinitelyTyped/DefinitelyTyped#43543]
The either function has wrong typings, the outcome of R.eihter predicates should not be booleans but actually any, the either should not return the boolean value but the value of function generated, which then is compared as being truth-y value or not.

/**
* A function wrapping calls to the two functions in an || operation, returning the result of the first
* function if it is truth-y and the result of the second function otherwise. Note that this is
* short-circuited, meaning that the second function will not be invoked if the first returns a truth-y value.
*/
either(pred1: Pred, pred2: Pred): Pred;
either(pred1: Pred): (pred2: Pred) => Pred;

and then the type of Pred is of course as follows:

type Pred = (...a: readonly any[]) => boolean;

in general this is not wrong, but in the case of either the returning value should not be the predicate it self but the actual, value generated by eihter functions.

so the typings should be

either(pred1: T1, pred2: T2): <T1 | T2>;

**Comment by DmitryMasley** [comment]
I have the same problem. Even examples in ramda docs don't match these types.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
