### ISSUE TITLE
Migrate DefinitielyTyped to use the Travis CI GitHub app

### ISSUE THREAD

**Issue by ExE-Boss** [DefinitelyTyped/DefinitelyTyped#43574]
Currently, the service based **Travis‑CI.org** seems to have some issues with reporting build status to **GitHub**, possibly because of some API change or something.

The **GitHub App** based **Travis‑CI.com** (https://github.com/apps/travis-ci/) doesn’t have this issue.

## See also:
- <https://docs.travis-ci.com/user/migrate/open-source-repository-migration>

---

/cc @RyanCavanaugh

**Comment by AviVahl** [comment]
Could also consider using GitHub Actions

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
