### ISSUE TITLE
Rename 'GitHubElectron' namespace to 'Electron'

### ISSUE THREAD

**Issue by brunnopleffken** [DefinitelyTyped/DefinitelyTyped#4358]
Does 'Electron' conflict with other d.ts files, or something? I wonder why it's named 'GitHubElectron', instead of just 'Electron', making it shorter and easier to type and read.

`var mainWindow: Electron.BrowserWindow = null;`

instead of...

`var mainWindow: GitHubElectron.BrowserWindow = null;`

**Comment by vvakame** [comment]
@jedmao what do you think about this comment?
I think `Electron` is better than `GitHubElectron`.
package name is conflicted, but symbol name are simple is better.

**Comment by jedmao** [comment]
@vvakame that's how it was named, originally. The only reason I changed it to GitHubElectron was because of [your comment here](https://github.com/borisyankov/DefinitelyTyped/pull/4273#issuecomment-99500513). Notice, there's already a package named [electron on npmjs.com](https://www.npmjs.com/package/electron). I think you made the name change suggestion because we didn't want to create any confusion against this npm package.

**Comment by rhysd** [comment]
This was already done.
