### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by Vadorequest** [DefinitelyTyped/DefinitelyTyped#43596]
I don't understand how to get a changelog.

Could you please add a CHANGELOG.md file in the root directory, with explanation as to how one's supposed to understand what has changed between two version? (basically, get a summary of changes, and a diff code)

For instance, I noticed `@types/js-cookie` has been updated from 2.2.4 to 2.2.5 but I don't understand how to see what has actually changed.

**Comment by AviVahl** [comment]
An auto-generated/committed changelog would be nice, although I can imagine how this could complicate any CI/CD flow...

I the meanwhile, you can use git's commit log to see which commits went in for a specific @types package. e.g. https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/js-cookie

**Comment by AviVahl** [comment]
Also, see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/26847

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
