### ISSUE TITLE
[amplitude-js] visitor.setOnce doesn't allow boolean type

### ISSUE THREAD

**Issue by Vadorequest** [DefinitelyTyped/DefinitelyTyped#43598]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @asido  @danmana @HintikkaKimmo 

![image](https://user-images.githubusercontent.com/3807458/78317455-a002bc00-7562-11ea-8a0d-4fb2127af86f.png)

`visitor.setOnce('initial_iframe', isInIframe);`
Function should also allow boolean type, I believe.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
