### ISSUE TITLE
[ @types/stripe ] importing fails

### ISSUE THREAD

**Issue by kaigothe** [DefinitelyTyped/DefinitelyTyped#43623]
- [x] I tried using the `@types/stripe` package and had problems.

  - Authors:   @wjohnsto  @CodeAnimal  @sampsonjoliver  @LinusU  @brannon  @kylekampy  @starhoshi @bruun @galtalmor @htunnicliff @squirly @tzarger @ifiokjr @yultyyev @cpsoinos @adamduren @saranshkataria @0xJoKe @delianides @gokulchandra @viralpickaxe @chrisleck @spacetag

Hi,
I have following Problem. Importing Stripe via @types/stripe fails since today. Last 2 months my Project works  fine with types/stripe.

How I importing Stripe: 

``` ts
import Stripe from "stripe"
```

in VS Code I got following error

```Module '"<directory of project>/node_modules/@types/stripe/index"' can only be default-imported using the 'esModuleInterop' flagts(1259)
index.d.ts(160, 1): This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag. 
```

My `tsconfig.json`
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "moduleResolution": "node",
        "outDir": "build",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "sourceMap": true,
        "esModuleInterop": true,
        "typeRoots": [
            "node_modules/@types"
        ]
    }
}
```

Typescript Version: 3.7.5
@types/stripe Version: 6.32.12

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
