### ISSUE TITLE
@types/ember (+friends) missing new APIs

### ISSUE THREAD

**Issue by NullVoxPopuli** [DefinitelyTyped/DefinitelyTyped#43630]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @chriskrycho 

If you do not mention the authors the issue will be ignored.

missing APIs (afaik)
 - `import { dependentKeyCompat } from '@ember/object/compat';`
    - [docs](https://api.emberjs.com/ember/3.17/functions/@ember%2Fobject%2Fcompat/dependentKeyCompat)
 - `import { setComponentTemplate } from '@ember/component';`
    - [rfc](https://github.com/emberjs/rfcs/blob/master/text/0481-component-templates-co-location.md#low-level-primitives)
    - [code](https://github.com/emberjs/ember.js/blob/7763d7aa72445c88a0e63da800266465bef14ce1/packages/%40ember/-internals/glimmer/lib/utils/component-template.ts#L10)
 - all of ember-cli-htmlbars 
    - [see issue](https://github.com/ember-cli/ember-cli-htmlbars/issues/468)

**Comment by chriskrycho** [comment]
Thanks for opening this! Mind opening this as a types issue typed-ember/ember-cli-typescript instead? That’s (much!) easier for us to track and manager!

**Comment by NullVoxPopuli** [comment]
here ya go: https://github.com/typed-ember/ember-cli-typescript/issues/1141 :D

**Comment by chriskrycho** [comment]
Much obliged! If no one else hits these, I should be able to knock them out mid-to-late next week!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
