### ISSUE TITLE
Missing optional parameter language in GeocoderRequest

### ISSUE THREAD

**Issue by pasblin** [DefinitelyTyped/DefinitelyTyped#43632]
If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/googlemaps` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cgwrench @Silver-Connection @nertzy @xaolas @mrmcnerd @martincostello @svenkreiss @bolatovumar @gauthierm @captain-igloo @demensky @life777 @simonhaenisch @gshigeto @Bat-Orshikh

GeocoderRequest Interface not declaring language optional parameter.(https://developers.google.com/maps/documentation/geocoding/intro)

**Comment by demensky** [comment]
The current version of [the definitions for `GeocoderRequest`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/googlemaps/index.d.ts#L2069) is in accordance with [the documentation](https://developers.google.com/maps/documentation/javascript/reference/geocoder#GeocoderRequest). The documentation does not mention the `language` field.

**Comment by pasblin** [comment]
Yes, I looked at that point , but maybe it could be added, although it is not reflected in the interface documentation, it does not mean that it cannot be used.

Regards.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
