### ISSUE TITLE
[@types/google-cloud__kms] Missing definitions for some methods on client

### ISSUE THREAD

**Issue by CarbonCollins** [DefinitelyTyped/DefinitelyTyped#43656]
- [x] I tried using the `@types/google-cloud__kms` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ben-tbotlabs @caiertl

Hi :wave:,

It seems that some of the methods in the @google-cloud/kms package are missing from the definitions.

I'm trying to follow the sample code for [Asymmetric Signing](https://github.com/googleapis/nodejs-kms/blob/master/samples/asymmetricSign.js) extract for usage:
```ts
  // Import the library and create a client
  const kms = require('@google-cloud/kms');
  const client = new kms.KeyManagementServiceClient();

  // --- some othe stuff --- //

  // Sign the message with Cloud KMS
  const [result] = await client.asymmetricSign({
    name: name,
    digest: {
      sha384: digest.digest(),
    },
  });
```

for the sample the following methods seem to be missing:
`asymmetricSign`

but on a quick glance over there seems to be other missing definitions too:
`listImportJobs`
`listCryptoKeyVersions`
`getKeyRing`
`getImportJob`
`getCryptoKey`
`getCryptoKeyVersion`
`createKeyRing`
`createImportJob`
`createCryptoKeyVersion`
`importCryptoKeyVersion`
`updateCryptoKey`
`updateCryptoKeyVersion`
`updateCryptoKeyPrimaryVersion`
`destroyCryptoKeyVersion`
`restoreCryptoKeyVersion`
`getPublicKey`
`asymmetricDecrypt`

**Comment by CarbonCollins** [comment]
I've created a [PR#43658](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43658) which adds the typings for asymmetricSign()

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
