### ISSUE TITLE
No JSDoc comments for google.maps.d.ts

### ISSUE THREAD

**Issue by cgwrench** [DefinitelyTyped/DefinitelyTyped#4365]
The Google Maps definitions, see [googlemaps/google.maps.d.ts](https://github.com/borisyankov/DefinitelyTyped/blob/7d2f0aa875cc3bc41f3567e3ff99d344df986155/googlemaps/google.maps.d.ts), do not contain any JSDoc comments. The [reference Google Maps API documentation](https://developers.google.com/maps/documentation/javascript/reference), contains excellent documentation for all classes and methods and it would be great to incorporate these into DefinitelyTyped.

**Comment by cgwrench** [comment]
This has been started by @Outlivier as part of #4539.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
