### ISSUE TITLE
Add missing jQuery AJAX overloads

### ISSUE THREAD

**Issue by cgwrench** [DefinitelyTyped/DefinitelyTyped#4367]
The jQuery Ajax shorthand methods `jQuery.get`, `jQuery.post` have missing overloads.

The methods 
- `jQuery.get( url [, data ] [, success ] [, dataType ] )` and
- `jQuery.post( url [, data ] [, success ] [, dataType ] )`

are definied in [jquery/jquery.d.ts](https://github.com/borisyankov/DefinitelyTyped/blob/7d2f0aa875cc3bc41f3567e3ff99d344df986155/jquery/jquery.d.ts), but the methods
- `jQuery.get( [settings ] )` and
- `jQuery.post( [settings ] )`

do not have corresponding definitions

**Comment by vvakame** [comment]
@cgwrench please send a pull request. @johnnyreilly

**Comment by johnnyreilly** [comment]
Yup - ping me when you submit it @cgwrench and I'll take a look.

**Comment by jasekiw** [comment]
Same issue here. I had to manually edit my definition file

**Comment by jasekiw** [comment]
I'll submit a pull request

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
