### ISSUE TITLE
filesystem polluting the global namespace 

### ISSUE THREAD

**Issue by mohsen1** [DefinitelyTyped/DefinitelyTyped#43683]
interfaces like `VoidCallback` do not belong to the global namespace

**Comment by mohsen1** [comment]
//cc @niikoo

**Comment by niikoo** [comment]
> //cc @niikoo

What can I help with? :)

**Comment by mohsen1** [comment]
Did I tag you right? 

I think this definition is adding too much noise to the global namespace. Do those interfaces have to be global?

**Comment by niikoo** [comment]
You mean the filesystem definition, right?

**Comment by mohsen1** [comment]
Yes

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
