### ISSUE TITLE
[react-native] AnimatedComponent doesn't have style

### ISSUE THREAD

**Issue by CosmaTrix** [DefinitelyTyped/DefinitelyTyped#43737]
I've been trying to animate a `react-native-svg` component using `Animated.createAnimatedComponent`. Because the `react-native-svg` components don't allow a `style` property, then that property cannot be found when they are wrapped in an `AnimatedComponent`.

The following code
```typescript
import React, { useRef, useEffect } from "react";
import { Animated } from "react-native";
import { Line } from "react-native-svg";

const AnimatedLine = Animated.createAnimatedComponent(Line);

const AnimatedComponent: React.FC = () => {
  const animatedX = useRef(new Animated.Value(0)).current;
  
  useEffect(() => {
    Animated.spring(animatedX, {
      toValue: 100
    }).start()
  }, []);

  return (
    <AnimatedLine
      style={{
        transform: [{ translateX: animatedX }]
      }}
    />
  );
};
```

outputs this error (even though the animation works as expected as `AnimatedComponent` allows the `style` prop)
```
TS2322: Type '{ style: { transform: { translateX: Value; }[]; }; }' is not assignable to type 'IntrinsicAttributes & AnimatedProps<LineProps> & { children?: ReactNode; }'.
Property 'style' does not exist on type 'IntrinsicAttributes & AnimatedProps<LineProps> & { children?: ReactNode; }'.
```

Maybe the `AnimatedProps` type should always include a `style` property?
```typescript
// Not sure of what the type for { style: any } should be
export type AnimatedProps<T> = { [key in keyof T]: WithAnimatedValue<T[key]> } & { style: any };
```

- "react-native": "0.61.4"
- "@types/react-native": "0.61.23"
- "react-native-svg": "11.0.1"

**Comment by rankery** [comment]
+ 1 got same Issue and it should be solved somehow

**Comment by yum650350** [comment]
+1

**Comment by anisfrontmen** [comment]
+1

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
