### ISSUE TITLE
@types/mongoose Property '_id' does not exist on type 'ObjectId'

### ISSUE THREAD

**Issue by mschnee** [DefinitelyTyped/DefinitelyTyped#43746]
> Mongoose adds a _id getter to ObjectId instances so you can use story.author._id regardless of whether author is populated.

Since mongoose version 5.8, mongoose has added a getter to ObjectId so that on fields that may or may not be populated, you can always access the `_id` without needing to ducktype if the field is populated or not.

While this would be a straightforward Pull Request, unfortunately, the DefinitelyTyped definitions for mongoose are for version `5.7.12`, and are now two minor versions out of date.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
