### ISSUE TITLE
[@types/ssh2] No writeFile method.

### ISSUE THREAD

**Issue by yunbookf** [DefinitelyTyped/DefinitelyTyped#43798]
Add writeFile method. Officially there is this method, but the current d.ts file does not. Official code address: https://github.com/mscdex/ssh2/blob/master/lib/SFTPWrapper.js.

- [x] I tried using the `@types/ssh2` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
  - Authors: @mscdex

**Comment by yunbookf** [comment]
Yes, and thx: @jeffrson

**Comment by yunbookf** [comment]
Thx: @Timmmm @wbobeirne @cowwoc 
I'm so sorry for you.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
