### ISSUE TITLE
angularjs: $q.when maybe wrong

### ISSUE THREAD

**Issue by Kinchkun** [DefinitelyTyped/DefinitelyTyped#4379]
Hello Guys,

the angular docu says about the $q.when:

> Wraps an object that might be a value or a (3rd party) then-able promise into a $q promise

In our application we using $q.when for example to wrap JQuery promises into angular promises. However, the angular.d.ts does not support this, because it only accepts the IPromise Interface and not every 'thenable' object.

I would propose the following definition:

```
interface IThenable<T> {
    then<TResult>(successCallback: (promiseValue: T) => IThenable<TResult>|TResult, errorCallback?: (reason: any) => any): IThenable<T>;
}
when<T>(value: IThenable<T>|T): IPromise<T>;
```

Maybe the IThenable interface can be even more generic and accepting everything with an 'then' which accepts two callbacks.

What do you say?

Kind regards,
Timo

**Comment by vvakame** [comment]
@Kinchkun please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
