### ISSUE TITLE
Mailgun attachment needs to be a class not an interface

### ISSUE THREAD

**Issue by sk-** [DefinitelyTyped/DefinitelyTyped#43825]
- Authors: @sampsonjoliver, @andipaetzold, @JiriBalcar, @CodeLenny

`mailgun-js` requires that the attachments are instances of the `Attachment` class (see https://github.com/highlycaffeinated/mailgun-js/blob/106420e/lib/request.js#L236-L259), however the type definitions require that the attachment only confirms to the interface, which breaks the code.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
