### ISSUE TITLE
[@types/pino]: hooks option is missing

### ISSUE THREAD

**Issue by moltar** [DefinitelyTyped/DefinitelyTyped#43852]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @psnider @BendingBender @screendriver @paambaati @alferpal

The `hooks` and ~~`formatters`~~ option props are missing.

Docs:

* https://github.com/pinojs/pino/blob/767759b1cdbdf64ba172b90b0fcee1756226e856/docs/api.md#hooks-object

Thanks!

**Comment by moltar** [comment]
Seems like `formatters` were added by #43847 (thanks @armanio123)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
