### ISSUE TITLE
[passport-oauth2] Extending `Strategy` only partially possible

### ISSUE THREAD

**Issue by stephtr** [DefinitelyTyped/DefinitelyTyped#43856]
- [ ] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @pasieronen @WangZishi @EduardoAC @ivan94 @daphnesmit

Hi,

I was working on the definitions of `passport-oauth2` (setting `clientSecret` optionally, since it's not required for example with PKCE #43459) and noticed, that there is an issue with the way, it exports the `Strategy`. Because of the current construct, the `OAuth2Strategy` has to be assignable to any strategy extending it, not just the other way around; it throws an error, if there is a required property, which doesn't exist in the base class.

Does anyone have an idea what's the easiest way to fix that? I played a bit around but didn't find a useful solution.

```
Type 'import("passport-oauth2/index").StrategyOptions' is not assignable to type 'import("passport-bnet/index").StrategyOptions'.
  Types of property 'clientSecret' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.
```

**Comment by daphnesmit** [comment]
For password grant strategy the secret is also not needed. I just send an empty string for the clientSecret property.
The whole problem of extending also lies much deeper in the fact that oauth2 class is protected from oauth2 package, which also makes overwriting that much harder. I recently just added to missing options properties. I am not the initial author fyi.
My advice. send an empty string inside your class  instead of undefined. this way the oauth2 contructor doesnt fall apart:)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
