### ISSUE TITLE
[@types/lodash] Question: run test

### ISSUE THREAD

**Issue by xiaoxiangmoe** [DefinitelyTyped/DefinitelyTyped#43879]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DanielRosenwasser @orta @sandersn @bczengel @chrootsu @stepancar @aj-r @e-cloud @thorn0 @jtmthf @DomiR @WilliamChelman

---

I find `lodash-tests.ts` has many errors. But I don't know How to run test for it. `npm run test` and `npm run lint lodash` works well and no error occur.

![lodash-tests.ts](https://user-images.githubusercontent.com/8111351/79184052-b7388800-7e45-11ea-81f9-4af74d05f4d5.png)

**Comment by xiaoxiangmoe** [comment]
@armanio123 Can you help me?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
