### ISSUE TITLE
testing inner methods of component with props and states dependency

### ISSUE THREAD

**Issue by humorean** [DefinitelyTyped/DefinitelyTyped#43885]
I am trying to test a method inside a component that has dependency with the props and state:
```
class MyComponent extends PureComponent {
constructor(props) {
    super(props);
    this.state = {
      user: "user1"
    };

    this.handleFile = this.handleFile.bind(this);
  }
  handleFile(fileType){
  const {fileName} = this.props
  const { user } = this.state
  return `${fileName}_${fileType}_${user}`
 }
}
....
```
Let's say my test case looks something like this:
```
describe("should handle file method", () => {
    let component = shallow(
      <MyComponent
        fileName={"file1"}
      />
    );
    it("with valid file name", () => {
      const instance = component.instance();
      instance.handleFile("jpg");
    })
  });
```
fileName will be undefined inside.  Is there a way we can pass in the props into the instance function?
@fa93hws

**Comment by fa93hws** [comment]
Am I supposed to be mentioned? I don't think I have much context regarding this issue..

**Comment by humorean** [comment]
> Am I supposed to be mentioned? I don't think I have much context regarding this issue..

Do you happen to know who I should've mentioned here for the question above?

**Comment by fa93hws** [comment]
> Do you happen to know who I should've mentioned here for the question above?
No, sorry. No idea at all..

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
