### ISSUE TITLE
[@types/pino]: pino.destination is missing options

### ISSUE THREAD

**Issue by moltar** [DefinitelyTyped/DefinitelyTyped#43882]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @armanio123 @psnider @BendingBender @screendriver @paambaati @alferpal

The `pino.destination` factory method supports an options object.

https://github.com/pinojs/pino/blob/master/docs/asynchronous.md#usage

```ts
const dest = pino.destination({ sync: false })
```

https://github.com/pinojs/pino/blob/55858047518ce7bf0d075e8f552da76f2d1b4e9e/pino.js#L204

Which seems to match sonic-boom options: https://github.com/mcollina/sonic-boom#sonicboomopts

**Comment by cesarfd** [comment]
Solved https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44642

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
