### ISSUE TITLE
@types/stripe: 7.13.22  - stripe.charges.update() - amount field missing

### ISSUE THREAD

**Issue by alan345** [DefinitelyTyped/DefinitelyTyped#43944]
- [X] I tried using the "@types/stripe": "^7.13.22" package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wjohnsto and @CodeAnimal 
Definitions by: William Johnston <https://github.com/wjohnsto>, Peter Harris <https://github.com/codeanimal/>

We are using now Typescript and Stripe library: "@types/stripe": "^7.13.22",

Unfortunately, this exceptional call:

```
const charge = await stripe.charges.update(
  'ch_1CmMk3IyNTgGDVfzqgWGCQr5',
  {
    amount: 2500,
  }
);
```

Described here: https://stripe.com/docs/issuing/testing#increasing-the-amount-of-an-authorization is not correctly typed.

The type error thrown is: Argument of type '{ amount: number; }' is not assignable to parameter of type 'ChargeUpdateParams'.

It is because this hook: Update a charge (https://stripe.com/docs/api/charges/update) doesn't have the value "amount" in the type 'ChargeUpdateParams'.
Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
