### ISSUE TITLE
[@types/passport-local] IVerifyOptions should be relaxed.

### ISSUE THREAD

**Issue by pruhstal** [DefinitelyTyped/DefinitelyTyped#43976]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/passport-local` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SomaticIT 

Problem:

passport.js [allows for an optional info object to be passed to the done callback](https://github.com/jaredhanson/passport/blob/master/lib/middleware/authenticate.js#L214
). I've used it before without TypeScript, now adding these definitions I get an error.

The `IVerifyOptions` [interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/passport-local/index.d.ts#L26-L28) is too limited (not sure why it got typed like this to begin with considering [there's an additional `type` key that was left out as well](https://github.com/jaredhanson/passport/blob/master/lib/middleware/authenticate.js#L232)) 

My proposal (on the following line
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/passport-local/index.d.ts#L43):

`done: (error: any, user?: any, options?: any)`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
