### ISSUE TITLE
@types/prosemirror-state: pluginKey.getState() is not typed

### ISSUE THREAD

**Issue by andrey-skl** [DefinitelyTyped/DefinitelyTyped#43982]
When one gets plugin state by the following code, they get `any` type while it is possible to type as PliginState:
```
type PluginState = {foo: boolean};
const pluginKey = new PluginKey<PluginState, Schema>('foo-plugin');

...

const pluginState = pluginKey.getState(editorState); // typed as any
```

Here is the place where `T` should be used instead of `any`:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/abe7571daf1b1b864cd6d1790670f1c910d1ea34/types/prosemirror-state/index.d.ts#L154

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
