### ISSUE TITLE
[@types/react-router] v3 - `InjectedRouter.router` missing some properties.

### ISSUE THREAD

**Issue by billyvg** [DefinitelyTyped/DefinitelyTyped#44055]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

If you do not mention the authors the issue will be ignored.

There seems to be a few properties missing in `InjectedRouter`
Here is an example https://codesandbox.io/s/exciting-night-ph3i6?file=/src/index.tsx
 
The commented out properties below exist but are missing in the type defs when using `withRouter` to inject `router`.

```
export interface InjectedRouter {
  // getCurrentLocation;
  // listenBefore
  // listen
  // transitionTo
    push: LocationFunction;
    replace: LocationFunction;
    go: GoFunction;
    goBack: NavigateFunction;
    goForward: NavigateFunction;
    //createKey
    createPath: CreatePartFunction<Path>;
    createHref: CreatePartFunction<Href>;
    //createLocation
    setRouteLeaveHook: LeaveHookFunction;
    isActive: ActiveFunction;
    // location
    // params
    // routes
}
```

You can see an example here: https://codesandbox.io/s/exciting-night-ph3i6?file=/src/index.tsx

/cc @sergey-buturlakin @mrk21 @vasek  @ngbrown @awendland @KostyaEsmukov @johnnyreilly @LKay @DovydasNavickas @ssorallen @gillchristian @nulladdict

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
