### ISSUE TITLE
@types/chrome-apps namespace seems incorrect?

### ISSUE THREAD

**Issue by darrnshn** [DefinitelyTyped/DefinitelyTyped#44165]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @niikoo @AdamLay @pine613 @mzsm @pyle @matthewkimber @otiai10 @couven92 @rreverser @sreimer15

Interfaces like `AppWindow` are namespaced under `chrome.app` rather than `chrome.app.window`, which seems wrong given the API is the `chrome.app.window` [API](https://developer.chrome.com/apps/app_window)?

**Comment by pyle** [comment]
Looks like we did this per the spec for @types/chrome but not @types/chrome-apps.

We should update it so that it matches the IDL file: https://source.chromium.org/chromium/chromium/src/+/master:extensions/common/api/app_window.idl

@niikoo was there a particular reason why it was done this way?

**Comment by pyle** [comment]
I think what we'll do is look to changing these to match the IDL spec above (). This will likely break some peoples code but fixing will be trivial.
While we're at it probably best to look at a solution to convert the IDL spec to a Typescript typing so that updates and changes in the future to Chrome APIs will be trivial.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
