### ISSUE TITLE
AngularFire correction and any example please?

### ISSUE THREAD

**Issue by kpgarrod** [DefinitelyTyped/DefinitelyTyped#4418]
There is a small issue with the definition of AngularFireArray.$watch. The callback receives an event object, not three separate parameters, so I think it should look like this:

```
interface AngularFireEvent{
    event: string;
    key: string;
    prevChild: string;
}
interface AngularFireArray extends Array<AngularFireSimpleObject> {
    $watch(cb: (AngularFireEvent) => void, context?: any): Function;
}
```

This may be a separate issue, but I am having real difficulty understanding how to use the defs to retrieve an array and access the data returned by the $firebaseArray. The issue seems to be that the type of the response is an array of AngularFireSimpleObject s, which don't contain the attributes of my data.

I've tried 101 different approaches and haven't succeeded. If anybody has a working example I would really appreciate it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
