### ISSUE TITLE
@types/mongoose problem with `$in` query condition

### ISSUE THREAD

**Issue by grallm** [DefinitelyTyped/DefinitelyTyped#44212]
Hello,
I tried to use `@types/mongoose` but I had a problem with types.
In a find query `$in` should take an array. Actually it can take Regex or string but if you try with Mongo an array of ObjectIds is valid too.
![in-mongo-types](https://user-images.githubusercontent.com/11904039/80243868-47f23d80-8668-11ea-853e-ef25a3f75d18.png)

It would be nice to update the type :D

Authors: @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab 

Thanks !
Malo

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
