### ISSUE TITLE
lodash pick not catching error

### ISSUE THREAD

**Issue by staeke** [DefinitelyTyped/DefinitelyTyped#44211]
If you know how to fix the issue, make a pull request instead.

- [ x ] I tried using the `@types/lodash` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x  ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andy-ms 

Hello Andy (or others)

I'm having this code

```ts
const obj = {a: 1, c: 2};
pick(obj, "a", "b");
```

@types/lodash: 4.14.150
typescript: 3.8.3

This passes without error, which seems wrong to me as `b` doesn't exist. The culprit seems to be the overload of `pick` which just accepts a `PropertyPath[]`. Can we remove that overload? Or fix it some other way so that this error is being picked up.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
