### ISSUE TITLE
[ERROR]@types/zepto/index.d.ts is not a module.

### ISSUE THREAD

**Issue by Sara2009** [DefinitelyTyped/DefinitelyTyped#44289]
TS2306: File 'xxx\node_modules\@types\zepto\index.d.ts' is not a module.

tsconfig.js
```json
{
  "compilerOptions": {
    "target": "ES5",
    "module": "ESNEXT",
    "lib": [
      "es6",
      "dom"
    ],
    "allowJs": false,
    "jsx": "react",
    "declaration": false,
    "sourceMap": false,
    "rootDir": "./",
    "strict": true,
    "noImplicitAny": false,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}
```
In index.tsx
```typescript
import $ from 'zepto';
```

Then i modify the node_modules\@types\zepto\index.d.ts
```typescript
...
export = $;
```
The error disappeared.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
