### ISSUE TITLE
mongoose-paginate-v2 doesn't compile

### ISSUE THREAD

**Issue by EDI-carvajal** [DefinitelyTyped/DefinitelyTyped#44285]
![image](https://user-images.githubusercontent.com/50920544/80434872-99950500-88c0-11ea-87bd-2b197eed522f.png)

@linusbrolin 
@simonxca
@woutgg
@oktapodia
@ChazEpps
@gamsterx

Mongoose-pagination-v2 compilation fails.
In the definitions file you can see there is a problem of assigning a type to some string type. This will make it so that any project that uses those definitions fails to compile.
I'm using typescript 3.8.3

**Comment by gamsterx** [comment]
Can you please try and add `| null` to the `customLabel` and check if this fixes the error?

``` javascript
[customLabel: string]: T[] | number | boolean | null | undefined;
```

**Comment by EDI-carvajal** [comment]
Yes, it does work with that change, thank you very much.
Hopefully that gets updated on the npm repo soon too

**Comment by pzmarzly** [comment]
For the reference: change merged in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45406 and is present in the latest version on the npm (1.3.7). I think the issue could be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
