### ISSUE TITLE
Alternatives to applying formatting to defs via PR

### ISSUE THREAD

**Issue by jedwards1211** [DefinitelyTyped/DefinitelyTyped#44286]
In a PR I made, people were complaining that formatting fixes (which were caused by a format on save IDE extension) were distracting, and were asking me to move the formatting fixes to a separate PR.

This seems totally unsustainable though.  Reviewing a PR just to apply formatting obviously isn't worth any maintainer's time, since _running prettier on a package and committing it directly would be faster than verifying a PR_.  Unless you set up some kind of bot to verify and merge automatically I guess.  I wouldn't want to bug any of you with a PR that just applies formatting to a package.

I do think it would be great to have more formatting though because would save all of us time when contributing changes.  We all have better things to do than maintain format by hand.

So it seems like the alternative options are:
* Format the whole repo, and enforce formatting with commit hooks/CI (I made a PR that implements enforcement: #42991)
* Move prettier config into an empty folder, symlink it into only those directories that should be formatted
* Design a system for flagging packages as formatted, so that commit hooks/CI only enforce format for those packages
* Abandon all plans for formatting, remove prettier configuration

The hassle I'm seeking to prevent is that people using a Prettier IDE extension have to:
* Remember to disable format on save when working on most type definitions here
* And if they forgot, go to extra trouble to undo accidentally committed formatting, unless they push back like I did

**Comment by peterblazejewicz** [comment]
I'd like to see opt-in based behavior:
* PR to the package can add package-level `.prettierrc` (or which ever config type is preffered. Prettier config at package level is fully acceptable, as Prettier support composition like EditorConfig).
* maintainers of the package can vote to preffer TABS, instead of spaces (there are some packages formatted solely using TABS here)
* if there is no `.prettierrc` on package level, it means behavior as usual.

Allowing `.prettierrc` on package level would require asking MS folks for opinion.

**Comment by jedwards1211** [comment]
Unfortunately one maintainer I talked to isn't interested in extra infrastructure to actually enforce formatting in pre-commit or CI: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44277#issuecomment-620694591

**Comment by peterblazejewicz** [comment]
Yes, as said, this could be probably an opt-in, on condition that DT package maintainers (from package TS head) agree. So only opt-in and (if agreed) per-package only. 
As read in the comment:
> prettier is an opt-in thing for people on DT

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
