### ISSUE TITLE
Leaflet 1.6.0 : L.Layer interface lacks feature property

### ISSUE THREAD

**Issue by TimeBandit** [DefinitelyTyped/DefinitelyTyped#44293]
@alejo90 @atd-schubert @mcauer 

**Description**
I tried using the `@types/leaflet": "^1.5.12"` package and had problems
I cannot access the feature property on the Layer object without getting the linting error:

**Error**
> any
> Property 'feature' does not exist on type 'Layer'

![code](https://user-images.githubusercontent.com/2059850/80487319-859ae300-8954-11ea-9c90-a508bfcbebac.png)

I know the property exits by looking at the console.
![Screenshot from 2020-04-28 13-32-16](https://user-images.githubusercontent.com/2059850/80487511-d4487d00-8954-11ea-9811-5c27aa2c9757.png)

**Environment**
I am using:
"@types/leaflet": "^1.5.12",
"leaflet": "^1.6.0",
"typescript": "~3.7.5",

**Comment by kygoh** [comment]
If you refer to the [Leaflet API Reference]( https://leafletjs.com/reference-1.6.0.html), the [Layer base class]( https://leafletjs.com/reference-1.6.0.html#layer) does not contain feature property. This can also be verified from the [leaflet source](https://github.com/Leaflet/Leaflet/blob/f662d44af5170bb5ba4ffb8a9b644c9569bcdd66/src/layer/Layer.js#L30-L119).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by domdfcoding** [comment]
The `feature` property does exist, but only for layers of GeoJSON classes. It's set dynamically by that class on all of its layers.

https://github.com/Leaflet/Leaflet/blob/c06df2473736ab28c2e28868df5e8b82cd2dc7ae/src/layer/GeoJSON.js#L123
