### ISSUE TITLE
[@types/ioredis] wrong return type for xread and xreadgroup

### ISSUE THREAD

**Issue by jeremychone** [DefinitelyTyped/DefinitelyTyped#44301]
- [x] I tried using the `@types/ioredis` package and had problems.

Package: @types/ioredis
Version: 4.16.0

## Problem
xread and xreadgroup return wrong type (see [index.d.ts @xread](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ioredis/index.d.ts#L831) )

Currently, both `xread` and `xreadgroup` return  type ` Array<[string, string[]]>` which does not match the ioredis result. 

## Solution (proposal)

The correct returns are: 
- `xgroup` is `[string, [string, string[]][]][] | null`
- `xgroupread` is `[string, [string, string[]][]][]` (xgroupread throws exception if stream does not exist, so never returns null). 

#### Side note

In my small [redstream](https://github.com/briteboard/node-redstream/blob/master/src/ioredis-type-helpers.ts) ioredis backed lib, as I found these array chain a little overwhelming, I decomposed them in my small semantic type as follow. It probably can be improved further. 

```ts
export type StreamName = string;
export type EntryId = string;
export type EntryRaw = [EntryId, string[]];
export type StreamReadRaw = [StreamName, EntryRaw[]][]; // [string, [string, string[]][]][]
```

Authors: @thmiyathmary @Plantain @chrisleck @aliarham11 @br8h @shaharmor @palindrom615 @reconbot @funthing @iamolegga @tingwai @pettyalex @SimonSchick @tianlinle @demian85

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
