### ISSUE TITLE
@types/url-parse Url.query should be string or map or any

### ISSUE THREAD

**Issue by gauthierm** [DefinitelyTyped/DefinitelyTyped#44318]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ChernenkoPaul @harisiva @DimitryDushkin @davidgoli

If you do not mention the authors the issue will be ignored.

The url-parse package by default parses the query string as a string. You can pass `true` or a function to the parse function to parse the query string into a key-value object like the current type definitions, but it is not the default behavior.

Maybe the parse function could be overloaded to return a string for query when false is passed or the value is omitted. Something like:

```ts
interface URLParseDefault extends URLParse {
    readonly query: string;
}

interface URLParseQueryString extends URLParse {
    readonly query: { [key: string]: string | undefined };
}

new(address: string): URLParseDefault;
new(address: string, parser: false): URLParseDefault;
new(address: string, parser: true): URLParseQueryString;
new(address: string, parser?: boolean | URLParse.QueryParser): URLParse;
new(address: string, location?: string | object, parser?: boolean | URLParse.QueryParser): URLParse;
...
```

If you wanted to be really fancy a generic type could also be added to `URLParse.QueryParser` to handle cases when custom query string parsing does not return type `object`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
