### ISSUE TITLE
Property 'heatLayer' does not exist on type 

### ISSUE THREAD

**Issue by manukrishnankt** [DefinitelyTyped/DefinitelyTyped#44325]
`
initialGraph() {
    var cities = L.layerGroup();
    var mbAttr = '';
    L.marker([52.505, -0.09]).bindPopup('This is Littleton, CO.').addTo(cities),
    L.marker([53.505, -0.09]).bindPopup('This is Denver, CO.').addTo(cities),
    L.marker([54.505, -0.09]).bindPopup('This is Aurora, CO.').addTo(cities),
    L.marker([55.505, -0.09]).bindPopup('This is Golden, CO.').addTo(cities);

    var steman = L.tileLayer('https://stamen-tiles-{s}.a.ssl.fastly.net/toner/{z}/{x}/{y}{r}.{ext}', {
      attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
      subdomains: 'abcd',
      minZoom: 0,
      maxZoom: 20,
    });
    this.newAddressPoints = addressPoints.map(function (p) { return [p[0], p[1]]; });
    var heat1 =L.heatLayer(this.newAddressPoints,{});
    var baseLayers = {
      "steman": steman,
	  "heat1 ,heat1 
    };
    var overlays = {
      "Cities": cities
    };
    L.control.layers(baseLayers, overlays).addTo(this.map);
  } 
}
`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
