### ISSUE TITLE
Duplicate identifier 'mod' with @types/node and @types/requirejs

### ISSUE THREAD

**Issue by rafaelytakei** [DefinitelyTyped/DefinitelyTyped#44340]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jbaldwin @DefinitlyTyped

I'm currently getting the following errors when using @types/node and @types/requirejs simultaneously: 

`ERROR in C:/xampp/htdocs/webpack_test-1/node_modules/@types/node/module.d.ts(57,14):
TS2300: Duplicate identifier 'mod'.
ERROR in C:/xampp/htdocs/webpack_test-1/node_modules/@types/requirejs/index.d.ts(38,11):
TS2300: Duplicate identifier 'mod'.
ERROR in C:/xampp/htdocs/webpack_test-1/node_modules/@types/requirejs/index.d.ts(422,13):
TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
