### ISSUE TITLE
maskedinput definition file does not match up with linked documentation

### ISSUE THREAD

**Issue by tysonzero** [DefinitelyTyped/DefinitelyTyped#4434]
In maskedinput.d.ts (and the respective tests) it states that `maskedinput.js` adds a method to `jQuery` called `inputmask` whereas in the project that is linked's documentation (and source code) it states that it adds a method to `jQuery` called `mask`.

I am not sure which should be changed, as it is possible that the d.ts file references a totally different but valid `maskedinput` library, or it could be that it should actually be `mask`.

**Comment by vvakame** [comment]
@tysonzero please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
