### ISSUE TITLE
[@types/recharts] FunnelChart, Funnel and Sankey type definitions are missing.

### ISSUE THREAD

**Issue by salomonMuriel** [DefinitelyTyped/DefinitelyTyped#44363]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rapmue @royxue @ZheyangSong @richbai90 @Gerhut 

If you do not mention the authors the issue will be ignored.

FunnelChart, Funnel and Sankey type definitions are missing. I'm too much of a newb to know how to fix it properly by myself, sorry!

**Comment by moonray** [comment]
Half a year later. Some chart types are sadly still missing.

**Comment by salomonMuriel** [comment]
I had to move to nivo.rocks due to this :(

**Comment by merylstreep** [comment]
Still unresolved : (

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
