### ISSUE TITLE
Puppeteer: incorrect return type for $eval and $$eval

### ISSUE THREAD

**Issue by drmercer-lucid** [DefinitelyTyped/DefinitelyTyped#44403]
The types for Puppeteer incorrectly claim that `$eval` and `$$eval` will wrap elements returned from the parameter function in ElementHandles. In reality, they only return serializable objects, so returning an Element results in `{}` (an empty object) being returned. See puppeteer/puppeteer#2609 and [the Puppeteer docs themselves](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pageevalselector-pagefunction-args-1) for more details. 

- [x] I tried using the `@types/puppeteer` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @marvinhagemeister @cdeutsch @ksm2 @SimonSchick @SerbanGhita @JasonKaz @davecardwell @angrykoala

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
