### ISSUE TITLE
node-zopfli-es.gzipSync

### ISSUE THREAD

**Issue by dilyanpalauzov** [DefinitelyTyped/DefinitelyTyped#44436]
types/node-zopfli-es/index.d.ts says gzipSync() accepts one parameter (options) but in reality it accepts two parameters: input buffer and optional options.

@Alorel

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
