### ISSUE TITLE
@types/node-schedule TS2339: Job#nextInvocation is not Date

### ISSUE THREAD

**Issue by NCPlayz** [DefinitelyTyped/DefinitelyTyped#44443]
- [x] I tried using the `@types/node-schedule` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @cyrilschumacher, @flowpl, @spike008t 

The problem is that Job#nextInvocation returns a CronDate, not a Date. CronDate can be found at https://github.com/harrisiirak/cron-parser/blob/master/lib/index.d.ts#L3 but is not an exported member therefore cannot be used as a type (AFAIK), but this issue is a bit of an annoyance since trying to use its methods to get a Date (`CronDate#getDate`) results in a TS2339. 
```ts
src/test.ts:74:52 - error TS2339: Property 'toDate' does not exist on type 'Date'.

74           let dur = moment.duration(nextInvocation.toDate() - Date.now());
                                                      ~~~~~~

src/test2.ts:53:48 - error TS2339: Property 'toDate' does not exist on type 'Date'.

53       let dur = moment.duration(nextInvocation.toDate() - Date.now());
                                                  ~~~~~~
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
