### ISSUE TITLE
[@types/heatmap.js] 'ILayer' interface error

### ISSUE THREAD

**Issue by diogo-rocha** [DefinitelyTyped/DefinitelyTyped#44453]
I tried using the `@types/heatmap.js` package and got the following error:

![error](https://i.imgur.com/9amPebf.png)

This cause the app to be stuck on last building step. What could be the cause?
I'm not sure if the issue is related with `@types/heatmap.js` or `@types/leaflet` since I'm using both so I'm mentioning authors of each of the packages.

**Environment**:
```
"typescript": "~3.7.5"
"@types/leaflet": "^1.5.12"
"leaflet": "^1.6.0"
"heatmap.js": "^2.0.5"
"@types/heatmap.js": "^2.0.36"
```
Authors: @lookuptable @rhys-vdw @alejo90 @atd-schubert @mcauer @ronikar @SanFrisc @life777 @henrythasler

**Comment by danmana** [comment]
Looks like `@types/heatmap.js` [depends on leaflet/v0](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/heatmap.js/tsconfig.json#L19) type definitions, which contain [ILayer](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet/v0/index.d.ts#L1314).

I don't know if there is any mechanism to handle conflicting `@types` versions ...  
The only thing you could do is make a PR to DefinitelyTyped to update heatmap.js to use latest leaflet types.

**Comment by rhys-vdw** [comment]
Yep. IIRC the types used to be for some leaflet plugin, and I left them at the bottom of the file. This was one of my earlier forays into typing... I'm pretty sure the leaflet stuff simply should not exist in this type set.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
