### ISSUE TITLE
Duplicate identifier 'submitAsSideEffect' in types/redux-form/lib/reduxForm.d.ts

### ISSUE THREAD

**Issue by mhall94** [DefinitelyTyped/DefinitelyTyped#44475]
Using the `@types/redux-form:8.2.4` package and had problems when building app.

Authors: @jeppeman in commit f7b47ec4d39eff52b9e204da84e7d8202765d907

![image](https://user-images.githubusercontent.com/7817258/81007395-0a9c6580-8e49-11ea-81fc-444ac61c3a58.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
