### ISSUE TITLE
findByIdAndUpdate returned value does not contain value or lastErrorObject or ok properties

### ISSUE THREAD

**Issue by manekshms** [DefinitelyTyped/DefinitelyTyped#44474]
findByIdAndUpdate return Query Object. but in type definition file its shows 

`export interface FindAndModifyWriteOpResultObject<TSchema> {
    //Document returned from findAndModify command.
    value?: TSchema;
    //The raw lastErrorObject returned from the command.
    lastErrorObject?: any;
    //Is 1 if the command executed correctly.
    ok?: number;
}`

There is no properties like value or lastErrorObject or ok
@peterblazejewicz @horiuchi @lukasz-zak

**Comment by peterblazejewicz** [comment]
@manekshms 
Let me know the version you're on. It seems that this specifi api has been decpreated:
http://mongodb.github.io/node-mongodb-native/3.6/api/lib_collection.js.html#line1796

**Comment by manekshms** [comment]
"@types/mongoose": "^5.7.14",
"mongoose": "^5.9.10",

**Comment by kenzik** [comment]
Seeing the same thing with:

```
"@types/mongoose": "^5.7.15",
"mongoose": "^5.9.12"
```

**Comment by kenzik** [comment]
I can confirm that the error we are seeing was introduced in 5.7.12.

**Comment by manekshms** [comment]
@peterblazejewicz Can you check that?

**Comment by neelav** [comment]
I think the issue has to do with this line: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L3452

When `rawResult: true`, the callback should use `FindAndModifyWriteOpResultObject` instead of `T`.  And when `rawResult: false`, then callback should use `T`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
