### ISSUE TITLE
[@types/lodash] [pick] Type difference between using _.pick and pick

### ISSUE THREAD

**Issue by zucker-rdrg** [DefinitelyTyped/DefinitelyTyped#44500]
In my example:

![code](https://user-images.githubusercontent.com/19388313/81117399-51608d00-8f27-11ea-97e8-ac55c3dbe715.png)
only test4 and test5 will throw a typescript error:
![error](https://user-images.githubusercontent.com/19388313/81117433-5d4c4f00-8f27-11ea-9e98-f95a0e5c9862.png)
I expect all of them to throw it.

So is there any correlation between import method (`_` or direct `pick`) and returning type?

My code
```js
public test1(x: {a: number, b: number}): { b: number } {
    return _.pick(x, 'a');
}

public test2(x: {a: number, b: number}): { b: number } {
    return _.pick<{ a: number }>(x, 'a');
}

public test3(x: {a: number, b: number}): { b: number } {
    const result = _.pick(x, 'a');
    
    return result;
}

public test4(x: {a: number, b: number}): { b: number } {
    const result: { a: number } = _.pick(x, 'a');
    
    return result;
}

public test5(x: {a: number, b: number}): { b: number } {
    return pick(x, 'a');
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
