### ISSUE TITLE
[@babel/traverse] Missing functionality

### ISSUE THREAD

**Issue by leafac** [DefinitelyTyped/DefinitelyTyped#44527]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @yortus @marvinhagemeister @rpetrich @mgroenhoff @tdreyno @dlgrit

The `@babel/traverse` library exports not only the `traverse()` function, but also [many auxiliary functions as properties of the `traverse()` function](https://github.com/babel/babel/blob/8aa5e574a0c47bd67614fb3a5042479889fed4fb/packages/babel-traverse/src/index.js#L43-L117), for example, `traverse.cheap()`.

Do you think we should add the type annotation for those auxiliary functions to make them available in TypeScript?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
