### ISSUE TITLE
FileSystemManager

### ISSUE THREAD

**Issue by xiaoqufengdi** [DefinitelyTyped/DefinitelyTyped#44563]
`    /**
		 * FileSystemManager.writeFile 的同步版本
         * @param filePath 要写入的文件路径
         * @param data 要写入的文本或二进制数据
         * @param encoding  指定写入文件的字符编码,合法值:"ascii", "base64", "binary", "hex", "ucs2/ucs-2/utf16le/utf-16le","utf-8/utf8", "latin1"
		 * @throws
		 * + fail no such file or directory, open ${filePath}	指定的 filePath 所在目录不存在
         * + fail permission denied, open ${dirPath}	指定的 filePath 路径没有写权限
         */
        wirteFileSync(filePath: string, data: string|ArrayBuffer, encoding: string): void;`
This is your code , but the name of Function is wrong.

**Comment by peterblazejewicz** [comment]
@xiaoqufengdi 
is this for types for https://github.com/chobits4/minapp-env?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
