### ISSUE TITLE
@types/babel__traverse is missing several isXXX methods

### ISSUE THREAD

**Issue by vedantroy** [DefinitelyTyped/DefinitelyTyped#44591]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @yortus @marvinhagemeister @rpetrich @mgroenhoff @dlgrit 

Not sure which version of the @types/babel__traverse I am using. I think it's the latest version (hence why I clicked the check mark). At the top it says "Type definitions for @babel/traverse 7.0"

I filed this issue in the babel repository, and they said to file it here, so I will just post the link to the Babel issue: https://github.com/babel/babel/issues/11535

**Comment by vedantroy** [comment]
Any update on this? I found several more issues in the typings. Specifically, all the "assert" methods are missing.

**Comment by hotlong** [comment]
+1

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
