### ISSUE TITLE
Google Map loading error in iOS and Safari browser "Total canvas memory use exceeds the maximum limit (Safari 12)"

### ISSUE THREAD

**Issue by venkatsan** [DefinitelyTyped/DefinitelyTyped#44604]
I am using google maps below version
from: @types/googlemaps@^3.30.9,
  _id: @types/googlemaps@3.39.1,
in my Ionic Angular application.
In safari browser while loading map it is getting error "Total canvas memory use exceeds the maximum limit (Safari 12)"

<img width="1664" alt="Screenshot 2020-05-10 at 1 12 46 AM" src="https://user-images.githubusercontent.com/489467/81483339-234ab800-925b-11ea-86d3-c319e09db533.png">

**Comment by peterblazejewicz** [comment]
The stack overflow is the best place for help. Seems to be implementation specific problem. Here is the repository for definition types only (that help to create a code with type checks), usage of types does not impact runtime problems at all.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
