### ISSUE TITLE
feat(@types/mongoose): a way to validate schema definitions against an interface.

### ISSUE THREAD

**Issue by Ranguna** [DefinitelyTyped/DefinitelyTyped#44623]
If you know how to fix the issue, make a pull request instead: Will do as soon as I know how to fix the described problem.

- [x] I tried using the `@types/mongoose` package and have _improvements_.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond
  - Authors: @karimsa of Schema method types

Currently there is no good way to tightly couple ts types to mongoose schemas, the usual way is to create an interface:
```ts
interface Animal {
  name: string;
}
```
And create the schema based on that:
```ts
new Schema({
  name: String
});
```

The problem with this is that you can do this:
```ts
interface Animal {
  name: number;
}

new Schema({
  name: Array,
  age: Number
});
```
And everything will still work.

My idea is to make Schema accept an interface that will validate the `type` prop in the schema:
```ts
interface Animal {
  name: string;
}

new Schema<Animal>({
  name: Array,
  age: Number
});
```
This would fail saying something along the lines of: `Type 'ArrayConstructor' is missing the following properties from type 'StringConstructor': fromCharCode, fromCodePoint, raw` and `Object literal may only specify known properties, and 'age' does not exist in type 'SchemaDefinition<Animal>'`.

The problem with this is that currently `Schema` already has one type parameter and I have no idea how to extend it with another one without breaking backward compatibility.

Any thoughts ?

Commit with working changes (but removed method name types and did not fix tests): https://github.com/Ranguna/DefinitelyTyped/commit/960c880eb297bafd892ff65903bda2b72bcaaa6b

--------------------------
URL to typescript playground: https://www.typescriptlang.org/play?ts=3.8.3#code/JYOwLgpgTgZghgYwgAgILIN4Chm+XALmQGcwpQBzAbhzwSNPJGttwBMGBPAWwCMB7ADY0AvlixhOABxQAVaRACycKTKgAeWQD5kAXlbJZyCAA9IINsWQgArn2gB+ZADk7vaAGF+IRjYRh+KGQCAyNTc0sSMkonAGVo5i8fMj8AoJC8fBBOGixQSFhEFFiEAAsIbjh5GQB5KTBiTR1sTLhBYDhiBwYElgMAegAqZC9ubm9kOrBgbysYQPxBQRIyirhkSRkrQf6DTYhuw1FxfeQS8sqAEQgYUGBp7009LM4dXUxWAG0pODBS5FAyAA1hBOPwYIYALpEc5raoQKaNeHKVTQTTfX6lSFaLTHLCCCBgZC8GGrK43O4PEDqVBvD6tIgtTJ4fYw3oGEQAGgM9HpzNwrLO7MyXIMHD5-MFsR4AkEAAoAJQc7mtCgQRkGTKC1z2KAcrBiIA

**Comment by Ranguna** [comment]
Pinging first author of mongoose types for opinions: @horiuchi

**Comment by karimsa** [comment]
Since `T` in `Schema<T>` refers to the currently defined methods in the schema, you could introduce a second generic `G` that has the shape of the properties. Something like:

```typescript
class Schema<T = any, G = any> extends ... {
   constructor(defn?: SchemaDefinition<G>, ...) { ... }
   ...
}
```

And then you can modify `SchemaDefinition` to only contain the keys that are also keys of `G`. For the values, you'll have to find a way to map the schema types to TS types for validation.

Ideally, we would use only one generic but for that we'd need to be able to separate the interface into one interface with only properties and one interface with only functions. I'm not sure this is possible in TS right now.

**Comment by Ranguna** [comment]
Aah you are right !

I don't know why but I thought that we had to define all type parameters or none, but yeah, it works if we add a default type :+1: .

> And then you can modify SchemaDefinition to only contain the keys that are also keys of G. For the values, you'll have to find a way to map the schema types to TS types for validation.

This is my current mapping:
```ts
type MapToSchemaType<T> =
    T extends string ? typeof String :
    T extends number ? typeof Number :
    T extends boolean ? typeof Boolean :
    T extends Date ? typeof Date :
    T extends Buffer ? typeof Buffer :
    T extends Array<any> ? typeof Array :
    T extends mongodb.Decimal128 ? typeof mongodb.Decimal128 :
    T extends mongodb.ObjectID ? typeof mongodb.ObjectID :
    T extends mongodb.ObjectId ? typeof mongodb.ObjectId :
    any;
```

> Ideally, we would use only one generic but for that we'd need to be able to separate the interface into one interface with only properties and one interface with only functions. I'm not sure this is possible in TS right now.

Actually, you can:
https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLLAB4QCbIN4BQyxyADlAPakCMAXMiAK4C2ARtANxEnlUBM9AM5gooAOZduxGCDrIAFAEpkAXgB8yAG4Vg2LiWQyByAGKMQCMMAoh9JGQGZ68gHRuANsGEB5GADkWdihBeiY2aABtAF1ldWRhURAxaIIAXwICMABPUhRvEHcsswsrGwAFSlI-OGYIQQAeABUNFWQy4AQAa3qpZEaAGmRevGQIgGlkUGROiCyKGD6ogFoAfnpG8ajkCAxIEGxBU3NLaxBkFeQJ0IhNaGRUiJm5hcaogjVMnLyCrL8bYpO5Uq1VqDWaqjaHW6vQGQwMI3GkzOT3mi1W602212EH2hwBpTOFxANzu9AmDxRLzeH0+uWQAFEMAh3IxsBBUHAwAgABbiCpUaBWOpNQYANRa+FGEymlLRaz6mJ2ewOyFF50uyGutyg90es1Rrwy7ggYGQcHo+UK+NO-KqNWF6Cw2A+xtNrAtPz+IGtQKoIIdmBwHyAA

But I think using two is good. One is the actual document that you use in `Model.create`, for example, and the other is the return of functions like `findOne`.

**Comment by karimsa** [comment]
That's cool. I didn't realize TS had ternaries for picking types now.

I think it makes sense to offer a single generic then, and internally separate it into two interfaces. Then you can use the props-only type for the document methods like `.create()` and use the full document for things like `.findOne()`. Otherwise, the user of the package has to remember to keep their types separate and that can be annoying since you want your ORM to maintain the type consistency for you.

**Comment by Ranguna** [comment]
Sounds good. I'll update my branch and make a PR soon.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
