### ISSUE TITLE
Problem with findByIdAndUpdate with mongoose and typescript

### ISSUE THREAD

**Issue by NervenCid** [DefinitelyTyped/DefinitelyTyped#44624]
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/mongoose` package and had problems.

With this line:

const newData: any= request.payload;
const updatedUser = await User.findByIdAndUpdate(request.params.id, newData);

I get this error;

Argument of type 'string | object | Readable | Buffer' is not assignable to parameter of type 'MongooseUpdateQuery<Pick<IUser, "_id" | "username" | "fullname" | "password" | "comparePassword">>'.
Type 'string' is not assignable to type 'MongooseUpdateQuery<Pick<IUser, "_id" | "username" | "fullname" | "password" | "comparePassword">>'.
Type 'string' is not assignable to type 'DotAndArrayNotation'.ts(2345)

But i don't know if it is a bug, it don't take "request.payload" directly

**Comment by kenzik** [comment]
Related to #44474?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
