### ISSUE TITLE
[@types/seamless-immutable] does not define `Immutable.set`

### ISSUE THREAD

**Issue by chuyik** [DefinitelyTyped/DefinitelyTyped#44657]
- [x] I tried using the `@types/seamless-immutable` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @zvs001 @alex3165 @xsburg @geirsagberg @RMHonor @pheromonez

It looks like the type definition does not define static methods like `Immutable.set` `Immutable.merge`.

Example:

```ts
var obj = Immutable({type: "parrot", subtype: "Norwegian Blue", status: "alive"});
// REPORT: Property 'set' does not exist on type 'typeof SeamlessImmutable'
Immutable.set(obj, "status", "dead");
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
