### ISSUE TITLE
@types/react-infinite-scroller export InfiniteScrollProps?

### ISSUE THREAD

**Issue by bmaclean** [DefinitelyTyped/DefinitelyTyped#44726]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fc8478c7cc45f20eff9295e6ccef0e394f4e81be/types/react-infinite-scroller/index.d.ts#L16

**Comment by bmaclean** [comment]
Given that it's in the public API, is there any reason we shouldn't export `InfiniteScrollProps` in the `InfiniteScroll` namespace here? I'm trying to write a light wrapper around `InfiniteScroll` and would like to extend its props directly.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
