### ISSUE TITLE
Add a openpgp keyId type

### ISSUE THREAD

**Issue by Gaff** [DefinitelyTyped/DefinitelyTyped#44736]
Is it possible to cretae a type for `getKeyId()` so that typescript recognises calls to `toHex()` etc?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c1e6c4907158dd9c4e5324e1d25a6520fd81dfc2/types/openpgp/ts3.2/index.d.ts#L3830

**Comment by peterblazejewicz** [comment]
@Gaff
So it incorrectly states (because of JSDoc {String} type), that it returns a string, while in fact this is a custom type?
https://github.com/openpgpjs/openpgpjs/blob/5d9629d6a3cf73dbda48611b530a1e039aab0295/src/type/keyid.js

**Comment by Gaff** [comment]
Right.

You'll have to bear with me because my Javascript / Typescript knowledge isn't great, but you can see in the openpgp unit tests that they invoke the `.toHex()` method on it:

https://github.com/openpgpjs/openpgpjs/blob/6214459dfbc340709f682f42205aa4b7d30fa267/test/general/keyring.js#L139

**Comment by Gaff** [comment]
Are you saying that the issue here is because the method doc claims it returns a String?

https://github.com/openpgpjs/openpgpjs/blob/fbbeaa3cd98d6b422867a38576b019731933bf54/src/packet/public_key.js#L201

If so I'll chase upstream.

**Comment by peterblazejewicz** [comment]
Keep us in the loop! Thx!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
