### ISSUE TITLE
@type/simpl-schema - wrong type for check

### ISSUE THREAD

**Issue by CaptainN** [DefinitelyTyped/DefinitelyTyped#44774]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/843feeed9961898fc2d73dc80dba3502f6608386/types/simpl-schema/index.d.ts#L97

This is the wrong value. It should actually be a reference to the check function from the `meteor/check` package. I'm not sure how to spec that - but [it's not a boolean](https://github.com/aldeed/simple-schema-js#validate-a-meteor-method-argument-and-satisfy-audit-argument-checks).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
