### ISSUE TITLE
Generic type 'ErrorRequestHandler' requires between 0 and 3 type arguments.

### ISSUE THREAD

**Issue by pavel-butkevich-98** [DefinitelyTyped/DefinitelyTyped#44808]
Hi! Have next dep in my package.json file:  "express": "4.17.1", "@types/express": "4.17.3",     "express-session": "1.17.1".
Now I'm trying to add  "@types/express-session": "1.17.0" but have the next errors in console.
Can anybody help me?
![image](https://user-images.githubusercontent.com/45014413/82150818-e46fc000-9861-11ea-9c72-b9d7f71f63a5.png)
![image](https://user-images.githubusercontent.com/45014413/82150715-9e1a6100-9861-11ea-9061-05b0bd6f9f12.png)
- Authors: @TheHandsomeCoder, @donnut, @mdekrey, @mrdziuban, @sbking, @afharo, @teves-castro, @1M0reBug, @hojberg, @samsonkeung, @angeloocana, @raynerd, @moshensky, @ethanresnick, @deftomat, @blimusiek, @biern, @rayhaneh, @rgm, @drewwyatt, @jottenlips, @minitesh, @Krantisinh, @pirix-gh, @brekk, @Nemo108, @jituanlin, @Philippe-mills, @Saul-Mirone

**Comment by HughEdwards1** [comment]
Also an issue for me using passport.

**Comment by mr-kapoor** [comment]
Same issue

**Comment by MoonLiightz** [comment]
Same for me. I went back to `@types/express@4.17.4` that works for me with TypeScript `3.9.5`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
