### ISSUE TITLE
@types/babel-types should be renamed

### ISSUE THREAD

**Issue by vedantroy** [DefinitelyTyped/DefinitelyTyped#44817]
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @yortus @baxtersa @marvinhagemeister @bcherny 

The `babel-types` package has been renamed to `@babel/types`. I think this means installing `@types/babel-types` is no longer useful, because while I can do `import * as t from 'babel-types'` after installing the typings, I need to actually be doing `import * as t from @babel/types`

**Comment by 43081j** [comment]
`@babel/types` ships its own types now afaik. you don't need a `@types` package anymore

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
