### ISSUE TITLE
atom: CompositeDisposable not declared

### ISSUE THREAD

**Issue by pimartin** [DefinitelyTyped/DefinitelyTyped#4482]
Concerns atom/atom.d.ts

I've tried to use TypeScript with a package based on the basic template but it seems the CompositeDisposable isn't defined in the "atom" module.

Here is the documentation page about it : https://atom.io/docs/api/v0.204.0/CompositeDisposable

**Comment by vvakame** [comment]
https://github.com/vvakame/atom-dts-generator
I'm working on it. but needs more time.

**Comment by pimartin** [comment]
Ok, thanks.

**Comment by enlight** [comment]
I'm working on updating the Atom typings for the 1.0 release, [WIP here](https://github.com/enlight/atom-typings), will submit PRs when done. Auto-generating the typings from the docs is a cool idea @vvakame, unfortunately the docs are incomplete so I'm just doing everything by hand.

**Comment by tarak162** [comment]
Any update on this?

**Comment by RikkiGibson** [comment]
Is this still unresolved?

**Comment by hszhsh** [comment]
Is there anyone still working on this?

**Comment by smhxx** [comment]
The issue mentioned in the title was resolved with #19993, then `CompositeDisposable` was subsequently moved to `@types/event-kit` where it belongs as part of #20146. Safe to close this issue/mark as resolved.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
