### ISSUE TITLE
Deprecate moment-timezone types

### ISSUE THREAD

**Issue by ellenaua** [DefinitelyTyped/DefinitelyTyped#44822]
Hi guys!

There has been a pull request into Moment-Timezone with .dts files which was waiting for merge. I merged that and now moment-timezone has its own .dts file inside. It's in new release of moment-timezone - 0.5.30

But users who have installed @types/moment-timezone now have this issue:
```
Cannot redeclare block-scoped variable 'tz'.
```

Can you please mark @types/moment-timezone as deprecated and since  moment-timezone version 0.5.30 dts files will be inside moment-timezone

**Comment by ellenaua** [comment]
Opened a pull request https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44823

**Comment by oboz** [comment]
Thanks! You save my day

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
