### ISSUE TITLE
[jest] Default toMatchObject's type to DeepPartial

### ISSUE THREAD

**Issue by stephenh** [DefinitelyTyped/DefinitelyTyped#44854]
Right now the definition of `toMatchObject` is:

```typescript
toMatchObject<E extends {} | any[]>(expected: E): R;
```

Which means just doing:

```typescript
const actual = { position: { x: 0; y: 0 };
expect(actual).toMatchObject({ position: { x: 0 } });
```

Doesn't provide any type-checking or auto-complete.

I can manually specify the type of `E`, but if I'm doing sub-object-matching (which is the primary usefulness of `toMatchObject` afaiu), then I need to (deep) partialize it, i.e.:

```typescript
expect(actual).toMatchObject<DeepPartial<typeof actual>>({ position: { x: 0 } });
```

Which is fairly verbose.

AFAIU `toMatchObject` could be changed to assume a default type of `E`, i.e.:

```typescript
toMatchObject<E extends {} | any[] = DeepPartial<T>>(expected: E): R;
```

Which, again afaiu, accurately describes the shape that `expected` should be.

Would this change be accepted if I submit a PR? 

cc @G-Rath @SimenB and @devanshj as blame shows you are recent contributes to the jest typings.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
