### ISSUE TITLE
angular-ui-* module structure consistency

### ISSUE THREAD

**Issue by mikecole** [DefinitelyTyped/DefinitelyTyped#4490]
I am using the definitions for both angular-ui-sortable and angular-ui-bootstrap, and the module structure is inconsistent between the two. Should there be an initiative to make them similar since the projects are closely related?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
