### ISSUE TITLE
LoDashObjectWrapper's generics don't work with ObjectIterator's

### ISSUE THREAD

**Issue by akalman** [DefinitelyTyped/DefinitelyTyped#4491]
ObjectIterator's definition is:

``` typescript
interface ObjectIterator<T, TResult> {
    (element: T, key: string, list: any): TResult;
}
```

and LoDashWrapper's map definitions is:

``` typescript
    interface LoDashObjectWrapper<T> {
        map<T extends {}, TResult>(
            callback: ObjectIterator<T, TResult>,
            thisArg?: any): LoDashArrayWrapper<TResult>;
    }
```

since the T parameter is extending `{}`, and the value function is typed like this `value(): T`, the generic parameter of LoDashObjectWrapper is the object itself, not the type of its properties.  This means that the correct definitions of LoDashObjectWrapper's map is this

``` typescript
interface LoDashObjectWrapper<T extends Dictionary<TValueType>> {
    map<TValueTypeResult>(
        callback: ObjectIterator<TValueType, TValueTypeResult>,
        thisArg?: any): LoDashArrayWrapper<TValueTypeResult>;
}
```

this is just one example where the generic parameter on LoDashObjectWrapper is sometimes used to refer to the object itself, and sometimes the type of its properties.

**Comment by vvakame** [comment]
@akalman please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
