### ISSUE TITLE
[@types/react] Infer types from children

### ISSUE THREAD

**Issue by caasi** [DefinitelyTyped/DefinitelyTyped#44974]
I tried to infer some of my React component property types from children, but every child is typed as `JSX.Element`.

Is it possible to improve type definitions so the property type remained in `JSX.Element`?

Currently I can only preserve children length:

```typescript
export interface InteractionProps<T> {
  name?: string;
  value?: T;
  onChange?: (v: T) => void;
}

type MapTupleToInteractionElement<T extends any[]> = {
  [P in keyof T]: ReactElement<InteractionProps<T[P]>>
}

interface Props<T extends any[]> extends InteractionProps<T> {
  children?:
  T extends [infer U]
  ? ReactElement<InteractionProps<U>>
  : T extends any[]
  ? MapTupleToInteractionElement<T>
  : never
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
