### ISSUE TITLE
ElasticSearch Types

### ISSUE THREAD

**Issue by cawoodm** [DefinitelyTyped/DefinitelyTyped#44991]
The `search` method on the ElasticSearch `Client` accepts a 2nd parameter which can contain e.g. `headers` for authentication, `ignore`, `macRetries` etc.
See https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html
```
const result = await client.search({
  index: 'my-index',
  from: 20,
  size: 10,
  body: { foo: 'bar' }
}, {
  ignore: [404],
  maxRetries: 3
})
```
The current type definition does not reflect this:
```
search<T>(params: SearchParams, callback: (error: any, response: SearchResponse<T>) => void): void;
search<T>(params: SearchParams): Promise<SearchResponse<T>>;
```
The error is therefore:
> Argument of type '{ headers: any; }' is not assignable to parameter of type '(error: any, response: SearchResponse<unknown>) => void'.
>  Object literal may only specify known properties, and 'headers' does not exist in type '(error: any, response: SearchResponse<unknown>) => void'.

Could you update the signature to reflect this?

Also, why the `void` result?

  - Authors: @CasperSkydt, @bfsmith

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
