### ISSUE TITLE
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/agora-rtc-sdk/index.d.ts 期望能够提供一份中文版本

### ISSUE THREAD

**Issue by nxboo** [DefinitelyTyped/DefinitelyTyped#45058]
声网是中国著名的音视频提供商
期望能够提供一份中文版本，方便国内开发者

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
