### ISSUE TITLE
Typings for edge endpoints isn't included yet

### ISSUE THREAD

**Issue by MatthijsBon** [DefinitelyTyped/DefinitelyTyped#45090]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @phreed 
@wy193777 
@ypconstante  
@janniclas  
@Cerberuser
@gsbelarus 
@PeterJFerrarotto 
@Spaxe 
@appleparan 

The following stylesheet causes errors:

```typescript
export const style: cytoscape.Stylesheet[] = [
	{
		// source-endpoint and target-endpoint cause warnings
		"selector": "edge.a",
		"style": {
			"curve-style":"straight",
			"source-endpoint":"0px 7px",
			"target-endpoint":"0px -25x",
		},
	},
	{
		// Same when trying unbundled-bezier
		"selector": "edge.b",
		"style": {
			"curve-style":"unbundled-bezier",
			"source-endpoint":"0px 7px",
			"target-endpoint":"0px -25x",
		},
	},
];
```
```
Type '{"curve-style": "straight";"source-endpoint": string;"target-endpoint": string;}' 
is not assignable to type 'Node | Edge | Core'. 
Object literal may only specify known properties, and '"source-endpoint"' does not exist in type 'Node | Edge | Core'.
```

It seems as if definitions are missing?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
