### ISSUE TITLE
react-table: nested headers typed as ColumnInstance, but do not match interface.

### ISSUE THREAD

**Issue by Bonnevie** [DefinitelyTyped/DefinitelyTyped#45113]
There seems to be a discrepancy in how `ColumnInstance` is typed, and how it used, particularly for nested headers where the nesting is defined by a `headers` property that is missing from the interface. 

```
let {headerGroups} = useTable({ data, columns});
let col: ColumnInstance<T> = headerGroups[0].headers[0] // headers are ColumnInstance arrays
console.log("col", col); // has a `headers` property if nested 
console.log("col", col.headers) // fails as `headers` is not a property of the ColumnInstance interface
```

@ggascoigne @stramel @gargroh @riceboyler

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
