### ISSUE TITLE
[@types/node] Generic types on streams

### ISSUE THREAD

**Issue by kbariotis** [DefinitelyTyped/DefinitelyTyped#45196]
Hey all, I would like to bump up these two issues (if you know of more please add them to the list) regarding adding generic types to the `stream` module.

I would love to go ahead and make an initial PR but just wanted to get your opinion on the matter. A good starting point could be just by adding a generic type to Readable/Writable.

- https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19761
- https://github.com/DefinitelyTyped/DefinitelyTyped/issues/2134

cc @Microsoft @DefinitelyTyped @jkomyno @a-tarasyuk @alvis @r3nya @btoueg @brunoscheufler @smac89 @touffy @DeividasBakanas @eyqs @Flarna @Hannes-Magnusson-CK @KSXGitHub @hoo29 @kjin @ajafff @islishude @mwiktorczyk @mohsen1 @n-e @octo-sniffle @galkin @parambirs @eps1lon @SimonSchick @ThomasdenH @WilcoBakker @wwwy3y3 @samuela @kuehlein @j-oliveras @bhongy @chyzwar @trivikr @nguymin4 @yoursunny @qwelias @ExE-Boss @Ryan-Willpower @peterblazejewicz @addaleax @JasonHK

Thank you

**Comment by SimonSchick** [comment]
This is going to be tricky, especially given streams have some specialised behaviour for buffers.
I'm all for this though, I never quite understood why these haven't been made generics from the get go.

**Comment by goloroden** [comment]
@kbariotis Are you still working on this?

**Comment by kbariotis** [comment]
@goloroden No, unfortunately, my time is really limited the past few months. Shall anyone wants to chime in, please be my guest. I think the PR above is a really good track. :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
