### ISSUE TITLE
[Parse] Schema.setCLP() type definition is missing

### ISSUE THREAD

**Issue by supermar1010** [DefinitelyTyped/DefinitelyTyped#45228]
- [x] I tried using the `@types/parse` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @dpoetzsch @jaeggerr @flavionegrao @wesleygrimes @agoldis @AlexandreHetu 
@dplewis @yomybaby @pocketcolin @rdhelms @jlnquere @yagotome @tybi @RaschidJFR @JeffGuKang @buitanloc @LinusU @REPTILEHAUS @kentrh @L3K0V @JeromeDeLeon 

On Parse.Schema setCLP() is missing. 

Its called like this:

``` typescript
  schema.setCLP({
    get: {'role:admin': true},
    find: {requiresAuthentication: true},
    count: {requiresAuthentication: false},
    update: {'*': true},
    create: {},// Is the same as '*': false
    delete: {'supermar1010': true},
  });
```

Here is an open PR with some more information: https://github.com/parse-community/docs/pull/700/files#diff-22c65bfd6614d949ec20e9d4461ce3cf

Unfortunately I don't fully understand typescript yet, so I don't know how to fix this.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
