### ISSUE TITLE
Cleave.js types breaks Vue.js project using TSX

### ISSUE THREAD

**Issue by 6XGate** [DefinitelyTyped/DefinitelyTyped#45220]
@clentfort , @jasongi-at-sportsbet , or @sashashakun 

Using `@types/cleave.js` in a **Vue.js** based project using **TSX** breaks all TSX/JSX compilation. The issue appears to be this libraries dependency on `@types/react`. Not sure if that can be spun out to a different type library, but there is not was to correct this in a webpack project. Cleave.js cannot be used with **Vue** and **TSX** with this library.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
