### ISSUE TITLE
Cannot create PlayerEndpoint kurento-client

### ISSUE THREAD

**Issue by jmezzera** [DefinitelyTyped/DefinitelyTyped#45243]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/kurento-client` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jhdevuk @michelalbers

If you do not mention the authors the issue will be ignored.

I'm trying to create a media pipeline with kurento-client (I'm new in this topic) and I'm having the following issue:

I want to replicate the rtsp server example in typescript and when I tried to create a Player element, I found out that there is no `create("PlayerEndpoint")` definition. Is that correct? How can I proceed? 

Thanks in advance

**Comment by neomedved** [comment]
This issue is fixed by [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47756).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
