### ISSUE TITLE
findOneAndReplace() definition missing

### ISSUE THREAD

**Issue by goulash1971** [DefinitelyTyped/DefinitelyTyped#45297]
Just a heads-up that there are no definitions for `findOneAndReplace` - I'm under some time pressure so have put a "generic" version into my project but will come back at a later date and take a look.

Thanks

**Comment by zacnomore** [comment]
@goulash1971 This repo contains types for multiple packages. What package contains `findOneAndReplace`?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
