### ISSUE TITLE
Rx.Observable.throttle is deprecated

### ISSUE THREAD

**Issue by heycalmdown** [DefinitelyTyped/DefinitelyTyped#4530]
https://github.com/Reactive-Extensions/RxJS/blame/master/doc/api/core/operators/debounce.md

So now we have a lack of alternatives: throttleFirst, throttleWithTimeout

@Igorbek ping if you still maintaining

**Comment by vvakame** [comment]
@heycalmdown please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
