### ISSUE TITLE
[@types/ip-address] Unable to resolve path to module 'ip-address'

### ISSUE THREAD

**Issue by psa-stanley** [DefinitelyTyped/DefinitelyTyped#45383]
- [x]  I tried using the @types/xxxx package and had problems.
- [x]  I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for StackOverflow. (Please ask any appropriate questions there).
- [x] Mention the authors (see Definitions by: in index.d.ts) so they can respond. @icopp @danwbyrne 

I am using VSCode which doesn't report any errors, but it fails in compilation. 
Thanks in advance.

```
import Vue from 'vue';
import Vuex from 'vuex';
import { Address4 } from 'ip-address';


Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    connectedIp: Array<Address4>(),
    activeIp: new Address4('127.0.0.1'),
  },
  mutations: {
  },
  actions: {
  },
  modules: {
  },
});
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
