### ISSUE TITLE
Google APIs (gapi*) are incomplete

### ISSUE THREAD

**Issue by alexeagle** [DefinitelyTyped/DefinitelyTyped#4541]
There are a handful of Google APIs in DT, as well as the gapi.d.ts for the client library.
But Google publishes many more APIs, and changes them often. The current strategy of typing these by hand is not so great.

We just did a TypeScript hackathon at Google and one of our coders wrote a prototype conversion tool that accesses Google's API discovery service, which serves machine-readable API definitions for all the gapi\* APIs. Does this sound like a good contribution to DefinitelyTyped? If so, let's work out some details of where the code can live, and how we'd run the generator to produce artifacts in the places users like TSD expect.

**Comment by vvakame** [comment]
@alexeagle please send a pull request. I'll review it.

**Comment by bourey** [comment]
I'd be happy to send something over.  The script currently runs via node.js; does that sound like a reasonable solution?  It currently requires an API name and version, but we could also create a version that requests the main discovery doc, then generates a .d.ts file for each listed API version.

**Comment by ithinkihaveacat** [comment]
For anyone coming across this issue via search, the conversion tool @alexeagle is referring to is possibly @vvakame's https://github.com/vvakame/gapidts (or at least, it does something similar).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
