### ISSUE TITLE
start vscode npm install then @types/vscode error. 1.46.0 not mach

### ISSUE THREAD

**Issue by stewinged** [DefinitelyTyped/DefinitelyTyped#45425]
start vscode plugin
yo code
npm install 
but "@types/vscode"not mach 1.46.0
see the npmjs. not found 1.46.0
just modify 1.45.1.
and run the lunch.json
the error  need 1.46.0
![image](https://user-images.githubusercontent.com/20498227/84359150-cc8a2280-abfa-11ea-9be9-ae853aa0c931.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
