### ISSUE TITLE
error TS2739: Type '{ jwt: any; }' is missing the following properties from type 'CookieSessionObject': isChanged, isNew, isPopulated

### ISSUE THREAD

**Issue by mohamadresaaa** [DefinitelyTyped/DefinitelyTyped#45431]
Hi, I used to use an @types/cookie-session@2.0.39, but now that I've updated, it gives me this error. Please help.
```
error TS2739: Type '{ jwt: any; }' is missing the following properties from type 'CookieSessionObject': isChanged, isNew, isPopulated
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
