### ISSUE TITLE
arcgis-js-api  Form object can not be instantiated in TypeScript

### ISSUE THREAD

**Issue by mkralCZ** [DefinitelyTyped/DefinitelyTyped#45450]
Hello @[Bjorn Svensson],
our customer encountered problem in TypeScript with @types/arcgis-js-api when 
Form object is instantiated 

import Format = require("esri/widgets/CoordinateConversion/support/Format");
const statePlaneCA = new Format...

compilation  (tsc app/main.ts in Visual Studio Code)  returns
TS2351: This expression is not constructable.
  Type 'Format' has no construct signatures.

We solved it by usage of 

// @ts-ignore

But maybe there is some problem with that module.

Regards

**Comment by NoashX** [comment]
Hi @mkralCZ, sorry you ran into this issue. We updated the module today, and this should now be fixed at 4.17.

**Comment by mkralCZ** [comment]
Hi Noah,
thank You for noticing me.
Regards

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
