### ISSUE TITLE
Credits not taking contributors into account

### ISSUE THREAD

**Issue by murbanowicz** [DefinitelyTyped/DefinitelyTyped#45478]
By an acciddent I have found that even if I am contributor for quite a few packages, I am never mentioned.
E.g. in bytebuffer - only original author is mentioned in credits.
Not sure where it is being generated but it is for sure broken in a way.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
