### ISSUE TITLE
react-native: How to use requireNativeComponent<T>(..)

### ISSUE THREAD

**Issue by mrousavy** [DefinitelyTyped/DefinitelyTyped#45497]
When using requireNativeComponent<T>(..) the error "React cannot be found" is thrown, see: https://github.com/facebook/react-native/issues/29145

How am I supposed to use this function? I'm passing the Props interface as the type parameter T, but that throws me that error.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
