### ISSUE TITLE
index.d.ts is not a module

### ISSUE THREAD

**Issue by agentg2007** [DefinitelyTyped/DefinitelyTyped#45505]
I imported @types/powerapps-component-framework using npm.

but when i import it in my index.ts i got **@types/powerapps-component-framework/index.d.ts' is not a module**

I have only successfully imported it when i changed the index.d.ts
![image](https://user-images.githubusercontent.com/43179883/84743219-36803e80-afe4-11ea-9b13-9d2a1608cf0f.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
