### ISSUE TITLE
@types/hapi__joi: Why are keys in `SchemaMap` optional?

### ISSUE THREAD

**Issue by dminkovsky** [DefinitelyTyped/DefinitelyTyped#45501]
I've got a schema like:

```
const schema = Joi.object<RegisterInput>({
    username: Joi.string()
        .pattern(/[a-z\d]/)
        .min(1)
        .max(20)
        .required(),
    password: Joi.string()
        .min(8)
        .max(20)
        .required(),
    device: Joi.object(),
});
```

where `RegisterInput` looks like

```
export interface RegisterInput {
    username: string;
    password: string;
    device?: DeviceInfo;
}
```

I noticed that if I change any of the key names passed to `Joi.object()`, Typescript produces an error as expected. Awesome!

However, if I remove any of the keys, I get no error. I looked into this a little, and noticed that `Joi.object()` is defined as:

```
object<TSchema = any, T = TSchema>(schema?: SchemaMap<T>): ObjectSchema<TSchema>
```

where `SchemaMap` is:

```
type SchemaMap<TSchema = any> = {
    [key in keyof TSchema]?: SchemaLike | SchemaLike[];
};
```

This explains the behavior.

My question is: why? If I pass a type parameter that is an interface with certain keys, don't I always want those keys to be included in the schema? **If any of the keys are optional, I can write them without `.required()`... so why the `?` in `key in keyof TSchema]?`**?

@Bartvds @laurence-myers @cglantschnig @DavidBR-SW @GaelMagnan @ralekna  @schfkt @rokoroku @dankraus @wanganjun @rafaelkallis @aconanlai @zaphoyd @thewillg @SimonSchick @afharo @lenovouser @AnandChowdhary @myovchev @RecuencoJones @freisenhauer @legraphista @SimchaWood @stevendesu

**Comment by AnandChowdhary** [comment]
No reason that I can think of, maybe there's an edge case somewhere? I guess less strict just makes sure types work in more cases? If you think this is a bug, feel free to open a PR and remove the `?`, I just err on the side of caution. 😄

The only use case I can think of is if you have an empty schema map `{}` which you want to validate, making sure all keys are `undefined` (no keys actually exist on the object)? So there can be 1 to n `SchemaLike | SchemaLike[]`, but there can also be none.

**Comment by stevendesu** [comment]
If I were to wager a guess, it's probably intended so that you can perform validation on a subset of the fields. Perhaps you want to validate passwords, but don't really care _**what**_ they enter for the username field. Forcing you to supply the username key to the schema would force you to validate it.

I'm not a TypeScript guru or a Joi guru, though, so my understanding could be entirely off base.

**Comment by rokoroku** [comment]
Actually, I think It remains that way because it was first written like that. 
If you want to make it more "strict" way, you can suggest a PR to keep its required fields. People still can achieve same scenario in this way: `Joi.object<Partial<RegisterInput>>({ ... })`.

I have no preference about keeping the required fields, but I can bear that migration cost.

**Comment by dminkovsky** [comment]
Thanks everyone who responded. 

> it's probably intended so that you can perform validation on a subset of the fields.

As @rokoroku says: you can use `Partial` to achieve that effect, right? I was thinking that too, and thought maybe these definitions are from before the utility classes were added?

As @rokoroku also mentions, this would probably be a breaking change for some people? Not sure if worth it. Will think some more. Please update if you all have more thoughts.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
