### ISSUE TITLE
mithril.d.ts: cannot find external module "mithril"

### ISSUE THREAD

**Issue by dho825** [DefinitelyTyped/DefinitelyTyped#4553]
@jtmueller I had noticed that whenever I tried `import m = require('mithril')` my text editor would throw a complaint that the external module could not be found. I realized that the definitions file never declared the module name for mithril: `declare module 'mithril' {...}`

I fixed this by wrapping everything in the module and I had no problems. It seems that the current implementation declares global variables m and Mithril, but that would cause the compiler to complain.

I guess it still works with build tools because it would eventually be wrapped and converted to JS, but this way is probably more "correct". But I'm still new to TS so please advise.

**Comment by dho825** [comment]
@jtmueller looking at mithril v0.2.0, I would say that some of the definitions are out-of-date. (ie. m.module has been renamed to m.component). Not sure if you're still active with this, but it would be great if you or someone like Leo could write up an updated definitions file...I could try but it would take me a while as I'm still green to TS and mithril.

**Comment by jhessin** [comment]
Bump - Definitely need this as the current mithril version is 2.0.3
I keep getting errors showing up in my typescript, but it still compiles without a problem (very annoying)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
