### ISSUE TITLE
Webpack (and possibly a bunch of others declarations) are not implementing eponymous interface as it was seemingly intended by the authors

### ISSUE THREAD

**Issue by shabunc** [DefinitelyTyped/DefinitelyTyped#45532]
In webpack [declaration](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/87809607c83181d5d47daea7bf8ea9f8a8d3734d/types/webpack/index.d.ts) we have following definitions: 

```ts
  interface Watching {
        close(callback: () => void): void;
        invalidate(): void;
    }
```

and, later on:
```ts

    namespace Compiler {
        type Handler = ICompiler.Handler;
        type WatchOptions = ICompiler.WatchOptions;

        class Watching implements Watching {
            constructor(compiler: Compiler, watchOptions: Watching.WatchOptions, handler: Watching.Handler);

            close(callback: () => void): void;
            invalidate(): void;
        }    

        namespace Watching {
            type WatchOptions = ICompiler.WatchOptions;
            type Handler = ICompiler.Handler;
        }    
    }    

```

The thing is that in this particular case the `class Watching` is actually implementing itself, not the interface Watching, which is presumably was not intention of authors (see [also](https://stackoverflow.com/questions/62418219/class-implementing-itself-instead-of-inheriting-an-eponymous-interface-in-outer)) 

I'm referring for the main authors for webpack definitions:

 @sirreal, @Lapple, @jason0x43, @elliottsj, @peterblazejewicz

**Comment by shabunc** [comment]
The solution would be (if I got the intentions of authors right) to have something like this

```ts
 class Watching implements globalThis.Watching {
            constructor(compiler: Compiler, watchOptions: Watching.WatchOptions, handler: Watching.Handler);

            close(callback: () => void): void;
            invalidate(): void;
        }  
```

**Comment by peterblazejewicz** [comment]
@shabunc just my 2c. IMHO this is just because authors of some of the most complex DT here favor definition fullfilling the foremost goals first (let the code compile), without followign the formality of the underlying code. For example some of DT I'm adding just augment new properties into interface of the configuration of a test runner, wihtout really adding proper shape of to runner's plugin itself. 
Obviously the proper shape of the Compiler and Watcher are out of sync, when looked directly (there are nice JDocs types now in the source code to quickly grasp the usage):
https://github.com/webpack/webpack/blob/master/lib/Compiler.js
https://github.com/webpack/webpack/blob/master/lib/Watching.js
IMO there is no need for special construct to be added on 'global'/'globalThis', if required by some use-case, the shape of the compiler could be ameneded (with removal of this interface which seems to serve no real purposes for me in the context of the current api - but it could served some earlier). But again, look into this from other perspective first: by adding those articial TS-only namespaces folks achieved the first goal with minimal (then) complexity.

**Comment by shabunc** [comment]
@peterblazejewicz I'm not sure I got you right. The thing is that if the intention was to implement interface Watching (and it's irrelevant to the fact how precise are definitions are) than this intention was not fulfilled - in future if one will modify the interface intention it's easy not to notice it and don't have it in class.

**Comment by peterblazejewicz** [comment]
@shabunc I'm only trying to explain, that problems with correctness of the DT package, can be understood: the first and foremost (at least for me) purpsoe of those DT packages is to allow to consume some widely (critically) pouplar vanilla JS package in TypeScript OFC your point is valid one, I'm just explaining why one can find problematic bits. There is a class Watching, no need for interfaces, just proper description of the webapck module. The folks in the Node DT package are trying hard to correctly reflect Node modularity and to fix past choices in non-breaking ways.

**Comment by shabunc** [comment]
@peterblazejewicz Aha, I see your point now, definitely, the other solution would be to god rid off interface. In fact whenever we have a single class it looks  quite often doubtful to split it into interface and class.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
