### ISSUE TITLE
Start a directory of ES6 DefinitelyTyped definitions

### ISSUE THREAD

**Issue by SonofNun15** [DefinitelyTyped/DefinitelyTyped#4556]
When compiling down to ES6 (so I can use ES6 modules with systemJS), I get errors in the DefinitelyTyped files for using `export =` (error TS1203). Would be nice to either have a directory of ES6 d.ts files or fix this so these files can compile to ES6.

**Comment by SonofNun15** [comment]
Shouldn't be a difficult change to make, but need some discussion as to how this would pan out, especially how it would effect the management tool, `tsd`.

**Comment by mkusher** [comment]
+1 for this issue
But before there will be a release including this fix https://github.com/Microsoft/TypeScript/pull/3041 for most packages there will be circular definition error...

**Comment by omencat** [comment]
I started a branch to convert some server-side code to es6, but I am also getting TS1202 and TS1203 errors on these external d.ts files. So at this point, it seems like we still need to target es5 until d.ts files support es6?

**Comment by cspotcode** [comment]
What if we write tooling to automatically convert CommonJS definitions to ES6 and vice versa?

When loading a CommonJS module in Babel, Babel treats it like an ES6 module with a single "default" export.  Thus a CommonJS module with this interface:
```
// CommonJS module
export xyz;
export abc;
```
has the following ES6 interface when loaded in Babel using `import foo from "foo"`
```
var _exports = {
  xyz: xyz;
  abc: abc;
}
export default _exports;
```

Tons of existing CommonJS modules can already be loaded with ES6 module syntax via Babel, *but* their type definitions need to be rewritten so that all exports are combined into a single `default` export.

Why not write tooling to do this automatically, based on the consumer's project configuration?

**Comment by vvakame** [comment]
`module.exports = foo;` is not exactly equals to `export default`.
If you want to throw away commonjs style code, you can use `import * as path from "path";` instead of `import path = require("path");`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
