### ISSUE TITLE
[@types/d3-array] Missing Methods + API changes since 2.0.3

### ISSUE THREAD

**Issue by hydrosquall** [DefinitelyTyped/DefinitelyTyped#45574]
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @gustavderdrache  / @tomwanzek  / @denisname / @Ledragon 

- New methods were added since the last module the types were validated against D3 v2.0.3, which was released in December 2018, specifically in 2.1.0, 2.2.0, 3.3.0, and 2.4.0. These include:

2.1.0

- [ ] Added d3.bin, d3.count, d3.minIndex, d3.maxIndex, d3.least, d3.leastIndex
- [ ] Deprecated scan, histogram
- [ ] Modify api of d3.permute

2.2.0

- [ ] New methods `d3.groups` and `d3.rollups`
- [ ] API change to d3.least and d3-leastIndex

2.3.0

- [ ] d3.greatest
- [ ] d3.greatestIndex
- [ ] d3.quantileSorted
- [ ] d3.quantile API change 

2.4.0

- [ ] d3.cumsum

Full notes:

- https://github.com/d3/d3-array/releases

**Comment by Ledragon** [comment]
Thanks for the feedback, d3 types update form a general point of view are tracked at #38939 so I suggest to close this and keep tracking the already open ticket

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
