### ISSUE TITLE
request: @types/deno to pull in https://github.com/denoland/deno/releases/latest/download/lib.deno.d.ts

### ISSUE THREAD

**Issue by balupton** [DefinitelyTyped/DefinitelyTyped#45597]
Here is a request for a `@types/deno` which stays up to date with https://github.com/denoland/deno/releases/latest/download/lib.deno.d.ts

So that I can easily write npm packages that are compatible with deno, node, and web browsers, such as is enabled by https://github.com/bevry/make-deno-edition - an example of such a package is https://github.com/bevry/start-of-week which currently requires a `// @ts-ignore` for the different entries, rather than making use a triple-slash directive

- https://github.com/bevry/start-of-week/blob/v2.5.0/source/deno.ts#L4-L5
- https://github.com/bevry/start-of-week/blob/v2.5.0/source/node.ts#L4-L5
- https://github.com/bevry/start-of-week/blob/v2.5.0/source/browser.ts#L4-L5

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
