### ISSUE TITLE
Error when compiling in node 14

### ISSUE THREAD

**Issue by Kenykore** [DefinitelyTyped/DefinitelyTyped#45604]
- I tried using the `@types/node` package and had the problems below .

`node_modules/@types/node/assert.d.ts:56:14 - error TS2300: Duplicate identifier 'assert'.

56     export = assert;
                ~~~~~~

  node_modules/@types/node/ts3.7/assert.d.ts:56:14
    56     export = assert;
                    ~~~~~~
    'assert' was also declared here.

node_modules/@types/node/ts3.5/globals.global.d.ts:1:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'global' must be of type 'Global', but here has type 'Global & typeof globalThis'.

1 declare var global: NodeJS.Global & typeof globalThis;
              ~~~~~~

  node_modules/@types/node/globals.global.d.ts:1:13
    1 declare var global: NodeJS.Global;
                  ~~~~~~
    'global' was also declared here.

node_modules/@types/node/ts3.7/assert.d.ts:56:14 - error TS2300: Duplicate identifier 'assert'.

56     export = assert;
                ~~~~~~

  node_modules/@types/node/assert.d.ts:56:14
    56     export = assert;
                    ~~~~~~
    'assert' was also declared here.`

- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I fixed this error by removing the assert.d.ts file in the node/ts3.7 folder ,seems it was conflicting with the existing assert.d.ts in the root @types/node folder

 @https://github.com/blog/821-mention-somebody-they-re-notified 
  - Authors: @kamal @tdreyno  @jonmagic @farcaller

**Comment by psperneac** [comment]
Did you find a more permanent solution?

**Comment by lincolnthree** [comment]
Also having this issue. Looking for a reasonable solution?

**Comment by lilasquared** [comment]
Having same issue

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
