### ISSUE TITLE
@types/node: crypto.generateKeyPairSync - should support more key types

### ISSUE THREAD

**Issue by jeffrson** [DefinitelyTyped/DefinitelyTyped#45614]
- [*] I tried using the `@types/node` package and had problems.

- Authors: @SimonSchick @rbuckton 
(sorry, don't know who else to mention...)

crypto.d.ts in @types/node only supports key types "rsa", "dsa", "ec". Node however can nowadays use 'ed25519', 'ed448', 'x25519', 'x448', or 'dh' too:
https://nodejs.org/api/crypto.html#crypto_crypto_generatekeypairsync_type_options

So please somebody add those (especially ed25519)...

**Comment by josteink** [comment]
From what I can tell, based on recent updates, only `dh` is actually missing in the latest type-definitions, and this was added in NodeJS 13.

https://nodejs.org/docs/latest-v13.x/api/crypto.html#crypto_crypto_generatekeypairsync_type_options

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
