### ISSUE TITLE
TSLint issues warnings on jasmine `spyOn()` declaration

### ISSUE THREAD

**Issue by Danon** [DefinitelyTyped/DefinitelyTyped#45615]
I tried to declare the same method as `spyOn()` , like so:
```
function serviceSpy<T, K extends keyof T = keyof T>(type: Type<T>, method: T[K] extends Function ? K : never): Spy {
    return spyOn(fixture.debugElement.injector.get(type), method);
}
```
But then TSLint suggested this issue:
```
TSLint: Don't use 'Function' as a type. Avoid using the `Function` type. Prefer a specific function type, like `() => void`.(ban-types)
```

So I reckon we could change `ts3.1\index.d.ts`
```
declare function spyOn<T, K extends keyof T = keyof T>(
    object: T, method: T[K] extends Function ? K : never,
): jasmine.Spy<
    T[K] extends jasmine.Func ? T[K] :
    T[K] extends { new (...args: infer A): infer V } ? (...args: A) => V :
    never
>;
```
to
```
// ...
object: T, method: T[K] extends () => void ? K : never,
// ...
// ...
// ...
// ...
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
