### ISSUE TITLE
[webpack] MultiCompiler doesn't define Multistats for callback/handler of run method

### ISSUE THREAD

**Issue by spamshaker** [DefinitelyTyped/DefinitelyTyped#45626]
The webpack.run function is overloaded by given either object or array of objects as configs.
In callback it defines that will return Stats type even the array of configs passed to the run method.
The issue seems to be in missing handler definition for MultiCompiler namespace
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bdba62e896baf7094d1ccabb709cb9d46dcd3d3a/types/webpack/index.d.ts#L1420
which should refer to MultiStats handler
![image](https://user-images.githubusercontent.com/4864089/85221215-4ae08480-b3b2-11ea-9524-e55236d66c25.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
