### ISSUE TITLE
 @types/react-table missing event argument for TableToggleCommonProps onChange method

### ISSUE THREAD

**Issue by auchynnikau** [DefinitelyTyped/DefinitelyTyped#45640]
I tried using the `@types/react-table` package and had problem with row selection.
As you can see on the screenshot bellow the `TableToggleCommonProps` interface has an `onChange` method which doesn't takes any arguments:
![image](https://user-images.githubusercontent.com/33329898/85292748-11d50c80-b4a5-11ea-8931-04661b9ebeb8.png)

But after selecting row we can see an error that required `event` argument:
![image](https://user-images.githubusercontent.com/33329898/85293175-a8093280-b4a5-11ea-9a92-73a3162f65a8.png)

  - Authors: @farcaller @jonmagic.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
