### ISSUE TITLE
@types/node Http2: url and writableEnded

### ISSUE THREAD

**Issue by hanspeter1** [DefinitelyTyped/DefinitelyTyped#45690]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/node` (12.12.47) package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jkomyno @alvis @a-tarasyuk 

**Bug 1:**
In `Http2.Http2ServerRequest` the url-property is not a readonly property. I can change it.

**Bug 2:**
In `Http2.Http2ServerResponse` the writableEnded-property is missing

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
