### ISSUE TITLE
Styled-components 5.1.1

### ISSUE THREAD

**Issue by thany** [DefinitelyTyped/DefinitelyTyped#45702]
```ts
const Base = styled<Props>('div').withConfig({
  shouldForwardProp: prop => prop !== 'display'
})`
  background: ${props => props.display ? 'hotink': 'rebeccapurple'};
`;
```

This is a new feature in styled-components 5.1.
Currently, this results in a following error at usage point during compilation:

```
Property 'withConfig' does not exist on type 'ThemedStyledFunction<"div", DefaultTheme, {}, never>'. ts(2339)
```

* [x]  I tried using the `@types/styled-components` package and had problems.
* [x]  I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
* [x]  [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
    * Authors: @Igorbek @Igmat @lavoaster @Jessidhia @jkillian @eps1lon @flavordaaave @wagerfield @Lazyuki @mgoszcz2 @danilofuchs

**Comment by quicksnap** [comment]
I think the type can be added to `ThemeStyledFunction` interface as follows: 

```tsx
      withConfig(config: {
        shouldForwardProp: (
          prop: keyof StyledComponentPropsWithRef<C>,
        ) => boolean
      }): ThemedStyledFunction<C, T, O, A>```

**Comment by quicksnap** [comment]
Derp, it appears my typings are out of date. This seems to be fixed in latest. 

This issue probably should be closed?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
