### ISSUE TITLE
CasperJs thenclick

### ISSUE THREAD

**Issue by rippo** [DefinitelyTyped/DefinitelyTyped#4574]
Line 85 of casper.d.ts shoul dbe

thenClick(selector: string, then? : Function): Casper;

Thanks

**Comment by vvakame** [comment]
@rippo please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
