### ISSUE TITLE
[IONIC 4] gapi.client.load is NOT working in IOS

### ISSUE THREAD

**Issue by Mohammad-shoman** [DefinitelyTyped/DefinitelyTyped#45755]
I am trying to integrate google calendar on my IONIC 4 app. 
It works fine on android but it's not working in IOS

I am trying to load the library like this:

```
 gapi.load('client', () => {
     alert("alert1");
     gapi.client.load('calendar', 'v3', () => {
        alert("alert2");
        this.addToCalendar();
      });
  });
```
alert 1 is shown but alert 2 is not

Any idea what's happening?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
