### ISSUE TITLE
Missing deploy readme on system-task and system-service

### ISSUE THREAD

**Issue by leocwlam** [DefinitelyTyped/DefinitelyTyped#45801]
I had 2 PR merged successfully. 
But missing README.md deployment on npmjs.com

- https://www.npmjs.com/package/@types/system-service
![image](https://user-images.githubusercontent.com/35342488/85639050-96668d00-b655-11ea-9403-ae9a0e05d315.png)
- https://www.npmjs.com/package/@types/system-task
![image](https://user-images.githubusercontent.com/35342488/85639331-6cfa3100-b656-11ea-8edf-bc8b1e110c75.png)

Can you help me for it?

Ref:
The PR are
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45489
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45585

Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: Leo Lam leocwlam@gmail.com

If you do not mention the authors the issue will be ignored.

**Comment by peterblazejewicz** [comment]
also: #45792

**Comment by sandersn** [comment]
Note that README.md ships with @types/system-service, and the `"readme"` key is properly filled as seen with https://registry.npmjs.org/@types/system-task. I'm having trouble seeing any substantial difference from a package with a README, like https://registry.npmjs.org/@types/aframe.

I think this may be an npm problem, or at least a change to npm's API, as we've run into before: https://github.com/npm/www/issues/11#issuecomment-241130897.

**Comment by sandersn** [comment]
I tried to bisect this, and narrowed down the break to between 19 June 06:34 (@types/react-vis) - 20 June 19:27 (@types/ssri). But the only nearby changes to the `@definitelytyped` code were on June 16 -- and the two changes were to the monorepo's package.json scripts, and the publisher's allowed-external-dependencies list. Neither of those has anything to do with package publishing.

The last update to the `npm` package was 2 months ago, so I don't think it's anything on the client side either.

Due to the previous bug, and a comment in the publisher source, I suspected the order of keys was different. But looking at the package json for the two, there's no difference.

* [react-vis](http://registry.npmjs.org/@types/react-vis)
* [system-task](http://registry.npmjs.org/@types/system-task)

**Comment by sandersn** [comment]
I opened https://github.com/npm/cli/issues/1475 to see if this is an npm/cli issue.

(I just realised that it might be the wrong repo but npm has jumped around so much that I'm not sure WHERE to open issues on the npm package.)

**Comment by leocwlam** [comment]
Thanks @sandersn

**Comment by leocwlam** [comment]
Hi @sandersn,

I want to followup on this issue.  I just check on both
https://www.npmjs.com/package/@types/system-service
and
https://www.npmjs.com/package/@types/system-task

They both are still missing README.md.

Thanks,

Leo

**Comment by sandersn** [comment]
Still waiting on a response on npm/cli#1475

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
