### ISSUE TITLE
Version mismatch between README.md and react.d.ts

### ISSUE THREAD

**Issue by RinatMullayanov** [DefinitelyTyped/DefinitelyTyped#4585]
I noticed that for react in  [REAME.md](https://github.com/borisyankov/DefinitelyTyped/blob/master/react/README.md) title written v0.13.**3** version
but [react.d.ts](https://github.com/borisyankov/DefinitelyTyped/blob/master/react/react.d.ts) title written v0.13.**1** version.

**Comment by vsiao** [comment]
Oh, I'm sorry about that. The README is correct.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
