### ISSUE TITLE
DbSignUpOptions does not allow name, given_name, or family_name.

### ISSUE THREAD

**Issue by tjjevans1** [DefinitelyTyped/DefinitelyTyped#45868]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9aedc1ffdd52e19967867a25cea0721ab7872c1f/types/auth0-js/index.d.ts#L851-L864

DbSignUpOptions does not include options for name, given_name or family_name, even though these fields are specified in the api.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
