### ISSUE TITLE
jsonwebtoken verify and decode always return an object

### ISSUE THREAD

**Issue by severo** [DefinitelyTyped/DefinitelyTyped#45873]
- [x] I tried using the `@types/jsonwebtoken` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SomaticIT @danielheim @brikou @vpk @rlgod

If you do not mention the authors the issue will be ignored.

---

Hi,

I understand from https://github.com/auth0/node-jsonwebtoken/blob/master/decode.js and https://github.com/auth0/node-jsonwebtoken/blob/master/verify.js that :

- <strike>the "json" option does not exist anymore in decode()</strike>
- the decode() and verify() function only return an object, and never a string

**Comment by peterblazejewicz** [comment]
@severo
IMO the JSON option support is still there, this is just pass-through to `jws`:
https://github.com/auth0/node-jws/blob/master/lib/verify-stream.js#L70

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
