### ISSUE TITLE
How to convert .d.ts to other format? say JSON or how to get AST for .d.ts ?

### ISSUE THREAD

**Issue by Archs** [DefinitelyTyped/DefinitelyTyped#4588]
JSON would be easy to parse in other languages, at least the AST would be helpful.

I know quite little about TypeScript but want to process .d.ts files, how can I do that?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
