### ISSUE TITLE
'eventsource' DOM augmentations are incompatible with TypeScript 4.0

### ISSUE THREAD

**Issue by rbuckton** [DefinitelyTyped/DefinitelyTyped#45935]
`eventsource` has an incompatible definitions for `MessageEventInit` and `MessageEvent` due to changes in lib.dom.d.ts in TypeScript 4.0. If changing these types to be compatible is a breaking change for TypeScript <=3.9 then it may be necessary to add a [`"typesVersions"` entry to the package.json](https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-use-features-from-typescript-31-or-above).

This was found while running on-demand DT tests on the TypeScript repo: https://typescript.visualstudio.com/TypeScript/_build/results?buildId=78525&view=logs&j=ae5f67bc-b508-52d0-18c7-3e0886a35c88&t=e2afb42f-d9e0-5ec8-c417-e22c6ef5223e&l=5496

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @scottleedavis, @afroozeh, @snakedrak, @Akuukis

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
