### ISSUE TITLE
'knockout' tests are failing due to overload resolution with 'null' on 'ko.observable'

### ISSUE THREAD

**Issue by rbuckton** [DefinitelyTyped/DefinitelyTyped#45938]
`knockout` is failing because `ko.observable` is overloaded with a `<T = any>(value: null): KnockoutObservable<T | null>` which breaks its own tests, at least when tested with TypeScript 4.0.

This was found while running on-demand DT tests on the TypeScript repo: https://typescript.visualstudio.com/TypeScript/_build/results?buildId=78525&view=logs&j=ae9e61d0-c116-562e-ef72-0c532f74ef92&t=99b9b1a5-4b32-54c1-6413-7fac564b8273&l=5516

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov, @Igorbek, @moonpyk, @EnableSoftware, @BenjaminEckardt, @ffMathy, @ltlombardi, @Retsam, @ReyPena

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
