### ISSUE TITLE
ssh2: `SFTPWrapper` missing `writeFile` method

### ISSUE THREAD

**Issue by kael-shipman** [DefinitelyTyped/DefinitelyTyped#45943]
## Prelims

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - @tkqubo 
  - @rbuckton 
  - @wrboyce 
  - @lucasmotta 
  - @hengkx 

## Issue

Hi all,

I'm using the ssh2 package @ `v0.8.9` and noticed that, while the package itself definitely has a `writeFile` method on the `SFTPWrapper` class, the type definitions do not show that method. I verified that the method appears to be functioning correctly by using it in the console.

Is there a reason that method was left off?

**Comment by rbuckton** [comment]
Its most likely missing because it's not documented in https://github.com/mscdex/ssh2/blob/master/SFTP.md. There are a number of methods on https://github.com/mscdex/ssh2/blob/master/lib/protocol/SFTP.js that aren't documented and aren't currently present in the definition, unfortunately.

**Comment by kael-shipman** [comment]
Ah, interesting. I suppose I could create typings for this, then, and add a PR? Any clarity on who would have to approve it?

**Comment by rvanmil** [comment]
Here’s a previous relevant PR which for some reason was closed and not merged: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43797

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
