### ISSUE TITLE
@types/simple-oauth2 is not compatible with current version

### ISSUE THREAD

**Issue by nazarkulyk** [DefinitelyTyped/DefinitelyTyped#45947]
Hallo,
I tried using the @types/simple-oauth2 package and it not compatible with latest simple-oauth2 version.

Last versions that works are:

@types/simple-oauth2 - 2.5.3
simple-oauth2 - 3.4.0

Current version of simple-oauth2 is 4.1.0 and starting with 4.0.0 package changed API. Can please someone update this package to be compatible with latest @simple-oauth2 versions?

Thanks a lot!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
