### ISSUE TITLE
JQuery.d.ts, why is it like this

### ISSUE THREAD

**Issue by df257** [DefinitelyTyped/DefinitelyTyped#45944]
![image](https://user-images.githubusercontent.com/7835444/86871930-cf9b0480-c10d-11ea-8927-6dc42a991636.png)

**Comment by df257** [comment]
There's a lot of useless content here

**Comment by martin-badin** [comment]
I agree with you. But authors want to have an example of code there, although it is unnecessary and it can be deprecated.

**Comment by leonard-thieu** [comment]
The example will render in-editor allowing users easy access to code examples.

![Code_2020-10-15_07-59-24](https://user-images.githubusercontent.com/5265970/96120811-1e9ac780-0ebd-11eb-8d1d-648066921038.png)

Could you explain why you think it's irrelevant?

**Comment by martin-badin** [comment]
I think that the example could be deprecated and the file is hard to read.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
