### ISSUE TITLE
@types/node is defining Symbol.observable when it probably shouldn't and the definition is incorrect.

### ISSUE THREAD

**Issue by benlesh** [DefinitelyTyped/DefinitelyTyped#45964]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @RyanCavanaugh

I was trying to correct the types of `Symbol.observable` as it was incorrectly defined in both `rxjs` and `symbol-observable`, and I noticed that the fix I made clashed with something. I was very surprised to see that `@types/node` defined `Symbol.observable`!

My gut tells me it should _not_ define it, as `Symbol.observable` was part of a Stage 1 TC39 proposal. Though it's been widely adopted by RxJS, Most, XStream, Redux, et al... I don't think it's at all used in the Node APIs, so it should probably be removed.

**Comment by benlesh** [comment]
cc @DanielRosenwasser

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
