### ISSUE TITLE
[atmosphere.js] Why are all Atmosphere members optional?

### ISSUE THREAD

**Issue by thw0rted** [DefinitelyTyped/DefinitelyTyped#45995]
- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Mory1879 @Sky161 @toedter 

The [current Atmosphere typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/atmosphere.js/index.d.ts) declare every single member as optional, including the top level AtmosphereRequest class, all member functions, etc.  I'm looking at the [Atmosphere docs](https://github.com/Atmosphere/atmosphere/wiki/atmosphere.js-API) and I don't see anything to suggest that I need to check if those might accidentally be undefined at runtime.  Was this intentional?  Do I need to always assume anything I access might be undefined?  If not, would you approve a PR removing a whole lot of `?:` from the existing typings?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
