### ISSUE TITLE
`types/arcgis-js-api/index.d.ts` is too big for GH api

### ISSUE THREAD

**Issue by elibarzilay** [DefinitelyTyped/DefinitelyTyped#46028]
Ping @Esri, @bsvensson

`types/arcgis-js-api/index.d.ts` is very big -- 5.3mb, and as I mentioned in a recent PR, you win the award of biggest file in DT.

Apparently, the GH api has a limit on files that it can retrieve, and when a file is bigger than 5mb, it silently produces an empty string without an error.  I updated the mergebot to detect this and show a proper error.  Previous to my changes, that PR was showing as a "New Definition" since it didn't check for the error -- future PRs will show the error and require maintainer resolution which would slow things down a lot.

It would be good to break it to multiple files or reduce the size of comments, or whatever, otherwise this will continue to be a problem.

---

BTW, to see the problem, go to the [api explorer](https://developer.github.com/v4/explorer/), run the following query and see the empty response:

```
query GetLabels {
  repository(name:"DefinitelyTyped", owner:"DefinitelyTyped") {
    object(expression: "master:types/arcgis-js-api/index.d.ts", ) {
      ... on Blob {
        __typename
        text
        byteSize
      }
    }
  }
}
```

**Comment by bsvensson** [comment]
Thanks @elibarzilay for pointing out the 5MB threshold.  We'll take a stab at making it smaller by only keeping the first part of each documentation snippet.

cc: @dasa  @annelfitz

**Comment by dasa** [comment]
We've reduced the size to 3.2 MB in PR #48628

**Comment by elibarzilay** [comment]
Nice -- I think that this should settle the error that happened on that pr.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
