### ISSUE TITLE
`types/fhir/fhir-tests.ts` is too big for GH api

### ISSUE THREAD

**Issue by elibarzilay** [DefinitelyTyped/DefinitelyTyped#46027]
Ping @meirgottlieb

`types/fhir/fhir-tests.ts` is very big -- 5.3mb.

Apparently, the GH api has a limit on files that it can retrieve, and when a file is bigger than 5mb, it silently produces an empty string without an error.  I updated the mergebot to detect this and show a proper error.  Future PRs might show the error and require maintainer resolution which would slow things down a lot.

It would be good to break it to multiple files or reduce the size of comments, or whatever, otherwise this will continue to be a problem.

Another problem is that you didn't use a correct "definitions by" in `index.d.ts`, so I had to manually track down the GH user that is responsible for this package.

---

BTW, to see the problem, go to the [api explorer](https://developer.github.com/v4/explorer/), run the following query and see the empty response:

```
query GetLabels {
  repository(name:"DefinitelyTyped", owner:"DefinitelyTyped") {
    object(expression: "master:types/fhir/fhir-tests.ts", ) {
      ... on Blob {
        __typename
        text
        byteSize
      }
    }
  }
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
