### ISSUE TITLE
`types/activex-libreoffice/index.d.ts` is dangerously big

### ISSUE THREAD

**Issue by elibarzilay** [DefinitelyTyped/DefinitelyTyped#46026]
Ping @zspitz

`types/activex-libreoffice/index.d.ts` is very big -- 5mb.

Apparently, the GH api has a limit on files that it can retrieve, and when a file is bigger than 5mb, it silently produces an empty string without an error.  I updated the mergebot to detect this and show a proper error.  In the case of this file, queries will still work, but if the file gets bigger by just a tiny bit, it will not go through the GH api (I've seen this happen to files that are 5.1mb).  At that point, the mergebot will show errors, and require a maintainer intervention which will likely slow things down.

It would be good to break it to multiple files or reduce the size of comments, or whatever, otherwise this will continue to be a problem.

**Comment by zspitz** [comment]
The definitions -- including the comments -- are for the most part auto-generated from the LibreOffice SDK, so reducing the comments is not really an option.

Splitting into two files with the top level namespaces doesn't really help -- one of the files is still nearly 5mB file.

Splitting on second-level namespaces would produce some 40 files. Is this reasonable? Or is it preferable to split at some arbitrary point in the second-level namespaces?

**Comment by zspitz** [comment]
Also, how exactly do I split the single file into multiple files? Could you link to some guidance?

**Comment by elibarzilay** [comment]
Looks like there's no text explicitly about splitting definitions, but there's the [general page on Declaration Merging](https://www.staging-typescript.org/docs/handbook/declaration-merging.html)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
