### ISSUE TITLE
`types/titanium/index.d.ts` is dangerously big

### ISSUE THREAD

**Issue by elibarzilay** [DefinitelyTyped/DefinitelyTyped#46029]
Ping @appcelerator, @janvennemann, @drauggres, @ffMathy

`types/titanium/index.d.ts` is very big -- 3mb.

Apparently, the GH api has a limit on files that it can retrieve, and when a file is bigger than 5mb, it silently produces an empty string without an error.  I updated the mergebot to detect this and show a proper error.

So this is not a problem ATM, but at some point things might fail (specifically, if it gets bigger than 5mb, mergebot will show errors).  It would be good to break it to multiple files or reduce the size of comments, or whatever.

**Comment by janvennemann** [comment]
@elibarzilay Thanks for notifying us on this. We'll try to split up the definitions into multiple files during the next update!

**Comment by elibarzilay** [comment]
Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
