### ISSUE TITLE
File in `office-js` and `office-js-preview` are dangerously big

### ISSUE THREAD

**Issue by elibarzilay** [DefinitelyTyped/DefinitelyTyped#46030]
Ping @OfficeDev, @Rick-Kirkham, @AlexJerabek, @ElizabethSamuel-MSFT, @sumurthy

The following two files are >=3mb:

    3.7M types/office-js/index.d.ts
    4.0M types/office-js-preview/index.d.ts

Apparently, the GH api has a limit on files that it can retrieve, and when a file is bigger than 5mb, it silently produces an empty string without an error.  I updated the mergebot to detect this and show a proper error.

These files are not a problem ATM, but they're very close and at some point there will likely be errors (including mergebot which will show errors and will require manual resolutions).  It would be good to break these files or reduce the size of comments, or whatever.

**Comment by AlexJerabek** [comment]
Thanks for the heads up @elibarzilay. Right now, these files power the types for the entire Office JavaScript API surface (Excel, Word, Outlook, etc). It'll be a massive undertaking to split this file, so it sounds like we should start that process soon.

**Comment by Rick-Kirkham** [comment]
@Alexander Jerabek<mailto:Alexander.Jerabek@microsoft.com>, @elibarzilay<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Felibarzilay&data=02%7C01%7Crickki%40microsoft.com%7C5cdf6f458b204e467b9808d827531146%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637302585009661757&sdata=kz3ydvXb8iJ7uW1A7mgKjPAHwonhdtDANuX0dppDAUw%3D&reserved=0>. Alternatively, since Microsoft owns GH, maybe we could get this size limitation raised.

**Comment by elibarzilay** [comment]
@AlexJerabek, well, you still have about 2mb of breathing space until this will become a problem -- if you just plan ahead to split it into two big chunks instead of one that would probably last a good while.  It's just that the current size + tendency to grow files from active projects that made me alert packages with such sizes.

@Rick-Kirkham, you could try and contact GH, but given the constraints of something that big I'm sure that they have good reasons for the current limit...  (And if you do, the something that would be really good is to get a proper error from such queries instead of silently returning an empty string...)

**Comment by elibarzilay** [comment]
Oh, one more note: we're currently fetching only `index.d.ts`, so if the main types all move out with `index.d.ts` reexporting them, that would work too.  (But future changes might make it fetch other files too.)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by AlexJerabek** [comment]
Hi @elibarzilay,

Not sure if this is still a problem or if you're the still person to ask, but office-js-preview's d.ts file is over 5MB now. Did that limitation get removed?
