### ISSUE TITLE
File in `types/dojo` are dangerously big

### ISSUE THREAD

**Issue by elibarzilay** [DefinitelyTyped/DefinitelyTyped#46031]
Ping @vansimke

The following two files are >=3mb:

    3.0M types/dojo/dojox.mobile.d.ts
    5.2M types/dojo/dijit.d.ts

Apparently, the GH api has a limit on files that it can retrieve, and when a file is bigger than 5mb, it silently produces an empty string without an error.  I updated the mergebot to detect this and show a proper error.

These files are not a problem ATM, since they're not needed for merging, but at some point there will likely be more problems that would result from this (including mergebot which might do more work).  It would be good to break these files or reduce the size of comments, or whatever.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
