### ISSUE TITLE
import NumericUpDown  from 'react-bootstrap/NumericUpDown ' not work 

### ISSUE THREAD

**Issue by re1220** [DefinitelyTyped/DefinitelyTyped#46036]
hi, 

I tried to import Numeric up down from bootstrap  and I get the following error:
Cannot find module 'react-bootstrap/NumericUpDown ' or its corresponding type declarations.ts(2307)

I installed :
npm install bootstrap-react-numeric-up-down @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons @fortawesome/react-fontawesome

from the link:
  https://www.npmjs.com/package/bootstrap-react-numeric-up-down

Thanks,

**Comment by peterblazejewicz** [comment]
@re1220 
I don't think proper definition for this specific package exists yet:
https://github.com/dfoverdx/bootstrap-react-numeric-up-down#readme 

So what I'd do, is to create a file `bootstrap-react-numeric-up-down.d.ts' in the same directory
with the content:
```ts
declare module 'bootstrap-react-numeric-up-down';
```
that will allow you to at least succesfully use that module with other TS code:
https://www.detroitlabs.com/blog/2018/02/28/adding-custom-type-definitions-to-a-third-party-library/

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
