### ISSUE TITLE
TS2339: Property 'app' does not exist on type 'typeof chrome'. in package @types/chrome

### ISSUE THREAD

**Issue by gustawdaniel** [DefinitelyTyped/DefinitelyTyped#46050]
> https://stackoverflow.com/questions/62874211/ts2339-property-app-does-not-exist-on-type-typeof-chrome-in-package-types

**Comment by peterblazejewicz** [comment]
@gustawdaniel shouldn't the `chrome.runtime.getManifest().version` be used here?
https://developer.chrome.com/extensions/runtime#method-getManifest
https://stackoverflow.com/questions/9167150/where-is-chrome-app-officially-documented

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
