### ISSUE TITLE
[types/ramda] Please use stable version of ts-toolbelt

### ISSUE THREAD

**Issue by katedoctor** [DefinitelyTyped/DefinitelyTyped#46131]
I use types/ramda and there is a problem with dependency during the build. I created an issue for ts-toobelt once, and after week problem valid again. 
link to an opened issue - https://github.com/millsp/ts-toolbelt/issues/129

**Comment by millsp** [comment]
It is stable, but ramda now supports ts>=3.7

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
