### ISSUE TITLE
Error: Package name should be strictly lowercase

### ISSUE THREAD

**Issue by inglec-arista** [DefinitelyTyped/DefinitelyTyped#46132]
I've written type definitions for the [`File`](https://www.npmjs.com/package/File) NPM module, which is distinct from [`file`](https://www.npmjs.com/package/file), another package with a lowercase name.

I get an error `Error: Package name 'File' should be strictly lowercase` when running `npm run test File`.
If I use lowercase I'll be referring to the other NPM module, which is not correct.

What's the correct workaround for this error?

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/22745 references this issue, but is closed with no responses.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by mattsmithcode** [comment]
This issue is effecting me for [another package](https://www.npmjs.com/package/justifiedGallery) which has a [package of the same name](https://www.npmjs.com/package/justifiedgallery). Is there a workaround for contributing to packages with uppercase characters in their name?

I don't get this error when running `npm test justifiedGallery`, but I do when running `npm run test-all`.

**Comment by orta** [comment]
NPM doesn't allow shipping a package with the same name and different case anymore - so you'd really need to build the types with a different name and then use `declare module` with the correct case inside that
