### ISSUE TITLE
issue with typescript

### ISSUE THREAD

**Issue by Rohit0510** [DefinitelyTyped/DefinitelyTyped#46153]
I have tried to use react-data-grid in tsx file by installing @type/react-data-grid but it is not working .
Error showing cannot find module and cannot resolve.

**Comment by peterblazejewicz** [comment]
`@type/react-data-grid` seems like a typo obviously: `@types/react-data-grid` (cannot be so easy to fix), can you please share the errors, so people couuld look into the problem? Thx!

**Comment by Rohit0510** [comment]
I have tried to install this package by following command
npm install --save @types/react-data-grid and facing the following error
Failed to load component "f4783611-9758-4073-be66-aa3ef9a23312" (HelloWorldWebPart). Original error: ***Failed to load entry point from component "f4783611-9758-4073-be66-aa3ef9a23312" (HelloWorldWebPart). Original error: Cannot find module 'react-data-grid'
plz share your suggestions to resolve this issue

**Comment by peterblazejewicz** [comment]
@Rohit0510 I think issue is with your project misconfiguration, not with the type definition itself (have you added dependency to `react-data-grid` itself?)

Please try to get help on react channel on TS discord:
https://discord.com/invite/typescript

This should get you started (sample snip on stackblitz with DT package setup):
https://stackblitz.com/edit/react-ts-7nzdqr

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
