### ISSUE TITLE
[@types/codemirror] Interface 'Editor' incorrectly extends interface 'Doc'

### ISSUE THREAD

**Issue by tjquillan** [DefinitelyTyped/DefinitelyTyped#46173]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
     - @mihailik 
     - @nrbernard
     - @Pr1st0n
     - @rileymiller
     - @toddself
     - @ysulyma
     - @azoson 
     - @kylesferrazza
     - @fityocsaba96
     - @koddsson

If you do not mention the authors the issue will be ignored.

Output:
```
node_modules/@types/codemirror/index.d.ts:208:15 - error TS2430: Interface 'Editor' incorrectly extends interface 'Doc'.

208     interface Editor extends Doc {
                  ~~~~~~

node_modules/@types/codemirror/index.d.ts:208:15 - error TS2430: Interface 'Editor' incorrectly extends interface 'Doc'.
  The types returned by 'listSelections()' are incompatible between these types.
    Type '{ anchor: Position; head: Position; empty(): boolean; }[]' is not assignable to type 'Range[]'.
      Type '{ anchor: Position; head: Position; empty(): boolean; }' is missing the following properties from type 'Range': from, to

208     interface Editor extends Doc {
                  ~~~~~~
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
