### ISSUE TITLE
[@types/google-protobuf] BinaryEncoder, BinaryDecoder not exported by original package

### ISSUE THREAD

**Issue by jackielii** [DefinitelyTyped/DefinitelyTyped#46204]
It looks like the original package didn't export the `BinaryEncoder`, `BinaryDecoder` `Int64` or `UInt64`:

https://github.com/protocolbuffers/protobuf/blob/master/js/commonjs/export.js

I think these should be exported though: https://github.com/protocolbuffers/protobuf/issues/7739

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
