### ISSUE TITLE
Dependency on source JavaScript within Nuget???

### ISSUE THREAD

**Issue by gravidThoughts** [DefinitelyTyped/DefinitelyTyped#4621]
5 Different versions of angular-ui-router.TypeScript.DefinitelyTyped exist in Nuget.

All 5 versions have the same exact preface of 

// Type definitions for Angular JS 1.1.5+ (ui.router module)
// Project: https://github.com/angular-ui/ui-router
// Definitions by: Michel Salib https://github.com/michelsalib
// Definitions: https://github.com/borisyankov/DefinitelyTyped

/// reference path="../angularjs/angular.d.ts" />

The metadata has no declared dependencies on Angular.UI.UI-Router which is the Nuget package that contains the javascript source for the d.ts file.

How am I supposed to tell which version of Angular.UI.UI-Router corresponds to the d.ts?

Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
