### ISSUE TITLE
Detox: Update (breaking) types for DetoxNext/v17

### ISSUE THREAD

**Issue by Guuz** [DefinitelyTyped/DefinitelyTyped#46224]
Detox is undergoing some bigger changes and the API is changing to.
https://github.com/wix/Detox/blob/d1aa4f547a6aa07d99f2dac0f0c627051a411df0/docs/Guide.Migration.md#1700

I was asked to mention the authors:
@TareqElMasri 
@stevechun 
@hammadj 
@santiagofm
@maxkomarychev
@Dor256

**Comment by naushad-madakiya** [comment]
any plans on adding these changes?

**Comment by santiagofm** [comment]
I doubt I'll work on this bc I don't use Detox anymore for now, I encourage you to add the new types yourselves!

**Comment by Dor256** [comment]
I can only start working on this in two weeks from now, I work closely with the Detox team so if this doesn't get addressed until I'm available I'll submit a PR

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
