### ISSUE TITLE
Relay StoreUpdater receives an argument of type RecordSourceSelectorProxy, not RecordSourceProxy

### ISSUE THREAD

**Issue by pranaygp** [DefinitelyTyped/DefinitelyTyped#46248]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c947e99f222c5801fe46a9a6fe4dc74b0dce5739/types/relay-runtime/lib/store/RelayStoreTypes.d.ts#L742

see https://relay.dev/docs/en/relay-store#recordsourceselectorproxy

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
