### ISSUE TITLE
Conflict @types/k6 with @types/node

### ISSUE THREAD

**Issue by Parahet** [DefinitelyTyped/DefinitelyTyped#46258]
There are some errors when I use **@types/node** with **@types/k6**
Here is my dependencies:
`"devDependencies": {
    "@types/url-parse": "^1.4.3",
    "typescript": "^3.9.7"
  },
  "dependencies": {
    "@types/k6": "^0.26.1",
    "@types/node": "^14.0.24",
    "tslint": "^6.1.2",
    "url-parse": "^1.4.7"
  }`
And I got next errors:
`node_modules/@types/k6/global.d.ts:69:9 - error TS2451: Cannot redeclare block-scoped variable 'console'.`
`node_modules/@types/node/console.d.ts:109:13 - error TS2451: Cannot redeclare block-scoped variable 'console'.`

When I remove **@types/node** everything is ok

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
