### ISSUE TITLE
React's useCallback: callback allows implicity any

### ISSUE THREAD

**Issue by lazybean** [DefinitelyTyped/DefinitelyTyped#46309]
We are using typescript with strict mode (specifically noImplicityAny: true).
This should disallow use to declare function with untyped parameters.
My problem is that the definition of `useCallback` explicity set the type of the callback's args to extend any[]; so if I omit type they are now any.
```
  const hello = useCallback((name, age: number) => {  // typsecript will warn me here, name has implicit 'any'
    return { name, age };
  }, []);

  const hello = useCallback((name, age: number) => { // I expect typescript to tell me `name` is implicitely `any`, but no.
    return { name, age };
  }, []);
```
![image](https://user-images.githubusercontent.com/529333/88367054-16822e80-cd8b-11ea-873c-c65abf23e646.png)

If I go change the definition of useCallback from :
` function useCallback<T extends (...args: any[]) => any>(callback: T, deps: DependencyList): T;`
to:
`function useCallback<T extends Function>(callback: T, deps: DependencyList): T;`
It then properly warns me, ~~but it certainly breaks many other things.~~, it seems to not break things.

![image](https://user-images.githubusercontent.com/529333/88367293-b770e980-cd8b-11ea-9c2f-4840a319a408.png)

- [x] I tried using the `@types/react` package and had problems.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @eps1lon

**Comment by eps1lon** [comment]
Ideally we would use `unknown[]` instead which would keep type safety even outside of noImplicitAny.  I just saw that TS 2.9 has already reached EOL. Might make sense to go over some types that could be improved with TS 3.0 and create a fork.

> function useCallback<T extends function>(callback: T, deps: DependencyList): T;
It then properly warns me, but it certainly breaks many other things.

Such as? A PR would be better suited for that to find out if that would indeed work.

Until then I suspect we can't really do much. Callbacks pretty common in JS so I suspect that there already exists a known pattern that preserves "implicit any" errors or it just doesn't work.

/cc @ferdaber, @Jessidhia

**Comment by lazybean** [comment]
Thanks for the quick answer!
> Ideally we would use `unknown[]` instead which would keep type safety even outside of noImplicitAny. I just saw that TS 2.9 
has already reached EOL. Might make sense to go over some types that could be improved with TS 3.0 and create a fork.
My attempts using `unknown[]` failed. 
> 
> > function useCallback(callback: T, deps: DependencyList): T;
> > It then properly warns me, but it certainly breaks many other things.
> 
> Such as? A PR would be better suited for that to find out if that would indeed work.
I just tried, and couldn't find anything breaking. I made a PR.
> 
> Until then I suspect we can't really do much. Callbacks pretty common in JS so I suspect that there already exists a known pattern that preserves "implicit any" errors or it just doesn't work.
> 
> /cc @ferdaber, @Jessidhia

**Comment by ferdaber** [comment]
The last time we (I) updated the minimum version requirement for React types, it broke the CI (way more than it usually does) and I had to split up the PR into 3 different ones due to the sheer volume of tests that needed to be run. I think it's one of those things that are better left with the TS-team maintainers (they do this from time to time I think).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
