### ISSUE TITLE
[@types/chartist] Missing properties and incorrect types.

### ISSUE THREAD

**Issue by lachieh** [DefinitelyTyped/DefinitelyTyped#46300]
- [x] I tried using the `@types/chartist` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] ~~I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).~~
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:
    - Matt Gibbs @mtgibbs
    - Simon Pfeifer @psimonski
    - Anastasiia Antonova @affilnost
    - Sunny Juneja @sunnyrjuneja
    - Sam Raudabaugh @raudabaugh
    - Manuel Borrajo @borrajo

First of all, thank you to all of the authors above. I appreciate your work!

I've been using this package to build a Chartist plugin and I've noticed something. Figured I would ask about it first before attempting to resolve.

- `IChartOptions` (or maybe just ILineChartOptions?) is missing the following properties:
  ```
  svg?: IChartistSvg;
  chartRect?: {
    height: () => number;
    width: () => number;
    padding: {
      bottom: number;
      left: number;
      right: number;
      top: number;
    };
    x1: number;
    x2: number;
    y1: number;
    y2: number;
  };
  ```

Edit: removed part of issue because I misunderstood data structure. Issue above still stands.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
