### ISSUE TITLE
[@types/googlemaps] compatibility with googlemaps versions 3.40+

### ISSUE THREAD

**Issue by philipreimer** [DefinitelyTyped/DefinitelyTyped#46312]
`index.d.ts` states: `// Type definitions for Google Maps JavaScript API 3.39`

[Google Maps Versioning guide](https://developers.google.com/maps/documentation/javascript/versions#choosing-a-version-number) states:

> After mid-August, you will be able to specify v=3.42, v=3.41, or v=3.40. [...] Version 3.39 will no longer be available.

Will there be an update for `@types/googlemaps` for googlemaps versions `3.40+`?
Or is the current version already compatible and the version information in `index.d.ts` is just outdated?

@jpoehnelt @demensky

**Comment by jpoehnelt** [comment]
The types will still be compatible. I have some work to automate the update of the types from the googlemaps published externs that are tied to a version, but it is currently on hold.

**Comment by IsaacSomething** [comment]
Seems to missing the `mapId` for the new map management things in beta

```
  interface MapOptions {
        mapId?:string;
```

ref: https://developers.google.com/maps/documentation/javascript/cloud-based-map-styling

**Comment by sgehrman** [comment]
dude, just wasted hours on this.  please fix.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
