### ISSUE TITLE
[@types/carbon-components-react] Incorrect 'shouldFilterItem' type on ComboBox component

### ISSUE THREAD

**Issue by machowina** [DefinitelyTyped/DefinitelyTyped#46320]
- [x] I tried using the `@types/carbon-components-react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
      - @kalbert312 
      - @sgregoire
      - @matchilling

I was using the ComboBox component, and the type for `shouldFilterItem` property is currently:
`shouldFilterItem?(item: ItemType, itemToString?: ComboBoxProps<ItemType>["itemToString"], inputValue?: string): void,`

However I think it should rather be:
`shouldFilterItem?({ item: ItemType, itemToString?: ComboBoxProps<ItemType>["itemToString"], inputValue?: string }): boolean,`
where instead of three parameters we have one object, and instead of void is boolean

The default value for that property in carbon library has return type boolean:
 `const defaultShouldFilterItem = () => true;`
And here in use of this function it takes object https://github.com/carbon-design-system/carbon/blob/0037736f71cce485e7b4e7539a7159f89315d11c/packages/react/src/components/ComboBox/ComboBox.js#L227

Thank you for all your work:)

**Comment by kalbert312** [comment]
This was resolved at some point in time.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
