### ISSUE TITLE
[Request] post-type-discovery

### ISSUE THREAD

**Issue by hirusi** [DefinitelyTyped/DefinitelyTyped#46339]
Requesting type definitions for [twozeroone/post-type-discovery](https://github.com/twozeroone/post-type-discovery) by @prtksxna.

@aimee-gm has done fantastic work [on her library microformats-parser](https://github.com/aimee-gm/microformats-parser) which may be useful here. See [type definitions for her project](https://github.com/aimee-gm/microformats-parser/blob/master/src/types.ts).

**Comment by prtksxna** [comment]
Is this something I can help with? Sorry I am not familiar with TypeScript at all 😞

**Comment by hirusi** [comment]
I'm not sure either, unfortunately. I tried writing my own definitions but failed pretty badly, hence this request.

**Comment by aimee-gm** [comment]
I can give this a go, but my preference would be to maintain them in https://github.com/twozeroone/post-type-discovery, if @prtksxna is happy for them to be there? It would involve adding TypeScript as a `devDependency`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
