### ISSUE TITLE
[lodash] Unable to map over a partition in a chain

### ISSUE THREAD

**Issue by danvk** [DefinitelyTyped/DefinitelyTyped#46377]
```ts
interface Person {
  name: string;
  age: number;
}

declare let people: Person[];
const [evens, odds] = _(people)
  .partition(p => p.age % 2 === 0)
  .map(parityPeople => parityPeople.map(p => p.name))
// ~~~ Property 'map' does not exist on type 'LoDashImplicitWrapper<[Person[], Person[]]>'.
  .value();
```

This code runs fine but fails to type check. Mapping over an unwrapped tuple type using the native `map` is fine:

```ts
  const [evens, odds] = _(people)
    .partition(p => p.age % 2 === 0)
    .value()
    .map(parityPeople => parityPeople.map(p => p.name));  // ok
```

- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @WilliamChelman @DomiR @aj-r

If you do not mention the authors the issue will be ignored.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
