### ISSUE TITLE
@types/react-datepicker - renderCalendarTo is not included

### ISSUE THREAD

**Issue by SaraKoncz** [DefinitelyTyped/DefinitelyTyped#46545]
It seems `renderCalendarTo` is not included in index.d.ts
This property also not properly documented in react-datepicker, but used by many users, please see issue below:
[react-datepicker/issues/520](https://github.com/Hacker0x01/react-datepicker/issues/520)

Would be a great help to include it in the index.d.ts, preferably not with `any` as type.

Authors: @andrewBalekha , @smrq

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
