### ISSUE TITLE
Missing Type Definitions for autoType function in d3-dsv?

### ISSUE THREAD

**Issue by n0x3u5** [DefinitelyTyped/DefinitelyTyped#46548]
- [x] I tried using the `@types/d3-dsv` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek , @gustavderdrache , @borisyankov , @denisname 

Attempting to import the [autoType](https://github.com/d3/d3-dsv#autoType) function from `d3-dsv` with `@types/d3-dsv` already installed results in the following error:
> Module 'node_modules/@types/d3-dsv' has no exported member 'autoType'. ts(2305)

Is this due to the type definition file missing the declaration for `autoType` or am I missing something?

**Comment by Ledragon** [comment]
@n0x3u5 could you check now? A new version of `d3-dsv` types has been published

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
