### ISSUE TITLE
(@types/d3-hierarchy) Suggestion: Add constrain to Datum type

### ISSUE THREAD

**Issue by reynard2007** [DefinitelyTyped/DefinitelyTyped#46564]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/d3-hierarchy` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tomwanzek, @gustavderdrache, @borisyankov, @denisname

If you do not mention the authors the issue will be ignored.

----

I suggest we constrain the value of `Datum` to be not `null` or `undefined`. Since the supported `typescript` version for this is v2.0, I am unable to use the conditional `NonNullable` that's available on v2.8. Instead, I just listed down the possible values that are not null and not undefined.

Currently, I am allowed by the `hierarchy` function to pass null | undefined values, which causes an uncaught error.

I created a [commit](https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...reynard2007:patch-1) for your review. Let me know if this works on your end.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
