### ISSUE TITLE
AbstractSeriesProps types does not include svg <rect> styles

### ISSUE THREAD

**Issue by galilmori** [DefinitelyTyped/DefinitelyTyped#46588]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a4a44ec932fc900325052bc8a3d655f6684dce37/types/react-vis/index.d.ts#L268

Since in the BarSeries styles are used in a  <rect/>, IMHO it should include svg styles such as rx ry. when I try to modify corners of bars i have to declare rx and ry as any at at the moment.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
