### ISSUE TITLE
InitialSettings declaration type missing in index.d.ts in bootstrap-date-range-picker

### ISSUE THREAD

**Issue by tarun1992** [DefinitelyTyped/DefinitelyTyped#46597]
I am working on an application that uses Reaact+Typescript and I am using react-bootstrap-daterangepicker modue to implement a date picker. While implementing this, with the below code 
 `<DateRangePicker startDate="1/1/2014" endDate="3/1/2014" 
			initialSettings={{locale:locale}}
			>
        <input type="text" className="form-control" />
      </DateRangePicker>`
I am getting below  error
`No overload matches this call.
Overload 1 of 2, '(props: Readonly<Props>): DateRangePicker', gave the following error.
Type '{ children: Element; startDate: string; endDate: string; initialSettings: { locale: { format: string; separator: string; applyLabel: string; cancelLabel: string; fromLabel: string; toLabel: string; customRangeLabel: string; daysOfWeek: string[]; monthNames: string[]; firstDay: number; }; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<DateRangePicker> &`

Can the module owner add this prop so that it works with the updated version of the date picker.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
