### ISSUE TITLE
[@types/oauth2-server] Types isn't supporting generator functions

### ISSUE THREAD

**Issue by Streeterxs** [DefinitelyTyped/DefinitelyTyped#46658]
As mentioned [here](https://oauth2-server.readthedocs.io/en/latest/model/spec.html#model-specification) generator fn is supported by a model obj.

The solution maybe be arround using IterableIterator and Generator interfaces.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @vangorra , @cirick , @d-fischer , @rvitorsantos

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
