### ISSUE TITLE
[@types/echarts] renderItem in @types/echarts/options/series/custom.d.ts defined incorrectly

### ISSUE THREAD

**Issue by uwemeier-sclable** [DefinitelyTyped/DefinitelyTyped#46670]
It looks like the definition of `renderItem` of interface `SeriesCustom` just got parsed according to the [Echarts documentation](https://echarts.apache.org/en/option.html#series-custom.renderItem). However, `renderItem` needs a function similar to `function (params: object, api: object): object` rather than an object with
```typescript
{
  arguments?: {
    params?: object;
    api? object { ... };
  };
  return?: object;
  ...
}
```

As a workaround, the function can be casted to `object`.

I'm sorry that I'm not proficient enough in typescript, to create a PR and type it correctly on my own.

Kind Regards,
Uwe

___
- [x] I tried using the `@types/echarts` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

  - Authors: @xieisabug @AntiMoron @liveangela @Ovilia @iRON5 @bilalucar @tmtron @dwhitney @ruixuel @robert-wettstaedt @trajnisz

**Comment by caperso** [comment]
yep I met same problem , hope someone familiar with echarts deal with it

**Comment by SteppingRazor** [comment]
@uwemeier-sclable @caperso 
Please check [version 4.8.3](https://www.npmjs.com/package/@types/echarts) and let me know.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
