### ISSUE TITLE
@types/xrm

### ISSUE THREAD

**Issue by BKamleitner** [DefinitelyTyped/DefinitelyTyped#46717]
Can getControl return Controls.StandardControl in @types\xrm\index.d.ts Authors: @scottdurow  such that isVisible (and others) are available?

Like it is now someone has to do:

(formContext.getControl("somefield") as Xrm.Controls.StandardControl).getDisabled() or am i missing something?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
