### ISSUE TITLE
Property 'MandateId' does not exist on type 'PayInData'.

### ISSUE THREAD

**Issue by mhernik** [DefinitelyTyped/DefinitelyTyped#46724]
Request to get PayIn returns two properties that are not typed:
* MandateId: string
* StatementDescriptor: string

Those attributes are missing in interface

Authors: @ifiokjr

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
