### ISSUE TITLE
IndicatorContainerProps not exported

### ISSUE THREAD

**Issue by simon-asp** [DefinitelyTyped/DefinitelyTyped#46788]
Is something wrong with CI or publishing infrastructure?
No

- [x] I tried using the `@types/react-select` package and had problems.
- [] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @claasahl @jonfreedman @Methuselah96 

### Issue
* I noticed that `IndicatorContainerProps` are not exported from the root, but the `ValueContainerProps` are. `IndicatorProps` are exported but I can't use that for my use case. See below.

### Example
I want to be able to build something like this, with the correct props. 
```
import React from 'react';
import Select, { components, IndicatorContainerProps } from 'react-select';

type OptionType = {
  label: string;
  value: string;
};

const IndicatorsContainer: React.FC<IndicatorContainerProps<OptionType>> = (props) => {
  return (
    <components.IndicatorsContainer {...props}>
      <div>Some indicator</div>
    </components.IndicatorsContainer>
  );
};

export const SomeComponent: React.FC = () => <Select components={{ IndicatorsContainer }} ... />;
```

**Comment by Methuselah96** [comment]
Make a PR and add an export to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/index.d.ts.

**Comment by simon-asp** [comment]
Thanks!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
