### ISSUE TITLE
bootbox.js is out of date

### ISSUE THREAD

**Issue by bradlis7** [DefinitelyTyped/DefinitelyTyped#4681]
Current bootbox version is 4.4.0, but you only have 4.0.0. One thing I noticed is that `bootbox.dialog()` returns a `JQuery` object, but your definition says it returns void.

**Comment by vvakame** [comment]
@bradlis7 please send a pull request. I'll review it.

**Comment by tetsuo13** [comment]
This issue was completed in PR #4741. Can someone please close it?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
