### ISSUE TITLE
[@types/prettier] Missing exports from standalone.d.ts

### ISSUE THREAD

**Issue by joeried** [DefinitelyTyped/DefinitelyTyped#46839]
standalone.js has exports for e.g. doc and util. If I'm not mistaken these exports are missing in the types. 

- [X] I tried using the `@types/prettier` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ikatyang, @ifiokjr, @ffflorian, @sosukesuzuki

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
