### ISSUE TITLE
[@types/elliptic] SignOptions not working

### ISSUE THREAD

**Issue by bokunobaka** [DefinitelyTyped/DefinitelyTyped#46837]
Is something wrong with CI or publishing infrastructure? No

- [x] I tried using the `@types/elliptic` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @danwbyrne  @Gilthoniel

If you do not mention the authors the issue will be ignored.

### The problem
Interface _ec.SignOptions.k_ is defined as _BN_, but starting version 6.1.0 of the library uses the _k_ as a _function_ "options.k(iter)" which throws and error
"ERROR TypeError: options.k is not a function"

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
