### ISSUE TITLE
The @types/i18n doesn't include { I18n } contructor update

### ISSUE THREAD

**Issue by TheInvoker** [DefinitelyTyped/DefinitelyTyped#46871]
Based on this recent update https://github.com/mashpie/i18n-node/issues/439

The i18n class now supports a { I18n } constructor property which allows you to make a new instance of i18n. The types for this is not there in @types/i18n. When would this be added?

**Comment by jcapinc** [comment]
Could you give examples for the old usage and the new usage?

**Comment by TheInvoker** [comment]
well according to this

https://www.npmjs.com/package/i18n

it supports
```

/**
 * require I18n with capital I as constructor
 */
const { I18n } = require("i18n");
 
/**
 * create a new instance 
 */
const i18n = new I18n();
```

So I figure the expected typescript usage should be

```
import { I18n } from "i18n";
const i18n = new I18n();
```

And the type of i18n is an instance of the original i18n class.

**Comment by woodcockjosh** [comment]
@jcapinc wen merge?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
