### ISSUE TITLE
DOM API Type Definition

### ISSUE THREAD

**Issue by mohsen1** [DefinitelyTyped/DefinitelyTyped#4688]
[DOM API](https://developer.mozilla.org/en-US/docs/Web/API) is huge but it's going to be useful to have it entirely covered. Libraries can benefit from it the most. Has anyone tried writing type definition of the DOM?

**Comment by cgwrench** [comment]
A number of the APIs and types listed on that page are already covered by [`lib.d.ts`](https://github.com/Microsoft/TypeScript/blob/master/bin/lib.d.ts).

However, I'm sure that many of the APIs which aren't part of the ECMAScript language or the core DOM API do not have their own typings (see, for example, [`window.performance`](https://developer.mozilla.org/en-US/docs/Web/API/Performance)), so it would be useful to have these typed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
