### ISSUE TITLE
@types/graphql-upload needs to be updated

### ISSUE THREAD

**Issue by Daavidaviid** [DefinitelyTyped/DefinitelyTyped#46904]
https://www.npmjs.com/package/@types/graphql-upload is still depending on the version `^14.0.0` of graphql. We need to upgrade to `^15.0.0`

**Comment by olyop** [comment]
[https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46904#issue-681965844](url)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
