### ISSUE TITLE
GetIntrinsic erros

### ISSUE THREAD

**Issue by dflorey** [DefinitelyTyped/DefinitelyTyped#46917]
I'm getting a bunch of errors like these and have no clue what to do to get my app compile again:

node_modules/@types/es-abstract/GetIntrinsic.d.ts:555:58 - error TS2339: Property 'flat' does not exist on type 'any[]'.
555         '%Array.prototype.flat%': typeof Array.prototype.flat;
                                                             ~~~~

node_modules/@types/es-abstract/GetIntrinsic.d.ts:556:61 - error TS2339: Property 'flatMap' does not exist on type 'any[]'.
556         '%Array.prototype.flatMap%': typeof Array.prototype.flatMap;

- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@ljharb 
@ExE-Boss

**Comment by ExE-Boss** [comment]
You need to have <code>[lib][tsconfig-lib]: ["ESNext"]</code> in your <code>[tsconfig.json]</code>.

[tsconfig-lib]: https://www.typescriptlang.org/tsconfig#lib
[tsconfig.json]: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by codekpchang** [comment]
I'm also running into this issue with my build and have already included `lib: ["ESNext"]` in my `tsconfig.json` file.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
