### ISSUE TITLE
async.d.ts parallel expecting all functions to have the same type

### ISSUE THREAD

**Issue by DanielReid** [DefinitelyTyped/DefinitelyTyped#46949]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov
 @kern0
@Penryn
@fenying
@pascalmartin
@Dmitri1337
@erossignon
@Juliiii
@brendtumi

Hi, I encountered an issue when I tried to use parallel for processes which return different types, like so:

```
  function foo() {
    parallel([foo1, foo2], (error: any, results: [results1, results2]: [number[], string[]]) => {
      console.log(results1 + ' ' + results2);
    });
  }

  function foo1(callback: (error: any, result: number[]) => void) {
    callback(null, [1, 2]);
  }
  function foo2(callback: (error: any, result: string[]) => void) {
    callback(null, ['hi', 'hjo']);
  }
```

This does not compile, and my understanding is that this is because the definition in 
```
export function parallel<T, E = Error>(tasks: Array<AsyncFunction<T, E>>, callback?: AsyncResultArrayCallback<T, E>): void;
```
binds all resultcallbacks to have the same type T.

I'm not sure how this could be fixed or whether it needs to; for now I'm working around it by simply going `parallel<number|string>...`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
