### ISSUE TITLE
Add types for package asar?

### ISSUE THREAD

**Issue by gzzchh** [DefinitelyTyped/DefinitelyTyped#46975]
the types file of package asar is here.   
https://github.com/electron/asar/blob/master/lib/index.d.ts  
have somebody add it to this repo?  

so that can use the npm to install the types instead of adding paths to the tsconfig.json

**Comment by peterblazejewicz** [comment]
@gzzchh 
That's not required, modern TSC reads information from `package.json` and there is a proper entry there:
https://github.com/electron/asar/blob/master/package.json#L6
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package
hth

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
