### ISSUE TITLE
@types/mongoose: typed projections

### ISSUE THREAD

**Issue by pbadenski** [DefinitelyTyped/DefinitelyTyped#47051]
At the moment `projection` is of type any... this is a more of an open-ended question whether it's at all possible to build types around it.

Ideally type returned from `findXXX` when projection is used would also take that information into the account.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
