### ISSUE TITLE
Types for jquery UI should be called jquery-ui as the package

### ISSUE THREAD

**Issue by crystalfp** [DefinitelyTyped/DefinitelyTyped#47068]
I have installed the package for jQuery UI this way: `npm i jquery-ui` then I installed the corresponding types with: ` npm i -D @types/jquery-ui` but this creates the directory `@types/jqueryui` that is named as an obsolete package. The latest package is called "jquery-ui" and so should the type package directory be called, otherwise typescript does not find it.

Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: Boris Yankov <https://github.com/borisyankov>, John Reilly <https://github.com/johnnyreilly> @johnnyreilly 

If you do not mention the authors the issue will be ignored.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
