### ISSUE TITLE
[@types/mongoose] Upgrade @types/mongodb to 3.5.26

### ISSUE THREAD

**Issue by pbadenski** [DefinitelyTyped/DefinitelyTyped#47070]
There's been a number of type fixes and at least one feature (compression option) since current 3.5.3 packaged with @types/mongoose.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
