### ISSUE TITLE
angular-resource.d.ts - IResourceClass'T bad return type to get/save/remove/delete method

### ISSUE THREAD

**Issue by ilgb** [DefinitelyTyped/DefinitelyTyped#4708]
In  IResourceClass'T get/save/remove/delete method return T type; but I think that they should be  IResource'T.
Without these we haven't the access to $promise and $resolved properties.
(it's ok for query method that return an IResourceArray'T)

**Comment by vvakame** [comment]
@ilgb please send a pull request. I'll review it.

**Comment by ilgb** [comment]
Pull request done (#4721)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
