### ISSUE TITLE
@types/ramda

### ISSUE THREAD

**Issue by char0n** [DefinitelyTyped/DefinitelyTyped#47081]
Hi @devrelm, 

I suppose you're the maintainer of the ramda types (I've inspected the latest commits there).
I'll provide a code to demonstrate the problem that I currently face.

```js
import { curry, both } from 'ramda';

const fn = curry((a: boolean, b: boolean): boolean => a && b);

const fn1 = fn(true);

both(fn1, fn1); // types ok

both(fn(true), fn(true)); // Curry<(...args: readonly any[]) => boolean>' is not assignable to parameter of type 'Pred'
```

I don't understand what is the different between assigning a curried function to a variable and using it later and inlining the curried call directly in composition. To me (not that familiar with TypeScript), this is equivalent.

Thank you for any answer!

**Comment by chughes87** [comment]
This is super interesting! Commenting to follow any answers someone might come up with.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
