### ISSUE TITLE
@types/leaflet L.control function is a namespace?

### ISSUE THREAD

**Issue by saosebastiao** [DefinitelyTyped/DefinitelyTyped#47085]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: 
@alejo90
@atd-schubert
@mcauer
@ronikar
@sanfrisc
@life777
@henrythasler
@captain-igloo 

When trying to run this code:

```
let toolbar: Control = L.control({ position: 'topright' }) as Control;
```

I get a type error:
```
namespace control
This expression is not callable.
  Type 'typeof control' has no call signatures.ts(2349)
```

Is this just the result of a missing function signature? Or is control really supposed to be a namespace. Sorry I can't be more help, I don't know how to modify type definitions appropriately for this function.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by bonesoul** [comment]
any ideas, fixes on this @saosebastiao, having the same issue here.

**Comment by Getsumi3** [comment]
So, looks like `L.control` type is actually a namespace and not an instance of `Control`(like we expected?).
Under the hood `L.control` is a function that returns a new instance of `Control`
So a workaround that I found is to directly use `Control` instead of `L.control` like this:

```
import L, { Control } from "leaflet";

const legend = new Control({ position: 'topright' });
```

It worked for me, hope it will work for you
