### ISSUE TITLE
[firefox-webext-browser] split namespaces by usage context so unavailable APIs are typed as such

### ISSUE THREAD

**Issue by leaumar** [DefinitelyTyped/DefinitelyTyped#47142]
Authors: @jsmnbom 

Suggestion I'd like to discuss before attempting to offer a PR (to not waste too much time if the idea is rejected): let's

1. split the namespaces into their own files (in part to break up the monolithic `index.d.ts` a bit)
2. export all namespaces from `index.d.ts` so that compatibility is not broken
3. export an additional few .d.ts files, e.g. `content-script.d.ts`, containing only the namespaces available in the given context

## as-is
`import "firefox-webext-browser"` everywhere: all APIs are available in every context, including e.g. background-only APIs in content scripts. You rely on knowledge and documentation (and some common sense, but still) to avoid calling APIs that are _not actually available at runtime_.
## to-be
`import "firefox-webext-browser/content-script"` (or other as appropriate) and simply only have access to APIs that are available in the first place. You cannot call APIs that will not exist at runtime.

If you agree with this idea, I can attempt a PR. :)

**Comment by jsmnbom** [comment]
I disagree with your "as-is". This is not how I've seen anyone use the definitions. If you install it from "@types/firefox-webext-browser" and make sure that typescript can load types from node_modules, then you never need to import it as it is automatically just available.
Also, these types are auto generated by https://github.com/jsmnbom/definitelytyped-firefox-webext-browser, and there's no easy way to find out in which contexts each API is availible (sure there's some data about some things in the schema files, but most of it is wrong or outdated or chrome specific), so that makes doing so next to impossible.

**Comment by leaumar** [comment]
Now that you mention it, it does make sense the types should be immediately available. Not sure they they aren't, my IDE complained about it until I imported the package.

I can't speak for the operational difficulty of checking/maintaining the info, so ok, if you're sure it's not very feasible, let's close the idea. One can only try. :) Thanks for discussing.

**Comment by jsmnbom** [comment]
What IDE are you using? It really should pick up types if your tsconfig is correct.
I mean, unless you wanna go digging through the firefox source or test every API in all contexts, I don't think there's a feasible way of getting proper data for this.

**Comment by leaumar** [comment]
FYI needing to import the types was just a glitch I still sometimes fall for where my IDE's type resolution gets stale and doesn't update with project changes until I restart it. The types work automatically indeed.
