### ISSUE TITLE
Mocha: typings allow mixing two test styles

### ISSUE THREAD

**Issue by just-boris** [DefinitelyTyped/DefinitelyTyped#47228]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/mocha` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @kazimanzurrashid @otiai10 @enlight @cspotcode @1999

The following code passes typescript check, but fails in runtime

```ts
it('bdd style', () => {});

test('tdd style', () => {})
```

Expected result that mocha typings allow to choose type of API, but only one at the time. Perhaps it could be fixed by importing the ui explicitly:

```js
import 'mocha/ui/bdd';

it('bdd style', () => {});

// error, cannot find name `test`
test('tdd style', () => {})
```

**Comment by cspotcode** [comment]
If we make this change, we should also allow consumers to avoid the globals
entirely, to avoid conflicts with other declarations.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
