### ISSUE TITLE
version 14.6.3  Cannot find name 'asserts'.

### ISSUE THREAD

**Issue by xudingjiemike** [DefinitelyTyped/DefinitelyTyped#47248]
i work with a few React projects. One of them has a dependency on a library  'types_node', today has some worry in build 

the log is：
ERROR in /Users/project/node_modules/_@types_node@14.6.3@@types/node/assert.d.ts(2,60):
TS2304: Cannot find name 'asserts'.

use version 14.6.2 ，the problem didn't happen

**Comment by G-Rath** [comment]
This is the same problem as #47250 - it's because DefinitelyTyped no longer supports TypeScript 2, as per the [support table](https://github.com/DefinitelyTyped/DefinitelyTyped#older-versions-of-typescript-30-and-earlier) in the readme.

You'll have to update to TypeScript 3.2 or above to be able to consume the latest version of `@types/node` :)

**Comment by chillinski** [comment]
Same fix here.

> use version 14.6.2 ，the problem didn't happen

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
