### ISSUE TITLE
jstree.d.ts: $.vakata error

### ISSUE THREAD

**Issue by meriturva** [DefinitelyTyped/DefinitelyTyped#4724]
The "vakata" property on JQueryStatic is not declared.
I guess that a simple:

```
interface JQueryStatic {
    vakata?: any;
}
```

has to be added on the d.ts file.
Thanks.
Meriturva

**Comment by vvakame** [comment]
@meriturva please send a pull request. I'll review it.

**Comment by AdaskoTheBeAsT** [comment]
Hi,

sorry for long delay - as soon as my latest pull request will be merged I will prepare that change.
I thought that 'vakata' is some internal stuff in and shouldn't be exposed in interface anyway I will add it.

Best regards

Adam

**Comment by meriturva** [comment]
Thanks @AdaskoTheBeAsT ....you can close that issue....we have already moved to kendo and angular 2.

**Comment by frjonsen** [comment]
@AdaskoTheBeAsT Did this ever get added? I am facing the same issue as meriturva was, though migrating to something else is not an option for us.

**Comment by AdaskoTheBeAsT** [comment]
Hi,

sorry for delay - pull request waiting for merge.

Best regards

Adam

**Comment by AdaskoTheBeAsT** [comment]
Pull req merged

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
