### ISSUE TITLE
[styled-components] Typing components defined as object props

### ISSUE THREAD

**Issue by zimmicz** [DefinitelyTyped/DefinitelyTyped#47265]
I like styled-components naming featured at https://medium.com/inturn-eng/naming-styled-components-d7097950a245. However, I hit the wall using it with Typescript, as I can't find a way to type styled components defined as object values.
I've set up a sandbox at https://codesandbox.io/s/wizardly-fog-z11r9?file=/src/App.tsx.

Is there anything that can be done to make it work?

cc @Igorbek @Igmat @LavaToaster @Jessidhia @JKillian @eps1lon @flavordaaave

**Comment by kambleaa007** [comment]
is this enhancement you are supposing?

**Comment by zimmicz** [comment]
Rather a question to find a way around the issue mentioned above.

**Comment by kambleaa007** [comment]
it seems similar to me, like `Typechecking With PropTypes` we use in reactJS

**Comment by kambleaa007** [comment]
no need to `height="x"`  in side tag, you can manage in.
```
Styled.InsideObject = styled.div<MyObject>`
  background: tomato;
  height: x;
`; 
```
then simple,
`<Styled.InsideObject>Inside</Styled.InsideObject>` will work

**Comment by zimmicz** [comment]
@kambleaa007 that's not the root problem of this. Imagine anything else instead of `height`, custom prop like `myCustomProp`. Using `Styled` object, Typescript won't complain you're sending `myCustomProp="10"` instead of `myCustomProp={10}`.

**Comment by orrybaram** [comment]
@zimmicz Hi, Im the author of that article and Im here cause I was having a separate issue. I think I have a fix for ya though!
Try this out:

```
const InsideObject = styled.div<MyObject>`
  background: tomato;
`;

export const Styled = {
  InsideObject
};
```

or

```
export const Styled = {
  InsideObject: styled.div<MyObject>`
  background: tomato;
`
};
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
