### ISSUE TITLE
msnodesql

### ISSUE THREAD

**Issue by KarlProkupek** [DefinitelyTyped/DefinitelyTyped#473]
Hi Boris,
please update the following lines in msnodesql.d.ts:
Callback of open was without type Information:

``` javascript
export function open(connectionString: string, callback: Openback): Connection;
interface Openback {
   (err: Error, con: Connection): void; 
}
```

Connection.queryRaw and Connection.query must not have an argument connectionString:

``` javascript
interface Connection {
   queryRaw(query: string): StreamEvents;
   queryRaw(query: string, callback: Callback): StreamEvents;
   queryRaw(query: string, params, callback: Callback): StreamEvents;

   query(query: string): StreamEvents;
   query(query: string, callback: Callback): StreamEvents;
   query(query: string, params, callback: Callback): StreamEvents;
...
```

As I am not (yet) familiar with sending patches it would be nice to include my changes.
Thank you.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
