### ISSUE TITLE
The children prop in react-native Pressable component should be optional

### ISSUE THREAD

**Issue by klazbaba** [DefinitelyTyped/DefinitelyTyped#47333]
The children prop in `@types/react-native` Pressable should be optional and not required. Because there are legitimate use cases where one might need something to click on without it wrapping anything. In a case like this, the TypeScript compiler raises an error, which shouldn't be the case.

Another thing observed is when a component is composed with Pressable, TypeScript seem to always expect that composed component to always have at least a child. So having something like `<ComposedComponent />` raises error.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
