### ISSUE TITLE
Incorrect component types in @types/mui-datatables

### ISSUE THREAD

**Issue by BohdanYavorskyi** [DefinitelyTyped/DefinitelyTyped#47376]
- [x] I tried using the `@types/mui-datatables` package and had problems.
- [x] I tried using the latest stable version of tsc. 

- Authors: @Favna , @ankithkonda , @hwatersiv , @souppower , @byrekt 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8340511f346a28abcdf4b0811550c1ca81ea20e5/types/mui-datatables/index.d.ts#L568

Getting TS error:
JSX element type 'TableToolbar' does not have any construct or call signatures.

When:
<MuiDataTable
      title=""
      data={[]}
      columns={columns}
      options={options}
      components={{
        TableToolbar: (props: MUIDataTableToolbar) =>
          (<TableToolbar {...props} />) as React.ReactNode,
      }}
    />

Solution:
Type of TableToolbar and other components must be as ComponentType (not Component) 
export const TableToolbar: React.ComponentType<MUIDataTableToolbar>;

**Comment by Favna** [comment]
Yeah you're right. This package has had some difficulties of getting merged because I'm the only one of the authors who seems to check their GitHub notifications. Therefore I think it would be a good idea if you create the pull request, then I can approve it and with the way the bot works it will be available on NPM much quicker than waiting for staff to approve it.

**Comment by V-Gutierrez** [comment]
@Favna could you assign it to me ? I'd like to work on it

**Comment by BohdanYavorskyi** [comment]
@Favna I added the PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47385.
Could you take a look at it?

**Comment by BohdanYavorskyi** [comment]
@Favna Could you merge the PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47385?
