### ISSUE TITLE
[@types/xrm] XrmEnum.ClientFormFactor has wrong enum values

### ISSUE THREAD

**Issue by wnbittle** [DefinitelyTyped/DefinitelyTyped#47462]
Authors: @derekfinlinson @6ix4our @markusmauch @daryllabar @clownwilleatme @scottdurow

The `XrmEnum.ClientFormFactor` values do not match the [documentation](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/client#getformfactor).

```typescript
    const enum ClientFormFactor {
        Unknown = 1,
        Desktop = 2,
        Tablet = 3,
        Phone = 4
    }
```

I didn't check other enums, but it might make sense to confirm others are correct at the same time.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
