### ISSUE TITLE
qunitjs: consider adding .load() definition

### ISSUE THREAD

**Issue by iwhp** [DefinitelyTyped/DefinitelyTyped#475]
There is a work around when using requirejs do load asynchronous tests.
For this, one has to use the "undocumented" feature 

```
QUnit.load(); 
```

Consider adding this to the d.ts:
    start(decrement?: number);
    load();                                                              // <----- ADDED

**Comment by galuszkak** [comment]
@iwhp `load()` was removed in 2.1.1 of QUnit, so I think this ticket should be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
