### ISSUE TITLE
[@types/braintree-web-drop-in] payPal buttonStyle property has invalid type

### ISSUE THREAD

**Issue by J-Gonzalez** [DefinitelyTyped/DefinitelyTyped#47511]
Link to thread on Braintree Repo: https://github.com/braintree/braintree-web-drop-in/issues/658

The type for buttonStyle on paypal on DefinitelyTyped  is defined as a string, but should be an object that allows the following properties: https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/customize-button/#button-styles

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6970a8fffa0743f0f5fc918e187fa37f0d2675df/types/braintree-web-drop-in/index.d.ts#L36

**Comment by Monteth** [comment]
Didn't you mean `paypalCreateOptions`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/braintree-web-drop-in/index.d.ts#L72 ?

**Comment by J-Gonzalez** [comment]
> Didn't you mean `paypalCreateOptions`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/braintree-web-drop-in/index.d.ts#L72 ?

Yea I did 🤦‍♂️. Your commit resolves it.

**Comment by iamricard** [comment]
This should be fixed now, see #49491 😄

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
