### ISSUE TITLE
 [@types/parse] File#save should contain FullOptions instead of SuccessFailureOptions

### ISSUE THREAD

**Issue by NiizumaEiji** [DefinitelyTyped/DefinitelyTyped#47544]
Missing property of FullOptions in File class. Without that authorization using masterKey is impossible.

authors: @dpoetzsch, @flavionegrao, @wesleygrimes, @agoldis , @AlexandreHetu, @dplewis, @yomybaby, @pocketcolin, @rdhelms

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
