### ISSUE TITLE
[@types/lodash] New version of types breaks type for _.throttle

### ISSUE THREAD

**Issue by kaiyoma** [DefinitelyTyped/DefinitelyTyped#47571]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar @aj-r @e-cloud @thorn0 @jtmthf @DomiR @WilliamChelman

If you do not mention the authors the issue will be ignored.

In version 4.14.157, this code works fine:

```
  const throttleValue = _.throttle(_.identity, interval);
  const throttledValue = throttleValue(value);
```

In the latest version (4.14.161), this no longer works and incorrect errors about the wrong number of arguments are being reported.

**Comment by igl** [comment]
Passing a async function to throttle will turn its return value to `| undefined`.

All our throttled async functions now fail `tsc` check with

`error TS2532: Object is possibly 'undefined'.`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
