### ISSUE TITLE
[@types/react] No type definition for SVGAnchorElement <a>

### ISSUE THREAD

**Issue by totony-misc** [DefinitelyTyped/DefinitelyTyped#47589]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon @zieka @dancerphil @dimitropoulos @disjukr @vhfmag @hellatan

Hey, it seems that the react types do not have the `<a>` element for SVG (https://developer.mozilla.org/en-US/docs/Web/SVG/Element/a).

`<a>` as HTMLElement and `<a>` as SVGElement have different properties, e.g. SVGElement can receive transform= as a property instead of as style.
I tried extending the definition and adding a SVGAnchorElement/Attributes, but it seems as though I can't define it since there already exists the HTML element with the same tag name.

I'm pretty novice in typescript so I wouldn't know how to fix this.

To reproduce:
```
import ReactDOM from 'react-dom';
import React from 'react';

ReactDom.render(<svg><a href='' transform="translate(0,0)"><text>a</text></a></svg>);
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
