### ISSUE TITLE
[@types/node] ServerResponse.socket/connection may be null

### ISSUE THREAD

**Issue by backbone87** [DefinitelyTyped/DefinitelyTyped#47627]
`ServerResponse.socket` & `ServerResponse.connection` may be null, but are declared to be always `Socket`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/http.d.ts#L157-L158

https://nodejs.org/docs/latest-v12.x/api/http.html#http_response_socket
> After response.end(), the property is nulled.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
