### ISSUE TITLE
[@types/react] react.ElementType infers type missing with Typescript's `dom` lib

### ISSUE THREAD

**Issue by zbinlin** [DefinitelyTyped/DefinitelyTyped#47633]
tsconfig.josn:
```json
{
    "compilerOptions": {
        "module": "es5",
        "lib": [
            "dom",
            "esnext"
        ],
        "strict": true,
        "jsx": "react"
    }
}
```

Examples: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdMAnmFnAKIA2WIWAdjAAqLLOgC8mKjAB0XHvyEiAPNjwyAEoICyAGQAKxMKiWbdc3gIB8l+rgh9U8ACbAAbgC4O3C4tbi4AOQurgE0cAD04RxQxFCewqyBZMFkAXDA6HwQ8GiowADmfMgARtxwMBDlIoHmCglYJtr6hsamOrVWlgHSDJFwAGLEpKr4st51IozVAMIAro4kHb4NenASyHxMlmt0cHtwAN67+ycA2gDS6XxwANZYTBAEcABSAMoAGtIAkgJQwA7AXBLVAAXU8b0+PxgfwBQPGAlQFxBcCwAA8YPwnOhVgB+OCXTx8LCuLBQY57AC+pzuDyeEO+v3+eTh8gRyIAPuTJGppNMSJAiQJ6ko9DYGMxEkt6qgAIxrOBzBYgKXKEYaJoGCBGRpmeEway2eyOODBGWeFV+OUSIJuUIRKIAeRuQA

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
