### ISSUE TITLE
[@types/mongo] `FilterQuery` not valid when querying for null or missing fields 

### ISSUE THREAD

**Issue by slamuu** [DefinitelyTyped/DefinitelyTyped#47686]
When querying for null or missing fields, e.g. `db.collection<{ field: string }>().find({ field: null })`, the criteria `null` is not a valid criteria even though documentation allows it (https://docs.mongodb.com/manual/tutorial/query-for-null-fields/#equality-filter)

I'm wondering if this case should be added to `mongodb.FilterQuery` type, via 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongodb/index.d.ts#L1554
```ts
export type FilterQuery<T> = {
    [P in keyof T]?: Condition<T[P]> : null;
} &
    RootQuerySelector<T>;
```

Authors:
@CaselIT @alanmarcell @dante-101 @mcortesi @EnricoPicci @AJCStriker @julien-c @daprahamian @denys-bushulyak @BastienAr @sindbach @geraldinelemeur @various89 @angela-1 @lirbank @hector7 @floric @erikc5000 @Manc @jloveridge @ranguna @HosseinAgha @albertossilva @peterblazejewicz @LinusU @taxilian @xamgore @avaly @HitkoDev @jtassin

**Comment by wyattjoh** [comment]
This issue is compounded when used with the `ignoreUndefined: true` option in the `MongoClient` constructor which will not include fields with values of undefined in the documents.

It's imperative to allow null in places where properties are undefined, ie:

```ts
interface User {
  deletedAt?: Date;
}

db.collection<User>("users").find({ deletedAt: null });
```

Would currently cause a type error. I could prepare a PR to address this if there's support for the change.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
