### ISSUE TITLE
[@types/ramda] Split definitions into separate files

### ISSUE THREAD

**Issue by wclr** [DefinitelyTyped/DefinitelyTyped#47695]
I think it is better to split single index into separate files
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/index.d.ts

It will make maintenance and contributions more comfortable.

**Comment by Nicholaiii** [comment]
@alperklc
What's the motivation for the re-exports in `es` folder, rather than using individual declaration files? It does seem quite unreasonable for a 2200 line index file.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
