### ISSUE TITLE
How to extend Express Request?

### ISSUE THREAD

**Issue by george-norris-salesforce** [DefinitelyTyped/DefinitelyTyped#47741]
Why is Typescript NOT extending the Request object? I'm beyond frustrated trying to get this to work..

Declare the type.. after installing the @types/Express package..

```
// global.d.ts

declare namespace Express {
  interface Request {
    user: string;
  }
}
```

```
(req, res) => {
  const user = req.user
}
```

`Property 'user' does not exist on type 'Request'`

WHY? WHY? WHY?

**Comment by joeflateau** [comment]
https://joeflateau.net/posts/extending-express-request-response-objects-in-typescript

**Comment by forivall** [comment]
The declaration needs to be in a `declare global` block.

Your `global.d.ts` should read:

```ts
declare global {
  namespace Express {
    interface Request {
      user: string;
    }
  }
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
