### ISSUE TITLE
Type for method updateLineItems() does not match name in shopify-buy

### ISSUE THREAD

**Issue by davidthrasher** [DefinitelyTyped/DefinitelyTyped#47742]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/464e13b9387252f7730db987ace1dc9076373232/types/shopify-buy/index.d.ts#L98

it would appear the method name is actually `updateLineitems()` 

Is there a reason this type is name `updateLineItem`?

**Comment by davidthrasher** [comment]
![Screen Shot 2020-09-17 at 4 17 26 PM](https://user-images.githubusercontent.com/25215475/93603587-35b7c980-f992-11ea-82c6-3a80b0fcbbd4.png)
![Screen Shot 2020-09-17 at 4 17 10 PM](https://user-images.githubusercontent.com/25215475/93603596-381a2380-f992-11ea-8bc6-24fe64ca2cd6.png)

**Comment by EricSSartorius** [comment]
I can confirm this. Seeing the same thing.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
