### ISSUE TITLE
Should the SNS event not have a arn field?

### ISSUE THREAD

**Issue by natac13** [DefinitelyTyped/DefinitelyTyped#47745]
Should the sns event not have an arn field like sqs? https://www.serverless.com/framework/docs/providers/aws/events/sns/
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/665d71ffc3efb5d52f7e81c32ea546accc76e0ab/types/serverless/plugins/aws/provider/awsProvider.d.ts#L367

- [x] I tried using the `@types/serverless` package and had problems.

- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @hassankhan @fredericbarthelet @bryan-hunter @ThomasAribart

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
