### ISSUE TITLE
Add new JQuery definition "bind" with variable arguments for callback function

### ISSUE THREAD

**Issue by cchet** [DefinitelyTyped/DefinitelyTyped#4778]
I am currently giving TypeScript a try and trying to implement my first TypeScript with jqplot.
JQPlot provides an data point click event which gets applied like this:

```
$('#'+id).bind('jqplotDataClick', function (ev, seriesIndex, pointIndex, data) { ... }
```

The problem now is that the definitions do not allow the signature of the callback function.
Therefore I added the following to the jquery.d.ts.

```
    bind(eventType: string, handler: (eventObject: JQueryEventObject, ...params: any[]) => any): JQuery;
```

which as far as I understand allows any signature of the callback function.

Is this a missing definition or am I am I mistaking ?

**Comment by omeszar** [comment]
cchet, First let me say thanks.

I'm not sure if you are mistaken either, but I ran into the same problem. I added your interface. What I did differently is I added it to a separate file ("jquery.fix.d.ts") That way if I update the jquery.d.ts I won't override your fix. :)

I added this to the new file:
interface JQuery {
    bind(eventType: string, handler: (eventObject: JQueryEventObject, ...params: any[]) => any): JQuery;        
}

**Comment by vvakame** [comment]
@johnnyreilly ?

**Comment by johnnyreilly** [comment]
Hi,

I think this is probably something that should live in jqplot.d.ts (I assume there is one?)

Though I could be wrong. Could you outline which of the methods [here](http://api.jquery.com/bind/) you are attempting to add a typing for?

**Comment by omeszar** [comment]
For me, I am not using jqplot. Instead I am using flow. Since it appears to be used in more than one library, maybe it should be in Jquery.d.ts??

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
