### ISSUE TITLE
AWS Serverless !Ref? 

### ISSUE THREAD

**Issue by natac13** [DefinitelyTyped/DefinitelyTyped#47791]
- [x] I tried using the `@types/serverless` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bryan-hunter 

If you do not mention the authors the issue will be ignored.

How do we do the !Ref from `.yml` in the new `serverless.ts` file?
I tried with 
```js
lambda:
  onError: {
    Ref: 'AlertTopic'
  }
```
as per this [example](https://github.com/serverless/serverless/pull/7755#issuecomment-646307998) but Typescript says that it must be a string.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
