### ISSUE TITLE
[@types/yargs] Path forward to supporting version 16.0

### ISSUE THREAD

**Issue by NathanYocum** [DefinitelyTyped/DefinitelyTyped#47879]
Current version is listed as 15.0 -- the version being supported may have gotten a little lost while yargs was working on a TS migration and there were questions on whether this will be maintained -- https://github.com/yargs/yargs/issues/1586#issuecomment-690364421

- Authors: @poelstra @mizunashi-mana @pushplay @steffenvv @forivall @ExE-Boss @Aankhen 

### v15.1
- [x] onFinishCommand (PR #41374) (https://www.github.com/yargs/yargs/issues/1473)

### v15.2
- [ ] deprecateOption (PR #47867) (https://github.com/yargs/yargs/pull/1559)
- [ ] strictCommands (PR #46984) (https://github.com/yargs/yargs/pull/1540)

### v15.3
No changes needed from v15.0

### v15.4
- [x] deprecateCommand (#47884) (https://github.com/yargs/yargs/pull/1624)
- [x] example can take an array (PR #47885) (https://github.com/yargs/yargs/pull/1682)

### v16.0
- [ ] strictOptions (No PR yet) (https://github.com/yargs/yargs/pull/1738)

**Comment by NathanYocum** [comment]
Might be missing a few changes needed for 16.0 support since I was just going off of a cursory glance of the CHANGELOG.md in the yargs repo

**Comment by pushplay** [comment]
Thanks for the background.  Hacktoberfest is coming up and I like free workout t-shirts.  If no one else grabs this by then I'll get on it.

**Comment by forivall** [comment]
I just submitted #50717 - strictcommands has been added to our types, idk about deprecateOption right now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
