### ISSUE TITLE
[@types/mongoose] SchemaDefinition doesn't have generic

### ISSUE THREAD

**Issue by UncleVic** [DefinitelyTyped/DefinitelyTyped#47873]
Hi, there!

If I have interface describes my object, I can't typing mongoose.SchemaDefinition, because it doesn't have generic
SchemaTypeOpts<any> - doesn't work at all.

`  interface SchemaDefinition {
    [path: string]: SchemaTypeOpts<any> | Schema | SchemaType;
  }`

My solution has been tested on real project.

`  type SchemaDefinition<T = any> = {
    [P in keyof T]-?: SchemaTypeOpts<T[P]> | Schema | SchemaType;
  };
interface SchemaTypeOpts<T> {
    alias?: string;
    type?: any; // here have to be ANY, not T
...............`

`  class Schema<T = any> extends events.EventEmitter {
    /**
     * Schema constructor.
     * When nesting schemas, (children in the example above), always declare
     * the child schema first before passing it into its parent.
     * @event init Emitted after the schema is compiled into a Model.
     */
    constructor(definition?: SchemaDefinition<T>, options?: SchemaOptions); //here

    /** Adds key path / schema type pairs to this schema. */
    add(obj: SchemaDefinition<T>, prefix?: string): void; // and here`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
