### ISSUE TITLE
[styled-components] Discriminated union props types are broken when inheriting styles.

### ISSUE THREAD

**Issue by AngusMorton** [DefinitelyTyped/DefinitelyTyped#47963]
If you have a component that can be restyled and has a discriminated union type as a prop when you try to restyle it using the `styled(MyComponent)` syntax the types don't work as expected. You can work-around the issue by manually providing the type argument (e.g. `styled(MyComponent)<MyComponentProps>`) but it would be nice if this worked out-of-the-box.

Attached is a code sandbox, that is a bit contrived but highlights the issue we're having in our codebase: https://codesandbox.io/s/styled-components-discriminated-union-issue-1nswg

cc @Igorbek @Igmat @LavaToaster @Jessidhia @JKillian @eps1lon @flavordaaave

**Comment by forivall** [comment]
Seems like there was a fix, but it was reverted https://github.com/DefinitelyTyped/DefinitelyTyped/commit/47a8bdda3e4d08f9163db839d5593913d5cfd8ca

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
