### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by serradura** [DefinitelyTyped/DefinitelyTyped#4803]
I want to use [Sourcegraph](https://sourcegraph.com) for DefinitelyTyped code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/borisyankov/DefinitelyTyped. (It should only take 30 seconds.)

Thank you!

**Comment by vvakame** [comment]
I got `TypeScript is not supported. Sourcegraph's advanced code search, browsing, and usage examples are only available for supported languages. If the language was detected incorrectly, or to use only basic repository operations, you can proceed anyway.` is this right?

**Comment by serradura** [comment]
@vvakame when I saw this, I understood that only the basic resources/search will be enabled.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
