### ISSUE TITLE
Mongoose SchemaType does not expose property 'instance'

### ISSUE THREAD

**Issue by sovcik** [DefinitelyTyped/DefinitelyTyped#48094]
package: mongoose
version: 5.7.36

Mongoose SchemaType has property 'instance' available as per https://mongoosejs.com/docs/schematypes.html, but it is not available in TS definition.

Authors: @horiuchi, @lukasz-zak, @jendrikw, @ethanresnick, @vologab

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
