### ISSUE TITLE
Property url missing

### ISSUE THREAD

**Issue by maurobernal** [DefinitelyTyped/DefinitelyTyped#48110]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/68c01d7914e4c13a0859c238c8f8258cfd33b36f/types/kendo-ui/index.d.ts#L10479

interface WindowContent {
        template?: string;
        **url?: string;**
    }

**Comment by maurobernal** [comment]
Example:
 $("#dialog").kendoWindow({
            width: "850px", height: "550px", title: "This is demo",
            content: {
                **url:** "https://demo/page
            },
            modal: true,
            visible: true,
            iframe: false,
            open: adjustSize,
            position: {
                top: 50, 
                left: "20%"
            }
        }).data("kendoWindow");

**Comment by peterblazejewicz** [comment]
@maurobernal 
It seems Telerik/Progress code is authored on GitHub and probably just republished here.
I'd advise to repost on GitHub project issues:
https://github.com/telerik/kendo-ui-core/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
