### ISSUE TITLE
[twig] Argument of type '{}' is not assignable to parameter of type 'CompileOptions'.

### ISSUE THREAD

**Issue by williamdes** [DefinitelyTyped/DefinitelyTyped#48127]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/twig` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

  - Authors: @soywiz @enko @mtizziani @dmelcer9

Please support Twig.renderFile with options being an object and not a CompileOptions.

README: https://www.npmjs.com/package/twig#usage-without-express
Code upstream: https://github.com/twigjs/twig.js/blob/master/src/twig.exports.js#L166
Source: https://github.com/wdes/changelog/blob/c05f1a7a63c88844e5c11d214b735ecc7d0fd603/src/changelog.js#L90
```ts
           Twig.renderFile(
                templateFile,
                {
                    args: args,
                    versions: versions,
                    links: links,
                    owner: owner,
                    repo: repo,
                },
                (err, html) => {
                    if (err) {
                        reject(err);
                    } else {
                        resolve(html);
                    }
                }
            );
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
