### ISSUE TITLE
gapi.d.ts

### ISSUE THREAD

**Issue by shrutiaggarwal3012** [DefinitelyTyped/DefinitelyTyped#4813]
Shouldn't it use gapi.auth2 rather than gapi.auth in the gapi.d.ts ?

**Comment by VishaalK** [comment]
@grant @sgtfrankieboy This is an old issue but according to the `index.d.ts` it is still `gapi.auth`. I am dealing with this same issue and the Google documentation also references `auth2`. Wondering what I am doing wrong. Thanks.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
