### ISSUE TITLE
[@type/vis] 'Week'' Scale is missing in @type/vis(  version - 4.21)

### ISSUE THREAD

**Issue by niksonkjohn** [DefinitelyTyped/DefinitelyTyped#48131]
I'm using vis/type (version 4.21). We need a week scale to display our timeline. But the week scale is missing from the type file. See the below code from my local file: vis-timeline/declaration/index.d.ts.
**Local version:**
export type TimelineTimeAxisScaleType = 'millisecond' | 'second' | 'minute' | 'hour' |'weekday' | 'day' | 'month' | 'year';

But in GitHub page, I can see week scale (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vis/index.d.ts)

**Github version:**
export type TimelineTimeAxisScaleType = 'millisecond' | 'second' | 'minute' | 'hour' |  'weekday' | 'day' | '**week**' | 'month' | 'year';

Any idea on this issue?

**Comment by niksonkjohn** [comment]
Anyone facing similar issue?

**Comment by AlexTruba** [comment]
Hi @niksonkjohn. What exact version did you use? There many versions of @types/vis package for 4.21 vis package. Property **'week'** was introduced in 4.21.19 version. Did you try to install this or next version?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
