### ISSUE TITLE
default in bootstrap-datepicker

### ISSUE THREAD

**Issue by Franko09** [DefinitelyTyped/DefinitelyTyped#48184]
- Authors: @jablko 

If you do not mention the authors the issue will be ignored.

We do not have access to $.fn.datepicker.defaults. Can it be added?

**Comment by martin-badin** [comment]
@Franko09 Could you please provide the documentation?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
