### ISSUE TITLE
[@types/lodash] interface LodashConvertible gone after making ts3.1 the default

### ISSUE THREAD

**Issue by mirkode** [DefinitelyTyped/DefinitelyTyped#48181]
Hey folks,

in commit [dbc59a8](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/dbc59a84fbc25c5c563909771eea0bfd69fb558f#diff-9cb49553ba96e91e0d447ea36a8d91b2) I can see that, when using ts3.1 as the default the lines

```javascript
interface LodashConvertible {
    convert(options: lodash.ConvertOptions): (...args: any[]) => any;
}
```
where removed from types/lodash/scripts/generate-fp.ts (116-119).

Was there a specific reason for this?

Because since then the `fp.map.convert({ cap: false })` is throwing the `Property 'convert' does not exist on type 'LodashMap'.` type error.
When reintroducing the `extends LodashConvertible` it can be used as normal.

Thanks!

- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @sandersn 

If you do not mention the authors the issue will be ignored.

**Comment by mirkode** [comment]
Hey @sandersn,
I also created a small (not tested and linted yet) [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48183) with some reverted changes

**Comment by sandersn** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44877 added this feature in May, but failed to add it to ts3.1 (it is NOT obvious that it needed to happen there too) When I moved ts3.1 up to the root at the end of August, I overwrote this new feature.

You just need to re-do #44877.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
