### ISSUE TITLE
Property 'expiredAt' does not exist on type 'VerifyErrors'.

### ISSUE THREAD

**Issue by Maligosus** [DefinitelyTyped/DefinitelyTyped#48251]
- [ ] I tried using the `@types/jsonwebtoken` package and had problems.
- Authors: @Maxime LUCE <https://github.com/SomaticIT>,                Daniel Heim <https://github.com/danielheim>,                Brice BERNARD <https://github.com/brikou>,Veli-Pekka Kestilä <https://github.com/vpk>,Daniel Parker<https://github.com/rlgod>,                Kjell Dießel <https://github.com/kettil>,                 Robert Gajda <https://github.com/RunAge>,                 Nico Flaig <https://github.com/nflaig>,                Linus Unnebäck <https://github.com/LinusU>                Ivan Sieder <https://github.com/ivansieder>                Piotr Błażejewicz <https://github.com/peterblazejewicz>

If you do not mention the authors the issue will be ignored.
Property 'expiredAt' does not exist on type 'VerifyErrors'.
Property 'expiredAt' does not exist on type 'NotBeforeError'.
err.expiredAt

jwt.verify(token,this.signature,(err:
//                                                  TokenExpiredError| 
//                                                  NotBeforeError| 
                                                     JsonWebTokenError|null, decode:any|undefined)=>{
 if (err)
//         {
//                   callback(err,{ 
//                                status: HttpStatus.FORBIDDEN, 
//                                 connected:true,
                                    message: "TokenIsExpired", expiredAt: err.expiredAt }) } 
else 
//         callback(null,decode); });

**Comment by emmanuelgautier** [comment]
This property seems not to exist for the type you mentioned: example for NotBeforeError https://github.com/auth0/node-jsonwebtoken/blob/master/lib/NotBeforeError.js

You should test which error is it before using the expiredAt property

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
