### ISSUE TITLE
A PR introduced a bug in Mongodb typings 

### ISSUE THREAD

**Issue by Xstoudi** [DefinitelyTyped/DefinitelyTyped#48300]
- [x] I tried using the `@types/mongodb` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT, @alanmarcell, @bitjson, @Dante-101, @mcortesi 

I also mention people that introduced the bug as a side effect of their PR : @liorcode and @Celend 

DefinitelyTyped/DefinitelyTyped@6a3556a1bc18bc2650612009011e5f0df4533125 introduced a bug when we explicitly type options with: 
`const options: FindOneOptions<T> = {}` and call `collection.findOne<T>({}, options)`

The bug reproduction is available [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYQgGzQUwMY2BAOwBo4AxYNGTKARQFdqBPE8ggEwHkDMOw9CAznAC+cAGZQIIOAHIQhAOYQ2AIxkBuALAAoHWLoFc+AnAWYYqDDn4EAPABUAfAAoAlAC4U6LEcIPHiDpwcFDmdFAmCKIAhkKWPjb+WtrCOjoA9OlwvDZCYLECmGxwwARopZieBBBwYJIqWCA6sYyG4ga+JmKlbACM-s7dlNSe5MO0DFCM-q6B2sHYgvCLVp1wALym5vHWxgOuycGhMOEmKwnGAHTd7FyYgxRUUCRI5SDAMJ4ArCIHOqm6bSZbJ8YxCNg4NDRULFADuHwAFltuFBgNg4NF2CUCB9gNFygAvIqeaiSKDNAStdH6Qw2cQ9ABMAyGT1Gj2o9CYMzmCyWcHOu0IGy2Fm8grsTjch35fIgoMEbNu3ByYP8wteoA+3xE0uOpxlqxs1x6dwe4xIctyfxSaSBWRVgjgEOwUJhcHhMCRZhRaIxWJg0QA1pgTKUMVAFHQQCGYAISVAyRSqe1acZ6ewAMzM9lQNnjTlTfwW+UEAQAfkVnGVJYE3IQQRlpeWYrWmzMosNe0l1qOYQiBouhGNSvuLOoxatyQBOlKTzE0WwmDgABFogGeSU2J4BDBUQQFNKAG74hhVKMqahT203Pq2VcBlxIYBb2RUHcyEjHtCnuC9X56Rk7zXaJH03TwZDfGAPzgL8fz-YRXAAzMgIfZwnxfCDMHfT8T0qX8RBeOA3i1OAvhIOoIAAK3FTx0M8eD-20IA) on the TS playground.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
