### ISSUE TITLE
@types/convert-units Power kW unit as kM

### ISSUE THREAD

**Issue by WAGuerra** [DefinitelyTyped/DefinitelyTyped#48317]
I tried using the `@types/convert-units` package and had problems.

The power unit for `kW` is wrong (currently it is `kM`) resulting in a wrong conversion.

**Comment by danmana** [comment]
@WAGuerra the code looks good, You should create a pull request with this commit, so it can get merged in DefinetlyTyped.

**Comment by WAGuerra** [comment]
> @WAGuerra the code looks good, You should create a pull request with this commit, so it can get merged in DefinetlyTyped.

Hi @danmana, I've already created a pull request. I am waiting to be merged.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
