### ISSUE TITLE
react-native-actionsheet maintainer review

### ISSUE THREAD

**Issue by virdesai** [DefinitelyTyped/DefinitelyTyped#48354]
Looking for a review for this super simple PR so I can remove a ts-expect-error annotation: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48275

- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ian-rudge

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
