### ISSUE TITLE
@types/d3 5.16.1 still depends on @types/d3-*

### ISSUE THREAD

**Issue by sinamoeini** [DefinitelyTyped/DefinitelyTyped#48414]
Hi @Methuselah96 

I saw that you just updated the @types/d3 package to reflect the version 2.0.0 of d3 components but `package.json` file of @types/d3 still depends on version 1 of all @types/d3-*. Therefore installing it still pulls from version 1

**Comment by Methuselah96** [comment]
Yes, that's intentional. `d3@5.16.1` still depends on version 1 (or 2 in some cases) of the d3 modules. It's not until `d3@6.0.0` that they should point to version 2 of the packages. I will be releasing `@types/d3@6.0.0` once I'm finished updating all the d3 module packages to version 2. See [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/38939#issuecomment-696772770) for more details.
