### ISSUE TITLE
[react]: useState should use optional param instead of overload

### ISSUE THREAD

**Issue by stefanpl** [DefinitelyTyped/DefinitelyTyped#48586]
- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable versions: `typescript v. 4.0.3`, `types/react v. 16.9.51`
- [x] I know what the problem is, so going to SO would not help.

Hello @johnnyreilly, @bbenezech, @ericanderson (sorry, no clue whom to notify, the issue template said I should notify people, but the authors list in the index.d.ts. is pretty darn long).

According to my understanding, this is perfectly valid code: 
```typescript
const [name, setName] = useState<string>(undefined);
```
But it fails with ` "strict": true,`, since typescript will complain about undefined being not a valid string value.

I think the problem is with the "convenience overload", as it's called in the definition file, for `useState`. If I understand [the TS manual](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#use-optional-parameters) correctly at this point, an optional parameter instead of an overload would solve the problem.

I might try to make a PR for this myself eventually, but since I couldn't come up with the correct solution right away I created this ticket so it does not get forgotten.

**Comment by NotWoods** [comment]
Hi @stefanpl, 

In this case Typescript's `strictNullChecks` flag is in effect (under `strict`) and is using correct behaviour. Here's a quick sample to demonstrate:

```tsx
function MyComponent() {
  const [name, setName] = useState<string>(undefined)

  return (
    <div>
      <span>Name is {name.length} long</span>
      <button onClick={() => setName("Jane")}>Change name</button>
    </div>
  );
}
```

Here, even if the TypeScript code compiled, there would be an error when you run it:

```
Cannot get `.length` of undefined
```

Until the button is clicked, `name` is set to `undefined` (as its the default state in this example). However, `name.length` throws as a result. For this reason, you shouldn't be able to pass in `undefined` to `useState<string>`, even if there were no parameters.

The best solution is to update your code to use `useState<string | undefined>(undefined)`. This way TypeScript will know your state can sometimes be undefined.

**Comment by stefanpl** [comment]
Hi @NotWoods , thanks for your reply.

Let me try to rephrase what I'm after here:

This is perfectly valid code (assuming TS `strict`):

```typescript
const [myString] = useState<string>();
```

The compiler will rightly type `myString` to `string | undefined`. Yes, I would have to handle the `undefined` in my UI code, but since TS knows it can be undefined, it will stop me from using it without checking first.

I would expect the same behavior when passing a variable that is undefined, or `string | undefined`, as an initial argument:

```typescript
const initialState: string | undefined = fnThatMightReturnString(dependingOnWhatever);
const [myString] = useState<string>(initialState);
```

I'd expect `myString` to be `string | undefined` here, but am presented with a TS error. Why should this be invalid? To react itself, passing `undefined` is totally okay (see ex. 1), and as long as the `myString` is correctly typed, I do not see any problem with this code.
Or am I missing something here?

**Comment by JaffParker** [comment]
@stefanpl I just tried to make the change you're requesting, but it'll create issues in strict setups. Here's what I tried:

```ts
/**
     * Returns a stateful value, and a function to update it.
     *
     * @version 16.8.0
     * @see https://reactjs.org/docs/hooks-reference.html#usestate
     */
    function useState<S = undefined>(initialState?: S | (() => S)): [S | undefined, Dispatch<SetStateAction<S | undefined>>];
```

But now Typescript tells me every time I try to use the value that it might be undefined, since it's a possible type. The overload actually is the only thing that allows you to provide a default value and not worry about checking for undefined.

So your best solution is what @NotWoods said: just give your state type `string | undefined`.

**Comment by Retsam** [comment]
I'm pretty sure the overloads *could* be written to allow this, e.g. this is a slightly simplified version:

```ts
function useState<T>(t: T): T;
function useState<T>(): T | undefined;
function useState<T>(t: T | undefined): T | undefined;
```

Due to overload precedence, if you did `useState("foo")` or `useState<string>("foo")`, it'll infer without `undefined`, but either `useState<string>()` or `useState<string>(undefined)`will infer with the `undefined`.

---

... but I don't think I'd make this change here, anyway.  It's a bit surprising behavior for `useState<string>(stringOrUndefined)` to work, and it might actually be masking a mistake if the developer didn't actually intend for `undefined` to be included in the initial value.

And I'm not sure what the benefit would be.  For the original example, ` useState<string>(undefined);`, you can just do `useState<string>()` and for the later example of:

```ts
const initialState: string | undefined = fnThatMightReturnString(dependingOnWhatever);
const [myString] = useState<string>(initialState);
```
Why not just remove the annotation and do: `useState(initialState)`.

The existing convenience overload is useful, it's nice to do `useState<string>()` as shorthand for `useState<string | undefined>()`, but this new version seems longer than the alternatives.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by moltar** [comment]
Having to explicitly set `undefined` also conflicts with [no-useless-undefined](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-useless-undefined.md#checkarguments) ESLint rule.

Calling `setName()` produces an error:

> Expected 1 arguments, but got 0

While calling `setName(undefined)` produces an ESLint error.

I realize that I could simply turn off the rule, but I don't think requiring an explicit `undefined` is the correct behaviour, because React (JS) supports `setName()`.
