### ISSUE TITLE
Does not include avgTypingSpeed

### ISSUE THREAD

**Issue by Nguyephi** [DefinitelyTyped/DefinitelyTyped#48594]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3d11f4cc510ee41fca5e25d557e2bc6a830d74c3/types/react-typist/index.d.ts#L38-L48

**Comment by bearfromtheabyss** [comment]
Can I work on this @Nguyephi ? 
I'm new to the codebase, but want to give it a try

**Comment by Nguyephi** [comment]
It looks like a simple fix to add. Would be great to have. I ended up adding a custom declaration file in my repo to solve this in my own app.

**Comment by shawnkoon** [comment]
Hi @Nguyephi thanks for the suggestion!

However, according to the [official doc](https://github.com/jstejada/react-typist#typist-props) and [javascript property](https://github.com/jstejada/react-typist/blob/master/src/Typist.jsx#L13-L24) of the `react-typist`, it seems like `avgTypingSpeed` is not being referenced :+1:

Please let me know if I am missing something, otherwise, happy coding :)
