### ISSUE TITLE
this.async() on validate not found

### ISSUE THREAD

**Issue by alvinadet** [DefinitelyTyped/DefinitelyTyped#48637]
` prompt([
        {
          type: 'input',
          name: 'range',
          message: 'Range',
          default: 1,
          validate(range) {
            const done = **this.async()** 

            if (Number(range) < 1) {
              // Pass the return value in the done callback
              done('Opps, the minimum number input is 1');
              return;
            }
            // Pass the return value in the done callback
            done(null, true);
          },
        },
      ])`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
