### ISSUE TITLE
[@types/node/v12] add WebAssembly global

### ISSUE THREAD

**Issue by rusnasonov** [DefinitelyTyped/DefinitelyTyped#48648]
This types required for VSCode Extensions developers. VSCode use node 12. Types [lives here](https://github.com/microsoft/TypeScript/blob/35111231f7ee48ce0ca08e4c1076d94b7125865b/lib/lib.dom.d.ts#L19006-L19013)

https://github.com/microsoft/vscode/issues/65559

 @Microsoft @DefinitelyTyped @jkomyno @a-tarasyuk @alvis @r3nya @btoueg @brunoscheufler @smac89 @touffy @DeividasBakanas @eyqs @Flarna @Hannes-Magnusson-CK @KSXGitHub @hoo29 @kjin @ajafff @islishude @mwiktorczyk @mohsen1 @n-e @octo-sniffle @galkin @parambirs @eps1lon @SimonSchick @ThomasdenH @WilcoBakker @wwwy3y3 @ZaneHannanAU @samuela @kuehlein @j-oliveras @bhongy @chyzwar @trivikr @nguymin4 @yoursunny @qwelias @ExE-Boss @JasonHK

**Comment by gilescope** [comment]
This would be _awesome_! Let's make it happen and unleash much faster vscode extensions.

**Comment by rusnasonov** [comment]
I'm not sure I have enough skills to add this things in right way =(

**Comment by ExE-Boss** [comment]
This most likely depends on: <https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/826>.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
