### ISSUE TITLE
Compatibility issue with @agm/core

### ISSUE THREAD

**Issue by Shawesh** [DefinitelyTyped/DefinitelyTyped#48675]
Looks like there is issues with the latest builds (3.40.0 AND 3.39.14) working with @agm/core.

![image](https://user-images.githubusercontent.com/23103359/95666957-38d74d00-0b2d-11eb-9be8-be11cdd4c5ae.png)

Fix: Uninstall and install this version **npm i @types/googlemaps@3.39.13**

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
