### ISSUE TITLE
@types/twig are wrong

### ISSUE THREAD

**Issue by kalicki2k** [DefinitelyTyped/DefinitelyTyped#48715]
The type definition of renderFile are wrong. Could you please update the package.

**Comment by princefishthrower** [comment]
@kalick2k - do you have more specific info, a screenshot maybe? This may have to do with the twig types that I extended recently - though it looks like they've since been updated by twig maintainers themselves.

**Comment by kalicki2k** [comment]
sorry @princefishthrower, after further research the mistake was mine.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
