### ISSUE TITLE
@types/yup wrong inferType for yup.string().required()

### ISSUE THREAD

**Issue by nicgirault** [DefinitelyTyped/DefinitelyTyped#48746]
With @types/yup 0.29.8 I get the following typescript error:

```typescript
import * as yup from 'yup'

const schema = yup.string().required()

interface Model {
  property: yup.InferType<typeof schema>
}

export const something: Model = {
  property: 'value',
}
```

`Type 'string' is not assignable to type 'Id<Partial<Pick<string, KeyOfUndefined<string>>> & Pick<string, never>>'`

![image](https://user-images.githubusercontent.com/551837/95875157-010d1700-0d72-11eb-806a-59b24e25ec57.png)

Am I doing something wrong?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
