### ISSUE TITLE
[@types/webpack] Deprecation for version 5

### ISSUE THREAD

**Issue by rajzik** [DefinitelyTyped/DefinitelyTyped#48803]
From version [webpack 5](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#typescript-typings), typings are no longer needed and should be deprecated. Can you please take a look?

- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo, @bumbleblym, @bcherny, @tommytroylin, @mohsen1, @jcreamer898, @alan-agius4, @jason0x43, @dennispg, @christophehurpeau, @ZSkycat, @johnnyreilly, @rwaskiewicz, @kuehlein, @rubenspgcavalcante, @andersk, @ofhouse, @danielthank, @sasurau4, @dionshihk, @peterblazejewicz

**Comment by ofhouse** [comment]
Thanks for raising the issue,

the Webpack 5 is [announcement](https://webpack.js.org/blog/2020-10-10-webpack-5-release/) is 5 days old so the vast majority of developers is still using Webpack 4 I guess. 😅
Because Webpack is a widely used package in the JavaScript community I would wait **at least a year** until we deprecate the the typings for Webpack 4 to give everyone enough time to do the upgrade.

As far as I understand Webpack 4 is not officially deprecated by the announcement of Webpack 5, and the webpack-4 branch is still pretty active and receives maintenance commits: https://github.com/webpack/webpack/tree/webpack-4

But we already started months ago to reject pull requests that contain typings for Webpack 5 and in the future we will only accept pull requests that contain typings for Webpack 4.

So give us and the community a bit of time to adopt the new release and then we can safely depreciate the typings here.

**Comment by rajzik** [comment]
@ofhouse I was mostly thinking that it is possible to differentiate between versions and deprecate only types for webpack 5 not for 4. But thanks for feedback.

**Comment by ofhouse** [comment]
Unfortunately the only way to deprecate a `@types` package is to delete it from repository.

Which would mean nobody could send in pull requests for this package, to fix or add typings for Webpack 4.

I hope that this does not confuse so many people, because we will only publish `4.x.x` versions from this types package.

So when you accedentially run `npm i --save-dev webpack @types/webpack` and look in the package.json you can see a major version discrepancy between the two packages.

**Comment by rajzik** [comment]
Ok cool So I Guess I can close the issue.

**Comment by dl748** [comment]
Note: you are also deprecating by VERSION.

You don't JUST delete the typings, you apply a version to it as well.
```
npm run not-needed -- typingsPackageName asOfVersion [libraryName]
# to which i ran
npm run not-needed -- webpack 5.0.0
```
