### ISSUE TITLE
[@types/terser-webpack-plugin] Support for webpack 5 

### ISSUE THREAD

**Issue by rajzik** [DefinitelyTyped/DefinitelyTyped#48806]
@types/terser-webpack-plugin doesn't support webpack 5 types which are now generated by webpack itself.

```
node_modules/@types/terser-webpack-plugin/index.d.ts:7:10 - error TS2305: Module '"../../webpack/types"' has no exported member 'Plugin'.

7 import { Plugin } from 'webpack';
           ~~~~~~
```

- [x] I tried using the `@types/terser-webpack-plugin` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Danscho, @peterblazejewicz

**Comment by Danscho** [comment]
@peterblazejewicz already created a pull request.
Please see: #48794.
This should resolve your issue.

**Comment by isellsoap** [comment]
I have another error message, when using terser-webpack-plugin 5.0.0 with webpack 5:

```
Type 'TerserPlugin' is not assignable to type '"..." | WebpackPluginInstance | ((this: Compiler, compiler: Compiler) => void)'.
  Type 'TerserPlugin' is not assignable to type '(this: Compiler, compiler: Compiler) => void'.
    Type 'TerserPlugin' provides no match for the signature '(this: Compiler, compiler: Compiler): void'.ts(2322)
```

Anyone else having this issue?

**Comment by jasonwilliams** [comment]
I still get this error with:
```json
"@types/terser-webpack-plugin": "^5.0.1",
"terser-webpack-plugin": "^5.0.3"
```

**Comment by buschtoens** [comment]
From what I can tell the issue is that the latest version of `@types/terser-webpack-plugin`, even after  #48794, still specifies `@types/webpack@*` as dependency, which resolves to `wepack@4.41.21`. It seems that this dependency is somehow added implicitly by @DefinitelyTyped, as I can't find it in the [`package.json`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ed541cd6d5f5e12bf6447163a1d53c767ae3cd87/types/terser-webpack-plugin/package.json). Do we maybe have to add `webpack@5` as a dependency to prevent this?

**Comment by rajzik** [comment]
@buschtoens 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48857
there was same issue with webpack 5.

**Comment by echochens** [comment]
Have any guys solved the problem？
