### ISSUE TITLE
No interface EditorConfig exported?

### ISSUE THREAD

**Issue by apappas1129** [DefinitelyTyped/DefinitelyTyped#48801]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/20f91236c9e2501370581a0201134b7e4dc145d3/types/ckeditor__ckeditor5-core/index.d.ts#L96

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
