### ISSUE TITLE
Smtp pool - how to set maxmessages to infinity 

### ISSUE THREAD

**Issue by vicky5989** [DefinitelyTyped/DefinitelyTyped#48835]
To send bulk emails,  nodemailer doc suggests to set maxmessages to infinity.. but in the types module,  maxmessages is of type number.  How to set infinity for maxmessages while using smtp pool.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
