### ISSUE TITLE
[@types/react] Extending IntrinsicElements with arbitrary attributes

### ISSUE THREAD

**Issue by danieldelcore** [DefinitelyTyped/DefinitelyTyped#48838]
I'm trying to arbitrarily extend the available attributes that can be passed into html elements, similar to how emotion enables a `css` prop through the use of a custom JSX pragma. Having the ability to pass attributes to html elements would enable me to hide some functionality away from the consumer and make some interesting optimisations. 

Is there a predefined way to enable this behaviour via the `IntrinsicElements` definition, something like this:

```ts
interface IntrinsicElements<CustomAttributes> {
  // HTML
  a: React.DetailedHTMLProps<React.AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement, CustomAttributes>;
  ...
}
```

Resulting in an API like this: 

```tsx
<button<{primary: boolean}> primary="true">Submit</button>
```

Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @DovydasNavickas @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa @pascaloliv @Hotell @franklixuefei @Jessidhia @saranshkataria @lukyth @eps1lon @zieka @dancerphil @dimitropoulos @disjukr @vhfmag @hellatan

**Comment by eps1lon** [comment]
https://react-typescript-cheatsheet.netlify.app/docs/advanced/types_react_api/#adding-non-standard-attributes should help.

Though I don't understand why you would add attributes that no browser understands. Either way, with module augmentation it should be possible.

**Comment by dimitropoulos** [comment]
My first gut reaction was "aww hellllll naw", but now that I took a moment to consider the utility of this I think it could be pretty cool.  Of course the default generic parameter would would change nothing for almost all users, but for those that need it this would be a far far far more ergonomic way to make these kinds of adjustments as compared to module augmentation.  Furthermore, module augmentation isn't _quite_ an appropriate solution because you would very likely only use these things here or there (rather than, say, for all `button`s or something).

I agree with @eps1lon that you should say a lot more about the use-case just so we're on the same page.  I haven't used emotion a _ton_, but I _thinkkk_ I understand why you want something like this and I see value in it.

If all HTMLElements are extendable in this way I can see a few different people it could help (including, people trying out new/unreleased browser APIs).

**Comment by eps1lon** [comment]
Just to be clear: There is already a way the extend existing elements using TypeScript APIs that are intended for this use case. We shouldn't add another API just because someone prefers it. There should be concrete use case that the existing API doesn't cover.

I don't think the actual use case would be `<button<{primary: boolean}> primary="true">Submit</button>` since that's kind of apparent what the type of `primary` is and that it is wrongly used here.

**Comment by dimitropoulos** [comment]
oh, neat.  I must just not understand.  how could you do this in an ad hoc fashion for a single `button` (but no others) using module augmentation (assuming that's the "already a way" you're referring to).

**Comment by danieldelcore** [comment]
Hey all, thanks so much for chiming in so far @eps1lon @dimitropoulos , much appreciated 💯 

To shed more light on my specific use-case, yes I'm aiming to achieve something similar to [transient props](https://medium.com/@probablyup/introducing-transient-props-f35fd5203e0c) / [props filtering](https://www.styletron.org/react#props-filtering) but via a custom jsx pragma. 

So i'm looking to approach it in a similar way, one idea was to [use non-standard attributes](https://react-typescript-cheatsheet.netlify.app/docs/advanced/types_react_api/#adding-non-standard-attributes) but define a generic type so i can tell typescript that these elements are non-standard but still to accept them since my library will be using them under the hood. They'll be filtered out before making it to the DOM. 

so something like this: `<button<{primary: boolean}> primary="true">Submit</button>`

or like this: `<button<'primary' | 'disabled'> primary="true" disabled="true">Submit</button>`

My challenge then is, how do/can I enhance the HTMLAttributes to accept a generic type? Is that possible in react's type definitions? (not suggesting we go to the enormous effort to add it if it's not possible just for me)

```typescript
import "react";

declare module "react" {
  interface ImgHTMLAttributes<T> extends HTMLAttributes<T> {
    loading?: "auto" | "eager" | "lazy";
  }
}
```

Alternatively, is there a way to accept any attribute starting with a `$`, this would work for me, but also appreciate that it isn't a `@types/react` problem 😄

**Comment by danieldelcore** [comment]
Going to close this for now! 

TS 4.1.* is introducing a new feature ([Template Literal Types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#template-literal-types)) that should allow us to achieve something similar to "transient props" like this:


```jsx
<button $primary={true} /> 
```

```ts
declare module 'react' {
    interface DOMAttributes<T> {
        [`${string}`]?: boolean;
    }
}

declare global {
    namespace JSX {
        interface IntrinsicAttributes {
            [`${string}`]?: boolean;
        }
    }
}
```

It also allows me to easily filter the props out before rendering the html element 😄  Close enough for me!

Thanks so much for your help everyone ❤️
