### ISSUE TITLE
Property organizationGeo missing within Xrm.OrganizationSettings

### ISSUE THREAD

**Issue by ddbd** [DefinitelyTyped/DefinitelyTyped#48849]
Within Dynamics 365 there is a setting within  Xrm.OrganizationSettings which gives you the geo location of the organisation
(EMEA for Europe)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
