### ISSUE TITLE
Wrong types for tokens in marked

### ISSUE THREAD

**Issue by LucasPaganini** [DefinitelyTyped/DefinitelyTyped#48891]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/27b68467fb38c599de8a7322023dd0da4c0e1f82/types/marked/index.d.ts#L315

From `marked@1.2.0`, the following tokens should be corrected:

```ts
interface List {
  type: 'list';
  raw: string;
  ordered: boolean;
  start: string | number;
  loose: boolean;
  items: ListItem[];
}

interface Text {
  type: 'text';
  raw: string;
  text: string;
  tokens?: Array<Text | Codespan>;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
