### ISSUE TITLE
@types/yup originalValue property in TestContext missing and test() overload with context argument is missing

### ISSUE THREAD

**Issue by alealpha2000** [DefinitelyTyped/DefinitelyTyped#48921]
@dhardtke @vtserman @MoretonBayRC @sseppola @YashdalfTheGray @vincentjames501 @robertbullen @sat0yu @deskoh @mauricedb @kalley @elias-garcia @iansan5653 @fjc0k

In the TestContext type there is a property called originalValue that is missing. Also the test function has a missing overload where the TestContext is passed as an argument instead of passed in the this parameter.
[Yup documentation](https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema)

**Comment by StudioSpindle** [comment]
Do you expect the originalValue to be in the testcontext? 

It seems to be more applicable for `mixed.transform((currentValue: any, originalValue: any) => any): Schema`.

Maybe it's an error in the docs?

**Comment by alealpha2000** [comment]
I'm pretty sure it's not an error in the docs. In `mixed.test` I casted `this `to `{originalValue:string}` and it worked.

**Comment by StudioSpindle** [comment]
Interesting.

I see it here indeed: https://github.com/jquense/yup/blob/master/src/util/createValidation.js#L21

There has been a change for this here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47069/files#diff-9a7135802f0759c6d56e408bd2fc0cf3c93d9dfe37580cfdd203568e3099963bR408

Via [PR-47069](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47069).

**Comment by StudioSpindle** [comment]
@abnersajr Do you need some help with the PR?

**Comment by abnersajr** [comment]
@StudioSpindle I'm gonna send the DT PR later today. I link here when I open this.

**Comment by abnersajr** [comment]
PR is opened @StudioSpindle and @alealpha2000 . Please let me know if any other change is required.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49524/files

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
