### ISSUE TITLE
dot-object object() should have different type for mods parameter

### ISSUE THREAD

**Issue by alexanderkogan** [DefinitelyTyped/DefinitelyTyped#48943]
- [x] I tried using the `@types/dot-object` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @nkovacic, @ricosandyca

**Description:** The documentation of [object](https://github.com/rhalff/dot-object#using-modifiers) shows, that mods is a dictionary of arrays like this:
```
var mods = {
  "doc.name": [_s.trim, _s.underscored],
};
```
Yet the type of the parameter is the same as in str, which is just `mods?: ModifierFunctionWrapper | Array<ModifierFunctionWrapper>`.

Thus the type should be something like: `{ [key: string]: ModifierFunctionWrapper | Array<ModifierFunctionWrapper> }`

### Example from dot-object documentation
```
var dot = require('dot-object');

var _s = require('underscore.string');

var row = {
  'nr': 200,
  'doc.name': '    My Document   '
};

var mods = {
  "doc.name": [_s.trim, _s.underscored],
};

dot.object(row, mods);

console.log(row);
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
