### ISSUE TITLE
@types/node-forge should have forge.pki.rsa.encrypt definition

### ISSUE THREAD

**Issue by Gu7z** [DefinitelyTyped/DefinitelyTyped#48955]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- Authors: @westy92 @flynetworks @Rafal2228 

When using node-forge with @types/node-forge, TS assumes that this function `forge.pki.rsa.encrypt()` does not exist but the function exists and can be used.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
