### ISSUE TITLE
[@types/mathjs] Shouldn't the string() method return only a string?

### ISSUE THREAD

**Issue by ekr3peeK** [DefinitelyTyped/DefinitelyTyped#48983]
- [x] I tried using the `@types/mathjs` package and had problems.
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @siavol  @andnp @bradbesserman @charlee @mark-wiemer 

Consider the following method in the type definitions:

```
/**
* Create a string or convert any object into a string. Elements of
* Arrays and Matrices are processed element wise.
* @param value A value to convert to a string
* @returns The created string
*/
string(
     value: MathType | null
): string | MathArray | Matrix;
```

Based on the name of the method, and the comment in the method, shouldn't this only return a `string`, or `string[]`? My typescript says that this can also be a `number` or a `number[]`.

**Comment by andnp** [comment]
I don't know the answer to this directly (I no longer actively use math.js), but I will point out that the documentation for this method states that an array or a matrix could be returned: [https://mathjs.org/docs/reference/functions/string.html](https://mathjs.org/docs/reference/functions/string.html
)
Perhaps what is intended by the documentation is actually `string | string[] | string[][]`?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
