### ISSUE TITLE
@types/ws addEventListener options are in wrong place

### ISSUE THREAD

**Issue by justinrush** [DefinitelyTyped/DefinitelyTyped#48994]
EventListenerOptions parameter is in the wrong place for "message", "close", and "error".  It is added as a parameter passed to the callback function instead of being added as the last parameter to addEventListener.  It is correct for "open" and "other".

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/97daa0e47d4ce592fca42fe7c32fb675a6fbae1f/types/ws/index.d.ts#L63

this:
```typescript
addEventListener(method: 'message', cb: (event: {
        data: any;
        type: string;
        target: WebSocket
    }, options?: WebSocket.EventListenerOptions) => void): void;
    addEventListener(method: 'close', cb: (event: {
        wasClean: boolean; code: number;
        reason: string; target: WebSocket
    }, options?: WebSocket.EventListenerOptions) => void): void;
    addEventListener(method: 'error', cb: (event: {
        error: any,
        message: any,
        type: string,
        target: WebSocket
    }, options?: WebSocket.EventListenerOptions) => void): void;
```

Should be this:
```typescript
addEventListener(method: 'message', cb: (event: {
        data: any;
        type: string;
        target: WebSocket
    }) => void, options?: WebSocket.EventListenerOptions): void;
    addEventListener(method: 'close', cb: (event: {
        wasClean: boolean; code: number;
        reason: string; target: WebSocket
    }) => void, options?: WebSocket.EventListenerOptions): void;
    addEventListener(method: 'error', cb: (event: {
        error: any,
        message: any,
        type: string,
        target: WebSocket
    }) => void, options?: WebSocket.EventListenerOptions): void;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
