### ISSUE TITLE
[datatables.net] responsive.recalc()

### ISSUE THREAD

**Issue by Serraniel** [DefinitelyTyped/DefinitelyTyped#49016]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/datatables.net` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Silver-Connection @omidkrad @pragmatrix @CNBoland 

Migrating our code to typescript we noticed an issue that `.responsive.recalc()` gives the following error, because it does not exists in the types. There also does not seem to be a separate package for the Responsive extension. But as this package also includes the `responsive` property for `Settings` interface I wanted to mention this here, too.

The error we get:
![image](https://user-images.githubusercontent.com/8461282/96859574-f2a1b800-1461-11eb-88f2-1c51fd083036.png)

See: https://datatables.net/reference/api/responsive.recalc()

**Comment by Serraniel** [comment]
Also https://datatables.net/reference/api/responsive.rebuild() seems to be missing as I just noticed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
