### ISSUE TITLE
@types/koa-redis using koa-session?

### ISSUE THREAD

**Issue by tonystaark** [DefinitelyTyped/DefinitelyTyped#49036]
May I know why koa redis lib using koa-generic session, but the @types/koa-redis using koa-session instead?

Which one should be using ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by kale1d0code** [comment]
Sounds like a mistake.
koa-redis was built to work with koa-generic-session
