### ISSUE TITLE
@types/node-forge cipher fixes

### ISSUE THREAD

**Issue by fcorneli** [DefinitelyTyped/DefinitelyTyped#49078]
To be able to compile my project, I had to add the following:
```typescript
declare module "node-forge" {
    namespace cipher {
        interface Mode {
            unpad: boolean;
            pad: boolean;
        }
        function createDecipher(algorithm: Algorithm, payload: util.ByteBuffer | Bytes | number[]): BlockCipher;
        function createCipher(algorithm: Algorithm, payload: util.ByteBuffer | Bytes | number[]): BlockCipher;
    }
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
