### ISSUE TITLE
snowflake-sdk types is missing some methods

### ISSUE THREAD

**Issue by orellabac** [DefinitelyTyped/DefinitelyTyped#49093]
The current types for the `snowflake-sdk` does is missing several methods for the `Statement` interface

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
