### ISSUE TITLE
[react-vis] Missing style parameter for Legend types

### ISSUE THREAD

**Issue by timtucker** [DefinitelyTyped/DefinitelyTyped#49113]
The types for most of the react-vis legends are missing the optional 'style" property:

Should just be a matter of adding:
style?: CSSProperties;

to the list of properties in the Typescript definition along with corresponding tests.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
