### ISSUE TITLE
Wrong interface StyleRules

### ISSUE THREAD

**Issue by Saiberbest** [DefinitelyTyped/DefinitelyTyped#49161]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8eb1ba30000d3e53bb3320427bd33d0d5e7945cc/types/radium/index.d.ts#L16

It should be:
```
interface StyleRules {
    [index: string]: React.CSSProperties | StyleRules;
}
```

**Comment by princefishthrower** [comment]
@Saiberbest - just made a pull request for this change here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49284

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
