### ISSUE TITLE
react.d.ts: onLoad/onError is missing from HTMLAttributes

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/DefinitelyTyped#4916]
This is needed to put an onload/onerror handler on an image.

**Comment by vvakame** [comment]
@hallarak please send a pull request. I'll review it.

**Comment by vsiao** [comment]
it's not documented, but `onReset` is also available. see bottom of https://github.com/facebook/react/issues/1718

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
