### ISSUE TITLE
chrome.sockets.AcceptEventArgs missing clientSocketId

### ISSUE THREAD

**Issue by fcorneli** [DefinitelyTyped/DefinitelyTyped#49181]
The `chrome.sockets.AcceptEventArgs` interface is missing the `clientSocketId:number` property.
This property is really required to unpause the corresponding socket.
Had to do the following within my code to make it work:
```typescript
function onAcceptCallback(acceptInfo: chrome.sockets.AcceptEventArgs, serverSocketId: number) {
    console.log("onAccept");
    if (acceptInfo.socketId !== serverSocketId) {
        return;
    }
    chrome.sockets.tcp.setPaused((acceptInfo as any).clientSocketId, false);
}
```

**Comment by fcorneli** [comment]
Work-around for this:
```typescript
declare global {
    namespace chrome {
        namespace sockets {
            interface AcceptEventArgs {
                clientSocketId: number;
            }
        }
    }
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
