### ISSUE TITLE
[@types/fabric] new Canvas variable 'uniformScaling' not defined

### ISSUE THREAD

**Issue by jromier** [DefinitelyTyped/DefinitelyTyped#49180]
From fabric 4.2.x version, the Canvas variable `uniScaleTransform` has been replaced by `uniformScaling`.

This change must be done in file fabric-impl.d.ts, line 1688.

Angular project using fabric cannot be compiled when using the new variable. Old variable is not working from fabric 4.2.x

- [x] I tried using the `@types/fabric` package v3.6.9 and had problems.
- Authors: @oklemencic @joewashear007 @mrand01 @bmartinson

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
