### ISSUE TITLE
[@types/pkijs] Certificate RelativeDistinguishedNames ObjectIdentifier

### ISSUE THREAD

**Issue by fcorneli** [DefinitelyTyped/DefinitelyTyped#49244]
According to the type definition, `ObjectIdentifier` should have a `valueBlock` property, while at runtime I simply get a string. Example code to demonstrate the issue:
```typescript
import Certificate from "pkijs/src/Certificate";
import * as asn1js from "asn1js";
import RelativeDistinguishedNames from "pkijs/src/RelativeDistinguishedNames";

let certData: Uint8Array = ...
let asn1Result = asn1js.fromBER(certData.buffer);
let certificate: Certificate = new Certificate({ schema: asn1Result.result });
for (let typeAndValue of certificate.subject.typesAndValues) {
    console.dir(typeAndValue.type); // type is a string instead of asn1js.ObjectIdentifier
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
