### ISSUE TITLE
webpack-virtual-modules not compatible with webpack 5

### ISSUE THREAD

**Issue by andyrooger** [DefinitelyTyped/DefinitelyTyped#49254]
- [x] I tried using the `@types/webpack-virtual-modules` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @AviVahl

`@types/webpack-virtual-modules` has a dependency on `@types/webpack` (webpack 4). `webpack-virtual-modules` now supports webpack 5 which holds its own typings now.

If I install `@types/webpack-virtual-modules` and `webpack@5` in the same project I get conflicts like the following

> node_modules/@types/webpack/index.d.ts(998,23): error TS2314: Generic type 'SyncWaterfallHook<T>' requires 1 type argument(s).
node_modules/@types/webpack/index.d.ts(999,22): error TS2314: Generic type 'SyncWaterfallHook<T>' requires 1 type argument(s).
node_modules/@types/webpack/index.d.ts(1000,28): error TS2314: Generic type 'AsyncSeriesWaterfallHook<T>' requires 1 type argument(s).
node_modules/@types/webpack/index.d.ts(1001,27): error TS2314: Generic type 'AsyncSeriesWaterfallHook<T>' requires 1 type argument(s).

As far as I can tell the typings for this package should work with either version of the webpack typings without issue, we just can't force `@types/webpack` to be installed.

**Comment by AviVahl** [comment]
Issue happens with many webpack plugin typings. The dependency on @types/webpack is automatically added by the publisher here I think. Not sure what's the best course of action.

There's the larger issue of webpack@5 now having built-in typings that are missing a lot of stuff already handled by @types/webpack. I'm guessing this would make deprecation (of @types/webpack) a hell.

**Comment by andyrooger** [comment]
Can we remove the automatic dependency by removing the import entirely? Then we could we stub out the bare minimum we need to be merged with whichever typings you choose to install?

e.g. rather than importing webpack can we use something like

```ts
declare module "webpack" {
    export interface Compiler { }
}
```

For now I'm using `types: []` in my tsconfig which is OK as a workaround until there's something else we can do.

**Comment by AviVahl** [comment]
I'm not sure each plugin implementing its own workarounds is the correct way forward.
There are several questions that come to mind:
- should `@types/webpack` be deprecated and removed? (since `webpack@5` contains built-in typings)
- there are three cases for plugins:
  - compatible with both `webpack@4` and `webpack@5` - harder to achieve in typings, as `@types/webpack` and new built-in typings diverge.
  - compatible only with `webpack@5` (usually via a breaking major) - are `@types/*` packages going to install `webpack: "*"` dep? can these coexist in DT with `@types/webpack` (for `webpack@4`)?
  - compatible only with `webpack@4` (breaks with the new webpack; usually abandoned plugins) - in the case of `@types/webpack` removal, what happens to `@types` of  plugins who did not upgrade to `webpack@5` yet?

Not sure what should be the DT approach for handling each of the above.

 +@sokra (webpack) +@DanielRosenwasser (typescript)

**Comment by AviVahl** [comment]
Btw next version of webpack-virtual-modules migrated to typescript: https://github.com/sysgears/webpack-virtual-modules/pull/72

So this specific plugin may end up have my built in .d.ts...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
