### ISSUE TITLE
[@types/oauth2-server] Inconsistencies between the official documentation and the types

### ISSUE THREAD

**Issue by thibauds** [DefinitelyTyped/DefinitelyTyped#49329]
I tried using the `@types/oauth2-server` package and had problems.

I wanted to implement the `getAuthorizationCode()` but the [documenation](https://oauth2-server.readthedocs.io/en/latest/model/spec.html#getauthorizationcode-authorizationcode-callback) states that `getAuthorizationCode` should return an object with a `code` property and the [type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/oauth2-server/index.d.ts#L410) states that the `AuhtorizationCode` interface has an `auhtorizationCode` property and not a `code` property.

Should we update the interface and rename the `auhtorizationCode` property to `code` or am I missing something?

@vangorra @cirick @d-fischer @rvitorsantos

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
