### ISSUE TITLE
Missing altKey modifier in Quill type

### ISSUE THREAD

**Issue by Eraldo** [DefinitelyTyped/DefinitelyTyped#49328]
According to quill's documentation: https://quilljs.com/docs/modules/keyboard/#key-bindings,
there are multiple key modifiers available (5 to be exact) and `altKey` is one of them.

However I get a compiler error because addBinding of QuillType (`this.quill.keyboard.addBinding`) does only support `shortKey`:
```ts
export interface Key {
    key: string;
    shortKey?: boolean;
}
```

This is what I am doing as a hacky workaround:
```ts
{key: 'q', altKey: true} as Key
```

This is where I ran into this: https://github.com/KillerCodeMonkey/ngx-quill/issues/1074

This is the quill line of source code in question:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/quill/index.d.ts#L24

I am not sure if there is a special reason for not including the other modifiers. 😊

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
