### ISSUE TITLE
[@types/node]

### ISSUE THREAD

**Issue by croraf** [DefinitelyTyped/DefinitelyTyped#49373]
```ts
const npm_process = child_process.spawn("npm", ["run", "create-groups"]);

npm_process.stdout.on('data', (data: Uint8Array) => {
  process.stdout.write(data.toString());
});
```

Can the @types/node be improved so that the type of `data` parameter is inferred here?

- [X ] I tried using the `@types/node` package and had problems.
- [X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jkomyno @a-tarasyuk @alvis @BrunoScheufler @eyqs @ajafff @samuela ...

**Comment by SimonSchick** [comment]
Streams are not generic types at this point (this is being worked on) but might take a long type due to ecosystem dependence.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
