### ISSUE TITLE
[node] Test failed (`no-outside-dependencies` lint rule)

### ISSUE THREAD

**Issue by Semigradsky** [DefinitelyTyped/DefinitelyTyped#49372]
@sandersn @rbuckton @ExE-Boss
```
> definitely-typed@0.0.3 test
> dtslint types "node"

testing from 3.2 to 3.4 in /home/dmitry/H/DefinitelyTyped/types/node/ts3.4
testing from 3.5 to 3.6 in /home/dmitry/H/DefinitelyTyped/types/node/ts3.6
testing from 3.7 to 4.2 in /home/dmitry/H/DefinitelyTyped/types/node
Error: /home/dmitry/H/DefinitelyTyped/node_modules/buffer/index.d.ts:1:1
ERROR: 1:1  no-outside-dependencies  File /home/dmitry/H/DefinitelyTyped/node_modules/buffer/index.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.  See: https://github.com/Microsoft/dtslint/blob/master/docs/no-outside-dependencies.md

    at /home/dmitry/H/DefinitelyTyped/node_modules/dtslint/bin/index.js:206:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/dmitry/H/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
```

I get this error on `master` branch.
The same in PR: #49264, #49461

**Comment by Semigradsky** [comment]
https://github.com/microsoft/dtslint/issues/315

**Comment by Semigradsky** [comment]
Was "fixed" by setting `"no-outside-dependencies": false,` to `tslint.json`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
