### ISSUE TITLE
Definition for angular-ui-grid

### ISSUE THREAD

**Issue by GeertVL** [DefinitelyTyped/DefinitelyTyped#4937]
Do we need to make a different definition for ui-grid while it replaces ng-grid for angular or can we update the current of ng-grid?

DefinitelyTyped/ng-grid/ng-grid.d.ts

**Comment by ofirgeller** [comment]
Please create a new one. Many people are still using the "old" ng-grid and since the new ui-grid is a rewrite that breaks the API in many ways and even has a new name to make sure users know that the definitions should also have a new name.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
