### ISSUE TITLE
@types/redux-form InjectedFormProps 

### ISSUE THREAD

**Issue by bpuns** [DefinitelyTyped/DefinitelyTyped#49450]
The original type definition would cause the component to fail to get props internally

```
export interface InjectedFormProps<FormData = {}, P = {}, ErrorType = string> {
    ......
}
```
I'll change it to the bottom. It works
```
export type InjectedFormProps<FormData = {}, P = {}, ErrorType = string> = {
    ......
} & P
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
