### ISSUE TITLE
[@types/amap-js-sdk] Tip is missing several fields

### ISSUE THREAD

**Issue by downeyfe** [DefinitelyTyped/DefinitelyTyped#49480]
The [Tip interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/amap-js-sdk/index.d.ts#L1237) is out of date and missing several fields that the real API produces.

I believe it should be something like:
```
interface Tip {
    name: string;
    district: string;
    adcode: string;
    address: string;
    city: any[]; // I couldn't find any result that had this populated, not sure what type it should be
    id: string;
    location: {
        Q: number;
        R: number;
        lat: number;
        lng: number;
    }
    typecode: string;
}
```

I'm happy to make the changes myself if people agree with them.

Authors: @agasbzj

**Comment by agasbzj** [comment]
Sorry about seeing this late and I really don't have time to update this recently. I think everyone will be happy to have you doing this. Thanks.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
