### ISSUE TITLE
[@types/babel-plugin-macros] In interface MacroParams the config property is missing.

### ISSUE THREAD

**Issue by hopefullToo** [DefinitelyTyped/DefinitelyTyped#49508]
@coffee-cup  In interface MacroParams the config property is missing. Should I make a pull request to change it or are there reasons for this ?

Authors: @billykwok , @coffee-cup , @ifiokjr

Regards 
Bernd

**Comment by coffee-cup** [comment]
I don't believe there is a reason it is missing. A PR would be great!

**Comment by hopefullToo** [comment]
@ coffee-cup Dear Jake, unfortunately I don't have access to my fork for DefinitelyTyped.git at the moment

Maybe it's easier if you add the one-liner -> config ?: {[key: string]: any};

_What I did locally:_
1. Property config added
interface MacroParams {
         references: {default: Babel.NodePath []} & References;
         state: Babel.PluginPass;
         babel: typeof Babel;
         **config ?: {[key: string]: any};**
     }

2. In the test babel-plugin-macros-tests.ts added:
if (config) {
             config.xyz = 7;
   }

Regards
Bernd

**Comment by hopefullToo** [comment]
@coffee-cup Dear Jake, 
In the end, I (hopefully) managed to get off my first PR.
Unfortunately I had problems calling the test packages. I couldn't install the dependencies.
Please refer to the notes in the PR.

Thank you
Bernd

**Comment by coffee-cup** [comment]
Hi @hopefullToo,
Sorry I missed the above comments.

I see you managed to create a PR and get it merged! Thanks for making it 😄

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
