### ISSUE TITLE
[@types/yup] property `options.index` missing in TestContext

### ISSUE THREAD

**Issue by StudioSpindle** [DefinitelyTyped/DefinitelyTyped#49518]
@dhardtke @vtserman @MoretonBayRC @sseppola @YashdalfTheGray @vincentjames501 @robertbullen @sat0yu @deskoh @mauricedb @kalley @elias-garcia @iansan5653 @fjc0k

Might be I'm missing something or doing something wrong.

But Typescript gives an error when trying to access `this.options.index`. Even though it _does_ exist in a custom test method:

```ts
const schema = yup.object().shape({
  people: yup.array().of(
    yup.object().shape({
      name: yup.string().test({
        name: "thing",
        message: "thing",
        test() {
          // Property 'index' does not exist on type 'ValidateOptions<object>'.
          const { index } = this.options;

          return true;
        }
      })
    })
  )
});
```

Should I define a type somewhere, or is it missing from the DT type definintion?

Working code example: https://stackblitz.com/edit/typescript-wqvlvc

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by darkdiesel** [comment]
2024 still have an issue
