### ISSUE TITLE
[@types/chart.js] Missing Chart.defaults.global.defaultColor

### ISSUE THREAD

**Issue by cdalexndr** [DefinitelyTyped/DefinitelyTyped#49573]
Property [Chart.defaults.global.defaultColor](https://www.chartjs.org/docs/latest/general/colors.html) is missing.

- [x] I tried using the `@types/chart.js` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @anuti, @FabienLavocat,@KentarouTakeda,@larrybahr,@mernen,@josefpaij,@danmana,@guillaume-ro-fr,@archy-bold,@braincore,@frabnt,@alexdor,@mahnuh,@Conrad777,@adripanico,@wertzui,@lekoaf,@ElianCordoba,@indigolain,@ricardo-mello,@rnicholus,@mrjack88,@canoceto,@nobu222,@Marcoru97,@tonybadguy,@Ilmarinen100,@IVIosi

**Comment by danmana** [comment]
Closed by #49585

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
