### ISSUE TITLE
[google-map-react] Wrong type definitions for google-map-react

### ISSUE THREAD

**Issue by jorissteyn** [DefinitelyTyped/DefinitelyTyped#49599]
The type definitions for google-map-react were updated in #47326, but it's not compatible with google-map-react 2.1 as advertised.

I'm unable to pinpoint the exact problem, but this is what I'm doing using google-map-react 2.1.9 and @types/google-map-react 2.1.0:

```
import GoogleMapReact from 'google-map-react';
```

Compiles with error:

```
  node_modules/@types/google-map-react/index.d.ts:213:1
    213 export = googleMapReact;
        ~~~~~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

Also, the types don't seem to export a symbol GoogleMapReact, only googleMapReact. I've temporarily worked around the problem by not including the type definitions and doing:

```
declare type GoogleMapReact = React.Component<any>;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
