### ISSUE TITLE
[@types/mongodb] collection.estimatedDocumentCount signature is invalid

### ISSUE THREAD

**Issue by gempain** [DefinitelyTyped/DefinitelyTyped#49601]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT @alanmarcell @101 @mcortesi @EnricoPicci @AJCStriker @c @daprahamian @bushulyak @BastienAr @sindbach @geraldinelemeur @various89 @1 @hector7 @floric @erikc5000 @Manc @jloveridge @ranguna @HosseinAgha @albertossilva @peterblazejewicz @LinusU @taxilian @xamgore @avaly @HitkoDev @Celend @jtassin @addaleax

The official [docs](https://docs.mongodb.com/manual/reference/method/db.collection.estimatedDocumentCount/) mention that:

> `db.collection.estimatedDocumentCount()` does not take a query filter and instead uses metadata to return the count for a collection.

Correct me if I'm wrong, but I think the signature should only take the options. Using query filters with this method will lead to incorrect results:

```
await collection.insertOne({
  name: 'foo',
  children: [
    { name: 'bar' },
  ],
});

const query = {
  name: 'huh',
};

console.log('estimatedCount', await collection.estimatedDocumentCount(query));
console.log('count', await collection.countDocuments(query));
```

will print

```
estimatedCount 1
count 0
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
