### ISSUE TITLE
@types/styled-components memoization don't pass it's props type 

### ISSUE THREAD

**Issue by beqramo** [DefinitelyTyped/DefinitelyTyped#49692]
Hi, I want to create  styled component  like so
```tsx
type TitlePropsType = {
   fontSize:number
}
const H1 = styled.h1<TitlePropsType>`
  font-size:${({fontSize}) => fontSize}px;
`;
```

and I want to memoize it like so:
```tsx
type TitlePropsType = {
   fontSize:number
}
const H1 = React.memo(styled.h1<TitlePropsType>`
  font-size:${({fontSize}) => fontSize}px;
`);
```
and when I use it, it doesn't show me its props that should be passed and shows me this: 
![image](https://user-images.githubusercontent.com/40486471/97280572-e3ea4500-1855-11eb-9c91-c32cf65af69e.png)

without the memo, everything works as expected.
where is the problem can you help me?
thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
