### ISSUE TITLE
[@types/echarts] Update to color type for options/text-style.d.ts 

### ISSUE THREAD

**Issue by chickennuggs9999** [DefinitelyTyped/DefinitelyTyped#49738]
I am using echarts and want to style the axis labels for my chart to be of different colors based on the axis label's string value or index. Is it possible to update the type definition for color in the BaseTextStyle from `color?: string;` to `color?: string | ((value: string, index: number) => string);`? 

Just like in the example here https://echarts.apache.org/en/option.html#yAxis.axisLabel.color.

Or is there a better workaround? Any help is appreciated!

- Authors: @xieisabug @AntiMoron @liveangela @Ovilia @iRON5 @bilalucar @tmtron @dwhitney @ruixuel @robert-wettstaedt @trajnisz @Ky6uk

**Comment by SteppingRazor** [comment]
Try to use version 4.9.2 of the package. The fix for this is included with this package version.

**Comment by chickennuggs9999** [comment]
> Try to use version 4.9.2 of the package. The fix for this is included with this package version.

I'm on version 4.9.2. Am I looking at the wrong line? 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/echarts/options/text-style.d.ts#L7

Thanks for replying!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
