### ISSUE TITLE
[@types/async] missing override for concatLimit function.

### ISSUE THREAD

**Issue by ju1ius** [DefinitelyTyped/DefinitelyTyped#49763]
Hi,

The type definitions are missing the async version of the [concatLimit](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/async/index.d.ts#L197) function.

Ping authors: @borisyankov @notarseniy @Penryn @fenying @pascalmartin

**Comment by ju1ius** [comment]
FYI, the following worked for me:

```typescript
// types/async.d.ts
import * as async from 'async'

declare module 'async' {
  export function concatLimit<T, R, E = Error>(
    arr: IterableCollection<T>,
    limit: number,
    iterator: AsyncResultIterator<T, R[], E>
  ): Promise<R[]>;
}

```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
