### ISSUE TITLE
Mapbox map interface has extraneous addLayer declaration

### ISSUE THREAD

**Issue by ntilwalli** [DefinitelyTyped/DefinitelyTyped#4977]
@Anahkiasen Can you remove the `addLayer` declaration in the `L.mapbox.Map` interface.  That function does not exist in the 2.2.1 version of the Mapbox Javascript API (https://www.mapbox.com/mapbox.js/api/v2.2.1/l-mapbox-map/) and it is shadowing the equivalent `addLayer` function in the Leaflet base class map which also has an optional `insertAtTheBottom` argument?

This:

```
    interface Map extends L.Map {
        tileLayer    : L.mapbox.TileLayer;
        gridLayer    : L.mapbox.GridLayer;
        featureLayer : L.mapbox.FeatureLayer;

        gridControl   : L.mapbox.GridControl;
        infoControl   : L.mapbox.InfoControl;
        legendControl : L.mapbox.LegendControl;
        shareControl  : L.mapbox.ShareControl;

        addLayer(layer: any): any;
        getTileJSON(): any;

    }
```

Should go to:

```
    interface Map extends L.Map {
        tileLayer    : L.mapbox.TileLayer;
        gridLayer    : L.mapbox.GridLayer;
        featureLayer : L.mapbox.FeatureLayer;

        gridControl   : L.mapbox.GridControl;
        infoControl   : L.mapbox.InfoControl;
        legendControl : L.mapbox.LegendControl;
        shareControl  : L.mapbox.ShareControl;

        getTileJSON(): any;

    }
```

**Comment by vvakame** [comment]
@ntilwalli please send a pull request. I'll review it.

**Comment by ntilwalli** [comment]
@vvakame Thanks. I created a pull request. 

https://github.com/borisyankov/DefinitelyTyped/pull/5010

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
