### ISSUE TITLE
marionette-tests.ts & backbone-tests.ts should fail

### ISSUE THREAD

**Issue by milkshakeuk** [DefinitelyTyped/DefinitelyTyped#4978]
Since these tests ignore the fact that `A 'super' call must be the first statement in the constructor when a class contains initialized properties or has parameter properties.` they should all be failing (if they are not already);

``` typescript
    class MyView extends Marionette.ItemView<MyModel> {
        behaviors: any;
        constructor(model: MyModel) {
            this.ui = {
                destroy: '.destroy'
            };
            this.behaviors = {
                DestroyWarn: {
                    message: 'hello'
                }
            };
            super({ model: model });
        }
        ...
    };
```

If all the `super` calls were moved to the first statement it would still not work as expected (though it may satisfy the tests). [see this backbone issue](https://github.com/jashkenas/backbone/issues/3560) for more information.

This  apply's to the **backbone-tests.ts** file as well.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
