### ISSUE TITLE
@types/stripe gets new version 50 times a day

### ISSUE THREAD

**Issue by JonnyBurger** [DefinitelyTyped/DefinitelyTyped#49788]
`@types/stripe` has had 50 new releases in the past day. I wonder if this is a bug?

![image](https://user-images.githubusercontent.com/1629785/100224816-9e389f00-2f1d-11eb-8fc2-31d1c497c772.png)

**Comment by orta** [comment]
/cc @sandersn 

Hrm, so this is a deprecated types package ( https://www.npmjs.com/package/@types/stripe ) - maybe we're deploying every deprecated module on every publish cycle?

**Comment by sandersn** [comment]
Looks like it started 10 days ago -- this was when it was deprecated, so I hope that this is a bug with only this package, and not with any deprecated package.

**Comment by sandersn** [comment]
Yep, doesn't happen with `@types/next-seo`, which was deprecated a day later.

**Comment by sandersn** [comment]
the logs make it look like a bug in the try-again logic for deprecation
when publishing the new version to be deprecated, it gave the following error each time:

```
publishing to github failed: Error: The expected resource was not found. : @types/stripe
```

BUT it stopped after a different deprecation also gave an error, but during the deprecation step instead of the publishing step:

```
Error: You can no longer unpublish this package.
Failed criteria: 
has dependent packages in the registry

Please deprecate it instead:
```

this makes no sense because deprecating a package from DT has two steps:
1. publish a stub package with no types, just a README.
2. deprecate the stub.

The stub-publish step doesn't check for the existence of the `@types` package. And the deprecate step doesn't try to unpublish.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
