### ISSUE TITLE
[@types/antlr4] Import/Export paths changed in antlr4 4.9.0

### ISSUE THREAD

**Issue by cmoesel** [DefinitelyTyped/DefinitelyTyped#49798]
Apparently [antlr4@4.9.0](https://www.npmjs.com/package/antlr4/v/4.9.0) switched over from `require` to `es` style exports and imports _and_ changed the location of the code in the packaged module (from `./` to `src/`).  As a result, the type definitions now do not reflect the reality of how the antlr4 types should be imported from the `antlr4@4.9.0` module.

For a related issue in the antlr4 project, see antlr/antlr4#2968.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @mcchatman8009 @tarilabs @jgellin-sf

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
