### ISSUE TITLE
Extend Express Session with own property

### ISSUE THREAD

**Issue by mpgr04** [DefinitelyTyped/DefinitelyTyped#49814]
I would like to give the Express Session an own property. But I encounter problems.
I have defined my own folder @types and added it to the TypeRoots in the .tsconfig file, the @types folder contains an index.d.ts file.
I saw that it should be possible to extend the Session object like this

```typescript
declare module 'express-session' {
    interface SessionData {
        counter: number;

    }
}
```

This works fine, but in my code the type Session changes to any because of this: Module '"express-session"' has no exported member 'Session'.

Now I found out that in newer versions you can probably extend the object as follows:

```typescript
declare module 'express-session' {
    interface Session {
        counter: number;

    }
}
```

This also works, the session type does not change to any and the property is present, but this triggers this error:
Property 'counter' is missing in type 'Session & Partial<SessionData>' but required in type 'Session'

Therefore it is now unclear to me how exactly I can extend the Session object

**Comment by wenhx** [comment]
Look here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/59b7135266eae0dd9cdd65e5fd341209e810ccf0/types/express-session/express-session-tests.ts#L63

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
