### ISSUE TITLE
[@type/parse] Parse.Cloud.onLiveQueryEvent is not available in current Parse JS SDK (node) Definition

### ISSUE THREAD

**Issue by OnielN14** [DefinitelyTyped/DefinitelyTyped#49820]
It looks like the definition of "Parse.Cloud.onLiveQueryEvent" is missing. 

here is the [documentation](https://docs.parseplatform.org/cloudcode/guide/#onlivequeryevent).

Thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
