### ISSUE TITLE
Update redux-saga-routines with createRoutineCreator

### ISSUE THREAD

**Issue by andrewbrodko** [DefinitelyTyped/DefinitelyTyped#49857]
Current type definitions missing createRoutineCreator() from the next commit:
https://github.com/afitiskin/redux-saga-routines/commit/b88a46d6c37bfe99b23c636bfeb99ab76d2a148b#diff-2c5199fb3614f89a348ce2193a8dc8408c0e14ff2c791466bec2f473e2328faa

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by lewismoten** [comment]
This is still an issue today and is reported here in https://github.com/afitiskin/redux-saga-routines/issues/75

Simply using any of the action creators causes a problem with dispatch, and their payloads are not typed.

```js
// TypeScript error
dispatch(load.trigger());
// Bypass
dispatch(load.trigger() as ReturnType<any>);
```

My environment:

redux-saga-routines: 3.2.3
@types/redux-saga-routines: 3.1.8
typescript: 5.5.4

VS Code: 1.891.1 (Universal)
Node: 18.18.2

To workaround the typecasting everywhere, I just ended up creating my own helper utilities using @reduxjs/toolkit `createAction` to do something similar to work around the missing/wrong TypeScript definitions.
