### ISSUE TITLE
@types/node does not implement uncaughtExceptionMonitor for version 12 (available since node 12.17)

### ISSUE THREAD

**Issue by garhul** [DefinitelyTyped/DefinitelyTyped#49887]
I'm using version 12.18.0 of @types/node in my project and node version 12.18 I cannot make use of uncaughtExceptionMonitor since it's not registered as a valid option.

Is this something that slipped off the roadmap or just not going to be implemented for version 12 ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
