### ISSUE TITLE
Method all param require a number instead a string Array

### ISSUE THREAD

**Issue by PadRocha** [DefinitelyTyped/DefinitelyTyped#49900]
![image](https://user-images.githubusercontent.com/23110724/100891275-b90b9600-347e-11eb-9ed0-353b368ae563.png)

in the @types/mongoose

```
/**
 * Specifies an $all query condition.
 * When called with one argument, the most recent path passed to where() is used.
 */
all(val: number): this;
all(path: string, val: number): this;
```
I understand that this parameter should ask for an array of objects, in fact the text editor asks for it.

Once corrected it allows me to do the function and the request is executed correctly

```
/**
 * Specifies an $all query condition.
 * When called with one argument, the most recent path passed to where() is used.
 */
all(val: string[]): this;
all(path: string, val: string[]): this;
```

![image](https://user-images.githubusercontent.com/23110724/100891890-5e266e80-347f-11eb-9ffc-a5d236090004.png)

**Comment by acrilex1** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49902, there is a bigger issue underneath

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
