### ISSUE TITLE
Allow `undefined` as a valid SystemStyleObject in @styled-sytem/css

### ISSUE THREAD

**Issue by gausie** [DefinitelyTyped/DefinitelyTyped#49927]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8c0f0309f82f667e1c8c1c650ed67f0585fc9a3d/types/styled-system__css/index.d.ts#L413

Aside from being accurate, this makes it compatible with `React.CSSProperties` which is useful for spreading props into `sx`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
