### ISSUE TITLE
lodash.groupBy has incorrect return type, Dictionary<T>

### ISSUE THREAD

**Issue by allenap** [DefinitelyTyped/DefinitelyTyped#49934]
At least one `lodash` function returns `Dictionary<T>`: `groupBy`.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/560c921e8b9ddec7a50a6d57793a0211ea696d81/types/lodash/common/common.d.ts#L247-L249

This type implies that for any key there is a `T` value to be found. However, at runtime, this is not true:

```typescript
// a will have type Dictionary<number>
const a = groupBy([1,1,2], a => a * a) // -> { '1': [ 1, 1 ], '4': [ 2 ] }

// av will have type number
const av = a["foo"] // -> undefined
```

One fix might be to change `Dictionary<T>` to include `undefined`:

```typescript
interface Dictionary<T> { 
    [index: string]: T | undefined; 
}
```

**Comment by cnees** [comment]
Underscore has the exact same problem.
Also, to underscore (heh) how wrong Dictionary<T> is for the return type, notice how it expects string keys! That's not a sound assumption for either Lodash or Underscore.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
