### ISSUE TITLE
globalize declaration breaks intellisense

### ISSUE THREAD

**Issue by dan-f** [DefinitelyTyped/DefinitelyTyped#49960]
Hey there. I'm experiencing a pretty odd side effect of having added a dependency on `@types/globalize`: intellisense in VS Code stops working. I'm pretty new to typescript (migrating from flow), so pardon any naivete here.

Here's the specific repro:
- typescript `4.1.2`
- VS Code `1.51.1`
- Create a project directory: `mkdir repro && cd repro`
- Create a yarn project:`yarn init`
- Initialize the typescript project: `yarn tsc --init`
- Create two files: `touch index.ts a.ts`
- Define a function `foo` in `a.ts`
- Open `index.ts` in VS Code
- Begin typing `fo` and see `foo` autocomplete; hitting enter will automatically import the function
- Delete the code in `index.ts` now
- Install the globalize declaration: `yarn add --dev @types/globalize`
- Begin typing `fo` again - autocompletion stops working
- Uninstall the globalize declaration: `yarn remove @types/globalize`
- Autocompletion works once more

Tagging the authors as suggested in the issue template: @gcastre @afromogli @bryanforbes

Thank you!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
