### ISSUE TITLE
@types/auth0 - add generics

### ISSUE THREAD

**Issue by aaronadamsCA** [DefinitelyTyped/DefinitelyTyped#49988]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/auth0/index.d.ts

It's been 4 years since @wbhob created most of these types, and at this point they would really benefit from some simple generics for many of the `any` types throughout.

I am too busy/new to try adding this myself right now, but I wanted to open an issue to track it.

` getProfile` would be a good place to start, I think this might be all that's needed:

```
getProfile<T = any>(accessToken: string): Promise<T>;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
