### ISSUE TITLE
[socket.io][socket.io-client] not needed since v3

### ISSUE THREAD

**Issue by david-fong** [DefinitelyTyped/DefinitelyTyped#50007]
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors of `socket.io-client`: @progre @divillysausages @florentpoujol
  - Authors of `socket.io`: @KentarouTakeda @gigi @BrainMaestro @murbanowicz @kevinkam

**Comment by murbanowicz** [comment]
Would you please provide any documentation and any explanation what is the issue?

**Comment by murbanowicz** [comment]
Oh I see. v3 migrated to TS so we do not need separate typings, not sure what we should do now to reflect it here?

**Comment by david-fong** [comment]
> Oh I see. v3 migrated to TS so we do not need separate typings, not sure what we should do now to reflect it here?

Take a look at [scripts/not-needed.js](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/scripts/not-needed.js)! I think we just need to do `node ./scripts/not-needed.js "socket.io" "3.0.0"; node ./scripts/not-needed.js "socket.io-client" "3.0.0";`

**Comment by murbanowicz** [comment]
I have started this work here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50011
but it requires more effort than I thought, so I will not be able to finish it soon.
Feel free to fork my repo and add missing changes.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
