### ISSUE TITLE
@types/insert-text-at-cursor - widen type for `input` param?

### ISSUE THREAD

**Issue by ethanroday** [DefinitelyTyped/DefinitelyTyped#50025]
@stof:

Should the type of the `input` parameter of `insertTextAtCursor` should be wider than `HTMLTextAreaElement | HTMLInputElement`? Let's say I want to append some arbitrary information any time a user pastes on the page. As written, the following generates an error:

```typescript
document.addEventListener("paste", event => {
  insertTextAtCursor(event.target, "something");
})
```

Produces:

```
Argument of type 'EventTarget | null' is not assignable to parameter of type 'HTMLTextAreaElement | HTMLInputElement'.
  Type 'null' is not assignable to type 'HTMLTextAreaElement | HTMLInputElement'
```

Since I can't do any clever type narrowing on `EventTarget` that would get me to the proper DOM node types, the only way I can get around this is to explicitly say `event.target as any`, which seems less than ideal.

I understand the motivation but, as written, the types break what seems to be a fairly straightforward use case.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
