### ISSUE TITLE
Unexpected path mapping

### ISSUE THREAD

**Issue by s1nce** [DefinitelyTyped/DefinitelyTyped#50075]
I am trying to write types for [pnpjs](https://github.com/pnp/pnpjs/), but CI failed on #50073 

`Error: In @pnp, unexpected path mapping for @pnp: 'pnpjs/v2/pnpjs'`

Seems this type of mapping is not support in definition-parser.js, could provide some suggestion to fix it

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
