### ISSUE TITLE
[@types/ioredis] Wrong type for callback inside dnsLookup

### ISSUE THREAD

**Issue by mchigit** [DefinitelyTyped/DefinitelyTyped#50150]
Package: @types/ioredis
Version: 4.17.8

# Problem

The type for `dnsLookup` callback does not match the type defined in [ioredis](https://github.com/luin/ioredis/blob/279f67eb18e6c20dc7d461fe6890ac22f63cd0fa/lib/cluster/ClusterOptions.ts#L6-L10)

In the ioredis library, family is considered optional parameter while in `@types/ioredis` it is required. 

# Solution (proposal)

Make family an optional parameter:
```
family?: number
```

On a side note, it seems like family is not even used in the actual function: https://github.com/luin/ioredis/blob/a381ac72b7dc1469a21b2215c6bb00fe7641a201/lib/cluster/index.ts#L896

Authors: @thmiyathmary @Plantain @chrisleck @aliarham11 @br8h @shaharmor @palindrom615 @reconbot @funthing @iamolegga @tingwai @pettyalex @SimonSchick @tianlinle @demian85

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
