### ISSUE TITLE
Inconsistencies and missing member for Fabric 4.2

### ISSUE THREAD

**Issue by stefa168** [DefinitelyTyped/DefinitelyTyped#50195]
- [x] I tried using the `@types/fabric` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @oklemencic @joewashear007 @mrand01 @NotWoods @bmartinson @RogerioTeixeira @BradleyHill @bmkrol823 @glenngartner @codertx @mike667 @nataliemarleny

# Issues: 
 - Currently when binding handlers to events fired by Canvas instances, the event type that is passed to the handler is IEvent, however there are events in Fabric 4.2.0 that do not return this kind of event (see for example event `path:created` which returns an object containing a Path instance).

 - PencilBrush is missing [member `decimate`](http://fabricjs.com/docs/fabric.PencilBrush.html#decimate).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
