### ISSUE TITLE
Unable to resolve path to module 'aws-lambda'  import/no-unresolved

### ISSUE THREAD

**Issue by gomesp** [DefinitelyTyped/DefinitelyTyped#50197]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @darbio @skarum @StefH @tobyhede @buggy @y13i  @SachinShekhar @ivanmartos @apalumbo @simonbuchan

I am trying to use the ```types/aws-lambda``` definitions in a serverless framework project. ESLint keeps throwing an error at this typing: ```error  Unable to resolve path to module 'aws-lambda'  import/no-unresolved``` when I am trying to import from ```aws-lambda``` (see this gist for the [full code](https://gist.github.com/gomesp/045f35d82c501f4d6cd0124924330988#file-users-ts)).

Is this supposed to work with the ```eslint-import-resolver-typescript``` package?

**Comment by darbio** [comment]
I can't see your gist (404) please can you check the link?

**Comment by SachinShekhar** [comment]
This is off-topic here.

If `ts` language server isn't throwing error, the problem is with `eslint` config. Also, you should disable module resolution check of `eslint`. That's none of a linter's business.

Here's a working copy of `eslint` for your starting point: https://github.com/ServerlesslyStack/Serverlessly/blob/main/.eslintrc.js (it also disables formatting rules which is none of linter's business).

**Comment by gomesp** [comment]
Thanks @SachinShekhar for the pointers. Closing the issue.
