### ISSUE TITLE
Typescript-bot notifies organisation instead of individuals

### ISSUE THREAD

**Issue by reda-alaoui** [DefinitelyTyped/DefinitelyTyped#50190]
Hi,

I am the author of w3c-image-capture module. I created the module in the name of my organization Cosium.

Lately, someone created this pull request for the module: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50177#pullrequestreview-555928823

The pull request notified the organisation instead of me. I could have missed the pull request if this person hadn’t ping me manually.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
