### ISSUE TITLE
Browser files way

### ISSUE THREAD

**Issue by hec9527** [DefinitelyTyped/DefinitelyTyped#50209]
Github limit the folder and file with 1000, how can I browser the types folder in that contains 6402 folder without donwload or clone it. it cost long long time

**Comment by lucaspontoexe** [comment]
Try cloning with `--depth 1`. It's way faster since you don't need to get the entire history

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
