### ISSUE TITLE
@types/mapbox-gl: new sky api types need adding

### ISSUE THREAD

**Issue by sami616** [DefinitelyTyped/DefinitelyTyped#50202]
![Screenshot 2020-12-20 at 12 50 00](https://user-images.githubusercontent.com/21065581/102713686-f61ab980-42c1-11eb-92df-aec1c0a55b2d.png)

Currently seeing this error, indicating that that the sky definitions are missing from `AnyLayer`

**Comment by tomarak** [comment]
pr: #50421

**Comment by tomarak** [comment]
closed by #50421

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
