### ISSUE TITLE
Platform.getRoutingService method is not compatible with the new version (8) of Routing Service

### ISSUE THREAD

**Issue by MohammedYaseen** [DefinitelyTyped/DefinitelyTyped#50212]
Is something wrong with CI or publishing infrastructure?
No
- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [ ] I tried using the `@types/heremaps` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Mohammed Al-khameri
  - 

If you do not mention the authors the issue will be ignored.

The method Platform.getRoutingService has only one optional param, however in the new version of routing service there are 2 required params: this.platform.getRoutingService(null, 8)           
 /**
             * This method returns an instance of H.service.RoutingService to query the Routing API.
             * @param opt_options {H.service.RoutingService.Options=}
             * @returns {H.service.RoutingService}
             */
            getRoutingService(opt_options?: H.service.RoutingService.Options): H.service.RoutingService;

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
