### ISSUE TITLE
Distributing gRPC protos

### ISSUE THREAD

**Issue by flexwie** [DefinitelyTyped/DefinitelyTyped#50214]
I am new to DefinitelyTyped so I am not quite sure if this really fits the @types package but anyways:

I am developing a module that depends on a gRPC server running in a seperate process. So I wondered if the Typescript protobuf bindings that I generated for that server could be distributed via @types for the module to consume? That would mean that the types are not really part of a npm package as the gRPC server is not intended to be a module itself.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
