### ISSUE TITLE
can it support miniprogram-computed？

### ISSUE THREAD

**Issue by Yubiao-Li** [DefinitelyTyped/DefinitelyTyped#50252]
when i use behavior like this
```js
const computedBehavior = require('miniprogram-computed');

Component({
  behaviors: [computedBehavior],
  computed: {
    showTags(data: any) {
      const showTags = data.videoItem?.showTag || [];
      // const showTags = [{type:'grey_tag',wording:'12点点33'},{type:'grey_tag',wording:'1233点点滴滴23'}]
      if (!data.showSecondTag) {
        return showTags.slice(0, 1);
      }
      return showTags;
    },
  },
})
```
there will be a ts error that “computed” not in “Options<{ showSecondTag: boolean; }, { videoItem: ObjectConstructor; showAvatar: BooleanConstructor; }, { reportTap(e: any): void; reportExposure(): void; }, {}, false>”
![image](https://user-images.githubusercontent.com/39786286/102970599-c4f4f000-4532-11eb-8ee5-f1dbeda05fa6.png)

how can i do

**Comment by Yubiao-Li** [comment]
watch option has another problem
![image](https://user-images.githubusercontent.com/39786286/103272884-f2d9a900-49f8-11eb-9ab0-a9b694cf2ffd.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
