### ISSUE TITLE
[@types/cache-manager] does not have set method without ttl parameter

### ISSUE THREAD

**Issue by alexey1966** [DefinitelyTyped/DefinitelyTyped#50326]
Module @types/cache-manager does not have set method in Multicache without ttl parameter.
It is necessary to foresee, because multicache can use multiple caches with different default TTL.  
So when you do not specify ttl for a record, default one should be used, which you specified in constructor for each cache used in multicache aggregator.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
