### ISSUE TITLE
'"~/node_modules/@types/mongodb"' has no exported member 'SortOptionObject'.

### ISSUE THREAD

**Issue by joyblanks** [DefinitelyTyped/DefinitelyTyped#50366]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/afffc48ce74bd024e47716578ca6317c07ed6cd7/types/agenda/index.d.ts#L12

node_modules/@types/agenda/index.d.ts:12:62 - error TS2305: Module '"~/node_modules/@types/mongodb"' has no exported member 'SortOptionObject'.

 import { MongoClient, Db, Collection, ObjectID, FilterQuery, **SortOptionObject** } from "mongodb";

**Comment by techparlons** [comment]
Hi @joyblanks, I had the same issue. I resolved mine by installing @types/mongodb

**Comment by iamNarcisse** [comment]
Hi @joyblanks, I had the same issue. I resolved mine by installing @types/mongodb

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
