### ISSUE TITLE
Prettier Incomplete Type Definations

### ISSUE THREAD

**Issue by AkiraVoid** [DefinitelyTyped/DefinitelyTyped#50370]
@ikatyang 

When I am trying to use Prettier with TypeScript on my website to display formatted code, I noticed some Incomplete type definations in @types/prettier.

The Prettier docs have introduced multiple ways to use Prettier on browser. With ES Module solution and NodeJS, every thing ran perfectly. But when I tried to deploy my website without NodeJS, the error occured.

First, I just use webpack to pack all ts code with Prettier, it's ok but Prettier is too large to deploy, so I want to use cdn to solve this problem. As the doc says, if I want to use CDN, I should use a config like this:

```json
{
    parser: "json",
    plugins: prettierPlugins,
}
```

Now you must noticed that here plugins is an object, but the type definations only  accept string[] and Plugin[]. I tried many times like:

```javascript
import parserBabel from "prettier/parser-babel";

{
    parser: "json",
    plugins: [parserBabel],
}

// Throw exception: parserBabel is not defined. 
// Threw by webpack generated file, like:

module.exports = parserBabel

// Because browser don't have a function named 'parserBabel', 
// but I imported plugin named parserBabel
// and webpack don't know the origin name of parserBabel

import prettierPlugin from 'prettier/parser-babel';

let prettierPlugins = [prettierPlugin];

// Throw just like above.

import prettierPlugins from 'prettier/parser-babel';

{
    parser: "json",
    plugins: prettierPlugins as unknown as [],
}

// Solution I am using now.
```

Yes, I did found a solution, but as you see, I gave up type checking... So actually I'm not using TypeScript. 

I hope you can solve this problem, thanks.

[Here](https://github.com/prettier/prettier/issues/9991#issuecomment-753467008) is the communication between me and the author of Prettier, it may make some sense on your understanding.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
