### ISSUE TITLE
[Node] Type support for v15.x.x?

### ISSUE THREAD

**Issue by tomasreimers** [DefinitelyTyped/DefinitelyTyped#50387]
Apologies if this is a simple question - when will we release types for node version v15.x.x? Is there a branch where we can contribute to development?

Thanks,
Tomas

- [ ] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jkomyno @a-tarasyuk @alvis @r3nya

**Comment by AviVahl** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50281

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
