### ISSUE TITLE
[New Types Request] @types/sync-fetch

### ISSUE THREAD

**Issue by RDIL** [DefinitelyTyped/DefinitelyTyped#50485]
This should be really easy.
`sync-fetch` is a wrapper around node fetch, so the only type that really needs to be written is the default export, which essentially is:
```ts
// psa: I have no idea how to write types, so this is a rough estimation
const _fetch = require("node-fetch");

export default function fetch(resource: string | _fetch.Request, init?: _fetch.Init);
```

Something like that I think.

Thank you to anybody who does this 😄

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by alex-laz** [comment]
`@types/sync-fetch` is available

Install with npm:

```
npm install -D @types/sync-fetch
```

Install with yarn:

```
yarn add -D @types/sync-fetch
```
