### ISSUE TITLE
@types/plotly.js The PlotType 'line' is missing

### ISSUE THREAD

**Issue by kpapadatos** [DefinitelyTyped/DefinitelyTyped#50514]
The PlotType 'line' is missing
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7dba1d0ba5ef5da655941ed771af49948c5e9be3/types/plotly.js/index.d.ts#L1031

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
