### ISSUE TITLE
The 'noOptionsMessage' should return ReactNode type?

### ISSUE THREAD

**Issue by Cedcn** [DefinitelyTyped/DefinitelyTyped#50521]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0439061c867374f203247dd3a5307d43278ab88b/types/react-select/src/Select.d.ts#L168

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
