### ISSUE TITLE
Interface type declaration error

### ISSUE THREAD

**Issue by Q-Qplus1s** [DefinitelyTyped/DefinitelyTyped#50576]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5f808f268b68182677b744d4483b0b7157f3a88f/types/prosemirror-transform/index.d.ts#L306
comment: 
```
/**
   * Change the type, attributes, and/or marks of the node at `pos`.
   * When `nodeType` is null, the existing node type is preserved,
   */
```
should be:
```typescript
type: NodeType<S> | null
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
