### ISSUE TITLE
Missing and conflicting LICENSE files

### ISSUE THREAD

**Issue by j-buckland** [DefinitelyTyped/DefinitelyTyped#50580]
# Issue:
In several, or even most of the packages, the LICENSE disagrees.
- The root level license https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/LICENSE is an MIT license, with a note that copyright should be given to the people listed at the beginning of the contributors file.
- The license given in unpkg seems to be an MIT license giving credit to Microsoft only. (Examples: [color-name](https://unpkg.com/browse/@types/color-name@1.1.1/LICENSE), [node-fetch](https://unpkg.com/browse/@types/node-fetch@2.5.7/LICENSE), [node](https://unpkg.com/browse/@types/node@10.17.50/LICENSE), [tunnel](https://unpkg.com/browse/@types/tunnel@0.0.1/LICENSE))

# Suggested fix:
- Correct whatever pipeline is pushing the packages to use the correct license file
- Have a LICENSE file for each package to make it explicit who should be given copyright credit. For example, https://github.com/open-telemetry/opentelemetry-js/tree/v0.6.1/packages/opentelemetry-context-zone or https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2864

Note that a top level license file unfortunately won't work for this repo as each package contains different copyright depending on who maintains it.

# Authors:
 - @types/color-name authors: @Ailrun 
  - @types/node-fetch authors: @kbkk @OmgImAlexis @alexandrusavin @ExE-Boss @southpolesteve @wilsonianb @AndrewLeedham @kyranet @vinaybedre @nikcorg 
  - @types/node authors: @jkomyno @a-tarasyuk @alvis @r3nya @BrunoScheufler @smac89 @DeividasBakanas @eyqs @Flarna @Hannes-Magnusson-CK @KSXGitHub, and more
  - @types/tunnel @BendingBender

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
