### ISSUE TITLE
[@types/xrm] Control.setVisible not available on all controls

### ISSUE THREAD

**Issue by remyvd** [DefinitelyTyped/DefinitelyTyped#50594]
According to the [documentation](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/setvisible) `setVisible` should be possible on every control (in contradiction to setDisable, which is all except kbsearch control).

```js
    const control = formContext.getControl(controlName);
    if (control !== null) {
        if (control.getVisible()) {
            control.setVisible(false);
        }
        return true;
    }
```

This wil result into:
`semantic error TS2551: Property 'setVisible' does not exist on type 'Control'. Did you mean 'getVisible'?`

Looks to me that `UiCanSetVisibleElement` should be applied to the interface `Control`. Or is there a control type which doesn't have this method?

Authors: @6ix4our @scottdurow @markusmauch @daryllabar @clownwilleatme

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
