### ISSUE TITLE
[@types/iarna__toml] Missing low-level API

### ISSUE THREAD

**Issue by fasterthanlime** [DefinitelyTyped/DefinitelyTyped#50618]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ajafff

The typings for `@iarna/toml` do not include the low-level TOMLParser API.

I've covered some of it in https://github.com/googleapis/release-please/pull/705 but it would be nice to cover all of it in the DefinitelyTyped typings.

It's a fairly extensive API with lots of methods, see https://github.com/iarna/iarna-toml/blob/latest/lib/toml-parser.js

It's not as well documented as the rest of the API but the README mentions it: https://github.com/iarna/iarna-toml#lowlevel-interface-example-example-w-parser-debugging

I may be able to help with that, but not in the very short term, I'm opening this today so there's a tracking issue for it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
