### ISSUE TITLE
_.unset does not take read only array

### ISSUE THREAD

**Issue by wokier** [DefinitelyTyped/DefinitelyTyped#50690]
Hi

i have written a test for usage of _.unset.
The one property version does pass, but the array version does not.
It may be related to the ReadOnlyArray<string> vs readonly string[] notation.

`import {TestBed} from '@angular/core/testing';
import {AppComponent} from './app.component';
import {AppModule} from './app.module';
import * as _ from 'lodash';

describe('App', () => {
    beforeEach(() => {
        TestBed.configureTestingModule({ declarations: [], providers: [], imports: [AppModule]});
    });

    it ('should unset one property', () => {
      let model = {a:1, b:2, c:3};
      console.log(model);
      _.unset(model,'c');
      console.log(model);
      expect(model.c).toBeUndefined();
    });

    it ('should unset two properties', () => {
      let model = {a:1, b:2, c:3};
      console.log(model);
      _.unset(model, ['b', 'c']);
      console.log(model);
      expect(model.b).toBeUndefined();
      expect(model.c).toBeUndefined();
    });

});
`

      "lodash": "^4.17.20",
      "@types/lodash": "^4.14.167",

**Comment by wokier** [comment]
The workaround is to use `_.omit` instead.
https://lodash.com/docs/4.17.15#omit

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
