### ISSUE TITLE
[@types/react] Return type of forwardRef is missing the "render" property

### ISSUE THREAD

**Issue by tremby** [DefinitelyTyped/DefinitelyTyped#50783]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @johnnyreilly @bbenezech @pzavolinsky ... there are a lot and it seems wrong to ping so many so I'll do those first few and the last few ... @disjukr @vhfmag @hellatan

I'm trying to "spy" on a component which has a forwarded ref in my tests via Jest, so I can check it's rendered when it's supposed to be.

The forwardRef implementation is here https://github.com/facebook/react/blob/9198a5cec0936a21a5ba194a22fcbac03eba5d1d/packages/react/src/ReactForwardRef.js and it looks to always have a `render` property.

That `render` property is what I want to spy on and test. But I'm getting a Typescript error saying that there is no such property. The tests meanwhile work just fine.

The type definition is here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L804

It seems to me that `render` is missing, but I recognize that I may be misunderstanding something, or going about spying on this component the wrong way (please enlighten me if so).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
