### ISSUE TITLE
[@types/w3c-web-usb] No syntax error but "Property 'usb' does not exist on type 'Navigator'" still occurs in the compilation even @types/w3c-web-usb has been installed

### ISSUE THREAD

**Issue by tomfong** [DefinitelyTyped/DefinitelyTyped#50839]
```
error TS2304: Cannot find name 'USBDevice'.

11   devices: USBDevice[] = [];
              ~~~~~~~~~
error TS2339: Property 'usb' does not exist on type 'Navigator'.

22     await navigator.usb.getDevices().then(
```

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @larsgk @thegecko 

If you do not mention the authors the issue will be ignored.

**Comment by thegecko** [comment]
This looks like a usage problem and should be put on stackoverflow.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
