### ISSUE TITLE
[@types/phoenix] PushStatus type restriction

### ISSUE THREAD

**Issue by anirudhsama** [DefinitelyTyped/DefinitelyTyped#50844]
Hi,

In PR #49958, a type was added for PushStatus and the allowed values were `ok`, `error` and `timeout`. I think there is no restriction on the allowed push statuses to be only these values. If you look at the documentation on Phoenix Channel `handle_in/3` method here: https://hexdocs.pm/phoenix/Phoenix.Channel.html#c:handle_in/3 the allowed response is of the format:
`{:reply, reply(), Phoenix.Socket.t()}` and the type of `reply()` is `reply() :: status :: atom() | {status :: atom(), response :: map()}`

@aloukissas can you please have a look?

Thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
