### ISSUE TITLE
[@types/ramda] Destructuring assignment with curried functions break types

### ISSUE THREAD

**Issue by EmCeeEs** [DefinitelyTyped/DefinitelyTyped#50887]
**Type of Issue**
Bug or limitation?

**Description**
Using [destructuring assignments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) on curried functions sets types to `any`.

**Example**
```typescript
import * as R from 'ramda'

const asObject = R.curry((a: number, b: number) => ({a, b}))
typeof asObject // Curry<(a: number, b: number) => {a: number, b: number}>

const asTuple = R.curry((a: number, b: number) => [a, b])
typeof asTuple // Curry<(a: number, b: number) => number[]>

const {a, b} = asObject(1, 2)
typeof a // any
typeof b // any

const [c, d] = asTuple(9, 8)
typeof c // any
typeof d // any
```
However, this works:
```typescript
const obj = asObject(1, 2)
typeof obj // {a: number, b: number}

const tuple = asTuple(9, 8)
typeof tuple // number[]
```

**Context**
├─ @types/ramda@0.27.36
│  └─ ts-toolbelt@^6.15.1
├─ ramda@0.27.1
├─ ts-toolbelt@6.15.5
└─ typescript@4.1.3

@TheHandsomeCoder

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
