### ISSUE TITLE
mathjs - MathArray definition update

### ISSUE THREAD

**Issue by dankellett** [DefinitelyTyped/DefinitelyTyped#50970]
- I tried using the `@types/mathjs` package and had problems.
  - Authors: @siavol @andnp @bradbesserman @pawkrol @charlee @mark-wiemer

The MathArray is currently restricted to numbers, preventing MathArrays of other types that are supported in the library. I believe the MathArray definition should be set to use all supported types by using MathType instead. 

Current: `type MathArray = number[] | number[][];`
Proposed: `type MathArray = MathType[] | MathType[][];`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
