### ISSUE TITLE
jqueryui missing definition for selectmenu

### ISSUE THREAD

**Issue by tstar** [DefinitelyTyped/DefinitelyTyped#5121]
jqueryui.d.ts missing definition for jQuery UI 1.11 selectmenu http://jqueryui.com/selectmenu/

**Comment by vvakame** [comment]
@tstar please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
