### ISSUE TITLE
[react-router] Strongly typed path does not work with path parameter constraints

### ISSUE THREAD

**Issue by bhollis** [DefinitelyTyped/DefinitelyTyped#51604]
- [x] I tried using the `@types/react-router` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @apieceofbart

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50295 added strong typing for the `path` parameter of `Route`, but the tests are incomplete and do not cover [the feature where you can specify regex constraints on path segments](https://github.com/pillarjs/path-to-regexp/tree/v1.7.0#custom-match-parameters). Example:

```
<Route path="/:membershipId(\d+)/d:version(1|2)">
```

In this case the `match` should have keys `membershipId` and `version`, but with the new typings match is:

```
match<{
    "membershipId(\\d+)": string;
} & {
    "version(1|2)": string;
}>
```

**Comment by apieceofbart** [comment]
Hey, sorry for runing your experience with @types/react-router. As far as I can tell there's no way to have a type safe version of regex - unless I am wrong. 
In that case I think the whole thing should be reverted unfotunately. 
I guess for now you have to stay on older version.

**Comment by dgreene1** [comment]
I think there’s a way to salvage the new stricter version and still allow users to use a Regex. All we have to do is make the generatePath function have an additional ternary where it checks if the type is a regex.

> @apieceofbart apieceofbart commented 2 hours ago
>  Hey, sorry for runing your experience with @types/react-router. As far as I can tell there's no way to have a type safe version of regex - unless I am wrong.
>  In that case I think the whole thing should be reverted unfotunately.
>  I guess for now you have to stay on older version.

It would just be sad to see it all go just to support the regex case.

**Comment by leonardodino** [comment]
hey there, @bhollis 

sorry, the PR which broke the regex usage on routes was actually mine 🙈 (#51355)

for the time being you can opt-out of it, on the routes that you are using regex with one of the following:

```jsx
<Route path={"/:membershipId(\d+)/:version(1|2)" as string}> // reflects the old behaviour
// or
<Route path={"/:membershipId(\d+)/:version(1|2)" as "/:membershipId/:version"}>
```

Indeed we should cover cases like this 😄 I even forgot that it allows this syntax.

**Comment by sirreal** [comment]
The route matching has several significant issues right now. I'd recommend reverting #51355.

It would be good to read through [`path-to-regexp`](https://www.npmjs.com/package/path-to-regexp)'s README to understand the sort of issue that aren't covered and the complexities involved in covering them. That's the library `react-router` is using under the hood.

> Custom Matching Parameters
> Parameters can have a custom regexp, which overrides the default match ([^/]+).

This issue is focused on custom matching parameters. This, alone, [seems manageable](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=54&pc=31#code/FAFwngDgpgBACgQwE4ILYDUEBsCusC8MAziEgJYB2A5jAD4wDaJ51AusMFAB4QD2SIGOGgwAol1IIAxiEQpUAHgAqMbiCgUAJkWKlKVAHwx8wGGZgq1G7TADktmAH4YAbwC+MAFynzlidZ0AAwASF0oAMygkGAA5NCg3AApQiKiYAH03AEpHQKdXRjk0GEpY+NZHT3hkNExcWA9vcwtVfy0glIpI6LjUBOSwrrTMrLznF0Ka1BKKMr7WKqKMbDwYRp8zP3V2mBDB7rmE3PyJhiWZw4rFqbrV9ebT89KlBer5W4aAbg5OHn5BYSwcSSGRLIjKVrbGzMfRGEzNAD0CJgCM8ECmCPRIAAFhsWlYdoFUZ0Dks3AiSWkAEpQEhuQJ45zAlCgqYKJZGABkYgkLNkU3BNJIRia5iRXnR8kxCBxeK2AV2nkp0TJFP21NpIHpjJ5IP58nZUy5ur5YIUQpAIo4iORqMlaDlkIVRKV6pVU21zSZvOk+rQhvkVptEqmjoJNkCrtS7vknvM3r1SwDaCDYttJBlZCk0pxdoxqH4UBzuOa8sJoRh1HJUaGMbQ5OVMAtcbMCdNbI5MG5zN9ZotqbM4oRGZAWeLefkYbaEYreirxLdb3rDK9Jt7HaNXjx4oAgrpM1JdCwaAB3WBSBCzABEkqIUCvMAARjhBJpeBRbIJUDKpCXfE7y0XTIV3jVxGgKBh7VQKpKyoV4lg+NYfkBDJjDXVkDXsAwOBQ9I0J7DC0HBWwRzHLFsVsbDcPwn1CNQYjUXCXheEo0BIFgPDCAIv16IUWwmJYqj2NQrjaJ44jPAE1jqNExMBT40js0k5jhxAA9UUfZBpOEzj0PEhS1NHJSBNU9TPE0pBTKM7SRF07izRIwyx2U3grOcizHDcqQbI4mi5PkYjFMY5jEgs2hNIALyyLyNOQTzFJ8kS9IcoKXJi8zkESHEyCIWgcRlHIvNY4BxQAZWxXgcCwTQn1gCYAAYYLnGg3DY2y-PbAK+IRRIADoAGoslYsqKqqmrHzqmAoKa48kJk5L5NsCc0AAWgoeJivm+z5NggwgA). However, given the other issues with parameter inference I don't believe it's viable to simply fix this.

> - Please note: Parameter names must use "word characters" (`[A-Za-z0-9_]`).

Capturing parameters seems to be "up to" a character that doesn't match "word characters", e.g. `/:param-name` would captura a parameter named `param` _not_ `param-name`.

> Modifiers must be placed after the parameter (e.g. /:foo?, /(test)?, /:foo(test)?, or {-:foo(test)}?).

I don't believe this is well handled.

> It is possible to write an unnamed parameter that only consists of a regexp. It works the same the named parameter, except it will be numerically indexed

Again, this isn'e well handled. 

I'd love to see the params inferred based on the string, but managing all of this seems difficult at best 🙂

**Comment by bhollis** [comment]
This works great now, and it's awesome to have the parameters be typed. Thanks for fixing it!

**Comment by dgreene1** [comment]
We should give some kind of internet award to @lmichelin, @apieceofbart, and others that contributed to this incredible feature. It eliminated a lot of boiler-plate code in many of my repos since I no longer have to do error prone runtime checks or write involved wrapper functions. A+

**Comment by pleunv** [comment]
Hi all,

I played around a bit with this as well when the template literal types came out in an attempt to extract types from the routes, similarly to how the PR linked to this issue fixed it.
However, I took it one step further and also mapped any string constraints to a string literal type. Quick illustration below of what I mean:

With the current implementation you get the following type extraction from a route. It doesn't take constraints into account and seems to choke on a constraint + optional combo.
I'm also not sure why this is `string | number | boolean` instead of `string`. Does RR/PTR attempt to parse the values? Couldn't find anything in the docs.

```ts
type ConstrainedParams = ExtractRouteParams<'/:p(one|two)'>;
type OptionalConstrainedParams = ExtractRouteParams<'/:p/:p2(a|b)?/:p3(c|d)'>;

// Extracted: 
type ConstrainedParams = { p: string | number | boolean; };
type OptionalConstrainedParams =
  { p: string | number | boolean; } &
  { "p2(a|b)"?: string | number | boolean | undefined; } &
  { p3: string | number | boolean; };
```

What you ideally want to achieve is the following, since this allows you to strongly type your route params and also encourages definition of stricter and constrained params (which, at least to me, is a good thing).

```ts
type ConstrainedParams = ExtractRouteParams<'/:p(one|two)'>;
type OptionalConstrainedParams = ExtractRouteParams<'/:p/:p2(a|b)?/:p3(c|d)'>;

// Extracted:
type ConstrainedParams = { p: 'one' | 'two' };
type OptionalConstrainedParams = {
    p: string;
    p3: "c" | "d";
    p2?: "a" | "b" | undefined;
}
```

I managed to achieve this with the following types.
**Warning:** not for sensitive eyes, but I'm sure it can be cleaned up and/or done in a more efficient way.

```ts
type OptionalPropertyNames<T> = {
  [K in keyof T]-?: {} extends { [P in K]: T[K] } ? K : never; // eslint-disable-line @typescript-eslint/ban-types
}[keyof T];

type SpreadProperties<L, R, K extends keyof L & keyof R> = {
  [P in K]: Exclude<R[P], undefined> | L[P];
};

type Id<T> = T extends infer U ? { [K in keyof U]: U[K] } : never;

type SpreadTwo<L, R> = Id<
  Pick<L, Exclude<keyof L, keyof R>> &
    Pick<R, Exclude<keyof R, OptionalPropertyNames<R>>> &
    Pick<R, Exclude<OptionalPropertyNames<R>, keyof L>> &
    SpreadProperties<L, R, OptionalPropertyNames<R> & keyof L>
>;

type ExtractParam<T extends string> = T extends `${infer Param}(${string})` ? Param : T;

type ExtractStringLiteral<T extends string> = T extends `${infer Type}|${infer Rest}`
  ? ExtractStringLiteral<Rest> | Type
  : T;

type InferParamType<T extends string> = T extends `${string}(${infer Type})`
  ? ExtractStringLiteral<Type>
  : string;

type ExtractParamShape<T extends string> = T extends `${infer Param}?`
  ? { [k in ExtractParam<Param>]?: InferParamType<Param> }
  : { [k in ExtractParam<T>]: InferParamType<T> };

export type ExtractRouteParamsWithConstraints<T extends string> = string extends T
  ? Record<string, string>
  : T extends `${string}:${infer Param}/${infer Rest}`
  ? SpreadTwo<ExtractParamShape<Param>, ExtractRouteParamsWithConstraints<Rest>>
  : T extends `${string}:${infer Param}`
  ? ExtractParamShape<Param>
  : Record<string, never>;
```

While I realize it's not very productive to try to type _all_ of the `path-to-regexp` functionality, I do feel that extending the existing approach in order to add stronger typing of params is mostly a net benefit. I'm sure there's scenarios I'm not covering though, since this is based on my use cases, but those can probably be supported too.

Is this anything you'd be willing to incorporate into the official types?

**Comment by leonardodino** [comment]
Hi @pleunv, I think it's a good idea!
It's worth opening a PR with the code and adding the tests for the intended cases.
If people agree and doesn't break too many cases or impacts performance too much would gladly be appreciated.

regarding `string | number | boolean` case, it might be either legacy or because it's shared with `generatePath()`, in which cases at least `number` makes sense and has an unambiguous usage.

**Comment by pkuczynski** [comment]
@pleunv I have exactly the same case as you presented. Would you be keen on firing up a PR with this change?
