### ISSUE TITLE
[react-select] forwardRef missing properties types

### ISSUE THREAD

**Issue by JuanM04** [DefinitelyTyped/DefinitelyTyped#51664]
When I use `forwardRef` and I pass `Props` (from `react-select`), the props doesn't work correctly. It's demostrated in this CodeSandox:
https://codesandbox.io/s/react-select-forward-ref-5gifj?file=/src/App.tsx

- [x] I tried using the `@types/react-select` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jonfreedman @Methuselah96 @thchia @rjoonas @kylemh

**Comment by Methuselah96** [comment]
Are you actually getting compile errors? It seems possible that this is just an issue with autocomplete.

Here's an example of passing the `options` prop and it seems to compile fine: https://codesandbox.io/s/react-select-forward-ref-forked-q34m3?file=/src/App.tsx.

**Comment by Methuselah96** [comment]
Got it, that makes sense. After a brief investigation, I believe the reason it's doing that is because the types for `Props` currently includes an index signature [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/src/Select.d.ts#L36) that basically allows for any prop. We're working on moving the types to `react-select` itself for v5.0, so I don't think it's worth changing it on DefinitelyTyped since it would probably be a breaking change for people.

In order to work around this for now you can import `NamedProps` from `react-select/src/Select` (which is the same as `Props` but without the index signature) and use that in place of the `Props` that you're importing from `react-select`.

**Comment by JuanM04** [comment]
Thank you very much!
And btw, which type should I use as the Ref? In the example it's set to `any`

**Comment by Methuselah96** [comment]
No problem.
The ref should be the default export of `react-select` (that you're importing as `ReactSelect` in your example).

**Comment by JuanM04** [comment]
Perfect!
I don't know if you want this issue to stay open for when you do the migration to the main repo, but feel free to close it.

**Comment by Methuselah96** [comment]
Glad to help out. If you would close it that would be great. I don't have the ability to close it because of the way DefinitelyTyped works.
