### ISSUE TITLE
[@types/json-schema-faker] TypeScript Says `jsf` Namespace Is Deprecated Instead of Just Default Function

### ISSUE THREAD

**Issue by ITenthusiasm** [DefinitelyTyped/DefinitelyTyped#51734]
## Checklist
- [x] I tried using the `@types/json-schema-faker` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @peterblazejewicz, @baremaximum 

## Problem:
Right now, using TypeScript in VS Code with the `json-schema-faker` package gives a misleading deprecation notice. With the following code:
```typescript
import jsf from "json-schema-faker";
import faker from "faker";
import * as Schemas from "./schemas";

jsf.extend("faker", () => faker);

export default function generate(schema: keyof typeof Schemas) {
  return jsf.generate(Schemas[schema]);
}
```
VS Code shows ~~strikethrough~~ formatting over both uses of ~~jsf~~, though `extend` and `generate` are not crossed out. The deprecation warning for `jsf` is a little misleading since I'm correctly using the exposed functions. Additionally, the [docs](https://github.com/json-schema-faker/json-schema-faker/blob/master/docs/USAGE.md) show examples of using the functions directly from the exported namespace.

Any ideas/thoughts on how to resolve this?

**Comment by baremaximum** [comment]
This is intentional. The warning indicates that use of the namespace is deprecated in this library. Instead, import the functions you need from the namespace and call those directly. 

So, instead of 

    import jsf from "json-schema-faker";

use:

    import { generate, extend } from 'json-schema-faker';

The docs in the library's repo use the deprecated import method because they are outdated. I'm not really involved with that project. I made these definitions because I was using the library and no definitions existed, so I made some and put them up in case other people find them useful. I don't really have time to make a PR to update the docs over there.

For your project, just ignore that aspect of the docs and you'll be fine; the warning will go away.

**Comment by peterblazejewicz** [comment]
@baremaximum I've made a PR to drop `@` from JSDoc tag, for me it worked in unintended way.
see #51736 
Let me know if it should be left 'as is' (no change), thx!

**Comment by ITenthusiasm** [comment]
@peterblazejewicz, from what I read from baremaximum's response, it seems like the code should be left "as is" -- at least for now.

**Comment by ITenthusiasm** [comment]
Gonna close this based on the response. Thanks @baremaximum
