### ISSUE TITLE
dymo-label-framework/index.d.ts is not a module

### ISSUE THREAD

**Issue by CorwinGray** [DefinitelyTyped/DefinitelyTyped#51819]
I tried using the `@types/dymo-label-framework` package authored by @thijskuipers and had problems.

I've done the install
`npm i -G @types/dymo-label-framework`

Attempt to import the node in an API.ts file (multiple ways, this is the one stated in README, already followed all other troubleshooting steps there as well, to no avail.)
`import * as dymo from "dymo-label-framework;`

Which produces a TCS Compilation Error
`File 'C:/projectfilepath/node_modules/@types/dymo-label-framework/index.d.ts' is not a module.`

Confirmed that file index.d.ts does exist at stated filepath, not sure what that's about.

All I'm attempting to do so far is get Printers.
`const printers = dymo.label.framework.getPrinters();`

If I attempt to run this without the import, it produces this Runtime Error:
`ReferenceError: dymo is not defined`

Am I missing something?  Should my import be different?  Any insights or assistance you can provide would be greatly appreciated.  Thanks!

**Comment by thijskuipers** [comment]
It's been a while (2015) since I used it myself... From the last project I can see I included it's declaration using `/// <reference path="../typings/dymo-label-framework/dymo-label-framework" />` at the top of the typescript file. Don't know whether you still need that (when compilation works, probably not).

Don't forget to include the [actual Dymo SDK](http://labelwriter.com/software/dls/sdk/js/DYMO.Label.Framework.latest.js) in the HTML you're going to use the script in `<script src="dymo_label_framework.min.js"></script>`.

It's not really a module, it's a named object `dymo` in the global namespace. See https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html for a thorough explanation.

**Comment by CorwinGray** [comment]
I completely understand that's its been a while since you've had to take a look at this.  The tech is a little dated.  Thank you for your response.  I was forgetting to include the script in the HTML, so I appreciate that.  However, I'm getting a tslint error when attempting to reference the namespace, `<reference> is not allowed, use imports`  and I can't seem to find any other way to reference the global namespace that's been setup.  I've gone through the documentation you recommended, and more, but I'm still not finding a solution to this.  Do you know of any way to import, or otherwise reference, a namespace without a <reference> call?

**Comment by thijskuipers** [comment]
So, just trying to reproduce, set up in an empty folder:

- `npm init` (accept all defaults)
- `npm install --save @types/dymo-label-framework`
- `tsc --init`
- create `index.ts` with `const printers = dymo.label.framework.getPrinters();` in it;
- `tsc --build`

Produces an `index.js` file with contents:
```javascript
"use strict";
var printers = dymo.label.framework.getPrinters();
```

No imports or reference needed, since it's a named object in the global namespace, so it's picked up by the typescript compiler automatically.

And the `ReferenceError` on runtime (I assume in a browser, cause that's the only place that would work) should be solved when you include the Dymo SDK I linked earlier. That will actually provider the global `dymo` object.

**Comment by thijskuipers** [comment]
And if the type isn't automatically found, you could use the [`types`](https://www.typescriptlang.org/tsconfig#types) or [`typeRoots`](https://www.typescriptlang.org/tsconfig#typeRoots) settings in the `tsconfig.json` file. But since you installed it using `npm` and is goes into the `@types` subfolder of `node_modules`, it should be picked up automatically.

**Comment by CorwinGray** [comment]
Turns out I was trying to access the SDK from a layer higher up than I should have been. Everything built exactly as it should have as soon as I moved the code to the proper .ts file.  Thank you @thijskuipers !  Definitely couldn't have figured this out without your help!
