### ISSUE TITLE
swipeleft/swiperight events in JQueryMobileEvents

### ISSUE THREAD

**Issue by MDuc** [DefinitelyTyped/DefinitelyTyped#520]
My TypeScript code, which is referencing jquerymobile.d.ts, is looking like this:

``` javascript
$(...).swipeleft(function() { ... });
```

The swipeleft and swiperight events seem to be defined in the JQueryMobileEvents interface in the jquerymobile.d.ts file. However, this interface isn't used anywhere else and I'm getting the following compilation error:

_The property 'swipeleft' does not exist on value of type 'JQuery'_

What am I doing wrong?
(I'm using TypeScript 0.8.3)

Thanks.

**Comment by NiklasRaab** [comment]
Same here :(

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
