### ISSUE TITLE
Avoid making React JSX types global, to play well with other JSX frameworks.

### ISSUE THREAD

**Issue by trusktr** [DefinitelyTyped/DefinitelyTyped#52321]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7121cbff798dae980fcef4153325c0df591cc80b/types/react/jsx-runtime.d.ts#L2

@eps1lon could we export `JSX` instead of making them global? This would make React play well with other JSX systems.

F.e., in one file that has a React component, and author would place this at the top:

```ts
/* @jsxImportSource react */
```

and then if they have another file with a different system, f.e. using [Solid](https://github.com/ryansolid/solid), they could write this at the top:

```ts
/* @jsxImportSource solid-js */
```

and then in the Solid component all the JSX types would be Solid-based JSX types where otherwise React types wouldn't make sense.

If someone only has one JSX system in their app, used in all their JSX files, they can place `jsxImportSource` in `tsconfig.json` so as not to have to write it in every `.tsx` file.

**Comment by trusktr** [comment]
The file at https://github.com/facebook/react/blob/master/packages/react/jsx-runtime.js already provides the actual runtime stuff. Now `jsx-runtime.d.ts` would `export namespace JSX {...}`

**Comment by trusktr** [comment]
Some info (but it's not totally clear): https://www.typescriptlang.org/tsconfig#jsxImportSource

**Comment by eps1lon** [comment]
I asked myself why we need the global a couple of times. But this was added before I started working on the types. Could you do some git-blame and research on github to find out why this was added?

**Comment by calummonro** [comment]
> I asked myself why we need the global a couple of times. But this was added before I started working on the types. Could you do some git-blame and research on github to find out why this was added?

Hey @eps1lon, sorry to bring up this old thread but I've been trying to implement a custom JSX transform for part of my app and I think I've traced the issue to these React types, namely that this package defines the React JSX types globally:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7121cbff798dae980fcef4153325c0df591cc80b/types/react/index.d.ts#L2965-L2966

It seems that TypeScript has a mechanism for looking up which JSX namespace to use based on the "factory function" specified:

![Screenshot 2022-10-31 at 17 03 01](https://user-images.githubusercontent.com/12599990/199066112-3d1e685c-22d9-47f6-b2c2-668ff52ad96e.png)

From here: https://www.typescriptlang.org/tsconfig#jsxFactory

And as @trusktr has mentioned, this should let us have different JSX transformations happening in different parts of the app.

This package declares the React JSX types on the global namespace which means it's not possible do do as the TypeScript docs suggest (since including this package will essentially make the "fallback" types React-specific).

Just to give more context, I have one file where I would like to use JSX syntax to make arbitrary function calls (the use case is niche but is valid as far as I understand).

I've set up the JSX Pragma and the code is transpiling and running just fine. The only thing I can't get to work nicely is the type-checking.
 
I've extended the global namespace with my JSX return types as advised here: https://www.typescriptlang.org/docs/handbook/jsx.html#type-checking

And I can see that my types are available, but the type checker is still expecting `ReactElement<any, any>`  as defined on `global.JSX.Element`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7121cbff798dae980fcef4153325c0df591cc80b/types/react/index.d.ts#L2967

Just out of curiosity I tested changing the types from:

![Screenshot 2022-10-31 at 17 14 10](https://user-images.githubusercontent.com/12599990/199068415-fdb5b282-6583-4e34-a2ae-c0e98df05a65.png)

to:

![Screenshot 2022-10-31 at 17 14 15](https://user-images.githubusercontent.com/12599990/199068432-5b8d23e5-32ca-42e0-8533-77ff17bdca94.png)

And this has resolved my issue: The React types are being used everywhere they should, and in my one file that uses a custom JSX transform, the global JSX types are being used (which I've defined myself and are free from React-specifics).

I'm not too savvy with TypeScript so I'm not sure how "good" this solution is, but I did want to highlight that it seems that the way this package has declared the JSX types breaks out-of-the box TypeScript functionality.

Happy to support on a fix for this - let me know if I can help.
