### ISSUE TITLE
gapi.client.load should return a promise

### ISSUE THREAD

**Issue by qbolec** [DefinitelyTyped/DefinitelyTyped#5276]
It's curenlty defined as returning void.
One can see clearly from example at https://developers.google.com/api-client-library/javascript/start/start-js that it returns a promise.

**Comment by vvakame** [comment]
@qbolec please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
