### ISSUE TITLE
backbone model url()

### ISSUE THREAD

**Issue by zhamid** [DefinitelyTyped/DefinitelyTyped#529]
The 'url' field in backbone model is declared as a field :-

``` javascript
url: any;
```

However, it can also be declared as a function :-

``` javascript
    url() {
      return '/api/1.0/path/' + this.get('id');
    }
```

IF I change the definition to a function (aka, url(): string) then typescript naturally does not complain about the use above but then it complains when I try to use it as a property.

I am not sure how to declare same name to be either property or function.  Any ideas?

**Comment by maser** [comment]
I just stumbled across this. I can modify the declaration from `url: any` to `url(): any`, but then all the places that don't use `url` as a method don't work anymore. I can't figure out how to even declare `url` in a way that let's me use it the way Backbone intends it to be used. Is this a limitation in the type system?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
