### ISSUE TITLE
[@types/styled-components-react-native]  prop types always any

### ISSUE THREAD

**Issue by sarahsporck** [DefinitelyTyped/DefinitelyTyped#53033]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/styled-components-react-native` and `@types/styled-components` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Methuselah96

==============
It seems that the the components properties type is always any.
E.g.:
```javascript
export const Content = styled.Text<{ language: string }>`
  font-size: 14px;
  letter-spacing: 0.5px;
  text-align: ${props => contentAlignment(props.language)};
  color: ${props => props.theme.colors.textColor};
`
``` 
After following the instructions from the [styled-components documentation](https://styled-components.com/docs/api#typescript) the props type always seems to be `any`. Am I missing something here? ~~Before extracting the react-native types in `@types/styled-components: 5.1.6 it is still working.~~ I appreciate any help.

**Comment by Taggotty** [comment]
@Igorbek @Igmat @lavoaster @Jessidhia @jkillian @eps1lon @flavordaaave @wagerfield @Lazyuki @mgoszcz2 @danilofuchs

This issue seems to be related to the `styled-components` package. The change proposed in #53490 would fix type hinting, as currently `C extends AnyStyledComponent` seems to be a too general and typescript alway matches this Type here. However I do not encounter this issue when using styled components in web. 
```typescript
export type StyledComponentPropsWithRef<
    C extends keyof JSX.IntrinsicElements | React.ComponentType<any>
> = C extends AnyStyledComponent
    ? React.ComponentPropsWithRef<StyledComponentInnerComponent<C>>
    : React.ComponentPropsWithRef<C>;
```

**Comment by Livven** [comment]
Running into the same issue. Does not seem to be caused by either `@types/styled-components` or `typescript` directly though, as versions `5.1.9` and `4.3.2` respectively _can_ work.

The issue appeared for me after deleting and re-generating the `package-lock.json`, so I would assume it to be due to a transitive dependency of the `typescript` package.

**Comment by bradmanAWS** [comment]
Is there any update to this issue? I'm still seeing this problem, with all styled components and props showing as type `any`.

**Comment by Taggotty** [comment]
I fixed this issue by retrying several times and using several devices. Therefore, I guess it is a dependency issue. We got it working with @types/styled-components-react-native: "5.1.1" and not specifying @types/styled-components. [Here ](https://github.com/Integreat/integreat-app/blob/main/native/package.json) you can checkout our `package.json`
