### ISSUE TITLE
The type of property model of Backbone Collection is wrong

### ISSUE THREAD

**Issue by dsosunov** [DefinitelyTyped/DefinitelyTyped#533]
The current version declares a type of collection property 'model' as Backbone.Model 

export class Collection extends ModelBase {
...
   model: Model; // it's wrong
}

But really it's not an instance of a model, it's a type of model; Unfortunately TypeScript doesn't have a type of type like C# have System.Type

Therefore, backbone cannot parse models after fetch and then create correct models from JSON as expected without correct type declaration.

Currently, if somebody will use the current version of type declaration then backbone will always create Backbone.Model

Reproduce:
export class MyCollection extends Backbone.Collection  {
   model: MyModel;
}

var collection = new MyCollection();
collection.fetch();

collection[0] instanceof MyModel == false
collection[0] instanceof Model == true

Proof:
export class MyCollection extends Backbone.Collection  {
   mode =  MyModel; // after change a type definition
}

var collection = new MyCollection();
collection.fetch();

collection[0] instanceof MyModel == true
collection[0] instanceof Model == true

Workaround:
var collection = new MyCollection(null, { model: MyModel } );

So, there MUST BE model: any.

**Comment by pligor** [comment]
From what I see this has been corrected to
```
// TODO: this really has to be typeof TModel
        //model: typeof TModel;
        model: { new(): TModel; }; // workaround
```
But how to use it?  
Because `this.model = MyModule.MyClass` gives a compilation error

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
