### ISSUE TITLE
Type object is not generic

### ISSUE THREAD

**Issue by achaloza** [DefinitelyTyped/DefinitelyTyped#54010]
Hello All,

I am implement google map using type script but facing issue on build time.

I am try "npm install --save @types/google-map-react" but not working.
"./node_modules/google-maps-react/index.d.ts:29:14
    TS2315: Type 'Object' is not generic."
    
    
![image](https://user-images.githubusercontent.com/15319181/123102869-1aaf4400-d453-11eb-8674-715767d32959.png)

**Comment by guilhermefront** [comment]
Hi @achaloza, google-maps-react have it's types bundled inside their package, you can see it here
https://github.com/fullstackreact/google-maps-react/blob/master/index.d.ts

So I would suggest you to open an issue in their github issues, but the library seems pretty much abandoned... So I actually recommend you to use another lib that have the same capabilities, like [this one](https://github.com/google-map-react/google-map-react). I have developed a complex case with it and is a great lib.

Note that doing `npm i --save @types/google-map-react` only installed because it's from another library, there's a difference between `google-maps-react` and `google-map-react`

**Comment by orta** [comment]
Closing as this seems like the right answer, please use discussions for these sorts of requests in the future 👍🏻
