### ISSUE TITLE
Inconsistent Following of .d.ts Guidelines

### ISSUE THREAD

**Issue by aedenj** [DefinitelyTyped/DefinitelyTyped#5430]
I noticed that many of the packages don't follow the [guidelines for writing .d.ts files](http://www.typescriptlang.org/Handbook#writing-dts-files-guidelines-and-specifics) entirely. For example, one guideline states don't use "I' with interfaces. Do inconsistencies exist because those guidelines are newish?

**Comment by vvakame** [comment]
please send a pull request. I want to remove `I` prefix too.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
