### ISSUE TITLE
ws WebSocket IServerOptions server property over-constrained?

### ISSUE THREAD

**Issue by nyx** [DefinitelyTyped/DefinitelyTyped#5461]
I found that in this type definition the optional property `server` is over-constrained as the `ws` library accepts either an `http.Server` or `https.Server`.  I am not sure how to resolve this without changes to either the node typings or to adopt an `any` type for the `server` property in the snippet below:

```
    module WebSocket {
        export interface IServerOptions {
            host?: string;
            port?: number;
            server?: http.Server;
```

Context:

https://github.com/borisyankov/DefinitelyTyped/blob/2d4c4679bc2b509f27435a4f9da5e2de11258571/ws/ws.d.ts#L93

This `ws` library example shows both use cases:

https://github.com/websockets/ws/blob/master/examples/ssl.js#L45

I've been running locally using the `any` solution described up top, but would prefer a more type-safe solution.

**Comment by vvakame** [comment]
@nyx please send a pull request. I'll review it.

**Comment by nyx** [comment]
@vvakame I haven't had much time to put together a PR here, locally the change is trivial and tested, but it may be a bit before I can provide a proper PR with tests.

**Comment by benjamin-willard** [comment]
To be honest, you should be using net.Server not http.Server, becuase for example

https.Server uses tls.Server which uses net.Server.
http.Server uses net.Server so therefore if you use net.Server you'll be able to easily bind correctly, where as both https and http Server would typically be working fine.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
