### ISSUE TITLE
Naming convention for issues related to specific type definition

### ISSUE THREAD

**Issue by cspotcode** [DefinitelyTyped/DefinitelyTyped#5528]
I propose a simple naming convention for issues that relate to an individual type definition.

If I want to file a bug about the jQuery definition, I would name my issue

> [jquery] missing method "foo"

The text within square brackets must match the name of the typing's directory in this repository.

The motivation is that, when I discover a bug in a type definition, I want to make sure I don't file a duplicate bug.  Therefore I need to search the issue queue for any other issues related to that type definition.

If this naming convention is explained on definitelytyped.org's [contribution guide](http://definitelytyped.org/guides/contributing.html), we can easily link to it when someone makes an issue that doesn't follow the convention.  Before long all issues will use the convention, and we'll no longer need to explain it.  That's the theory, at least.

**Comment by vvakame** [comment]
please send a pull request directly.

**Comment by cspotcode** [comment]
If I understand correctly, the pull request should add a description of the
naming convention to the contribution guide?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
