### ISSUE TITLE
ES6 syntax - "Module <name> has no default export"

### ISSUE THREAD

**Issue by srolel** [DefinitelyTyped/DefinitelyTyped#5611]
I started trying to use VSCode with ES6 and I'm running into this. Changing the declaration to `import * as  path from 'path'` for example works for intellisense, but then babel's transpiled output is invalid. Is there a plan to switch to the current syntax? If not, could anyone point me to some instructions on how to modify the d.ts files to work in this case?

**Comment by vvakame** [comment]
I think your code is correct. and I don't have knowledge of babel. what is the problem?
http://goo.gl/ovrcPJ

**Comment by denis-sokolov** [comment]
Possible duplicate #5128.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
