### ISSUE TITLE
node.d.ts: depends erroneously on TS lib.d.ts (includes DOM definitions)

### ISSUE THREAD

**Issue by nahuel** [DefinitelyTyped/DefinitelyTyped#5641]
`node.d.ts` needs `lib.d.ts` to be present, but `lib.d.ts` includes DOM definitions that only works in the browser. The correct way is to depend on TS `lib.core.d.ts` or `lib.core.es6.d.ts` , but if you use one of them with `node.d.ts` and `"noLib" : true` in your `tsconfig.json`, then `console.log()` calls will be marked as errors, because `console.log()` is defined on `lib.d.ts` as included in the browser API and NOT on `node.d.ts` or (correctly) on `lib.core(.es6).d.ts`.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
