### ISSUE TITLE
Missing tsd for angular2/http

### ISSUE THREAD

**Issue by debanjanbasu** [DefinitelyTyped/DefinitelyTyped#5672]
Can someone create the tsd file for angular2/http? Now that it is out of the standard angular2.d.ts

**Comment by vvakame** [comment]
@alexeagle ?

**Comment by debanjanbasu** [comment]
angular2 alpha 36 has taken out the http in a separate js file. The angular2.d.ts does not include the http tsds so that needs to be done. Just as it was done for the angular router.

**Comment by alexeagle** [comment]
This is the issue in angular repo:
https://github.com/angular/angular/issues/3733

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
