### ISSUE TITLE
Nice new github features

### ISSUE THREAD

**Issue by basarat** [DefinitelyTyped/DefinitelyTyped#5683]
https://github.com/blog/2051-protected-branches-and-required-status-checks

@borisyankov would be great to protect `master` from force pushes :rose:

**Comment by borisyankov** [comment]
I saw this earlier and was thinking about this.
I like that we are thinking the same way ;)

What do you think of this (if possible):
Force a single commit or PR to change only a single folder?

**Comment by basarat** [comment]
> Force a single commit or PR to change only a single folder

Probably not. There are common use cases to allow multiple folder changes e.g. a TS version upgrade, or a plugin definition modification that requires the original library definition to be slightly tweaked

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
