### ISSUE TITLE
support process.domain in node.js

### ISSUE THREAD

**Issue by emmettnicholas** [DefinitelyTyped/DefinitelyTyped#5703]
I'm brand new to TypeScript (~30 minutes in), so sorry if I'm missing something obvious:

I'm unable to use `process.domain`:

```
/// <reference path="node-0.10.d.ts" />

var domain = require('domain');

domain.create().run(function() {
    console.log(process.domain);
});
```

When I compile this with `tsc foo.ts`, I get the following error:

```
error TS2339: Property 'domain' does not exist on type 'Process'.
```

`process.domain` is referenced in the [Node.js Domain docs](https://nodejs.org/api/domain.html):

> It sets domain.active and **process.domain** to the domain, and implicitly pushes the domain onto the domain stack managed by the domain module (see domain.exit() for details on the domain stack).

**Comment by vvakame** [comment]
@emmettnicholas try this definition files. https://github.com/borisyankov/DefinitelyTyped/blob/master/node/node.d.ts

**Comment by emmettnicholas** [comment]
@vvakame Does that file define `process.domain` somewhere?

**Comment by vvakame** [comment]
wow, please send a pull request!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
