### ISSUE TITLE
[@types/backbone] class Model attributes stated as Partial<T>

### ISSUE THREAD

**Issue by elxkat** [DefinitelyTyped/DefinitelyTyped#57045]
Hi,

We have an issue with the latest typings, as they mandate all model interface attributes to be | undefined, either with Partial statement on the model interface or | undefined on the get().
If an interface field isn't mandatory is should be stated in that specific interface, not forced by the typings.
`interface TestModel {
  mandatory: string;
  nonMandatory?: string;
}`
**Current typings force "mandatory" string attribute type to string | undefined, forcing checks upon usage.**

Also, currently model ctor & other initializers accept T for attributes, not Partial<T>.
See:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/218d54eb41bf327e50a9b064231ac9c05368b84a/types/backbone/index.d.ts#L256

reference of issue:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/218d54eb41bf327e50a9b064231ac9c05368b84a/types/backbone/index.d.ts#L221
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/218d54eb41bf327e50a9b064231ac9c05368b84a/types/backbone/index.d.ts#L268

Thanks!

@khasanovbi

**Comment by khasanovbi** [comment]
When we create a new model instance, if we don't have defaults set, then get for all model fields return undefined.
Does you use defaults in your case?
I think it's a trade-off between convenience and type strictness.
I do not mind to return the original behavior, but I would also like to hear more opinions. @jgonggrijp could you take a look plz?

**Comment by elxkat** [comment]
Thanks for the quick response!
We do, matching our model interface.
So the use case is not defining defaults() + using the ctor without any params (i.e. undefined attributes).
I understand it's the framework impl and that in vanilla js it's a valid case, however in ts if you've stated a model interface it's weird creating a model instance that doesn't follow the interface.
I think it's too harsh forcing all other (and probably main) use-cases to follow Partial<> because of it.
I think both should be of type T:
attributes: T;
defaults(): T;

**Comment by jgonggrijp** [comment]
Two thoughts:

1. Whenever possible, I'd like to avoid creating situations where TS will tell the programmer that perfectly valid code isn't valid. Among other things, this means that the `Partial<T>` should stay in the `set` method, because once all attributes have been set once, it should be possible to omit mandatory attributes in multi-key updates. Not allowing that is just needlessly complicating life for developers.
2. I'd also like to avoid needlessly breaking existing code. This is a second reason to keep the `Partial<T>` at least in the `set` method.

That said, I understand the wish to have more control over whether particular attributes can be safely assumed to be defined or not when calling `get`. Unfortunately, however, you can always `unset` an attribute, no matter how hard you believe that it shouldn't be allowed:

```ts
const example = new Model<{ mandatory: string }>({ mandatory: 'example' });
example.get('mandatory'); // 'example'
example.unset('mandatory'); // allowed
example.get('mandatory'); // undefined
```

You could conceivably change the Backbone typings so that TS will refuse to `unset` a required attribute, but at that point, you're deviating pretty far from the actual semantics of Backbone itself. On top of `Partial<>` already being a sort of norm in JavaScript in general, Jeremy Ashkenas has also made a conscious choice to consider all attributes optional specifically in Backbone's `Model`. `Model` should really be thought of as a free-form key-value store.

In the end, I think TS is just a tool and we shouldn't force its conventions onto pre-existing libraries. Rather, we should stretch the typings to match the real situation as closely as possible. I think @khasanovbi did a pretty accurate job returning `T[A] | undefined` from `get`. `T` lets you enforce that particular attributes be set in the constructor and lets you prevent developers from making up new attribute names on the spot, which I think is already a luxury compared to what you get from Backbone itself.
