### ISSUE TITLE
Last Long.js change brakes browser support.

### ISSUE THREAD

**Issue by eugenega** [DefinitelyTyped/DefinitelyTyped#5731]
This is a defect.
The current Long.d.ts supports only "require" for RequireJS or CommonJS, e.g. var long = require("long");. New definition no longer supports plain web browser. In the previous long.d.ts version there were lines that support browser
 // for browser
 declare module dcodeIO {
 export var Long:LongStatic;
 }
 Now they are deleted. Need to return it.

**Comment by vvakame** [comment]
@eugenega please send a pull request. I'll review it.

**Comment by eugenega** [comment]
I sent pull request. Please review.

**Comment by eugenega** [comment]
I sent pull request. Please review.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
