### ISSUE TITLE
/angularjs/angular.d.ts - IAnimateService.addClass wrong signature

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/DefinitelyTyped#5807]
I believe this needs to go from something like:
addClass(element: JQuery, className: string, done?: Function): IPromise<any>;
to:
addClass(element: JQuery, className: string, done?: animate.IAnimationOptions): IPromise<any>;

https://docs.angularjs.org/api/ngAnimate/service/$animate

**Comment by vvakame** [comment]
@mif007 please send a pull request. I'll review it.

**Comment by mif007** [comment]
#5919

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
