### ISSUE TITLE
Durandal.d.ts file out of sync with current release

### ISSUE THREAD

**Issue by rwhepburn** [DefinitelyTyped/DefinitelyTyped#585]
The current release of Durandal is version 1.2.0 but the Durandal.d.ts file is currently only updated for 1.1.1. Some important functions are missing (e.g. onNavigationComplete function in the Router Plug-In).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
