### ISSUE TITLE
jqueryui.d.ts - missing properties in TooltipOptions and TooltipUIParams

### ISSUE THREAD

**Issue by pboucher1960** [DefinitelyTyped/DefinitelyTyped#5876]
Based on actual code in the jQueryUI library (v 1.14.4) interface TooltipOptions is missing close and open properties and should be:

```
interface TooltipOptions {
    content?: any; // () or string
    disabled?: boolean;
    hide?: any; // boolean, number, string or object
    items?: string;
    position?: any; // TODO
    show?: any; // boolean, number, string or object
    tooltipClass?: string;
    track?: boolean;
    close?: TooltipEvent;
    open?: TooltipEvent;
}
```

Interface TooltipUIParams is currently empty but it should be

```
interface TooltipUIParams {
    tooltip?: Tooltip;
}
```

Thanks!

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
