### ISSUE TITLE
CRLF in PhoneGap files corrupts my transpiled JS files

### ISSUE THREAD

**Issue by matheo** [DefinitelyTyped/DefinitelyTyped#5881]
Hi!
I just wanted to report some CRLF line endings on:
cordova/plugins/Globalization.d.ts
phonegap/phonegap.d.ts
that are disturbing my LF transpilation.

Seems that once Atom process an CRLF, it uses that EOL instead my configured LF.
Thanks for the attention on this matter

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
