### ISSUE TITLE
jqueryui.d.ts - missing event handlers in AutocompleteOptions

### ISSUE THREAD

**Issue by 3hs4n** [DefinitelyTyped/DefinitelyTyped#5894]
Based on actual code in the jQueryUI library and API documentation, the interface AutocompleteOptions is missing event handlers such as (open, focus, etc). I suggest the interface to extends AutocompleteEvents, i.e.

``` javascript
interface AutocompleteOptions extends AutocompleteEvents {
...
}
```

**Comment by vvakame** [comment]
@3hs4n please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
