### ISSUE TITLE
React.js Props "ref" type

### ISSUE THREAD

**Issue by kuon** [DefinitelyTyped/DefinitelyTyped#6041]
I tried to change the props type in the PR https://github.com/borisyankov/DefinitelyTyped/pull/6040

But I noticed the tests where not passing.

The original discussion leading to the fix is here: https://github.com/Microsoft/TypeScript/issues/4682

Anybody who has more insight on the react definition file can look at it?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
