### ISSUE TITLE
'pipes' property is missing from the ViewFactory interface in the angular 2 type definition

### ISSUE THREAD

**Issue by deeleman** [DefinitelyTyped/DefinitelyTyped#6056]
The title says it all. When checking the ViewFactory interface in the angular2 definition type we can see that the `pipes` property is missing, thus preventing certain IDEs (such as Atom) to build the file or raise exceptions.

``` typescript
  interface ViewFactory {

     new(obj: {
    templateUrl?: string,
    template?: string,
    directives?: Array<Type | any | any[]>,
    pipes?: Array<Type | any | any[]>, // <- Missing!
    encapsulation?: ViewEncapsulation,
    styles?: string[],
    styleUrls?: string[],
  }): ViewMetadata;
```

**Comment by alexeagle** [comment]
Could you try the pre-release of alpha-41, which uses a different typings distribution?
Or just provide a repro (sample file using pipes property) and I'll verify.

https://github.com/alexeagle/angular2-distro/blob/master/README.md

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
