### ISSUE TITLE
conflict in require.d.ts

### ISSUE THREAD

**Issue by ken-blocklevel** [DefinitelyTyped/DefinitelyTyped#6083]
I have setup a node js server using commonjs serverside and amd client side. when using ///<reference path="path/to/require.d.ts" /> in the client code, i get a conflict while compiling code.

require.d.ts(368,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.

This issue I believe, comes from the node.d.ts. Even though I am not using a reference to that type defenition (node.d.ts) in clientside code, so that's strange. It is the only file in my project containing the word 'NodeRequire'. However, like I said I am not using a reference to that code clientside.

the client app.ts file:

```
/// <reference path="../../typings/requirejs/require.d.ts" />

requirejs.config(
    {
        baseUrl: 'output',

        paths: {
            'socket.io': '../socket.io/socket.io.js'
        }
    }
);

require(['./main']);
```

update

The problem is the fact that I ám loading 'socket.io.d.ts' in another file, and 'socket.io.d.ts' loads 'node.d.ts'. However, knowing this doesn't resolve the conflict. These files should be usable combined. Also, the word 'require' is used often by requirejs and node...

![screen shot 2015-10-01 at 13 27 15](https://cloud.githubusercontent.com/assets/14290569/10219553/32098a28-6840-11e5-80ed-9e0dba0e2274.png)

**Comment by billccn** [comment]
TypeScript transitively load `d.ts` files, so somewhere in the definition files you use for your client side `node.d.ts` was referenced. Alternatively, it could be included via `tsconfig.json` or the compiler command line.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
