### ISSUE TITLE
Out of Date Chance.js Library

### ISSUE THREAD

**Issue by mperrenoud** [DefinitelyTyped/DefinitelyTyped#6087]
The definition for Chance.js is out of date. Specifically the mixin definition has changed for sure. Previously it expected a single string and function pair, now it accepts an entire object.

Please update the definitions.

Thanks!

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by mperrenoud** [comment]
After some more review I found that it may not be completely out of date, I just know of one very specific change needed for the type script definitions. I can make that pull request for you.

**Comment by mperrenoud** [comment]
It produced a 403 when trying to push to my new branch so I could build a pull request:

    Michaels-MBP:DefinitelyTyped mike$ git push origin update-chance-typings
    Username for 'https://github.com': mperrenoud
    Password for 'https://mperrenoud@github.com': 
    remote: Permission to borisyankov/DefinitelyTyped.git denied to mperrenoud.
    fatal: unable to access 'https://github.com/borisyankov/DefinitelyTyped.git/': The requested URL returned error: 403

Do you need to provide me permissions to contribute?
This is my first time contributing to a GitHub project that's open like this.
Did I miss a step?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
