### ISSUE TITLE
WHY Remove types for TS <=3.9 ?? 

### ISSUE THREAD

**Issue by neekychan** [DefinitelyTyped/DefinitelyTyped#60907]
why Remove types for TS <=3.9 , by a tiny version update???

there are many ts3.x project running online.

after rm 3.9 types support,we must upate all project with ts4, it's dangerous.

please ,rollback this version, and release @types/whatwg-url as 9.x version.

some base lib dependences @types/x, we can't change it depend version directly, so we have to update ts3 to 4, it's not easy.

@jablko

**Comment by jablko** [comment]
<del>

Can you install `@types/whatwg-url` version 8.2.1 (the last version [with support for TS 3.9](https://www.npmjs.com/package/@types/whatwg-url?activeTab=versions)) by using:
```sh
npm install --tag ts3.9 @types/whatwg-url
```

If you *directly* depend on `@types/whatwg-url` from a project that supports TS <4.0, can you use something like the following, in your package.json dependencies:
```json
"@types/whatwg-url": "ts3.9"
```

</del>

> some base lib dependences @types/x, we can't change it depend version directly, so we have to update ts3 to 4, it's not easy.

Re-reading your issue I see the problem is a transitive dependency of `@types/x` on `@types/whatwg-url`. For projects that support TS <4.0, the best solution is to commit an [`.npmrc`](https://docs.npmjs.com/cli/v8/configuring-npm/npmrc) config file to the project, containing:
```npmrc
tag=ts3.9
```
I think? See https://docs.npmjs.com/cli/v8/using-npm/config#tag

That, or use `"@types/whatwg-url": "ts3.9"` in [npm `overrides`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) or [Yarn `resolutions`](https://yarnpkg.com/configuration/manifest#resolutions)?

To rollback the change and keep the TS <=3.9 types we'd first need a [change to the DT CI](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60786#issue-1269453583) --- and probably a change to the [support window](https://github.com/DefinitelyTyped/DefinitelyTyped#support-window)?

**Comment by neekychan** [comment]
> Re-reading your issue I see the problem is a transitive dependency of `@types/x` on `@types/whatwg-url`. For projects that support TS <4.0, the best solution is to commit an [`.npmrc`](https://docs.npmjs.com/cli/v8/configuring-npm/npmrc) config file to the project, containing:

Thanks you.this way is work normally.But we build project with Company's CI machine online. They rm .npmrc file on building progress. So still not work.

we update ts3 to ts4 temporary。 T_T

**Comment by neekychan** [comment]
We have reslove this problem.
thanks jablko.
we update our tnpm package.json.
set resolutions options, just like yarn
"resolutions": {
    "@types/whatwg-url": "ts3.9"
  },
