### ISSUE TITLE
lodash.d.ts findKey etc broken when predicate is a function

### ISSUE THREAD

**Issue by vivainio** [DefinitelyTyped/DefinitelyTyped#6100]
lodash.d.ts findKey does this:

``` typescript
        findKey(
            object: any,
            callback: (value: any) => boolean,
            thisArg?: any): string;
```

The callback, however, takes 3 arguments: (value, index|key, collection).

This should be changed to accommodate for index and collection.

The same applies to several other places where predicate is expected.

**Comment by vivainio** [comment]
Pull request that implements this added

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
