### ISSUE TITLE
CI Build Optimization

### ISSUE THREAD

**Issue by Jojoshua** [DefinitelyTyped/DefinitelyTyped#62319]
CI Builds are very slow. It's wasting time and resources. Does the whole kitchen sink really need to be brought in in order to run the tests for a single package?

**Comment by malthe** [comment]
10,000+ this, the current setup is insane.

**Comment by jakebailey** [comment]
This issue is ancient; the current DT infrastructure installs the absolute minimum amount of packages possible, then tests only packages that are affected. The only thing it doesn't do is use multiple machines (which is on my personal TODO).

Can you please clarify why the "current setup is insane"? Do you have an example of something that was slower than expected?

**Comment by malthe** [comment]
I'm just seeing builds (failed ones, admittedly) take 90+ minutes to complete on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67978.

**Comment by jakebailey** [comment]
Yes, touching node is huge because it has to verify that 2000+ other packages still work as it's one of the most depended on packages. Adding parallel jobs should help with that.

(The perf of such a change was _much_ worse a few months ago.)

**Comment by malthe** [comment]
Thanks, appreciate it. Makes sense.

**Comment by malthe** [comment]
But okay, even with 2,000 packages needing to get installed and tested, that leaves 2.7 seconds for each one without parallelism. I would think that with caching and running with a reasonable parallelism, e.g. 8x – the total runtime could be considerably less than 90 minutes.

**Comment by jakebailey** [comment]
`dtslint` checks each package against 10 versions of TypeScript, as well as a bunch of eslint rules which use types themselves. A change in a dependency could affect any of them (we had to recently ensure that more stuff was tested as it turned out many oopses were not caught), so there's really not any caching that can be done.

**Comment by jakebailey** [comment]
As for general performance, there is of course profiling that could be done on some of our rules to figure out what low hanging fruit there is there.

**Comment by jakebailey** [comment]
I just merged a PR which shards the tests and moves everything to GHA (whose runners have 2x the cores of Pipelines).

For an average `@types/node` PR, this should reduce CI time from 2-3 _hours_ down to _15 minutes_.
