### ISSUE TITLE
redux-thunk and TypeScript 1.6

### ISSUE THREAD

**Issue by schlaup** [DefinitelyTyped/DefinitelyTyped#6231]
The definitions for redux-thunk do not seem to work with TypeScript 1.6.

From the test:

import thunk from 'redux-thunk';

Error: "thunk" is undefined

import \* as thunk from 'redux-thunk';

the compiler complains at this line: (wrong type)

```
    applyMiddleware(thunk),
```

My workaround:

```
    import * as thunk from 'redux-thunk';
    ...
    applyMiddleware(<any> thunk),
```

does work.

My guess is a mixup of old commonjs style (default) exports and new ES6 modules.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by Strate** [comment]
Here is my `redux-thunk` definitions:

```ts
declare module 'redux-thunk' {
    import {MiddlewareArg} as Redux from 'redux'
    export default function(obj: MiddlewareArg): Function
}
```

**Comment by louy** [comment]
You need to change it to this:

```
export = function(obj: MiddlewareArg): Function
```

and remove previous `export`s

**Comment by oheard** [comment]
I've just ran into this issue. Any news on status?

**Comment by born2net** [comment]
+
   import * as thunk from 'redux-thunk';
fixed my issues in TS as well..

**Comment by born2net** [comment]
+1
  import * as thunk from 'redux-thunk';
    ...
    applyMiddleware(<any> thunk),
worked !!!!!

**Comment by HenrikBechmann** [comment]
I replaced the tsd-installed definition with this:
```
declare module 'redux-thunk' {
    import {MiddlewareArg} from 'redux'
    export default function(obj: MiddlewareArg): Function
}
```
using typescript 1.8.2, redux-thunk 2.0.1

mainline:

```
import thunk from 'redux-thunk'
...
const reduxRouterMiddleware = routerMiddleware(browserHistory)

const store = createStore(
    mainReducer,
    applyMiddleware(reduxRouterMiddleware, thunk)
)

```
that worked.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
