### ISSUE TITLE
Do not use sys.p()

### ISSUE THREAD

**Issue by ChALkeR** [DefinitelyTyped/DefinitelyTyped#6232]
https://github.com/borisyankov/DefinitelyTyped/blob/master/async/async-tests.ts#L396-L398
It is going away: https://github.com/nodejs/node/pull/2529.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by ChALkeR** [comment]
I'm not using DefinetelyTyped, nor TypeScript. I'm not even sure where does `sys` come from in that file.
Hence no pull request.

**Comment by ChALkeR** [comment]
Note that `util.p()` (aka `sys.p()`) has been removed already.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
