### ISSUE TITLE
Circular dependency with serve-static

### ISSUE THREAD

**Issue by tamasfoldi** [DefinitelyTyped/DefinitelyTyped#6265]
Hi,

I'm trying to add it via NuGet Package Manager, and I receive and error which says that there is a circular dependency with serve static.
> Install-Package : Circular dependency detected 'express.TypeScript.DefinitelyTyped 2.1.7 => mime.TypeScript.DefinitelyTyped 0.0.1 => node.TypeScript.DefinitelyTyped 1.7.8 => serve-static.TypeScript.DefinitelyTyped 0.0.4 => express.TypeScript.DefinitelyTyped 2.1.7'.

Can you fix this somehow?

**Comment by vvakame** [comment]
@staxmanade ?

**Comment by staxmanade** [comment]
It looks like there is a circular reference:

https://github.com/borisyankov/DefinitelyTyped/blob/master/express/express.d.ts#L14
https://github.com/borisyankov/DefinitelyTyped/blob/master/serve-static/serve-static.d.ts#L13

The root circular reference will have to be addressed.

**Comment by flcdrg** [comment]
From what I can gather, the root problem is:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/express/express.d.ts#L1077

I had a go at making an 'express-core.d.ts' file by moving everything except the `var static..` line (so it didn't depend on serve-static), but can't figure out how to declare the modules so that they 'merge' when you reference express.d.ts and express-core.d.ts together.

Maybe this isn't possible or the wrong approach.

**Comment by staxmanade** [comment]
Closing issue - track in PR for now.

**Comment by flcdrg** [comment]
Note for anyone upgrading from the old versions now that the PR has been merged. You'll need to manually remove the old packages to get over the 'dependency hump'.

```
uninstall-package express.TypeScript.DefinitelyTyped -Force
uninstall-package serve-static.TypeScript.DefinitelyTyped -Force
install-package express.TypeScript.DefinitelyTyped  -DependencyVersion Highest
```

Hopefully from now on, this problem won't reoccur on future package updates.
