### ISSUE TITLE
dds module is not defined

### ISSUE THREAD

**Issue by nugetchar** [DefinitelyTyped/DefinitelyTyped#6269]
When trying to run the following : [vortex-web-client.ts](https://github.com/borisyankov/DefinitelyTyped/blob/master/vortex-web-client/vortex-web-client-tests.ts), dds module is undefined.

Reference path is correct.
Compilation done with grunt : 
- module : commonjs
- target : es5

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
