### ISSUE TITLE
angular.d.ts: Value of type 'IQService' is not callable. Did you mean to include 'new'?

### ISSUE THREAD

**Issue by vivainio** [DefinitelyTyped/DefinitelyTyped#6285]
I'm trying to do 

``` typescript

       // q is ng.IQService

        return this.$q((resolve, reject) => {
        }
```

But I get:

```
Error TS2348: Value of type 'IQService' is not callable. Did you mean to include 'new'?
```

ng.IQService should be callable to use the 'streamlined ES6 style promise' API of $q.

**Comment by chrootsu** [comment]
Maybe it is a problem of outdated definitions, because needed signatures already exist https://github.com/borisyankov/DefinitelyTyped/blob/8c7a7d07c908ee10a23c3c636ca7c2d4b49a65d4/angularjs/angular.d.ts#L997-L998
The same issue https://github.com/borisyankov/DefinitelyTyped/issues/5777

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
