### ISSUE TITLE
Mocha - Missing variable IContextDefinition

### ISSUE THREAD

**Issue by jessebuitenhuis** [DefinitelyTyped/DefinitelyTyped#6319]
I'm trying to get rid of `describe()` and `it()` warnings in WebStorm. After installing the Mocha library, the 'unresolved' warning changed into an `Method expression is not of Function type`.

It seems there is no IContextDefinition in this file:
https://github.com/borisyankov/DefinitelyTyped/blob/master/mocha/mocha.d.ts#L40

What should I do or install to fix this error? Thanks in advance!

**Comment by vvakame** [comment]
sorry i don't know. do you use TypeScript feature?

**Comment by rcchen** [comment]
`IContextDefinition` is defined as an interface here: https://github.com/borisyankov/DefinitelyTyped/blob/master/mocha/mocha.d.ts#L154

**Comment by misea** [comment]
IntelliJ/WebStorm's Typescript interpreter doesn't seem to want to merge 'declare class Mocha' with 'declare module Mocha' until after both are declared. I am very new to Typescript so don't know whether this is a problem with the declaration or IntelliJ's implementation. 

If you move the global var exports to *below* the module declaration IntelliJ is happier.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
