### ISSUE TITLE
Update Durandal.d.ts to support TypeScript 0.9

### ISSUE THREAD

**Issue by rwhepburn** [DefinitelyTyped/DefinitelyTyped#633]
The durandal.d.ts file needs to be updated to leverage TypeScript 0.9 features. 

It seems KnockoutJS has already added support for TypeScript 0.9 (e.g. Generics) in knockout.d.ts. Since there is a dependency between durandal.d.ts and knockout.d.ts it means that durandal.d.ts needs to be updated to reference the new Knockout Generic Types.

Complicating this, there is a new version of Durandal 2.0 just around the corner so I'm not sure if this needs to be fixed now or wait for Durandal 2.0 to release?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
