### ISSUE TITLE
Update express-validator to latest

### ISSUE THREAD

**Issue by Joshua-F** [DefinitelyTyped/DefinitelyTyped#6339]
Changes that I've found between 2.9.0 and 2.17.1
- Validation schema (ctavan/express-validator#145)
- `withMessage(string)` added (ctavan/express-validator#159)
- `asyncValidationErrors()` added to `Express.Request` (ctavan/express-validator#164)

Ref https://github.com/ctavan/express-validator/compare/v2.9.0...v2.17.1

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
