### ISSUE TITLE
allow any property name as return type

### ISSUE THREAD

**Issue by heycalmdown** [DefinitelyTyped/DefinitelyTyped#6353]
I have an issue during writing a piece of declaration for existing node.js module - bluebird.js. The module has a method named `props` which gets an object has promises in it then return an object have same property names. It seems like object-version `map`. I wanted to add types for that.

For `all` I can easily get the types like

``` typescript
  static all<T1, T2>(values: [Promise.Thenable<T1>, Promise.Thenable<T2>]): Promise<[T1, T2]>;
  static all<T1, T2, T3>(values: [Promise.Thenable<T1>, Promise.Thenable<T2>, Promise.Thenable<T3>]): Promise<[T1, T2, T3]>;
  // ...
```

But for `props` the other hand,

``` typescript
  static props<T1>(object: {[k:string]: Promise.Thenable<T1>}): Promise<{[k:string]: T1}>;
```

I'm getting this

```
bluebird/bluebird-tests.ts(530,10): error TS2339: Property 'foo' does not exist on type '{ [k: string]: Foo; }'.
bluebird/bluebird-tests.ts(534,10): error TS2339: Property 'bar' does not exist on type '{ [k: string]: Bar; }'.
```

Is there any tip for issue like this?

**Comment by use-strict** [comment]
The error is provided out of context. I assume you have a modified `bluebird-tests.ts` file. Can you paste the code that errors?

**Comment by heycalmdown** [comment]
I also opened new thread at https://github.com/Microsoft/TypeScript/issues/5305
It's a question about a best practice and know how to make good typings. On the other hand, it is about the language itself. Sorry for duplication.

Any thought?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
