### ISSUE TITLE
Three.js - Property 'defines' is missing in type 'Material'

### ISSUE THREAD

**Issue by LucasBertrand** [DefinitelyTyped/DefinitelyTyped#6354]
Hello ! 

Here is my code :

```
let geometry: any = this._geometries.get( renderer.geometry );
let material: THREE.Material = this._materials.get( renderer.material );
...
let obj: THREE.Object3D = new THREE.Line( geometry, material ); // error
```

'Argument of type 'Material' is not assignable to parameter of type 'ShaderMaterial'. Property 'defines' is missing in type 'Material'.

Edit : Sorry, I verified the d.ts and this defines property is absent in the main class Material. Don't consider this issue. Have a good day !

**Comment by vvakame** [comment]
@gyohk ?

**Comment by gyohk** [comment]
THREE.Line class should accept following three types as 'material' argument.
・LineBasicMaterial
・LineDashedMaterial
・ShaderMaterial

Thank you for reporting your problem.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
