### ISSUE TITLE
require.d.ts error TS2300: Duplicate identifier 'bundles'

### ISSUE THREAD

**Issue by tstar** [DefinitelyTyped/DefinitelyTyped#6376]
requirejs/require.d.ts(93,2): error TS2300: Duplicate identifier 'bundles'.
requirejs/require.d.ts(133,2): error TS2300: Duplicate identifier 'bundles'.

Thanks.

**Comment by Strate** [comment]
:+1:

**Comment by bmdixon** [comment]
+1

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
