### ISSUE TITLE
request-promise.d.ts cannot access directly to request.jar()

### ISSUE THREAD

**Issue by jdavanne** [DefinitelyTyped/DefinitelyTyped#6408]
I'm having an typescript warning using `request.jar()` when using `request-promise`...
Can `request-promise.d.ts` be updated ?

I suppose this is also the case for other request direct calls : (from `request.d.ts`)

``` typescript
export function forever(agentOptions: any, optionsArg: any): Request;
export function jar(): CookieJar;
export function cookie(str: string): Cookie;
```

**Comment by davinci1976** [comment]
May I suggest a fix like :
```typescript
    module RequestPromiseAPI {
        export interface Options extends request.Options {
            simple?: boolean;
            transform?: (body: any, response: http.IncomingMessage) => any;
            resolveWithFullResponse?: boolean;
        }

        export function jar(): request.CookieJar; // <-- Add this ?
    }
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
