### ISSUE TITLE
Automatically generate TypeScript definitions

### ISSUE THREAD

**Issue by bartosz-k** [DefinitelyTyped/DefinitelyTyped#6433]
I have an idea for semi-automatic .d.ts files generation - where is the best place to start a discussion? I'm writing it here couse I didn't find any kind of forums.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
