### ISSUE TITLE
i dont know where to submit definition

### ISSUE THREAD

**Issue by werddomain** [DefinitelyTyped/DefinitelyTyped#6459]
i have created a definition for i plugin i love: bootstrap-switch

pasebin: http://pastebin.com/TRYaQcac

// Type definitions for bootstrap-switch 3.3.2
// Project: https://github.com/nostalgiaz/bootstrap-switch
// Definitions by: Benoit Robin (werddomain@gmail.com)
// Definitions: <Not Listed>

**Comment by tkrotoff** [comment]
Read this guide: http://definitelytyped.org/guides/contributing.html
When everything ok, make a pull request like for any other GitHub repository

**Comment by horiuchi** [comment]
LGTM :+1:

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
