### ISSUE TITLE
Unable to get office-js Type script definition through nuget 

### ISSUE THREAD

**Issue by hitendramalviya** [DefinitelyTyped/DefinitelyTyped#6470]
I am unable to get Type script definition through nuget & package mangers shows error message saying  `Unable to resolve dependencies. 'bootstrap 3.0.0' is not compatible with 'Twitter.Bootstrap 3.0.1.1 constraint: bootstrap (≥ 
3.0.1)'.`
`At line:1 char:1`
`+ Install-Package office-js.TypeScript.DefinitelyTyped`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`+ CategoryInfo          : NotSpecified: (:) [Install-Package], Exception`
`+ FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand`

**Comment by vvakame** [comment]
@staxmanade ?

**Comment by staxmanade** [comment]
That's strange because there are no dependencies specified for this package: http://www.nuget.org/packages/office-js.TypeScript.DefinitelyTyped/0.0.3

@hitendramalviya can you check other packages you have installed? (The `Twitter.Bootstrap` package http://www.nuget.org/packages/Twitter.Bootstrap required >= 3.0.1 of `bootstrap`) (but none of these from what I can tell are controleld by DefinitelyTyped nuget packages...

**Comment by hitendramalviya** [comment]
First of all I must say sorry for late response & thanks to @vvakame & @staxmanade for their early response.
There are some issue with my solution package manager, there were duplicate package presents in solution. After removing duplicate Twitter.Bootstrap package It is installing properly without any error message.
