### ISSUE TITLE
gridfs-stream.d.ts: Missing fineOne & curCol

### ISSUE THREAD

**Issue by jaalfaro** [DefinitelyTyped/DefinitelyTyped#6487]
gridfs-stream.d.ts does not define the fineOne function or the curCol property.

**Comment by jaalfaro** [comment]
Pull request to address this ticket.#6506.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
