### ISSUE TITLE
[react-intl] Version 2.0.0 is in beta. Working on a definition

### ISSUE THREAD

**Issue by cdroulers** [DefinitelyTyped/DefinitelyTyped#6518]
I've forked the repo and started working on the definition : https://github.com/cdroulers/DefinitelyTyped/tree/master/react-intl

I'd love feedback, especially from @bgrieder since he wrote the definition for 1.2.0! I haven't created tests yet, but that'll come very soon.

Is the naming convention for both supported versions ok?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
