### ISSUE TITLE
"tsd history" --> browserstate/history.js name shadows rackt/history

### ISSUE THREAD

**Issue by sebastiankr** [DefinitelyTyped/DefinitelyTyped#6524]
npm install history refers to https://github.com/rackt/history and not https://github.com/browserstate/history.js.

How is that resolved? 
1 . Rename current history to historyjs?
2. Create new tsd name like 'rackthistory' and deviate from npm name?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
