### ISSUE TITLE
knockout.d.ts has a parameter that needs to be optional on KnockoutStatic.applyBindingsToNode

### ISSUE THREAD

**Issue by tandyjames** [DefinitelyTyped/DefinitelyTyped#672]
basically:
    applyBindingsToNode(node: Element, options: any, viewModel: any): void;
needs to be:
    applyBindingsToNode(node: Element, options: any, viewModel?: any): void;

I have an extension from the web which uses this without passing the viewModel and it works fine.
Not sure if there are other similar spots.
Thanks for keeping up this library!

**Comment by ltlombardi** [comment]
@vvakame This should be closed. Already fixed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
