### ISSUE TITLE
React-bootstrap contribution

### ISSUE THREAD

**Issue by sqrtroot** [DefinitelyTyped/DefinitelyTyped#6732]
Hi all,

The react-bootstrap definition was missing a definition for collapse https://react-bootstrap.github.io/components.html#utilities-collapse

I created the definition but don't know how to add it to this project

``` Typescript
    // <Collapse />
    // ----------------------------------------
    interface CollapseProps{
        dimension?: string;
        getDimensionValue?: Function;
        in?: boolean;
        onEnter?: Function;
        onEntered?: Function;
        onEntering?: Function;
        onExit?: Function;
        onExited?: Function;
        onExeting?: Function;
        role?: string;
        timeout?: number;
        transitionAppear?: boolean;
        unmountOnExit?: boolean;
    }
    interface Collapse extends React.ReactElement<CollapseProps> { }
    interface CollapseClass extends React.ComponentClass<CollapseProps> { }
    var Collapse: CollapseClass;
```

Can anyone help me?

**Comment by vvakame** [comment]
https://help.github.com/articles/using-pull-requests/

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
