### ISSUE TITLE
Typescript 0.9 add missing interface Read/Writable observable

### ISSUE THREAD

**Issue by SebaVDP** [DefinitelyTyped/DefinitelyTyped#676]
I need to create a function that accept all multiple overloaded parameters
Here is my example:

``` Typescript
class AClass {

IsVisible: ???;

MyMethod(param: KnockoutObservable<boolean>);
MyMethod(param: KnockoutComputed<boolean>);
MyMethod(param: boolean);
MyMethod(param: any)
{
    if (ko.isObservable(param) === true || ko.isComputed(param) === true) {
        this.IsVisible = param;
    }
    else {
        this.IsVisible = ko.observable(param);
    }
}

ToggleVisible(){
    this.IsVisible(!this.IsVisible());
 }
```

I would like to use an interface to define IsVisible.
Is it possible to add a "similar" interface

``` Typescript
interface KnockoutReadWritable<T> {
    (value: T): void;
    ():  T;
}

```

and of course extending current interfaces in knockout

``` Typescript
interface KnockoutObservable<T> extends KnockoutObservableBase, KnockoutReadWritable<T>{
     // ...
}
interface KnockoutObservableArray<T> extends KnockoutObservableArrayFunctions<T>, KnockoutReadWritable<T[]>{
     // ...
}
interface KnockoutComputed<T> extends KnockoutComputedFunctions, KnockoutReadWritable<T>{
     // ...
}
```

Thnx

**Comment by Retsam** [comment]
Pretty old issue, I think this is covered: `KnockoutComputed` extends `KnockoutObservable` which is read/writable.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
