### ISSUE TITLE
editorconfig + tsconfig settings for consistency and cleanup

### ISSUE THREAD

**Issue by jesperronn** [DefinitelyTyped/DefinitelyTyped#6834]
#4214 introduced editorconfig.

In the files I was looking, we had both tabs in stead of spaces, and lines with trailing whitespace.

Furthermore, my editor (Atom) default tslint settings flags things as singlequotes being used in stead of doublequotes.

I really like consistency, and I think all typings in this repos should be treated equally and consistently :)

I suggest these settings:

`.editorconfig`:

```
insert_final_newline = true
indent_style = space
indent_size = 4
```

and

for linting:
- prefer single quotes

There may be dependencies to other software projects which I am not aware of. Please share your thoughts here :)

**Comment by jesperronn** [comment]
Just realizing these two pieces of information

* Contribution guide: [Coding Style](http://definitelytyped.org/guides/contributing.html#code-style)
* (Discussion in #1709)[https://github.com/DefinitelyTyped/DefinitelyTyped/issues/1709]

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
