### ISSUE TITLE
WebGLRendererParameters missing logarithmicDepthBuffer

### ISSUE THREAD

**Issue by alexpyzhianov** [DefinitelyTyped/DefinitelyTyped#6837]
The interface `WebGLRendererParameters` is missing property `logarithmicDepthBuffer` that is obviosly present
http://threejs.org/docs/#Reference/Renderers/WebGLRenderer

**Comment by vvakame** [comment]
@gyohk ?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
