### ISSUE TITLE
Function requiring IVector<string> does not accept string array

### ISSUE THREAD

**Issue by wwrafter** [DefinitelyTyped/DefinitelyTyped#6842]
In a Windows 10 Universal app, I'm trying to use the FileSavePicker to select a file. I am using Typescript. The insert method takes two parameters, a string and an IVector. The following code is from the MS website, but it is just straight javascript.

savePicker.fileTypeChoices.insert("Word Document", [".docx"]);

The error text is, "Argument of type string[] is not assignable to parameter of type IVector". I have been able to get it to work using this:

var tempVec: Windows.Foundation.Collections.IVector;
tempVec.append(".docx");
savePicker.fileTypeChoices.insert("Word Document", tempVec);

That seems unreasonably verbose. Is there a better syntax for accomplishing this?

http://stackoverflow.com/questions/33792978/how-to-pass-ivectorstring-in-typescript

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
