### ISSUE TITLE
FullCalendar missing options

### ISSUE THREAD

**Issue by werddomain** [DefinitelyTyped/DefinitelyTyped#6893]
FullCalendar.Options is missing these options :

lang?: string;
nextDayThreshold?: string;
eventLimit?: boolean;

**Comment by neooleg** [comment]
This is because repository contains definitions for FullCalendar 1.6.1. While all mentioned options were added with 2.0 version, see details at [Info on upgrading to version 2](http://fullcalendar.io/wiki/Upgrading-to-v2/).

So the definitions need to be updated up to FullCalendar 2.0 version.

It would be great if you rename the issue for this.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
