### ISSUE TITLE
dojox module declarations don't work in typescript 1.6

### ISSUE THREAD

**Issue by pierssen** [DefinitelyTyped/DefinitelyTyped#6930]
Please correct me if I'm doing something wrong, but I'm trying to use dojox.charting.d.ts, and I cannot get the module declarations to work.

For example:

declare module "dojox/charting/Chart" {
    var exp: dojox.charting.Chart
    export=exp;
}

If I change it to this, then my code compiles and runs nicely:

declare module "dojox/charting/Chart" {
    import exp = dojox.charting.Chart;
    export=exp;
}

**Comment by vvakame** [comment]
@vansimke ?

**Comment by vansimke** [comment]
I've looked at it and I think that @pierssen is right. If I recall correctly, the syntax in the files would imply that an object of that type will be returned (i.e. a singleton as in dojo/router). However, if a class definition needs to be returned, then the proposed change is correct.

**Comment by dgwaldo** [comment]
This has been a fairly large pain point for me.  I have a modified typing file broken out to fix this in my project, I suppose I should make a PR and submit it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
