### ISSUE TITLE
Mongo typings don't include promise alternatives

### ISSUE THREAD

**Issue by simonh1000** [DefinitelyTyped/DefinitelyTyped#6939]
Mongo originally used callbacks, but they now support Promises. These are not included in the current typings.

**Comment by Think7** [comment]
I started on this today. 

You can download my version here: http://puu.sh/lFi1N/5b2a16d66e.ts

It is NOT complete and i still have a ways to go. But the Collection class where most of the essential operations happen should be better than what is currently offered.

Both versions of the official methods are supported:

```
method(query, options?): Promise
```
and

```
method(query, options?, callback?): void | Promise
```

Notice the second call will return either a promise or void depending on if you give it a callback. It FELT better to have two separate definitions but it is a bit redundant. Let me know your thoughts.

**Comment by simonh1000** [comment]
Hi, this is fantastic and has addressed a number of my error messages. I'm confused about your edit though as that seems to be about MongoDB, rather than Mongoose

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
