### ISSUE TITLE
version 4.17.1，the type of the data variable is inferred to never by _.has

### ISSUE THREAD

**Issue by xujintai123** [DefinitelyTyped/DefinitelyTyped#69528]
**issue：**
on 4.17.1 version，the type of the data variable is inferred to never by _.has。
![image](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/66779465/44a910ef-4096-4c5f-82f8-4fd03c8e4cd5)

**source of problem：**
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69291
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/1c01676bd56522b1eb13f7e4e0a2415773c535a6#diff-0740e38db2dd38b18fb8612ceef08349585a3d898fb6ad21522819b8677804f7

**Comment by aj-r** [comment]
I'm surprised it narrows the type to `never` - we have tests to ensure the type remains `T` when `_.has` returns false.

I'm guessing the issue is that `data`'s type requires `level` to be set, so our type guard simplifies to `object is T`. Thus typescript thinks `_.has` can never return false, which would be correct as far as the type system is concerned.

Why do you need to use `_.has()` in this case? Can you simply remove it and assume the property is set? If not, consider changing the type to make the property optional. Or use `Object.hasOwnProperty()` instead.

**Comment by aj-r** [comment]
Ah, I just noticed #69534 which should fix this.

**Comment by tidhar-ziv** [comment]
This issue is still not solved in version 4.17.4
``` ts
import _ from "lodash";

function test(doc: any) {
    if (_.has(doc, "something")) {
    }
    else {
        doc["something"] = true;
    }
}
```
This code will trigger "TS2322: Type 'boolean' is not assignable to type 'never'."

**Comment by aj-r** [comment]
That seems like reasonable behavior IMHO - if TS thinks the propery doesn't exist then it won't let you set it. If you want to treat the object as a map, use something like `Record<string, boolean>` (or maybe `Record<string, any>`) instead of `any`.

**Comment by tidhar-ziv** [comment]
equivalent non lodash code doesn't give an error"
``` ts
function test(doc: any) {
    if (doc.hasOwnProperty("something")) {
    }
    else {
        doc["something"] = true;
    }
}
```
the type of doc is "any", why would _.has change that? not sure it's lodash job to "discipline" developers, too opinionated, and anyway this is a breaking change, as that was not the behavior in version "4.17.0"
