### ISSUE TITLE
Bluebird.d.ts .get() should be available

### ISSUE THREAD

**Issue by DomiR** [DefinitelyTyped/DefinitelyTyped#6992]
The definition file contains `get` already but it is commented out: `// TODO find way to fix get()`. 

What seems to be problem? It should also contain `.get(index:number)`.

**Comment by vvakame** [comment]
um, please send a pull request first. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
