### ISSUE TITLE
Angular UI Router's IResolvedState is missing path

### ISSUE THREAD

**Issue by mastertinner** [DefinitelyTyped/DefinitelyTyped#6996]
Angular UI Router's `IResolvedState` should have a property `path`.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
