### ISSUE TITLE
Expose interfaces in Auth0

### ISSUE THREAD

**Issue by ianks** [DefinitelyTyped/DefinitelyTyped#7000]
I would like to be able to access some of the interfaces from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/auth0/auth0.d.ts

Currently, I do not know of a way to do this. Would it be possible to include the interfaces as part of the module?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
