### ISSUE TITLE
SinonStub does not contain stubbed object's methods

### ISSUE THREAD

**Issue by electricmonk** [DefinitelyTyped/DefinitelyTyped#7003]
Consider this test:

``` typescript
import {stub} from 'sinon';
const {expect} = require('chai');

interface I {
    func(num: Number): String
}

class C implements I {
    func(num: Number): String {
        return new String(num);
    }
}

describe("Sinon Stub", () => {
    it("implements functions on the stubbed interface", () => {
        const impl = stub(C);

        expect(impl.func).to.exist;
    });
});
```

TSC fails with this message:

```
ERROR in ./test/sinon.spec.ts
(19,21): error TS2339: Property 'c' does not exist on type 'SinonStub'.
```

Now, this is expectable, but maybe the return value of `SinonStubStatic` should be generic on a type argument passed to `SinonStatic.stub`?

**Comment by vvakame** [comment]
please send a pull resut. I'll review it.

**Comment by mkusher** [comment]
I've prepare simple example for `sinon.createStubInstance` [here](https://github.com/mkusher/DefinitelyTyped/commit/ac03ef21f5f30160dc1889f3edf3b71274427c21), but it requires `ts 2.1`. I think it would be cool to apply such mapper to all stub functions, but as I understand it is not possible now to have specific version of ts for specific package in DT. Am I right?

**Comment by fatso83** [comment]
This should be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
