### ISSUE TITLE
Updated MongoDB.d.ts

### ISSUE THREAD

**Issue by Think7** [DefinitelyTyped/DefinitelyTyped#7021]
Hello

I have spent a few hours updating the MongoDB.d.ts file but am unfamiliar with creating a pull request to officially submit it.

Here is the updated file: http://puu.sh/lGwbJ/66765b38c7.zip

**Comment by mathiasr-infocorp** [comment]
Hi @Think7, [here](https://help.github.com/articles/creating-a-pull-request/) is the GitHub docs on how to create a pull request.
Hope this helps.

**Comment by simonh1000** [comment]
Has this PR been submitted and accepted - I'd love to be able to use this

**Comment by pfzero** [comment]
Hi, 

Nice work on updating definitions. Can we also use mongodb as namespace and not only a module?
This means that instead of declaring mongodb as module we can do both, so it's easier to "extend" and use mongodb interfaces.

So this should be used instead.
```typescript

declare module mongodb {
    // definitions here
}

declare module "mongodb" {
    export = mongodb;
}
```

What do you think?

**Comment by Think7** [comment]
Finally created a PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7396#issuecomment-167878155 Not sure if i did everything correctly, never contribuited to a repo before...

In the meantime, here is a newer version of the defs:
http://puu.sh/mcSmf/d03fb419a0.zip

@pfzero I have made the change in the above def but not in the PR i submitted. If that gets approved i will submit a new one with your change. Sorry about this! (Missed your request first time around)

**Comment by pfzero** [comment]
@Think7 Looks like your tests are failing due to not including the Promise library. I am not sure if ES6-Promises are used within node-mongodb-driver or `bluebird`, but either way, at the beginning of your test file you should require the promise module:

```typescript
/// <reference path="../node/node.d.ts" />
import MongoDB = require('mongodb');
import Promise = require('bluebird'); // or some other polyfill you might be using;

// then your tests

```

It works on your machine because, probably, you're using node >= v.4.0.0 which comes with native support for promises, whereas the TravisCI environment might be using some older node version, and thus not having Promise support. So you have to use some polyfill.

p.s. Can you also update the mongodb.d.ts file to have it as namespace and module as well?

Thanks.

**Comment by simonh1000** [comment]
Mongo uses special promises, which do not support e.g. catch

**Comment by kevinfairclough** [comment]
The deprecated functions have been removed from this definition file.  I think they should be left in, they're still in the driver.

**Comment by Think7** [comment]
@kevinfairclough 

I see your point however:

- The methods have been depreciated by MongoDB and are not recommended for continued use.
- As there is no way (AFAIK) to include warnings or IntelliSense comments within a def, a user will not a current method from an outdated one without looking at the docs. Not having included them throws an errr.
- When i started on this def my goal was to make it "current". Add what's vital, strip what's depreciated or incorrect.
- It took a bit to sort out the depreciated methods and remove them :P Normally i wouldn't care about throwing away code, but in this case doing so doesn't / feel / like it would add value.

Moving forward, i will maintain this def in a separate repo. If someone wants to tackle merging it and adding in the depreciated defs, here please do! I just can't spend the time to sort out why CI fails for this and every other MongoDB update anyone has submitted.

Kind of wish there was a more organized support system for people who devote the time up update the defs but have difficulty submitting the updates. :/

**Comment by Think7** [comment]
@simonh1000 I'm not sure if this is true. 

Looking through the node-mongodb-native source there are many cases of this comment:
```
// A Promise library class the application wishes to use such as Bluebird, must be ES6 compatible.
```
Both ES6 Promise and Bluebird 2.9 which is listed in the package.json both support .catch().

**Comment by simonh1000** [comment]
Hi Andrew. I've lost track here. Can I just confirm that you think
mongo/mongoose have deprecated their (non standard) promises and encourage
us to use our own preference? No problem if that's the case

**Comment by Think7** [comment]
@simonh1000 Yes, at least with regard to the mongodb native driver. Mongoose is a separate project with a separate d.ts. I am purely talking about the mongo driver.

In the 2.0 and 2.1 sources (of the driver), there are comments in the implementation saying specifically that promises must be ES6 compatible. Both Bluebird 2.9 which is listed in the package.json and ES6 Promise are both ES6 compatible.

**Comment by Think7** [comment]
Updated definition will be maintained here: 

https://github.com/Think7/Mongo.d.ts

**Comment by CaselIT** [comment]
@Think7 a version compatible with mongodb 2.1 has been merged here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7565

**Comment by Think7** [comment]
Wow, Thank You!

Wish i had known you were working on this also. Could have saved both of us a lot of time! :P

**Comment by pfzero** [comment]
@Think7 @CaselIT Great job guys! Thank you :)

**Comment by pfzero** [comment]
@Think7 You might also want to update the readme file from your separate mongo definition [repo](https://github.com/Think7/mongodb.d.ts).

**Comment by Think7** [comment]
@pfzero Will do! (Some time today :P)

@CaselIT Your def is missing initializeUnorderedBulkOp.

```
...
    //http://mongodb.github.io/node-mongodb-native/2.1/api/Collection.html#initializeOrderedBulkOp
    initializeOrderedBulkOp(options: CollectionOptions): OrderedBulkOperation; 	
    //http://mongodb.github.io/node-mongodb-native/2.1/api/Collection.html#initializeUnorderedBulkOp
    initializeOrderedBulkOp(options: CollectionOptions): OrderedBulkOperation; 	
...
```

Ordered is in there twice. Literally just need to add an "un" :D

**Comment by CaselIT** [comment]
@Think7 I created a pull request https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7924
There was a lot of copy paste involved, so there will probably be other similar typos :)

Feel free to update them yourself if you find more :+1:

**Comment by CaselIT** [comment]
@pfzero I'm trying to do as you suggest here https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7021#issuecomment-167768306 on my fork of the repository, here https://github.com/CaselIT/DefinitelyTyped/pull/3 but it does not compile as you suggest. 
> mongodb/mongodb.d.ts(1270,16): error TS2435: Ambient modules cannot be nested in other modules or namespaces.

Maybe it could work if we do in the express type definition https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/express/express.d.ts#L16

**Comment by pfzero** [comment]
@CaselIT The express definitions style are like that because the Req and Res interfaces can be enhanced before being exported from the module. This might also be the case for Mongo, I think. 

The difference is that when declaring as namespace you can get full access to the underlying classes and structures from the module ( which I'm pretty sure it isn't the case for mongo ) whilst when declaring the defs like express you can enhance the Req and Res objects (because this is the actual usage of express) with custom properties, and when you import the module within your project, you'll get all the extra properties you declared beforehand.

Your error is due to usage of an external module by importing it within your namespace rather than referencing it. So you could use EventEmitter like this:

```typescript
/// <reference path="path/to/eventemitter3" />

declare module MongoDB {
     export abstract class Db extends EventEmitter3.EventEmitter {
         // class signature here...
     }
}

declare module "mongodb" {
    // export the public interface exposed by the module;
    export = MongoDB;
}
```

But I am not sure which is the best version to write the definitions. Either express style and thus users of the library can eventually `enhance` the underlying structures (which I think it's the most correct way of doing it) or to do it with full namespace declaration (and giving more flexibility for extending / enhancing the structures easily).

**Comment by CaselIT** [comment]
@pfzero I've tried changing it as you suggest and it does indeed pass the test.
Still in introduces a dependency on `eventemitter3` that is not in the original code. I'm not sure if it's  recommended.

I tried to use `NodeJS.EventEmitter` first but it is only an interface, not a class, so I would have to explicitly implement it to make it work. I do not know if there is a way to reference the `EventEmitter` class declared in the `events` module of `node.d.ts` without importing it.

**Comment by Think7** [comment]
@CaselIT How would you like to move forward with the maintenance of this def?

Your version is more complete and has some classes defined i did not, but it also contains errors. Mine lacks some class defs but should not contain any errors.

I'm not as experienced as i should be with working on a shared code base. Not suree what the procedure is. :P

**Comment by CaselIT** [comment]
@Think7 You can merge them if you want. 
Also have a look at https://github.com/typings/typings that replaces tsd. It has no need of a central repo for the typings.

**Comment by Think7** [comment]
@CaselIT Sent you an email (i hope) to your unibo.it account. Let me know if you got it. 

If that wasn't you, would you mind emailing me directly? andrew@dkai.dk

I'm also on the TypeScript and DefinitivlyTyped Gitter rooms: 

https://gitter.im/Microsoft/TypeScript

https://gitter.im/DefinitelyTyped/DefinitelyTyped

**Comment by Think7** [comment]
A repo using the new typings native external fancy external module system can be found here:

https://github.com/Think7/typings-mongodb

This will hopefully be a combined effort of @CaselIT and myself <3

Will start merging his changes today and submit to the typings registry when completed.

**Comment by pfzero** [comment]
@CaselIT @Think7 Guys I am not sure if the definitions are really reflecting the public api exposed from mongodb. I am saying this because for example the `Collection` class is exported from the mongo module definition, but, the [docs](http://mongodb.github.io/node-mongodb-native/2.1/api/Collection.html) states that the class cannot be used directly, and it's an internal type; i.e. a module-level class.

So using the definitions you can actually do:

```typescript
import {Collection} from 'mongodb';

class SomeCustomCollection extends Collection {
    // implementation here
}

// and then
// this one is will produce an error at runtime,
// but it will not be cathed by the ts compiler
let col = new SomeCustomCollection(); 

```

So in this case an interface should be used. Users of the library can then import the interface and extend it to add custom properties or methods on the interface, and they'll not be able to instantiate it (this being the desired behaviour anyways). Otherwise, definitions on popular ODMs will get troublesome.

**Comment by CaselIT** [comment]
@pfzero I agree that's was an error. I've updated the open pull request https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7924

**Comment by pfzero** [comment]
Also, regarding the namespacing/module declaration dilema, since the library is making use of `eventemitter`, the correct definitions for reflecting this must either declare a local `EventEmitter` interface or import / reference it. The previous version of mongodb definitions didn't include any dependencies on eventemitter because no interface / class was extending it.

Since you've used it in the defs, then you have to provide a definition for it. When declaring as a module you must import it from somewhere (just like you did), and, when declaring as a namespace you have to reference it via `/// <reference ... />` tag at the top of the file.

Declaring it as a namespace gives the flexibility of providing definitions for frameworks that work `magically` behind the scenes, e.g. sails.js. In this case you have MongoDB as native driver, wrapped by Waterline which is then used by sails. So all the models you declare in sails are autoloaded by the framework and transformed into collections. Thus, when declaring the model you want to access the waterline definitions without importing it because you'll not use the module anyways. So you'll need waterline declared as a namespace and module at the same time (because waterline can be used solely). For declaring it as a namespace, and because it depends on MongoDB driver, you'll also need the MongoDB to be declared as a namespace.

I hope I was clear enough :P . Please let me know if I can help somehow. :)

BTW, thanks for the great work. :)

**Comment by Think7** [comment]
@pfzero 

The typings system works differently than DT. 

If you check the def, there is no module or namespace declaration at all. This is because typings "compiles" the d.ts on the fly depending on the enviroment it's being used in when you install it

See here for more info: https://github.com/typings/typings/issues/152#issuecomment-178494228

It will decide what the appropriate wrapper will be. Also all modules are defined as external.

Since to use this d.ts with typings the user MUST install the node typing, using event emitter should not cause an issue.

In your example with Waterline: Typings.d.ts's have dependencies. So the waterline typings would depend on this mongo typing. When both are installed, the typings application sorts out all the details and strings it together so it works.

**Comment by pfzero** [comment]
Aaah, I see. Thanks for the info @Think7. I won't bother you with the namespacing / module differences anymore :p

**Comment by scippio** [comment]
Just my observation... is it correct? Maybe I'll create pull request for missing things...

_BulkWriteResult_ {
  ok: [Getter],  ---------- ok: number;
  nInserted: [Getter], ---------- nInserted: number;
  **<don't exists?>** , ---------- nUpdated: number;
  nUpserted: [Getter], ---------- nUpserted: number;
  nMatched: [Getter], ---------- **<missing?>**
  nModified: [Getter], ---------- nModified: number;
  nRemoved: [Getter], ---------- nRemoved: number;
  getInsertedIds: [Function], ---------- getInsertedIds(): Array<Object>;
  getUpsertedIds: [Function], ---------- getUpsertedIds(): Array<Object>;
  getUpsertedIdAt: [Function], ---------- getUpsertedIdAt(index: number): Object;
  getRawResponse: [Function], ---------- getRawResponse(): Object;
  hasWriteErrors: [Function], ---------- hasWriteErrors(): boolean;
  getWriteErrorCount: [Function], ---------- getWriteErrorCount(): number;
  getWriteErrorAt: [Function], ---------- getWriteErrorAt(index: number): WriteError;
  getWriteErrors: [Function], ---------- getWriteErrors(): Array<Object>;
  getLastOp: [Function], ---------- getLastOp(): Object;
  getWriteConcernError: [Function], ---------- getWriteConcernError(): WriteConcernError;
  toJSON: [Function], ---------- **<missing?>**
  toString: [Function], ---------- **<missing?>**
  isOk: [Function] ---------- **<missing?>**
}

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
