### ISSUE TITLE
[@types/node] error TS2502: 'Storage' is referenced directly or indirectly in its own type annotation.

### ISSUE THREAD

**Issue by mark-wiemer** [DefinitelyTyped/DefinitelyTyped#70320]
When creating a new project that imports `"@types/node": "^22.4.0"`, TS gives an error on compilation:

```sh
node_modules/@types/node/globals.d.ts:159:9 - error TS2502: 'Storage' is referenced directly or indirectly in its own type annotation.

159     var Storage: typeof globalThis extends { onmessage: any; Storage: infer T } ? T
```

The referenced value is here, and it does look like a true positive to me:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e5e3fc99a4e4fb10a41d33cbe7d26f148f37558a/types/node/globals.d.ts#L159-L163

**Comment by Renegade334** [comment]
So, it turns out that this breaks with the WebWorker lib, which does declare `onmessage` but _doesn't_ implement `Storage`, so the `extends { onmessage...` hack breaks. The CI only runs checks with DOM and non-DOM libs, so this was missed.

Changing `onmessage` to a DOM-only variable (`onabort`, for example) should fix this.

**Comment by jakebailey** [comment]
FWIW adding a new tsconfig to run in the node tests would be straightforward, if you're willing to increase the test time by 50%.

**Comment by jakebailey** [comment]
Ah, you did that in the PR 😄
