### ISSUE TITLE
angular.ui.router nested views

### ISSUE THREAD

**Issue by boxertech** [DefinitelyTyped/DefinitelyTyped#7041]
With the change to support strictDI (#5258) where IState.views?: {} went to IState.views?: { [name:string]: IState }, my nested views definition breaks the ts compile with the error:

```
src\app\core\core.module.ts(19,39): error TS2345: Argument of type '{ name: string; abstract: boolean; views: { "topNavView@": IState; "rightNavView@": IState;
}; } ...' is not assignable to parameter of type 'IState'.
  Type '{ name: string; abstract: boolean; views: { "topNavView@": IState; "rightNavView@": IState; }; }' is not assignable to type 'IState'.
[11:22:57] TypeScript: 1 semantic error
```

My state def:

```
[{
    name: 'root',
    abstract: true,
    views: {
    "topNavView@": {
        templateUrl: 'app/core/topNav.html',
        controller: 'app.core.TopNavCtrl',
        controllerAs: 'topNav'
    },
    "rightNavView@": {
        templateUrl: 'app/core/rightNav.html',
        controller: 'app.core.RightNavCtrl',
        controllerAs: 'rightNav'
    }
    }
},{
    name: 'components',
    parent: 'root',
    url: '/',
    templateUrl: 'app/core/componentLayout.html',
    controller: 'app.core.ComponentsCtrl',
    controllerAs: 'comps'
}]
```

If I change the .d.ts back to IState.views?: {}, the compile succeeds.  Of course, I removed the constraint.  Do we need to define our nested views differently? Or do we need to define the nested views in the .d.ts differently?

**Comment by vvakame** [comment]
please send a pull request if you want.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
