### ISSUE TITLE
jQuery definitions missing $.event.trigger

### ISSUE THREAD

**Issue by vukasin-nikodijevic** [DefinitelyTyped/DefinitelyTyped#7081]
Solution is described [here](http://stackoverflow.com/a/14442290)

It would be nice to have that in place in `jquery.d.ts`

**Comment by vvakame** [comment]
@johnnyreilly

**Comment by johnnyreilly** [comment]
PR's welcome!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
