### ISSUE TITLE
Missing options attribute in ITemplateOptions

### ISSUE THREAD

**Issue by benzid-wael** [DefinitelyTyped/DefinitelyTyped#7088]
the `templateOptions` attribute accept already an `options` attribute which describe the different `option` for the `select` input, e.g:

```
{
    "key": "state",
    "type": "select",
    "templateOptions": {
      "label": "State",
      "options": [
        {
          "name": "Alabama",
          "value": "AL"
        },
        {
          "name": "Alaska",
          "value": "AK"
        }
    }
}
```

However, the `ItemplateOptions` does not contains definition of `options`  field. For more details, see http://angular-formly.com/#/example/bootstrap-formly/select

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
