### ISSUE TITLE
[angular.d.ts] ILocationService.$$html5 missing

### ISSUE THREAD

**Issue by dr-zone** [DefinitelyTyped/DefinitelyTyped#7132]
The $$html5 property is missing from the ng.ILocationService

It is used for getting if Html5Mode is enabled

```
$$html5: boolean;
```

**Comment by vvakame** [comment]
please send a pull reques. I'll review it. but, it is not private function?

**Comment by pocesar** [comment]
yes, anything that has $$ in angular 1.x is considered private and shouldn't be used (leads to inconsistent code, because it might be removed in future)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
