### ISSUE TITLE
es6-promise Promise.all error

### ISSUE THREAD

**Issue by OliverJAsh** [DefinitelyTyped/DefinitelyTyped#7138]
See https://github.com/Microsoft/TypeScript/issues/5935

Please could we use the same fix as https://github.com/Microsoft/TypeScript/pull/5973?

**Comment by vvakame** [comment]
patches welcome!

**Comment by OliverJAsh** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7299

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
