### ISSUE TITLE
Lodash and Underscore conflict with each other

### ISSUE THREAD

**Issue by arkon** [DefinitelyTyped/DefinitelyTyped#7141]
Could be resolved by just explicitly calling it `lodash` instead of `_`, for example.

**Comment by pocesar** [comment]
it's being discussed on how we can solve this #5045 (for many other libraries as well)

**Comment by vjau** [comment]
I don't understand, i use lodash and underscore in my project, but the typings from both get mixed.
In a file, i import `import u from 'underscore'`  but when i use it with `u.uniqu(arr, true)` typescript complains that the signature is not good since it's using lodash uniqu signature instead of underscore's one.
I don't even understand how both end up mixed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by IRCraziestTaxi** [comment]
Even installing the latest versions of both @types/underscore and @types/lodash, this is still an issue.

```
node_modules/@types/lodash/index.d.ts:239:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable '_' must be of type 'UnderscoreStatic', but here has type 'LoDashStatic'.

239 declare var _: _.LoDashStatic;
                ~

  node_modules/@types/underscore/index.d.ts:15:13
    15 declare var _: _.UnderscoreStatic;
                   ~
    '_' was also declared here.
```

I cannot find how others are getting around it, if they are at all. How has this not been addressed?
