### ISSUE TITLE
Foundation/Foundation-Sites tsd query

### ISSUE THREAD

**Issue by jafern14** [DefinitelyTyped/DefinitelyTyped#7169]
When running "tsd query foundation" from the cli you end up getting foundation and foundation-sites. While this is the intended functionality, the two files are creating variables in to the same namespace. When trying to compile a project that is using foundation in the bower.json file it will then return an error and fail in compilation due to the fact that FoundationStatic and FoundationSitesStatic collide in the same namespace. Results in failed build

**Comment by connelhooley** [comment]
Pretty new to TypeScript but as a work-a-round I was able to get rid of the error by running:

`tsd install foundation-sites/foundation --save`

Rather than `tsd install foundation --save`

Hope this helps.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
