### ISSUE TITLE
Update linq.d.ts to correct case

### ISSUE THREAD

**Issue by nibblesnbits** [DefinitelyTyped/DefinitelyTyped#7214]
the .d.ts for linqjs is either out of date or incorrect.  The library has all of the functions as camel case, while the definition file is all Pascal case.  Is it possible to fork just that part of the repo so I can fix it and put in a pull request?

**Comment by vvakame** [comment]
sure, please send a PR!

**Comment by nibblesnbits** [comment]
Is it possible to pull down just the appropriate files, or do I need to fork and pull the whole DefinitelyTyped repo?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
