### ISSUE TITLE
sequelize missing field "models"

### ISSUE THREAD

**Issue by havsar** [DefinitelyTyped/DefinitelyTyped#7220]
Sequelize type definitions 3.4.1:

Sequelize instance is missing field "models" as described in the following document: http://docs.sequelizejs.com/en/latest/api/sequelize/#models

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
