### ISSUE TITLE
Conflict with angular-ui-router.d.ts

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/DefinitelyTyped#7284]
I began getting errors with my typings after adding angular-ui-router.d.ts to my project , so much so that the project was failing with multiple errors in angular.d.ts 

http://stackoverflow.com/questions/34380997/module-ng-has-no-exported-members-in-vs-code

I eventually turned off the `ng` part of angular.d.ts as in the update of the question above. This solved the issue and i just started referencing everything with `angular.` instead of `ng.` in the application. 

Except in the Route config file . I had overlooked that i had not changed `ng.ui.IStateProvider`. This however did not break the application and it is running fine. But how? How does `private $stateProvider: ng.ui.IStateProvider` still work. This leads me to believe that there is something wrong with `angular-ui-router.d.ts` . I cannot find any reference to `ng` in that file, regardless the application is still running and i am getting full intellisense on `ng.ui` . It should be noted that `ng dot` only brings up `ui` and no other namespaces.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
