### ISSUE TITLE
Angular.d.ts - IComponentOptions Error - Comma separated fields

### ISSUE THREAD

**Issue by ByronLudwig** [DefinitelyTyped/DefinitelyTyped#7317]
angular.d.ts - The IComponentOptions has comma separated fields which should be semi-colon separated. This is producing an error when the tsd:install runs for gulp.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
