### ISSUE TITLE
React - 'history/lib/createBrowserHistory' seems to be broken

### ISSUE THREAD

**Issue by RichardJECooke** [DefinitelyTyped/DefinitelyTyped#7350]
This module definition seems broken, please see this StackOverflow question: http://stackoverflow.com/questions/34443593/how-to-fix-ts2349-cannot-invoke-an-expression-whose-type-lacks-a-call-signatur

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
