### ISSUE TITLE
angular.d.ts does not build

### ISSUE THREAD

**Issue by thomaseyde** [DefinitelyTyped/DefinitelyTyped#7362]
I installed `angularjs.TypeScript.DefinitelyTyped` today, but angular.d.ts does not build. Visual Studio reports 400+ build errors.

I also notice that `angularjs.TypeScript.DefinitelyTyped` depends on `jquery.TypeScript.DefinitelyTyped`!? Why do we want that?

**Comment by MarkAPhillips** [comment]
The issue relates to the jquery dependency as it defaults to the lowest version 0.1.1 rather than 2.3.3
In the earlier version typescript used "bool" instead of "boolean" as the type.
Please note this issue relates to obtaining angular js from Nuget so assume this is an issue with the [nuget package](https://www.nuget.org/packages/angularjs.TypeScript.DefinitelyTyped/).

**Comment by thomaseyde** [comment]
Yes, it's an issue with the NuGet package. 

And I find it disturbing it has a dependency on jQuery: Those two are not related to each other. When I need type definitions for jQuery, I hope to find that in a separate package. We should not be forced upon dependencies we don't need, definitely when the total does not build.

**Comment by evilgeniuscreative** [comment]
I'm really confused by how to tell WHICH version of Typescript the angular.d.ts and the jquery.d.ts files are compatible with, in addition to which versions of angular and jquery they're compatible with. I assume that the 1.x / 2.x in the headers of the files are referring to the framworks, not Typescript. thanks

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
