### ISSUE TITLE
yeoman-generator.d.ts does not contain reference to user object

### ISSUE THREAD

**Issue by connelhooley** [DefinitelyTyped/DefinitelyTyped#7427]
The following user api appears to be missing:
http://yeoman.io/generator/actions_user.html

Useage would look like this:

``` TypeScript
import * as yo from 'yeoman-generator';
export default class ThemeGenerator extends yo.generators.Base {
    prompting() {
        console.log(this.user.git.name());
    }
}
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
