### ISSUE TITLE
Compiler missing typo

### ISSUE THREAD

**Issue by davidleureka** [DefinitelyTyped/DefinitelyTyped#7442]
I'm using the definitions for the [sequelize library](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/sequelize) and its not catching a typo in the code that I believe it should.

I am calling the `define` method like this:

```
import Sequelize = require('sequelize')

function createModel(sequelize: Sequelize.Sequelize, Types: Sequelize.DataTypes) {
    let Pipe = sequelize.define('MyTable', {
        myField: { type: Types.BOOLEAN, allowNull: true, defaultValue_bad: true }
    })
}
```

Notice that the `defaultValue` property is misspelled. The compiler is not catching this.

However, if I do this:

```
let opts: Sequelize.DefineAttributeColumnOptions = {
    type: Types.BOOLEAN, allowNull: true, defaultValue_bad: true
}

let Pipe = sequelize.define('MyTable', {
    myField: opts
})
```

it does catch the issue. Am I doing something wrong? Is there an issue with the definition of the `define` method? Is there a bug in the compiler?

The relevant definitions are these (I think):

```
define<TInstance, TAttributes>( modelName : string, attributes : DefineAttributes, options? : DefineOptions<TInstance> ) : Model<TInstance, TAttributes>;

interface DefineAttributes {
    [name : string] : string | DataTypeAbstract | DefineAttributeColumnOptions;
}

interface DefineAttributeColumnOptions extends ColumnOptions {
    type: string | DataTypeAbstract;
    unique?: boolean | string | { name: string, msg: string };
    primaryKey?: boolean;
    autoIncrement?: boolean;
    comment?: string;
    references? : DefineAttributeColumnReferencesOptions;
    onUpdate? : string;
    onDelete? : string;
    get? : () => any;
    set? : ( val : any ) => void;
    validate? : DefineValidateOptions;
    values? : Array<string>;
}

interface ColumnOptions {
    allowNull?: boolean;
    field? : string;
    defaultValue?: any;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
