### ISSUE TITLE
autobahn definitely typed

### ISSUE THREAD

**Issue by bradws** [DefinitelyTyped/DefinitelyTyped#7446]
Hi,

Is there any chance of providing a very simple working example of this?

Thanks.

**Comment by vvakame** [comment]
:+1:

**Comment by codegastudio** [comment]
👍

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
