### ISSUE TITLE
Foundation problem

### ISSUE THREAD

**Issue by samvloeberghs** [DefinitelyTyped/DefinitelyTyped#7472]
Hi,

I'm having a problem with the definition of the foundation-sites.
It does not find "foundation-sites" but when I search for "foundation" it does.

```
C:\>tsd install foundation-sites --save

>> zero results

C:\>tsd install foundation --save

 - foundation-sites / foundation
   -> jquery        > jquery
 - foundation       / foundation
   -> jquery        > jquery

>> running install..

>> written 3 files:

    - foundation-sites/foundation.d.ts
    - foundation/foundation.d.ts
    - jquery/jquery.d.ts

C:\>
```

Any thoughts on this?
Kr
Sam V.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
