### ISSUE TITLE
gl-matrix/gl-matrix.d.ts: Please change GLM.IArray to Array<number>

### ISSUE THREAD

**Issue by PublicParadise** [DefinitelyTyped/DefinitelyTyped#7611]
Consider this typescript function:

``` typescript
/// <reference path="../typings/gl-matrix/gl-matrix.d.ts" />

function setMatrixUniform(gl: WebGLRenderingContext, 
                          matrixUniform: WebGLUniformLocation, 
                          fromMatrix: GLM.IArray): void {
    gl.uniformMatrix4fv(matrixUniform, false, Float32Array.from(fromMatrix));
}
```

When compiled with tsc 1.7.5 you'll get this error:

```
error TS2345: Argument of type 'IArray' is not assignable to parameter of type 'ArrayLike<number>'.
```

Proposed fix:

``` typescript
declare module GLM {    
    type IArray = Array<number>;
}
```

(I accidentally filed an issue against `toji/gl-matrix` instead of `DefinitelyTyped/DefinitelyTyped`, see https://github.com/toji/gl-matrix/issues/201. `tatx/DefinitelyTyped` has not enabled support for reporting issues.)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
