### ISSUE TITLE
threejs Object3D.modelViewMatrix and Object3D.normalMatrix are wrong

### ISSUE THREAD

**Issue by matgr1** [DefinitelyTyped/DefinitelyTyped#7614]
the properties: 

```
    modelViewMatrix: { value: Matrix4 };

    normalMatrix: { value: Matrix3 };
```

should just be:

```
    modelViewMatrix: Matrix4;

    normalMatrix: Matrix3;
```

**Comment by vvakame** [comment]
please send a pull request.

**Comment by matgr1** [comment]
submitted pull request #7750 ...I'm a noob, so let me know if anything's not right please!

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
