### ISSUE TITLE
Backbone object

### ISSUE THREAD

**Issue by chiefmc** [DefinitelyTyped/DefinitelyTyped#7629]
Hi All!

I'm trying to use Backbone's global object as an event dispatcher and the app works just fune, although the compiler doesn't like this statement:

``` javascript
Backbone.trigger("planloading:start"); // compiler says: 'TS2339: Property 'trigger' does not exist on type 'typeof Backbone'.'
```

What can be done to the declaration to avoid this?

**Comment by zobidafly** [comment]
hmmm seems "trigger" method is applied against Backbone.Events. hope you fixed it.

**Comment by Spinarooni** [comment]
I think the intended use per Backbone documentation is to `extend` the Backbone.Events object onto your app's own event object.

http://backbonejs.org/#Events

**Comment by Nemo157** [comment]
Note from the first paragraph of http://backbonejs.org/#Events-catalog:

> The `Backbone` object itself mixes in `Events`, and can be used to emit any global events that your application needs. 

So the example code in this issue is correct, the `Backbone` namespace/object should mixin the `Events` methods.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
