### ISSUE TITLE
Amcharts 

### ISSUE THREAD

**Issue by chadhumphrey** [DefinitelyTyped/DefinitelyTyped#7636]
I'm using the Amcharts 3, Angular2 Beta and DefinitelyTyped, and npm

I'm trying to integrate an Amcharts (that works on well on php, I don't see the error coming from amcharts) into Angular2. 

When I compile the TypeScript, I keep getting an error "Property 'ready' does not exist on type 'typeof AmCharts'. 

`AmCharts.ready(function() {
      console.log('test 25');
      alert('page loaded');
      createStockChart();
    });`

I reviewed amcharts/AmCharts.d.ts and I don't see the ready function in there? When I load the code in the browser it blows past the function and doesn't even throw an error. However this is the crazy thing every once in a while with no logical reason it works, but I can seem to replicate it to solve the problem.

**Comment by Toufux** [comment]
hello 
did you manage to make it works?
thank you

**Comment by SrinivasKothapalli** [comment]
Hi ,
  is this got fixed, i ran into same problem,

AmCharts.isReady,
AmCharts.AmMap(),
AmCharts.maps

etc it could not find them....

**Comment by Toufux** [comment]
I made it work with a simple setTimeout(amchart....., 0);

**Comment by arunsaibk** [comment]
could you please let me know how you implemented using  setTimeout I tried but no luck

**Comment by arunsaibk** [comment]
@DimitriMathot Please share the code how you make it work, I tried but no luck

**Comment by DimitriMathot** [comment]
I don't have it anymore, it was in my last job, can't keep the code, and I don't remember anything about that... Sorry

**Comment by arunsaibk** [comment]
solution : 
Follow this and it got resolved
https://angular.io/api/core/NgZone

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
