### ISSUE TITLE
Polymer elements

### ISSUE THREAD

**Issue by nalbion** [DefinitelyTyped/DefinitelyTyped#7717]
It'd be great if you guys could resolve #4513.  Even better if `tsd` could handle external repos (https://github.com/DefinitelyTyped/tsd/issues/87) or if this repo included git submodules.

I have generated 179 `.d.ts` files in 8 subdirectories at https://github.com/nalbion/polymer-elements-typings

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
