### ISSUE TITLE
Three.js: DataTexture wrong type of "data" parameter

### ISSUE THREAD

**Issue by alexpyzhianov** [DefinitelyTyped/DefinitelyTyped#7718]
From the [docs](http://threejs.org/docs/index.html#Reference/Textures/DataTexture): "The data argument must be an ArrayBuffer or a typed array view."
Currently it has `ImageData` interface, which is wrong.

**Comment by vvakame** [comment]
@gyohk ?

**Comment by gyohk** [comment]
Thank you for the pointed out.
I'll fix it soon.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
