### ISSUE TITLE
Definitely Not Versioned

### ISSUE THREAD

**Issue by snoopcheri** [DefinitelyTyped/DefinitelyTyped#7719]
What's the recommended way to find a TypeScript definition file for a specific version of a library and a specific TypeScript version? (for example a definition file for lodash v2.4.2, which compiles with TypeScript 1.5 and above)

What I know is the following:
#### Library Version

Some TypeScript definition files contain a comment at the beginning of the file, which mentions the version of the library this definition file refers to (e.g. AngularJS which specifies version 1.4+). Other TypeScript definition files don't mention anything in this respect - not even in the commit history.

Is there no reliable way to know what library version is covered by a TypeScript definition file?
#### TypeScript version

The DefinitelyTyped repository has branches starting with 0.8 up to 1.4.1. I'm assuming that this represents the TypeScript version itself. Unfortunately it ends with 1.4.1. Therefore I assumed that TypeScript definition files on the master branch are valid for TypeScript 1.4.1 and above. Unfortunately this is not always the case - there are TypeScript definition file which are only valid for TypeScript 1.6 and above.

Is there no reliable way to know what TypeScript version is required for a TypeScript definition file?

What we're doing at the moment is storing commit hashes of TypeScript definition files that compile with the TypeScript version we're using currently (v1.5.3). While this is a pain, it kinda works. But since we usually don't know, which library version the definition file is for, we're just hoping for the best. This doesn't sound like a promising and reliable process though.

**Comment by snoopcheri** [comment]
Anyone?

An answer along the lines "there is no recommended way, apart from being up-to-date with TypeScript and libraries is the best you can do" or "it depends on the library" are perfectly acceptable answers. :)

I'm mainly asking because I want to be sure that I'm not missing something very obvious here...

**Comment by alainsahli** [comment]
+1

**Comment by sir-marc** [comment]
No one?

**Comment by simonalbrecht** [comment]
+1 👍

**Comment by mhegazy** [comment]
@types packages have TS version tags on them.  if you want a specific version of the compiler then fix your dependency on `@ts2.0` for instance.

**Comment by simonalbrecht** [comment]
@mhegazy Yes that is clear. 

The issue here is that there is no clear way to see for which version of a library the typings are for. The version numbers of the `@types` package only very rarely match the version of the dependency you're pulling the typings in. For example, `jquery@3.2.1` (which is the latest version at this time) is paired with `@types/jquery@2.0.42`.

The only indicator you get is the file header (which is also not always present or even up-to-date) that contains the version number (usually only major) which makes it really hard to do an upgrade for a specific version of a library. For the example with jquery above, the header comment says it is compatible with jQuery 1.10.x/2.x but does not mention 3.x at all:

```
// Type definitions for jQuery 1.10.x / 2.0.x
```
Source: [jquery/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c223230018708c8ee6fd9e1871801ed0106502c2/types/jquery/index.d.ts)

----

The idea of being always up-to-date is great, but seldom doable in a large project or company.

There is just too much of guesswork and trial and error involved for my taste. I know this is a community project and kept alive by volunteer contributors with tight resources but I do not understand why there is no guideline on versioning.

Typescript is supposed to speed up development by eliminating the problems and bugs that happen in vanilla JS due to its untyped nature but with incorrect typings and some that do not match at all for the major version this is just as bad.

**Comment by KodingSykosis** [comment]
Over a year and still no solution?  Why does the definition file have independent versioning?  Isn't it really just a contract?  I currently have an issue where my definition file for jquery doesn't match the version we're actually using.

**Comment by erlangp** [comment]
+1

**Comment by erlangp** [comment]
+1

**Comment by jez9999** [comment]
I totally agree with this.  All the tutorials say how easy it is to use DefinitelyTyped but that's only if you're grabbing the latest version of a package and you grab the latest typings and they happen to work.  If you need the typings for an older version of a package or the typings aren't up-to-date, you're SOL.  The obvious way to do it would be for me to be able to say in `package.json`:

```
...
  "dependencies": {
    "uuid": "^3.1.0"
  },
  "devDependencies": {
    "@types/uuid": "^3.1.0"
  },
...
```

At the time of writing, `uuid` is at 3.1.0 and `@types/uuid` is at version 3.4.2.  Why isn't it at 3.1.0?  This versioning should be strictly enforced.

**Comment by OliverJAsh** [comment]
I would really like to see changelogs for each package. Could that be considered as part of this?

**Comment by katesowles** [comment]
Not having some method of tracking version changes (releases? changelog? SOMETHING?) is absurd. Hoping this gets some attention.

**Comment by RyanCavanaugh** [comment]
`git log` ?

If anyone wants to drop a CHANGELOG.md file in a given types folder and try to get PRs to keep it up to date, that'd be great. We can put it in the auto-generated README too.

**Comment by katesowles** [comment]
@RyanCavanaugh Running `git log` is not a helpful solution in this case. I can see the commit list plainly enough from the github, but what about that do you think is akin to a changelog? Commits still are not tied to a specific release and even if they were, a user would have to wade through the entire repo's ~43k commit's to find the ones relevant to the definitions they're trying to update. Much of the OSS community understands this and so they include a changelog SOMEWHERE in their online documentation so users can avoid this sort of laborious digging.

**Comment by RyanCavanaugh** [comment]
> a user would have to wade through the entire repo's ~43k commit's to find the ones relevant to the definitions they're trying to update.

?

```
C:\github\DefinitelyTyped\types\jquery>git log --pretty=oneline --abbrev-commit .
bef4d2b27d Enable "esModuleInterop" in all tsconfigs (#23354)
37685e11dd Add tslint disables for no-const-enum (#23134)
32a23a8139 [jquery] Update to jQuery 3.3. (#23095)
29c6e0f81a [jquery] Support projects without ES2015.Iterable. (#22766)
1e7989f8ce [jquery] Overriding the beforeSend function for AjaxSettings and UrlAjaxSettings to indicate a more appropriate settings parameter type Fixed errors when running lint
3f7bbeaa51 Miscellaneous lint fixes (#21116)
4e52c4dea6 jquery: Fix lint (#20965)
19f89399e4 Ensure every package has a tslint.json (#21009)
fdd6cc3a35 [jquery] `after()`, `append()`, `before()`, and `prepend()` can accept an array of JQuery (#20319)
42cf3abe63 [jquery] Add ajaxSettings property. (#20433)
947a8fb761 Enable strictFunctionTypes (#20373)
32ae9f623b Fix test failures
b8ea87c68e Strict function variance fixes round 1
924fafffc0 Fix remaining lint errors (#19166)
44a9d083d4 Merge pull request #18638 from leonard-thieu/jquery-promise
5d6c651a1a Apply stricter lint rules (#19063)
```

We could potentially generate a change log for each package based on the commit messages. What'd be the best place to put it, and what kind of format should it have?

**Comment by erlangp** [comment]
maybe:
[lib_name] [lib_version] [typed_version]
[Name] [0.0.0] [0.0.0]
? @RyanCavanaugh

**Comment by rjimenezda** [comment]
Sorry for bumping this, and this might be more suited towards `tsc`. 

Is there really no mechanism to control the Typescript version? I've ended up indirectly installing some packages from @typed that are breaking / muddling my build.

Some library that I'm not consuming directly recently added a definition file using Typescript 3 features. It just so happens that this library is in the dependency graph of a linting tool I'm using, so after doing `npm install`, their @types showed up in my node_modules. Now my build complains / is broken because of the Typescript 3 features.

Am I doing something wrong? I can do `"skipLibCheck": true` to ignore those, but it's not granular at all.

Correct me if I'm wrong, but the compiler always parses all the definition files on node_modules/@types, doesn't it? There's no way of telling it to ignore certain ones.

Maybe @types files should adopt some mandatory metadata that the compiler could parse, like the TS version. Then tsc could throw a warning or just ignore files not compatible with your compiler.

**Comment by RyanCavanaugh** [comment]
@rjimenezda a few things

You can add a `types` list to your `tsconfig.json`, though this does mean you'll have to manually specify "all but" the problematic one.

From a configuration side, IMO the package author was wrong to include a `@types` dependency in their package, because it creates exactly this situation.

In the future we'll be able to use the `typesVersions` feature (see https://github.com/Microsoft/TypeScript/pull/26568) so that older compilers see other versions of type definition files, but that feature only provides compat for TS 3.1+ (IOW eventually this won't be a problem anymore)

**Comment by rjimenezda** [comment]
Thanks for the answer @RyanCavanaugh, much appreciated.

I also think they should've done this differently (perphaps not a minor, but a major upgrade), but to each their own.

That feature looks very promising. So for instance, tsc 3.2 will ignore declaration files that are not compatible with it? (Like a future 4.x).

As for the problem itself, I'll try to lock down this library version or manually specify all the types we're using (as a temporary fix)

**Comment by Machiaweliczny** [comment]
Can't type packages have matching library version defined in `peerDependencies`?

**Comment by aaronbeall** [comment]
I really like the idea of having a generated CHANGELOG.md file. Any update on that @RyanCavanaugh ?

**Comment by noobling** [comment]
Its okay one day all common packages will be in typescript anyway :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.

**Comment by wdoug** [comment]
@orta, based on this comment:

> Roughly, if the problem is about a single @types/xyz package then it goes into GitHub Discussions where it can be classed as 'answered' by the poster, if the problem is systemic to DefinitelyTyped - then it's in GitHub Issues.

I would think this should perhaps remain as an issue since it is a discussion systemic to DefinitelyTyped, not about any particular package. Does that seem right?

**Comment by orta** [comment]
Do you have a reason for re-opening? `typesVersion` is one part of the answer to the OP, and we tag ts versions on npm too. That DT types don't match the exact versions on npm is well documented at this point and folks strive to keep major and minor in sync.

The side discussion of a changelog is interesting, and I'd help get PRs to [dt-tools](https://github.com/microsoft/DefinitelyTyped-tools) merged which try to do that  (you could base it on the code in [DOM-lib-generator](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/main/src/changelog.ts#L15)) - but realistically that is its own issue

**Comment by wdoug** [comment]
Thanks for the notes. Yeah, after reviewing, I think you're right that if there is continued interest in something like generating a changelog that would be more appropriate in a separate issue.

**Comment by jonenst** [comment]
Hi @orta ,
is there a recommended way to know which release contains a given commit ? For normal projects I usually do `git tag --contains XYZ` and the project has the responsability that these git tags match release versions on package repositories. 

Also what about the mirror question: is there a way to know what source commit was used to publish a given version to npm ? Again normally since versions and git tags are equivalent, the answer is straightforward to obtain.

note: in my case, I manually ran a dichotomy search on npm's content to find ou that https://github.com/DefinitelyTyped/DefinitelyTyped/commit/443451ccc5db3adf1865853e152636f1a9ba5dd5 was not in https://unpkg.com/@types/react@18.2.7/index.d.ts but present in https://unpkg.com/@types/react@18.2.8/index.d.ts
