### ISSUE TITLE
IComponentOptions not supporting multiple transclude anymore

### ISSUE THREAD

**Issue by goleafs** [DefinitelyTyped/DefinitelyTyped#7734]
this used to work:

```
var component: ng.IComponentOptions = {
    transclude: {
        content: "content",
        header: "header"
    }
```

But now it will only take a boolean for transclude value... however if you use component : any - the mutli-transclusion still works.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
