### ISSUE TITLE
Linq definition files confusing

### ISSUE THREAD

**Issue by rjamesnw** [DefinitelyTyped/DefinitelyTyped#776]
OK, the jquery.linq.js file has the SAME code embedded that also exists in linq.js, so if I ONLY include jquery.linq.js (so as not to download the same base code twice)) then I can access $.Enumerable and so on ... but the typescript file linq.d.ts only defines "var Enumerable"!!! :/

As a fix I added this line to my code:
Enumerable = jQuery.Enumerable;

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
