### ISSUE TITLE
ColumnDef Types

### ISSUE THREAD

**Issue by vetterj73** [DefinitelyTyped/DefinitelyTyped#7780]
I am using the filter property in IColumnDef.  There has an exposed property called filter.  That property has many properties but the two I am interested in are selectedOptions and type.

selectedOption extends IfilterOption which has two properties
value - number
label - string
Does value really need to be a string?  I don't use the types but I really want to and I place a string in each of them and it works fine but when I try to build it doesn't build since it is the wrong type.

type
I am setting the type property to uiGridConstants.filter.SELECT which is a string but the type property in the interface is of a number which seems it should allow a string.  I have found many examples online of using the property this way but the types are inconstant with typescript.

```
private getSchema(): Array<uiGrid.IColumnDef> {
 var schema = [
     { field: "process", displayName: "Process", enableFiltering: false, width: 33, cellTemplate: "checkBoxTemplate", enableColumnMenu: false },
     { field: "id", width: 140, displayName: "Queue Id", enableColumnMenu: false, enableFiltering: false},
     { field: "documentType", width: 250, displayName: "Type", enableColumnMenu: false, filter: { selectOptions: this.documentTypes, type:  this.uiGridConstants.filter.SELECT } },
     { field: "documentStatus", width: 400, displayName: "Status", enableColumnMenu: false, enableFiltering: false },
     { field: "proposedFixes", width: 300, displayName: "Proposed Fixes", enableColumnMenu: false, filter: { selectOptions: this.proposedFixes, type: this.uiGridConstants.filter.SELECT } }
 ];

 return schema;
```

 }

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
