### ISSUE TITLE
Return types for IHttpService's HTTP methods are wrong

### ISSUE THREAD

**Issue by rickwebiii** [DefinitelyTyped/DefinitelyTyped#7796]
get, delete, post, and every other http method should return an `IHttpPromise<IHttpPromiseCallbackArg<T>>` instead of an `IHttpPromise<T>`.

**Comment by horiuchi** [comment]
Please fix this bug, and send pull request!

**Comment by mmiszy** [comment]
That's not valid. Check the angular-tests.ts file, the promise is actually resolved with `IHttpPromiseCallbackArg`. This is because `$http` methods return `IHttpPromise<T>` but the definition of `IHttpPromise` is in fact a `IHttpPromiseCallbackArg<T>` wrapped in a promise – exactly what you want to have.
```typescript
interface IHttpPromise<T> extends IPromise<IHttpPromiseCallbackArg<T>> {
```
