### ISSUE TITLE
Using RequestPromise .d.ts file.    Property 'then' does not exist on type 'Request'.

### ISSUE THREAD

**Issue by bkbonner** [DefinitelyTyped/DefinitelyTyped#7850]
Hi, there are a few things that are unclear on the request-promise.d.ts file.
1.  the last two lines are:

```
    var requestPromise: request.RequestAPI<RequestPromise, RequestPromiseOptions, request.RequiredUriUrl>;
    export = requestPromise;
```

what do these mean?   How do I get to RequestPromise?
1.  When I write code using the request promise code, I have:

```
import * as rp from "request-promise";
export class Service {
    getProjects(): void {
        rp.get("urlgoeshere").auth("username_goes_here", "password_goes_here").then(...);              
    }
}
```

It gives me an error on ".then"  Property 'then' does not exist on type 'Request'.

So it looks like it's caused because of the chaining.   The request.d.ts file shows that it's returning a Request...and RequestPromise extends Request...so I thought it should work.

Any insight on why this is happening...and what I can do to fix it?

**Comment by bkbonner** [comment]
Maybe I'm calling it in a way that I was expecting to behave, but maybe it doesn't support that.

I looked at the [tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/request-promise/request-promise-tests.ts) and it looks like I can't do was I was hoping for.  I was really hoping it would extend it and properly support request chaining, but it looks like the tests don't indicate that.

I'm still unclear on the requestAPI syntax of:
```
 requestPromise: request.RequestAPI<RequestPromise, RequestPromiseOptions, request.RequiredUriUrl>;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
