### ISSUE TITLE
How can I know the cursor absolute position in text?

### ISSUE THREAD

**Issue by VascoPessanha** [DefinitelyTyped/DefinitelyTyped#7894]
Hi guys,
The ace editor seems to work with positions with row and col, but I would like to know the specific absolute position inside the text (for example knowing how many characters are before the cursor).

This was already asked in the following forum:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/883

Is there a simple way to do this or do I need to do this algorithm manually?
Cheers,
Vasco

**Comment by hugoruscitti** [comment]
Hi @VascoPessanha, you can use some like this to get the absolute position:

```
editor.session.doc.positionToIndex(editor.selection.getCursor()) 
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
