### ISSUE TITLE
New "bind" overload function require

### ISSUE THREAD

**Issue by bchukiat** [DefinitelyTyped/DefinitelyTyped#7913]
I need to add the new "bind" overload function into jquery.d.ts to let it compile without error when I want to return extra object through the callback function.

bind(eventType: string, handler: (eventObject: JQueryEventObject, obj:any) => any): JQuery;

**Comment by vvakame** [comment]
@johnnyreilly ?

**Comment by johnnyreilly** [comment]
I don't think I understand.  An example would be helpful?

**Comment by bchukiat** [comment]
Hi John and Wakame-san,

Greeting from Thailand,

Regarding to jQuery bind example (http://api.jquery.com/bind/) on custom
event,

$( "p" ).trigger( "myCustomEvent", [ "John" ] );

$( "p" ).bind( "myCustomEvent", function( e, myName, myValue ) {.....


In order to implement this, I need to add the below line into  jquery.d.ts

bind(eventType: string, handler: (eventObject: JQueryEventObject,* obj:any*)
=> any): JQuery;

thus let the TypeScript compiler happy.

But every time I upgrade jquery.d.ts, I need to add this line manually. So,
it will be good if you help to add this functionality into jquery.d.ts.

Do hope you understand and "Khob khun krub"( = thank you).


Warm Regards,

Chukiat





On Sat, Feb 6, 2016 at 11:04 PM, John Reilly <notifications@github.com>
wrote:

> I don't think I understand. An example would be helpful?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7913#issuecomment-180798288>
> .
>



-- 
Chukiat B.
085-171 7700

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
