### ISSUE TITLE
SEQUELIZE: Sequelize.import test or example

### ISSUE THREAD

**Issue by afaayerhan** [DefinitelyTyped/DefinitelyTyped#7916]
currently Sequelize.import does not have a test to show how to use it with typescript in sequelize-test.ts file or does anyone has good example like this https://github.com/sequelize/express-example in typescript

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
