### ISSUE TITLE
es6-promise.d.ts Promise.reject should be also generic.

### ISSUE THREAD

**Issue by aichi** [DefinitelyTyped/DefinitelyTyped#7932]
Imagine you have method  which return typed promise. If you would like to return rejected promise you have to cast it as shown bellow:

```
do(): Promise<void> {
  if (something) {
        return Promise.reject(new Error()) as Promise<void>;
  }
  return Promise.resolve<void>();
};
```

I would expect same generic method as resolve so I would like to write it this way: 

```
do(): Promise<void> {
...
  return Promise.<void>reject(new Error());
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
