### ISSUE TITLE
Lodash: duplicate definitions

### ISSUE THREAD

**Issue by HarelM** [DefinitelyTyped/DefinitelyTyped#7940]
When downloading the latest nuget package lodash is getting two files: version 4.0 and version 3.10.
this causes compilation error due to duplicate declarations.

**Comment by vvakame** [comment]
@staxmanade ?

**Comment by staxmanade** [comment]
Looks like we should move the older version into the legacy folder.

`lodash-3.10.d.ts` -> `./legacy/lodash-3.10.d.ts`
`lodash-tests-3.10.ts` -> `./legacy/lodash-tests-3.10.ts`

This would exclude it from the nuget packaging.

**Comment by HarelM** [comment]
Is this planned to be fix in any future release? I have been updating this package for the last three times and this wasn't fixed. It's extremely annoying... I'm sure it a matter of 5 minutes to do.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
