### ISSUE TITLE
Lovefield.d.ts: in RawForeignKeySpec, timing option should be of type ConstraintTiming

### ISSUE THREAD

**Issue by Kornik34** [DefinitelyTyped/DefinitelyTyped#7954]
Actually, in RawForeignKeySpec, the options "action" and "timing" are both of type ConstraintAction. The "timing" option should be of type "ConstraintTiming" like this:

type RawForeignKeySpec = {
   local: string
   ref: string
   action?: lf.ConstraintAction
   timing?: lf.ConstraintTiming
}

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by Kornik34** [comment]
done in #8014. I'm not sure to have it done well. It was my first pull request. The create request process is not really easy to understand...

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
