### ISSUE TITLE
sendgrid constructor should be callable with just the API key

### ISSUE THREAD

**Issue by MrWako** [DefinitelyTyped/DefinitelyTyped#7966]
Hi Folks,

Noticed that the sendgrid constructor should be able to be called with a single argument as done in the examples:

https://github.com/sendgrid/sendgrid-nodejs

so I think the api_key argument on

```
    interface Constructor {
        (api_user: string, api_key: string, options?: Options): Instance;
        new (api_user: string, api_key: string, options?: Options): Instance;
    }
```

needs to be made optional. Looking at the javascript the first argument is `apiUserorKey`, and is used for both bits of data depending on how many arguments are supplied.

```
var Sendgrid = function(apiUserOrKey, apiKeyOrOptions, options) {...}
```

Perhaps this is just because the sendgird node package is now at 2.0.0.

My workaround is to pass the api key as the first arguement and `undefined` as the second argument.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by xChrisPx** [comment]
Is this still up to date? I am having a similar issue linked to it, or maybe it's just my ineptitude of using the definitions. Could you take a look at this please? http://stackoverflow.com/questions/36446199/typescript-definitions-for-sendgrid

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
