### ISSUE TITLE
consider automatically tagging PR's with a label indicating the project they touch

### ISSUE THREAD

**Issue by brandf** [DefinitelyTyped/DefinitelyTyped#7974]
I would like to start getting involved with the bluebird definitions, so I thought I'd keep an eye on PR's that touch this project.  This would be made easier if I could filter the 400+ PR's to only those that touch bluebird.  

It looks like there is a bot to notify project owners upon a new PR, so I'd like to suggest that bot also label the PRs appropriately.

Thanks for consideration.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
