### ISSUE TITLE
leaflet.d.ts update broke existing project

### ISSUE THREAD

**Issue by marsmith** [DefinitelyTyped/DefinitelyTyped#7988]
Looks like something in #7925 maybe or another one of the commits that affected leaflet in the last 24 hours

**Comment by vvakame** [comment]
what kind of error do you get?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
