### ISSUE TITLE
Q.d.ts - global 'Q' reference is confusing

### ISSUE THREAD

**Issue by sp00x** [DefinitelyTyped/DefinitelyTyped#8013]
Not sure if this is just plain wrong usage from my side, but it had me confused for a bit when using from Node.js:

Compiles fine, shows intellisense in Atom with atom-typescript installed, but blows up at runtime:

```
/// <reference path="typings/q/Q.d.ts"/>
Q.defer(); // compiles fine, but at runtime: ReferenceError: Q is not defined
```

Using a lower-case q variable was what made me see the problem in the case above (missing import):

```
/// <reference path="typings/q/Q.d.ts"/>
q.defer(); // doesn't compile: cannot find name 'q'
```

Obviously this is how it's supposed to be:

```
/// <reference path="typings/q/Q.d.ts"/>
import q = require('q');
q.defer();
```

FWIW, this is what I had first, but then moved the code to a separate file but forgot the import:

```
/// <reference path="typings/q/Q.d.ts"/>
import Q = require('q');
Q.defer();
```

I'm not sure if I am just doing something weird and wrong here (capital Q), or this is a problem with how the type is defined?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
