### ISSUE TITLE
Marionette.CollectionView - collection is missing

### ISSUE THREAD

**Issue by misantronic** [DefinitelyTyped/DefinitelyTyped#8052]
I'm pretty new to DefinitelyTyped.

`Marionette.CompositeView` and `Marionette.CollectionView` always tells me, that `collection` is an "unresolved variable".
Is this because in 

``` typescript
 class CollectionView<TModel extends Backbone.Model, TView extends View<Backbone.Model>> extends View<TModel>
```

the `collection` is missing as a property?

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
