### ISSUE TITLE
Node typing failing on BuffType

### ISSUE THREAD

**Issue by Foxandxss** [DefinitelyTyped/DefinitelyTyped#8058]
I want to ping @jvilk here for introducing this change.

I am using node.d.ts (tried on 4.2.2 and latest 5.x) and I get:

(416,9): error TS2502: 'BuffType' is referenced directly or indirectly in its own type annotation.
(417,9): error TS2502: 'SlowBuffType' is referenced directly or indirectly in its own type annotation.

I don't think this is normal, isn't it?

Thank you.

**Comment by jvilk** [comment]
That's abnormal... what version of TypeScript are you using? I'm using 1.7.3.

**Comment by Foxandxss** [comment]
I am at 1.7.5

**Comment by jvilk** [comment]
Just upgraded, and no problem?

```
$ tsc --version
message TS6029: Version 1.7.5
$ tsc --module commonjs node/node.d.ts
$
```

**Comment by Foxandxss** [comment]
Oh, I can see that as well. I am no TS / d.ts expert so I can't see what's fishy. On my project with a tsconfig I get a bunch of dupes and (TS2300) and this two. I build against ES5 and commonjs as well.

I will research a bit more to see if the problem is only in my end.

**Comment by jvilk** [comment]
Maybe you are accidentally including two copies `node.d.ts`? I've done that before with dependencies that `/// <reference` a separate `node.d.ts` file, and learned the hard way to avoid any reference tags in dependencies!

**Comment by jvilk** [comment]
(I now just put `.d.ts` files in `tsconfig` instead of `reference`ing them)

**Comment by datoml** [comment]
I got the same error :(.

**Comment by jvilk** [comment]
@datoml check the same things I suggested to @Foxandxss . If you are using the correct version of TypeScript, and aren't including `node.d.ts` twice somehow, then it works.

**Comment by datoml** [comment]
Checked the code. There are no two references.
But I found out that this boilerplate i tried had some issues with typings.
It downloaded an old node.d.ts file.
But I have to investigate further why.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
