### ISSUE TITLE
node.d.ts "global" conflict with Classical

### ISSUE THREAD

**Issue by ScallyGames** [DefinitelyTyped/DefinitelyTyped#8060]
In node.d.ts "declare var global: NodeJS.Global" conflicts with the definition in Classical (https://github.com/drubino/Classical) causing my TypeScript compiler to throw an error. Since I'm rather new to TypeScript I am not sure how to fix this.

**Comment by vvakame** [comment]
I think you should open this issue to Classical repo.
https://github.com/drubino/Classical/blob/master/bin/classical.d.ts#L24
this declaration is not useful... I think this line can be remove.

FYI, https://github.com/Microsoft/TypeScript/issues/3215

**Comment by drubino** [comment]
Thank you for bringing this issue to our attention. I believe the global declaration can be removed from classical.d.ts file for now. We will address this issue in our next version.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
