### ISSUE TITLE
ui-router-extras definitions seem to be incomplete

### ISSUE THREAD

**Issue by jacob-robertson** [DefinitelyTyped/DefinitelyTyped#8062]
I'm pulling the ui-router-extras using tsd, but it seems like the definitions are incomplete.  It's definitely missing some of the property extensions to the IState interface that one needs when configuring deep state redirects.  The file in this other repo seems to be more correct.  At least, it has the things I need.

https://github.com/marcel-k/UiRouterStickyStates/blob/master/typings/ui-router-extras/ui-router-extras.d.ts

I would attempt to reconcile this myself, but I'm not sure either version of the definitions is actually complete.  I'll leave it in the (more) capable hands of someone else and include the other file manually for now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
