### ISSUE TITLE
Naming conventions for interfaces

### ISSUE THREAD

**Issue by rekna1** [DefinitelyTyped/DefinitelyTyped#810]
Some definition files use an I prefix for interfaces, other don't...
(e.g. angular does, restangular or signalr doesn't)
Would it be better to have some common naming convention (all interfaces start with the prefix I )?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
