### ISSUE TITLE
Clipboard.js does not match actual usage

### ISSUE THREAD

**Issue by longzheng** [DefinitelyTyped/DefinitelyTyped#8126]
@impworks I noticed that you added a wrapper for clipboard.js typedefinition with the npm name in this commit so it's `new clipboard.Clipboard(...)`
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/9d3c0e31928a196677b1371a350a363cf1357317

However the actual clipboard.js usage does _not_ use the npm namespace. It's just a global `new Clipboard(...)`. This conflicts with the TypeDefinition.

**Comment by vvakame** [comment]
please send a pull request, I'll review it.

**Comment by danielmillipede** [comment]
I've just noticed the same thing. Don't have time to submit a PR at the moment, unfortunately.

**Comment by j2jensen** [comment]
This can be closed. The files in question were fixed in subsequent changes.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/clipboard/index.d.ts
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/clipboard/clipboard-tests.ts

**Comment by chulkilee** [comment]
FYI `@types/clipboard` 2.0.0 does not work with clipboard 2.0.1 due to zenorocha/clipboard.js#532

I don't know what is the "correct" way to export ES module - there is open issue zenorocha/clipboard.js#568

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
