### ISSUE TITLE
mssql.d.ts "Promise" cannot be found

### ISSUE THREAD

**Issue by ScallyGames** [DefinitelyTyped/DefinitelyTyped#8130]
"Promise" in Line 148, 150, ... is not defined

**Comment by vvakame** [comment]
@Aides359 please use with `--target es6` or es6-promise.d.ts

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
