### ISSUE TITLE
restangular - responseHandler missing as parameter in setErrorInterceptor

### ISSUE THREAD

**Issue by iberodev** [DefinitelyTyped/DefinitelyTyped#8144]
The current restangular type definition has:
`setErrorInterceptor(errorInterceptor: (response: IResponse, deferred: angular.IDeferred<any>) => any): void;`

but it needs an additional parameter `responseHandler` as per https://github.com/mgonto/restangular#seterrorinterceptor
and
https://github.com/mgonto/restangular/pull/726

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
