### ISSUE TITLE
jQueryUI: `event` types unrecognized, incomplete

### ISSUE THREAD

**Issue by crm416** [DefinitelyTyped/DefinitelyTyped#819]
Using `jqueryui.d.ts` and `jquery.d.ts`, the following code doesn't recnogize the type signature for `change`:

```
var my_slider : JQueryUI.Slider = $("#my_slider").slider;
my_slider ({
    slide: (event , ui) => {
        event++;
        event.text('Text');
        ...  
    }
});
```

It picks up that `my_slider` is indeed of type `JQueryUI.Slider`, but `event` and `ui` are of type `any`.

Additionally, I'm not sure that the `JQueryUI.SliderUIParams` interface is complete. At the moment, it's empty. An appropriate substitution would be:

```
interface SliderUIParams {
    value: number;
    values?: number[];
    handle: JQuery;
}
```

Look forward to hearing from you!

-Charlie

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
