### ISSUE TITLE
Using generics for Backbone.View model

### ISSUE THREAD

**Issue by omidkrad** [DefinitelyTyped/DefinitelyTyped#821]
Hi,

Now that generics is available, is there any way we can fix this?

Please see:
http://typescript.codeplex.com/workitem/699

Thanks,
Omid

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
