### ISSUE TITLE
Not compile nuget filewriter.TypeScript.DefinitelyTyped

### ISSUE THREAD

**Issue by AlexHrom** [DefinitelyTyped/DefinitelyTyped#8270]
Hi,

thanks for good tool for development, but we think that find problem.

We use nuget and last update not compile bacase of this:
file: typings/filewriter/filewriter.d.ts
line: 92

``` typescript
var FileSaver: {
    /**
     * When the FileSaver constructor is called, the user agent must return a new FileSaver object with readyState set to INIT.
     * This constructor must be visible when the script's global object is either a Window object or an object implementing the WorkerUtils interface.
     */    new(data:Blob): FileSaver;}
```

we think it should add "declare" because in *.d.ts not allow use 'not declare'.
Work version:

``` typescript
declare var FileSaver: {
    /**
     * When the FileSaver constructor is called, the user agent must return a new FileSaver object with readyState set to INIT.
     * This constructor must be visible when the script's global object is either a Window object or an object implementing the WorkerUtils interface.
     */    new(data:Blob): FileSaver;}
```

**Comment by vvakame** [comment]
@staxmanade ?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/163a4277199c3d896d9efffe24ea84c85f55c8ac/filewriter/filewriter.d.ts#L92-L98
![definitelytyped_filewriter_filewriter_d_ts_at_163a4277199c3d896d9efffe24ea84c85f55c8ac_ _definitelytyped_definitelytyped](https://cloud.githubusercontent.com/assets/125332/13370483/d13c6180-dd4b-11e5-87b1-179067ca4141.png)

**Comment by staxmanade** [comment]
The current version on NuGet has the correct `declare var...` syntax: 

[NuGet download link](https://www.nuget.org/api/v2/package/filewriter.TypeScript.DefinitelyTyped/0.8.5)

@AdminShum try making sure you've installed the most recent version from NuGet.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
