### ISSUE TITLE
SlickGrid Sort options wrong

### ISSUE THREAD

**Issue by JJegers** [DefinitelyTyped/DefinitelyTyped#8325]
I am trying to use the SlickGrid Typed code and I see on 9/9/2015 Koloto committed a change to the slickgrid/SlickGrid.d.ts file on line 1328 where the definition was changed.
-   export interface OnSortEventArgs<T extends SlickData> extends GridEventArgs<T> {
      multiColumnSort: boolean;
  -      sortCol?: Column<T>;
  -      sortCols: Column<T>[];
  -      sortAsc?: boolean;
  -      sortCol?: SortColumn<T>;
  -      sortCols?: SortColumn<T>[];
  -      sortAsc: boolean;
    }

In particular the "sortCol?" field I believe should be left as a "Column" type instead of a "SortColumn" type.  (The "SortCols" I believe is correct).  The reason I think this, is in the JS code it does:
          if (!options.multiColumnSort) {
            trigger(self.onSort, {
              multiColumnSort: false,
              sortCol: column,
              sortAsc: sortOpts.sortAsc}, e);
          } else {
            trigger(self.onSort, {
              multiColumnSort: true,
              sortCols: $.map(sortColumns, function(col) {
                return {sortCol: columns[getColumnIndex(col.columnId)], sortAsc: col.sortAsc };
              })}, e);
          }

and when I run it through the debugger I get:
?args.sortCol
    cssClass: "cell-title"
    defaultSortAsc: true
    field: "CompanyName"
    focusable: true
    headerCssClass: null
    id: "CompanyName"
    minWidth: 30
    name: "Company Name"
    rerenderOnResize: false
    resizable: true
    selectable: true
    sortable: true
    width: 200

I've been programming for a long time but this is my first time working with github so please understand if I'm not submitting this request the correct way.
Thanks.

**Comment by vvakame** [comment]
please send a pull request first. We need it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
