### ISSUE TITLE
sqlite3.d.ts: Incorrect return type for function verbose()

### ISSUE THREAD

**Issue by Penryn** [DefinitelyTyped/DefinitelyTyped#8371]
The member `verbose` has an incorrect return type of `void` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/sqlite3/sqlite3.d.ts#L80)

```
 function verbose(): void;
```

Looking at the library's code (https://github.com/mapbox/node-sqlite3/blob/master/lib/sqlite3.js#L156) shows it's actually supposed to return a `sqlite3` object:

```
sqlite3.verbose = function() {
    ...
    return this;
 };
```

I'm not sure how to make a module member return the module type (ie: `this`), otherwise I'd do it myself (I keep getting syntax errors with all my creative answers). So if someone explains a solution but is too lazy to commit it, I can make this change.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by Penryn** [comment]
Er... I don't have the code for a PR, otherwise I would!

> I'm not sure how to make a module member return the module type (ie: `this`).

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
