### ISSUE TITLE
[react.d.ts] DragEvent doesn't contain MouseEvent's properties

### ISSUE THREAD

**Issue by YusongLiu** [DefinitelyTyped/DefinitelyTyped#8395]
I am using react/react.d.ts, and got this error:
error TS2339: Property 'clientY' does not exist on type 'DragEvent'.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
