### ISSUE TITLE
Clarification on submitting definition files for a newer version of a library

### ISSUE THREAD

**Issue by DavidKDeutsch** [DefinitelyTyped/DefinitelyTyped#8413]
I would like to submit a d.ts file for the 0.2.5 version of [gridstack](https://github.com/troolee/gridstack.js). Reading the [contribution guidelines](http://definitelytyped.org/guides/contributing.html), it indicates I should rename the current d.ts file to include its version, and then add mine as the default. But I see a few problems with this:
- People currently using the default name and the old version of the library will have an invalid definition  file for their version.
- If the new file and old file are in the same directory, all users will have to delete one or the other on their machine, or they will get conflicting definitions. I currently have to do that with the lodash definitions.

It would seem to me that it would be best to have different _directories_ for each version, so that separate nuget packages are made, and people could install the version they want. 

All that being said, is my original understanding of the guidelines correct, i.e. that both files should be in the same directory, with the new one as the default?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
