### ISSUE TITLE
Should obsolete methods be included in a definition file?

### ISSUE THREAD

**Issue by DavidKDeutsch** [DefinitelyTyped/DefinitelyTyped#8414]
When writing a definition file, should obsolete methods be included? For the library I am defining, they are callable, but on the other hand, when you _do_ call them, you get a warning in the console that they shouldn't be used and will actually be removed in a future version.

**Comment by vvakame** [comment]
`.d.ts` is guide for programming.
I think you can remove obsolete feature definitions.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
