### ISSUE TITLE
cordova is not defined

### ISSUE THREAD

**Issue by zhouhao27** [DefinitelyTyped/DefinitelyTyped#8499]
I installed cordova and related plugin by:

```
typings install cordova --ambient --save
typings install 'github:DefinitelyTyped/DefinitelyTyped/cordova/plugins/Camera.d.ts#ac7f83bdcf1dfd70e70acf7a87cf8e83719dacd6' --save --ambient 
typings install 'github:DefinitelyTyped/DefinitelyTyped/cordova/plugins/FileSystem.d.ts#ac7f83bdcf1dfd70e70acf7a87cf8e83719dacd6' --save --ambient 

```

I have no problem to use **Camera** plugin. But when I tried to use **file** plugin like this:

```
window.resolveLocalFileSystemURI(cordova.file.applicationDirectory + "www/index.html", (fileEntry)=> {
});
```

I got the following error message:

> cordova is not defined

Don't know what's wrong. Can anybody help? Thanks.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
