### ISSUE TITLE
angular-animate: IModule.animation() does not work in the latest release

### ISSUE THREAD

**Issue by okamiconcept** [DefinitelyTyped/DefinitelyTyped#8503]
I tried using the latest `angularjs/angular-animate.d.ts` file in this repo and had problems.

The IModule.animation() method have moved from module angular to angular.animate, so we can't call the method from the IModule instanciated object

The lines removed are at the end the file:

``` typescript
-declare module angular {
     interface IModule {
-        animate(cssSelector: string, animateFactory: angular.animate.IAnimateFactory): IModule;
+        animation(name: string, animationFactory: IAnimateFactory): IModule;
+        animation(name: string, inlineAnnotatedFunction: any[]): IModule;
+        animation(object: Object): IModule;
     }
+
 }
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by okamiconcept** [comment]
It's done.

**Comment by myty** [comment]
Looking forward to this getting merged. Adding the reference to PR #8566

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
