### ISSUE TITLE
Kendo-Ui DataSource getByUid returns Model

### ISSUE THREAD

**Issue by EmirKrkic** [DefinitelyTyped/DefinitelyTyped#8506]
- [X] I want to talk about `kendo-ui.d.ts`.
  - The authors of that type definition are cc/ @tsvetomir 
    Looking at the documentation on http://docs.telerik.com/kendo-ui/api/javascript/data/datasource#methods-getByUid it states that it should return the ObservableObject but the type in the .ts file is kendo.data.Model. 
    I think this is wrong.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
