### ISSUE TITLE
mithril.d.ts` no intellisense.

### ISSUE THREAD

**Issue by daslicht** [DefinitelyTyped/DefinitelyTyped#8522]
- [ ] I tried using the latest `mithril.d.ts` file but I dont get any intellisense.
  mithril.d.ts should also be available for teh server when rendering mithril components on the server 
  see: https://github.com/StephanHoyer/mithril-node-render

I tried importing the browser d.ts but still no luck , idea?

**Comment by vvakame** [comment]
@lhorie @cbowdon ?

**Comment by cbowdon** [comment]
Sorry - I'm not able to use VS for this so can't really help. You might want to try confirming you do get intellisense for other defs and trying to figure out what's different.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
