### ISSUE TITLE
Express.dts server-static import error ?

### ISSUE THREAD

**Issue by daslicht** [DefinitelyTyped/DefinitelyTyped#8529]
- [ ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
  The following line : 
  https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/express/express.d.ts#L28

Throws the following error:
typings/main/ambient/express/index.d.ts(28,34): error TS2307: Cannot find module 'serve-static'.

?

**Comment by daslicht** [comment]
installing the typing for serve-static solved this, shouldn't it be automatic installed as dependency ?

**Comment by hewholived** [comment]
+1 ^^

**Comment by daslicht** [comment]
same with mimetype

**Comment by HB-2012** [comment]
It took me a few hours to figure this one out... Please add this as a dependency to make it easier for people who are just introduced to DefinitelyTyped.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
