### ISSUE TITLE
fs-promise is not defined but would be identical to fs-extra-promise

### ISSUE THREAD

**Issue by kruncher** [DefinitelyTyped/DefinitelyTyped#8542]
- [x] I tried using the latest `fs-extra-promise/fs-extra-promise.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `fs-extra-promise/fs-extra-promise.d.ts`.
  - The authors of that type definition are cc/ @midknight41 and @jasonswearingen

The [fs-promise](https://www.npmjs.com/package/fs-promise) package on npm (with higher download counts) includes promise support for `fs-extra` and seems to expose the same API described by `fs-extra-promise.d.ts`. The only trouble is that the package name is different and thus the `fs-extra-promise` type definitions do not work with `fs-promise`.

What would be the best way to approach adding the same definitions under the name `fs-promise/fs-promise.d.ts`?

Many thanks!

**Comment by jasonswearingen** [comment]
Hi @kruncher if the d.ts author does it right, in the d.ts file the definition's interface will be seperate from what's being exported (the ambient typing).  If so, you can reference the d.ts and create your own export that uses the original interface.

in this specific example however, you can not do that.   when I create my own typings I make sure to seperate the interface from the export, but in this situation I just copy/pasted the typing found in the node.d.ts and changed it to use promises.   I have complained about the encapsulation of interface declarations in ambient typings before but it's not going to change.

So in this example I strongly recomend you just copy the entire fs-extra-promise.d.ts file and rename the stuff you want.    copy/pasting is bad, but the other option is to convert the fs-extra-promise.d.ts to export the interface seperately.     If you want to do that, I'd be happy with a pull request but probably just easier to "let it go" in this example, since the underlying Node fs module isn't going to change, so no need to worry about the copy/pasted version getting obsolete.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
