### ISSUE TITLE
Extend function types in when.d.ts to arbitrary number of parameters

### ISSUE THREAD

**Issue by hanneshdc** [DefinitelyTyped/DefinitelyTyped#8551]
Example problem: I can't use when.lift on methods with more than 5 parameters.

The fix would be to add an extra definition using the ...args syntax to support any number of parameters. The drawback is that there would be no type checking on the parameters of the lifted function if there are more than 5, but this is better than it failing completely.

This applies to call, apply, spread and attempt too.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
