### ISSUE TITLE
zip.js.d.ts checks out on its own

### ISSUE THREAD

**Issue by DmitryEfimenko** [DefinitelyTyped/DefinitelyTyped#8577]
- I want to talk about `zip.js/zip.js.d.ts`.
  - The authors of that type definition are cc/ @lgrignon 

Whenever I pull a local copy of `DefinitellyTyped` repository, the two files: `zip.js.d.ts` and `zip.js-tests.ts` are getting checked out automatically even though this definitions are completely irrelevant to what I want to work on and I never touch them.

I also can't seem to undo pending changes to these files. The moment I select "Undo", they get re-checked out.

Anyone else has this issue?

**Comment by lgrignon** [comment]
Never noticed the problem you mentionned, sorry.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
