### ISSUE TITLE
core interfaces not fully implemented

### ISSUE THREAD

**Issue by omnibusinc** [DefinitelyTyped/DefinitelyTyped#8578]
- [x ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.

Some of the fuctions in interfaces in express-serve-static-core which inherit from interfaces in node.d.ts aren't being recognized.
For example, in node.d.ts's ServerResponse interface, signatures for 'end' and writeHead' methods are defined.
In express-serve-static-core, the Response interface inherits from node's ServerResponse.
In express.d.ts, the Response interface extends core.Response.
If, however, we try to do this, the 'end' and 'writeHead' functions are not recognized on the Express.Response type:

proxy.on('error', (error: any, req: Express.Request, res: Express.Response) => {
  if (!res['headersSent']) {
    res.writeHead(500, {'content-type': 'application/json'});
  }
  var json = {error: 'proxy_error', reason: error.message};
  res.end(JSON.stringify(json));
});  

Specifically, the IDE (Atom) reports that:
"Property 'writeHead' does note exist on type 'Response'", 
"Property 'end' does note exist on type 'Response'",

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
