### ISSUE TITLE
webmidi definition update

### ISSUE THREAD

**Issue by QuaxelBrod** [DefinitelyTyped/DefinitelyTyped#8588]
After fiddeling arround with webmidi I think there is something missing:
Interface MIDIInput and MIDIOutput should extend MIDIPort.
After getting access to Midi I can iterate through the list of devices, but all Information about that device is missing in .d.ts. In console.log you find all the properties
- [X ] I tried using the latest `webmidi/webmidi.d.ts` file in this repo and had problems.
- [X ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
