### ISSUE TITLE
There is something wrong with `form-data`

### ISSUE THREAD

**Issue by OxOOo** [DefinitelyTyped/DefinitelyTyped#8615]
At present `form-data` module is exactly a class, but the d.ts file is too old.
- [x] I tried using the latest `form-data/form-data.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `form-data/form-data.d.ts`.
  - The authors of that type definition are cc/ @....

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
