### ISSUE TITLE
knockout.d.ts has problems

### ISSUE THREAD

**Issue by pgorbas** [DefinitelyTyped/DefinitelyTyped#8625]
- [x] I tried using the latest `knockout.d.ts` file in this repo and had problems.
- [x] Downloads are not working at [http://knockoutjs.com]

![image](https://cloud.githubusercontent.com/assets/11726837/13889259/95167a42-ed13-11e5-8652-4e82f54c6a91.png)

![image](https://cloud.githubusercontent.com/assets/11726837/13889281/be37bb2a-ed13-11e5-85d3-afba444e9a08.png)

![image](https://cloud.githubusercontent.com/assets/11726837/13889385/50590e14-ed14-11e5-8e90-94749d3ce0dc.png)

![image](https://cloud.githubusercontent.com/assets/11726837/13889489/cc5a6b3e-ed14-11e5-85ce-ca43ec54568e.png)

**Comment by vvakame** [comment]
What version of tsc do you use? please try with tsc 1.8.7.

**Comment by ltlombardi** [comment]
This should be closed. :blush:

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
