### ISSUE TITLE
And You know es6 modules?

### ISSUE THREAD

**Issue by acopalipsis** [DefinitelyTyped/DefinitelyTyped#8727]
`import * as React from "react";`  
I wouldn't say if this line was written on the back of a porn star. But personally I'm not into porn school and realize that this import can only pornographer to write. Rewrite the code so that the import was correct 
`import React from "react";`  
And finish writing code in Notepad, already 2016 and there are ide which simply will not let this shameful code.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
