### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by hamid6** [DefinitelyTyped/DefinitelyTyped#8735]
This question might have already been asked, but why did DT not create versioned definitions at first?

Something like:

|--node
|----0.10.10
|------node.d.ts
|----0.10.11
|------node.d.ts
|----0.4.2
|------node.d.ts
|--lodash
|----0.3.4
|------lodash.d.ts
|----0.3.5
|------lodash.d.ts

**Comment by vvakame** [comment]
We can't maintain it.
Our resource is limited. 
For example, the old version definitions is removed at the time of version-up tsc.

**Comment by matthiasg** [comment]
Explicitly stating the version (not inside an unstructured comment) would go a long way. e.g tooling could use that to still show infos when semver is major/minor compatible. could warn when minor/major differences (might now show all - minor, might be wrong - major).

Nobody should expect full version up-to-dateness, but there is no long-term value in types when the intellisense offered by types gets outdated WITHOUT seeing it. In the worst, compilers would make to write wrong code which fails at runtime and it might take some time to find out why because devs wouldnt have looked at it first.

At the very least the tsd tool could use that version information to compare with npm information and print a report. That could be integrated ala lint into a compile process.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
