### ISSUE TITLE
node-azure module name

### ISSUE THREAD

**Issue by connelhooley** [DefinitelyTyped/DefinitelyTyped#8788]
The module name appears to be out of date/incorrect. It should be "azure-storage" not "azure".

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node-azure/azure.d.ts

As per the guide here:
https://azure.microsoft.com/en-gb/documentation/articles/storage-nodejs-how-to-use-table-storage/

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
