### ISSUE TITLE
Handlebars Duplicate Identifier Compile Errors NuGet package

### ISSUE THREAD

**Issue by bradlis7** [DefinitelyTyped/DefinitelyTyped#8798]
After adding the NuGet package `Handlebars.TypeScript.DefinitelyTyped`, it's throwing a lot of "Duplicate Identifier" errors because there are two handlebars files. My project will not compile with it installed.

**Comment by vvakame** [comment]
what version of tsc do you use?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
