### ISSUE TITLE
'_.intersectionBy()' method is stated as not chainable

### ISSUE THREAD

**Issue by ZuBB** [DefinitelyTyped/DefinitelyTyped#8814]
Hi there!

I tried using the latest (is it this one e12c8e3bcdd77fb05d498ec61525be6ad112dfd6 ?) `lodash/lodash.d.ts` file in this repo and had problems.

> error TS2339: Property 'intersectionBy' does not exist on type 'LoDashImplicitObjectWrapper<any>'.

Could you please fix that?

Thanks in advance

**Comment by vvakame** [comment]
please send a pull request.
cc/ @chrootsu

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
