### ISSUE TITLE
Latest node.d.ts isn't supported Node.js v5.x API

### ISSUE THREAD

**Issue by xr0master** [DefinitelyTyped/DefinitelyTyped#8815]
- [X] I tried using the latest `node/node.d.ts` file in this repo and had problems.
- [X] I want to talk about `node/node.d.ts`.
  - The authors of that type definition are cc/ @vvakame

**Comment by vvakame** [comment]
please send a pull request.

**Comment by buildjosh** [comment]
I guess now we need 6.x definitions. One question I have though is can multiple versions of the definitions exist at once? So for instance the Buffer class in node 6.x has alloc(), .from(), etc that are meant to replace the new() constructor, but 4.x still uses the new() constructor.

**Comment by vvakame** [comment]
@buildjosh  I made #9341 . please check it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
