### ISSUE TITLE
using shortcut of RequestAPI<Request, CoreOptions, RequiredUriUrl>

### ISSUE THREAD

**Issue by hbakhtiyor** [DefinitelyTyped/DefinitelyTyped#8846]
- [ ] I want to talk about `request/request.d.ts`.
  - The authors of that type definition are cc/ @soywiz, @bonnici, @Bartvds, @joeskeen, @ccurrens

i use `github:DefinitelyTyped/DefinitelyTyped/request/request.d.ts#2d64e0d9450e084b30f5c0e39e88a5a861a6d7c1`

``` ts
import {Request, CoreOptions, RequiredUriUrl, RequestAPI} from "request";

export class Dummy {
    constructor(request: RequestAPI<Request, CoreOptions, RequiredUriUrl>) {

    }
}
```

what's the shortcut of the `RequestAPI<Request, CoreOptions, RequiredUriUrl>`?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
