### ISSUE TITLE
noUiSlider error TS2307

### ISSUE THREAD

**Issue by dawidk92** [DefinitelyTyped/DefinitelyTyped#8852]
`import * as noUiSlider from 'nouislider';`
outputs error TS2307: Cannot find module 'nouislider' but it works.

typings 0.7.12
tsc 1.8.9

typings.json:
`"nouislider": "registry:dt/nouislider#8.0.2+20160317120654"`

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/nouislider/nouislider.d.ts does not have `declare module "nouislider" { ...`. please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
