### ISSUE TITLE
How much time it takes to merge the pull request after all the checks have passed?

### ISSUE THREAD

**Issue by Syncfusion-JavaScript** [DefinitelyTyped/DefinitelyTyped#8897]
What is the approximate time takes to merge the pull request into the repo after all the checks have passed? I cant find this info anywhere in the contribution guide.

**Comment by sumitkm** [comment]
I think the process after automated checks is pretty manual. I've had my definition PR merged within a 36 hours if I remember correctly. There is no eta as such I guess!

**Comment by vvakame** [comment]
Finally, merge is manual operation.
Reviews have been doing in about 2-5 day intervals when I cheerful.

https://github.com/DefinitelyTyped/dt-review-bot

**Comment by scharf** [comment]
who is doing the manual merge?

**Comment by vvakame** [comment]
me and @horiuchi and other @DefinitelyTyped/contributors .

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
