### ISSUE TITLE
Issue with Provider<T> type.

### ISSUE THREAD

**Issue by dzmitrypaulouski** [DefinitelyTyped/DefinitelyTyped#8913]
I tried using the latest `angular-odata-resources.d.ts` file in this repo and had problems.

There is a `Provider<T>` class in this typings that has next method:
        `get(key: any, success?: ((p:T)=>void), error?: (()=>void)): T;`

The return type of this method (in typings) is `T` so I can't use `$promise` property to retrieve data using promise. But when I checked the returned value in JavaScript I found that it has `$promise` property and has the `Resource` type.

So is it correct to use "`T`" as return type or it should be `IResource<T>`?

P.S. `Provider<T>` class is not covered by tests.

**Comment by vvakame** [comment]
IMHO, `T & IResource<T>` ?
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
