### ISSUE TITLE
Shouldn't faceVertexUvs:Vector2[][] in THREE.Geometry really be Vector2[][][]? 

### ISSUE THREAD

**Issue by saabi** [DefinitelyTyped/DefinitelyTyped#8935]
@florentpoujol @gyohk
Basically that...

I was adapting the [million letter demo](https://github.com/html5rocks/www.html5rocks.com/tree/master/content/tutorials/webgl/million_letters/static) from Javascript to Typescript and I kept getting a typechecking compilation error.

This is the [original, working, code](https://github.com/html5rocks/www.html5rocks.com/blob/master/content/tutorials/webgl/million_letters/static/particles_three.js#L66):

``` javascript
    geo.faceVertexUvs[0].push([
      new THREE.Vector2( ox, oy+off ),
      new THREE.Vector2( ox+off, oy+off ),
      new THREE.Vector2( ox+off, oy )
    ]);
    geo.faceVertexUvs[0].push([
      new THREE.Vector2( ox, oy+off ),
      new THREE.Vector2( ox+off, oy ),
      new THREE.Vector2( ox, oy )
    ]);
```

The compiler kept expecting me to push simple Vector2 objects until I added the additional [] to the type definition file.

**Comment by florentpoujol** [comment]
Indeed, in the code we can see that an array of Vector2 is pushed as new entry of an array, itself the first entry of `geo.faceVertexUvs`. 

So there is 3 arrays and `Vector2[][][]` is the correct definition.

I will add it to pull #8825 , thanks !

**Comment by saabi** [comment]
Sure, I was kind of sleepy and overworked at the time so I wasn't too sure what was going on.

I guess the correct way of looking at it is an array of layers, containing arrays of faces, containing arrays of Vector2s for each UV coordinate.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
