### ISSUE TITLE
async definition wrong

### ISSUE THREAD

**Issue by murcal** [DefinitelyTyped/DefinitelyTyped#8937]
Original: doWhilst(fn: AsyncVoidFunction, test: () => boolean, callback: (err: any) => void): void;
Working:  doWhilst<T>(fn: any, test: (data: any) => boolean, callback: (err: any) => void): void;

It is possible to add results to the callback and the test function. The current version asumes a AsyncVoid which does not provide the callback function with a error and result return.

Working example:

``` js
async.doWhilst(function(callback) {
    let res ={done: false};
    callback(null, res);
}, function(res) {
    return !res.done;
}, function(err) {
    console.log(err);
    console.log('done iter1');
});
```

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
