### ISSUE TITLE
d3 scales should allow string ranges

### ISSUE THREAD

**Issue by danvk** [DefinitelyTyped/DefinitelyTyped#8941]
For example:

```javascript
> d3.scale.linear().range(['white', 'red'])(0.5)
#ff8080"
```

But with TypeScript, I get the following error:

```
error TS2345: Argument of type 'string[]' is not assignable to parameter of type 'number[]'.
  Type 'string' is not assignable to type 'number'.
```

The `.range()` method should accept `string[]` as well as `number[]`.

- [x] I tried using the latest `d3/d3.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `d3/d3.d.ts`.
  - The authors of that type definition are cc/ @gustavderdrache, @borisyankov

**Comment by gustavderdrache** [comment]
I tried to balance the flexibility of D3's scales with "proper" type safety, so I compromised by creating  [multiple overloads](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/d3/d3.d.ts#L1502-L1504) of the scale constructors:

* `d3.scale.linear()` creates a linear scale that outputs numbers,
* `d3.scale.linear<Output>()` creates a linear scale that outputs values of type `Output`, and
* `d3.scale.linear<Range, Output>()` creates a linear scale that outputs values of type `Output` and requires an [interpolator factory](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/d3/d3.d.ts#L1519) that is compatible with `(a: Range, b: Range) => (t: number) => Output`.

The last overload exists largely for compatibility with the [color interpolation functions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/d3/d3.d.ts#L1707-L1713), since they can take color instances or simple strings.

With all that in mind, you just need to add `<string>` at the end of your call to `d3.scale.linear`:

```typescript
let scale = d3.scale.linear<string>().range(['white', 'red']);
let result: string = scale(0.5);
```

**Comment by danvk** [comment]
Perfect, `d3.scale.linear<string>` it is! Thanks for the quick response, @gustavderdrache.
