### ISSUE TITLE
IReply interface should have state(key: string, value: string) method added

### ISSUE THREAD

**Issue by bherila** [DefinitelyTyped/DefinitelyTyped#8946]
- [X] I tried using the latest https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/hapi/hapi.d.ts
  file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/hapi/hapi.d.ts#L242
  - The authors of that type definition are cc/ @....

IReply interface should have `state(key: string, value: string)` method added.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by bherila** [comment]
included in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8960

**Comment by AJamesPhillips** [comment]
We can close this now @bherila @DefinitelyTyped

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
