### ISSUE TITLE
Leaflet .on() overloads

### ISSUE THREAD

**Issue by danvk** [DefinitelyTyped/DefinitelyTyped#8959]
The `.on()` methods for Leaflet are [declared as](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/641df27e73ca67fa7199a3deedae104198d41a17/leaflet/leaflet.d.ts#L490):

``` ts
  on(type: string, fn: (e: LeafletEvent) => void, context?: any): Layers;
  once(type: string, fn: (e: LeafletEvent) => void, context?: any): Layers;
  off(type: string, fn?: (e: LeafletEvent) => void, context?: any): Layers;
```

But `LeafletEvent` is often too generic. For example, if I register a handler via `layer.on('mouseover', e => { ... })` then then `e` parameter is really a `LeafletMouseEvent`, which has more specific properties.

These methods should be overloaded to have more precise event types in the callback depending on the 
event. This does seem to be possible in TS. See, e.g. [`createElement`](https://github.com/Microsoft/TypeScript/blob/873574fa659552f443cd9c54210fcb54cade3588/src/lib/dom.generated.d.ts#L2783), which will return `HTMLAnchorElement` when called as `createElement('a')`, `HTMLDivElement` for `'div'`, etc.
- [x] I tried using the latest `leaflet/leaflet.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `leaflet/leaflet.d.ts`.
  - The authors of that type definition are cc/ @rgripper

**Comment by vvakame** [comment]
please send a pull request.

**Comment by rgripper** [comment]
@vvakame :+1:

**Comment by kygoh** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b325764a0b804d8215611d234e63d8e9612e6402/types/leaflet/index.d.ts#L332-L486

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
