### ISSUE TITLE
libxmljs: i get a runtime error: XMLDocument is not a function

### ISSUE THREAD

**Issue by wallride** [DefinitelyTyped/DefinitelyTyped#8991]
- [X] I tried using the latest `libxmljs/libxmljs.d.ts` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The author of that type definition is François de Campredon https://github.com/fdecampredon

Hi there! The definition for the libxmljs seems to be inactual. Definition has a class named XMLDocument, but the JS-module has only Document function. I guess the HTMLDocument class is invalid too. 
Current libxmljs version is 0.17.1 and the definition is for 0.14.2

Don't you think it should be updated?

**Comment by vvakame** [comment]
please send a pull request first.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
