### ISSUE TITLE
blueimp-md5: blueimp.md5 is not a function

### ISSUE THREAD

**Issue by Zzzen** [DefinitelyTyped/DefinitelyTyped#8996]
- [x] I tried using the latest `blueimp-md5.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I want to talk about `xxxx/xxxx.d.ts`.
  Error occurs when I try to use the definition file like this `hashed = require("blueimg-md5").md5("my string")`.
  From [npm page](https://www.npmjs.com/package/blueimp-md5), we can see that the export of this module is simply a function.

```
    // Use the following version if you installed the package with npm: 
        var md5 = require("blueimp-md5"), 
        query = url.parse(req.url).query;
    // Calculate and print the MD5 hash of the url query: 
    res.end(md5(query));
```

The definition should be 

```
declare module 'blueimp-md5' {
    function md5(value: string, key?: string, raw?: boolean): string;
    export = md5;
}
```

rather than

```
declare module 'blueimp-md5' {
    export function md5(value: string, key?: string, raw?: boolean): string;
}
```

**Comment by otobrglez** [comment]
I have the same problem. ;| Definition is still the same.

**Comment by m927259903** [comment]
me too.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
