### ISSUE TITLE
CordovaPlugin doesn't have XXX property

### ISSUE THREAD

**Issue by davidleon** [DefinitelyTyped/DefinitelyTyped#8997]
I tried to install typings install cordova. and install phonegap-plugin-barcodeScanner
the ts compiler complains the cordova.plugins of type CordovaPlugin doesn't have barcodeScanner property.
Is it better to define the interface CordovaPlugin as any? 
- [x] I tried using the latest `cordova/index.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

**Comment by vvakame** [comment]
I'm not phonegap user. But I think `phonegap-plugin-barcodescanner` plugin is not exists in this repo.

**Comment by davidleon** [comment]
@vvakame the thing is it's hard to write decent type definition ts, is there any automation program can be used to generate type automatically?

**Comment by vvakame** [comment]
@davidleon no, not yet exists. We should write it manually.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
