### ISSUE TITLE
express serve static core Cannot find module 'http'

### ISSUE THREAD

**Issue by tamasfoldi** [DefinitelyTyped/DefinitelyTyped#9014]
I tried using the latest `express-serve-static-core/express-serve-static-core.d.ts` file in this repo and had problems.
  - The authors of that type definition are cc/ @flcdrg 

Where can I get definitions for http, or how can I solve this?

**Comment by flcdrg** [comment]
express-serve-static-core.d.ts is a file that is shared between express.d.ts and serve-static.d.ts. It was created because otherwise there was a circular dependency between express and serve-static. This isn't a problem for JavaScript/TypeScript but is problematic for NuGet.

You shouldn't just reference the core file, you should get NuGet or tsd to pull in express and/or serve-static and also tell it to get the 'highest' version for dependencies (Dependency Behavior = 'Highest' for NuGet).

The 'http' module itself is actually part of Node and is defined in node.d.ts. This is also a required dependency so should be pulled in automatically by referencing express or serve-static.

I created a new project, added the d.ts files as above, and then confirmed this TypeScript compiles 

```
import * as http from "http";
import * as url from "url";
import * as express from "express";

var app = express();
http.createServer(app).listen(80);
```

I hope that helps.

**Comment by tamasfoldi** [comment]
Thanks a lot! I have used typings install with npm and that didnt pulled the dependencies. Now it is working after adding the node.d.ts

**Comment by flcdrg** [comment]
No worries!
