### ISSUE TITLE
Azure Mobile Services "duplicate identifier" warnings

### ISSUE THREAD

**Issue by georgeedwards** [DefinitelyTyped/DefinitelyTyped#9099]
- [x] I tried using the latest `azuremobileservicesclient/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `azuremobileservicesclient/index.d.ts`.
  - The authors of that type definition are cc/ @dmorosinotto

I am struggling to use the Microsoft Azure Mobile Services SDK in a TypeScript project, so I was [recommended](http://stackoverflow.com/questions/36813024/npm-modules-arent-showing-up-in-emca2015-js-imports) to install the typings definition referenced above. However, doing so hasn't solved the issue, and when I investigate thedefinition index.d.ts file, it has a whole load of duplicate identifier warnings, see below:

[![enter image description here](http://i.stack.imgur.com/Z3Mfm.png)](http://i.stack.imgur.com/Z3Mfm.png)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
