### ISSUE TITLE
Node.js crypto.Hash to extend NodeJS.ReadWriteStream

### ISSUE THREAD

**Issue by jan-osch** [DefinitelyTyped/DefinitelyTyped#9112]
Please refer to official node.js docs: `https://nodejs.org/dist/latest-v4.x/docs/api/crypto.html#crypto_class_hash` - Hash interface should be a both writable and readable stream. The Hash interface should extend `NodeJS.ReadWriteStream`.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
