### ISSUE TITLE
ui-grid no validation services and properties

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/DefinitelyTyped#9114]
I tried using the latest `ui-grid/ui-grid.d.ts` file in this repo and had problems.
There is no validation services and properties.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by ashwin027** [comment]
+1

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
