### ISSUE TITLE
selenium-webdriver/selenium-webdriver.d.ts - No caps_ variable available in Capabilities class

### ISSUE THREAD

**Issue by serhiy-yevtushenko** [DefinitelyTyped/DefinitelyTyped#9118]
- [X ] I tried using the latest `selenium-webdriver/selenium-webdriver` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - The authors of that type definition are cc /@BillArmstrong

The caps_ variable is not exposed in the Capabilities class. I could understand, that this is due to policy of not exposing private variables, caps_ is not included in typescript definition.

At the same time, it is more or less standard way of defining, whether the protractor test is executed under certain browser (see, for example, answer on stack overflow http://stackoverflow.com/questions/23872955/get-the-current-browser-name-in-protractor-test, http://stackoverflow.com/questions/22917219/protractor-accessing-capabilities
)

I was not able to found the alternative way to get this information in protractor tests.

Therefore, could the Capabilities class be modified to include as well variable caps_ (for example, as follows: caps_: any;)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
