### ISSUE TITLE
ReactDOM.render needs to return Component<P, S> 

### ISSUE THREAD

**Issue by petilon** [DefinitelyTyped/DefinitelyTyped#9168]
Prior to March 13 we had this variant of ReactDOM.render:

`function render<P, S>(
            element: ReactElement<P>,
            container: Element,
            callback?: (component: Component<P, S>) => any): Component<P, S>;
`

This is important because when I call myComponent.setState() I get typechecking on the state object I pass in. On March 13 this was removed, and we no longer have a variant that returns a component with strongly typed state. 

This is a major loss. Can we bring it back please?

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
