### ISSUE TITLE
sequelize/sequelize.d.ts error on "findOrCreate"  return type (line 3875)

### ISSUE THREAD

**Issue by lonsenluo** [DefinitelyTyped/DefinitelyTyped#9172]
I tried using the latest `sequelize/sequelize.d.ts` file in this repo and had problems.
the Model.findOrCreate return type should be  `Promise<Array<any>>`  not  `Promise<Promise<TInstance>>`

**Comment by vvakame** [comment]
please send a pull request.

**Comment by zachrip** [comment]
@mingyang91 I noticed you have a fix for this issue in your fork - do you plan on a PR?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
