### ISSUE TITLE
Discussing Promise in es6-shim

### ISSUE THREAD

**Issue by Ptival** [DefinitelyTyped/DefinitelyTyped#9192]
Paging in @rbuckton @vvakame 

I wonder whether there is a good reason to have written:

``` typescript
then [...] onrejected?: (reason: any) => TResult | PromiseLike<TResult>): Promise<TResult>;
then [...] onrejected?: (reason: any) => void): Promise<TResult>;
```

As opposed to:

``` typescript
then [...] onrejected?: (reason: any) => TResult | PromiseLike<TResult> | void): Promise<TResult>;
```

and the same question for `catch`.

I see the benefits of separating in multiple definitions when the result type gets influenced by the choice of the overload, but it is not the case here.

**Comment by vvakame** [comment]
👍

**Comment by rtm** [comment]
Who wrote this code? Who owns it?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
