### ISSUE TITLE
angular.d.ts: Incorrect return type for $q.all

### ISSUE THREAD

**Issue by AbhishekGarg** [DefinitelyTyped/DefinitelyTyped#9215]
In `IQService`, overloads of `all` method are defined with varying number of generic type arguments. 

One of them:
`all<T1, T2>(values: [T1 | IPromise<T1>, T2 | IPromise<T2>]): IPromise<[T1, T2]>;`

The return type now means that response will be an array of the given types, whereas it should be an array of promises of the given types, i.e., *something like*

`all<T1, T2>(values: [T1 | IPromise<T1>, T2 | IPromise<T2>]): IPromise<[IHttpPromiseCallbackArg<T1>, IHttpPromiseCallbackArg<T2>]>;`
<br>
This is expected because the required data is present in `data` property of the response, rather than being available directly, particularly for `$http` calls. Code sample:

```ts
interface Foo { a: string }
interface Bar { b: string }

$http: ng.IHttpService;

getData<T>(): ng.IHttpPromise<T> {
    return this.$http.get("http://my.resource");
}

this.$q.all<Foo, Bar>([this.getData<Foo>(), this.getData<Bar>()]).then((response) => {
    let foo = response[0];  //Type Foo
    let bar = response[1].data;  //Error: Property 'data' does not exist on type 'Bar'.
});
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by mmiszy** [comment]
@AbhishekGarg The of typing of `$q.all` function is correct. It takes an array of Promises or values and returns a promise of values. That's the point of `$q.all` and that's exactly how it works.

Your code is incorrect, though. `$http.get(…)` returns `IHttpPromise<T>` which resolves to `IHttpPromiseCallbackArg<T>`. Your code says that `$q.all` should expect promises resolve to `Foo` and `Bar` which is obviously not true - they resolve to `IHttpPromiseCallbackArg<Foo>` and `IHttpPromiseCallbackArg<Bar>` and therefore correct `$q.all` template types are as follows:

```typescript
$q.all<IHttpPromiseCallbackArg<Foo>, IHttpPromiseCallbackArg<Bar>>([this.getData<Foo>(), this.getData<Bar>()]).then((response) => {
    let foo = response[0].data.a; // it works, as expected
});
```

You could also omit these explicit types here completely and get correct results:

```typescript
$q.all([this.getData<Foo>(), this.getData<Bar>()]).then((response) => {
    let foo = response[0].data.a; // it works, as expected
});
```

The proper question is: **Why your clearly incorrect code is not a compilation error?** I'm not sure and I suggest you file a bug report in https://github.com/Microsoft/TypeScript/issues

This issue should be closed.

**Comment by AbhishekGarg** [comment]
@mmiszy Thanks for your reply. 

In my code snippet, by saying `$q.all<Foo, Bar>` I do not mean that the promises should resolve to `Foo` and `Bar`, they should indeed resolve to `IHttpPromiseCallbackArg`. It just means I am providing types for the generics. The function is still taking an array of promises. So, the code isn't incorrect.

```ts
this.$http.get<Foo>("http://my.resource").then((response) => {
    let foo = response.data.a; // works as expected, response if of type IHttpPromiseCallBackArg<Foo>
});

this.$q.all<Foo, Bar>([this.getData<Foo>(), this.getData<Bar>()]).then((response) => {
    let foo = response[0];  // Type Foo, should have been IHttpPromiseCallBackArg<Foo>
    let bar = response[1].data;  // Error: Property 'data' does not exist on type 'Bar'.
});
```
The first code snippet you gave does not look right in the above context. With `$http.get`, we get a `response` of `IHttpPromiseCallbackArg`, `response` from `$q.all` should not be any different, it should be array of `IHttpPromiseCallbackArg`.

The second snippet obviously works, but has the disadvantage of getting response as `any[]`, basically useless in the TypeScript context.

Maybe the proposed change is at the wrong place, but IMHO a change is required.

**Comment by mmiszy** [comment]
> I do not mean that the promises should resolve to `Foo` and `Bar`

When you use `$q.all<Foo, Bar>` it means that the promise will resolve with array of [Foo, Bar], that's exactly what it means. What you get obviously is not `[Foo, Bar]`, it's `[IHttpPromiseCallbackArg<Foo>, IHttpPromiseCallbackArg<Bar>]` so that's the type you should provide for the template.

> With `$http.get`, we get a response of `IHttpPromiseCallbackArg`, response from `$q.all` should not be any different, it should be array of `IHttpPromiseCallbackArg`

`$q.all` returns exactly what it should. Promises are more general concept, they're **not** used exclusively with `$http` and there's no reason for `$q.all` to return `IHttpPromiseCallbackArg` and it doesn't make any sense. `$q.all<T>` resolves with array of `T`, this is how it is, how it always has been. If you want it to resolve with array of `IHttpPromiseCallbackArg<Foo>` then pass correct type to the template: `$q.all<IHttpPromiseCallbackArg<Foo>>(…)`

> the code isn't incorrect

The code IS incorrect. I think TypeScript should prevent you from even doing that, I don't understand why it doesn't, but still the code is incorrect. Consider this example:

```typescript
$q.all<string>([getData<Foo>()]).then(function (response) {
	const foo = response[0];
});
```
Is this correct? Of course not. `getData<Foo>()` returns `IHttpPromise<Foo>` so it should result in compilation error because it's not compatible with `string`. However, TypeScript compiles it just fine and it _thinks_ `foo` inside the callback has type `string` which is wrong. Analogy to your case:

```typescript
$q.all<Foo>([this.getData<Foo>()]).then((response) => {
    const foo = response[0];
});
```
Is it correct? Nope. `getData<Foo>()` returns `IHttpPromise<Foo>` so it should result in compilation error because it's not compatible with `Foo`. However, TypeScript compiles it just fine and it _thinks_ `foo` inside the callback has type `Foo` which is wrong. So you have to change the way you use `$q.all` function to make it correct: `$q.all<IHttpPromiseCallbackArg<Foo>>(…)`

> The second snippet obviously works, but has the disadvantage of getting response as any[], basically useless in the TypeScript context.

That's not true, at least when I test it types are recognised just fine. See from line 60: [Playground example](http://www.typescriptlang.org/play/#src=interface%20IQResolveReject%3CT%3E%20%7B%0A%09()%3A%20void%3B%0A%09(value%3A%20T)%3A%20void%3B%0A%7D%0A%0Ainterface%20IQService%20%7B%0A%09new%20%3CT%3E(resolver%3A%20(resolve%3A%20IQResolveReject%3CT%3E)%20%3D%3E%20any)%3A%20IPromise%3CT%3E%3B%0A%09new%20%3CT%3E(resolver%3A%20(resolve%3A%20IQResolveReject%3CT%3E%2C%20reject%3A%20IQResolveReject%3Cany%3E)%20%3D%3E%20any)%3A%20IPromise%3CT%3E%3B%0A%09%3CT%3E(resolver%3A%20(resolve%3A%20IQResolveReject%3CT%3E)%20%3D%3E%20any)%3A%20IPromise%3CT%3E%3B%0A%09%3CT%3E(resolver%3A%20(resolve%3A%20IQResolveReject%3CT%3E%2C%20reject%3A%20IQResolveReject%3Cany%3E)%20%3D%3E%20any)%3A%20IPromise%3CT%3E%3B%0A%09all%3CT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%2C%20T7%2C%20T8%2C%20T9%2C%20T10%3E(values%3A%20%5BT1%20%7C%20IPromise%3CT1%3E%2C%20T2%20%7C%20IPromise%3CT2%3E%2C%20T3%20%7C%20IPromise%3CT3%3E%2C%20T4%20%7C%20IPromise%20%3CT4%3E%2C%20T5%20%7C%20IPromise%3CT5%3E%2C%20T6%20%7C%20IPromise%3CT6%3E%2C%20T7%20%7C%20IPromise%3CT7%3E%2C%20T8%20%7C%20IPromise%3CT8%3E%2C%20T9%20%7C%20IPromise%3CT9%3E%2C%20T10%20%7C%20IPromise%3CT10%3E%5D)%3A%20IPromise%3C%5BT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%2C%20T7%2C%20T8%2C%20T9%2C%20T10%5D%3E%3B%0A%09all%3CT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%2C%20T7%2C%20T8%2C%20T9%3E(values%3A%20%5BT1%20%7C%20IPromise%3CT1%3E%2C%20T2%20%7C%20IPromise%3CT2%3E%2C%20T3%20%7C%20IPromise%3CT3%3E%2C%20T4%20%7C%20IPromise%20%3CT4%3E%2C%20T5%20%7C%20IPromise%3CT5%3E%2C%20T6%20%7C%20IPromise%3CT6%3E%2C%20T7%20%7C%20IPromise%3CT7%3E%2C%20T8%20%7C%20IPromise%3CT8%3E%2C%20T9%20%7C%20IPromise%3CT9%3E%5D)%3A%20IPromise%3C%5BT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%2C%20T7%2C%20T8%2C%20T9%5D%3E%3B%0A%09all%3CT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%2C%20T7%2C%20T8%3E(values%3A%20%5BT1%20%7C%20IPromise%3CT1%3E%2C%20T2%20%7C%20IPromise%3CT2%3E%2C%20T3%20%7C%20IPromise%3CT3%3E%2C%20T4%20%7C%20IPromise%20%3CT4%3E%2C%20T5%20%7C%20IPromise%3CT5%3E%2C%20T6%20%7C%20IPromise%3CT6%3E%2C%20T7%20%7C%20IPromise%3CT7%3E%2C%20T8%20%7C%20IPromise%3CT8%3E%5D)%3A%20IPromise%3C%5BT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%2C%20T7%2C%20T8%5D%3E%3B%0A%09all%3CT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%2C%20T7%3E(values%3A%20%5BT1%20%7C%20IPromise%3CT1%3E%2C%20T2%20%7C%20IPromise%3CT2%3E%2C%20T3%20%7C%20IPromise%3CT3%3E%2C%20T4%20%7C%20IPromise%20%3CT4%3E%2C%20T5%20%7C%20IPromise%3CT5%3E%2C%20T6%20%7C%20IPromise%3CT6%3E%2C%20T7%20%7C%20IPromise%3CT7%3E%5D)%3A%20IPromise%3C%5BT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%2C%20T7%5D%3E%3B%0A%09all%3CT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%3E(values%3A%20%5BT1%20%7C%20IPromise%3CT1%3E%2C%20T2%20%7C%20IPromise%3CT2%3E%2C%20T3%20%7C%20IPromise%3CT3%3E%2C%20T4%20%7C%20IPromise%20%3CT4%3E%2C%20T5%20%7C%20IPromise%3CT5%3E%2C%20T6%20%7C%20IPromise%3CT6%3E%5D)%3A%20IPromise%3C%5BT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%2C%20T6%5D%3E%3B%0A%09all%3CT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%3E(values%3A%20%5BT1%20%7C%20IPromise%3CT1%3E%2C%20T2%20%7C%20IPromise%3CT2%3E%2C%20T3%20%7C%20IPromise%3CT3%3E%2C%20T4%20%7C%20IPromise%20%3CT4%3E%2C%20T5%20%7C%20IPromise%3CT5%3E%5D)%3A%20IPromise%3C%5BT1%2C%20T2%2C%20T3%2C%20T4%2C%20T5%5D%3E%3B%0A%09all%3CT1%2C%20T2%2C%20T3%2C%20T4%3E(values%3A%20%5BT1%20%7C%20IPromise%3CT1%3E%2C%20T2%20%7C%20IPromise%3CT2%3E%2C%20T3%20%7C%20IPromise%3CT3%3E%2C%20T4%20%7C%20IPromise%20%3CT4%3E%5D)%3A%20IPromise%3C%5BT1%2C%20T2%2C%20T3%2C%20T4%5D%3E%3B%0A%09all%3CT1%2C%20T2%2C%20T3%3E(values%3A%20%5BT1%20%7C%20IPromise%3CT1%3E%2C%20T2%20%7C%20IPromise%3CT2%3E%2C%20T3%20%7C%20IPromise%3CT3%3E%5D)%3A%20IPromise%3C%5BT1%2C%20T2%2C%20T3%5D%3E%3B%0A%09all%3CT1%2C%20T2%3E(values%3A%20%5BT1%20%7C%20IPromise%3CT1%3E%2C%20T2%20%7C%20IPromise%3CT2%3E%5D)%3A%20IPromise%3C%5BT1%2C%20T2%5D%3E%3B%0A%09all%3CTAll%3E(promises%3A%20IPromise%3CTAll%3E%5B%5D)%3A%20IPromise%3CTAll%5B%5D%3E%3B%0A%09all(promises%3A%20%7B%20%5Bid%3A%20string%5D%3A%20IPromise%3Cany%3E%3B%20%7D)%3A%20IPromise%3C%7B%20%5Bid%3A%20string%5D%3A%20any%3B%20%7D%3E%3B%0A%09all%3CT%20extends%20%7B%7D%3E(promises%3A%20%7B%20%5Bid%3A%20string%5D%3A%20IPromise%3Cany%3E%3B%20%7D)%3A%20IPromise%3CT%3E%3B%0A%09reject(reason%3F%3A%20any)%3A%20IPromise%3Cany%3E%3B%0A%09resolve%3CT%3E(value%3A%20IPromise%3CT%3E%7CT)%3A%20IPromise%3CT%3E%3B%0A%09resolve()%3A%20IPromise%3Cvoid%3E%3B%0A%09when%3CT%3E(value%3A%20IPromise%3CT%3E%7CT)%3A%20IPromise%3CT%3E%3B%0A%09when()%3A%20IPromise%3Cvoid%3E%3B%0A%7D%0A%0Ainterface%20IPromise%3CT%3E%20%7B%0A%09then%3CTResult%3E(successCallback%3A%20(promiseValue%3A%20T)%20%3D%3E%20IPromise%3CTResult%3E%7CTResult%2C%20errorCallback%3F%3A%20(reason%3A%20any)%20%3D%3E%20any%2C%20notifyCallback%3F%3A%20(state%3A%20any)%20%3D%3E%20any)%3A%20IPromise%3CTResult%3E%3B%0A%09catch%3CTResult%3E(onRejected%3A%20(reason%3A%20any)%20%3D%3E%20IPromise%3CTResult%3E%7CTResult)%3A%20IPromise%3CTResult%3E%3B%0A%09finally(finallyCallback%3A%20()%20%3D%3E%20any)%3A%20IPromise%3CT%3E%3B%0A%7D%0A%0Ainterface%20IHttpPromiseCallbackArg%3CT%3E%20%7B%0A%09data%3F%3A%20T%3B%0A%09status%3F%3A%20number%3B%0A%7D%0A%0Ainterface%20IHttpPromise%3CT%3E%20extends%20IPromise%3CIHttpPromiseCallbackArg%3CT%3E%3E%20%7B%7D%0A%0Ainterface%20IHttpService%20%7B%0A%09get%3CT%3E(url%3A%20string)%3A%20IHttpPromise%3CT%3E%3B%0A%7D%0A%0Avar%20%24q%3AIQService%3B%0Avar%20%24http%3AIHttpService%3B%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%0Ainterface%20Foo%20%7B%0A%09a%3Anumber%3B%0A%7D%0Ainterface%20Bar%20%7B%0A%09b%3Astring%3B%0A%7D%0A%0Afunction%20getData%3CT%3E()%3AIHttpPromise%3CT%3E%20%7B%0A%09return%20%24http.get%3CT%3E(%22http%3A%2F%2Fmy.resource%22)%3B%0A%7D%0A%0A%24q.all(%5BgetData%3CFoo%3E()%2C%20getData%3CBar%3E()%5D).then(function%20(response)%20%7B%0A%09const%20foo%20%3D%20response%5B0%5D%3B%20%2F%2F%20type%20Foo%0A%09const%20bar%20%3D%20response%5B1%5D%3B%20%2F%2F%20type%20Bar%0A%09foo.data.a.toFixed(1)%3B%0A%09bar.data.b.charAt(1)%3B%0A%7D)%3B)

**Comment by AbhishekGarg** [comment]
> When you use `$q.all<Foo, Bar>` it means that the promise will resolve with array of [Foo, Bar], that's exactly what it means.

This is correct in view of the current definition of $q.all. I was just trying to make my intent clear.


>```ts
$q.all<string>([getData<Foo>()]).then(function (response) {
    const foo = response[0];
});
```

This definitely looks incorrect. I'll file a bug report with the TypeScript repo. Thanks for making this clear with an example.

>`$q.all` returns exactly what it should. Promises are more general concept, they're **not** used exclusively with `$http` and there's no reason for `$q.all` to return `IHttpPromiseCallbackArg`

This is true. Definition for `$q.all` is correct. My only issue is with the `response` in the promise callback. The suggested type to `$q.all` (returns `IPromise`) looks like a workaround, one we clearly don't require for `$http.get` (returns `IHttpPromise`, which extends `IPromise`). 
My final question is: "Are `IPromise` and `IHttpPromise` so different that they have different `response` types in callback function in `.then`?" Should there be something like `IPromiseCallbackArg`?

```ts
let httpPromise: IHttpPromise<Foo>,
      promise: IPromise<Foo>;

httpPromise.then((response) => {
    const foo = response; // Has type IHttpCalbackArg<Foo>
});

promise.then((response) => {
    const foo = response; // Has type Foo
});
```

**Comment by AbhishekGarg** [comment]
@mmiszy Many thanks for your explanations, helped me get closer to the root issue.
Closing this issue as `$q.all` typings are correct.
