### ISSUE TITLE
Express: No support for boolean functions

### ISSUE THREAD

**Issue by georgeedwards** [DefinitelyTyped/DefinitelyTyped#9231]
- [x] I tried using the latest `express/index.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `express/index.d.ts`.
  - The authors of that type definition are cc/ @borisyankov @vvakame

If I have the following code, to show a fairly simple and common JS approach to using secured REST API Calls then, the Auth.isAuthenticated argument causes a TS error. 

```
static init(app: express.Application, router: express.Router) {
    router.route('/api/private/*', Auth.isAuthenticated);
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
