### ISSUE TITLE
mz/mz.d.ts: Conflicting call signatures

### ISSUE THREAD

**Issue by cstruct** [DefinitelyTyped/DefinitelyTyped#9242]
- [x] I tried using the latest `mz/mz.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

The `Completer` interface from the `mz/readline` is currently un-implementable without type casting. This since there are conflicting call signatures. 

The conflicting call signatures:

``` TypeScript
        (line: string): Promise<[string[], string]>;
        (line: string): [string[], string];
```

This could be solved by using a union type, i.e.

``` TypeScript
        (line: string): Promise<[string[], string]> | [string[], string];
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
