### ISSUE TITLE
Alt.js source remote are only allowed one argument by type definitions.

### ISSUE THREAD

**Issue by mantagen** [DefinitelyTyped/DefinitelyTyped#9246]
@vvakame 

Due to alt API as expressed here http://alt.js.org/docs/async/#remotestate-object-args-any, source remote method can take arguments beyond the state, however the type definitions only allow for one argument to be passed in. Please see below.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/alt/alt.d.ts#L57

This line I believe should be
```
  remote(...args):Promise<S>;
```

or similar.

Do you agree?

**Comment by vvakame** [comment]
I don't use alt.js. please send a pull request first.
cc/ @Shearerbeard

**Comment by Shearerbeard** [comment]
I'm in agreement @mantagen but unfortunately my current company is no longer consuming alt and typescript so I may not have the bandwidth to update these definitions any time soon (would love to if time does permit), I don't think they have been worked on since TS was in 1.5 BETA and AltJS was about to hit version 0.17.x

**Comment by joemclo** [comment]
Hi,
PR for this issue here:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10440

**Comment by joemclo** [comment]
PR now merged .. This can be closed
