### ISSUE TITLE
Redux.d.ts is now obsolete

### ISSUE THREAD

**Issue by pfgray** [DefinitelyTyped/DefinitelyTyped#9247]
- [x] I want to talk about `redux/redux.d.ts`.
  - The authors of that type definition are cc/ @wbuchwalter, @vvakame, @stepancar, @pdeva, @googol7, @kuy

Also cc'ing @aikoven, @Igorbek, @use-strict, as they have commits on the official redux type definition.

As of [redux 3.4.0](https://github.com/reactjs/redux/releases/tag/v3.4.0), redux is now shipped with an official [type definition file](https://github.com/reactjs/redux/blob/master/index.d.ts), which is more refined than the one included in this repo.

**Is there an established protocol for what should happen when a project that doesn't have typings suddenly has them?**

In my opinion, the redux type file here should be deprecated, and other typefiles dependent on redux (react-redux, react-redux-router, etc) should all be aligned with the official type definition from redux.

**Comment by Igorbek** [comment]
Agree, it should be depricated. However, aligning all the definitions with the offcial one will be tough. At least, we somehow need to refer to that defintion during build process. And the redux typings delivered within the npm package. Any ideas?

**Comment by blakeembrey** [comment]
If I had to guess, there's at least 50 typings in DefinitelyTyped that are no longer valid because they have been moved inline. People using Typings can still reference them since it's by commit hash. Why not just delete them?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
