### ISSUE TITLE
Websocket 

### ISSUE THREAD

**Issue by dbrgn** [DefinitelyTyped/DefinitelyTyped#9254]
- [x] I want to talk about `websocket/websocket.d.ts`.
- The authors of that type definition are cc/ @loyd

The current `websocket` definitions seem to be specific to the node.js implementation, as there are includes from `node/node.d.ts`.

I'm working on a project that's client-side only, so I need a definition of the browser side, without including `node.d.ts`. Does someone with more familiarity with the websocket standard know whether [that spec](https://developer.mozilla.org/de/docs/Web/API/WebSocket) matches the one provided by node (except for the Buffer parts)?

**Comment by dbrgn** [comment]
As far as I can tell by the Mozilla docs linked above, this is all that's provided by the browser:

```typescript
// Type definitions for websocket
// Definitions by: Danilo Bargen <https://github.com/dbrgn>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare const enum ReadyState {
    Connecting = 0,
    Open = 1,
    Closing = 2,
    Closed = 3,
}

declare module "websocket" {

    export interface WebSocket {
        binaryType: string;
        bufferedAmount: number; // readonly
        extensions: string;
        onclose: EventListener;
        onerror: EventListener;
        onmessage: EventListener;
        onopen: EventListener;
        protocol: string;
        readyState: ReadyState; // readonly
        url: string; // readonly

        constructor(url: string, protocols?: string | string[]);
        close(code?: number, reason?: string);
        send(data: string | ArrayBuffer | Blob);
    }
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
