### ISSUE TITLE
Leaflet: GeoJSONOptions style definition is wrong / too narrow

### ISSUE THREAD

**Issue by Grovespaz** [DefinitelyTyped/DefinitelyTyped#9257]
The current style property of GeoJSONOptions is defined as a function returning style properties:

```
style?: (featureData: any) => any;
```

However, the real definition is wider, as I am allowed to pass in a regular object like so:

```
var geoJson = L.geoJson(geoJsonRoute, {
    style: {
        "color": "#ff7800",
        "weight": 5,
        "opacity": 0.65
    }
});
```

which gets rejected by the current typing. Can we widen the definition of style?
(see also http://leafletjs.com/examples/geojson.html)

(cc-ing @rgripper ?)

**Comment by rgripper** [comment]
@Grovespaz Yes, I think we could redefine it to smth like 
    type StyleFactoryOrValue = (featureData: any) => any | { style: any }
    style?: StyleFactoryOrValue;

Would be superawesome, if you could test it (probably provide better definition), fix the definitions file and submit a pull request! :)

**Comment by Grovespaz** [comment]
Agreed, I'll try to whip up a better definition and submit a PR. Thanks!

**Comment by rgripper** [comment]
@Grovespaz :+1:

**Comment by chriszrc** [comment]
Hi, 
I don't want to open a new issue for this, since I'm not sure it is a typescript problem, but I get compilation errors when using the GeoJSONOptions. 

`let geoJsonLayer:L.GeoJSON = L.geoJSON(featureCollection,{
        onEachFeature:function(feature,layer){
          if (feature.properties) {
            layer.bindPopup(feature.properties.id);
          }
        }
 });
`

Gives the error:

`Argument of type '{ onEachFeature: (feature: any, layer: any) => void; }' is not assignable to parameter of type 'GeoJSONOptions'. Types of property 'onEachFeature' are incompatible. Type '(feature: any, layer: any) => void' is not assignable to type 'void'.`

Is this a real problem? Am I missing something?
