### ISSUE TITLE
lodash.d.ts find method doesn't accept an object (dictionary) which key is a number

### ISSUE THREAD

**Issue by djflex68** [DefinitelyTyped/DefinitelyTyped#9299]
I tried using the latest `lodash.d.ts` file in this repo and had problems.
The method find doesn't accept an object (dictionary) which key is a number, as first parameter. This is only working when the key is of type string. This should be possible in both cases.

**Comment by djflex68** [comment]
My fault, bad check

**Comment by vvakame** [comment]
@bczengel @chrootsu @stepancar

**Comment by stepancar** [comment]
@djflex68 , please, share example, which reproduce this issue

**Comment by djflex68** [comment]
```
var foo: { [key: string]: string } = {
    1: "bar",
    2: "hello"
};

_.find(foo, (element) => { return element == "bar" });
```

works

Whereas :

```
`var foo: { [key: number]: string } = {
    1: "bar",
    2: "hello"
};

_.find(foo, (element) => { return element == "bar" });`
```

throws compile error 

> Argument of type '{ [key: number]: string; }' is not assignable to parameter of type 'List<string> | Dictionary<string>'.
  Type '{ [key: number]: string; }' is not assignable to type 'Dictionary<string>'.
    Index signature is missing in type '{ [key: number]: string; }'.

**Comment by enterframe** [comment]
+1

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
