### ISSUE TITLE
follow option for node-glob is not represented in gulp SrcOptions interface

### ISSUE THREAD

**Issue by lorenjerickson** [DefinitelyTyped/DefinitelyTyped#9300]
- [x] I tried using the latest `gulp/gulp.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `gulp/gulp.d.ts`.
  - The authors of that type definition are cc/ @

node-glob supports the `follow` option that causes it to follow symlinks when processing glob patterns. Gulp claims to "support all node-glob options", however the `follow` option is not represented in the SrcOptions interface under this type definition.

**Comment by vvakame** [comment]
please send pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
