### ISSUE TITLE
react-fa correct usage

### ISSUE THREAD

**Issue by luisrudge** [DefinitelyTyped/DefinitelyTyped#9321]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- The author of that type definition is @flaub

Correct usage of the react-fa package is `import {Icon} from 'react-fa'` (docs: https://github.com/andreypopp/react-fa#usage)

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by flaub** [comment]
This has changed since I originally wrote the wrapper against v4.0.0

https://github.com/andreypopp/react-fa/compare/v4.0.0...master

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
