### ISSUE TITLE
expect.d.ts: missing method and a question to Extensions

### ISSUE THREAD

**Issue by otbe** [DefinitelyTyped/DefinitelyTyped#9331]
Hi,

Im using the latest version of expect (.d.ts) in my typescript project, but there are some problems.
In my opinion `reset` is a missing method in `Spy`. I have added it manually and it works :)

The other problem is: how to add and use an `Extension`? I tried the following

``` javascript
import expect, { extend, Extension } from 'expect';

const myExtension: Extension = {
  toDo: function(): void {
//    assert(true);
  }
}

extend(myExtension);

it('Test', () => {
   expect(spy).toDo(); // at this point tsc complains: "Property 'toDo' does not exist on type 'Expectation"
  (<any>expect(spy)).toDo(); // works but is ugly :/
});
```

Thanks :)

// cc authors @vvakame @jmreidy

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
