### ISSUE TITLE
joi.d.ts out of date, missing types

### ISSUE THREAD

**Issue by tanepiper** [DefinitelyTyped/DefinitelyTyped#9332]
Hi there,

A minor issue has been that for a while using joi.d.ts and Webstorm, it shows weak warnings for Joi - such as this:

![joi](https://cloud.githubusercontent.com/assets/376930/15252926/ec580efc-1927-11e6-8440-5eea56d4f8b8.png)

It seems to have this for all the major types (string, number, bool, although not regex I've noticed)

I've ensured the definition is active in this project.  I've also noticed that it's rather out of date (joi.d.ts refers to v6.5.0 but the current version is 9.0.0).  Also it still refers to the old spumko repo but it's been moved to https://github.com/hapijs/joi

//cc @Bartvds @j-sheppard

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by alex3165** [comment]
In the meantime, I think the definitions need to be namespaced, would be nice to wrap every definitions :
```
export = Joi;
export as namespace Joi;

declare namespace Joi {
// Definitions here
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
