### ISSUE TITLE
dojo/request/xhr definitions don't match code

### ISSUE THREAD

**Issue by lobsteropteryx** [DefinitelyTyped/DefinitelyTyped#9338]
The current definitions for the `dojo/request/xhr` module don't match the source code; the helper methods (get, post, etc) are exposed in the definitions file, but commented out in the code.  

In addition, the base `xhr` method returns either a promise or a deferred, but the definitions have it returning `void`, which makes using `then`, etc. impossible.

See:  https://github.com/dojo/dojo/blob/1.10/request/xhr.js

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
