### ISSUE TITLE
Missing DatePickerOptions for angular-ui-bootstrap

### ISSUE THREAD

**Issue by HarelM** [DefinitelyTyped/DefinitelyTyped#9342]
Hi,
Can you please add date picker options for `angular-ui-bootstrap`.
Current available is only `IDatepickerConfig` and `IDatepickerPopupConfig` which as far as I understand are not the same...
Thanks!
Keep up the good work!

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by HarelM** [comment]
I think I read the instructions wrong, I didn't end up using a config object but used the attributes, but there might be still missing classes over there.
I won't be able to send a pull request as I'm currently buried in other projects.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
