### ISSUE TITLE
Duplicate Identifiers

### ISSUE THREAD

**Issue by levmixali4** [DefinitelyTyped/DefinitelyTyped#9360]
After updating lodash.TypeScript.DefinitelyTyped from nuget to version 2.3.3
I have two d.ts files in folder typings/lodash: 'lodash-3.10.d.ts' and 'lodash.d.ts' 
After build I receive around 80 errors with content:  Duplicate Identifier <Identifier name>

**Comment by vvakame** [comment]
@staxmanade ?

**Comment by staxmanade** [comment]
The other file needs to be moved into a "legacy" folder.

**Comment by HarelM** [comment]
Are you planning to fix this soon? I get an error every time I update this definition...

**Comment by DavidKDeutsch** [comment]
Where is the code that contains the nuspecs and whatnot? This particular issue has been a problem for quite a long time, and I've been forced to include the lodash.d.ts file in on of my nuget packages (as opposed to having the lodash DT package as a dependency) because otherwise all the users of my package get these errors. There should really be two lodash packages, one with the legacy file and one with current one.

**Comment by staxmanade** [comment]
@DavidKDeutsch The [NugetAutomation](https://github.com/DefinitelyTyped/NugetAutomation/) repo is the logic that controls the nuget publishing.

It's already designed to exclude `.d.ts` files in a `legacy` folder (https://github.com/DefinitelyTyped/NugetAutomation/blob/master/CreatePackages.ps1#L154).

So, I'd recommend submitting a pull-request just moving the legacy typings to get them excluded.

Hope that helps.

**Comment by DavidKDeutsch** [comment]
Ah, thanks! I was searching the DefinitelyTyped repo, as it never occurred to me that there were others. Will indeed submit a PR.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
