### ISSUE TITLE
jquery-steps: Definitions do not match the actual implementation (v1.1.0)

### ISSUE THREAD

**Issue by WoMayr** [DefinitelyTyped/DefinitelyTyped#9390]
- [X] I tried using the latest `jquery-steps/jquery-steps.d.ts` file in this repo and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] I want to talk about `jquery-steps/jquery-steps.d.ts`.
  - The authors of that type definition are cc/ @jblank 

Just pointing out that the provided definitions don't match the signature of the actual calls. The version of the definitions and the plugin match.
Examples:
- The inital call of this plugin is `$(element).steps()` and not `$(element).JQuerySteps()`. 
- The function for this object itself are structured like `$(element).steps("function name", parameters...)` and not called directly like `$(element).<function name>(parameters..)`

See [API documentation](https://github.com/rstaib/jquery-steps/wiki/Methods) of JQuery Steps

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
