### ISSUE TITLE
fix export  winjs/winjs.d.ts

### ISSUE THREAD

**Issue by cybermerlin** [DefinitelyTyped/DefinitelyTyped#9438]
- [https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e1ba8156f25009d5a616d7dc12dd25b08ec05fc8/winjs/winjs.d.ts] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.

change on line 10624 to:

``` javascript
declare module 'winjs' {
    export default WinJS;
}
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
