### ISSUE TITLE
Did some typings disappear?

### ISSUE THREAD

**Issue by peterjuras** [DefinitelyTyped/DefinitelyTyped#9440]
- [ ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

I'm having some issues getting typings for some modules since they no longer appear to be in the DT repository. I used tsd and now typings but it appears they are just simply gone. The modules that I am no longer finding are:

```
"empty-dir": "github:DefinitelyTyped/DefinitelyTyped/empty-dir/empty-dir.d.ts#c50f6872583ffb0b9b26a780db7825ed5e17fcee"
"gulp-conflict": "github:DefinitelyTyped/DefinitelyTyped/gulp-conflict/gulp-conflict.d.ts#c50f6872583ffb0b9b26a780db7825ed5e17fcee"
"gulp-template": "github:DefinitelyTyped/DefinitelyTyped/gulp-template/gulp-template.d.ts#c50f6872583ffb0b9b26a780db7825ed5e17fcee"
"mock-gulp-dest": "github:DefinitelyTyped/DefinitelyTyped/mock-gulp-dest/mock-gulp-dest.d.ts#c50f6872583ffb0b9b26a780db7825ed5e17fcee"
```

The weird thing is that the commit hashes don't even appear to be in the history anymore and I just can't find any reference to the files on the internet anymore. Has the master branch been detached at any point? My old build logs prove that the files were there at some point in time.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
