### ISSUE TITLE
Update svg.js definition

### ISSUE THREAD

**Issue by jkevingutierrez** [DefinitelyTyped/DefinitelyTyped#9454]
- [x] I tried using the latest `svgjs/svgjs.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `svgjs/svgjs.d.ts`.
  - The authors of that type definition are cc/ @seanhess

Could you update the svg.js definition ? In the official repo of svg.js they have an updated definition: https://github.com/wout/svg.js/blob/master/svg.js.d.ts

**Comment by d-asensio** [comment]
Hey @vvakame what's the better way to update the aforementioned file? Can I update it or is better to upload another file with the current version number?

**Comment by vvakame** [comment]
@d-asensio http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html please check this document.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
