### ISSUE TITLE
google.maps.infobubble ERROR TS2305

### ISSUE THREAD

**Issue by Sireini** [DefinitelyTyped/DefinitelyTyped#9482]
I tried to include the google.maps.infobubble but when I build the app it throws me the following error on multiple lines:

`typings/globals/google.maps.infobubble/index.d.ts(21,31): error TS2305: Module 'google.maps' has no exported member 'Map'.`

`typings/globals/google.maps.infobubble/index.d.ts(21,56): error TS2305: Module 'google.maps' has no exported member 'Marker'.`

`typings/globals/google.maps.infobubble/index.d.ts(26,36): error TS2305: Module 'google.maps' has no exported member 'LatLng'.`

Did someone get the same error and what have you done to fix this?

**Comment by vvakame** [comment]
Do you use `typings`?
`googlemaps.infobubble/google.maps.infobubble.d.ts` has this reference `/// <reference path="../googlemaps/google.maps.d.ts" />`

**Comment by miguelleitevieira** [comment]
Hi, 

I installed "@types/googlemaps.infobubble": "^3.0.0".

When I try to import the module to use InfoBubble: 
import { InfoBubble } from 'googlemaps.infobubble';
I get an error: /@types/googlemaps.infobubble/index.d.ts' is not a module.

Someone know how to solve?

Thanks.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
