### ISSUE TITLE
can you add esri/styles/basic

### ISSUE THREAD

**Issue by MarcBate** [DefinitelyTyped/DefinitelyTyped#9513]
I don't see "esri/styles/basic" or other esri/styles in the typescript definition file for arcgis-js-api.  Is this how you would do it:
From https://developers.arcgis.com/javascript/3/jsapi/esri.styles.basic-amd.html
declare module "esri/styles/basic" {
  class resultAvailableThemes {
    basemaps:string[];
    description:string;
    label:string;
    name:string;
  }
  class schemeParams {
    basemap:string;
    geometryType:string;
    theme:string;
  }
  class resultSchemes {
    primaryScheme:any;
    secondarySchemes:any;
  }
  class esriStylesBasic {
    getAvailableThemes(basemap?:string):resultAvailableThemes;
    getSchemes(params:schemeParams):resultSchemes;
  }
  export = esriStylesBasic;
}

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
