### ISSUE TITLE
protobuf.js issues. 

### ISSUE THREAD

**Issue by MeirionHughes** [DefinitelyTyped/DefinitelyTyped#9535]
I think there is a bug in protobuf/protobuf.js definition

going off the [official example](https://github.com/dcodeIO/protobuf.js/blob/master/examples/websocket/www/index.html)

Given

``` ts
var Message = ProtoBuf.loadProtoFile("./example.proto").build("Message");
```

`Message` should have a method called `decode` in-order to decode the data, but it doesn't. It also should be new-able too, but it isn't. 

cc: @ttowncompiled

**Comment by MeirionHughes** [comment]
with a little bit of wizardry (and using dt~ByteBuffer typings) it is possible to fully type it

```ts
declare namespace ProtoBuf {  
   var ByteBuffer: ByteBuffer;
        
   export function loadProto(proto: string): IProtoBuilder;
   
   export class Proto<T>
   {      
       decode(buffer:ByteBuffer):T & Proto<T>
       encode():ByteBuffer;
   } 
   
   export interface IProtoBuilder
   {      
       build<T>(proto:string):T & Proto<T> & INew<T & Proto<T>> 
   } 
   
   interface INew<T> {
       new (): T;
   }     
}

declare module "protobufjs" {
    export = ProtoBuf;
}
```

and example usage: 

```
var Message = ProtoBuf
      .loadProto(protocol)
      .build<IMessage>("Message");   

 var msg = new Message();     

```

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
