### ISSUE TITLE
webstorm causes hundreds of changes to jquery.d.ts file when editing

### ISSUE THREAD

**Issue by jasekiw** [DefinitelyTyped/DefinitelyTyped#9539]
- [x ] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

has anyone else ran into the issue where webstorm will cause a git diff for the middle asterisk of every comment in the jquery.d.ts file?

every time I got to commit a modification it does this so I have to resort to a text editor like sublime text.

```
     /**
      * Call all callbacks in a list with the given context and arguments.
-     * 
+     *
      * @param context A reference to the context in which the callbacks in the list should be fired.
      * @param arguments An argument, or array of arguments, to pass to the callbacks in the list.
      */
```

This really isn't any issue but a call out to see if I can get to the cause of this.

Thanks.

**Comment by vvakame** [comment]
please send a pull request first.
cc/ @johnnyreilly

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
