### ISSUE TITLE
Highcharts is missing zoomOut() method

### ISSUE THREAD

**Issue by petrkoutnysw** [DefinitelyTyped/DefinitelyTyped#9542]
There is missing zoomOut() method in highcharts.d.ts, please add it.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by petrkoutnysw** [comment]
I am afraid I dont have the access rights. I am connecting through SSH and it did not work :(

**Comment by vvakame** [comment]
@petrkoutnysw https://help.github.com/articles/using-pull-requests/ please check this article. Don't afraid 😺

**Comment by petrkoutnysw** [comment]
I know how to send pull request but I am unable to push my branch with updates, I do not have rights. Can you please make me a contributor? I hope I understand situation correctly :) thanks for your patience.

**Comment by vvakame** [comment]
You can't push your branch to this repository. It is collect.
You should fork this repository and push to forked (your) repository.

**Comment by petrkoutnysw** [comment]
Thank you very much, I have already sent the pull request :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
