### ISSUE TITLE
Missing modPow definition in big-integer

### ISSUE THREAD

**Issue by grempe** [DefinitelyTyped/DefinitelyTyped#9626]
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @Airblader @Deathspike @DanCorder

I installed this type definition using typings:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/big-integer/big-integer.d.ts

However, I noticed that the definition is missing a description for the `modPow` method (others?) which is part of the BigInteger.js package.

https://github.com/peterolson/BigInteger.js

Perhaps someone could update this?  I am brand new to TypeScript and don't yet feel comfortable with the pull request and ensuring it is correct.

I noted that this repo by @demurgos does seem to include it.

https://github.com/demurgos/typed-big-integer

Thanks

**Comment by demurgos** [comment]
Hi,
I wrote my typings from scratch. I did not follow the current official relation between `tsd` and `typings`, but if you want to import my definitions to TSD it's OK.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
