### ISSUE TITLE
ORIGINAL EXCEPTION: TypeError: this.lineChart.Line is not a function

### ISSUE THREAD

**Issue by fee-studio** [DefinitelyTyped/DefinitelyTyped#9630]
- [x] I tried using the latest `chart/chart.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. 1.8.10
- [x] I want to talk about `chart/chart.d.ts`.
  - The authors of that type definition are @vvakame 

and, I copy code from [here](http://stackoverflow.com/questions/34653045/third-party-js-in-angular2-typescript)

this is a my error:
**EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in build/pages/home-page/home-page.html:8:2
ORIGINAL EXCEPTION: TypeError: this.lineChart.Line is not a function**

and, My code is:

```
@Directive({
    selector: '[chart]' // Attribute selector
})
export class ChartDirective {
    lineChart:Chart;
    constructor(el:ElementRef, renderer:Renderer) {
        el.nativeElement.style.backgroundColor = 'yellow';
        var ctx:any = el.nativeElement.getContext("2d");

        this.lineChart = new Chart(ctx);
        this.lineChart.Line(data);
    }
}
```

**Comment by vvakame** [comment]
cc/ @Steve-Fenton

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
