### ISSUE TITLE
backbone typings are missing

### ISSUE THREAD

**Issue by arahansen** [DefinitelyTyped/DefinitelyTyped#9677]
Trying to install typings for Backbone.js and I seem to be downloading an invalid typings index.d.ts

Running the following command:
`typings install dt~backbone --save --global`

Produces the appropriate files:
typings/global/backbone/index.d.ts
typings/global/backbone/typings.json

However, index.d.ts consists of only the generated comment:
// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/backbone/backbone.d.ts

Where I would expect this file to contain all the backbone namespace declarations.

That link also leads to a blank index.d.ts source file. So... My guess is that something went haywire in generating typing info? But, not totally familiar with the generation process to be confident in such a conjecture.

**Comment by vvakame** [comment]
cc/ @blakeembrey

**Comment by blakeembrey** [comment]
@vvakame I'm open to suggestion on how Typings can handle this, but currently there's no way to indicate dependencies and no imports using DefinitelyTyped, so there's no way to know that the Backbone typings are meant to include the references. 

References are always stripped from Typings installation because of their ambiguous nature. There would have been a couple of warnings that this was occurring though.
