### ISSUE TITLE
Node.js typings (ReadStream methods)

### ISSUE THREAD

**Issue by tarurar** [DefinitelyTyped/DefinitelyTyped#9710]
I want to talk about `node/node.d.ts`.
The method `destroy` of class `fs.ReadStream` is not available in the definition. I can call this method in regular javascript but not in typescript. Is it ok?

**Comment by vvakame** [comment]
please send a pull request first. I'll review it.

**Comment by DanielRosenwasser** [comment]
@tarurar where exactly is this API documented? I can't find it on Node's site.

**Comment by tarurar** [comment]
@DanielRosenwasser I don't see it either, but if you try to examine the `__proto__` of the `ReadStream` object you will find this method:
`ReadStream {
  open: [Function],
  _read: [Function],
  destroy: [Function],
  close: [Function] }` 

I saw examples in javascript which uses stream.destroy() to eliminate memory leaks.

**Comment by tarurar** [comment]
@vvakame ok, done

**Comment by DanielRosenwasser** [comment]
@tarurar interestingly I just saw a PR relating to this pop up:

https://github.com/nodejs/node/issues/5898#issuecomment-212417054

In other words, it should *probably* be documented, but it should be fine to add here.

**Comment by rhyek** [comment]
Hi. Just hit this. Wanted to make a PR for this, but wanted to understand the difference between the [Readable](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7d261965d80029817dfcbeb8e5dc39ddeb868923/types/node/v13/stream.d.ts#L22) class and the [ReadableStream](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7d261965d80029817dfcbeb8e5dc39ddeb868923/types/node/v13/globals.d.ts#L587) global interface.

The class is defining more methods than the interface, but a few packages I use (like dockerode) uses the global `NodeJS.ReadableStream` instead of the class. Seems like that may be common.

I believe the interface should define all these methods and the class should implement them, correct?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
