### ISSUE TITLE
Loglevel 1.4.0 doesn't support hierarchical calling to `getLogger()`

### ISSUE THREAD

**Issue by hedefalk** [DefinitelyTyped/DefinitelyTyped#9724]
- [x] I tried using the latest loglevel/loglevel.d.ts file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I want to talk about `loglevel/loglevel.d.ts`.
  - The authors of that type definition are cc/ @flqw and @Pro 

I just shot myself in the foot with doing something like:

`let log = loglevel.getLogger('ensime-client').getLogger('websocket');`

which this d.ts supports but not the real js:

https://github.com/pimterry/loglevel/blob/1.4.0/lib/loglevel.js#L198

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
