### ISSUE TITLE
ui-grid sortDirectionCycle problem

### ISSUE THREAD

**Issue by ghost** [DefinitelyTyped/DefinitelyTyped#9747]
Hi, I tried using the latest `ui-grid/ui-grid.d.ts` file in this repo and had problems.

There is sth like this:
`sortDirectionCycle?: Array<IUiGridConstants>;`

and I have no idea how to use this. In ui-grid library sortDirectionCycle takes array of options:
 IUiGridConstants.ASC, IUiGridConstants.DESC or null and it works fine. Both the  IUiGridConstants.ASC and  IUiGridConstants.DESC are string properties.

I think in typings sortDirectionCycle? should be like this:
`sortDirectionCycle?: Array<string>;`

I've checked it and it's working.

**Comment by vvakame** [comment]
cc/ @btesser @joeskeen

**Comment by joeskeen** [comment]
Since any string isn't valid for this field, it seems to me that we should be able to use a union of string literal types to give the best typing support.  I'll try to take a look and see if I can come up with something.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
