### ISSUE TITLE
d3 Selection<T>.node() wrong return type (I think?)

### ISSUE THREAD

**Issue by chadbr** [DefinitelyTyped/DefinitelyTyped#9775]
-I tried using the latest `typings/modules/d3/index.d.ts` file in this repo and had a problem.
- The authors of that type definition are cc/ @gustavderdrache

I'm taking a function originally written in javascript and adding more and more type information.

I stumbled a bit when trying to use the node() function on a Selection<Datum> type:

  interface Selection<Datum> {

Looking at https://github.com/d3/d3/wiki/Selections#node (and it's use in my function) -- the node is an arbitrary collection of nodes based on what was selected.

On Line 794 -- Selection<Datum>.node() is hard coded to return EventTarget...

```
/**
 * Returns the first non-null element in the selection, or null otherwise.
 */
node(): EventTarget;
```

I'm thinking it should return Datum -- or maybe Any?

So for example - I've declared my selection like so:

```
let canvas = this.host.append("canvas") as D3.Selection<HTMLCanvasElement>; //this is a d3 selection object....
```

So when I try to get the DOM node from the selection -- if I don't cast it to HTMLCanvasElement I get a compilation error because it's returning EventTarget instead of HTMLCanvasElement

```
let context = (canvas.node() as HTMLCanvasElement).getContext("2d");// as CanvasRenderingContext2D;
```

Anyone has on opinion on this? If nobody objections I'll make the change and submit a pull request.

**Comment by gustavderdrache** [comment]
It should not return `Datum`, as that's the type of the bound data. What the `T` in `Selection<T>` refers to is the bound data -- see the return type of [`Selection#data()`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/d3/d3.d.ts#L259-L262) and [`Selection#datum()`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/d3/d3.d.ts#L290-L293) for examples.

The intention is that the more commonly-used methods (`attr` and `style`, for instance) are well-typed, and if you need a specific type of node, you perform the type assertion written above:

```typescript
let node = d3.select('canvas').node() as HTMLCanvasElement;
let context = node.getContext('2d');
```

The reason it returns `EventTarget` instead of `any` is that we can guarantee that it is some kind of thing in the DOM, and `EventTarget` is the simplest type available. It's not too different from the `eventTarget` property in [the `Event` interface](https://github.com/Microsoft/TypeScript/blob/v1.8.10/lib/lib.d.ts#L7085-L7105), since in general the compiler can't make any guarantees about _what_ the element is.

If it's helpful, it's worth noting that the `Selection` interface is a bit like the [`NodeSelector` interface](https://github.com/Microsoft/TypeScript/blob/v1.8.10/lib/lib.d.ts#L16507-L16510) in this respect.

**Comment by tomwanzek** [comment]
As part of some legacy D3v3 issue clean-up, can this issue be please closed?

D3v4 has been released and supported with actively maintained definitions for several months now, so it would be great to have only current issues open for clarity.

Thanks in advance!

cc @gustavderdrache @andy-ms
