### ISSUE TITLE
Unable to use Angular material custom Dialog

### ISSUE THREAD

**Issue by jayakumarn** [DefinitelyTyped/DefinitelyTyped#9780]
- [ ] I tried using the latest `angular-material.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I want to talk about `angular-material.d.ts`.
  - The authors of that type definition are cc/ @Matt Traynham

HI ,
 I am making use of angular material in my typescript project . When I tried to make use angular material alert and confirm box its working fine. But when I tried to use if of custom dialog box. I am getting error like "TypeError: Cannot read property '0' of undefined"

Please find my sample code below
`

   showPopup(ev): void {

```
this.$mdDialog.show({
  controller: function DialogController($scope, $mdDialog) {
this.$scope.hide = function() {
this.$mdDialog.hide();
};
this.$scope.cancel = function() {
this.$mdDialog.cancel();
};
this.$scope.answer = function(answer) {
this.$mdDialog.hide(answer);
};
  },
templateUrl: 'sample.html',
parent: angular.element(document.body),
targetEvent: ev,
clickOutsideToClose:true
 })
.then(function(answer) {
this.$scope.status = 'You said the information was "' + answer + '".';
}, function() {
this.$scope.status = 'You cancelled the dialog.';
});


}
```

`

Kindly help me where Am I Wrong ? It would be great if any one could help me.

**Comment by nikolay-borzov** [comment]
I don't think you need to prefix `$scope` by `this` inside a controller.
See [docs](https://material.angularjs.org/latest/api/service/$mdDialog#javascript-object-syntax)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
