### ISSUE TITLE
Is a bug?

### ISSUE THREAD

**Issue by keyiis** [DefinitelyTyped/DefinitelyTyped#9781]
@rictic @martine 
When i comment "logging: false" as below

```
var sequelize = new Sequelize("test", "", "", {
                storage: "./test.db",
                //logging: false,
                dialect: "sqlite"
});
```

```
Navs.findAll().then(function (navs) {
    console.log(navs);
    return navs;
}).catch(function (err) {
    console.log(err);
    return err;
});
```

will ger error:

```
TypeError: Illegal invocation
    at Sequelize.log (D:\work\nodejs\angular\angular2-electron\node_modules\sequelize\lib\sequelize.js:1338:21)
    at Query.run (D:\work\nodejs\angular\angular2-electron\node_modules\sequelize\lib\dialects\sqlite\query.js:93:20)
    at D:\work\nodejs\angular\angular2-electron\node_modules\sequelize\lib\sequelize.js:843:20
```

If i remove comment,all work fine,is a bug?or my mistake?
my env:

```
node:6.2.1
"ts-loader": "^0.7.2",
"typescript": "^1.8.10",
"typings": "^1.1.0",
"webpack": "^1.13.1",
sequelize: "^3.23.3",
sqlite3: "^3.1.4",
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
