### ISSUE TITLE
Build: Cannot find namespace 'ng'.	

### ISSUE THREAD

**Issue by prashanthbachu** [DefinitelyTyped/DefinitelyTyped#9788]
I tried using the  `angular/angular.d.ts` file for 1.4+ version and I get the issues like can't find namespace 'ng' , cannot find name 'angular'.

**Comment by vvakame** [comment]
Do you use this file? https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angularjs/legacy/angular-1.4.d.ts
You can use `angular` namespace.

**Comment by prashanthbachu** [comment]
Yes, I use the same file. ng namespace is everywhere in our app, is there a way to use ng namespace.

Thank you!

**Comment by aluanhaddad** [comment]
@prashanthbachu `import ng = angular`?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
