### ISSUE TITLE
Remove redux-saga declaations in favour of official declaration files

### ISSUE THREAD

**Issue by mhegazy** [DefinitelyTyped/DefinitelyTyped#9797]
Definition of redux-saga is now shipping with official typings, see https://github.com/yelouafi/redux-saga/blob/master/index.d.ts

The declaration file should be deleted from this repo, and possibly a redirect notice be added.

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9791#issuecomment-228267303 for more context.

**Comment by mhegazy** [comment]
//cc @RyanCavanaugh  and @andy-ms we should add a redirect notice for this. @andy-ms what is the format for this?

**Comment by andy-ms** [comment]
@mhegazy See https://github.com/Microsoft/types-publisher/pull/23/files "notNeededPackages.json". Does that format look good? Currently the file goes in the `types-publisher` repo rather than in DefinitelyTyped, but that could be changed.

**Comment by mhegazy** [comment]
@RyanCavanaugh thoughts?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
