### ISSUE TITLE
commander.d.ts has undocumented private API methods that should be removed(?)

### ISSUE THREAD

**Issue by cspotcode** [DefinitelyTyped/DefinitelyTyped#9808]
- [x] I want to talk about `commander/commander.d.ts`.
  - The authors of that type definition are cc/ @vvakame and @mdezem

I notice a lot of items in the .d.ts marked `@api private`.  They aren't in `commander-tests.ts` nor are they in [commander's](https://github.com/tj/commander.js) [documentation](http://tj.github.io/commander.js/).  They should be removed from the type declaration, right?  If so I'm happy to write a pull request.

**Comment by vvakame** [comment]
please send a pull request.
I think We can use undocumented api if it is needed. but it is better to not using it.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
