### ISSUE TITLE
Mark  dexie/dexie.d.ts as not needed

### ISSUE THREAD

**Issue by mhegazy** [DefinitelyTyped/DefinitelyTyped#9836]
see comment in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7093#issuecomment-228736928

**Comment by mhegazy** [comment]
//cc: @andy-ms

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
