### ISSUE TITLE
Issue regarding missing function on interface materialize-css.d.ts

### ISSUE THREAD

**Issue by chingyawhao** [DefinitelyTyped/DefinitelyTyped#9840]
- The authors of that type definition are @eriklieben & @leonyu.
- Materialize.updateTextFields() does not exist yet...

**Comment by raiden0610** [comment]
Hello,
Also there is no support for Autocomplete since this typings are made for the version 0.97.5 and the autocomplete wasn't released.

Is it possible to add it ?

Regards

**Comment by leonyu** [comment]
@chingyawhao added `updateTextFields` via #9849

You can add `autocomplete` too, it is fairly simple. It is most likely

```ts
declare namespace Materialize {
    interface AutoCompleteOptions {
        data: { [key: string]: string };
    }
// .... existing code ....

interface JQuery {
// .... existing code ....
    autocomplete(options: Materialize.AutoCompleteOptions)
}
```

**Comment by raiden0610** [comment]
Thanks, i'm kinda new to typescript, How can you import the JQuery that's inside the materialize typings ?
Because when I import JQuery, the compiler doesn't recognize the autocomplete method, he import JQuery typings

**Comment by leonyu** [comment]
You don't need to import/add jQuery, it is already there in the file, you just need to add the line for autocomplete at the end. 

This follows [Declaration Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) feature of type declaration.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
