### ISSUE TITLE
gridstack.d.ts interface IGridstackOptions  requires for each options to be defined

### ISSUE THREAD

**Issue by jvelezc** [DefinitelyTyped/DefinitelyTyped#9887]
Currently:https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/gridstack/gridstack.d.ts

``` javascript
interface IGridstackOptions {
    /**
     * if true the resizing handles are shown even if the user is not hovering over the widget (default: false)
     */
    alwaysShowResizeHandle: boolean;
    /**
     * turns animation on (default: true)
     */
    animate: boolean;
... many more lines 
```

So if there is default values why are you forcing the consumer to actually have to declare it. 
Instead make it optional with ?

``` javascript
interface IGridstackOptions {

    alwaysShowResizeHandle?: boolean;
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
