### ISSUE TITLE
material-ui: className not defined as prop

### ISSUE THREAD

**Issue by david-gregorian** [DefinitelyTyped/DefinitelyTyped#9900]
- [x] I tried using the latest `material-ui/material-ui.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `material-ui/material-ui.d.ts`.

Hey there,
The property className is missing on nearly every props interface.

It would be awesome if someone could add them :)

The authors of that type definition are @ngbrown  and @herrmanno .

Best wishes, Dave

**Comment by ngbrown** [comment]
@daveGregorian Yes, in general, on every single component, `React.HTMLAttributes` could potentially apply, yet I can't just include that on the props inheritance because some DOM handlers have different definitions.

I'm not really sure how to handle this going forward with TypeScript.  It seems to rely on how they decide to handle mixins.  See Microsoft/TypeScript#2919.

Any suggestions?

**Comment by minodisk** [comment]
@daveGregorian @ngbrown It looks like it can be closed with the commit: [Updated per documentation for v0\.14\.4\. · DefinitelyTyped/DefinitelyTyped@745bc4b](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/745bc4b343672b6ac9881d50b51478926c8a658c).

**Comment by minodisk** [comment]
@andy-ms Could you close this issue?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
