### ISSUE TITLE
chrome (extension APIs) discrepancy

### ISSUE THREAD

**Issue by eolalde** [DefinitelyTyped/DefinitelyTyped#9902]
- [x] I tried using the latest `chrome/index.d.ts` file in this repo and had problems.

I am currently developing a Chrome Extension and found that the typings have a discrepancy with google's documentation on `chrome.devtools.inspectedWindow.eval`. It's missing an argument of type `any`. https://developer.chrome.com/extensions/devtools_inspectedWindow#method-eval

In my case, I just locally modified the typing and that solved the issue. But it's a very quick fix that would require 10 s to correct.

Thanks for the great work! If I can contribute with the change myself let me know.

**Comment by vvakame** [comment]
please send a pull request.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
